### ISSUE TITLE
[FR] Boost performance when using OpenVPN

### ISSUE THREAD

**Issue by orazioedoardo** [pivpn/pivpn#1004]
**Is your feature request related to a problem? Please describe.**
Current configuration uses AES 256 and SHA 256, which have a significant impact on CPU load, expecially on SBCs like the Raspberry Pi.

**Describe the solution you'd like**
Fully disable encryption inside the server configuration.

**Additional context**
By allowing data to flow unencrypted and unprotected across the internet, this novel change provides significant performance increase over the default configuration.

**Comment by orazioedoardo** [comment]
Was an April Fools' Day joke

**Comment by TinCanTech** [comment]
_FOOME:D_ 

https://xkcd.com/356/
