### ISSUE TITLE
[BUG] Clients don't get assigned IPv4 addresses on connection (PiVPN WireGuard)

### ISSUE THREAD

**Issue by QuarkSolution** [pivpn/pivpn#1007]
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

**Describe the bug**
WireGuard PiVPN. When clients are added through "pivpn add", PiVPN assigns the entire subnet to the client device (e.g. 10.6.0.2/24). When you add a different device, the conf shows, say, 10.6.0.3/24. but the client doesn't get assigned a IP on connection (I checked using "pivpn -c") When I manually changed the interface CIDRs on client devices to /32, and the client CIDRs to /32 in wg0.conf, and obviously restarted the service, it worked.

**To Reproduce**
1. PiVPN WireGuard on amd64
2. Add a device using "pivpn add"
3. Open wg0.conf

**Expected behavior**
Client CIDR notations should have /32. Do the clients really need /24?!

**Desktop (please complete the following information):**
 - VPN Protocol: WireGuard
 - OS: Ubuntu 18.04 
 - Version [e.g. 22]: latest, installed tonight 

**Additional context**
I also manually added IPv6 addresses, and proper IPv6 firewalls rules to make that work. After my fixes for IPv4 addresses, both work perfectly.

**Comment by orazioedoardo** [comment]
Can i see `pivpn -d` as well as a non working client config and a working client config? Obviously remove keys and IPs.

**Comment by QuarkSolution** [comment]
![pivpn d](https://user-images.githubusercontent.com/54516411/78409583-0aa20f00-75d8-11ea-85ae-159da54c372f.png)

That's my pivpn -d output. If you see the Roys-iPhoneX client configuration under "Client configuration shown below", that was a non-working configuration, which I had to change to the following:
![pivpn working client config](https://user-images.githubusercontent.com/54516411/78409593-0e359600-75d8-11ea-89a9-9199edeb4f6a.jpeg)

I added the IPv6 addresses manually AFTER I fixed the issue.

**Comment by orazioedoardo** [comment]
> Client CIDR notations should have /32. Do the clients really need /24?!

While I think /32 works as well, I don't think /24 on the client prevented your client from connecting. I myself use the PiVPN config without issues, any chance that you also had some other firewall issues that you fixed in the meanwhile?

**Comment by QuarkSolution** [comment]
I didn't. Maybe it's a Windows specific issue with /24? Because my iPhone would work fine, my WIndows laptop wouldn't get an IP. Only after I changed those to /32, my Windows laptop started working.

**Comment by orazioedoardo** [comment]
I was reviewing the issues and went back here.

When you set `Address = 10.6.0.2/24`, you are not giving the client 256 addresses, you are just defining an IP with a mask for the network of the wireguard interface. Pretty much like you have (for example) 192.168.1.13/24 for a physical interface.
Then you use `AllowedIPs = 10.6.0.2/32` on the server to allow only that single IP inside the tunnel.

> I didn't. Maybe it's a Windows specific issue with /24? Because my iPhone would work fine, my WIndows laptop wouldn't get an IP.

In regard to the internal IP, 10.6.0.X, that is not assigned by the server, it is autoassigned by the client when you turn on wireguard (even if hasn't connected to the server yet).

> but the client doesn't get assigned a IP on connection (I checked using "pivpn -c")

This means that the client can't reach the server.

Since it's been a while, I'm closing the issue. Reopen if you have anything to add.
