### ISSUE TITLE
[Support] Is there a way to increase WireGuard speed?

### ISSUE THREAD

**Issue by reinisb** [pivpn/pivpn#1009]
## In raising this issue, I confirm the following: 

- [x] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

### Issue
Hi folks!

Today I formatted my SD card, installed the newest raspbian lite and set up a WireGuard server via pivpn on my Raspberry Pi 3 Model B+. The pivpn setup was seamless and WireGuard clients on my iPhone and MacBook are working great. Thanks a lot folks!

Now, about performance. I have a 200 Mbit/s up/down fiber optics connection and WireGuard manages to reach 97Mbit/s up/down on speedtest.net (server and client are using ethernet). Yes, I know, Iiperf would most likely report higher numbers, but I wanted to check "real-life" speeds. The download speed (97 Mbit/s) is a slight improvement over OpenVPN (86 Mbit/s), while upload speed (97 Mbit/s) is a significant improvement over OpenVPN (67 Mbit/s). I can also see that CPU load of my Raspberry Pi 3 Model B+ is only ~22%.

Now, I browsed the web and issues in this repo, but I could not find speed reports from others. Hence, my question - is there a way to significantly increase the WireGuard speed by changing some aspects of the pivpn WireGuard config on my Raspberry Pi 3 Model B+? If not, will an upgrade to Raspberry Pi 4 Model B allow to increase the speed relative to what I have right now? If yes, what speeds are you experiencing on Pi 4?

Thanks!

<img width="1454" alt="Screen Shot 2020-04-04 at 10 14 22" src="https://user-images.githubusercontent.com/6346595/78422755-69b06400-766a-11ea-99f4-5ed493c374b7.png">

### Have you searched for similar issues and solutions?
Yes

### Console output of      `curl -L install.pivpn.dev | bash`
```
  I got the blue Existing Install Detected! screen in my Terminal. What exactly should I post here?
```

### Console output of      `pivpn add` or `pivpn add nopass`
```
 Enter a Name for the Client: 
```

### Console output of      `pivpn debug`
```
  ::::		PiVPN debug		 ::::
=============================================
::::		Latest commit		 ::::
commit f045e3935d12e1eb714fa0f630b021209e926aef (grafted, HEAD -> master, origin/test, origin/master, origin/HEAD)
Author: Orazio <orazioedoardo@users.noreply.github.com>
Date:   Mon Mar 23 08:48:19 2020 +0100

    Merge pull request #991 from rayden84/typo-fix
    
    Update install.sh
=============================================
::::	    Installation settings    	 ::::
PLAT=Raspbian
OSCN=buster
USING_UFW=0
IPv4dev=eth0
dhcpReserv=1
IPv4addr=10.77.77.160/24
IPv4gw=10.77.77.254
install_user=pi
install_home=/home/pi
VPN=wireguard
pivpnPORT=1194
pivpnDNS1=8.8.8.8
pivpnDNS2=8.8.4.4
pivpnHOST=REDACTED
INPUT_CHAIN_EDITED=0
FORWARD_CHAIN_EDITED=0
pivpnPROTO=udp
pivpnDEV=wg0
pivpnNET=10.6.0.0
subnetClass=24
UNATTUPG=1
INSTALLED_PACKAGES=(git dnsutils iptables-persistent raspberrypi-kernel-headers wireguard wireguard-tools wireguard-dkms qrencode unattended-upgrades)
=============================================
::::  Server configuration shown below   ::::
[Interface]
PrivateKey = server_priv
Address = 10.6.0.1/24
ListenPort = 1194
# begin reinis
[Peer]
PublicKey = reinis_pub
PresharedKey = psk
AllowedIPs = 10.6.0.2/32
# end reinis
# begin macbook
[Peer]
PublicKey = macbook_pub
PresharedKey = psk
AllowedIPs = 10.6.0.3/32
# end macbook
=============================================
::::  Client configuration shown below   ::::
[Interface]
PrivateKey = reinis_priv
Address = 10.6.0.2/24
DNS = 8.8.8.8, 8.8.4.4

[Peer]
PublicKey = server_pub
PresharedKey = psk
Endpoint = REDACTED:1194
AllowedIPs = 0.0.0.0/0, ::0/0
=============================================
:::: 	Recursive list of files in	 ::::
::::	[4m/etc/wireguard shown below	 ::::
/etc/wireguard:
configs  keys  wg0.conf

/etc/wireguard/configs:
clients.txt  macbook.conf  reinis.conf

/etc/wireguard/keys:
macbook_priv  macbook_pub  psk	reinis_priv  reinis_pub  server_priv  server_pub
=============================================
::::		Self check		 ::::
:: [OK] IP forwarding is enabled
:: [OK] Iptables MASQUERADE rule set
:: [OK] WireGuard is running
:: [OK] WireGuard is enabled (it will automatically start on reboot)
:: [OK] WireGuard is listening on port 1194/udp
=============================================
:::: Having trouble connecting? Take a look at the FAQ:
:::: https://github.com/pivpn/pivpn/wiki/FAQ
=============================================
:::: WARNING: This script should have automatically masked sensitive       ::::
:::: information, however, still make sure that PrivateKey, PublicKey      ::::
:::: and PresharedKey are masked before reporting an issue. An example key ::::
:::: that you should NOT see in this log looks like this:                  ::::
:::: YIAoJVsdIeyvXfGGDDadHh6AxsMRymZTnnzZoAb9cxRe                          ::::
=============================================
::::		Debug complete		 ::::

```
### Have you taken any steps towards solving your issue?
```
I searched online, but could not find an answer.
```

**Comment by orazioedoardo** [comment]
Not related to PiVPN, though here's my take: maybe check if your ethernet cable on the rapberry Pi support 1 Gigabit/s, the 3B+ should be able to do more than 100 Megabit/s. Do you get 200 Megabit/s using speedtest-cli on the 3B+?

**Comment by reinisb** [comment]
> Not related to PiVPN, though here's my take: maybe check if your ethernet cable on the rapberry Pi support 1 Gigabit/s, the 3B+ should be able to do more than 100 Megabit/s. Do you get 200 Megabit/s using speedtest-cli on the 3B+?

Hi! Thanks for the response. I checked the ethernet cable with my laptop - I can confirm 200 Mbit/s up/down. I also run speedtest-cli on 3B+ and here's the output (I wonder why upload is only 150 Mbit/s - SD card limitation? other limitation?).

```
pi@wireguard:~ $ python speedtest.py --server 1268
Retrieving speedtest.net configuration...
Testing from TET (REDACTED)...
Retrieving speedtest.net server list...
Retrieving information for the selected server...
Hosted by Tet (Riga) [0.38 km]: 8.072 ms
Testing download speed................................................................................
Download: 203.16 Mbit/s
Testing upload speed................................................................................................
Upload: 152.51 Mbit/s
```

**Comment by orazioedoardo** [comment]
> I also run speedtest-cli on 3B+ and here's the output (I wonder why upload is only 150 Mbit/s - SD card limitation? other limitation?).

I don't know, probably CPU power? Quirks with that specific speedtest server: https://github.com/sivel/speedtest-cli#inconsistency. Most likely not an SD card issue, the test should be performed in RAM.

There are not many knobs with WireGuard, maybe MTU but I've never experimented with that.

**Comment by reinisb** [comment]
> I don't know, probably CPU power? Quirks with that specific speedtest server: https://github.com/sivel/speedtest-cli#inconsistency. Most likely not an SD card issue, the test should be performed in RAM.

I installed speedtest-cli on my 2019 quad-core mac and I get the exact same down/up speed as with 3B+. Hence, I suppose it is the limitation of python.

That being said, I would still appreciate if someone could please post their speed results when running a PiVPN Wireguard server on Raspberry Pi 3B+ or 4B. Thanks!

**Comment by orazioedoardo** [comment]
> Returning to the original topic - I would still really appreciate if someone could please post their speed results when running a PiVPN Wireguard server on Raspberry Pi 3B+ or 4B. That would allow to verify whether going above 97Mbit/s up/down with Wireguard server on a Raspberry Pi is possible. Thanks!

I found this: https://www.reddit.com/r/WireGuard/comments/eeafds/wireguard_throughput_on_raspberry_pi_4/
