### ISSUE TITLE
[BUG] `pivpn add` generates incomplete OpenVPN configuration

### ISSUE THREAD

**Issue by mardy** [pivpn/pivpn#1010]
## In raising this issue, I confirm the following: 

- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

**Describe the bug**
The `.ovpn` files generated by the `pivpn add` command only contain the OpenVPN keys, but no configuration.

**To Reproduce**
1. Configure pivpn for OpenVPN
2. Run `pivpn add`
3. Look at the generated script under `~/ovpns/`: it contains only the `<ca>`, `<cert>`, `<key>` and `<tls-auth>` elements.

**Expected behavior**
I would expect the generated script to contain the IP address and port of the VPN server, the username and, if needed, other client configuration options.

**Command output**
The command emits an error while run, though I wonder if it's actually related:
```
$ pivpn add
Enter a Name for the Client:  mytest
How many days should the certificate last?  1080
Enter the password for the client:  
Enter the password again to verify:  
spawn ./easyrsa build-client-full mytest

Note: using Easy-RSA configuration from: ./vars

Using SSL: openssl OpenSSL 1.1.1d  10 Sep 2019
Generating a RSA private key
.+++++
.......................................+++++
writing new private key to '/etc/openvpn/easy-rsa/pki/private/mytest.key.BV1eJEasbN'
Enter PEM pass phrase:hello

Verifying - Enter PEM pass phrase:
-----
Using configuration from /etc/openvpn/easy-rsa/pki/safessl-easyrsa.cnf
Check that the request matches the signature
Signature ok
The Subject's Distinguished Name is as follows
commonName            :ASN.1 12:'mytest'
Certificate is to be certified until Mar 20 10:24:17 2023 GMT (1080 days)

Write out database with 1 new entries
Data Base Updated
Client's cert found: mytest.crt
Client's Private Key found: mytest.key
CA public Key found: ca.crt
tls Private Key found: ta.key
cat: Default.txt: No such file or directory


========================================================
Done! mytest.ovpn successfully created! 
mytest.ovpn was copied to:
  /home/mardy/ovpns
for easy transfer. Please use this profile only on one
device and create additional profiles for other devices.
========================================================
```

**Comment by orazioedoardo** [comment]
> The command emits an error while run, though I wonder if it's actually related:

It is, the template is missing, no idea why, post the output of `pivpn -d`.

**Comment by mardy** [comment]
Here it is (I changed some hashes to "XXX" just be on the paranoid side): [debug.txt](https://github.com/pivpn/pivpn/files/4444040/debug.txt)

**Comment by orazioedoardo** [comment]
During the installation, the [template](https://github.com/pivpn/pivpn/blob/4e8d4dfd8ef01e49f3137d5fc5a2afa14a465e47/files/etc/openvpn/easy-rsa/pki/Default.txt) is copied [here](https://github.com/pivpn/pivpn/blob/4e8d4dfd8ef01e49f3137d5fc5a2afa14a465e47/auto_install/install.sh#L1934), if such file is missing, I don't see how a client named `streghetta` could successfully connect, so perhaps you accidentally deleted `Default.txt` when making some changes? I see that you changed the server config from `tls-version-min 1.2` to `tls-version-min 1.0`.

`Apr  7 11:26:33 macmini ovpn-server[5053]: REDACTED:44846 [streghetta] Peer Connection Initiated with [AF_INET]REDACTED:44846`

**Comment by mardy** [comment]
> if such file is missing, I don't see how a client named `streghetta` could successfully connect

I manually extracted all the keys, and configured a few devices. The VPN works fine, it's just that the generated `ovpn` files are incomplete.

> so perhaps you accidentally deleted `Default.txt` when making some changes? I see that you changed the server config from `tls-version-min 1.2` to `tls-version-min 1.0`.

I had to change that to support a specific client. But no, I didn't delete `Default.txt` :-)

What I had to fight with, is that the command `curl -L https://install.pivpn.io` did (and still does) not work from that server (connection timed out), so I had to download the script locally and than push it over the PI. If the installation script is downloading the template from the same server, that might have failed too. 

`curl` works on the PI, it looks like it's just the server `install.pivpn.io` which does not work from my location (Finland, with connection provided by Elisa.fi). I downloaded the script from Russia and it worked.

**Comment by orazioedoardo** [comment]
> If the installation script is downloading the template from the same server, that might have failed too.

The file is copied from the cloned repo which is on github. Can is see the folder structure? `ls -lR /etc/.pivpn`.

If you just want to fix the generation with `pivpn add`, just download `Default.txt` into `/etc/openvpn/easy-rsa/pki` and update the file according to your configuration.

**Comment by mardy** [comment]
It looks like the file is there: 
[folders.txt](https://github.com/pivpn/pivpn/files/4445065/folders.txt)

**Comment by orazioedoardo** [comment]
So it means that for some reason the confOVPN function did not run. As I said if you want to fix pivpn, just copy the file to the proper location, otherwise if you want to help me understand the reason, download the script, add `set -x` after the `#!/usr/bin/env bash`, and run the script manually to reinstall. It will run in verbose mode, thus you will need to hide quite a bit of text to post the output here.

Pick one.

**Comment by orazioedoardo** [comment]
No comments in a while, closing...

Reopen if you need further assistance on the same topic.
