### ISSUE TITLE
[Question] Next release?

### ISSUE THREAD

**Issue by gurpal2000** [pivpn/pivpn#1012]
[Question] I read somewhere (possibly old) that this project was no longer maintained. Clearly there are many commits/activity. Is there going to be a release at some point?

thank you

**Comment by orazioedoardo** [comment]
I answered a similar question [here](https://github.com/pivpn/pivpn/issues/916#issuecomment-580755528):
> Just install from the master branch. You don't see new releases not because master is still buggy but because we don't really have a reason to create them.
