### ISSUE TITLE
[Support] PIVPN on Pi-hole install some sites not available

### ISSUE THREAD

**Issue by imc67** [pivpn/pivpn#1013]
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [?] The issue I am reporting can be *replicated*.
- [?] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

### Issue
I installed PIVPN (option Wireguard) on an existing Pi-hole install (RPi3b). All seems to work perfect ... however some websites are not reachable like Wordpress.org!

root@pihole:/home/pi# host wordpress.org 10.6.0.1
;; communications error to 10.6.0.1#53: end of file
;; communications error to 10.6.0.1#53: end of file

### Have you searched for similar issues and solutions?
    (yes/no / which issues?)
yes but this particular not found

### Console output of      `curl -L install.pivpn.dev | bash`
```
  Output Here
```

### Console output of      `pivpn add` or `pivpn add nopass`
```
  Output Here
```

### Console output of      `pivpn debug`
```
root@pihole:/home/pi# pivpn debug
::::            PiVPN debug              ::::
=============================================
::::            Latest commit            ::::
commit f045e3935d12e1eb714fa0f630b021209e926aef (HEAD -> master, origin/test, origin/master, origin/HEAD)
Merge: fcf05d7 df43513
Author: Orazio <orazioedoardo@users.noreply.github.com>
Date:   Mon Mar 23 08:48:19 2020 +0100

    Merge pull request #991 from rayden84/typo-fix
    
    Update install.sh
=============================================
::::        Installation settings        ::::
PLAT=Raspbian
OSCN=buster
USING_UFW=0
IPv4dev=eth0
IPv4addr=192.168.1.2/24
IPv4gw=192.168.1.1
install_user=pi
install_home=/home/pi
VPN=wireguard
pivpnPORT=51820
pivpnDNS1=10.6.0.1
pivpnDNS2=
pivpnHOST=REDACTED
INPUT_CHAIN_EDITED=0
FORWARD_CHAIN_EDITED=0
pivpnPROTO=udp
pivpnDEV=wg0
pivpnNET=10.6.0.0
subnetClass=24
UNATTUPG=1
INSTALLED_PACKAGES=(iptables-persistent raspberrypi-kernel-headers wireguard wireguard-tools wireguard-dkms qrencode unattended-upgrades)
=============================================
::::  Server configuration shown below   ::::
[Interface]
PrivateKey = server_priv
Address = 10.6.0.1/24
ListenPort = 51820
# begin ***-iphone
[Peer]
PublicKey = ***-iphone_pub
PresharedKey = psk
AllowedIPs = 10.6.0.2/32
# end ***-iphone
# begin ***-ipad
[Peer]
PublicKey = ***-ipad_pub
PresharedKey = psk
AllowedIPs = 10.6.0.3/32
# end ***-ipad
# begin ***-macbook
[Peer]
PublicKey = ***-macbook_pub
PresharedKey = psk
AllowedIPs = 10.6.0.4/32
# end ***-macbook
# begin ###-iphone
[Peer]
PublicKey = ###-iphone_pub
PresharedKey = psk
AllowedIPs = 10.6.0.5/32
# end ###-iphone
# begin ###-ipad
[Peer]
PublicKey = ###-ipad_pub
PresharedKey = psk
AllowedIPs = 10.6.0.6/32
# end ###-ipad
# begin kodi
[Peer]
PublicKey = kodi_pub
PresharedKey = psk
AllowedIPs = 10.6.0.7/32
# end kodi
=============================================
::::  Client configuration shown below   ::::
[Interface]
PrivateKey = ***-iphone_priv
Address = 10.6.0.2/24
DNS = 10.6.0.1

[Peer]
PublicKey = server_pub
PresharedKey = psk
Endpoint = REDACTED:51820
AllowedIPs = 0.0.0.0/0, ::0/0
=============================================
::::    Recursive list of files in       ::::
::::    /etc/wireguard shown below       ::::
/etc/wireguard:
configs  keys  wg0.conf

/etc/wireguard/configs:
clients.txt  ###-ipad.conf  ###-iphone.conf  kodi.conf  ***-ipad.conf  ***-iphone.conf  ***-macbook.conf

/etc/wireguard/keys:
###-ipad_priv  ###-iphone_priv  kodi_priv  ***-ipad_priv  ***-iphone_priv  ***-macbook_priv  psk          server_pub
###-ipad_pub   ###-iphone_pub   kodi_pub   ***-ipad_pub   ***-iphone_pub   ***-macbook_pub   server_priv
=============================================
::::            Self check               ::::
:: [OK] IP forwarding is enabled
:: [OK] Iptables MASQUERADE rule set
:: [OK] WireGuard is running
:: [OK] WireGuard is enabled (it will automatically start on reboot)
:: [OK] WireGuard is listening on port 51820/udp
=============================================
:::: Having trouble connecting? Take a look at the FAQ:
:::: https://github.com/pivpn/pivpn/wiki/FAQ
=============================================
:::: WARNING: This script should have automatically masked sensitive       ::::
:::: information, however, still make sure that PrivateKey, PublicKey      ::::
:::: and PresharedKey are masked before reporting an issue. An example key ::::
:::: that you should NOT see in this log looks like this:                  ::::
:::: YIAoJVsdIeyvXfGGDDadHh6AxsMRymZTnnzZoAb9cxRe                          ::::
=============================================
::::            Debug complete           ::::```
### Have you taken any steps towards solving your issue?
```
search the internet for solutions```

**Comment by imc67** [comment]
Without doing anything after a half an hour it suddenly worked?! Yesterday evening I had the same issue and also then after x time it worked again.....

**Comment by orazioedoardo** [comment]
How about these? (Run from the raspberry pi).
```
dig wordpress.org @192.168.1.2
dig wordpress.org @10.6.0.1
dig wordpress.org @127.0.0.1
```

**Comment by imc67** [comment]
```
root@pihole:/etc/dnsmasq.d# dig wordpress.org @192.168.1.2

; <<>> DiG 9.11.5-P4-5.1-Raspbian <<>> wordpress.org @192.168.1.2
;; global options: +cmd
;; connection timed out; no servers could be reached
```

```
root@pihole:/etc/dnsmasq.d# dig wordpress.org @10.6.0.1
;; Truncated, retrying in TCP mode.

; <<>> DiG 9.11.5-P4-5.1-Raspbian <<>> wordpress.org @10.6.0.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 16166
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1452
;; QUESTION SECTION:
;wordpress.org.                 IN      A

;; ANSWER SECTION:
wordpress.org.          578     IN      A       198.143.164.252

;; Query time: 37 msec
;; SERVER: 10.6.0.1#53(10.6.0.1)
;; WHEN: Tue Apr 07 13:29:10 BST 2020
;; MSG SIZE  rcvd: 58
```

```
root@pihole:/etc/dnsmasq.d# dig wordpress.org @127.0.0.1
;; Truncated, retrying in TCP mode.

; <<>> DiG 9.11.5-P4-5.1-Raspbian <<>> wordpress.org @127.0.0.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 17886
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1452
;; QUESTION SECTION:
;wordpress.org.                 IN      A

;; ANSWER SECTION:
wordpress.org.          495     IN      A       198.143.164.252

;; Query time: 39 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Tue Apr 07 13:30:33 BST 2020
;; MSG SIZE  rcvd: 58
```

Just some more info as I'm googling around:
I also used Pi-hole for DHCP, since PIVPN added I get notifications from other devices in the home network that they didn't get connections anymore. In this thread (https://github.com/pivpn/pivpn/issues/946#issuecomment-595401066) I used the solution to delete (rename) 02-pivpn.conf but that didn't work out.
I solved it temporarily to make my home router DHCP again en disabled DHCP in Pi-hole.
[just FYI I live in The Netherlands but am already for 5 weeks on "holiday" in Spain where I'm since 3,5 weeks in full lockdown. The RPi with Pi-hole and PIVPN is at home so I must be careful not to break it ;-) ]

**Comment by orazioedoardo** [comment]
What's the current interface listening behavior in the pihole dashboard? Do you have `/etc/dnsmasq.d/02-pivpn.conf`? If you do, post it's content, even if you renamed it (renaming does not disable the configuration).

> root@pihole:/etc/dnsmasq.d# dig wordpress.org @192.168.1.2

; <<>> DiG 9.11.5-P4-5.1-Raspbian <<>> wordpress.org @192.168.1.2
;; global options: +cmd
;; connection timed out; no servers could be reached

DNS resolution from the LAN seems broken.

**Comment by imc67** [comment]
haha I renamed to 02-pivpn.conf.backup

this is the content:

addn-hosts=/etc/pivpn/hosts.wireguard
interface=wg0

**Comment by orazioedoardo** [comment]
Try to completely remove `/etc/dnsmasq.d/02-pivpn.conf.backup`, restart pihole with `pihole restartdns` and then post the output of `dig wordpress.org @192.168.1.2`.

**Comment by imc67** [comment]
Wow, that did this job!

```
root@pihole:/etc/dnsmasq.d# dig wordpress.org @192.168.1.2
;; Truncated, retrying in TCP mode.

; <<>> DiG 9.11.5-P4-5.1-Raspbian <<>> wordpress.org @192.168.1.2
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 39539
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1452
;; QUESTION SECTION:
;wordpress.org.                 IN      A

;; ANSWER SECTION:
wordpress.org.          553     IN      A       198.143.164.252

;; Query time: 48 msec
;; SERVER: 192.168.1.2#53(192.168.1.2)
;; WHEN: Tue Apr 07 14:19:40 BST 2020
;; MSG SIZE  rcvd: 58
```

Do you think DHCP on Pi-hole will work again?

**Comment by orazioedoardo** [comment]
> Do you think DHCP on Pi-hole will work again?

It should 

> --- I see the first local devices coming up in Pi-hole interface

That’s a good sign. Close the issue if you are satisfied.

By the way, when PiVPN prompts to use Pi-hole as the DNS for the VPN, you don’t need to change the listening behavior in the pi-hole web interface. The 02-pivpn.conf file is created automatically if needed, more information in the issue you linked above.

**Comment by imc67** [comment]
@orazioedoardo thanks for your help, all seems to work just I wanted it to be.

Stay save and healthy!

Kind regards,

Marcel.

**Comment by matsonfamily** [comment]
What's the purpose of the` /etc/dnsmasq.d/02-pivpn.conf` file?  i disabled it and restarted [pihole] DNS and everything still works fine.  Can browse external and internal [to the network i VPN'd to] networks fine.

**Comment by orazioedoardo** [comment]
@matsonfamily it contains the mapping ip -> client name so that when you visit the pihole dashboard you see vpn clients listed by their name and not ip.
