### ISSUE TITLE
[Support] Disable NAT / Set PiVPN to transparent mode (Wireguard)

### ISSUE THREAD

**Issue by ewbree** [pivpn/pivpn#1014]
Hello,

I am trying to get my PiVPN (Running Wireguard) to work without using NAT.
I am using a Unifi USG for routing.

What I want is that when a client (peer) connects to the PiVPN (Wireguard) is that my Unifi USG will see the client (peer) as the source of the incoming traffic over the VPN tunnel (10.6.0.2) and not the IP of the Raspberry Pi itself (172.16.10.1). This should then enable me to use the firewall of the Unifi USG can block traffic to certain VLAN's from specific source IP's that originate from the VPN.

I have tried to look on the internet for anything about it, but with no luck. I do see people have installed Wireguard manually and need to add an iptables rule that basically enable NAT between the local IP of the Raspberry Pi and the IP of the Wireguard server on it. I effectively want to turn of this NAT feature, but I do not have any rules or options in place to do so.

Any help would be greatly appreciated.

Also yes, I can connect to my VPN fine and it all works. I just want to be able to see the IP of the peer (as if the connected client is inside the network). Not the Raspberry that now does the forwarding (thus NAT).

Debug below:
```::::            PiVPN debug              ::::
=============================================
::::            Latest commit            ::::
commit 4e8d4dfd8ef01e49f3137d5fc5a2afa14a465e47 (grafted, HEAD -> master, origin/test, origin/master, origin/HEAD)
Author: Orazio <orazioedoardo@users.noreply.github.com>
Date:   Tue Apr 7 13:45:43 2020 +0200

    Merge pull request #1000 from psgoundar/pivpn

    Updated listOVPN to Include Expiration Dates
=============================================
::::        Installation settings        ::::
PLAT=Raspbian
OSCN=buster
USING_UFW=0
IPv4dev=eth0
IPv4addr=172.16.10.1/24
IPv4gw=172.16.10.254
install_user=pi
install_home=/home/pi
VPN=wireguard
pivpnPORT=51820
pivpnDNS1=10.6.0.1
pivpnDNS2=
pivpnHOST=REDACTED
INPUT_CHAIN_EDITED=0
FORWARD_CHAIN_EDITED=0
pivpnPROTO=udp
pivpnDEV=wg0
pivpnNET=10.6.0.0
subnetClass=24
UNATTUPG=1
INSTALLED_PACKAGES=()
=============================================
::::  Server configuration shown below   ::::
[Interface]
PrivateKey = server_priv
Address = 10.6.0.1/24
ListenPort = 51820
# begin ewoud-telefoon
[Peer]
PublicKey = ewoud-telefoon_pub
PresharedKey = psk
AllowedIPs = 10.6.0.2/32
# end ewoud-telefoon
# begin jeroendeneef
[Peer]
PublicKey = jeroendeneef_pub
PresharedKey = psk
AllowedIPs = 10.6.0.3/32
# end jeroendeneef
=============================================
::::  Client configuration shown below   ::::
[Interface]
PrivateKey = ewoud-telefoon_priv
Address = 10.6.0.2/24
DNS = 10.6.0.1

[Peer]
PublicKey = server_pub
PresharedKey = psk
Endpoint = REDACTED:51820
AllowedIPs = 0.0.0.0/0
=============================================
::::    Recursive list of files in       ::::
::::    /etc/wireguard shown below       ::::
/etc/wireguard:
configs  keys  wg0.conf

/etc/wireguard/configs:
clients.txt  ewoud-telefoon.conf  jeroendeneef.conf

/etc/wireguard/keys:
ewoud-telefoon_priv  ewoud-telefoon_pub  jeroendeneef_priv  jeroendeneef_pub  psk  server_priv  server_pub
=============================================
::::            Self check               ::::
:: [OK] IP forwarding is enabled
:: [OK] Iptables MASQUERADE rule set
:: [OK] WireGuard is running
:: [OK] WireGuard is enabled (it will automatically start on reboot)
:: [OK] WireGuard is listening on port 51820/udp
=============================================
:::: Having trouble connecting? Take a look at the FAQ:
:::: https://github.com/pivpn/pivpn/wiki/FAQ
=============================================
:::: WARNING: This script should have automatically masked sensitive       ::::
:::: information, however, still make sure that PrivateKey, PublicKey      ::::
:::: and PresharedKey are masked before reporting an issue. An example key ::::
:::: that you should NOT see in this log looks like this:                  ::::
:::: YIAoJVsdIeyvXfGGDDadHh6AxsMRymZTnnzZoAb9cxRe                          ::::
=============================================
::::            Debug complete           ::::
```

**Comment by ewbree** [comment]
I managed to fix it by actually installing OpenVPN first. Searching around for that and using the command:
**`iptables -t nat -L -n -v`.**

That show the rule:
**`138  8438 MASQUERADE  all  --  *      eth0    10.6.0.0/24          0.0.0.0/0            /* wireguard-nat-rule */` which I then deleted by using the command: `sudo iptables -t nat -D POSTROUTING -s 10.6.0.0/24 -o eth0 -m comment --comment wireguard-nat-rule -j MASQUERADE`**

After having already created a route in on my gateway to the Raspberry Pi for the Wireguard subnet it now behaves as I want it to. Hosts now appear as if they're inside the network instead of going through NAT to reach it.

**Comment by orazioedoardo** [comment]
> After having already created a route in on my gateway to the Raspberry Pi for the Wireguard subnet it now behaves as I want it to. Hosts now appear as if they're inside the network instead of going through NAT to reach it

Yes that's the right way, add a route to 10.6.0.0/24 using 172.16.10.1 as gateway. And remove the NAT rule.

> I am sure I am not the only one wanting to do this. So me and others would maybe appreciate it if this would be an option to disable or enable NAT with the installation process of PiVPN?

I think this is better added to the wiki, disabling NAT also requires to mess with the default gateway, which not every user is able to or can do (many ISP routers won't allow you to do this).

**Comment by ewbree** [comment]
Yes. Next step is to get the pivpn IP subnet to 172.16.1.0/24
Because I want to keep everything in the 172.16.x.x range.

A lot of companies and homes use 192.168.x.x or 10.x.x.x so this reduces my chances of my VPN not working when I only route specific traffic over it through the 'Allowedips' setting.

**Comment by mwoolweaver** [comment]
> Yes. Next step is to get the pivpn IP subnet to 172.16.1.0/24

have you tried editing `/etc/wireguard/wg0.conf`? If so disregard what follows...

Original:

			[Interface]
			PrivateKey = (xxxxx-You-Can-Not-Has-Private-Key-xxxxx)
			Address = 10.6.0.1/24
			ListenPort = 51820


Edit:

			[Interface]
			PrivateKey = (xxxxx-You-Can-Not-Has-Private-Key-xxxxx)
			Address = 172.16.1.0/24
			ListenPort = 51820

**Comment by ewbree** [comment]
> > Yes. Next step is to get the pivpn IP subnet to 172.16.1.0/24
> 
> have you tried editing `/etc/wireguard/wg0.conf`? If so disregard what follows...
> 
> Original:
> 
> ```
> 		[Interface]
> 		PrivateKey = (xxxxx-You-Can-Not-Has-Private-Key-xxxxx)
> 		Address = 10.6.0.1/24
> 		ListenPort = 51820
> ```
> 
> Edit:
> 
> ```
> 		[Interface]
> 		PrivateKey = (xxxxx-You-Can-Not-Has-Private-Key-xxxxx)
> 		Address = 172.16.1.0/24
> 		ListenPort = 51820
> ```

Yes. I already tried and it worked. Sadly, new users still get an IP from the 10.6.0.x subnet. Though no hard to change. But quite a pain to do it on multiple files for one single new user...

**Comment by mwoolweaver** [comment]
> Yes. I already tried and it worked. Sadly, new users still get an IP from the 10.6.0.x subnet. Though no hard to change. But quite a pain to do it on multiple files for one single new user...

So would this be a @Wireguard issue? As Wireguard should had out IP's for network that it's interface uses?

**Comment by ewbree** [comment]
> > Yes. I already tried and it worked. Sadly, new users still get an IP from the 10.6.0.x subnet. Though no hard to change. But quite a pain to do it on multiple files for one single new user...
> 
> So would this be a @WireGuard issue? As Wireguard should hand out IP's for the range of IP's that it's interface uses?

I doubt it is. I get the following when I do: `pivpn -d`

![image](https://user-images.githubusercontent.com/42831465/79613316-9484c880-80fe-11ea-83c7-5e5cee19389e.png)

pivpnNET is still at '10.6.0.0'.
Must still not have something fully configured.

Not only that, but I also want to add a second instance of wireguard (wg1 or something) that **does** include NAT and works on a tagged subinterface to another network of mine. But that's future stuff I want to add.

**Comment by mwoolweaver** [comment]
> pivpnNET is still at '10.6.0.0'.

Probably just need to edit the files in `/etc/pivpn/` accordingly

The output from that command looks like the `SetupVars.conf` file found in the directory I mentioned. There’s also another file in there you might wanna change

**Comment by orazioedoardo** [comment]
Editing setupVars.conf only influences future client generation, if you just want to change the existing setup, edit `/etc/wireguard/wg0.conf`, client configuration and possibly firewall rules.

Using 172.16.1.0/24 for the VPN subnet will conflict with the LAN subnet. If your VPN client wants to send packets to 172.16.0.3, how does it know if you mean a VPN client 172.16.0.3 or LAN client 172.16.0.3?

**Comment by ewbree** [comment]
I already managed to create a subinterface (tagged virtual interface) on eth0 and use the NAT rule to only route 172.16.1.64/26 to that and NAT it. Though now my friend can't reach the NAS in the 172.6.10.0/24 subnet, probably because there is not default route from the subinterface. I will fix that eventually.

> Using 172.16.1.0/24 for the VPN subnet will conflict with the LAN subnet. If your VPN client wants to send packets to 172.16.0.3, how does it know if you mean a VPN client 172.16.0.3 or LAN client 172.16.0.3?

That problems would only exist if you have:
1: Anything else except 0.0.0.0/0 as allowedip.
2: Your remote client is in a 172.16.0.0/24 subnet. (That's the whole reason I chose 172.16.x.x as internal network because a lot of homes and offices use either 10.x.x.x or 192.168.x.x.)
3: It won't conflict on my network because I already reserved 172.16.1.0/24 in my documentation.

**Comment by kevindd992002** [comment]
I'm trying to do something similar here as I want my gateway/firewall pfsense to see clients from the remote side by their real private IP's, not by the remote peer IP as achieved in this thread. Is there any way to disable outbound NATting on the wg interface itself?

**Comment by sypion** [comment]
2 years later I'm encountering a similar issue.

Client IPs from Wireguard are showing up as my VM's IP on AdGuard Home. The only way I can mitigate this is by removing the MASQUERADE postforward rule generated by PiVPN like @ewbree shared. My only struggle now is that domains when using the Wireguard VPN are not being resolved, likely due to the fact that there is no longer a NAT rule.

What rule can I enter in iptables so that service can return to my Wireguard clients and AdGuard Home is resolving properly and displayingthe client IPs?
