### ISSUE TITLE
Cannot access internet while connected to pivpn on home network

### ISSUE THREAD

**Issue by jsb6770** [pivpn/pivpn#1020]
I could not find this issue anywhere. I can connect to my pivpn while on mobile network on my phone, and I get internet access. If I turn wifi on, on my phone, or try to connect to my pivpn on my laptop, I can connect, but I do not have access to internet. I have not tried while connected to a different network, other than my own. I also am using Wireguard. What could be causing this? What do you need in order to help me with this issue?

**Comment by proper-type** [comment]
Which wifi are you using? Could be a public network where UDP oder Wireguard is blocked.

**Comment by jsb6770** [comment]
I am using my home wifi so I do not believe it’s a port forwarding issue. I know it might seem redundant to connect to a vpn while connected to my home network but I want to set up pihole, so I want functionality on all my devices

**Comment by shelleycat485** [comment]
1 When you say "connect to your pivpn on your laptop" you are connecting through your external internet address.
2 When your laptop is connected, can you ping your home network gateway (might be your router, probably is by default)
3 What does a dns query (e.g nsquery from your laptop) say about your dns when connected to the internet, and then when connected by pivpn?

**Comment by orazioedoardo** [comment]
> If I turn wifi on, on my phone, or try to connect to my pivpn on my laptop, I can connect, but I do not have access to internet. I have not tried while connected to a different network, other than my own.

From: https://github.com/pivpn/pivpn/wiki/FAQ#packet-capture

> Connecting from the same network as the server not only doesn't make sense (you are already inside the network the VPN is supposed to connect you to) but may not work with many routers.

**Comment by Rustymage** [comment]
Are you using OpenVPN or Wireguard?

**Comment by 4s3ti** [comment]
Closing this one ... l
Not only the use case doesn't make sense at all but also the VPN seems to be working as expected and the thread is inactive
