### ISSUE TITLE
[BUG] backup.sh: Small Spelling & Grammar Issue

### ISSUE THREAD

**Issue by cliss** [pivpn/pivpn#1024]
## In raising this issue, I confirm the following: 
- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

**Describe the bug**
There are a couple of spelling and grammar mistakes in the `backup` script.

- [ ] The script's output reads `crated` instead of `created`
- [ ] The script's output reads `cr`e`ated to` instead of `created in`

**To Reproduce**
1. `pivpn -bk` and observe output

**Expected behavior**
Script's output should read `Backup created in`. Instead it reads `Backup crated to`

**Screenshots**
```
pi@raspberrypi:~ $ pivpn -bk
Backup crated to /home/pi/pivpnbackup/20200421-081139-pivpnwgbackup.tgz 
To restore the backup, follow instructions at:
https://github.com/pivpn/pivpn/wiki/FAQ#how-can-i-migrate-my-configs-to-another-pivpn-instance
```

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
I am adding a PR for this issue immediately.

**Comment by orazioedoardo** [comment]
Done, thanks,
