### ISSUE TITLE
[Support]  chained vpn server

### ISSUE THREAD

**Issue by unicorn667** [pivpn/pivpn#1026]
Hi All,

it´s possible to chain pivpn server?

I have found a very good how to here, is this also possible with pivvpn?

https://www.ckn.io/blog/2017/12/28/wireguard-vpn-chained-setup/

thx for reading

Best Regards

**Comment by orazioedoardo** [comment]
You can use PiVPN to install the WireGuard servers mentioned in the guide but the rest is out of scope here.
