### ISSUE TITLE
[BUG] update operation does not appear to set permissions, and does not source bash_completion

### ISSUE THREAD

**Issue by shelleycat485** [pivpn/pivpn#1028]
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

**Describe the bug**
The update.sh script copies files from the local repository.  The installer script uses the 'install' command and sets permissions.
The installer script sources the bash_completion after copying, the update.sh does not.
The effect is that permissions may not be the same after the update, and the bash completion will not be updated until the next reboot

**To Reproduce**
1. Go to copy of repository, edit scripts/install.sh, search for bash_completion
2. Compare with installer.sh, search for /etc/bash_completion.d

I found this when updating update.sh for installation of both wireguard and opvn protocols.

**Comment by orazioedoardo** [comment]
Actually I'm not really sure if the update script is really useful, as written in the original [Upgrading wiki](https://github.com/pivpn/pivpn/wiki/Upgrading) PiVPN is an installer (and a bit management) script, there is not really much to update. Scripts from the git repo change but mostly to accommodate changes in the install script @4s3ti

**Comment by orazioedoardo** [comment]
Follow up on issue #1069
