### ISSUE TITLE
wireguard IPV6

### ISSUE THREAD

**Issue by GPConnect** [pivpn/pivpn#1032]
Hello, 

Just wondering if we can setup pivpn in dual stack mode using wireguard ?

My pihole is setup in dual stack mode but it seem like the pivpn setup only chose to works with ipv4 for endpoint and dns ! 

Are we protected against ipv6 leak ? 

Thanks

**Comment by orazioedoardo** [comment]
IPv6 is not currently supported (I myself can't test it). IPv6 leak should be avoided: https://github.com/pivpn/pivpn/commit/1352ccf9a3d7c6379e0b205be73558c7e3bd3ef4
