### ISSUE TITLE
[BUG] <install script and pivpn sh not completing correctly>

### ISSUE THREAD

**Issue by brantchyoga** [pivpn/pivpn#1034]
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

**Describe the bug**
I am a beginner so bear with me if I say something stupid.
Running the install script `curl -L https://install.pivpn.io | bash` begins the download but first forces me to apt-get -update (according to the newer raspbian OS documentation, we should only be using "apt" not "apt-get" because it could update an unstable version)(Issue #1). Then pivpn shell opens and the next Issue is at the end of the shell prompts where it informs me that my Kernel is not up to date (wireguard needs a specific kernel if so which one please) despite the fact I am running the latest version 4.19...v64 (Issue #2). Then I am forced into an apt-get upgrade or to stop installation. "Apt-get upgrade" should now be "apt full-upgrade" unless you want upgrade possibility to an unstable version of raspbian OS(Issue #3). I am asked to reboot. Then login back in and run the install script again only to see that my kernel is still the latest 4.19..v64 but the message says something about wireguard needing the latest kernel which I have would you like to do your apt-get upgrade and reboot? This leaves me in one big loop never fully completing the install script.
**To Reproduce**
preq-> set raspberry pi's IP static on router
1. Format sd card fat32-download berryboot and put on SD card
2.connect 2.5" SATA III SSD 480gb to usb3 port
3.Go through berryboot choose sda (SSD) -format ext4 (OS will load/run on SSD not SD card)
4. Choose Raspbian full desktop (silicon valley host)
5. log on and go to terminal.  execute "df -h" to make sure SSD is in use.
6. execute "curl -L https://install.pivpn.io | bash"
7. defaults -> choose wireguard (I read that it was better)
8.After the apt-get upgrade your file system may start to crash like mine. This has been an issue for a bit now and the solution is not to use apt-get upgrade but to only use apt full-upgrade so you only ever are upgrading to a stable version.

**Expected behavior**
I have never set up pivpn before but I expected to be able to at least fully install everything before something went wrong.
**Screenshots**
I can reproduce this problem (already done it 3x). I can take screenshots if wanted and put them on here

**Desktop (please complete the following information):**
 - VPN Protocol 
I wanted wireguard
I am using berryboot so I can use SSD for more storage with Raspbian Buster full desktop downloaded/running on the SSD
newest stable version Rasbian buster linux kernel 4.19.75v64

**Smartphone (please complete the following information):**
I didn't make it to this part to even set up :(
 - VPN Protocol

**Additional context**
I am a beginner so how things work together can be tricky (PiVPN not like BerryBoot? PiVPN not compatible with SSD?) but I decided that if nothing else PiVPN shouldn't be forcing apt-get because of the unstable downloads... Currently breaking my file system until I erase format and try again. Btw if anyone seem this has some time to help a beginner with just what is possible with putting things together with a pi or general hints to resources I might be able to read that could be useful I would appreciate it.

**Comment by orazioedoardo** [comment]
> Then pivpn shell opens and the next Issue is at the end of the shell prompts where it informs me that my Kernel is not up to date (wireguard needs a specific kernel if so which one please) despite the fact I am running the latest version 4.19...v64

This has been added because many users downloaded Raspbian and run PiVPN without upgrading the system first, which caused many problems when installing wireguard.

> I am a beginner so how things work together can be tricky (PiVPN not like BerryBoot?

As far as I know, to multiboot, berryboot uses a custom kernel for which the kernel headers package (for WireGuard) is not selected in the install script.

> I decided that if nothing else PiVPN shouldn't be forcing apt-get because of the unstable downloads

apt-get leads to unstable packages? Some links?

**Comment by brantchyoga** [comment]
Here are some links to the new way to update and upgrade:
Official raspbian site suggested apt update itself -

https://www.raspberrypi.org/documentation/linux/software/apt.md

Difference you might ask between them -

https://itsfoss.com/apt-vs-apt-get-difference/

Don't believe it causes issues? Problems that arise when used on raspbian OS nowadays (many recent issues in the last year arose from this) -

https://www.raspberrypi.org/forums/viewtopic.php?f=91&t=245022
https://www.raspberrypi.org/forums/viewtopic.php?t=245073

Google search file system crashes with raspbain OS and apt-get.... Many official links pop up in regards to this known issue.

**Comment by brantchyoga** [comment]
Thank You for the Information on Berryboots kernel! Is there any resources out there that help  understand the differences and possibilities of putting different applications together. I stupidly though I could get linux applications to work together because their all linux right? uhhhh Just trying to cram knowledge and experiences down my throat. I love to read as well if you have a book in mind.

**Comment by orazioedoardo** [comment]
Those problems reported on the forum arose because people were running prerelease versions of Raspbian and apt-get does not change the release file when upgrading, which means you had to explicitly tell apt-get to move to stable (apt instead does it automatically). Also apt doesn’t like to be used in scripts.
