### ISSUE TITLE
[Support] curl: Failed to connect to raw.githubusercontent.com port 443

### ISSUE THREAD

**Issue by N0rWatch322** [pivpn/pivpn#1035]
Hello Everyone,     Ref: #449 

I have 2x raspberry pi 4b+ units running as Pi-Holes with Unbound DNS. I am attempting to install PiVPN but I cannot seem to progress past the first step on one of them:     
################:~ $ sudo curl -L https://install.pivpn.io | bash
         % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                                           Dload   Upload   Total   Spent    Left  Speed
      100   162  100      162    0        0         107        0  0:00:01  0:00:01 --:--:--   107
          0       0      0          0    0        0             0        0  --:--:--  0:00:02 --:--:--       0
       curl: (7) Failed to connect to raw.githubusercontent.com port 443: Connection refused
################:~ $ curl -L https://install.pivpn.io | bash
         % Total    % Received % Xferd  Average Speed    Time     Time     Time  Current
                                                           Dload    Upload   Total   Spent       Left    Speed
      100   162  100      162    0        0         294        0  0:00:01  0:00:01  --:--:--       107
          0       0      0          0    0        0             0        0  --:--:--  0:00:02   --:--:--           0
       curl: (7) Failed to connect to raw.githubusercontent.com port 443: Connection refused
################:~ $ pivpn add nopass
#-bash: pivpn: command not found
################:~ $ pivpn debug
-bash: pivpn: command not found
################:~ $ sudo iptables -t nat -S
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P POSTROUTING ACCEPT
-P OUTPUT ACCEPT
################:~ $ sudo iptables -S
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
################:~ $ sudo netstat -uanp | grep openvpn
################:~ $

I'm not sure how to progress, shy of doing a full reinstall of the Pi-Hole/Unbound unit.

**Comment by orazioedoardo** [comment]
It’s error on your side, curl tells you that github does not accept connections, which is not the case. Can you open https://install.pivpn.io on a different device on the same network?

**Comment by N0rWatch322** [comment]
So having tried the link, it takes a refresh or two, but it sees the corresponding file
