### ISSUE TITLE
[BUG] password produced on screen when adding user

### ISSUE THREAD

**Issue by lucserre** [pivpn/pivpn#1037]
## In raising this issue, I confirm the following:

- [x] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

**Describe the bug**
When adding a user with pivpn (pivpn -a) and specifying a password, that password is then displayed in plain text on the user screen. I believe this is not appropriate for security.

**To Reproduce**
1. Add a pivpn user the regular way, and specify a password.  ($ pivpn -a)

**Expected behavior**
When pivpn produces an output, I would expect the password to not be produced on the user's screen

**Desktop (please complete the following information):**
 - VPN Protocol
 - OS: raspbian
 - Version 1.9

**Comment by orazioedoardo** [comment]
Thanks, will have a look.

**Comment by lucserre** [comment]
Actually, even the latest version does the same thing.  I think it's easy_rsa that is the problem, or maybe pivpn interacting with easy_rsa in the wrong way or something like that. Why would easy_rsa show you the password on screen? I don't know.

**Comment by TinCanTech** [comment]
When `easyrsa` creates a client cert/key with a password that password is read from screen by `openssl`.  That password is not displayed on-screen.

**Comment by orazioedoardo** [comment]
I think this is an issue with expect feeding easyrsa with passwords.

**Comment by lucserre** [comment]
Ya - definitely happening right here:    
(in makeOVPN.sh)
expect "Enter PEM pass phrase" { send -- "${PASSWD}\r" }
expect "Verifying - Enter PEM pass phrase" { send -- "${PASSWD}\r" }

**Comment by orazioedoardo** [comment]
@lucserre Password is not shown for me, however I recall an expect script which did leak the text and solved adding a sleep before sending the text. Does it work for you?
```
expect "Enter PEM pass phrase" { sleep 0.1; send -- "${PASSWD}\r" }
expect "Verifying - Enter PEM pass phrase" { sleep 0.1; send -- "${PASSWD}\r" }
```

**Comment by lucserre** [comment]
@orazioedoardo  Success!  That did work.
What it looks like now for me.
```
Using SSL: openssl OpenSSL 1.1.0l  10 Sep 2019
Generating an EC private key
writing new private key to '/etc/openvpn/easy-rsa/pki/private/test2.key.r2eahiToya'
Enter PEM pass phrase:
Verifying - Enter PEM pass phrase:
-----
```

**Comment by jerrythiesen** [comment]
Reproduced. Screenshot below. Sorry, its so large. However, when adding:
```
expect "Enter PEM pass phrase" { sleep 0.1; send -- "${PASSWD}\r" }
expect "Verifying - Enter PEM pass phrase" { sleep 0.1; send -- "${PASSWD}\r" }
```
It does not display.

VPN Protocol
OS: raspbian
Version 1.9

![image](https://user-images.githubusercontent.com/36054829/82557851-7b769980-9b3a-11ea-94ab-4f958cd52fa1.png)

**Comment by lucserre** [comment]
@jerrythiesen It looks like that sreenshot shows that the passwords are being displayed in plain text on the screen, but you pasted code with the sleep 0.1 command included.  Can you confirm if your screenshot was taken with the original code or the sleep command added version of the code?

**Comment by orazioedoardo** [comment]
@jerrythiesen So, does the sleep hide the password or not?

**Comment by jerrythiesen** [comment]
@orazioedoardo - Passing sleep hides the password. Confirmed last night.
