### ISSUE TITLE
[Support] Install on LinuxMint 19.3

### ISSUE THREAD

**Issue by RileyKA** [pivpn/pivpn#1038]
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

### Have you searched for similar issues and solutions?
    (yes/no / which issues?)
yes

### Console output of      `curl -L install.pivpn.dev | bash`
```
  Invalid OS ├───────────────────────────┐
     │                                                                    │ 
     │ We have not been able to detect a supported OS.                    │ 
     │ Currently this installer supports Raspbian, Debian and Ubuntu.     │ 
     │ For more details, check our documentation at                       │ 
     │ https://github.com/pivpn/pivpn/wiki
```

### Console output of      `pivpn add` or `pivpn add nopass`
```
  Output Here
```

### Console output of      `pivpn debug`
```
  Output Here
```
### Have you taken any steps towards solving your issue?
```
  which?
```

**Comment by getwisp** [comment]
Please read the "Prerequisites" section in README.md.
Also, please read the output of the script.
Also, please understand what a feature request is.

If you feel so inclined, I'm sure you are very welcome to find out which packages are required in Linux Mint.

**Comment by 4s3ti** [comment]
answer here: https://github.com/pivpn/pivpn/pull/1040
