### ISSUE TITLE
[Support] Can't install Wireguard on rpi 4b raspbian

### ISSUE THREAD

**Issue by lucki1000** [pivpn/pivpn#1039]
Hi,
I have a rpi4b with 4GB ram and the latest raspbian, and if i do:
```
 curl -L https://install.pivpn.io | bash 
``` 
it breaks by installing Wireguard:
```
::: Checking for existing base files...
:::    Checking /etc/.pivpn is a repo... OK!
:::     Updating repo in /etc/.pivpn... [-] done!
::: Using VPN: WireGuard
::: Installing WireGuard from Debian package... 
::: WireGuard is already available in the repositories
:::    Checking for raspberrypi-kernel-headers... already installed!
:::    Checking for wireguard... not installed!
:::    Checking for wireguard-tools... already installed!
:::    Checking for wireguard-dkms... not installed!
:::    Checking for qrencode... already installed!
:::    Failed to install wireguard!
:::    Failed to install wireguard-dkms!
```

What i tried:
```
sudo apt dist-upgrade
sudo apt upgrade -y
sudo reboot
sudo rpi-update:
 *** Raspberry Pi firmware updater by Hexxeh, enhanced by AndrewS and Dom
 *** Performing self-update
 *** Relaunching after update
 *** Raspberry Pi firmware updater by Hexxeh, enhanced by AndrewS and Dom
 *** Your firmware is already up to date
```
OS Version:
```
pi@raspberrypi:~ $ uname -a
Linux raspberrypi 4.19.97-v8+ #1294 SMP PREEMPT Thu Jan 30 13:27:08 GMT 2020 aarch64 GNU/Linux
pi@raspberrypi:~ $ lsb_release -a
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
```
I have also tried to install PiVPN with wg in Ubuntu 20.04 arm64 only there is the option wireguard not offered to me.
Can anyone help me to install PiVPN with Wireguard?

**Comment by orazioedoardo** [comment]
What Raspbian image is this? I don't recall them having a 64 bit kernel (aarch64 in uname -a).

**Comment by lucki1000** [comment]
If you write:
```
arm_64bit=1
```
in you config.txt then you will get a arm v8 aarch64 kernel on the latest Raspbian Buster version, but you mean the problem is my Kernel?

**Comment by 4s3ti** [comment]
@lucki1000 because Wireguard runs on Kernel and requires kernel modules .. if you don't have the correct kernel .. pivpn will fail to install.

**Comment by lucki1000** [comment]
Okay thanks.

**Comment by albertobissacco** [comment]
i have the same problem and with "uname -a" i get:
`
Linux raspberrypi 5.4.40-v7+ #1316 SMP Tue May 12 13:04:54 BST 2020 armv7l GNU/Linux
`

**Comment by linareyne** [comment]
> @lucki1000 because Wireguard runs on Kernel and requires proper kernel modules and headers .. if you don't have the correct kernel .. pivpn will fail to install.

Raspberry Pi OS has a 64 bit beta, which will become the default Raspberry Pi OS. Do we have to wait until that point for PiVPN to work or something?
