### ISSUE TITLE
pivpn fails installing in Freenas Jail (freebsd)

### ISSUE THREAD

**Issue by krouter** [pivpn/pivpn#1042]
I understand pivpn is designed for rpi, but since its so good and stable..  i was hoping to install it on freenas jail to over come the 100mbs limit on pi3b.
Please help if it's a relatively easy fix.

I logged into freenas jail as 'root' and changed to bash shell by typing bash at the prompt.

Here is the error i got and dont know how to process further.

How can i fix this and use pivpn as the wireguard server that is meant to run inside freenas?

----====

[root@wireguardvpn /]# curl -L https://install.pivpn.io | bash

% Total % Received % Xferd Average Speed Time Time Time Current

Dload Upload Total Spent Left Speed

100 162 100 162 0 0 173 0 --:--:-- --:--:-- --:--:-- 173

100 80405 100 80405 0 0 54883 0 0:00:01 0:00:01 --:--:-- 54883

:::

::: You are root.

main: line 254: /etc/os-release: No such file or directory

main: line 258: VER_MAP: bad array subscript

main: line 302: whiptail: command not found

[root@wireguardvpn /]#

----====

**Comment by 4s3ti** [comment]
Sorry @krouter freenas is based on FreeBSD which is fundamentally different from Debian ... and would require us to develop a specific jail for it ... don't see us supporting it in any near future if ever ... 

if you want a wireguard server running on FreeBSD you will have to look for it elsewhere ...  

Colsing, feel free to re-open or comment if you wish :)
