### ISSUE TITLE
[Support] Wireguard bridge mode with external DHCP?

### ISSUE THREAD

**Issue by spookyrecharge** [pivpn/pivpn#1043]
Hi guys,

I'm wondering if it's possible to configure Wireguard in bridge mode and use external (router) DHCP server with a possibility to run in via part of PiVPN?

I have tried to do same thing on OpenVPN and it worked like a charm. But apparently configs aren't the same.

Thank you!

**Comment by orazioedoardo** [comment]
WireGuard does not support bridge mode.

**Comment by mr4lexndr** [comment]
Is there any way to see hostnames within home network while connecting through WireGuard from outside of the lan? I am using Raspberry pi as my VPN server. It is at home connected to lan. I would like to reach all devices connected to the same network, when connecting remotely through vpn. I can ping their IP’s but no hostnames are recognised. I use this for file sharing as well as for other services. I have tried resolving hostnames and dns is set to my router ip but it did not change anything.

**Comment by mr4lexndr** [comment]
> Hi guys,
> 
> I'm wondering if it's possible to configure Wireguard in bridge mode and use external (router) DHCP server with a possibility to run in via part of PiVPN?
> 
> I have tried to do same thing on OpenVPN and it worked like a charm. But apparently configs aren't the same.
> 
> Thank you!

How did you do it with OpenVPN?

**Comment by orazioedoardo** [comment]
Closing as per https://github.com/pivpn/pivpn/issues/1043#issuecomment-624516612
