### ISSUE TITLE
[BUG] The installation script fails with an error on line 971

### ISSUE THREAD

**Issue by massasan** [pivpn/pivpn#1044]
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*.
- [] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

The installation script fails with an error on line 971 and returns the following
Checking for existing base files...
:::    Checking /etc/.pivpn is a repo...:::  

  Cloning https://github.com/pivpn/pivpn.git into /etc/.pivpn...pivpn/auto_install/install.sh: 
  line 971: cd: /etc/.pivpn: No such file or directory

I apologize if I do something wrong.
I'm asking the question for the first time, and English is not my native language

**Comment by massasan** [comment]
I forgot to tell you, I'm trying to follow these instructions https://pimylifeup.com/raspberry-pi-vpn-server/    My problems start after step 8

**Comment by kobimx** [comment]
Same problem here
if i manually clone the repo into /etc/.pivpn the error changes to this

`::: Checking for existing base files...`

`:::    Checking /etc/.pivpn is a repo...:::`

`Updating repo in /etc/.pivpn...main: line 949: cd: /etc/.pivpn: No such file or directory`

**Comment by NovaViper** [comment]
I'm having the same issue

**Comment by kobimx** [comment]
Manually cloning the repo with
`sudo git clone https://github.com/pivpn/pivpn /etc/.pivpn` 
solves the issue for me

**Comment by orazioedoardo** [comment]
Is this issue specific to OctoPi? Can you rung the script like that and post the output? https://github.com/pivpn/pivpn/issues/521#issuecomment-420957752

**Comment by NovaViper** [comment]
Im not sure if the OP is using OctoPi, but the only way I could make it work for me was using 'sudo -i' and ran the command under a root user

**Comment by 4s3ti** [comment]
@orazioedoardo This is OctoPi Specific stuff .. 

Here: https://github.com/pivpn/pivpn/wiki#what-about-octopi

**Comment by orazioedoardo** [comment]
@4s3ti Oh, I always forget this.

**Comment by NovaViper** [comment]
@4s3ti I tried the steps in the wiki but I keep getting this ``::: Can't open options.conf
`` error

**Comment by orazioedoardo** [comment]
Closing as it seems a common issue with OctoPi that has a working workaround, reopen if you have the same error not on OctoPi.
