### ISSUE TITLE
[BUG] problem during pivpn -up

### ISSUE THREAD

**Issue by Darkmagister** [pivpn/pivpn#1045]
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

**Describe the bug**
i'm trying to update the pivpn script but it fail,
```
sudo pivpn -up
going do update PiVPN Scripts
Cloning into '/etc/.pivpn'...
remote: Enumerating objects: 40, done.
remote: Counting objects: 100% (40/40), done.
remote: Compressing objects: 100% (35/35), done.
remote: Total 2408 (delta 18), reused 15 (delta 2), pack-reused 2368
Receiving objects: 100% (2408/2408), 773.53 KiB | 712.00 KiB/s, done.
Resolving deltas: 100% (1359/1359), done.
cp: cannot stat '/etc/.pivpn/scripts/bash-completion': No such file or directory
PiVPN Scripts have been updated
```
the file that is searching is not here /etc/.pivpn/scripts/bash-completion
but here i think /etc/.pivpn/scripts/openvpn/bash-completion

but i don't know what to do
also it says upda completed, is that true?

i'm using a raspbian lite 10.3 on a raspberry pi 3 b+

**Comment by chipsnblip** [comment]
does it work if you omit sudo?  asking because i don't use sudo for pivpn and everything works as intended

**Comment by Darkmagister** [comment]
without sudo i get some permission error

**Comment by 4s3ti** [comment]
Most likely not a bug .. but your vpn was installed using an older version of pivpn script ... Check here:
should fix your issue 

https://github.com/pivpn/pivpn/issues/916

**Comment by Darkmagister** [comment]
thanks, i didn't see that, sorry.
