### ISSUE TITLE
No external connection

### ISSUE THREAD

**Issue by jpras8000** [pivpn/pivpn#105]
installed:
2016-09-23-raspbian-jessie
curl -L https://install.pivpn.io | bash
Forwarded port 1194 on my router to my PIVPN
Created user keys (.ovpn)

When I am trying to connect via an external connection (internet) I am not able to connect to my PIVPN.
I am able to connect to my PIVPN via my internal network on my external IP. When I disable port 1194 on my router I am also not able to connect anymore from internal.

What can here be the case that I am not able to connect from the internet?

I also opened and forwarded port 22 from external to my PIVPN. This also does not work from the internet. Can it be a routing or firewall issue on the Raspberry?

**Comment by StephenKinger** [comment]
You have to set up a NAT IP/PORT forward on your router.
Default configuration of iptables allows you to access to a service from internet if you have set a correct forward on your router.
For example, try to forward the port 22 to your raspberry port 22 and try to connect to SSH.
When you are able to open a ssh connection from internet, add the 1194 UDP port forward to your 1194 port of your raspi and delete ssh forward.

**Comment by jpras8000** [comment]
I already tried that. Did not work. I forewarded port 80 to my ip-cam and works fine via internet......

**Comment by 0-kaladin** [comment]
This seems to be networking issues on your end.  just have to make sure the remote xxxx option in your client is accessible from the internet.  since you can connect from internal network we know pivpn itself is setup correctly.
