### ISSUE TITLE
[BUG] pivpn -r does not delete wireguard clients

### ISSUE THREAD

**Issue by ksurl** [pivpn/pivpn#1050]
## In raising this issue, I confirm the following: 

- [x] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

**Describe the bug**
when running command to remove clients for a wireguard install, it does nothing
**To Reproduce**
1. run `sudo pivpn -r`
2. it lists the current clients
3. type the client name you want e.g. test2
4. it exits after confirming
5. run `pivpn list`
6. confirm client is still listed, config file still in `/etc/wireguard/configs`, keys still in `/etc/wireguard/keys` and peer still listed in `/etc/wireguard/wg0.conf`

**Expected behavior**
client config, client public and private keys deleted, client removed from peers in `/etc/wireguard/wg0.conf ` and the client list in `/etc/wireguard/configs/clients.txt`

**Server:**
 - VPN: Wireguard
 - OS: Ubuntu 18.04.4 vm
 - Version: latest as of 5-16-2020

**Comment by shelleycat485** [comment]
Cannot reproduce on new AWS machine instance, ubuntu 18.04.1 nor 18.04.4.  Did installation, add client, remove client; repeated; updated instance version to 18.04.4, repeated add client then removed; rebooted, added client, removed client ok.  Repeated with add one, add another, remove first. Repeated again with two clients added, then one removed this time using all commands as sudo pivpn.  Confirmed in last case only that the keys and configs.txt were as expected.
Sorry but I cannot see the fault.

**Comment by ksurl** [comment]
I just ran it again and confirmed it still does this. is there anything I can check? this was a fresh install. all files in /etc/wireguard are owned by root:root.

**Comment by ksurl** [comment]
Debug output:
<details>
 <summary>(click to expand)</summary>
    ::::		[4mPiVPN debug[0m		 ::::
    =============================================
    ::::		[4mLatest commit[0m		 ::::
    commit 4e8d4dfd8ef01e49f3137d5fc5a2afa14a465e47
    Author: Orazio <orazioedoardo@users.noreply.github.com>
    Date:   Tue Apr 7 13:45:43 2020 +0200

        Merge pull request #1000 from psgoundar/pivpn
        
        Updated listOVPN to Include Expiration Dates
    =============================================
    ::::	    [4mInstallation settings[0m    	 ::::
    PLAT=Ubuntu
    OSCN=bionic
    USING_UFW=0
    IPv4dev=ens18
    install_user=USER
    install_home=/home/USER
    VPN=wireguard
    pivpnPORT=51280
    pivpnDNS1=10.0.1.1
    pivpnDNS2=
    pivpnHOST=REDACTED
    INPUT_CHAIN_EDITED=0
    FORWARD_CHAIN_EDITED=0
    pivpnPROTO=udp
    pivpnDEV=wg0
    pivpnNET=10.6.0.0
    subnetClass=24
    UNATTUPG=1
    INSTALLED_PACKAGES=(iptables-persistent qrencode)
    =============================================
    ::::  [4mServer configuration shown below[0m   ::::
    [Interface]
    PrivateKey = server_priv
    Address = 10.6.0.1/24
    ListenPort = 51280

    # begin client1
    [Peer]
    PublicKey = client1_pub
    PresharedKey = psk
    AllowedIPs = 10.6.0.2/32
    # end client1
    # begin client2
    [Peer]
    PublicKey = client2_pub
    PresharedKey = psk
    AllowedIPs = 10.6.0.3/32
    # end client2
    # begin test3
    [Peer]
    PublicKey = test3_pub
    PresharedKey = psk
    AllowedIPs = 10.6.0.4/32
    # end test3
    =============================================
    ::::  [4mClient configuration shown below[0m   ::::
    [Interface]
    PrivateKey = client1_priv
    Address = 10.6.0.2/24
    DNS = 10.0.1.1

    [Peer]
    PublicKey = server_pub
    PresharedKey = psk
    Endpoint = REDACTED:51280
    AllowedIPs = 0.0.0.0/0, ::0/0
    =============================================
    :::: 	[4mRecursive list of files in[0m	 ::::
    ::::	[4m/etc/wireguard shown below[0m	 ::::
    /etc/wireguard:
    configs
    keys
    wg0.conf

    /etc/wireguard/configs:
    clients.txt
    client1.conf
    client2.conf
    test3.conf

    /etc/wireguard/keys:
    psk
    client1_priv
    client1_pub
    server_priv
    server_pub
    client2_priv
    client2_pub
    test3_priv
    test3_pub
    =============================================
    ::::		[4mSelf check[0m		 ::::
    :: [OK] IP forwarding is enabled
    :: [OK] Iptables MASQUERADE rule set
    :: [OK] WireGuard is running
    :: [OK] WireGuard is enabled (it will automatically start on reboot)
    :: [OK] WireGuard is listening on port 51280/udp
    =============================================
    :::: Having trouble connecting? Take a look at the FAQ:
    :::: [1mhttps://github.com/pivpn/pivpn/wiki/FAQ[0m
    =============================================
    :::: [1mWARNING[0m: This script should have automatically masked sensitive       ::::
    :::: information, however, still make sure that [4mPrivateKey[0m, [4mPublicKey[0m      ::::
    :::: and [4mPresharedKey[0m are masked before reporting an issue. An example key ::::
    :::: that you should NOT see in this log looks like this:                  ::::
    :::: YIAoJVsdIeyvXfGGDDadHh6AxsMRymZTnnzZoAb9cxRe                          ::::
    =============================================
    ::::		[4mDebug complete[0m		 ::::

</details>

**Comment by shelleycat485** [comment]
Is your user really called USER?

**Comment by orazioedoardo** [comment]
Show the output of `pivpn -r`.

**Comment by ksurl** [comment]
no I redacted for privacy. 

```
::  Client list  ::
• client1
• client2
• test3
Please enter the Name of the Client to be removed from the list above: test3
Do you really want to delete test3? [Y/n]
```

**Comment by orazioedoardo** [comment]
> no I redacted for privacy. 

Fine, but does the output stop there?

**Comment by ksurl** [comment]
everything is there. the only thing I changed was username and device client names listed. I could try a fresh reinstall. I don't see any reason it doesn't work...even running removeCONF.sh with the client name as argument yields same result since it's just calling that script from the pivpn script.

**Comment by shelleycat485** [comment]
I asked a couple of days ago, from your debug output, is your user (who installed the pivpn) really called USER.  Its seems an unusual name for a real user, and it it is not USER, your setupVars.conf is wrong.  On a machine of mine the relevant lines are
install_user=pi
install_home=/home/pi

**Comment by toad77** [comment]
I am also having this problem.  The client still appears in the  `/etc/wireguard/configs/clients.txt`.

```
pi@demodog:~/configs $ pivpn -r
::  Client list  ::
• todd
• todd-split
• todd-full
Please enter the Name of the Client to be removed from the list above: todd
sha256sum: configs/todd.conf: No such file or directory
Do you really want to delete todd? [Y/n] Y
sed: -e expression #1, char 51: unterminated address regex
::: Updated server config
rm: cannot remove 'configs/todd.conf': No such file or directory
::: Client config for todd removed
rm: cannot remove 'keys/todd_priv': No such file or directory
rm: cannot remove 'keys/todd_pub': No such file or directory
::: Client Keys for todd removed
::: Successfully deleted todd
sed: -e expression #1, char 10: unterminated address regex
::: Updated hosts file for Pi-hole
::: WireGuard restarted
```

**Comment by ksurl** [comment]
yes it is NOT actually USER. I said I redacted for privacy. let's call it USER1 then if you insist.

**Comment by toad77** [comment]
@ksurl Yes, that's correct.  I should have clarified.  The first time through, -r did remove the files.  However, I still see the 'todd' client when I run -r again and when I run -c.

**Comment by shelleycat485** [comment]
@ksurl Sorry, no ideas now except I would now go and put print statements in every line of the uninstall script and see if it is getting to the end.  You should at least start getting error messages as per toad77

**Comment by orazioedoardo** [comment]
@toad77 I found the issue. The client still appeared in `client.txt` because the grep command used to determine which line to remove returned multiple results when you had multiple clients with similar names like `todd`, `todd-2`, `3-todd`, so the sed command that actually removed the line didn't find the match.

**Comment by toad77** [comment]
@orazioedoardo Excellent!  Thank you for your hard work in tracking that down.

**Comment by orazioedoardo** [comment]
> @orazioedoardo Excellent! Thank you for your hard work in tracking that down.

Thanks. Full disclosure though, I only checked the removal script today.
