### ISSUE TITLE
[BUG] Documentation error in FAQ wiki

### ISSUE THREAD

**Issue by ChrisCrossCrash** [pivpn/pivpn#1053]
## In raising this issue, I confirm the following: 

- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting can be *is* directly related to the pivpn installer script.
(Ok, well not exactly, but it's about the documentation for the script.)
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

**Describe the bug**
Under the section [How Can I Migrate my configs to another PiVPN Instance?](https://github.com/pivpn/pivpn/wiki/WireGuard#how-can-i-migrate-my-configs-to-another-pivpn-instance) of the Wireguard FAQ on step three, it says:

> Copy the extracted content: sudo cp -r etc/wireguard /etc/wireguard

but it should say this:

> Copy the extracted content: sudo cp -r etc/wireguard /etc

otherwise, you'll end up with this:
```
/etc/wireguard/
├── configs
├── keys
└── wireguard/
        ├── configs
        └── keys
```

**Update:** I just checked, and the same issue exists for the OpenVPN FAQ.

Also, `pivpn -bk` provides a link to a section in the documentation that no longer exists:
```
ubuntu@ssh:~$ pivpn -bk
Backup crated to /home/ubuntu/pivpnbackup/20200522-101248-pivpnwgbackup.tgz
To restore the backup, follow instructions at:
https://github.com/pivpn/pivpn/wiki/FAQ#how-can-i-migrate-my-configs-to-another-pivpn-instance
```

Perhaps this section could be updated in the general FAQ, with links to the new protocol-specific sections, like this:

### How Can I Migrate my configs to another PiVPN Instance?
Please see the protocol-specific FAQ:
- [OpenVPN](https://github.com/pivpn/pivpn/wiki/OpenVPN#how-can-i-migrate-my-configs-to-another-pivpn-instance)
- [WireGuard](https://github.com/pivpn/pivpn/wiki/WireGuard#how-can-i-migrate-my-configs-to-another-pivpn-instance)

**Comment by orazioedoardo** [comment]
Wiki commands changed and [links](https://github.com/pivpn/pivpn/commit/427c484cacf32c938574e58486773b69b9e2b386#diff-179da8459e84bc41a473e2921dce8b57L56-R87) as well.

**Comment by Tralapo** [comment]
It might me an error from my side, but it seems there's no documentation about restoring a backup anymore?
The new link that was created in this issue doesn't work anymore.
