### ISSUE TITLE
cant begin installation

### ISSUE THREAD

**Issue by dansimpson1990** [pivpn/pivpn#106]
Hi guys, I'm a bit of a noob but i can begin the installation of pivpn which i was able to before.
here is the terminal response:

pi@raspberrypi:~ $ curl -L https://install.pivpn.io | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (60) SSL certificate problem: certificate is not yet valid
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.

**Comment by redfast00** [comment]
It seems the time on your Pi is wrong. Can you give me the result of `date`?

**Comment by redfast00** [comment]
Closing this since this is not PiVPN related.
