### ISSUE TITLE
[Support] <Smartphone bypass partly Wireguard VPN?>

### ISSUE THREAD

**Issue by ovz93br43v7** [pivpn/pivpn#1061]
In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [Not 100% sure!] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

No failed install.

### Issue
I have set up Pihole and PiVPN (wireguard). Installation was no problem.
Two android 10 smartphones were connected (barcode scan), test of "Packet capture" https://github.com/pivpn/pivpn/wiki/FAQ was successful. I can also see in the wireguard app on my smartphone that XX MB were sent/received and I can see in Pihole that the smartphones requesting certain domains which are passed or blocked.
But I found out that that some packet bypass somehow the wireguard VPN because I can access using mobile data some domains which are normally blocked by Pihole and I can't see in Pihole that the smartphone is requesting this domain. When I'm Inside my home WLAN this domains are blocked. 
My only idea was that probably IPv6 requests somehow bypass the VPN connection?

### Have you searched for similar issues and solutions?
    (yes/no / which issues?)
Yes but don't find anything matching to my issue.

### Console output of      `curl -L install.pivpn.dev | bash`
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     5  100     5    0     0     26      0 --:--:-- --:--:-- --:--:--    26
100   162  100   162    0     0    580      0 --:--:-- --:--:-- --:--:--   580
100 80405  100 80405    0     0   160k      0 --:--:-- --:--:-- --:--:-- 1670k
:::
::: sudo will be used for the install.
::: Cancel selected. Exiting
```
--> existing install detected

### Console output of      `pivpn add` or `pivpn add nopass`
pivpn add
```
Enter a Name for the Client:
```
pivpn add nopass
```
::: Error: Got an unexpected argument 'nopass'
::: Create a client conf profile
:::
::: Usage: pivpn <-a|add> [-n|--name <arg>] [-h|--help]
:::
::: Commands:
:::  [none]               Interactive mode
:::  -n,--name            Name for the Client (default: 'raspberrypi')
:::  -h,--help            Show this help dialog
```

### Console output of      `pivpn debug`
```
::::		PiVPN debug		 ::::
=============================================
::::		Latest commit		 ::::
commit 4e8d4dfd8ef01e49f3137d5fc5a2afa14a465e47 (HEAD -> master, origin/master, origin/HEAD)
Merge: f045e39 4039a0d
Author: Orazio <orazioedoardo@users.noreply.github.com>
Date:   Tue Apr 7 13:45:43 2020 +0200

    Merge pull request #1000 from psgoundar/pivpn
    
    Updated listOVPN to Include Expiration Dates
=============================================
::::	    Installation settings    	 ::::
PLAT=Raspbian
OSCN=buster
USING_UFW=0
IPv4dev=eth0
dhcpReserv=1
IPv4addr=xxx.xxx.xxx.xxx/xxx
IPv4gw=xxx.xxx.xxx.xxx
install_user=xxx
install_home=/home/xxx
VPN=wireguard
pivpnPORT=51820
pivpnDNS1=xxx.xxx.xxx.xxx
pivpnDNS2=
pivpnHOST=REDACTED
INPUT_CHAIN_EDITED=0
FORWARD_CHAIN_EDITED=0
pivpnPROTO=udp
pivpnDEV=wg0
pivpnNET=xxx.xxx.xxx.xxx
subnetClass=24
UNATTUPG=1
INSTALLED_PACKAGES=(raspberrypi-kernel-headers wireguard wireguard-tools wireguard-dkms qrencode)
=============================================
::::  Server configuration shown below   ::::
[Interface]
PrivateKey = server_priv
Address = xxx.xxx.xxx.xxx/xxx
ListenPort = 51820
# begin d_smartphone
[Peer]
PublicKey = d_smartphone_pub
PresharedKey = psk
AllowedIPs = xxx.xxx.xxx.xxx/xxx, ::0/0
# end d_smartphone
# begin m_smartphone
[Peer]
PublicKey = m_smartphone_pub
PresharedKey = psk
AllowedIPs = xxx.xxx.xxx.xxx/xxx, ::0/0
# end m_smartphone
=============================================
::::  Client configuration shown below   ::::
[Interface]
PrivateKey = d_smartphone_priv
Address = xxx.xxx.xxx.xxx/xxx
DNS = xxx.xxx.xxx.xxx

[Peer]
PublicKey = server_pub
PresharedKey = psk
Endpoint = REDACTED:51820
AllowedIPs = 0.0.0.0/0, ::0/0
=============================================
:::: 	Recursive list of files in	 ::::
::::	[4m/etc/wireguard shown below	 ::::
/etc/wireguard:
configs  keys  wg0.conf

/etc/wireguard/configs:
clients.txt  d_smartphone.conf	m_smartphone.conf

/etc/wireguard/keys:
d_smartphone_priv  d_smartphone_pub  m_smartphone_priv	m_smartphone_pub  psk  server_priv  server_pub
=============================================
::::		Self check		 ::::
:: [OK] IP forwarding is enabled
:: [OK] Iptables MASQUERADE rule set
:: [OK] WireGuard is running
:: [OK] WireGuard is enabled (it will automatically start on reboot)
:: [OK] WireGuard is listening on port 51820/udp
=============================================
:::: Having trouble connecting? Take a look at the FAQ:
:::: https://github.com/pivpn/pivpn/wiki/FAQ
=============================================
:::: WARNING: This script should have automatically masked sensitive       ::::
:::: information, however, still make sure that PrivateKey, PublicKey      ::::
:::: and PresharedKey are masked before reporting an issue. An example key ::::
:::: that you should NOT see in this log looks like this:                  ::::
:::: YIAoJVsdIeyvXfGGDDadHh6AxsMRymZTnnzZoAb9cxRe                          ::::
=============================================
::::		Debug complete		 ::::

```
### Have you taken any steps towards solving your issue?
```
1. I have added ", ::0/0" to allowed IPs for clients (was missing) as explained here https://www.reddit.com/r/WireGuard/comments/b0m5g2/ipv6_leaks_psa_for_anyone_here_using_wireguard_to/

2. Activate "permanent VPN" and "block connections without VPN" on Android smartphones.

But both changed nothing to my problem.

Because I'm not 100% sure whether this is related to PiVPN intaller script I created here an addtional request: https://www.reddit.com/r/WireGuard/comments/gsqb3l/wireguard_successfully_installed_with_help_of/
```

**Comment by orazioedoardo** [comment]
> 1. I have added ", ::0/0" to allowed IPs for clients (was missing) as explained here https://www.reddit.com/r/WireGuard/comments/b0m5g2/ipv6_leaks_psa_for_anyone_here_using_wireguard_to/

True but you need that in the client config (it's already there since this commit https://github.com/pivpn/pivpn/commit/1352ccf9a3d7c6379e0b205be73558c7e3bd3ef4), not the server config.

> But I found out that that some packet bypass somehow the wireguard VPN because I can access using mobile data some domains which are normally blocked by Pihole and I can't see in Pihole that the smartphone is requesting this domain. When I'm Inside my home WLAN this domains are blocked.
My only idea was that probably IPv6 requests somehow bypass the VPN connection?

Well, with allowedips 0.0.0.0/0, ::0/0 the client should tunnel everything through the VPN. There isn't much you can change, maybe when you turn on the VPN the client has some cached dns responses so it doesn't ask pihole, bypassing the adblock?

To get a better insight into this you should try on a pc with wireshark or tcpdump and actually see which traffic goes where.

**Comment by ovz93br43v7** [comment]
Thanks for your answer. I was also thinking about old cache, but why only with mobile data and not during Wi-Fi use?

Today I made some additional trails with the both smartphones, and until now it seems to be possible to bypass the VPN only for apps inside the Android work profile. I can access with the browser inside the work profile domains which are blocked by regex filters of pihole but only during using mobile data connection. With Wi-Fi all requests of the work profile are blocked by Pihole.
Same domains on same device using the browser inside the private profile are blocked also during using mobile data connection. 

I searched through the internet but don't find anything useful until now, according what I read the VPN should be used for all apps. There is no additional option so separately activate this for the work profile. I already activate "permanent VPN" and "block connections without VPN". 
Probably the work profile provider app (shelter) could cause this, but why only during mobile data connection?!? :-/

**Comment by orazioedoardo** [comment]
> Thanks for your answer. I was also thinking about old cache, but why only with mobile data and not during Wi-Fi use?

Because on wifi the cached response is from pihole, which is a null response, while on mobile you get the unblocked response from you isp’s dns.

> Same domains on same device using the browser inside the private profile are blocked also during using mobile data connection.

Seems related to your phone configuration then.

**Comment by ovz93br43v7** [comment]
> Seems related to your phone configuration then.
I agree.

**Comment by ovz93br43v7** [comment]
Just if someone have also trouble with that. You have to clone Wireguard in your work profile of your phone. And set up a additional client for this work profile.

At the moment it still don't work for me, if I connect my work profile with any wireguard profile my hole internet in the work profile is broken. I'm still searching for a solution.
