### ISSUE TITLE
[BUG] It's not compatible with Linux Mint

### ISSUE THREAD

**Issue by marcosmartingm** [pivpn/pivpn#1062]
Linux Mint is based in Ubuntu and i can not install it

**Comment by orazioedoardo** [comment]
Duplicate of https://github.com/pivpn/pivpn/pull/1040. There you can see why it's not officially supported even though it should work ([here](https://github.com/pivpn/pivpn/pull/1040/files) you can see what to change to make the installer accept linux mint).
