### ISSUE TITLE
[FR] <The New Namespace Solution>

### ISSUE THREAD

**Issue by krouter** [pivpn/pivpn#1063]
**Is your feature request related to a problem? Please describe.**
Current wg server has a frequent outage of eth0 related switch but wlan0 is always on. but eth0 is preferred due to it's gigabit card.
The wg is setup with default iptables postrouting rules defaulted to eth0 since its a solid gigabit router. when eth0 is down, people can connect to wlan0 by changing the client endpoint.

**Describe the solution you'd like**
leverage the suggested namespace solution and created a hybrid/unified solution that is agnostic to both eth0 and wlan0 and auto handle the routings.
see ref: https://www.wireguard.com/netns/#sample-script

**Describe alternatives you've considered**
none

**Additional context**

**Comment by orazioedoardo** [comment]
This seems to be useful on the client, not on the server, isn't it?

**Comment by krouter** [comment]
Server. Incase eth0 is down while wg0 is still running, then the routing table should update to wlan0 as fail over. Since the server is connected to both Lan and wifi at all times.
Also, periodically it can check and fall back on to eth0 once it is back up. Hope this helps.

**Comment by orazioedoardo** [comment]
> Server. Incase eth0 is down while wg0 is still running, then the routing table should update to wlan0 as fail over. Since the server is connected to both Lan and wifi at all times.
Also, periodically it can check and fall back on to eth0 once it is back up. Hope this helps.

Ok, but it doesn't seem the solution proposed on the website. It shows how to "merge" the two physical interfaces into a wireguard interface so that traffic is redirected to the encrypted tunnel regardless of the working physical interface, so you can force all traffic through wireguard without setting routing tables (because you only have that wg interface available).

**Comment by krouter** [comment]
You are correct. I got mixed up and tried to state the problem and the initial suggested solution. Eventually while scouring the web, found the above solution and thought it would be elegant and perfect. No need for monkeying around with IP routes or any...
Sounded, simple, clean and neat.

**Comment by orazioedoardo** [comment]
So I guess this can be closed. Reopen if I'm mistaken.

**Comment by krouter** [comment]
My understanding is that pivpn software installed on the server could possibly create the name space solution (fusing eth0 and wlan0) as part of the installation steps while setting up the wireguard configuration and creating the wg0.conf setup. Pls correct me if I'm wrong in expecting this as a possible feature or capability.

**Comment by orazioedoardo** [comment]
> My understanding is that pivpn software installed on the server could possibly create the name space solution (fusing eth0 and wlan0)

Fusing eth0 and wlan0 into what? Definitely not wg0, with a single VPN interface, how can the client connect to the raspberry?

> Pls correct me if I'm wrong in expecting this as a possible feature or capability.

I'm not sure, if you have an idea, please explain the steps.
