### ISSUE TITLE
[Support] <error pivpn -a>

### ISSUE THREAD

**Issue by manulpz** [pivpn/pivpn#1066]
hi, execute pivpn -a nopass but have error. i have 5 users created older.

Enter a Name for the Client:  user06
How many days should the certificate last?  1080
    invalid section len 108, max remaining 44
    invalid subsection length 268435554, max allowed 34
    invalid section len 108, max remaining 44
    invalid subsection length 268435554, max allowed 34
expect: error while loading shared libraries: libexpect.so.5.45: cannot open shared object file: No such file or directory
[ERROR]: Client Public Key Certificate not found: user06.crt

any idea, thanks.

**Comment by orazioedoardo** [comment]
> expect: error while loading shared libraries: libexpect.so.5.45: cannot open shared object file: No such file or directory

Closing as not following the issue template. By the way, this is an error with your system, not pivpn, possibly your sd card.
