### ISSUE TITLE
[FR] Automatic port forwarding / UPnP

### ISSUE THREAD

**Issue by Anuskuss** [pivpn/pivpn#1068]
**Is your feature request related to a problem? Please describe.**
First of all, thank you for your work. I've never used any VPN server before and the installation is pretty easy. What I missing though to make this perfect would be some form of automatic port forwarding on my router.

**Describe the solution you'd like**
Maybe [linux-igd](https://packages.debian.org/stretch/linux-igd). See [this guide](https://hackviking.com/2016/03/19/pi-make-a-vpn-gateway-with-upnp-port-forwarding/). I haven't personally tested it yet because I'm awaiting your input first.

**Describe alternatives you've considered**
systemd/cron

**Additional context**
Pros:
- Make the setup even easier
- Better security by opening/closing the port when the interface ups/downs
- Not forced to use static IP/DHCP reservations

Cons:
- Not every router supports UPnP

**Comment by orazioedoardo** [comment]
UPnP is useful for applications that frequently change the forwarded port and are not open all the time, like peer to peer programs. However PiVPN installs a server, which you probably always keep running, I don't think people disable the VPN or delete the forwarding rule when they don't need the VPN for few hours. Static IP is still required as many users use the Raspberry Pi as DNS server too. I think adding support for UPnP would require moderate testing for automating something you do just once in a while.

P.S. Also UPnP is infamously known for not being very secure as it requires no authentication and has suffered from many vulnerabilities like responding to commands from the internet.

**Comment by Anuskuss** [comment]
While I agree with you here, would it really hurt to offer it? Let the user choose, and warn them about the (potential) caveats. Maybe even default to no. For me it would certainly be useful since it's a set-and-done deal and I feel like my server has more control over the port; it can even be changed automagically if I ever want another port for whatever reason.
Anyway, I will test the guide to see if it even works on my setup but I'll leave this issue open in case someone else wants to add something to this.

**Comment by Anuskuss** [comment]
Ok, I've managed to get it to work. If anyone wants this as well (WireGuard only) here is what you have to do:

1. Install miniupnpc
```
sudo apt install miniupnpc
```
2. Open `/lib/systemd/system/wg-quick@.service` and paste this under `ExecStop`
```
ExecStartPost=/usr/bin/upnpc -e WireGuard -r 51280 UDP
ExecStopPost=/usr/bin/upnpc -d 51280 UDP
```
3. Restart the service
```
sudo systemctl daemon-reload
sudo systemctl restart wg-quick@wg0.service
```

**Comment by Anuskuss** [comment]
Ok, I've managed to get it to work. If anyone wants this as well (WireGuard only) here is what you have to do:

1. Install miniupnpc
```
sudo apt install miniupnpc
```
2. Open `/lib/systemd/system/wg-quick@.service` and paste this under `ExecStop`
```
ExecStartPost=/usr/bin/upnpc -e WireGuard -r 51820 UDP
ExecStopPost=/usr/bin/upnpc -d 51820 UDP
```
3. Restart the service
```
sudo systemctl daemon-reload
sudo systemctl restart wg-quick@wg0.service
```

**Comment by orazioedoardo** [comment]
Usually you don't want to modify the upstream systemd unit, otherwise you loose those changes when the package is updated (`wg-quick` in this case). Instead, use `systemctl edit wg-quick@.service` to create an override:

```
[Service]
ExecStartPost=[...]
ExecStopPost=[...]
```

It should work for OpenVPN as well.

> While I agree with you here, would it really hurt to offer it? Let the user choose, and warn them about the (potential) caveats. Maybe even default to no. For me it would certainly be useful since it's a set-and-done deal and I feel like my server has more control over the port; it can even be changed automagically if I ever want another port for whatever reason.

Ok but as expected, problems are never so easy, here's a list of things to check when implementing this:

- Check if the command worked (not the exit status but whether the port forwarding was added or not). I think this is important: The added value of UPnP is that we can enable port forwarding without the user having to fiddle with the router configuration, if we can't be sure whether it worked or not the user would still have to check the router.
- Check if you need port forwarding, for example on a cloud provider you don't, not sure about AWS though (I think, they should provide a public IP address).
- Check if UPnP is available.

**Comment by Anuskuss** [comment]
>  Instead, use `systemctl edit wg-quick@.service` to create an override:

TIL.

> Check if UPnP is available.

So unfortunately I can't turn off UPnP on my router (talk about security right) but I can give you the expected output.

1. Ask the user _Do you want UPnP?_
2. If yes, install `miniupnpc`. We could probably check if there is an UPnP device beforehand by scanning the network but that seems a little bit excessive and `miniupnpc` is a light package anyway.
3. Run `upnpc -P` (*Get Presentation url*)
```
upnpc : miniupnpc library test client, version 2.1.
 (c) 2005-2018 Thomas Bernard.
Go to http://miniupnp.free.fr/ or https://miniupnp.tuxfamily.org/
for more information.
List of UPNP devices found on the network :
 desc: http://192.168.0.1:49152/IGDdevicedesc_brlan0.xml
 st: urn:schemas-upnp-org:device:InternetGatewayDevice:1

Found valid IGD : http://192.168.0.1:49152/upnp/control/WANIPConnection0
Local LAN ip address : 192.168.0.6
Presentation URL found:
            http://192.168.0.1/
```
Then regex search for `^Found valid IGD`, `^Presentation URL found:\n.+\n` or maybe check for *No Presentation URL found* (I don't know what it would say in that case but maybe your router is more capable so you can figure it out).

4. If found continue, else purge `miniupnpc`
5. Add the custom overwrite with custom name `-e (OpenVPN|WireGuard)` and custom `-r ${PORT} UDP`
6. Check `upnpc -l` (*List redirections*)
```
upnpc : miniupnpc library test client, version 2.1.
 (c) 2005-2018 Thomas Bernard.
Go to http://miniupnp.free.fr/ or https://miniupnp.tuxfamily.org/
for more information.
List of UPNP devices found on the network :
 desc: http://192.168.0.1:49152/IGDdevicedesc_brlan0.xml
 st: urn:schemas-upnp-org:device:InternetGatewayDevice:1

Found valid IGD : http://192.168.0.1:49152/upnp/control/WANIPConnection0
Local LAN ip address : 192.168.0.6
Connection Type : IP_Routed
Status : Connected, uptime=0s, LastConnectionError : ERROR_NONE
MaxBitRateDown : 100000000 bps (100.0 Mbps)   MaxBitRateUp 100000000 bps (100.0                                                                                                                                Mbps)
ExternalIPAddress = ###.###.###.###
 i protocol exPort->inAddr:inPort description remoteHost leaseTime
 0 TCP 29942->192.168.0.6:32400 'Plex Media Server' '' 457200
 1 UDP 51820->192.168.0.6:51820 'WireGuard' '' 604800
GetGenericPortMappingEntry() returned 713 (SpecifiedArrayIndexInvalid)
```
Check with `^ \d+ UDP ${PORT}->${IP}:${PORT}`.

7. Profit

**Comment by Anuskuss** [comment]
>  Instead, use `systemctl edit wg-quick@.service` to create an override:

TIL.

> Check if UPnP is available.

So unfortunately I can't turn off UPnP on my router (talk about security right) but I can give you the expected output.

1. Ask the user _Do you want UPnP?_
2. If yes, install `miniupnpc`. We could probably check if there is an UPnP device beforehand by scanning the network but that seems a little bit excessive and `miniupnpc` is a light package anyway.
3. Run `upnpc -P` (*Get Presentation url*)
```
upnpc : miniupnpc library test client, version 2.1.
 (c) 2005-2018 Thomas Bernard.
Go to http://miniupnp.free.fr/ or https://miniupnp.tuxfamily.org/
for more information.
List of UPNP devices found on the network :
 desc: http://192.168.0.1:49152/IGDdevicedesc_brlan0.xml
 st: urn:schemas-upnp-org:device:InternetGatewayDevice:1

Found valid IGD : http://192.168.0.1:49152/upnp/control/WANIPConnection0
Local LAN ip address : 192.168.0.6
Presentation URL found:
            http://192.168.0.1/
```
Then regex search for `^Found valid IGD`, `^Presentation URL found:\n.+\n` or maybe check for *No Presentation URL found* (I don't know what it would say in that case but maybe your router is more capable so you can figure it out).

4. If found continue, else purge `miniupnpc`
5. Add the custom override with custom name `-e (OpenVPN|WireGuard)` and custom `-r ${PORT} UDP`
6. Check `upnpc -l` (*List redirections*)
```
upnpc : miniupnpc library test client, version 2.1.
 (c) 2005-2018 Thomas Bernard.
Go to http://miniupnp.free.fr/ or https://miniupnp.tuxfamily.org/
for more information.
List of UPNP devices found on the network :
 desc: http://192.168.0.1:49152/IGDdevicedesc_brlan0.xml
 st: urn:schemas-upnp-org:device:InternetGatewayDevice:1

Found valid IGD : http://192.168.0.1:49152/upnp/control/WANIPConnection0
Local LAN ip address : 192.168.0.6
Connection Type : IP_Routed
Status : Connected, uptime=0s, LastConnectionError : ERROR_NONE
MaxBitRateDown : 100000000 bps (100.0 Mbps)   MaxBitRateUp 100000000 bps (100.0                                                                                                                                Mbps)
ExternalIPAddress = ###.###.###.###
 i protocol exPort->inAddr:inPort description remoteHost leaseTime
 0 TCP 29942->192.168.0.6:32400 'Plex Media Server' '' 457200
 1 UDP 51820->192.168.0.6:51820 'WireGuard' '' 604800
GetGenericPortMappingEntry() returned 713 (SpecifiedArrayIndexInvalid)
```
Check with `^ \d+ UDP ${PORT}->${IP}:${PORT}`.

7. Profit

**Comment by daryll-swer** [comment]
Basically, I have a MikroTik Edge Router which has a public IP and NATted, in front of it is a TP-Link AP (in AP mode, bridged), which is where the WireGuard Pi is connected to.

MikroTik is 192.168.1.1/24
AP is bridged and is 192.168.1.2

So when running upnpc, it ends up detecting the UPnP feature on the TP-Link with its IP address (192.168.1.2) and "URL" instead of the MikroTik.

Can you share more details on how to correct the "Found IGD" device?

**Comment by Anuskuss** [comment]
@daryll-swer Can you not just disable UPnP on your TP-Link? If not you're probably looking for the `-u` argument:
> -u url : bypass discovery process by providing the XML root description url.

Anyway, you'll probably get more help if you ask directly in [miniupnp/miniupnp](https://github.com/miniupnp/miniupnp).

**Comment by daryll-swer** [comment]
> @daryll-swer Can you not just disable UPnP on your TP-Link? If not you're probably looking for the `-u` argument:
> 
> > -u url : bypass discovery process by providing the XML root description url.
> 
> Anyway, you'll probably get more help if you ask directly in [miniupnp/miniupnp](https://github.com/miniupnp/miniupnp).

That's the problem. The TP-Link is in AP mode and IP bridged. Meaning UPnP is not accessible at all. It is disabled.

-u wouldn't work as my edge router is RouterOS. There does not seem to be an XML URL for that.

**Comment by 4s3ti** [comment]
Closing this as there are no plans for supporting such feature nor i see any benefit on doing so, there are even several security researches advising against even having it enabled in first place.
