### ISSUE TITLE
[BUG] updating pivpn does not create new wireguard config and script folders

### ISSUE THREAD

**Issue by ksurl** [pivpn/pivpn#1069]
## In raising this issue, I confirm the following: 

- [x] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

**Describe the bug**
after updating from an install prior to may 19 to fix the new commit that fixed the removal of wireguard clients, it seems the paths for config, vars file and scripts changed. the update script did not account for that. and some commands fail since it can't find the files in the new path since they don't exist.

no /etc/pivpn/wireguard folder, no /opt/pivpn/wireguard folder

**To Reproduce**
1. do an install based on a commit prior for may 20
2.  run `pivpn -up`
3. error: /opt/update.sh: line 108: syntax error near unexpected token `else'
3. run `pivpn -r`
4. error: ::: Missing setup vars file!

**Expected behavior**
normal ability to remove, add clients, update, list clients

**Server:**
 - VPN Protocol: wireguard
 - OS: ubuntu 18.04
 - Version: latest commit June 9, 2020

**Additional context**

I was able to manually fix this by creating the missing folders and copying the expected conf and scripts there after checking the existing scripts that were updated (/usr/loca/bin/pivpn and /opt/pivpn/removeCONF.sh):

```
mkdir /etc/pivpn/wireguard
cp /etc/pivpn/setupVars.conf /etc/pivpn/wireguard/
mkdir /opt/pivpn/wireguard
git clone https://github.com/pivpn/pivpn /opt/.pivpn
cp -R /opt/.pivpn/scripts/* /opt/pivpn/
```

**Comment by orazioedoardo** [comment]
> it seems the paths for config, vars file and scripts changed. the update script did not account for that. and some commands fail since it can't find the files in the new path since they don't exist.

That's a limitation of the current update script, in fact for this reasons updating is [disabled](https://github.com/pivpn/pivpn/commit/f06f6d79203c29ebd785f860a81a15e9caac4fc9) for new installs.

Paths changed to accommodate the dual mode feature and just cloning the repository is not enough, you also need to detect if those changes would break previous installations.

For example the fix you are referring to also changes the way clients are added, which means you need to update the wg0.conf as well according to the [new format](https://github.com/pivpn/pivpn/blob/b2ab7fc862e31da92576d51609f250701eb6e02c/scripts/wireguard/makeCONF.sh#L111-L116).

**Comment by ksurl** [comment]
I've updated wg0.conf to match the new format. is there a list of changes to be aware of or I just need to read through all the commits since then?

**Comment by orazioedoardo** [comment]
Main changes [here](https://github.com/pivpn/pivpn/blob/master/LatestUpdate.md#jun-9th-2020). Some fixes [here](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+is%3Aclosed+label%3AMerged). Other changes in the commit log, however most of them don't apply to previous installations.

**Comment by gonzus** [comment]
Sorry, I just ran into this myself. So, if my pivpn installation borked? Should I re-install everything?

**Comment by crookshanked** [comment]
> Sorry, I just ran into this myself. So, is my pivpn installation borked? Should I re-install everything?

Wondering the same. Everything including pivpn -u is returning ::: Missing setup vars file!

**Comment by ksurl** [comment]
> > Sorry, I just ran into this myself. So, is my pivpn installation borked? Should I re-install everything?
> 
> Wondering the same. Everything including pivpn -u is returning ::: Missing setup vars file!
> 

You can fix this with the commands in my original post.

**Comment by crookshanked** [comment]
> > > Sorry, I just ran into this myself. So, is my pivpn installation borked? Should I re-install everything?
> > 
> > 
> > Wondering the same. Everything including pivpn -u is returning ::: Missing setup vars file!
> 
> You can fix this with the commands in my original post.

Okay, tried that out and still getting the same message. I'm using OpenVPN setup on my instance so I will try subbing out that for wire guard.

**Comment by orazioedoardo** [comment]
You can also revert to a commit that has the older path (replace openvpn with wireguard if needed):

```
sudo -s
git clone https://github.com/pivpn/pivpn.git /etc/.pivpn
git checkout 4e8d4dfd8ef01e49f3137d5fc5a2afa14a465e47
cp /etc/.pivpn/scripts/*.sh /opt/pivpn/
cp /etc/.pivpn/scripts/openvpn/*.sh /opt/pivpn/
cp /etc/.pivpn/scripts/openvpn/bash-completion /etc/bash_completion.d/
exit
```

**Comment by gonzus** [comment]
Works for me now. Thanks everyone.

**Comment by ksurl** [comment]
Since there is no support for migrating from old format, and the only fix is manually or reinstall, I am closing this.

**Comment by amiroff157** [comment]
> Since there is no support for migrating from old format, and the only fix is manually or reinstall, I am closing this.

any instruction on how to do a clean uninstall at least?

**Comment by ksurl** [comment]
delete pivpn folders (backup your configs if you want to re-use without re-issuing new keys) and re-run the installer. if you want to restore existing configs then that will probably have to be done manually in the text files
