### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by Tonino84** [pivpn/pivpn#1070]
Hello guys. I'm using a Raspberry Zero W.
I'm trying to install pivpn but but I get always that error. Can you help me please? 
![Screenshot_20200611_091710_com teamviewer teamviewer market mobile](https://user-images.githubusercontent.com/66770846/84357514-1278c380-abc6-11ea-82fe-4349a4861c8f.jpg)

**Comment by orazioedoardo** [comment]
It's a common problem with OctoPi: https://github.com/pivpn/pivpn/wiki#what-about-octopi

**Comment by Tonino84** [comment]
Hello, I think I ve solved. Thanks.

Do you know if there is an updated guide to setup it? I was looking for an up to date guide, but on youtube there are only old "version" guide.

Thanks

**Comment by orazioedoardo** [comment]
> Hello, I think I ve solved. Thanks.

Please next time read the issue template, closed issues and the wiki before posting.

> - [] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
> - [] The issue I am reporting can be *replicated*.
> - [] The issue I am reporting can be *is* directly related to the pivpn installer script.
> - [] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

> Do you know if there is an updated guide to setup it? I was looking for an up to date guide, but on youtube there are only old "version" guide.

You shouldn't really need a guide to set it up, the installer walks you through all the steps.

**Comment by orazioedoardo** [comment]
Closing as it seem to be solved, If you have other problems open a new issue following the template.
