### ISSUE TITLE
Port forwarding help

### ISSUE THREAD

**Issue by brad2388** [pivpn/pivpn#1071]
Currently have the tunnel working and can get to the internet. But im trying to open ports to allow my plex server to work.

At my house im behind a cgnat. But at our vacation house we have fiber and can open ports. I have the pi setup at the vacation house with the pivpn running.
Can anyone help me?

**Comment by orazioedoardo** [comment]
> Currently have the tunnel working and can get to the internet. But im trying to open ports to allow my plex server to work.


If your Plex server is at your vacation house you should be able to reach it using its internal IP while connected via PiVPN. Anyways, it’s not clear what issue you have, and you have not filled the template, so I will close. Reopen after you have provided the details.

**Comment by brad2388** [comment]
> > Currently have the tunnel working and can get to the internet. But im trying to open ports to allow my plex server to work.
> 
> If your Plex server is at your vacation house you should be able to reach it using its internal IP while connected via PiVPN. Anyways, it’s not clear what issue you have, and you have not filled the template, so I will close. Reopen after you have provided the details.

Not sure about a template?

The plex server is at my main house. The pivpn server is at the vacation house. Im trying to tunnel thru my cgnat and get to my plex from the vacation house.

**Comment by orazioedoardo** [comment]
> Not sure about a template?

When you open an issue, you have some text with some fields that you are supposed to fill:

> # PiVPN Issue Template
> PLEASE READ THIS TEMPLATE CAREFULLY BEFORE OPENING AN ISSUE! 
> Any Issue opened that doesn't follow this template will be removed. 

Continues...

> The plex server is at my main house. The pivpn server is at the vacation house. Im trying to tunnel thru my cgnat and get to my plex from the vacation house.

Well you can do it but it's not trivial. You could setup a second raspberry at the main house that connects to PiVPN at the vacation house, so you have a point-to-point tunnel as a base point. Then you need to configure both raspberry pis to forward traffic between the two LANs and possibly also setup some routes on both router.

Anyway that's a networking problem no related to PiVPN.

**Comment by brad2388** [comment]
The networking is what im trying to figure out i guess. Im using the windows openvpn gui to connect to the pivpn. But how do i open ports in the tunnel to get back to the plex?

**Comment by orazioedoardo** [comment]
As I said, it's just not a matter of opening ports, when you connect to PiVPN via OpenVPN, you reach your vacation LAN, but you want to reach the main house LAN, and that's a different feat.

**Comment by brad2388** [comment]
Gotcha!

Is there somewhere i can learn how to reach it or help me?

**Comment by orazioedoardo** [comment]
Networking subreddits on Reddit, OpenVPN forum.
