### ISSUE TITLE
Can access LAN but cannot access WAN

### ISSUE THREAD

**Issue by nmcc1212** [pivpn/pivpn#1072]
when connected to the VPN I can interact with devices on the network but I cannot go onto websites while the VPN is on

**Comment by orazioedoardo** [comment]
Closing as not following the issue template, reopen after you have provided such details.


> # PiVPN Issue Template
> PLEASE READ THIS TEMPLATE CAREFULLY BEFORE OPENING AN ISSUE! 
> Any Issue opened that doesn't follow this template will be removed.
