### ISSUE TITLE
Linux install can't change ownerhsip of '/etc/wireguard': operation not permitted

### ISSUE THREAD

**Issue by RGhadamian** [pivpn/pivpn#1073]
I can follow all the instructions up to this point when trying to install wireguard on the actual device itself. For some reason I get this error?

**Comment by neutronscott** [comment]
@RGhadamian just passing by but it'd help if you gave screenshots or snippets of output to know when you got this error.

**Comment by RGhadamian** [comment]
Thanks @neutronscott good point. I've attached a screenshot
<img width="819" alt="Screen Shot 2020-06-27 at 12 15 47 pm" src="https://user-images.githubusercontent.com/7765692/85912501-4879a100-b870-11ea-815b-a8637f8c2922.png">

**Comment by orazioedoardo** [comment]
This is the XY problem, you are asking about the attempted solution Y

> Linux install can't change ownerhsip of '/etc/wireguard': operation not permitted

instead of the actual problem X

> it doesn't allow me to actually browse...just timesout...

By the way I'm closing this as not following the issue template, reopen after you have provided such details.

> # PiVPN Issue Template
> PLEASE READ THIS TEMPLATE CAREFULLY BEFORE OPENING AN ISSUE! 
> Any Issue opened that doesn't follow this template will be removed.
