### ISSUE TITLE
[Support] Pivpn error " Missing setup vars file!" after pivpn commands.

### ISSUE THREAD

**Issue by Andreiva13** [pivpn/pivpn#1075]
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

Hello, so basically any command pivpn command besides `pivpn -up, pivpn -l, pivpn -c, pivpn -qr and pivpn -h` responds with " Missing setup vars file! ".
The vpn service itself (wireguard) works just fine but is limited by the fact that I can't add new users.

### Have you searched for similar issues and solutions?
    Yes, found nothing similar

### Console output of      `curl -L install.pivpn.dev | bash`
```
  Output Here
```

### Console output of      `pivpn add` or `pivpn add nopass`
```
  Output Here
```

### Console output of      `pivpn debug`
```
   Missing setup vars file! 
```
### Have you taken any steps towards solving your issue?
```
  which?
```

**Comment by orazioedoardo** [comment]
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

### Have you searched for similar issues and solutions?
    Yes, found nothing similar

Well, not really: https://github.com/pivpn/pivpn/issues/1069

**Comment by Andreiva13** [comment]
> 
> 
>     * [x]  The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).
> 
> 
> ### Have you searched for similar issues and solutions?
> 
> ```
> Yes, found nothing similar
> ```
> 
> Well, not really: #1069

Oh, sorry. I guess I need to improve my googling skills.

**Comment by orazioedoardo** [comment]
You can also search the error text in the issues: https://github.com/pivpn/pivpn/issues?q=Missing+setup+vars+file%21
