### ISSUE TITLE
Pivpn and smarthome

### ISSUE THREAD

**Issue by lodgemoorlad** [pivpn/pivpn#1076]
Hi, can anyone help me out here please.

I’m not too familiar when it comes to VPN’s and not sure what they can do if anything more than a making a secure link into your home router and onto the web. 

Thing is I’ve various sensors and cameras etc around the house, the garden and in my pond. Some I can only monitor when at home on my LAN via various apps and I’d like to access them while out and about.

So my question is, Will pivpn allow me access to my network of cameras & sensors remotely that I can’t access now?  And if not, what can it do, other than create a secure link back home and onto the web. 
Thanks

**Comment by shelleycat485** [comment]
Yes it can.  I have been using pivpn throughout the lockdown to access an office net work remotely and securely (actually multiple people have access).  The remote net work is 192.168.22.XX/24, and has a router onto an ISP.  The pivpn is connected to the network and has an address onto the network of 192.168.22.202.  On the network there is a CCTV camera recorder, with an address of 192.168.22.23.  
When I start the VPN client on my PC, it is connected directly to the 192.168.22.xx network.  If I enter 192.168.22.23 into my browser, I see the camera server as if I were connected directly to a switch on that network.  I think that is exactly what you are asking for.  If a do a SSH into the pi running the pivpn, I need to connect to pi@192.168.22.202 fro my PC.

**Comment by lodgemoorlad** [comment]
Hi shelleycat485


Really appreciate your reply and the news that I can access my camera(s).

That's actually brilliant news for me, so thank you for explaining how to
do it too.

I'm with now tv but moving to Plusnet in a couple of weeks, so I'll get it
ready for then, well as much as I can as I'm told nowtv don't allow port
forwarding.

You mention your pc connecting to it.

So one last question, sorry..

Do you know if a tablet or smartphone would also connect to it , the camera
via the pivpn I mean.

Sorry for all the dumb questions.. Alex

**Comment by shelleycat485** [comment]
Yes, it should work in exactly the same manner.  You need to have the VPN client on your phone, transfer the configuration file to the phone (email it to yourself, its only small), load it into the client, then make the VPN connection.  Then you open the phone browser and type in the home address of your camera.  On my tablet I have used the openvpn client from the android app store.

**Comment by lodgemoorlad** [comment]
Hi shelleycat485

Its really decent of you to help out and to know it can work, TBO, it's
more important it works for me than it been awkward

But I appreciate your input, just need to get set up with my new provider

Cheers
A

**Comment by 4s3ti** [comment]
inactive thread. closing.
