### ISSUE TITLE
[Support] PiVPN with OpenVPN Waiting for server Issue (Client Side)

### ISSUE THREAD

**Issue by stefan5641** [pivpn/pivpn#1079]
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [probably] The issue I am reporting can be *replicated*.
- [don't think so] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [most likely] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

### Issue
Installed PiVPN with OpenVPN following https://blog.crankshafttech.com/2019/12/set-up-pihole-with-doh-and-pivpn.html without the optional stuff at the end. I used Filezilla and downloaded my ovpn profile and imported it in the mobile OpenVPN app. When I try to connect it says waiting for server.
My port Forward:
![image](https://user-images.githubusercontent.com/46286331/86182096-95d76600-bb2f-11ea-8820-36664c6cd766.png)

### Have you searched for similar issues and solutions?
    (yes)

### Console output of      `curl -L install.pivpn.dev | bash`
```
  Output Here
```

### Console output of      `pivpn add` or `pivpn add nopass`
```
  Output Here
```

### Console output of      `pivpn debug`
```
::: Generating Debug Output
::::            PiVPN debug              ::::
=============================================
::::            Latest commit            ::::
commit b2ab7fc862e31da92576d51609f250701eb6e02c
Author: Orazio <orazioedoardo@users.noreply.github.com>
Date:   Tue Jun 9 15:45:38 2020 +0200

    Fix change from pull request #1000 that prevented 'pivpn -l' to show revoked client names
=============================================
::::        Installation settings        ::::
PLAT=Raspbian
OSCN=buster
USING_UFW=0
IPv4dev=eth0
IPv4addr=192.168.0.50/24
IPv4gw=192.168.0.1
install_user=pi
install_home=/home/pi
VPN=openvpn
pivpnPROTO=udp
pivpnPORT=42069
pivpnDNS1=10.8.0.1
pivpnDNS2=
pivpnSEARCHDOMAIN=
pivpnHOST=REDACTED
TWO_POINT_FOUR=1
pivpnENCRYPT=256
USE_PREDEFINED_DH_PARAM=0
INPUT_CHAIN_EDITED=0
FORWARD_CHAIN_EDITED=0
pivpnDEV=tun0
pivpnNET=10.8.0.0
subnetClass=24
UNATTUPG=1
INSTALLED_PACKAGES=(iptables-persistent openvpn grepcidr expect unattended-upgrades)
HELP_SHOWN=1
=============================================
::::  Server configuration shown below   ::::
dev tun
roto udp
port 42069
ca /etc/openvpn/easy-rsa/pki/ca.crt
cert /etc/openvpn/easy-rsa/pki/issued/StefanPiHolePiVPN_9b77b45d-441e-4af2-a898-acc695595a13.crt
key /etc/openvpn/easy-rsa/pki/private/StefanPiHolePiVPN_9b77b45d-441e-4af2-a898-acc695595a13.key
dh none
ecdh-curve prime256v1
topology subnet
server 10.8.0.0 255.255.255.0
# Set your primary domain name server address for clients
push "dhcp-option DNS 192.168.0.50"
push "block-outside-dns"
# Override the Client default gateway by using 0.0.0.0/1 and
# 128.0.0.0/1 rather than 0.0.0.0/0. This has the benefit of
# overriding but not wiping out the original default gateway.
push "redirect-gateway def1"
#push "route 192.168.0.0 255.255.255.0"
client-to-client
client-config-dir /etc/openvpn/ccd
keepalive 15 120
remote-cert-tls client
tls-version-min 1.2
tls-crypt /etc/openvpn/easy-rsa/pki/ta.key
cipher AES-256-CBC
auth SHA256
user openvpn
group openvpn
persist-key
persist-tun
crl-verify /etc/openvpn/crl.pem
status /var/log/openvpn-status.log 20
status-version 3
syslog
verb 3
#DuplicateCNs allow access control on a less-granular, per user basis.
#Remove # if you will manage access by user instead of device.
#duplicate-cn
# Generated for use by PiVPN.io
=============================================
::::  Client template file shown below   ::::
client
dev tun
proto udp
remote REDACTED 42069
resolv-retry infinite
nobind
remote-cert-tls server
tls-version-min 1.2
verify-x509-name StefanPiHolePiVPN_9b77b45d-441e-4af2-a898-acc695595a13 name
cipher AES-256-CBC
auth SHA256
auth-nocache
verb 3
=============================================
::::    Recursive list of files in       ::::
::: /etc/openvpn/easy-rsa/pki shows below :::
/etc/openvpn/easy-rsa/pki/:
ca.crt
crl.pem
Default.txt
ecparams
index.txt
index.txt.attr
index.txt.attr.old
index.txt.old
issued
openssl-easyrsa.cnf
private
renewed
revoked
safessl-easyrsa.cnf
serial
serial.old
stefan5641.ovpn
stefan.ovpn
ta.key

/etc/openvpn/easy-rsa/pki/ecparams:
prime256v1.pem

/etc/openvpn/easy-rsa/pki/issued:
stefan5641.crt
stefan.crt
StefanPiHolePiVPN_9b77b45d-441e-4af2-a898-acc695595a13.crt

/etc/openvpn/easy-rsa/pki/private:
ca.key
stefan5641.key
stefan.key
StefanPiHolePiVPN_9b77b45d-441e-4af2-a898-acc695595a13.key

/etc/openvpn/easy-rsa/pki/renewed:
private_by_serial
reqs_by_serial

/etc/openvpn/easy-rsa/pki/renewed/private_by_serial:

/etc/openvpn/easy-rsa/pki/renewed/reqs_by_serial:

/etc/openvpn/easy-rsa/pki/revoked:
private_by_serial
reqs_by_serial

/etc/openvpn/easy-rsa/pki/revoked/private_by_serial:

/etc/openvpn/easy-rsa/pki/revoked/reqs_by_serial:
=============================================
::::            Self check               ::::
:: [OK] IP forwarding is enabled
:: [OK] Iptables MASQUERADE rule set
:: [OK] OpenVPN is running
:: [OK] OpenVPN is enabled (it will automatically start on reboot)
:: [ERR] OpenVPN is not listening, try to restart now? [Y/n] y
Done
[INFO] Run pivpn -d again to see if we detect issues
=============================================
:::: Having trouble connecting? Take a look at the FAQ:
:::: https://github.com/pivpn/pivpn/wiki/FAQ
=============================================
::::      Snippet of the server log      ::::
Jul  1 08:33:02 StefanPiHolePiVPN ovpn-server[15364]: Options error: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/server.conf:2: roto (2.4.7)
Jul  1 08:33:02 StefanPiHolePiVPN ovpn-server[15364]: Use --help for more information.
Jul  1 08:33:08 StefanPiHolePiVPN ovpn-server[15384]: Options error: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/server.conf:2: roto (2.4.7)
Jul  1 08:33:08 StefanPiHolePiVPN ovpn-server[15384]: Use --help for more information.
Jul  1 08:33:13 StefanPiHolePiVPN ovpn-server[15403]: Options error: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/server.conf:2: roto (2.4.7)
Jul  1 08:33:13 StefanPiHolePiVPN ovpn-server[15403]: Use --help for more information.
Jul  1 08:33:18 StefanPiHolePiVPN ovpn-server[15423]: Options error: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/server.conf:2: roto (2.4.7)
Jul  1 08:33:18 StefanPiHolePiVPN ovpn-server[15423]: Use --help for more information.
Jul  1 08:33:23 StefanPiHolePiVPN ovpn-server[15434]: Options error: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/server.conf:2: roto (2.4.7)
Jul  1 08:33:23 StefanPiHolePiVPN ovpn-server[15434]: Use --help for more information.
Jul  1 08:33:29 StefanPiHolePiVPN ovpn-server[15454]: Options error: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/server.conf:2: roto (2.4.7)
Jul  1 08:33:29 StefanPiHolePiVPN ovpn-server[15454]: Use --help for more information.
Jul  1 08:33:34 StefanPiHolePiVPN ovpn-server[15606]: Options error: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/server.conf:2: roto (2.4.7)
Jul  1 08:33:34 StefanPiHolePiVPN ovpn-server[15606]: Use --help for more information.
Jul  1 08:33:39 StefanPiHolePiVPN ovpn-server[15625]: Options error: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/server.conf:2: roto (2.4.7)
Jul  1 08:33:39 StefanPiHolePiVPN ovpn-server[15625]: Use --help for more information.
Jul  1 08:33:45 StefanPiHolePiVPN ovpn-server[15638]: Options error: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/server.conf:2: roto (2.4.7)
Jul  1 08:33:45 StefanPiHolePiVPN ovpn-server[15638]: Use --help for more information.
Jul  1 08:33:50 StefanPiHolePiVPN ovpn-server[15678]: Options error: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/server.conf:2: roto (2.4.7)
Jul  1 08:33:50 StefanPiHolePiVPN ovpn-server[15678]: Use --help for more information.
=============================================
::::            Debug complete           ::::
:::
::: Debug output completed above.
::: Copy saved to /tmp/debug.txt
:::



DIDN'T SEE MY PUBLIC IP ANYWHERE ON HERE. AM RUNNING PiVPN WITH PiHole THOUGH.
```
### Have you taken any steps towards solving your issue?
```
  Googled but found nothing.
```

**Comment by orazioedoardo** [comment]
Can you post the output of these:

`systemctl status openvpn`

`tail -n 20 /var/log/openvpn.log`

The second command may contain public IPs, remove them if any.

**Comment by stefan5641** [comment]
"systemctl status openvpn" output this:

● openvpn.service - OpenVPN service
   Loaded: loaded (/lib/systemd/system/openvpn.service; enabled; vendor preset: enabled)
   Active: active (exited) since Wed 2020-07-01 08:33:51 CEST; 1min 39s ago
  Process: 15691 ExecStart=/bin/true (code=exited, status=0/SUCCESS)
 Main PID: 15691 (code=exited, status=0/SUCCESS)

Jul 01 08:33:51 StefanPiHolePiVPN systemd[1]: Starting OpenVPN service...
Jul 01 08:33:51 StefanPiHolePiVPN systemd[1]: Started OpenVPN service.

"tail -n 20 /var/log/openvpn.log" output this:
 Jul  1 08:36:04 StefanPiHolePiVPN ovpn-server[16153]: Options error: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/server.conf:2: roto (2.4.7)
Jul  1 08:36:04 StefanPiHolePiVPN ovpn-server[16153]: Use --help for more information.
Jul  1 08:36:10 StefanPiHolePiVPN ovpn-server[16172]: Options error: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/server.conf:2: roto (2.4.7)
Jul  1 08:36:10 StefanPiHolePiVPN ovpn-server[16172]: Use --help for more information.
Jul  1 08:36:15 StefanPiHolePiVPN ovpn-server[16192]: Options error: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/server.conf:2: roto (2.4.7)
Jul  1 08:36:15 StefanPiHolePiVPN ovpn-server[16192]: Use --help for more information.
Jul  1 08:36:21 StefanPiHolePiVPN ovpn-server[16203]: Options error: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/server.conf:2: roto (2.4.7)
Jul  1 08:36:21 StefanPiHolePiVPN ovpn-server[16203]: Use --help for more information.
Jul  1 08:36:26 StefanPiHolePiVPN ovpn-server[16223]: Options error: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/server.conf:2: roto (2.4.7)
Jul  1 08:36:26 StefanPiHolePiVPN ovpn-server[16223]: Use --help for more information.
Jul  1 08:36:32 StefanPiHolePiVPN ovpn-server[16242]: Options error: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/server.conf:2: roto (2.4.7)
Jul  1 08:36:32 StefanPiHolePiVPN ovpn-server[16242]: Use --help for more information.
Jul  1 08:36:37 StefanPiHolePiVPN ovpn-server[16263]: Options error: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/server.conf:2: roto (2.4.7)
Jul  1 08:36:37 StefanPiHolePiVPN ovpn-server[16263]: Use --help for more information.
Jul  1 08:36:42 StefanPiHolePiVPN ovpn-server[16282]: Options error: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/server.conf:2: roto (2.4.7)
Jul  1 08:36:42 StefanPiHolePiVPN ovpn-server[16282]: Use --help for more information.
Jul  1 08:36:48 StefanPiHolePiVPN ovpn-server[16294]: Options error: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/server.conf:2: roto (2.4.7)
Jul  1 08:36:48 StefanPiHolePiVPN ovpn-server[16294]: Use --help for more information.
Jul  1 08:36:53 StefanPiHolePiVPN ovpn-server[16313]: Options error: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/server.conf:2: roto (2.4.7)
Jul  1 08:36:53 StefanPiHolePiVPN ovpn-server[16313]: Use --help for more information.

**Comment by stefan5641** [comment]
Also updated the debug, since I realised I didnt also enter the information below this ":: [ERR] OpenVPN is not listening, try to restart now? [Y/n] y"

**Comment by orazioedoardo** [comment]
You server config `/etc/openvpn/server.conf` has a typo:  `roto udp` instead of `proto udp`. Fix it than restart `sudo systemctl restart openvpn`

**Comment by stefan5641** [comment]
I just did and was able to connect first try. I need further help, I want to be able to use WOL to wake up my other PCs home. That is possible with the VPN connection right? I already enabled WOL on my devices and forwarded the ports as you can see on the Port Forwarding picture above. Can you help me get further because I can't start my PCs consistently? 

I have a Kodi device at home and use "Advanced Wake On Lan" on the Kodi to wake up my media PC and it works, however, I am unable to wake it up consistently with any other device. Any Software you can recommend or how to troubleshoot the issue. I know this isn't very PiVPN related but I have asked everywhere and have been unable to solve this. Thanks for helping me figure out my VPN problem and thanks in advance if you wish to help me with the WOL issue. :)

**Comment by orazioedoardo** [comment]
>  I already enabled WOL on my devices and forwarded the ports as you can see on the Port Forwarding picture above. Can you help me get further because I can't start my PCs consistently?

Sorry I can't help you with WoL, however AFAIK WoL works with MAC addresses, which are not transmitted over the internet. So I would use conect to the raspberry via ssh over vpn and then trigger wol from there.

Close the issue if you solved the waiting for server issue.

**Comment by stefan5641** [comment]
Thanks a lot for the help, I really appreciate it, will try to do that. Ty
