### ISSUE TITLE
Unable to connect 

### ISSUE THREAD

**Issue by cbirchy87** [pivpn/pivpn#108]
Installation went very well! installed as default Port 1194 (default) with a user setup.

However i cannot connect. I;ve tried via windows 10 and android. What type of VPN does this use? I've tried connecting via the local address 192.168.0.7 also my public IP and also xxx.xxx.xx.x:1194. I still cannot connect. 

Router is also forwaring 1194 to my PI at 192.168.0.7 any ideas?

**Comment by redfast00** [comment]
For Android, you can use this app: [OpenVPN for Android] (https://play.google.com/store/apps/details?id=de.blinkt.openvpn) (also available on FDroid, OSS). For Windows, you check out the [OpenVPN downloads page](https://openvpn.net/index.php/open-source/downloads.html).

**Comment by cbirchy87** [comment]
Am i right in thinking i need to import the certs for the VPN to work. This i didn't do. How can i connect using something that cannot connect using a cert, IE a cctv ip camera?

**Comment by redfast00** [comment]
You first need to generate your `.ovpn` file on your Pi with the following command: `pivpn add`. This will generate a `.ovpn` file in the `ovpns` folder in your home directory on your Pi. You then need to transfer this file to your client device (like an Android phone or a laptop) and import in on the device. The `.ovpn` file contains both the certs and the configuration, so the only thing you have to do is import it, enter the password you typed when you created the `.ovpn` file and you should be good to go.

I don't quite understand the question about the CCTV IP camera, can you formulate it differently?

**Comment by cbirchy87** [comment]
I will give it ago. 

So if my server is on Site A with the PI and my CCTV camera on on SITE b. I need to set a VPN up between the two so they appear on the same network. I can only enter IP, Subnets and Gateways. Is this possible?

**Comment by redfast00** [comment]
You need to have your VPN server and your IP CCTV camera on the same network (for example on the 192.168.0.0/24 subnet)  and then you need to forward port 1194 to the Pi. If you then VPN into the Pi, you will be able to connect to the IP camera with your client device from anywhere (as long as you don't have a subnet conflict)..

**Comment by cbirchy87** [comment]
Thanks for you help! All connected. Now i just need to work out how to access my files! Thank you!

**Comment by redfast00** [comment]
@cbirchy87: you can run `cat ovpns/yourfile.ovpn` to output the file to your terminal and then copy paste it into an ovpn file on your PC. Another option is to use a program like WinSCP to copy the file directly or use an online service like https://transfer.sh.

**Comment by redfast00** [comment]
@cbirchy87: can this issue be closed?

**Comment by cbirchy87** [comment]
Yes please! :D thanks again
