### ISSUE TITLE
[Support] cannot use pivpn add

### ISSUE THREAD

**Issue by JackyHe398** [pivpn/pivpn#1080]
Hey hi everyone 
When I finish download pivpn on raspberry pi4 today and try to start using it. I find out that it cannot run normally (or that's my fault). 
When I try to use the command 'pivpn add' it just return this

pi@raspberrypi:~ $ pivpn add
::: To pass off to the pivpn command for each protocol
:::
::: Usage: pivpn wg  <command> [option]
::: Usage: pivpn ovpn <command> [option]
:::
:::  -h,  help             Show this help dialog
:::  -u,  uninstall        Uninstall pivpn from your system!
:::  -bk, backup           Backup VPN configs and user profiles

i cannot really understand what happen and my english is not good at all. i think it is not a normal output. i search i on google but still cannot find one who met this problem
here are some setting and hope those data can help to  solve the problem
model: raspberry raspberry pi 4 model b
operating system:  raspberry pi os (called raspbian before)
using utp in pivpn
change the port before 
ufw (firewall) is on
I have tried to re-downloading it for several times

that all 
thx

**Comment by orazioedoardo** [comment]
Hi, `pivpn add` returns that output because you installed both wireguard and openvpn. To control wireguard use `pivpn wg something`, for example `pivpn wg add`. To control openvpn use `pivpn ovpn something`.

**Comment by JackyHe398** [comment]
ohhhhhhhhhhhhhhhhhh
thank you so much

**Comment by orazioedoardo** [comment]
No problem, close the issue if you solved.
