### ISSUE TITLE
(7) Couldn't connect to server

### ISSUE THREAD

**Issue by blueduck3285** [pivpn/pivpn#1089]
Using curl -L https://install.pivpn.io | bash gives me this
![image](https://user-images.githubusercontent.com/24479706/87216398-9d9bc500-c2fc-11ea-8e12-abd0418dae64.png)

while sudo ping -c 5 www.google.com gives me
![image](https://user-images.githubusercontent.com/24479706/87216420-c754ec00-c2fc-11ea-9ec8-afc4a20eec8d.png)

I obviously have a connection on my pi.

**Comment by orazioedoardo** [comment]
Try the direct link: `curl -L https://github.com/pivpn/pivpn/blob/master/auto_install/install.sh | bash`

**Comment by orazioedoardo** [comment]
I've updated the README with this information: https://github.com/pivpn/pivpn#installation
