### ISSUE TITLE
Not able to access IPv4 HTTP(S) addresses

### ISSUE THREAD

**Issue by terencejackson8000** [pivpn/pivpn#109]
Hi Guys,

I have installed PiVPN and I am still impressed how easy and fast it was! Thanks for this great project!

Unfortunately I am facing a little problem. When I am connecting to OpenVPN from an IPv6 connection I am not able to connect to internal IPv4 addresses via HTTP(S). I am able to ping these addresses, though. I am also able to access the internet.

Can somebody help me with this problem? Is this even an OpenVPN problem?

Thanks!

TJ

**Comment by redfast00** [comment]
My guess: you might have a subnet conflict (for example: your client device at Starbucks is in the 192.168.0.0/24 subnet and your home also uses the 192.168.0.0/24 subnet. If your internal server is at 192.168.0.50 (at home) and you ping it, your client pings 192.168.0.50 on the Starbucks network.) You can avoid this by setting your home subnet to something uncommon (mine is 192.168.236.0/24).

**Comment by terencejackson8000** [comment]
Thanks for the answer @redfast00 .
My home subnet is 192.168.0.0/24, my target subnet is 192.168.1.0/24, so it should not be a conflict here.

Also it is interesting that I can connect to e.g. 19.2.168.1.99 via Putty (Port 22), but as soon as I try http://192.168.1.10/ it is not working (Apache is running :) )

**Comment by cfcolaco** [comment]
@redfast00 guess this one can go to ... oct 2016 ... no more interaction ?
