### ISSUE TITLE
how can I that check wireguard is working

### ISSUE THREAD

**Issue by lodgemoorlad** [pivpn/pivpn#1092]
Hi all
I've a really dumb question to ask.

I have just set up my Pivpn, which uses Wireguard. But I don't have a clue if its working.How can I check it, can anyone advise please. I said it was a dumb question :-)

So far I have loaded up the config file to to the WG app and nothing bad happens, I can surf the web albeit I'm having problems connecting to a few devices I have around the place when the app is turned on. When its off,things are ok. So I'm hoping its an indication something changed when its on. But I really don't know how to tell its working, hope someone can help. Thanks in advance

**Comment by orazioedoardo** [comment]
Closing as not following the issue template, reopen after you have provided such details.


> # PiVPN Issue Template
> PLEASE READ THIS TEMPLATE CAREFULLY BEFORE OPENING AN ISSUE! 
> Any Issue opened that doesn't follow this template will be removed.
