### ISSUE TITLE
Connecting to Wireguard VPN through router WAN IP and Access the Internet through Paid VPN service?

### ISSUE THREAD

**Issue by jorgsmash** [pivpn/pivpn#1094]
Hi all. I used PiVPN in that past and had used the OpenVPN protocol. I moved about 8 months ago and haven't fooled with it since. I recently updated to a new router and decided to re-install PiVPN. I was happy to see the new options for Wireguard so I gave it a shot.

As a side-note: My PiVPN (along with PiHole DNS) installation is running in VirtualBox on a Windows Host. Guest OS is Ubuntu 18. Network interface is bridged to my ethernet adapter. 

At first I thought I was having connection issues with my mobile phone because the Wireguard app would show I was connected but I couldn't access local LAN IPs or get out to the Internet.

Upon further investigation I realized that I have my Windows machine connected to a VPN service I pay for (VPN Unlimited). Normally (I have done this in other use-cases) I can use port forwarding through my router to forward ports from my WAN interface on the router (ISP IP) to this Windows machine. Any connections made out to Internet from the device go out through the VPN. 

Upon disabling the paid VPN service on my Windows Host machine, my mobile phone was able to connect to the Wireguard VPN and I was able to ping local LAN IPs from my mobile device, and my mobile phone's public IP became the public IP for my ISP. 

Is it possible to set this up so the connection works when my Windows computer is connected to my VPN service? I would ideally like to have port forwarding set up so that the Router WAN (ISP IP) forwards to the IP of the Ubuntu VM, and any device that connects to the wireguard VPN would have access to local LAN resources (PiHole DNS server, Plex) and then any connections out to the Internet go through the paid VPN service. 

I can't remember if this worked in the past with OpenVPN but I am about 80% or more positive that it did work. 

As a second side note: My router supports OpenVPN configurations as well. So I tried to set up the router so that the Paid VPN service (via ovpn config file) is used by the Ubuntu VM. This still did not allow the wireguard connection to work. 

Here are the steps I went through initially to ensure everything was working correctly before I disabled the paid VPN service on my Windows Host:

Service is running
```
$ sudo systemctl status wg-quick@wg0.service
● wg-quick@wg0.service - WireGuard via wg-quick(8) for wg0
   Loaded: loaded (/lib/systemd/system/wg-quick@.service; indirect; vendor preset: enabled)
   Active: active (exited) since Thu 2020-07-16 15:24:39 UTC; 6min ago
     Docs: man:wg-quick(8)
           man:wg(8)
           https://www.wireguard.com/
           https://www.wireguard.com/quickstart/
           https://git.zx2c4.com/wireguard-tools/about/src/man/wg-quick.8
           https://git.zx2c4.com/wireguard-tools/about/src/man/wg.8
  Process: 1083 ExecStart=/usr/bin/wg-quick up wg0 (code=exited, status=0/SUCCESS)
 Main PID: 1083 (code=exited, status=0/SUCCESS)

Jul 16 15:24:37 hogwarts-backup-pi-hole-vm systemd[1]: Starting WireGuard via wg-quick(8) for wg0...
Jul 16 15:24:38 hogwarts-backup-pi-hole-vm wg-quick[1083]: [#] ip link add wg0 type wireguard
Jul 16 15:24:38 hogwarts-backup-pi-hole-vm wg-quick[1083]: [#] wg setconf wg0 /dev/fd/63
Jul 16 15:24:39 hogwarts-backup-pi-hole-vm wg-quick[1083]: [#] ip -4 address add 10.6.0.1/24 dev wg0
Jul 16 15:24:39 hogwarts-backup-pi-hole-vm wg-quick[1083]: [#] ip link set mtu 1420 up dev wg0
Jul 16 15:24:39 hogwarts-backup-pi-hole-vm systemd[1]: Started WireGuard via wg-quick(8) for wg0.
```

```
$ lsmod | grep wireguard
wireguard             217088  0
ip6_udp_tunnel         16384  1 wireguard
udp_tunnel             16384  1 wireguard
```

Service is listening
```
$ netstat -ano | grep 6969
udp        0      0 0.0.0.0:6969            0.0.0.0:*                           off (0.00/0/0)
udp6       0      0 :::6969                 :::*                                off (0.00/0/0)
```

TCPdump shows port forwarding is correct since external traffic is getting to LAN ip.

```
$ sudo tcpdump -v -i enp0s3 port 6969
tcpdump: listening on enp0s3, link-type EN10MB (Ethernet), capture size 262144 bytes
15:17:02.307457 IP (tos 0x0, ttl 45, id 16444, offset 0, flags [DF], proto UDP (17), length 88)
    external-ip.8434 > 192.168.50.4.6969: UDP, length 60
15:17:07.308865 IP (tos 0x0, ttl 45, id 18064, offset 0, flags [DF], proto UDP (17), length 35)
    external-ip.8434 > 192.168.50.4.6969: UDP, length 7
15:17:12.313950 IP (tos 0x0, ttl 45, id 22148, offset 0, flags [DF], proto UDP (17), length 60)
    external-ip.8434 > 192.168.50.4.6969: UDP, length 32
15:17:17.317989 IP (tos 0x0, ttl 45, id 23063, offset 0, flags [DF], proto UDP (17), length 74)
    external-ip.8434 > 192.168.50.4.6969: UDP, length 46
15:17:22.322597 IP (tos 0x0, ttl 45, id 24548, offset 0, flags [DF], proto UDP (17), length 58)
    external-ip.8434 > 192.168.50.4.6969: UDP, length 30
15:17:27.328636 IP (tos 0x0, ttl 45, id 28379, offset 0, flags [DF], proto UDP (17), length 141)
    external-ip.8434 > 192.168.50.4.6969: UDP, length 113
15:17:32.333220 IP (tos 0x0, ttl 45, id 31037, offset 0, flags [DF], proto UDP (17), length 89)
    external-ip.8434 > 192.168.50.4.6969: UDP, length 61
15:17:37.351421 IP (tos 0x0, ttl 45, id 33668, offset 0, flags [DF], proto UDP (17), length 68)
    external-ip.45817 > 192.168.50.4.6969: UDP, length 40
```
Nmap shows the port is not responding back to remote machine
From remote machine:

```
$ sudo nmap -sVU -p 6969 -Pn -v pub_dns_name

Starting Nmap 6.40 ( http://nmap.org ) at 2020-07-16 11:16 EDT
NSE: Loaded 23 scripts for scanning.
Initiating Parallel DNS resolution of 1 host. at 11:16
Completed Parallel DNS resolution of 1 host. at 11:16, 0.01s elapsed
Initiating UDP Scan at 11:16
Scanning pub_dns_name (ip) [1 port]
Completed UDP Scan at 11:16, 2.02s elapsed (1 total ports)
Initiating Service scan at 11:16
Scanning 1 service on pub_dns_name (ip)
Completed Service scan at 11:17, 82.58s elapsed (1 service on 1 host)
NSE: Script scanning ip.
Initiating NSE at 11:17
Completed NSE at 11:18, 30.01s elapsed
Nmap scan report for pub_dns_name (ip)
Host is up.

PORT     STATE         SERVICE VERSION
6969/udp open|filtered acmsoda

Read data files from: /usr/bin/../share/nmap
Service detection performed. Please report any incorrect results at http://nmap.org/submit/ .
Nmap done: 1 IP address (1 host up) scanned in 114.90 seconds
```

```
$ pivpn -d
::::            PiVPN debug              ::::
=============================================
::::            Latest commit            ::::
commit b2ab7fc862e31da92576d51609f250701eb6e02c (grafted, HEAD -> master, origin/test, origin/master, origin/HEAD)
Author: Orazio <orazioedoardo@users.noreply.github.com>
Date:   Tue Jun 9 15:45:38 2020 +0200

    Fix change from pull request #1000 that prevented 'pivpn -l' to show revoked client names
=============================================
::::        Installation settings        ::::
PLAT=Ubuntu
OSCN=bionic
USING_UFW=0
IPv4dev=enp0s3
install_user=jorg
install_home=/home/jorg
VPN=wireguard
pivpnPORT=6969
pivpnDNS1=10.6.0.1
pivpnDNS2=
pivpnHOST=REDACTED
INPUT_CHAIN_EDITED=0
FORWARD_CHAIN_EDITED=0
pivpnPROTO=udp
pivpnDEV=wg0
pivpnNET=10.6.0.0
subnetClass=24
UNATTUPG=1
INSTALLED_PACKAGES=(wireguard wireguard-tools wireguard-dkms qrencode)
=============================================
::::  Server configuration shown below   ::::
[Interface]
PrivateKey = server_priv
Address = 10.6.0.1/24
ListenPort = 6969
### begin S7 ###
[Peer]
PublicKey = S7_pub
PresharedKey = S7_psk
AllowedIPs = 10.6.0.2/32
### end S7 ###
=============================================
::::  Client configuration shown below   ::::
[Interface]
PrivateKey = S7_priv
Address = 10.6.0.2/24
DNS = 10.6.0.1

[Peer]
PublicKey = server_pub
PresharedKey = S7_psk
Endpoint = REDACTED:6969
AllowedIPs = 0.0.0.0/0, ::0/0
=============================================
::::    Recursive list of files in       ::::
::::    /etc/wireguard shown below       ::::
/etc/wireguard:
configs  keys  wg0.conf

/etc/wireguard/configs:
clients.txt  S7.conf

/etc/wireguard/keys:
S7_priv  S7_psk  S7_pub  server_priv  server_pub
=============================================
::::            Self check               ::::
:: [OK] IP forwarding is enabled
:: [OK] Iptables MASQUERADE rule set
:: [OK] WireGuard is running
:: [OK] WireGuard is enabled (it will automatically start on reboot)
:: [OK] WireGuard is listening on port 6969/udp
=============================================
:::: Having trouble connecting? Take a look at the FAQ:
:::: https://github.com/pivpn/pivpn/wiki/FAQ
=============================================
:::: WARNING: This script should have automatically masked sensitive       ::::
:::: information, however, still make sure that PrivateKey, PublicKey      ::::
:::: and PresharedKey are masked before reporting an issue. An example key ::::
:::: that you should NOT see in this log looks like this:                  ::::
:::: YIAoJVsdIeyvXfGGDDadHh6AxsMRymZTnnzZoAb9cxRe                          ::::
=============================================
::::            Debug complete           ::::
```

**Comment by jorgsmash** [comment]
Just an update. I setup another instance of PiVPN and went with the OpenVPN protocol this time. I can't connect using the OpenVPN app on my phone. I confirmed my VPN server is receiving the packets using tcpdump, but the connection doesn't succeed. I generated an additional VPN profile just to be sure and that one won't connect either. Here's the tcpdump:

> backup-pi-hole-vm:~$ sudo tcpdump -v -i enp0s3 udp port 1194
tcpdump: listening on enp0s3, link-type EN10MB (Ethernet), capture size 262144 bytes
15:57:14.607044 IP (tos 0x0, ttl 47, id 18162, offset 0, flags [DF], proto UDP (17), length 82)
    212.sub-174-228-143.myvzw.com.11171 > 192.168.50.4.openvpn: UDP, length 54
15:57:15.567437 IP (tos 0x0, ttl 47, id 18218, offset 0, flags [DF], proto UDP (17), length 82)
    212.sub-174-228-143.myvzw.com.11171 > 192.168.50.4.openvpn: UDP, length 54
15:57:16.577658 IP (tos 0x0, ttl 47, id 18271, offset 0, flags [DF], proto UDP (17), length 82)
    212.sub-174-228-143.myvzw.com.11171 > 192.168.50.4.openvpn: UDP, length 54
15:57:17.557210 IP (tos 0x0, ttl 47, id 18291, offset 0, flags [DF], proto UDP (17), length 82)
    212.sub-174-228-143.myvzw.com.11171 > 192.168.50.4.openvpn: UDP, length 54
15:57:18.588123 IP (tos 0x0, ttl 47, id 18367, offset 0, flags [DF], proto UDP (17), length 82)
    212.sub-174-228-143.myvzw.com.11171 > 192.168.50.4.openvpn: UDP, length 54
15:57:18.739287 IP (tos 0x0, ttl 64, id 56547, offset 0, flags [DF], proto UDP (17), length 65)
    192.168.50.4.openvpn > 192.168.50.1.44562: UDP, length 37
15:57:19.597778 IP (tos 0x0, ttl 47, id 18449, offset 0, flags [DF], proto UDP (17), length 82)
    212.sub-174-228-143.myvzw.com.11171 > 192.168.50.4.openvpn: UDP, length 54
15:57:20.587493 IP (tos 0x0, ttl 47, id 18505, offset 0, flags [DF], proto UDP (17), length 82)
    212.sub-174-228-143.myvzw.com.11171 > 192.168.50.4.openvpn: UDP, length 54
15:57:21.647381 IP (tos 0x0, ttl 47, id 18580, offset 0, flags [DF], proto UDP (17), length 82)
    212.sub-174-228-143.myvzw.com.11171 > 192.168.50.4.openvpn: UDP, length 54
15:57:22.608658 IP (tos 0x0, ttl 47, id 18606, offset 0, flags [DF], proto UDP (17), length 82)
    212.sub-174-228-143.myvzw.com.11171 > 192.168.50.4.openvpn: UDP, length 54
15:57:23.645982 IP (tos 0x0, ttl 47, id 18690, offset 0, flags [DF], proto UDP (17), length 82)
    212.sub-174-228-143.myvzw.com.11170 > 192.168.50.4.openvpn: UDP, length 54
15:57:24.596370 IP (tos 0x0, ttl 47, id 18783, offset 0, flags [DF], proto UDP (17), length 82)
    212.sub-174-228-143.myvzw.com.11170 > 192.168.50.4.openvpn: UDP, length 54
15:57:25.595730 IP (tos 0x0, ttl 47, id 18865, offset 0, flags [DF], proto UDP (17), length 82)
    212.sub-174-228-143.myvzw.com.11170 > 192.168.50.4.openvpn: UDP, length 54
15:57:26.596251 IP (tos 0x0, ttl 47, id 18907, offset 0, flags [DF], proto UDP (17), length 82)
    212.sub-174-228-143.myvzw.com.11170 > 192.168.50.4.openvpn: UDP, length 54
15:57:27.606153 IP (tos 0x0, ttl 47, id 18998, offset 0, flags [DF], proto UDP (17), length 82)
    212.sub-174-228-143.myvzw.com.11170 > 192.168.50.4.openvpn: UDP, length 54
15:57:28.596159 IP (tos 0x0, ttl 47, id 19009, offset 0, flags [DF], proto UDP (17), length 82)
    212.sub-174-228-143.myvzw.com.11170 > 192.168.50.4.openvpn: UDP, length 54
15:57:29.646622 IP (tos 0x0, ttl 47, id 19079, offset 0, flags [DF], proto UDP (17), length 82)
    212.sub-174-228-143.myvzw.com.11170 > 192.168.50.4.openvpn: UDP, length 54
15:57:30.606022 IP (tos 0x0, ttl 47, id 19116, offset 0, flags [DF], proto UDP (17), length 82)
    212.sub-174-228-143.myvzw.com.11170 > 192.168.50.4.openvpn: UDP, length 54
^C
18 packets captured
18 packets received by filter
0 packets dropped by kernel


What could be causing the connection to not succeed if the VPN server is getting the packets and the vpn profile is valid? Thanks all!

**Comment by orazioedoardo** [comment]
> Is it possible to set this up so the connection works when my Windows computer is connected to my VPN service? I would ideally like to have port forwarding set up so that the Router WAN (ISP IP) forwards to the IP of the Ubuntu VM, and any device that connects to the wireguard VPN would have access to local LAN resources (PiHole DNS server, Plex) and then any connections out to the Internet go through the paid VPN service.

It should be but this is out of scope of PiVPN (non even an issue).

> Nmap shows the port is not responding back to remote machine

This is expected, both OpenVPN and WireGuard are configured to be invisible from post scans.

> I setup another instance of PiVPN and went with the OpenVPN protocol this time. I can't connect using the OpenVPN app on my phone. I confirmed my VPN server is receiving the packets using tcpdump, but the connection doesn't succeed.

This is a different topic, you should open another issue for this.

P.S. I edited your comments for readability

**Comment by jorgsmash** [comment]
> > Is it possible to set this up so the connection works when my Windows computer is connected to my VPN service? I would ideally like to have port forwarding set up so that the Router WAN (ISP IP) forwards to the IP of the Ubuntu VM, and any device that connects to the wireguard VPN would have access to local LAN resources (PiHole DNS server, Plex) and then any connections out to the Internet go through the paid VPN service.
> 
> It should be but this is out of scope of PiVPN (non even an issue).
> 
> > Nmap shows the port is not responding back to remote machine
> 
> This is expected, both OpenVPN and WireGuard are configured to be invisible from post scans.
> 
> > I setup another instance of PiVPN and went with the OpenVPN protocol this time. I can't connect using the OpenVPN app on my phone. I confirmed my VPN server is receiving the packets using tcpdump, but the connection doesn't succeed.
> 
> This is a different topic, you should open another issue for this.
> 
> P.S. I edited your comments for readability

Thank you, I tried to edit it several times to make it look better but the block quotes weren't working. I'll try and figure out the issue I was having and will make a new issue if I need further help. Thank you!
