### ISSUE TITLE
[Support] Firewall enabled by default?

### ISSUE THREAD

**Issue by dffvb** [pivpn/pivpn#1095]
Hi there, first of thanks for the great work. 

I have a rather simple question I couldnt find an answer to. Is there a firewall (uf) enabled by default? Meaning I install pivpn on a naked Ubuntu Server. Even though I am only forwarding 443 from my router to the pivpn machine, I am not fully sure, how much additional hardening is reuqired (e.g. enable ufw, disable ssh) etc. 

Additional question, when installing it on a standard raspbian, would there be any security issue leaving standard pi credentials? (Of course I change them, I am more asking to understand the security concepts behind).

**Comment by orazioedoardo** [comment]
> Is there a firewall (uf) enabled by default?

On a clean install of Raspbian (and many other distros), the firewall permits everything. PiVPN only adds the minimum amount of rules required to poke into the firewall (also supports ufw).

> I am not fully sure, how much additional hardening is reuqired (e.g. enable ufw, disable ssh) etc.
>
> Additional question, when installing it on a standard raspbian, would there be any security issue leaving standard pi credentials? (Of course I change them, I am more asking to understand the security concepts behind).

https://wiki.ubuntu.com/BasicSecurity and https://www.raspberrypi.org/documentation/configuration/security.md. Please note that if you install ufw AFTER PiVPN you will need to manually add several rules.

**Comment by dffvb** [comment]
Thank you for the answer! This means harden the system and then install pivpn, thanks also for the links, maybe a little hint on the download page would be good, I could imagine some noobs opening their Pis to the internet :-) 

Overall I am really amazed by pivpn - it is such a charm to have both (openVPN and Wireguard) installed in the blink of an eye
