### ISSUE TITLE
[Support] <The Pivpn setup quits after choosing what user to save to?>

### ISSUE THREAD

**Issue by MadsRudolph** [pivpn/pivpn#1096]
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

pi@octopi:~ $ curl install.pivpn.dev | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     5  100     5    0     0      9      0 --:--:-- --:--:-- --:--:--     9
bash: line 1: Found: command not found

### 
when I run "curl -L https://install.pivpn.io | bash" i go through the setup process, but after choosing what user it will be saved to, it goes back to the command prompt and the console says

pi@octopi:~ $ curl -L https://install.pivpn.io | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   162  100   162    0     0    486      0 --:--:-- --:--:-- --:--:--   486
100 83592  100 83592    0     0  98227      0 --:--:-- --:--:-- --:--:-- 98227
:::
::: sudo will be used for the install.
::: Hostname length OK
::: Verifying free disk space...
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: Your system is up to date! Continuing with PiVPN installation...
[sudo] password for pi: 
:::    Checking for git... already installed!
:::    Checking for tar... already installed!
:::    Checking for wget... already installed!
:::    Checking for curl... already installed!
:::    Checking for grep... already installed!
:::    Checking for dnsutils... already installed!
:::    Checking for whiptail... already installed!
:::    Checking for net-tools... already installed!
:::    Checking for bsdmainutils... already installed!
:::    Checking for dhcpcd5... already installed!
:::    Checking for iptables-persistent... already installed!
::: Using User: pi
:::
::: Checking for existing base files...
:::    Checking /usr/local/src/pivpn is a repo...:::    Cloning https://github.com/pivpn/pivpn.git into /usr/local/src/pivpn...main: line 993: cd: /usr/local/src/pivpn: No such file or directory

### Have you searched for similar issues and solutions?
    (yes/no / which issues?)
yes case #484

### Console output of      `curl -L install.pivpn.dev | bash`
```
  pi@octopi:~ $ curl -L install.pivpn.dev | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     5  100     5    0     0     31      0 --:--:-- --:--:-- --:--:--    31
100   162  100   162    0     0    529      0 --:--:-- --:--:-- --:--:--   529
100 83592  100 83592    0     0   127k      0 --:--:-- --:--:-- --:--:--  748k
:::
::: sudo will be used for the install.
::: Hostname length OK
::: Verifying free disk space...
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: Your system is up to date! Continuing with PiVPN installation...
:::    Checking for git... already installed!
:::    Checking for tar... already installed!
:::    Checking for wget... already installed!
:::    Checking for curl... already installed!
:::    Checking for grep... already installed!
:::    Checking for dnsutils... already installed!
:::    Checking for whiptail... already installed!
:::    Checking for net-tools... already installed!
:::    Checking for bsdmainutils... already installed!
:::    Checking for dhcpcd5... already installed!
:::    Checking for iptables-persistent... already installed!
::: Static IP already configured.
::: Using User: pi
:::
::: Checking for existing base files...
:::    Checking /usr/local/src/pivpn is a repo...:::    Cloning https://github.com/pivpn/pivpn.git into /usr/local/src/pivpn...main: line 993: cd: /usr/local/src/pivpn: No such file or directory

```

### Console output of      pivpn add or pivpn add nopass

```
pi@octopi:~ $ pivpn add
bash: pivpn: command not found

pi@octopi:~ $ pivpn add nopass
bash: pivpn: command not found
```

### Console output of      `pivpn debug`
```
command not found
```
### Have you taken any steps towards solving your issue?
```
i have tried updating "sudo apt-get update"
![pi vpn problem](https://user-images.githubusercontent.com/68565302/87987221-9172ed00-cade-11ea-85c7-4203f460a9cf.png)

```

**Comment by utechtl** [comment]
I'm running into the same issue

`:::    Checking /usr/local/src/pivpn is a repo...:::    
Cloning https://github.com/pivpn/pivpn.git into /usr/local/src/pivpn... [/]  /usr/lib/git-core/git-remote-https: error while loading shared libraries: ????????g?L>??:y????%?2?4P?( fh?????^?P??_?PX?ZT?P?Z\?SR???_?P?Z??YR???: cannot open shared object file: No such file or directory`

Though I'm not on octoprint, it's the latest rasbian lite image, up to date and nothing installed other than pihole installed by their curl instruction.

**Comment by MadsRudolph** [comment]
Okay, but shouldn't I be able to get Pivpn on the same Pi as I'm running octopi?

**Comment by orazioedoardo** [comment]
@MadsRudolph There are several duplicate issues about OctoPi, please read them! The FAQ too.

https://github.com/pivpn/pivpn/issues?q=octoprint

https://github.com/pivpn/pivpn/issues?q=main%3A+line+993%3A+cd%3A+%2Fusr%2Flocal%2Fsrc%2Fpivpn%3A+No+such+file+or+directory

**Comment by orazioedoardo** [comment]
@utechtl That's an issue with git or curl, try to reinstall them.
