### ISSUE TITLE
IP tables/no connectivity-SOLVED

### ISSUE THREAD

**Issue by cabsandy** [pivpn/pivpn#110]
Apologies for not being a direct issue-but I found this, and then fixed it. Set up VPN, could get a valid IP and could ping the 10.8.0.1 server-but no internet connectivity could be had from my client machine. I should mention the server is an Odroid 64-this may be a contributing factor.

Looking through some of the posts, I knew the issue was iptables related-as i suspect a fair few folks have had/get. Using some of the posts on here, I figured out the following was missing from my iptables (it should have been inserted as part of the script)

`sudo iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE`

If I then did an iptables-save, I could see this-but it would not go into the /etc/iptables/rules.v4 file.
And when I rebooted, not only did the rules.v4 file go back to default, the iptables-save was default as well. I figured out the iptables-persistent package wasn't working properly. After much head-scratching, I realised that I had to do the following, in these steps:

- sudo iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE

- sudo iptables-save

- sudo dpkg-reconfigure iptables-persistent -and accept the prompt to save to the default files.

It seems that iptables-persistent is not some overseeing, real-time updating service
[http://unix.stackexchange.com/questions/125833/why-isnt-the-iptables-persistent-service-saving-my-changes](url) -it only saves what is in the iptables at that time, and will then reload those rules at reboot for you. Simply doing an iptables-save (for me anyway) would not persist after a reboot-I had to then run iptables-persistent to make it persistent!

So rebooted, files now had the correct iptables and when connecting from the client, could surf the Internet.Sorted! I'd do this after the script has run if your device is not a mainline box like a Raspberry Pi (my Pi's work fine with the script-the Odroid runs Ubuntu Mate 16.04)
Hope this helps someone

**Comment by redfast00** [comment]
I think I already have a solution. Just to confirm, can you give me the the output of `cat /etc/pivpn/DET_PLATFORM`?

**Comment by cabsandy** [comment]
Here ya go

```
odroid@odroid64-1:~$ cat /etc/pivpn/DET_PLATFORM
Ubuntu
```

**Comment by redfast00** [comment]
This will be fixed when #113 is merged.
