### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by luco85** [pivpn/pivpn#1100]
hello! I'm trying to install pivpn but when it ask to choose a user when i hit OK (with pi user) installation exit an report this error

::: Your system is up to date! Continuing with PiVPN installation...
:::    Checking for git... already installed!
:::    Checking for tar... already installed!
:::    Checking for wget... already installed!
:::    Checking for curl... already installed!
:::    Checking for grep... already installed!
:::    Checking for dnsutils... already installed!
:::    Checking for whiptail... already installed!
:::    Checking for net-tools... already installed!
:::    Checking for bsdmainutils... already installed!
:::    Checking for dhcpcd5... already installed!
:::    Checking for iptables-persistent... already installed!
::: Static IP already configured.
::: Using User: pi
:::
::: Checking for existing base files...
:::    Checking /usr/local/src/pivpn is a repo...:::     Updating repo in /usr/local/src/pivpn...main: line 967: cd: /usr/local/src/pivpn: No such file or directory
 I try to flash sd card with clean installation but nothing change. any suggestion? thanks

**Comment by orazioedoardo** [comment]
Every week the same issue. Do you guys even read the FAQ or at least existing issues to look for a solution?
