### ISSUE TITLE
[Support] <How to remove all logs?>

### ISSUE THREAD

**Issue by RaspberryTech01** [pivpn/pivpn#1102]
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

### Issue
Hi! I was wondering if its possible to remove all logs from wireguard? For example, if I list connected clients it shows their public IP address. I was wondering if its possible to prevent this from showing. Are there any other logs and where can I find them?/*

### Have you searched for similar issues and solutions?
    (yes/no / which issues?)
yes, looked on google and FAQ but found nothing.

**Comment by orazioedoardo** [comment]
By default, WireGuard does not save any log. `pivpn -c` gets the list of connected clients via `wg show wg0`, whose content is kept in memory (RAM) until you stop or restart the interface `sudo systemctl restart wg-quick@wg0`. There is no built in way to prevent this from showing.

**Comment by RaspberryTech01** [comment]
If I have a script which restarts wg-quick@wg0, will the users that are connected lose connection, and if so for how many seconds roughly?

**Comment by orazioedoardo** [comment]
> will the users that are connected lose connection

Yes.

> for how many seconds roughly?

According to the WireGuard white paper, it should be 5 seconds.

By the way, you can still figure out who is connected by capturing traffic on the physical interface (eth0, wlan0).

**Comment by RaspberryTech01** [comment]
I see thank you.
