### ISSUE TITLE
[BUG] Unattended upgrades and apt sources point to Bullseye (Raspbian)

### ISSUE THREAD

**Issue by Flint4** [pivpn/pivpn#1103]
## In raising this issue, I confirm the following: 

- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

**Describe the bug**
I have installed PiVPN with Wireguard VPN on Raspbian Buster. During PiVPN installation I accepted set-up of unattended upgrades. 

After installation I noticed that PiVPN adds repository `deb http://raspbian.raspberrypi.org/raspbian/ bullseye main` in /etc/apt/sources.list.d/pivpn-bullseye.list. Additionally, it adds `"o=Raspbian,n=bullseye";` into /etc/apt/apt.conf.d/50unattended-upgrades

For systems not using Raspbian Bullseye, PiVPN should not force Bullseye repository without asking. I'd expect PiVPN to enable unattended upgrades for the currently installed OS version only, in my case Buster. 

Best regards, 
Alex

**Comment by orazioedoardo** [comment]
Bullseye repository is added only to install WireGuard and APT pinning [is used](https://github.com/pivpn/pivpn/blob/32bd1c628af9e1926f3f4471c0bf49c74deff7c7/auto_install/install.sh#L1262-L1263) to prevent any other package from that repository from being pulled as updates for existing packages.

Unattended upgrades for the curren OS are already installed by virtue of having [these lines](https://github.com/pivpn/pivpn/blob/32bd1c628af9e1926f3f4471c0bf49c74deff7c7/files/etc/apt/apt.conf.d/50unattended-upgrades.Raspbian#L38-L42). `"o=Raspbian,n=bullseye";` is added to additionally upgrade packages from Bullseye repo (still, only WireGuard).

**Comment by orazioedoardo** [comment]
No replies in a while, closing...
