### ISSUE TITLE
[Support] No packets get through on otherwise successful installation of Wireguard on RPi4

### ISSUE THREAD

**Issue by smokemyshoes** [pivpn/pivpn#1105]
In raising this issue, I confirm the following: 
- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

Hi

I have just successfully installed Wireguard VPN with the PiVPN installer on a fresh installation of Raspberry OS Buster Lite on a RPi4 with only Pi-Hole 5 and Unbound (Recursive DNS resolver) already installed. Everything is fully updated and upgraded and installation went through without any errors and Pi-hole was detected.

After creating clients (scanning the QR codes) on two different iPhones I wasn't able to 'get through' to the Wireguard VPN server though on both phones it seemed like they were connected. 

The Raspberry Pi is connected to a (dumb) switch which is connected to my ISP's router/modem. I have disabled the router firewall completely (while troubleshooting) and DHCP+DNS is also completely disabled on the router and handled by Pi-Hole . I have reserved a Static IP to the RPi's MAC-adress in Pi-hole though I don't know if that's needed when the Pi-hole is handling DHCP.

On my router the port forwarding looks something like this:
```
LAN IP: 192.168.1.60
WAN port: 51820
LAN port: 51820
Protocol: Both <--- I know only UDP is needed but for troubleshooting
WAN IP: Any
```
I have followed the troubleshooting guide and searched open and closed issues without any success. It's probably trivial but I'm not that savvy.  Here's the output of my troubleshooting:

`pi@raspberrypi:~ $ pivpn -d`
```
::::		PiVPN debug		 ::::
=============================================
::::		Latest commit		 ::::
commit 32bd1c628af9e1926f3f4471c0bf49c74deff7c7 (grafted, HEAD -> master, origin/test, origin/master, origin/HEAD)
Author: Orazio <orazioedoardo@users.noreply.github.com>
Date:   Fri Jul 24 18:52:57 2020 +0200

    Update LatestUpdate.md
=============================================
::::	    Installation settings    	 ::::
PLAT=Raspbian
OSCN=buster
USING_UFW=0
IPv4dev=eth0
dhcpReserv=1
IPv4addr=192.168.1.60/24
IPv4gw=192.168.1.254
install_user=pi
install_home=/home/pi
VPN=wireguard
pivpnPORT=51820
pivpnDNS1=10.6.0.1
pivpnDNS2=
pivpnHOST=REDACTED
INPUT_CHAIN_EDITED=0
FORWARD_CHAIN_EDITED=0
pivpnPROTO=udp
pivpnDEV=wg0
pivpnNET=10.6.0.0
subnetClass=24
UNATTUPG=1
INSTALLED_PACKAGES=(iptables-persistent wireguard wireguard-tools wireguard-dkms)
=============================================
::::  Server configuration shown below   ::::
[Interface]
PrivateKey = server_priv
Address = 10.6.0.1/24
ListenPort = 51820
### begin YYYYIphone ###
[Peer]
PublicKey = XXXXIphone_pub
PresharedKey = XXXXIphone_psk
AllowedIPs = 10.6.0.2/32
### end XXXXIphone ###
### begin YYYYiPhone ###
[Peer]
PublicKey = YYYYiPhone_pub
PresharedKey = YYYYiPhone_psk
AllowedIPs = 10.6.0.3/32
### end YYYYiPhone ###
=============================================
::::  Client configuration shown below   ::::
[Interface]
PrivateKey = XXXXIphone_priv
Address = 10.6.0.2/24
DNS = 10.6.0.1

[Peer]
PublicKey = server_pub
PresharedKey = XXXXIphone_psk
Endpoint = REDACTED:51820
AllowedIPs = 0.0.0.0/0, ::0/0
=============================================
:::: 	Recursive list of files in	 ::::
::::	/etc/wireguard shown below	 ::::
/etc/wireguard:
configs  keys  wg0.conf

/etc/wireguard/configs:
clients.txt  YYYYiPhone.conf  XXXXIphone.conf

/etc/wireguard/keys:
YYYYiPhone_priv  YYYYiPhone_psk  YYYYiPhone_pub  server_priv  server_pub  XXXXIphone_priv  XXXXIphone_psk	XXXXIphone_pub
=============================================
::::		Self check		 ::::
:: [OK] IP forwarding is enabled
:: [OK] Iptables MASQUERADE rule set
:: [OK] WireGuard is running
:: [OK] WireGuard is enabled (it will automatically start on reboot)
:: [OK] WireGuard is listening on port 51820/udp
=============================================
:::: Having trouble connecting? Take a look at the FAQ:
:::: https://github.com/pivpn/pivpn/wiki/FAQ
=============================================
:::: WARNING: This script should have automatically masked sensitive       ::::
:::: information, however, still make sure that PrivateKey, PublicKey      ::::
:::: and PresharedKey are masked before reporting an issue. An example key ::::
:::: that you should NOT see in this log looks like this:                  ::::
:::: YIAoJVsdIeyvXfGGDDadHh6AxsMRymZTnnzZoAb9cxRe                          ::::
=============================================
::::		Debug complete		 ::::
```
`pi@raspberrypi:~ $ sudo systemctl restart wg-quick@wg0`
No message / output at all

`pi@raspberrypi:~ $ lsmod | grep wireguard`
```
wireguard             131072  0
ip6_udp_tunnel         16384  1 wireguard
udp_tunnel             16384  1 wireguard
ipv6                  450560  36 wireguard
```

`pi@raspberrypi:~ $ cat /etc/pivpn/wireguard/setupVars.conf`
```
PLAT=Raspbian
OSCN=buster
USING_UFW=0
IPv4dev=eth0
dhcpReserv=1
IPv4addr=192.168.1.60/24
IPv4gw=192.168.1.254
install_user=pi
install_home=/home/pi
VPN=wireguard
pivpnPORT=51820
pivpnDNS1=10.6.0.1
pivpnDNS2=
pivpnHOST=<MY_SUB-DOMAIN>.ignorelist.com
INPUT_CHAIN_EDITED=0
FORWARD_CHAIN_EDITED=0
pivpnPROTO=udp
pivpnDEV=wg0
pivpnNET=10.6.0.0
subnetClass=24
UNATTUPG=1
INSTALLED_PACKAGES=(iptables-persistent wireguard wireguard-tools wireguard-dkms)
```

`pi@raspberrypi:~ $ ip -f inet address show eth0`
```
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    inet 192.168.1.60/24 brd 192.168.1.255 scope global noprefixroute eth0
       valid_lft forever preferred_lft forever
```

`pi@raspberrypi:~ $ curl -s https://checkip.amazonaws.com`
`5.186.115.XXX`

`pi@raspberrypi:~ $ dig +short <MY_SUB-DOMAIN>.ignorelist.com`
`5.186.115.XXX`

`pi@raspberrypi:~ $ sudo -s`
`root@raspberrypi:/home/pi# tcpdump -n -i eth0 udp port 51820`
```
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on eth0, link-type EN10MB (Ethernet), capture size 262144 bytes
```
I then turned on two different tunnels using the Wireguard iOS app on two iPhones while connected to 4G and afterwards i tried to visit a webpage but connection timed-out. After a minute or so, no packages had been received or send.

`^C`
```
0 packets captured
0 packets received by filter
0 packets dropped by kernel
```
I hope this is enough information. But if not, please let me know, preferably with detailed instructions.

Thanks in advance!

**Comment by orazioedoardo** [comment]
Looking at your detailed report, everything seems ok. What kind of connection you have at home? Landline or cellular? Have you ever tried port forwarding in the past?

**Comment by smokemyshoes** [comment]
I have a fiber connection - so landline.

Yes, I've forwarded a few ports in the past - many years ago though.

My ISP provided router is an old piece of junk and the admin interface / options are pretty basic to say the least. I can try to dump a screenshot of the forwarded port this evening.

Could it be a iptables issue on the RPi? I have zero knowledge of iptables but if you can direct me, I can post some them for you.

**Comment by orazioedoardo** [comment]
> Could it be a iptables issue on the RPi? I have zero knowledge of iptables but if you can direct me, I can post some them for you.

Post the output of `sudo iptables -S` and `sudo iptables -S -t nat`. The thing is that tcpdump captures incoming traffic before iptables has a change to filter and potentially block so if `tcpdump -n -i eth0 udp port 51820` shows no output, it means that no packets are reaching the port, so I think it is a port forwarding issue.

Do you know if your ISP uses CGnat?

We can also do a simple port forward test for a TCP port (I saw you also have TCP forwarded).

-  Set up a netcat listener with `nc -l -v 51820`
- Then go to https://www.canyouseeme.org/ and check port 51820, can it see you?
 
Use CTRL-C to stop the listener.

**Comment by smokemyshoes** [comment]
I just called my ISP and it actually turned out that they they are using CGnat or what the technical support guy referred to as "extra nat'ing". I will check this evening if the issue have been resolved.

**Comment by smokemyshoes** [comment]
Hurray, It's working now. So it was my ISP's CGNAT that caused the problem.

I'm really sorry that I bothered you with helping me when it is now so obvious that I should just have checked with my ISP first.

And many many thanks for your great work - Who would have believed that you could have a state-of-the-art VPN server up and running on a Raspberry Pi in half an hour.

**Comment by orazioedoardo** [comment]
> Hurray, It's working now. So it was my ISP's CGNAT that caused the problem.
> 
> I'm really sorry that I bothered you with helping me when it is now so obvious that I should just have checked with my ISP first.

Actually this issue was resolved pretty fast since you actually followed the troubleshooting steps. You almost got there with the CGNAT: https://github.com/pivpn/pivpn/wiki/FAQ#what-to-do-if-i-see-no-packets

> Check if your ISP uses Carrier-grade NAT (check online). With CGNAT, your router gets a private IP, making port forwarding ineffective. This is mostly the norm if your router connects via 4G/LTE. If that's the case, you need to ask the ISP for a public IP.
