### ISSUE TITLE
obfs4proxy

### ISSUE THREAD

**Issue by meltinkernel** [pivpn/pivpn#1108]
Thank you very much for the fantastic pivpn project. I just want to ask you if its possible to add the obfs4proxy to the script. Because Currently some Deep Packet Inspector can detect openvpn traffic and block the traffic. It will be very useful to add this feature to the script.Thanks a lot.

**Comment by orazioedoardo** [comment]
Possibly, but depends on the effort required to automate it and the actual ease of use as well as effectiveness of the obfuscation. Can you explain how would that work in practice?

**Comment by sak171** [comment]
Hi

**Comment by meltinkernel** [comment]
> Possibly, but depends on the effort required to automate it and the actual ease of use as well as effectiveness of the obfuscation. Can you explain how would that work in practice?

Hi Orazioedoardo, simply ISP's use some packet analyzer like Wireshark to detect the type of the protocol which is being transferred, if the the type of the protocol is openvpn, then the packet will be dropped. You can find the useful information here in this link:
[](https://proprivacy.com/vpn/guides/openvpn-scramble-xor-obfuscation)
Also there is a project by HRomie on github to obfuscate openvpn traffic via obfs4 which is great check the link below:
[](https://github.com/HRomie/obfs4proxy-openvpn)
I think it would be great if this feature is integrated with the pivpn project. Thanks

**Comment by 4s3ti** [comment]
have my reservations if this is something pivpn should provide ... I completely understand the value of it, but still i am not really sure.

**Comment by 4s3ti** [comment]
some though on this, and don't think it should be implemented on pivpn, it could be another project that could work with pivpn and we could work into supporting it, as it works now for example with pi-hole, however not directly on PiVPN.
