### ISSUE TITLE
OpenVPN service not starting on Debian

### ISSUE THREAD

**Issue by contouredsolutions** [pivpn/pivpn#1109]
So, I attempted to run the install script on a new Debian VM install (the website says "It runs on any Debian VPS Server"). Everything seemed to install, but the OpenVPN service won't start. When I ran pivpn -d, it looks like some TLS file is missing (see image below). Not sure what would cause that or if the way I am trying to do this is even really supported. Should I use a particular version of Debian or just stick with a Raspberry Pi? If this install was messed up, can I run it again and start from scratch?

Please let me know. Thanks!

![image](https://user-images.githubusercontent.com/69371659/89695502-0dd04300-d8c9-11ea-95bd-557f2d12229e.png)

**Comment by orazioedoardo** [comment]
Closing as not following the issue template, reopen after providing such information.

**Comment by contouredsolutions** [comment]
Such information as what? My apologies, I have never used Github before.

Thank you in advanced for helping me resolve this issue.

**Comment by orazioedoardo** [comment]
When you open a support request you get this to fill.

> 
> 
> ## In raising this issue, I confirm the following: 
> 
> `{please fill the checkboxes, e.g: [X]}`
> 
> - [] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
> - [] The issue I am reporting can be *replicated*.
> - [] The issue I am reporting can be *is* directly related to the pivpn installer script.
> - [] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).
> 
> 
> 
> 
> 
> 
> 
> ### Issue
> 
> 
> ### Have you searched for similar issues and solutions?
>     (yes/no / which issues?)
> 
> 
> ### Console output of      `curl -L install.pivpn.dev | bash`
> ```
>   Output Here
> ```
> 
> 
> ### Console output of      `pivpn add` or `pivpn add nopass`
> ```
>   Output Here
> ```
> 
> ### Console output of      `pivpn debug`
> ```
>   Output Here
> ```
> ### Have you taken any steps towards solving your issue?
> ```
>   which?
> ```
>

**Comment by contouredsolutions** [comment]
Trying this again:


    [X] I have read and understood the contributors guide.
    [X] The issue I am reporting can be replicated.
    [X] The issue I am reporting can be is directly related to the pivpn installer script.
    [X] The issue I am reporting isn't a duplicate (see FAQs, closed issues, and open issues).

Issue
Have you searched for similar issues and solutions?

Yes. pivpn missing ta.key file. 

Console output of curl -L install.pivpn.dev | bash

`root@debian-vpn:/home/SOMEUSER# curl -L install.pivpn.dev | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     5  100     5    0     0     15      0 --:--:-- --:--:-- --:--:--    15
100   162  100   162    0     0    151      0  0:00:01  0:00:01 --:--:-- 54000
100 82755  100 82755    0     0  67225      0  0:00:01  0:00:01 --:--:-- 67225
:::
::: You are root.
::: Reconfigure option selected.
::: Hostname length OK
::: Verifying free disk space...
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: Your system is up to date! Continuing with PiVPN installation...
:::    Checking for git... already installed!
:::    Checking for tar... already installed!
:::    Checking for wget... already installed!
:::    Checking for curl... already installed!
:::    Checking for grep... already installed!
:::    Checking for dnsutils... already installed!
:::    Checking for whiptail... already installed!
:::    Checking for net-tools... already installed!
:::    Checking for bsdmainutils... already installed!
:::    Checking for iptables-persistent... already installed!
::: Using User: SOMEUSER
:::
::: Checking for existing base files...
:::    Checking /usr/local/src/pivpn is a repo... OK!
:::     Updating repo in /usr/local/src/pivpn... done!
::: Using VPN: OpenVPN
::: Installing OpenVPN from Debian package...
::: OpenVPN is already available in the repositories
:::    Checking for openvpn... already installed!
:::    Checking for grepcidr... already installed!
:::    Checking for expect... already installed!
::: Using Google servers.
::: Backing up the openvpn folder to /etc/openvpn_2020-08-24-141240.tar.gz
./easyrsa: 341: set: Illegal option -o echo
::: Building CA...
Using SSL: openssl OpenSSL 1.1.1d  10 Sep 2019
read EC key
writing EC key
./easyrsa: 341: set: Illegal option -o echo

::: CA Complete.

Note: using Easy-RSA configuration from: /etc/openvpn/easy-rsa/vars
Using SSL: openssl OpenSSL 1.1.1d  10 Sep 2019
Generating an EC private key
writing new private key to '/etc/openvpn/easy-rsa/pki/easy-rsa-1107.YrT3rV/tmp.FAK2Y2'
-----
Using configuration from /etc/openvpn/easy-rsa/pki/easy-rsa-1107.YrT3rV/tmp.oHNrEn
Check that the request matches the signature
Signature ok
The Subject's Distinguished Name is as follows
commonName            :ASN.1 12:'debian-vpn_9a43ed25-235f-4182-a291-804cf06585b6'
Certificate is to be certified until Aug 22 21:12:44 2030 GMT (3650 days)

Write out database with 1 new entries
Data Base Updated
./easyrsa: 341: set: Illegal option -o echo
main: line 1912: openvpn: command not found

Note: using Easy-RSA configuration from: /etc/openvpn/easy-rsa/vars
Using SSL: openssl OpenSSL 1.1.1d  10 Sep 2019
Using configuration from /etc/openvpn/easy-rsa/pki/easy-rsa-1186.tl7M1c/tmp.pUznEQ

An updated CRL has been created.
CRL file: /etc/openvpn/easy-rsa/pki/crl.pem

./easyrsa: 341: set: Illegal option -o echo
main: line 1918: adduser: command not found
chown: invalid user: 'openvpn:openvpn'
main: line 2056: sysctl: command not found
main: line 2091: iptables: command not found
main: line 2092: iptables: command not found
main: line 2101: iptables: command not found
main: line 2102: iptables: command not found
main: line 2104: iptables: command not found
main: line 2105: iptables: command not found
main: line 2112: iptables: command not found
main: line 2115: iptables: command not found
main: line 2123: iptables: command not found
main: line 2126: iptables: command not found
main: line 2127: iptables: command not found
main: line 2136: iptables-save: command not found
::: Install Complete...
::: Restarting services...
:::    Checking for unattended-upgrades... already installed!
::: Setupfiles copied to /etc/pivpn/openvpn/setupVars.conf
mkdir: cannot create directory '/etc/pivpn/openvpn/': File exists
::: Installing scripts to /opt/pivpn...
ln: failed to create symbolic link '/etc/bash_completion.d/pivpn': File exists
ln: failed to create symbolic link '/usr/local/bin/pivpn': File exists
 done.
::: Flushing writes to disk...
::: done.
:::
root@debian-vpn:/home/SOMEUSER#
`

Console output of pivpn add or pivpn add nopass

`root@debian-vpn:/home/SOMEUSER# pivpn add nopass
::: Create a client ovpn profile, optional nopass
:::
::: Usage: pivpn <-a|add> [-n|--name <arg>] [-p|--password <arg>]|[nopass] [-d|--days <number>] [-b|--bitwarden] [-i|--iOS] [-o|--ovpn] [-h|--help]
:::
::: Commands:
:::  [none]               Interactive mode
:::  nopass               Create a client without a password
:::  -n,--name            Name for the Client (default: 'debian-vpn')
:::  -p,--password        Password for the Client (no default)
:::  -d,--days            Expire the certificate after specified number of days (default: 1080)
:::  -b,--bitwarden       Create and save a client through Bitwarden
:::  -i,--iOS             Generate a certificate that leverages iOS keychain
:::  -o,--ovpn            Regenerate a .ovpn config file for an existing client
:::  -h,--help            Show this help dialog

Enter a Name for the Client:  dmartinez
How many days should the certificate last?  1080
spawn ./easyrsa build-client-full dmartinez nopass

Note: using Easy-RSA configuration from: /etc/openvpn/easy-rsa/vars
Using SSL: openssl OpenSSL 1.1.1d  10 Sep 2019
Generating an EC private key
writing new private key to '/etc/openvpn/easy-rsa/pki/easy-rsa-1431.IoIZCE/tmp.t5RmFA'
-----
Using configuration from /etc/openvpn/easy-rsa/pki/easy-rsa-1431.IoIZCE/tmp.NODYsJ
Check that the request matches the signature
Signature ok
The Subject's Distinguished Name is as follows
commonName            :ASN.1 12:'dmartinez'
Certificate is to be certified until Aug  9 21:14:41 2023 GMT (1080 days)

Write out database with 1 new entries
Data Base Updated

Client's cert found: dmartinez.crt
Client's Private Key found: dmartinez.key
CA public Key found: ca.crt
[ERROR]: tls Private Key not found: ta.key
root@debian-vpn:/home/SOMEUSER#`

Console output of pivpn debug

`root@debian-vpn:/home/SOMEUSER# pivpn debug
::: Generating Debug Output
::::            PiVPN debug              ::::
=============================================
::::            Latest commit            ::::
commit 32bd1c628af9e1926f3f4471c0bf49c74deff7c7
Author: Orazio <orazioedoardo@users.noreply.github.com>
Date:   Fri Jul 24 18:52:57 2020 +0200

    Update LatestUpdate.md
=============================================
::::        Installation settings        ::::
PLAT=Debian
OSCN=buster
USING_UFW=0
IPv4dev=ens18
install_user=SOMEUSER
install_home=/home/SOMEUSER
VPN=openvpn
pivpnPROTO=udp
pivpnPORT=1194
pivpnDNS1=8.8.8.8
pivpnDNS2=8.8.4.4
pivpnSEARCHDOMAIN=
pivpnHOST=REDACTED
TWO_POINT_FOUR=1
pivpnENCRYPT=256
USE_PREDEFINED_DH_PARAM=
INPUT_CHAIN_EDITED=1
FORWARD_CHAIN_EDITED=1
pivpnDEV=tun0
pivpnNET=10.8.0.0
subnetClass=24
UNATTUPG=1
INSTALLED_PACKAGES=()
HELP_SHOWN=1
=============================================
::::  Server configuration shown below   ::::
dev tun
proto udp
port 1194
ca /etc/openvpn/easy-rsa/pki/ca.crt
cert /etc/openvpn/easy-rsa/pki/issued/debian-vpn_9a43ed25-235f-4182-a291-804cf06585b6.crt
key /etc/openvpn/easy-rsa/pki/private/debian-vpn_9a43ed25-235f-4182-a291-804cf06585b6.key
dh none
ecdh-curve prime256v1
topology subnet
server 10.8.0.0 255.255.255.0
# Set your primary domain name server address for clients
push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 8.8.4.4"
# Prevent DNS leaks on Windows
push "block-outside-dns"
# Override the Client default gateway by using 0.0.0.0/1 and
# 128.0.0.0/1 rather than 0.0.0.0/0. This has the benefit of
# overriding but not wiping out the original default gateway.
push "redirect-gateway def1"
client-to-client
client-config-dir /etc/openvpn/ccd
keepalive 15 120
remote-cert-tls client
tls-version-min 1.2
tls-crypt /etc/openvpn/easy-rsa/pki/ta.key
cipher AES-256-CBC
auth SHA256
user openvpn
group openvpn
persist-key
persist-tun
crl-verify /etc/openvpn/crl.pem
status /var/log/openvpn-status.log 20
status-version 3
syslog
verb 3
#DuplicateCNs allow access control on a less-granular, per user basis.
#Remove # if you will manage access by user instead of device.
#duplicate-cn
# Generated for use by PiVPN.io
=============================================
::::  Client template file shown below   ::::
client
dev tun
proto udp
remote REDACTED 1194
resolv-retry infinite
nobind
remote-cert-tls server
tls-version-min 1.2
verify-x509-name debian-vpn_9a43ed25-235f-4182-a291-804cf06585b6 name
cipher AES-256-CBC
auth SHA256
auth-nocache
verb 3
=============================================
::::    Recursive list of files in       ::::
::: /etc/openvpn/easy-rsa/pki shows below :::
/etc/openvpn/easy-rsa/pki/:
ca.crt
crl.pem
Default.txt
ecparams
index.txt
index.txt.attr
index.txt.attr.old
index.txt.old
issued
openssl-easyrsa.cnf
private
renewed
revoked
safessl-easyrsa.cnf
serial
serial.old

/etc/openvpn/easy-rsa/pki/ecparams:
prime256v1.pem

/etc/openvpn/easy-rsa/pki/issued:
debian-vpn_9a43ed25-235f-4182-a291-804cf06585b6.crt
dmartinez.crt

/etc/openvpn/easy-rsa/pki/private:
ca.key
debian-vpn_9a43ed25-235f-4182-a291-804cf06585b6.key
dmartinez.key

/etc/openvpn/easy-rsa/pki/renewed:
private_by_serial
reqs_by_serial

/etc/openvpn/easy-rsa/pki/renewed/private_by_serial:

/etc/openvpn/easy-rsa/pki/renewed/reqs_by_serial:

/etc/openvpn/easy-rsa/pki/revoked:
private_by_serial
reqs_by_serial

/etc/openvpn/easy-rsa/pki/revoked/private_by_serial:

/etc/openvpn/easy-rsa/pki/revoked/reqs_by_serial:
=============================================
::::            Self check               ::::
:: [OK] IP forwarding is enabled
:: [ERR] Iptables MASQUERADE rule is not set, attempt fix now? [Y/n] Y
/opt/pivpn/self_check.sh: line 43: iptables: command not found
/opt/pivpn/self_check.sh: line 44: iptables-save: command not found
Done
:: [ERR] Iptables INPUT rule is not set, attempt fix now? [Y/n] Y
/opt/pivpn/self_check.sh: line 57: iptables: command not found
/opt/pivpn/self_check.sh: line 58: iptables-save: command not found
Done
:: [ERR] Iptables FORWARD rule is not set, attempt fix now? [Y/n] Y
/opt/pivpn/self_check.sh: line 72: iptables: command not found
/opt/pivpn/self_check.sh: line 73: iptables: command not found
/opt/pivpn/self_check.sh: line 74: iptables-save: command not found
Done
:: [OK] OpenVPN is running
:: [OK] OpenVPN is enabled (it will automatically start on reboot)
:: [ERR] OpenVPN is not listening, try to restart now? [Y/n] Y
Done
[INFO] Run pivpn -d again to see if we detect issues
=============================================
:::: Having trouble connecting? Take a look at the FAQ:
:::: https://github.com/pivpn/pivpn/wiki/FAQ
=============================================
::::      Snippet of the server log      ::::
Aug 24 14:15:42 debian-vpn ovpn-server[1536]: WARNING: cannot stat file '/etc/openvpn/easy-rsa/pki/ta.key': No such file or directory (errno=2)
Aug 24 14:15:42 debian-vpn ovpn-server[1536]: Options error: --tls-crypt fails with '/etc/openvpn/easy-rsa/pki/ta.key': No such file or directory (errno=2)
Aug 24 14:15:42 debian-vpn ovpn-server[1536]: Options error: Please correct these errors.
Aug 24 14:15:42 debian-vpn ovpn-server[1536]: Use --help for more information.
Aug 24 14:15:48 debian-vpn ovpn-server[1539]: WARNING: cannot stat file '/etc/openvpn/easy-rsa/pki/ta.key': No such file or directory (errno=2)
Aug 24 14:15:48 debian-vpn ovpn-server[1539]: Options error: --tls-crypt fails with '/etc/openvpn/easy-rsa/pki/ta.key': No such file or directory (errno=2)
Aug 24 14:15:48 debian-vpn ovpn-server[1539]: Options error: Please correct these errors.
Aug 24 14:15:48 debian-vpn ovpn-server[1539]: Use --help for more information.
Aug 24 14:15:53 debian-vpn ovpn-server[1542]: WARNING: cannot stat file '/etc/openvpn/easy-rsa/pki/ta.key': No such file or directory (errno=2)
Aug 24 14:15:53 debian-vpn ovpn-server[1542]: Options error: --tls-crypt fails with '/etc/openvpn/easy-rsa/pki/ta.key': No such file or directory (errno=2)
Aug 24 14:15:53 debian-vpn ovpn-server[1542]: Options error: Please correct these errors.
Aug 24 14:15:53 debian-vpn ovpn-server[1542]: Use --help for more information.
Aug 24 14:15:58 debian-vpn ovpn-server[1551]: WARNING: cannot stat file '/etc/openvpn/easy-rsa/pki/ta.key': No such file or directory (errno=2)
Aug 24 14:15:58 debian-vpn ovpn-server[1551]: Options error: --tls-crypt fails with '/etc/openvpn/easy-rsa/pki/ta.key': No such file or directory (errno=2)
Aug 24 14:15:58 debian-vpn ovpn-server[1551]: Options error: Please correct these errors.
Aug 24 14:15:58 debian-vpn ovpn-server[1551]: Use --help for more information.
Aug 24 14:16:03 debian-vpn ovpn-server[1561]: WARNING: cannot stat file '/etc/openvpn/easy-rsa/pki/ta.key': No such file or directory (errno=2)
Aug 24 14:16:03 debian-vpn ovpn-server[1561]: Options error: --tls-crypt fails with '/etc/openvpn/easy-rsa/pki/ta.key': No such file or directory (errno=2)
Aug 24 14:16:03 debian-vpn ovpn-server[1561]: Options error: Please correct these errors.
Aug 24 14:16:03 debian-vpn ovpn-server[1561]: Use --help for more information.
=============================================
::::            Debug complete           ::::
:::
::: Debug output completed above.
::: Copy saved to /tmp/debug.txt
:::
root@debian-vpn:/home/SOMEUSER#

`

Have you taken any steps towards solving your issue?

`I have attempted both a repair and a reinstallation`

**Comment by contouredsolutions** [comment]
Trying this again:


    [X] I have read and understood the contributors guide.
    [X] The issue I am reporting can be replicated.
    [X] The issue I am reporting can be is directly related to the pivpn installer script.
    [X] The issue I am reporting isn't a duplicate (see FAQs, closed issues, and open issues).

Issue
Have you searched for similar issues and solutions?

Yes. pivpn missing ta.key file. 

Console output of curl -L install.pivpn.dev | bash

`root@debian-vpn:/home/SOMEUSER# curl -L install.pivpn.dev | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     5  100     5    0     0     15      0 --:--:-- --:--:-- --:--:--    15
100   162  100   162    0     0    151      0  0:00:01  0:00:01 --:--:-- 54000
100 82755  100 82755    0     0  67225      0  0:00:01  0:00:01 --:--:-- 67225
:::
::: You are root.
::: Reconfigure option selected.
::: Hostname length OK
::: Verifying free disk space...
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: Your system is up to date! Continuing with PiVPN installation...
:::    Checking for git... already installed!
:::    Checking for tar... already installed!
:::    Checking for wget... already installed!
:::    Checking for curl... already installed!
:::    Checking for grep... already installed!
:::    Checking for dnsutils... already installed!
:::    Checking for whiptail... already installed!
:::    Checking for net-tools... already installed!
:::    Checking for bsdmainutils... already installed!
:::    Checking for iptables-persistent... already installed!
::: Using User: SOMEUSER
:::
::: Checking for existing base files...
:::    Checking /usr/local/src/pivpn is a repo... OK!
:::     Updating repo in /usr/local/src/pivpn... done!
::: Using VPN: OpenVPN
::: Installing OpenVPN from Debian package...
::: OpenVPN is already available in the repositories
:::    Checking for openvpn... already installed!
:::    Checking for grepcidr... already installed!
:::    Checking for expect... already installed!
::: Using Google servers.
::: Backing up the openvpn folder to /etc/openvpn_2020-08-24-141240.tar.gz
./easyrsa: 341: set: Illegal option -o echo
::: Building CA...
Using SSL: openssl OpenSSL 1.1.1d  10 Sep 2019
read EC key
writing EC key
./easyrsa: 341: set: Illegal option -o echo

::: CA Complete.

Note: using Easy-RSA configuration from: /etc/openvpn/easy-rsa/vars
Using SSL: openssl OpenSSL 1.1.1d  10 Sep 2019
Generating an EC private key
writing new private key to '/etc/openvpn/easy-rsa/pki/easy-rsa-1107.YrT3rV/tmp.FAK2Y2'
-----
Using configuration from /etc/openvpn/easy-rsa/pki/easy-rsa-1107.YrT3rV/tmp.oHNrEn
Check that the request matches the signature
Signature ok
The Subject's Distinguished Name is as follows
commonName            :ASN.1 12:'debian-vpn_9a43ed25-235f-4182-a291-804cf06585b6'
Certificate is to be certified until Aug 22 21:12:44 2030 GMT (3650 days)

Write out database with 1 new entries
Data Base Updated
./easyrsa: 341: set: Illegal option -o echo
main: line 1912: openvpn: command not found

Note: using Easy-RSA configuration from: /etc/openvpn/easy-rsa/vars
Using SSL: openssl OpenSSL 1.1.1d  10 Sep 2019
Using configuration from /etc/openvpn/easy-rsa/pki/easy-rsa-1186.tl7M1c/tmp.pUznEQ

An updated CRL has been created.
CRL file: /etc/openvpn/easy-rsa/pki/crl.pem

./easyrsa: 341: set: Illegal option -o echo
main: line 1918: adduser: command not found
chown: invalid user: 'openvpn:openvpn'
main: line 2056: sysctl: command not found
main: line 2091: iptables: command not found
main: line 2092: iptables: command not found
main: line 2101: iptables: command not found
main: line 2102: iptables: command not found
main: line 2104: iptables: command not found
main: line 2105: iptables: command not found
main: line 2112: iptables: command not found
main: line 2115: iptables: command not found
main: line 2123: iptables: command not found
main: line 2126: iptables: command not found
main: line 2127: iptables: command not found
main: line 2136: iptables-save: command not found
::: Install Complete...
::: Restarting services...
:::    Checking for unattended-upgrades... already installed!
::: Setupfiles copied to /etc/pivpn/openvpn/setupVars.conf
mkdir: cannot create directory '/etc/pivpn/openvpn/': File exists
::: Installing scripts to /opt/pivpn...
ln: failed to create symbolic link '/etc/bash_completion.d/pivpn': File exists
ln: failed to create symbolic link '/usr/local/bin/pivpn': File exists
 done.
::: Flushing writes to disk...
::: done.
:::
root@debian-vpn:/home/SOMEUSER#
`

Console output of pivpn add or pivpn add nopass

`root@debian-vpn:/home/SOMEUSER# pivpn add nopass
::: Create a client ovpn profile, optional nopass
:::
::: Usage: pivpn <-a|add> [-n|--name <arg>] [-p|--password <arg>]|[nopass] [-d|--days <number>] [-b|--bitwarden] [-i|--iOS] [-o|--ovpn] [-h|--help]
:::
::: Commands:
:::  [none]               Interactive mode
:::  nopass               Create a client without a password
:::  -n,--name            Name for the Client (default: 'debian-vpn')
:::  -p,--password        Password for the Client (no default)
:::  -d,--days            Expire the certificate after specified number of days (default: 1080)
:::  -b,--bitwarden       Create and save a client through Bitwarden
:::  -i,--iOS             Generate a certificate that leverages iOS keychain
:::  -o,--ovpn            Regenerate a .ovpn config file for an existing client
:::  -h,--help            Show this help dialog

Enter a Name for the Client:  dmartinez
How many days should the certificate last?  1080
spawn ./easyrsa build-client-full dmartinez nopass

Note: using Easy-RSA configuration from: /etc/openvpn/easy-rsa/vars
Using SSL: openssl OpenSSL 1.1.1d  10 Sep 2019
Generating an EC private key
writing new private key to '/etc/openvpn/easy-rsa/pki/easy-rsa-1431.IoIZCE/tmp.t5RmFA'
-----
Using configuration from /etc/openvpn/easy-rsa/pki/easy-rsa-1431.IoIZCE/tmp.NODYsJ
Check that the request matches the signature
Signature ok
The Subject's Distinguished Name is as follows
commonName            :ASN.1 12:'dmartinez'
Certificate is to be certified until Aug  9 21:14:41 2023 GMT (1080 days)

Write out database with 1 new entries
Data Base Updated

Client's cert found: dmartinez.crt
Client's Private Key found: dmartinez.key
CA public Key found: ca.crt
[ERROR]: tls Private Key not found: ta.key
root@debian-vpn:/home/SOMEUSER#`

Console output of pivpn debug

`root@debian-vpn:/home/SOMEUSER# pivpn debug
::: Generating Debug Output
::::            PiVPN debug              ::::
=============================================
::::            Latest commit            ::::
commit 32bd1c628af9e1926f3f4471c0bf49c74deff7c7
Author: Orazio <orazioedoardo@users.noreply.github.com>
Date:   Fri Jul 24 18:52:57 2020 +0200

    Update LatestUpdate.md
=============================================
::::        Installation settings        ::::
PLAT=Debian
OSCN=buster
USING_UFW=0
IPv4dev=ens18
install_user=SOMEUSER
install_home=/home/SOMEUSER
VPN=openvpn
pivpnPROTO=udp
pivpnPORT=1194
pivpnDNS1=8.8.8.8
pivpnDNS2=8.8.4.4
pivpnSEARCHDOMAIN=
pivpnHOST=REDACTED
TWO_POINT_FOUR=1
pivpnENCRYPT=256
USE_PREDEFINED_DH_PARAM=
INPUT_CHAIN_EDITED=1
FORWARD_CHAIN_EDITED=1
pivpnDEV=tun0
pivpnNET=10.8.0.0
subnetClass=24
UNATTUPG=1
INSTALLED_PACKAGES=()
HELP_SHOWN=1
=============================================
::::  Server configuration shown below   ::::
dev tun
proto udp
port 1194
ca /etc/openvpn/easy-rsa/pki/ca.crt
cert /etc/openvpn/easy-rsa/pki/issued/debian-vpn_9a43ed25-235f-4182-a291-804cf06585b6.crt
key /etc/openvpn/easy-rsa/pki/private/debian-vpn_9a43ed25-235f-4182-a291-804cf06585b6.key
dh none
ecdh-curve prime256v1
topology subnet
server 10.8.0.0 255.255.255.0
# Set your primary domain name server address for clients
push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 8.8.4.4"
# Prevent DNS leaks on Windows
push "block-outside-dns"
# Override the Client default gateway by using 0.0.0.0/1 and
# 128.0.0.0/1 rather than 0.0.0.0/0. This has the benefit of
# overriding but not wiping out the original default gateway.
push "redirect-gateway def1"
client-to-client
client-config-dir /etc/openvpn/ccd
keepalive 15 120
remote-cert-tls client
tls-version-min 1.2
tls-crypt /etc/openvpn/easy-rsa/pki/ta.key
cipher AES-256-CBC
auth SHA256
user openvpn
group openvpn
persist-key
persist-tun
crl-verify /etc/openvpn/crl.pem
status /var/log/openvpn-status.log 20
status-version 3
syslog
verb 3
#DuplicateCNs allow access control on a less-granular, per user basis.
#Remove # if you will manage access by user instead of device.
#duplicate-cn
# Generated for use by PiVPN.io
=============================================
::::  Client template file shown below   ::::
client
dev tun
proto udp
remote REDACTED 1194
resolv-retry infinite
nobind
remote-cert-tls server
tls-version-min 1.2
verify-x509-name debian-vpn_9a43ed25-235f-4182-a291-804cf06585b6 name
cipher AES-256-CBC
auth SHA256
auth-nocache
verb 3
=============================================
::::    Recursive list of files in       ::::
::: /etc/openvpn/easy-rsa/pki shows below :::
/etc/openvpn/easy-rsa/pki/:
ca.crt
crl.pem
Default.txt
ecparams
index.txt
index.txt.attr
index.txt.attr.old
index.txt.old
issued
openssl-easyrsa.cnf
private
renewed
revoked
safessl-easyrsa.cnf
serial
serial.old

/etc/openvpn/easy-rsa/pki/ecparams:
prime256v1.pem

/etc/openvpn/easy-rsa/pki/issued:
debian-vpn_9a43ed25-235f-4182-a291-804cf06585b6.crt
dmartinez.crt

/etc/openvpn/easy-rsa/pki/private:
ca.key
debian-vpn_9a43ed25-235f-4182-a291-804cf06585b6.key
dmartinez.key

/etc/openvpn/easy-rsa/pki/renewed:
private_by_serial
reqs_by_serial

/etc/openvpn/easy-rsa/pki/renewed/private_by_serial:

/etc/openvpn/easy-rsa/pki/renewed/reqs_by_serial:

/etc/openvpn/easy-rsa/pki/revoked:
private_by_serial
reqs_by_serial

/etc/openvpn/easy-rsa/pki/revoked/private_by_serial:

/etc/openvpn/easy-rsa/pki/revoked/reqs_by_serial:
=============================================
::::            Self check               ::::
:: [OK] IP forwarding is enabled
:: [ERR] Iptables MASQUERADE rule is not set, attempt fix now? [Y/n] Y
/opt/pivpn/self_check.sh: line 43: iptables: command not found
/opt/pivpn/self_check.sh: line 44: iptables-save: command not found
Done
:: [ERR] Iptables INPUT rule is not set, attempt fix now? [Y/n] Y
/opt/pivpn/self_check.sh: line 57: iptables: command not found
/opt/pivpn/self_check.sh: line 58: iptables-save: command not found
Done
:: [ERR] Iptables FORWARD rule is not set, attempt fix now? [Y/n] Y
/opt/pivpn/self_check.sh: line 72: iptables: command not found
/opt/pivpn/self_check.sh: line 73: iptables: command not found
/opt/pivpn/self_check.sh: line 74: iptables-save: command not found
Done
:: [OK] OpenVPN is running
:: [OK] OpenVPN is enabled (it will automatically start on reboot)
:: [ERR] OpenVPN is not listening, try to restart now? [Y/n] Y
Done
[INFO] Run pivpn -d again to see if we detect issues
=============================================
:::: Having trouble connecting? Take a look at the FAQ:
:::: https://github.com/pivpn/pivpn/wiki/FAQ
=============================================
::::      Snippet of the server log      ::::
Aug 24 14:15:42 debian-vpn ovpn-server[1536]: WARNING: cannot stat file '/etc/openvpn/easy-rsa/pki/ta.key': No such file or directory (errno=2)
Aug 24 14:15:42 debian-vpn ovpn-server[1536]: Options error: --tls-crypt fails with '/etc/openvpn/easy-rsa/pki/ta.key': No such file or directory (errno=2)
Aug 24 14:15:42 debian-vpn ovpn-server[1536]: Options error: Please correct these errors.
Aug 24 14:15:42 debian-vpn ovpn-server[1536]: Use --help for more information.
Aug 24 14:15:48 debian-vpn ovpn-server[1539]: WARNING: cannot stat file '/etc/openvpn/easy-rsa/pki/ta.key': No such file or directory (errno=2)
Aug 24 14:15:48 debian-vpn ovpn-server[1539]: Options error: --tls-crypt fails with '/etc/openvpn/easy-rsa/pki/ta.key': No such file or directory (errno=2)
Aug 24 14:15:48 debian-vpn ovpn-server[1539]: Options error: Please correct these errors.
Aug 24 14:15:48 debian-vpn ovpn-server[1539]: Use --help for more information.
Aug 24 14:15:53 debian-vpn ovpn-server[1542]: WARNING: cannot stat file '/etc/openvpn/easy-rsa/pki/ta.key': No such file or directory (errno=2)
Aug 24 14:15:53 debian-vpn ovpn-server[1542]: Options error: --tls-crypt fails with '/etc/openvpn/easy-rsa/pki/ta.key': No such file or directory (errno=2)
Aug 24 14:15:53 debian-vpn ovpn-server[1542]: Options error: Please correct these errors.
Aug 24 14:15:53 debian-vpn ovpn-server[1542]: Use --help for more information.
Aug 24 14:15:58 debian-vpn ovpn-server[1551]: WARNING: cannot stat file '/etc/openvpn/easy-rsa/pki/ta.key': No such file or directory (errno=2)
Aug 24 14:15:58 debian-vpn ovpn-server[1551]: Options error: --tls-crypt fails with '/etc/openvpn/easy-rsa/pki/ta.key': No such file or directory (errno=2)
Aug 24 14:15:58 debian-vpn ovpn-server[1551]: Options error: Please correct these errors.
Aug 24 14:15:58 debian-vpn ovpn-server[1551]: Use --help for more information.
Aug 24 14:16:03 debian-vpn ovpn-server[1561]: WARNING: cannot stat file '/etc/openvpn/easy-rsa/pki/ta.key': No such file or directory (errno=2)
Aug 24 14:16:03 debian-vpn ovpn-server[1561]: Options error: --tls-crypt fails with '/etc/openvpn/easy-rsa/pki/ta.key': No such file or directory (errno=2)
Aug 24 14:16:03 debian-vpn ovpn-server[1561]: Options error: Please correct these errors.
Aug 24 14:16:03 debian-vpn ovpn-server[1561]: Use --help for more information.
=============================================
::::            Debug complete           ::::
:::
::: Debug output completed above.
::: Copy saved to /tmp/debug.txt
:::
root@debian-vpn:/home/SOMEUSER#

`

Have you taken any steps towards solving your issue?

`I have attempted both a repair and a reinstallation`
