### ISSUE TITLE
Debian iptables-persistent vs Ubuntu netfilter-persistent

### ISSUE THREAD

**Issue by fNCZsp5AV5n8d5** [pivpn/pivpn#1110]
I tried running the bash installer but recieved the error "failed to install iptables-persistent." I tried installing on Odroid hardware from an Armbian Ubuntu 5.6 server image. It seems Ubuntu uses 'netfilter-persistent' instead of 'iptables-persistent' via this site/comment: https://askubuntu.com/questions/941315/failed-to-start-iptables-persistent-service

When I run the netfilter command, it is active from my screenshot. I feel a potential solution for the script installer may be an if-then statement for 'iptables-persistent' & 'netfilter-persistent'.

I was attempting to test my Odroid hw to replace my slower Rasp-Pi. I tried the testing branch installer too see if that possibly addressed netfilter but it also failed. I will try an Odroid Armbian Debian server image but I feel adding code to address netfilter is required to support Ubuntu via the installer.

I'm willing to help to test but my linux knowlegde is limited and coding skills DNE.

![Screenshot_2020-08-09_16-16-20](https://user-images.githubusercontent.com/64604784/89741587-0011ed80-da82-11ea-9763-7bdd5308a9d8.png)

**Comment by orazioedoardo** [comment]
iptables-persistent on Ubuntu has netfilter-persistent as a dependency: https://packages.ubuntu.com/bionic/iptables-persistent

Maybe Armbian repositories only have netfilter-persistent? `cat /etc/apt/sources.list /etc/apt/sources.list.d/*`

**Comment by orazioedoardo** [comment]
No replies in a while, closing...

**Comment by sunjam** [comment]
@orazioedoardo I'm also running into trouble with `Failed to install iptables-persistent`.  To answer your repository question above...

```
$ cat /etc/apt/sources.list /etc/apt/sources.list.d/*
deb http://deb.debian.org/debian buster main contrib non-free
#deb-src http://deb.debian.org/debian buster main contrib non-free

deb http://deb.debian.org/debian buster-updates main contrib non-free
#deb-src http://deb.debian.org/debian buster-updates main contrib non-free

deb http://deb.debian.org/debian buster-backports main contrib non-free
#deb-src http://deb.debian.org/debian buster-backports main contrib non-free

deb http://security.debian.org/ buster/updates main contrib non-free
#deb-src http://security.debian.org/ buster/updates main contrib non-free
deb http://apt.armbian.com buster main buster-utils buster-desktop
deb [arch=arm64] https://download.docker.com/linux/debian buster edge

```

However, it does seem that iptables-persistent is already installed on Debian Buster.
```
$ sudo apt-get install iptables-persistent
Reading package lists... Done
Building dependency tree       
Reading state information... Done
iptables-persistent is already the newest version (1.0.11).
```

**Comment by orazioedoardo** [comment]
@sunjam What's the output of `dpkg-query -W -f='${Status}' "iptables-persistent"`?

**Comment by sunjam** [comment]
> @sunjam What's the output of `dpkg-query -W -f='${Status}' "iptables-persistent"`?

$ dpkg-query -W -f='${Status}' "iptables-persistent"
install ok half-configured

**Comment by orazioedoardo** [comment]
The package is not completely installed (otherwise it would show `install ok installed`), remove it with `sudo apt remove iptables-persistent` and reinstall pivpn. It should reconfigure automatically.

**Comment by sunjam** [comment]
> The package is not completely installed (otherwise it would show `install ok installed`), remove it with `sudo apt remove iptables-persistent` and reinstall pivpn. It should reconfigure automatically.

hmm, Installer still fails after removal,.  But `sudo apt remove iptables-persistent && sudo apt-get install iptables-persistent` succeeded. Installer works now.
