### ISSUE TITLE
No files in opvns along with error

### ISSUE THREAD

**Issue by jobensingh** [pivpn/pivpn#112]
Hi, when I try to do pivpn add and go through the prompts, I get an error at the end, as well as my ovpns folder being empty. I have tried reinstalling which hasnt worked. The error is [ERROR]: tls-auth Key not found: ta.key

**Comment by redfast00** [comment]
Can you give me the output of `sudo ls /etc/openvpn/easy-rsa/keys/`?

**Comment by jobensingh** [comment]
01.pem  Default.txt     index.txt.attr.old  server.crt     Test.crt
02.pem  dh2048.pem      index.txt.old       server.csr     Test.csr
ca.crt  index.txt       serial              server.key     Test.key
ca.key  index.txt.attr  serial.old          Test.3des.key

**Comment by redfast00** [comment]
Well, that's really odd. What platform are you on? Can you reinstall and give me a full log? Can you give me the output of `sudo openvpn --genkey --secret /dev/stdout`? Thanks!

**Comment by jobensingh** [comment]
Sorry for the long time no reply, But I have it working now. In the past before posting this issue I had tried reinstalling pivpn, and reinstalling raspbian all together to no avail. Now I did it and it suddenly began working. To my knowledge I didnt do anything really different. Thanks for the help!
