### ISSUE TITLE
Way to Use PiVPN w/o Public IP?

### ISSUE THREAD

**Issue by craftcm** [pivpn/pivpn#1121]
I’ve been running PiVPN successfully for a couple of years, but live in an apartment community where tenets are provided with internet access. While I was previously assigned a public IP address that was exposed to the internet, I’ve since been moved over to a private WAN IP with no way to get the provider to switch me back to a public IP. Is there any way to successfully use PiVPN in a situation like this? I don’t have access to any external port forwarding. Thank you for any guidance.

**Comment by orazioedoardo** [comment]
Not directly but you could use a second Raspberry Pi or server with PiVPN (publicly accessible) as a relay. It requires specific firewall and routing configuration on both networks.

**Comment by orazioedoardo** [comment]
No replies in a while, closing...
