### ISSUE TITLE
[Support] Input/Output Error

### ISSUE THREAD

**Issue by Racso93** [pivpn/pivpn#1123]
`{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

### Issue
I am trying to install PiVPN as explained in the documentation, but I get an error when getting the files from the repository (see the coinsole output)

### Have you searched for similar issues and solutions?
    (yes/no / which issues?)
Yes, I have found a few issues on here, bit none completely match the error and none solve the issue.

### Console output of      `curl -L install.pivpn.dev | bash`
```
root@raspberrypi:/home/pi/prueba# curl -L https://install.pivpn.io | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   162  100   162    0     0    582      0 --:--:-- --:--:-- --:--:--   584
100 82755  100 82755    0     0   154k      0 --:--:-- --:--:-- --:--:--  338k
:::
::: You are root.
::: Hostname length OK
::: Verifying free disk space...
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: Your system is up to date! Continuing with PiVPN installation...
:::    Checking for git... already installed!
:::    Checking for tar... already installed!
:::    Checking for wget... already installed!
:::    Checking for curl... already installed!
:::    Checking for grep... already installed!
:::    Checking for dnsutils... already installed!
:::    Checking for whiptail... already installed!
:::    Checking for net-tools... already installed!
:::    Checking for bsdmainutils... already installed!
:::    Checking for dhcpcd5... already installed!
:::    Checking for iptables-persistent... already installed!
::: Static IP already configured.
::: Using User: pi
:::
::: Checking for existing base files...
:::    Checking /usr/local/src/pivpn is a repo...:::    Cloning https://github.com/pivpn/pivpn.git into /usr/local/src/pivpn... [\]  fatal: cannot exec 'fetch-pack': Input/output error
main: line 989: cd: /usr/local/src/pivpn: No such file or directory
```

**Comment by orazioedoardo** [comment]
`Input/output error` means that your SD card may be failing. What's the output of `dmesg --level=err`, assuming you haven't rebooted after seeing such error?

**Comment by rockford11** [comment]
I am running into a similar issue. the same message without the "fatal: cannot exec 'fetch-pack' : Input/output error". I have /usr/local/src/pivpn...main: line 989: cd: /usr/local/src/pivpn: No such file or directory.

**Comment by 4s3ti** [comment]
> Had the same issue on an octopi image.
> After browsing the code I figured out that the (sudo) git command was failing:
> `sudo git clone -q --depth 1 --no-single-branch https://github.com/pivpn/pivpn.git /usr/local/src/pivpn`
> 
> So I executed this manually and saw the following:
> 
> ```
> Please do not run git as root, your regular user account is enough :)
> 
> If you need to run git with root rights for some other application than
> what comes preinstalled on this image you can remove this sanity check:
> 
>     sudo rm /root/bin/git
> 
> You might have to restart your login session after doing that.
> ```
> 
> Executed `sudo rm /root/bin/git` and ran `curl -L https://install.pivpn.io | bash` again, the installation continued without errors tada

you could have been spared all the trouble if you have checked the wiki :p

https://github.com/pivpn/pivpn/wiki#what-about-octopi
