### ISSUE TITLE
[BUG] <Bug Description Here>

### ISSUE THREAD

**Issue by MakeSenseIoT** [pivpn/pivpn#1124]
Installation on RPi 4 64 bit doesn't give me an option to select Wireguard, installs OpenVPN without user choice
pi@raspberrypi:~# uname -a
Linux raspberrypi 5.4.51-v8+ #1333 SMP PREEMPT Mon Aug 10 16:58:35 BST 2020 aarch64 GNU/Linux
Kindly advice how to fix it

**Comment by orazioedoardo** [comment]
No issue template, no title, did not read existing issues. The answer has been given multiple times.
