### ISSUE TITLE
Error No such file or directory

### ISSUE THREAD

**Issue by manoleitor97** [pivpn/pivpn#1125]
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*.
- [] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

**Describe the bug**
Hello, Im new in the raspberry and the github world. I Installed the PiVpn on my Raspberry so I can have a OpenVpn client on it and It worked fine. But I'm an idiot and then I installed octoprint later on the Raspberry. Of course, all my VPN dissapeared. So I started to install PiVpn again on my Raspberry, now with Octopi installed before and using PuTTy. But now when I'm trying to install it, it says: "cd: /usr/local/src/pivpn: No such file or directory" After picking the user (pi). I don't know what happened but I tried to create the folder by myself and when I run the installation, It gets eliminated.

Sorry If I don't explain myself or send the right information but I'm a completely noob. Thanks in advance,

**To Reproduce**
pi@octopi:~ $ curl -L https://install.pivpn.io | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   162  100   162    0     0    251      0 --:--:-- --:--:-- --:--:--   251
100 82755  100 82755    0     0  71587      0  0:00:01  0:00:01 --:--:-- 71587
:::
::: sudo will be used for the install.
::: Hostname length OK
::: Verifying free disk space...
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: Your system is up to date! Continuing with PiVPN installation...
[sudo] password for pi:
:::    Checking for git... already installed!
:::    Checking for tar... already installed!
:::    Checking for wget... already installed!
:::    Checking for curl... already installed!
:::    Checking for grep... already installed!
:::    Checking for dnsutils... already installed!
:::    Checking for whiptail... already installed!
:::    Checking for net-tools... already installed!
:::    Checking for bsdmainutils... already installed!
:::    Checking for dhcpcd5... already installed!
:::    Checking for iptables-persistent... already installed!
::: Static IP already configured.
::: Using User: pi
:::
::: Checking for existing base files...
:::    Checking /usr/local/src/pivpn is a repo...:::    Cloning https://github.c                              om/pivpn/pivpn.git into /usr/local/src/pivpn...main: line 989: cd: /usr/local/sr                              c/pivpn: No such file or directory

**Comment by orazioedoardo** [comment]
Duplicate issue https://github.com/pivpn/pivpn/wiki#what-about-octopi
