### ISSUE TITLE
[Support] No packets received via WireGuard and Pi-Hole (Raspberry Pi 2)

### ISSUE THREAD

**Issue by eastonj98** [pivpn/pivpn#1126]
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

### Issue
I have successfully installed PiVPN with WireGuard on my Raspberry Pi 2B v1.1 and configured it to work with Pi-Hole on the same device.

Unfortunately, WireGuard does not seem to work. If I run `pivpn -qr` followed by my device index (`1`) and add it on my phone using the app, when I connect, it doesn't seem to make a connection at all. The app displays no error messages, but when trying to load anything on the internet (or anything on my router's LAN), nothing happens. The error Google Chrome on Android gives me is `DNS_PROBE_FINISHED_NO_INTERNET`.

 I'll list a few things below to make life easier for everyone:

- ISP: `Sky (GB)`
- Router Default Gateway: `192.168.0.1`
- Public IP Configuration: Configured to use my dynamic DNS (`xxxxxx.ddns.net`)
- Pi's Address: `192.168.0.62 `
- PiVPN Server Address: `10.6.0.1/24`
- PiVPN Port: `53133`

My router is port-forwarding port `53133` to `192.168.0.62` (Set as the "Destination IPv4 Address").

### Have you searched for similar issues and solutions?
Yes, I'll list suggestions found on the internet that have not worked:

- Changing Pi-Hole to "Listen on all interfaces, permit all origins"
- Changing the port to something else in case the router is blocking it
- Checking that the DDNS hostname has the correct IP
- Checking that the config is using the correct DNS IP (which it is, in that it is using the address of my Pi)

### Console output of      `pivpn add` or `pivpn add nopass`
```
  pi@raspberrypi:~ $ pivpn add
Enter a Name for the Client: SupportTest
::: Client Keys generated
::: Client config generated
::: Updated server config
::: Updated hosts file for Pi-hole
::: WireGuard restarted
======================================================================
::: Done! SupportTest.conf successfully created!
::: SupportTest.conf was copied to /home/pi/configs for easy transfer.
::: Please use this profile only on one device and create additional
::: profiles for other devices. You can also use pivpn -qr
::: to generate a QR Code you can scan with the mobile app.
======================================================================
```

### Console output of      `pivpn debug`
```
pi@raspberrypi:~ $ pivpn debug
::::            PiVPN debug              ::::
=============================================
::::            Latest commit            ::::
commit 32bd1c628af9e1926f3f4471c0bf49c74deff7c7 (grafted, HEAD -> master, origin/test, origin/master, origin/HEAD)
Author: Orazio <orazioedoardo@users.noreply.github.com>
Date:   Fri Jul 24 18:52:57 2020 +0200

    Update LatestUpdate.md
=============================================
::::        Installation settings        ::::
PLAT=Raspbian
OSCN=buster
USING_UFW=0
IPv4dev=eth0
dhcpReserv=1
IPv4addr=192.168.0.62/24
IPv4gw=192.168.0.1
install_user=pi
install_home=/home/pi
VPN=wireguard
pivpnPORT=53133
pivpnDNS1=192.168.0.62
pivpnHOST=REDACTED
INPUT_CHAIN_EDITED=0
FORWARD_CHAIN_EDITED=1
pivpnPROTO=udp
pivpnDEV=wg0
pivpnNET=10.6.0.0
subnetClass=24
UNATTUPG=1
INSTALLED_PACKAGES=(iptables-persistent unattended-upgrades)
=============================================
::::  Server configuration shown below   ::::
[Interface]
PrivateKey = server_priv
Address = 10.6.0.1/24
ListenPort = 53133
### begin DEV1 ###
[Peer]
PublicKey = DEV1_pub
PresharedKey = DEV1_psk
AllowedIPs = 10.6.0.2/32
### end DEV1 ###
### begin SupportTest ###
[Peer]
PublicKey = SupportTest_pub
PresharedKey = SupportTest_psk
AllowedIPs = 10.6.0.3/32
### end SupportTest ###
=============================================
::::  Client configuration shown below   ::::
[Interface]
PrivateKey = DEV1_priv
Address = 10.6.0.2/24
DNS = 192.168.0.62

[Peer]
PublicKey = server_pub
PresharedKey = DEV1_psk
Endpoint = <REDACTED-DDNS-HOSTNAME>:53133
AllowedIPs = 0.0.0.0/0, ::0/0
=============================================
::::    Recursive list of files in       ::::
::::    /etc/wireguard shown below       ::::
/etc/wireguard:
configs  keys  wg0.conf

/etc/wireguard/configs:
clients.txt  DEV1.conf  DEV1.conf

/etc/wireguard/keys:
DEV1_priv  DEV1_psk  DEV1_pub  server_priv  server_pub  SupportTest_priv  SupportTest_psk  SupportTest_pub
=============================================
::::            Self check               ::::
:: [OK] IP forwarding is enabled
:: [OK] Iptables MASQUERADE rule set
:: [OK] Iptables FORWARD rule set
:: [OK] WireGuard is running
:: [OK] WireGuard is enabled (it will automatically start on reboot)
:: [OK] WireGuard is listening on port 53133/udp
=============================================
:::: Having trouble connecting? Take a look at the FAQ:
:::: https://github.com/pivpn/pivpn/wiki/FAQ
=============================================
:::: WARNING: This script should have automatically masked sensitive       ::::
:::: information, however, still make sure that PrivateKey, PublicKey      ::::
:::: and PresharedKey are masked before reporting an issue. An example key ::::
:::: that you should NOT see in this log looks like this:                  ::::
:::: YIAoJVsdIeyvXfGGDDadHh6AxsMRymZTnnzZoAb9cxRe                          ::::
=============================================
::::            Debug complete           ::::

```
### Have you taken any steps towards solving your issue?
All the ones listed in "Have you searched for similar issues and solutions?" - along with completely re-installing the image on my Pi and then reinstalling Pi-Hole before PiVPN with WireGuard.

I then followed all the steps in the FAQ, including listening for packets. After a while, I realised nothing was coming through, so I `CTRL-C`'d out.

### Output of IPTABLES:
sudo iptables -S:
```
pi@raspberrypi:~ $ sudo iptables -S
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
-A FORWARD -d 10.6.0.0/24 -i eth0 -o wg0 -m conntrack --ctstate RELATED,ESTABLISHED -m comment --comment wireguard-forward-rule -j ACCEPT
-A FORWARD -s 10.6.0.0/24 -i wg0 -o eth0 -m comment --comment wireguard-forward-rule -j ACCEPT
-A FORWARD -i wg0 -j ACCEPT
-A FORWARD -o wg0 -j ACCEPT
```

sudo iptables -t nat -S:
```
pi@raspberrypi:~ $ sudo iptables -t nat -S
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P POSTROUTING ACCEPT
-P OUTPUT ACCEPT
-A POSTROUTING -s 10.6.0.0/24 -o eth0 -m comment --comment wireguard-nat-rule -j MASQUERADE
-A POSTROUTING -o eth0 -j MASQUERADE
```

**Comment by orazioedoardo** [comment]
See [this issue](https://github.com/pivpn/pivpn/issues/1105), you may have Carrier-Grade NAT or "double NAT", you should ask your ISP about that. Also, do you have more than one router on your network?

**Comment by eastonj98** [comment]
> See [this issue](https://github.com/pivpn/pivpn/issues/1105), you may have Carrier-Grade NAT or "double NAT", you should ask your ISP about that. Also, do you have more than one router on your network?

My apologies, I forgot to mention this - it's one of the first things I checked for. I used the [Windows Powershell method](https://www.itechtics.com/how-to-check-public-ip-address-using-command-line-in-windows-10/#PowerShell). The IP displayed in the browser was the same as the one listed in Powershell, so no CGNAT.

**Comment by orazioedoardo** [comment]
No sorry, you will always see a public IP there because server need a public IP to talk to you, however, this doesn't mean you are not under CGNAT. Being under CGNAT means that your home router is not internet facing but behind another router in the ISP network. That second router actually has the public IP you see. You should ask your ISP.

**Comment by eastonj98** [comment]
There's only one router. In the log page, the IP lease it is renewing is the same as the one listed in when I go to view my IP in Powershell and online. As such, I am convinced that CGNAT is not at play here, but unfortunately I have no way of contacting my ISP because I am not the account holder.

But if the router is displaying the same IP as the Powershell window and websites, surely it can't be CGNAT?

**Comment by orazioedoardo** [comment]
> There's only one router. In the log page, the IP lease it is renewing is the same as the one listed in when I go to view my IP in Powershell and online. As such, I am convinced that CGNAT is not at play here, but unfortunately I have no way of contacting my ISP because I am not the account holder.
> 
> But if the router is displaying the same IP as the Powershell window and websites, surely it can't be CGNAT?

If the router IP you are referring to is the "WAN IP" or "external IP", then it's likely that you are NOT under CGNAT. Try the netcat listener test as explained here (you need to forward an additional port for the test): https://github.com/pivpn/pivpn/issues/1105#issuecomment-669812440

**Comment by eastonj98** [comment]
I followed the steps listed in that article:

("PORT" below is TCP 53133)

> - Set up a netcat listener with nc -l -v PORT
> - Then go to https://www.canyouseeme.org/ and check port PORT

Strangely, [CanYouSeeMe](https://www.canyouseeme.org) could not see the port! I don't quite understand that. The `netcat` listener also returned no results. Maybe I am on CGNAT then :-/

**Comment by eastonj98** [comment]
I have no idea what has just happened, but for some reason WireGuard is now working. Haven't changed a thing. Computers, eh?
