### ISSUE TITLE
[Support]  Can't connect with WireGuard (followed FAQ)

### ISSUE THREAD

**Issue by JHerseth** [pivpn/pivpn#1128]
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

### Issue
Can't connect to pivpn using wireguard android client

### Have you searched for similar issues and solutions?
    no

### Console output of      `curl -L install.pivpn.dev | bash`
```
  Nothing - goes to installer
```

### Console output of      `pivpn add` or `pivpn add nopass`
```
    Enter a Name for the Client:
```

### Console output of      `pivpn debug`
```
  pi@raspberrypi:~ $ pivpn debug
::::            PiVPN debug              ::::
=============================================
::::            Latest commit            ::::
commit 32bd1c628af9e1926f3f4471c0bf49c74deff7c7 (grafted, HEAD -> master, origin/test, origin/master, origin/HEAD)
Author: Orazio <orazioedoardo@users.noreply.github.com>
Date:   Fri Jul 24 18:52:57 2020 +0200

    Update LatestUpdate.md
=============================================
::::        Installation settings        ::::
PLAT=Raspbian
OSCN=buster
USING_UFW=0
IPv4dev=wlan0
dhcpReserv=1
IPv4addr=192.168.1.38/24
IPv4gw=192.168.1.1
install_user=pi
install_home=/home/pi
VPN=wireguard
pivpnPORT=2707
pivpnDNS1=10.6.0.1
pivpnDNS2=
pivpnHOST=REDACTED
INPUT_CHAIN_EDITED=0
FORWARD_CHAIN_EDITED=0
pivpnPROTO=udp
pivpnDEV=wg0
pivpnNET=10.6.0.0
subnetClass=24
UNATTUPG=1
INSTALLED_PACKAGES=(raspberrypi-kernel-headers wireguard wireguard-tools wireguard-dkms qrencode unattended-upgrades)
=============================================
::::  Server configuration shown below   ::::
[Interface]
PrivateKey = server_priv
Address = 10.6.0.1/24
ListenPort = 2707
### begin jonas ###
[Peer]
PublicKey = jonas_pub
PresharedKey = jonas_psk
AllowedIPs = 10.6.0.3/32
### end jonas ###
=============================================
::::  Client configuration shown below   ::::
[Interface]
PrivateKey = jonas_priv
Address = 10.6.0.3/24
DNS = 10.6.0.1

[Peer]
PublicKey = server_pub
PresharedKey = jonas_psk
Endpoint = REDACTED:2707
AllowedIPs = 0.0.0.0/0, ::0/0
=============================================
::::    Recursive list of files in       ::::
::::    /etc/wireguard shown below       ::::
/etc/wireguard:
configs  keys  wg0.conf

/etc/wireguard/configs:
clients.txt  jonas.conf

/etc/wireguard/keys:
jonas_priv  jonas_psk  jonas_pub  server_priv  server_pub
=============================================
::::            Self check               ::::
:: [OK] IP forwarding is enabled
:: [OK] Iptables MASQUERADE rule set
:: [OK] WireGuard is running
:: [OK] WireGuard is enabled (it will automatically start on reboot)
:: [OK] WireGuard is listening on port 2707/udp
=============================================
:::: Having trouble connecting? Take a look at the FAQ:
:::: https://github.com/pivpn/pivpn/wiki/FAQ
=============================================
:::: WARNING: This script should have automatically masked sensitive       ::::
:::: information, however, still make sure that PrivateKey, PublicKey      ::::
:::: and PresharedKey are masked before reporting an issue. An example key ::::
:::: that you should NOT see in this log looks like this:                  ::::
:::: YIAoJVsdIeyvXfGGDDadHh6AxsMRymZTnnzZoAb9cxRe                          ::::
=============================================
::::            Debug complete           ::::
```
### Have you taken any steps towards solving your issue?
```
  All the steps in the FAQ

pi@raspberrypi:~ $ sudo iptables -S
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT

pi@raspberrypi:~ $ sudo iptables -t nat -S
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P POSTROUTING ACCEPT
-P OUTPUT ACCEPT
-A POSTROUTING -s 10.6.0.0/24 -o wlan0 -m comment --comment wireguard-nat-rule -j MASQUERADE

pi@raspberrypi:~ $ sudo netstat -anlp |grep 2707
udp        0      0 0.0.0.0:2707            0.0.0.0:*                           -
udp6       0      0 :::2707                 :::*                                -
```
I can add that I've set up portforwarding of 2707 to 192.168.1.38. I got a bunch of other rules set up for services running on my desktop computer, and they're accessible from the outside without issue,

**Comment by JHerseth** [comment]
changing my port to 27716 resolved the issue. Netstat shows nothing running on 2707 now, so I don't really know why it didn't work, as there should not have been any conflicts. You may close this if there is nothing to add.  If you want me to do something to figure out why it originally didn't work, please tell me :+1:

**Comment by orazioedoardo** [comment]
Maybe you had ddns set up but the IP wasn't updated yet and coincidentally it got updated after you changed the port.

**Comment by JHerseth** [comment]
@orazioedoardo I didn't use ddn(on purpose at least) , is there anything in the debug info indicating i did? I have a dynamic IP but it hasn't changed since 2016 so I have it memlrized :)

**Comment by orazioedoardo** [comment]
No, no info indicating that. It was just a random guess since I found unlikely that my first guess, that port 2707 was blocked by your ISP, could be right, since that port is uncommon.

**Comment by JHerseth** [comment]
> No, no info indicating that. It was just a random guess since I found unlikely that my first guess, that port 2707 was blocked by your ISP, could be right, since that port is uncommon.
> 
> I'm wondering if forwarding port 2707 for some other service works.

Good idea. I'll try it when I get home
