### ISSUE TITLE
[Support] pivpn -d shows "WireGuard is not running..."

### ISSUE THREAD

**Issue by jameswagar** [pivpn/pivpn#1130]
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

I have PiVPN WireGuard installed on a Debian 10 Linux container on Proxmox and pivpn -d shows that "WireGuard is not running" and also "WireGuard is not listening..." I cannot access the internet when connected to the WireGuard VPN.

It does not look like wg-quick is running or can find the "wg0" interface.

### Have you searched for similar issues and solutions?
    (yes/no / which issues?)

Yes. I searched for any issues showing "WireGuard is not running" or "listening"

### Console output of      `curl -L install.pivpn.dev | bash`
```
root@wireguard:~# curl -L install.pivpn.dev | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     5  100     5    0     0     14      0 --:--:-- --:--:-- --:--:--    14
100   162  100   162    0     0    158      0  0:00:01  0:00:01 --:--:--   158
100 82755  100 82755    0     0  76981      0  0:00:01  0:00:01 --:--:-- 76981
:::
::: You are root.
::: Repair option selected.
::: Hostname length OK
::: Verifying free disk space...
:::
::: Checking apt-get for upgraded packages.... done!
:::

::: Your system is up to date! Continuing with PiVPN installation...
:::    Checking for git... already installed!
:::    Checking for tar... already installed!
:::    Checking for wget... already installed!
:::    Checking for curl... already installed!
:::    Checking for grep... already installed!
:::    Checking for dnsutils... already installed!
:::    Checking for whiptail... already installed!
:::    Checking for net-tools... already installed!
:::    Checking for bsdmainutils... already installed!
:::    Checking for iptables-persistent... already installed!
::: PiVPN Automated Installer
::: This installer will transform your Debian host into an OpenVPN or WireGuard server!
::: Initiating network interface

::: Using interface: eth0
::: Since we think you are not using Raspbian, we will not configure a static IP for you.
::: wg will hold your ovpn configurations.
:::
::: Checking for existing base files...
:::    Checking /usr/local/src/pivpn is a repo... OK!
::: Repairing an existing installation, not downloading/updating local repos
::: WireGuard will be installed
::: Installing WireGuard from Debian package...
::: WireGuard is already available in the repositories
:::    Checking for linux-headers-amd64... already installed!
:::    Checking for wireguard... already installed!
:::    Checking for wireguard-tools... already installed!
:::    Checking for wireguard-dkms... already installed!
:::    Checking for qrencode... already installed!
::: Using port 51820
::: Using DNS 192.168.0.194 192.168.0.195
dig failed, now trying to curl checkip.amazonaws.com
::: Using domain name NAME.duckdns.org
::: Backing up the wireguard folder to /etc/wireguard_2020-08-31-193506.tar.gz
::: The Server Keys will now be generated.
::: Server Keys have been generated.
::: Server config generated.
::: Install Complete...
::: Restarting services...
Job for wg-quick@wg0.service failed because the control process exited with error code.
See "systemctl status wg-quick@wg0.service" and "journalctl -xe" for details.
::: Enabling unattended upgrades
:::    Checking for unattended-upgrades... already installed!
::: Setupfiles copied to /etc/pivpn/wireguard/setupVars.conf
mkdir: cannot create directory '/etc/pivpn/wireguard/': File exists
::: Installing scripts to /opt/pivpn...
ln: failed to create symbolic link '/etc/bash_completion.d/pivpn': File exists
ln: failed to create symbolic link '/usr/local/bin/pivpn': File exists
ln: failed to create symbolic link '/opt/pivpn/scripts': File exists
 done.
::: Flushing writes to disk...
::: done.
::: Installation Complete!
::: Now run 'pivpn add' to create the client profiles.
::: Run 'pivpn help' to see what else you can do!

::: If you run into any issue, please read all our documentation carefully.
::: All incomplete posts or bug reports will be ignored or deleted.

::: Thank you for using PiVPN.
::: It is strongly recommended you reboot after installation.
```

### Console output of      `pivpn add` or `pivpn add nopass`
```
root@wireguard:~# pivpn add
Enter a Name for the Client: NAME
::: Client Keys generated
::: Client config generated
::: Updated server config
Job for wg-quick@wg0.service failed because the control process exited with error code.
See "systemctl status wg-quick@wg0.service" and "journalctl -xe" for details.
::: Failed to restart WireGuard
======================================================================
::: Done! NAME.conf successfully created!
::: james.conf was copied to /home/wg/configs for easy transfer.
::: Please use this profile only on one device and create additional
::: profiles for other devices. You can also use pivpn -qr
::: to generate a QR Code you can scan with the mobile app.
======================================================================
```

### Console output of      `pivpn debug`
```
::::            PiVPN debug              ::::
=============================================
::::            Latest commit            ::::
commit 32bd1c628af9e1926f3f4471c0bf49c74deff7c7 (grafted, HEAD -> master, origin/test, origin/master, origin/HEAD)
Author: Orazio <orazioedoardo@users.noreply.github.com>
Date:   Fri Jul 24 18:52:57 2020 +0200

    Update LatestUpdate.md
=============================================
::::        Installation settings        ::::
PLAT=Debian
OSCN=buster
USING_UFW=0
IPv4dev=eth0
install_user=wg
install_home=/home/wg
VPN=wireguard
pivpnPORT=51820
pivpnDNS1=192.168.0.194
pivpnDNS2=192.168.0.195
pivpnHOST=REDACTED
INPUT_CHAIN_EDITED=0
FORWARD_CHAIN_EDITED=0
pivpnPROTO=udp
pivpnDEV=wg0
pivpnNET=10.6.0.0
subnetClass=24
UNATTUPG=1
INSTALLED_PACKAGES=(git dnsutils net-tools iptables-persistent linux-headers-amd64 wireguard wireguard-tools wireguard-dkms qrencode unattended-upgrades)
=============================================
::::  Server configuration shown below   ::::
[Interface]
PrivateKey = server_priv
Address = 10.6.0.1/24
ListenPort = 51820
### begin NAME###
[Peer]
PublicKey = NAME_pub
PresharedKey = NAME_psk
AllowedIPs = 10.6.0.2/32
### end NAME ###
=============================================
::::  Client configuration shown below   ::::
[Interface]
PrivateKey = NAME_priv
Address = 10.6.0.2/24
DNS = 192.168.0.194, 192.168.0.195

[Peer]
PublicKey = server_pub
PresharedKey = NAME_psk
Endpoint = REDACTED:51820
AllowedIPs = 0.0.0.0/0, ::0/0
=============================================
::::    Recursive list of files in       ::::
::::    /etc/wireguard shown below       ::::
/etc/wireguard:
configs  keys  wg0.conf

/etc/wireguard/configs:
clients.txt  NAME.conf

/etc/wireguard/keys:
NAME_priv  NAME_psk  NAME_pub  server_priv  server_pub
=============================================
::::            Self check               ::::
:: [OK] IP forwarding is enabled
:: [OK] Iptables MASQUERADE rule set
:: [ERR] WireGuard is not running, try to start now? [Y/n] y
Job for wg-quick@wg0.service failed because the control process exited with error code.
See "systemctl status wg-quick@wg0.service" and "journalctl -xe" for details.
Done
:: [OK] WireGuard is enabled (it will automatically start on reboot)
:: [ERR] WireGuard is not listening, try to restart now? [Y/n] y
Job for wg-quick@wg0.service failed because the control process exited with error code.
See "systemctl status wg-quick@wg0.service" and "journalctl -xe" for details.
Done
[INFO] Run pivpn -d again to see if we detect issues
=============================================
:::: Having trouble connecting? Take a look at the FAQ:
:::: https://github.com/pivpn/pivpn/wiki/FAQ
=============================================
:::: WARNING: This script should have automatically masked sensitive       ::::
:::: information, however, still make sure that PrivateKey, PublicKey      ::::
:::: and PresharedKey are masked before reporting an issue. An example key ::::
:::: that you should NOT see in this log looks like this:                  ::::
:::: YIAoJVsdIeyvXfGGDDadHh6AxsMRymZTnnzZoAb9cxRe                          ::::
=============================================
::::            Debug complete           ::::
```
### Have you taken any steps towards solving your issue?
```
  which?

Searched issues in GitHub, Reddit, Google, etc.
```

**Comment by jameswagar** [comment]
Here is the output of "systemctl status wg-quick@wg0.service"

* wg-quick@wg0.service - WireGuard via wg-quick(8) for wg0
   Loaded: loaded (/lib/systemd/system/wg-quick@.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2020-08-31 19:37:09 UTC; 4h 5min ago
     Docs: man:wg-quick(8)
           man:wg(8)
           https://www.wireguard.com/
           https://www.wireguard.com/quickstart/
           https://git.zx2c4.com/wireguard-tools/about/src/man/wg-quick.8
           https://git.zx2c4.com/wireguard-tools/about/src/man/wg.8
  Process: 1301 ExecStart=/usr/bin/wg-quick up wg0 (code=exited, status=1/FAILURE)
 Main PID: 1301 (code=exited, status=1/FAILURE)

Aug 31 19:37:08 wireguard systemd[1]: Starting WireGuard via wg-quick(8) for wg0...
Aug 31 19:37:09 wireguard wg-quick[1301]: [#] ip link add wg0 type wireguard
Aug 31 19:37:09 wireguard wg-quick[1301]: Error: Unknown device type.
Aug 31 19:37:09 wireguard wg-quick[1301]: Unable to access interface: Protocol not supported
Aug 31 19:37:09 wireguard wg-quick[1301]: [#] ip link delete dev wg0
Aug 31 19:37:09 wireguard wg-quick[1301]: Cannot find device "wg0"
Aug 31 19:37:09 wireguard systemd[1]: wg-quick@wg0.service: Main process exited, code=exited, status=1/FAILURE
Aug 31 19:37:09 wireguard systemd[1]: wg-quick@wg0.service: Failed with result 'exit-code'.
Aug 31 19:37:09 wireguard systemd[1]: Failed to start WireGuard via wg-quick(8) for wg0.

**Comment by orazioedoardo** [comment]
What's the output of `uname -a` and `sudo dkms status`?

**Comment by jameswagar** [comment]
Thanks, @orazioedoardo.

uname -a:

Linux wireguard 5.4.34-1-pve #1 SMP PVE 5.4.34-2 (Thu, 07 May 2020 10:02:02 +0200) x86_64 GNU/Linux

dkms status (I'm root):

wireguard, 1.0.20200712, 4.19.0-10-amd64, x86_64: installed

**Comment by orazioedoardo** [comment]
Well, WireGuard was build for kernel 4.19 but now you seem to have switched to kernel 5.4. Either revert to kernel 4.19 or try `sudo dpkg-reconfigure wireguard-dkms` to rebuild the module for the new kernel.

**Comment by jameswagar** [comment]
Thanks. Is there a better version of Debian or Ubuntu that I should use for PiVPN/WireGuard?

I am using a Linux container so I’d like to use the most compatible OS version.

**Comment by orazioedoardo** [comment]
Debian 10/Ubuntu 20.04 is fine. However WireGuard requires a kernel module, I'm not sure if you can install it in a container.

**Comment by jameswagar** [comment]
Ok. Thanks. I have tried the `sudo dpkg-reconfigure wireguard-dkms` command. If that doesn't work, I'll create an actual VM.

I appreciate your help.

**Comment by jameswagar** [comment]
@orazioedoardo I tried run the PiVPN installer on a 20.04.1 VM and the installation stopped saying it was an unsupported OS.

Is there something I need to do before running PiVPN aside from apt-get update/upgrade?

**Comment by orazioedoardo** [comment]
It should warn about unsupported but you can go ahead anyways. Another option, use the test branch: https://github.com/pivpn/pivpn/wiki#testing

**Comment by jameswagar** [comment]
Ok. Thank you. I installed a Debian 10 VM. So I will give that a try.

**Comment by jameswagar** [comment]
After some issues with Debian, I ended up installing an Ubuntu 20 VM, and PiVPN with WireGuard is now working fine using the test branch.

Thanks again for your help.

**Comment by paulzak** [comment]
> Well, WireGuard was build for kernel 4.19 but now you seem to have switched to kernel 5.4. Either revert to kernel 4.19 or try `sudo dpkg-reconfigure wireguard-dkms` to rebuild the module for the new kernel.

I was having difficulty getting my once working wireguard server to start and this command seems to have resolved my problem.  I'm grateful for the suggestion.
