### ISSUE TITLE
[Support] Change "installation settings" afterwards

### ISSUE THREAD

**Issue by Backes89** [pivpn/pivpn#1133]
After installing and configuring PiVpn and PiHole on a raspberry pi I wanted to install the Pi at my parents home. They use an alternative ip-address range which differs from the network I configured the Pi in.

My network: 192.168.178.0/24
Other network: 192.168.179.0/24

I changed the IP of the PI to match de ip-range at my parents house and I can now connect in the local network to the PI. The only problem is that PiVPN still has the old ip-settings and did not update them itself. Is there any manual option to change this.

pivpn -d Output:
`
::::        Installation settings        ::::
PLAT=Raspbian
OSCN=buster
USING_UFW=0
IPv4dev=eth0
dhcpReserv=1
IPv4addr=192.168.178.3/24
IPv4gw=192.168.178.1
install_user=pi
install_home=/home/pi
VPN=wireguard
pivpnPORT=51820
pivpnDNS1=10.6.0.1
pivpnDNS2=
pivpnHOST=REDACTED
INPUT_CHAIN_EDITED=0
FORWARD_CHAIN_EDITED=0
pivpnPROTO=udp
pivpnDEV=wg0
pivpnNET=10.6.0.0
subnetClass=24
UNATTUPG=1
INSTALLED_PACKAGES=(iptables-persistent)
`

IPv4addr=192.168.178.3/24 --> needs to be 192.168.179.2/24
IPv4gw=192.168.178.1 --> 192.168.179.1

**Comment by orazioedoardo** [comment]
If you set up a static IP, you can change that inside the file `/etc/dhcpcd.conf`.
