### ISSUE TITLE
 CHAIN_ADD failed (No such file or directory): chain PREROUTING

### ISSUE THREAD

**Issue by eos1d3** [pivpn/pivpn#1135]
## In raising this issue, I confirm the following: 

- [x] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

**Describe the bug**
When installing on Raspbian Buster (Raspberry Pi3), there are iptables errors in the script.

```
::: Server Keys have been generated.
::: Server config generated.
iptables v1.8.2 (nf_tables):  CHAIN_ADD failed (No such file or directory): chain PREROUTING
iptables v1.8.2 (nf_tables): Couldn't load match `comment':No such file or directory

Try `iptables -h' or 'iptables --help' for more information.
iptables v1.8.2 (nf_tables): Couldn't load match `comment':No such file or directory

Try `iptables -h' or 'iptables --help' for more information.
::: Install Complete...
::: Restarting services...
```

**To Reproduce**
1. Run installation script
2. Wait for `Server config generated`.
3. After that, the errors are shown.

**Expected behavior**
No such errors

**Additional context**
This is because Raspbian Buster uses nftables instead of iptables. To fix the problem, run the command before the installation script. This changes iptables as default.

```
sudo update-alternatives --set iptables /usr/sbin/iptables-legacy
# for ipv6
sudo update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy
```

Re-run the script and there is no error after this fix. And everything works.

**Comment by orazioedoardo** [comment]
According to https://github.com/pivpn/pivpn/issues/1015, we don't need to switch to legacy anymore and indeed the script worked without that change (I've tested before merging and no one has reported this before).

```
iptables v1.8.2 (nf_tables):  CHAIN_ADD failed (No such file or directory): chain PREROUTING
iptables v1.8.2 (nf_tables): Couldn't load match `comment':No such file or directory

Try `iptables -h' or 'iptables --help' for more information.
```

I saw this error when installing pivpn with a pending kernel upgrade, however the iptables rules where correctly applied after a reboot into the new kernel.

**Comment by eos1d3** [comment]
I saw exactly these error messages from you.

But my PI 3 running Buster has been updated to latest version and rebooted many hours ago.

**Comment by orazioedoardo** [comment]
Maybe something changed with the [latest release](https://downloads.raspberrypi.org/raspios_armhf/release_notes.txt) of Raspbian. Let's see if someone else reports this error too.

**Comment by eos1d3** [comment]
I will try to make new installation of 20-Aug image to see if same problem exists or not.

**Comment by eos1d3** [comment]
Reinstalled fresh Raspberry Pi OS (32-bit) Lite on my Pi3 and update everything:
```
Minimal image based on Debian Buster
Version:August 2020
Release date:2020-08-20
Kernel version:5.4
```

The errors do not occur any more. So using the script does not need to switch to legacy mode.

But it is strange that my last system was made by image of Raspberry Pi OS released in June, and has been updated too. It is also Debian Buster and does not have anything but Tor only.
