### ISSUE TITLE
Server certificate

### ISSUE THREAD

**Issue by Matthiasfranck** [pivpn/pivpn#1136]
When I run the command _pivpn list_ I get this:

_The first entry should always be your valid server!_

Why is this first entry for? And what to do when this certificate expires?

**Comment by orazioedoardo** [comment]
> Why is this first entry for?

The server has a certificate (public and private key) to authenticate itself to the client so the latter knows he's connecting to the actual server and not a fake one.

> And what to do when this certificate expires?

Regenerate the server certificate and update all client .ovpn files or (easier) reinstall PiVPN. Consider though that the certificate lasts 10 years.

**Comment by Matthiasfranck** [comment]
Thanks for your response. How can I regenerate the server certificate? Is it just adding a new user with exactly the same name?

**Comment by orazioedoardo** [comment]
> Is it just adding a new user with exactly the same name? 

No, the steps are around this line https://github.com/pivpn/pivpn/blob/32bd1c628af9e1926f3f4471c0bf49c74deff7c7/auto_install/install.sh#L1898 but as I said, if you do that you need to update all clients with the new server certificate.

Is there a specific reason why you need to do this?

**Comment by Matthiasfranck** [comment]
Thank you! There is no specific reason, but I was wondering what I need to do when it expires in the future.
