### ISSUE TITLE
Cannot connect to Windows running Wireguard

### ISSUE THREAD

**Issue by Bboy486** [pivpn/pivpn#1141]
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

**Describe the bug**
When I run pivpn -d it shows wireguard not running. This happens each time I run pivpn -d. 
::::            Self check               ::::
:: [OK] IP forwarding is enabled
:: [OK] Iptables MASQUERADE rule set
:: [OK] Iptables FORWARD rule set
:: [ERR] WireGuard is not running, try to start now? [Y/n] Y

Re-running the PIVPN install shows (as a repair) shows:

::: Restarting services...
Job for wg-quick@wg0.service failed because the control process exited with error code.
See "systemctl status wg-quick@wg0.service" and "journalctl -xe" for details.
::: Enabling unattended upgrades
:::    Checking for unattended-upgrades... already installed!
::: Setupfiles copied to /etc/pivpn/wireguard/setupVars.conf
mkdir: cannot create directory '/etc/pivpn/wireguard/': File exists
::: Installing scripts to /opt/pivpn...
ln: failed to create symbolic link '/etc/bash_completion.d/pivpn': File exists
ln: failed to create symbolic link '/usr/local/bin/pivpn': File exists
ln: failed to create symbolic link '/opt/pivpn/scripts': File exists
 done.
::: Flushing writes to disk...
::: done.
::: Installation Complete!
::: Now run 'pivpn add' to create the client profiles.
::: Run 'pivpn help' to see what else you can do!

::: If you run into any issue, please read all our documentation carefully.
::: All incomplete posts or bug reports will be ignored or deleted.

::: Thank you for using PiVPN.
::: It is strongly recommended you reboot after installation.

**To Reproduce**

1. Go to Pi
2. run pivpn -d

**Expected behavior**
Wireguard should automatically run and I should be able to connect my phone to my home computer. 

 - VPN Protocol - Wireguard
 - OS: Rasp Pi (Host), Note 10+ Client,, Windows 10 Home Client

**Comment by orazioedoardo** [comment]
The actual output of `pivpn -d` may be interesting. Also `uname -a` and `sudo dkms status`.

**Comment by Bboy486** [comment]
https://pastebin.com/h74nfSiq

Odd it is saying there are no certs.

**Comment by orazioedoardo** [comment]
```
::::            Self check               ::::
:: [OK] IP forwarding is enabled
:: [OK] Iptables MASQUERADE rule set
:: [OK] Iptables FORWARD rule set
:: [OK] WireGuard is running
:: [OK] WireGuard is enabled (it will automatically start on reboot)
:: [OK] WireGuard is listening on port 51820/udp
```

Seems fine. 
```
/etc/wireguard/configs:
clients.txt
```

Well yes there are no clients yet.

By the way you can post the output right here, don't need to link pastebin or similar.

**Comment by Bboy486** [comment]
Thank you. I was able to get pivpn to run but only on my Windows 10 Home Machine. On my Windows 10 Pro machine (which has the same settings as the other windows machine) when I import the conf (same on both machines for testing):

wireguard unable to create wintun interface

2020-09-21 21:33:45.762: [TUN] [brandon] Unable to create Wintun interface: Error creating interface: No driver for device "Wintun" installed

**Comment by Bboy486** [comment]
Just checking back to see if you can assist. Thanks!

**Comment by orazioedoardo** [comment]
`2020-09-21 21:33:45.762: [TUN] [brandon] Unable to create Wintun interface: Error creating interface: No driver for device "Wintun" installed`


This is an issue with WireGuard on your PC, not PiVPN.
