### ISSUE TITLE
Question: How to route only DNS request through Wireguard tunnel?

### ISSUE THREAD

**Issue by smokemyshoes** [pivpn/pivpn#1145]
- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

Hi

First of all thanks a lot for your great effort! Due to your work it is literally possible to have a VPN up and running and being connected to it from a client in less than 15 min. I wouldn’t have believed that before I tried it.

My question probably isn’t related to pivpn alone, but probably wireguard in general, but since you promote that your installation can be combined with pi-hole, maybe you will still take the time to answer this question nevertheless.

Reading through closed issues I found this https://github.com/pivpn/pivpn/issues/1055, but from the explanation of the issue, it's not clear to me if what OP wants to achieve is the same as me.

My setup is like this: I have wireguard installed through pivpn on a RPi4 along with pi-hole and Unbound which acts as the DNS resolver (and sinkhole) for my lan (192.168.24.1/24). My RPi (192.168.24.2) is directly connected to my router (192.168.24.1) and I’m currently routing all traffic (0.0.0.0/0) from my iPhone through the server.

If I want to only route DNS request for WWW traffic (0.0.0.0/0) to my wireguard server and still be able to access my home network from my client, how would I configure the server and/or client?

Many thanks in advance…

**Comment by zilexa** [comment]
I want this too and will give it a try tomorrow. There is documentation available. Check this article and the one before:
https://docs.pi-hole.net/guides/vpn/dual-VPN/

**Comment by orazioedoardo** [comment]
1) https://github.com/pivpn/pivpn/wiki/WireGuard#how-do-i-allow-clients-access-to-my-home-network-but-not-the-internet-through-my-pivpn

2) https://github.com/pivpn/pivpn/wiki/WireGuard#how-do-i-use-pi-hole-with-pivpn

If you chose to use Pi-hole at install time, probably you have DNS = 10.6.0.1 (raspberry pi virtual ip) however after 1) you will route 192.168.24.0/24 which doesn't include 10.6.0.1, hence DNS = 192.168.24.2.

**Comment by zilexa** [comment]
I don't want to hijack this issue, but I installed PiVPN on Ubuntu 20.04.1:
Wireguard
My Ubuntu pc: 192.168.88.10 (192.168.88.0/24)
My DNS server (PiHole): 192.168.88.3
Pihole: pihole -a -i all, then checked the webui, indeed listening to all interfaces.

Created 1 client config and scanned the QR. 
After connecting the phone (Pixel 1, Android 10) with the Wireguard app, there is a connection, but I cannot access any website or local IP address.

```
pivpn -c
::: Connected Clients List :::
Name           Remote IP      Virtual IP      Bytes Received      Bytes Sent      Last Seen
Rud-Pixel      (none)         10.6.0.2        0B                  0B              (not yet)
asterix@Obelix:~/Downloads$ pivpn -d
[sudo] password for asterix: 
::::		PiVPN debug		 ::::
=============================================
::::		Latest commit		 ::::
commit 32bd1c628af9e1926f3f4471c0bf49c74deff7c7 (grafted, HEAD -> master, origin/master, origin/HEAD)
Author: Orazio <orazioedoardo@users.noreply.github.com>
Date:   Fri Jul 24 18:52:57 2020 +0200

    Update LatestUpdate.md
=============================================
::::	    Installation settings    	 ::::
PLAT=Ubuntu
OSCN=focal
USING_UFW=0
IPv4dev=eno1
install_user=asterix
install_home=/home/asterix
VPN=wireguard
pivpnPORT=51822
pivpnDNS1=192.168.88.3
pivpnDNS2=
pivpnHOST=REDACTED
INPUT_CHAIN_EDITED=0
FORWARD_CHAIN_EDITED=1
pivpnPROTO=udp
pivpnDEV=wg0
pivpnNET=10.6.0.0
subnetClass=24
UNATTUPG=1
INSTALLED_PACKAGES=(dnsutils net-tools iptables-persistent wireguard wireguard-tools wireguard-dkms qrencode)
=============================================
::::  Server configuration shown below   ::::
[Interface]
PrivateKey = server_priv
Address = 10.6.0.1/24
ListenPort = 51822
### begin Rud-Pixel ###
[Peer]
PublicKey = Rud-Pixel_pub
PresharedKey = Rud-Pixel_psk
AllowedIPs = 10.6.0.2/32
### end Rud-Pixel ###
=============================================
::::  Client configuration shown below   ::::
[Interface]
PrivateKey = Rud-Pixel_priv
Address = 10.6.0.2/24
DNS = 192.168.88.3

[Peer]
PublicKey = server_pub
PresharedKey = Rud-Pixel_psk
Endpoint = REDACTED:51822
AllowedIPs = 0.0.0.0/0, ::0/0
=============================================
:::: 	Recursive list of files in	 ::::
::::	/etc/wireguard shown below	 ::::
/etc/wireguard:
configs  keys  wg0.conf

/etc/wireguard/configs:
clients.txt  Rud-Pixel.conf

/etc/wireguard/keys:
Rud-Pixel_priv	Rud-Pixel_psk  Rud-Pixel_pub  server_priv  server_pub
=============================================
::::		Self check		 ::::
:: [OK] IP forwarding is enabled
:: [OK] Iptables MASQUERADE rule set
:: [OK] Iptables FORWARD rule set
:: [OK] WireGuard is running
:: [OK] WireGuard is enabled (it will automatically start on reboot)
:: [OK] WireGuard is listening on port 51822/udp
=============================================
:::: Having trouble connecting? Take a look at the FAQ:
:::: https://github.com/pivpn/pivpn/wiki/FAQ
=============================================
:::: WARNING: This script should have automatically masked sensitive       ::::
:::: information, however, still make sure that PrivateKey, PublicKey      ::::
:::: and PresharedKey are masked before reporting an issue. An example key ::::
:::: that you should NOT see in this log looks like this:                  ::::
:::: YIAoJVsdIeyvXfGGDDadHh6AxsMRymZTnnzZoAb9cxRe                          ::::
=============================================
::::		Debug complete		 ::::
```

I looked at the FAQ and troubleshooting, but nothing seems to be out of order. Yet my phone basically has no internet connection after connecting to the server :(

**Comment by smokemyshoes** [comment]
@orazioedoardo Thanks a lot. I'll give it a try this evening. I completely misunderstood that part of the Wireguard Wiki. I understood it like with the client settings in link 1, I wouldn't be able to connect to any other IP's than my own lan when the client was connected to the VPN. DOH!

**Comment by smokemyshoes** [comment]
It worked!

**Comment by EsmailELBoBDev2** [comment]
nope, it did not work for me, so i'm posting this for future myself or someone like me. i followed this and it worked so yup https://it.playswellwithflavors.com/2020/04/09/creating-a-split-tunnel-user-in-pivpn/
