### ISSUE TITLE
[Support] Wireguard connects OK, but no access to internet or LAN

### ISSUE THREAD

**Issue by zilexa** [pivpn/pivpn#1147]
### Issue
PiVPN on Ubuntu 20.04.1 (Intel PC):
* Wireguard
* My Ubuntu pc: 192.168.88.10 (192.168.88.0/24)
* I have a CNAME domain, obelix.cloud that links to the dyndns address of my Mikrotik router which directs to my server public IP.
* But for testing purposes I simply fill in the public IP of my server. 
* My DNS server (PiHole): 192.168.88.3 BUT I reinstalled PiVPN and selected Cloudflare instead to ensure PiHole is not the issue.
* Pihole: pihole -a -i all, then checked the webui, indeed listening on all interfaces.
Created 1 client config and scanned the QR. 
- port forwarding of port 51822 (tcp) and 1194 (udp).

After connecting the phone (Pixel 1, Android 10) with the Wireguard app, there is a connection, but I cannot access any website (address not found).

### Have you taken any steps towards solving your issue?
* I reinstalled PiVPN, this time selecting Cloudflare as DNS to ensure PiHole is not the issue. On my phone, I still cannot access any website. 
* On my phone I changed `Allowed IPs` from ` 0.0.0.0/0, ::/0` to `192.168.88.0/24, ::/0` and reconnected to test if I could access my LAN, as I suppose you do not use a DNS server for that. But I also could not access LAN (192.168.88.10:someport-to-webui-of-a-service).
* I followed the debug steps on the website, nothing seemed out of ordinary.

### Debug info
```
::::		PiVPN debug		 ::::
=============================================
::::		Latest commit		 ::::
commit 32bd1c628af9e1926f3f4471c0bf49c74deff7c7 (grafted, HEAD -> master, origin/master, origin/HEAD)
Author: Orazio <orazioedoardo@users.noreply.github.com>
Date:   Fri Jul 24 18:52:57 2020 +0200

    Update LatestUpdate.md
=============================================
::::	    Installation settings    	 ::::
PLAT=Ubuntu
OSCN=focal
USING_UFW=0
IPv4dev=eno1
install_user=asterix
install_home=/home/asterix
VPN=wireguard
pivpnPORT=51822
pivpnDNS1=1.1.1.1
pivpnDNS2=1.0.0.1
pivpnHOST=REDACTED
INPUT_CHAIN_EDITED=0
FORWARD_CHAIN_EDITED=1
pivpnPROTO=udp
pivpnDEV=wg0
pivpnNET=10.6.0.0
subnetClass=24
UNATTUPG=1
INSTALLED_PACKAGES=()
=============================================
::::  Server configuration shown below   ::::
[Interface]
PrivateKey = server_priv
Address = 10.6.0.1/24
ListenPort = 51822
### begin Shanti-Pixel ###
[Peer]
PublicKey = Shanti-Pixel_pub
PresharedKey = Shanti-Pixel_psk
AllowedIPs = 10.6.0.2/32
### end Shanti-Pixel ###
=============================================
::::  Client configuration shown below   ::::
[Interface]
PrivateKey = Shanti-Pixel_priv
Address = 10.6.0.2/24
DNS = 1.1.1.1, 1.0.0.1

[Peer]
PublicKey = server_pub
PresharedKey = Shanti-Pixel_psk
Endpoint = REDACTED:51822
AllowedIPs = 0.0.0.0/0, ::0/0
=============================================
:::: 	Recursive list of files in	 ::::
::::	/etc/wireguard shown below	 ::::
/etc/wireguard:
configs  keys  wg0.conf

/etc/wireguard/configs:
clients.txt  Shanti-Pixel.conf

/etc/wireguard/keys:
server_priv  server_pub  Shanti-Pixel_priv  Shanti-Pixel_psk  Shanti-Pixel_pub
=============================================
::::		Self check		 ::::
:: [OK] IP forwarding is enabled
:: [OK] Iptables MASQUERADE rule set
:: [OK] Iptables FORWARD rule set
:: [OK] WireGuard is running
:: [OK] WireGuard is enabled (it will automatically start on reboot)
:: [OK] WireGuard is listening on port 51822/udp
=============================================
:::: Having trouble connecting? Take a look at the FAQ:
:::: https://github.com/pivpn/pivpn/wiki/FAQ
=============================================
:::: WARNING: This script should have automatically masked sensitive       ::::
:::: information, however, still make sure that PrivateKey, PublicKey      ::::
:::: and PresharedKey are masked before reporting an issue. An example key ::::
:::: that you should NOT see in this log looks like this:                  ::::
:::: YIAoJVsdIeyvXfGGDDadHh6AxsMRymZTnnzZoAb9cxRe                          ::::
=============================================
::::		Debug complete		 ::::
```

I looked at the FAQ and troubleshooting, but nothing seems to be out of order. Yet my phone basically has no internet connection after connecting to the server :(

**Comment by starwarsfan17** [comment]
For PiHole: Have you checked /etc/dnsmasq.d/01-pihole.conf whether the interface is listed correctly?

**Comment by zilexa** [comment]
As mentioned, I reinstalled PiVPN (run the installer again) and reconfigure, selected Cloudflare, I have the exact same issue. 
At this moment all my tests exclude PiHole and use Cloudflare. 


PiHole: /etc/dnsmasq.d/01-pihole.conf 
```
addn-hosts=/etc/pihole/local.list
addn-hosts=/etc/pihole/custom.list


localise-queries


no-resolv



cache-size=10000

log-queries
log-facility=/var/log/pihole.log

local-ttl=2

log-async
server=192.168.88.4#53
server=127.0.0.1
except-interface=nonexisting
rev-server=192.168.88.0/24,192.168.88.1
server=/Obelix/192.168.88.1
server=/use-application-dns.net/
```

**Comment by starwarsfan17** [comment]
Sorry, mixed up files. There should be also a 02-pivpn.conf in the same folder. Also please check in this file whether the setting for the interface is contained i.e. interface=tun0.

**Comment by sorenmichaelsen** [comment]
I am following this. I have the same problem. A freshly install Pi4. First thing i installed was Pihole and PiVpn with wireguard. I have handshake but no internet. My settings looks a lot like Zilexas

**Comment by zilexa** [comment]
> Sorry, mixed up files. There should be also a 02-pivpn.conf in the same folder. Also please check in this file whether the setting for the interface is contained i.e. interface=tun0.
Huh, why would there be such a file? There is no such file, which is correct because that makes no sense at all as Pihole is not aware of PiVPN. And I have not created that file. In none of the guides/documentation that I have read is there any mention of that file.

But this is nearly offtopic as my issue is not caused by PiHole because I am currently not using it, I am using Cloudflare to test and I have the same issue.

**Comment by zilexa** [comment]
Solved the main issue: I had opened tcp port 51822 instead of udp. Now I can connect and access internet. I can even access local lan after making the change mentioned in the description. 

My actual goal is to *ONLY* have DNS traffic and LAN access via PiVPN-Wireguard. Normal internet should bypass the tunnel.

I did this:
https://github.com/pivpn/pivpn/wiki/WireGuard#how-do-i-allow-clients-access-to-my-home-network-but-not-the-internet-through-my-pivpn

But when the client device does an Whats My IP check, I see the device has the same IP as my home server public IP. Meaning internet traffic is still going via the tunnel! --> is this a bug?

**Comment by PhillySports** [comment]
zilexa, I am having the same issue that you were having.  Handshake, but no internet connection.  I do have udp port 51820 opened.  Did you do anything else to get it working.

Here is my debug output:
::::            PiVPN debug              ::::
=============================================
::::            Latest commit            ::::
commit 32bd1c628af9e1926f3f4471c0bf49c74deff7c7 (grafted, HEAD -> master, origin/master, origin/HEAD)
Author: Orazio <orazioedoardo@users.noreply.github.com>
Date:   Fri Jul 24 18:52:57 2020 +0200

    Update LatestUpdate.md
=============================================
::::        Installation settings        ::::
PLAT=Raspbian
OSCN=buster
USING_UFW=0
IPv4dev=eth0
IPv4addr=192.168.1.201/24
IPv4gw=192.168.1.1
install_user=steve
install_home=/home/steve
VPN=wireguard
pivpnPORT=51820
pivpnDNS1=1.1.1.1
pivpnDNS2=1.0.0.1
pivpnHOST=REDACTED
INPUT_CHAIN_EDITED=0
FORWARD_CHAIN_EDITED=0
pivpnPROTO=udp
pivpnDEV=wg0
pivpnNET=10.6.0.0
subnetClass=24
UNATTUPG=1
INSTALLED_PACKAGES=(iptables-persistent raspberrypi-kernel-headers wireguard wireguard-tools wireguard-dkms qrencode unattended-upgrades)
=============================================
::::  Server configuration shown below   ::::
[Interface]
PrivateKey = server_priv
Address = 10.6.0.1/24
ListenPort = 51820
### begin Steve ###
[Peer]
PublicKey = Steve_pub
PresharedKey = Steve_psk
AllowedIPs = 10.6.0.2/32
### end Steve ###
=============================================
::::  Client configuration shown below   ::::
[Interface]
PrivateKey = Steve_priv
Address = 10.6.0.2/24
DNS = 1.1.1.1, 1.0.0.1

[Peer]
PublicKey = server_pub
PresharedKey = Steve_psk
Endpoint = REDACTED:51820
AllowedIPs = 0.0.0.0/0, ::0/0
=============================================
::::    Recursive list of files in       ::::
::::    /etc/wireguard shown below       ::::
/etc/wireguard:
configs  keys  wg0.conf

/etc/wireguard/configs:
clients.txt  Steve.conf

/etc/wireguard/keys:
server_priv  server_pub  Steve_priv  Steve_psk  Steve_pub
=============================================
::::            Self check               ::::
:: [OK] IP forwarding is enabled
:: [OK] Iptables MASQUERADE rule set
:: [OK] WireGuard is running
:: [OK] WireGuard is enabled (it will automatically start on reboot)
:: [OK] WireGuard is listening on port 51820/udp
=============================================
:::: Having trouble connecting? Take a look at the FAQ:
:::: https://github.com/pivpn/pivpn/wiki/FAQ
=============================================
:::: WARNING: This script should have automatically masked sensitive       ::::
:::: information, however, still make sure that PrivateKey, PublicKey      ::::
:::: and PresharedKey are masked before reporting an issue. An example key ::::
:::: that you should NOT see in this log looks like this:                  ::::
:::: YIAoJVsdIeyvXfGGDDadHh6AxsMRymZTnnzZoAb9cxRe                          ::::
=============================================
::::            Debug complete           ::::

**Comment by RaspberryTech01** [comment]
I am suddenly having the same issue on 2 of 3 VPNs. It connects but cannot resolve anything. Using pivpn+pihole.

**Comment by starwarsfan17** [comment]
So, in order to reduce the confusion here:
I had the pihole installed first and added PiVPN later. During the installation of PiVPN it asked me whether it should route the DNS queries through pihole (so noticed the available installation of pihole). Therefore the file I mentioned before was already available and I just had to add the line in the file to get it working. Also, I have OpenVPN method installed on my server, thought I would be similar to Wireguard.

In a quick google search I found the below post:
https://discourse.pi-hole.net/t/pi-hole-wireguard/18021/10

When this doesn't solve the issue, I would have done this in my setup and see how it is going in order to have a proper answer to your request.

**Comment by RaspberryTech01** [comment]
> So, in order to reduce the confusion here:
> I had the pihole installed first and added PiVPN later. During the installation of PiVPN it asked me whether it should route the DNS queries through pihole (so noticed the available installation of pihole). Therefore the file I mentioned before was already available and I just had to add the line in the file to get it working. Also, I have OpenVPN method installed on my server, thought I would be similar to Wireguard.
> 
> In a quick google search I found the below post:
> https://discourse.pi-hole.net/t/pi-hole-wireguard/18021/10
> 
> When this doesn't solve the issue, I would have done this in my setup and see how it is going in order to have a proper answer to your request.

I solved my issue by unblocking googlesyndicate.com.

**Comment by zilexa** [comment]
In my case, PiHole runs via Docker. Using a Docker macvlan, it gets its own IP address (instead of the IP of the server).
In this case when you install PiVPN on the same machine it won't recognise PiHole is running in Docker. That is why you should select custom.

I read online it's a limitation of PiHole: it won't work as DNS provider for both LAN and Wireguard VPN. If you want that you should run a second instance of PiHole. That's rediculous in my opinion.

I also realised, I don't actually need PiHole. I already use Unbound as recursive DNS server. PiHole is added to filter ads. But PiHole still does not have simple a way to quickly disable it for a single device. I need that many times to complete an online buy or whatever. So it's just annoying.

Now I learned Unbound can be used with a block list. I am going to stop trying to get PiHole Docker to work with LAN+PiVPN Wireguard and see if I can get it to work with only Unbound (Docker) instead.

**Comment by orazioedoardo** [comment]
> @starwarsfan17 how do you know an extra file is required? What should it contain? Because even the PiHole website does not mention it.
> edit: I did that, created /etc/dnsmasq.d/02-ovpn.conf and added a single line interface=tun0.
> Restarted PiHole, now no local device can access any website :(
> Removing that newly created file and rebooting pihole gave local devices access again. What am I missing?

Depending on your pihole "listening behavior", adding interface=tun0 will prevent pihole from working inside the lan (not pihole's fault), but regular dnsmasq behavior. PiVPN did this when offering pihole but this was changed so it doesn't break pihole anymore.

If you installed pihole after pivpn and want to use pihole for the vpn, just follow https://github.com/pivpn/pivpn/wiki/WireGuard#how-do-i-use-pi-hole-with-pivpn

**Comment by zilexa** [comment]
> > @starwarsfan17 how do you know an extra file is required? What should it contain? Because even the PiHole website does not mention it.
> > edit: I did that, created /etc/dnsmasq.d/02-ovpn.conf and added a single line interface=tun0.
> > Restarted PiHole, now no local device can access any website :(
> > Removing that newly created file and rebooting pihole gave local devices access again. What am I missing?
> 
> Depending on your pihole "listening behavior", adding interface=tun0 will prevent pihole from working inside the lan (not pihole's fault), but regular dnsmasq behavior. PiVPN did this when offering pihole but this was changed so it doesn't break pihole anymore.
> 
> If you installed pihole after pivpn and want to use pihole for lan + vpn at the same time, just follow https://github.com/pivpn/pivpn/wiki/WireGuard#how-do-i-use-pi-hole-with-pivpn

Unfortunately the situation is different when PiHole runs in Docker (on the same machine). That guide doesn't work in that case, even if you have a docker network macvlan setup and a macvlan on the host itself (otherwise you can't access the PiHole IP from the same machine).

**Comment by zilexa** [comment]
Closing this as the original issue was no LAN access. That is fixed.
