### ISSUE TITLE
pivpn with both Wireguard and OpenVPN

### ISSUE THREAD

**Issue by cmjordan42** [pivpn/pivpn#1148]
I have pivpn working splendidly with a cloud-based Ubuntu VPS and multiple client Android & Windows devices over Wireguard. However, I have some devices which cannot support Wireguard and I would like to still connect them via OpenVPN.

It seems that so long as there is a pivpn installation already in place, running a new install only offers repair and reconfigure options. Is it possible to use pivpn to run both Wireguard and OpenVPN, ideally with a single pihole service?

**Comment by orazioedoardo** [comment]
Yes it is, just use Reconfigure and install the other VPN.

**Comment by cmjordan42** [comment]
Great, thank you. Will give it a try. Maybe consider renaming that option in the menu to make this clearer? I did not proceed further because I didn't want to destroy existing connectivity for devices. I would be happy to submit a PR for this if you'd be interested.

**Comment by HeinvdW** [comment]
reconfigure:  curl -L install.pivpn.dev | bash

**Comment by orazioedoardo** [comment]
> Great, thank you. Will give it a try. Maybe consider renaming that option in the menu to make this clearer? I did not proceed further because I didn't want to destroy existing connectivity for devices. I would be happy to submit a PR for this if you'd be interested.

Sure, submit to the test branch.

**Comment by orazioedoardo** [comment]
Doesn't seem there is more to add here, closing...
