### ISSUE TITLE
[Support] Cannot connect when UFW is enabled

### ISSUE THREAD

**Issue by HeinvdW** [pivpn/pivpn#1152]
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

### Issue
PiVPN is running fine except when ufw is enabled.
UFW was enabled before the installation of PiVPN. (as well as PiHole)
PiVPN added the rules.
I reconfirmed the settings with pivpn -d
UFW setup:
`     To                         Action      From
     --                         ------      ----
[ 1] Anywhere on eth0           ALLOW FWD   10.6.0.0/24 on wg0
[ 2] 51822/udp                  ALLOW IN    Anywhere
[ 3] 22/tcp                     ALLOW IN    Anywhere
[ 4] 80/tcp                     ALLOW IN    Anywhere
[ 5] 443/tcp                    ALLOW IN    Anywhere
[ 6] 5335                       ALLOW IN    Anywhere
[ 7] 51822/udp (v6)             ALLOW IN    Anywhere (v6)
[ 8] 22/tcp (v6)                ALLOW IN    Anywhere (v6)
[ 9] 80/tcp (v6)                ALLOW IN    Anywhere (v6)
[10] 443/tcp (v6)               ALLOW IN    Anywhere (v6)
[11] 5335 (v6)                  ALLOW IN    Anywhere (v6)
`
pivpn -d output
`=============================================
::::        Installation settings        ::::
PLAT=Raspbian
OSCN=buster
USING_UFW=1
IPv4dev=eth0
IPv4addr=192.168.2.111/24
IPv4gw=192.168.2.254
install_user=rpi1
install_home=/home/rpi1
VPN=wireguard
pivpnPORT=51822
pivpnDNS1=10.6.0.1
pivpnDNS2=
pivpnHOST=REDACTED
pivpnPROTO=udp
pivpnDEV=wg0
pivpnNET=10.6.0.0
subnetClass=24
UNATTUPG=1
INSTALLED_PACKAGES=(wireguard)

=============================================
::::  Client configuration shown below   ::::
[Interface]
PrivateKey = rpi1_priv
Address = 10.6.0.2/24
DNS = 10.6.0.1

[Peer]
PublicKey = server_pub
PresharedKey = rpi1_psk
Endpoint = REDACTED:51822
AllowedIPs = 0.0.0.0/0, ::0/0
=============================================
::::    Recursive list of files in       ::::
::::    /etc/wireguard shown below       ::::
/etc/wireguard:
configs  keys  wg0.conf

/etc/wireguard/configs:
clients.txt  rpi1.conf

/etc/wireguard/keys:
rpi1_priv  rpi1_psk  rpi1_pub  server_priv  server_pub
=============================================
::::            Self check               ::::
:: [OK] IP forwarding is enabled
:: [OK] Ufw is enabled
:: [OK] Iptables MASQUERADE rule set
:: [OK] Ufw input rule set
:: [OK] Ufw forwarding rule set
:: [OK] WireGuard is running
:: [OK] WireGuard is enabled (it will automatically start on reboot)
:: [OK] WireGuard is listening on port 51822/udp
`

### Have you searched for similar issues and solutions?
    having looked up ufw setting, only found iptables settings

### Console output of      `curl -L install.pivpn.dev | bash`
```
rpi1@RPI1:~ $ curl -L install.pivpn.dev | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     5  100     5    0     0     21      0 --:--:-- --:--:-- --:--:--    21
100   162  100   162    0     0    424      0 --:--:-- --:--:-- --:--:--   424
100 82755  100 82755    0     0  92154      0 --:--:-- --:--:-- --:--:--  160k
:::
::: sudo will be used for the install.
::: Update option selected.
::: The updating functionality for PiVPN scripts is temporarily disabled
::: To keep the VPN (and the system) up to date, use 'apt update' and 'apt upgrade'
```

### Console output of      `pivpn add` or `pivpn add nopass`
```
  Enter a Name for the Client:
```

### Console output of      `pivpn debug`
```
=============================================
::::        Installation settings        ::::
PLAT=Raspbian
OSCN=buster
USING_UFW=1
IPv4dev=eth0
IPv4addr=192.168.2.111/24
IPv4gw=192.168.2.254
install_user=rpi1
install_home=/home/rpi1
VPN=wireguard
pivpnPORT=51822
pivpnDNS1=10.6.0.1
pivpnDNS2=
pivpnHOST=REDACTED
pivpnPROTO=udp
pivpnDEV=wg0
pivpnNET=10.6.0.0
subnetClass=24
UNATTUPG=1
INSTALLED_PACKAGES=(wireguard)
=============================================
::::  Client configuration shown below   ::::
[Interface]
PrivateKey = rpi1_priv
Address = 10.6.0.2/24
DNS = 10.6.0.1

[Peer]
PublicKey = server_pub
PresharedKey = rpi1_psk
Endpoint = REDACTED:51822
AllowedIPs = 0.0.0.0/0, ::0/0
=============================================
::::    Recursive list of files in       ::::
::::    /etc/wireguard shown below       ::::
/etc/wireguard:
configs  keys  wg0.conf

/etc/wireguard/configs:
clients.txt  rpi1.conf

/etc/wireguard/keys:
rpi1_priv  rpi1_psk  rpi1_pub  server_priv  server_pub
=============================================
::::            Self check               ::::
:: [OK] IP forwarding is enabled
:: [ERR] Ufw is not enabled, try to enable now? [Y/n] n
:: [OK] Iptables MASQUERADE rule set
:: [ERR] Ufw input rule is not set, attempt fix now? [Y/n] n
:: [ERR] Ufw forwarding rule is not set, attempt fix now? [Y/n] n
:: [OK] WireGuard is running
:: [OK] WireGuard is enabled (it will automatically start on reboot)
:: [OK] WireGuard is listening on port 51822/udp
[INFO] Run pivpn -d again to see if we detect issues
=============================================

```
### Have you taken any steps towards solving your issue?
```
Google for correct ufw rules
install and remove ufw
install and remove pivpn
disable and enable ufw
pivpn works fine when ufw is disabled
follow https://github.com/pivpn/pivpn/wiki/FAQ (troubleshooting) all OK
```

**Comment by orazioedoardo** [comment]
Reinstall, reenable ufw and then answer yes Y to the self check.

**Comment by HeinvdW** [comment]
Nope, disable, enable again, same behaviour, no DNS server active.
ufw disable -> DNS server active

**Comment by orazioedoardo** [comment]
Can I see the ufw and iptables configurations? Do you have pi-hole?

```
sudo iptables -t nat -S
sudo ufw status verbose
```

**Comment by HeinvdW** [comment]
Of course, here it is.
`sudo iptables -t nat -S
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P POSTROUTING ACCEPT
-P OUTPUT ACCEPT
-A POSTROUTING -s 10.6.0.0/24 -o eth0 -m comment --comment wireguard-nat-rule -j MASQUERADE
-A POSTROUTING -s 10.6.0.0/24 -o eth0 -m comment --comment wireguard-nat-rule -j MASQUERADE
-A POSTROUTING -s 10.6.0.0/24 -o eth0 -m comment --comment wireguard-nat-rule -j MASQUERADE
-A POSTROUTING -s 10.6.0.0/24 -o eth0 -m comment --comment wireguard-nat-rule -j MASQUERADE`
and
`sudo ufw status verbose
Status: active
Logging: on (low)
Default: deny (incoming), allow (outgoing), deny (routed)
New profiles: skip

To                         Action      From
--                         ------      ----
51820/udp                  ALLOW IN    Anywhere
22/tcp                     ALLOW IN    Anywhere
5335                       ALLOW IN    Anywhere
80/tcp                     ALLOW IN    Anywhere
443/tcp                    ALLOW IN    Anywhere
51820/udp (v6)             ALLOW IN    Anywhere (v6)
22/tcp (v6)                ALLOW IN    Anywhere (v6)
5335 (v6)                  ALLOW IN    Anywhere (v6)
80/tcp (v6)                ALLOW IN    Anywhere (v6)
443/tcp (v6)               ALLOW IN    Anywhere (v6)

Anywhere on eth0           ALLOW FWD   10.6.0.0/24 on wg0
`

**Comment by orazioedoardo** [comment]
Well, I assumed than when you installed the DNS server, you also added an UFW rule to let DNS through.

```
sudo ufw allow 53/tcp
sudo ufw allow 53/udp
```

**Comment by HeinvdW** [comment]
In fact I acted as follows:
1) setup RPI Buster Lite
2) Install PiHole
3) Install unbound
4) Install UFW
5) Install PiVPN

Problem is that I wanted to lean back because PiVPN offered me to adapt the UFW rules.
It made me stop thinking.
Maybe PiVPN should add a comment at the install or setup the rules in the PiVPN installation.

I'm very gratefull for your help.

**Comment by orazioedoardo** [comment]
PiVPN does set up rules for the VPN if ufw is installed and enabled, it won't setup rules for DNS or other services.
