### ISSUE TITLE
[Support] PIVPN not forwarding on latest Raspberry Pi OS

### ISSUE THREAD

**Issue by stonehippo** [pivpn/pivpn#1153]
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

### Issue

I have a Raspberry Pi that has been running PIVPN for over a year, with issue. I had it set up to use OpenVPN, and can confirm that it was both accepting connections and correctly handling traffic about a week ago.

I tried to connect to this OpenVPN server yesterday, and found that it wasn’t correctly forwarding any traffic. When connected to the VPN, I can reach the host that is running the server, but not any hosts within it’s local network, nor on the internet.

### Have you searched for similar issues and solutions?
    (yes/no / which issues?)

Yes. I haven’t see anything that matches this exactly.

### Console output of      `curl -L install.pivpn.dev | bash`
```
  Output Here
```

### Console output of      `pivpn add` or `pivpn add nopass`
```
  I’m not having any issues creating new configs. See below.
```

### Console output of      `pivpn debug`
```

::::		[4mPiVPN debug[0m		 ::::
=============================================
::::		[4mLatest commit[0m		 ::::
commit 32bd1c628af9e1926f3f4471c0bf49c74deff7c7
Author: Orazio <orazioedoardo@users.noreply.github.com>
Date:   Fri Jul 24 18:52:57 2020 +0200

    Update LatestUpdate.md
=============================================
::::	    [4mInstallation settings[0m    	 ::::
PLAT=Raspbian
OSCN=buster
USING_UFW=1
IPv4dev=eth0
dhcpReserv=1
IPv4addr=192.168.1.10/24
IPv4gw=192.168.1.1
install_user=george_w
install_home=/home/george_w
VPN=openvpn
pivpnPROTO=udp
pivpnPORT=11123
pivpnDNS1=10.8.0.1
pivpnDNS2=
pivpnSEARCHDOMAIN=
pivpnHOST=REDACTED
TWO_POINT_FOUR=1
pivpnENCRYPT=256
USE_PREDEFINED_DH_PARAM=
pivpnDEV=tun0
pivpnNET=10.8.0.0
subnetClass=24
UNATTUPG=1
INSTALLED_PACKAGES=(dnsutils openvpn expect)
HELP_SHOWN=1
=============================================
::::  [4mServer configuration shown below[0m   ::::
dev tun
proto udp
port 11123
ca /etc/openvpn/easy-rsa/pki/ca.crt
cert /etc/openvpn/easy-rsa/pki/issued/rpi1b_f5b11b6f-e88a-49ce-b28a-7260b450e7cf.crt
key /etc/openvpn/easy-rsa/pki/private/rpi1b_f5b11b6f-e88a-49ce-b28a-7260b450e7cf.key
dh none
ecdh-curve prime256v1
topology subnet
server 10.8.0.0 255.255.255.0
# Set your primary domain name server address for clients
push "dhcp-option DNS 10.8.0.1"
push "block-outside-dns"
# Override the Client default gateway by using 0.0.0.0/1 and
# 128.0.0.0/1 rather than 0.0.0.0/0. This has the benefit of
# overriding but not wiping out the original default gateway.
push "redirect-gateway def1"
client-to-client
client-config-dir /etc/openvpn/ccd
keepalive 15 120
remote-cert-tls client
tls-version-min 1.2
tls-crypt /etc/openvpn/easy-rsa/pki/ta.key
cipher AES-256-CBC
auth SHA256
user openvpn
group openvpn
persist-key
persist-tun
crl-verify /etc/openvpn/crl.pem
status /var/log/openvpn-status.log 20
status-version 3
syslog
verb 3
#DuplicateCNs allow access control on a less-granular, per user basis.
#Remove # if you will manage access by user instead of device. 
#duplicate-cn
# Generated for use by PiVPN.io
=============================================
::::  [4mClient template file shown below[0m   ::::
client
dev tun
proto udp
remote REDACTED 11123
resolv-retry infinite
nobind
remote-cert-tls server
tls-version-min 1.2
verify-x509-name rpi1b_f5b11b6f-e88a-49ce-b28a-7260b450e7cf name
cipher AES-256-CBC
auth SHA256
auth-nocache
verb 3
=============================================
:::: 	[4mRecursive list of files in[0m	 ::::
::: [4m/etc/openvpn/easy-rsa/pki shows below[0m :::
/etc/openvpn/easy-rsa/pki/:
Default.txt
ca.crt
crl.pem
ecparams
index.txt
index.txt.attr
index.txt.attr.old
index.txt.old
issued
karen.ovpn
openssl-easyrsa.cnf
pockethippo.ovpn
private
prohippo.ovpn
renewed
revoked
safessl-easyrsa.cnf
serial
serial.old
ta.key
work.ovpn
zoe.ovpn

/etc/openvpn/easy-rsa/pki/ecparams:
prime256v1.pem

/etc/openvpn/easy-rsa/pki/issued:
karen.crt
pockethippo.crt
prohippo.crt
rpi1b_f5b11b6f-e88a-49ce-b28a-7260b450e7cf.crt
work.crt
zoe.crt

/etc/openvpn/easy-rsa/pki/private:
ca.key
karen.key
pockethippo.key
prohippo.key
rpi1b_f5b11b6f-e88a-49ce-b28a-7260b450e7cf.key
work.key
zoe.key

/etc/openvpn/easy-rsa/pki/renewed:
private_by_serial
reqs_by_serial

/etc/openvpn/easy-rsa/pki/renewed/private_by_serial:

/etc/openvpn/easy-rsa/pki/renewed/reqs_by_serial:

/etc/openvpn/easy-rsa/pki/revoked:
private_by_serial
reqs_by_serial

/etc/openvpn/easy-rsa/pki/revoked/private_by_serial:
0931AFDEC6AB0E75D3110AA855723800.key
9D582FB35DA31F88303F2F808E8D382C.key

/etc/openvpn/easy-rsa/pki/revoked/reqs_by_serial:
0931AFDEC6AB0E75D3110AA855723800.req
9D582FB35DA31F88303F2F808E8D382C.req
=============================================
::::		[4mSelf check[0m		 ::::
:: [OK] IP forwarding is enabled
:: [OK] Ufw is enabled
:: [OK] Iptables MASQUERADE rule set
:: [OK] Ufw input rule set
:: [OK] Ufw forwarding rule set
:: [OK] OpenVPN is running
:: [OK] OpenVPN is enabled (it will automatically start on reboot)
:: [OK] OpenVPN is listening on port 11123/udp
=============================================
:::: Having trouble connecting? Take a look at the FAQ:
:::: [1mhttps://github.com/pivpn/pivpn/wiki/FAQ[0m
=============================================
::::      [4mSnippet of the server log[0m      ::::
Sep 29 20:51:05 rpi1b ovpn-server[908]: REDACTED:21093 VERIFY EKU OK
Sep 29 20:51:05 rpi1b ovpn-server[908]: REDACTED:21093 VERIFY OK: depth=0, CN=pockethippo
Sep 29 20:51:05 rpi1b ovpn-server[908]: REDACTED:21093 peer info: IV_VER=3.git::b08a6c37
Sep 29 20:51:05 rpi1b ovpn-server[908]: REDACTED:21093 peer info: IV_PLAT=ios
Sep 29 20:51:05 rpi1b ovpn-server[908]: REDACTED:21093 peer info: IV_NCP=2
Sep 29 20:51:05 rpi1b ovpn-server[908]: REDACTED:21093 peer info: IV_TCPNL=1
Sep 29 20:51:05 rpi1b ovpn-server[908]: REDACTED:21093 peer info: IV_PROTO=2
Sep 29 20:51:05 rpi1b ovpn-server[908]: REDACTED:21093 peer info: IV_AUTO_SESS=1
Sep 29 20:51:05 rpi1b ovpn-server[908]: REDACTED:21093 peer info: IV_GUI_VER=net.openvpn.connect.ios_3.2.1-3429
Sep 29 20:51:05 rpi1b ovpn-server[908]: REDACTED:21093 peer info: IV_SSO=openurl
Sep 29 20:51:05 rpi1b ovpn-server[908]: REDACTED:21093 Control Channel: TLSv1.3, cipher TLSv1.3 TLS_AES_256_GCM_SHA384, 256 bit EC, curve: prime256v1
Sep 29 20:51:05 rpi1b ovpn-server[908]: REDACTED:21093 [pockethippo] Peer Connection Initiated with [AF_INET]REDACTED:21093
Sep 29 20:51:05 rpi1b ovpn-server[908]: pockethippo/REDACTED:21093 OPTIONS IMPORT: reading client specific options from: /etc/openvpn/ccd/pockethippo
Sep 29 20:51:05 rpi1b ovpn-server[908]: pockethippo/REDACTED:21093 MULTI: Learn: 10.8.0.2 -> pockethippo/REDACTED:21093
Sep 29 20:51:05 rpi1b ovpn-server[908]: pockethippo/REDACTED:21093 MULTI: primary virtual IP for pockethippo/REDACTED:21093: 10.8.0.2
Sep 29 20:51:05 rpi1b ovpn-server[908]: pockethippo/REDACTED:21093 PUSH: Received control message: 'PUSH_REQUEST'
Sep 29 20:51:05 rpi1b ovpn-server[908]: pockethippo/REDACTED:21093 SENT CONTROL [pockethippo]: 'PUSH_REPLY,dhcp-option DNS 10.8.0.1,block-outside-dns,redirect-gateway def1,route-gateway 10.8.0.1,topology subnet,ping 15,ping-restart 120,ifconfig 10.8.0.2 255.255.255.0,peer-id 0,cipher AES-256-GCM' (status=1)
Sep 29 20:51:05 rpi1b ovpn-server[908]: pockethippo/REDACTED:21093 Data Channel: using negotiated cipher 'AES-256-GCM'
Sep 29 20:51:05 rpi1b ovpn-server[908]: pockethippo/REDACTED:21093 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Sep 29 20:51:05 rpi1b ovpn-server[908]: pockethippo/REDACTED:21093 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
=============================================
::::		[4mDebug complete[0m		 ::::

 ```
### Have you taken any steps towards solving your issue?
```
  which?
```

Yes, I’ve tried several things. I disabled `ufw` to see if it was a firewall issue. I removed and reinstalled PIVPN, and have installed both OpenVPN and WireGuard on the same host, with the same result. I also installed a fresh install on Raspberry Pi OS on another SD card, installed ufw and PIVPN, and put replaced the OS wholesale. Same result: I can create configs, and connect, but cannot get beyond the PIVPN host.

I also installed Ubuntu 20.04 LTS 64-bit on an RPI3, plus ufw and PIVPN. This host worked fine; configs and connections. As a last step, I changed out my router config, releasing and renewing to get a new fixed IP address on the old host, and even redoing the port forwarding config. As long as I’m running Raspberry Pi OS on the original host, I can connect, but no forwarding.

I haven’t tried the latest Raspberry Pi OS on a different RPI with PIVPN yet. I’ll give that a try next, but I don’t have a lot of hope that’ll work.

**Comment by orazioedoardo** [comment]
Could be this https://github.com/pivpn/pivpn/issues/1146

**Comment by stonehippo** [comment]
@orazioedoardo I don't think so. I usually try testing the VPN from a mobile/LTE connection. And it doesn't appear to be a subnet issue: a default install of OpenVPN via PIVPN on Ubuntu seems to work fine. That said, I'm wondering about DNS config. I don't think it is, but I can't remember if I tried a vanilla DNS set up when I re-installed.

**Comment by orazioedoardo** [comment]
Can I see the ufw and iptables configurations?

```
sudo iptables -t nat -S
sudo ufw status verbose
```

**Comment by stonehippo** [comment]
@orazioedoardo I’ve done some more digging, and I think something broke on DNS, not PIVPN. I’m going to close this one.

Just to answer your question, though here’s the output of my current iptables setup:

```
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT
-A POSTROUTING -s 10.6.0.0/24 -o eth0 -m comment --comment wireguard-nat-rule -j MASQUERADE
```

And here’s ufw:

```
Status: active
Logging: on (low)
Default: deny (incoming), allow (outgoing), deny (routed)
New profiles: skip

To                         Action      From
--                         ------      ----
51820/udp                  ALLOW IN    Anywhere                  
22/tcp                     LIMIT IN    Anywhere                  
53/udp                     ALLOW IN    Anywhere                  
22/tcp (v6)                LIMIT IN    Anywhere (v6)             
53/udp (v6)                ALLOW IN    Anywhere (v6)             
51820/udp (v6)             ALLOW IN    Anywhere (v6)             

Anywhere on eth0           ALLOW FWD   10.6.0.0/24 on wg0 
```

Given that the issue seems to happen even when I’ve disabled ufw, I think my local DNS proxy on the host is not binding correctly, so now I’m looking at that.

Thanks for the support.

**Comment by stonehippo** [comment]
Hmm, so I’ve confirmed that this issue seems to be when I use my PIVPN as DNS. I’ve got a very simple DNS proxy that I built that provides the DNS for my Wireguard setup (it’s at [tiny-mdns-proxy](https://github.com/stonehippo/tiny-mdns-proxy)). It was working correctly with PIVPN until sometime in the past couple of weeks.

I know that the DNS proxy is working (if I have PIVPN/Wireguard set up to either use Google or the PIVPN host as DNS, I can connect, then use `nslookup`|`dig` to resolves both local and remote servers), but if I have it set as the DNS for the tunnel, no bueno. I’m going to use public DNS for the moment, since I need the tunnel, but I’m going to spend a little time trying to figure out why this is happening now, and wasn’t before.

**Comment by orazioedoardo** [comment]
Sorry, I don't understand, does DNS work or not when using the VPN?

**Comment by stonehippo** [comment]
@orazioedoardo That's what is confounding. Explicit DNS requests (for example, `dig @10.6.0.1 www.google.com`) resolve and return results when using my PIVPN host for DNS. But anything else seems to fail (trying to use a browser, for example). I can see the requests come in and get resolved by the proxy, but things stall on the connected client. If I configure the client to use a public DNS, things snap back.

I've confirmed that this is happening by altering a couple of Wireguard client configs, and installing them side by side on my iPhone. Enable the one with public DNS, and we're good. PIVPN as DNS host, not so much. I don't think this is really a PIVPN issue, since it could be something funky with the proxy, so it should probably be closed, and I'll comment back here later when I figure out what's happening.

For reference, here's the pertinent part of the configs. First, the working one:

```
[Interface]
PrivateKey = xxxxxxxxxxxxxx
Address = 10.6.0.6/24
DNS = 8.8.8.8, 8.8.4.4

[Peer]
PublicKey = xxxxxxxxxxxx
PresharedKey = xxxxxxxxxxx
Endpoint = my.domainname.com:51820
AllowedIPs = 0.0.0.0/0, ::0/0
```

And the con
```
[Interface]
PrivateKey = xxxxxxxxxxxxxx
Address = 10.6.0.6/24
DNS = 10.6.0.1

[Peer]
PublicKey = xxxxxxxxxxxx
PresharedKey = xxxxxxxxxxx
Endpoint = my.domainname.com:51820
AllowedIPs = 0.0.0.0/0, ::0/0
```

As I mentioned before, this DNS proxy worked fine for over a year, and nothing about it has changed.

**Comment by stonehippo** [comment]
Found the issue with the DNS proxy, and things are good again. Pushed a fix to the repo, too.
