### ISSUE TITLE
[Support] watchguard and openvpn still with password auth

### ISSUE THREAD

**Issue by paradonym** [pivpn/pivpn#1154]
As far as I can see pivpn creates Certificates in both Watchguard and OpenVPN modes.
I know that's the way to go and it's way safer that way, but can we still have connections just using a password?

How do I set the IP range the VPN clients will be put in? (to put them into the routers non-DHCP range to actually access the network).

**Comment by orazioedoardo** [comment]
> As far as I can see pivpn creates Certificates in both Watchguard and OpenVPN modes.
> I know that's the way to go and it's way safer that way, but can we still have connections just using a password?

Possibly: https://openvpn.net/community-resources/using-alternative-authentication-methods/

> How do I set the IP range the VPN clients will be put in? (to put them into the routers non-DHCP range to actually access the network).

By changing the variable [here](https://github.com/pivpn/pivpn/blob/32bd1c628af9e1926f3f4471c0bf49c74deff7c7/auto_install/install.sh#L1027) (for openvpn) or [here](https://github.com/pivpn/pivpn/blob/32bd1c628af9e1926f3f4471c0bf49c74deff7c7/auto_install/install.sh#L1049) (for wireguard).

**Comment by paradonym** [comment]
> Possibly: https://openvpn.net/community-resources/using-alternative-authentication-methods/

Does that mean pivpn -add just doesn't create certificates if client-cert-not-required is found in the /etc/openvpn/server.conf or does that mean that the certificate created by pivpn can be ignored?

I was just a bit confused, older howtos for pivpn possibly using old versions simply got auth data without certificates. That may have changed, but I also couldn't see an option for that in the setup dialogs.

**Comment by orazioedoardo** [comment]
`pivpn add` always creates a certificate protected with a password, optionally without password. Login with username + password in not implemented by pivpn but that link suggests some ways to accomplish that. You can set `client-cert-not-required` if you actually want to use username + password and not username + password + client certificate.

**Comment by TinCanTech** [comment]
`--client-cert-not-required` is deprecated, use `--verify-client-cert none`

**Comment by paradonym** [comment]
Couldn't start pivpn with client-cert-not-required or verify-client-cert none in /etc/openvpn/server.conf. pivpn ovpn -d logged that lines as an invalid configuration. 
Do I do something wrong here? Without that connections with Cert work.

**Comment by orazioedoardo** [comment]
You need to add an authentication method as described in the resource posted.

**Comment by orazioedoardo** [comment]
Closing as unrelated and inactive, but may be useful for some user, so will add the information badge
