### ISSUE TITLE
Wireguard on host, PiHole in Docker with own IP via Macvlan

### ISSUE THREAD

**Issue by zilexa** [pivpn/pivpn#1155]
In raising this issue, I confirm the following: 

- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

### Issue
PiVPN - Wireguard works as in: connection works, access to internet and LAN or even LAN only (my goal). 
**However, it only works if I enter a public DNS address in the client config (e.g. 1.1.1.1). Not when I use my own DNS server (PiHole) running via Docker with a macvlan. My Wireguard clients can not ping to the PiHole IP address or any of the other two addresses created via the Docker macvlan network.** So the issue is not with PiHole not listening (I followed this information and can confirm PiHole (after a clean install) is now listening on all interfaces. 

Goal: access Docker macvlan IP addresses (like PiHole) when remote, connected via Wireguard.

Note during installation of PiVPN I simply selected 1.1.1.1 to be able to test the connection. Afterwards I manually changed the client config files to DNS of my PiHole. 
```
router: 192.168.88.1
LAN network: 192.168.88.0/24
host (Ubuntu 20.04): 192.168.88.10
```

```
Docker macvlan:
networks:
  DNS-network:
    driver: macvlan
    driver_opts:
      parent: eno1
    ipam:
      config:
        - subnet: 192.168.88.0/24
          gateway: 192.168.88.1
          ip_range: 192.168.88.96/29  # Chosen sub range of the subnet
          aux_addresses:          # This reserves addresses as they are configured per container.
            host-macvlan: 192.168.88.96 # reserved for a macvlan that needs to be created on the host to be able to access PiHole etc.
            Unbound: 192.168.88.98
            PiHole: 192.168.88.99
            Unifi: 192.168.88.100
```
This creates a Docker macvlan, allowing 3 containers to have their own IP address (no need for port forwarding, required with lots of containers that need the same ports). 
I have 3 docker that I need access to, their addresses will be: 192.168.88.98 (Unbound), 192.168.88.99 (PiHole), 192.168.88.100 (Unifi Controller).

With any LAN client, I can now access these IP addresses. However I cannot reach them via the host machine itself.
In order to be able to access these containers on the host machine, I have created a macvlan (besides the one in Docker) on the host machine itself:
```
sudo ip link add mynet-shim link eno1 type macvlan mode bridge
sudo ip addr add 192.168.88.96/32 dev mynet-shim
sudo ip link set mynet-shim up
sudo ip route add 192.168.88.96/29 dev mynet-shim
```
What is happening here: the addr add command takes the first IP in the range of the docker macvlan.
Then the entire docker macvlan range is added as route.

Now, the host machine can access these IP addresses. 
Note: my DNS server (as entered in my router) is now 192.168.88.99 (PiHole in Docker). It is not the IP of the host running Docker.

### Have you searched for similar issues and solutions?
    (yes)
https://github.com/pivpn/pivpn/issues/1147

### Console output of      `pivpn debug`
```
::::		PiVPN debug		 ::::
=============================================
::::		Latest commit		 ::::
commit 32bd1c628af9e1926f3f4471c0bf49c74deff7c7 (grafted, HEAD -> master, origin/master, origin/HEAD)
Author: Orazio <orazioedoardo@users.noreply.github.com>
Date:   Fri Jul 24 18:52:57 2020 +0200

    Update LatestUpdate.md
=============================================
::::	    Installation settings    	 ::::
PLAT=Ubuntu
OSCN=focal
USING_UFW=0
IPv4dev=eno1
install_user=asterix
install_home=/home/asterix
VPN=wireguard
pivpnPORT=51822
pivpnDNS1=1.1.1.1
pivpnDNS2=
pivpnHOST=REDACTED
INPUT_CHAIN_EDITED=0
FORWARD_CHAIN_EDITED=1
pivpnPROTO=udp
pivpnDEV=wg0
pivpnNET=10.6.0.0
subnetClass=24
UNATTUPG=1
INSTALLED_PACKAGES=()
=============================================
::::  Server configuration shown below   ::::
[Interface]
PrivateKey = server_priv
Address = 10.6.0.1/24
ListenPort = 51822
PostUp   = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eno1 -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eno1 -j MASQUERADE
### begin Shanti-Pixel ###
[Peer]
PublicKey = Shanti-Pixel_pub
PresharedKey = Shanti-Pixel_psk
AllowedIPs = 10.6.0.2/32
### end Shanti-Pixel ###
### begin Rud-Pixel ###
[Peer]
PublicKey = Rud-Pixel_pub
PresharedKey = Rud-Pixel_psk
AllowedIPs = 10.6.0.3/32
### end Rud-Pixel ###
### begin Idefix ###
[Peer]
PublicKey = Idefix_pub
PresharedKey = Idefix_psk
AllowedIPs = 10.6.0.4/32
### end Idefix ###
=============================================
::::  Client configuration shown below   ::::
[Interface]
PrivateKey = Shanti-Pixel_priv
Address = 10.6.0.2/24
DNS = 192.168.88.99

[Peer]
PublicKey = server_pub
PresharedKey = Shanti-Pixel_psk
Endpoint = REDACTED:51822
AllowedIPs = 0.0.0.0/0, ::0/0
=============================================
:::: 	Recursive list of files in	 ::::
::::	/etc/wireguard shown below	 ::::
/etc/wireguard:
configs  keys  wg0.conf

/etc/wireguard/configs:
clients.txt  Idefix.conf  Rud-Pixel.conf  Shanti-Pixel.conf

/etc/wireguard/keys:
Idefix_priv  Idefix_psk  Idefix_pub  Rud-Pixel_priv  Rud-Pixel_psk  Rud-Pixel_pub  server_priv	server_pub  Shanti-Pixel_priv  Shanti-Pixel_psk  Shanti-Pixel_pub
=============================================
::::		Self check		 ::::
:: [OK] IP forwarding is enabled
:: [OK] Iptables MASQUERADE rule set
:: [OK] Iptables FORWARD rule set
:: [OK] WireGuard is running
:: [OK] WireGuard is enabled (it will automatically start on reboot)
:: [OK] WireGuard is listening on port 51822/udp
=============================================
:::: Having trouble connecting? Take a look at the FAQ:
:::: https://github.com/pivpn/pivpn/wiki/FAQ
=============================================
:::: WARNING: This script should have automatically masked sensitive       ::::
:::: information, however, still make sure that PrivateKey, PublicKey      ::::
:::: and PresharedKey are masked before reporting an issue. An example key ::::
:::: that you should NOT see in this log looks like this:                  ::::
:::: YIAoJVsdIeyvXfGGDDadHh6AxsMRymZTnnzZoAb9cxRe                          ::::
=============================================
::::		Debug complete		 ::::

### Have you taken any steps towards solving your issue?
Yes, I learned how to create the macvlan on the host from articles on the web.

**Comment by orazioedoardo** [comment]
Sorry but if the problem is the DNS server and the VPN works with an upstream one, then this is not related to PiVPN.


```
PostUp   = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eno1 -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eno1 -j MASQUERADE
```

By the way you don't need these, PiVPN already sets this rules as part of the installation.

**Comment by orazioedoardo** [comment]
No responses in a while, closing...

**Comment by zilexa** [comment]
I switched to Adguard Home. You don't install that via Docker since it is just a single binary file and a config file. 

Now I can connect with PiVPN Wireguard while remote, and only let DNS traffic go over the tunnel by simply entering my IP:port (my serverip:Adguard port) in the DNS field of the client conf file. And by limiting the cidr to that of my LAN, all other traffic bypasses the tunnel. Only DNS and LAN access go through the tunnel.

This even works with Unbound in Docker, and AdGuard using the Unbound IP:port as the sole upstream DNS server :) 

The issue was really with PiHole-in-Docker.
