### ISSUE TITLE
[Support] Question - Can I uninstall "iptables-persistant" and replace it with UFW

### ISSUE THREAD

**Issue by smokemyshoes** [pivpn/pivpn#1156]
- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

Hi

Maybe more a question than a support request, but nevertheless...

As far as I remember the pivpn installation-script install _iptables-persistent_ to ensure that firewall rules are loaded on boot, correct?

I would like to install _UFW_ as i'm not that savvy with iptable rulles and would like a simpler interface. But as far as I understand, _iptables-persistent_ and _UFW_ doesn't get along very well and thus my question is; Can I uninstall iptables-persistent and let UFW handle loading of firefall rules upon boot without compromising security?

If there's something I have completely misunderstood, please enlighten me. Thanks in advance.

**Comment by smokemyshoes** [comment]
Hmm... I wanted to add some further info to the original post but for some reason I'm not able to...

[This issue](https://github.com/pivpn/pivpn/issues/414) (#414) was the one that suggested to me that _UWF_ and _iptables-persistent_ clashes and [this](https://github.com/pivpn/pivpn/issues/1152)support request (#1152) tells me that _pivpn_ does infact work with _UFW_ but in this case _UFW_ was installed before _pivpn_.

So actually I would like to rephrase my question to:
1) Does _UFW_ and _iptables-persistent_ still clash? and if yes...
2) Can I just uninstall _iptables-persistent_ and install _UFW_ without first uninstalling _pivpn_ or is it advised to first uninstall _pivpn_ and the reinstall it again afterwards?

**Comment by smokemyshoes** [comment]
Hmm... I wanted to add some further info to the original post but for some reason I'm not able to...

[Issue #414](https://github.com/pivpn/pivpn/issues/414) was what originally suggested to me that _UWF_ and _iptables-persistent_ clashes and from [issue #1152](https://github.com/pivpn/pivpn/issues/1152) it's evident that _pivpn_ does infact work with _UFW_ but in this case _UFW_ was installed before _pivpn_.

So actually I would like to rephrase my question to:
1) Does _UFW_ and _iptables-persistent_ still clash? and if yes...
2) Can I just uninstall _iptables-persistent_ and install _UFW_ without first uninstalling _pivpn_ or is it advised to first uninstall _pivpn_ and the reinstall it again afterwards?

**Comment by orazioedoardo** [comment]
1. I'm not sure.
2. If you install UFW after PiVPN, you will need to add required rules for the functioning of the VPN by yourself, whereas if you install PiVPN after UFW, the script will set rules for you.

**Comment by smokemyshoes** [comment]
Okay, then it might be simplest just to uninstall pivpn first.
