### ISSUE TITLE
Works fine when connected over Wired Ethernet but fails over WiFi

### ISSUE THREAD

**Issue by micmosoft** [pivpn/pivpn#1157]
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

**Describe the bug**
I have a source and target location.  They are different.  On the target is a Raspberry pi 4B installed with latest PiVpn

The source is my house about 50km away.

When I connect via wired Ethernet from my Laptop with OpenVpn client to back of ISP router works fine
When I instead connect via any one of my Mikrotik (I configured) Wireless Access, via same laptop, with same config file points it JUST DOES NOT WORK !!
When I connect my Laptop to a Mobile hotspot from my 4G phone  (Three UK network) it works fine

**To Reproduce**
a) try the client with your laptop and a 4G hotspot connection
b) try same client on same laptop via Wifi Connection.
Obviously I'd like to emphasise the source location is NOWHERE near the target location, 40km distant

(There was a very similar report raised and it was closed, IMHO wrongly.  Somebody tried to add to the closed post but nothing happened.  The claim was made I think in this other report that the user was trying to reach the PiVpn target whilst sitting on the same Wifi Network as the PiVpn.  )

**Expected behavior**
Expected behaviour is that I would get a working PiVpn connection over my home Wifi which needless to say works for everything else. 

**Screenshots**

**Desktop (please complete the following information):**
 - VPN client is OpenVPN Connect 3.2.0 1064
 - OS:  Windows 10 Enterprise Build 2004, all fixes applied

**Smartphone (please complete the following information):**
My Smartphone is a Oneplus 7T running Android 10.0.13.HD65BA all latest fixes upto Sept 2020 applied

**Additional context**

So clearly this is a networking problem, but it is bugging me and my neighbour who also tried it from their completely different ISP, using their wireless connection and it doesn't work either.  Exact same issue.  Their laptop works when using a Hotspot, but when at their home, using their Wifi to connect to the remote PiVpn no worky.

PiVpn at the target end is clearly working fine as the 1194 port forward works and everything works when the client connection is made via my 4G connection.  But somehow when the client i.e. me on the same laptop, connects from the home network, noworky.   NONE of my firewalls  (and there are many) are blocking outbound 1194, and to repeat, if I connect an Ethernet wire from laptop directly to the ISP router, then all works fine.

From the fact that direct connection to the back of the ISP router works it cannot be that the ISP is somehow blocking my outbound request.

**Comment by shelleycat485** [comment]
Can you ping with both the ethernet connection and the wifi connection to the source with the VPN turned off?  If so, can you change the ping size to 1500 and then verify that you can still ping from both?.   
Can you check that you are using IP V4 on both?

**Comment by orazioedoardo** [comment]
No comments in a while, closing...
