### ISSUE TITLE
[BUG] pivpn: command not found (after instalation)

### ISSUE THREAD

**Issue by BanjerHD** [pivpn/pivpn#1160]
- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

**Describe the bug**
I installed pivpn and rebooted, and when I type `pivpn` in console, it says: `bash: pivpn: command not found`.
I am on a raspberry pi.
I tried unstalling and installing again and the only errors that are there are:
```
ln: failed to create symbolic link '/etc/bash_completion.d/pivpn': File exists
ln: failed to create symbolic link '/usr/local/bin/pivpn': No such file or direc
```
I don't know if this is because I installed it before or if it did the same the first time.

**To Reproduce**
1. Install pivpn
2. type `pivpn` in console

**Expected behavior**
The normal behavior when typing `pivpn`

**Desktop (please complete the following information):**
 - OS: Raspbian
 - Version: 9

**Comment by shelleycat485** [comment]
The uninstall/reinstall may not have completed correctly, so I am ignoring the two symbolic link errors to start with.  I've just installed on a rpi 4, but it happens to be running buster, but the locations should be the same.
1  Can you show output of: ls /usr/local/src/pivpn
2  Can you show output of:  ls /etc/pivpn/wireguard/setupVars.conf
3  Can you show output of: ls /opt/pivpn
4 Can you show output of:  ls /usr/local/bin
5 Can you show output of: file /usr/local/bin/pivpn
6 Can you show output of: which pivpn
7 Can you show output of /etc/os-version, and say which type of pi you are using
8 Were  you trying on a new installation, and if so, have you tried version 10 (buster)
9  Were you using wireguard or openvpn, I'm assuming you left it as the default of wireguard

**Comment by shelleycat485** [comment]
Its the missing /usr/local/bin.  My output is:

pi@rpi4:~ $ ls /usr/local/bin
pivpn

which is the command that is missing.   I'm looking for a sd card now to check with version 9, but /usr/local/bin is a standard location for raspbian/debian distributions as far as I know.  You may have to reinstall the operating system if something like that has gone missing.  I don't think that is a fault with the installer, something broke your operating system earlier, but I'll try to check.

**Comment by BanjerHD** [comment]
@shelleycat485 Thanks for helping me out!! I got it working using:
```
sudo mkdir /usr/local/bin
```
And then doing `curl -L https://install.pivpn.io | bash` again and selecting repair.

I think it is a problem with my OS indeed and I hope that it works like normal now after creating the folder manualy.
