### ISSUE TITLE
Mac Can't see Home Network Devices, Shared Resources

### ISSUE THREAD

**Issue by graydon2212** [pivpn/pivpn#1161]
I'm not the greatest with computers, and decided to get a Raspberry Pi to learn more.  My first project was to set My Raspberry Pi 4 up as a VPN Server. To my amazement bey pretty much following the instructions here I succeeded and it took me less than an hour!

If I connect from another Network using OpenVPN my MacBook is now routing internet traffic back through my home network...So far so good.

When I go into the Finder, I can't see my other Mac Devices....Not so good.  If I open Network Utility on my MacBook I can ping all of the IP Addresses of the devices connected to my home network.

Am I missing something simple here?

Thanks in advance for your help....

**Comment by graydon2212** [comment]
Is my question making no sense?

**Comment by orazioedoardo** [comment]
Can you connect to those other devices via IP?

**Comment by graydon2212** [comment]
No.  I can screen share using VNC.  But I can’t access the disks on my Apple Mac Computers or on My WD My Cloud NAS.  

I can ping all of those device when connected via VPN however.  And Traceroute shows the hops to get to them.

**Comment by orazioedoardo** [comment]
If you can screenshare via VNC to an host inside the local network, then the VPN is definitely working.

What protocol and/or ports do you use to access shared disks on your Mac or the NAS? Protocols that rely on Bonjour don't work via VPN.

**Comment by graydon2212** [comment]
I have both afp and smb/Windows selected on my Mac’s sharing properties.   

When I connect via VPN my internet traffic appears to come from the IP address of my home internet connection.   So the VPN is definitely working.  It’s just the access to the shared drives that seems to be the issue.

**Comment by orazioedoardo** [comment]
Try to connect using smb://ipaddress or something similar: https://support.apple.com/guide/mac-help/connect-mac-shared-computers-servers-mchlp1140/10.15/mac/10.15

**Comment by orazioedoardo** [comment]
No replies in a while, closing...
