### ISSUE TITLE
[Support] How do I allow clients access to my home network but not the internet through my PiVPN, BUT NOT KILL THE CLIENT INTERNET CONNECTION?

### ISSUE THREAD

**Issue by rwwinn1** [pivpn/pivpn#1162]
https://github.com/pivpn/pivpn/wiki/WireGuard#how-do-i-allow-clients-access-to-my-home-network-but-not-the-internet-through-my-pivpn does not explain how to allow clients to connect to home network but not the internet through wireguard AND NOT KILL THE INTERNET CONNECTION. I've searched all over to find out how to route LAN (home network) traffic through the VPN and all other traffic via the internet.

If I set
AllowedIPs = 192.168.2.0/24 <my home LAN>
on the client and connect to the VPN, I can ping a server at 192.168.2.15, but can't ping google.com. If I am not connected to the VPN I can, obviously, ping google.com and cannot ping 192.168.2.1.

How do I configure AllowedIPs on the client to allow traffic to 192.168.2.0/24 AND allow all other traffic through the internet? Do I also have to modify parameters on the server side?

### Have you searched for similar issues and solutions?
```
YES
```

### Console output of      `curl -L install.pivpn.dev | bash`
![image](https://user-images.githubusercontent.com/23082209/96031117-2b1a1400-0e1a-11eb-907b-d947b5386796.png)

### Console output of      `pivpn add` or `pivpn add nopass`
```
  Output Here
```

### Console output of      `pivpn debug`
```
pi@raspberrypi:~ $ pivpn debug
::::            PiVPN debug              ::::
=============================================
::::            Latest commit            ::::
commit 32bd1c628af9e1926f3f4471c0bf49c74deff7c7 (grafted, HEAD -> master, origin/test, origin/master, origin/HEAD)
Author: Orazio <orazioedoardo@users.noreply.github.com>
Date:   Fri Jul 24 18:52:57 2020 +0200

    Update LatestUpdate.md
=============================================
::::        Installation settings        ::::
PLAT=Raspbian
OSCN=buster
USING_UFW=0
IPv4dev=eth0
IPv4addr=192.168.2.21/24
IPv4gw=192.168.2.1
install_user=pi
install_home=/home/pi
VPN=wireguard
pivpnPORT=51820
pivpnDNS1=9.9.9.9
pivpnDNS2=149.112.112.112
pivpnHOST=REDACTED
INPUT_CHAIN_EDITED=0
FORWARD_CHAIN_EDITED=0
pivpnPROTO=udp
pivpnDEV=wg0
pivpnNET=10.6.0.0
subnetClass=24
UNATTUPG=1
INSTALLED_PACKAGES=(dnsutils iptables-persistent raspberrypi-kernel-headers wireguard wireguard-tools wireguard-dkms qrencode unattended-upgrades)
=============================================
::::  Server configuration shown below   ::::
[Interface]
PrivateKey = server_priv
Address = 10.6.0.1/24
ListenPort = 51820
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
### begin Cami ###
[Peer]
PublicKey = Cami_pub
PresharedKey = Cami_psk
AllowedIPs = 10.6.0.2/32
### end Cami ###
### begin Dad ###
[Peer]
PublicKey = Dad_pub
PresharedKey = Dad_psk
AllowedIPs = 10.6.0.3/32
### end Dad ###
=============================================
::::  Client configuration shown below   ::::
[Interface]
PrivateKey = Cami_priv
Address = 10.6.0.2/24
DNS = 9.9.9.9, 149.112.112.112

[Peer]
PublicKey = server_pub
PresharedKey = Cami_psk
Endpoint = REDACTED:51820
AllowedIPs = 0.0.0.0/0, ::0/0
=============================================
::::    Recursive list of files in       ::::
::::    /etc/wireguard shown below       ::::
/etc/wireguard:
configs  keys  wg0.conf

/etc/wireguard/configs:
Cami.conf  clients.txt  Dad.conf

/etc/wireguard/keys:
Cami_priv  Cami_psk  Cami_pub  Dad_priv  Dad_psk  Dad_pub  server_priv  server_pub
=============================================
::::            Self check               ::::
:: [OK] IP forwarding is enabled
:: [OK] Iptables MASQUERADE rule set
:: [OK] WireGuard is running
:: [OK] WireGuard is enabled (it will automatically start on reboot)
:: [OK] WireGuard is listening on port 51820/udp
=============================================
:::: Having trouble connecting? Take a look at the FAQ:
:::: https://github.com/pivpn/pivpn/wiki/FAQ
=============================================
:::: WARNING: This script should have automatically masked sensitive       ::::
:::: information, however, still make sure that PrivateKey, PublicKey      ::::
:::: and PresharedKey are masked before reporting an issue. An example key ::::
:::: that you should NOT see in this log looks like this:                  ::::
:::: YIAoJVsdIeyvXfGGDDadHh6AxsMRymZTnnzZoAb9cxRe                          ::::
=============================================
::::            Debug complete           ::::

```
### Have you taken any steps towards solving your issue?
```
  which?
```

**Comment by shelleycat485** [comment]
I think what you want is called something like split horizon.  You need to set up routes on the client so that:
Traffic for the VPN goes down the WG interface
All other traffic goes through the Ethernet/Wifi connection.
I have never done this, because its complicated and if you get it wrong you will expose the Server network (the home network in your case) to the internet without a firewall.  I have been using VPNs to allow remote access to an office, but I have never dared to try setting up complicated routing.
Its beyond the scope of pivpn, which is supposed to be an easy to use VPN set up.

**Comment by rwwinn1** [comment]
So, I found stuff on setting up wireguard with "split tunneling", but there are inconsistencies with how to do it and if it even actually works. 
This [article ](https://emanuelduss.ch/2018/09/wireguard-vpn-road-warrior-setup/)(under split tunneling) said that adding the VPN IP and the remote network IP to the "AllowedIPs" variable on the client creates a split tunnel. That doesn't work for me.

This [article](https://medium.com/@ATheCoder/how-to-use-split-tunneling-for-your-vpn-on-windows-10-85e76635914d) says that you have to configure Windows Split Tunneling on your Windows client. I have not tried this because I suspect there is a simpler solution.

This [article](https://news.ycombinator.com/item?id=19544532) says the same thing about putting the VPN IP and the remote network IP in the AllowedIPs variable. Again for me this allows access to the remote network but not the internet.

This [one](https://www.reddit.com/r/selfhosted/comments/b5pymz/split_tunnel_in_wireguard/) says to only put the remote network IP in AllowedIPs and it should work. No.

I've determined that it is a DNS issue. google.com is not resolving when I am connected to my vpn with a split tunnel (via setting AllowedIPs = 192.168.2.0/24 on my client). But I can ping google via 216.58.194.174. I have confirmed that my remote network traffic is going through the vpn and my ping to google is not so I do have a split tunnel.

If I put the DNS server IPs in AllowedIPs (AllowedIPs = 192.168.2.0/24, 9.9.9.9, 149.112.112.112) then, when I am connected to vpn google.com will resolve and ping through the internet split, not the vpn split.

Why? Am I supposed to configure DNS on the client manually in order to have a split tunnel (instead of putting the DNS IPs in AllowedIPs)?

**Comment by shelleycat485** [comment]
Sorry, I cannot help further, you have just confirmed to me that it is complicated.  Let us know what you find.

**Comment by orazioedoardo** [comment]
Can you post your current client configuration (one of them)? Remove the endpoint IP and all keys.

**Comment by rwwinn1** [comment]
[Interface]
PrivateKey = <>
Address = 10.6.0.3/24
DNS = 9.9.9.9, 149.112.112.112

[Peer]
PublicKey = <>
PresharedKey = <>
AllowedIPs = 192.168.2.0/24
Endpoint = <>

If I hard code the DNS into my client adapter everything is fine and that solves the problem. If I leave my client adapter to obtain a DNS automatically, then the client can't resolve host names when connected to the VPN.

Also, if I leave the client adapter to obtain a DNS automatically but put the DNS IPs in "AllowedIPs" in the wireguard client configuration, then that solves the issue too; the client can resolve host names.

**Comment by orazioedoardo** [comment]
`AllowedIPs` specifies which IP or IP range should go through the tunnel. The optional `DNS` field specifies the DNS server(s) that should override the system DNS when you turn on the VPN interface on the client.

Since 9.9.9.9 and 149.112.112.112 don't fall into the 192.168.2.0/24 range, they will NOT go through the VPN, instead, they should go outside the tunnel.

When you turn on the VPN, which DNS server is your client actually using?

**Comment by rwwinn1** [comment]
I'm testing my VPN connection using my mobile hot spot (so as not to be on the LAN I'm connecting to via VPN when testing the VPN). The DNS when I use my hotspot is the hotspot gateway 192.168.43.138. This resolves host names when not on VPN and doesn't when on VPN.

**Comment by orazioedoardo** [comment]
You WireGuard client is supposed to use DNS 9.9.9.9, 149.112.112.112 when you turn on the VPN. What device are you using?

**Comment by rwwinn1** [comment]
Right. My client is a windows 10 machine. The hotspot is an Android phone.

**Comment by orazioedoardo** [comment]
If you use the config on your Android phone instead, do you encounter any problem?

**Comment by rwwinn1** [comment]
So, I dumped testing through the android hot spot and tested using a network not related to my home LAN. Had the same issue: when connecting with the wireguard client with just my home LAN IP range as the "Allowed IPs" value in the client configuration, I could access my LAN, but nothing on the internet because DNS was dead. 

Finally, I deleted the DNS variable from my wireguard client config, "DNS = 9.9.9.9, 149.112.112.112" and viola, I have a split tunnel: I can access my home network space (I connect to home machines via IP address, not domain names so I don't need a DNS on the home network side) and the internet (the internet side can now resolve with my internet provider DNS). For some reason, the DNS specified in the wireguard client config was blocking my machine from using the internet side DNS and was also not resolving thorough the VPN side.

**Comment by orazioedoardo** [comment]
> For some reason, the DNS specified in the wireguard client config was blocking my machine from using the internet side DNS and was also not resolving thorough the VPN side.

Considering [this](https://github.com/pivpn/pivpn/issues/1162#issuecomment-712214804), I think it was an issue with your client.

**Comment by rwwinn1** [comment]
I believe the resolution is that if the optional DNS variable is set on the client, the split tunnel must use those DNS entries **through the VPN side of the split.** And those DNS entries can only be reached on the VPN side if they fall into the ip range specified in Allowed IPs. Otherwise you must omit the optional DNS variable on the client and then the internet side of the split will resolve the DNS.

**Comment by orazioedoardo** [comment]
> I believe the resolution is that if the optional DNS variable is set on the client, the split tunnel must use those DNS entries **through the VPN side of the split.**

I've tested this on Linux and it doesn't seem to be the case. Using `DNS = 9.9.9.9, 149.112.112.112` with `AllowedIPs = 192.168.2.0/24`, makes queries go outside the tunnel as expected. In fact DNS = something simply configures the sistem resolver to use those IPs, it has nothing to do with wireguard itself.

**Comment by rwwinn1** [comment]
Perhaps its a Windows issue or a Windows Wireguard client issue.
