### ISSUE TITLE
IP Questions

### ISSUE THREAD

**Issue by cbirchy87** [pivpn/pivpn#117]
So PiVPN is all installed and really happy so far. I have whats more of a networking question. I want to make sure my IP addresses are all correct and can contact

Home network 192.168.0.1 - 192.168.0.254 Subnet 255.255.255.0
Home PC - 192.168.0.6
Raspberry Pi: 192.168.0.7
CCTV Cameria 192.168.0.8

When im using another internet connection my IP to my laptop is set by PiVPN to: 10.8.0.6 Subnet 255.255.255.252

With these details will i be able to install my CCTV camera onto its software onto the PC. In other words can these IP communicate. If they cant how can i change the IP the PIVPN gives me.

Kind Regards

**Comment by redfast00** [comment]
Yes, they should be able to communicate. If it's not too much effort and you are able to, please change your home subnet to something uncommon like 192.168.66.0/24, so you won't run into subnet conflicts. Let me know if you have any problems.

**Comment by cbirchy87** [comment]
that maybe possible. I will test out comms tonight. (uk time) thanks again

**Comment by cbirchy87** [comment]
OK just tested now. Working completly perfectly! Great job! not going to change the home network range due to the fallout being a bad day in changing settings. My camera is commincating perfectly!

Very impressed! I am going to use the project to demostrate VPN links! thanks again!
