### ISSUE TITLE
[BUG] wiki says to run pivpn -u rather than pivpn -d to debug

### ISSUE THREAD

**Issue by haltdev** [pivpn/pivpn#1171]
https://github.com/pivpn/pivpn/wiki/FAQ

> If your debug log shows some [ERR], accept the [Y/n], run **pivpn -u** again and verify that all checks pass. If not, stop here and look up the error (if you get any) among existing issues or open a new issue.

The command should be pivpn -d

**Comment by orazioedoardo** [comment]
Thanks for spotting this! Fixed.
