### ISSUE TITLE
Can't copy files to NAS SMB share

### ISSUE THREAD

**Issue by widarr** [pivpn/pivpn#1172]
Yesterday I set up a VPN Server for my office via the PiVPN script on the latest Raspberry Pi (Model B 8GB RAM)
OS: latest Raspberry Pi OS Version: August 2020

The only thing I did before was giving all computers & printers in the office a static IP because the hostnames of the machines where not resolved. But access via IP address works.

Most stuff seems to work, I made some VNC connections to computers in the network with TightVNC and RealVNC, I can open the share on a WD MyCloudEx2 Ultra NAS and map a Network drive on Windows / mount a smb:// dir on my Arch Linux box.
I can also read/copy files to my local machine from that NAS.

What does not work is copying files to the NAS share in the VPN network. (Tried a 30kB pdf file)
Even stranger is that when I create a new file in a NAS dir and write something to it and save - it works! 
(Copying files to the NAS from within the office LAN works of course)
But copying takes an eternity and stops with the error Message "There is a problem accessing Y:\..... Make sure you are connected to the network and try again"

I read something about a TUN/TAP issue with SMB, may that be it?

**Comment by shelleycat485** [comment]
1 Are you sure the username/password for the NAS directory you accessing is correct for the copy and has write permissions?  
2 Can you show the network mapping command line you use. I find using mapped drive letters does work.  e.g. net use z: \\192.168.123.22\data /user:name
3 Have you tried wireshark to see you have bidirectional traffic to and from the vlan client

**Comment by orazioedoardo** [comment]
No replies in a while, closing...
