### ISSUE TITLE
[Support] MAC OSX routing not working / Windows routing okay.

### ISSUE THREAD

**Issue by paradonym** [pivpn/pivpn#1173]
### Issue

MAC OS X Clients seems not to get internal IPs/Hostname access because of internal DNS address warning, while Windows Clients work as expected.

Error Message (of both OpenVPN Connect and Tunnelblick on MAC OS X):
Warning: DNS server address 'internal IP of router in the network of the Pi' is not a public IP address amd is not being routed through the VPN.

MAC OS X Clients can connect, but can't access the IP range of the network PiVPN is, and are blocked from accessing websites (which is self-explanatory because of the message)

### Have you searched for similar issues and solutions?
    (yes/no / which issues?)
https://www.reddit.com/r/VPN/comments/ab0hi2/pivpn_and_mac/ describes that you have to use third-party-software. Tunnelblick and OpenVPN Connect is used by the clients.

### Console output of      `curl -L install.pivpn.dev | bash`
```
  That would install Pivpn Dev? That's not what I want nor what I think would help in any way. I can assure you the AVM FritzBox router has unfiltered internet access.
```

### Console output of      `pivpn add` or `pivpn add nopass`
```
pi@$hostname:~ $ pivpn add
::: To pass off to the pivpn command for each protocol
:::
::: Usage: pivpn wg  <command> [option]
::: Usage: pivpn ovpn <command> [option]
:::
:::  -h,  help             Show this help dialog
:::  -u,  uninstall        Uninstall pivpn from your system!
:::  -bk, backup           Backup VPN configs and user profiles
pi@$hostname:~ $ pivpn add nopass
::: To pass off to the pivpn command for each protocol
:::
::: Usage: pivpn wg  <command> [option]
::: Usage: pivpn ovpn <command> [option]
:::
:::  -h,  help             Show this help dialog
:::  -u,  uninstall        Uninstall pivpn from your system!
:::  -bk, backup           Backup VPN configs and user profiles

```

### Console output of      `pivpn debug`
```
pi@$hostname:~ $ pivpn debug
::: To pass off to the pivpn command for each protocol
:::
::: Usage: pivpn wg  <command> [option]
::: Usage: pivpn ovpn <command> [option]
:::
:::  -h,  help             Show this help dialog
:::  -u,  uninstall        Uninstall pivpn from your system!
:::  -bk, backup           Backup VPN configs and user profiles
```
### Have you taken any steps towards solving your issue?
```
searched for differences whether Apple thinks it has to access OpenVPN servers differently than any other operating system would normally do. - without any luck.

Analysing whether it is somewhat invalid to use DNS servers inside IP ranges OpenVPN servers are in... Which should be possible in any situation (which already is when using Windows to connect).

LAN access is possible. The clients inside the network need to connect to a NAS, Windows clients can already do that when connecting to the VPN.

Haven't checked same-IP range on the client side of the client-to-site connection yet... (but asked users to report that). it may be possible that both sides using the same default IP range which could lead to errors, but especially not to errors on the DNS in the VPN clients log.
```

**Comment by orazioedoardo** [comment]
Since you have both openvpn and wireguard, please provide the output of the openvpn debug using `pivpn ovon debug`

**Comment by paradonym** [comment]
IP Ranges of all MAC users had been the same, one end had to change because of openvpn client routing
