### ISSUE TITLE
[Feature Request] Make pivpn not always set "AllowedIPs = 0.0.0.0/0, ::0/0" cause I mostly generate split tunnels for wireguard.

### ISSUE THREAD

**Issue by mwoolweaver** [pivpn/pivpn#1177]
So this turned into a feature request quickly. 

As you can see here on [line 113 of wireguard/makeCONF.sh](https://github.com/pivpn/pivpn/blob/test/scripts/wireguard/makeCONF.sh#L113) AllowedIPs is always set to 0.0.0.0/0, ::0/0 which is kinda inconvenient since I only ever use split tunnels for dns and LAN access when not home. The ability to set this variable via `/etc/pivpn/wireguard/setupVars.conf` as explained in the Reddit comment below would be nice feature.

Maybe you could set the value for AllowedIPs in `/etc/pivpn/wireguard/setupVars.conf` to 0.0.0.0/0, ::0/0 and then it could be changed if needed by the user.

----
edit:
judging by [this comment](https://www.reddit.com/r/pivpn/comments/i2fpmz/how_do_i_set_client_configuration_defaults_for/g04i13t/) on Reddit I assume this isn't possible ATM.

**Comment by orazioedoardo** [comment]
Done: https://github.com/pivpn/pivpn/commit/3ed54bf71db9dcd989370821094ca0dfc9b48749

**Comment by 4s3ti** [comment]
Merged into master: https://github.com/pivpn/pivpn/commit/b5ec995f68fbae2eb30b50e1b6a4350f96316f2e
