### ISSUE TITLE
[Support] Can't Connect client (server poll timeout)

### ISSUE THREAD

**Issue by jaum20** [pivpn/pivpn#1178]
### Issue
After installing PiVPN I can't conect to the VPN. Im testing using my smarphone mobile network with android client. The log gives me the error: "server poll timeout trying next remote entry". Tried capture packages, but received nothing. I'm using no-ip ddns and the openvpn port is open on my home router. 

### Have you searched for similar issues and solutions?
    (yes/no / which issues?)
yes, #[807](https://github.com/pivpn/pivpn/issues/807)

### cat /etc/iptables/rules.v4
# Generated by iptables-save v1.8.4 on Fri Nov 13 17:53:50 2020
*filter
:INPUT ACCEPT [1492:954565]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [1122:185540]
COMMIT
# Completed on Fri Nov 13 17:53:50 2020
# Generated by iptables-save v1.8.4 on Fri Nov 13 17:53:50 2020
*nat
:PREROUTING ACCEPT [43:4376]
:INPUT ACCEPT [4:450]
:OUTPUT ACCEPT [141:10529]
:POSTROUTING ACCEPT [0:0]
-A POSTROUTING -s 10.8.0.0/24 -o wlan0 -m comment --comment openvpn-nat-rule -j MASQUERADE
-A POSTROUTING -j MASQUERADE
-A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE
COMMIT
# Completed on Fri Nov 13 17:53:50 2020

###  $ sudi iptables -S
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT

### $ sudo iptables -t nat -S
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT
-A POSTROUTING -s 10.8.0.0/24 -o wlan0 -m comment --comment openvpn-nat-rule -j MASQUERADE
-A POSTROUTING -j MASQUERADE
-A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE

### $ ip -o link | grep "state UP" | awk '{print $2}' | cut -d':' -f1 | cut -d'@' -f1
wlan0

### Console output of      `pivpn debug`
```
::: Generating Debug Output
[sudo] password for joaopsvieira: 
::::		PiVPN debug		 ::::
=============================================
::::		Latest commit		 ::::
commit 443ef51e293a1aaca57cf1f8505a5328ac148fda
Author: Orazio <orazioedoardo@users.noreply.github.com>
Date:   Wed Nov 4 11:45:36 2020 +0100

    Update LatestUpdate.md
=============================================
::::	    Installation settings    	 ::::
PLAT=Ubuntu
OSCN=focal
USING_UFW=0
IPv4dev=wlan0
install_user=joaopsvieira
install_home=/home/joaopsvieira
VPN=openvpn
pivpnPROTO=udp
pivpnPORT=1194
pivpnDNS1=8.8.8.8
pivpnDNS2=8.8.4.4
pivpnSEARCHDOMAIN=
pivpnHOST=REDACTED
TWO_POINT_FOUR=1
pivpnENCRYPT=256
USE_PREDEFINED_DH_PARAM=
INPUT_CHAIN_EDITED=0
FORWARD_CHAIN_EDITED=0
pivpnDEV=tun0
pivpnNET=10.8.0.0
subnetClass=24
UNATTUPG=0
INSTALLED_PACKAGES=()
HELP_SHOWN=1
=============================================
::::  Server configuration shown below   ::::
dev tun
proto udp
port 1194
ca /etc/openvpn/easy-rsa/pki/ca.crt
cert /etc/openvpn/easy-rsa/pki/issued/rk322x-box_9dd26aaa-7628-47b2-836b-29f778201eb8.crt
key /etc/openvpn/easy-rsa/pki/private/rk322x-box_9dd26aaa-7628-47b2-836b-29f778201eb8.key
dh none
ecdh-curve prime256v1
topology subnet
server 10.8.0.0 255.255.255.0
# Set your primary domain name server address for clients
push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 8.8.4.4"
# Prevent DNS leaks on Windows
push "block-outside-dns"
# Override the Client default gateway by using 0.0.0.0/1 and
# 128.0.0.0/1 rather than 0.0.0.0/0. This has the benefit of
# overriding but not wiping out the original default gateway.
push "redirect-gateway def1"
client-to-client
client-config-dir /etc/openvpn/ccd
keepalive 15 120
remote-cert-tls client
tls-version-min 1.2
tls-crypt /etc/openvpn/easy-rsa/pki/ta.key
cipher AES-256-CBC
auth SHA256
user openvpn
group openvpn
persist-key
persist-tun
crl-verify /etc/openvpn/crl.pem
status /var/log/openvpn-status.log 20
status-version 3
syslog
verb 3
#DuplicateCNs allow access control on a less-granular, per user basis.
#Remove # if you will manage access by user instead of device. 
#duplicate-cn
# Generated for use by PiVPN.io
=============================================
::::  Client template file shown below   ::::
client
dev tun
proto udp
remote REDACTED 1194
resolv-retry infinite
nobind
remote-cert-tls server
tls-version-min 1.2
verify-x509-name rk322x-box_9dd26aaa-7628-47b2-836b-29f778201eb8 name
cipher AES-256-CBC
auth SHA256
auth-nocache
verb 3
=============================================
:::: 	Recursive list of files in	 ::::
::: /etc/openvpn/easy-rsa/pki shows below :::
/etc/openvpn/easy-rsa/pki/:
ca.crt
client4.ovpn
crl.pem
Default.txt
ecparams
index.txt
index.txt.attr
index.txt.attr.old
index.txt.old
issued
openssl-easyrsa.cnf
private
renewed
revoked
safessl-easyrsa.cnf
serial
serial.old
ta.key

/etc/openvpn/easy-rsa/pki/ecparams:
prime256v1.pem

/etc/openvpn/easy-rsa/pki/issued:
client4.crt
rk322x-box_9dd26aaa-7628-47b2-836b-29f778201eb8.crt

/etc/openvpn/easy-rsa/pki/private:
ca.key
client4.key
rk322x-box_9dd26aaa-7628-47b2-836b-29f778201eb8.key

/etc/openvpn/easy-rsa/pki/renewed:
private_by_serial
reqs_by_serial

/etc/openvpn/easy-rsa/pki/renewed/private_by_serial:

/etc/openvpn/easy-rsa/pki/renewed/reqs_by_serial:

/etc/openvpn/easy-rsa/pki/revoked:
private_by_serial
reqs_by_serial

/etc/openvpn/easy-rsa/pki/revoked/private_by_serial:

/etc/openvpn/easy-rsa/pki/revoked/reqs_by_serial:
=============================================
::::		Self check		 ::::
:: [OK] IP forwarding is enabled
:: [OK] Iptables MASQUERADE rule set
:: [OK] OpenVPN is running
:: [OK] OpenVPN is enabled (it will automatically start on reboot)
:: [OK] OpenVPN is listening on port 1194/udp
=============================================
:::: Having trouble connecting? Take a look at the FAQ:
:::: https://github.com/pivpn/pivpn/wiki/FAQ
=============================================
::::      Snippet of the server log      ::::
Nov 13 17:54:18 localhost ovpn-server[732]: OpenVPN 2.4.7 arm-unknown-linux-gnueabihf [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Sep  5 2019
Nov 13 17:54:18 localhost ovpn-server[732]: library versions: OpenSSL 1.1.1f  31 Mar 2020, LZO 2.10
Nov 13 17:54:18 localhost ovpn-server[732]: ECDH curve prime256v1 added
Nov 13 17:54:18 localhost ovpn-server[732]: Outgoing Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Nov 13 17:54:18 localhost ovpn-server[732]: Outgoing Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Nov 13 17:54:18 localhost ovpn-server[732]: Incoming Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Nov 13 17:54:18 localhost ovpn-server[732]: Incoming Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Nov 13 17:54:18 localhost ovpn-server[732]: TUN/TAP device tun0 opened
Nov 13 17:54:18 localhost ovpn-server[732]: TUN/TAP TX queue length set to 100
Nov 13 17:54:18 localhost ovpn-server[732]: /sbin/ip link set dev tun0 up mtu 1500
Nov 13 17:54:18 localhost ovpn-server[732]: /sbin/ip addr add dev tun0 10.8.0.1/24 broadcast 10.8.0.255
Nov 13 17:54:18 localhost ovpn-server[732]: Could not determine IPv4/IPv6 protocol. Using AF_INET
Nov 13 17:54:18 localhost ovpn-server[732]: Socket Buffers: R=[163840->163840] S=[163840->163840]
Nov 13 17:54:18 localhost ovpn-server[732]: UDPv4 link local (bound): [AF_INET][undef]:1194
Nov 13 17:54:18 localhost ovpn-server[732]: UDPv4 link remote: [AF_UNSPEC]
Nov 13 17:54:18 localhost ovpn-server[732]: GID set to openvpn
Nov 13 17:54:18 localhost ovpn-server[732]: UID set to openvpn
Nov 13 17:54:18 localhost ovpn-server[732]: MULTI: multi_init called, r=256 v=256
Nov 13 17:54:18 localhost ovpn-server[732]: IFCONFIG POOL: base=10.8.0.2 size=252, ipv6=0
Nov 13 17:54:18 localhost ovpn-server[732]: Initialization Sequence Completed
=============================================
::::		Debug complete		 ::::
::: 
::: Debug output completed above.
::: Copy saved to /tmp/debug.log
::: 

```
### Have you taken any steps towards solving your issue?
```
I followed the faq steps https://github.com/pivpn/pivpn/wiki/FAQ.
```

**Comment by orazioedoardo** [comment]
If you see no tcpdump output it means packets are not reaching the Raspberry Pi, regardless of what software you are running on it or firewall rules. What's the exact tcpdump command you tried? Do you use a landline connection or cellular?

**Comment by jaum20** [comment]
I used the commnad:

`tcpdump -n -i wlan0 udp port 1194`

The server is on a landline connection. I used the android client to test (cellular connection).

**Comment by orazioedoardo** [comment]
Command is correct (capture packets that match wlan0 interface and udp port 1194).

Do you also have ethernet connected or just wifi? Any chance you mistakenly forwarded the port to the ethernet ip?

**Comment by jaum20** [comment]
`wlan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.0.105  netmask 255.255.255.0  broadcast 192.168.0.255`

my router [config](https://images2.imgbox.com/72/aa/qZA9ErJj_o.png)

I think it is correct

**Comment by orazioedoardo** [comment]
Is this router directly connected to the internet? Are there other routers/modems in between?

**Comment by jaum20** [comment]
directly connected

**Comment by orazioedoardo** [comment]
Sorry I think I’m running out of ideas. Have you ever tried port forwarding in the past? Do you know if your ISP uses carrier grade nat? You can somehow check this by looking at the router admin interface, specifically “WAN IP”. If you are under cgnat it should fall inside these ranges: https://en.wikipedia.org/wiki/Private_network#Private_IPv4_addresses

**Comment by jaum20** [comment]
Looks like my ISP uses NAT. I checker my WAN IP on router status and it is different from my public IP when I check it on myip.com. So, there is no way to port forwarding in my case?

**Comment by orazioedoardo** [comment]
No because when your ISP uses NAT, there is another router upstream with does the NAT, which you do not control. You should to ask your ISP for a public IP.

**Comment by jaum20** [comment]
Okay, I contacted my ISP and surprisingly they opened the 1194 port for me in their NAT with no additional costs. Now, when I send a `echo "abcd" | netcat -u -v -w2 myddns 1194` using termux in my android via 4g I have outputs on tcpdump (`10:XX:XX.XXXXXX IP 189.XX.XX.XXX.XXXX > 192.168.0.107.1194: UDP, length 5`), but still can connect using the openvpn android client. Not even tcdump shows any received package.

**Comment by jaum20** [comment]
I created another client and now it is working! Thank you for your valuable help
