### ISSUE TITLE
[Support] Can't get connection

### ISSUE THREAD

**Issue by ellzzett** [pivpn/pivpn#1181]
Hi everybody,

need some support. First of all I'm an absolute noob concerning PiVPN. I installed it 2 month ago and setup openvpn for my mobile. It was working fine. Yesterday we had a blackout and PiVPN isn't working anymore. I tried to start the service and raspberry pi again, tried to create a ne certificate for my mobile. But nothing worked. Can you help me out? I used "pivpn ovpn -d command" to get some debug info:

=============================================
::::		Self check		 ::::
:: [OK] IP forwarding is enabled
:: [OK] Iptables MASQUERADE rule set
:: [OK] OpenVPN is running
:: [OK] OpenVPN is enabled (it will automatically start on reboot)
:: [OK] OpenVPN is listening on port XXXX/udp
=============================================
:::: Having trouble connecting? Take a look at the FAQ:
:::: https://github.com/pivpn/pivpn/wiki/FAQ
=============================================
::::      Snippet of the server log      ::::
Nov 15 19:52:31 raspberrypi ovpn-server[986]: Exiting due to fatal error
Nov 15 19:52:31 raspberrypi ovpn-server[986]: Closing TUN/TAP interface
Nov 15 19:52:31 raspberrypi ovpn-server[986]: /sbin/ip addr del dev tun0 10.8.0.1/24
Nov 15 19:52:37 raspberrypi ovpn-server[1006]: OpenVPN 2.4.7 arm-unknown-linux-gnueabihf [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 20 2019
Nov 15 19:52:37 raspberrypi ovpn-server[1006]: library versions: OpenSSL 1.1.1d  10 Sep 2019, LZO 2.10
Nov 15 19:52:37 raspberrypi ovpn-server[1006]: ECDH curve prime256v1 added
Nov 15 19:52:37 raspberrypi ovpn-server[1006]: Outgoing Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Nov 15 19:52:37 raspberrypi ovpn-server[1006]: Outgoing Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Nov 15 19:52:37 raspberrypi ovpn-server[1006]: Incoming Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Nov 15 19:52:37 raspberrypi ovpn-server[1006]: Incoming Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Nov 15 19:52:37 raspberrypi ovpn-server[1006]: TUN/TAP device tun0 opened
Nov 15 19:52:37 raspberrypi ovpn-server[1006]: TUN/TAP TX queue length set to 100
Nov 15 19:52:37 raspberrypi ovpn-server[1006]: /sbin/ip link set dev tun0 up mtu 1500
Nov 15 19:52:37 raspberrypi ovpn-server[1006]: /sbin/ip addr add dev tun0 10.8.0.1/24 broadcast 10.8.0.255
Nov 15 19:52:37 raspberrypi ovpn-server[1006]: Could not determine IPv4/IPv6 protocol. Using AF_INET
Nov 15 19:52:37 raspberrypi ovpn-server[1006]: Socket Buffers: R=[180224->180224] S=[180224->180224]
Nov 15 19:52:37 raspberrypi ovpn-server[1006]: TCP/UDP: Socket bind failed on local address [AF_INET][undef]:4364: Address already in use (errno=98)
Nov 15 19:52:37 raspberrypi ovpn-server[1006]: Exiting due to fatal error
Nov 15 19:52:37 raspberrypi ovpn-server[1006]: Closing TUN/TAP interface
Nov 15 19:52:37 raspberrypi ovpn-server[1006]: /sbin/ip addr del dev tun0 10.8.0.1/24
=============================================
::::		Debug complete		 ::::

**Comment by orazioedoardo** [comment]
Incomplete issue template, closing...

Please fill the form you are presented with when you reopen the issue.
