### ISSUE TITLE
[Support] Wireguard connection suddenly don't work anymore[partly fixed, remaining error in debug]

### ISSUE THREAD

**Issue by ovz93br43v7** [pivpn/pivpn#1184]
- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [unsure how my issue came up so I don't know] The issue I am reporting can be *replicated*.
- [unsure] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

### Issue
I used PiVPN with wireguard for several month without any issue. Today suddenly the VPN connection didn't worked anymore. I logged on the raspberrypi and tried to find out what the problem is.
`pivpn -c --> Unable to access interface: Protocol not supported`
`pivpn -d --> ::: Missing setup vars file!`

I checked the folder /etc/pivpn/SetupVars.conf file exists. 
I checked the content of the SetupVars.conf file it is the same like in my backup of the raspberry pi sd card.
I checked the content of /etc/wireguard/wg0.conf, seems also to be the same as before in my backup.

I found this reddit post : [reddit](https://www.reddit.com/r/pivpn/comments/ji0ulo/pivpn_with_wireguard_stopped_working/) and there was a guide linked --> [guide](https://www.rpiathome.com/2020/05/13/the-unofficial-non-definitive-wireguard-troubleshooting-page/)
I followed this guide:
`apt update`
`apt upgrade`
`apt install raspberrypi-kernel-headers` --> output `raspberrypi-kernel-headers is already installed (1.20201022-1)`
`reboot now`
`apt reinstall wireguard-dkms`

Then `pivpn -c` showed again my client list. 
But I still get `pivpn -d --> ::: Missing setup vars file!`. I checked the folder `/etc/pivpn/SetupVars.conf` file exists. According to [FAQ](https://github.com/pivpn/pivpn/wiki/WireGuard) there should be a sub-folder `wireguard` --> `/etc/pivpn/wireguard/setupVars.conf`
I now manually copied the `setupVars.conf` file to `/etc/pivpn/wireguard/setupVars.conf`and run again `pivpn -d`:

And got the again complete debug output. But at the top I got the following error:
```
::::		Latest commit		 ::::
fatal: Kein Git-Repository: '/usr/local/src/pivpn/.git'
```

### Have you searched for similar issues and solutions?
    (yes/no / which issues?)
Yes, see explanation above.

### Console output of      `curl -L install.pivpn.dev | bash`
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    17  100    17    0     0     57      0 --:--:-- --:--:-- --:--:--    57
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (35) error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error
```

### Console output of      `pivpn debug`
```
::::		PiVPN debug		 ::::
=============================================
::::		Latest commit		 ::::
fatal: Kein Git-Repository: '/usr/local/src/pivpn/.git'
=============================================
::::	    Installation settings    	 ::::
PLAT=Raspbian
OSCN=buster
USING_UFW=0
IPv4dev=eth0
dhcpReserv=1
IPv4addr=xxx
IPv4gw=xxx
install_user=xxx
install_home=/home/xxx
VPN=wireguard
pivpnPORT=xxx
pivpnDNS1=xxx
pivpnDNS2=
pivpnHOST=REDACTED
INPUT_CHAIN_EDITED=0
FORWARD_CHAIN_EDITED=0
pivpnPROTO=udp
pivpnDEV=wg0
pivpnNET=xxx
subnetClass=xxx
UNATTUPG=1
INSTALLED_PACKAGES=(raspberrypi-kernel-headers wireguard wireguard-tools wireguard-dkms qrencode)
=============================================
::::  Server configuration shown below   ::::
[Interface]
PrivateKey = server_priv
Address = xxxx
ListenPort = xxx
# begin xxx
[Peer]
PublicKey = xxx_pub
PresharedKey = psk
AllowedIPs = xxx
# end xxx
# begin xxx
[Peer]
PublicKey = xxx_pub
PresharedKey = psk
AllowedIPs = xxx
# end xxx
# begin xxx_work
[Peer]
PublicKey = xxx_pub
PresharedKey = psk
AllowedIPs = xxx
# end xxx
# begin xxx
[Peer]
PublicKey = xxx_pub
PresharedKey = psk
AllowedIPs = xxx
# end xxx
=============================================
::::  Client configuration shown below   ::::
[Interface]
PrivateKey = xxx
Address = xxx
DNS = xxx

[Peer]
PublicKey = server_pub
PresharedKey = psk
Endpoint = REDACTED:xxx
AllowedIPs = 0.0.0.0/0, ::0/0
=============================================
:::: 	Recursive list of files in	 ::::
::::	[4m/etc/wireguard shown below	 ::::
/etc/wireguard:
configs  keys  wg0.conf

/etc/wireguard/configs:
clients.txt  xxx.conf	xxx.conf	xxx.conf  xxx.conf

/etc/wireguard/keys:
xxx_priv  xxx_priv  m_smartphone_priv  xxx_priv  psk	   server_pub
xxx_pub   xxx_pub   xxx_pub   xxx_pub   server_priv
=============================================
::::		Self check		 ::::
:: [OK] IP forwarding is enabled
:: [OK] Iptables MASQUERADE rule set
:: [OK] WireGuard is running
:: [OK] WireGuard is enabled (it will automatically start on reboot)
:: [OK] WireGuard is listening on port xxx/udp
=============================================
:::: Having trouble connecting? Take a look at the FAQ:
:::: https://github.com/pivpn/pivpn/wiki/FAQ
=============================================
:::: WARNING: This script should have automatically masked sensitive       ::::
:::: information, however, still make sure that PrivateKey, PublicKey      ::::
:::: and PresharedKey are masked before reporting an issue. An example key ::::
:::: that you should NOT see in this log looks like this:                  ::::
:::: YIAoJVsdIeyvXfGGDDadHh6AxsMRymZTnnzZoAb9cxRe                          ::::
=============================================
::::		Debug complete		 ::::
```
### Have you taken any steps towards solving your issue?
```
Some steps from reddit, see explanation at the top.
```

**Comment by orazioedoardo** [comment]
> pivpn -d --> ::: Missing setup vars file!

Did you run `pivpn -up`? That error is caused by breaking changes in the new version, you can attempt to fix using steps outlined here: https://github.com/pivpn/pivpn/issues/1069 but reinstalling is recommended.

> pivpn -c --> Unable to access interface: Protocol not supported

This is a different error and your steps to solve were correct.

**Comment by ovz93br43v7** [comment]
Thank you for your answer!

> Did you run `pivpn -up`? 

Yes I tried this but my version of pivpn reject this with the following message:
`::: The updating functionality for PiVPN scripts is temporarily disabled`
`::: To keep the VPN (and the system) up to date, use 'apt update' and 'apt upgrade'`

**Comment by orazioedoardo** [comment]
Well the workaround now is in my comment above.

**Comment by ovz93br43v7** [comment]
Yes, thanks for that! The workaround worked for me. Just wanted to answer your question regarding `pivpn -up`

**Comment by ovz93br43v7** [comment]
@orazioedoardo Sorry to ask you again but I have again a problem with my wireguard. Today the service don't start anymore. Reboot don't help. 
`pivpn -d` show error:
```
:: [ERR] WireGuard is not running, try to start now? [Y/n] Y
Job for wg-quick@wg0.service failed because the control process exited with error code.
See "systemctl status wg-quick@wg0.service" and "journalctl -xe" for details.
Done
:: [OK] WireGuard is enabled (it will automatically start on reboot)
:: [ERR] WireGuard is not listening, try to restart now? [Y/n] Y
Job for wg-quick@wg0.service failed because the control process exited with error code.
See "systemctl status wg-quick@wg0.service" and "journalctl -xe" for details.
Done
```
`systemctl status wg-quick@wg0.service` shows
```
● wg-quick@wg0.service - WireGuard via wg-quick(8) for wg0
   Loaded: loaded (/lib/systemd/system/wg-quick@.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2020-12-10 07:24:02 CET; 17min ago
     Docs: man:wg-quick(8)
           man:wg(8)
           https://www.wireguard.com/
           https://www.wireguard.com/quickstart/
           https://git.zx2c4.com/wireguard-tools/about/src/man/wg-quick.8
           https://git.zx2c4.com/wireguard-tools/about/src/man/wg.8
  Process: 2848 ExecStart=/usr/bin/wg-quick up wg0 (code=exited, status=1/FAILURE)
 Main PID: 2848 (code=exited, status=1/FAILURE)

Dez 10 07:24:02 raspberrypi systemd[1]: Starting WireGuard via wg-quick(8) for wg0...
Dez 10 07:24:02 raspberrypi wg-quick[2848]: [#] ip link add wg0 type wireguard
Dez 10 07:24:02 raspberrypi wg-quick[2848]: Error: Unknown device type.
Dez 10 07:24:02 raspberrypi wg-quick[2848]: Unable to access interface: Protocol not supported
Dez 10 07:24:02 raspberrypi wg-quick[2848]: [#] ip link delete dev wg0
Dez 10 07:24:02 raspberrypi wg-quick[2848]: Cannot find device "wg0"
```

I reinstalled wireguard-dkms package then everything runs fine. But I'm confused why this could happen again.
My only ideas are:
- unattended update (standard configuration) changed something ....but I assumed this is important for server security
- that something is wrong with my apt packet sources? I see there buster and bullseye. But bullseye is a future debian release and I don't know whether it  have to be there or why it is there :-/

Probably you have an idea?

**Comment by orazioedoardo** [comment]
Try `sudo dpkg-reconfigure wireguard-dkms` and then `sudo systemctl restart wg-quick@wg0`.

**Comment by ovz93br43v7** [comment]
You missed the last part, I already reinstalled `wireguard-dkms`
And now everything is working again.
I want to narrow down why this happening and if possible to fix it.

But my only idea is that something here is wrong:
My only ideas are:

    unattended update (standard configuration) changed something ....but I assumed this is important for server security
    that something is wrong with my apt packet sources? I see there buster and bullseye. But bullseye is a future debian release and I don't know whether it have to be there or why it is there :-/

Probably you have an idea?

**Comment by orazioedoardo** [comment]
> You missed the last part, I already reinstalled wireguard-dkms
> And now everything is working again.

Oh I thought you reinstalled the package but it didn't recompile the module for some reason.

> But my only idea is that something here is wrong:

Unattended upgrade upgraded wireguard-dkms o the kernel, it failed to recompile the module and on next reboot or module restart it stopped working. It happens from time to time, I don't really know who to blame but a simple recompilation fixes the problem.

**Comment by ovz93br43v7** [comment]
Okay thanks for answer. Ok that means that happens also from time to time on your pi?
I thought probably I have apt package source from testing branch activated...because I see during `apt update` everything that my pi pulls also from bullseye repo...

Do you know how I could compare whether I have wrong or testing sources activated?!?

**Comment by orazioedoardo** [comment]
> Okay thanks for answer. Ok that means that happens also from time to time on your pi?

Yes. I'm thinking to add dpkg-reconfigure to the pivpn self check to easen the fix.

> I thought probably I have apt package source from testing branch activated...because I see during `apt update` everything that my pi pulls also from bullseye repo...

The PiVPN installed adds the bullseye repo because wireguard is not in the default buster or stretch repo.

**Comment by ovz93br43v7** [comment]
Would it make sense to add `sudo dpkg-reconfigure wireguard-dkms` and then `sudo systemctl restart wg-quick@wg0` to a cron job and run it after `unattended update&upgrade` to prevent trouble when in holiday without access to SSH to rpi....

**Comment by orazioedoardo** [comment]
You can setup an apt `DPkg::Post-Invoke` script that recompiles the module if necessary. Another suggestion, if you need "high availability": install openvpn (using pivpn) alongside wireguard as a backup. Just run the curl command again, choose reconfigure and then openvpn.

**Comment by ovz93br43v7** [comment]
Thank you for your fast answers!
Just to be sure I understand (source:  [https://wiki.debian.org/AptConfiguration](https://wiki.debian.org/AptConfiguration))
Add to 
`/etc/apt/apt.conf.d/`
a configuration file with any name with following content:
`Dpkg::Post-Invoke {"dpkg-reconfigure wireguard-dkms";"systemctl restart wg-quick@wg0";};`
could work.

Could it be possible that you build this into PiVPN in the future?

**Comment by orazioedoardo** [comment]
> could work.

That would recompile the module no matter what (and add delay) on every package installation, uninstallation and upgrade. That's why you should somehow check whether the module has been recompiled successfully by dkms.

> Could it be possible that you build this into PiVPN in the future?

Possibly, however this could naturally be "fixed" with the next release of Debian, which should have the module built-in.

**Comment by ovz93br43v7** [comment]
You are right!
I tried to find a script but found nothing matching to this issue.
So I tried with trail and error to extract the status with help of some script pieces I found online.
Here my first try:
```
status="$(systemctl status wg-quick@wg0.service --no-page)"
status_text=$(echo "${status}" | grep -o 'active')
if [ "${status_text}" == "active" ]
then
    echo "Wireguard active, do nothing"
else
    echo "Wireguard not active, starting dpkg-reconfigure"
    dpkg-reconfigure wireguard-dkms
    systemctl restart wg-quick@wg0
fi
```

make the script executable with: `sudo chmod +x /path/to/script.sh`

Add to
`/etc/apt/apt.conf.d/`
a configuration file with any name with following content:
Dpkg::Post-Invoke {"\pathto\above\script.sh";};

**Comment by orazioedoardo** [comment]
Shorter:

```
if systemctl -q is-active wg-quick@wg0; then
    echo "Wireguard active, do nothing"
else
    echo "Wireguard not active, starting dpkg-reconfigure"
    dpkg-reconfigure wireguard-dkms
    systemctl restart wg-quick@wg0
fi
```

However, if recompilation failed, you won't notice until the module is reloaded (it won't be reloaded on package upgrade, so...):
```
if systemctl -q restart wg-quick@wg0; then
    echo "Wireguard started, do nothing"
else
    echo "Wireguard not restarted, starting dpkg-reconfigure"
    dpkg-reconfigure wireguard-dkms
    systemctl restart wg-quick@wg0
fi
```
By the way, forward slashes `Dpkg::Post-Invoke {"7pathto/above/script.sh";};`

**Comment by ovz93br43v7** [comment]
I try to understand what the difference is between the scripts. 
The first script checks the status "active" in the process list which I can see myself in the terminal after entering the command `systemctl -q`. 

But the second script looks for "restart" which I can't see in the process list of `systemctl -q`. I assumed that a active process is also restarted? And when wireguard-dkms recompilation fails then it won't get the status active or not?

**Comment by orazioedoardo** [comment]
> And when wireguard-dkms recompilation fails then it won't get the status active or not?

When the recompilation fails you won't notice until you restart the interface or reboot the system.

**Comment by ovz93br43v7** [comment]
Just in case that anybody else is using this. Due to the fact that I would not see the `echo` outputs because I'm not looking all the time on terminal on my pi. I have installed additionally `s-nail` to send me emails for various things.

See line 5:
```
if systemctl -q restart wg-quick@wg0; then
    echo "Wireguard started, do nothing"
else
    echo "Wireguard not restarted, starting dpkg-reconfigure"
    s-nail -A MAILBOX -s "email subject: for example Wireguard not restarted --> dpkg-reconfigure executed" name@domain.net
    dpkg-reconfigure wireguard-dkms
    systemctl restart wg-quick@wg0
fi
```
