### ISSUE TITLE
PIVPN Reconfiguration

### ISSUE THREAD

**Issue by LeeMcCreery** [pivpn/pivpn#1187]
Hello,  I have run PIVPN for about a year.  My ISP changed my external IP.  How do I reconfigure my PIVPN to accept connections again?  Do I just need to generate a new key for my client to connect?  Or do I just rerun the setup process?

Thanks

**Comment by danpilch** [comment]
Openvpn or wireguard?

**Comment by LeeMcCreery** [comment]
OpenVPN

**Comment by teymur1988** [comment]
Hi,

I have the same question but WireGuard related. Where are the firewall rules script is stored? How do I reconfigure PIVPN?

Thanks

**Comment by shelleycat485** [comment]
I don't think you have to do anything with the firewall rules, the VPN server needs to accept clients from anywhere at a port.
The client config file(s) needs editing [on the client], for wg the copies are in  /etc/wireguard/configs - there is the address of the server in there with the port.  But if you are editing a config file, why not just generate a new one and import it at the client?
Setupvars.conf has the server address, you could try editing that, That's where the address is picked up from when generating a new client file.  Its under /etc/pivpn/...
I use a dynamic ddns service to try and avoid such editing.

**Comment by orazioedoardo** [comment]
You need to update the configuration files to point clients to the new IP: [WireGuard](https://github.com/pivpn/pivpn/wiki/WireGuard#how-do-i-change-the-public-ipdns-name-of-the-pivpn-after-the-install) or [OpenVPN](https://github.com/pivpn/pivpn/wiki/OpenVPN#how-do-i-change-the-public-ipdns-name-of-the-pivpn-after-the-install).
