### ISSUE TITLE
[Support] Unable to install pivpn - "/tmp/setupVars.conf: Permission denied" when running install.sh script

### ISSUE THREAD

**Issue by tnguy151** [pivpn/pivpn#1188]
Hi,
For some unknown reasons, I couldn't complete installing pivpn using install.sh script. I've tried to uninstall and reinstall again but "pivpn uninstall" (or even simply "pivpn") wasn't registered as a valid command; uninstall.sh script didn't work either due to "Missing setup vars file!". Attached bellow is the debug log. Any help is appreciated. Thanks!

![image](https://user-images.githubusercontent.com/56045900/100413924-8a3c8c80-3046-11eb-9e85-718c413278e4.png)
![image](https://user-images.githubusercontent.com/56045900/100413972-a809f180-3046-11eb-8d4d-4ada19bfc033.png)

**Comment by orazioedoardo** [comment]
What system is this? Do you happen to have read-only /tmp? Post the output of:
- `mount`
- `cat /etc/os-release`

**Comment by tnguy151** [comment]
I'm running Ubuntu server 20.04.1 LTS on a Pi 4B. I don't think it was the issue with read-only /tmp because I definitely can write/create a file within it even without sudo.

Output of `mount`:
![image](https://user-images.githubusercontent.com/56045900/100520823-ff56b180-316d-11eb-8ebe-474f37c62e30.png)

Output of `cat /etc/os-release`:
![image](https://user-images.githubusercontent.com/56045900/100520836-13021800-316e-11eb-8a2d-abfac2975f06.png)

**Comment by orazioedoardo** [comment]
What about `ls -l /tmp/setupVars.conf`?

Please avoid posting pictures of text, just post the text itself.

**Comment by tnguy151** [comment]
Output of `ls -l /tmp/setupVars.conf`:
`ls: cannot access '/tmp/setupVars.conf': No such file or directory`

**Comment by orazioedoardo** [comment]
I thought that maybe there was a file /tmp/setupVars.conf owned by another user such that ubuntu couldn't write over it (which is what the script does), but that doesn't seem the case. Perhaps you have rebooted in the meanwhile, which cleared /tmp, can run the script again?

**Comment by tnguy151** [comment]
Ok, this is sorta funny because I've definitely tried rebooting and rerunning the script before and still got the same errors, but it's working this time. Anyhoo, thank you @orazioedoardo for your help and patience. Hope you enjoy the rest of your weekend!
