### ISSUE TITLE
How do I change the set port forwarding number?

### ISSUE THREAD

**Issue by bluezebra2** [pivpn/pivpn#119]
I have issues connecting to my VPN on both school and work networks, so I want to try changing the port forwarding numbers( from my current 1194 which I set on start up to a different number). How would I go about changing those numbers on the raspberry pi?

**Comment by auzzie32** [comment]
If you are port forwarding with a router, you can change the port in the router settings without changing the PiVPN configuration. Then take your .ovpn file, open it in a basic text editor and change 1194 to the new port number. (FYI, editing the ovpn file is great for changed IP addresses too)

**Comment by bluezebra2** [comment]
I tried this and it doesn't work, it just makes it so i cant connect at all. I tried at least 10 different router configurations with no success. Any other ideas?

**Comment by bluezebra2** [comment]
Or alternatively, ideas about getting around (what I believe are) proxys and or firewalls of schools and businesses.

**Comment by redfast00** [comment]
@bluezebra2:: Have you tried uninstalling, then reinstalling and choosing TCP, port 443? Most orgs won't block this since this is used for HTTPS.

**Comment by bluezebra2** [comment]
I was hoping to avoid this because I chose the highest encryption setting and it took a while to make the key, but I'll try this and see if it works. Should I just rerun the installer or uninstall and reinstall everything?

**Comment by bluezebra2** [comment]
@redfast00:: thank you that worked! I appreciate the help everyone!
