### ISSUE TITLE
[Support] Site-to-Site VPN with OpenVPN

### ISSUE THREAD

**Issue by ebnerjoh** [pivpn/pivpn#1199]
In raising this issue, I confirm the following:

- [X] I have read and understood the contributors guide.
- [X] The issue I am reporting can be replicated.
- [X] The issue I am reporting can be is directly related to the pivpn installer script.
- [X] The issue I am reporting isn't a duplicate (see FAQs, closed issues, and open issues).

**Question:**
I have two networks:
Network A: 192.168.1.0/24
Network B: 192.168.0.0/24

In both networks I have a PIVPN Raspberry. Client to Server connection is working on both. I can connect with the OpenVPN Client to both PIVPNs and the corresponding Subnet.

Now I want to setup a Site-2-Site VPN to enable access from all Clients in Network A to Network B.

I am searching now a couple of days but I didnt got it running nor didnt I find any proper How-TO.

Br,
Johannes

**Comment by 4s3ti** [comment]
Hi! thanks for opening an issue on our github page, please consider that when opening issues you should follow the template accordingly .. currently you are opening a support request using a bug report template. 

We provide templates so you can provide us the details we need to be able to help you out, checking all the boxes doesn't make it any better or any faster to get help, quite the opposite will only take out our attention from what is really important. 

Please take that in consideration next time, or whenever you ask for help in this or any other open source project. 

Regardless, the subject is not pivpn related, is rather a custom setup, also I seen you have posted on reddit https://www.reddit.com/r/pivpn/comments/kaaaw1/pivpn_site_to_site_vpn_config/ 

also please take into consideration that you are asking for help with a very specific type of setup that not everyone has experience (me included) with, so it might take a while until someone has the chance or notices it and helps you with it. 

thanks for your understanding and for using pivpn. 
kind regards. 

Closing this topic.
