### ISSUE TITLE
[Support]RPi can connect with OpenVPN but no traffic

### ISSUE THREAD

**Issue by basvaningen** [pivpn/pivpn#1209]
`{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

Did a clean of the minimal Raspbian Buster image.
Used the script to do all the install work.
Opened the default UDP port to the IP of the Raspberry
Transfered the .ovpn file to my iphone
I can connect to it with my phone but can't browse any site or access internal webpage of router or printer

### Have you searched for similar issues and solutions?
    (yes/no / which issues?) Yes

### Console output of      `curl -L install.pivpn.dev | bash`
 % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    17  100    17    0     0    459      0 --:--:-- --:--:-- --:--:--   472
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (35) error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error

### Console output of      `pivpn debug`
```
  ::: Generating Debug Output
::::		PiVPN debug		 ::::
=============================================
::::		Latest commit		 ::::
commit 13f0fe7cbdcdb31537b3fd0e2eb34652e886cc1b
Author: 4s3ti <4s3ti@protonmail.com>
Date:   Wed Dec 9 19:22:29 2020 +0100

    ProBot Stale
    
    Added probot integration to marke topics as inactives and automatically
    close them.
    read .github/stale.yml for more details.
=============================================
::::	    Installation settings    	 ::::
PLAT=Raspbian
OSCN=buster
USING_UFW=0
IPv4dev=eth0
IPv4addr=192.168.2.20/24
IPv4gw=192.168.2.254
install_user=pi
install_home=/home/pi
VPN=openvpn
pivpnPROTO=udp
pivpnPORT=1194
pivpnDNS1=8.8.8.8
pivpnDNS2=8.8.4.4
pivpnSEARCHDOMAIN=
pivpnHOST=REDACTED
TWO_POINT_FOUR=1
pivpnENCRYPT=256
USE_PREDEFINED_DH_PARAM=
INPUT_CHAIN_EDITED=0
FORWARD_CHAIN_EDITED=0
pivpnDEV=tun0
pivpnNET=10.8.0.0
subnetClass=24
UNATTUPG=1
INSTALLED_PACKAGES=()
HELP_SHOWN=1
=============================================
::::  Server configuration shown below   ::::
dev tun
proto udp
port 1194
ca /etc/openvpn/easy-rsa/pki/ca.crt
cert /etc/openvpn/easy-rsa/pki/issued/openvpn_9fa5225d-f490-48e7-b171-8e3bcb4639f1.crt
key /etc/openvpn/easy-rsa/pki/private/openvpn_9fa5225d-f490-48e7-b171-8e3bcb4639f1.key
dh none
ecdh-curve prime256v1
topology subnet
server 10.8.0.0 255.255.255.0
# Set your primary domain name server address for clients
push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 8.8.4.4"
# Prevent DNS leaks on Windows
push "block-outside-dns"
# Override the Client default gateway by using 0.0.0.0/1 and
# 128.0.0.0/1 rather than 0.0.0.0/0. This has the benefit of
# overriding but not wiping out the original default gateway.
push "redirect-gateway def1"
client-to-client
client-config-dir /etc/openvpn/ccd
keepalive 15 120
remote-cert-tls client
tls-version-min 1.2
tls-crypt /etc/openvpn/easy-rsa/pki/ta.key
cipher AES-256-CBC
auth SHA256
user openvpn
group openvpn
persist-key
persist-tun
crl-verify /etc/openvpn/crl.pem
status /var/log/openvpn-status.log 20
status-version 3
syslog
verb 3
#DuplicateCNs allow access control on a less-granular, per user basis.
#Remove # if you will manage access by user instead of device. 
#duplicate-cn
# Generated for use by PiVPN.io
=============================================
::::  Client template file shown below   ::::
client
dev tun
proto udp
remote REDACTED 1194
resolv-retry infinite
nobind
remote-cert-tls server
tls-version-min 1.2
verify-x509-name openvpn_9fa5225d-f490-48e7-b171-8e3bcb4639f1 name
cipher AES-256-CBC
auth SHA256
auth-nocache
verb 3
=============================================
:::: 	Recursive list of files in	 ::::
::: /etc/openvpn/easy-rsa/pki shows below :::
/etc/openvpn/easy-rsa/pki/:
basvaningen.ovpn
ca.crt
crl.pem
Default.txt
ecparams
index.txt
index.txt.attr
index.txt.attr.old
index.txt.old
issued
openssl-easyrsa.cnf
private
renewed
revoked
safessl-easyrsa.cnf
serial
serial.old
ta.key

/etc/openvpn/easy-rsa/pki/ecparams:
prime256v1.pem

/etc/openvpn/easy-rsa/pki/issued:
basvaningen.crt
openvpn_9fa5225d-f490-48e7-b171-8e3bcb4639f1.crt

/etc/openvpn/easy-rsa/pki/private:
basvaningen.key
ca.key
openvpn_9fa5225d-f490-48e7-b171-8e3bcb4639f1.key

/etc/openvpn/easy-rsa/pki/renewed:
private_by_serial
reqs_by_serial

/etc/openvpn/easy-rsa/pki/renewed/private_by_serial:

/etc/openvpn/easy-rsa/pki/renewed/reqs_by_serial:

/etc/openvpn/easy-rsa/pki/revoked:
private_by_serial
reqs_by_serial

/etc/openvpn/easy-rsa/pki/revoked/private_by_serial:

/etc/openvpn/easy-rsa/pki/revoked/reqs_by_serial:
=============================================
::::		Self check		 ::::
:: [OK] IP forwarding is enabled
:: [OK] Iptables MASQUERADE rule set
:: [OK] OpenVPN is running
:: [OK] OpenVPN is enabled (it will automatically start on reboot)
:: [OK] OpenVPN is listening on port 1194/udp
=============================================
:::: Having trouble connecting? Take a look at the FAQ:
:::: https://github.com/pivpn/pivpn/wiki/FAQ
=============================================
::::      Snippet of the server log      ::::
Dec 23 15:40:23 openvpn ovpn-server[556]: REDACTED:62992 peer info: IV_PROTO=2
Dec 23 15:40:23 openvpn ovpn-server[556]: REDACTED:62992 peer info: IV_AUTO_SESS=1
Dec 23 15:40:23 openvpn ovpn-server[556]: REDACTED:62992 peer info: IV_GUI_VER=net.openvpn.connect.ios_3.2.2-3507
Dec 23 15:40:23 openvpn ovpn-server[556]: REDACTED:62992 peer info: IV_SSO=openurl
Dec 23 15:40:23 openvpn ovpn-server[556]: REDACTED:62992 Control Channel: TLSv1.3, cipher TLSv1.3 TLS_AES_256_GCM_SHA384, 256 bit EC, curve: prime256v1
Dec 23 15:40:23 openvpn ovpn-server[556]: REDACTED:62992 [basvaningen] Peer Connection Initiated with [AF_INET]REDACTED:62992
Dec 23 15:40:23 openvpn ovpn-server[556]: basvaningen/REDACTED:62992 OPTIONS IMPORT: reading client specific options from: /etc/openvpn/ccd/basvaningen
Dec 23 15:40:23 openvpn ovpn-server[556]: basvaningen/REDACTED:62992 MULTI: Learn: 10.8.0.2 -> basvaningen/REDACTED:62992
Dec 23 15:40:23 openvpn ovpn-server[556]: basvaningen/REDACTED:62992 MULTI: primary virtual IP for basvaningen/REDACTED:62992: 10.8.0.2
Dec 23 15:40:23 openvpn ovpn-server[556]: basvaningen/REDACTED:62992 PUSH: Received control message: 'PUSH_REQUEST'
Dec 23 15:40:23 openvpn ovpn-server[556]: basvaningen/REDACTED:62992 SENT CONTROL [basvaningen]: 'PUSH_REPLY,dhcp-option DNS 8.8.8.8,dhcp-option DNS 8.8.4.4,block-outside-dns,redirect-gateway def1,route-gateway 10.8.0.1,topology subnet,ping 15,ping-restart 120,ifconfig 10.8.0.2 255.255.255.0,peer-id 6,cipher AES-256-GCM' (status=1)
Dec 23 15:40:23 openvpn ovpn-server[556]: basvaningen/REDACTED:62992 Data Channel: using negotiated cipher 'AES-256-GCM'
Dec 23 15:40:23 openvpn ovpn-server[556]: basvaningen/REDACTED:62992 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Dec 23 15:40:23 openvpn ovpn-server[556]: basvaningen/REDACTED:62992 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Dec 23 15:40:29 openvpn ovpn-server[556]: REDACTED:62980 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Dec 23 15:40:29 openvpn ovpn-server[556]: REDACTED:62980 TLS Error: TLS handshake failed
Dec 23 15:40:29 openvpn ovpn-server[556]: REDACTED:62980 SIGUSR1[soft,tls-error] received, client-instance restarting
Dec 23 15:40:34 openvpn ovpn-server[556]: REDACTED:62981 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Dec 23 15:40:34 openvpn ovpn-server[556]: REDACTED:62981 TLS Error: TLS handshake failed
Dec 23 15:40:34 openvpn ovpn-server[556]: REDACTED:62981 SIGUSR1[soft,tls-error] received, client-instance restarting
=============================================

```
### Have you taken any steps towards solving your issue?
```
  - Uninstalled PiVPN
  - Tried other DNS settings
  - Turned off/on the compression on the iPhone app
```

**Comment by shelleycat485** [comment]
I've seen similar, when I had a bad client config file (out of date/wrong pivpn install).  From the logs the connection was made to the server but the TLS negotiation failed.  Are you sure you have a current client config for that server that is installed?  Can you check with another device?

**Comment by TinCanTech** [comment]
Set the server config to use `verb 4` (Replace `verb 3`) and post your server log again.

**Comment by basvaningen** [comment]
@TinCanTech  Here is the new server log:

::: Generating Debug Output
::::		PiVPN debug		 ::::
=============================================
::::		Latest commit		 ::::
commit 13f0fe7cbdcdb31537b3fd0e2eb34652e886cc1b
Author: 4s3ti <4s3ti@protonmail.com>
Date:   Wed Dec 9 19:22:29 2020 +0100

    ProBot Stale
    
    Added probot integration to marke topics as inactives and automatically
    close them.
    read .github/stale.yml for more details.
=============================================
::::	    Installation settings    	 ::::
PLAT=Raspbian
OSCN=buster
USING_UFW=0
IPv4dev=eth0
IPv4addr=192.168.2.20/24
IPv4gw=192.168.2.254
install_user=pi
install_home=/home/pi
VPN=openvpn
pivpnPROTO=udp
pivpnPORT=1194
pivpnDNS1=8.8.8.8
pivpnDNS2=8.8.4.4
pivpnSEARCHDOMAIN=
pivpnHOST=REDACTED
TWO_POINT_FOUR=1
pivpnENCRYPT=256
USE_PREDEFINED_DH_PARAM=
INPUT_CHAIN_EDITED=0
FORWARD_CHAIN_EDITED=0
pivpnDEV=tun0
pivpnNET=10.8.0.0
subnetClass=24
UNATTUPG=1
INSTALLED_PACKAGES=()
HELP_SHOWN=1
=============================================
::::  Server configuration shown below   ::::
dev tun
proto udp
port 1194
ca /etc/openvpn/easy-rsa/pki/ca.crt
cert /etc/openvpn/easy-rsa/pki/issued/openvpn_9fa5225d-f490-48e7-b171-8e3bcb4639f1.crt
key /etc/openvpn/easy-rsa/pki/private/openvpn_9fa5225d-f490-48e7-b171-8e3bcb4639f1.key
dh none
ecdh-curve prime256v1
topology subnet
server 10.8.0.0 255.255.255.0
# Set your primary domain name server address for clients
push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 8.8.4.4"
# Prevent DNS leaks on Windows
push "block-outside-dns"
# Override the Client default gateway by using 0.0.0.0/1 and
# 128.0.0.0/1 rather than 0.0.0.0/0. This has the benefit of
# overriding but not wiping out the original default gateway.
push "redirect-gateway def1"
client-to-client
client-config-dir /etc/openvpn/ccd
keepalive 15 120
remote-cert-tls client
tls-version-min 1.2
tls-crypt /etc/openvpn/easy-rsa/pki/ta.key
cipher AES-256-CBC
auth SHA256
user openvpn
group openvpn
persist-key
persist-tun
crl-verify /etc/openvpn/crl.pem
status /var/log/openvpn-status.log 20
status-version 3
syslog
verb 4
#DuplicateCNs allow access control on a less-granular, per user basis.
#Remove # if you will manage access by user instead of device. 
#duplicate-cn
# Generated for use by PiVPN.io
=============================================
::::  Client template file shown below   ::::
client
dev tun
proto udp
remote REDACTED 1194
resolv-retry infinite
nobind
remote-cert-tls server
tls-version-min 1.2
verify-x509-name openvpn_9fa5225d-f490-48e7-b171-8e3bcb4639f1 name
cipher AES-256-CBC
auth SHA256
auth-nocache
verb 3
=============================================
:::: 	Recursive list of files in	 ::::
::: /etc/openvpn/easy-rsa/pki shows below :::
/etc/openvpn/easy-rsa/pki/:
basvaningen.ovpn
ca.crt
crl.pem
Default.txt
ecparams
index.txt
index.txt.attr
index.txt.attr.old
index.txt.old
issued
openssl-easyrsa.cnf
private
renewed
revoked
safessl-easyrsa.cnf
serial
serial.old
ta.key

/etc/openvpn/easy-rsa/pki/ecparams:
prime256v1.pem

/etc/openvpn/easy-rsa/pki/issued:
basvaningen.crt
openvpn_9fa5225d-f490-48e7-b171-8e3bcb4639f1.crt

/etc/openvpn/easy-rsa/pki/private:
basvaningen.key
ca.key
openvpn_9fa5225d-f490-48e7-b171-8e3bcb4639f1.key

/etc/openvpn/easy-rsa/pki/renewed:
private_by_serial
reqs_by_serial

/etc/openvpn/easy-rsa/pki/renewed/private_by_serial:

/etc/openvpn/easy-rsa/pki/renewed/reqs_by_serial:

/etc/openvpn/easy-rsa/pki/revoked:
private_by_serial
reqs_by_serial

/etc/openvpn/easy-rsa/pki/revoked/private_by_serial:

/etc/openvpn/easy-rsa/pki/revoked/reqs_by_serial:
=============================================
::::		Self check		 ::::
:: [OK] IP forwarding is enabled
:: [OK] Iptables MASQUERADE rule set
:: [OK] OpenVPN is running
:: [OK] OpenVPN is enabled (it will automatically start on reboot)
:: [OK] OpenVPN is listening on port 1194/udp
=============================================
:::: Having trouble connecting? Take a look at the FAQ:
:::: https://github.com/pivpn/pivpn/wiki/FAQ
=============================================
::::      Snippet of the server log      ::::
Dec 28 13:28:34 openvpn ovpn-server[555]: REDACTED:31015 peer info: IV_VER=3.git::2952f561
Dec 28 13:28:34 openvpn ovpn-server[555]: REDACTED:31015 peer info: IV_PLAT=ios
Dec 28 13:28:34 openvpn ovpn-server[555]: REDACTED:31015 peer info: IV_NCP=2
Dec 28 13:28:34 openvpn ovpn-server[555]: REDACTED:31015 peer info: IV_TCPNL=1
Dec 28 13:28:34 openvpn ovpn-server[555]: REDACTED:31015 peer info: IV_PROTO=2
Dec 28 13:28:34 openvpn ovpn-server[555]: REDACTED:31015 peer info: IV_AUTO_SESS=1
Dec 28 13:28:34 openvpn ovpn-server[555]: REDACTED:31015 peer info: IV_GUI_VER=net.openvpn.connect.ios_3.2.2-3507
Dec 28 13:28:34 openvpn ovpn-server[555]: REDACTED:31015 peer info: IV_SSO=openurl
Dec 28 13:28:34 openvpn ovpn-server[555]: REDACTED:31015 Control Channel: TLSv1.3, cipher TLSv1.3 TLS_AES_256_GCM_SHA384, 256 bit EC, curve: prime256v1
Dec 28 13:28:34 openvpn ovpn-server[555]: REDACTED:31015 [basvaningen] Peer Connection Initiated with [AF_INET]REDACTED:31015
Dec 28 13:28:34 openvpn ovpn-server[555]: basvaningen/REDACTED:31015 OPTIONS IMPORT: reading client specific options from: /etc/openvpn/ccd/basvaningen
Dec 28 13:28:34 openvpn ovpn-server[555]: basvaningen/REDACTED:31015 MULTI: Learn: 10.8.0.2 -> basvaningen/REDACTED:31015
Dec 28 13:28:34 openvpn ovpn-server[555]: basvaningen/REDACTED:31015 MULTI: primary virtual IP for basvaningen/REDACTED:31015: 10.8.0.2
Dec 28 13:28:34 openvpn ovpn-server[555]: basvaningen/REDACTED:31015 PUSH: Received control message: 'PUSH_REQUEST'
Dec 28 13:28:34 openvpn ovpn-server[555]: basvaningen/REDACTED:31015 SENT CONTROL [basvaningen]: 'PUSH_REPLY,dhcp-option DNS 8.8.8.8,dhcp-option DNS 8.8.4.4,block-outside-dns,redirect-gateway def1,route-gateway 10.8.0.1,topology subnet,ping 15,ping-restart 120,ifconfig 10.8.0.2 255.255.255.0,peer-id 0,cipher AES-256-GCM' (status=1)
Dec 28 13:28:34 openvpn ovpn-server[555]: basvaningen/REDACTED:31015 Data Channel: using negotiated cipher 'AES-256-GCM'
Dec 28 13:28:34 openvpn ovpn-server[555]: basvaningen/REDACTED:31015 Data Channel MTU parms [ L:1549 D:1450 EF:49 EB:406 ET:0 EL:3 ]
Dec 28 13:28:34 openvpn ovpn-server[555]: basvaningen/REDACTED:31015 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Dec 28 13:28:34 openvpn ovpn-server[555]: basvaningen/REDACTED:31015 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Dec 28 13:29:35 openvpn ovpn-server[555]: basvaningen/REDACTED:31015 PID_ERR replay-window backtrack occurred [14] [SSL-0] [00000000000000_0000000000000000000000000000000000000000000000000] 0:740 0:726 t=1609158575[0] r=[-3,64,15,14,1] sl=[28,64,64,272]
=============================================
::::		Debug complete		 ::::
::: 
::: Debug output completed above.
::: Copy saved to /tmp/debug.log
:::

**Comment by 4s3ti** [comment]
Edited your comment, please be more careful when pasting outputs, wrap it inside 3 back-ticks like this:  

&#96;&#96;&#96;
Codeblock // output  here 
&#96;&#96;&#96;

**Comment by TinCanTech** [comment]
@basvaningen your server log suggests that the client is having a problem.

Please set **verb 4** in your client config and try to connect then paste your log (correctly) here.

My initial thought is that this may be incorrect: client config
```
verify-x509-name openvpn_9fa5225d-f490-48e7-b171-8e3bcb4639f1 name
```

**Comment by orazioedoardo** [comment]
No replies in a while, closing...
