### ISSUE TITLE
[Support] unattended install on an EC2 instance fails with "no such file or directory"

### ISSUE THREAD

**Issue by mijndert** [pivpn/pivpn#1210]
## In raising this issue, I confirm the following: 

- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

### Issue

I have an install script in user-data which will do an unattended install of PiVPN on an EC2 instance running Ubuntu 20.04:

When I run this script from the command prompt everything's fine. When it runs from user-data it fails.

The script:

```
# Create options file
cat << EOF > /root/options.conf
USING_UFW=0
IPv4dev=ens5
install_user=ubuntu
install_home=/home/ubuntu
VPN=openvpn
pivpnPROTO=udp
pivpnPORT=1194
pivpnDNS1=8.8.8.8
pivpnDNS2=8.8.4.4
pivpnSEARCHDOMAIN=
TWO_POINT_FOUR=1
pivpnENCRYPT=521
USE_PREDEFINED_DH_PARAM=0
INPUT_CHAIN_EDITED=0
FORWARD_CHAIN_EDITED=0
pivpnDEV=tun0
pivpnNET=10.8.0.0
subnetClass=24
UNATTUPG=1
EOF
# Install PiVPN from options.conf
cd /root
curl -L https://install.pivpn.io > install.sh
chmod +x install.sh
./install.sh --unattended options.conf
```

Error:

```
Checking /usr/local/src/pivpn is a repo...:::    Cloning https://github.com/pivpn/pivpn.git into /usr/local/src/pivpn...    #010#010#010#010./install.sh: line 1035: cd: /usr/local/src/pivpn: No such file or directory
```

The directory is created however: 

```
/usr/local/src/pivpn# ls -la
total 152
drwxr-xr-x 8 root root  4096 Dec 24 14:20 .
drwxr-xr-x 3 root root  4096 Dec 24 14:20 ..
drwxr-xr-x 2 root root  4096 Dec 24 14:20 auto_install
-rw-r--r-- 1 root root  3253 Dec 24 14:20 CODE_OF_CONDUCT.md
-rw-r--r-- 1 root root  1281 Dec 24 14:20 CONTRIBUTING.md
drwxr-xr-x 2 root root  4096 Dec 24 14:20 examples
drwxr-xr-x 3 root root  4096 Dec 24 14:20 files
drwxr-xr-x 8 root root  4096 Dec 24 14:20 .git
drwxr-xr-x 3 root root  4096 Dec 24 14:20 .github
-rw-r--r-- 1 root root     7 Dec 24 14:20 .gitignore
-rw-r--r-- 1 root root 15410 Dec 24 14:20 LatestUpdate.md
-rw-r--r-- 1 root root  1075 Dec 24 14:20 LICENSE
-rw-r--r-- 1 root root 74614 Dec 24 14:20 logos.jpg
-rw-r--r-- 1 root root  9379 Dec 24 14:20 README.md
drwxr-xr-x 4 root root  4096 Dec 24 14:20 scripts
```

I'm out of ideas. I've been looking at the installer script but I can't seem to figure out a workaround for this. It does seem to be some kind of race condition in which the directory isn't yet available when the check is done.

### Have you searched for similar issues and solutions?
Searched, found a few, but not about EC2.

### Console output of      `curl -L install.pivpn.dev | bash`
```
Not relevant since only the unattended install fails.
```

### Console output of      `pivpn add` or `pivpn add nopass`
```
None, since the installer fails.
```

### Console output of      `pivpn debug`
```
None, since the installer fails.
```
### Have you taken any steps towards solving your issue?
```
I tried running it from a different directory and using a different shell, to no avail.
```

**Comment by 4s3ti** [comment]
User data runs quite early in the boot process, that might be why, will try to investigate a bit more about this

**Comment by mijndert** [comment]
I had a look at this, I now execute the commands 5 minutes after the EC2 instance had launched. The same error occurs however.

```
Cloning https://github.com/pivpn/pivpn.git into /usr/local/src/pivpn..../install.sh: line 1035: cd: /usr/local/src/pivpn: No such file or directory
```

It still looks like a race condition somewhere, I'll try some more things...

**Comment by 4s3ti** [comment]
Haven't dived into this one yet, but seems pivpn is also lacking some checks for directories ...

**Comment by 4s3ti** [comment]
Playing around a bit with this ... 

* *Hetzner*: Was able to run unattended  during user-data and verified running
  * OS: debian 11
 
* *AWS*: Was able to run unattended during user-data and verified running
  * OS: Debian 11
  * AMI-ID: ami-045c4a673232682a2
  * region: eu-north-1

**How I did it:** 

I mostly use terraform to spin up infrastructure, and rarely interact with aws console, and provided the following script as user data: 

```
$cat pivpnuserdatatest.sh 
#!/bin/bash

apt update && apt install -y git
git clone https://github.com/pivpn/pivpn /tmp/pivpn
cd /tmp/pivpn || exit
bash ciscripts/startup.sh -o
bash auto_install/install.sh --unattended ciscripts/ci_openvpn.conf
```

will add this to docs.

**Comment by 4s3ti** [comment]
Here's another variation of the OP script: 

```
#!/bin/bash
# Create options file
cat << EOF > /tmp/options.conf
USING_UFW=0
IPv4dev=ens5
install_user=admin
install_home=/home/admin
VPN=openvpn
pivpnPROTO=udp
pivpnPORT=1194
pivpnDNS1=8.8.8.8
pivpnDNS2=8.8.4.4
TWO_POINT_FOUR=1
pivpnENCRYPT=256
USE_PREDEFINED_DH_PARAM=1
INPUT_CHAIN_EDITED=0
FORWARD_CHAIN_EDITED=0
pivpnDEV=tun0
pivpnNET=10.8.0.0
subnetClass=24
UNATTUPG=1
EOF
# Install PiVPN from options.conf
apt update && apt install -y git
git clone https://github.com/pivpn/pivpn /tmp/pivpn
cd /tmp/ || exit
bash pivpn/auto_install/install.sh --unattended /tmp/options.conf
```

**Comment by 4s3ti** [comment]
committed to docs: https://github.com/pivpn/docs/commit/ed83004f04248132740393fdb0e36971c98302bd 

Available at: https://docs.pivpn.io/guides/user-data/

closing...
