### ISSUE TITLE
Fix confusing prompt when removing a wireguard config

### ISSUE THREAD

**Issue by mquirin** [pivpn/pivpn#1212]
When removing a Wireguard config there is a confirmation prompt:

https://github.com/pivpn/pivpn/blob/443ef51e293a1aaca57cf1f8505a5328ac148fda/scripts/wireguard/removeCONF.sh#L83

The prompt indicates that the default is yes ("[Y/n]") but when just pressing enter nothing happens.
This is double confusing as there is no stdout that nothing is done and the return code is 0, indicating success.

**Comment by 4s3ti** [comment]
Merged into master: https://github.com/pivpn/pivpn/commit/b5ec995f68fbae2eb30b50e1b6a4350f96316f2e
