### ISSUE TITLE
Issue trying to update piVPN per pivpn -up

### ISSUE THREAD

**Issue by r3htanz** [pivpn/pivpn#1215]
Trying to update the pivpn on my Raspberry Pi 4 by typing `pivpn -up` leads into the error message:

    ::: The updating functionality for PiVPN scripts is temporarily disabled
    ::: To keep the VPN (and the system) up to date, use 'apt update' and 'apt upgrade'

**Comment by 4s3ti** [comment]
all seem as intended, please read the error properly.

**Comment by JamesGaither** [comment]
What is reasoning behind having this disabled? The help function still lists it as well as the documentation on docs.pivpn.io . If this is going to continue to be disabled, might I suggest removing it from the help list. If this is an issue that needs to be resolved, please have a ticket open and I could try to help out with it if needed.

**Comment by 4s3ti** [comment]
I have no clue of the reason behind it as i have been in and out ... @orazioedoardo  .can you provide more details?

**Comment by orazioedoardo** [comment]
> What is reasoning behind having this disabled?

https://github.com/pivpn/pivpn/commit/f06f6d79203c29ebd785f860a81a15e9caac4fc9

> The help function still lists it as well as the documentation on docs.pivpn.io . If this is going to continue to be disabled, might I suggest removing it from the help list.

At the time there were issues with users trying updating, I left the command `pivpn -up` to inform users about the removal. Can probably be removed by now.
