### ISSUE TITLE
[BUG] Installation on Ubuntu 20.10 fails

### ISSUE THREAD

**Issue by zilexa** [pivpn/pivpn#1216]
## In raising this issue, I confirm the following: 
- [x] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

**Describe the bug**
Run the script on Ubuntu 20.10, it will fail and stop. Note on the exact same machine, **the script runs successfully on Ubuntu 20.04!**
The system is an Intel Core i3-9100. 

```
$ sudo curl -L https://install.pivpn.io | bash 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   162  100   162    0     0   2417      0 --:--:-- --:--:-- --:--:--  2417
100 83088  100 83088    0     0   587k      0 --:--:-- --:--:-- --:--:--  587k
:::
::: sudo will be used for the install.
::: Did not detect perfectly supported OS but,
::: Continuing installation at user's own risk...
::: Hostname length OK
::: Verifying free disk space...
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: Your system is up to date! Continuing with PiVPN installation...
:::    Checking for git... already installed!
:::    Checking for tar... already installed!
:::    Checking for wget... already installed!
:::    Checking for curl... already installed!
:::    Checking for grep... already installed!
:::    Checking for dnsutils... not installed!
:::    Checking for whiptail... already installed!
:::    Checking for net-tools... not installed!
:::    Checking for bsdmainutils... not installed!
:::    Checking for iptables-persistent... not installed!
:::    Failed to install dnsutils!
:::    Failed to install net-tools!
:::    Failed to install bsdmainutils!
:::    Failed to install iptables-persistent!
$
```

**To Reproduce**
1.  On a clean Ubuntu 20.10 system,
2. Run ` sudo curl -L https://install.pivpn.io | bash `
3. Continue when you get the warning about unsupported OS
4. See output above. Nothing happens after. 

**Expected behavior**
Installation asks more questions and finishes successfully.

**Desktop (please complete the following information):**
 - VPN Protocol : not selected yet
 - OS: Ubuntu Budgie
 - Version: 20.10

**Comment by Matr1x-101** [comment]
I know how to fix this; just manually install all the dependancies. It works with Ubuntu MATE 20.10

**Comment by shelleycat485** [comment]
Its down as issue #1204
The minimum required to fix is: sudo apt-get update, before the install , then it will find the iptables-persistent.

**Comment by 4s3ti** [comment]
duplicate: https://github.com/pivpn/pivpn/issues/1204

Closing
