### ISSUE TITLE
Installed PiVPN sucessfully, but ssh and vnc not working

### ISSUE THREAD

**Issue by Matr1x-101** [pivpn/pivpn#1217]
I installed PiVPN with WireGuard sucessfully, but then, my ssh and vnc suddenly stopped working. I've tried rebooting, restaring the services, re-allowing ssh and vnc to pass through `ufw`, reinstalling `openssh-server` and `tightvncserver`, but it is not working. I get the error `ssh: connect to host (my ip) port 22: connection refused`. I know this is a problem with PiVPN. Is there a fix?

**Comment by shelleycat485** [comment]
Can you give more information?
1. Can you ping your ssh machine with the PiVPN installed and connected?
2. Are you connecting using a DNS name, or a direct IP.  Can you ping with both of these?  If only one works you may have a DNS problem
3. Is your SSH config set up to only listen on one interface? If so, it may not be listening on the wg0 interface
4. Are you listening on IPV4? (netstat -ant) If you were using IPv6 before, PiVPN does not support that.  
5. Can you ssh to the machine from itself with PiVPN installed?

**Comment by Matr1x-101** [comment]
When I try to ping:
`Pinging [my raspberry pi ip] with 32 bytes of data:
General failure.
General failure.
General failure.
General failure.

Ping statistics for [my raspberry pi ip]:
    Packets: Sent = 4, Received = 0, Lost = 4 (100% loss),`

I am using a DDNS address. It is working perfectly fine

I am using IPv4.

I can ssh when I am not connected, however, when I am I can't ssh into anything on my network.

**Comment by shelleycat485** [comment]
So if you cannot ping with wireguard connected, you are getting no VPN connection.  Are the figures in the wireguard client ticking up - showing bytes being send and received? They take  a few seconds to start, but should show some handshaking taking place.

![image](https://user-images.githubusercontent.com/63857845/103474654-0771c480-4d9e-11eb-9b8d-6aea39babbc4.png)

**Comment by Matr1x-101** [comment]
Yup. Working!

![image](https://user-images.githubusercontent.com/70490301/103941963-8b71d680-5127-11eb-9d3d-618954efeb00.png)

**Comment by shelleycat485** [comment]
So is the data transfer just working, or is the rest working too?  
Next step is to check you can ping using the wg0 addresses, probably 10.6.0.1 and 10.6.0.2 from the client.  This would prove the tunnel is working, and isolate the fault to the server forwarding/firewall.

**Comment by Matr1x-101** [comment]
I checked `10.6.0.2` and sure enough, it's working

Results:
`Pinging 10.6.0.2 with 32 bytes of data:
Reply from 10.6.0.2: bytes=32 time<1ms TTL=128
Reply from 10.6.0.2: bytes=32 time<1ms TTL=128
Reply from 10.6.0.2: bytes=32 time<1ms TTL=128
Reply from 10.6.0.2: bytes=32 time<1ms TTL=128

Ping statistics for 10.6.0.2:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 0ms, Average = 0ms`

**Comment by Matr1x-101** [comment]
Oh, and it's not just my Raspberry Pi. It's also any address that starts with `192.168`

**Comment by shelleycat485** [comment]
1 Get on the client
2 ping 10.6.0.2  that should be the client  (looks like you are currently pinging client from itself from the < 1ms response time), just confirm that.
3 ping 10.6.0.1 that's the wireguard server
4 Get on the wireguard server (the pi)  Can you run pivpn -d on the wireguard server and post the diagnostic output,
5 Pinging any 192.168.x.y address from the client (assuming you are on the client) failing just means that you have a failure of routing on the wireguard server, probably.
6 On the wireguard server, (the pi) can you show the output of ifconfig, which should show the addresses you have on that machine's interfaces
7 On the wireguard server (the pi) can you show the output of route, which should show whether you have the routes set up correctly.  The other thing that matters, the masquerade, should be shown in the pivpn debug output I'm asking for above.
Best wishes

**Comment by Matr1x-101** [comment]
`10.6.0.1` and `10.6.0.2` are pinging perfectly fine.

 This is the output of pivpn -d: 
::::        Installation settings        ::::
PLAT=Ubuntu
OSCN=groovy
USING_UFW=0
IPv4dev=wlan0
install_user=matrix
install_home=/home/matrix
VPN=wireguard
pivpnPORT=51820
pivpnDNS1=9.9.9.9
pivpnDNS2=149.112.112.112
pivpnHOST=REDACTED
INPUT_CHAIN_EDITED=1
FORWARD_CHAIN_EDITED=1
pivpnPROTO=udp
pivpnDEV=wg0
pivpnNET=10.6.0.0
subnetClass=24
UNATTUPG=1
INSTALLED_PACKAGES=()
=============================================
::::  Server configuration shown below   ::::
[Interface]
PrivateKey = server_priv
Address = 10.6.0.1/24
ListenPort = 51820
### begin matrix ###
[Peer]
PublicKey = matrix_pub
PresharedKey = matrix_psk
AllowedIPs = 10.6.0.2/32
### end matrix ###
=============================================
::::  Client configuration shown below   ::::
[Interface]
PrivateKey = matrix_priv
Address = 10.6.0.2/24
DNS = 9.9.9.9, 149.112.112.112

[Peer]
PublicKey = server_pub
PresharedKey = matrix_psk
Endpoint = REDACTED:51820
AllowedIPs = 0.0.0.0/0, ::0/0
=============================================
::::    Recursive list of files in       ::::
::::    /etc/wireguard shown below       ::::
/etc/wireguard:
client_private_key
client_public_key
configs
keys
matrix.conf
matrix-desktop.conf
matrix-updated.conf
server_private_key
server_public_key
wg0-client.conf.save
wg0.conf

/etc/wireguard/configs:
clients.txt
matrix.conf

/etc/wireguard/keys:
matrix_priv
matrix_psk
matrix_pub
server_priv
server_pub
=============================================
::::            Self check               ::::
:: [OK] IP forwarding is enabled
:: [OK] Iptables MASQUERADE rule set
:: [OK] Iptables INPUT rule set
:: [OK] Iptables FORWARD rule set
:: [OK] WireGuard is running
:: [OK] WireGuard is enabled (it will automatically start on reboot)
:: [OK] WireGuard is listening on port 51820/udp
=============================================
:::: Having trouble connecting? Take a look at the FAQ:
:::: https://github.com/pivpn/pivpn/wiki/FAQ
=============================================
:::: WARNING: This script should have automatically masked sensitive       ::::
:::: information, however, still make sure that PrivateKey, PublicKey      ::::
:::: and PresharedKey are masked before reporting an issue. An example key ::::
:::: that you should NOT see in this log looks like this:                  ::::
:::: YIAoJVsdIeyvXfGGDDadHh6AxsMRymZTnnzZoAb9cxRe                          ::::
=============================================
::::            Debug complete           ::::
:::
::: Debug output completed above.
::: Copy saved to /tmp/debug.log
:::

Output of `ifconfig`

        ether dc:a6:32:55:40:da  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 651834  bytes 86862501 (86.8 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 651834  bytes 86862501 (86.8 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
virbr0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 192.168.122.1  netmask 255.255.255.0  broadcast 192.168.122.255
        ether 52:54:00:6f:10:ea  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
wg0: flags=209<UP,POINTOPOINT,RUNNING,NOARP>  mtu 1420
        inet 10.6.0.1  netmask 255.255.255.0  destination 10.6.0.1
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 1000  (UNSPEC)
        RX packets 1112  bytes 291808 (291.8 KB)
        RX errors 106  dropped 0  overruns 0  frame 106
        TX packets 928  bytes 472004 (472.0 KB)
        TX errors 412  dropped 0 overruns 0  carrier 0  collisions 0

wlan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.0.56  netmask 255.255.255.0  broadcast 192.168.0.255
        inet6 fe80::7cbe:d1d1:764b:c4d1  prefixlen 64  scopeid 0x20<link>
        ether dc:a6:32:55:40:dc  txqueuelen 1000  (Ethernet)
        RX packets 1050789  bytes 1186485849 (1.1 GB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 707897  bytes 366204596 (366.2 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

Output of `route`;

Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         192.168.0.1     0.0.0.0         UG    303    0        0 wlan0
10.6.0.0        0.0.0.0         255.255.255.0   U     0      0        0 wg0
link-local      0.0.0.0         255.255.0.0     U     1000   0        0 wlan0
192.168.0.0     0.0.0.0         255.255.255.0   U     303    0        0 wlan0
192.168.122.0   0.0.0.0         255.255.255.0   U     0      0        0 virbr0

**Comment by shelleycat485** [comment]
The only thing I can see wrong there, is the wg0 interface has high levels of tx packets dropped - that should not be happening, but if you rebooted and looked again it might look better. 

Can you see if you have the problem if you turn off /unconfigure the virbr0 interface?  perhaps that is interfering, 

Everything else looks normal to me.  Sorry not to be more helpful.

**Comment by orazioedoardo** [comment]
No replies in a while, closing...

**Comment by VBA-N7** [comment]
I got the same problem :( Can you share the solution please ? @Matr1x-101

**Comment by Matr1x-101** [comment]
@VBA-N7 I don't think I got it working in the end, also it's been a while and I don't have the original files anymore, sorry to be of no help. Maybe make a new issue?
