### ISSUE TITLE
[FR] Configureable PersistentKeepalive

### ISSUE THREAD

**Issue by knecht-d** [pivpn/pivpn#1219]
Hi,
first of all big kudos for the tool.
I failed installing wireguard manually but succeeded with pivpn without any issue.
And the cli-tools are really great for maintaining.
I have just one issue/feature request regarding the `PersistentKeepalive` setting in wireguard:

**Is your feature request related to a problem? Please describe.**
If operating behind a NAT or Firewall `PersistentKeepalive` can solve some issues (see https://www.wireguard.com/quickstart/).
Since in my case the VPN-Server is behind a NAT (and a lot of clients as well), I often need to adjust the config with this setting.

**Describe the solution you'd like**
I think it would be great to have a "default" setting in `setupVars.conf`.
E.g. `KEEPALIVE_SERVER` and `KEEPALIVE_CLIENT` which is used in `wireguard/makeCONF.sh` to directly create a config with the desired settings.
In addition there might be a cli-parameter to overwrite or set the settings for a specific client (e.g. `--keepalive-server, -K`, `--keepalive-client, -k`; names are of course discussable)
Setting it to "0" would disable it.

**Describe alternatives you've considered**
There is the option to manually adjust the config after creating. Which requires additional work.
It would also be an option to hard-code the defaults locally as in https://github.com/pivpn/pivpn/pull/1174.
But I think others could benefit from such an option as well.

**Additional context**
I'm not an expert with shell-scripts but I think I could implement the feature(s) I described above for a PR.
However, I'm not sure how to adjust the install-script so that the settings could be configured during installation.
And I don't know how this could be implemented for OpenVPN as well. (Afaik there is a similar setting there)

What do you think? I'm open for feedback and discussions 🙂

**Comment by orazioedoardo** [comment]
Adding a configurable keepalive variable is easy but I think it provides a small benefit for the majority of PiVPN's users (see the pull request you mentioned).

**Comment by orazioedoardo** [comment]
No replies in a while, closing...

**Comment by DerDanilo** [comment]
FYI: Added to wireguard profiles
https://github.com/pivpn/pivpn/pull/1321/commits/88a701c16a62b002daf291fb0822c5e5f720c58a
