### ISSUE TITLE
[Investigation] Ubuntu Xenial, Wireguard fails to start

### ISSUE THREAD

**Issue by 4s3ti** [pivpn/pivpn#1224]
There seems to be an Edge case on Ubuntu Xenial where PiVPN installs wireguard and wg-quick@wg0 service fails to start, 

This can be seen on travis-ci test jobs i have been working on: https://travis-ci.com/github/4s3ti/pivpn/jobs/470886062 

however i have been failing to replicate this in order to find the culprit

Systems where i have run tests: 

AWS 
Hetzner
Scaleway (not entirely sure if i did on this one)
manually installed ubuntu xenial

@orazioedoardo have you stumbled on this? 
is there a way to replicate this so we can eventually try to cover it?

**Comment by 4s3ti** [comment]
Managed to get some more logging from the ci-scripts: 

```
Unit wg-quick@wg0.service has begun starting up.
Jan 12 17:40:51 pivpn.test wg-quick[5162]: [#] ip link add wg0 type wireguard
Jan 12 17:40:51 pivpn.test wg-quick[5162]: RTNETLINK answers: Operation not supported
Jan 12 17:40:51 pivpn.test wg-quick[5162]: Unable to access interface: Protocol not supported
Jan 12 17:40:51 pivpn.test wg-quick[5162]: [#] ip link delete dev wg0
Jan 12 17:40:51 pivpn.test wg-quick[5162]: Cannot find device "wg0"
Jan 12 17:40:51 pivpn.test systemd[1]: wg-quick@wg0.service: Main process exited, code=exited, status=1/FAILURE
Jan 12 17:40:51 pivpn.test systemd[1]: Failed to start WireGuard via wg-quick(8) for wg0.
Subject: Unit wg-quick@wg0.service has failed
Defined-By: systemd
Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
Unit wg-quick@wg0.service has failed.
```

**Comment by blackm** [comment]
run into the same issue after rebooting my rpi....fix it with **dpkg-reconfigure wireguard-dkms** ...kernel module for the current kernel was missing. You may need to install your kernel headers.

**Comment by 4s3ti** [comment]
@blackm Cool thanks for the tip ... the problem is that i cannot replicate the issue to find the solution ... as i say in the description i am building CI/CD Pipelines and automated testing ... and it fails on the Pipeline machines but not in none of the machines i have tried, will try that and see if it might fix

**Comment by 4s3ti** [comment]
@orazioedoardo do you have any clue what might be causing this?? i can't replicate this in any way ... you can see the logs on travis

**Comment by orazioedoardo** [comment]
@4s3ti I haven't tested Xenial yet. I think the issue could be similar to that of Raspian in the past: the wireguard package is compiled against newer headers but the running kernel is older on a clean install.

**Comment by 4s3ti** [comment]
it might be a specific tricky case ... i tested in multiple cloud providers, even on a fresh manual install of xenial and couldn't get that issue to happen in any scenario .. only happening on Travis CI servers ... but i don't really like to see it failing when the script is actually working ... and don't really wanted to tweak the CI scripts in a way to make it pass ... but I might Ignore the pivpn scripts on that particular distro as they are properly tested on the other ones

**Comment by 4s3ti** [comment]
I have Moved the scripts that cause the pipeline to after_script .. they are still run we can still see their output and exit codes but won't make it fail, since its a really edge case on xenial .. will keep this open in case anyone manages to replicate

**Comment by 4s3ti** [comment]
Closing this as it seems to be happening only on the CI environment.
