### ISSUE TITLE
VPN Site to Site

### ISSUE THREAD

**Issue by Kahiogoo** [pivpn/pivpn#1225]
Hello,
I would like to know if it is possible to make a site-to-site VPN connection with piVPN. If so, how to proceed?
Thank you so much

Kahio

**Comment by orazioedoardo** [comment]
It is definitely possible, you need two Raspberry Pi, however that's a bit too much a IT tech support request, way beyond the scope of PiVPN. Issues are not meant for general networking help, you should ask on dedicated forums.

**Comment by H34dl3ss** [comment]
I'm also interested in setting up a Site2Site.
@Kahiogoo 
Have you found a solution to do so?
I was thinking of setting up the basics with PiVPN and modifying the configs to have a Site2Site.

**Comment by Kahiogoo** [comment]
Hello @H34dl3ss,
Unfortunately I still haven't found a solution. 
I am beginning to move towards simpler solutions (Zyxell ...). But I would have preferred to find an open-source solution, especially based on raspberry and OpenVPN or WireGuard.

**Comment by freddyrios** [comment]
@orazioedoardo its kind of a documentation issue. There is no mention about site to site, which one of 2 common usages of vpn (the other one being simple remote access).

By the way, are you saying between the lines, that it does makes sense to use pivpn as a starting point for site to site setups?

**Comment by 4s3ti** [comment]
> By the way, are you saying between the lines, that it does makes sense to use pivpn as a starting point for site to site setups?

No!  either it isn't a documentation issue or anything is being said between the lines, simply its not in the **scope** of PiVPN project ... PiVPN project has the objective of easily make a VPN server accessible! 

It is possible? yes it is, can be done with pivpn? yes it can however Site-to-Site VPNs are more "Advanced" setups for more specific use cases! which even I don't have a requirement for one, as simple as that ...

PiVPN Objective is to make VPNs as accessible as possible specially to the ones with less technical knowledge and to keep it as simple as possible! 

This said, I am closing this thread. 

If anyone knows how to make a Site2Site using PiVPN, has the time and wants to help others doing it, feel free to make a blog post about it and submit a PR to our [docs ](https://github.com/pivpn/docs) and ill gladly review it! 


this is not that we don't want to grow or support more use cases, its more that we cannot afford to support more and more stuff without the resources for it!

**Comment by freddyrios** [comment]
@4s3ti thanks for the clear answer!

A little note in the doc that mentions pivpn is aimed mainly at vpns for privacy & remote access scenarios only could help avoid future questions, while also being helpful for anybody having the same question.

**Comment by 4s3ti** [comment]
@freddyrios well I don't believe that note should be added also ... let's say that someone is willing to invest its time to implement such feature and stick around to help maintaining it? I don't see a reason why not!
however as it is right now ... we just can't afford it :)
