### ISSUE TITLE
[Support] rpi3 + pihole + pivpn: server poll timeout.?

### ISSUE THREAD

**Issue by grbesd1** [pivpn/pivpn#1226]
## In raising this issue, I confirm the following:

`{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*.
- [] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

### Issue
Wi-Fi Hardware: TP-Link Archer C20 V5 WiFi Router
DNS Server Hardware: Raspberry Pi 3 
OS: Raspbian OS with pihole.
Router IP: 192.168.7.x
rpi ip: 192.168.7.104
dns server ip: 192.168.7.104 

I have recently setup rpi with pihole and it's works fine on my local wifi network. Now, i want to add openvpn, so i can access pihole dns server remotely for that i'm using pivpn. 

pivpn script works fine and openvpn installation is complete and openvpn is running.

pi@raspberrypi:~ $ ps -eax |  grep openvpn
14949 ?        Ss     0:00 /usr/sbin/openvpn --daemon ovpn-server --status /run/openvpn/server.status 10 --cd /etc/openvpn --config /etc/openvpn/server.conf --writepid /run/openvpn/server.pid

I have generated client profile and using android openvpn connect to connect. It has imported profile but it is giving following error: " server poll imeout issue.trying next remote entry." 

I want to emphasize that i have tried nearly as many time as possible using pihole + openvpn guide or pivpn bash script. But nothing works.

### Have you searched for similar issues and solutions?
    (yes/no / which issues?)
yes

### Console output of      `curl -L install.pivpn.io | bash`
```
  successful
```

### Console output of      `pivpn add` or `pivpn add nopass`
```
  successful.
```

### Console output of      `pivpn debug`
```
::: Generating Debug Output
::::		PiVPN debug		 ::::
=============================================
::::		Latest commit		 ::::
commit 75acaf97ae4457bbfdf9ec5ea0df5c6380bf5c1a
Author: 4s3ti <4s3ti@protonmail.com>
Date:   Fri Jan 8 16:04:21 2021 +0100

    Change issue template
    
    Changed issue template from pivpn.dev to pivpn.io
=============================================
::::	    Installation settings    	 ::::
PLAT=Raspbian
OSCN=buster
USING_UFW=0
IPv4dev=wlan0
IPv4addr=192.168.7.104/24
IPv4gw=192.168.7.1
install_user=pi
install_home=/home/pi
VPN=openvpn
pivpnPROTO=udp
pivpnPORT=12945
pivpnDNS1=10.8.0.1
pivpnDNS2=
pivpnSEARCHDOMAIN=
pivpnHOST=REDACTED
TWO_POINT_FOUR=1
pivpnENCRYPT=256
USE_PREDEFINED_DH_PARAM=
INPUT_CHAIN_EDITED=0
FORWARD_CHAIN_EDITED=0
pivpnDEV=tun0
pivpnNET=10.8.0.0
subnetClass=24
UNATTUPG=1
INSTALLED_PACKAGES=(openvpn)
HELP_SHOWN=1
=============================================
::::  Server configuration shown below   ::::
dev tun
proto udp
port 12945
ca /etc/openvpn/easy-rsa/pki/ca.crt
cert /etc/openvpn/easy-rsa/pki/issued/raspberrypi_42c788f0-04ad-4378-8a9f-59d61daf1864.crt
key /etc/openvpn/easy-rsa/pki/private/raspberrypi_42c788f0-04ad-4378-8a9f-59d61daf1864.key
dh none
ecdh-curve prime256v1
topology subnet
server 10.8.0.0 255.255.255.0
# Set your primary domain name server address for clients
push "dhcp-option DNS 192.168.7.104"
push "block-outside-dns"
# Override the Client default gateway by using 0.0.0.0/1 and
# 128.0.0.0/1 rather than 0.0.0.0/0. This has the benefit of
# overriding but not wiping out the original default gateway.
#push "redirect-gateway def1"
push "192.168.7.0 255.255.255.0"
client-to-client
client-config-dir /etc/openvpn/ccd
keepalive 15 120
remote-cert-tls client
tls-version-min 1.2
tls-crypt /etc/openvpn/easy-rsa/pki/ta.key
cipher AES-256-CBC
auth SHA256
user openvpn
group openvpn
persist-key
persist-tun
crl-verify /etc/openvpn/crl.pem
status /var/log/openvpn-status.log 20
status-version 3
syslog
verb 3
tun-mtu 1500 
mssfix 1360
#DuplicateCNs allow access control on a less-granular, per user basis.
#Remove # if you will manage access by user instead of device. 
#duplicate-cn
# Generated for use by PiVPN.io
=============================================
::::  Client template file shown below   ::::
client
dev tun
proto udp
remote REDACTED 12945
resolv-retry infinite
nobind
remote-cert-tls server
tls-version-min 1.2
verify-x509-name raspberrypi_42c788f0-04ad-4378-8a9f-59d61daf1864 name
cipher AES-256-CBC
auth SHA256
auth-nocache
verb 3
=============================================
:::: 	Recursive list of files in	 ::::
::: /etc/openvpn/easy-rsa/pki shows below :::
/etc/openvpn/easy-rsa/pki/:
biradar.ovpn
ca.crt
crl.pem
Default.txt
ecparams
index.txt
index.txt.attr
index.txt.attr.old
index.txt.old
issued
openssl-easyrsa.cnf
private
renewed
revoked
safessl-easyrsa.cnf
serial
serial.old
ta.key

/etc/openvpn/easy-rsa/pki/ecparams:
prime256v1.pem

/etc/openvpn/easy-rsa/pki/issued:
biradar.crt
raspberrypi_42c788f0-04ad-4378-8a9f-59d61daf1864.crt

/etc/openvpn/easy-rsa/pki/private:
biradar.key
ca.key
raspberrypi_42c788f0-04ad-4378-8a9f-59d61daf1864.key

/etc/openvpn/easy-rsa/pki/renewed:
private_by_serial
reqs_by_serial

/etc/openvpn/easy-rsa/pki/renewed/private_by_serial:

/etc/openvpn/easy-rsa/pki/renewed/reqs_by_serial:

/etc/openvpn/easy-rsa/pki/revoked:
private_by_serial
reqs_by_serial

/etc/openvpn/easy-rsa/pki/revoked/private_by_serial:
192EB9DC21A1B96014AFB42AA15F73FC.key

/etc/openvpn/easy-rsa/pki/revoked/reqs_by_serial:
192EB9DC21A1B96014AFB42AA15F73FC.req
=============================================
::::		Self check		 ::::
:: [OK] IP forwarding is enabled
:: [OK] Iptables MASQUERADE rule set
:: [OK] OpenVPN is running
:: [OK] OpenVPN is enabled (it will automatically start on reboot)
:: [OK] OpenVPN is listening on port 12945/udp
=============================================
:::: Having trouble connecting? Take a look at the FAQ:
:::: https://github.com/pivpn/pivpn/wiki/FAQ
=============================================
::::      Snippet of the server log      ::::
Jan 17 11:34:14 raspberrypi ovpn-server[14949]: OpenVPN 2.4.7 arm-unknown-linux-gnueabihf [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 20 2019
Jan 17 11:34:14 raspberrypi ovpn-server[14949]: library versions: OpenSSL 1.1.1d  10 Sep 2019, LZO 2.10
Jan 17 11:34:14 raspberrypi ovpn-server[14949]: ECDH curve prime256v1 added
Jan 17 11:34:14 raspberrypi ovpn-server[14949]: Outgoing Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Jan 17 11:34:14 raspberrypi ovpn-server[14949]: Outgoing Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Jan 17 11:34:14 raspberrypi ovpn-server[14949]: Incoming Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Jan 17 11:34:14 raspberrypi ovpn-server[14949]: Incoming Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Jan 17 11:34:14 raspberrypi ovpn-server[14949]: TUN/TAP device tun0 opened
Jan 17 11:34:14 raspberrypi ovpn-server[14949]: TUN/TAP TX queue length set to 100
Jan 17 11:34:14 raspberrypi ovpn-server[14949]: /sbin/ip link set dev tun0 up mtu 1500
Jan 17 11:34:14 raspberrypi ovpn-server[14949]: /sbin/ip addr add dev tun0 10.8.0.1/24 broadcast 10.8.0.255
Jan 17 11:34:14 raspberrypi ovpn-server[14949]: Could not determine IPv4/IPv6 protocol. Using AF_INET
Jan 17 11:34:14 raspberrypi ovpn-server[14949]: Socket Buffers: R=[180224->180224] S=[180224->180224]
Jan 17 11:34:14 raspberrypi ovpn-server[14949]: UDPv4 link local (bound): [AF_INET][undef]:12945
Jan 17 11:34:14 raspberrypi ovpn-server[14949]: UDPv4 link remote: [AF_UNSPEC]
Jan 17 11:34:14 raspberrypi ovpn-server[14949]: GID set to openvpn
Jan 17 11:34:14 raspberrypi ovpn-server[14949]: UID set to openvpn
Jan 17 11:34:14 raspberrypi ovpn-server[14949]: MULTI: multi_init called, r=256 v=256
Jan 17 11:34:14 raspberrypi ovpn-server[14949]: IFCONFIG POOL: base=10.8.0.2 size=252, ipv6=0
Jan 17 11:34:14 raspberrypi ovpn-server[14949]: Initialization Sequence Completed
=============================================

```
### Have you taken any steps towards solving your issue?
```
  which?
```
sudo iptables -t nat -S
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P POSTROUTING ACCEPT
-P OUTPUT ACCEPT
-A POSTROUTING -s 10.8.0.0/24 -o wlan0 -m comment --comment openvpn-nat-rule -j MASQUERADE
-A POSTROUTING -s 10.8.0.0/24 ! -d 10.8.0.0/24 -j SNAT --to-source 192.168.7.104
-A POSTROUTING -s 10.8.0.0/24 ! -d 10.8.0.0/24 -j SNAT --to-source 192.168.7.104
-A POSTROUTING -s 10.8.0.0/24 ! -d 10.8.0.0/24 -j SNAT --to-source 192.168.7.104
-A POSTROUTING -s 10.8.0.0/24 ! -d 10.8.0.0/24 -j SNAT --to-source 192.168.7.104

sudo ufw status verbose
Status: inactive

curl -s https://checkip.amazonaws.com
It matches piVPN Host.

pi@raspberrypi:~ $ ip -f inet address
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
3: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    inet 192.168.7.104/24 brd 192.168.7.255 scope global dynamic noprefixroute wlan0
       valid_lft 46240sec preferred_lft 35440sec
8: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN group default qlen 100
    inet 10.8.0.1/24 brd 10.8.0.255 scope global tun0
       valid_lft forever preferred_lft forever

**Comment by orazioedoardo** [comment]
Server pool timeout means that the client can't reach the server. Have you forwarded port 12945 UDP on your router? You can follow these troubleshooting steps too: https://github.com/pivpn/pivpn/wiki/FAQ#how-do-i-troubleshoot-connection-issues

**Comment by orazioedoardo** [comment]
No replies in a while, closing...
