### ISSUE TITLE
Installing both Wireguard *and* OpenVPN (for TAP)

### ISSUE THREAD

**Issue by TheMaskedAvengers** [pivpn/pivpn#1227]
Hi folks,

I'm looking to get my pi set up with both a good VPN for security on public wifi and also to access servers/devices which are inside my network. I understand Wireguard is better for the former but can't talk to your local network devices without some convoluted work arounds  (no TAP support)..I also know it saves IPs which is fine for most of my use but there'll be times when I want a bit better privacy (no logs) and (much more often) to interact with servers within my LAN (I don't want to port forward these to the external network for security reasons - would rather use a TAP VPN to bridge my way into my local network than leave lots of open ports to the wide world....For this OpenVPN is the way to go...I get it's clunkier...I get that all that broadcast traffic etc will add overhead etc and potentially slow it down....

Question:
The PiVPN script makes setting up WG and OpenVPN super easy...but the fact that it's either or is slightly frustrating as my setup would really benefit from both of them...

Is there an easy work around to use the wrapper to set up the second one? As I'm about to try to do it manually and this project just makes it *so* much easier!

PS - I did actually hit problems with WG install on the latest version of raspbian on a 3B+ using PiVPN - PIVPN wouldn't start... currently reinstalling to try to fix it. Output below in case someone knows the issue. I've already got the latest kernel headers (tried that). Looks like WG isn't starting for whatever reason...

```
=============================================
::::		Self check		 ::::
:: [OK] IP forwarding is enabled
:: [OK] Iptables MASQUERADE rule set
**:: [ERR] WireGuard is not running, try to start now? [Y/n] Y**
Warning: The unit file, source configuration file or drop-ins of wg-quick@wg0.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Job for wg-quick@wg0.service failed because the control process exited with error code.
See "systemctl status wg-quick@wg0.service" and "journalctl -xe" for details.
Done
:: [OK] WireGuard is enabled (it will automatically start on reboot)
:: [OK] WireGuard is listening on port 51820/udp
[INFO] Run pivpn -d again to see if we detect issues
=============================================
:::: Having trouble connecting? Take a look at the FAQ:
:::: https://github.com/pivpn/pivpn/wiki/FAQ
=============================================
:::: WARNING: This script should have automatically masked sensitive       ::::
:::: information, however, still make sure that PrivateKey, PublicKey      ::::
:::: and PresharedKey are masked before reporting an issue. An example key ::::
:::: that you should NOT see in this log looks like this:                  ::::
:::: YIAoJVsdIeyvXfGGDDadHh6AxsMRymZTnnzZoAb9cxRe                          ::::
=============================================
::::		Debug complete		 ::::
::: 
::: Debug output completed above.
::: Copy saved to /tmp/debug.log
```

```
wg-quick@wg0.service - WireGuard via wg-quick(8) for wg0
   Loaded: loaded (/lib/systemd/system/wg-quick@.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/wg-quick@wg0.service.d
           └─override.conf
   **Active: failed (Result: exit-code)** since Mon 2021-01-18 15:37:36 GMT; 3min 35s ago
     Docs: man:wg-quick(8)
           man:wg(8)
           https://www.wireguard.com/
           https://www.wireguard.com/quickstart/
           https://git.zx2c4.com/wireguard-tools/about/src/man/wg-quick.8
           https://git.zx2c4.com/wireguard-tools/about/src/man/wg.8
 **Main PID: 5373 (code=exited, status=1/FAILURE)**

Jan 18 15:37:36 pivpn upnpc[5380]: for more information.
Jan 18 15:37:36 pivpn upnpc[5380]: List of UPNP devices found on the network :
Jan 18 15:37:36 pivpn upnpc[5380]:  desc: http://192.168.1.1:52869/gatedesc.xml
Jan 18 15:37:36 pivpn upnpc[5380]:  st: urn:schemas-upnp-org:device:InternetGatewayDevice:1
Jan 18 15:37:36 pivpn upnpc[5380]: Found valid IGD : http://192.168.1.1:52869/upnp/control/WANIPConn1
Jan 18 15:37:36 pivpn upnpc[5380]: Local LAN ip address : 192.168.1.175
**Jan 18 15:37:36 pivpn upnpc[5380]: UPNP_DeletePortMapping() failed with code : 714
Jan 18 15:37:36 pivpn systemd[1]: wg-quick@wg0.service: Control process exited, code=exited, status=2/INVALIDAR
Jan 18 15:37:36 pivpn systemd[1]: wg-quick@wg0.service: Failed with result 'exit-code'.
Jan 18 15:37:36 pivpn systemd[1]: Failed to start WireGuard via wg-quick(8) for wg0.**
```

**Comment by TheMaskedAvengers** [comment]
Sorry no idea why the formatting went so large!

**Comment by 4s3ti** [comment]
Fixed, edited your post, multi line code // output should be wrapped inside Three Backticks (`), you were using single back ticks which should be used for single line code

**Comment by shelleycat485** [comment]
You said  "The PiVPN script makes setting up WG and OpenVPN super easy...but the fact that it's either or is slightly frustrating as my setup would really benefit from both of them..."

It supports both.  Just run the installer a second time, reconfigure, select the other protocol and install it.  I find it easiest to use this:

```
bash pivpn/auto_install/install.sh
```
for the second one.  The repository is in /usr/local/src/pivpn/  

For your second problem, I've had to uninstall wireguard-dkms and reinstall it.

**Comment by orazioedoardo** [comment]
No replies in a while, closing...
