### ISSUE TITLE
[Support] No access to network after changing interface and subnet?

### ISSUE THREAD

**Issue by Shaker1978** [pivpn/pivpn#1230]
## In raising this issue, I confirm the following:
- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

I prepared a Raspberry PI 3 at home on a x.x.117.0 subnet using the WiFi interface and using DHCP with an IP reservation. I used the install script on https://install.pivpn.io just a few days ago this week. It worked when using an OpenVPN client on my Android phone out of the mobile network. **I could access my LAN devices just fine**.

Then I wanted to try this PI in a different place. I used the LAN port, a static IP address and the subnet was x.x.2.0.
In the server.conf I changed
push "dhcp-option DNS xxxx"
to match their router's IP address and in Default.txt I changed the remote address.
Then I added a new client (pivpn add).
I imported the new .ovpn in a Windows OpenVPN client and could connect to the PI. I could start an SSH session as well. **But no access to the rest of the network was possible**.

iptables gives me:
MASQUERADE  all  --  10.8.0.0/24          anywhere             /* openvpn-nat-rule */

What did I forget when changing the configs? What else can be wrong here?

### Have you searched for similar issues and solutions?
yes, other solutions were saying to add another iptables rule for eth0, but since it says "anywhere" in my version, I think, this is find.

**Comment by Shaker1978** [comment]
Sorry, just contunied my search and found that in /etc/iptables/rules.v4 it says ... -o wlan0 ...
I will try changing this and try again with LAN.

But, the switching of the subnet shouldn't be a problem in general, right?

**Comment by orazioedoardo** [comment]
PiVPN optionally sets a static IP inside `/etc/dhcpcd.conf` which you need to update if you change subnet.

**Comment by orazioedoardo** [comment]
No replies in a while, closing...
