### ISSUE TITLE
[Improvement] Make ShellCheck Happy

### ISSUE THREAD

**Issue by 4s3ti** [pivpn/pivpn#1233]
PiVPN is currently failing on Linting tests, 

https://travis-ci.com/github/pivpn/pivpn/jobs/475625045

PiVPN scripts should pass on shellcheck and this should be later used to evaluate PR quality. 

Since it is not Breaking anything in the script, I have added `allow_failures` for linting stage until this has been closed.

**Comment by orazioedoardo** [comment]
We should also have a coding style guide. As of now coding style is not consistent.

**Comment by 4s3ti** [comment]
agree! but i am not sure if am the right one to implement that .... having shellcheck checking for good practices is already a good start.

**Comment by orazioedoardo** [comment]
We could just link to this one: https://google.github.io/styleguide/shellguide.html

**Comment by DundarGoc** [comment]
I've had the most success with [shfmt](https://github.com/mvdan/sh) when it comes to shell formatters and can highly recommend it.

**Comment by DundarGoc** [comment]
I'm new to pull requests, do you prefer one mid-sized pull request with a list of of changes och one pull request per change?

**Comment by 4s3ti** [comment]
@DundarGoc Personally i prefer smaller fixing one issue at a time as they tend to be easier to read and review, also makes easier to track any issue in case it comes up :) this said i don't mind having a thouzand of commits for the same issue :)

**Comment by DundarGoc** [comment]
I can't find setupVars.conf in the repo, is it created at runtime or something?

**Comment by 4s3ti** [comment]
@DundarGoc Yes, basically during runtime script echoes the variables and its values to that file which is in turn used later by the pivpn scripts as a way to identify which options were used during setup and by the --debug option to info on whichsettings were used during the setup

That file can also be used for `--unattended` setups ... 1 example here: https://github.com/pivpn/pivpn/blob/master/ciscripts/ci_wireguard.conf

**Comment by 4s3ti** [comment]
Chellsheck is now happy on test branch! 

CI Job will no longer tolerate failures on Lint/shellcheck stage.

**Comment by 4s3ti** [comment]
Merged to master today. 
https://github.com/pivpn/pivpn/commit/d4e3a63522e4edaa2f9ad9f2d8dd6ffab4117ff9

Closing ...
