### ISSUE TITLE
[Support] Unable to change public IP

### ISSUE THREAD

**Issue by bobaxxx** [pivpn/pivpn#1235]
## In raising this issue, I confirm the following:

`{please fill the checkboxes, e.g: [X]}`

- [x] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate

- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).

### Issue
Hi all,

I got pivpn working on a remote ovh vps (fr located), running debian 10. I have the 2 instance of pivpn working (wireguard + openvpn), there is a pihole already installed.

I have an ipfailover parked, so i wanted to switch my public wireguard IP with this one, with no success. What i did : 

- Using changing ip guide at : "https://docs.pivpn.io/wireguard/"
- Configuring ipfailover on my existing network card with this guide : "https://support.us.ovhcloud.com/hc/en-us/articles/360014248820-How-to-Configure-IP-Aliasing-on-a-VPS#debian" (eth0:0)
- Changing "pivpnhost=" parameters with the ipfailover address in /etc/pivpn/wireguard/setupvars.conf
- Changing "ipv4adress=" parameters with the ipfailover address in /etc/pihole/setupvars.conf
- Changing the pivpn endpoint on the client configuration file (anyway, with or without this change, result is the same)
- reboot

When i disconnect and reconnect wireguard on my cllient, i check and im still using the original public ip address.

Is this related to the eth0:0 associated to the eth0 network card ? or do i miss some other parameter/config file inside the vps ?

### Have you searched for similar issues and solutions?
    yes, i dont find anything related to my problem

**Comment by orazioedoardo** [comment]
Post the debug log: `pivpn -d`

**Comment by bobaxxx** [comment]
::::		PiVPN debug		 ::::
=============================================
::::		Latest commit		 ::::
commit 13f0fe7cbdcdb31537b3fd0e2eb34652e886cc1b
Author: 4s3ti <4s3ti@protonmail.com>
Date:   Wed Dec 9 19:22:29 2020 +0100

    ProBot Stale
    
    Added probot integration to marke topics as inactives and automatically
    close them.
    read .github/stale.yml for more details.
=============================================
::::	    Installation settings    	 ::::
PLAT=Debian
OSCN=buster
USING_UFW=0
IPv4dev=eth0
install_user=vpn
install_home=/home/vpn
VPN=wireguard
pivpnPORT=51820
pivpnDNS1=10.6.0.1
pivpnDNS2=
pivpnHOST=REDACTED
INPUT_CHAIN_EDITED=1
FORWARD_CHAIN_EDITED=1
pivpnPROTO=udp
pivpnDEV=wg0
pivpnNET=10.6.0.0
subnetClass=24
UNATTUPG=0
INSTALLED_PACKAGES=(wireguard-tools qrencode linux-headers-amd64 wireguard-dkms)
=============================================
::::  Server configuration shown below   ::::
[Interface]
PrivateKey = server_priv
Address = 10.6.0.1/24
ListenPort = 51820
### begin seb-tel-internet ###
[Peer]
PublicKey = seb-tel-internet_pub
PresharedKey = seb-tel-internet_psk
AllowedIPs = 10.6.0.2/32
### end seb-tel-internet ###
### begin sebpc-internet ###
[Peer]
PublicKey = sebpc-internet_pub
PresharedKey = sebpc-internet_psk
AllowedIPs = 10.6.0.3/32
### end sebpc-internet ###
### begin manue-tel ###
[Peer]
PublicKey = manue-tel_pub
PresharedKey = manue-tel_psk
AllowedIPs = 10.6.0.4/32
### end manue-tel ###
### begin pivpn-maison ###
[Peer]
PublicKey = pivpn-maison_pub
PresharedKey = pivpn-maison_psk
AllowedIPs = 10.6.0.7/32
### end pivpn-maison ###
### begin kodi-hc ###
[Peer]
PublicKey = kodi-hc_pub
PresharedKey = kodi-hc_psk
AllowedIPs = 10.6.0.5/32
### end kodi-hc ###
### begin manue-pc ###
[Peer]
PublicKey = manue-pc_pub
PresharedKey = manue-pc_psk
AllowedIPs = 10.6.0.6/32
### end manue-pc ###
=============================================
::::  Client configuration shown below   ::::
[Interface]
PrivateKey = seb-tel-internet_priv
Address = 10.6.0.2/24
DNS = 10.6.0.1

[Peer]
PublicKey = server_pub
PresharedKey = seb-tel-internet_psk
Endpoint = REDACTED:51820
AllowedIPs = 0.0.0.0/0, ::0/0
=============================================
:::: 	Recursive list of files in	 ::::
::::	/etc/wireguard shown below	 ::::
/etc/wireguard:
configs
keys
wg0.conf

/etc/wireguard/configs:
clients.txt
kodi-hc.conf
manue-pc.conf
manue-tel.conf
pivpn-maison.conf
sebpc-internet.conf
seb-tel-internet.conf

/etc/wireguard/keys:
kodi-hc_priv
kodi-hc_psk
kodi-hc_pub
manue-pc_priv
manue-pc_psk
manue-pc_pub
manue-tel_priv
manue-tel_psk
manue-tel_pub
pivpn-maison_priv
pivpn-maison_psk
pivpn-maison_pub
sebpc-internet_priv
sebpc-internet_psk
sebpc-internet_pub
seb-tel-internet_priv
seb-tel-internet_psk
seb-tel-internet_pub
server_priv
server_pub
=============================================
::::		Self check		 ::::
:: [OK] IP forwarding is enabled
:: [OK] Iptables MASQUERADE rule set
:: [OK] Iptables INPUT rule set
:: [OK] Iptables FORWARD rule set
:: [OK] WireGuard is running
:: [OK] WireGuard is enabled (it will automatically start on reboot)
:: [OK] WireGuard is listening on port 51820/udp
=============================================
:::: Having trouble connecting? Take a look at the FAQ:
:::: https://github.com/pivpn/pivpn/wiki/FAQ
=============================================
:::: WARNING: This script should have automatically masked sensitive       ::::
:::: information, however, still make sure that PrivateKey, PublicKey      ::::
:::: and PresharedKey are masked before reporting an issue. An example key ::::
:::: that you should NOT see in this log looks like this:                  ::::
:::: YIAoJVsdIeyvXfGGDDadHh6AxsMRymZTnnzZoAb9cxRe                          ::::
=============================================
::::		Debug complete		 ::::




i see another line into those 2 config files  

- /etc/pivpn/setupVars.conf -> IPv4dev=eth0
- /etc/pihole/setupVars.conf -> PIHOLE_INTERFACE=eth0

but the one interface im using is now eth0:0, should i change it ?
or maybe i test to recreate new client ?

**Comment by bobaxxx** [comment]
:::: PiVPN debug ::::

:::: Latest commit ::::
commit 13f0fe7
Author: 4s3ti 4s3ti@protonmail.com
Date: Wed Dec 9 19:22:29 2020 +0100

ProBot Stale

Added probot integration to marke topics as inactives and automatically
close them.
read .github/stale.yml for more details.

=============================================
Installation settings
PLAT=Debian
OSCN=buster
USING_UFW=0
IPv4dev=eth0
install_user=vpn
install_home=/home/vpn
VPN=wireguard
pivpnPORT=51820
pivpnDNS1=10.6.0.1
pivpnDNS2=
pivpnHOST=REDACTED
INPUT_CHAIN_EDITED=1
FORWARD_CHAIN_EDITED=1
pivpnPROTO=udp
pivpnDEV=wg0
pivpnNET=10.6.0.0
subnetClass=24
UNATTUPG=0
INSTALLED_PACKAGES=(wireguard-tools qrencode linux-headers-amd64 wireguard-dkms)

Server configuration shown below
[Interface]
PrivateKey = server_priv
Address = 10.6.0.1/24
ListenPort = 51820
begin seb-tel-internet

[Peer]
PublicKey = seb-tel-internet_pub
PresharedKey = seb-tel-internet_psk
AllowedIPs = 10.6.0.2/32
end seb-tel-internet
begin sebpc-internet

[Peer]
PublicKey = sebpc-internet_pub
PresharedKey = sebpc-internet_psk
AllowedIPs = 10.6.0.3/32
end sebpc-internet
begin manue-tel

[Peer]
PublicKey = manue-tel_pub
PresharedKey = manue-tel_psk
AllowedIPs = 10.6.0.4/32
end manue-tel
begin pivpn-maison

[Peer]
PublicKey = pivpn-maison_pub
PresharedKey = pivpn-maison_psk
AllowedIPs = 10.6.0.7/32
end pivpn-maison
begin kodi-hc

[Peer]
PublicKey = kodi-hc_pub
PresharedKey = kodi-hc_psk
AllowedIPs = 10.6.0.5/32
end kodi-hc
begin manue-pc

[Peer]
PublicKey = manue-pc_pub
PresharedKey = manue-pc_psk
AllowedIPs = 10.6.0.6/32
end manue-pc

=============================================
Client configuration shown below
[Interface]
PrivateKey = seb-tel-internet_priv
Address = 10.6.0.2/24
DNS = 10.6.0.1
[Peer]
PublicKey = server_pub
PresharedKey = seb-tel-internet_psk
Endpoint = REDACTED:51820
AllowedIPs = 0.0.0.0/0, ::0/0

Recursive list of files in	 

/etc/wireguard shown below
/etc/wireguard:
configs
keys
wg0.conf

/etc/wireguard/configs:
clients.txt
kodi-hc.conf
manue-pc.conf
manue-tel.conf
pivpn-maison.conf
sebpc-internet.conf
seb-tel-internet.conf
/etc/wireguard/keys:
kodi-hc_priv
kodi-hc_psk
kodi-hc_pub
manue-pc_priv
manue-pc_psk
manue-pc_pub
manue-tel_priv
manue-tel_psk
manue-tel_pub
pivpn-maison_priv
pivpn-maison_psk
pivpn-maison_pub
sebpc-internet_priv
sebpc-internet_psk
sebpc-internet_pub
seb-tel-internet_priv
seb-tel-internet_psk
seb-tel-internet_pub
server_priv
server_pub

Self check

:: [OK] IP forwarding is enabled
:: [OK] Iptables MASQUERADE rule set
:: [OK] Iptables INPUT rule set
:: [OK] Iptables FORWARD rule set
:: [OK] WireGuard is running
:: [OK] WireGuard is enabled (it will automatically start on reboot)
:: [OK] WireGuard is listening on port 51820/udp
:::: Having trouble connecting? Take a look at the FAQ:
:::: https://github.com/pivpn/pivpn/wiki/FAQ
:::: WARNING: This script should have automatically masked sensitive ::::
:::: information, however, still make sure that PrivateKey, PublicKey ::::
:::: and PresharedKey are masked before reporting an issue. An example key ::::
:::: that you should NOT see in this log looks like this: ::::
:::: YIAoJVsdIeyvXfGGDDadHh6AxsMRymZTnnzZoAb9cxRe ::::

:::: Debug complete ::::

i see another line into those 2 config files

    /etc/pivpn/setupVars.conf -> IPv4dev=eth0
    /etc/pihole/setupVars.conf -> PIHOLE_INTERFACE=eth0

but the one interface im using is now eth0:0, should i change it ?
or maybe i test to recreate new client ?

**Comment by orazioedoardo** [comment]
> but the one interface im using is now eth0:0, should i change it ?

Possibly, can I see `sudo iptables -S` and `sudo iptables -t nat -S`?

**Comment by bobaxxx** [comment]
sudo iptables -S : 

-P INPUT DROP
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
-N f2b-nginx-http-auth
-A INPUT -p tcp -m multiport --dports 80,443 -j f2b-nginx-http-auth
-A INPUT -i eth0 -p udp -m udp --dport 1194 -m comment --comment openvpn-input-rule -j ACCEPT
-A INPUT -p tcp -m multiport --dports 80,443 -j f2b-nginx-http-auth
-A INPUT -i eth0 -p udp -m udp --dport 51820 -m comment --comment wireguard-input-rule -j ACCEPT
-A INPUT -p tcp -m multiport --dports 80,443 -j f2b-nginx-http-auth
-A INPUT -p tcp -m multiport --dports 80,443 -j f2b-nginx-http-auth
-A INPUT -p tcp -m tcp --dport 25 -j DROP
-A INPUT -s 172.104.242.173/32 -j DROP
-A INPUT -s 185.202.2.68/32 -j DROP
-A INPUT -i eth0 -p udp -m udp --dport 51820 -j ACCEPT
-A INPUT -i wg0 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 53 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 853 -j ACCEPT
-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -s 10.8.0.0/24 -p icmp -m icmp --icmp-type 8 -m state --state NEW,RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p udp -m udp --dport 123 -j ACCEPT
-A INPUT -p tcp -m multiport --dports 80,443 -j ACCEPT
-A INPUT -j DROP
-A FORWARD -d 10.8.0.0/24 -i eth0 -o tun0 -m conntrack --ctstate RELATED,ESTABLISHED -m comment --comment openvpn-forward-rule -j ACCEPT
-A FORWARD -s 10.8.0.0/24 -i tun0 -o eth0 -m comment --comment openvpn-forward-rule -j ACCEPT
-A FORWARD -d 10.6.0.0/24 -i eth0 -o wg0 -m conntrack --ctstate RELATED,ESTABLISHED -m comment --comment wireguard-forward-rule -j ACCEPT
-A FORWARD -s 10.6.0.0/24 -i wg0 -o eth0 -m comment --comment wireguard-forward-rule -j ACCEPT
-A FORWARD -i wg0 -o eth0 -j ACCEPT
-A FORWARD -i eth0 -o wg0 -j ACCEPT
-A f2b-nginx-http-auth -s 94.26.113.110/32 -j DROP
-A f2b-nginx-http-auth -s 87.103.245.138/32 -j DROP
-A f2b-nginx-http-auth -s 81.218.45.241/32 -j DROP
-A f2b-nginx-http-auth -s 141.98.10.217/32 -j DROP
-A f2b-nginx-http-auth -s 87.103.245.138/32 -j DROP
-A f2b-nginx-http-auth -s 87.103.245.138/32 -j DROP
-A f2b-nginx-http-auth -s 87.103.245.138/32 -j DROP
-A f2b-nginx-http-auth -j RETURN
-A f2b-nginx-http-auth -j RETURN
-A f2b-nginx-http-auth -j RETURN
-A f2b-nginx-http-auth -j RETURN

sudo iptables -t nat -S : 


-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P POSTROUTING ACCEPT
-P OUTPUT ACCEPT
-A POSTROUTING -s 10.8.0.0/24 -o eth0 -m comment --comment openvpn-nat-rule -j MASQUERADE
-A POSTROUTING -s 10.6.0.0/24 -o eth0 -m comment --comment wireguard-nat-rule -j MASQUERADE
-A POSTROUTING -s 10.8.1.0/24 -o eth0 -j MASQUERADE


no need to worried about clear text ip address, because this is some drop and ban from iptables/f2ban

**Comment by orazioedoardo** [comment]
You need to edit (as root) the following rules file: `/etc/iptables/rules.v4`

> 1) -A INPUT -i eth0 -p udp -m udp --dport 51820 -j ACCEPT

Rule 1 is redundant as you have 2

> 2) -A INPUT -i eth0 -p udp -m udp --dport 51820 -m comment --comment wireguard-input-rule -j ACCEPT

Change eth0 to eth0:0 on 2.

> 3) -A FORWARD -d 10.6.0.0/24 -i eth0 -o wg0 -m conntrack --ctstate RELATED,ESTABLISHED -m comment --comment wireguard-forward-rule -j ACCEPT
> 4) -A FORWARD -s 10.6.0.0/24 -i wg0 -o eth0 -m comment --comment wireguard-forward-rule -j ACCEPT

eth0:0 on 3 and 4

> 5) -A FORWARD -i wg0 -o eth0 -j ACCEPT
> 6) -A FORWARD -i eth0 -o wg0 -j ACCEPT

5 and 6 are redundant as you have 3 and 4

> 7) -A POSTROUTING -s 10.6.0.0/24 -o eth0 -m comment --comment wireguard-nat-rule -j MASQUERADE

eth0:0 on 7

> 8) -A POSTROUTING -s 10.8.1.0/24 -o eth0 -j MASQUERADE

If you intended to write 10.8.0.0/24, then that's redundant too.

As root, update the firewall with `iptables-restore < /etc/iptables/rules.v4`

Update this:

`/etc/pivpn/setupVars.conf -> IPv4dev=eth0:0`

and reconfigure pihole with `pihole -r`

**Comment by bobaxxx** [comment]
Thx i am fixing this and i have some questions : 

i change rules for eth0:0 but can the 2 rules stick together like : 

-A INPUT -i **eth0** -p udp -m udp --dport 51820 -m comment --comment wireguard-input-rule -j ACCEPT
-A INPUT -i **eth0:0** -p udp -m udp --dport 51820 -m comment --comment wireguard-input-rule -j ACCEPT

then : 

-A FORWARD -d 10.6.0.0/24 -i **eth0** -o wg0 -m conntrack --ctstate RELATED,ESTABLISHED -m comment --comment wireguard-forward-rule -j ACCEPT
-A FORWARD -s 10.6.0.0/24 -i wg0 -o **eth0** -m comment --comment wireguard-forward-rule -j ACCEPT
-A FORWARD -d 10.6.0.0/24 -i **eth0:0** -o wg0 -m conntrack --ctstate RELATED,ESTABLISHED -m comment --comment wireguard-forward-rule -j ACCEPT
-A FORWARD -s 10.6.0.0/24 -i wg0 -o **eth0:0** -m comment --comment wireguard-forward-rule -j ACCEPT

and finally : 

-A POSTROUTING -s 10.6.0.0/24 -o **eth0** -m comment --comment wireguard-nat-rule -j MASQUERADE
-A POSTROUTING -s 10.6.0.0/24 -o **eth0:0** -m comment --comment wireguard-nat-rule -j MASQUERADE

My final thought is to switch from the original public ip to the failoverip and doing this in a "second", or maybe as fast as i want

**Comment by orazioedoardo** [comment]
Yes you can have both. This rules tell the system which "packet flow" is allowed through the firewall. If a rule doesn't match the specified packet flow, it will be skipped.

**Comment by bobaxxx** [comment]
thx, this will be better, i just can add some script to quickly change pivpn conf file and pihole conf file

i will tell you if it works

**Comment by orazioedoardo** [comment]
>  just can add some script to quickly change pivpn conf file

The `IPv4dev` line in the pivpn conf file is used by the debug script to check if the firewall rules match the interface used at installation, it's not actually required for the functioning of the VPN.

> and pihole conf file

Wait actually pihole should listen on wg0 and tun0, not on th0 or eth0:0, otherwise you open the server to DNS attacks.

**Comment by bobaxxx** [comment]
Ok so i understand you advise me not to do so with pihole conf file

**Comment by orazioedoardo** [comment]
Check your pihole dashboard. If you have eth0 or wth0:0 listed, you should reconfigure and set wg0 (only allow pihole when using wireguard).

**Comment by bobaxxx** [comment]
pihole by default is listening to eth0

im going to change it to wg0
but when you said "and reconfigure pihole with pihole -r"

should i repair or reconfigure ?

**Comment by orazioedoardo** [comment]
Repair I think

**Comment by bobaxxx** [comment]
i did it, i changed the pivpnHost parameters in the pivpn.conf file too (https://docs.pivpn.io/wireguard/)

pihole is listening to wg0

i noticed by default, when i try to reconfigure pihole (not repair, then i dont finish reconfigure), even if i choose wg0 listening, i only have the choice for the original public ip,but i can change it
when i go further, i only have the original ovh gateway (same ip range as the original public ip)

Im still behind the original public ip on eth0 (no matter what endpoint i use)

**Comment by orazioedoardo** [comment]
No replies in a while, closing...
