### ISSUE TITLE
[Feature Request] Fetch the latest install script if running an outdated version

### ISSUE THREAD

**Issue by TomatoCo** [pivpn/pivpn#1236]
**Is your feature request related to a problem? Please describe.**
I recently had to reinstall pivpn. I used the script I had already downloaded and all of the .conf files I generated had empty AllowedIPs. This caused the conf files to be rejected.

**Describe the solution you'd like**
Some way for the install script to verify that it is the most recent version.

**Describe alternatives you've considered**
A reminder to always get the latest version?

I kinda feel like this is a bug, but it's definitely a bug that only happens in this narrow sequence of events caused by me. I used a script downloaded from before https://github.com/pivpn/pivpn/commit/3ed54bf71db9dcd989370821094ca0dfc9b48749

**Comment by orazioedoardo** [comment]
> I used a script downloaded from before

Seems an edge case to me. It should be easy to solve though: add some lines in the current script that downloads and runs the latest script from github. However it wouldn't work retroactively.

**Comment by orazioedoardo** [comment]
No replies in a while, closing...
