### ISSUE TITLE
How to setup PiVPN client on Raspberry Pi?

### ISSUE THREAD

**Issue by KrisW-Pi** [pivpn/pivpn#1238]
Hi
Thanks for a great job with creating the PiVPN script. It's so helpful for a people like me, beginners in Linux environment.
I have installed and configured PiVPN server on one of my Raspberry Pi (set static local IP, port 1194 UDP opened on router, DNS set with No-Ip). I can connect from outside on my Smartphone and Laptop using OpenVPN app with great speeds. I have tried to connect my Asus Router RT-AC86U using the .ovpn file with no success. I don't know what is stopping the router to connect. 
I have decided to connect my other Raspberry Pi 4 (as a client)  to my current Raspberry Pi server with your script PiVPN installed.
I want to setup the other Raspberry Pi as a WiFi Router with vpn connection running on it.
How do I set up PiVPN Client and connect to the other PiVPN server? Is there such an easy script like yours PiVPN?
Best regards
Kris

**Comment by orazioedoardo** [comment]
> I have tried to connect my Asus Router RT-AC86U using the .ovpn file with no success. I don't know what is stopping the router to connect.

Hard to tell without logs or errors.

> I have decided to connect my other Raspberry Pi 4 (as a client) to my current Raspberry Pi server with your script PiVPN installed.

It's basically like connecting a Linux machine so: https://docs.pivpn.io/openvpn/#linux

> I want to setup the other Raspberry Pi as a WiFi Router with vpn connection running on it.

This is not covered by PiVPN but there are guides online. Usually those let you setup a configuration for a commercial VPN but PiVPN is no different.

**Comment by orazioedoardo** [comment]
No replies in a while, closing...
