### ISSUE TITLE
syntax error in install.sh

### ISSUE THREAD

**Issue by jfavega** [pivpn/pivpn#124]
When using 'curl -L https://install.pivpn.io | bash' you get the following error:

bash: line 746: syntax error near unexpected token `)'
bash: line 746: `    if [ "$ENCRYPT" -ge "4096" ] && whiptail --backtitle "Setup OpenVPN" --title "Diffie-Hellman Parameters" --defaultno --yesno "Generating Diffie-Hellman parameters for a $ENCRYPT-bits key might take a long time on a Raspberry Pi. Do you want to download them? (If you're paranoid, choose 'No')" $r $c)'

**Comment by Esteidinger** [comment]
Still getting the error

**Comment by AriesMOo** [comment]
same here :(
