### ISSUE TITLE
[Support] Block specific clients from accessing local network devices. 

### ISSUE THREAD

**Issue by WaukyTL** [pivpn/pivpn#1244]
## In raising this issue, I confirm the following:

`{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

### Issue

I am trying to figure out a way to block/restrict certain PiVPN (WireGuard) clients from accessing my local devices/network. 
I am running PiHole with PiVPN (WireGuard) on my Raspberry Pi 3B+. Everything works great. My friends and I play this mobile game together and when they are behind my VPN, it skips ads. This feature is very nice. I have allowed certain trusted friends to access my PiVPN as clients so they can benefit from the ad blocking remotely when we are all playing the same game. With that being said, I have noticed that some friends has the ability to see my devices on on my network. I would like to just give 1 or 2 of these clients Internet only access with not LAN access. Is this possible?

### Have you searched for similar issues and solutions?
Yes - I have been searching for the better part of a day on this topic via google, reddit and some FB PiHolePiVPN groups and haven't found anything that lines up with this request. I feel like this may be very simple but I can't figure it out.

### Console output of      `curl -L install.pivpn.io | bash`
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    17  100    17    0     0     62      0 --:--:-- --:--:-- --:--:--    62
100   162  100   162    0     0    235      0 --:--:-- --:--:-- --:--:--  1296
100 83358  100 83358    0     0  86831      0 --:--:-- --:--:-- --:--:-- 86831
:::
::: sudo will be used for the install.
::: Cancel selected. Exiting
```

### Console output of      `pivpn add` or `pivpn add nopass`
```
  Output Here
```

### Console output of      `pivpn debug`
```
::::		PiVPN debug		 ::::
=============================================
::::		Latest commit		 ::::
commit d7771c251418fa443869397d46f93c5b0c197558
Author: 4s3ti <4s3ti@protonmail.com>
Date:   Sat Feb 6 23:04:11 2021 +0100

    Merge branch test into master
    
    fixes #1234
    ci/cd fixes and improvements
=============================================
::::	    Installation settings    	 ::::
PLAT=Raspbian
OSCN=buster
USING_UFW=0
IPv4dev=eth0
dhcpReserv=1
IPv4addr=192.168.0.2/24
IPv4gw=192.168.0.1
install_user=pi
install_home=/home/pi
VPN=wireguard
pivpnPORT=51820
pivpnDNS1=10.6.0.1
pivpnDNS2=
pivpnHOST=REDACTED
INPUT_CHAIN_EDITED=0
FORWARD_CHAIN_EDITED=0
pivpnPROTO=udp
pivpnDEV=wg0
pivpnNET=10.6.0.0
subnetClass=24
ALLOWED_IPS="0.0.0.0/0, ::0/0"
UNATTUPG=1
INSTALLED_PACKAGES=()
=============================================
::::  Server configuration shown below   ::::
[Interface]
PrivateKey = server_priv
Address = 10.6.0.1/24
ListenPort = 51820
### begin TLiPhone ###
[Peer]
PublicKey = TLiPhone_pub
PresharedKey = TLiPhone_psk
AllowedIPs = 10.6.0.2/32
### end TLiPhone ###
### begin TLiPad ###
[Peer]
PublicKey = TLiPad_pub
PresharedKey = TLiPad_psk
AllowedIPs = 10.6.0.3/32
### end TLiPad ###
### begin NBiPhone ###
[Peer]
PublicKey = NBiPhone_pub
PresharedKey = NBiPhone_psk
AllowedIPs = 10.6.0.4/32
### end NBiPhone ###
### begin JBAndroid ###
[Peer]
PublicKey = JBAndroid_pub
PresharedKey = JBAndroid_psk
AllowedIPs = 10.6.0.5/32
### end JBAndroid ###
=============================================
::::  Client configuration shown below   ::::
[Interface]
PrivateKey = TLiPhone_priv
Address = 10.6.0.2/24
DNS = 10.6.0.1

[Peer]
PublicKey = server_pub
PresharedKey = TLiPhone_psk
Endpoint = REDACTED:51820
AllowedIPs = 0.0.0.0/0, ::0/0
=============================================
:::: 	Recursive list of files in	 ::::
::::	[4m/etc/wireguard shown below	 ::::
/etc/wireguard:
configs
keys
wg0.conf

/etc/wireguard/configs:
clients.txt
JBAndroid.conf
NBiPhone.conf
TLiPad.conf
TLiPhone.conf

/etc/wireguard/keys:
JBAndroid_priv
JBAndroid_psk
JBAndroid_pub
NBiPhone_priv
NBiPhone_psk
NBiPhone_pub
server_priv
server_pub
TLiPad_priv
TLiPad_psk
TLiPad_pub
TLiPhone_priv
TLiPhone_psk
TLiPhone_pub
=============================================
::::		Self check		 ::::
:: [OK] IP forwarding is enabled
:: [OK] Iptables MASQUERADE rule set
:: [OK] WireGuard is running
:: [OK] WireGuard is enabled (it will automatically start on reboot)
:: [OK] WireGuard is listening on port 51820/udp
=============================================
:::: Having trouble connecting? Take a look at the FAQ:
:::: https://github.com/pivpn/pivpn/wiki/FAQ
=============================================
:::: WARNING: This script should have automatically masked sensitive       ::::
:::: information, however, still make sure that PrivateKey, PublicKey      ::::
:::: and PresharedKey are masked before reporting an issue. An example key ::::
:::: that you should NOT see in this log looks like this:                  ::::
:::: YIAoJVsdIeyvXfGGDDadHh6AxsMRymZTnnzZoAb9cxRe                          ::::
=============================================
::::		Debug complete		 ::::

```
### Have you taken any steps towards solving your issue?

I've searched PiVPN documentation but can't find anything relating to this specify thing. Maybe it's a feature that hasn't been implemented yet? Or it's simple and I should know already. Either way, I look forward to the reply and thank you for reading.

**Comment by orazioedoardo** [comment]
You can achieve this with a firewall rule, assuming JBAndroid is your friend with IP 10.6.0.5:

```
sudo -s
iptables -I FORWARD -i wg0 -o eth0 -s 10.6.0.5 -d 192.168.0.0/24 -j DROP
iptables-save > /etc/iptables/rules.4
exit
```

Explanation:
```
iptables          ---> tool used to manage the firewall
-I FORWARD        ---> when a data packet goes from wireguard to the local network (and wide internet) through the Pi, it traverses the FORWARD chain, which contains rules that are evaluated in order from first to last. This adds the following rule to the top of the chain so it is the first to be evaluated.
-i wg0            ---> from wireguard interface
-o eth0           ---> to ethernet interface
-s 10.6.0.5       ---> source ip
-d 192.168.0.0/24 ---> destination ip range (your (local network)
-j DROP           ---> discard those data packets
```

**Comment by WaukyTL** [comment]
This worked. Thank you so much for the help. I really appreciate you spending time to answer my questions.

**Comment by zilexa** [comment]
@WaukyTL normally this would also block the IP address of the device running PiHole since it's within the range of 192.168.0.0/24. How did you solve that? 
I noticed in your log your DNS is the Wireguard network server IP (10.6.0.1), that can't be your PiHole right?

**Comment by planetahuevo** [comment]
@orazioedoardo How do you change or revert the Iptables rule? 

Thanks!

**Comment by orazioedoardo** [comment]
@planetahuevo To remove, same steps but use `-D` (delete) instead of `-I`: https://ipset.netfilter.org/iptables.man.html

**Comment by planetahuevo** [comment]
Thanks. Somehow it is not working.
I created an user with 10.6.0.3 and added it to my mobile. 
If I connect with that client, the traffic goes through but it does not block the local ips... 
I want to make sure the block is not on the client (which works fine so far) but on the server. 
Maybe this is not really important, as I am the only one that has the keys for the users... 

Thanks!!

**Comment by orazioedoardo** [comment]
> If I connect with that client, the traffic goes through but it does not block the local ips...

What's the output of `iptables -vnL FORWARD`?

**Comment by planetahuevo** [comment]
`Chain FORWARD (policy ACCEPT 82344 packets, 33M bytes)
 pkts bytes target     prot opt in     out     source               destination
   21  1196 DROP       all  --  wg0    eth0    10.6.0.3             192.168.0.0/24`

**Comment by orazioedoardo** [comment]
Chain pkts is 21 so it is indeed being blocked.

> I expect that to be blocked, but maybe that does not use the eth0 ?

If it is in the range 192.168.0.0/24 it should be blocked.

**Comment by planetahuevo** [comment]
> Is the LAN IP range correct? Do you use ethernet?
Yes. 192.168.0.31 and yes connected by cable to the pi. It is a pi 1B so it is the only cable.

> If it is in the range 192.168.0.0/24 it should be blocked.
I can browse and visit the admin of the pi-hole when connected with the mobile to 4g and using VPN the tunnel.
So it should be blocked but it is not. 
Any way to test live traffic going through iptables?

**Comment by TinCanTech** [comment]
Personally, I would not accept this form of thread hijacking.  
The OP here posted their PiVPN debug log ..

**Comment by 4s3ti** [comment]
Coments blocked. 
Once again @planetahuevo If you have an issue, Post a proper report with popper details! 

Thanks for the warning @TinCanTech
