### ISSUE TITLE
[Support] Bullseye repo no longer necesssary?

### ISSUE THREAD

**Issue by jorgemieec** [pivpn/pivpn#1257]
## In raising this issue, I confirm the following:

`{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

### Issue
I got this:

```
pi@pi2:~ $ sudo apt-cache policy wireguard
wireguard:
  Installed: 1.0.20200827-1
  Candidate: 1.0.20200827-1
  Version table:
 *** 1.0.20200827-1 100
         -1 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf Packages
        100 /var/lib/dpkg/status
     1.0.20200827-1~bpo10+1 500
        500 http://archive.raspberrypi.org/debian buster/main armhf Packages
```

So this means the default Raspberry Pi OS repo supports Wireguard. Since I am abroad, how could I delete the bullseye repo and not interfere with the configuration I have of WG,, so it doesn't ruin anything?

**Comment by orazioedoardo** [comment]
The bullseye repo is here:` /etc/apt/sources.list.d/pivpn-bullseye-repo.list` and a preference file is here `/etc/apt/preferences.d/pivpn-limit-bullseye`.

**Comment by jorgemieec** [comment]
I already checked that. But if I delete those repos, what will happen to my wireguard installation in a future update?

**Comment by orazioedoardo** [comment]
> I already checked that. But if I delete those repos, what will happen to my wireguard installation in a future update?

Well, actually you are right, you should remove and reinstall `wireguard`, `wireguard-tools`, `wireguard-dkms` (so you start using those from the built-in repo). It shouldn't kill the wireguard interface in the process but I wouldn't do it remotely to be extra sure. Maybe install openvpn too or setup ssh as a backup.

**Comment by jorgemieec** [comment]
Ok, thank you for your help. I have a backup Raspberry Pi Model B, I might use that.

**Comment by orazioedoardo** [comment]
There is nothing to change, test branch already skips the repo if wireguard is found within the built-in repo, so I guess I'll close.
