### ISSUE TITLE
I've created a Web UI for PiVPN (WireGuard).

### ISSUE THREAD

**Issue by WeeJeWel** [pivpn/pivpn#1258]
Hi there! 👋🏻

I absolutely love PiVPN and recently have been using WireGuard as well. It's so fast and simple, but it lacked a great UI to manage a server. So I created one!

**Screenshots**

![Screenshot 2021-02-21 at 17 52 04](https://user-images.githubusercontent.com/319873/108635447-bd44bf80-747f-11eb-906c-ef4fd7f43075.png)

![Screenshot 2021-02-21 at 17 45 22](https://user-images.githubusercontent.com/319873/108635432-abfbb300-747f-11eb-9213-9df9dd87d1a1.png)

**Source**

The project can be found here: https://github.com/WeeJeWel/pivpn-web

Note that it doesn't currently support OpenVPN, but if it gets some traction, it shouldn't be hard to implement next to WireGuard.

If you like it, it might be nice to share this somewhere so users can find it. 🚀

**Comment by mwoolweaver** [comment]
any chance this could be done without docker? 

I have been wanting something like this for a long time but don't have much experience with docker.

**Comment by WeeJeWel** [comment]
> any chance this could be done without docker?
> 
> I have been wanting something like this for a long time but don't have much experience with docker.

Sure, just install Node.js and run `npm run serve`. I suggest to use PM2 to keep it running on boot.

**Comment by 4s3ti** [comment]
There are a few projects like this, but unfortunately they end up getting unmaintained ... I wonder if we can have an official one ... however i am not the best a web development ... @orazioedoardo what u think?

**Comment by 4s3ti** [comment]
In the meantime, you can make a PR and add your project here: https://github.com/pivpn/docs

**Comment by WeeJeWel** [comment]
> In the meantime, you can make a PR and add your project here: https://github.com/pivpn/docs

I've created a PR, thank you!

**Comment by orazioedoardo** [comment]
> I wonder if we can/should have an official one ...

I think we should, it would be valuable. @WeeJeWel I have some questions:

1) There is no way around installing Node.js and npm right?
2) Sending commands and authenticating via SSH seems inflexible, what if someone has key authentication only, 2fa or even no ssh at all? Could you run shell commands on the host?
3) Even on a local network, some users might feel uneasy about downloading configurations over HTTP. Maybe the web interface should be served over the wireguard/openvpn interface only, with a plain username/pass indipendent from os credentials.

**Comment by 4s3ti** [comment]
Pi-hole seems to be using this: https://github.com/ColorlibHQ/AdminLTE  

Should we go down the same route?

**Comment by WeeJeWel** [comment]
> 1. There is no way around installing Node.js and npm right?

That's true, it's the language I know best. But for the end-user, I provide a Docker image so it all runs inside of that.

> 2. Sending commands and authenticating via SSH seems inflexible, what if someone has key authentication only, 2fa or even no ssh at all? Could you run shell commands on the host?

Also true. Key auth could be solved using an environment variable and exposing the public key, but how would the front-end look like? You definitely don't want anyone on the LAN being able to log in.

> 3. Even on a local network, some users might feel uneasy about downloading configurations over HTTP. Maybe the web interface should be served over the wireguard/openvpn interface only, with a plain username/pass indipendent from os credentials.

That could be possible but it's another direction. I personally like the 'one tool, one job' mantra. If you want HTTPS, but nginx in front of it. If you want another method of authentication, maybe we can make auth-adapters in the project.

Initially I started using `exec("sudo pivpn ...")` directly on the host, but went with SSH because it allows the project to 1. run in Docker 2. use SSH as auth mechanism instead of inventing my own (and editing config files, which is a pain in the ass for new users) and 3. allowing the project to run on another machine than the PiVPN installation.

**Comment by orazioedoardo** [comment]
> That's true, it's the language I know best. But for the end-user, I provide a Docker image so it all runs inside of that.

I was thinking in terms of footprint (docker + nodejs + npm) make up a lot of packages to install and update. 

> Also true. Key auth could be solved using an environment variable and exposing the public key, but how would the front-end look like? You definitely don't want anyone on the LAN being able to log in.

My idea is:

1) User runs the install script
2) At the end he's given an URL (like http://10.6.0.1/pivpn) with default credentials and an autogenerated VPN config
3) User connects to the VPN
4) User goes to the Web UI
5) User logs in (or creates an account if no default credential are created)

> That could be possible but it's another direction. I personally like the 'one tool, one job' mantra: if you want HTTPS, use nginx in front of it. If you want another method of authentication, maybe we can make auth-adapters in the project.

Yes, however proper HTTPS inside the LAN is probably overly complicated for beginner users, that's why I thought HTTP over VPN only.

> Pi-hole seems to be using this: https://github.com/ColorlibHQ/AdminLTE
> 
> Should we go down the same route?

This would be the lightest, and we could piggyback on the existing web server pihole installs (if found).

**Comment by WeeJeWel** [comment]
> I was thinking in terms of footprint (docker + nodejs + npm) make up a lot of packages to install and update.

Please note that the user doesn't have to install Node.js & npm. They only have to install Docker.

> My idea is:

That would be nice. Personally I don't like creating an account for every service on my pi, but it has upsides as well (users with only ssh keys, being one).

**Comment by WeeJeWel** [comment]
> This would be the lightest, and we could piggyback on the existing web server pihole installs (if found).

That does seem to be front-end only. I'd advice against piggybacking on pi-hole, it creates a major dependency and not everyone wants to use pi-hole.

**Comment by orazioedoardo** [comment]
> I'd advice against piggybacking on pi-hole, it creates a major dependency and not everyone wants to use pi-hole.

Agree, actually I meant to detect and use the web server (lighttpd) if that is installed, not depend on pi-hole itself.

**Comment by WeeJeWel** [comment]
> > I'd advice against piggybacking on pi-hole, it creates a major dependency and not everyone wants to use pi-hole.
> 
> Agree, actually I meant to detect and use the web server (lighttpd) if that is installed, not depend on pi-hole itself.

Hm but what if someone removes pi-hole, how to prevent lighttpd from being removed as well?

Anyway, I'm a strong contender of 'ship your own dependencies', but it's your project! :-)

**Comment by orazioedoardo** [comment]
> Hm but what if someone removes pi-hole, how to prevent lighttpd from being removed as well?

Right, I don't think it's possible, unless pivpn installs lighttpd before pi-hole.

> Anyway, I'm a strong contender of 'ship your own dependencies', but it's your project! :-)

Well, if it was for me, I'd like to reuse existing components to minimize installed software and disk space, however I don't think there is a need to put a web server on front for authentication if docker is setup to bind to 10.6.0.0/24.

@4s3ti What do you think of this setup?

**Comment by 4s3ti** [comment]
Need to give it some it some thought ... 

Agree we should not depend on anyone, when i mentioned pi-hole i mentioned we could sneak it and see how they are handling it. 

using lighttpd might become an issue as it was (and very well) highlighted, considering a lot of pivpn users also use pi-hole. 

Giving the scope of the project, HTTPS even tough it's very appreciated is not really a paramount, if required by more advanced users any reverse-proxy in front of it will take care of it! 

This said ... i believe that anything with the ability to serve web-interface can hold the demand doesn't even need fancy features, we should indeed ensure that the web interface is only accessible internally or trough trough the VPN itself only.


However ....  I want to make sure we offer the best possible and reliable solution!!

**Comment by WeeJeWel** [comment]
FYI PiVPN-Web now support disabling/enabling users 🎉

<img width="797" alt="Screenshot 2021-02-23 at 20 50 33" src="https://user-images.githubusercontent.com/319873/108899574-dfbe1080-7618-11eb-834a-df0d37169749.png">

**Comment by eabase** [comment]
Ooh noo, not docker... :(  
What is the [space overhead](https://stackoverflow.com/questions/26753087/how-to-analyze-disk-usage-of-a-docker-container) for using docker in this case? 

Why are we looking at `lighttpd`? There are probably several dozens of alternative options and variations of that, which would not need any PiHole deps.

https://gist.github.com/willurd/5720255#comment-841915
https://github.com/VaradLanke/https-file-server-python
https://gist.github.com/dergachev/7028596
https://docs.aiohttp.org/en/stable/web_quickstart.html

**Comment by WeeJeWel** [comment]
FYI the total size of PiVPN-Web with Docker is only 123.7MB.

**Comment by WeeJeWel** [comment]
Anyway, a web server is easy. It's just a question of which language you want to write the backend logic in.

**Comment by WeeJeWel** [comment]
Why don't we just show a dialog at the end of the installation process with a few options for UIs?

```
Do you want to use a graphical user interface to manage PiVPN clients?

[x] No
[_] Use PiVPN-Web (Docker, ~150 MB)
[_] ...
```

**Comment by pchristod** [comment]
I like the design and the work you did with this, very impressive!
I don't even have a problem with Docker because I could run this on my Synology NAS with the other Docker Container. However the remote access poses a problem here (like it has been mentioned in one of the earlier comments) due to SSH Key Authentication only. Would love to see something integrated like this out of the box at any point in the future. Imho best option would still be to use a newly created user. I do believe most people wouldn't have a problem with that. Bonus is added security.

**Comment by orazioedoardo** [comment]
> Why don't we just show a dialog at the end of the installation process with a few options for UIs?

Sure, It would work that way.

**Comment by DerDanilo** [comment]
I absolutely love this simple web UI!

We should get it integrated, be it with docker or without docker. Then again we would also need to add some sort of reverse proxy (if not provided by the webui itself) that allows SSL/TLS encryption for the frontend. 

I actually wrote a simple Ansible role to deploy pivpn and pivpn-web. The Nginx Proxy Config looks like this:

```
{{ansible_managed|comment}}

{% if wireguard_pivpn_web_nginx_redirect_to_https|bool %}
server {
    listen              {{ wireguard_pivpn_web_nginx_port_http }};
    server_name         _;
    server_tokens       off;

    location / {
           return 301 https://\$host:{{ wireguard_pivpn_web_nginx_port_https }}\$request_uri; # enforce https
    }
}
{% endif %}

server {
    listen                  {{ wireguard_pivpn_web_nginx_port_https }} http2 ssl;
    server_name             _;
    server_tokens           off;
    ssl_certificate         {{ wireguard_pivpn_web_nginx_cert }};
    ssl_certificate_key     {{ wireguard_pivpn_web_nginx_key }};

    # intermediate configuration
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;
    ssl_session_timeout 1d;
    ssl_session_cache shared:MozSSL:10m;  # about 40000 sessions
    ssl_session_tickets off;
    ssl_dhparam /etc/ssl/dhparam.pem;

    location / {
        proxy_pass http://localhost:{{ wireguard_pivpn_web_docker_port }};
        proxy_set_header Host $host;
        proxy_http_version 1.1;
    }
}


```

**Comment by 4s3ti** [comment]
> We should get it integrated, be it with docker or without docker. Then again we would also need to add some sort of reverse proxy (if not provided by the webui itself) that allows SSL/TLS encryption for the frontend.

We should not provide this!

Its true we should encrypt traffic and use SSL/TLS all the time even internally ... however in this particular case, 
I do believe we should provide the web-ui, however it should be up to the user to put SSL/TLS on it by applying whatever solution it considers best for its use case! 

This web SHOULD be running on a closed network therefore its not possible to have CA's like letsencrypt to sign the certificate and causing browsers to halt the access to the page therefore bringing more open issues like: "I can't open the interface"

**Comment by DerDanilo** [comment]
> This web SHOULD be running on a closed network therefore its not possible to have CA's like letsencrypt to sign the certificate and causing browsers to halt the access to the page therefore bringing more open issues like: "I can't open the interface"

Okay, this makes sense. 
Would it be okay to give an simple example in a README/Docs how this could be done? Maybe even with a self signed cert which is still better than unencrypted at all. Example means that we do not provide the solution but give a hint at how it could look like. I don't need this info but maybe other do.

**Comment by WeeJeWel** [comment]
> > Would it be okay to give an simple example in a README/Docs how this could be done? Maybe even with a self signed cert which is still better than unencrypted at all. Example means that we do not provide the solution but give a hint at how it could look like. I don't need this info but maybe other do.
> 
> If you could manage to make wubUI only accessable over the VPN then would you really _**need**_ https?

That makes it harder to setup the first user though.

**Comment by 4s3ti** [comment]
well first things first ... @WeeJeWel webui only works with wireguard ... 

I don't mind integrating it and making it official .. but if we are going down that path ... let's not get too much ahead in features and and what not! 

the first issue that needs to be solved is OpenVPN support, as i see it currently does not suport OpenVPN so it cannot be integrated as part of PiVPN Project or supported as the official recommended ui, so i'd say that is the first thing to endorse if @WeeJeWel is up to the trouble.

**Comment by 4s3ti** [comment]
> > Why don't we just show a dialog at the end of the installation process with a few options for UIs?
> 
> Sure, It would work that way.

think this would not be easily maintainable ... believe we should provide a single ui, either maintained by us, or a separate project that we define as our go to web interface and we help maintaining

**Comment by WeeJeWel** [comment]
> the first issue that needs to be solved is OpenVPN support, as i see it currently does not suport OpenVPN so it cannot be integrated as part of PiVPN Project or supported as the official recommended ui, so i'd say that is the first thing to endorse if @WeeJeWel is up to the trouble.

I’ll just be honest. I have no interest in adding support for OpenVPN. In my view it’s an old protocol with no advantages over WireGuard, and I’d actually recommend you remove it from PiVPN altogether as soon as you think is reasonable.

**Comment by DerDanilo** [comment]
> I’ll just be honest. I have no interest in adding support for OpenVPN. In my view it’s an old protocol with no advantages over WireGuard, and I’d actually recommend you remove it from PiVPN altogether as soon as you think is reasonable.

I agree but maybe if the community still uses it someone else could add support for it. Saying this without know the code(!): It doesn't seem much work to add support for OpenVPN though since OpenVPN also has a script with commands that can be executed just like with wireguard.
Is there someone else in the community appart from @WeeJeWel that would like to contribute to get OpenVPN to the WebUI? (I don't since I don't use OVPN). Purely asking for the community here.

**Comment by WeeJeWel** [comment]
FYI I’ve made the code in such a way that adding OpenVPN support should be very straightforward.

**Comment by orazioedoardo** [comment]
> think this would not be easily maintainable ... believe we should provide a single ui, either maintained by us, or a separate project that we define as our go to web interface and we help maintaining

I'm not sure what you have implied from my previous comment, however I'm ok with an option to install a single UI.

> I’d actually recommend you remove it from PiVPN altogether as soon as you think is reasonable.

I don't think we will remove OpenVPN anytime soon, It is still very useful due to its many knobs, it's supported on many routers too and since it's an userspace daemon it is less likely to break like the wireguard module does sometimes.

**Comment by flipptx** [comment]
was there ever a non docker solution for this? with a guide?

**Comment by 4s3ti** [comment]
Closing this Topic, seems that @WeeJeWel archived this project and moved to a different project without PiVPN integration at all
https://github.com/WeeJeWel/pivpn-web
