### ISSUE TITLE
[Support] OpenVPN connection times out. tcpdump reports no packets

### ISSUE THREAD

**Issue by vaio2005** [pivpn/pivpn#1259]
## In raising this issue, I confirm the following:

`{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

As the titles say, my raspberry pi is not receiving UDP packets. I have followed the FAQs, and at the end it says to open an issue, so here I'm. 

### Have you searched for similar issues and solutions?
 Yes

### Console output of      `pivpn debug`
```

=============================================
::::            Self check               ::::
/etc/pivpn/openvpn/setupVars.conf: line 7: 192.168.1.100/24: No such file or directory
:: [OK] IP forwarding is enabled
:: [OK] Iptables MASQUERADE rule set
:: [OK] Iptables FORWARD rule set
:: [OK] OpenVPN is running
:: [OK] OpenVPN is enabled (it will automatically start on reboot)
:: [OK] OpenVPN is listening on port 1194/udp
=============================================
:::: Having trouble connecting? Take a look at the FAQ:
:::: https://github.com/pivpn/pivpn/wiki/FAQ
=============================================
::::      Snippet of the server log      ::::
Feb 22 08:48:01 raspberrypi ovpn-server[25527]: library versions: OpenSSL 1.1.1d  10 Sep 2019, LZO 2.10
Feb 22 08:48:01 raspberrypi ovpn-server[25527]: NOTE: your local LAN uses the extremely common subnet address 192.168.0.x or 192.168.1.x.  Be aware that this might create routing conflicts if you connect to the VPN server from public locations such as internet cafes that use the same subnet.
Feb 22 08:48:01 raspberrypi ovpn-server[25527]: ECDH curve prime256v1 added
Feb 22 08:48:01 raspberrypi ovpn-server[25527]: Outgoing Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Feb 22 08:48:01 raspberrypi ovpn-server[25527]: Outgoing Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Feb 22 08:48:01 raspberrypi ovpn-server[25527]: Incoming Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Feb 22 08:48:01 raspberrypi ovpn-server[25527]: Incoming Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Feb 22 08:48:01 raspberrypi ovpn-server[25527]: TUN/TAP device tun0 opened
Feb 22 08:48:01 raspberrypi ovpn-server[25527]: TUN/TAP TX queue length set to 100
Feb 22 08:48:01 raspberrypi ovpn-server[25527]: /sbin/ip link set dev tun0 up mtu 1500
Feb 22 08:48:01 raspberrypi ovpn-server[25527]: /sbin/ip addr add dev tun0 10.8.0.1/24 broadcast 10.8.0.255
Feb 22 08:48:01 raspberrypi ovpn-server[25527]: Could not determine IPv4/IPv6 protocol. Using AF_INET
Feb 22 08:48:01 raspberrypi ovpn-server[25527]: Socket Buffers: R=[180224->180224] S=[180224->180224]
Feb 22 08:48:01 raspberrypi ovpn-server[25527]: UDPv4 link local (bound): [AF_INET][undef]:1194
Feb 22 08:48:01 raspberrypi ovpn-server[25527]: UDPv4 link remote: [AF_UNSPEC]
Feb 22 08:48:01 raspberrypi ovpn-server[25527]: GID set to openvpn
Feb 22 08:48:01 raspberrypi ovpn-server[25527]: UID set to openvpn
Feb 22 08:48:01 raspberrypi ovpn-server[25527]: MULTI: multi_init called, r=256 v=256
Feb 22 08:48:01 raspberrypi ovpn-server[25527]: IFCONFIG POOL: base=10.8.0.2 size=252, ipv6=0
Feb 22 08:48:01 raspberrypi ovpn-server[25527]: Initialization Sequence Completed
=============================================
::::            Debug complete           ::::
:::
::: Debug output completed above.
::: Copy saved to /tmp/debug.log
:::

```
### Have you taken any steps towards solving your issue?
I tried opening the ports with iptables (here follows output of ```sudo iptables -S``` and ```sudo iptables -t nat -S```. Since I've also rules with iptables-legacy, I'm adding the output of that too.)
```
sudo iptables -S

-P INPUT ACCEPT
-P FORWARD DROP
-P OUTPUT ACCEPT
-N DOCKER
-N DOCKER-ISOLATION-STAGE-1
-N DOCKER-USER
-N DOCKER-ISOLATION-STAGE-2
-A FORWARD -j DOCKER-USER
-A FORWARD -j DOCKER-ISOLATION-STAGE-1
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -o docker0 -j DOCKER
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
-A FORWARD -i docker0 -o docker0 -j ACCEPT
-A FORWARD -d 10.8.0.0/24 -i enxb827eb287663 -o tun0 -m conntrack --ctstate RELATED,ESTABLISHED -m comment --comment openvpn-forward-rule -j ACCEPT
-A FORWARD -s 10.8.0.0/24 -i tun0 -o enxb827eb287663 -m comment --comment openvpn-forward-rule -j ACCEPT
-A DOCKER -d 172.17.0.2/32 ! -i docker0 -o docker0 -p tcp -m tcp --dport 9000 -j ACCEPT
-A DOCKER -d 172.17.0.2/32 ! -i docker0 -o docker0 -p tcp -m tcp --dport 8000 -j ACCEPT
-A DOCKER -d 172.17.0.3/32 ! -i docker0 -o docker0 -p tcp -m tcp --dport 8443 -j ACCEPT
-A DOCKER-ISOLATION-STAGE-1 -i docker0 ! -o docker0 -j DOCKER-ISOLATION-STAGE-2
-A DOCKER-ISOLATION-STAGE-1 -j RETURN
-A DOCKER-USER -j RETURN
-A DOCKER-ISOLATION-STAGE-2 -o docker0 -j DROP
-A DOCKER-ISOLATION-STAGE-2 -j RETURN
# Warning: iptables-legacy tables present, use iptables-legacy to see them

sudo iptables -t nat -S

-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P POSTROUTING ACCEPT
-P OUTPUT ACCEPT
-N DOCKER
-A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
-A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE
-A POSTROUTING -s 10.8.0.0/24 -o enxb827eb287663 -m comment --comment openvpn-nat-rule -j MASQUERADE
-A POSTROUTING -s 172.17.0.2/32 -d 172.17.0.2/32 -p tcp -m tcp --dport 9000 -j MASQUERADE
-A POSTROUTING -s 172.17.0.2/32 -d 172.17.0.2/32 -p tcp -m tcp --dport 8000 -j MASQUERADE
-A POSTROUTING -s 172.17.0.3/32 -d 172.17.0.3/32 -p tcp -m tcp --dport 8443 -j MASQUERADE
-A OUTPUT ! -d 127.0.0.0/8 -m addrtype --dst-type LOCAL -j DOCKER
-A DOCKER -i docker0 -j RETURN
-A DOCKER ! -i docker0 -p tcp -m tcp --dport 9001 -j DNAT --to-destination 172.17.0.2:9000
-A DOCKER ! -i docker0 -p tcp -m tcp --dport 8000 -j DNAT --to-destination 172.17.0.2:8000
-A DOCKER ! -i docker0 -p tcp -m tcp --dport 8080 -j DNAT --to-destination 172.17.0.3:8443
# Warning: iptables-legacy tables present, use iptables-legacy to see them


LEGACY iptables -s

-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
-A INPUT -p udp -m udp --dport 1194 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 1194 -j ACCEPT

iptables-legacy -t nat -S

-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT
```
EDIT:
I think that I port forwarded right, as online udp port testers say "OPEN/FILTERED". 
I also added a rule with `sudo iptables -A INPUT -p udp -m udp --dport 1194 -j ACCEPT`

**Comment by orazioedoardo** [comment]
Your setupVars.conf file might be corrupted somehow
> /etc/pivpn/openvpn/setupVars.conf: line 7: 192.168.1.100/24: No such file or directory

Please post the full `pivpn debug`

**Comment by vaio2005** [comment]
`
::: Generating Debug Output
/etc/pivpn/openvpn/setupVars.conf: line 7: 192.168.1.100/24: No such file or directory
::::            PiVPN debug              ::::
=============================================
::::            Latest commit            ::::
commit d7771c251418fa443869397d46f93c5b0c197558
Author: 4s3ti <4s3ti@protonmail.com>
Date:   Sat Feb 6 23:04:11 2021 +0100

    Merge branch test into master

    fixes #1234
    ci/cd fixes and improvements
=============================================
::::        Installation settings        ::::
PLAT=Raspbian
OSCN=buster
USING_UFW=0
IPv4dev=enxb827eb287663
dhcpReserv=1
IPv4addr=192.168.1.50/24
192.168.1.100/24
IPv4gw=192.168.1.254
install_user=pi
install_home=/home/pi
VPN=openvpn
pivpnPROTO=udp
pivpnPORT=1194
pivpnDNS1=10.8.0.1
pivpnDNS2=
pivpnSEARCHDOMAIN=
pivpnHOST=REDACTED
TWO_POINT_FOUR=1
pivpnENCRYPT=256
USE_PREDEFINED_DH_PARAM=
INPUT_CHAIN_EDITED=0
FORWARD_CHAIN_EDITED=1
pivpnDEV=tun0
pivpnNET=10.8.0.0
subnetClass=24
ALLOWED_IPS=""
UNATTUPG=1
INSTALLED_PACKAGES=()
HELP_SHOWN=1
=============================================
::::  Server configuration shown below   ::::
dev tun
proto udp
port 1194
ca /etc/openvpn/easy-rsa/pki/ca.crt
cert /etc/openvpn/easy-rsa/pki/issued/raspberrypi_6bebfab1-8d5b-4f5f-b811-083347e7b7d0.crt
key /etc/openvpn/easy-rsa/pki/private/raspberrypi_6bebfab1-8d5b-4f5f-b811-083347e7b7d0.key
dh none
ecdh-curve prime256v1
topology subnet
server 10.8.0.0 255.255.255.0
# Set your primary domain name server address for clients
push "dhcp-option DNS 10.8.0.1"
push "block-outside-dns"
# Override the Client default gateway by using 0.0.0.0/1 and
# 128.0.0.0/1 rather than 0.0.0.0/0. This has the benefit of
# overriding but not wiping out the original default gateway.
push "redirect-gateway def1"
client-to-client
client-config-dir /etc/openvpn/ccd
keepalive 15 120
remote-cert-tls client
tls-version-min 1.2
tls-crypt /etc/openvpn/easy-rsa/pki/ta.key
cipher AES-256-CBC
auth SHA256
user openvpn
group openvpn
persist-key
persist-tun
crl-verify /etc/openvpn/crl.pem
status /var/log/openvpn-status.log 20
status-version 3
syslog
verb 3
#DuplicateCNs allow access control on a less-granular, per user basis.
#Remove # if you will manage access by user instead of device.
#duplicate-cn
# Generated for use by PiVPN.io
=============================================
::::  Client template file shown below   ::::
client
dev tun
proto udp
remote REDACTED 1194
resolv-retry infinite
nobind
remote-cert-tls server
tls-version-min 1.2
verify-x509-name raspberrypi_6bebfab1-8d5b-4f5f-b811-083347e7b7d0 name
cipher AES-256-CBC
auth SHA256
auth-nocache
verb 3
=============================================
::::    Recursive list of files in       ::::
::: /etc/openvpn/easy-rsa/pki shows below :::
/etc/openvpn/easy-rsa/pki/:
Default.txt
ca.crt
crl.pem
ecparams
index.txt
index.txt.attr
index.txt.attr.old
index.txt.old
issued
openssl-easyrsa.cnf
private
renewed
revoked
rpi.ovpn
safessl-easyrsa.cnf
serial
serial.old
ta.key

/etc/openvpn/easy-rsa/pki/ecparams:
prime256v1.pem

/etc/openvpn/easy-rsa/pki/issued:
raspberrypi_6bebfab1-8d5b-4f5f-b811-083347e7b7d0.crt
rpi.crt

/etc/openvpn/easy-rsa/pki/private:
ca.key
raspberrypi_6bebfab1-8d5b-4f5f-b811-083347e7b7d0.key
rpi.key

/etc/openvpn/easy-rsa/pki/renewed:
private_by_serial
reqs_by_serial

/etc/openvpn/easy-rsa/pki/renewed/private_by_serial:

/etc/openvpn/easy-rsa/pki/renewed/reqs_by_serial:

/etc/openvpn/easy-rsa/pki/revoked:
private_by_serial
reqs_by_serial

/etc/openvpn/easy-rsa/pki/revoked/private_by_serial:

/etc/openvpn/easy-rsa/pki/revoked/reqs_by_serial:
=============================================
::::            Self check               ::::
/etc/pivpn/openvpn/setupVars.conf: line 7: 192.168.1.100/24: No such file or directory
:: [OK] IP forwarding is enabled
:: [OK] Iptables MASQUERADE rule set
:: [OK] Iptables FORWARD rule set
:: [OK] OpenVPN is running
:: [OK] OpenVPN is enabled (it will automatically start on reboot)
:: [OK] OpenVPN is listening on port 1194/udp
=============================================
:::: Having trouble connecting? Take a look at the FAQ:
:::: https://github.com/pivpn/pivpn/wiki/FAQ
=============================================
::::      Snippet of the server log      ::::
Feb 22 09:42:40 raspberrypi ovpn-server[25527]: 10.212.54.248:41951 tls-crypt unwrap error: packet replay
Feb 22 09:42:40 raspberrypi ovpn-server[25527]: 10.212.54.248:41951 TLS Error: tls-crypt unwrapping failed from [AF_INET]10.212.54.248:41951
Feb 22 09:42:41 raspberrypi ovpn-server[25527]: 10.212.54.248:41951 tls-crypt unwrap error: bad packet ID (may be a replay): [ #1 / time = (1613983356) Mon Feb 22 09:42:36 2021 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 22 09:42:41 raspberrypi ovpn-server[25527]: 10.212.54.248:41951 tls-crypt unwrap error: packet replay
Feb 22 09:42:41 raspberrypi ovpn-server[25527]: 10.212.54.248:41951 TLS Error: tls-crypt unwrapping failed from [AF_INET]10.212.54.248:41951
Feb 22 09:42:42 raspberrypi ovpn-server[25527]: 10.212.54.248:41951 tls-crypt unwrap error: bad packet ID (may be a replay): [ #1 / time = (1613983356) Mon Feb 22 09:42:36 2021 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 22 09:42:42 raspberrypi ovpn-server[25527]: 10.212.54.248:41951 tls-crypt unwrap error: packet replay
Feb 22 09:42:42 raspberrypi ovpn-server[25527]: 10.212.54.248:41951 TLS Error: tls-crypt unwrapping failed from [AF_INET]10.212.54.248:41951
Feb 22 09:42:43 raspberrypi ovpn-server[25527]: 10.212.54.248:41951 tls-crypt unwrap error: bad packet ID (may be a replay): [ #1 / time = (1613983356) Mon Feb 22 09:42:36 2021 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 22 09:42:43 raspberrypi ovpn-server[25527]: 10.212.54.248:41951 tls-crypt unwrap error: packet replay
Feb 22 09:42:43 raspberrypi ovpn-server[25527]: 10.212.54.248:41951 TLS Error: tls-crypt unwrapping failed from [AF_INET]10.212.54.248:41951
Feb 22 09:43:37 raspberrypi ovpn-server[25527]: 10.212.54.248:41951 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Feb 22 09:43:37 raspberrypi ovpn-server[25527]: 10.212.54.248:41951 TLS Error: TLS handshake failed
Feb 22 09:43:37 raspberrypi ovpn-server[25527]: 10.212.54.248:41951 SIGUSR1[soft,tls-error] received, client-instance restarting
Feb 22 09:45:36 raspberrypi ovpn-server[25527]: rpi/10.212.54.248:1025 [rpi] Inactivity timeout (--ping-restart), restarting
Feb 22 09:45:36 raspberrypi ovpn-server[25527]: rpi/10.212.54.248:1025 SIGUSR1[soft,ping-restart] received, client-instance restarting
Feb 22 10:10:16 raspberrypi ovpn-server[25527]: tls-crypt unwrap error: packet too short
Feb 22 10:10:16 raspberrypi ovpn-server[25527]: TLS Error: tls-crypt unwrapping failed from [AF_INET]REDACTED:60031
Feb 22 10:44:46 raspberrypi ovpn-server[25527]: tls-crypt unwrap error: packet too short
Feb 22 10:44:46 raspberrypi ovpn-server[25527]: TLS Error: tls-crypt unwrapping failed from [AF_INET]REDACTED:38171
=============================================
::::            Debug complete           ::::
:::
::: Debug output completed above.
::: Copy saved to /tmp/debug.log
:::
` It appears that the file is missing, however I can open it. (nano /etc/pivpn/openvpn/setupVars.conf) What should I do?

**Comment by vaio2005** [comment]
Ok, this is strange a lot.
It wasn't working, I did the debug and now I can connect to it. However, I cannot connect to the internet (`DNS_PROBE_FINISHED_NO_INTERNET`). I'm using pihole, if it can be an issue.

**Comment by orazioedoardo** [comment]
You have some docker rules in the way, let's give pivpn rules the highest priority (remove and add back)

```
sudo -i
iptables -D FORWARD -d 10.8.0.0/24 -i enxb827eb287663 -o tun0 -m conntrack --ctstate RELATED,ESTABLISHED -m comment --comment openvpn-forward-rule -j ACCEPT
iptables -D FORWARD -s 10.8.0.0/24 -i tun0 -o enxb827eb287663 -m comment --comment openvpn-forward-rule -j ACCEPT
iptables -t nat -D POSTROUTING -s 10.8.0.0/24 -o enxb827eb287663 -m comment --comment openvpn-nat-rule -j MASQUERADE

iptables -I 1 FORWARD -d 10.8.0.0/24 -i enxb827eb287663 -o tun0 -m conntrack --ctstate RELATED,ESTABLISHED -m comment --comment openvpn-forward-rule -j ACCEPT
iptables -I 2 FORWARD -s 10.8.0.0/24 -i tun0 -o enxb827eb287663 -m comment --comment openvpn-forward-rule -j ACCEPT
iptables -t nat -I POSTROUTING -s 10.8.0.0/24 -o enxb827eb287663 -m comment --comment openvpn-nat-rule -j MASQUERADE

iptables-save > /etc/iptables/rules.v4
exit
```
> It appears that the file is missing, however I can open it. (nano /etc/pivpn/openvpn/setupVars.conf) What should I do?

You have this extraneous line `192.168.1.100/24` after `IPv4addr=[...]`. You only have one line like this `IPv4addr=192.168.1.50/24` with the actual IP of the raspberry pi.

**Comment by vaio2005** [comment]
The actual ip of the RPI is 192.168.1.100, the other one (192.168.1.50) is assigned automatically by the router, (idk why). I've done the command for the rules, but I still don't have internet access. (I restarted the rpi to make sure the changes were fully applied)

**Comment by orazioedoardo** [comment]
Can browser local devices by IP? Also let's check the iptables output again.

**Comment by vaio2005** [comment]
Yes I can access the pihole webserver by going to 10.8.0.1. 
this is the output of iptables -S
```-P INPUT ACCEPT
-P FORWARD DROP
-P OUTPUT ACCEPT
-N DOCKER
-N DOCKER-ISOLATION-STAGE-1
-N DOCKER-USER
-N DOCKER-ISOLATION-STAGE-2
-A FORWARD -j DOCKER-USER
-A FORWARD -j DOCKER-ISOLATION-STAGE-1
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -o docker0 -j DOCKER
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
-A FORWARD -i docker0 -o docker0 -j ACCEPT
-A FORWARD -d 10.8.0.0/24 -i enxb827eb287663 -o tun0 -m conntrack --ctstate RELATED,ESTABLISHED -m comment --comment openvpn-forward-rule -j ACCEPT
-A FORWARD -s 10.8.0.0/24 -i tun0 -o enxb827eb287663 -m comment --comment openvpn-forward-rule -j ACCEPT
-A DOCKER -d 172.17.0.2/32 ! -i docker0 -o docker0 -p tcp -m tcp --dport 9000 -j ACCEPT
-A DOCKER -d 172.17.0.2/32 ! -i docker0 -o docker0 -p tcp -m tcp --dport 8000 -j ACCEPT
-A DOCKER -d 172.17.0.3/32 ! -i docker0 -o docker0 -p tcp -m tcp --dport 8443 -j ACCEPT
-A DOCKER-ISOLATION-STAGE-1 -i docker0 ! -o docker0 -j DOCKER-ISOLATION-STAGE-2
-A DOCKER-ISOLATION-STAGE-1 -j RETURN
-A DOCKER-USER -j RETURN
-A DOCKER-ISOLATION-STAGE-2 -o docker0 -j DROP
-A DOCKER-ISOLATION-STAGE-2 -j RETURN
```

**Comment by orazioedoardo** [comment]
What about accessing the router web interface? I assume it has one at 192.168.1.254.

**Comment by vaio2005** [comment]
Yes, it's the one at 192.168.1.254. And yes, I can access it.

**Comment by vaio2005** [comment]
Also, after some time that the VPN is idle (not active traffic), it gets disconnected and doesn't reconnect.

**Comment by orazioedoardo** [comment]
It could be DNS then, run `pihole -a -i local` to tell pihole to listen to all local interfaces (LAN + VPN)

**Comment by vaio2005** [comment]
It works now, but it's super slow, even compared to the slowest lte connection. Also, sometimes it just crashes.

**Comment by orazioedoardo** [comment]
What's your home internet speed, both download and upload speed?

**Comment by vaio2005** [comment]
where the vpn is 50mb down 5 up
where vpn used 100 down 20 up

**Comment by orazioedoardo** [comment]
This means you can get up to 5 mbps down/up when using the VPN.

**Comment by vaio2005** [comment]
I know that, the thing is that pages don't even load correctly. I guess it's just bandwith then. Thanks for the help. (Penso tu sia italiano, grazie mille)

**Comment by orazioedoardo** [comment]
Yes I'm italian too. If pages don't load correctly, you can try this: https://github.com/pivpn/pivpn/issues/54 (you need to restart openvpn to apply changes `sudo systemctl restart openvpn`). Also see mentioned issues below on that page.
