### ISSUE TITLE
Unknown OpenVPN event occurred : Transport error on (my VPN ip address): NETWORK_RECVERROR 

### ISSUE THREAD

**Issue by bluezebra2** [pivpn/pivpn#126]
I am able to connect to my school internet but when I go to work I get the issue listed above (Unknown OpenVPN event occurred : Transport error on [my VPN ip address]: NETWORK_RECV_ERROR), I am assuming there is a dpi blocker or something. Any suggestions to remedy this? I can provide any other additional information if needed.

**Comment by redfast00** [comment]
Yes, this probably means they are blocking your IP address or doing deep packet inspection. (just a little note: if they block it, they probably don't want you visiting the blocked services. Please don't get fired)

**Comment by bluezebra2** [comment]
Thanks for your concern but I just want to be able to check bank account and other sensitive information like that with out people snooping in on my stuff ( ive had issues with this in the past). I go to two schools also and one of my schools has done the same thing. Is there anyway around this whole issue?

**Comment by redfast00** [comment]
I'm sorry, but your probably out of luck with OpenVPN. Have you tried some of the solutions offered by [Streisand](https://github.com/jlund/streisand)?

**Comment by bluezebra2** [comment]
I never heard of Streisand I'll take a look

**Comment by redfast00** [comment]
Closing this since this is no longer OpenVPN related
