### ISSUE TITLE
[Support] <Error sudo ./openvpn-install.sh>

### ISSUE THREAD

**Issue by ro0TuX777** [pivpn/pivpn#1260]
## In raising this issue, I confirm the following:

`{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

### Issue
attempting to sudo ./openvpn-install.s on a Raspberry Pi 4 with Kali 2020.4 32 bit OS.
 hostnamectl
   Static hostname: kali
         Icon name: computer
        Machine ID: 315928cc6d65415aab45a9abd81a6b01
           Boot ID: 6e756a4e1f5e4774bcf9ce2c023c7fe0
  Operating System: Kali GNU/Linux Rolling
            Kernel: Linux 4.19.127-Re4son-v7l+
      Architecture: arm
### Have you searched for similar issues and solutions?
    (yes/no / which issues?)
Yes, however there are no returned searches when key words Kali + Raspberry are used

### Console output of      `curl -L install.pivpn.io | bash`
```
  Debian 9 or higher is required to use this installer.
This version of Debian is too old and unsupported.
```

### Console output of      `pivpn add` or `pivpn add nopass`
```
  Output Here
```

### Console output of      `pivpn debug`
```
 pivpn: command not found (because installation fails)
```
### Have you taken any steps towards solving your issue?
```
Followed installation instructions found online, youtube videos
```

**Comment by 4s3ti** [comment]
Hi, I am not really sure what you are really trying to achieve and what documentation you have seen.. but certainly was not ours! 

Kali is not supported, and not at all recommended for this, 

Please read the documentation at https://docs.pivpn.io

Closing.
