### ISSUE TITLE
[BUG] unable to clone the repository

### ISSUE THREAD

**Issue by l0u1sg** [pivpn/pivpn#1263]
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting *is* directly related to the pivpn installer script.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

**Describe the bug**
The script can't clone the repository, and I can't either.

**To Reproduce**
1. sudo  curl -L https://install.pivpn.io | bash 
2. Click Yes
3. Select pi user

**Expected behavior**
I was waiting for the script to clone the repo and access it.

**Screenshots**
![image](https://user-images.githubusercontent.com/46707587/109396077-2325c100-7930-11eb-8ed4-f96963301143.png)

**Desktop (please complete the following information):**
 - VPN Protocol : None
 - OS: Raspberry OS

**Additional context**
I tried to launch it directly on the sudo account but nothing helped. I also tried to manually clone the repo in the same folder, the terminal shows me that the clone is running for 1 second. Then when I do the ls command in the folder, nothing is displayed.

**Comment by orazioedoardo** [comment]
What's the output of `sudo git clone https://github.com/pivpn/pivpn.git /usr/local/bin/pivpn` and `which git`?

**Comment by orazioedoardo** [comment]
No responses in a while, closing...
