### ISSUE TITLE
[BUG] Improper IP Address after subnetclass change

### ISSUE THREAD

**Issue by Matt-L-KZ7MFL** [pivpn/pivpn#1267]
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting *is* directly related to the pivpn installer script.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

**Describe the bug**
After changing the pivpnNET to 10.0.5.16 and subnetClass to 28 it should produce IP's between 10.0.5.17-30. Instead it produces an improper IP of 10.0.5..2/28. I have also changed the wg0.conf file to 10.0.5.16/28.

**To Reproduce**
1. Install PiVPN normally using Pi-Hole and WireGuard.
2. Edit the wg0.conf file to address = 10.0.5.16/28
3. Edit setupVars.conf to match the included file.
4. Restarted system.
5. ran pivpn -a named TEST.
6. Check /home/pi/configs/TEST.conf for IP address.

Side Note: after changing numerous files that record the client configured IP to 10.0.5.17 I can prove that PiVPN/WireGuard work as intended. 

EDIT: I should mention i'm trying to get piVPN to work in the 10.0.5.16/28 subnet which has addresses from 10.0.5.16-30. Not the 10.0.5.0/28 subnet which has addresses from 10.0.5.0-15.

**Comment by orazioedoardo** [comment]
`pivpnNET` should be `10.0.5.0` with 0 at as the least significant octet. Also you need to update `/etc/iptables/rules.v4`

**Comment by orazioedoardo** [comment]
I've removed your log because it contained an actual configuration. You can send `pivpn debug` as text instead of attachment.

**Comment by Matt-L-KZ7MFL** [comment]
> `pivpnNET` should be `10.0.5.0` with 0 at as the least significant octet. Also you need to update `/etc/iptables/rules.v4`

When I change the pivpnNET to 10.0.5.0 then it gives me IP's in the 10.0.5.1-15 range when i'm looking to get IP's in the 10.0.5.16-30 range (10.0.5.16/28).

**Comment by orazioedoardo** [comment]
Well actually you can't do it because the script that creates configs starts counting at 1. You can modify the makeCONF.sh script.

**Comment by Matt-L-KZ7MFL** [comment]
I would suggest changing the script to start at what ever number is the last octet of the pivpnNET that way it can account for different subnet masks.

**Comment by TinCanTech** [comment]
Please excuse.

**_Said the Actress to the Bishop_**:

- _If you have a verified, peer reviewed and properly formatted pull request ..
 then I got the test repo to merge it with_ .. :kiss:

**Comment by DerDanilo** [comment]
While I would welcome a patch for this. @Matt-L-KZ7MFL Are you planning to contribute or can we close this issue?

**Comment by 4s3ti** [comment]
No need to close, can stay open if anyone wants to work on it. PR are welcomed :)

**Comment by Normanras** [comment]
I was facing similar problems, though most of my subnet changes were x.x.0.0 and I couldn't get connections to happen. If I changed the script before installation, it worked without issue. I didn't spend too much time debugging it though and just added an option to choose your subnet during installation. Submitted the PR earlier today

**Comment by 4s3ti** [comment]
Pre-archive closing, more information [here](https://github.com/pivpn/pivpn/releases/tag/v4.6.0)
