### ISSUE TITLE
[Support] Any way to view active connections via PiVPN or WireGuard logs?

### ISSUE THREAD

**Issue by sunrisepi** [pivpn/pivpn#1269]
## In raising this issue, I confirm the following:

- [xxx] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [xxx] The issue I am reporting can be *replicated*.
- [xxx] The issue I am reporting can be directly related to the pivpn installer script.
- [xxx] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

### General Comments
Installation went fairly well, and I am able to connect without issues using WireGuard.  I did encounter a bug with the installation script (ran it via curl -L https://install.pivpn.io | bash) in that I said I would be making connections via a DNS Name (not a static IP), and I was never asked by the script what my DNS Name is.  So I had to edit the configs afterwards to replace my dynamic IP with my DDNS DNS name.

Anyway, the installation script didn't go over this so I am asking a question here.  I am trying to figure out when connections occur via WireGuard.  I want to make sure I know every time there is a connection made to my VPN.  I do not see any way to view logs for this activity, which is very strange.  I know I can run the **wg** command, but it just tells me which peers were connected and when the latest handshake occurred...  And **pivpn** doesn't seem to have any ability to show current active clients (again, just "last seen").

Ideally, I would like to see a connection log (like OpenVPN has) where it indicates when a connection starts, IP information, etc.  How can we view WireGuard connection log information?  Thank you.

### Have you searched for similar issues and solutions?
    (yes/no / which issues?) Yes.

I tried searching for other issues containing "log" but found nothing pertaining to this

### Have you taken any steps towards solving your issue?
```
Yes.  I tried checking wireguard.com, not a bunch of information on logs there. 
 ```
It mentions "Debug Logs" at https://www.wireguard.com/quickstart/, but I was unable to get this working, I think because the version of WireGuard installed by PiVPN does not include the dynamic debugging support, but I'm not sure & would appreciate further info on that too.  

Thanks a bunch!  I really like WireGuard and PiVPN, the installation went very smoothly (and I'm using it seamlessly with PiHole as well).  Now I just want to make sure I can increase monitoring around the VPN so I can track when connections are happening. Thank you.
```

**Comment by TinCanTech** [comment]
Wireguard is very light weight and does not offer the kind of functions which Openvpn does.

There is no `wg --log file` , for example.

**Comment by DerDanilo** [comment]
https://github.com/WeeJeWel/pivpn-web shows active users and traffic

**Comment by sunrisepi** [comment]
> https://github.com/WeeJeWel/pivpn-web shows active users and traffic

Thanks a bunch, I'll check it out!
