### ISSUE TITLE
Install stuck on "preparing to configure dhcpcd5 (armhf)"

### ISSUE THREAD

**Issue by BrodyStone21** [pivpn/pivpn#1270]
As the title says I'm trying to install PiVPN, I went to the website, ran the install script and everything works fine until I get to where it says "preparing to configure dhcpcd (armhf)" and it gets stuck there, now what I did do was `sudo ps -aux | grep [d]ebconf-apt-progress | awk '{print $2}` and I killed the processes which exits the install and I can see the install stops at 
```
:::    Failed to install dhcpcd5!
:::    Failed to install iptables-persistent!
Reading package lists...
Building dependency tree...
Reading state information...
iptables-persistent is already the newest version (1.0.11+deb10u1).
dhcpcd5 is already the newest version (1:8.1.2-1+rpt1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
2 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up dhcpcd5 (1:8.1.2-1+rpt1) ...

Configuration file '/etc/dhcpcd.conf'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** dhcpcd.conf (Y/I/N/O/D/Z) [default=N] ? pi@raspberrypi:~ $ 
```

I do have Open Media Vault and Plex running. One problem I have noticed with OMV is that dhcpcd doesn't work at all, my WiFi symbol in the top right says that no network interfaces can be found and there is no /etc/dhcpcd file. I'm not sure what I should do next, what do you guys think? Has anyone managed to get both PiVPN and OMV to work on the same installation? I feel like this isn't really a PiVPN issue but more of a dhcpcd issue, what should I do?

**Comment by orazioedoardo** [comment]
`sudo apt upgrade` then if prompted to take action on `dhcpcd5`, choose to install the package mantainer's version to reset the file. Run the PiVPN install script again.

**Comment by orazioedoardo** [comment]
No responses in a while, closing...
