### ISSUE TITLE
[Support] - PiVPN on my Raspberry 4

### ISSUE THREAD

**Issue by AURELB87** [pivpn/pivpn#1281]
Hi all,

I want to make my Openvpn and pi-hole server on my Raspberry 4. I have tried with a Raspian distribution and now I just tried with a Ubuntu version.

On both cases, no problem during the installation step: 
- **First** : PiVPN installation
- **Second** : Cyberghost procedure to configure openvpn (https://support.cyberghostvpn.com/hc/en-us/articles/213270689-Raspberry-Pi-How-to-configure-OpenVPN-for-Raspbian-RaspBMC-Raspberry-Pi-)
- **Third** : Pi-hole installation
- **Fourth** : Adding a new user with `pivpn -a`

My Raspberry seems to be connected through the VPN because my public IP is different than one from my router.
If I use the user file generated in step 4 (*.conf) on my "OpenVPN Connect", It doesn't work: I can't connect.

On my router, I have forwarded the port 1194 to my Raspberry IP.
If I try `pivpn -d`, I have : `[ERR] OpenVPN is not listening, try to restart now?`

I think the problem is here but I tried a lot of solution without solving the problem.

How could I check that my 1194 is well open ?
Could you please help me ?

Many thanks.
aurelien

**Comment by shelleycat485** [comment]
1 What does, on the pi,
 ```netstat -anu```
 show. It should show the listening port on 1194.
2 I would suggest trying only pivpn first, to see that there is no interaction with the other software. 
3 I also use a PI4 for the same purposes as you, but use Wireguard and p-hole instead.  Does that work?  You can install wireguard at the same time as opevpn, the port forwarding is different of course.
3 It would also really help if you followed the instructions to answer all the questions about the installation and posted the debug output

**Comment by AURELB87** [comment]
Hello Shelleycat485,

Thanks for your answer.

1- I can confirm that I didn't see the listening port on 1194 (I don't use 1194 because I already changed it to try another port but I didn't see this port).

2- Already try it, same.

3- I can try but I don't know if I can use Wireguard with my Cyberghost account: I don't think so.

4- I can prepare the log file but I can confirm that I followed this tutorial :
https://somik.org/ubuntu-18-04-install-pi-hole-with-pivpn/#:~:text=%20Ubuntu%2018.04%20Install%20Pi-Hole%20with%20PiVPN%20,your%20DNS%20provider%20IP%20address%20%281.1.1.1...%20More%20

I can also confirm that I already try this installation with others tutorials and with Raspberry Pi OS desktop & lite. Same behavior.

I think the problem is the port fowarding from my ISP but I already open ports on it but it seems doesn't work.
Thanks.

Aurelien

**Comment by AURELB87** [comment]
Hello,

Today I have tried again with a new install. I can confirm that just after the pivpn (and a reboot) the port 1194 is listening.
The port stops to listen just after the Cyberghost procedure.

Any idea ?

Many thanks.
Aurelien

**Comment by shelleycat485** [comment]
Your original step 1 configures the PI4 as an openvpn server.
Your original step 2 seems to be (and I don't use cyberghost) setting up the pi to be a VPN Client at the same time as the server.    
I don't think that will work.  You need two machines, a server and a client.

Can you try doing step 1 -  (set up as openvpn server).
Then, install openvpn onto a PC to test with.  Set up the openvpn client on the PC using the conf file from the Pi4.  Now see if the PC can make an openvpn connection to the pi4.   If this works - you have a working openvpn server on the Pi4.   (This may not work from your own LAN - you might have to have the PC linked through a tethered phone or via a  second internet connection)

**Comment by AURELB87** [comment]
Ok... well.

I confirm that it's work well if I not use the original step 2. But it use my public ip address: it's not hidden.
Is there no a way to hide my public ip address ?

**Comment by shelleycat485** [comment]
Hi
I'm just trying to help you debug the pivpn part, and that test will show whether you have a working pivpn installation. 
However, its hard to block your public ip address - any sending or receiving from you is going to see that address because its how you get to you.  If your PC uses a VPN, the sites you browse will see the address of the VPN server.  If the VPN server is at your own address, then the sites you browse will see your VPN server address which is yours.  The only way to block your public IP address is to have a VPN server with its own public IP address - for example you could hire a server somewhere else and then run a VPN server on that machine.

**Comment by AURELB87** [comment]
Hi shelleycat485,

Many thanks for all your answer and your help.
I was thinking to do that with my account in Cyberghost (or another) linked with my own VPN.

It's working like this, I will see all others solutions if needed.

Thanks! :)
