### ISSUE TITLE
[Support] <Redundancy and local IP>

### ISSUE THREAD

**Issue by Artnal** [pivpn/pivpn#1287]
### In raising this issue, I confirm the following:

- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*.
- [] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

### Issue

I have just installed a second Raspberry Pi for redundancy of the VPN + Pihole  on each, let's call them RPI1 and RPI2. I have connectivity issues at seemingly random times, such as: 
- Loss of DNS resolution from LAN devices; 
- Loss of VPN connection to the Raspberry pi I am trying to reach
- Connection to the wrong Raspberry Pi for DNS resolution. _ie_, when connected through VPN to RPI1, RPI2 acts as a DNS even though I want RPI1 to do so primarily.

### Have you searched for similar issues and solutions?
    (yes)

### Console output of      `pivpn debug` on RPI1
```::::            PiVPN debug              ::::
=============================================
::::            Latest commit            ::::
commit d7771c251418fa443869397d46f93c5b0c197558
Author: 4s3ti <4s3ti@protonmail.com>
Date:   Sat Feb 6 23:04:11 2021 +0100

    Merge branch test into master

    fixes #1234
    ci/cd fixes and improvements
=============================================
::::        Installation settings        ::::
PLAT=Raspbian
OSCN=buster
USING_UFW=0
IPv4dev=eth0
dhcpReserv=1
IPv4addr=192.168.1.[local RPI1 address]/24
IPv4gw=192.168.1.1
install_user=[Username]
install_home=/home/[Username]
VPN=wireguard
pivpnPORT=[Port open on router]
pivpnDNS1=10.6.0.1
pivpnDNS2=192.168.1.[local RPI2 address]
pivpnHOST=REDACTED
INPUT_CHAIN_EDITED=0
FORWARD_CHAIN_EDITED=0
pivpnPROTO=udp
pivpnDEV=wg0
pivpnNET=10.6.0.0
subnetClass=24
ALLOWED_IPS="0.0.0.0/0, ::0/0"
UNATTUPG=1
INSTALLED_PACKAGES=(iptables-persistent raspberrypi-kernel-headers wireguard-tools wireguard-dkms qrencode unattended-upgrades)
=============================================
::::  Server configuration shown below   ::::
[Interface]
PrivateKey = server_priv
Address = 10.6.0.1/24
ListenPort = [Port open on router]
### begin [client 1] ###
[Peer]
PublicKey = [client 1]_pub
PresharedKey = [client 1]_psk
AllowedIPs = 10.6.0.2/32
### end [client 1] ###
### begin [client 2] ###
[Peer]
PublicKey = [client 2]_pub
PresharedKey = [client 2]_psk
AllowedIPs = 10.6.0.3/32
### end [client 2] ###
### begin [client 3] ###
[Peer]
PublicKey = [client 3]_pub
PresharedKey = [client 3]_psk
AllowedIPs = 10.6.0.4/32
### end [client 3] ###
### begin [client 4] ###
[Peer]
PublicKey = [client 4]_pub
PresharedKey = [client 4]_psk
AllowedIPs = 10.6.0.5/32
### end [client 4] ###
### begin [client 5] ###
[Peer]
PublicKey = [client 5]_pub
PresharedKey = [client 5]_psk
AllowedIPs = 10.6.0.6/32
### end [client 5] ###
### begin [client 6] ###
[Peer]
PublicKey = [client 6]_pub
PresharedKey = [client 6]_psk
AllowedIPs = 10.6.0.7/32
### end [client 6] ###
=============================================
::::  Client configuration shown below   ::::
[Interface]
PrivateKey = [client 1]_priv
Address = 10.6.0.2/24
DNS = 10.6.0.1, 192.168.1.[local RPI2 address]

[Peer]
PublicKey = server_pub
PresharedKey = [client 1]_psk
Endpoint = REDACTED:[Port open on router]
AllowedIPs = 0.0.0.0/0, ::0/0
=============================================
::::    Recursive list of files in       ::::
::::    /etc/wireguard shown below       ::::
/etc/wireguard:
configs
keys
wg0.conf
wg0.conf.save
wg0.conf.save.1

/etc/wireguard/configs:
clients.txt
[client 1].conf
[client 2].conf
[client 3].conf
[client 4].conf
[client 5].conf
[client 6].conf

/etc/wireguard/keys:
[client 1]_priv
[client 1]_psk
[client 1]_pub
[client 2]_priv
[client 2]_psk
[client 2]_pub
[client 3]_priv
[client 3]_psk
[client 3]_pub
[client 4]_priv
[client 4]_psk
[client 4]_pub
[client 5]_priv
[client 5]_psk
[client 5]_pub
server_priv
server_pub
[client 6]_priv
[client 6]_psk
[client 6]_pub
=============================================
::::            Self check               ::::
:: [OK] IP forwarding is enabled
:: [OK] Iptables MASQUERADE rule set
:: [OK] WireGuard is running
:: [OK] WireGuard is enabled (it will automatically start on reboot)
:: [OK] WireGuard is listening on port [Port open on router]/udp
=============================================
:::: Having trouble connecting? Take a look at the FAQ:
:::: https://github.com/pivpn/pivpn/wiki/FAQ
=============================================
:::: WARNING: This script should have automatically masked sensitive       ::::
:::: information, however, still make sure that PrivateKey, PublicKey      ::::
:::: and PresharedKey are masked before reporting an issue. An example key ::::
:::: that you should NOT see in this log looks like this:                  ::::
:::: YIAoJVsdIeyvXfGGDDadHh6AxsMRymZTnnzZoAb9cxRe                          ::::
=============================================
::::            Debug complete           ::::
```

### Console output of      `pivpn debug` on RPI2
```::::            PiVPN debug              ::::
=============================================
::::            Latest commit            ::::
commit b2ab7fc862e31da92576d51609f250701eb6e02c (grafted, HEAD -> master, origin/test, origin/master, origin/HEAD)
Author: Orazio <orazioedoardo@users.noreply.github.com>
Date:   Tue Jun 9 15:45:38 2020 +0200

    Fix change from pull request #1000 that prevented 'pivpn -l' to show revoked client names
=============================================
::::        Installation settings        ::::
PLAT=Raspbian
OSCN=buster
USING_UFW=0
IPv4dev=eth0
dhcpReserv=1
IPv4addr=192.168.1.[local RPI2 address]/24
IPv4gw=192.168.1.1
install_user=pi
install_home=/home/pi
VPN=wireguard
pivpnPORT=[Port open on router]
pivpnDNS1=10.6.0.1
pivpnDNS2=
pivpnHOST=REDACTED
INPUT_CHAIN_EDITED=0
FORWARD_CHAIN_EDITED=0
pivpnPROTO=udp
pivpnDEV=wg0
pivpnNET=10.6.0.0
subnetClass=24
UNATTUPG=1
INSTALLED_PACKAGES=()
=============================================
::::  Server configuration shown below   ::::
[Interface]
PrivateKey = server_priv
Address = 10.6.0.1/24
ListenPort = [Port open on router]
### begin [client1] ###
[Peer]
PublicKey = [client1]_pub
PresharedKey = [client1]_psk
AllowedIPs = 10.6.0.2/32
### end [client1] ###
### begin [client2] ###
[Peer]
PublicKey = [client2]_pub
PresharedKey = [client2]_psk
AllowedIPs = 10.6.0.3/32
### end [client2] ###
### begin [client3] ###
[Peer]
PublicKey = [client3]_pub
PresharedKey = [client3]_psk
AllowedIPs = 10.6.0.4/32
### end [client3] ###
### begin [client4] ###
[Peer]
PublicKey = [client4]_pub
PresharedKey = [client4]_psk
AllowedIPs = 10.6.0.5/32
### end [client4] ###
### begin [client5] ###
[Peer]
PublicKey = [client5]_pub
PresharedKey = [client5]_psk
AllowedIPs = 10.6.0.6/32
### end [client5] ###
### begin [client6] ###
[Peer]
PublicKey = [client6]_pub
PresharedKey = [client6]_psk
AllowedIPs = 10.6.0.7/32
### end [client6] ###
=============================================
::::  Client configuration shown below   ::::
[Interface]
PrivateKey = [client1]_priv
Address = 10.6.0.2/24
DNS = 10.6.0.1

[Peer]
PublicKey = server_pub
PresharedKey = [client1]_psk
Endpoint = REDACTED:[Port open on router]
AllowedIPs = 0.0.0.0/0, ::0/0
=============================================
::::    Recursive list of files in       ::::
::::    /etc/wireguard shown below       ::::
/etc/wireguard:
configs  keys  wg0.conf  wireguard

/etc/wireguard/configs:
[client3].conf  clients.txt  [client5].conf  [client1].conf  CPRP3.conf  [client4].conf  [client2].conf

/etc/wireguard/keys:
[client3]_priv  [client3]_pub       [client5]_psk  [client1]_priv  [client1]_pub      [client6]_psk  [client4]_priv  [client4]_pub   [client2]_psk  server_priv
[client3]_psk   [client5]_priv  [client5]_pub  [client1]_psk   [client6]_priv  [client6]_pub  [client4]_psk   [client2]_priv  [client2]_pub  server_pub

/etc/wireguard/wireguard:
=============================================
::::            Self check               ::::
:: [OK] IP forwarding is enabled
:: [OK] Iptables MASQUERADE rule set
:: [OK] WireGuard is running
:: [OK] WireGuard is enabled (it will automatically start on reboot)
:: [OK] WireGuard is listening on port [Port open on router]/udp
=============================================
:::: Having trouble connecting? Take a look at the FAQ:
:::: https://github.com/pivpn/pivpn/wiki/FAQ
=============================================
:::: WARNING: This script should have automatically masked sensitive       ::::
:::: information, however, still make sure that PrivateKey, PublicKey      ::::
:::: and PresharedKey are masked before reporting an issue. An example key ::::
:::: that you should NOT see in this log looks like this:                  ::::
:::: YIAoJVsdIeyvXfGGDDadHh6AxsMRymZTnnzZoAb9cxRe                          ::::
=============================================
::::            Debug complete           ::::

```

### Have you taken any steps towards solving your issue?

 I am not particularly knowledgeable in this domain, and the issue could be crazy stupid. I wonder if one elements specifically could be part of the issue: the possibility that after installing Pivpn on both RPIs, they would in conflict for the ownership of the 10.6.0.1 address (and possible 10.6.0.X for the clients). Are there possible other issues, such as dnsmasq-related? I am a bit at loss as to how to proceed to resolve this.

Thanks a bunch!

**Comment by shelleycat485** [comment]
I've had 2 Rpi 3s running as a redundant pair since the beginning of lockdown.  They actually have been so reliable I wonder whether I needed to have a pair.

Anyway, the setup used is: 1 has openvpn (1194);  and 2 has openvpn (1196) and wireguard (usual port).  They are connected by users having the config files, and the users are given two config files for openvpn, with instructions that either config can be used and will work.  I've never seen any unreliability or DNS conflict.  The router has 3 port forwarding rules set up, and is accessed by a single ddns name.  All the (remote end) LAN devices use the DNS from the (remote end) router.

The DNS for the clients is handled by each PI, and I've never seen any effect such as you say.  However, I've got external DNS servers set up on the pivpn configs - so my DNS entry, e.g. for the wireguard conf has an entry for the 1.1.1.1 servers.

I hope this helps, but I cannot see an obvious problem with your configs.

**Comment by Artnal** [comment]
Thank you for your input shelleycat485.

In case someone lands on this post in the future, I have solved the issue although I am not sure which part of my changes resolved it. Here's how I proceeded:

- I fully removed pivpn, to restart from scratch on it. 
- Once pivpn/Wireguard reinstalled, I added the following iptables to `/etc/wireguard/wg0.conf`, under [Interface]

> PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
- I also changed (still under [Interface]) "Address" to "10.6.1.1", to avoid any possible conflict with RPI1, which was already "10.6.0.1"
- I changed the dnsmasq as follows: in `/etc/dnsmasq.d/01-pihole.conf` (can also be done through the Pihole's GUI settings, under DNS)

> interface=eth0
-  and in `/etc/dnsmasq.d/02-pivpn.conf`, I added the line

> interface=wg0

- Finally, I modified parts of `/etc/pivpn/wireguard/setupVars.conf` as follows: 
> pipvpnDNS1=10.6.1.1
 
#to match the change I made above
> pipvpnDNS2=192.168.1.[local RPI1 address]

#to have a backup DNS if, for some reason, pihole on RPI2 fails. I am not sure a) if it is necessary and b) if putting "10.6.0.1" instead would have had the same effect
>pivpnNET=10.6.1.0

#for the coherence of the VPN subnet created through this RPI.

That seems to have resolved the issue. From my very limited understanding of the matter, I believe that the Iptables I added essentially made it look like traffic was coming from eth0 even though it actually came from wireguard (wg0). This, in turn, led pihole to accept incoming traffic through the VPN.

For safety, I regenerated new clients from wireguard on this basis. It works fine right now, both wireguard and LAN connections are resolved by the pihole DNS.
