### ISSUE TITLE
[Support] Can't install PIVPN

### ISSUE THREAD

**Issue by jsfrederick** [pivpn/pivpn#1288]
## In raising this issue, I confirm the following:

`{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

### Have you searched for similar issues and solutions?
    (yes/no / which issues?)
Yes

### Console output of      `curl -L install.pivpn.io | bash`
```
  root@Pi-hole:~# curl -L https://install.pivpn.io | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   162  100   162    0     0    364      0 --:--:-- --:--:-- --:--:--   364
100 83358  100 83358    0     0   116k      0 --:--:-- --:--:-- --:--:--  116k
:::
::: You are root.
::: Hostname length OK
::: Verifying free disk space...
:::
::: Package Cache update is needed, running apt-get update -y ...
 done!
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: Your system is up to date! Continuing with PiVPN installation...
:::    Checking for git... already installed!
:::    Checking for tar... already installed!
:::    Checking for wget... already installed!
:::    Checking for curl... already installed!
:::    Checking for grep... already installed!
:::    Checking for dnsutils... already installed!
:::    Checking for whiptail... already installed!
:::    Checking for net-tools... already installed!
:::    Checking for bsdmainutils... already installed!
:::    Checking for iptables-persistent... not installed!oot@Pi-hole:~# curl -L https://install.pivpn.io | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   162  100   162    0     0    364      0 --:--:-- --:--:-- --:--:--   364
100 83358  100 83358    0     0   116k      0 --:--:-- --:--:-- --:--:--  116k
:::
::: You are root.
::: Hostname length OK
::: Verifying free disk space...
:::
::: Package Cache update is needed, running apt-get update -y ...
 done!
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: Your system is up to date! Continuing with PiVPN installation...
:::    Checking for git... already installed!
:::    Checking for tar... already installed!
:::    Checking for wget... already installed!
:::    Checking for curl... already installed!
:::    Checking for grep... already installed!
:::    Checking for dnsutils... already installed!
:::    Checking for whiptail... already installed!
:::    Checking for net-tools... already installed!
:::    Checking for bsdmainutils... already installed!
:::    Checking for iptables-persistent... not installed!


(The GUI Screes for Installing packages and configuring iptables-persistant appear here)

:::    Failed to install iptables-persistent!
Reading package lists...
Building dependency tree...
Reading state information...
iptables-persistent is already the newest version (1.0.11+deb10u1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up iptables-persistent (1.0.11+deb10u1) ...
Can't locate object method "new" via package "Text::Iconv" (perhaps you forgot to load "Text::Iconv"?) at /usr/share/perl5/Debconf/Encoding.pm line 65.
dpkg: error processing package iptables-persistent (--configure):
 installed iptables-persistent package post-installation script subprocess returned error exit status 29
Errors were encountered while processing:
 iptables-persistent
E: Sub-process /usr/bin/dpkg returned an error code (1)
root@Pi-hole:~#
```

### Console output of      `pivpn add` or `pivpn add nopass`
```
  Output Here
```

### Console output of      `pivpn debug`
```
  Output Here
```
### Have you taken any steps towards solving your issue?
```
  reinstalled PIVPN.  Updated packages

Armbian Buster 21.02.3
```

**Comment by shelleycat485** [comment]
It does install on a raspian buster release. I have never used Armbian Buster before, whats the hardware you are using?

**Comment by jsfrederick** [comment]
> It does install on a raspian buster release. I have never used Armbian Buster before, whats the hardware you are using?

Rock64.  I had it working on my previous Rock64/Armbian instance.  Needed to rebuild the setup as my Pi-Hole died.  But this is a new install.

**Comment by salem84** [comment]
Hi, same error with Armbian on OrangePi PC

`uname -a`
> Linux orangepipc 5.10.21-sunxi #21.02.3 SMP Mon Mar 8 00:28:04 UTC 2021 armv7l GNU/Linux

I think it's a problem with this armbian version, because on previous installation with the same OrangePi it works.

Maybe something related to Docker installation?

**Comment by 4s3ti** [comment]
Trying to install OpenVPN or Wireguard??

**Comment by jsfrederick** [comment]
> Trying to install OpenVPN or Wireguard??

Wireguard

**Comment by 4s3ti** [comment]
Ok, so first concept to clear, you are not installing pivpn ... pivpn is a set of scripts that will install a VPN Procotol for you, either wireguard or OpenVPN. 

Unfortunately Not all Boards are supported with Wireguard as it is not possible to determine the correct kernel headers to use on all different kinds of boards and that might be the reason why pivpn is not being able to install it. 

the fact that it was working on a previous version doesn't mean it should work on a newer one, quite the opposite, kernel changes, packages can change name, there's a lot that can be different. 

@orazioedoardo might be able to give you more details about it once it comes around and has some time to provide some input here.

**Comment by orazioedoardo** [comment]
> Unfortunately Not all Boards are supported with Wireguard as it is not possible to determine the correct kernel headers to use on all different kinds of boards and that might be the reason why pivpn is not being able to install it.

Yes, there are too many combinations of kernels and kernel headers to meaningfully handle.

**Comment by nathanielbutts** [comment]
@jsfrederick I had the same issue on a new install of DietPi on a Raspberry 4.  Found this during my search and itsolved my issue.

[https://github.com/pivpn/pivpn/issues/231#issuecomment-290849696](url)

**Comment by StudentBlake** [comment]
I experienced this on DietPi RPi ARMv8 Buster (64-bit). The solution that worked for me was installing any packages that it stopped on manually, then rerunning the script until it successfully installed. For me, that was iptables-persistent and unattended-upgrades.
