### ISSUE TITLE
install erased firewall, left machine unprotected

### ISSUE THREAD

**Issue by edn1** [pivpn/pivpn#1289]
i'm using iptables-legacy 
when installing openvpn via pivpn, it overwritten /etc/iptables/rules.v4 with empty ruleset (only nat was there)
it didn't even ask before overwriting ...

**Comment by 4s3ti** [comment]
Hi, thanks for reaching out, 

If you believe this is a bug, please properly fill the bug template when opening a new issue. 


Closing. 
Please feel free to re-open with the properly filled template.
