### ISSUE TITLE
[Support] NAT error

### ISSUE THREAD

**Issue by Ashwin-droid** [pivpn/pivpn#1290]
## In raising this issue, I confirm the following:

`{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

### Issue
When I add a openvpn with 'pivpn add' and enter the parameters it succeeds and also my pivpn installation is successful. I use a duck duck go ddns and a cron job to update the in every public ip every 5 min and I have also set port forwarding which opens 1194 port on either ends and it still doesn't work which means that I have 2 or more layered nat which is not accessible by me so any solutions like udp/tcp nat hole punching?

### Have you searched for similar issues and solutions?
    (yes/no / which issues?)
    No

### Console output of      `curl -L install.pivpn.io | bash`
```
  Doesn't matter
```

### Console output of      `pivpn add` or `pivpn add nopass`
```
 pi@raspberrypi:~ $ sudo pivpn add nopass
Enter a Name for the Client:  Ashwin-droid
How many days should the certificate last?  1080
spawn ./easyrsa build-client-full Ashwin-droid nopass

Note: using Easy-RSA configuration from: /etc/openvpn/easy-rsa/varsUsing SSL: openssl OpenSSL 1.1.1d  10 Sep 2019
Generating an EC private key
writing new private key to '/etc/openvpn/easy-rsa/pki/easy-rsa-3365.cYUMxe/tmp.zMAjqm'
-----
Using configuration from /etc/openvpn/easy-rsa/pki/easy-rsa-3365.cYUMxe/tmp.4gbvdQ
Check that the request matches the signature
Signature ok
The Subject's Distinguished Name is as follows
commonName            :ASN.1 12:'Ashwin-droid'
Certificate is to be certified until Mar 15 06:19:18 2024 GMT (1080 days)

Write out database with 1 new entries
Data Base Updated

Client's cert found: Ashwin-droid.crt
Client's Private Key found: Ashwin-droid.key
CA public Key found: ca.crt
tls Private Key found: ta.key
::: Updated hosts file for Pi-hole


========================================================
Done! Ashwin-droid.ovpn successfully created!
Ashwin-droid.ovpn was copied to:
  /home/pi/ovpns
for easy transfer. Please use this profile only on one
device and create additional profiles for other devices.
========================================================
 

Or 


pi@raspberrypi:~ $ sudo pivpn add
Enter a Name for the Client:  ashwin-droid
How many days should the certificate last?  1080
Enter the password for the client:
Enter the password again to verify:
spawn ./easyrsa build-client-full ashwin-droid

Note: using Easy-RSA configuration from: /etc/openvpn/easy-rsa/varsUsing SSL: openssl OpenSSL 1.1.1d  10 Sep 2019
Generating an EC private key
writing new private key to '/etc/openvpn/easy-rsa/pki/easy-rsa-3525.T2ReKP/tmp.ONEBOe'
Enter PEM pass phrase:
Verifying - Enter PEM pass phrase:
-----
Using configuration from /etc/openvpn/easy-rsa/pki/easy-rsa-3525.T2ReKP/tmp.47xZza
Check that the request matches the signature
Signature ok
The Subject's Distinguished Name is as follows
commonName            :ASN.1 12:'ashwin-droid'
Certificate is to be certified until Mar 15 06:22:24 2024 GMT (1080 days)

Write out database with 1 new entries
Data Base Updated

Client's cert found: ashwin-droid.crt
Client's Private Key found: ashwin-droid.key
CA public Key found: ca.crt
tls Private Key found: ta.key
::: Updated hosts file for Pi-hole


========================================================
Done! ashwin-droid.ovpn successfully created!
ashwin-droid.ovpn was copied to:
  /home/pi/ovpns
for easy transfer. Please use this profile only on one
device and create additional profiles for other devices.
========================================================
```

### Console output of      `pivpn debug`
```
  ::: Generating Debug Output
::::            PiVPN debug              ::::
=============================================
::::            Latest commit            ::::
commit d7771c251418fa443869397d46f93c5b0c197558
Author: 4s3ti <4s3ti@protonmail.com>
Date:   Sat Feb 6 23:04:11 2021 +0100

    Merge branch test into master

    fixes #1234
    ci/cd fixes and improvements
=============================================
::::        Installation settings        ::::
PLAT=Raspbian
OSCN=buster
USING_UFW=0
IPv4dev=wlan0
IPv4addr=192.168.0.111/24
IPv4gw=192.168.0.1
install_user=pi
install_home=/home/pi
VPN=openvpn
pivpnPROTO=udp
pivpnPORT=1194
pivpnDNS1=10.8.0.1
pivpnDNS2=
pivpnSEARCHDOMAIN=
pivpnHOST=REDACTED
TWO_POINT_FOUR=1
pivpnENCRYPT=521
USE_PREDEFINED_DH_PARAM=0
INPUT_CHAIN_EDITED=0
FORWARD_CHAIN_EDITED=0
pivpnDEV=tun0
pivpnNET=10.8.0.0
subnetClass=24
ALLOWED_IPS=""
UNATTUPG=1
INSTALLED_PACKAGES=()
HELP_SHOWN=1
=============================================
::::  Server configuration shown below   ::::
dev tun
proto udp
port 1194
ca /etc/openvpn/easy-rsa/pki/ca.crt
cert /etc/openvpn/easy-rsa/pki/issued/raspberrypi_683508d4-bbe8-4b9a-95a2-c7ede0365af3.crt
key /etc/openvpn/easy-rsa/pki/private/raspberrypi_683508d4-bbe8-4b9a-95a2-c7ede0365af3.key
dh none
ecdh-curve secp521r1
topology subnet
server 10.8.0.0 255.255.255.0
# Set your primary domain name server address for clients
push "dhcp-option DNS 10.8.0.1"
push "block-outside-dns"
# Override the Client default gateway by using 0.0.0.0/1 and
# 128.0.0.0/1 rather than 0.0.0.0/0. This has the benefit of
# overriding but not wiping out the original default gateway.
push "redirect-gateway def1"
client-to-client
client-config-dir /etc/openvpn/ccd
keepalive 15 120
remote-cert-tls client
tls-version-min 1.2
tls-crypt /etc/openvpn/easy-rsa/pki/ta.key
cipher AES-256-CBC
auth SHA256
user openvpn
group openvpn
persist-key
persist-tun
crl-verify /etc/openvpn/crl.pem
status /var/log/openvpn-status.log 20
status-version 3
syslog
verb 3
#DuplicateCNs allow access control on a less-granular, per user basis.
#Remove # if you will manage access by user instead of device.
#duplicate-cn
# Generated for use by PiVPN.io
=============================================
::::  Client template file shown below   ::::
client
dev tun
proto udp
remote REDACTED 1194
resolv-retry infinite
nobind
remote-cert-tls server
tls-version-min 1.2
verify-x509-name raspberrypi_683508d4-bbe8-4b9a-95a2-c7ede0365af3 name
cipher AES-256-CBC
auth SHA256
auth-nocache
verb 3
=============================================
::::    Recursive list of files in       ::::
::: /etc/openvpn/easy-rsa/pki shows below :::
/etc/openvpn/easy-rsa/pki/:
Ashwin.ovpn
ca.crt
crl.pem
Default.txt
ecparams
index.txt
index.txt.attr
index.txt.attr.old
index.txt.old
issued
openssl-easyrsa.cnf
private
renewed
revoked
safessl-easyrsa.cnf
serial
serial.old
ta.key

/etc/openvpn/easy-rsa/pki/ecparams:
secp521r1.pem

/etc/openvpn/easy-rsa/pki/issued:
Ashwin.crt
raspberrypi_683508d4-bbe8-4b9a-95a2-c7ede0365af3.crt

/etc/openvpn/easy-rsa/pki/private:
Ashwin.key
ca.key
raspberrypi_683508d4-bbe8-4b9a-95a2-c7ede0365af3.key

/etc/openvpn/easy-rsa/pki/renewed:
private_by_serial
reqs_by_serial

/etc/openvpn/easy-rsa/pki/renewed/private_by_serial:

/etc/openvpn/easy-rsa/pki/renewed/reqs_by_serial:

/etc/openvpn/easy-rsa/pki/revoked:
private_by_serial
reqs_by_serial

/etc/openvpn/easy-rsa/pki/revoked/private_by_serial:

/etc/openvpn/easy-rsa/pki/revoked/reqs_by_serial:
=============================================
::::            Self check               ::::
:: [OK] IP forwarding is enabled
:: [OK] Iptables MASQUERADE rule set
:: [OK] OpenVPN is running
:: [OK] OpenVPN is enabled (it will automatically start on reboot)
:: [OK] OpenVPN is listening on port 1194/udp
=============================================
:::: Having trouble connecting? Take a look at the FAQ:
:::: https://github.com/pivpn/pivpn/wiki/FAQ
=============================================
::::      Snippet of the server log      ::::
Mar 30 16:32:33 raspberrypi ovpn-server[394]: OpenVPN 2.4.7 arm-unknown-linux-gnueabihf [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 20 2019
Mar 30 16:32:33 raspberrypi ovpn-server[394]: library versions: OpenSSL 1.1.1d  10 Sep 2019, LZO 2.10
Mar 30 16:32:33 raspberrypi ovpn-server[394]: ECDH curve secp521r1 added
Mar 30 16:32:33 raspberrypi ovpn-server[394]: Outgoing Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Mar 30 16:32:33 raspberrypi ovpn-server[394]: Outgoing Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Mar 30 16:32:33 raspberrypi ovpn-server[394]: Incoming Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Mar 30 16:32:33 raspberrypi ovpn-server[394]: Incoming Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Mar 30 16:32:34 raspberrypi ovpn-server[394]: TUN/TAP device tun0 opened
Mar 30 16:32:34 raspberrypi ovpn-server[394]: TUN/TAP TX queue length set to 100
Mar 30 16:32:34 raspberrypi ovpn-server[394]: /sbin/ip link set dev tun0 up mtu 1500
Mar 30 16:32:34 raspberrypi ovpn-server[394]: /sbin/ip addr add dev tun0 10.8.0.1/24 broadcast 10.8.0.255
Mar 30 16:32:34 raspberrypi ovpn-server[394]: Could not determine IPv4/IPv6 protocol. Using AF_INET
Mar 30 16:32:34 raspberrypi ovpn-server[394]: Socket Buffers: R=[180224->180224] S=[180224->180224]
Mar 30 16:32:34 raspberrypi ovpn-server[394]: UDPv4 link local (bound): [AF_INET][undef]:1194
Mar 30 16:32:34 raspberrypi ovpn-server[394]: UDPv4 link remote: [AF_UNSPEC]
Mar 30 16:32:34 raspberrypi ovpn-server[394]: GID set to openvpn
Mar 30 16:32:34 raspberrypi ovpn-server[394]: UID set to openvpn
Mar 30 16:32:34 raspberrypi ovpn-server[394]: MULTI: multi_init called, r=256 v=256
Mar 30 16:32:34 raspberrypi ovpn-server[394]: IFCONFIG POOL: base=10.8.0.2 size=252, ipv6=0
Mar 30 16:32:34 raspberrypi ovpn-server[394]: Initialization Sequence Completed
=============================================
::::            Debug complete           ::::
:::
::: Debug output completed above.
::: Copy saved to /tmp/debug.log
:::
```
### Have you taken any steps towards solving your issue?
```
  none 
```

**Comment by Ashwin-droid** [comment]
And also if I modify the opvn file to target local ip, it works like a charm (but that defys the entire purpose of vpn)(which in my case is using my home network remotely and private and ad-blocking network (pivpn + pihole))

**Comment by Ashwin-droid** [comment]
Same issue with wireguard vpn

**Comment by TinCanTech** [comment]
You only need to `open`/`port-forward` `UDP:1194` on the server end.

**Comment by 4s3ti** [comment]
@Ashwin-droid is your ISP putting you behind a NAT? please check that with them and if it is the case check if they can provide you with a public ip address for yourself. 

Otherwise there is no way.

**Comment by Ashwin-droid** [comment]
@TinCanTech here is my port forwarding rule. Check whether it is correct ![Screenshot_20210401-104415_Adblock Browser.jpg](https://user-images.githubusercontent.com/58349846/113246850-772d1800-92d7-11eb-9615-b6f0160bba4b.jpg)

**Comment by Ashwin-droid** [comment]
@4s3ti probably yeah. Because my earlier router(which died in a mishap) had openvpn server built in but I never got it to work.

**Comment by Ashwin-droid** [comment]
Here is the openvpn log
> 10:54:16.637 -- ----- OpenVPN Start -----

10:54:16.639 -- EVENT: CORE_THREAD_ACTIVE

10:54:16.646 -- OpenVPN core 3.git:released:662eae9a:Release android armv7a thumb2 32-bit PT_PROXY

10:54:16.657 -- Frame=512/2048/512 mssfix-ctrl=1250

10:54:16.672 -- UNUSED OPTIONS
4 [resolv-retry] [infinite] 
5 [nobind] 
8 [verify-x509-name] [raspberrypi_683508d4-bbe8-4b9a-95a2-c7ede0365af3] [name] 
11 [auth-nocache] 
12 [verb] [3] 

10:54:16.673 -- EVENT: RESOLVE

10:54:16.687 -- Contacting 255.255.255.255:1194 via UDP

10:54:16.688 -- EVENT: WAIT

10:54:16.703 -- Connecting to [test.duckdns.org]:1194 (255.255.255.255) via UDPv4

10:54:26.678 -- Server poll timeout, trying next remote entry...

10:54:26.680 -- EVENT: RECONNECTING

10:54:26.689 -- EVENT: RESOLVE

10:54:26.713 -- Contacting 255.255.255.255:1194 via UDP

10:54:26.715 -- EVENT: WAIT

10:54:26.734 -- Connecting to [test.duckdns.org]:1194 (255.255.255.255) via UDPv4

10:54:36.683 -- Server poll timeout, trying next remote entry...

10:54:36.685 -- EVENT: RECONNECTING

10:54:36.696 -- EVENT: RESOLVE

10:54:36.708 -- Contacting 255.255.255.255:1194 via UDP

10:54:36.709 -- EVENT: WAIT

10:54:36.741 -- Connecting to [test.duckdns.org]:1194 (255.255.255.255) via UDPv4

10:54:46.689 -- Server poll timeout, trying next remote entry...

10:54:46.691 -- EVENT: RECONNECTING

10:54:46.707 -- EVENT: RESOLVE

10:54:46.717 -- Contacting 255.255.25.255:1194 via UDP

10:54:46.718 -- EVENT: WAIT

10:54:46.725 -- Connecting to [test.duckdns.org]:1194 (255.255.255.255) via UDPv4

10:54:56.010 -- EVENT: DISCONNECTED

10:54:56.011 -- Tunnel bytes per CPU second: 0

10:54:56.012 -- ----- OpenVPN Stop -----


255.255.255.255 not an actual ip
test.duckdns.com not an actual ddns

**Comment by orazioedoardo** [comment]
From: https://docs.pivpn.io/faq/#what-to-do-if-i-see-no-packets

> Check if your ISP uses Carrier-grade NAT (check online). With CGNAT, your router gets a private IP, making port forwarding ineffective. This is mostly the norm if your router connects via 4G/LTE. If that's the case, you need to ask the ISP for a public IP.

**Comment by Ashwin-droid** [comment]
> From: https://docs.pivpn.io/faq/#what-to-do-if-i-see-no-packets
> 
> > Check if your ISP uses Carrier-grade NAT (check online). With CGNAT, your router gets a private IP, making port forwarding ineffective. This is mostly the norm if your router connects via 4G/LTE. If that's the case, you need to ask the ISP for a public IP.

I had checked with my ISP I have a public ip but it seems that I am having problems with port forwarding

**Comment by Ashwin-droid** [comment]
> > From: https://docs.pivpn.io/faq/#what-to-do-if-i-see-no-packets
> > > Check if your ISP uses Carrier-grade NAT (check online). With CGNAT, your router gets a private IP, making port forwarding ineffective. This is mostly the norm if your router connects via 4G/LTE. If that's the case, you need to ask the ISP for a public IP.
> 
> I had checked with my ISP I have a public ip but it seems that I am having problems with port forwarding

no i am facing a cgnat

**Comment by Ashwin-droid** [comment]
is there any methord that I can use like reverse port forwarding or reverse vpn tunnel as  i dont want to pay extra money

sorry if the above mentioned methords are not possible as i just googled it 

is there any way to route the traffic over gcp and dynamically route them (please free tire)

**Comment by 4s3ti** [comment]
I am sure there might some way to go around but its probably way more advanced setup with a lot of routing headache, completely out of pivpn scope and not sure if anyone has expertise / knowledge on how to do it.

**Comment by TinCanTech** [comment]
If there were a free way around CGNAT then the internet would break..

**Comment by 4s3ti** [comment]
> If there were a free way around CGNAT then the internet would break..

Entirely true!!! 

all this said guess this can be closed. 
@Ashwin-droid feel free to re-open if you feel that there is anything else we ca do for you.

**Comment by Ashwin-droid** [comment]
Thanks for your time and support
