### ISSUE TITLE
[Support] Generating profile for VPN server running behind the NAT with port translation

### ISSUE THREAD

**Issue by jirih** [pivpn/pivpn#1291]
### In raising this issue, I confirm the following:

- [x] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

## Issue
Current setup: OpenVPN server is running on a local private network behind the NAT. Server's port is default, e.g. 1194. NAT is translating connections from publicIP:publicPORT to privateIP:privatePORT. The VPN works fine with this setup when connected to the publicIP:publicPORT.

The problem I have is generating the profiles using PiVPN. When I generate a new one, it contains a following line:
remote mypublicdn.org 1194

Unless this line is manually changed, the client cannot connect to the VPN server.

I tried to change pivpnPORT in /etc/pivpn/openvpn/setupVars.conf from 1194 to my privatePORT but when a new profile is then generated, the "remote" line remains the same in the profile (a bit surprising) and as a bonus, pivpn -d fails saying "[ERR] OpenVPN is not listening, try to restart now? [Y/n]" (not so surprising).

Is it possible to handle my setup with the pivpn?

### Have you searched for similar issues and solutions?
  yes

### Console output of      `pivpn add` or `pivpn add nopass`
Looks ok, no issue here, I guess.
```
Enter a Name for the Client:  test
How many days should the certificate last?  1080
spawn ./easyrsa build-client-full test nopass

Note: using Easy-RSA configuration from: /etc/openvpn/easy-rsa/vars
Using SSL: openssl OpenSSL 1.1.1d  10 Sep 2019
Generating an EC private key
writing new private key to '/etc/openvpn/easy-rsa/pki/easy-rsa-28090.n8cS80/tmp.uIILpb'
-----
Using configuration from /etc/openvpn/easy-rsa/pki/easy-rsa-28090.n8cS80/tmp.QbsHlx
Check that the request matches the signature
Signature ok
The Subject's Distinguished Name is as follows
commonName            :ASN.1 12:'test'
Certificate is to be certified until Mar 15 07:50:58 2024 GMT (1080 days)

Write out database with 1 new entries
Data Base Updated

Client's cert found: test.crt
Client's Private Key found: test.key
CA public Key found: ca.crt
tls Private Key found: ta.key


========================================================
Done! test.ovpn successfully created!
test.ovpn was copied to:
  /home/ludolf/ovpns
for easy transfer. Please use this profile only on one
device and create additional profiles for other devices.
========================================================

```
### Console output of      `pivpn debug`
Relevant info above.

### Have you taken any steps towards solving your issue?
  searching Internet - the "best" advice I found was "do not translate ports". Not an option for me.

**Comment by TinCanTech** [comment]
Are you sure you have you enabled `port-forwarding` on your router ?

**Comment by jirih** [comment]
> Are you sure you have you enabled `port-forwarding` on your router ?

Yes, port translation works. The connection to vpn from outside my router is ok. Just the generated profile is wrong and needs a manual fix.

Please note that publicPORT != privatePORT in my case.

**Comment by TinCanTech** [comment]
That is not how NAT works.

Under NAT, Port translation is only ever supposed to happen on egress, not on ingress.

Your router is setup incorrectly.

**Comment by WildOne69** [comment]
There are use cases for PiVPN behind NAT @TinCanTech , my $work has everything on private IP space even though we own multiple /24's and it allows us to move around internet-facing servers and devices with VERY **little** changes to the configuration at the firewall versus a lot of changes at the firewall if we kept our internet-facing servers on /24's. 

you REALLY should spend some time reading up on NAT66 and SNAT and DNAT and Bi-directional NAT on firewalls before you replied.

**Comment by TinCanTech** [comment]
@WildOne69 You can configure your firewall however you  like, providing the device supports what you want to do, that does not make it a good idea .. I'm not getting into an argument with a total stranger about _somebody else's network_ and no reply from the OP in almost three months.

**Comment by 4s3ti** [comment]
Inactive Thread. 
The Reporter is no longer answer and coming up here just to bash people is highly unappreciated! 

@WildOne69 I REALLY Recommend you to spend sometime finding for good manners and learning how to be polite! 

Closing and locking thread.!
