### ISSUE TITLE
[Support] Internet connection drops while using VPN and accessing resources on home network through dynamic dns

### ISSUE THREAD

**Issue by szerencl** [pivpn/pivpn#1292]
## In raising this issue, I confirm the following:

- [x] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [x] The issue I am reporting isn't a duplicate

## Issue
I'm running a PiVPN (wireguard), PiHole combo, and while I'm remotely connected through the VPN and try to access resources that were made available publicly through DDNS the internet connection drops (on the home network as well as on the VPN connection, I know this because I tried connecting to a different machine in the home network with TeamViewer and it went offline), but the connection comes back in ~3-10 minutes after closing the application that caused it.

The applications causing it are Plex Media Server, and Home Assistant. Both were made available remotely with DDNS and port forwarding. For example accessing Home Assistant through the public DDNS domain causes the issue, but accessing it with the Pi's IP address doesn't. Also using the DDNS while not connected to the VPN doesn't cause issues.
With Plex I can't even start streaming while on the VPN because it drops. However using my samaba share I can easily watch the same content.

Some things to mention are that both of these issues involve video streams as I added a camera feed to HA, and with Plex of course being a streaming service it is a given.
And the connection drop isn't instant, it takes around 1 minute while the stream is slowed to a crawl.
While the connection is dropped there is no handshake and received data on the VPN.

### Have you searched for similar issues and solutions?
    Yes, but only found issues where people didn't have connection at all with PiHole and PiVPN.

### Console output of      `pivpn debug`
```
  ::: Generating Debug Output
::::            PiVPN debug              ::::
=============================================
::::            Latest commit            ::::
commit 13f0fe7cbdcdb31537b3fd0e2eb34652e886cc1b
Author: 4s3ti <4s3ti@protonmail.com>
Date:   Wed Dec 9 19:22:29 2020 +0100

    ProBot Stale

    Added probot integration to marke topics as inactives and automatically
    close them.
    read .github/stale.yml for more details.
=============================================
::::        Installation settings        ::::
PLAT=Raspbian
OSCN=buster
USING_UFW=0
IPv4dev=eth0
dhcpReserv=1
IPv4addr=192.168.42.42/24
IPv4gw=192.168.42.1
install_user=pi
install_home=/home/pi
VPN=wireguard
pivpnPORT=51820
pivpnDNS1=10.6.0.1
pivpnDNS2=
pivpnHOST=REDACTED
INPUT_CHAIN_EDITED=0
FORWARD_CHAIN_EDITED=0
pivpnPROTO=udp
pivpnDEV=wg0
pivpnNET=10.6.0.0
subnetClass=24
UNATTUPG=1
INSTALLED_PACKAGES=(wireguard-tools wireguard-dkms)
=============================================
::::  Server configuration shown below   ::::
[Interface]
PrivateKey = server_priv
Address = 10.6.0.1/24
ListenPort = 51820
#PreUp = iptables -t nat -A POSTROUTING -j MASQUERADE -o eth0
#PreDown = iptables -t nat -D POSTROUTING -j MASQUERADE -o eth0
### begin Client1 ###
[Peer]
PublicKey = Client1_pub
PresharedKey = Client1_psk
AllowedIPs = 10.6.0.2/32
### end Client1 ###
### begin Client2 ###
[Peer]
PublicKey = Client2_pub
PresharedKey = Client2_psk
AllowedIPs = 10.6.0.3/32
### end Client2 ###
=============================================
::::  Client configuration shown below   ::::
[Interface]
PrivateKey = Client1_priv
Address = 10.6.0.2/24
DNS = 10.6.0.1

[Peer]
PublicKey = server_pub
PresharedKey = Client1_psk
Endpoint = REDACTED:51820
AllowedIPs = 0.0.0.0/0, ::0/0
=============================================
::::    Recursive list of files in       ::::
::::    /etc/wireguard shown below       ::::
/etc/wireguard:
configs
keys
wg0.conf

/etc/wireguard/configs:
clients.txt
Client2.conf
Client1.conf

/etc/wireguard/keys:
Client2_priv
Client2_psk
Client2_pub
Client1_priv
Client1_psk
Client1_pub
server_priv
server_pub
=============================================
::::            Self check               ::::
:: [OK] IP forwarding is enabled
:: [OK] Iptables MASQUERADE rule set
:: [OK] WireGuard is running
:: [OK] WireGuard is enabled (it will automatically start on reboot)
:: [OK] WireGuard is listening on port 51820/udp
=============================================
:::: Having trouble connecting? Take a look at the FAQ:
:::: https://github.com/pivpn/pivpn/wiki/FAQ
=============================================
:::: WARNING: This script should have automatically masked sensitive       ::::
:::: information, however, still make sure that PrivateKey, PublicKey      ::::
:::: and PresharedKey are masked before reporting an issue. An example key ::::
:::: that you should NOT see in this log looks like this:                  ::::
:::: YIAoJVsdIeyvXfGGDDadHh6AxsMRymZTnnzZoAb9cxRe                          ::::
=============================================
::::            Debug complete           ::::
:::
::: Debug output completed above.
::: Copy saved to /tmp/debug.log
:::
```
### Have you taken any steps towards solving your issue?
```
 - Tried switching the port forward for VPN to UDP and TCP instead of just UDP, but no cigar.
 - Unfortunately I have to deal with a double NAT, but I added the second router to the DMZ but no success. I have the port forwards set up on both routers.
 - PiHole is listening on all interfaces.
 - Tried pinging my public IP from inside the network and from the VPN but no answer
 This might have something to do with the issue?

ping REDACTED
PING REDACTED (REDACTED) 56(84) bytes of data.
^C
--- REDACTED ping statistics ---
25 packets transmitted, 0 received, 100% packet loss, time 962ms

```

**Comment by orazioedoardo** [comment]
Can you access Plex or Home Assistant using the LAN (internal) IP while remotely connected to the VPN?

**Comment by szerencl** [comment]
For HA yes, but for Plex turning off remote play doesn't solve the issue because it still uses the service provided by Plex to some intent. Note though that, opening the Plex client doesn't cause the issue. It only presents when I start to stream something. But streaming videos from the local samba (w/ VLC) share works.

I think it has to do something with the path of data, but I don't understand how that would make devices on the local network lose internet connection.
remote -> VPN -> local -> internet -> local -> VPN -> remote

Also a thing I noticed previously is that the VPN connection doesn't work (no internet or local network access) if I try to connect while on the local network. Don't know if it's relevant or this is the expected behaviour.

**Comment by orazioedoardo** [comment]
> For HA yes, but for Plex turning off remote play doesn't solve the issue because it still uses the service provided by Plex to some intent.

I've heard Plex uses some interesting tricks to let you connect to the server using `https://app.plex.tv/desktop`. Can you use `http://lan_ip:32400` to connect to the Plex server. You need to disable [Secure Server Connections](https://support.plex.tv/articles/206225077-how-to-use-secure-server-connections/), so if you do disable port forwarding for Plex for security.

> I think it has to do something with the path of data, but I don't understand how that would make devices on the local network lose internet connection.

Wait? Devices on the local network loose connection??? I thought your VPN client did.

> Also a thing I noticed previously is that the VPN connection doesn't work (no internet or local network access) if I try to connect while on the local network. Don't know if it's relevant or this is the expected behaviour.

This is a limitation of your router: it doesn't let you connect to a device in the local network when referencing it using the router public IP: https://en.wikipedia.org/wiki/Hairpinning

**Comment by szerencl** [comment]
> Can you use http://lan_ip:32400 to connect to the Plex server?

I can access it but can't start streaming with the web browser this way. Only if I use plex.tv to access it for some reason.

> Wait? Devices on the local network loose connection???

Yes. I have a PC on at the moment in the local network and can connect to it with TeamViewer. However when I lose connection because of the said issues and disable the VPN (so I have connection and can acces the internet on the remote network), TeamViewer reports the PC in the local network offline, and only comes back online at the same time as I am able to connect to the VPN again. Could it be that this is messing up the PiHole somehow? That's the only thing that PC is using from the Pi.

> This is a limitation of your router: it doesn't let you connect to a device in the local network when referencing it using the router public IP

So could this be the cause of the issue? I think the ISP router doesn't support this (as many other things... that thing is so bad).

**Comment by szerencl** [comment]
> Could it be that this is messing up the PiHole somehow?

Update:
Tried setting google as the DNS for that PC instead of PiHole, but it still went offline.

**Comment by orazioedoardo** [comment]
> So could this somehow be the cause of the issue, or would this mean that I wouldn't even be able to open Plex client or HA using the DDNS when on VPN.

Actually, I didn't explain it fully (it does in the wikipedia page). It doesn't let you connect FROM A DEVICE IN THE LOCAL NETWORK to a device also in the local network when referencing it using the router public IP.

> Yes. I have a PC on at the moment in the local network and can connect to it with TeamViewer. However when I lose connection because of the said issues and disable the VPN (so I have connection and can acces the internet on the remote network), TeamViewer reports the PC in the local network offline, and only comes back online at the same time as I am able to connect to the VPN again. Could it be that this is messing up the PiHole somehow? That's the only thing that PC is using from the Pi.

What does TeamViewer have to do with the VPN? Please explain all PCs and networks involved.

**Comment by szerencl** [comment]
> What does TeamViewer have to do with the VPN? Please explain all PCs and networks involved.

That's how I know the PC on the same network as the Pi lost internet connection, because I'm not there currently.

There's a PC on the same network as the Pi, let's call that the local network. I can connect to that PC through TeamViewer even without VPN, so I can verify it has internet connection.
On the remote network I have my laptop and connect to the local network with the VPN, and when trying to access said services I lose internet access on the VPN connection.
When I disconnect the VPN I have internet connection on my laptop (remote network) but I can't connect to the PC in the local network with TeamViewer, because it lost internet connection as well. 
After the connection comes back online and I connect to it with TeamViewer the application I'm running on it reports that it had lost the connection.

**Comment by orazioedoardo** [comment]
> On the remote network I have my laptop and connect to the local network with the VPN, and when trying to access said services I lose internet access on the VPN connection.

Do you happen to have the same 192.168.42.0/24 IP range on the remote network? That could cause conflicts. Do you actually loose internet access on the VPN connection or just access to the local network?

> When I disconnect the VPN I have internet connection on my laptop (remote network) but I can't connect to the PC in the local network with TeamViewer, because it lost internet connection as well.

Try to run some background download on the PC on the local network to make sure it's that computer that looses connection when you tun on the VPN on the remote PC.

It is possible that when you turn on the VPN on a device, connections that where initiated outside the tunnel  just drop, but you should be able to restart them. For example try to use TeamViewer after connecting to the VPN.

Also try another remote network, like a cellular network.

**Comment by szerencl** [comment]
> Do you happen to have the same 192.168.42.0/24 IP range on the remote network? That could cause conflicts.

Actually it does but I tried connecting with my phone connection and disconnecting everything else, but it also happens this way.

> Do you actually loose internet access on the VPN connection or just access to the local network?

I lose internet as well. Websites don't load, can't ping anything until I disable the VPN.

> Try to run some background download on the PC on the local network to make sure it's that computer that looses connection when you tun on the VPN on the remote PC.

I did just that. The internet drops.

> It is possible that when you turn on the VPN on a device, connections that where initiated outside the tunnel just drop, but you should be able to restart them. For example try to use TeamViewer after connecting to the VPN.

I only lose connection when I try to access said services through the VPN, but then I can't connect through TeamViewer because the PC in the local network lost connection. (I disable VPN, so I have internet on the remote network).

> Also try another remote network, like a cellular network.

Also happens on cellular.

**Comment by orazioedoardo** [comment]
> I lose internet as well. Websites don't load, can't ping anything until I disable the VPN.

Can you actually reach the Raspberry at this point? https://docs.pivpn.io/faq/#how-do-i-troubleshoot-connection-issues

> I did just that. The internet drops.

I can't explain this sorry. Maybe try to get rid of the double NAT and use a single router?

**Comment by szerencl** [comment]
> Can you actually reach the Raspberry at this point?

No, but I will try when I have physical access to it, and also try to get rid of the double NAT.

**Comment by szerencl** [comment]
Finally had the chance to put the ISP router into bridge mode, and lo and behold the problem is gone.
Now I only have to find a way to use a different DNS provider on the guest network of my own router, but that's a different story.
Thank you for your help @orazioedoardo!
