### ISSUE TITLE
why is the update script currently (since 2020may?) disabled?

### ISSUE THREAD

**Issue by matsonfamily** [pivpn/pivpn#1293]
from what i can discern, the update script has been disabled since the last edit, about a year ago, but I don't see an "issue" about this and cannot find any comments in the history that explain this.  I'm not a coder, so I may be missing something, but if there's an issue this is addressing, can we have an open issue that documents is, so I can track when it's resolved?  Thanks.  Also, until it's resolved, should we be updating any scripts that have been updated in the last year, manually? [since it's not a debian package]

https://github.com/pivpn/pivpn/blob/master/scripts/update.sh

**Comment by 4s3ti** [comment]
if i am not mistaken this is the main reason why: https://github.com/pivpn/pivpn/issues/1069

Mainly related with breaking changes and confusion with users having it installed with prior versions and therefore breaking their installations. 

pivpn just makes the installation process for you, all the rest is updated through your package manager. 

This said it was disabled till we find a solution and the old philosophy remains, https://github.com/pivpn/pivpn/wiki/Upgrading

What is important to keep updated is your protocols not pivpn! Pivpn is only worth being updated if you really want any feature we might have added to the scripts that assist you with managing your vpn. 

if you really want to update it ... for now there are only two ways ... 
1. backup your installation, re-install and restore the backup or manually update 
2. cd `/usr/src/pivpn && git pull origin master` be aware that this approach might introduce changes not backwards compatible therefore break your setup.

**Comment by matsonfamily** [comment]
Thanks!!  I don't know why i never found that */wiki/Upgrading page.  makes sense now (except why the script presents the -up option at all).  I guess it wouldn't be too difficult to `pivpn uninstall`, and then re download the script and install again [and configuring half a dozen clients wouldn't be difficult].  Is there a way to determine which version of the pivpn install I have, so that I may determine if anything was added from my version?

**Comment by orazioedoardo** [comment]
> Is there a way to determine which version of the pivpn install I have, so that I may determine if anything was added from my version?

Run `pivpn debug` and at the beginning of the output you will see the date of the last change to PiVPN.
