### ISSUE TITLE
[Support] .OVPN How is it made?

### ISSUE THREAD

**Issue by myxxmikeyxx** [pivpn/pivpn#1294]
How does the script make that file and where is that part?
I am having trouble finding that part.

**Comment by orazioedoardo** [comment]
Here: https://github.com/pivpn/pivpn/blob/d7771c251418fa443869397d46f93c5b0c197558/scripts/openvpn/makeOVPN.sh

**Comment by myxxmikeyxx** [comment]
Thank you very mush @orazioedoardo
