### ISSUE TITLE
[Suggestion] chown failing when user and group are not the same

### ISSUE THREAD

**Issue by UniverseDevel** [pivpn/pivpn#1296]
## In raising this issue, I confirm the following: 

- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting *is* directly related to the pivpn installer script.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

**Describe the bug**
After installing Raspberry Pi OS I changed the name of a default user, but I left the group as it is as I find no benefit in changing that. PiVPN automatically assumes that group is always the same as username. In my case I am constantly getting error messages like `
chown: invalid group: ‘myname:myname’` and files stored in home folder are crated as root:root. This can be seen in following instances (there might be more but these cause error for me right now): 
https://github.com/pivpn/pivpn/blob/d7771c251418fa443869397d46f93c5b0c197558/scripts/openvpn/makeOVPN.sh#L227
https://github.com/pivpn/pivpn/blob/d7771c251418fa443869397d46f93c5b0c197558/scripts/openvpn/makeOVPN.sh#L378
https://github.com/pivpn/pivpn/blob/d7771c251418fa443869397d46f93c5b0c197558/scripts/openvpn/makeOVPN.sh#L454
Installation script asks only for username but should ask for group as well:
https://github.com/pivpn/pivpn/blob/d7771c251418fa443869397d46f93c5b0c197558/auto_install/install.sh#L902

**To Reproduce**
Steps to reproduce the behaviour:
1. Have an RPi installation and change only username of default user or create a new user with different group and appropriate sudo rights
2. Install PiVPN
3. Add new client
4. Error should be seen along the way

**Expected behaviour**
Installation should ask about user group as well for chmod to fill in correct group and not assume the group is the same as username.

**Desktop (please complete the following information):**
 - OpenVPN
 - OS: Raspbian GNU/Linux
 - Version 10 (buster)

**Comment by 4s3ti** [comment]
to be honest, and don't get me wrong but i don't think it is a bug .. i think the issue is rather here: 

> After installing Raspberry Pi OS I changed the name of a default user, but I left the group as it is as I find no benefit in changing that. 


So many years of pivpn and this is a first! why rename the user and not rename the group? that's sounds  just confusing and not right thing to do! 

Also you should have in consideration that when you install a package / software on linux that relies on users/groups changing that will break! 

its like changing nginx or apache and then renaming the www-data user and expect it to work properly. 

we base the code on best and common practices and by default nowadays, each user has its own group, if you rename a user you should rename the group as well and change the variables on /etc/pivpn/setupvars.conf

Regardless of any of this, I do think it is a good call out and won't hurt to add some checks about this. and have a `installgroup` variable for situations where users want to tweak a bit more their setups

**Comment by UniverseDevel** [comment]
> to be honest, and don't get me wrong but i don't think it is a bug .. i think the issue is rather here:
> 
> > After installing Raspberry Pi OS I changed the name of a default user, but I left the group as it is as I find no benefit in changing that.

I must agree here, calling this a bug might be a little over the line mainly due to how nonstandard the setup is and I was kinda expecting this reaction.

> So many years of pivpn and this is a first! why rename the user and not rename the group? that's sounds just confusing and not right thing to do!
> 
> Also you should have in consideration that when you install a package / software on linux that relies on users/groups changing that will break!
> 
> its like changing nginx or apache and then renaming the www-data user and expect it to work properly.
> 
> we base the code on best and common practices and by default nowadays, each user has its own group, if you rename a user you should rename the group as well and change the variables on /etc/pivpn/setupvars.conf

I understand and you are of course correct, when you consider common practices, defaults and so on. But there are so many other use cases when different group might be needed to be used regardless of the nonstandard setup that I have. Also never had a single problem with this setup for like 4 years so far, usually software depending on such things let you configure both or creates own user. Which is why I suggested this. As this is my person device, this is not such a big deal if unchanged.

I don't want to sound ungrateful as this software is amazing and I am actually sad that I just found out about it. I had created similar set of scripts like a year ago, attempting to do something similar and I hated my implementation. Only difference was I tried to include 2FA.

Maybe little off topic but, I am also not sure if there is no dialog for `pivpnNET` to be changed during installation or I just missed that but it would be useful to ask for it as well because my network is currently limited to mask 255.255.252.0 and range for VPN is on 10.0.2.X. Its not hard to change and reconfigure but I was a bit surprised that this was set to default (10.8.0.0) and for a second OpenVPN started to hand out invalid IP addresses. :)

**Comment by TinCanTech** [comment]
> my network is currently limited to mask 255.255.252.0 and range for VPN is on 10.0.2.X. Its not hard to change and reconfigure but I was a bit surprised that this was set to default (10.8.0.0) and for a second OpenVPN started to hand out invalid IP addresses.

Your OpenVPN server is configured to hand out IP addresses in the `10.8.0.0/24` subnet.

What addresses did it start _handing out_ ?

**Comment by UniverseDevel** [comment]
Default for OpenVPN is 10.8.0.0/24 but my network is configured to 10.0.0.0/22 so anything above 10.0.3.255 is invalid. It started to hand out 10.8.0.X addresses. I had to manually change server.conf to correct this value.

eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.0.0.11  netmask 255.255.252.0  broadcast 10.0.3.255

**Comment by TinCanTech** [comment]
It sounds like you have manually introduced a network conflict to your VPN.

The VPN network is not supposed to be within your LAN network.

Why don't you post your current server config so we can take a look ?

**Comment by UniverseDevel** [comment]
This is what got generated after install, note the comment after `server` parameter.

```
dev tun
proto tcp
port 8443
ca <path to CA>
cert <path to CERT>
key <path to Key>
dh none
ecdh-curve prime256v1
topology subnet
server 10.8.0.0 255.255.255.0 # had to change this to `server 10.0.2.0 255.255.255.0` for OpenVPN to hand out IPs in valid range and the one that I designated for VPN
# Set your primary domain name server address for clients
push "dhcp-option DNS 10.0.0.1"
push "dhcp-option DNS 8.8.8.8"
# Prevent DNS leaks on Windows
push "block-outside-dns"
# Override the Client default gateway by using 0.0.0.0/1 and
# 128.0.0.0/1 rather than 0.0.0.0/0. This has the benefit of
# overriding but not wiping out the original default gateway.
push "redirect-gateway def1"
client-to-client
client-config-dir /etc/openvpn/ccd
keepalive 15 120
remote-cert-tls client
tls-version-min 1.2
tls-crypt /etc/openvpn/easy-rsa/pki/ta.key
cipher AES-256-CBC
auth SHA256
user openvpn
group openvpn
persist-key
persist-tun
crl-verify /etc/openvpn/crl.pem
status /var/log/openvpn-status.log 20
status-version 3
syslog
verb 3
#DuplicateCNs allow access control on a less-granular, per user basis.
#Remove # if you will manage access by user instead of device.
#duplicate-cn
# Generated for use by PiVPN.io
```

**Comment by TinCanTech** [comment]
> Default for OpenVPN is 10.8.0.0/24 but my network is configured to 10.0.0.0/22 so anything above 10.0.3.255 is invalid. It started to hand out 10.8.0.X addresses. I had to manually change server.conf to correct this value.
> 
> eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST> mtu 1500
> inet 10.0.0.11 netmask 255.255.252.0 broadcast 10.0.3.255

> server 10.8.0.0 255.255.255.0 # had to change this to `server 10.0.2.0 255.255.255.0` for OpenVPN to hand out IPs in valid range, 10.0.2.X is designated for VPN but anything above 10.0.3.255 is invalid

With your VPN server started please run:
`ip r`
on the server and post the result.

**Comment by UniverseDevel** [comment]
```
default via 10.0.0.1 dev eth0 proto dhcp src 10.0.0.11 metric 202
10.0.0.0/22 dev eth0 proto dhcp scope link src 10.0.0.11 metric 202
10.0.2.0/24 dev tun0 proto kernel scope link src 10.0.2.1
```

**Comment by TinCanTech** [comment]
You have **borked** your VPN.
```
tct@home:~$ ipcalc -n 10.0.0.0/22
Address:   10.0.0.0             00001010.00000000.000000 00.00000000
Netmask:   255.255.252.0 = 22   11111111.11111111.111111 00.00000000
Wildcard:  0.0.3.255            00000000.00000000.000000 11.11111111
=>
Network:   10.0.0.0/22          00001010.00000000.000000 00.00000000
HostMin:   10.0.0.1             00001010.00000000.000000 00.00000001
HostMax:   10.0.3.254           00001010.00000000.000000 11.11111110
Broadcast: 10.0.3.255           00001010.00000000.000000 11.11111111
Hosts/Net: 1022                  Class A, Private Internet

tct@home:~$ ipcalc -n 10.0.2.0/24
Address:   10.0.2.0             00001010.00000000.00000010. 00000000
Netmask:   255.255.255.0 = 24   11111111.11111111.11111111. 00000000
Wildcard:  0.0.0.255            00000000.00000000.00000000. 11111111
=>
Network:   10.0.2.0/24          00001010.00000000.00000010. 00000000
HostMin:   10.0.2.1             00001010.00000000.00000010. 00000001
HostMax:   10.0.2.254           00001010.00000000.00000010. 11111110
Broadcast: 10.0.2.255           00001010.00000000.00000010. 11111111
Hosts/Net: 254                   Class A, Private Internet
```

Because this **issue** is about `user/group` names and assignments, I will leave it at that.

**Comment by UniverseDevel** [comment]
The configuration that I puth there is working as expected and I think you did not understood what my initial problem was. My problem was that installation did not let me choose on which range OpenVPN should assign IPs and assumed default 10.8.0.0/24 that was not valid on my network. But, as it had an easy fix and is working correctly after setting 10.0.2.0/24 we don't have to discuss this any further.

**Comment by 4s3ti** [comment]
> Maybe little off topic but, I am also not sure if there is no dialog for pivpnNET to be changed during installation or I just missed that but it would be useful to ask for it as well because my network is currently limited to mask 255.255.252.0 and range for VPN is on 10.0.2.X. Its not hard to change and reconfigure but I was a bit surprised that this was set to default (10.8.0.0) and for a second OpenVPN started to hand out invalid IP addresses. :)

It is intended to be like that, and we won't add a dialog for it, see: https://github.com/pivpn/pivpn/issues/1273

**Comment by UniverseDevel** [comment]
Ah, I see. Its fine like that. Its not my first try configuring OpenVPN so its not a problem, I was just wondering that if I missed it somewhere or it was intentionally left out. Now I know. Thank you.
