### ISSUE TITLE
[Support] Does PiVPN support AdGuardHome?

### ISSUE THREAD

**Issue by chriscn** [pivpn/pivpn#1297]
I am a big fan of this script and often install it on the same Raspberry Pi as PiHole. I’m thinking about switching from PiHole to Adguard Home, does PiVPN natively support this? I notice that when installing PiVPN after installing PiHole it finds the installation, changes the ‘hops’ settings and then sets the DNS. 

Or do I need to do anything manually through AdGuardHome.

**Comment by orazioedoardo** [comment]
Looks like Adguard is DNS based, so yes it should work.

**Comment by NitelPhyoe** [comment]
@chriscn It work with AdGuard Home, But You need to choose dns server option to `Pi as local DNS` when installing pivpn.

**Comment by orazioedoardo** [comment]
No responses in a while, closing...
