### ISSUE TITLE
tls-version-min not working

### ISSUE THREAD

**Issue by computerfr33k** [pivpn/pivpn#13]
I get the following error when starting the vpn on Ubuntu 14.04

`
Options error: Unrecognized option or missing parameter(s) in /etc/openvpn/server.conf:27: tls-version-min (2.3.2)
`

**Comment by 0-kaladin** [comment]
Ah, looks like ubuntu is running an older version of openvpn in its repo than raspbian.  I'll strip that option out on the next update if using ubuntu.  In the meantime just delete the tls-server-min line from your /etc/openvpn/server.conf file.

**Comment by computerfr33k** [comment]
unfortunately the openvpn repo on their site doesn't work with arm.
