### ISSUE TITLE
how should I edit settings after deployment?

### ISSUE THREAD

**Issue by orangepizza** [pivpn/pivpn#130]
for example, address of server for external clients.
I set it to a rounter's free ddns address, but it broke last week, so I bought a rounter from another company, so I have to use different address for it. I changed manually for already created clients, but pivpn -add will create ovpn files with old address with it. how can I change that?

**Comment by redfast00** [comment]
You have two options:

- Reinstall PiVPN and input the correct name. This is the easiest solution, but will require you to do the whole setup again.
- Edit `/etc/openvpn/easy-rsa/keys/Default.txt` and replace `remote old.ddns.com <port>` with `remote new.ddns.com <port>`. You will also have to do this in your `.ovpn` files you generated before the change.

**Comment by philwolstenholme** [comment]
Just a note that ```/etc/openvpn/easy-rsa/keys/Default.txt``` is now found here: ```/etc/openvpn/easy-rsa/pki/Default.txt```

See: https://github.com/pivpn/pivpn/blob/df16e8dd591b09913450279f7fad71df2af621da/auto_install/install.sh#L962

**Comment by kjunggithub** [comment]
Just FYI,I had to sudo to be able to see/edit this file.
