### ISSUE TITLE
[SUPPORT] Not able to visit external websites on VPN with PPPoE

### ISSUE THREAD

**Issue by twlawrenceko** [pivpn/pivpn#1309]
Hi all,

I have initially set up PPPoE on Raspberry Pi then configure PiVPN with OpenVPN. After the client connects the VPN, the client is able to ping all internal devices but not able to visit google or ping 8.8.8.8.

Initially I have set DNS with 8.8.8.8, later on set with my router gateway IP 192.168.1.1, and also tried with Raspberry Pi's own IP 192.168.1.123, but none of those worked. 

I believe it is a gateway DNS issue related to PPPoE connection, is there any method to resolve this?

Thanks

**Comment by 4s3ti** [comment]
Please fill the support request properly.
