### ISSUE TITLE
cannot connect .ovpn

### ISSUE THREAD

**Issue by mind-mind** [pivpn/pivpn#1310]
I use PIVPN to generate config .ovpn, but after I use 

openvpn file.ovpn, it cannot connect.

Tue May 11 16:24:34 2021 OpenVPN 2.4.7 arm-unknown-linux-gnueabihf [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 20 2019
Tue May 11 16:24:34 2021 library versions: OpenSSL 1.1.1d  10 Sep 2019, LZO 2.10
Enter Private Key Password: ****
Tue May 11 16:24:36 2021 Outgoing Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Tue May 11 16:24:36 2021 Outgoing Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Tue May 11 16:24:36 2021 Incoming Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Tue May 11 16:24:36 2021 Incoming Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Tue May 11 16:24:36 2021 TCP/UDP: Preserving recently used remote address: [AF_INET]1.46.32.38:1194
Tue May 11 16:24:36 2021 Socket Buffers: R=[180224->180224] S=[180224->180224]
Tue May 11 16:24:36 2021 UDP link local: (not bound)
Tue May 11 16:24:36 2021 UDP link remote: [AF_INET]1.46.32.38:1194
Tue May 11 16:25:36 2021 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Tue May 11 16:25:36 2021 TLS Error: TLS handshake failed
Tue May 11 16:25:36 2021 SIGUSR1[soft,tls-error] received, process restarting
Tue May 11 16:25:36 2021 Restart pause, 5 second(s)

it was something like this all day. 
How can I fix it?

**Comment by shelleycat485** [comment]
Can you give the usual information when opening a ticket, all anyone can see from this is that the client cannot connect.   Also a pivpn -d on the server would be helpful.  And perhaps the steps to create the problem and the history (its never worked, its suddenly changed, other clients work, I've tested a local connection before and it worked?)

**Comment by 4s3ti** [comment]
Edited your comment and enclosed the `pivpn -d` information in a code block.

**Comment by mind-mind** [comment]
Sorry, I haven't a code block and don't prefer to download, so hope the above will help. Thanks.

**Comment by shelleycat485** [comment]
Issue #1298 looks similar - you may have an IPV4/IPV6 issue.  If you have IPV6 on your Raspberry Pi, try turning it off.
