### ISSUE TITLE
VPN not Connecting with Iphone

### ISSUE THREAD

**Issue by ascheier** [pivpn/pivpn#1314]
Hello,
I have been working on this for a few days now and I keep running into the same problem. I download pivpn, create a profile, and scan the QR code with the wireguard app and everything looks like it is working until I try to turn on the VPN on my phone. When I turn on the VPN and try to go to a website or do anything on the internet, it doesn't work. I double-checked that I had the correct port forwarded on my network and that all looks good. I am using a raspberry pi 3B and an iPhone 11 running IOS 14.6. If anybody has run into a problem like this or knows anything about it, any help is appreciated. I would definitely consider myself a beginner when it comes to networking so there might be something pretty obvious that I am missing. I will also attach a screenshot of my port forwarding settings.
<img width="1158" alt="Screen Shot 2021-05-25 at 1 20 05 PM" src="https://user-images.githubusercontent.com/63080605/119548692-13b1ea80-bd5c-11eb-86a0-5b5dd7f24ba8.png">

**Comment by bruhreid** [comment]
Same issue here

**Comment by 4s3ti** [comment]
Please properly fill in the Support request template.

**Comment by williamgh2019** [comment]
You may be missed input DNS IP during setup

**Comment by 4s3ti** [comment]
closing. 

Requested to properly fill the issue template .. and still nothing. 

Please re-open with all the requested details in the issue template.
