### ISSUE TITLE
command "cd usr/local/src/pivpn" in auto-install.sh throws error  

### ISSUE THREAD

**Issue by thelastWallE** [pivpn/pivpn#1315]
I try to install now pivpn for like 2 hours and every method comes to an end at this error.

Output of `bash pivpn/auto_install/install.sh`

 ```
bash pivpn/auto_install/install.sh
:::
::: sudo will be used for the install.
::: Hostname length OK
::: Verifying free disk space...
:::
::: Package Cache update is needed, running apt-get update -y ...
 done!
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: Your system is up to date! Continuing with PiVPN installation...
:::    Checking for git... already installed!
:::    Checking for tar... already installed!
:::    Checking for wget... already installed!
:::    Checking for curl... already installed!
:::    Checking for grep... already installed!
:::    Checking for dnsutils... already installed!
:::    Checking for whiptail... already installed!
:::    Checking for net-tools... already installed!
:::    Checking for bsdmainutils... already installed!
:::    Checking for apt-transport-https... already installed!
:::    Checking for dhcpcd5... already installed!
:::    Checking for iptables-persistent... already installed!
::: Using User: pi
:::
::: Checking for existing base files...
:::    Checking /usr/local/src/pivpn is a repo... not found!
:::    Cloning https://github.com/pivpn/pivpn.git into /usr/local/src/pivpn...pivpn/auto_install/install.sh: line 1034: cd: /usr/local/src/pivpn: No such file or directory
```
The directory gets removed before the change directory command so this throws an error.
Line:
https://github.com/pivpn/pivpn/blob/4a5804a24c7397c24945c0f94c2609483f008100/auto_install/install.sh#L1034

**Comment by shelleycat485** [comment]
1 what are you installing on?
2 what operating system?
3 what account are you using?

AWS Ubuntu 20.04 does not show this problem. A Pi 3B using Linux raspbx 5.10.17-v7+ Debian version 10.9 does not show this problem.  A  Pi 3B using Linux rpi3 4.19.66-v7+  Debian Version 9.13 does not show this problem.  (I did not do a full install, on these, just enough to check the clone operation).

**Comment by sflems** [comment]
Same issue here, solved by running bash install with sudo: 
```
git clone https://github.com/pivpn/pivpn.git
sudo bash pivpn/auto_install/install.sh
```

**Comment by shelleycat485** [comment]
Just to clarify, you should not have to install using sudo, though it is a workaround.  It would be interesting to know under what circumstances the non-sudo fault occurs.

**Comment by sflems** [comment]
I first attempted Method 1 as per the readme. 
```
curl -L https://install.pivpn.io | bash
```
This results in the same error as above.

Method 3, _verbatim_ results in the same error. I haven't made any other user permission changes that should affect this. Let me know if you'd like any other specifics.

OS Info:
```
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

**Comment by shelleycat485** [comment]
This is puzzling. I made a new buster image on a Pi3B.  This gave 
```
Linux raspberrypi 5.10.17-v7+ #1414 SMP Fri Apr 30 13:18:35 BST 2021 armv7l GNU/Linux. 

```
I was running it headless.   The only changes I made were to enable ssh using raspi-config, and also put local ssh certificates on. Nothing else.  Then:
```
git clone https://github.com/pivpn/pivpn.git
./pivpn/auto_install/install.sh
```
This was successful - the installation went ahead.  I've got no ideas where my installation is different from yours.

**Comment by sflems** [comment]
I just ran the install on a second Pi4 configured identically to the first
(same image and config) and the setup ran flawlessly without the use of
sudo.

Officially perplexed.

**Comment by shelleycat485** [comment]
I wonder if the git clone is failing silently, then of course the directory will not be there.  That would be a transient network error.  At the moment the script is discarding any error information.  I will try a number of times with the redirection to null removed, and the spinner removed (near line 1034 ).

**Comment by orazioedoardo** [comment]
Looks similar to https://github.com/pivpn/pivpn/issues/1210

**Comment by iComputerfreak** [comment]
I had the same problem with my Raspberry Pi 4 Model B. Removing `> /dev/null` in https://github.com/pivpn/pivpn/blob/4a5804a24c7397c24945c0f94c2609483f008100/auto_install/install.sh#L1033
resulted in the git clone output not being voided and revealed the following:
```
::: Checking for existing base files...
:::    Checking /usr/local/src/pivpn is a repo... not found!
:::    Cloning https://github.com/pivpn/pivpn.git into /usr/local/src/pivpn... [/]  Please do not run git as root, your regular user account is enough :)

If you need to run git with root rights for some other application than
what comes preinstalled on this image you can remove this sanity check:

    sudo rm /root/bin/git

You might have to restart your login session after doing that.
./install.sh: line 1034: cd: /usr/local/src/pivpn: No such file or directory
```

It seems that on the Raspberry Pi 4 Model B, running git using sudo will fail.
As a workaround, executing the above command `sudo rm /root/bin/git` and therefore removing the "root version" of git that always fails with this message worked for me.

**Comment by 4s3ti** [comment]
@iComputerfreak What OS are you using???

 https://docs.pivpn.io/faq/#what-about-octopi

**Comment by iComputerfreak** [comment]
Ah. I am indeed using OctoPi. Sorry for the confusion I did not know this was a modification of OctoPi only.
