### ISSUE TITLE
IP Address Not Changing When VPN is enabled

### ISSUE THREAD

**Issue by isaac7437** [pivpn/pivpn#1318]
Hello, 
I've set up WireGuard VPN on my Raspberry Pi 3B, however, when I enable the VPN on my phone, the public IP address doesn't change. I am using a Samsung A51 5G with the latest version of [WireGuard for Android](https://play.google.com/store/apps/details?id=com.wireguard.android) installed.
The configuration file is imported into the app, which was downloaded via the QR code. 
The VPN turns on, but I don't get a change of IP address, as mentioned above.
I have tried doing port forwarding, however, I'm unsure on how to do it, so maybe that's the problem? - I have Virgin Media WiFi.

Here's what the port forwarding settings look like:

![image](https://user-images.githubusercontent.com/50076680/119979380-c7acb300-bfb2-11eb-862d-2cccee9f45bb.png)

I'm not sure what to put whereas on other tutorials, there are only two boxes to fill in. Or is it nothing to do with port forwarding?

Can someone help?
Thanks.

**Comment by 4s3ti** [comment]
Please properly fill in the support request template. 

question number one ... Are you connecting to the VPN while connected to the same network you are at? 

Please be aware that if you have your VPN server Inside your home .. when you connect to that VPN server .. you will always see your home ip address.

**Comment by isaac7437** [comment]
> Please properly fill in the support request template.

**Added more details.**

> question number one ... Are you connecting to the VPN while connected to the same network you are at?

**Firstly, I am connected to my home network, then I switch on the VPN using [WireGuard](https://play.google.com/store/apps/details?id=com.wireguard.android). When I switch on the VPN, I still have a working internet connection, however, as mentioned my IP address doesn't change.**

> Please be aware that if you have your VPN server Inside your home .. when you connect to that VPN server .. you will always see your home ip address.

**My VPN server is located in my house and my phone is connected to the same network, so would that be why I'm not getting a change in IP address? If this correct, how would I see if the VPN is actually working as it should?**

**Thanks!**

**Comment by TinCanTech** [comment]
> If this correct, how would I see if the VPN is actually working as it should?

It is **correct**.

To test, connect to you VPN and then unplug your server from your network and you will not be able to access the internet.

**Comment by isaac7437** [comment]
Thank you, @TinCanTech and @4s3ti. I'll test this soon then close this issue after.

**Comment by isaac7437** [comment]
When trying the VPN without any port forwarding, I have no internet connection when it is switched on. - This is on my PC.

I use these settings for port forwarding, are the port boxes correct?

![image](https://user-images.githubusercontent.com/50076680/120044099-15520b80-c005-11eb-8cee-b8d1318d4e5a.png)

With port forwarding active, I'm able to use the internet with the VPN on.

I've had a quick look on how to actually see if the VPN is working or not, and [this website](https://dnsleaktest.com) comes up.

Results:

With the VPN off, only one Virgin Media server comes up. - (I'm using Virgin Media).

With the VPN on, I get nine servers. These are from 'Woody Net'...

![image](https://user-images.githubusercontent.com/50076680/120044686-36672c00-c006-11eb-9a7f-b475dda2a5c6.png)

**Am I meant to be getting these? - I chose CloudFlare as my DNS service.**

Thanks.

**Comment by orazioedoardo** [comment]
Port forwarding is correct, although "Protocol" should be just UDP and not Both (UDP + TCP), since WireGuard is UDP only.

> With the VPN off, only one Virgin Media server comes up. - (I'm using Virgin Media).

This is likely the Virgin Media DNS server.

> With the VPN on, I get nine servers. These are from 'Woody Net'...

These are likely the IPs of the Cloudflare servers closest to your home location, where you installed PiVPN.

To test the VPN:

With VPN off, connect to your home network and check the IP shown on the website you linked above.

Then, with VPN on, change network (for example use the cellular network), and go to the website again, it should show your home IP again.

**Comment by isaac7437** [comment]
> Port forwarding is correct, although "Protocol" should be just UDP and not Both (UDP + TCP), since WireGuard is UDP only.

**I've changed the protocol to UDP**

![image](https://user-images.githubusercontent.com/50076680/120062928-7c4edf00-c05c-11eb-888b-abe76dcc60a4.png)

> To test the VPN:
> 
> With VPN off, connect to your home network and check the IP shown on the website you linked above.
> 
> Then, with VPN on, change network (for example use the cellular network), and go to the website again, it should show your home IP again.

**I've done the above steps and it looks like it's working!**

I went on this [DNS leak website](https://surfshark.com/dns-leak-test). When the VPN is off, it says this:

![image](https://user-images.githubusercontent.com/50076680/120063120-87563f00-c05d-11eb-9886-d07d5be6b9c0.png)

When it's on it says this:

![image](https://user-images.githubusercontent.com/50076680/120063154-b66cb080-c05d-11eb-95be-6bb53930d4b8.png)

**This is meant to happen right?**

**Comment by orazioedoardo** [comment]
Can you post the debug log from the raspberry pi? `pivpn debug`

**Comment by isaac7437** [comment]
> Can you post the debug log from the raspberry pi? `pivpn debug`

**I'm out at the moment, I'll do it when I get home. Is something wrong?**

**Comment by orazioedoardo** [comment]
> I'm out at the moment, I'll do it when I get home. Is something wrong?

No, just wanted to make sure the VPN is correctly installed and DNS is set.

**Comment by isaac7437** [comment]
> No, just wanted to make sure the VPN is correctly installed and DNS is set.

**Here it is:**

[debug.log](https://github.com/pivpn/pivpn/files/6564565/debug.log)

**Comment by isaac7437** [comment]
`::::		[4mPiVPN debug[0m		 ::::
=============================================
::::		[4mLatest commit[0m		 ::::
commit 4a5804a24c7397c24945c0f94c2609483f008100
Author: 4s3ti <4s3ti@protonmail.com>
Date:   Sat May 8 15:51:27 2021 +0200

    Multiple fixes and Shellcheck complaiance
    
    fixes for Issue #1306, qrcode now defaults to ansiutf8,
    added flag -a256 or --ansi256 if their fonts are having trouble
    
    Shellcheck compliance #1233 for qrcodeCONF.sh,
    LIST array is now created with mapfile instead
    quoted multiple variables.
    
    fixes for Issue #1307, User creation won't allow user creation with name
    starting with "-", qrcodeCONF.sh won't accept wrong options or users starting with "-"
    and exit with error code 1
=============================================
::::	    [4mInstallation settings[0m    	 ::::
PLAT=Raspbian
OSCN=buster
USING_UFW=0
IPv4dev=eth0
dhcpReserv=1
IPv4addr=192.168.0.25/24
IPv4gw=192.168.0.1
install_user=pi
install_home=/home/pi
VPN=wireguard
pivpnPORT=51820
pivpnDNS1=9.9.9.9
pivpnDNS2=149.112.112.112
pivpnHOST=REDACTED
INPUT_CHAIN_EDITED=0
FORWARD_CHAIN_EDITED=0
pivpnPROTO=udp
pivpnMTU=1420
pivpnDEV=wg0
pivpnNET=10.6.0.0
subnetClass=24
ALLOWED_IPS="0.0.0.0/0, ::0/0"
UNATTUPG=1
INSTALLED_PACKAGES=(dnsutils iptables-persistent wireguard-tools qrencode unattended-upgrades)
=============================================
::::  [4mServer configuration shown below[0m   ::::
[Interface]
PrivateKey = server_priv
Address = 10.6.0.1/24
MTU = 1420
ListenPort = 51820
### begin Isaac ###
[Peer]
PublicKey = Isaac_pub
PresharedKey = Isaac_psk
AllowedIPs = 10.6.0.2/32
### end Isaac ###
### begin Isaac_PC ###
[Peer]
PublicKey = Isaac_PC_pub
PresharedKey = Isaac_PC_psk
AllowedIPs = 10.6.0.3/32
### end Isaac_PC ###
=============================================
::::  [4mClient configuration shown below[0m   ::::
[Interface]
PrivateKey = Isaac_priv
Address = 10.6.0.2/24
MTU = 1420
DNS = 9.9.9.9, 149.112.112.112

[Peer]
PublicKey = server_pub
PresharedKey = Isaac_psk
Endpoint = REDACTED:51820
AllowedIPs = 0.0.0.0/0, ::0/0
=============================================
:::: 	[4mRecursive list of files in[0m	 ::::
::::	[4m/etc/wireguard shown below[0m	 ::::
/etc/wireguard:
configs
keys
wg0.conf

/etc/wireguard/configs:
clients.txt
Isaac.conf
Isaac_PC.conf

/etc/wireguard/keys:
Isaac_PC_priv
Isaac_PC_psk
Isaac_PC_pub
Isaac_priv
Isaac_psk
Isaac_pub
server_priv
server_pub
=============================================
::::		[4mSelf check[0m		 ::::
:: [OK] IP forwarding is enabled
:: [OK] Iptables MASQUERADE rule set
:: [OK] WireGuard is running
:: [OK] WireGuard is enabled (it will automatically start on reboot)
:: [OK] WireGuard is listening on port 51820/udp
=============================================
:::: Having trouble connecting? Take a look at the FAQ:
:::: [1mhttps://github.com/pivpn/pivpn/wiki/FAQ[0m
=============================================
:::: [1mWARNING[0m: This script should have automatically masked sensitive       ::::
:::: information, however, still make sure that [4mPrivateKey[0m, [4mPublicKey[0m      ::::
:::: and [4mPresharedKey[0m are masked before reporting an issue. An example key ::::
:::: that you should NOT see in this log looks like this:                  ::::
:::: YIAoJVsdIeyvXfGGDDadHh6AxsMRymZTnnzZoAb9cxRe                          ::::
=============================================
::::		[4mDebug complete[0m		 ::::
`

**Comment by orazioedoardo** [comment]
> pivpnDNS1=9.9.9.9
> pivpnDNS2=149.112.112.112

Looks like you chose Quad9, not Cloudflare.

> With the VPN on, I get nine servers. These are from 'Woody Net'...

I checked this and apparently Quad9 uses the WoodyNet ISP, seems fine then.

However, since you are asking why is the IP address not changing when on VPN, you might want to read this: https://github.com/pivpn/pivpn/issues/34

**Comment by isaac7437** [comment]
Thanks, @orazioedoardo, I thought I selected Cloudflare. Is there any way of changing this without having to do the install again? 

> However, since you are asking why is the IP address not changing when on VPN, you might want to read this: #34

Helpful!

**Comment by orazioedoardo** [comment]
Just edit the DNS section in the WireGuard app.

**Comment by isaac7437** [comment]
> Just edit the DNS section in the WireGuard app.

Thanks, I've changed the DNS to this...

![Screenshot_20210529-141414_WireGuard.jpg](https://user-images.githubusercontent.com/50076680/120071674-47588180-c088-11eb-991d-4b271c24e9e0.jpg)

When I do a DNS leak test, it comes up with one Cloudflare server.

**Comment by orazioedoardo** [comment]
Yes it’s correct.

**Comment by isaac7437** [comment]
> Yes it’s correct.

Great. Thanks, everyone for your help!

**Comment by O643874** [comment]
I have a similar problem, in which our Git admins have allowed inbound git requests from intranet IPs or VPN IPs. However (and very strangely), browser based access to GitHub works fine from a browser, but fails when using Git command line. And even curiouser, when we do a "curl ifconfig.me" from Windows command line, it DOES show a source IP of the VPN, BUT when I use GIT command-line, it gets the IP provided by my ISP and says that it is not whitelisted.
