### ISSUE TITLE
[FR] <Increase Key Size Wireguard>

### ISSUE THREAD

**Issue by jonathanmmm** [pivpn/pivpn#1320]
Hi,

I saw that Wireguard only supports 128 bit size key, is it possible to support a key of size 256 bit (in openvpn config I would choose 4096 bit), as to acess a server more strength is better to have stronger cipher than to have a bit more performance. (even a pi can be used that way to get access to a network for administration e.g. home network).

If there is a manual fix which file I have to edit in the script or so, that would also be great :)

Thanks :-)

**Comment by orazioedoardo** [comment]
No, WireGuard only supports Curve25519, which provides "only" 128 bits of security (although technically it's a 256 bit keypair).

Even if you could change to a bigger keypair, like with OpenVPN, where you can go up to 521, the strength would change from "unbreakable with current technology" to "unbreakable with current technology".
