### ISSUE TITLE
[Support] Unable to install

### ISSUE THREAD

**Issue by MichaelJTritter** [pivpn/pivpn#1324]
## In raising this issue, I confirm the following:

`{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

### Console output of      `curl -L install.pivpn.io | bash`
```
<!-- 100   162  100   162    0     0    383      0 --:--:-- --:--:-- --:--:--   384
100 84313  100 84313    0     0  96689      0 --:--:-- --:--:-- --:--:--  580k
:::
::: sudo will be used for the install.
::: Hostname length OK
::: Verifying free disk space...
:::
::: Package Cache update is needed, running apt-get update -y ...
 done!
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: There are 24 updates available for your system!
::: We recommend you update your OS after installing PiVPN!
:::
:::    Checking for git... already installed!
:::    Checking for tar... already installed!
:::    Checking for wget... already installed!
:::    Checking for curl... already installed!
:::    Checking for grep... already installed!
:::    Checking for dnsutils... already installed!
:::    Checking for whiptail... already installed!
:::    Checking for net-tools... already installed!
:::    Checking for bsdmainutils... already installed!
:::    Checking for dhcpcd5... already installed!
:::    Checking for iptables-persistent... not installed!
:::    Failed to install iptables-persistent!
Reading package lists...
Building dependency tree...
Reading state information...
The following package was automatically installed and is no longer required:
  python-colorzero
Use 'sudo apt autoremove' to remove it.
The following additional packages will be installed:
  netfilter-persistent
The following NEW packages will be installed:
  iptables-persistent netfilter-persistent
0 upgraded, 2 newly installed, 0 to remove and 25 not upgraded.
Need to get 22.0 kB of archives.
After this operation, 81.9 kB of additional disk space will be used.
Get:1 https://1v2.cc:443/raspbian buster/main armhf netfilter-persistent all 1.0.11+deb10u1 [10.2 kB]
Get:2 https://1v2.cc:443/raspbian buster/main armhf iptables-persistent all 1.0.11+deb10u1 [11.8 kB]
Err:1 https://1v2.cc:443/raspbian buster/main armhf netfilter-persistent all 1.0.11+deb10u1
  File has unexpected size (6508 != 10220). Mirror sync in progress? [IP: 199.195.248.73 443]
  Hashes of expected file:
   - SHA256:0459aa9676eb66b90e97f25ea19e21807a1c0b86cf74f487274a819d37da01d7
   - SHA1:a9ef7094e3a03f208d9dc4c96597179cba55f22c [weak]
   - MD5Sum:a0aef261b07e7a1711c1c3bd029fb309 [weak]
   - Filesize:10220 [weak]
Err:2 https://1v2.cc:443/raspbian buster/main armhf iptables-persistent all 1.0.11+deb10u1
  File has unexpected size (6508 != 10220). Mirror sync in progress? [IP: 199.195.248.73 443]
  Hashes of expected file:
   - SHA256:23ad28b6bde862d480fcb27ca749f084e4941f2a4320f9d6eba9114d34b06028
   - SHA1:beb2bbcccf2a8a093b3f1afcf89e19b656c4db54 [weak]
   - MD5Sum:7383ac76986791e6725af3eaebdcb551 [weak]
   - Filesize:11796 [weak]
E: Failed to fetch https://1v2.cc:443/login  File has unexpected size (6508 != 10220). Mirror sync in progress? [IP: 199.195.248.73 443]
   Hashes of expected file:
    - SHA256:0459aa9676eb66b90e97f25ea19e21807a1c0b86cf74f487274a819d37da01d7
    - SHA1:a9ef7094e3a03f208d9dc4c96597179cba55f22c [weak]
    - MD5Sum:a0aef261b07e7a1711c1c3bd029fb309 [weak]
    - Filesize:10220 [weak]
E: Failed to fetch https://1v2.cc:443/login  File has unexpected size (6508 != 10220). Mirror sync in progress? [IP: 199.195.248.73 443]
   Hashes of expected file:
    - SHA256:23ad28b6bde862d480fcb27ca749f084e4941f2a4320f9d6eba9114d34b06028
    - SHA1:beb2bbcccf2a8a093b3f1afcf89e19b656c4db54 [weak]
    - MD5Sum:7383ac76986791e6725af3eaebdcb551 [weak]
    - Filesize:11796 [weak]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

```

### Console output of      `pivpn add` or `pivpn add nopass`
```
  Output Here
```

### Console output of      `pivpn debug`
```
  Output Here
```
### Have you taken any steps towards solving your issue?
```
I disabled PiHole as well to prevent filtering issues. I've already ran sudo apt-get update, sudo apt full-upgrade --fix-missing and sudo apt-update. My internet connection is working.
```

**Comment by orazioedoardo** [comment]
This is an issue with your APT mirror, not related with PiVPN.

**Comment by MichaelJTritter** [comment]
Ok, and for those of us who don't know how to do that, how do we do that? I thought thats what apt-get update does.

**Comment by orazioedoardo** [comment]
Well, let's take a look at the content of the  `/etc/apt/sources.list` file.

**Comment by MichaelJTritter** [comment]
Mine is missing, very curious.

**Comment by orazioedoardo** [comment]
Really? What's the output of `find /etc/apt`

**Comment by MichaelJTritter** [comment]
No such file or directory.

**Comment by orazioedoardo** [comment]
Are you running those commands on the Raspberry Pi?

**Comment by MichaelJTritter** [comment]
I'm doing it through SSH on Putty to the Pi - as I am not home, I can't physically do it on the Pi itself (and Teamviewer is terrible).

**Comment by orazioedoardo** [comment]
> I'm doing it through SSH on Putty to the Pi

Fine, though if the last `find` command gives you `No such file or directory.` then there is some serious breakage on your Pi.

**Comment by MichaelJTritter** [comment]
It works fine though, which is odd, any thoughts? Should I reformat/start over or?

**Comment by orazioedoardo** [comment]
Can you verify first that the folder and the file do not actually exist? I don’t think the apt package manager would even start if those files are missing.

**Comment by MichaelJTritter** [comment]
I actually did find it, for some reason, find etc/apt/ didn't work, but when I did a find /etc, I copied and pasted the entire thing into word and searched for apt, I was able to find it, I found this: /etc/apt - which matches what you said to find.

**Comment by orazioedoardo** [comment]
> I actually did find it, for some reason, find etc/apt/ didn't work

`etc/apt/` is different from `/etc/apt/`. The former searches in the current directory, the latter starts from the root / directory, which is what we wanted.

Post the current content of the `/etc/apt/sources.list` file (between code quotes).

**Comment by MichaelJTritter** [comment]
Here is the information: 

deb http://raspbian.raspberrypi.org/raspbian/ buster main contrib non-free rpi
# Uncomment line below then 'apt-get update' to enable 'apt-get source'
deb-src http://raspbian.raspberrypi.org/raspbian/ buster main contrib non-free $

**Comment by orazioedoardo** [comment]
It contains the default repo, so can you run `sudo apt update`?

**Comment by MichaelJTritter** [comment]
![image](https://user-images.githubusercontent.com/7680382/123424886-6c5ce900-d58f-11eb-98e0-853819071545.png)

Kind of a newb to this Linux stuff, only know enough to be dangerous lol.

**Comment by orazioedoardo** [comment]
No error reported, probably that was a transient issue with the mirror you where being redirected to. You should be able to install PiVPN now.

**Comment by MichaelJTritter** [comment]
I did that, still same thing.
![image](https://user-images.githubusercontent.com/7680382/123428558-f14a0180-d593-11eb-9cd3-7b7d384b1f1b.png)

**Comment by orazioedoardo** [comment]
Let's set mirrors explicitly: open `/etc/apt/sources.list` and replace the URLs (after `deb` and before `buster`) with one of these mirrors, usually the closest to you: https://www.raspbian.org/RaspbianMirrors. Then update the package list and the system with `sudo apt update && sudo apt upgrade`.

By the way if you have difficulties even using APT or Linux in general, you should become more familiar with those first.

**Comment by MichaelJTritter** [comment]
Greetings,

That fixed it, thanks!
