### ISSUE TITLE
Profile was remove from server but client still able to connect

### ISSUE THREAD

**Issue by williamgh2019** [pivpn/pivpn#1327]
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting *is* directly related to the pivpn installer script.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

**Describe the bug**
When I remove an account in server but that VPN profile still be able connect from the phone to server.

**To Reproduce**
1. Go to Ubuntu server then remove a VPN profile
2. Open up WireGuard iOS app and connect
3. The VPN symbol at top bar is connect to server 

**Expected behavior**
It would be error unable to connect to server. 

**Screenshots**
![image](https://user-images.githubusercontent.com/17005582/123540491-72a6bd00-d769-11eb-8047-7b343aaa11f6.jpeg)

**Smartphone (please complete the following information):**
 - VPN Protocol: WireGuard 
 - Device: iPhone 8+
 - OS: iOS 
 - Version 14.4.2

**Comment by 4s3ti** [comment]
Can you still reach the internet when connected after revoking?

**Comment by williamgh2019** [comment]
Cannot access internet only VPN can connect as normal and my LAN IP can't access too but why VPN still can connect?

**Comment by 4s3ti** [comment]
well then its not working ... can we get some logs? I guess that is not pivpn related at all but rather wireguard.

**Comment by shelleycat485** [comment]
Can you press the > sign, and look at the stats.  Then can you confirm that the client is actually connected and you get traffic.  You may just be trying to connect and actually there is no traffic - look for the data bytes counting up on that second screen.
