### ISSUE TITLE
Not receiving any packets

### ISSUE THREAD

**Issue by Wafflewithketchup** [pivpn/pivpn#1328]
I have run through the entire FAQ, until the end when running tcpdump and not receiving any packages.
I used to have it working perfectly, then I moved, and now I wanted to set it up again, with a new ISP & Modem/Router.
I've reinstalled PiVPN, reconnected my devices. 
I've done the setup the same as last time, but now it won't work. My DDNS is pointing to the right IP.
Debug log included at the bottom.
The FAQ also said to include the output of said commands.

```
root@DietPi:~# sudo iptables -S
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
root@DietPi:~# sudo iptables -t nat -S
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P POSTROUTING ACCEPT
-P OUTPUT ACCEPT
-A POSTROUTING -s 10.6.0.0/24 -o eth0 -m comment --comment wireguard-nat-rule -j MASQUERADE
```

[debug.log](https://github.com/pivpn/pivpn/files/6728641/debug.log)

**Comment by 4s3ti** [comment]
Checkwith your ISP if your are now being placed behind a NAT.

**Comment by TinCanTech** [comment]
Mo mention of `port_forwarding`

**Comment by Wafflewithketchup** [comment]
In the log it says that port forwarding is okay. Furthermore I've set it
correctly in my router. But I don't have too much confidence that's working
as its supposed to, as setting my pihole as dns server in the router also
doesn't seem to do much.

**Comment by shelleycat485** [comment]
If port forwarding is set up correctly, you should see the packets coming into the VPN server.   If you are not seeing any packets your port forwarding is very likely wrong.

Do you get the same result not using DDNS, just the direct address?
Have you got IPv6 set up?  If so, try again with it all disabled?  (Not that I am against IPV6 but pivpn does not support it)

what I would do is check port forwarding - for example set up an alternate port forwarding to a service you can control locally and check that works -  set up a HTTP server (say port 8080) and check that your port forwarding can get to that port 8080 from outside.

**Comment by Wafflewithketchup** [comment]
When I use the direct adress I get the same result as with the DDNS.
I use unbound (should be configured for both, not sure it works though), but pihole is setup for both ipv4 and 6, this is not something I had to change last time to get it to work though.
I don't know how to set up a http server? But when running tcpdump with my phone on wifi it does work fine. I assume it's the portforwarding then. I'll check with my ISP when I have some time. Seeing how that's changed it seems the most likely.

**Comment by TinCanTech** [comment]
> In the log it says that port forwarding is okay

No, it says that `ip_forwarding` is enabled. 

The script does not test for `port_forwarding` on your router because that is not something which it can do.

**Comment by orazioedoardo** [comment]
> The script does not test for port_forwarding on your router because that is not something which it can do.

This would be a nice addition, where the script or a binary requests an external server (for example `reachabilitycheck.pivpn.io`) to send a specific packet to the VPN port.

**Comment by TinCanTech** [comment]
Nope.

IP does not work like that ..

**Comment by orazioedoardo** [comment]
Why not? A PiVPN script could request an API on `reachabilitycheck.pivpn.io` to send a packet to the VPN port. If the script receives such packet, it responds to the external server, which will confirm via the same API that the port is open.

**Comment by TinCanTech** [comment]
> If the **script** receives such packet, it responds to the external server

OK, I meant _if the VPN server_ received such a packet then it would not respond.

**Comment by 4s3ti** [comment]
closing this one. this should be added as feature request to further discuss how this can be implemented.
