### ISSUE TITLE
[BUG] Wireguard Timeouts

### ISSUE THREAD

**Issue by xLogiiCx** [pivpn/pivpn#1329]
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*.
- [] The issue I am reporting *is* directly related to the pivpn installer script.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

**Describe the bug**

Hello, 
I am using PiVPN (Wireguard) with Pihole and Unbound on my RaspberryPI 4B.
When i use the Wireguard Config on my Andriod Phone and Route all Traffic to the Pi, 
my Requests time out. 
However in my Pihole query log i can still see the DNS lookup for the Domain. 
This only happens, when i am **not** connected directly to my LAN.
e.g. When i am connected with my Phones mobile data the requests time out. 
When i am connected to my WLAN (VPN still on with Kill Switch) the requests work perfectly. 
UFW is enabled but PiVPN added its rules. 

`pivpn -d` return:

```
::: Generating Debug Output
::::		PiVPN debug		 ::::
=============================================
::::		Latest commit		 ::::
commit 5aa0de636f32fd674b77a2b3dd64d97b51680707
Author: 4s3ti <4s3ti@protonmail.com>
Date:   Mon May 31 21:01:46 2021 +0200

    IRC From freenode to libera.chat
    
    Changed info about IRC Chanel,
    Chanel moved from freenode to libera.chat
=============================================
::::	    Installation settings    	 ::::
PLAT=Raspbian
OSCN=buster
USING_UFW=1
IPv4dev=eth0
dhcpReserv=1
IPv4addr=192.168.178.200/23
IPv4gw=192.168.178.1
install_user=pi
install_home=/home/pi
VPN=wireguard
pivpnPORT=REDACTED
pivpnDNS1=192.168.178.200
pivpnDNS2=10.6.0.1
pivpnHOST=REDACTED
pivpnPROTO=udp
pivpnMTU=1420
pivpnDEV=wg0
pivpnNET=10.6.0.0
subnetClass=24
ALLOWED_IPS="0.0.0.0/0, ::0/0"
UNATTUPG=1
INSTALLED_PACKAGES=()
=============================================
::::  Server configuration shown below   ::::
[Interface]
PrivateKey = server_priv
Address = 10.6.0.1/24
MTU = 1420
ListenPort = REDACTED
### begin phone ###
[Peer]
PublicKey = phone_pub
PresharedKey = phone_psk
AllowedIPs = 10.6.0.2/32
### end phone ###
=============================================
::::  Client configuration shown below   ::::
[Interface]
PrivateKey = phone_priv
Address = 10.6.0.2/24
MTU = 1420
DNS = 192.168.178.200, 10.6.0.1

[Peer]
PublicKey = server_pub
PresharedKey = phone_psk
Endpoint = REDACTED:REDACTED
AllowedIPs = 0.0.0.0/0, ::0/0
=============================================
:::: 	Recursive list of files in	 ::::
::::	/etc/wireguard shown below	 ::::
/etc/wireguard:
configs
keys
wg0.conf

/etc/wireguard/configs:
clients.txt
phone.conf

/etc/wireguard/keys:
phone_priv
phone_priv_psk
phone_priv_pub
server_priv
server_pub
=============================================
::::		Self check		 ::::
:: [OK] IP forwarding is enabled
:: [OK] Ufw is enabled
:: [OK] Iptables MASQUERADE rule set
:: [OK] Ufw input rule set
:: [OK] Ufw forwarding rule set
:: [OK] WireGuard is running
:: [OK] WireGuard is enabled (it will automatically start on reboot)
:: [OK] WireGuard is listening on port REDACTED/udp
=============================================
:::: Having trouble connecting? Take a look at the FAQ:
:::: https://github.com/pivpn/pivpn/wiki/FAQ
=============================================
:::: WARNING: This script should have automatically masked sensitive       ::::
:::: information, however, still make sure that PrivateKey, PublicKey      ::::
:::: and PresharedKey are masked before reporting an issue. An example key ::::
:::: that you should NOT see in this log looks like this:                  ::::
:::: YIAoJVsdIeyvXfGGDDadHh6AxsMRymZTnnzZoAb9cxRe                          ::::
=============================================
::::		Debug complete		 ::::
::: 
::: Debug output completed above.
::: Copy saved to /tmp/debug.log
:::
```

**Output `sudo ufw status verbose`**

```
Status: active
Logging: on (low)
Default: deny (incoming), allow (outgoing), deny (routed)
New profiles: skip

To                         Action      From
--                         ------      ----
REDACTED/udp               ALLOW IN    Anywhere                   # allow-wireguard
ssh                        ALLOW IN    192.168.178.0/23          
53                         ALLOW IN    192.168.178.0/23          
80                         ALLOW IN    192.168.178.0/23          
53                         ALLOW IN    10.6.0.0/24               
80                         ALLOW IN    10.6.0.0/24               
ssh                        ALLOW IN    10.6.0.0/24               
REDACTED/udp (v6)          ALLOW IN    Anywhere (v6)              # allow-wireguard

Anywhere on eth0           ALLOW FWD   10.6.0.0/24 on wg0
```

**Expected behavior**
All my Traffic should go through the Pi/My Local Network using Pihole as DNS and without timing out. 

**Smartphone (please complete the following information):**
 - VPN Protocol: Wireguard
 - Device: Samsung Galaxy S20 Ultra
 - OS: Android
 - Version 10

**Additional context**
On Website such as canyouseeme.org my Port is not shown as forwarded, but i guess its an Anti Scan Feature of my Router because the DNS Requests are "going through".

**Comment by orazioedoardo** [comment]
Have you forwarded the port?

**Comment by xLogiiCx** [comment]
Yes, the Port is forwarded. I guess without it the DNS Requests also would not be in the Pihole log.
And i already did these 5 steps.

**Comment by orazioedoardo** [comment]
Try the troubleshooting: https://docs.pivpn.io/faq.html#how-do-i-troubleshoot-connection-issues

**Comment by xLogiiCx** [comment]
Already tried everything in that guide. Also i tried reinstalling everything.

**Comment by orazioedoardo** [comment]
No packets then? Do you have a single router between the pi and the internet?

**Comment by xLogiiCx** [comment]
Yes, its a single router. 
Like i said DNS Requests are working perfectly.
TCPDump also shows Packets when accessing a Website. 
But still the Site times out.

**Comment by orazioedoardo** [comment]
This is sometimes a symptom of too high MTU. In the WireGuard Android app lower the MTU by decrements of 10 until you find the highest that works.

**Comment by xLogiiCx** [comment]
Ill try that and report back.

**Comment by xLogiiCx** [comment]
Set MTU to 1400 and it seems to work. 
Thanks.
