### ISSUE TITLE
TLS handshake failed due to not receiving any packets.

### ISSUE THREAD

**Issue by RWTHLHK** [pivpn/pivpn#1330]
I installed pivpn on my raspberry pi 4B and openvpn client on both my smart phone and laptop. I don't have public IP so used DDNS by noip.com. But i got the following error when connecting:
TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
TLS Error: TLS handshake failed
Then I troubleshooted the issues following the steps online and got the following feedback:
![image](https://user-images.githubusercontent.com/43910101/124520512-007b4b80-dded-11eb-8711-3b493a41112e.png)
No error occurs. Then I check the ip and other information as the steps tell me.  All of them are correct.
Afterwards I tried to capture the packets by command  tcpdump -n -i wlan0 udp port 1194( I indeed use wlan connection). and found no packets coming in and out, exactly like the given unsuccessful example .
Finally i ran command sudo iptables -S and sudo iptables -t nat -S, then got:
![image](https://user-images.githubusercontent.com/43910101/124521954-b779c600-ddf1-11eb-8f23-ed8b18ca046d.png)
It seems correct......
My router is a Huawei LTE router B818-263 via 4G connects. So my guess is that the port forwarding is ineffective, however, I tried to ask for public IP before and got refused. So asking for a public IP is also a dead end. I'd like to ask is there any another way to fix this?  Is it possible to get vpn with aid of  tunneling of ngrok?

**Comment by orazioedoardo** [comment]
First off, please do not post text as images, post the actual text. Second, unfortunately is very common among cellular connection to be under NAT, as you figured out. This is unlikely to change unless we switch to IPv6 which has a larger address space.

>  I'd like to ask is there any another way to fix this?

You can get around using two raspberry pi, one of which has a public IP. I've outlined some of the steps here but you need a bit of knowledge of networks and the ability to add static routes on the router: https://github.com/pivpn/pivpn/issues/1150#issuecomment-711964267

> Is it possible to get vpn with aid of tunneling of ngrok?

Possibly, but that's another project.

**Comment by RWTHLHK** [comment]
> First off, please do not post text as images, post the actual text. Second, unfortunately is very common among cellular connection to be under NAT, as you figured out. This is unlikely to change unless we switch to IPv6 which has a larger address space.
> 
> > I'd like to ask is there any another way to fix this?
> 
> You can get around using two raspberry pi, one of which has a public IP. I've outlined some of the steps here but you need a bit of knowledge of networks and the ability to add static routes on the router: [#1150 (comment)](https://github.com/pivpn/pivpn/issues/1150#issuecomment-711964267)
> 
> > Is it possible to get vpn with aid of tunneling of ngrok?
> 
> Possibly, but that's another project.

ok, thank you very much! Sry, this is the first time I use github to ask question. I don't know much about the posting rules.

**Comment by orazioedoardo** [comment]
I don't think there is much to add here, so I'm closing the issue.
