### ISSUE TITLE
[Support] Choose which devices to have VPN

### ISSUE THREAD

**Issue by asyba** [pivpn/pivpn#1331]
Can I choose which devices to have VPN?

Background:

Im looking to setup a VPN on my RPI 4b with Pi-hole as DNS.
(All devices will use DNS to the RPI pi-hole.)

I want to choose some devices to be connected to the VPN and other devices not.
The devices that are connected to the VPN some times I will need to disable the vpn.

The VPN main use for me is for streaming not need for encryption/security.
I want to choose which devices I want to use this VPN, I don't want the whole network I just want some IPs.
(special for 2 Apple TV and one notebook to access content from US)

**Comment by orazioedoardo** [comment]
PiVPN lets you install a VPN server to allow remote clients to securely connect to your network and tunnel their internet through your home. It's not a VPN client that connects to commercial VPN services to bypass geo restrictions.
