### ISSUE TITLE
WireGuard stops working after pi upgrade

### ISSUE THREAD

**Issue by DJFraz** [pivpn/pivpn#1332]
I’m running ubuntu on my pi 4 version B. Whenever I update my pi, WireGuard stops functioning and I have to uninstall/reinstall pivpn. I’m guessing this has something to do with the kernel being updated. 

I attempted to restore a backup I made with pivpn prior to it no longer working, but still couldn’t get things working again. I’ll probably have to start from scratch and have to readd all my clients again. 

Is there an easier way to do all this or is this just how it is with WireGuard on pi?

thanks.

**Comment by orazioedoardo** [comment]
Both Raspbian 10 and Ubuntu 20.04 (and later) have been shipping the WireGuard bundled with the kernel for quite some time now. I've not tested Ubuntu lately but on Raspbian I haven't experienced a breakage on kernel upgrades in the last six months or more. Are you using a custom kernel? Perhaps post the debug log here the next time it breaks so we can attempt to figure out.

**Comment by TheUntouchable** [comment]
> Important! Avoid using rpi-update if you plan to run WireGuard. rpi-update installs development kernel that don't always come with matching kernel headers, which are required to successfully compile the module.
> 
>     Reinstall latest kernel and kernel headers: sudo apt install --reinstall raspberrypi-kernel raspberrypi-kernel-headers.
>     Reboot into the new kernel: sudo reboot.
>     Recompile WireGuard kernel module: sudo dpkg-reconfigure wireguard-dkms.
>     Restart WireGuard (you should get no output): sudo systemctl restart wg-quick@wg0.
>     Run pivpn -d and verify that all checks are [OK].
https://github.com/pivpn/pivpn/wiki/WireGuard#how-to-i-fix-a-broken-wireguard-update

**Comment by DJFraz** [comment]
> If by "pi upgrade" you mean running "rpi-update".

Nope. I've only ever ran `sudo apt upgrade` on it as I run Ubuntu for Pi.

**Comment by TheUntouchable** [comment]
Mh okay, running here on raspberry os lite without any prolems since months.. :)

**Comment by orazioedoardo** [comment]
At most you need to do what @TheUntouchable suggested, definitely you don't need to reinstall PiVPN. Can't say much besides wait for the issue to come up again and then take a look.

**Comment by tobiabocchi** [comment]
I've had a similar problem after updating Ubuntu.. I solved it reloading systemctl's deamon with `sudo systemctl daemon-reload` and `sudo systmectl restart wg-quick@wg0.service`
