### ISSUE TITLE
Cant install pivpn on raspberry pi. Crash at user select menu

### ISSUE THREAD

**Issue by reubengidlow** [pivpn/pivpn#1334]
Trying to install pivpn onto my pi. Get half way through the config to the point of selecting a user and then it crashes. im no expert and was just following forums so can anyone give me some help

this is what the terminal shows:

pi@raspberrypi:~ $ sudo curl --insecure -L https://install.pivpn.io | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   162  100   162    0     0    786      0 --:--:-- --:--:-- --:--:--   790
100 84313  100 84313    0     0   210k      0 --:--:-- --:--:-- --:--:--  210k
:::
::: sudo will be used for the install.
::: Hostname length OK
::: Verifying free disk space...
:::
::: Package Cache update is needed, running apt-get update -y ...
 done!
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: Your system is up to date! Continuing with PiVPN installation...
:::    Checking for git... already installed!
:::    Checking for tar... already installed!
:::    Checking for wget... already installed!
:::    Checking for curl... already installed!
:::    Checking for grep... already installed!
:::    Checking for dnsutils... already installed!
:::    Checking for whiptail... already installed!
:::    Checking for net-tools... already installed!
:::    Checking for bsdmainutils... already installed!
:::    Checking for dhcpcd5... already installed!
:::    Checking for iptables-persistent... already installed!
::: Using User: pi
:::
::: Checking for existing base files...
:::    Checking /usr/local/src/pivpn is a repo... not found!
:::    Cloning https://github.com/pivpn/pivpn.git into /usr/local/src/pivpn... [/]  fatal: unable to access 'https://github.com/pivpn/pivpn.git/': server certificate verification failed. CAfile: none CRLfile: none
main: line 1034: cd: /usr/local/src/pivpn: No such file or directory

**Comment by orazioedoardo** [comment]
Why are you using the `--insecure` flag? You are making yourself vulnerable to attacks. Just run `curl -L https://install.pivpn.io | bash`

**Comment by reubengidlow** [comment]
> Why are you using the `--insecure` flag? You are making yourself vulnerable to attacks. Just run `curl -L https://install.pivpn.io | bash`

I used it because `curl -L https://install.pivpn.io | bash` doesn't work

**Comment by orazioedoardo** [comment]
> I used it because `curl -L https://install.pivpn.io | bash` doesn't work

This means that there are some SSL issues with your Raspbian installation, or (hopefully not), active attack on your network. You should not attempt to bypass security measures.

1) Are you trying to install PiVPN on a clean install of Raspberry Pi OS?
2) Is you Raspberry Pi clock correct? You can check by running `date`

**Comment by reubengidlow** [comment]
I have checked everything and there is no active attack. 

I normally use my pi for a samba file share server on the home network and have had it running as a server for the last year. 1) When I set up it was a clean raspberry pi os 2) yes the clock is correct

Is it best to start everything again from scratch and reinstall the os and rebuild the pi?

**Comment by orazioedoardo** [comment]
> Is it best to start everything again from scratch and reinstall the os and rebuild the pi?

Let's see what's going on first with the connection to GitHub: `curl -v https://github.com/pivpn/pivpn`. Do you get some secure connection error or something like that? If you do get an error, what about with another website like `https://google.com`? Since it's related to SSL certificates, you might try to reinstall the associated package `sudo apt install --reinstall ca-certificates`.

**Comment by reubengidlow** [comment]
Looks like i needed to reinstall the associated packages

Thanks for the help
