### ISSUE TITLE
[Support] Can't access network drive through OpenVPN

### ISSUE THREAD

**Issue by VaultDeveloper** [pivpn/pivpn#1336]
## In raising this issue, I confirm the following:

- [x] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

### Issue
What I need: I need to access hard drive in my home network from the outside world.
I installed pivpn on a RPI with OpenVPN. OpenVPN use the port `1195` because `1194` is already taken by my router. I don't use a domain because I have a static IP address. I can connect to the VPN without worries and make requests on the Internet.

My problem is that a hard drive connected to my router is accessible if I am in LAN, but not from the VPN from outside the network. Weirder, I can access the share drive if I plug the hard drive into a Windows 7 PC over wifi and share it. But if I connect the PC by ethernet cable I can't access the share drive anymore.

I am not very good at networking, so I need help to debug this situation. I would prefer to connect the hard drive to the router, or alternatively, share the hard drive on an ethernet connected PC. If you think this is a OpenVPN related issue let me know.

Is it possible that my ISP blocks requests based on the local IP address? How can I confirm that this is the problem?

Thank you in advance for your precious time.

### pivpn debug
```
=============================================
::::        Installation settings        ::::
PLAT=Raspbian
OSCN=buster
USING_UFW=0
IPv4dev=wlan0
dhcpReserv=1
IPv4addr=192.168.0.30/24
IPv4gw=192.168.0.1
install_user=admin
install_home=/home/admin
VPN=openvpn
pivpnPROTO=udp
pivpnPORT=1195
pivpnDNS1=9.9.9.9
pivpnDNS2=149.112.112.112
pivpnSEARCHDOMAIN=
pivpnHOST=REDACTED
TWO_POINT_FOUR=0
pivpnENCRYPT=2048
USE_PREDEFINED_DH_PARAM=1
INPUT_CHAIN_EDITED=0
FORWARD_CHAIN_EDITED=0
pivpnDEV=tun0
pivpnNET=10.8.0.0
subnetClass=24
ALLOWED_IPS=""
UNATTUPG=1
INSTALLED_PACKAGES=()
HELP_SHOWN=1
=============================================
::::  Server configuration shown below   ::::
dev tun
proto udp
port 1195
ca /etc/openvpn/easy-rsa/pki/ca.crt
cert /etc/openvpn/easy-rsa/pki/issued/raspberrypi_{{guid}}                        bb0511.crt
key /etc/openvpn/easy-rsa/pki/private/raspberrypi_{{guid}}                        bb0511.key
dh /etc/openvpn/easy-rsa/pki/dh2048.pem
topology subnet
server 10.8.0.0 255.255.255.0
# Set your primary domain name server address for clients
push "dhcp-option DNS 9.9.9.9"
push "dhcp-option DNS 149.112.112.112"
# Prevent DNS leaks on Windows
push "block-outside-dns"
# Override the Client default gateway by using 0.0.0.0/1 and
# 128.0.0.0/1 rather than 0.0.0.0/0. This has the benefit of
# overriding but not wiping out the original default gateway.
push "redirect-gateway def1"
client-to-client
client-config-dir /etc/openvpn/ccd
keepalive 15 120
remote-cert-tls client
tls-version-min 1.2
tls-auth /etc/openvpn/easy-rsa/pki/ta.key 0
cipher AES-256-CBC
auth SHA256
user openvpn
group openvpn
persist-key
persist-tun
crl-verify /etc/openvpn/crl.pem
status /var/log/openvpn-status.log 20
status-version 3
syslog
verb 3
#DuplicateCNs allow access control on a less-granular, per user basis.
#Remove # if you will manage access by user instead of device.
#duplicate-cn
# Generated for use by PiVPN.io
=============================================
::::  Client template file shown below   ::::
client
dev tun
proto udp
remote REDACTED 1195
resolv-retry infinite
nobind
key-direction 1
remote-cert-tls server
tls-version-min 1.2
verify-x509-name raspberrypi_{{guid}}bb0511 name
cipher AES-256-CBC
auth SHA256
auth-nocache
verb 3


...


=============================================
::::            Self check               ::::
:: [OK] IP forwarding is enabled
:: [OK] Iptables MASQUERADE rule set
:: [OK] OpenVPN is running
:: [OK] OpenVPN is enabled (it will automatically start on reboot)
:: [OK] OpenVPN is listening on port 1195/udp
=============================================
```

**Comment by orazioedoardo** [comment]
> I am not very good at networking, so I need help to debug this situation. I would prefer to connect the hard drive to the router, or alternatively, share the hard drive on an ethernet connected PC. If you think this is a OpenVPN related issue let me know.

Can you access other devices on the local network when using the VPN? How do you access the network drive (protocol)?

> Is it possible that my ISP blocks requests based on the local IP address? How can I confirm that this is the problem?

That's not possible, the traffic between your VPN client and your Raspberry Pi is encrypted.

**Comment by VaultDeveloper** [comment]
We haven't troubleshoot, but my partner wants a harddrive directly connected to the RPI. We do not have any trouble with this new strategy.
