### ISSUE TITLE
Issue with setting up OpenVPN on raspberryPI

### ISSUE THREAD

**Issue by FlorjanKlancar** [pivpn/pivpn#1339]
Hello,
I need help with setting up my OpenVPN server on raspberryPI, I have followed the tutorial on https://www.pivpn.io/ and after I imported my config file to mobile app it does not want to connect... It keeps saying connecting to "ip:port", then stops after timeout. I have opened the ports on both routers aswell (ISP one and mine) for the TCP port number... Does anyone have an idea what could be wrong, when I type lsod command on pi it does not show openvpn port listening, but systemctl command shows that service is running...?

Thank you in advance.

**Comment by TinCanTech** [comment]
https://forums.openvpn.net/viewtopic.php?f=4&t=32682#p100959
