### ISSUE TITLE
[Support] How do I use Pi-hole with PiVPN - docs clarification

### ISSUE THREAD

**Issue by planetahuevo** [pivpn/pivpn#1340]
## In raising this issue, I confirm the following:

- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

### Issue
On this official docs: 
https://github.com/pivpn/pivpn/wiki/WireGuard#how-do-i-use-pi-hole-with-pivpn
it says: 
Edit the PiVPN configuration with sudo nano /etc/pivpn/wireguard/setupVars.conf
Remove the pivpnDNS1=[...] and pivpnDNS2=[...] lines
Add this line pivpnDNS1=192.168.23.211 to point clients to the PiVPN IP

But it also say: 
Note that if you install PiVPN after Pi-hole, your existing Pi-hole installation will be detected and the script will ask if you want to use it as the DNS for the VPN, so you won't need to go through all these steps.

My PiVPN asked about that and I say yes. 
So my setup should be ready for both, and it seems it is working, but I wanted to check the settings to make sure and then I realise that my  config does not include this line pivpnDNS1=192.168.23.211

And instead I have this: 
pivpnDNS1=10.6.0.1   

It looks like that the VPN devices are using my local router dns and therefore using the pihole, but I want to force the DNS.
What I want is that the devices using the VPN get the dns from the pi-hole and no access to local devices. 

So my question is: 
- Do I need to leave it as it is (10.6.0.1 ) or do I need to follow that docs and change it to the local IP of my pihole (which is the same IP as the pivpn)?

### Have you searched for similar issues and solutions?
Yes , I have been reading so much, but there are so many guides and I decided to trust the docs. 
    This issue is a clarification about the official docs.

Thanks!

**Comment by 4s3ti** [comment]
By your description Should be fine, just make sure that pihole is listening on all interfaces as stated on step 5 here: 

https://docs.pivpn.io/wireguard.html#pi-hole-with-pivpn


However when you opened the ticket you got a template that asked for information that you skipped and you should have provided! without that we cannot confirm it properly.

**Comment by planetahuevo** [comment]
This has nothing to do with my setup and I did fill up the template with all the relevant information. 
You are linking me to the exact doc I am asking the question about. 
I will try again with other words: 
That link you and I shared, say it should use the local ip of the pi 

`Replace the line DNS = [...], [...] with this line DNS = 192.168.23.211`

The system automatically use 10.6.0.1, which is the internal ip of the ip, but not the local ip on my network.

Which one is right? Docs or the automated system? 

It should be 192.168.XX or 10.6.0.1?

**Comment by 4s3ti** [comment]
> This has nothing to do with my setup and I did fill up the template with all the relevant information.

For whom?? what you think is the relevant information and the *Actual* relevant information are different thinks and that is why we have a template with data for users to provide! 

Read my previous answer again!! Should be fine .. but DATA is needed to confirm!! 

Those should be the *same* device, 192.168.xx should be the lan ip, and 10.6.0.1 should be the VPN Network IP, but once again either me or anyone that might come around to help needs data!

**Comment by planetahuevo** [comment]
Hi @4s3ti 
I know they are the same device. 
I know my setup is working. 
I detected a probable problem on the docs and I tried to help here opening a ticket so the docs can be clarified for others. 

The docs should help anyone, so my particular setup, which is no particular at all, has nothing to do with this ticket. 

Please read my question as your answer is not an answer for my question at all but to a problem I do not have. Thank you for trying to help though. 

And no need to shout. I can read you perfectly without the ! marks.

**Comment by 4s3ti** [comment]
Is it that hard to provide the data? 
How can i tell you what is more correct if i have no data to see your particular setup and try to understand what's going on? 

Both should be correct, it all depends on what have you installed first as stated in the docs.

**Comment by planetahuevo** [comment]
Yes it is hard because I have destroyed the particular installation and I am not at that location until next weekend. 

If someone will install pi-hole first and then pivpn, the docs tell you to follow the automated setup. 
But then it will tell you how to do the same thing manually. 
The manual way to setup and the automatic script do different things (local ip vs 10.6.0.1). 

Maybe both options are OK, I do not know, and that is what I am asking, but I think it would be good to have consistency on the manual way vs the automatic way, so both do the same.

!! means shouting in any language, or at least strong emotion. https://en.wikipedia.org/wiki/Exclamation_mark

**Comment by 4s3ti** [comment]
> !! means shouting in any language, or at least strong emotion. https://en.wikipedia.org/wiki/Exclamation_mark

of course it is a strong affirmation, its written everywhere that incomplete issue reports might be closed without any warning, and your's is incomplete as 90% of the issues that come around here and after years of trying to make things simple for users, people steel seem to not read what's in front of their eyes, so do i get a little pissed of? of course, think everyone would! 

> Yes it is hard because I have destroyed the particular installation and I am not at that location until next weekend.

This was not written anywhere on your support request which in turn it seems not to be a support request exactly a support request, which i understood quite well from the beginning!  so in the end i might be right to be a little annoyed right? 

> Maybe both options are OK, I do not know, and that is what I am asking, but I think it would be good to have consistency on the manual way vs the automatic way, so both do the same.

The only explanation i can give you is that the option with the local ip was written before we have the automated way, also  when doing it manually it is easier for a common user to find the local ip of the raspberry pi instead  of the VPN internal IP and since pihole is listening on all interfaces both options are correct. there isn't a "more" correct one. 

Docs have their own repo, where you can make questions about it, you  can even help improving them if you know how, or by simply making a properly formulated suggestion: https://github.com/pivpn/docs

I don't think me or anyone here is that strict to not accept suggestions/improvements, even crazy ideas we take time to look at them, but in the end its annoying to have things written in different places and to take the time to make things easier for everybody and still noticing the same things every time i come around here.

**Comment by planetahuevo** [comment]
Thanks. 
I will transfer the issue to the github of the docs, as that was always the intention of this "support" (that was the only option that make some sense when creating the issue here). 

This is the answer I was looking for: 

> "The only explanation i can give you is that the option with the local ip was written before we have the automated way, also when doing it manually it is easier for a common user to find the local ip of the raspberry pi instead of the VPN internal IP and since pihole is listening on all interfaces both options are correct"

So thanks for that too. 

> I don't think me or anyone here is that strict to not accept suggestions/improvements, even crazy ideas we take time to look at them, but in the end its annoying to have things written in different places and to take the time to make things easier for everybody and still noticing the same things every time i come around here.

That is exactly why I wanted to suggest the edit on the docs, so I agree with you here too. Official docs should be the first place to look. That is what I did and it was not clear to me. 

I am not going to reply to the rest of the message as it is not relevant to the topic at all. 

Have a nice day!
