### ISSUE TITLE
[Support] OpenVPN not listening

### ISSUE THREAD

**Issue by Tripwire117** [pivpn/pivpn#1342]
## In raising this issue, I confirm the following:

`{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

### Issue
The issue I have pertains to server.pid and OpenVPN not listening. When debugging PiVPN it gives the option to restart Open VPN. Upon launching it gives an error saying server.pid does not exist. I am unsure what this file is, it's purpose nor how to re-generate it. I went as far as checking to see OpenVPN was running, it seemed to be. I tried a combination of root access/sudo to see if it was a permissions issue. 

My knowledge in linux is scarce, so any input & support would be greatly appreciated, I have looked up security enhancements months ago as I was using the the pi as a web server with remote access. I am unsure if there is a filter I have to have in place allowing the ports or not. If there is I don't recall how to access this info.

### Have you searched for similar issues and solutions?
    (yes/no / which issues?)
Yes, Some other users were having similar issues, however none pertaining to server.pid/access to the file.

### Console output of      `curl -L install.pivpn.io | bash`
```
  Output Here
```

### Console output of      `pivpn add` or `pivpn add nopass`
```
  Output Here
```
=============================================
:::: Having trouble connecting? Take a look at the FAQ:
:::: https://github.com/pivpn/pivpn/wiki/FAQ
=============================================
::::      Snippet of the server log      ::::

https://pastebin.com/hZ4J92sA

=============================================

### Console output of      `pivpn debug`
```
  Output Here
```
### Have you taken any steps towards solving your issue?
```
- Reinstalled OVPN, PiVpn
- Checked Ovpn service, it appears to be running
- Re-configured the application several times
```

**Comment by orazioedoardo** [comment]
Please fill the issue template when opening a new issue, particularly  `pivpn debug`.
