### ISSUE TITLE
Where's the wiki?

### ISSUE THREAD

**Issue by Lenbok** [pivpn/pivpn#1345]
The main README has several links to "the wiki", e.g. https://github.com/pivpn/pivpn/wiki#testing https://github.com/pivpn/pivpn/wiki/WireGuard https://github.com/pivpn/pivpn/wiki/FAQ#how-do-i-troubleshoot-connection-issues etc, but none of those links work. There looks to be no wiki associated with the github project. Is there supposed to be a wiki still? Is the README just out of date and those documents are elsewhere?

**Comment by 4s3ti** [comment]
Thanks for the heads'up .. I have disabled it ... and might have missed to change those liks ... 

Our docs are at https://docs.pivpn.io

**Comment by 4s3ti** [comment]
Fixed in last merge
