### ISSUE TITLE
tlscrypt v2 support

### ISSUE THREAD

**Issue by tkmw1985** [pivpn/pivpn#1348]
Hello !  

Is it possible to add tlscrypt v2 in this super awsome script ?

**Comment by TinCanTech** [comment]
If you are interested in TLS-Crypt-V2 you may like to try this: https://github.com/TinCanTech/easy-tls

**Comment by tkmw1985** [comment]
Hello dear TinchCanTech !

Yes i know already about it but i do not know how to do it properly can not find step by step command or manual for understand ! 

Will be much appreciated if you point me. 

Thank you.

**Comment by TinCanTech** [comment]
There are 24 pages of help in the wiki.

If you would like to open an issue [here](https://github.com/TinCanTech/easy-tls/issues), I'll see what I can do.

**Comment by Hylosium** [comment]
Good noon,

I am trying to use easy-tls with pivpn but I have OpenVPN 2.4 installed and when I try to update to 2.5 it says that doesn't support armhf (my distribution is armbian for orangepilite, based on Ubuntu Focal, it will attach photos)
![Captura de pantalla de 2021-10-01 22-03-28](https://user-images.githubusercontent.com/90805628/135680266-b7ac456a-b2d2-48b2-8506-ab59ec6e9f0a.png) ![Captura de pantalla de 2021-10-01 22-10-12](https://user-images.githubusercontent.com/90805628/135680540-c9c980c4-b0b9-4f34-87fb-d2fa203dde53.png)

What could I do to solve this error and continuing installing [05 = Quick Start Normal mode](https://github.com/TinCanTech/easy-tls/wiki/05-=-Quick-Start-Normal-mode) I think this is what I need to use tls-crypt v2 and bypass DPI.

The code I use is:
`sudo -s`
`wget -O - https://swupdate.openvpn.net/repos/repo-public.gpg | apt-key add -`
`echo "deb http://build.openvpn.net/debian/openvpn/stable focal main" > /etc/apt/sources.list.d/openvpn-aptrepo.list`
`exit`

Thanks in advance.

**Comment by 4s3ti** [comment]
Moving thread to discussions.
