### ISSUE TITLE
Install is fine, but never a connection. 

### ISSUE THREAD

**Issue by Esteidinger** [pivpn/pivpn#135]
Hi, 

Having trouble getting this setup. The installer runs just fine. But when I try to connect it never responds. 

I have a first GEN Pi. 
I've run the installer a number of times in different fashions. 
I tried UDP first and when that didn't work I tried TCP. 
Originally I was using a wifi dongle, but i switched to hardwired as a test. 
On my last install I started with a new NOOBS install, hardwired, using TCP. 

I called comcast who said they are not blocking my ports, and to call router manufacture. 
I called Apple and they said my time capsule (Airport Extreme) is working as designed. And the IP cameras I have externally available work great also. 

I'm not really sure where else to go for troubleshooting. I would love some advice. 

I'm testing using the OpenVPN client app, or Tunnelblick on my mac. 

Here is the output from an attempted connect. 

[OpenVPN_failure.txt](https://github.com/pivpn/pivpn/files/555816/OpenVPN_failure.txt)

**Comment by redfast00** [comment]
It seems that the client isn't able to connect to the server. Have you portforwarded your Pi to the internet?

**Comment by Esteidinger** [comment]
I checked the logs in var and they are empty. 

Yes, I have done the port forwarding. I called my isp and originally they said that everything was fine. I think I have more to talk with them about.

**Comment by Esteidinger** [comment]
Comast is unable to help. I've opened a ticket with openVPN, but the PiVPN product install's a few other bits that might be interesting to test. Any advice?

**Comment by 0-kaladin** [comment]
Really just seems like that port and external IP you are using are not getting through to your pi. Really just focus on ensuring your port forward in your router is working correctly.

**Comment by 38aytac38** [comment]
I have the same problem the pi wont open port 1194

**Comment by redfast00** [comment]
@38aytac38 that's because you have to do it yourself: you have to log into your router and portforward the port.

**Comment by celsian** [comment]
I knew I was going to be setting this up so I forwarded my port in advance. Later during setup via SSH install was successful, but like @Esteidinger I was unable to connect. After confirming the port, ensuring DNS was pointing to the right IP and trying a connection direct to IP I finally decided to check my router settings again. My port forwarding was indeed setup, but for TCP only. I had intended to set it up as "BOTH" which would have included UDP. I made the change and the connection was immediately successful. Thanks guys.

**Comment by RyoisMC** [comment]
when i see what ports are open on the pi it doesn't show 1194

**Comment by redfast00** [comment]
@RyoisMC: how did you check the open ports on your Pi?

**Comment by celsian** [comment]
@RyoisMC This is a function of your router, not the pi. If you share your router's manufacturer and model number we might be able to help you open the appropriate port. Again, this MUST be done on the device between the Pi and your Modem.

**Comment by RyoisMC** [comment]
@celsia and @redfast00 i used fing to scan my raspberry pi and my router is a NETGEAR WNR2000v5 I think. I've port forwarded 1194 as an UPD

**Comment by celsian** [comment]
@RyoisMC If you port forwarded then you should have no problem connecting. Remember that you cannot initiate a VPN connection on the same network as the server. If you're trying to connect at home, tether off your cell phone.

Realistically your Pi should have a static IP (that way the DHCP lease doesn't run out and change your IP, because your port 1194 would then be forwarded to the wrong address.)

**Comment by RyoisMC** [comment]
@celsian thx ill try tethered, how about different wifi network?

**Comment by celsian** [comment]
@ryoismc Any other network besides the one your server is connected to should work.

**Comment by RyoisMC** [comment]
@celsian could i do it connected to a different router but same network and ip

**Comment by celsian** [comment]
No.

**Comment by RyoisMC** [comment]
@celsian k thx
ill do it

**Comment by fpessolano** [comment]
Same problem on fresh install. Yes forwarding port is open, all seemed fine. My client cannot connect.

**Comment by 0-kaladin** [comment]
closing.
