### ISSUE TITLE
[BUG] <Bug Description Here>

### ISSUE THREAD

**Issue by Nottoknow2** [pivpn/pivpn#1351]
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting *is* directly related to the pivpn installer script.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

**Describe the bug**

**To Reproduce**
1. Install pihole 
2. Install pivpn with pihole as dns server and default settings 
3. Make a client and qr code
4. Import it on phone they search anything then it is incredibly slow/no access

**Expected behavior**
Being able to search w/o ads as normal

**Desktop (please complete the following information):**
 - WireGuard 
 - OS: Ubuntu 20.04
 - Version Latest as of 9/2/2021

**Smartphone (please complete the following information):**
 - WireGuard 
 - Device: iPhone 11
 - OS: iOS 14.4
 - Version Latest as of 9/2/2021

**Additional context**
It did say connection is behind a nat

**Comment by 4s3ti** [comment]
This is not a bug, At the minimum its a Support request!

**Comment by 2boot** [comment]
My apologies for contacting on a closed post but I can see no other way.

If I click the "support" and "bug report" requests from this page https://github.com/pivpn/pivpn/discussions 
I get led to these links
https://raw.githubusercontent.com/pivpn/pivpn/master/.github/ISSUE_TEMPLATE/pivpn-report.md
https://raw.githubusercontent.com/pivpn/pivpn/master/.github/ISSUE_TEMPLATE/bug_report.md
both these result in 404 pages

I see you changed reporting 26 days ago and think somethings may not have been fully updated.
