### ISSUE TITLE
[Support] When installing and configuring PIVPN it does not connect

### ISSUE THREAD

**Issue by TheBlackmad** [pivpn/pivpn#1356]
Hello,

I am trying to make pivpn working on my Raspberry PI as an VPN Server. The objective is to get access to my local network when I am out from home. Because my ISP provided me with an IPv6 for my router, I cannot setup on my Fritzbox VPN for IPv6 (not implemented). This is the reason why I decided to create my Raspberry PI 4 with PiVPN on it and trying to forward all ports. 

So here it is the problem. I installed the PiVPN and configured it. I created a user and scan it on my mobile phone, so with the Wireguard Client I would be able to connect. I connect from my mobile and with ifconfig from a Termux terminal I see I get the IP address I got configured in Wireguard /PiVPN. However, in the connection I see the bytes sent but no bytes are received. I cannot either see any of my computers in my network. 

I know the router is properly configured, because I could try to forward a port to my Raspberry, open it to the world for a minute and I could connect with a netcat command from my mobile. So router is correctly configured. The problem seems to be on the configuration of the WireGuard/PIVPN or th IPTABLES.

Output for 'iptables -S'
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT

Output for 'iptables -t nat -S'
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P POSTROUTING ACCEPT
-P OUTPUT ACCEPT
-A POSTROUTING  -s 10.6.0.0/24 -o eth0 -m comment --comment wireguard-nat-rule -j MASQUERADE

I tried to configure this on my own, but I ended up with having no internet connection at all, so I mess it all up.

Also I followed https://docs.pivpn.io/faq/ and everything is ok, so then I open this issue.

I would be very thankful if someone could help or provide any information that may help to resolve it.

Thanks!
The Blackmad

unfortunately without any success. I have tried in the last days to play around trying to discover where I am failing making it work I have tritd.

**Comment by orazioedoardo** [comment]
> Also I followed https://docs.pivpn.io/faq/ and everything is ok, so then I open this issue.

What do you mean by "everything is ok"? What about https://docs.pivpn.io/faq/#what-to-do-if-i-see-no-packets

Please post the debug log too `pivpn debug`.

**Comment by TheBlackmad** [comment]
Hi, thanks for the response Orazio. By "everything is ok" I mean that when I follow the FAQ, I can perform the configuration as it is described in the FAQand the configuration seems to work correctly. However, I cannot seetraffic coming in if I use tcpdump over that port.

I think the problem is in the iproute that for whatever reason it does not send back. I see my mobile phone connected with Wireguard and the local IP 10.6.0.2. However, I cannot see any other computer in my network. That's why I say it should be an iprouting problem as traffic from 10.6.0.2 is not routed to my internal home network 192.168.178.0/24.
 
The 'pivpn debug' gives me the following output:
::::		PiVPN debug		 ::::
=============================================
::::		Latest commit		 ::::
Branch: master
Commit: ****************************************
Author: 4s3ti
Date: Thu Aug 5 15:12:33 2021 +0200
Summary: Latest Changes update.
=============================================
::::	    Installation settings    	 ::::
PLAT=Raspbian
OSCN=buster
USING_UFW=0
IPv4dev=eth0
dhcpReserv=1
IPv4addr=192.168.178.10/24
IPv4gw=192.168.178.1
install_user=pi
install_home=/home/pi
VPN=wireguard
pivpnPORT=51820
pivpnDNS1=8.8.8.8
pivpnDNS2=8.8.4.4
pivpnHOST=REDACTED
INPUT_CHAIN_EDITED=0
FORWARD_CHAIN_EDITED=0
pivpnPROTO=udp
pivpnMTU=1420
pivpnDEV=wg0
pivpnNET=10.6.0.0
subnetClass=24
ALLOWED_IPS="0.0.0.0/0, ::0/0"
UNATTUPG=1
INSTALLED_PACKAGES=()
=============================================
::::  Server configuration shown below   ::::
[Interface]
PrivateKey = server_priv
Address = 10.6.0.1/24
PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -D FORWARD -o wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
MTU = 1420
ListenPort = 51820
### begin TheBlackmad ###
[Peer]
PublicKey = TheBlackmad_pub
PresharedKey = TheBlackmad_psk
AllowedIPs = 10.6.0.2/32
### end TheBlackmad ###
=============================================
::::  Client configuration shown below   ::::
[Interface]
PrivateKey = TheBlackmad_priv
Address = 10.6.0.2/24
MTU = 1420
DNS = 8.8.8.8, 8.8.4.4

[Peer]
PublicKey = server_pub
PresharedKey = TheBlackmad_psk
Endpoint = [****:****:****:****:****:****:****:****]:51820
AllowedIPs = ::0/0, 10.6.0.0/24
=============================================
:::: 	Recursive list of files in	 ::::
::::	/etc/wireguard shown below	 ::::
/etc/wireguard:
configs
helper
keys
wg0.conf
wg0.conf.bk
wg0.conf.save

/etc/wireguard/configs:
clients.txt
TheBlackmad.conf

/etc/wireguard/helper:

/etc/wireguard/keys:
server_priv
server_pub
TheBlackmad_priv
TheBlackmad_psk
TheBlackmad_pub
=============================================
::::		Self check		 ::::
:: [OK] IP forwarding is enabled
:: [OK] Iptables MASQUERADE rule set
:: [OK] WireGuard is running
:: [OK] WireGuard is enabled (it will automatically start on reboot)
:: [OK] WireGuard is listening on port 51820/udp
=============================================
:::: Having trouble connecting? Take a look at the FAQ:
:::: https://docs.pivpn.io/faq
=============================================
:::: WARNING: This script should have automatically masked sensitive       ::::
:::: information, however, still make sure that PrivateKey, PublicKey      ::::
:::: and PresharedKey are masked before reporting an issue. An example key ::::
:::: that you should NOT see in this log looks like this:                  ::::
:::: YIAoJVsdIeyvXfGGDDadHh6AxsMRymZTnnzZoAb9cxRe                          ::::
=============================================
::::		Debug complete		 ::::

**Comment by orazioedoardo** [comment]
> However, I cannot seetraffic coming in if I use tcpdump over that port.

Is port forwarding enabled? Are you under CGNAT? How about [this](https://github.com/pivpn/pivpn/issues/1316#issuecomment-851269619)?

> I see my mobile phone connected with Wireguard and the local IP 10.6.0.2.

Actually, when you turn on the VPN, no connection (handshake really) is done, even though it "looks" enabled. Only when actually attempting to connect to some host, then the handshake is performed. 

> That's why I say it should be an iprouting problem as traffic from 10.6.0.2 is not routed to my internal home network 192.168.178.0/24.

This is not a problem as the PiVPN is configured such that traffic coming from VPN clients will look like coming from the Pi itself (192.168.178.10).

**Comment by TheBlackmad** [comment]
Port Forwarding is enable in my router providing access to the internet. This is a Fritzbox and I configured the Port Forwarding for this 51820. Whether I am under CGNAT it might be the case (not sure, really. How can I check it?). My ISP provides internet connection through a Dual Stack-Lite, so my Fritzbox connects to the internet through a DS-Lite and it has an IPv6. If I check my IP address on my mobile, it is actually an IPv6 and I can ping IPv6 addresses over the internet. Is CGNAT an issue reaching my home network from outside?

So if I am connected on my mobile network from my mobile device, get an 10.6.0.2 address and I ping using Termux App any computer on my network (so with 'ping 192.168.178.10'), I believe it should work as the ping is 'coming into my network' as if it were from 192.168.178.10

**Comment by orazioedoardo** [comment]
> Whether I am under CGNAT it might be the case (not sure, really. How can I check it?).

You can check online whether your ISP uses CGNAT, or check the WAN address on your router. If it is different from the IP address websites see, then you are under CGNAT.

> My ISP provides internet connection through a Dual Stack-Lite, so my Fritzbox connects to the internet through a DS-Lite and it has an IPv6. If I check my IP address on my mobile, it is actually an IPv6 and I can ping IPv6 addresses over the internet.

IPv6 only connection? (Can't help much with that). Do you have an IPv4 address too?

**Comment by TheBlackmad** [comment]
If I go to a service like https://whatismyipaddress.com/, the website sees that I have an IPv6 address (coinciding to my Ipv6 address of my laptop) and an IPv4 that is in the form of 95.0.0.0 that is actually somebody's address (a router or whatever from my ISP, but definitely not my router, as it only has an IPv6) to let me reach IPv4-type Internet. My ISP has an IPv6 infrasstructure, and to let me reach IPv4 they use a Dual-Stack system so I can also see IPv4 addresses from the internet. Whether this is using a CGNAT I do not know. From my little knowledge on IPv6 I think it is the case. 
If I go to my router, I see his IPv6 address with a network/subnet different from the IPv6 prefix that my laptop has.

If I click on the https://whatismyipaddress.com/ on my IPv6, it says that this IP address is a hostname. If I click on the IPv4 it tells me the IP address is for XXXXX.dynamic.kabel-deutschland.de. If I traceroute this address, it goes to
_gateway (192.168.178.1) 
YYYYYY.static.kabel-deutschland.de (******)
* * *
an then it never responds to the traceroute. So the IPv4 supposed to be for my router is somebody beyond my direct contact. I believe then that in IPv4, I am behind a CGNAT. 

So a public IPv4 address specific for my router, I do not have, and I am only seen as IPv6 on the Internet. That is why I am playing (or messing) with IPv6.

So, does it mean that I cannot set up a VPN connection with Wireguard, because of this CGNAT / IPv6 only, etc....?

**Comment by TheBlackmad** [comment]
I have had problem with my internet, I have restarted it and checked again. my rputer says 192.x.x.x. and whatismyipaddress says the request comes from 95.x.x.x. so it should be, on ipv4 be behind cgnat.

**Comment by orazioedoardo** [comment]
> So, does it mean that I cannot set up a VPN connection with Wireguard, because of this CGNAT / IPv6 only, etc....?

IPv6 only is not an issue, CGNAT is. There is a thread here for IPv6: https://github.com/pivpn/pivpn/issues/259

> my rputer says 192.x.x.x. and whatismyipaddress says the request comes from 95.x.x.x. so it should be, on ipv4 be behind cgnat.

192.something (I guess 192.168.178.1) is the LAN address of the router. 95.x is the internet facing address which can also be the Fritzbox WAN address (no CGNAT) or an address of the NAT device from the ISP (in case of CGNAT).

**Comment by TheBlackmad** [comment]
Hello,
the thread for IPv6 #259 helped a lot. I can now connect and Wireguard in my mobile device when connected via mobile data and through VPN, I see data being received and trasmitted.

I realized that the iptables did not route appropriately on the IPv6. I have no other access to my PiVPN Server apart from IPv6. Therefore, I had to use ip6tables instead, activate with sysctl and indicate explicitly to the PiVPN that protocol udp6/tcp6 is to be used.

Here I place my /etc/wireguard/wg0.conf file in case it may help anyone:

[Interface]
PrivateKey = ****
Address = 10.6.0.1/24
PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -D FORWARD -o wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
PostUp = sysctl net.ipv6.conf.eth0.accept_ra=2
PostUp = sysctl net.ipv6.conf.%i.forwarding=1 net.ipv6.conf.eth0.forwarding=1
PostUp = ip6tables -A FORWARD -i %i -j ACCEPT; ip6tables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = ip6tables -D FORWARD -i %i -j ACCEPT; ip6tables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
MTU = 1420
ListenPort = 51820
### begin TheBlackmad ###
[Peer]
PublicKey = ****
PresharedKey = ****
AllowedIPs = 10.6.0.2/32
### end TheBlackmad ###

on the other hand, I place as well my client config file:
[Interface]
PrivateKey = ****
Address = 10.6.0.2/24
MTU = 1420
DNS = 8.8.8.8, 8.8.4.4

[Peer]
PublicKey = ****
PresharedKey = *****
Endpoint = [****:****:****:****:****:****:****:****]:51820
AllowedIPs = ::/0, 0.0.0.0/0

on the /etc/pivpn/wireguard/setupVars.conf I also added 
pivpnPROTO=udp6
ALLOWED_IPS="0.0.0.0/0, ::0/0"

so the Allowed IPs can connect using udp6 (version 6)!

Now I can connect to my local network through a VPN tunnel and I can ping any other machine at home and it works. In fact, I can ping my 'mobile device' from any computer in the network and my mobile phone responds to it.

So thank you very much @orazioedoardo for the support given. It gave me very good insights about how PiVPN and Wireguard behaves! Much appreciated.
