### ISSUE TITLE
PiVPN should NOT automatically set the MTU to 1420. 

### ISSUE THREAD

**Issue by squidds** [pivpn/pivpn#1357]
PiVPN is an amazing tool. I use it to keep my cell phone connected to my home network, and from my home network I tunnel to my VPN provider. I like to think this "enhances" my privacy because I can filter DNS and use Unbound. 

That being said, I have had a huge headache the past couple weeks because I thought I had an NAT or firewall rule issue on my pFsense router. I reconfiged the debian VM I have PiVPN running on 3-4 times, I redid the host networking, reinstalled pFsense, carefully combed the firewall logs. Hours on end. 

My configs were fine. Everything looked great. 

It was the automatic 1420 MTU that PiVPN sets in the script. 

This is not a complaint, more of an observation. I had this issue in the past, and then someone along the way I asked for help from knew to set the MTU to automatic. This time, that never happened.

Thanks for this tool, though.

**Comment by orazioedoardo** [comment]
1420 is the default WireGuard MTU. If you don't set the line, it is still 1420.

**Comment by squidds** [comment]
It's not. The config from PIVPN explicitly sets it in the QR code.

**Comment by orazioedoardo** [comment]
I know the config sets it explicitly, but that’s the default anyway.

**Comment by squidds** [comment]
So you're saying that setting 1420 and not setting anything (auto) are the
same thing?

**Comment by orazioedoardo** [comment]
Yes.

**Comment by orazioedoardo** [comment]
> I had this issue in the past, and then someone along the way I asked for help from knew to set the MTU to automatic. This time, that never happened.

Though if that's the case, what client was affected, and what MTU was being set?

**Comment by squidds** [comment]
It's a pixel 4. 1420 doesn't work. Removing the 1420 works fine.

**Comment by orazioedoardo** [comment]
Looks like on [Linux](https://github.com/WireGuard/wireguard-tools/blob/af260d529eaa4387632c3d8dc8b02fd11c54f6bb/src/wg-quick/linux.bash#L140-L141) the MTU is set to 1420 if not specified, whereas on [Android](https://github.com/WireGuard/wireguard-tools/blob/af260d529eaa4387632c3d8dc8b02fd11c54f6bb/src/wg-quick/android.c#L1021) it's the MTU of the interface used for the default route (basically your wifi or cellular interface), minus 80.

Can you verify that? You should be able to get the MTU via adb or a terminal emulator. The cellular interface should be called `rmnet` I believe.

**Comment by squidds** [comment]
https://photos.app.goo.gl/AfcyUkA9YCB1U1LZA



Sorry, am out of the house. All my rmnet interfaces are using a MTU of
1500.

**Comment by squidds** [comment]
To be clear, everything was working fine at 1420 except when I connected to
an external wifi network. I was able to stay connected over mobile data and
my internal wifi network in my home.

**Comment by orazioedoardo** [comment]
Done, thanks for bringing this up.

**Comment by squidds** [comment]
I'm glad to be of assistance. Thanks.
