### ISSUE TITLE
OVPN File not found after creating a user

### ISSUE THREAD

**Issue by marcocet** [pivpn/pivpn#137]
I have just finished setting up the pivpn server and creating my first user and i cant find the ovpn file /home/pi/ovpn. Please help.

**Comment by redfast00** [comment]
Can you give me the output of `pivpn add`?

**Comment by marcocet** [comment]
Enter a name for the client:

**Comment by redfast00** [comment]
Have you actually tried entering a name?

**Comment by marcocet** [comment]
I created the user and everything but the ovpn doesn't show up

**Comment by redfast00** [comment]
Could you give me the full output and the output of `pivpn debug`?

**Comment by 0-kaladin** [comment]
@marcocet if no further response soon will close issue.
