### ISSUE TITLE
[Support] <cant connect to pivpn.io>

### ISSUE THREAD

**Issue by parkcheck** [pivpn/pivpn#1370]
## In raising this issue, I confirm the following:

`{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

### Issue
SSL expired

### Have you searched for similar issues and solutions?
    (yes/no / which issues?)
yes nothing found

### Console output of      `curl -L install.pivpn.io | bash`
```

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (60) SSL certificate problem: certificate has expired
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
root@raspberrypi:/usr/share#

```

### Console output of      `pivpn add` or `pivpn add nopass`
```
  Output Here
```

### Console output of      `pivpn debug`
```
  Output Here
```
### Have you taken any steps towards solving your issue?
```
  which?
```

**Comment by Kelventri** [comment]
The

> ## In raising this issue, I confirm the following:
> `{please fill the checkboxes, e.g: [X]}`
> 
> * [x]  I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
> * [x]  The issue I am reporting can be _replicated_.
> * [x]  The issue I am reporting can be _is_ directly related to the pivpn installer script.
> * [x]  The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).
> 
> ### Issue
> SSL expired
> 
> ### Have you searched for similar issues and solutions?
> ```
> (yes/no / which issues?)
> ```
> 
> yes nothing found
> 
> ### Console output of `curl -L install.pivpn.io | bash`
> ```
> 
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (60) SSL certificate problem: certificate has expired
> More details here: http://curl.haxx.se/docs/sslcerts.html
> 
> curl performs SSL certificate verification by default, using a "bundle"
>  of Certificate Authority (CA) public keys (CA certs). If the default
>  bundle file isn't adequate, you can specify an alternate file
>  using the --cacert option.
> If this HTTPS server uses a certificate signed by a CA represented in
>  the bundle, the certificate verification probably failed due to a
>  problem with the certificate (it might be expired, or the name might
>  not match the domain name in the URL).
> If you'd like to turn off curl's verification of the certificate, use
>  the -k (or --insecure) option.
> root@raspberrypi:/usr/share#
> ```
> 
> ### Console output of `pivpn add` or `pivpn add nopass`
> ```
>   Output Here
> ```
> 
> ### Console output of `pivpn debug`
> ```
>   Output Here
> ```
> 
> ### Have you taken any steps towards solving your issue?
> ```
>   which?
> ```

**Comment by parkcheck** [comment]
i updated the raspberry os and finally was able to do it.

**Comment by Kelventri** [comment]
> los
> 
> > ## Al plantear este problema, confirmo lo siguiente:
> > `{please fill the checkboxes, e.g: [X]}`
> > 
> > * [x]   He leído y comprendido la [guía para colaboradores](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md) .
> > * [x]   El problema que estoy informando se puede _reproducir_ .
> > * [x]   El problema que estoy informando puede ser _se_ relaciona directamente con el script de instalación pivpn.
> > * [x]   El problema que estoy informando no es un duplicado (consulte [Preguntas frecuentes](https://github.com/pivpn/pivpn/wiki/FAQ) , [problemas cerrados](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) y [problemas abiertos](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen) ).
> > 
> > ### Asunto
> > SSL caducado
> > ### ¿Ha buscado problemas y soluciones similares?
> > ```
> > (yes/no / which issues?)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > si nada encontrado
> > ### Salida de consola de `curl -L install.pivpn.io | bash`
> > ```
> > 
> >   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
> >                                  Dload  Upload   Total   Spent    Left  Speed
> >   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (60) SSL certificate problem: certificate has expired
> > More details here: http://curl.haxx.se/docs/sslcerts.html
> > 
> > curl performs SSL certificate verification by default, using a "bundle"
> >  of Certificate Authority (CA) public keys (CA certs). If the default
> >  bundle file isn't adequate, you can specify an alternate file
> >  using the --cacert option.
> > If this HTTPS server uses a certificate signed by a CA represented in
> >  the bundle, the certificate verification probably failed due to a
> >  problem with the certificate (it might be expired, or the name might
> >  not match the domain name in the URL).
> > If you'd like to turn off curl's verification of the certificate, use
> >  the -k (or --insecure) option.
> > root@raspberrypi:/usr/share#
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Salida de consola de `pivpn add`o`pivpn add nopass`
> > ```
> >   Output Here
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Salida de consola de `pivpn debug`
> > ```
> >   Output Here
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### ¿Ha tomado alguna medida para resolver su problema?
> > ```
> >   which?
> > ```
