### ISSUE TITLE
[Support] how to update pivpn

### ISSUE THREAD

**Issue by frank-github** [pivpn/pivpn#1375]
## In raising this issue, I confirm the following:

`{please fill the checkboxes, e.g: [X]}`

- [X] I have read the [documentation](https://docs.pivpn.io)
- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [] The issue I am reporting can be *is* directly related to the pivpn installer script.

### Have you searched for similar issues and solutions?
    yes - update problems

### Has your install failed? 
```
no
```

#### What type of hardware are you running PiVPN at?

```
Raspberrypi 
```
#### Output of `uname -a`
```
  Linux raspberry3 5.10.63-v7+ #1459 SMP Wed Oct 6 16:41:10 BST 2021 armv7l GNU/Linux

```

### Console output of      `pivpn add` or `pivpn add nopass`
```
 raspberry3:/etc# pivpn add nopass
::: Missing setup vars file!

```

Using pivpn since a while. I often update with pivpn -up
Now it do not work anymore

```
 raspberry3:/etc# pivpn -up
::: The updating functionality for PiVPN scripts is temporarily disabled
::: To keep the VPN (and the system) up to date, use 'apt update' and 'apt upgrade'

```
I had installed pivpn with install script curl -L https://install.pivpn.io | bash  months ago
and updated raspbian from stretch to Buster since.
apt can not found any package pivpn :-(

how can I now update pivpn ?

All search I found wrote to use the install script for installation....

**Comment by 4s3ti** [comment]
first why do you want to update pivpn? 

That functionality was disabled due to compatibility with older iterations of pivpn script as we did some breaking some time ago. 

Also PiVPN doesn't really need update per se ... 
if you're looking to update your VPN protocol just run `apt update && apt upgrade` as you do for regular updates

**Comment by frank-github** [comment]
I can't add any new clients with pivpn add (error: missing setup vars file....)
my 2 older (and successful) running clients I installed with this command.

Now I tried to install a new client with basic wg commands, but this client do not work correct.
he can connect, but no data transfer is possible :-(
wireguard on server see this new client (wg output), but also wrote no data transfer

I had no idea, what's wrong. Found nowhere any logging....  maybe I'm looking at the wrong places.....

the setup of the first two clients went with pivpn so easy and error free.
I had the hope that pivpn could help me again, but pivpn doesn't seem to work anymore.
So I thought an update could solve the problem.

**Comment by 4s3ti** [comment]
then your problem is elsewhere ... the Support template was requesting more data .. .please edit your issue and add the missing information, here is the template: https://raw.githubusercontent.com/pivpn/pivpn/master/.github/ISSUE_TEMPLATE/support-request.md

**Comment by frank-github** [comment]
my wireguard problem is not a pivpn issue
I now know pivpn update not needed and if I can you the install script again
thanks
