### ISSUE TITLE
> los

### ISSUE THREAD

**Issue by Kelventri** [pivpn/pivpn#1376]
> los
> 
> > ## Al plantear este problema, confirmo lo siguiente:
> > `{please fill the checkboxes, e.g: [X]}`
> > 
> > * [x]   He leído y comprendido la [guía para colaboradores](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md) .
> > * [x]   El problema que estoy informando se puede _reproducir_ .
> > * [x]   El problema que estoy informando puede ser _se_ relaciona directamente con el script de instalación pivpn.
> > * [x]   El problema que estoy informando no es un duplicado (consulte [Preguntas frecuentes](https://github.com/pivpn/pivpn/wiki/FAQ) , [problemas cerrados](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) y [problemas abiertos](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen) ).
> > 
> > ### Asunto
> > SSL caducado
> > ### ¿Ha buscado problemas y soluciones similares?
> > ```
> > (yes/no / which issues?)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > si nada encontrado
> > ### Salida de consola de `curl -L install.pivpn.io | bash`
> > ```
> > 
> >   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
> >                                  Dload  Upload   Total   Spent    Left  Speed
> >   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (60) SSL certificate problem: certificate has expired
> > More details here: http://curl.haxx.se/docs/sslcerts.html
> > 
> > curl performs SSL certificate verification by default, using a "bundle"
> >  of Certificate Authority (CA) public keys (CA certs). If the default
> >  bundle file isn't adequate, you can specify an alternate file
> >  using the --cacert option.
> > If this HTTPS server uses a certificate signed by a CA represented in
> >  the bundle, the certificate verification probably failed due to a
> >  problem with the certificate (it might be expired, or the name might
> >  not match the domain name in the URL).
> > If you'd like to turn off curl's verification of the certificate, use
> >  the -k (or --insecure) option.
> > root@raspberrypi:/usr/share#
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Salida de consola de `pivpn add`o`pivpn add nopass`
> > ```
> >   Output Here
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Salida de consola de `pivpn debug`
> > ```
> >   Output Here
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### ¿Ha tomado alguna medida para resolver su problema?
> > ```
> >   which?
> > ```

_Originally posted by @Kelventri in https://github.com/pivpn/pivpn/issues/1370#issuecomment-956132300_

**Comment by 4s3ti** [comment]
English only!
