### ISSUE TITLE
Adding in additional layer of encryption with Stunnel or obfsproxy

### ISSUE THREAD

**Issue by JJwatt5614** [pivpn/pivpn#138]
Hi everyone,

I have pivpn installed on my RPi3 and it is working perfectly so far. Thanks to everyones effort in making it work.

I would like to add an additional layer of encryption with SSL in order to "wrap" my traffic in it. However, I am not sure how to do this. Can someone help guide me through this and the difference between stunnel and obfsproxy?

Thanks!

**Comment by redfast00** [comment]
@JJwatt5614 Your traffic is already encrypted by OpenVPN and you should be safe unless you chose for 1024-bits encryption. We already setup some security features as default:

- `ta.key`: prevents brute force attemts/DoS
- We are using modern cryptography: `AES-256-CBC` and enforcing `TLS 1.2` for key negotiation.
- We set it up so clients can't impersonate the server
- You can easily revoke certificates if you suspect they have been breached.

If you are still paranoid, you can choose for a `4096-bits` key and generate your DH-parameters yourself.

**Comment by redfast00** [comment]
@JJwatt5614 If you still want to do this, check out this [post in the community wiki](https://community.openvpn.net/openvpn/wiki/TrafficObfuscation) about obfsproxy (for obfuscating your OpenVPN traffic).
