### ISSUE TITLE
makeOVPN.sh No such file or directory

### ISSUE THREAD

**Issue by prov3it** [pivpn/pivpn#1416]
Just did a fresh install.

```
/usr/local/bin/pivpn: line 18: /opt/pivpn/openvpn/makeOVPN.sh: No such file or directory
```
openvpn-dir does not exist. I chose to build pivpn with openvpn and higher compatibility.

Quick fix with:
```
ln -s /opt/pivpn/makeOVPN.sh /opt/pivpn/openvpn/makeOVPN.sh
```

**Comment by 4s3ti** [comment]
Hi, thanks for using pivpn and for reaching back however before opening an issue you should read the documentation first. 

Please read: https://github.com/pivpn/pivpn#feedback--support

Closing...
