### ISSUE TITLE
PiVPN working on a RPi Debian netinstall

### ISSUE THREAD

**Issue by pixilarion** [pivpn/pivpn#142]
What follows isn't really an issue but rather the solution to some issues I encountered during the installation.

First of all, I have a bare minimum Debian installation (netinstall), based on [raspbian-ua-netinst](https://github.com/debian-pi/raspbian-ua-netinst).

1. An `apt-get update` should be recommended. At first the script tried to install some dependencies but failed because of outdated respository information.
2. I had to install _curl_ and _whiptail_ myself. A simple _apt-get install curl whiptail_ solves this.
3. On the first run, pkitool --initca failed, showing a rather obscure error code:
`error:0E065068:configuration file routines:STR_COPY:variable has no value:conf_def.c:618:line 198`.
Although the installation script of pivpn seemed ok with it and continued like nothing happened, I encountered some errors further down the road, which made me examine this error.
I found the solution on [the ubuntu forum](https://ubuntuforums.org/showthread.php?t=2218935): `export KEY_ALTNAMES="something"` needs to be added to `/etc/openvpn/easy-rsa/vars`
4. After that I tried a few things I can't remember (mainly trying to build certificates manually), but in the end I just reran the installationscript of pivpn
5. The script ran fine, the 'Generating DH' phase took a lot longer, but in the end everything works just fine.

**Comment by redfast00** [comment]
@pixilarion: thanks a lot. I will add this as soon as possible

**Comment by redfast00** [comment]
@pixilarion you will still need to install `curl` manually, since it is needed to get the install script (`curl -L install.pivpn.io | bash`).
