### ISSUE TITLE
[BUG] Connection failure when LAN of server changes

### ISSUE THREAD

**Issue by watchingdogs** [pivpn/pivpn#1420]
## In raising this issue, I confirm the following: 

- [x] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting *is* directly related to the pivpn installer script.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

**Describe the bug**
The file `/etc/pivpn/wireguard/setupVars.conf` contains the hard-coded value of the router and the IPv4 address of the server, which causes connection issues. The issue was fixed on my end, by updating the values and restarting the server.
An update to the debug script that checks if the values in the file are still valid, and if not it updates them would solve the issue.

**To Reproduce**
Buy a new router. 

**Expected behavior**
Connection issues arise.

**Additional context**

```
$ uname -a
Linux raspberrypi 5.10.63-v7l+ #1459 SMP Wed Oct 6 16:41:57 BST 2021 armv7l GNU/Linux
```

**Comment by 4s3ti** [comment]
sorry but i can't see how this is a bug! at best this is a feature request and should be dealt like such here: 

https://github.com/pivpn/pivpn/discussions/categories/feature-requests

also at best we could warn users of such difference but we should not update them, that's up to you if you want to Re-configure your router with same network settings as before or if you want to update the `setupVars.conf` 

Moved to feature requests.
