### ISSUE TITLE
Connection from client works but client is unable to break out to the internet after connecting

### ISSUE THREAD

**Issue by chaoszone** [pivpn/pivpn#143]
Hi,
first of all, wow, your work here is really amazing, thanks for all the effort.
The installation went smooth for me and also connection from a client (Android Phone) works great.
However after connecting, the client can't connect to any internet services (e.g. www)
Does anything have to be configured on the server to do that?
The config in dhcpcp.conf seems to be fine:

::: interface eth0
    static ip_address=192.168.0.128/24
    static routers=192.168.0.1
    static domain_name_servers=192.168.0.1

**Comment by 0-kaladin** [comment]
Prob something with IP tables. What OS is your pi on?

**Comment by chaoszone** [comment]
Latest Jesse light image.

Am 05.11.2016 3:16 vorm. schrieb "0-kaladin" <notifications@github.com>:

**Comment by HaniKali** [comment]
I couldnt connect to my LAN or the internet when I connected to the vpn, following [this](https://github.com/pivpn/pivpn/issues/141) sorted both the internet and LAN out.

**Comment by 0-kaladin** [comment]
If that does fix it then there is a bug somewhere...

**Comment by chaoszone** [comment]
It did not fix the problem 🙁

Am 06.11.2016 12:54 vorm. schrieb "0-kaladin" <notifications@github.com>:

If that does fix it then there is a bug somewhere...

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/pivpn/pivpn/issues/143#issuecomment-258650424>, or mute
the thread

**Comment by chaoszone** [comment]
Where could I check if something is wrong with the IP routing?

**Comment by 0-kaladin** [comment]
try setting this:
static domain_name_servers=192.168.0.1
to 8.8.8.8 instead.

**Comment by mplawner** [comment]
https://github.com/pivpn/pivpn/issues/151

**Comment by 0-kaladin** [comment]
@chaoszone is pi-hole also installed or no?

**Comment by lupa18** [comment]
Here I have installed and also client don't have internet. I commented this line:
#push "redirect-gateway def1"
Then, restart server and client and now works

**Comment by robreczarek** [comment]
@lupa18 This worked for me. I ran this command prior (plus reboot after) to the config file update

> sudo /sbin/iptables -P FORWARD ACCEPT
> sudo /sbin/iptables --table nat -A POSTROUTING -o eth0 -j MASQUERADE

Not sure if the iptables step was necessary though.

**Comment by eckirchn** [comment]
I am able to connect a fedora client to the PiVPN server, and it appears to be routing all internet traffic through the PiVPN server to my router, but I am not able to see any local machines.

**Comment by cfcolaco** [comment]
@eckirchn have you tried all methods spoken here? 

please provide more info ... pivpn debug ... log files ... iptables rules output

**Comment by eckirchn** [comment]
@cfcolaco, thank you for the response, I found out it is working, however it was avahi that was leading me to think it was not.  Avahi was not being forwarded, which for now, I am ok with.  It sounds like I need to go to a level 2 VPN, which appears to be bridging, which I am not interested in doing.  Unless there are any other suggestions, I am content not having avahi functional, as it does add a layer of security to the connection.

**Comment by cfcolaco** [comment]
@redfast00 this one can be closed also! ;) thank you again
