### ISSUE TITLE
[Support] Instructions for properly changing IPv4addr and IPv4gw

### ISSUE THREAD

**Issue by reinisb** [pivpn/pivpn#1430]
## In raising this issue, I confirm the following:

- [X] I have read the [documentation](https://docs.pivpn.io)
- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting can be *is* directly related to the pivpn installer script.

### Have you searched for similar issues and solutions?
Yes
### Has your install failed? 
```
No
```

#### What type of hardware are you running PiVPN at?

```
Raspberrypi 3B+
```
#### Output of `uname -a`
```
Linux raspberrypi 5.10.63-v7+ #1488 SMP Thu Nov 18 16:14:44 GMT 2021 armv7l GNU/Linux
```

#### Output of `cat /etc/os-release`
```
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

### Issue
I've set up wireguard server through pivpn and everything works perfectly. Now, I will be relocating my raspberry and the `IPv4addr` and `IPv4gw` addresses at the new location will be different. Is it safe to simply edit these two addresses at `/etc/pivpn/wireguard/setupVars.conf`? Or do I need to do anything else (i.e. recreate client configs)? I could not find any information about this use case in the docs [here](https://docs.pivpn.io/wireguard/) or [here](https://docs.pivpn.io/faq/). Thank you!

<img width="891" alt="Screen Shot 2021-12-10 at 11 43 15" src="https://user-images.githubusercontent.com/6346595/145554351-d7decc02-8e98-46e7-8543-02cdba2b7598.png">

### Have you taken any steps towards solving your issue?
```
I read documentation and browsers the web for 2 hours, but could not find instructions.
```

**Comment by orazioedoardo** [comment]
PiVPN optionally sets a static IP by editing the `/etc/dhcpcd.conf` file with the `IPv4addr` and `IPv4gw` varaibles, whose values are gathered at install time. They are saved to the setupVars file, but not used after install. If you relocate the Pi, you should update `/etc/dhcpcd.conf` according to the new network.

**Comment by reinisb** [comment]
@orazioedoardo thanks for the quick response! Indeed, at the bottom of `/etc/dhcpcd.conf` I see the following lines. I do have a follow-up question though - what about `pivpnDNS1` vs `domain_name_servers` values - why are they different and can I safely change them?

```
interface eth0
        static ip_address=192.168.1.223/24
        static routers=192.168.1.1
        static domain_name_servers=192.168.1.1
```

PS It would be really valuable to document this in PiVPN docs.

**Comment by orazioedoardo** [comment]
The pivpn creation script uses the `pivpnDNS1` and `pivpnDNS2` variables to set the DNS server that VPN clients will use. `domain_name_servers` is the DNS server used by the Pi itself which is set in the static ip conf and grabbed from the `/etc/resolv.conf` file.
