### ISSUE TITLE
[Support] Let PIVPN use two NIC 

### ISSUE THREAD

**Issue by fgnm** [pivpn/pivpn#1431]
## In raising this issue, I confirm the following:

`{please fill the checkboxes, e.g: [X]}`

- [x] I have read the [documentation](https://docs.pivpn.io)
- [x] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting can be *is* directly related to the pivpn installer script.

### Have you searched for similar issues and solutions?
    Yes

### Has your install failed? 
```
no
```

#### What type of hardware are you running PiVPN at?

```
Raspberry Pi4
```
#### Output of `uname -a`
```
Linux raspberrypi 5.10.63-v7l+ #1488 SMP Thu Nov 18 16:15:28 GMT 2021 armv7l GNU/Linux
```

#### Output of `cat /etc/os-release`
```
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

### Issue

I have a raspberry pi4 connected with both Ethernet and wifi network adapters, the ethernet communicate with external world, while wifi is connected to an internal local network. Raspberry's network is properly configured because it can access both external world (such as google.it) and wifi local network (192.168.111.1).
Now, when I try to connect to PIVPN with a Client it works, I can ping external world but I cannot access to local network (i.e. 192.168.111.10). It's something in PIVPN configuration that isn't set well but I can't find what.

### Have you taken any steps towards solving your issue?
I tried to add this line to `/etc/openvpn/server.conf` but without luck
```
 push "route 192.168.111.0 255.255.255.0"
```

**Comment by domisant** [comment]
Hi,

I think you're almost there... have you checked the iptables roules?
You need to add this rule as root:
`iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o wlan0 -j MASQUERADE`
Don't forget to save the iptables roule:
`/sbin/iptables-save > /etc/iptables/rules.v4`

**Comment by fgnm** [comment]
Thanks! It worked :)
