### ISSUE TITLE
Web Interface with OpenRSD

### ISSUE THREAD

**Issue by mitchellurgero** [pivpn/pivpn#144]
Not an issue, but https://github.com/mitchellurgero/openrsd now has a page that can use the add and revoke options of pivpn :) From my testing it works 100% - OpenRSD is an Open Source RaspberryPi Dashboard (Web Interface) that can do a lot of basic and some advanced configuration and management of Raspbian based OS's :) try it out!

**Comment by redfast00** [comment]
@mitchellurgero: Thanks for letting us know :smiley: . Once your project is out of beta, it might get added to our README.
