### ISSUE TITLE
[Support] vpn question or support idk  

### ISSUE THREAD

**Issue by progamer562** [pivpn/pivpn#1446]
- [yes] I have read the [documentation](https://docs.pivpn.io)
- [yes] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [yes] The issue I am reporting can be *replicated*.
- [yes] The issue I am reporting can be *is* directly related to the pivpn installer script.

i wanted to know that i cant connect to my local pcs that are not on the vpn is there a way to let me see them and use them while i have the vpn on without the computer not running the vpn

wiregurd 
raspberry pi 4gb

**Comment by acognigni-evotecnia** [comment]
Sorry . dont understand your question. you are connecting to a vpn and want to see the computers in the internal network of the server without having to connect them to the vpn?

**Comment by progamer562** [comment]
Yes sorry about what I said I had no time typeing it

**Comment by progamer562** [comment]
are you there?

**Comment by progamer562** [comment]
?

**Comment by TinCanTech** [comment]
A VPN can do what you want but `pivpn` does not do it.

**Comment by progamer562** [comment]
i thought you can do it locally not the server

**Comment by progamer562** [comment]
but on my ipad it lets me

**Comment by TinCanTech** [comment]
If you feel confident then read the Openvpn [howto](https://community.openvpn.net/openvpn/wiki/HOWTO#ExpandingthescopeoftheVPNtoincludeadditionalmachinesoneithertheclientorserversubnet)

**Comment by progamer562** [comment]
But WireGuard is safer right?
