### ISSUE TITLE
[Support] Disconnection of wireguard clients

### ISSUE THREAD

**Issue by nefta** [pivpn/pivpn#1457]
Hello colleagues, good day
I have pihole and pivpn wireguard in ubuntu served in the cloud, and I have mikrotik clients connected through wireguard, everything works perfectly, but it happens that when there is a power outage or internet outage in the client routers (mikrotik) they disconnect from pivpn (wireguard) you have to restart the server for them to reconnect.
I hope someone can help me to solve this conflict.
Thanks a lot!

**Comment by 4s3ti** [comment]
Duplicate: https://github.com/pivpn/pivpn/discussions/1458
Closing
