### ISSUE TITLE
OpenRSD + PiVPN = Amazing Web Interface :D

### ISSUE THREAD

**Issue by mitchellurgero** [pivpn/pivpn#146]
OpenRSD is now out of beta. Can a dev check it out?

https://github.com/mitchellurgero/openrsd

Has a LOT of features for Raspbian based OS's.(Including a web interface for PiVPN scripts / commands)

**Comment by 0-kaladin** [comment]
ok... There is a lot I like here.
High level thoughts, post your responses:

1. what is your goal here?  Would you like to see me offer this as part of the pivpn installer?  IE ask the user if they would like to add a GUI to their pi?  

2. If I did that I'd probably want to turn on the managment interface of the openvpn server so you could interact with those commands as well: https://openvpn.net/index.php/open-source/documentation/miscellaneous/79-management-interface.html
Not all of them but things like 'hold' 'version' 'kill (connected clients)' 'status' etc i could see being useful, etc.

3.  Would like PiVPN to be its own heading, like Dashboard, Basic Config, Advanced Config, PiVPN Management, Power Options etc.
the PiVPN Management would only show if you detect PiVPN is installed, this way those using the UI without PiVPN don't see unnecessary headings.

thoughts? Feedback?

**Comment by mitchellurgero** [comment]
I like the idea, however OpenRSD is a separate project, and I wanted to just state that it has a couple basic functions for PiVPN (I will take those out if you want, thought it was a cool feature).

If we did team up and worked on both projects together (Or I can make a completely new interface for PiVPN, completely separate from OpenRSD), then I could move PiVPN to its own Navbar item.

email me if you'd like: info@urgero.org (It forwards to my personal, not putting that here though :) )

**Comment by 0-kaladin** [comment]
No I wasn't implying to take them out.  Keep them in and add more, up to you.
I didn't want to work on it, just use as is.  Just maybe keep a fork of it here that has PiVPN on its own navbar item and adds as much as it can to the pivpn.  It'd still be separate as it can be the last thing this installer asks the user, whether or not they want to install a gui that shows them cpu/mem etc of their pi and also has some pivpn commands built in.  Would be nice.

**Comment by mitchellurgero** [comment]
I agree, Well I can move PiVPN to it's own navbar item, then if you want to add it as an install-able option :) otherwise, you can link in the README if wanted. :D

**Comment by arikalfus** [comment]
Personally, I prefer projects that have a focused, refined use case. Here, PiVPN is a great little script that gets your Raspberry Pi up and running as an OpenVPN server. Easy.

Adding a web GUI/interface to that interaction is a value add, but I would prefer it separate from the project/script that sets up the server.

**Comment by 0-kaladin** [comment]
So you'd prefer a separate curl command vs at the end of the pivpn install it just asks if you want to install a gui, y/n?

**Comment by mitchellurgero** [comment]
Well install is simple and can be scripted, just a git clone of the openrsd repo + changing the user and group of the apache server to run as pi.

It should be a separate script too, so I agree with @arikalfus on that aspect, Like discussed before, maybe just putting it in the readme would be enough. Or I can fork OpenRSD and rebuild it specifically for PiVPN in a new project.

So, @0-kaladin, let me know and I can do that.

**Comment by arikalfus** [comment]
@0-kaladin Personally I would prefer a separate command. However, the aim of your project is to provide a benefit in an easy, one-off way to potentially non-technical users. I believe that's your goal, correct? There's an argument to be made that, in that case, make it as simple as possible and bundle it into the script. Another curl command is another confusing step to someone that doesn't understand all of this.

But keeping them separate lets you work on them as two distinct projects, which you could argue they are. The script and the GUI. And you could share a command at pivpn.io that just concats the second curl | bash sequence for the GUI, so to a non-technical user it's still just one "command" they're running.

**Comment by mitchellurgero** [comment]
Well someone let me know I can fork OpenRSD and strip it down to just PiVPN GUI.

**Comment by mitchellurgero** [comment]
But I would prefer to leave it as is because of all the features it offers.

**Comment by 0-kaladin** [comment]
Let me clearly lay out what I'd want to do to avoid confusion.
You leave your project as-is.  Develop it with features/fixes as you see fit (quite obviously).
I fork it over here in the pivpn organization.  As you add features or changes either I merge them in where wanted, or add you as a member to this org so you can do yourself.
As a separate repo here in pivpn org a few things can happen.  
1.  you can selectively choose if a feature goes into openrsd the separate project or the one that gets installed with pivpn.
2. I can make the changes I'd like, which off the top of my head, for the pivpn install I'd use nginx, change the url to be like pivpn-ui, offer htaccess auth if the user wants, etc.  basically because i'd script the install i'd change the things on the system (not really the src) to support pivpn stuff more.
3. as a separate fork its easy to install with a separate curl from the pivpn installer.

but I def don't want you to fork to strip down to just pivpn, those other features will be handy for pivpn users as well, to see their cpu mem etc.

**Comment by mitchellurgero** [comment]
With the authentication mech I wrote it really only supports the PAM-auth I did (With custom binary to authenticate against the /etc/passwd file in Raspbian) But you are more than welcome to fork and do what you like :) If you want to fork, here are the files that are ABSOLUTELY required for the PiVPN feature to work in the web interface:

```
/dlnd_profile.php
/index.php (Edit funciton body() to your needs.)
/logout.php
/page.php (Remove everything except openvpn stuff. This does the dynamic loading of page(s))
/app/auth_log
/app/blocked_ip
/app/bin/chkpasswd
/app/auth.php
/app/funcitons-orsd.js
/app/functions.php
/app/logs.php (Used as a general sudo cat <filename> function (Reads the profile files for PiVPN)
/app/profile-revoke.php
/app/profile.php
/bower_components
/css
/dist
/img
/js
/less
/pages/openvpn.php (Displays all the stats, profiles, etc to the user)
```

If I missed something, I'll add later, otherwise I can just fork to pivpn-gui make the modifications to make it PiVPN only, then give you ownership?

**Comment by zerocolTHS** [comment]
So how do we install the gui >? 

But nothing. 
```
How to install

Please visit pivpn.io for more information.
```

**Comment by mitchellurgero** [comment]
> cd /var/www/html
> 
> git clone https://github.com/mitchellurgero/pivpn-gui

**Comment by lsandersvega** [comment]
Hi Mitchell

I installing the pivpn gui  but show the following error:

remote: Repository not found.
fatal: repository 'https://github.com/mitchellurgero/pivpn-gui/' not found

**Comment by mitchellurgero** [comment]
Please go read the repo. It explains why it's not found...

**Comment by e-clin** [comment]
> @0-kaladin Personally I would prefer a separate command. However, the aim of your project is to provide a benefit in an easy, one-off way to potentially non-technical users. I believe that's your goal, correct? There's an argument to be made that, in that case, make it as simple as possible and bun1dle it into the script. Another curl command is another confusing step to someone that doesn't understand all of this.
> 
> But keeping them separate lets you work on them as two distinct projects, which you could argue they are. The script and the GUI. And you could share a command at pivpn.io that just concats the second curl | bash sequence for the GUI, so to a non-technical user it's still just one "command" they're running.

As a "non-technical" newbie to Raspberry Pi who enjoyed setting up an OpenVPN personal server recently, I would very much welcome this idea. I wish the installer could include an option for installing a web UI/dashboard to monitor and manage the connections to and traffic through my server. Thanks for your great work!
