### ISSUE TITLE
[FR] Rename clients

### ISSUE THREAD

**Issue by vervaekejonathan** [pivpn/pivpn#1460]
Is it possible to rename clients (when using wireguard) so that their new name shows up when listing them via the `pivpn -c` or `pivpn -l` flags?

**Comment by 4s3ti** [comment]
Is this a feature request or a general question? 

Before opening an issue or discussion please read: https://github.com/pivpn/pivpn#feedback--support 

closing.

**Comment by vervaekejonathan** [comment]
Rename your client in the following files:
- ~/.configs/NAME.conf
- /etc/wireguard/configs/NAME.conf
- /etc/wireguard/configs/clients.txt -> search for NAME
