### ISSUE TITLE
Can't connect to VPN

### ISSUE THREAD

**Issue by SubatomicGenome** [pivpn/pivpn#147]
I've followed the instructions perfectly. I've generated my keys and imported them to my clients. 

I HAVE FORWARDED PORTS AND THIS IS DONE PROPERLY. I know this because I do hosting. I have Killing floor 2 server, Minecraft, Mumble, I have a bunch of already working services on my network that function beautifully...

I've properly forwarded the ports to the IP of my Pi... And I can't connect from within the network, (not that I need to) but mainly, connect externally. I can't make a connection at all. The app I'm using is on android and I'm trying to connect to this VPN server with my phone 

https://play.google.com/store/apps/details?id=net.openvpn.openvpn&hl=en

This is the application I'm using for Android. I've FTP'd over the key to my SD card and imported it. 
When I try to connect, it just says "Waiting for Server" indefinitely. 

I've had other VPNs working before but they were crap but they worked and I've used this port before. And before you ask, I've gone through my port list and double checked for duplicates. We are clean here.

I've done everything over and over with no success. What gives? Please help.

-Sub

**Comment by 0-kaladin** [comment]
it is configured to work externally.  You said you can't connect from within the network.  Well that would be expected.  did you turn off wifi on your phone to ensure you are trying to connect externally?   
Did you reboot your pi after installation?  Waiting for server means it simply isn't hitting the server so either the openvpn process isn't running or you didn't really try externally yet.

**Comment by SubatomicGenome** [comment]
Indeed I've turned off wifi. When I went to the gym this morning I tested it there on their network. I'm remoting into my sister's computer right now to make sure it's not a problem with my phone or my mobile network or anything of the such. No go... And yes I rebooted my pi. A ton of times in fact. 

I'm also running pihole I don't know if that has anything to do with it. But the ports are forwarded and I've tried not one or two, but many networks. Rebooted my router and disabled and re-enabled ports. 

After you reboot doesn't the openvpn process start up automatically??? After a reboot, as far as the service is concerned I should have no issues there right? If that's not the case. What is the command to start openvpn process?

**Comment by 0-kaladin** [comment]
It should start auto.  
run `netstat -plnu`
if you left it on UDP.
you should see something closely matching this in the list:
`udp        0      0 0.0.0.0:1194            0.0.0.0:*                           2730/openvpn`
if you do, it is running.  

then you can run
`iptables -t nat -L`
you should see something like...
`Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination

Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination
MASQUERADE  all  --  10.8.0.0/24          anywhere`

if all this looks good, then you aren't hitting your pi when you try to connect.  router, etc. isn't getting it there.

**Comment by SubatomicGenome** [comment]
I left it on UDP. But that line is not there at all.

"udp        0      0 0.0.0.0:60349           0.0.0.0:*                           -
udp        0      0 0.0.0.0:53              0.0.0.0:*                           -
udp        0      0 0.0.0.0:68              0.0.0.0:*                           -
udp        0      0 0.0.0.0:68              0.0.0.0:*                           -
udp        0      0 0.0.0.0:30828           0.0.0.0:*                           -
udp        0      0 65.4.154.52:123         0.0.0.0:*                           -
udp        0      0 127.0.0.1:123           0.0.0.0:*                           -
udp        0      0 0.0.0.0:123             0.0.0.0:*                           -
udp        0      0 65.4.154.255:137        0.0.0.0:*                           -
udp        0      0 65.4.154.52:137         0.0.0.0:*                           -
udp        0      0 0.0.0.0:137             0.0.0.0:*                           -
udp        0      0 65.4.154.255:138        0.0.0.0:*                           -
udp        0      0 65.4.154.52:138         0.0.0.0:*                           -
udp        0      0 0.0.0.0:138             0.0.0.0:*                           -
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           -
udp6       0      0 :::39925                :::*                                -
udp6       0      0 :::53                   :::*                                -
udp6       0      0 fe80::60e1:8311:60e:123 :::*                                -
udp6       0      0 ::1:123                 :::*                                -
udp6       0      0 :::123                  :::*                                -
udp6       0      0 :::49796                :::*                                -
udp6       0      0 :::64738                :::*                                -
udp6       0      0 :::5353                 :::*                                -
"

This means it's not started I assume?? If it's supposed to start at boot, what would cause it from not launching?

**Comment by 0-kaladin** [comment]
as root try running
```
systemctl enable openvpn.service
systemctl start openvpn.service
```

**Comment by SubatomicGenome** [comment]
Nothing. Nothing at all. It said the service enabled and I started it. But nothing is working.... Think I'm giving up and trying something else..
