### ISSUE TITLE
[BUG] Static IP non available on Raspberry Pi OS 64-bit

### ISSUE THREAD

**Issue by orazioedoardo** [pivpn/pivpn#1474]
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting *is* directly related to the pivpn installer script.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

**Describe the bug**

**To Reproduce**
1. Install the 64-bit version of Raspberry Pi OS
2. Install PiVPN
3. Observe that the installer [says](https://github.com/pivpn/pivpn/blob/f80b0a7962d91862132c0a4abd65c1e67bd37bd7/auto_install/install.sh#L652-L654) that you are not using Raspbian and thus will not set a static IP

**Expected behavior**
The installer asks the user whether a static IP should be configured.

**Additional context**
This issue is due to the fact that the 64-bit version of Raspbian advertises itself as Debian. I think an alternative way to detect raspbian is by looking for the `/etc/apt/sources.list.d/raspi.list` file. It should also work on DietPi versions for Raspberry Pi.

**Comment by ProfessorStrawberry** [comment]
My temporary solution is to adjust 

> /etc/os-release

 with the following entries until the install is done:

`cat /etc/os-release`

```
PRETTY_NAME="Raspbian GNU/LINUX 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian

```

**Comment by jsures** [comment]
having same issue, fresh install of pivpn on 64 bit bullseye.

**Comment by jsures** [comment]
> 

this worked for me. traffic is flowing through pihole but i cant seem to connect to local network, not sure what i am missing in my setup.

**Comment by orazioedoardo** [comment]
@jsures That's another issue, file a support request in discussions.

**Comment by orazioedoardo** [comment]
It should work now, can you check (test branch)? https://github.com/pivpn/pivpn#to-install-from-testdevelopment-branch
