### ISSUE TITLE
[BUG] ./install.sh: line 587: ip: command not found

### ISSUE THREAD

**Issue by Subcode** [pivpn/pivpn#1477]
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting *is* directly related to the pivpn installer script.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

**Describe the bug**

**To Reproduce**
1. Run 'curl https://raw.githubusercontent.com/pivpn/pivpn/master/auto_install/install.sh | bash on installed pi.'
2. Attempt to install
3. See error

**Expected behavior**
Simply getting PiVPN installed

The problem was a missing iproute/iproute2 package. Should the installer not install this?

**Comment by orazioedoardo** [comment]
It's weird that `iproute2` is not installed, which OS are you running?

**Comment by orazioedoardo** [comment]
No response in a while, closing.
