### ISSUE TITLE
Client Profile Generation Password Error

### ISSUE THREAD

**Issue by afkgeek** [pivpn/pivpn#148]
I've run into an issue when trying to create client profiles with passwords that contain special characters.

```
$ pivpn add
Enter a Name for the Client:  test
NOTE: If you run ./clean-all, I will be doing a rm -rf on /etc/openvpn/easy-rsa/keys
Enter the password for the client:  
Enter the password again to verify:  
spawn ./build-key-pass test
Generating a 2048 bit RSA private key
............+++
........................................................................................................+++
writing new private key to 'test.key'
Enter PEM pass phrase:can't read "t": no such variable
    while executing
"send "Te$t!00\r" "
    invoked from within
"expect "Enter PEM pass phrase" { send "Te$t!00\r" }"
spawn openssl rsa -in test.key -des3 -out test.3des.key
unable to load Private Key
1996028000:error:0906D06C:PEM routines:PEM_read_bio:no start line:pem_lib.c:696:Expecting: ANY PRIVATE KEY
expect: spawn id exp6 not open
    while executing
"expect "Enter PEM pass phrase" { send "Te$t!00\r" }"
[ERROR]: Client Public Key Certificate not found: test.crt
```

It seems that when the password is sent, the special characters being sent aren't being escaped.

**Comment by afkgeek** [comment]
I believe it could be sorted by escaping the characters using sed.

`PASSWD=$(echo -n $PASSWD | sed -e 's/\\/\\\\/g' -e 's/\//\\\//g' -e 's/\$/\\\$/g' -e 's/!/\\!/g' -e 's/\./\\\./g' -e "s/'/\\\'/g" -e 's/"/\\"/g' -e 's/\*/\\\*/g' -e 's/\@/\\\@/g' -e 's/\#/\\\#/g' -e 's/£/\\£/g' -e 's/%/\\%/g' -e 's/\^/\\\^/g' -e 's/\&/\\\&/g' -e 's/(/\\(/g' -e 's/)/\\)/g' -e 's/-/\\-/g' -e 's/_/\\_/g' -e 's/\+/\\\+/g' -e 's/=/\\=/g' -e 's/\[/\\\[/g' -e 's/\]/\\\]/g' -e 's/;/\\;/g' -e 's/:/\\:/g' -e 's/|/\\|/g' -e 's/</\\</g' -e 's/>/\\>/g' -e 's/,/\\,/g' -e 's/?/\\?/g' -e 's/~/\\~/g' -e 's/{/\\{/g' -e 's/}/\\}/g')`

**Comment by 0-kaladin** [comment]
@afkgeek if you edit /opt/pivpn/makeOVPN.sh with the above changes let me know if it works for you.

**Comment by 0-kaladin** [comment]
oh and thanks for the nice sed line.  saved me some time.. :)

**Comment by projectdigital** [comment]
Not sure if this is related or not but I've recently just worked through your script successfully (downloaded and installed 30 minutes ago) apart from generating client keys. It looks as if you've tried to automatically make the PEM passphrase the same as the client password, however this doesn't seem to be working. No matter what password I enter when adding new clients I always get "password incorrect" when trying to actually connect. It seems that all clients are being assigned the PEM password of "$PASSWD" (without quotes). As in, if I connect from my android and use $PASSWD as the password I can connect successfully.

**Comment by 0-kaladin** [comment]
I broke something with my last commit. Give me a few hours..

**Comment by projectdigital** [comment]
No worries! Timing aye!
I'll try again tonight. Thanks a bunch!

**Comment by 0-kaladin** [comment]
Yea I just verified you are correct... Hmm this is difficult..

**Comment by projectdigital** [comment]
Yeah, I noticed the symbol thing but don't actually mind too much. I know enough to do a small amount of debugging not not enough to actually make a valuable contribution to the case so I'm sorry for that. Background is in php and web mostly.. Good luck :)

**Comment by 0-kaladin** [comment]
ok try it now.  since you've already installed you will want to grab the makeOVPN.sh script here and replace it with the one on your pi that is at /opt/pivpn/makeOVPN.sh

Also QA note: 
To manually test the password on a generated key you'd just
`openssl rsa -in $NAME.key`

**Comment by projectdigital** [comment]
Will do. I'm out at the moment sorry but will let you know how it goes when I'm home. Few hours out. Thanks!

**Comment by adrigrillo** [comment]
I keep having this error. Just downloaded and installed, I also try copying the makeOVPN.sh file of the commit that resolves this bug and nothing.

**Comment by projectdigital** [comment]
You need to change the permissions for the file after you've copied it to the pi. It's not given full permissions by default. Worked perfectly Ray for me once I did this and rebooted.

**Comment by 0-kaladin** [comment]
The installer does set perms. Are you sure they didn't get messed up if you updated the file manually?

**Comment by adrigrillo** [comment]
Don't know what was the problem, I reinstalled raspbian again and now works perfectly.

**Comment by projectdigital** [comment]
Yup, installer set permissions correctly. When I manually copied the new file over though (used winscp) i had to update the permissions for it because the owner wasn't root.

**Comment by adrigrillo** [comment]
That sound logic, but I'm my case I only copied the content of the new makeOVPN.sh in the existing file with the correct permissions, so not permissions change would have been necesary. I didn't know what I did wrong, but with a fresh install everything worked fine again, so I'll say that this issue is closed. Thank you for the help.
