### ISSUE TITLE
bind9-dnsutils has unmet dependencies

### ISSUE THREAD

**Issue by birdybird123** [pivpn/pivpn#1483]
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*.
- [] The issue I am reporting *is* directly related to the pivpn installer script.
- [] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

**Describe the bug**

 The following packages have unmet dependencies:
 bind9-dnsutils : Depends: bind9-libs (= 1:9.16.22-1~deb11u1) but 1:9.16.27-1~deb11u1 is to be installed
E: Unable to correct problems, you have held broken packages.
:::    Failed to install dnsutils!
:::    Failed to install iptables-persistent!

On raspbian bullseye with OMV6 installed

**Additional context**

**Comment by orazioedoardo** [comment]
> Unable to correct problems, you have held broken packages.

What it you run `sudo apt update && sudo apt upgrade` to update the system before running the PiVPN installer?

**Comment by birdybird123** [comment]
did that already :
Depends: bind9-libs (= 1:9.16.22-1deb11u1) but 1:9.16.27-1deb11u1 is to be installed

**Comment by orazioedoardo** [comment]
What's the output of `cat /etc/os-release`, `apt-cache policy bind9-libs`, `apt-cache policy bind9-dnsutils`?

**Comment by birdybird123** [comment]
its now working. strange


Op zo 17 apr. 2022 09:37 schreef Orazio ***@***.***>:

**Comment by orazioedoardo** [comment]
I'm closing then.
