### ISSUE TITLE
expect EOF

### ISSUE THREAD

**Issue by funikki** [pivpn/pivpn#149]
# PiVPN Issue Template

## Console output of `curl install.pivpn.io | bash`
```

```

## Console output of `pivpn add` or `pivpn add nopass`
```

```

## Console output of `pivpn debug`
```

```

## Issue
After sending command pivpn add, this is what I got:
Enter a Name for the Client:  test
NOTE: If you run ./clean-all, I will be doing a rm -rf on /etc/openvpn/easy-rsa/keys
Enter the password for the client:
Enter the password again to verify:
/opt/pivpn/makeOVPN.sh: riga 76: expect: command not found
/opt/pivpn/makeOVPN.sh: riga 98: expect: command not found
[ERROR]: Client Public Key Certificate not found: test.crt

**Comment by redfast00** [comment]
Is `expect` installed? Can you run `which expect`?

**Comment by funikki** [comment]
I've installed Expect and now everything seems ok.
Thanks.
