### ISSUE TITLE
Pi-hole?

### ISSUE THREAD

**Issue by seiterseiter** [pivpn/pivpn#15]
In the contributions you had pi-hole, does that mean that this can block ads too? If so how do I enable it?

**Comment by 0-kaladin** [comment]
No, go to pi-hole.net to install that.  I've contributed to them cause I used their script framework and many of their functions as the basis for these scripts as well.  It is structured well and I saw no reason to re-invent the wheel there.

**Comment by seiterseiter** [comment]
I mean by having the vpn that can be accessed from anywhere around the world with Pi-Hole blocking ads in the vpn..
