### ISSUE TITLE
Debugging procedures needed

### ISSUE THREAD

**Issue by philgithub1** [pivpn/pivpn#150]
I have a zte f620 modem and portforwarding is easily settable. However nmap shows the port closed on the WAN and open,filtered on the LAN.
I thought the pivpn config tool would be able to change more configs. I hate to uninstall and reinstall. Can I uninstall/reinstall and save/reuse my client.ovpns and server dh keys since they take the longest.? That would be a nice option for debugging bad connections.
Does the WAN IP changing by the ISP affect the server settings or just the client?
How can I change the port on the server?
Can I test the install by using a client to point to the LAN address if so do I need to change anything on the server or just the client?

**Comment by redfast00** [comment]
@philgithub1: Yes, you can "easily" change your hostname/IP address, port and even protocol by editing: `/etc/openvpn/server.conf`, `/etc/openvpn/easy-rsa/keys/Default.txt` and your `.ovpn` files. If your ISP changes your IP, you can use a service like DynDNS or FreeDNS to always forward the domain to your IP address.

**Comment by philgithub1** [comment]
@redfast00 is there a use or need to have the server.conf maintain the updated IP address. I can email changes as they occur for the remote client use. But why would the server care what the WAN IP is?

**Comment by redfast00** [comment]
Yes, indeed. You do however need to change all three files if you want to change ports or protocols. I'm sorry for the miscommunication.

**Comment by jamie-sherriff** [comment]
Sorry for digging up and old thread but i wanted to change stuff aswell and noticed i did not have Default.txt file at /etc/openvpn/easy-rsa/keys/Default.txt

I instead found it in /etc/openvpn/easy-rsa/pki/Default.txt, has the location of default.txt changed?

**Comment by gsaiz** [comment]
@jamie-sherriff I can confirm this, I would suggest updating the documentation

**Comment by McNugget6750** [comment]
I have the same issue with editing files. The entry hostname doesn't even exist in my Default.txt
Therefore I can't change my server IP/hostname.
The documentation if late 2016. Please ipdate when these important changes are made to the config files and file locations. 

PIVPN seems extremely easy but these changes make it difficult for starters with this system.

Thanks
Timo

**Comment by cfcolaco** [comment]
@McNugget6750 I just moved to a new home in a new country and I am rebuilding my stuff... Please open a new ticket explaining exactly your issue and what is the problem you are facing right now ( don't forget to mention this issue ) 

Thank you.

**Comment by k-five** [comment]
Hi,
I had to reopen this thread for not creating a new one.
I tried everything to change the port to other number and it did not work. It just works with `1194`.  

Where should be modified for changing a port?

I modified (server) :

```bash
grep 5090 -ir .
./server.conf:port 5090
./easy-rsa/pki/Default.txt:remote  xxx.xxx.xxx.xxx 5090
./easy-rsa/pki/name.ovpn:remote xxx.xxx.xxx.xxx 5090
```
and (client):
```bash
client
dev tun
proto udp
remote xxx.xxx.xxx.xxx 5090
resolv-retry infinite
nobind
remote-cert-tls server
```
as well as `iptable`  (server):
```bash
-A INPUT -i eth0 -p udp -m udp --dport 5090 -m comment --comment openvpn-input-rule -j ACCEPT
```
and the service is listening on the port `5090`:
```bash
udp      UNCONN      0       0      0.0.0.0:5090       0.0.0.0:*      users:(("openvpn",pid=25798,fd=6))
```

**Comment by SirMcSourTowel** [comment]
> Hi, I had to reopen this thread for not creating a new one. I tried everything to change the port to other number and it did not work. It just works with `1194`.
> 
> Where should be modified for changing a port?
> 
> I modified (server) :
> 
> ```shell
> grep 5090 -ir .
> ./server.conf:port 5090
> ./easy-rsa/pki/Default.txt:remote  xxx.xxx.xxx.xxx 5090
> ./easy-rsa/pki/name.ovpn:remote xxx.xxx.xxx.xxx 5090
> ```
> 
> and (client):
> 
> ```shell
> client
> dev tun
> proto udp
> remote xxx.xxx.xxx.xxx 5090
> resolv-retry infinite
> nobind
> remote-cert-tls server
> ```
> 
> as well as `iptable` (server):
> 
> ```shell
> -A INPUT -i eth0 -p udp -m udp --dport 5090 -m comment --comment openvpn-input-rule -j ACCEPT
> ```
> 
> and the service is listening on the port `5090`:
> 
> ```shell
> udp      UNCONN      0       0      0.0.0.0:5090       0.0.0.0:*      users:(("openvpn",pid=25798,fd=6))
> ```

I too am having this issue. Please advise
