### ISSUE TITLE
[BUG] TLS key negotiation failed to occur within 60 seconds (check your network connectivity)

### ISSUE THREAD

**Issue by indjev99** [pivpn/pivpn#1502]
I've had a pivpn server set up for a a long time and haven't had issues until now. I've been using it from multiple devices and from multiple networks. However, 2-3 days ago it stopped working for all clients from all networks I tried. No changes have been made to the server or the network configuration thereof. When connecting from, say, the OpenVPN android app, the error is not very informative. I checked the server logs using `sudo systemctl status openvpn@server.service` and the error shown is the one in the title: `TLS key negotiation failed to occur within 60 seconds (check your network connectivity)`. However, this appears instantly when I try to connect (not after 60 seconds). I saw a few similar issues and none of the "fixes" listed there worked for me.

**Comment by Fuckingnameless** [comment]
same issue although it´s a new install with me, checked all FAQ items, wireguard works

OS: last raspbian 64bit

**Comment by orazioedoardo** [comment]
Can you port the log at `/var/log/openvpn.log`, removing public IP addresses?

**Comment by mhmdimmo** [comment]
same issue here nothing changed on my setup was working fine and then the system log shows TLS key negotiation failed to occur within 60 seconds (check your network connectivity)

tried to make several clean setup again but the error still the same
