### ISSUE TITLE
PiVPN gets stuck at Install for OpenVPN & Wireguard

### ISSUE THREAD

**Issue by JustMyLuck6** [pivpn/pivpn#1511]
I followed the instructions after I choose to install OpenVPN or WireGuard the installation stopped and will not continue. I researched all possible fixes but cannot find any. I tried every other installation method on the pivpn page and I still run into the same issue. I also used port forwarding on my router. 
![Screenshot 2022-04-28 035649](https://user-images.githubusercontent.com/93460515/165728127-d1a0f177-6ce3-49c1-82cb-7fd1cb2095be.png)

**Comment by 4s3ti** [comment]
Please Fill in the report template adequately. 

https://github.com/pivpn/pivpn#feedback--support

> PiVPN team may close any Discussion/Issue without any warning if they don't follow the Guidelines

**Comment by romton843** [comment]
I have the exact same issue. I will fill the report template adequately.

**Comment by romton843** [comment]
Have you tried to type "sudo" in front of "curl -L https://install.pivpn.io/ | bash"

**Comment by bassamanator** [comment]
Having the same issue. Tried multiple times and it just gets stuck. Just now I tried with `sudo` and this time there was a message, though still stuck.

```sh
::: Checking for existing base files...
:::    Checking /usr/local/src/pivpn is a repo... OK!
:::     Updating repo in /usr/local/src/pivpn from https://github.com/pivpn/pivpn.git ... done!
::: Using VPN: WireGuard
pivpn/auto_install/install.sh: line 1939: /tmp/setupVars.conf: Permission denied <-- NEW
```
