### ISSUE TITLE
PiVPN Profiles cannot receive data after Raspberry pi downtime. 

### ISSUE THREAD

**Issue by krakenbait** [pivpn/pivpn#1517]
## In raising this issue, I confirm the following:

`{please fill the checkboxes, e.g: [X]}`

- [X] I have read the [documentation](https://docs.pivpn.io)
- [] Is it a feature request? please consider opening a [Discussion] (https://github.com/pivpn/pivpn/discussions/new)
- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.  
- [] The issue I am reporting *is* directly related to the pivpn installer script.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

### Has your install failed? 
```
no
```

### Describe the issue
Every time my Raspberry Pi restarts, I completely lose the ability to use my PiVPN profiles via Wireguard. The data received portion of the WireGuard tunnel just fails to appear (see attached photo). The only way I currently know how to fix this issue is to create a brand new PiVPN profile for each device and install them individually. It's growing quite annoying and I am wondering if there is a simpler way of restarting the PiVPN profiles. 

**Expected behavior**
My PiVPN profiles would continue to work normally after a rebooted Pi server. 

**Screenshots**
<img width="314" alt="Screen Shot 2022-05-03 at 11 07 58 PM" src="https://user-images.githubusercontent.com/80723669/166622069-e51bdba3-0fa4-423d-a064-8f1888c83dbd.png">

### Can you replicate the issue? Describe the steps below

1. Unplug Raspberry Pi 4
2.  Restart the device 
3. Turn on Wireguard protocol
4. PiVPN refuses to download any data

### Have you searched for similar issues and solutions?
    (yes/no / which issues?)
yes

**Additional context**

### Have you taken any steps towards solving your issue?
```
I have had to manually reinstall each PiVPN profile on every device any time my Raspberry Pi experiences downtime. The only way I know to get it to work again is to completely install a new profile each time it happens. 
```

#### What type of hardware are you running PiVPN at? 

```
A standalone hardwired Raspberry Pi 4 with Pihole running. 

```
#### Output of `uname -a`
```
Linux pi 5.15.32-v7l+ #1538 SMP Thu Mar 31 19:39:41 BST 2022 armv7l GNU/Linux
```

#### Output of `cat /etc/os-release`
```
 PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

### If install failed Please provide the console output of  `curl -L https://install.pivpn.io | bash`
```
N/A, Install was successful. 
```

### Console output of      `curl -L install.pivpn.io | bash`
```
N/A, Install was successful. 
```

### Console output of      `pivpn add` or `pivpn add nopass`
```
  N/A, Profile installation is successful. 
```

### Console output of      `pivpn debug`

```
  ::: Generating Debug Output
::::		PiVPN debug		 ::::
=============================================
::::		Latest commit		 ::::
Branch: master
Commit: f80b0a7962d91862132c0a4abd65c1e67bd37bd7
Author: 4s3ti
Date: Fri Dec 3 21:41:13 2021 +0100
Summary: Update Changelog
=============================================
::::	    Installation settings    	 ::::
PLAT=Raspbian
OSCN=bullseye
USING_UFW=0
IPv4dev=eth0
dhcpReserv=1
IPv4addr=192.165.9.176/25
IPv4gw=192.165.9.1
install_user=pi
install_home=/home/pi
VPN=wireguard
pivpnPORT=51820
pivpnDNS1=10.6.0.1
pivpnDNS2=
pivpnHOST=REDACTED
INPUT_CHAIN_EDITED=0
FORWARD_CHAIN_EDITED=0
pivpnPROTO=udp
pivpnMTU=1420
pivpnDEV=wg0
pivpnNET=10.6.0.0
subnetClass=24
ALLOWED_IPS="0.0.0.0/0, ::0/0"
UNATTUPG=1
INSTALLED_PACKAGES=(bsdmainutils iptables-persistent wireguard-tools qrencode)
=============================================
::::  Server configuration shown below   ::::
[Interface]
PrivateKey = server_priv
Address = 10.6.0.1/24
MTU = 1420
ListenPort = 51820
### begin Michael_iPhone_1611 ###
[Peer]
PublicKey = Michael_iPhone_1611_pub
PresharedKey = Michael_iPhone_1611_psk
AllowedIPs = 10.6.0.2/32
### end Michael_iPhone_1611 ###
### begin Michael_iMac_1611 ###
[Peer]
PublicKey = Michael_iMac_1611_pub
PresharedKey = Michael_iMac_1611_psk
AllowedIPs = 10.6.0.3/32
### end Michael_iMac_1611 ###
### begin Michael_Macbook_1611 ###
[Peer]
PublicKey = Michael_Macbook_1611_pub
PresharedKey = Michael_Macbook_1611_psk
AllowedIPs = 10.6.0.4/32
### end Michael_Macbook_1611 ###
### begin Katie_iPhone_1611 ###
[Peer]
PublicKey = Katie_iPhone_1611_pub
PresharedKey = Katie_iPhone_1611_psk
AllowedIPs = 10.6.0.5/32
### end Katie_iPhone_1611 ###
### begin Katie_Macbook_1611 ###
[Peer]
PublicKey = Katie_Macbook_1611_pub
PresharedKey = Katie_Macbook_1611_psk
AllowedIPs = 10.6.0.6/32
### end Katie_Macbook_1611 ###
### begin Michael_Desktop_1611 ###
[Peer]
PublicKey = Michael_Desktop_1611_pub
PresharedKey = Michael_Desktop_1611_psk
AllowedIPs = 10.6.0.7/32
### end Michael_Desktop_1611 ###
=============================================
::::  Client configuration shown below   ::::
[Interface]
PrivateKey = Michael_iPhone_1611_priv
Address = 10.6.0.2/24
DNS = 10.6.0.1

[Peer]
PublicKey = server_pub
PresharedKey = Michael_iPhone_1611_psk
Endpoint = REDACTED:51820
AllowedIPs = 0.0.0.0/0, ::0/0
=============================================
:::: 	Recursive list of files in	 ::::
::::	[4m/etc/wireguard shown below	 ::::
/etc/wireguard:
configs
keys
wg0.conf

/etc/wireguard/configs:
clients.txt
Katie_iPhone_1611.conf
Katie_Macbook_1611.conf
Michael_Desktop_1611.conf
Michael_iMac_1611.conf
Michael_iPhone_1611.conf
Michael_Macbook_1611.conf

/etc/wireguard/keys:
Katie_iPhone_1611_priv
Katie_iPhone_1611_psk
Katie_iPhone_1611_pub
Katie_Macbook_1611_priv
Katie_Macbook_1611_psk
Katie_Macbook_1611_pub
Michael_Desktop_1611_priv
Michael_Desktop_1611_psk
Michael_Desktop_1611_pub
Michael_iMac_1611_priv
Michael_iMac_1611_psk
Michael_iMac_1611_pub
Michael_iPhone_1611_priv
Michael_iPhone_1611_psk
Michael_iPhone_1611_pub
Michael_Macbook_1611_priv
Michael_Macbook_1611_psk
Michael_Macbook_1611_pub
server_priv
server_pub
=============================================
::::		Self check		 ::::
:: [OK] IP forwarding is enabled
:: [OK] Iptables MASQUERADE rule set
:: [OK] WireGuard is running
:: [OK] WireGuard is enabled (it will automatically start on reboot)
:: [OK] WireGuard is listening on port 51820/udp
=============================================
:::: Having trouble connecting? Take a look at the FAQ:
:::: https://docs.pivpn.io/faq
=============================================
:::: WARNING: This script should have automatically masked sensitive       ::::
:::: information, however, still make sure that PrivateKey, PublicKey      ::::
:::: and PresharedKey are masked before reporting an issue. An example key ::::
:::: that you should NOT see in this log looks like this:                  ::::
:::: YIAoJVsdIeyvXfGGDDadHh6AxsMRymZTnnzZoAb9cxRe                          ::::
=============================================
::::		Debug complete		 ::::
::: 
::: Debug output completed above.
::: Copy saved to /tmp/debug.log
::: 
``

**Comment by orazioedoardo** [comment]
Restart the Pi and post the output of `sudo systemctl status wg-quick@wg0`.

**Comment by orazioedoardo** [comment]
I thought that maybe the vpn didn’t start on boot but looks like it does. Are you using the same profile on multiple devices at the same time?

**Comment by krakenbait** [comment]
Each device using wireguard has a separate profile, you can see them broken down in the debug log.

**Comment by orazioedoardo** [comment]
Yes, I saw them but I could not exclude that case. Can you run [tcpdump](https://docs.pivpn.io/faq/#packet-capture) to see whether packets reach the VPN? Do you see all clients (10.6.0.X) in `pivpn -c`?

**Comment by krakenbait** [comment]
All of my clients are accounted for, although it appears that no packets are reaching the Pi with the VPN turned on. 
<img width="730" alt="Screen Shot 2022-05-04 at 1 17 25 PM" src="https://user-images.githubusercontent.com/80723669/166801132-a1e64f0d-5b2d-4190-9816-e915e84386de.png">
<img width="762" alt="Screen Shot 2022-05-04 at 1 22 07 PM" src="https://user-images.githubusercontent.com/80723669/166801149-c0b8df30-7bcf-43c5-ac16-cd0c280aee58.png">

**Comment by orazioedoardo** [comment]
The port in the tcpdump command is 51820, not 52290. Also avoid posting images of text.

**Comment by krakenbait** [comment]
My apologies, although I get the same result with the VPN client active. 

pi@pi:~ $ sudo -s
root@pi:/home/pi# tcpdump -n -i eth0 udp port 51820
tcpdump: verbose output suppressed, use -v[v]... for full protocol decode
listening on eth0, link-type EN10MB (Ethernet), snapshot length 262144 bytes

**Comment by krakenbait** [comment]
My apologies, although I get the same result with the VPN client active. 

pi@pi:~ $ sudo -s
root@pi:/home/pi# tcpdump -n -i eth0 udp port 51820
tcpdump: verbose output suppressed, use -v[v]... for full protocol decode
listening on eth0, link-type EN10MB (Ethernet), snapshot length 262144 bytes

**Comment by orazioedoardo** [comment]
Well if you don’t see any packets it means… that the client is not actually sending anything. What if you try to remove and add the same configuration on the client (let’s say on the macbook)? Don’t generate a new one with PiVPN.

**Comment by krakenbait** [comment]
I deleted and added the same configuration in the wireguard application on my mac, but can only see the same results. No data received and minimal sent data.

**Comment by orazioedoardo** [comment]
Connect the macbook to the same network as raspberry pi, then in the wireguard app, edit the endpoint for the configuration to `192.165.9.176` (the lan ip of the pi). What about now?

**Comment by krakenbait** [comment]
It works! Would you mind explaining to me how the endpoint might have been changed?

**Comment by orazioedoardo** [comment]
It works in the local network, to work over the internet, endpoint must be the public IP of your home connection.

During the installation you are asked whether you want to set the endpoint to an IP or a domain name. It is then saved as `pivpnHOST` in the file `/etc/pivpn/wireguard/setupVars.conf`, which is used as reference when creating clients.

You should verify that Endpoint matches the public IP, see the troubleshooting at my link above.

**Comment by krakenbait** [comment]
Thanks for your help, I'll check out the documentation you sent.
