### ISSUE TITLE
Need to install expect 

### ISSUE THREAD

**Issue by martinalberto** [pivpn/pivpn#152]
# PiVPN Issue Template

## Console output 
```
/opt/pivpn/makeOVPN.sh: line 73: expect: command not found

```

## raspbery pi version:
```

Version hardware: 2.1 
 Software: RASPBIAN JESSIE LITE very important LITE!

```

## Solution:

```
sudo apt-get install expect
```

I think it is better to include install expect in install.sh

**Comment by 0-kaladin** [comment]
Installer already installs expect. Would like to see your install output to see why it didn't get in.

**Comment by martinalberto** [comment]
I try again and i don't have this problem.

It is possible 1 case:

1.- Start install script.
2.- stop script by Ctl+C in section  "apt-get update"
3.- Start again InstallScript.
4.- in this time the "apt-get update" don't execute.
5.- When the script will install expect -> respond:
```
root@raspberrypi:~# apt-get --no-install-recommends install expect
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package expect
```
6.- And the expect software is not instaled.

This case is only if you don't make a "apt-get update".

I hope it can help you.

_P.D: you script is very very useful., thanks !_

**Comment by 0-kaladin** [comment]
ah, ok.  so basically the script detected that apt-get update was run, yet it really wasn't, hence expect was never found.  I don't think any adjustments are required in the script here.
when you first install any OS you should run apt-get update && apt-get upgrade to get the latest packages.
