### ISSUE TITLE
404 links from https://github.com/pivpn/pivpn/discussions

### ISSUE THREAD

**Issue by 2boot** [pivpn/pivpn#1526]
## In raising this issue, I confirm the following:

`{please fill the checkboxes, e.g: [X]}`

- [] I have read the [documentation](https://docs.pivpn.io)
- [] Is it a feature request? please consider opening a [Discussion] (https://github.com/pivpn/pivpn/discussions/new)
- [] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*.  
- [] The issue I am reporting *is* directly related to the pivpn installer script.
- [] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

### Has your install failed? 
```
yes/no
```

### Describe the issue

**Expected behavior**

**Screenshots**

### Have you searched for similar issues and solutions?
    (yes/no / which issues?)

**Additional context**

### Have you taken any steps towards solving your issue?
```
  which?
```

#### What type of hardware are you running PiVPN at?

```
Raspberrypi (specify the model)
Ordroid
OrangePi
bananaPi
Virtual machine
```
#### Output of `uname -a`
```
  OUTPUT HERE / ANSWER HERE
  DO NOT DELETE THE BACK-TICKS 
  PASTE THE OUTPUT INSIDE THE BACK-TICKS
```

#### Output of `cat /etc/os-release`
```
  OUTPUT HERE / ANSWER HERE
  DO NOT DELETE THE BACK-TICKS 
  PASTE THE OUTPUT INSIDE THE BACK-TICKS
```

### If install failed Please provide the console output of  `curl -L https://install.pivpn.io | bash`
```
  OUTPUT HERE / ANSWER HERE
  DO NOT DELETE THE BACK-TICKS 
  PASTE THE OUTPUT INSIDE THE BACK-TICKS
```

### Console output of      `curl -L install.pivpn.io | bash`
```
  OUTPUT HERE
  DO NOT DELETE THE BACK-TICKS 
  PASTE THE OUTPUT INSIDE THE BACK-TICKS
```

### Console output of      `pivpn add` or `pivpn add nopass`
```
  OUTPUT HERE
  DO NOT DELETE THE BACK-TICKS 
  PASTE THE OUTPUT INSIDE THE BACK-TICKS
```

### Console output of      `pivpn debug`

```
  OUTPUT HERE
  DO NOT DELETE THE BACK-TICKS 
  PASTE THE OUTPUT INSIDE THE BACK-TICKS
```

**Comment by 2boot** [comment]
My apologies for contacting on a closed post but I can see no other way.

If I click the "support" and "bug report" requests from this page https://github.com/pivpn/pivpn/discussions
I get led to these links
https://raw.githubusercontent.com/pivpn/pivpn/master/.github/ISSUE_TEMPLATE/pivpn-report.md
https://raw.githubusercontent.com/pivpn/pivpn/master/.github/ISSUE_TEMPLATE/bug_report.md
both these result in 404 pages

I see you changed reporting 26 days ago and think somethings may not have been fully updated.

**Comment by 4s3ti** [comment]
Thanks for bringing this up .. those are actually needing update, I forgot to update those when i changed the issue template.

**Comment by 4s3ti** [comment]
Fixed it believe there's nothing else pointing towards those documents. 

Thanks.
