### ISSUE TITLE
pivpn command not found after installation

### ISSUE THREAD

**Issue by mickdavis** [pivpn/pivpn#153]
Immediately after running the pivpn installation when I try to run "pivpn add" the command is not found.  I searched the entire drive and it is not there.  It worked a couple of days ago.

**Comment by redfast00** [comment]
Is there a PiVPN folder in `/opt`?

**Comment by mickdavis** [comment]
Yes, but it's empty.

**Comment by redfast00** [comment]
That's odd... What OS are you on? Did you do anything special?

**Comment by mickdavis** [comment]
Raspberry Pi Jessian Lite

Nothing special.  I ran it once and got everything working except I
couldn't connect to one of my machines with a JNLP application, so I
thought I would create a different installation using TCP and that install
did not have the pivpn script.   That was on a new sd card btw.

So I thought maybe there was a bug with the TCP install, wiped the sd card
and did it again choosing UDP.  Same result.

**Comment by catcam** [comment]
same problem here  ...rbpi2 raspbian jesse ...  /opt/pivpn/    empty    
regards and tnx for great work Niksa

**Comment by 0-kaladin** [comment]
Would love to see install output if you have or can dupe.
I should save this to a file so we can always get.  Another thing to add...

**Comment by 0-kaladin** [comment]
Also what about /etc/.pivpn
Anything in there?

**Comment by mickdavis** [comment]
There isn't an /etc/.pivpn.  There is a /etc/pivpn and it contains 6 files,
all uppercase names, such as INSTALL_PORT, INSTALL_PROTO, INSTALL_USER...

**Comment by mickdavis** [comment]
I would be happy to.  I'm not a Linux expert, can you give me some pointers
on how to do this?

**Comment by catcam** [comment]
terminal output:


Last login: Fri Nov 18 19:26:15 2016 from 192.168.0.28
root@minibian:~# pivpn
-bash: pivpn: command not found
root@minibian:~# curl -L https://install.pivpn.io | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   178  100   178    0     0    174      0  0:00:01  0:00:01 --:--:--   174
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0:::
::: You are root.
100 42627  100 42627    0     0  26884      0  0:00:01  0:00:01 --:--:-- 88437
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: There are 167 updates availible for your pi!
::: We recommend you run 'sudo apt-get upgrade' after installing PiVPN!
:::
:::
::: Checking dependencies:
:::    Checking for openvpn... already installed!
:::    Checking for easy-rsa... already installed!
:::    Checking for git... already installed!
:::    Checking for iptables-persistent... already installed!
:::    Checking for dnsutils... already installed!
:::    Checking for expect... already installed!
:::    Checking for whiptail... already installed!
::: Verifying free disk space...
::: Using interface: eth0
::: Static IP already configured.
::: Using User: niksa
:::
::: Stopping OpenVPN service... done.
:::
::: Checking for existing base files...
:::    Checking /etc/.pivpn is a repo... not found!!
:::    Cloning https://github.com/pivpn/pivpn.git into /etc/.pivpn... done!
:::
::: Installing scripts to /opt/pivpn...cp: cannot stat ‘/etc/.pivpn/scripts/makeOVPN.sh’: No such file or directory
cp: cannot stat ‘/etc/.pivpn/scripts/listOVPN.sh’: No such file or directory
cp: cannot stat ‘/etc/.pivpn/scripts/removeOVPN.sh’: No such file or directory
cp: cannot stat ‘/etc/.pivpn/scripts/uninstall.sh’: No such file or directory
cp: cannot stat ‘/etc/.pivpn/scripts/pivpnDebug.sh’: No such file or directory
chmod: cannot access ‘/opt/pivpn/makeOVPN.sh’: No such file or directory
chmod: cannot access ‘/opt/pivpn/listOVPN.sh’: No such file or directory
chmod: cannot access ‘/opt/pivpn/removeOVPN.sh’: No such file or directory
chmod: cannot access ‘/opt/pivpn/uninstall.sh’: No such file or directory
chmod: cannot access ‘/opt/pivpn/pivpnDebug.sh’: No such file or directory
cp: cannot stat ‘/etc/.pivpn/pivpn’: No such file or directory
chmod: cannot access ‘/usr/local/bin/pivpn’: No such file or directory
cp: cannot stat ‘/etc/.pivpn/scripts/bash-completion’: No such file or directory
bash: line 390: /etc/bash_completion.d/pivpn: No such file or directory
 done.
::: Using protocol: udp
NOTE: If you run ./clean-all, I will be doing a rm -rf on /etc/openvpn/easy-rsa/keys
::: Building CA...
bash: line 797: /etc/.pivpn/ca_info.txt: No such file or directory

::: CA Complete.
pkitool: Need a readable ca.crt and ca.key in /etc/openvpn/easy-rsa/keys
Try pkitool --initca to build a root certificate/key.
Generating DH parameters, 1024 bit long safe prime, generator 2
This is going to take a long time
........................+................................+....................................................................................................+..................................................................................................................................................................+.........................+............................................................+.........................................................................................+..........+..................+..................................+.....+............................................................................................................+.....................................+......................+.................+.............................................................................................................................................................................+...................................+.............................+..............................+.....+........................................+..............+.....................................+...............................................................+...........................+..................................................................+.........................................................................+...................................+......................................................+............+......+....................................+...................................+.............................................................+.......+.........................+...........................................+...........+.......+...........+.......................................................................................+.................................................+.....+..........................................................................................................................................+.............................................................................++*++*++*
cp: cannot stat ‘/etc/.pivpn/server_config.txt’: No such file or directory
sed: can't read /etc/openvpn/server.conf: No such file or directory
sed: can't read /etc/openvpn/server.conf: No such file or directory
sed: can't read /etc/openvpn/server.conf: No such file or directory
sed: can't read /etc/openvpn/server.conf: No such file or directory
sed: can't read /etc/openvpn/server.conf: No such file or directory
net.ipv4.ip_forward = 1
run-parts: executing /usr/share/netfilter-persistent/plugins.d/15-ip4tables save
run-parts: executing /usr/share/netfilter-persistent/plugins.d/25-ip6tables save
cp: cannot stat ‘/etc/.pivpn/Default.txt’: No such file or directory
sed: can't read /etc/openvpn/easy-rsa/keys/Default.txt: No such file or directory
sed: can't read /etc/openvpn/easy-rsa/keys/Default.txt: No such file or directory
mkdir: cannot create directory ‘/home/niksa/ovpns’: File exists
::: Using Google DNS servers.
Synchronizing state for openvpn.service with sysvinit using update-rc.d...
Executing /usr/sbin/update-rc.d openvpn defaults
Executing /usr/sbin/update-rc.d openvpn enable
::: Install Complete...
root@minibian:~#

**Comment by 0-kaladin** [comment]
Thanks!

**Comment by 0-kaladin** [comment]
@catcam can you try this again now?

**Comment by 0-kaladin** [comment]
Or @mickdavis if you can run the installer again now.

**Comment by catcam** [comment]
sorry for waiting ... here is the output:

root@minibian:~# curl -L https://install.pivpn.io | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   178  100   178    0     0    160      0  0:00:01  0:00:01 --:--:--   160
:::
::: You are root.
100 42700  100 42700    0     0  24338      0  0:00:01  0:00:01 --:--:-- 24338
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: There are 179 updates availible for your pi!
::: We recommend you run 'sudo apt-get upgrade' after installing PiVPN!
:::
:::
::: Checking dependencies:
:::    Checking for openvpn... already installed!
:::    Checking for easy-rsa... already installed!
:::    Checking for git... already installed!
:::    Checking for iptables-persistent... already installed!
:::    Checking for dnsutils... already installed!
:::    Checking for expect... already installed!
:::    Checking for whiptail... already installed!
::: Verifying free disk space...
::: Using interface: eth0
::: Static IP already configured.
::: Using User: niksa
 [/]  E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?                                                                              :::
::: Stopping OpenVPN service... done.
:::
::: Checking for existing base files...
:::    Checking /etc/.pivpn is a repo...:::    Cloning https://github.com/pivpn/pivpn.git into /etc/.pivpn... done!
:::
::: Installing scripts to /opt/pivpn...cp: cannot stat ‘/etc/.pivpn/scripts/makeOVPN.sh’: No such file or directory
cp: cannot stat ‘/etc/.pivpn/scripts/listOVPN.sh’: No such file or directory
cp: cannot stat ‘/etc/.pivpn/scripts/removeOVPN.sh’: No such file or directory
cp: cannot stat ‘/etc/.pivpn/scripts/uninstall.sh’: No such file or directory
cp: cannot stat ‘/etc/.pivpn/scripts/pivpnDebug.sh’: No such file or directory
chmod: cannot access ‘/opt/pivpn/makeOVPN.sh’: No such file or directory
chmod: cannot access ‘/opt/pivpn/listOVPN.sh’: No such file or directory
chmod: cannot access ‘/opt/pivpn/removeOVPN.sh’: No such file or directory
chmod: cannot access ‘/opt/pivpn/uninstall.sh’: No such file or directory
chmod: cannot access ‘/opt/pivpn/pivpnDebug.sh’: No such file or directory
cp: cannot stat ‘/etc/.pivpn/pivpn’: No such file or directory
chmod: cannot access ‘/usr/local/bin/pivpn’: No such file or directory
cp: cannot stat ‘/etc/.pivpn/scripts/bash-completion’: No such file or directory
bash: line 390: /etc/bash_completion.d/pivpn: No such file or directory
 done.
::: Using protocol: udp
NOTE: If you run ./clean-all, I will be doing a rm -rf on /etc/openvpn/easy-rsa/keys
::: Building CA...
bash: line 794: /etc/.pivpn/ca_info.txt: No such file or directory

::: CA Complete.
pkitool: Need a readable ca.crt and ca.key in /etc/openvpn/easy-rsa/keys
Try pkitool --initca to build a root certificate/key.
Generating DH parameters, 1024 bit long safe prime, generator 2
This is going to take a long time
........................+.........+.........................+............+.......................+.....................................+.................+...................................................................+.............+.............+...................................................................................+.........................+.............................................................+........................................+........................................+.............+..............+..+..........................................................+.......................................................................................................+...................................................................................................................+..........+..................................................................+...............................+...................................................................................................................................+...............+.+.....................+................+.............................................................................+....................................................+.......................................................+...................+.+............+............+.................+.....................................................................+...................+.........................................................+.................................................++*++*++*
cp: cannot stat ‘/etc/.pivpn/server_config.txt’: No such file or directory
sed: can't read /etc/openvpn/server.conf: No such file or directory
sed: can't read /etc/openvpn/server.conf: No such file or directory
sed: can't read /etc/openvpn/server.conf: No such file or directory
sed: can't read /etc/openvpn/server.conf: No such file or directory
sed: can't read /etc/openvpn/server.conf: No such file or directory
net.ipv4.ip_forward = 1
run-parts: executing /usr/share/netfilter-persistent/plugins.d/15-ip4tables save
run-parts: executing /usr/share/netfilter-persistent/plugins.d/25-ip6tables save
cp: cannot stat ‘/etc/.pivpn/Default.txt’: No such file or directory
sed: can't read /etc/openvpn/easy-rsa/keys/Default.txt: No such file or directory
sed: can't read /etc/openvpn/easy-rsa/keys/Default.txt: No such file or directory
mkdir: cannot create directory ‘/home/niksa/ovpns’: File exists
::: Using Google DNS servers.
Synchronizing state for openvpn.service with sysvinit using update-rc.d...
Executing /usr/sbin/update-rc.d openvpn defaults
Executing /usr/sbin/update-rc.d openvpn enable
::: Install Complete...
root@minibian:~#

**Comment by 0-kaladin** [comment]
Still not sure why it seems not to be getting the git files down to /etc/.pivpn.
But your systems dpkg is locked.  
Can you reboot
then run `apt-get update && apt-get upgrade`
make sure the above didn't error.
then reboot
then run the installer again?

**Comment by catcam** [comment]
i did this ... and now is unsuported os .... anyway tnx for time .... switching to full size raspbian
Best regards Niksa

**Comment by 0-kaladin** [comment]
I use jessie lite.  I'm going to say something wrong with your sd card, the part that is failing for you is just writing to sd card.

**Comment by 73** [comment]
For future reference:
This happens if `/etc/.pivpn` and `/opt/pivpn` exist prior to installation. Remove them and your good.

**Comment by Mithrandir2k17** [comment]
I had the same issue. ovpn files were copied to home//ovpns. After adding the lacking INSTALL_USER file I found out that I am also lacking the Default.txt since only the certificates were echoe'd into the file but not any of the configuration. I tried a fresh install so this:

> For future reference:
This happens if /etc/.pivpn and /opt/pivpn exist prior to installation. Remove them and your good.

could not have caused any of the problems. Upon manually fixing the ovpn file and trying to connect to the vpn I got stuck on it trying to connect forever but that might have had other reasons. I am running on a Raspi model 3B and on the latest raspian-stretch-lite with all updates installed. I removed my installtion for now, hoping for a fix being available soon :) especially since ufw seems to have problems on this version as well and I sadly don't have the time to set everything up manually atm.

**Comment by edegraaff** [comment]
Having the same issues seems it fails somewhere during installation in a lite version of raspberian lite somewhere the prereq's are not there and also the dialogues are not similar as i should expect like, no questions asked regarding udp or tcp

**Comment by tmxkn1** [comment]
I'm finnally able to solve this problem.

What was my problem:
- after writing `sudo pivpn add` and hit enter, console returns something similar to below:  
```
E: etc\pivpn\INSTALL_USER not found.
Enter a name for the client:
```
- after entering user name and password, console returns something similar to below:

```
...
E: cat Default.txt: No such file or directory
...
file saved to home//ovpns
```

What I did to solve the problem:

- remove `/etc/.pivpn` and `/opt/pivpn`.
- get root permission `sudo -s`.
- reinstall the script.

**Comment by thrasher0815** [comment]
If anyone is looking this up... I'm also using a custom build of Raspian (OctoPi) and had the same errors ... 
```
:::    Checking /etc/.pivpn is a repo...:::     Updating repo in /etc/.pivpn... done!
:::
::: Stopping OpenVPN service... done.
:::
::: Installing scripts to /opt/pivpn...cp: cannot stat '/etc/.pivpn/scripts/makeOVPN.sh': No such file or directory
```

I checked /etc/.pivpn and the directory was empty. 

For sh*ts and giggles, I tried to clone the repo manually into the directory, running
`git clone https://github.com/pivpn/pivpn.git /etc/.pivpn`
and I got a permission denied. 

So I tried it with sudo and got a nice warning saying: 
`Please do not run git as root, your regular user account is enough :)

If you need to run git with root rights for some other application than
what comes preinstalled on this image you can remove this sanity check:

    sudo rm /root/bin/git

You might have to restart your login session after doing that.`

So apparently in my build, sudo is not allowed to run git. I removed the "sanity check" and ran the installer script again - this time it was smooth sailing.

**Comment by hhoweson** [comment]
Finally got this working (=

I think what did it for me was:

```
sudo rm -r /etc/.pivpn
sudo rm /root/bin/git
sudo curl -L https://install.pivpn.io | bash
```

Removing any existing folder, enabling proper sudo permissions for git and then attempting a reinstall seemed to do it for me.
