### ISSUE TITLE
Wireguard not available as an option

### ISSUE THREAD

**Issue by gaston-arg** [pivpn/pivpn#1547]
Hi everyone,

Recently I was trying to reinstall Wireguard on my Linuc device running Dietpi OS (HW is Orane Pi Zero) but on the installation screen it goes straight to OpenVPN, and I'm not given the option to choose between Wireguard and OpenVPN.

Any clues on why might this be happening?
Thanks

**Comment by rexdivakar** [comment]
Even i'm facing the same issue !!

**Comment by 4s3ti** [comment]
Yes I do actually have clues, however seems you have not read the documentation :) 

Read here: https://github.com/pivpn/pivpn#feedback--support 

and here: https://docs.pivpn.io/faq/#what-boardsoses-does-pivpn-support 

And then if you still have not found your answer ... Re-open this issue and properly fill the Template that was presented to you when you pressed the green button, it exists for a reason :)

**Comment by gaston-arg** [comment]
The template is mainly focused on existing installations. I can't even install it.

**Comment by 4s3ti** [comment]
Rly going down that route? 
Fill what you can! because last time i checked the template asks things that can be answered without installation, it even.. imagine .. it even asks if you can install it or not
