### ISSUE TITLE
Orange PI Plus

### ISSUE THREAD

**Issue by kgoerbig** [pivpn/pivpn#155]
I ran this script fine on a Raspberry PI II, however, I was wondering if it can be run on a Orange PI Plus? Biggest benefit of the Orange PI Plus would be a gigabit interface opposed to 10/100.

**Comment by 0-kaladin** [comment]
if orange pi plus can run raspbian or debian jessie then it should work fine.

**Comment by redfast00** [comment]
Btw, PiVPN will also run on all SBC's running DietPi. That includes Orange Pi.
