### ISSUE TITLE
backup missing wireguard/setupVars.conf

### ISSUE THREAD

**Issue by nathanpride** [pivpn/pivpn#1555]
When migrating my `pivpn` settings to a new server the backup did(does) not contain all used settings.
- `pivpn -bk`
- fresh install of Rapberry PI OS lite (32 bit)
- installed `PiVPN` via `curl ... bash`
- restored files as described in https://docs.pivpn.io/wireguard/#migrating-pivpn-wireguard

Behaviour exhibited:
- able to connect,  `pivpn -c` shows an active client, 
- client does not connect to the internet

Checked with `pivpn -d`, no change

Discovered that the `pivpnNET` (in `wireguard/setupVars.conf`) was using a different subnet from the original machine.
updated `wireguard/setupVars.conf`, ran `pivpn -d` which updated "Iptables MASQUERADE rule", vpn now works _for existing clients_

If the backup had contained the `setupVars.conf` and the guide included a couple of extra step frustrations could have been avoided :)

**Comment by 4s3ti** [comment]
Pre-archive closing, more information [here](https://github.com/pivpn/pivpn/releases/tag/v4.6.0)
