### ISSUE TITLE
cannot install pivpn from script

### ISSUE THREAD

**Issue by tonywright** [pivpn/pivpn#1561]
I had a nicely working pivpn on my raspberry pi 4 server and running open vpn on my phone when I had a cert expired. I tried to create a new client ovpn  but this did not generate a new certificate. I read that the best way to get a new cert was to uninstall and re-install pivpn, however, now, regardless of which option I choose (openvpn/wireguard) when running the install script it just stops at "::: Using VPN: WireGuard" (or openvpn) and does nothing else. If I ctr-c out of it then pivpn is not installed. I have manually installed openvpn and wireguard  but wasn't prompted to install them before that. Has anything changed or are there unmentioned dependencies ? what should it be doing after this stage?
Thanks for any help getting this working again.
Tony

The full install feedback is :
```
:::
::: sudo will be used for the install.
::: Hostname length OK
::: Verifying free disk space...
:::
::: Package Cache update is needed, running apt-get update -y ...
 done!
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: Your system is up to date! Continuing with PiVPN installation...
:::    Checking for git... already installed!
:::    Checking for tar... already installed!
:::    Checking for curl... already installed!
:::    Checking for grep... already installed!
:::    Checking for dnsutils... already installed!
:::    Checking for grepcidr... already installed!
:::    Checking for whiptail... already installed!
:::    Checking for net-tools... already installed!
:::    Checking for bsdmainutils... already installed!
:::    Checking for bash-completion... already installed!
:::    Checking for dhcpcd5... already installed!
:::    Checking for iptables-persistent... already installed!
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libc-ares2 libmaxminddb0 libqt5multimedia5 libqt5multimedia5-plugins libqt5multimediagsttools5 libqt5multimediaquick5 libqt5multimediawidgets5 libsmi2ldbl libwireshark-data libwireshark11 libwiretap8
  libwscodecs2 libwsutil9 wireshark-common wireshark-qt
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
::: IPv6 test connections to google.com have failed. Disabling IPv6 support. (The curl test failed with code: 6)
grep: /etc/resolv.conf: No such file or directory
::: Static IP already configured.
::: Using User: tony
:::
::: Checking for existing base files...
:::    Checking /usr/local/src/pivpn is a repo... OK!
:::     Updating repo in /usr/local/src/pivpn from https://github.com/pivpn/pivpn.git ... done!
::: Using VPN: WireGuard

```

**Comment by orazioedoardo** [comment]
> grep: /etc/resolv.conf: No such file or directory

No `resolv.conf` file? What's the output of `ip -f inet address show`? Operating system?

**Comment by tonywright** [comment]
There is a resolv.conf as an "ls" shows it, however I have just realised it is a link to another file "/etc/resolvconf/run/resolv.conf" which doesn't seem to exist, I am running raspian buster. A search for resolv.conf returns:
/etc/resolv.conf
/lib/systemd/resolv.conf
/var/spool/postfix/etc/resolv.conf

/lib/systemd/resolv.conf has:
_nameserver 127.0.0.53
options edns0_

Not sure hat has gone wrong there, I m running pihole for dns which I thought pivpn should pick up.
I'm a bit wary of restoring resolv.conf in case it crashes pihole, everything else is working fine, any ideas?

**Comment by tonywright** [comment]
result of  ip -f inet address show is:
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    inet 10.75.75.101/8 brd 10.255.255.255 scope global noprefixroute eth0
       valid_lft forever preferred_lft forever

**Comment by orazioedoardo** [comment]
> Not sure hat has gone wrong there

If your DNS works on the Pi, probably you are just using systemd-resolved, you can check with `resolvectl status`. I believe the link shouldn't be broken but that issue is out of scope with PiVPN.

> I m running pihole for dns which I thought pivpn should pick up.

It will later in the installation. `/etc/resolv.conf` is inspected to prepare the static IP configuration.

> 2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
inet 10.75.75.101/8 brd 10.255.255.255 scope global noprefixroute eth0
valid_lft forever preferred_lft forever

That's https://github.com/pivpn/pivpn/issues/1518 as I suspected. PiVPN uses a /24 subnet in the 10.0.0.0/8 subnet for the VPN IP range, and the script gets stuck finding an empty range because there is none in your case. I'll try to implement a fix/workaround in the test branch.

**Comment by tonywright** [comment]
hmmm, I have told it not to change the ip as it is reserved in the router so no need to update the pi. 
Thanks for looking at this.
Is the "Unstable" test version stable enough to use? and will this be rolled out to the stable version later?
Thanks
Tony

**Comment by orazioedoardo** [comment]
> I have told it not to change the ip as it is reserved in the router so no need to update the pi.
It doesn't change the IP if you say you don't need it, but configuration is prepared before so the script can show what the final configuration would be.

> Is the "Unstable" test version stable enough to use?

Probably yes at this time, it's not a major change.

and will this be rolled out to the stable version later?

Yes but there is no date.

**Comment by pinesol93** [comment]
I had word for word the exact same issue as OP. The workaround mentioned in issue 1518 did the trick

**Comment by TheRoarkster** [comment]
This is a "me too" post, but also with some additional data points:

1.  Like some others, I had pivpn working on a prior install, but reinstalled.
2.  I tried both the main and test branches.
3.  I do not get the `/etc/resolv.conf` error (see below).
4.  The script fails for both wireguard and OpenVpn.

Here is the tail of the script where it fails:
```
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
::: IPv6 test connections to google.com have failed. Disabling IPv6 support. (The curl test failed with code: 7)
::: Using User: hxr
:::
::: Checking for existing base files...
:::    Checking /usr/local/src/pivpn is a repo... OK!
:::     Updating repo in /usr/local/src/pivpn from https://github.com/pivpn/pivpn.git ... [/]  done!
:::     Checkout branch 'test' from https://github.com/pivpn/pivpn.git in /usr/local/src/pivpn...
:::     'test' branch checkout done!
::: Using VPN: OpenVPN
```

I will try the workaround and report back.

**Comment by TheRoarkster** [comment]
UPDATE:   The workaround in #1518 to edit the install script (`pivpn/auto_install/install.sh`) by commenting out the entire routine starting with `generateRandomSubnet()` allows the script to run.

**Comment by heybrodes** [comment]
I experienced the same issue and when it hung i did a Ctrl+\ and the script continued. I did not modify the install scipt at all.

**Comment by patg84** [comment]
> I experienced the same issue and when it hung i did a Ctrl+\ and the script continued. I did not modify the install scipt at all.

That's all fine and dandy but the tun0 adapter never gets created.

**Comment by patg84** [comment]
> This is a "me too" post, but also with some additional data points:
> 
> 1. Like some others, I had pivpn working on a prior install, but reinstalled.
> 2. I tried both the main and test branches.
> 3. I do not get the `/etc/resolv.conf` error (see below).
> 4. The script fails for both wireguard and OpenVpn.
> 5. Like [1518](https://github.com/pivpn/pivpn/issues/1518), my IP range is in 10.0.0.x.
> 6. **HOWEVER,** prior iterations of the script worked with this range -- as I have been on 10.0.0.x since before the script (or RPi) existed.
> 
> Here is the tail of the script where it fails:
> 
> ```
> 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
> ::: IPv6 test connections to google.com have failed. Disabling IPv6 support. (The curl test failed with code: 7)
> ::: Using User: hxr
> :::
> ::: Checking for existing base files...
> :::    Checking /usr/local/src/pivpn is a repo... OK!
> :::     Updating repo in /usr/local/src/pivpn from https://github.com/pivpn/pivpn.git ... [/]  done!
> :::     Checkout branch 'test' from https://github.com/pivpn/pivpn.git in /usr/local/src/pivpn...
> :::     'test' branch checkout done!
> ::: Using VPN: OpenVPN
> ```
> 
> I will try the workaround and report back.

Please tell me you fixed this....

**Comment by orazioedoardo** [comment]
Issue #1518 should be fixed in the test branch.

**Comment by 4s3ti** [comment]
Pre-archive closing, more information [here](https://github.com/pivpn/pivpn/releases/tag/v4.6.0)

**Comment by FahimFBA** [comment]
> I experienced the same issue and when it hung i did a Ctrl+\ and the script continued. I did not modify the install scipt at all.

The same thing worked in my case.
