### ISSUE TITLE
pivpn connectiom using wireguard from iphone

### ISSUE THREAD

**Issue by bobster316** [pivpn/pivpn#1570]
I have followed the instructions to setup pivpn on a raspberry pi 4. the pi is connected via ethernet cable
directly to a spare port on the back of my virgin hub router.
When i initiate a connection form wireguard on my iphone I can see the VPN icone appear on the top right 
of the screen briefly then it goes off and back to the normal 4g.
plrase advise what commands and outputs you need to help identify the issue 
Thanks

**Comment by 4s3ti** [comment]
Thank you for your report, please read: https://github.com/pivpn/pivpn#general-guidelines and properly fill the issue template that is presented to you when you clicked the button to open a new issue, it can be found here: https://raw.githubusercontent.com/pivpn/pivpn/master/.github/ISSUE_TEMPLATE/pivpn-report.md
