### ISSUE TITLE
Possibility to force OS detection when installing: case Linux Mint

### ISSUE THREAD

**Issue by leapoli** [pivpn/pivpn#1571]
Hi everyone

I'd like to install on a Linux Mint (which is an Ubuntu), but the installer doesn't detect the underlying OS.
Will be great if there is an option to force the OS. Ex: --force-os Ubuntu (when using Linux Mint or another Ubuntu based distro).
Nowadays is not possible to install on a Linux Mint distro.

Thank you!

**Comment by 4s3ti** [comment]
thanks for your feedback however, Mint or any other consumer/desktop linux distros are not intended for this kind of usage, therefore no such feature is provided and there is no intention of supporting such.
