### ISSUE TITLE
Potentially only run on "released" code

### ISSUE THREAD

**Issue by 0-kaladin** [pivpn/pivpn#158]
Would be nice if the curl to install always used the latest release instead of the latest commit.  Development would be easier and allow for testing I think easier.  I tried to setup the testing branch but it isn't perfect.

To do this I think we'd need to first get the latest release:
curl -s https://api.github.com/repos/pivpn/pivpn/releases/latest
then get the hash of the install script to actually execute on that version.
once repo downloaded , checkout the tag so we are using that version of all the files.

High level thoughts here, just wanted to get it down before i forgot.

**Comment by redfast00** [comment]
We could work with multiple branches (a `develop` and a `stable` branch, and merge if necessary. The owner of pivpn.io (@0-kaladin?) could even make a subdomain like `dev.pivpn.io` that points to the `develop` branch. This way we can eliminate the code used for downloading the `test` branch if a certain env variable is set.

**Comment by 0-kaladin** [comment]
well what you described I have working even without the other domain (yes I have pivpn.io).  just pass TESTING=1, I have it on the wiki
https://github.com/pivpn/pivpn/wiki

and you'll see the TESTING var in the install script.  
The method above just allows us to ensure the curl is using a "release".  Just something to consider though we could always use the test branch and only merge to master on release.  
6 for one, half dozen the other..   Just food for thought.

**Comment by 0-kaladin** [comment]
btw @redfast00 go here https://github.com/orgs/pivpn/teams and see if you can request to join the team.

**Comment by redfast00** [comment]
@0-kaladin: sent a request to join the team.
I just read the wiki and noticed there is indeed a test domain. Maybe we should write a `CONTRIBUTING.MD` that tells potential devs which branch to push to.

**Comment by 0-kaladin** [comment]
Yea this whole work isn't worth it as testing from the test branch works fine.  
Created contributing.md as you suggested, that will suffice.
