### ISSUE TITLE
Traffic isn't identified as OpenVPN when using generated server config

### ISSUE THREAD

**Issue by tuur29** [pivpn/pivpn#160]
I'm having problems connecting to my home-based server from behind a enterprise firewall (fortinet). I went to my local helpdesk and we determined the problem to be the following: Their firewall only allows a set number of applications and traffic coming from my server back to the client wasn't identified as being OpenVPN traffic. Other server were identified fine and worked as expected. 

Apart from the port I haven't changed a single thing from the default generated openvpn server configuration.

**Comment by redfast00** [comment]
They probably detect OpenVPN traffic based on port. Have you tried using the IANA OpenVPN port (1194 IIRC)?

**Comment by tuur29** [comment]
I have and it didn't change a thing. Other OpenVPN server worked fine on that same custom port (that's where I got it from).

**Comment by redfast00** [comment]
Can you post the config for the other OpenVPN server that worked? Does it still work?

**Comment by tuur29** [comment]
Oh thanks for editing the title, didn't even noticed I forgot to copy the T.

Anyways, the working server isn't mine, so I don't have the file. He just told me he installed OpenVPN as described on the official site and made his config file based on the sample config there.

The exact error I'm getting on the client side is "TLS handshake failed", I've looked for some solutions and am going to try adding "mode server, tls-server" and "tls-client" to the respective files. I'll keep you updated if I find what's causing this. If you have any clue what might cause this, I'd be happy to receive help. I'm kind of a VPN beginner.

**Comment by 0-kaladin** [comment]
TLS handshake will fail if they are trying to inspect SSL traffic.  Are you sure they are not?

**Comment by tuur29** [comment]
No I'm not, is there a way to test this is the case? The guy from the helpdesk said he also has a OpenVPN server at his home and it works fine.

**Comment by 0-kaladin** [comment]
The fortinet guy would know.  I just don't know of anything this server would do to 'identify' itself.  The fortinet log would be the best clues to see what is going on.  or why it doesn't think the traffic is identified, whatever that really means.

**Comment by tuur29** [comment]
The guy from the local helpdesk made a support ticket with fortinet, I'll keep you updated when I receive some more information.

**Comment by 0-kaladin** [comment]
I'll close this soon if there is no further feedback, @tuur29

**Comment by tuur29** [comment]
I still haven't heard anything from the support ticket. I've 'fixed' my problem temporarily by disabling TLS (removing tls-version-min and tls-auth lines).

**Comment by 0-kaladin** [comment]
that tends to tell me they are in fact inspecting ssl traffic from this server if removing the tls auth allows it to work.  Regardless I'll close for now and if you ever get more info just post in here again.
