### ISSUE TITLE
 [ERROR]: Client Public Key Certificate not found: Kite79.crt

### ISSUE THREAD

**Issue by snow79** [pivpn/pivpn#1600]
Hi all, today i have try to install pivpn, i have see a guide online and all step are same but at the end when i make the user pivpn show me a error:

- [X] I have read the [documentation](https://docs.pivpn.io)
- [] Is it a feature request? please consider opening a [Discussion] (https://github.com/pivpn/pivpn/discussions/new)
- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.  
- [] The issue I am reporting *is* directly related to the pivpn installer script.
- [] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

### Has your install failed? 
```
no
```

### Describe the issue

**Expected behavior**

**Screenshots**

### Can you replicate the issue? Describe the steps below

pivpn -a
User name, password repeat password... error

### Have you searched for similar issues and solutions?
Yes i search and i have try 
 
**Additional context**

### Have you taken any steps towards solving your issue?
```
  which?
```

#### What type of hardware are you running PiVPN at?

```
Raspberrypi  cm4 2gb wifi 

Virtual machine
```
#### Output of `uname -a`
```
  OUTPUT HERE / ANSWER HERE
  DO NOT DELETE THE BACK-TICKS 
  PASTE THE OUTPUT INSIDE THE BACK-TICKS
```

#### Output of `cat /etc/os-release`
```
  OUTPUT HERE / ANSWER HERE
  DO NOT DELETE THE BACK-TICKS 
  PASTE THE OUTPUT INSIDE THE BACK-TICKS
```

### If install failed Please provide the console output of  `curl -L https://install.pivpn.io | bash`
```
  OUTPUT HERE / ANSWER HERE
  DO NOT DELETE THE BACK-TICKS 
  PASTE THE OUTPUT INSIDE THE BACK-TICKS
```

### Console output of      `curl -L install.pivpn.io | bash`
```
  OUTPUT HERE
  DO NOT DELETE THE BACK-TICKS 
  PASTE THE OUTPUT INSIDE THE BACK-TICKS
```

### Console output of      `pivpn add` or `pivpn add nopass`
```
```
pi@fluiddpi:~ $ pivpn -a
Enter a Name for the Client:  Kite79
How many days should the certificate last?  1080
Enter the password for the client:
Enter the password again to verify:
spawn ./easyrsa build-client-full Kite79
* Notice:
Using Easy-RSA configuration from: /etc/openvpn/easy-rsa/pki/vars

* Notice:
Using SSL: openssl OpenSSL 1.1.1n  15 Mar 2022

Generating an EC private key
writing new private key to '/etc/openvpn/easy-rsa/pki/32c62085/temp.60a0fe62'
Enter PEM pass phrase:
3070140480:error:28078065:UI routines:UI_set_result_ex:result too small:../crypto/ui/ui_lib.c:905:You must type in 4 to 1024 c
3070140480:error:2807106B:UI routines:UI_process:processing error:../crypto/ui/ui_lib.c:545:while reading strings
3070140480:error:0906406D:PEM routines:PEM_def_callback:problems getting password:../crypto/pem/pem_lib.c:59:
3070140480:error:0907E06F:PEM routines:do_pk8pkey:read key:../crypto/pem/pem_pk8.c:83:

Easy-RSA error:

Failed to generate request

Host: nix | Linux | /bin/bash

expect: spawn id exp4 not open
    while executing
"expect eof"
[2022-08-24T00:17:03+0100]: [ERROR]: Client Public Key Certificate not found: Kite79.crt
```
```

### Console output of      `pivpn debug`

```
  OUTPUT HERE
  DO NOT DELETE THE BACK-TICKS 
  PASTE THE OUTPUT INSIDE THE BACK-TICKS
```
i have check online, i see more post old date , i have try this:
` openssl genrsa -des3 -passout pass:x -out server.pass.key 2048`
i try this:
`openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 -out server.key`
but when i try to make the user the problem persist...
sudo apt update      #all update
sudo apt upgrade    #all upgrade

**Comment by bzeeman** [comment]
I am seeing the same issue here. It’s like it is not sending the typed in password to the PEM passphrase input.

**Comment by 4s3ti** [comment]
Hi, please feel the template that I believe to have been presented to you when you opened the issue. we need the data requested on it to investigate. 

here's the link for the raw content off the template: https://raw.githubusercontent.com/pivpn/pivpn/master/.github/ISSUE_TEMPLATE/pivpn-report.md

Edit your post and update it with the info requested there.

**Comment by 4s3ti** [comment]
Most likely a bug and related with #1601

**Comment by 4s3ti** [comment]
Please read:  

https://github.com/pivpn/pivpn/issues/1601#issuecomment-1226646362
