### ISSUE TITLE
Can't create a users pivpn add on SSL 3.0

### ISSUE THREAD

**Issue by victorgalvez96** [pivpn/pivpn#1603]
I was trying to install PIVPN on my Raspberry with the new Ubuntu 22.04 and i found a problem on the script with the new versions of Ubuntu 22.04 and SSL 3.0 (with more than one installations)

The new user creation script (pivpn -a) everytime i run it, it failed with this error:

```
Enter PEM pass phrase:
2070C585FFFF0000:error:14000065:UI routines:UI_set_result_ex:result too small:../crypto/ui/ui_lib.c:884:You must type in 4 to 1024 characters
2070C585FFFF0000:error:1400006B:UI routines:UI_process:processing error:../crypto/ui/ui_lib.c:544:while reading strings
2070C585FFFF0000:error:0480006D:PEM routines:PEM_def_callback:problems getting password:../crypto/pem/pem_lib.c:62:
2070C585FFFF0000:error:07880109:common libcrypto routines:do_ui_passphrase:interrupted or cancelled:../crypto/passphrase.c:184:
2070C585FFFF0000:error:1C80009F:Provider routines:p8info_to_encp8:unable to get passphrase:../providers/implementations/encode_decode/encode_key2any.c:116:
```

What i have done to solve this problem is replace on the sentence of the creation of the password for the PEM the variable $PASSWD for the variable $PASSSWD_UNESCAPED

```
expect "Enter PEM pass phrase" {sleep 0.1; send -- "${PASSWD_UNESCAPED}\r"}
expect "Verifying - Enter PEM pass phrase" {sleep 0.1; send -- "${PASSWD_UNESCAPED}\r"}

```

It seems like than at ssl 3.0 doesn't like the operations you do to escape the chars in PASSWD.

Cheers

**Comment by 4s3ti** [comment]
Hi, the issue has been fixed that variable has also been removed, as all the escaping. 

https://github.com/pivpn/pivpn/issues/1601#issuecomment-1226646362
