### ISSUE TITLE
Invalid URL on install batch - 

### ISSUE THREAD

**Issue by rlacava93** [pivpn/pivpn#1606]
Hi there! 

First of all, thanks a lot for this work! I already installed this on a couple of Pi and works great. 

Today I'm installing into a new one, and I get an error trying to reach "http://raspbian.raspberrypi.org/raspbian buster/main armhf libcurl3-gnutls armhf 7.64.0-4+deb10u2"

The exact error is "Failed to fetch http://raspbian.raspberrypi.org/raspbian/pool/main/c/curl/libcurl3-gnutls_7.64.0-4+deb10u2_armhf.deb  404  Not Found [IP: 93.93.128.193 80]"

The URL isn't correct anymore, I think they release a new version (modify date yesterday on that web) and they change the file name to "[libcurl3-gnutls_7.64.0-4+deb10u3_armhf.deb] (http://raspbian.raspberrypi.org/raspbian/pool/main/c/curl/libcurl3-gnutls_7.64.0-4+deb10u3_armhf.deb)"

Idk if is the same package you need on your project, but I hope this helps :) 

Regards! 

![Screen Shot 2022-08-30 at 18 13 02](https://user-images.githubusercontent.com/38698442/187544242-470349df-885e-4c6b-82b8-0188fd0f4fce.png)

**Comment by 4s3ti** [comment]
Please fill the issue template and provide more data, we need it to troubleshoot. Also we install CURL from the system repositories, First glance might be your system that is somewhat broken.

**Comment by 4s3ti** [comment]
Tested with both Ubuntu and debian, could not replicate, not having a raspbian/raspberrypi os at hand right not to double check.

**Comment by rlacava93** [comment]
Hi again @4s3ti , thanks for the quick response. 

Here is the output of the install command.

-------------------------------->
:~  $ curl https://raw.githubusercontent.com/pivpn/pivpn/master/auto_install/install.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  110k  100  110k    0     0   204k      0 --:--:-- --:--:-- --:--:--  205k
:::
::: sudo will be used for the install.
::: Hostname length OK
::: Verifying free disk space...
:::
::: Package Cache update is needed, running apt-get update -y ...
 done!
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: Your system is up to date! Continuing with PiVPN installation...
:::    Checking for git... not installed!
:::    Checking for tar... already installed!
:::    Checking for curl... already installed!
:::    Checking for grep... already installed!
:::    Checking for dnsutils... not installed!
:::    Checking for grepcidr... not installed!
:::    Checking for whiptail... already installed!
:::    Checking for net-tools... already installed!
:::    Checking for bsdmainutils... already installed!
:::    Checking for bash-completion... already installed!
:::    Checking for dhcpcd5... already installed!
:::    Checking for iptables-persistent... not installed!
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  git-man libcurl3-gnutls liberror-perl libirs161 netfilter-persistent
Suggested packages:
  rblcheck git-daemon-run | git-daemon-sysvinit git-doc git-el git-email git-gui gitk gitweb git-cvs git-mediawiki git-svn
The following NEW packages will be installed:
  dnsutils git git-man grepcidr iptables-persistent libcurl3-gnutls liberror-perl libirs161 netfilter-persistent
0 upgraded, 9 newly installed, 0 to remove and 0 not upgraded.
Need to get 292 kB/6770 kB of archives.
After this operation, 34.0 MB of additional disk space will be used.
Err:1 http://raspbian.raspberrypi.org/raspbian buster/main armhf libcurl3-gnutls armhf 7.64.0-4+deb10u2
  404  Not Found [IP: 93.93.128.193 80]
E: Failed to fetch http://raspbian.raspberrypi.org/raspbian/pool/main/c/curl/libcurl3-gnutls_7.64.0-4+deb10u2_armhf.deb  404  Not Found [IP: 93.93.128.193 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
:::    Failed to install git!
:::    Failed to install dnsutils!
:::    Failed to install grepcidr!
:::    Failed to install iptables-persistent!
[2022-08-30T22:09:12+0100]:
<--------------------------------

This is on a fresh install of a Raspberry Pi OS Litle (Legacy) 32 bits, on a Rpi 2B+. 
The only command executed after the OS install was "apt update" and "apt full-upgrade"


As sugested on the msj I execute "sudo apto-get update" successfully and try to install again the project, but the same error appears 


-------------------------------->
:~ $ curl https://raw.githubusercontent.com/pivpn/pivpn/master/auto_install/install.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  110k  100  110k    0     0   198k      0 --:--:-- --:--:-- --:--:--  198k
:::
::: sudo will be used for the install.
::: Hostname length OK
::: Verifying free disk space...
:::
::: Package Cache update is needed, running apt-get update -y ...
 done!
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: Your system is up to date! Continuing with PiVPN installation...
:::    Checking for git... not installed!
:::    Checking for tar... already installed!
:::    Checking for curl... already installed!
:::    Checking for grep... already installed!
:::    Checking for dnsutils... not installed!
:::    Checking for grepcidr... not installed!
:::    Checking for whiptail... already installed!
:::    Checking for net-tools... already installed!
:::    Checking for bsdmainutils... already installed!
:::    Checking for bash-completion... already installed!
:::    Checking for dhcpcd5... already installed!
:::    Checking for iptables-persistent... not installed!
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  git-man libcurl3-gnutls liberror-perl libirs161 netfilter-persistent
Suggested packages:
  rblcheck git-daemon-run | git-daemon-sysvinit git-doc git-el git-email git-gui gitk gitweb git-cvs git-mediawiki git-svn
The following NEW packages will be installed:
  dnsutils git git-man grepcidr iptables-persistent libcurl3-gnutls liberror-perl libirs161 netfilter-persistent
0 upgraded, 9 newly installed, 0 to remove and 0 not upgraded.
Need to get 292 kB/6770 kB of archives.
After this operation, 34.0 MB of additional disk space will be used.
Err:1 http://raspbian.raspberrypi.org/raspbian buster/main armhf libcurl3-gnutls armhf 7.64.0-4+deb10u2
  404  Not Found [IP: 93.93.128.193 80]
E: Failed to fetch http://raspbian.raspberrypi.org/raspbian/pool/main/c/curl/libcurl3-gnutls_7.64.0-4+deb10u2_armhf.deb  404  Not Found [IP: 93.93.128.193 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
:::    Failed to install git!
:::    Failed to install dnsutils!
:::    Failed to install grepcidr!
:::    Failed to install iptables-persistent!
[2022-08-30T23:45:31+0100]:
<--------------------------------


If I ping 93.93.128.193 or raspbian.raspberrypi.org the network connectivity is OK 

Let me know if I can get you more details or what should I do, maybe I have to use another OS version?

Thanks again

**Comment by 4s3ti** [comment]
this is what we need! it should have show up when you pressed the new issue: 

https://raw.githubusercontent.com/pivpn/pivpn/master/.github/ISSUE_TEMPLATE/pivpn-report.md

Please use triple back ticks (`) to flag the start and the end of code / output blocks. I have edited your post.

**Comment by rlacava93** [comment]
Hi @4s3ti ! 

Just to let you know that the issue is solved, I just try again a few minutes ago, and is working properly.

Thanks for your support! 
Regards
