### ISSUE TITLE
install script creates invalid ufw rules

### ISSUE THREAD

**Issue by kurromat** [pivpn/pivpn#1607]
## In raising this issue, I confirm the following:

`{please fill the checkboxes, e.g: [X]}`

- [x] I have read the [documentation](https://docs.pivpn.io)
- [] Is it a feature request? please consider opening a [Discussion] (https://github.com/pivpn/pivpn/discussions/new?category=feature-requests)
- [] Is this a support request? please consider copying the content of this document and using it to open a [Discussion](https://github.com/pivpn/pivpn/discussions/new?category=support)
- [x] I have read and understood the [PiVPN General Guidelines](https://github.com/pivpn/pivpn/#general-guidelines)
- [x] The issue I am reporting can be *replicated*.  
- [x] The issue I am reporting *is* directly related to the pivpn installer script.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

### Has your install failed? 
```
yes
```

### Describe the issue

The script tries to create ufw rules. For both IPv4 and IPv6, it creates a broken MASQUERADE rule, in the before(6).rule files.
After that, the script hangs trying to restart services.

**Expected behavior**
a valid MASQUERADE-rule in before.rule and before6.rule

**Screenshots**

### Can you replicate the issue? Describe the steps below
Initially I had the problem with the IPv6 MASQUERADE-rule on an Ubuntu upgraded to 22.04.
I tried it with a clean installation of 22.04, now the IPv4 MASQUERADE-Rule has a Problem, too.
I can replicate the issue by fixing the ufw rules, uninstalling and running the install script again.

### Have you searched for similar issues and solutions?
    yes, but did not find matching issues

**Additional context**
I have a pihole running on the same raspberry, and I installed the OpenVPN - variant.

relevant output of the script:

```
::: Detected UFW is enabled.
::: Adding UFW rules...
ERROR: Bad source address
ERROR: problem running ufw-init
Bad argument `COMMIT'
Error occurred at line: 14
Try `iptables-restore -h' or 'iptables-restore --help' for more information.
ip6tables-restore v1.8.7 (nf_tables): host/network `' not found
Error occurred at line: 13
Try `ip6tables-restore -h' or 'ip6tables-restore --help' for more information.

Problem running '/etc/ufw/before.rules'
Problem running '/etc/ufw/before6.rules'

::: UFW configuration completed.
::: Install Complete...
::: Restarting services...

```

the broken IPv6 rule:
```
*nat
:POSTROUTING ACCEPT [0:0]
-I POSTROUTING -s /64 -o eth0 -j MASQUERADE -m comment --comment openvpn-nat-rule
 COMMIT

```
The problem seems to be that the variable `pivpnNETv6` is never set for IPv6 OpenVPN.

the broken IPv4 rule:

```
*nat
:POSTROUTING ACCEPT [0:0]
-I POSTROUTING -s 10.1.233.0/24 -o eth0 -j MASQUERADE -m comment --comment openvpn-nat-rule
 COMMIT
```
I‘m not sure about the issue here, all I see is that after the script finished, there is no tun0 interface (which I assume would provide the 10.1… net)

### Have you taken any steps towards solving your issue?
```
Ran the script on a fresh Ubuntu 22.04 installation, tried to set pivpnNETv6 by hand
```

#### What type of hardware are you running PiVPN at?

```
Raspberrypi 4
```
#### Output of `uname -a`
```
Linux raspberry 5.15.0-1013-raspi #15-Ubuntu SMP PREEMPT Mon Aug 8 06:33:06 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux  
```

#### Output of `cat /etc/os-release`
```
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

### If install failed Please provide the console output of  `curl -L https://install.pivpn.io | bash`
```
::: Detected UFW is enabled.
::: Adding UFW rules...
ERROR: Bad source address
ERROR: problem running ufw-init
Bad argument `COMMIT'
Error occurred at line: 14
Try `iptables-restore -h' or 'iptables-restore --help' for more information.
ip6tables-restore v1.8.7 (nf_tables): host/network `' not found
Error occurred at line: 13
Try `ip6tables-restore -h' or 'ip6tables-restore --help' for more information.

Problem running '/etc/ufw/before.rules'
Problem running '/etc/ufw/before6.rules'

::: UFW configuration completed.
::: Install Complete...
::: Restarting services...
```

### Console output of      `curl -L install.pivpn.io | bash`
```
  OUTPUT HERE
  DO NOT DELETE THE BACK-TICKS 
  PASTE THE OUTPUT INSIDE THE BACK-TICKS
```

### Console output of      `pivpn add` or `pivpn add nopass`
```
  OUTPUT HERE
  DO NOT DELETE THE BACK-TICKS 
  PASTE THE OUTPUT INSIDE THE BACK-TICKS
```

### Console output of      `pivpn debug`

```
  OUTPUT HERE
  DO NOT DELETE THE BACK-TICKS 
  PASTE THE OUTPUT INSIDE THE BACK-TICKS
```

**Comment by harvp0wn** [comment]
Same issue Ubuntu 20.04 x64

**Comment by 4s3ti** [comment]
will investigate and see if i can find the culprit.

**Comment by 4s3ti** [comment]
Managed to replicate, issue should be somewhere here: https://github.com/pivpn/pivpn/blob/master/auto_install/install.sh#L3125-L3179 

will take a deeper look as soon as i have a bit.

**Comment by Starfoxfs** [comment]
This is the same i posted:
https://github.com/pivpn/pivpn/issues/1620

The Bug is that the install script (PiVPN) sets a Space before COMMIT under /etc/ufw/before.rules and /etc/ufw/before6.rules on line 14.

Remove this Space before COMMIT in both files and it works

But anyway the install script (PiVPN) has to be fixed.

**Comment by 4s3ti** [comment]
@Starfoxfs Your comment / Issue was indeed very helpful thanks a lot! I should push a fix to test branch soon.

**Comment by 4s3ti** [comment]
Pushed fix into test branch

**Comment by kurromat** [comment]
Thanks for the help. I finally managed to find the time to try again, and while the error in before.rules is gone, the error in before6.rules remains:

```::: Detected UFW is enabled.
::: Adding UFW rules...
ERROR: Bad source address
ERROR: problem running ufw-init
ip6tables-restore v1.8.7 (nf_tables): host/network `' not found
Error occurred at line: 13
Try `ip6tables-restore -h' or 'ip6tables-restore --help' for more information.

Problem running '/etc/ufw/before6.rules'
```
The affected rule:
```*nat
:POSTROUTING ACCEPT [0:0]
-I POSTROUTING -s /64 -o eth0 -j MASQUERADE -m comment --comment openvpn-nat-rule
COMMIT
```
with line 13 being `POSTROUTING -s /64...`

I still think an empty variable (`pivpnNETv6=""`) causes the issue, since the script seems to rely on it being there (in line 3161 of auto_install/install.sh)
```          sed_pattern="${sed_pattern} -s ${pivpnNETv6}\/${subnetClassv6}"```

Should I open a new issue?

**Comment by 4s3ti** [comment]
I will re-open this one since its related. will take a look when i have some time, however if someone wants to give it a go PR are always very welcomed.

**Comment by 4s3ti** [comment]
Managed to replicate, only happening with OpenVPN

```
::: Adding UFW rules...
ERROR: problem running ufw-init
ip6tables-restore v1.8.7 (nf_tables): host/network `' not found
Error occurred at line: 13
Try `ip6tables-restore -h' or 'ip6tables-restore --help' for more information.

Problem running '/etc/ufw/before6.rules'
```

Seems the `pivpnNETv6` Variable is never set as opposed to wireguard. 
Fixed on test branch: https://github.com/pivpn/pivpn/commit/ab1fe203992dc0ef586644efb12488b876ed9555
