### ISSUE TITLE
Importing .conf client files impossible (permission to access "configs" folder denied)

### ISSUE THREAD

**Issue by SweetWinterSmile2022** [pivpn/pivpn#1608]
Hopefully this is the right place to bring an issue to the attention.

Yesterday I have been installing Wireguard by using the PIVPN setup. I did this install on a new installed Raspbian version on my Raspberry Pi. The step by step installing went smooth, however once it was time to import, i. e. secure copy the .conf files to the respective clients there excisted a problem. The "configs" folder that does appear after that 1 (or more) clients are entered seems to be locked and does not allow access. Also with WINSCP this is being denied.

Hopefully the issue has been explained clear enough here. Looking forward to a solution as it was used to work smoothly in the past. It was possible to open the folder containing the .conf files and secure copy them to the desired client.

Wishing you all a great day. :-)

**Comment by SweetWinterSmile2022** [comment]
Thank you very much for explaining (in detail) how you solved this. :-) Hopefully soon there comes a solution for this so that it works "normal" again based on the documentation and how to install PIVPN. In previous installs I never came across this issue before.

**Comment by zcatk** [comment]
Rather than changing permissions, simply issue `sudo -i` and then access your config. Use `exit` to get out of your root session. FYI- sudo -i: Gives you a root prompt with a new shell environment (as if root did a login).

This is a better solution than messing with your permissions IMO

**Comment by skyfxl** [comment]
> Rather than changing permissions, simply issue `sudo -i` and then access your config. Use `exit` to get out of your root session. FYI- sudo -i: Gives you a root prompt with a new shell environment (as if root did a login).
> 
> This is a better solution than messing with your permissions IMO

Even after changing to root so you can copy the .conf file elsewhere, the .conf file still doesn't have the appropriate permissions set on it to allow you to retrieve it over SFTP so I still had to use the command @joshm89 shared to change the permissions on the .conf file :/...

**Comment by zcatk** [comment]
My apologies, I thought you were using SSH exclusively. If you `cat` the config, then you simply copy the contents into your client profile. Seems like you got it figured out, but good I do for anyone else. Cheers.

**Comment by 4s3ti** [comment]
Theres a lot info missing here.

The "create issue" button provided you with a template that asks for quite relevant information to understand what's going on. 

which user have you used to run PiVPN? root? raspberry? foo? 
What user have you selected to hold the configuration files? 

It feels that you have selected one  user to have the config files and you are accessing with another, which most likely is the cause for not having permissions. 

Also it could be a bug, but without the info on the template its hard to tell. 



## Please don't mess up with permissions, use the solution pointed out by @skyfxl or simply do `su -` and you will get a root shell.

**Comment by wcDogg** [comment]
I just ran into this issue as well. 

* Ubuntu 20.04 LTS on AWS Lightsail
* SSH user = ubuntu (not root)
* Install command = curl -L https://install.pivpn.io | bash
* During installer, selected ubuntu user to hold configs
* Added a clinet
* Creates /home/ubuntu/configs but assigns root:root permissions to folder and files

**Comment by zcatk** [comment]
Lord. Don’t add permissions, just cat the file using sudo -I yo copy paste your configuration.

**Comment by overbyrn** [comment]
I discovered this too when configuring an OCI instance for both OpenVPN and WireGuard.  I noticed the perms for ~/opvns was good, whereas ~/configs was not.  Whilst I agree, the simple workaround is to use sudo -i, nevertheless it's still a workaround.  A quick scan thru the scripts shows a small inconsistency in the way the profile dirs are created.  I think all that's needed is to harmonize the initial directory creation in makeCONF.sh as it is in makeOVPN.sh and be sure to chown user and group.

makeOVPN.sh
```bash
if [[ ! -d "${install_home}/ovpns" ]]; then
  mkdir "${install_home}/ovpns"
  chown "${install_user}:${install_user}" "${install_home}/ovpns"
  chmod 0750 "${install_home}/ovpns"
fi
```

```bash
dest_path="${install_home}/ovpns/${NAME}${FILEEXT}"
cp "/etc/openvpn/easy-rsa/pki/${NAME}${FILEEXT}" "${dest_path}"
chown "${install_user}:${install_user}" "${dest_path}"
chmod 640 "/etc/openvpn/easy-rsa/pki/${NAME}${FILEEXT}"
chmod 640 "${dest_path}"
unset dest_path
```

makeCONF.sh
```bash
if [[ ! -d "${install_home}/configs" ]]; then
  mkdir "${install_home}/configs"
  chown "${userGroup}" "${install_home}/configs"
  chmod 0750 "${install_home}/configs"
fi
```

```bash
cp "configs/${CLIENT_NAME}.conf" "${install_home}/configs/${CLIENT_NAME}.conf"
chown "${userGroup}" "${install_home}/configs/${CLIENT_NAME}.conf"
chmod 640 "${install_home}/configs/${CLIENT_NAME}.conf"
```

**Comment by 4s3ti** [comment]
There is a lot of missing info on this thread. 

@overbyrn  you are right those scripts need to be harmonized but it should be done the other way around, we want to keep code DRY not repeat code, and I highly doubt that is the reason why. 

Maybe you have missed [this](https://github.com/pivpn/pivpn/blob/master/scripts/wireguard/makeCONF.sh#L14)?? 

What is happening is exactly what you stated however is being shorthanded but the variable definition above. 

Also I do believe we should have seen this error much more often, and there should be more to it than just this. 
Something to which could have been clarified if more details would have been provided from the get-go. 

This being said commit https://github.com/pivpn/pivpn/commit/704d9f979586e1668af23654e2a4dc2223f2fec0 harmonizes the thing the right way. 

Closing.
