### ISSUE TITLE
Use EC algo once server supports OpenVPN 2.4

### ISSUE THREAD

**Issue by 0-kaladin** [pivpn/pivpn#161]
Everything is in place to easily support EC also except having openvpn 2.4 on the server side.
on Ubuntu/Debian this will be easier as we can pull from openvpn's repo but that repo doesn't build for the arm arch (raspberry pi).
See Issue #53  for history of this.

**Comment by fyellin** [comment]
This will be awesome.

**Comment by redfast00** [comment]
If there is no other solution, can we compile OpenVPN on the device. This will however have some drawbacks: performance (we have to compile OpenVPN on a Pi) and increased maintenance.

**Comment by 0-kaladin** [comment]
I probably would never resort to that.  Worst case scenario is to do what I did with easy-rsa3.  Fork it, compile releases ourselves and have those releases available here.  The script then leverages our pre-compiled releases to install.  But let's see once openvpn 2.4 is out maybe there will be a ppa etc or some other resource to get it from.

**Comment by fyellin** [comment]
I see that OpenVPN 2.4.0 2 was officially released a few days ago.  I'm hoping this means that the build issues have been fixed.

https://openvpn.net/index.php/open-source/downloads.html

**Comment by 0-kaladin** [comment]
Likely I'll try this in a month+.  No huge rush and wouldn't mind them getting a few bugfix releases out, seeing if any PPA's pop up with builds, and having the security audits underway to see what is found.

**Comment by arikalfus** [comment]
Ping! What's the project's current thoughts on openvpn 2.4?

**Comment by cfcolaco** [comment]
@arikalfus PiVPN already gives you the latest openvpn version but is actually supported only on Debian, there is no ARM version ( at least until mid-July ) ... so ... still, have to wait a bit longer for this, or to  @0-kaladin and @redfast00 to have a little more time to sort this out, hope I am not lying to you since I just got back and I am still in the middle of job and country changing! ;)

**Comment by jellemdekker** [comment]
Debian Stretch now uses OpenVPN 2.4.0 by default. [Source](https://packages.debian.org/stretch/openvpn)

**Comment by cfcolaco** [comment]
Test branch already supports raspbian stretch which is already using OpenVPN 2.4.

**Comment by d0nlab** [comment]
+1 possible to try now?

**Comment by arikalfus** [comment]
I can look at the integration in a couple of weeks unless someone wants to try it earlier. Too much going on right now to look at it earlier.

**Comment by arikalfus** [comment]
Looking back at this in full - I'd prefer raspbian stable be supported, not just raspbian stretch. What are all your thoughts

**Comment by cfcolaco** [comment]
@redfast00 The new merge also Fixes this one right?

**Comment by redfast00** [comment]
@cfcolaco I don't think this is implemented yet (I don't see anything related to generating an EC key in the 2.4 commit)

**Comment by cfcolaco** [comment]
Hmm this is not by far my area of expertise, probably i got it wrong but ...

> tls-crypt instead of tls-auth to encrypt (not only authenticate) the control channel
>elliptic curves for the key exchange (no need to generate/download dh parameters)
>compress lz4 instead of compl-lzo for less cpu intensive compression

From @orazioedoardo pr #471  .... can i get a better picture of this then?

**Comment by redfast00** [comment]
Whoops, overlooked that. It looks like it's implemented, so I'll close this.

**Comment by arikalfus** [comment]
Is this fully implemented? In re-installing PiVPN it still generated RSA/DH keys, which shouldn't be necessary if we're using ECDH/ECDSA

**Comment by orazioedoardo** [comment]
If you choose to enable openvpn 2.4 features [the script](https://github.com/pivpn/pivpn/blob/master/auto_install/install.sh#L905) will disable DH, which makes openvpn use ECDH with the default curve (secp384r1). Certificates are still RSA because mobile clients do not support ECDSA yet.

**Comment by cfcolaco** [comment]
Thanks a lot @orazioedoardo God job! =D

**Comment by arikalfus** [comment]
Got it, thanks for that clarification
