### ISSUE TITLE
OpenVPN: makeOVPN.sh causes client ccd file error

### ISSUE THREAD

**Issue by 4s3ti** [pivpn/pivpn#1616]
### Discussed in https://github.com/pivpn/pivpn/discussions/1613

<div type='discussions-op-text'>

<sup>Originally posted by **liasom** September  4, 2022</sup>
New installations (today and yesterday) of OpenVPN on two separate Raspberry Pi computers. One is Pi Zero 1.3 with 32-bit Raspberry Pi OS lite and the other is Pi Zero 2 W with Pi OS 64-bit. This error happens on both. When I create a client ovpn profile the corresponding ccd file contains an error in having no space between the ip address and subnet. This content pasted in from one of the ccd files.

ifconfig-push 10.0.8.2255.255.255.0
</div>

Faulty line: https://github.com/pivpn/pivpn/blob/master/scripts/openvpn/makeOVPN.sh#L478 

Missing space after `${i}`

**Comment by joakjo** [comment]
Thanks :pray:
