### ISSUE TITLE
Home network access, no internet access

### ISSUE THREAD

**Issue by jicho** [pivpn/pivpn#162]
Hi,

I've installed PiVPN. Installation worked super simple, thanks! Creating .opvn files is even easier, but... After installing the connection on my iPhone I can connect to my home network and access the machines, but I can't access websites.

This probably has something to do with routing, but where do I need to look into?

Must say that I'm feeling a little stupid that I can't find the problem :( Hope you can help...?

Oh... I installed PiVPN / OpenVPN on a RasPi with the latest version of Jessie.

**Comment by 0-kaladin** [comment]
Can you paste the output of your install?  
or since you just installed can you run the pivpn uninstall, then install again and capture that if the problem persists?

**Comment by jicho** [comment]
In /etc/pivpn I've found the following:

> pi@piweb:/etc/pivpn $ tail *
> ==> DET_PLATFORM <==
> Raspbian
> 
> ==> INSTALL_PORT <==
> 1194
> 
> ==> INSTALL_PROTO <==
> udp
> 
> ==> INSTALL_USER <==
> pi
> 
> ==> NO_UFW <==
> 1
> 
> ==> REVOKE_STATUS <==
> 0
> pi@piweb:/etc/pivpn $

**Comment by 0-kaladin** [comment]
was hoping to get the text that output to your screen when you installed.  I'd like to see if it complained about anything during install.

**Comment by jicho** [comment]
Oh, sorry... There where no errors on screen during the installation :)

I will reinstall PiVPN this weekend and report an update.

**Comment by 0-kaladin** [comment]
ok, even if you don't see errors, when you reinstall please paste all that output here.

**Comment by jicho** [comment]
I removed my old installation. After a reboot I started a new installation end ended up with a lot of "not found" messages. As a result I did a manual apt-get update, upgrade and dist-upgrade. Started the installation process again and the script actually works again without the errors. 

After generating the .opvn files everything worked :) The thing was that I only added my router IP as a DNS server for the static IP in the dhcpcd.config, adding 8.8.8.8 to the list solved the problem with the internet access on my RasPi. After that I've setup OpenDNS instead my local IP only and, guess what, everything worked :)

Here are the errors that I go during the installation after the uninstall:
> pi@piweb:~ $ sudo curl -L https://install.pivpn.io | bash
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   178  100   178    0     0     28      0  0:00:06  0:00:06 --:--:--    48
> 100 40156  100 40156    0     0   3391      0  0:00:11  0:00:11 --:--:--  9657
> :::
> ::: sudo will be used for the install.
> :::
> ::: Checking apt-get for upgraded packages.... done!
> :::
> ::: Your pi is up to date! Continuing with PiVPN installation...
> :::
> ::: Checking dependencies:
> :::    Checking for openvpn... Not found! Installing.... [/]  E: There are problems and -y was used without --force-yes
>  done!
> :::    Checking for git... Not found! Installing.... [/]  E: There are problems and -y was used without --force-yes
>  done!
> :::    Checking for dhcpcd5... already installed!
> :::    Checking for tar... already installed!
> :::    Checking for wget... already installed!
> :::    Checking for grep... already installed!
> :::    Checking for iptables-persistent... Not found! Installing.... [/]  E: There are problems and -y was used without --force-yes
>  done!
> :::    Checking for dnsutils... Not found! Installing.... [/]  E: There are problems and -y was used without --force-yes
>  done!
> :::    Checking for expect... Not found! Installing.... [/]  E: There are problems and -y was used without --force-yes
>  done!
> :::    Checking for whiptail... already installed!
> ::: Verifying free disk space...
> ::: Using interface: eth0
> bash: line 266: nslookup: command not found
> ::: Static IP already configured.
> ::: Using User: pi
>  [/]  E: There are problems and -y was used without --force-yes
> ::: 
> ::: Stopping OpenVPN service...Failed to stop openvpn.service: Unit openvpn.service not loaded.
>  done.
> sed: can't read /etc/apt/apt.conf.d/50unattended-upgrades: No such file or directory
> :::
> ::: Checking for existing base files...
> :::    Checking /etc/.pivpn is a repo...:::    Cloning https://github.com/pivpn/pivpn.git into /etc/.pivpn...sudo: git: command not found
>  done!
> :::
> ::: Installing scripts to /opt/pivpn...cp: cannot stat ‘/etc/.pivpn/scripts/makeOVPN.sh’: No such file or directory
> cp: cannot stat ‘/etc/.pivpn/scripts/clientStat.sh’: No such file or directory
> cp: cannot stat ‘/etc/.pivpn/scripts/listOVPN.sh’: No such file or directory
> cp: cannot stat ‘/etc/.pivpn/scripts/removeOVPN.sh’: No such file or directory
> cp: cannot stat ‘/etc/.pivpn/scripts/uninstall.sh’: No such file or directory
> cp: cannot stat ‘/etc/.pivpn/scripts/pivpnDebug.sh’: No such file or directory
> chmod: cannot access ‘/opt/pivpn/makeOVPN.sh’: No such file or directory
> chmod: cannot access ‘/opt/pivpn/clientStat.sh’: No such file or directory
> chmod: cannot access ‘/opt/pivpn/listOVPN.sh’: No such file or directory
> chmod: cannot access ‘/opt/pivpn/removeOVPN.sh’: No such file or directory
> chmod: cannot access ‘/opt/pivpn/uninstall.sh’: No such file or directory
> chmod: cannot access ‘/opt/pivpn/pivpnDebug.sh’: No such file or directory
> cp: cannot stat ‘/etc/.pivpn/pivpn’: No such file or directory
> chmod: cannot access ‘/usr/local/bin/pivpn’: No such file or directory
> cp: cannot stat ‘/etc/.pivpn/scripts/bash-completion’: No such file or directory
> bash: line 391: /etc/bash_completion.d/pivpn: No such file or directory
>  done.
> ::: Using protocol: udp
> tar: /etc/openvpn: Cannot open: No such file or directory
> tar: Error is not recoverable: exiting now
> chown: cannot access ‘/etc/openvpn/easy-rsa’: No such file or directory
> mkdir: cannot create directory ‘/etc/openvpn/easy-rsa/pki’: No such file or directory
> tee: /etc/openvpn/easy-rsa/vars: No such file or directory
> bash: line 732: cd: /etc/openvpn/easy-rsa: No such file or directory

At the end my connection issue was the DNS setting :S

**Comment by 0-kaladin** [comment]
So you messed up the DNS setting?  Or the script automatically put in the wrong one?
BTW i'm adding to the script to try to get the apt errors so it doesn't just blindly continue after that when everything will fail.

**Comment by jicho** [comment]
Yes, it was my mistake... wrong assumption when entering the DNS settings. The script did nothing wrong.

**Comment by jicho** [comment]
BTW thanks for the quick support!
