### ISSUE TITLE
PiVPN Install Script Bug with UFW Firewall add a Space before COMMIT

### ISSUE THREAD

**Issue by Starfoxfs** [pivpn/pivpn#1620]
## In raising this issue, I confirm the following:

`{please fill the checkboxes, e.g: [X]}`

- [x] I have read the [documentation](https://docs.pivpn.io)
- [x] Is it a feature request? please consider opening a [Discussion] (https://github.com/pivpn/pivpn/discussions/new?category=feature-requests)
- [x] Is this a support request? please consider copying the content of this document and using it to open a [Discussion](https://github.com/pivpn/pivpn/discussions/new?category=support)
- [x] I have read and understood the [PiVPN General Guidelines](https://github.com/pivpn/pivpn/#general-guidelines)
- [x] The issue I am reporting can be *replicated*.  
- [x] The issue I am reporting *is* directly related to the pivpn installer script.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

### Has your install failed? 
```
no
```

### Describe the issue

I installed new PiVPN 4.1.2 to a Raspberry Pi with latest stable UFW Firewall
If UFW is activated PiVPN install Script writes before.rules and beforev6.rules of UFW Firewall new, to add wireguard settings

Here is the BUG, PiVPN install Script adds a Space before COMMIT on line 14 of before.rules and beforev6.rules

That causes a start failure of UFW Firewall.

**Expected behavior**

**Screenshots**

### Can you replicate the issue? Describe the steps below

1. Install PiVPN 4.1.2 with enabled UFW Firewall
2. Reboot System
3. UFW Firewall is inactive 
4. If you try to enable UFW its a Error with Iptables and UFW-INIT
5. Just delete the Space before COMMIT on line 14 of before.rules and beforev6.rules (Solution)

### Have you searched for similar issues and solutions?
    (no )

**Additional context**

### Have you taken any steps towards solving your issue?
```
 Just delete the Space before COMMIT on line 14 of before.rules and beforev6.rules (Solution)
```

#### What type of hardware are you running PiVPN at?

```
Raspberrypi (4B)
Ordroid
OrangePi
bananaPi
Virtual machine
```
#### Output of `uname -a`
```
  OUTPUT HERE / ANSWER HERE
  DO NOT DELETE THE BACK-TICKS 
  PASTE THE OUTPUT INSIDE THE BACK-TICKS
```

#### Output of `cat /etc/os-release`
```
  OUTPUT HERE / ANSWER HERE
  DO NOT DELETE THE BACK-TICKS 
  PASTE THE OUTPUT INSIDE THE BACK-TICKS
```

### If install failed Please provide the console output of  `curl -L https://install.pivpn.io | bash`
```
  OUTPUT HERE / ANSWER HERE
  DO NOT DELETE THE BACK-TICKS 
  PASTE THE OUTPUT INSIDE THE BACK-TICKS
```

### Console output of      `curl -L install.pivpn.io | bash`
```
  OUTPUT HERE
  DO NOT DELETE THE BACK-TICKS 
  PASTE THE OUTPUT INSIDE THE BACK-TICKS
```

### Console output of      `pivpn add` or `pivpn add nopass`
```
  OUTPUT HERE
  DO NOT DELETE THE BACK-TICKS 
  PASTE THE OUTPUT INSIDE THE BACK-TICKS
```

### Console output of      `pivpn debug`

```
  OUTPUT HERE
  DO NOT DELETE THE BACK-TICKS 
  PASTE THE OUTPUT INSIDE THE BACK-TICKS
```

**Comment by robinsonjohn** [comment]
I can confirm the same as above on Ubuntu 20.04.

**Comment by 4s3ti** [comment]
Pushed fix into test branch
