### ISSUE TITLE
Docker for PiVPN

### ISSUE THREAD

**Issue by t0msk** [pivpn/pivpn#1622]
Hello, I have RPi4 with Portainer and I would like to ask you if you have some docker container of PiVPN, I just found this: https://hub.docker.com/r/pivpn/pivpn.io but there are no instructions and I want to use Wireguard.

Using that docker container I get error: `exec /docker-entrypoint.sh: exec format error`

My idea is that I don't want to have running services on my RPi host, I want to have everything in container, so I would like to have PiVPN too.

**Comment by 4s3ti** [comment]
That Is the Docker image of https://pivpn.io website, not PIVPN Image. 

At the moment we do not provide any docker containers, here are some experimental things you can do to play around and try to build your own: https://docs.pivpn.io/install/#docker-experimental
