### ISSUE TITLE
Implement good Install log

### ISSUE THREAD

**Issue by 0-kaladin** [pivpn/pivpn#163]
Tried doing a simple install log by just sending the entire install pivpn function to tee and log per this commit 
Option 1: https://github.com/pivpn/pivpn/commit/1cada67979d09fba68a5d946c5476e57349fe2a4

I didn't love it as its filled with garbage ascii chars from the whiptails etc.

Would like to explore other options.
Thoughts?  Ideas?  

Here is Option 2:
put this at the top of the script:
```
exec 3>&1 4>&2
trap 'exec 2>&4 1>&3' 0 1 2 3
exec 1>log.out 2>&1
```

that will send all output to the log.out file.
Which also isn't ideal but now for all things I want to also send to console I'd do:
```
# Build the certificate authority
    printf "::: Building CA...\n" | tee /dev/fd/3
    ${SUDOE} ./easyrsa --batch build-ca nopass | tee /dev/fd/3
    printf "\n::: CA Complete.\n" | tee /dev/fd/3
```

this would get it to the log file but i'm using tee to also send to the console now.
since I don't want the whiptail's in the log I can just redirect them solely to the console with:
`whiptail --msgbox --backtitle "Setup OpenVPN" --title "Server Information" "The server key, Diffie-Hellman key, and HMAC key will now be generated." ${r} ${c} >&3`

This is basically what I want, the downside is would have to go through entire script, line by line to add the tee or redirect as needed.  Seems tedious.

Am I missing another solution here?  Should I just do the first and maybe at the end try to sanitize out the ascii garbage? (could be option 3).

**Comment by 4s3ti** [comment]
I guess this can be closed, 
PiVPN is doing a good job logging its actions and working well with pivpn debug.
