### ISSUE TITLE
DNS_PROBE_STARTED or DNS_PROBE_FINISHED_NO_INTERNET when connected to PiVPN WireGuard

### ISSUE THREAD

**Issue by githubissocool** [pivpn/pivpn#1635]
So I setup pivpn today and enabled upnp on my router and added port forwarding rules, however when I am connected and try browsing the web, i get ERR_NAME_NOT RESOLVED, it can't find any domain(s) ip address, I checked if the port is open both on server and the port forwarding port and they are active. I checked by visiting the ports and if it says connection refused it means that the connection is active waiting for a client to connect.

What is wrong? Is it because I am connecting to the VPN on the same network the VPN was setup on? I don't have mobile data to  test with it.

I also tried connecting to the VPN with the local ip and get the same error, I have tried reloading ufw, didn't work. I checked logs they seem fine. My server is listening. 

What the frick is happening?!

Edit: I apparently was able to connect without err name not resolved by turning off private dns but now i get a new error when browsing: DNS_PROBE_STARTED or DNS_PROBE_FINISHED_NO_INTERNET.
I get the same error when connecting to the local ip.

Back to nothing loading...

**Comment by 4s3ti** [comment]
https://github.com/pivpn/pivpn#feedback--support
