### ISSUE TITLE
interactive adding client allows cert name with space (unremovable in wg)

### ISSUE THREAD

**Issue by 07pepa** [pivpn/pivpn#1639]
## In raising this issue, I confirm the following:
- [x] I have read the [documentation](https://docs.pivpn.io)
- [x] I have read and understood the [PiVPN General Guidelines](https://github.com/pivpn/pivpn/#general-guidelines)
- [x] The issue I am reporting can be *replicated*.  
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

### Has your install failed? 
```
no
```

### Describe the issue
it is possible to create  clinet with spaces in its name like this

this likely breaks storage format (everything is shifted by one space (column)) since when you list your clients it shows key as

`test` for `spacetest  test` (and if that is right it it makes wireguard wulnerable since key can be something simple as **`test`**)
**hence critical security  bug**  even it is public key, it is not random and weekens the ciphre considerably (and yes i did not read code but this is serious enought to just report

if you try to remove it with 
pivpn wg -r 'spacetest test' it does not remove it

please provide instruction for fixing the storage format and fix the posibility of adding this

**Expected behavior**
spaces are not allowed and clients are reported corectly

### Can you replicate the issue? Describe the steps below

`pivpn ovpn -a` or `pivpn wg -a` 

and  in interactive mode you type something like 'spacetest test'

### Have you searched for similar issues and solutions?
  yes and nothing found 

### Have you taken any steps towards solving your issue?
```
brief skimm over code
reporting issue
```

#### What type of hardware are you running PiVPN at?

```
Raspberrypi  4 4Gig
```
#### Output of `uname -a`
```
 Linux AC-pi 5.15.61-v8+ #1579 SMP PREEMPT Fri Aug 26 11:16:44 BST 2022 aarch64 GNU/Linux
```

#### Output of `cat /etc/os-release`
```
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

### Console output of      `pivpn debug`
``` pivpn wg debug
::: Generating Debug Output
::::            PiVPN debug              ::::
=============================================
::::            Latest commit            ::::
Branch: master
Commit: 202c173dd783036a09fa6de6e3a2409d4ea565d9
Author: 4s3ti
Date: Sun Sep 4 16:41:57 2022 +0200
Summary: fix(openvpn): makeOVPN Missing space
=============================================
::::        Installation settings        ::::
PLAT=Debian
OSCN=bullseye
USING_UFW=0
pivpnforceipv6route=1
IPv4dev=eth0
dhcpReserv=1
IPv4addr=<REDACTED>
IPv4gw=<REDACTED>
install_user=pi
install_home=/home/pi
VPN=wireguard
pivpnPORT=<REDACTED>
pivpnDNS1=<REDACTED>
pivpnDNS2=
pivpnHOST=REDACTED
INPUT_CHAIN_EDITED=0
FORWARD_CHAIN_EDITED=0
INPUT_CHAIN_EDITEDv6=
FORWARD_CHAIN_EDITEDv6=
pivpnPROTO=udp
pivpnMTU=1420
pivpnDEV=wg0
pivpnNET=<REDACTED>
subnetClass=24
pivpnenableipv6=0
ALLOWED_IPS=<REDACTED>
UNATTUPG=1
INSTALLED_PACKAGES=()
=============================================
::::  Server configuration shown below   ::::
[Interface]
PrivateKey = server_priv
Address = <REDACTED>
MTU = 1420
ListenPort = 51820

<recacted clients but no spacetest test after delete>
=============================================
::::  Client configuration shown below   ::::
<recacted clients but no spacetest test>
=============================================
::::    Recursive list of files in       ::::
::::    /etc/wireguard shown below       ::::
/etc/wireguard:
configs
keys
wg0.conf

/etc/wireguard/configs:
clients.txt
<recacted clients but no spacetest test after delete>
/etc/wireguard/keys:
<recacted clients but no spacetest test after delete>
=============================================
::::            Self check               ::::
:: [OK] IP forwarding is enabled
:: [OK] Iptables MASQUERADE rule set
:: [OK] WireGuard is running
:: [OK] WireGuard is enabled
(it will automatically start on reboot)
:: [OK] WireGuard is listening on port 51820/udp
=============================================
:::: Having trouble connecting? Take a look at the FAQ:
:::: https://docs.pivpn.io/faq
=============================================
:::: WARNING: This script should have automatically masked sensitive       ::::
:::: information, however, still make sure that PrivateKey, PublicKey      ::::
:::: and PresharedKey are masked before reporting an issue. An example key ::::
:::: that you should NOT see in this log looks like this:                  ::::
:::: YIAoJVsdIeyvXfGGDDadHh6AxsMRymZTnnzZoAb9cxRe                          ::::
=============================================
::::            Debug complete           ::::
:::
::: Debug output completed above.
::: Copy saved to /tmp/debug.log
:::
```

**Comment by 4s3ti** [comment]
Hi, thanks for your report, really appreciate it! This is indeed a bug, however this is not a security issue at all.

Even though you are right that values are shifted, this only affects the The `pivpn -l` and **not the key itself** 

here is the `pipvn -l` for wireguard for example: https://github.com/pivpn/pivpn/blob/master/scripts/wireguard/listCONF.sh#L21-L24

`pivpn -l`  lists based on columns separated by spaces "value1 value2 value3 value4" 

By adding a space to the name, when you list the clients it will show you the wrong value as "key" however that value **is not** the key!

Also Keys are not at all generated based on any inputs provided by the users, and public keys are exactly that, public keys! 

Haven't tested or tried to replicate this, but quick look at the code, and Issue is most likely 

here for wireguard: https://github.com/pivpn/pivpn/blob/master/scripts/wireguard/makeCONF.sh#L78-L95 
here for openvpn: https://github.com/pivpn/pivpn/blob/master/scripts/openvpn/makeOVPN.sh#L273-L288

Adding another condition to check for empty spaces and exit could probably fix this. 


Will see if i have time to push a fix to the test branch today.

**Comment by 4s3ti** [comment]
Edited the title of the Issue to avoid unnecessary alarm.

**Comment by 07pepa** [comment]
i was suspitios that it was just not displayed correctly but i am not shellscript programer (java/python) and i  rather put that it is security issue since i could not ruled it out

thanks

**Comment by 4s3ti** [comment]
In the meantime, to remove clients with a space in the name, escape the space whto a `\`. Example for wireguard:

`pivpn -r foo\ bar`

Then remove it from `/etc/wireguard/configs/clients.txt`

**Comment by 4s3ti** [comment]
Fix pushed to test branch.

**Comment by 4s3ti** [comment]
fixed: https://github.com/pivpn/pivpn/releases/tag/v4.1.4
