### ISSUE TITLE
How to connect to pivpn from computer?

### ISSUE THREAD

**Issue by MichaelGofron** [pivpn/pivpn#1641]
I'm trying to connect to pivpn from my computer but I'm not sure how to get all the info needed. 
I tried through the vpn section and then set the remote address and the remote id which I got through a curl command (`curl -s https://checkip.amazonaws.com%60/))  which showed what my external public facing ip was.
I then authenticated with the username of my raspberry pi and the password for it.
I was unable to connect to the vpn though. I'm wondering are the remote address and remote id the same? How can I get them if they're different. Also are the username and password just for the raspberry pi system or is this a separate one for the pivpn and how can I get them if they are separate from my system?

**Comment by orazioedoardo** [comment]
To connect to the VPN, connect to the Raspberry Pi via SSH/SFTP and download the configuration stored in `/home/youruser/ovpns`or `/home/youruser/configs` download the OpenVPN or WireGuard app on the computer, and open the configuration with that app.
