### ISSUE TITLE
Generate OVPN in 2.3.11 format

### ISSUE THREAD

**Issue by EZarnosky** [pivpn/pivpn#1646]
I am unable to add the OVPN file/connection to my Synology RT2600ac running SRM 1.3.x. Synology appears to have updated the OpenVPN client on their DSM 7.x NAS systems, but not on their routers. Is there an option I can use, or script line(s) I can change that will generate a OVPN file in 2.3.11 format? I have spent weeks going round and round with Synology support and been unsuccessful to get a useful response from them.

**Comment by TinCanTech** [comment]
@EZarnosky Technically, OpenVPN 2.3 is unsupported and 5 years out of date.
https://community.openvpn.net/openvpn/wiki/SupportedVersions

What error message does v2.3.11 throw for you ?

**Comment by EZarnosky** [comment]
I figured it out. I guess it is a bug in the Synology SRM. When I attempted to add a new OpenVPN connection I would get the following error:

`Unable to perform this operation, possibly because the network connection is unstable or the system is busy. Please sign into SRM again.`

I noticed that it still created the connection. I thine tried to make the connection, but I got:

`Oct 30 19:04:32 synovpnc: connection.c:284 Fail to get interface info.
Oct 30 19:04:32  synovpnc: connection.c:284 Fail to get interface info.
Oct 30 19:04:33 openvpn[21030]: NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Oct 30 19:04:33 openvpn[21030]: neither stdin nor stderr are a tty device and you have neither a controlling tty nor systemd - can't ask for 'Enter Private Key Password:'.  If you used --daemon, you need to use --askpass to make passphrase-protected keys work, and you can not use --auth-nocache.`

I researched this a little and found that Synology set the OpenVPN client a little strangely. I revoked the user I created and created them again with the `nopass` option. After that I was able to make a connection.
