### ISSUE TITLE
Short description of Your Issue here

### ISSUE THREAD

**Issue by EZarnosky** [pivpn/pivpn#1647]
I seemed to have missed it, but does PiVPN provide access to the PiHOLE web interface? I can't seem to connect at all. Also what might the admin password be?

http://<IP>/admin
https://<IP>/admin

**Comment by orazioedoardo** [comment]
> I seemed to have missed it, but does PiVPN provide access to the PiHOLE web interface?

Yes, type the LAN IP of the Pi-hole.

> Also what might the admin password be?

You know that.
