### ISSUE TITLE
Packages uninstaller prompt indicates Yes as the default answer

### ISSUE THREAD

**Issue by TinCanTech** [pivpn/pivpn#1653]
Hi,

sorry for not using the template, this "bug" is very simple.

I ran `pivpn -u` to uninstall and noticed that, for each package to uninstall the script prompts with a question followed by `[Y/n]`. This suggests that `Y` is the default.

I would have expected to see `[y/n]`, to indicate that there is no default answer.

My copy of `pivpn` is a few months out of date, so this could have already been addressed.  Thank you.

**Comment by 4s3ti** [comment]
I think that is the intended behavior ... when you ask to uninstall .. it will uninstall everything it installed by default and then you choose if you want to keep anything specific .. no? 

Or when you accept the default it does nothing?

**Comment by TinCanTech** [comment]
> Or when you accept the default it does nothing?

The script does not have any default, which is why the `[Y/n]` prompt caught my attention.

Example:
```
::: Do you wish to remove qrencode from your system? [Y/n]: 
::: You must answer yes or no!
::: Do you wish to remove qrencode from your system? [Y/n]: y
:::	Removing qrencode...done! 
```

**Comment by 4s3ti** [comment]
alright then ... will try to change that as soon as i have a bit .. till there tagging the issue :)

**Comment by 4s3ti** [comment]
Should be fixed and on master branch now :)
