### ISSUE TITLE
Clarification when on same pi as pihole

### ISSUE THREAD

**Issue by molly78** [pivpn/pivpn#166]
I can't quite sort this - in dnsmasq.conf I added:
listen-address=127.0.0.1, 192.168.1.9

that's the static address of my pi running pihole & piVPN

I set it up to use my domain - xxx.yyy.com - rather than an IP

I tried listen-address=127.0.0.1, 192.168.1.9, 10.8.0.1 as per the FAQ, but that didn't work.

I'm not sure what that listen line should be for my instance, as I can connect to it, but then the traffic goes nowhere as it's stuck trying to dns thru pihole.

Thanks,

**Comment by 0-kaladin** [comment]
did you restart dnsmasq after changing listen line?  your last looks correct:
listen-address=127.0.0.1, 192.168.1.9, 10.8.0.1

**Comment by molly78** [comment]
Yes, I actually rebooted my pi after changes

copy/paste from dnsmasq is
listen-address=127.0.0.1, 192.168.1.9, 10.8.0.1

where does the 10.8.0.1 come from BTW? Is that the IP range OpenVPN uses to forward on?

**Comment by 0-kaladin** [comment]
the 10.8.0.1 should be the IP of the tun0 interface which is where your vpn client is coming from.
if you run ifconfig you should see your interfaces and their IPs.  you can also try using the interfaces for the listen-address as in:
`listen-address=lo, eth0, tun0`

**Comment by 0-kaladin** [comment]
also verify the output of this command looks something like this:
`iptables -t nat -L -n -v`
```
Chain PREROUTING (policy ACCEPT 194K packets, 16M bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain INPUT (policy ACCEPT 148K packets, 13M bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain OUTPUT (policy ACCEPT 101K packets, 6797K bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain POSTROUTING (policy ACCEPT 101K packets, 6797K bytes)
 pkts bytes target     prot opt in     out     source               destination
   35  2100 MASQUERADE  all  --  *      eth0    10.8.0.0/24          0.0.0.0/0
```

**Comment by molly78** [comment]
Much thanks for your help

pi@pihole:~ $  iptables -t nat -L -n -v
modprobe: ERROR: could not insert 'ip_tables': Operation not permitted
iptables v1.4.21: can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.

**Comment by 0-kaladin** [comment]
You need to be root to run those commands.

**Comment by molly78** [comment]
aaah, apologies

root@pihole:~#  iptables -t nat -L -n -v
Chain PREROUTING (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain POSTROUTING (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
root@pihole:~#

**Comment by 0-kaladin** [comment]
Yea you have no masquerade rules. Look at issue #151 I've posted near the bottom of that what you need. I'm not on computer right now so can't paste in here. Would love to see your install output to see why the rules didn't apply from the script.

**Comment by 0-kaladin** [comment]
please run this as root:
```
iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o "eth0" -j MASQUERADE
netfilter-persistent save
```
The script runs this yet you don't have the rules in iptables.  I'd love to see your install output if you want to uninstall and reinstall and see if the script still didn't add the iptables commands.

**Comment by molly78** [comment]
uninstalled and reinstalled
log:

pi@pihole:~ $  curl -L https://install.pivpn.io | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   178  100   178    0     0    366      0 --:--:-- --:--:-- --:--:--   366
:::
::: sudo will be used for the install.
100 40715  100 40715    0     0  44325      0 --:--:-- --:--:-- --:--:-- 44325
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: Your pi is up to date! Continuing with PiVPN installation...
:::
::: Checking dependencies:
:::    Checking for openvpn... already installed!
:::    Checking for git... already installed!
:::    Checking for dhcpcd5... already installed!
:::    Checking for tar... already installed!
:::    Checking for wget... already installed!
:::    Checking for grep... already installed!
:::    Checking for iptables-persistent... already installed!
:::    Checking for dnsutils... already installed!
:::    Checking for expect... already installed!
:::    Checking for whiptail... already installed!
::: Verifying free disk space...
::: Cancel selected. Exiting...
pi@pihole:~ $  curl -L https://install.pivpn.io | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   178  100   178    0     0    466      0 --:--:-- --:--:-- --:--:--   468
100 40715  100 40715    0     0  49346      0 --:--:-- --:--:-- --:--:--  148k
:::
::: sudo will be used for the install.
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: Your pi is up to date! Continuing with PiVPN installation...
:::
::: Checking dependencies:
:::    Checking for openvpn... already installed!
:::    Checking for git... already installed!
:::    Checking for dhcpcd5... already installed!
:::    Checking for tar... already installed!
:::    Checking for wget... already installed!
:::    Checking for grep... already installed!
:::    Checking for iptables-persistent... already installed!
:::    Checking for dnsutils... already installed!
:::    Checking for expect... already installed!
:::    Checking for whiptail... already installed!
::: Verifying free disk space...
::: Using interface: eth0
::: Static IP already configured.
::: Using User: pi
:::
::: Stopping OpenVPN service... done.
:::
::: Checking for existing base files...
:::    Checking /etc/.pivpn is a repo... OK!
:::     Updating repo in /etc/.pivpn... done!
:::
::: Installing scripts to /opt/pivpn... done.
::: Using protocol: udp
::: Building CA...
Generating a 2048 bit RSA private key
..............+++
.......+++
writing new private key to '/etc/openvpn/easy-rsa/pki/private/ca.key.PBcpPG6oNN'
-----

::: CA Complete.

Note: using Easy-RSA configuration from: ./vars
Generating a 2048 bit RSA private key
.........................................................+++
....................................................................+++
writing new private key to '/etc/openvpn/easy-rsa/pki/private/server.key.7EPPMJZ3Qy'
-----
Using configuration from /etc/openvpn/easy-rsa/openssl-1.0.cnf
Check that the request matches the signature
Signature ok
The Subject's Distinguished Name is as follows
commonName            :ASN.1 12:'server'
Certificate is to be certified until Dec  8 20:58:24 2026 GMT (3650 days)

Write out database with 1 new entries
Data Base Updated

Note: using Easy-RSA configuration from: ./vars
Generating DH parameters, 2048 bit long safe prime, generator 2
This is going to take a long time


DH parameters of size 2048 created at /etc/openvpn/easy-rsa/pki/dh.pem

net.ipv4.ip_forward = 1
run-parts: executing /usr/share/netfilter-persistent/plugins.d/15-ip4tables save
run-parts: executing /usr/share/netfilter-persistent/plugins.d/25-ip6tables save
Synchronizing state for openvpn.service with sysvinit using update-rc.d...
Executing /usr/sbin/update-rc.d openvpn defaults
Executing /usr/sbin/update-rc.d openvpn enable
::: Install Complete...



rebooted


pi@pihole:~ $ sudo  iptables -t nat -L -n -v
Chain PREROUTING (policy ACCEPT 369 packets, 25131 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain INPUT (policy ACCEPT 357 packets, 24237 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain OUTPUT (policy ACCEPT 83 packets, 6556 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain POSTROUTING (policy ACCEPT 81 packets, 6404 bytes)
 pkts bytes target     prot opt in     out     source               destination
    2   152 MASQUERADE  all  --  *      eth0    10.8.0.0/24          0.0.0.0/0
    0     0 MASQUERADE  all  --  *      eth0    10.8.0.0/24          0.0.0.0/0
    0     0 MASQUERADE  all  --  *      eth0    10.8.0.0/24          0.0.0.0/0


-----------------

log from OpenVPN on my device as it times out now


2016-12-10 16:50:39 EVENT: RESOLVE
2016-12-10 16:50:39 Contacting 1x.1x.1x.1x:1194 via UDP
2016-12-10 16:50:39 EVENT: WAIT
2016-12-10 16:50:39 SetTunnelSocket returned 1
2016-12-10 16:50:39 Connecting to [pivpn.xxxxxx.ca]:1194 (1x.1x.1x.1x) via UDPv4
2016-12-10 16:50:39 NET Internet:ReachableViaWWAN/WR t------
2016-12-10 16:50:39 NET WiFi:NotReachable/WR t------
2016-12-10 16:50:49 Server poll timeout, trying next remote entry...
2016-12-10 16:50:49 EVENT: RECONNECTING
2016-12-10 16:50:49 EVENT: RESOLVE
2016-12-10 16:50:49 Contacting 1x.1x.1x.1x:1194 via UDP
2016-12-10 16:50:49 EVENT: WAIT
2016-12-10 16:50:49 SetTunnelSocket returned 1
2016-12-10 16:50:49 Connecting to [pivpn.xxxxxx.ca]:1194 (1x.1x.1x.1x) via UDPv4
2016-12-10 16:50:59 Server poll timeout, trying next remote entry...
2016-12-10 16:50:59 EVENT: RECONNECTING
2016-12-10 16:50:59 EVENT: RESOLVE
2016-12-10 16:50:59 Contacting 1x.1x.1x.1x:1194 via UDP
2016-12-10 16:50:59 EVENT: WAIT
2016-12-10 16:50:59 SetTunnelSocket returned 1
2016-12-10 16:50:59 Connecting to [pivpn.xxxxxx.ca]:1194 (1x.1x.1x.1x) via UDPv4
2016-12-10 16:51:09 Server poll timeout, trying next remote entry...
2016-12-10 16:51:09 EVENT: RECONNECTING
2016-12-10 16:51:09 EVENT: RESOLVE
2016-12-10 16:51:09 Contacting 1x.1x.1x.1x:1194 via UDP
2016-12-10 16:51:09 EVENT: WAIT
2016-12-10 16:51:09 SetTunnelSocket returned 1
2016-12-10 16:51:09 Connecting to [pivpn.xxxxxx.ca]:1194 (1x.1x.1x.1x) via UDPv4

**Comment by 0-kaladin** [comment]
ok i'll close this still need to figure out why iptables masquerade didn't save for you first time.
