### ISSUE TITLE
Cannot access local subnet

### ISSUE THREAD

**Issue by andrum99** [pivpn/pivpn#1665]
I'm having trouble accessing my local subnet from the VPN. I'm using the Wireguard option for PiVPN. The installation tool will let me set the DNS to my local DNS server, but I cannot access anything on that subnet. Is this supposed to Just Work? If not, can someone tell me how to get it working?

**Comment by iLl3ctRo** [comment]
As far as i know the default settings dont forward the local subnet to the VPN Network. Depending on your configuration you must change the settings for the host and client in the corresponding conf files yourself.

I know that posting a Link is not the ideal answer but A good explainition is given in this blog post:

[WIreguard local forwarding](https://iliasa.eu/wireguard-how-to-access-a-peers-local-network/)

**Comment by orazioedoardo** [comment]
> Is this supposed to Just Work?

Yes it is. Can you browse the web though the VPN?

> As far as i know the default settings dont forward the local subnet to the VPN Network.

It forwards everything.

**Comment by andrum99** [comment]
> > Is this supposed to Just Work?
> 
> Yes it is. Can you browse the web though the VPN (just to check whether you are actually connected)?

No, but my DNS is set to my local DNS server and I cannot access any of the local subnet. I can ping hosts out on the internet, but I need my local DNS server to be accessible from VPN clients.

> 
> > As far as i know the default settings dont forward the local subnet to the VPN Network.
> 
> It forwards everything.

Then something is broken in my setup. Should I post config files or logs? Or was there a question perhaps in the PiVPN setup that I should have given a different answer to?

**Comment by 4s3ti** [comment]
> Then something is broken in my setup. Should I post config files or logs? Or was there a question perhaps in the PiVPN setup that I should have given a different answer to?

That should have been done from the beginning. 

https://github.com/pivpn/pivpn#general-guidelines

> * If you have not found the answer feel free to open an [issue](https://github.com/pivpn/pivpn/issues/new/choose) and we will do our best to help out
>     * Please help us helping you and fill the template adequately providing the requested data Even if it doesn't feel relevant to you

There's a Template for that exact same reason.
