### ISSUE TITLE
Install...impossible curl -L https://raw.githubusercontent.com/pivpn/pivpn/master/auto_install/install.sh | bash

### ISSUE THREAD

**Issue by BigBobDalton** [pivpn/pivpn#1666]
I constantly receive an erro;
 fatal: unable to access 'https://github.com/pivpn/pivpn.git/': Failed to connect to github.com port 443: No route to host

regardless of which installation method.

Raspberry clean install, 
::: Your system is up to date! Continuing with PiVPN installation...
:::    Checking for git... already installed!
:::    Checking for tar... already installed!
:::    Checking for curl... already installed!
:::    Checking for grep... already installed!
:::    Checking for dnsutils... already installed!
:::    Checking for grepcidr... already installed!
:::    Checking for whiptail... already installed!
:::    Checking for net-tools... already installed!
:::    Checking for bsdmainutils... already installed!
:::    Checking for bash-completion... already installed!
:::    Checking for dhcpcd5... already installed!
:::    Checking for iptables-persistent... already installed!
Reading package lists... Done

No errors.

I guess your site is down??

**Comment by orazioedoardo** [comment]
> I guess your site is down??

Your connection is. Reopen the issue if that's not the case.
