### ISSUE TITLE
Client attribute (-c) not supported on v1.6?

### ISSUE THREAD

**Issue by rdlf4** [pivpn/pivpn#167]
Hello, PiVPN team!

I'm running PiVPN Version 1.6 on my Raspberry Pi Model B+ and I've got some questions:
On the PiVPN website, there's this command:
`pivpn -c` which lists connected clients to my VPN. But it doesn't work. The output to this command gives no results and suggests a list of other commands, the `-c` is not listed as a "supported" attribute.
So what's up with that? I'm really sorry if this has been asked before, but I looked up and judging from the thread topics, there seems to be no related question to this.
An other thing, I also would like to connect to my Home VPN using an Ubuntu PC from work. The problem is that the applet made by OpenVPN for the Gnome Network Manager is nothing but trouble, and so is Gadmin, which requires extra keys, such as DH key and TA key - where do I find those?
Please let me know if some extra info/command output is required to better address my questions and I'll promptly quote them here.

Thank you.

**Comment by rdlf4** [comment]
Another question just popped up in my mind:
You see, I chose not to install unattended updates during installation process, so is there a way to manage unattended updates using the Terminal? The reason I decided not to install it is because I really don't want to mess up with PiVPN, but at the same time I don't want to miss out on the secutiry updates for it.

Thanks again.

**Comment by redfast00** [comment]
Client list only got added in 1.7 and it got fixed in 1.8. The other keys you need for the Ubuntu applet are in the `.ovpn` file: you will need to copy-paste them into separate files. Another way you can do this is by running `openvpn - - config client.ovpn` as root. You can update your Pi with `apt-get update` and `apt-get upgrade` as root. Unattended updates basically means that the Pi will automatically install all important security updates.

**Comment by rdlf4** [comment]
Thank you for replying, redfast00
OpenVPN is not really working on my Ubuntu and Linux Mint. Like, at all.
After trying to give it a go, using the Terminal, this is what I got from `sudo openvpn ptsusr2.ovpn`:

> Options error: Unrecognized option or missing parameter(s) in ptsusr2.ovpn:11: tls-version-min (2.2.1)

So I used Nano and edited out the line `#tls-version-min 1.2`; After doing that, I tried the same command, to which it output: 

> Options error: Unrecognized option or missing parameter(s) in ptsusr2.ovpn:12: verify-x509-name (2.2.1)

What the heck.. Went back into the file and edited out `#verify-x509-name server name`
It goes without saying my hopes were practically none at this point, but I tried to openvpn it once again, to see how it goes:

> user@user-GA-78LMT-USB3:/media/ef2a28ac-086d-47fc-92ff-859f5f11b216/home/user/Documents/VPN$ sudo openvpn ptsusr2.ovpn
> Sun Dec 11 06:26:43 2016 OpenVPN 2.2.1 i686-linux-gnu [SSL] [LZO2] [EPOLL] [PKCS11] [eurephia] [MH] [PF_INET6] [IPv6 payload 20110424-2 (2.2RC2)] built on Dec  1 2014
> Sun Dec 11 06:26:43 2016 NOTE: OpenVPN 2.1 requires '--script-security 2' or higher to call user-defined scripts or executables
> Enter Private Key Password:
> Sun Dec 11 06:26:47 2016 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
> Sun Dec 11 06:26:47 2016 Control Channel Authentication: tls-auth using INLINE static key file
> Sun Dec 11 06:26:47 2016 LZO compression initialized
> Sun Dec 11 06:26:47 2016 UDPv4 link local: [undef]
> Sun Dec 11 06:26:47 2016 UDPv4 link remote: [AF_INET]xxx.xx.xxx.xxx:1194
> Sun Dec 11 06:27:47 2016 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
> Sun Dec 11 06:27:47 2016 TLS Error: TLS handshake failed
> Sun Dec 11 06:27:47 2016 SIGUSR1[soft,tls-error] received, process restarting

Edited information: IP Address.
As you can see, it looked promising at first, but no luck after all.
Then, after googling around I noticed OpenVPN and Gnome Network Manager just won't play along so I found yet another tool from the GNOME team called Gadmin. I already created the CA, Certificate and Key files separately from my OVPN file, but it also requires the TA key as well as the DH key - those are they keys giving me an extra headache to find. 
Also, while we're at it, is it possible to upgrade from v1.6 to 1.8 or even the latest version of PiVPN from my RPi?
 
Regards.

**Comment by redfast00** [comment]
I'm sorry, you'll have to reinstall... In 1.8, we're using ECDSA keys. Also, I think you have an outdated version of the OpenVPN client.

**Comment by rdlf4** [comment]
I'm trying this on two different devices, a PC running Ubuntu Precise Pangolin 12.04 and the other one runs Linux Mint 17.3, which is based on Ubuntu 14.04. Both computers have installed OpenVPN v2.2.1 from the official repository (Launchpad/Ubuntu) and are running into the same problem.
Could you please confirm the issues mentioned previously do not happen after installing v2.3.14? 

Thank you.

**Comment by redfast00** [comment]
Do you have a smartphone running Android? You can download the OpenVPN for Android app and test it. I am pretty sure it might be because your version.
