### ISSUE TITLE
The Future of PiVPN Debug

### ISSUE THREAD

**Issue by 0-kaladin** [pivpn/pivpn#168]
So in the test branch I've begun expanding on pivpn debug.  It currently tries to detect if iptables are applied correctly and prompt user if we can fix.  What I will prefer to do in the future is have pivpn debug be the output command.  It will simply output the things we want or deem necessary to help debug.  Then we add some sub-commands to it like
pivpn debug detect
which maybe will try to detect common issues.
pivpn debug firewall
will try to ensure ufw/iptables is setup properly.  then can even ask the user questions to effect changes that maybe were incorrect from initial setup.  

Anyway that is some high level thoughts, will flush out more as free time allows.

**Comment by 4s3ti** [comment]
Closing this one as pivpndebug seems to be quite complete these days.
