### ISSUE TITLE
[BUG] Error when list clients connected

### ISSUE THREAD

**Issue by oijkn** [pivpn/pivpn#1680]
## In raising this issue, I confirm the following:

`{please fill the checkboxes, e.g: [X]}`

- [x] I have read the [documentation](https://docs.pivpn.io)
- [] Is it a feature request? please consider opening a [Discussion] (https://github.com/pivpn/pivpn/discussions/new?category=feature-requests)
- [] Is this a support request? please consider copying the content of this document and using it to open a [Discussion](https://github.com/pivpn/pivpn/discussions/new?category=support)
- [x] I have read and understood the [PiVPN General Guidelines](https://github.com/pivpn/pivpn/#general-guidelines)
- [x] The issue I am reporting can be *replicated*.  
- [x] The issue I am reporting *is* directly related to the pivpn installer script.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

### Has your install failed? 
```
No
```

### Describe the issue
When I want to display the list of clients connected to the server, an error message appears (not blocking).

**Expected behavior**
Display the list of clients connected to the server, without error messages.

**Screenshots**
```sh
user@pi:~/ovpns $ pivpn -c
: NOTE : The output below is NOT real-time!
:      : It may be off by a few minutes.

::: Client Status List :::
/opt/pivpn/openvpn/clientStat.sh: line 53: printf: - : invalid option   <== THIS IS THE ERROR
printf: usage: printf [-v var] format [arguments]
Name        Remote IP              Virtual IP         Bytes Received      Bytes Sent      Connected Since
SmartPhone  xxx.xxx.xxx.xxx:zzz    yyy.yyy.yyy.yyy    11KiB               18KiB           09:30:32 1674721832 1
```

### Can you replicate the issue? Describe the steps below

1. Type: 'pivpn -c'

### Have you searched for similar issues and solutions?
Yes, no result.

**Additional context**

### Have you taken any steps towards solving your issue?
```
I try to reboot the Raspberry but the bug is always here.
```

#### What type of hardware are you running PiVPN at?

```
Raspberrypi 4 8Go
```
#### Output of `uname -a`
```
Linux casaos 5.15.84-v8+ #1613 SMP PREEMPT Thu Jan 5 12:03:08 GMT 2023 aarch64 GNU/Linux
```

#### Output of `cat /etc/os-release`
```
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

### If install failed Please provide the console output of  `curl -L https://install.pivpn.io | bash`
```
No problem with install.
```

### Console output of      `curl -L install.pivpn.io | bash`
```
No problem with install.
```

### Console output of      `pivpn add` or `pivpn add nopass`
```
No problem with new client.
```

### Console output of      `pivpn debug`

```
No problem with pivpn.
```

**Comment by orazioedoardo** [comment]
Was fixed [here](https://github.com/pivpn/pivpn/pull/1661).
