### ISSUE TITLE
Maximum limit of 254 Wireguard clients

### ISSUE THREAD

**Issue by AR1111100011** [pivpn/pivpn#1683]
I have configured a PiVPN server with Wireguard. The network range I use is pivpnNET=172.31.96.0 and subnetClass=22.
I have reached the client with IP 172.31.97.254. From this point on I can't create any more clients. I have been looking at the makeCONF.sh script and I have seen that it checks the last octet of the clients file.
Is there any way I can continue using clients using the network 172.31.96.0? If I change the network in setupVars.conf I understand that I will still get the same thing, since it checks only the last octet of that file.

**Comment by orazioedoardo** [comment]
Yeah this is something that should be changed. In the meanwhile you can edit `/etc/wireguard/wg0.conf`

**Comment by AR1111100011** [comment]
And what do I get by editing that? The script to generate new users will still not work.

**Comment by orazioedoardo** [comment]
You are right, actually. Are you asking for a feature to change the subnet to a bigger one, or use a bigger subnet for everyone?

**Comment by AR1111100011** [comment]
Currently my network is as follows:

Network: 172.31.96.0/22       	
HostMin:	172.31.96.1	
HostMax:	172.31.99.254	
Broadcast: 172.31.99.255	
Hosts/Net: 1022	

The script started assigning IPs for clients from 172.31.96.2 to 172.31.96.254. The script should still be able to assign IPs, the next one would be the 172.31.97.1

**Comment by kratkotut** [comment]
Have you found a solution? Tell me what you can do.

**Comment by 4s3ti** [comment]
Pre-archive closing, more information [here](https://github.com/pivpn/pivpn/releases/tag/v4.6.0)
