### ISSUE TITLE
OpenVPN Server Wont Start

### ISSUE THREAD

**Issue by NoahConstrictr** [pivpn/pivpn#1689]
## In raising this issue, I confirm the following:

`{please fill the checkboxes, e.g: [X]}`

- [X] I have read the [documentation](https://docs.pivpn.io)
- [] Is it a feature request? please consider opening a [Discussion] (https://github.com/pivpn/pivpn/discussions/new?category=feature-requests)
- [] Is this a support request? please consider copying the content of this document and using it to open a [Discussion](https://github.com/pivpn/pivpn/discussions/new?category=support)
- [X] I have read and understood the [PiVPN General Guidelines](https://github.com/pivpn/pivpn/#general-guidelines)
- [X] The issue I am reporting can be *replicated*.  
- [] The issue I am reporting *is* directly related to the pivpn installer script.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

### Has your install failed? 
```
yes/no no
```

### Describe the issue

I can install PiVPN with the OpenVPN configuration just fine, but when I try to start the server with "sudo systemctl start openvpn-server@server.service" I get "Job for openvpn-server@server.service failed because the control process exited with error code.
See "systemctl status openvpn-server@server.service" and "journalctl -xe" for details."

**Expected behavior**
Access point opens and I'm able to connect.

**Screenshots**

### Can you replicate the issue? Describe the steps below

1. Copy & paste the PiVPN installation command into the terminal. "curl -L https://install.pivpn.io | bash"
2. Go through the configuration for PiVPN with OpenVPN
3. Try to open the OpenVPN server with "sudo systemctl start openvpn-server@server.service"
4. See "Job for openvpn-server@server.service failed because the control process exited with error code.
See "systemctl status openvpn-server@server.service" and "journalctl -xe" for details."

### Have you searched for similar issues and solutions?
    (yes/no / which issues?)
Yes, I've tried looking for issues about not being able to start OpenVPN server.

**Additional context**
"journalctl -xe" gives me this: 
[journalctl.txt](https://github.com/pivpn/pivpn/files/10733747/journalctl.txt)
I'm also using the feature to use Pi-Hole with PiVPN.

### Have you taken any steps towards solving your issue?
```
  Opened a discussion on the official OpenVPN forums (which is really small and inactive), the r/OpenVPN reddit, and on the OpenVPN GitHub issues site, but it might have been useful uploading on a PiVPN site.
```

#### What type of hardware are you running PiVPN at?

```
Raspberry Pi 4 2gb
```
#### Output of `uname -a`
```
  Linux raspberrypi 5.15.84-v7l+ #1613 SMP Thu Jan 5 12:01:26 GMT 2023 armv7l GNU/Linux
  DO NOT DELETE THE BACK-TICKS 
  PASTE THE OUTPUT INSIDE THE BACK-TICKS
```

#### Output of `cat /etc/os-release`
```
  PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
  NAME="Raspbian GNU/Linux"
  VERSION_ID="11"
  VERSION="11 (bullseye)"
  VERSION_CODENAME=bullseye
  ID=raspbian
  ID_LIKE=debian
  HOME_URL="http://www.raspbian.org/"
  SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
  BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
  DO NOT DELETE THE BACK-TICKS 
  PASTE THE OUTPUT INSIDE THE BACK-TICKS
```

### If install failed Please provide the console output of  `curl -L https://install.pivpn.io | bash`
```
  OUTPUT HERE / ANSWER HERE
  DO NOT DELETE THE BACK-TICKS 
  PASTE THE OUTPUT INSIDE THE BACK-TICKS
```

### Console output of      `curl -L install.pivpn.io | bash`
```
  OUTPUT HERE
  DO NOT DELETE THE BACK-TICKS 
  PASTE THE OUTPUT INSIDE THE BACK-TICKS
```

### Console output of      `pivpn add` or `pivpn add nopass`
```
  OUTPUT HERE
  DO NOT DELETE THE BACK-TICKS 
  PASTE THE OUTPUT INSIDE THE BACK-TICKS
```

### Console output of      `pivpn debug`

```
  https://github.com/pivpn/pivpn/files/10733880/pivpn_debug.txt
  DO NOT DELETE THE BACK-TICKS 
  PASTE THE OUTPUT INSIDE THE BACK-TICKS
```

**Comment by TinCanTech** [comment]
For the benefit of pivpn, moved from:
https://github.com/OpenVPN/openvpn/issues/250#

**Comment by 4s3ti** [comment]
> Steps to reproduce the behavior:
>
>   Copy & paste the PiVPN installation command into the terminal. "curl -L https://install.pivpn.io/ | bash"
>    Go through the configuration for PiVPN with OpenVPN
>    Try to open the OpenVPN server with "sudo systemctl start [openvpn-server@server.service](mailto:openvpn-server@server.service)"
>    See "Job for [openvpn-server@server.service](mailto:openvpn-server@server.service) failed because the control process exited with error code.
>    See "systemctl status [openvpn-server@server.service](mailto:openvpn-server@server.service)" and "journalctl -xe" for details." 

Could not reproduce! 

1) You are not using the default settings,this invalidate your "Steps to reproduce". Steps to reproduce, means that you have actually tried the same thing multiple times and the behavior happened every single time. 

2) Seems some packages were not installed, so maybe there was some error during installation, and you are not providing any log from the installation. 

3) Also why would you try to start the service out of the blue? what was the reason in first place to try the service, pivpn does it for you when the installation finishes. 

4) From the PiVPN Debug output you are linking, it seems openvpn service is actually running

```Feb 13 19:33:47 raspberrypi ovpn-server[570]: MULTI: multi_init called, r=256 v=256
Feb 13 19:33:47 raspberrypi ovpn-server[570]: IFCONFIG POOL IPv4: base=10.47.172.2 size=252
Feb 13 19:33:47 raspberrypi ovpn-server[570]: Initialization Sequence Completed
```


Everything points to a issue with your system, and its specific to something you might have done. looking at the topic linked .. sounds that there was quite some tinkering.

I would advice to try from a clean system, with a fresh raspbian, and simply follow the steps. 
After the installation you can check the status of openvpn with `systemctl status openvpn` if the the issue persist please re-open the Issue with the adequate details.

**Comment by NoahConstrictr** [comment]
I just reinstalled the entire operating system, and realized that it wasn't even that. For some reason, when PiVPN made the .ovpn file, it used the wrong IP address, and I had to manually change it, and then it worked just fine. I don't know if this is a bug or whatever, but it works now.
