### ISSUE TITLE
Hi, I have the same problem, I’m using an Iphone and my PiVPN doesn’t work when I’m connected to wifi (of course not the wifi where the pi is set on), it only works when i use mobile data. Can someone help me?

### ISSUE THREAD

**Issue by JJackintosh** [pivpn/pivpn#1690]
## In raising this issue, I confirm the following:

`{please fill the checkboxes, e.g: [X]}`

- [] I have read the [documentation](https://docs.pivpn.io)
- [] Is it a feature request? please consider opening a [Discussion] (https://github.com/pivpn/pivpn/discussions/new?category=feature-requests)
- [] Is this a support request? please consider copying the content of this document and using it to open a [Discussion](https://github.com/pivpn/pivpn/discussions/new?category=support)
- [] I have read and understood the [PiVPN General Guidelines](https://github.com/pivpn/pivpn/#general-guidelines)
- [] The issue I am reporting can be *replicated*.  
- [] The issue I am reporting *is* directly related to the pivpn installer script.
- [] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

### Has your install failed? 
```
yes/no
```

### Describe the issue

**Expected behavior**

**Screenshots**

### Have you searched for similar issues and solutions?
    (yes/no / which issues?)

**Additional context**

### Have you taken any steps towards solving your issue?
```
  which?
```

#### What type of hardware are you running PiVPN at?

```
Raspberrypi (specify the model)
Ordroid
OrangePi
bananaPi
Virtual machine
```
#### Output of `uname -a`
```
  OUTPUT HERE / ANSWER HERE
  DO NOT DELETE THE BACK-TICKS 
  PASTE THE OUTPUT INSIDE THE BACK-TICKS
```

#### Output of `cat /etc/os-release`
```
  OUTPUT HERE / ANSWER HERE
  DO NOT DELETE THE BACK-TICKS 
  PASTE THE OUTPUT INSIDE THE BACK-TICKS
```

### If install failed Please provide the console output of  `curl -L https://install.pivpn.io | bash`
```
  OUTPUT HERE / ANSWER HERE
  DO NOT DELETE THE BACK-TICKS 
  PASTE THE OUTPUT INSIDE THE BACK-TICKS
```

### Console output of      `curl -L install.pivpn.io | bash`
```
  OUTPUT HERE
  DO NOT DELETE THE BACK-TICKS 
  PASTE THE OUTPUT INSIDE THE BACK-TICKS
```

### Console output of      `pivpn add` or `pivpn add nopass`
```
  OUTPUT HERE
  DO NOT DELETE THE BACK-TICKS 
  PASTE THE OUTPUT INSIDE THE BACK-TICKS
```

### Console output of      `pivpn debug`

```
  OUTPUT HERE
  DO NOT DELETE THE BACK-TICKS 
  PASTE THE OUTPUT INSIDE THE BACK-TICKS
```

**Comment by 4s3ti** [comment]
Please read: https://github.com/pivpn/pivpn#feedback--support before opening an issue. 

please check: https://docs.pivpn.io/faq/#how-do-i-troubleshoot-connection-issues

if you still have an issue please re-open and *properly* fill the issue template and don't put the whole issue description on the title. 

Closing.
