### ISSUE TITLE
Feature Request for Obfuscation on Wireguard

### ISSUE THREAD

**Issue by tejt99** [pivpn/pivpn#1701]
Hi, I'm a complete beginner at this whole thing but your script has made it super simple for me to have a home VPN server for many years. However, I recently moved to a new office that utilises deep packet inspection to block VPN traffic. I've heard that this will prevent them blocking me. I tried to do this following a few articles, however, when I clicked connect, the client just wouldn't.

My feature request is to add another section to the PiVPN script that asks if the user would like to add an obfuscation layer.

Thank you so much for all your hard work, this is a brilliant tool

**Comment by 4s3ti** [comment]
Obfuscation is not a feature provided directly by wireguard, or OpenVPN, this is provided by external applications. This mean we would have to install and setup those thus adding extra dependencies for those cases and actually moving away from what PiVPN actually is. Even though I totally understand why this could be beneficial, I am not entirely sure if this should be a feature provided by PiVPN.

**Comment by TinCanTech** [comment]
Adding obfuscation is a big commitment, for very little return.

**Comment by tejt99** [comment]
Thank you for considering it anyway

**Comment by 4s3ti** [comment]
No worries. Closing.
