### ISSUE TITLE
Masquerade rule bug on reboot

### ISSUE THREAD

**Issue by OfficialMuffin** [pivpn/pivpn#1702]
I have a basic wireguard setup alongside PiHole on a Raspberry Pi 4 8GB with just 4 clients. When rebooted, communication between wireguard clients work but no Internet connection. When `pivpn -d` is used upon reboot, it asks me to add the masquerade rule again. It works! Not sure what's going on.

**Comment by 4s3ti** [comment]
https://github.com/pivpn/pivpn#feedback--support
