### ISSUE TITLE
Installation doesn't work

### ISSUE THREAD

**Issue by AuthorProxy** [pivpn/pivpn#1704]
<img width="741" alt="image" src="https://user-images.githubusercontent.com/1407631/224557205-4ac57e48-3f17-4b1e-b490-4bcac70b2fbf.png">

nothing more, waited for 30 min, tried multiple times at upcloud.com at different servers:
ubuntu server 22.04 and Debian GNU \ Linux 11

**Comment by SriramKeerthi** [comment]
Looks like it's trying to clone the repo, but `git` doesn't want to run as `root`:

```
root@somepi:/home/pi# git clone https://github.com/pivpn/pivpn.git
Please do not run git as root, your regular user account is enough :)

If you need to run git with root rights for some other application than
what comes preinstalled on this image you can remove this sanity check:

    sudo rm /root/bin/git

You might have to restart your login session after doing that.
```

**Comment by 4s3ti** [comment]
Please do not highjack issues form other users. 

First and foremost please read the docs: https://pivpn.io  
Please read the README specially this part: https://github.com/pivpn/pivpn#feedback--support 

The answer for that git issue is actually there: https://docs.pivpn.io/faq/#what-about-octopi 

When you create an issue you are prompted with details in the issue creation

**Comment by SriramKeerthi** [comment]
@4s3ti Apologies, I misread the output from @AuthorProxy's error, assuming it was the same issue. I didn't realise the script was failing at a similar location with a slightly different error. I have removed my answer.

@AuthorProxy you're right about the output of the script not being descriptive. Apologies for any confusion caused.

**Comment by 4s3ti** [comment]
@AuthorProxy unfortunately the person with the octopi issue deleted its comment.

Let me tell you how this should work: 

1) you need support, you follow the rules on the [README](https://github.com/pivpn/pivpn/blob/master/README.md) as simple as that. if you refuse to read them and provide what we request on the issue template, then there is no way we can help you. 
2) Pull requests are always very welcome! 

thread locked.
