### ISSUE TITLE
[General Issue]: pivpn installer doesn't properly configure ufw to allow connections to local network

### ISSUE THREAD

**Issue by ajaskiewiczpl** [pivpn/pivpn#1710]
### In raising this issue I confirm that

- [X] I have read the [documentation](https://docs.pivpn.io)
- [X] I have read and understood the [PiVPN General Guidelines](https://github.com/pivpn/pivpn/#general-guidelines)
- [X] I have read and understood the [PiVPN Troubleshooting Guidelines](https://docs.pivpn.io/faq/#how-do-i-troubleshoot-connection-issues)
- [X] The issue I am reporting isn't a duplicate, see [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen).
- [X] I have searched for similar issues and solutions
- [X] I can replicate the issue even after a clean OS installation

### Describe the issue

I installed pivpn using official installer script and I can connect to it from outside using DNS name. Internet connection works but I cannot access local network (192.168.1.0/24) because connection is blocked by ufw. I had to add following rule and now it works:
`sudo ufw allow from 10.113.224.0/24 to 192.168.1.0/24`

### Expected behavior

Access to local network should work out of the box.

### Please describe the steps to replicate the issue

Install pivpn using official installer script, connect to VPN from outside of your home network and try access local network.

### Have you taken any steps towards solving your issue?

 I had to add following rule and now it works:
`sudo ufw allow from 10.113.224.0/24 to 192.168.1.0/24`

### Where did you run pivpn?

RaspberryPi 4

### Please provide your output from `uname -a`

Linux rpi4.local 6.1.19-v8+ #1637 SMP PREEMPT Tue Mar 14 11:11:47 GMT 2023 aarch64 GNU/Linux

### Details about Operative System

PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

### Debug output
```
::: Generating Debug Output
::::            PiVPN debug              ::::
=============================================
::::            Latest commit            ::::
Branch: master
Commit: 4032a55c80f25b51419180eda93f44d579ab79e9
Author: 4s3ti
Date: Wed Mar 29 14:54:19 2023 +0200
Summary: docs(issues): Remove old markdown template
=============================================
::::        Installation settings        ::::
PLAT=Debian
OSCN=bullseye
USING_UFW=1
pivpnforceipv6route=1
IPv4dev=eth0
dhcpReserv=1
IPv4addr=192.168.1.2/24
IPv4gw=192.168.1.1
install_user=user
install_home=/home/user
VPN=wireguard
pivpnPORT=51820
pivpnDNS1=9.9.9.9
pivpnDNS2=149.112.112.112
pivpnHOST=REDACTED
pivpnPROTO=udp
pivpnMTU=1420
pivpnDEV=wg0
pivpnNET=10.113.224.0
subnetClass=24
pivpnenableipv6=0
ALLOWED_IPS="0.0.0.0/0, ::0/0"
UNATTUPG=1
INSTALLED_PACKAGES=()
=============================================
::::  Server configuration shown below   ::::
[Interface]
PrivateKey = server_priv
Address = 10.113.224.1/24
MTU = 1420
ListenPort = 51820
### begin pivpn-mobile ###
[Peer]
PublicKey = pivpn-mobile_pub
PresharedKey = pivpn-mobile_psk
AllowedIPs = 10.113.224.2/32
### end pivpn-mobile ###
=============================================
::::  Client configuration shown below   ::::
[Interface]
PrivateKey = pivpn-mobile_priv
Address = 10.113.224.2/24
DNS = 9.9.9.9, 149.112.112.112

[Peer]
PublicKey = server_pub
PresharedKey = pivpn-mobile_psk
Endpoint = REDACTED:51820
AllowedIPs = 0.0.0.0/0, ::0/0
=============================================
::::    Recursive list of files in       ::::
::::    /etc/wireguard shown below       ::::
/etc/wireguard:
configs
keys
wg0.conf

/etc/wireguard/configs:
clients.txt
pivpn-mobile.conf

/etc/wireguard/keys:
pivpn-mobile_priv
pivpn-mobile_psk
pivpn-mobile_pub
server_priv
server_pub
=============================================
::::            Self check               ::::
:: [OK] IP forwarding is enabled
:: [OK] Ufw is enabled
:: [OK] Iptables MASQUERADE rule set
:: [OK] Ufw input rule set
:: [OK] Ufw forwarding rule set
:: [OK] WireGuard is running
:: [OK] WireGuard is enabled
(it will automatically start on reboot)
:: [OK] WireGuard is listening on port 51820/udp
=============================================
:::: Having trouble connecting? Take a look at the FAQ:
:::: https://docs.pivpn.io/faq
=============================================
:::: WARNING: This script should have automatically masked sensitive       ::::
:::: information, however, still make sure that PrivateKey, PublicKey      ::::
:::: and PresharedKey are masked before reporting an issue. An example key ::::
:::: that you should NOT see in this log looks like this:                  ::::
:::: YIAoJVsdIeyvXfGGDDadHh6AxsMRymZTnnzZoAb9cxRe                          ::::
=============================================
::::            Debug complete           ::::
:::
::: Debug output completed above.
::: Copy saved to /tmp/debug.log
:::
```

**Comment by ajaskiewiczpl** [comment]
Yes I had couple of ufw rules before (allowing traffic on ports 80, 443), but besides that it was clean install.

**Comment by orazioedoardo** [comment]
Post the full `sudo ufw status verbose`

**Comment by pawl** [comment]
I'm having a similar issue. Here's my output of `sudo ufw status verbose`:
```
Status: active
Logging: on (low)
Default: deny (incoming), allow (outgoing), deny (routed)
New profiles: skip

To                         Action      From
--                         ------      ----
51820/udp                  ALLOW IN    Anywhere                   # allow-wireguard
22/tcp                     ALLOW IN    Anywhere                  
51820/udp (v6)             ALLOW IN    Anywhere (v6)              # allow-wireguard
22/tcp (v6)                ALLOW IN    Anywhere (v6)             

Anywhere on eth0           ALLOW FWD   10.170.159.0/24 on wg0    
```

I can also see logs in `journalctl -e` that show that traffic between port 8080 between clients is being blocked:
```
[UFW BLOCK] IN=wg0 OUT=wg0 MAC= SRC=10.170.159.2 DST=10.170.159.3 LEN=64 TOS=0x00 PREC=0x00 TTL=63 ID=0 DF PROTO=TCP SPT=57870 DPT=8080
```

**Comment by pawl** [comment]
I ended up fixing my issue by running:
```
sudo iptables -A FORWARD -i wg0 -o wg0 -p tcp --dport 8080 -m state --state NEW,ESTABLISHED -j ACCEPT
```
(you will probably want to replace 8080 with whatever port you're trying to allow)

I also tried this but it didn't work:
```
ufw allow fwd on wg0 proto tcp from any to any port 8080
```

**Comment by suurt8ll** [comment]
@pawl You prevented me from going clinically insane debugging this. Thanks, it works!

**Comment by creeper6530** [comment]
I did the following as of time of writing, and worked well:

`ufw route insert 2 allow in on wg0 from "fd11:5ee:bad:c0de::/64" out on eth0 to any`
