### ISSUE TITLE
[General Issue]: home assistant frontend stopped worked after pivpn install

### ISSUE THREAD

**Issue by radu022003** [pivpn/pivpn#1714]
### In raising this issue I confirm that

- [X] I have read the [documentation](https://docs.pivpn.io)
- [X] I have read and understood the [PiVPN General Guidelines](https://github.com/pivpn/pivpn/#general-guidelines)
- [X] I have read and understood the [PiVPN Troubleshooting Guidelines](https://docs.pivpn.io/faq/#how-do-i-troubleshoot-connection-issues)
- [X] The issue I am reporting isn't a duplicate, see [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen).
- [X] I have searched for similar issues and solutions
- [X] I can replicate the issue even after a clean OS installation

### Describe the issue

after installing on a debian11 with a running home assistant supervised installation, frontend is not accessible any longer

### Expected behavior

install a working wireguard server

### Please describe the steps to replicate the issue

1. have a Debian 11 and a home assistant supervised installation
2. run the install script
3. follow steps
4. after reboot, home assistant frontend not reachable

### Have you taken any steps towards solving your issue?

don't know what to start with

### Where did you run pivpn?

generic x86

### Please provide your output from `uname -a`

Linux atom 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux

### Details about Operative System

Debian 11

### Debug output

already uninstalled it

**Comment by orazioedoardo** [comment]
I don't see how that might be related, we do add firewall rules but only to accept connection, we don't block anything. Are you able to reproduce now? If so post the output of `iptables -vnL`

**Comment by 4s3ti** [comment]
Pre-archive closing, more information [here](https://github.com/pivpn/pivpn/releases/tag/v4.6.0)
