### ISSUE TITLE
Clients that don't accept .ovpn

### ISSUE THREAD

**Issue by kamalca** [pivpn/pivpn#172]
I am trying to connect a chromebook to my vpn. I installed the two necessary certificates: ca.crt and client.pfx, but it is also requiring a username/password. Has anyone connected a chromebook to a vpn before that could help me out?

**Comment by fyellin** [comment]
I don't have a chromebook handy, but the documention indicates that it wants you to give it your  as a p12 file.  Searching for "pkcs12 openvpn" should give you the information you need on creating one of these.

**Comment by kamalca** [comment]
I successfully created the pkcs12 file but it is also requesting a username and password and I'm not sure when/if I set those.

**Comment by 0-kaladin** [comment]
Please reference Issue #27
