### ISSUE TITLE
[Feature Request]: During initial setup, allow port selection for DNS names

### ISSUE THREAD

**Issue by jzalmanowitz** [pivpn/pivpn#1729]
### In raising this issue I confirm that

- [X] I have read the [documentation](https://docs.pivpn.io)
- [X] I have read and understood the [PiVPN General Guidelines](https://github.com/pivpn/pivpn/#general-guidelines)
- [X] I have read and understood the [PiVPN Troubleshooting Guidelines](https://docs.pivpn.io/faq/#how-do-i-troubleshoot-connection-issues)
- [X] The issue I am reporting isn't a duplicate, see [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen).
- [X] I have searched for similar issues and solutions
- [X] I can replicate the issue even after a clean OS installation

### Describe the issue

During initial setup, when prompted for static IP vs. dns name, could you please add the ability to specify an incoming port?  My ISP blocks all high-range ports for incoming connections, and as a result I have to use a non-standard port for WireGuard (in this case I use 1313).

### Expected behavior

As an end user, when I am prompted for static IP vs. DNS name, I want the ability to enter in a custom port so that when I run 'pivpn -a' to add a new client, I do not have to manually modify the configs in /etc/wireguard/configs/ for the client.conf Endpoint line before I generate a QR code.  If I do not specify a custom port, then I want the default port to be the port used.

### Please describe the steps to replicate the issue

n/a

### Have you taken any steps towards solving your issue?

Currently, I have to manually update the client.conf Endpoint line before I generate the QR code.

### Where did you run pivpn?

RaspeberryPi 3b

### Please provide your output from `uname -a`

n/a

### Details about Operative System

applies to all

### Debug output

n/a

**Comment by orazioedoardo** [comment]
Sorry for the delay but the installer already allows selecting the VPN port. You can't use a different port for different client so I don't see why you would want to modify the port at client creation.
