### ISSUE TITLE
[General Issue]: pivpn -off user disables also user-1, user-2...user-n

### ISSUE THREAD

**Issue by dolorosus** [pivpn/pivpn#1733]
### In raising this issue I confirm that

- [X] I have read the [documentation](https://docs.pivpn.io)
- [X] I have read and understood the [PiVPN General Guidelines](https://github.com/pivpn/pivpn/#general-guidelines)
- [X] I have read and understood the [PiVPN Troubleshooting Guidelines](https://docs.pivpn.io/faq/#how-do-i-troubleshoot-connection-issues)
- [X] The issue I am reporting isn't a duplicate, see [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen).
- [X] I have searched for similar issues and solutions
- [X] I can replicate the issue even after a clean OS installation

### Describe the issue

```pivpn -off user``` disables also user-1, user-2...user-n

```
oot@RASPI4~_#pivpn list
::: Clients Summary :::
Client      Public key                                        Creation date
user        Xt1S..................................tqnUI=      07 Jun 2023, 14:58, CEST
user-1      /wkr..................................5mFnA=      07 Jun 2023, 14:58, CEST
user-2      ajlD..................................NA0Ts=      07 Jun 2023, 14:58, CEST
user-3      J6Ts..................................bAJXM=      07 Jun 2023, 14:58, CEST
::: Disabled clients :::

root@RASPI4~_#pivpn -off user
Confirm you want to disable user? [Y/n] y
user
::: Updated server config
::: Successfully disabled user
::: WireGuard reloaded 
```

Now I expect "user" to be disabled, but user-1, user-2,user-3 have been also disabled

``` 
root@RASPI4~_#pivpn list
::: Clients Summary :::
Client      Public key                                        Creation date
user        Xt1S...................................qnUI=      07 Jun 2023, 14:58, CEST
user-1      /wkr...................................mFnA=      07 Jun 2023, 14:58, CEST
user-2      ajlD...................................A0Ts=      07 Jun 2023, 14:58, CEST
user-3      J6Ts...................................AJXM=      07 Jun 2023, 14:58, CEST
::: Disabled clients :::
[disabled]   user
[disabled]   user-1
[disabled]   user-2
[disabled]   user-3
```

### Expected behavior

```pivpn -off user ```  should only disable "user" 

### Please describe the steps to replicate the issue

```
root@RASPI4~_#pivpn list
::: Clients Summary :::
Client      Public key                                        Creation date
user        Xt1S..................................tqnUI=      07 Jun 2023, 14:58, CEST
user-1      /wkr..................................5mFnA=      07 Jun 2023, 14:58, CEST
user-2      ajlD..................................NA0Ts=      07 Jun 2023, 14:58, CEST
user-3      J6Ts..................................bAJXM=      07 Jun 2023, 14:58, CEST
::: Disabled clients :::

root@RASPI4~_#pivpn -off user
Confirm you want to disable user? [Y/n] y
user
::: Updated server config
::: Successfully disabled user
::: WireGuard reloaded 
```

instead of  "user" also "user-1", "user-2","user-3" have been disabled

```
root@RASPI4~_#pivpn list
::: Clients Summary :::
Client      Public key                                        Creation date
user        Xt1S...................................qnUI=      07 Jun 2023, 14:58, CEST
user-1      /wkr...................................mFnA=      07 Jun 2023, 14:58, CEST
user-2      ajlD...................................A0Ts=      07 Jun 2023, 14:58, CEST
user-3      J6Ts...................................AJXM=      07 Jun 2023, 14:58, CEST
::: Disabled clients :::
[disabled]   user
[disabled]   user-1
[disabled]   user-2
[disabled]   user-3
```

### Have you taken any steps towards solving your issue?

adding " ###" to grep/sed commands in (en/dis)ableCONF.sh

### Where did you run pivpn?

RaspberryPi

### Please provide your output from `uname -a`

Linux RASPI4 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux

### Details about Operative System

PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

### Debug output

```
root@RASPI4~_#pivpn -d
::: Generating Debug Output
::::            PiVPN debug              ::::
=============================================
::::            Latest commit            ::::
Branch: master
Commit: 4032a55c80f25b51419180eda93f44d579ab79e9
Author: 4s3ti
Date: Wed Mar 29 14:54:19 2023 +0200
Summary: docs(issues): Remove old markdown template
=============================================
```

**Comment by 4s3ti** [comment]
Hi,

I noticed that you closed the pull request you done upon request for some changes. may I know the reason why?
I will be very glad to accept it and merge it into the test branch if you change the PR according to the guidelines.

**Comment by 4s3ti** [comment]
alright! makes sense! Thanks a lot!
