### ISSUE TITLE
[General Issue]: Update disabled - v.1.9.0

### ISSUE THREAD

**Issue by un99known99** [pivpn/pivpn#1736]
### In raising this issue I confirm that

- [X] I have read the [documentation](https://docs.pivpn.io)
- [X] I have read and understood the [PiVPN General Guidelines](https://github.com/pivpn/pivpn/#general-guidelines)
- [X] I have read and understood the [PiVPN Troubleshooting Guidelines](https://docs.pivpn.io/faq/#how-do-i-troubleshoot-connection-issues)
- [X] The issue I am reporting isn't a duplicate, see [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen).
- [X] I have searched for similar issues and solutions
- [X] I can replicate the issue even after a clean OS installation

### Describe the issue

installed pivpn quite some time ago via the one liner script.
Now I wanted to update but getting following output:

pivpn -v
Version 1.9
root@pihole[/home/pi] # pivpn -up
::: The updating functionality for PiVPN scripts is temporarily disabled
::: To keep the VPN (and the system) up to date, use 'apt update' and 'apt upgrade'

any help in how to upgrade? (using it with openvpn)

### Expected behavior

upgrading pivpn via pivpn -upgrade

### Please describe the steps to replicate the issue

pivpn -up

### Have you taken any steps towards solving your issue?

pivpn -up

### Where did you run pivpn?

Raspberry Pi

### Please provide your output from `uname -a`

Linux pi 6.1.21-v7+ #1642 SMP Mon Apr  3 17:20:52 BST 2023 armv7l GNU/Linux

### Details about Operative System

bullseye, latest patch levels

### Debug output

root@pihole[/home/pi] # pivpn -up
::: The updating functionality for PiVPN scripts is temporarily disabled
::: To keep the VPN (and the system) up to date, use 'apt update' and 'apt upgrade'

**Comment by 4s3ti** [comment]
Hi,

here are more details about it: https://github.com/pivpn/pivpn/issues/1293
