### ISSUE TITLE
Unable to migrate server to new RPi

### ISSUE THREAD

**Issue by freerainboxbox** [pivpn/pivpn#175]
http://pastebin.com/E9DqyNNS

**Comment by 0-kaladin** [comment]
This might be difficult. How hard is it for you to just get new certs onto your clients so you can just do a complete new install? 
You could migrate over time. In other words bring up new server on a different port than old. Then as you have time or it is possible use the new server ovpn files on the clients. Both work until you have all clients moved over then kill the old server.

**Comment by freerainboxbox** [comment]
I figured it out. All I had to do was use the correct openvpn package for my Pi3, then cp -r the server.conf, the easy-rsa keys and certs, and the ta.key (which I used to protect my server from DDoS attacks), and then changed the port forwarding rules on my router. Btw, your software is great! Takes a lot of guesswork out of setting up the server. I'm actually posting this comment from my Pi3 right now!
