### ISSUE TITLE
PiVPN - Masquerade-Input-Forward, has to be re-initiated after each reboot  [General Issue]: 

### ISSUE THREAD

**Issue by Grandclaw** [pivpn/pivpn#1752]
### In raising this issue I confirm that

- [X] I have read the [documentation](https://docs.pivpn.io)
- [X] I have read and understood the [PiVPN General Guidelines](https://github.com/pivpn/pivpn/#general-guidelines)
- [X] I have read and understood the [PiVPN Troubleshooting Guidelines](https://docs.pivpn.io/faq/#how-do-i-troubleshoot-connection-issues)
- [X] The issue I am reporting isn't a duplicate, see [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen).
- [X] I have searched for similar issues and solutions
- [X] I can replicate the issue even after a clean OS installation

### Describe the issue

Long story ,short.
What i want to do ?
Bought mini-PC (lenovo company small pc) , installed with ethernet to my router, made clean install of Ubuntu 20.04 , installed PiVPN to use it with Wireguard, and when i am moving to another country etc. i want to connect to my home network ,and make a wifi connection as well for other devices to login into the same home network (where the PiVPN Server is)

Problem ?

After restart, i run the "pivpn -d" and each time it requests to fix the files, if i do it , it works ..
(Masquerade-Input-Forward)

### Expected behavior

What i expect ?

I want whenever the PC loses power, or restarts or whatever, the connection with PiVPN and Wireguard WILL NOT be lost , so i can access it, after i will not be physically in front of the server

### Please describe the steps to replicate the issue

1. Clean install Ubuntu 20.04
2. Install PiVPN 
3. Configure Wireguard and default port.
4. Restart machine after ending of the wizard
5. Voillaaaa...! 

### Have you taken any steps towards solving your issue?

Clean - and read more forums , etc. but couldn't find the solution to it.

### Where did you run pivpn?

Lenovo M710Q + Ubuntu 20.04

### Please provide your output from `uname -a`

Linux vpn-thinkcentre-710q 5.15.0-76-generic #83~20.04.1-Ubuntu SMP Wd Jun 21 20:23:31 UTC 2023 x86 x64 GNU/Lunux

### Details about Operative System

Lenovo M710Q
Ubuntu 20.04

### Debug output

pivpn debug

**Comment by orazioedoardo** [comment]
Post the actual `pivpn debug`, perhaps also `sudo iptables -vnL` and s`udo iptables -t nat -vnL`

**Comment by Grandclaw** [comment]
> Post the actual `pivpn debug`, perhaps also `sudo iptables -vnL` and s`udo iptables -t nat -vnL`

Fixed it :)
I had to delete everyting and start over the entire intsallation
