### ISSUE TITLE
pivpnclient on raspi

### ISSUE THREAD

**Issue by regalboot** [pivpn/pivpn#176]
Hy i installed pivpn on a raspy as server. It works fine with my iphone and also with my win pc
Now i will try it with a other raspi as client,
This dosn t work. i have copy and link the .conf file and i can start the client but it will not do a connection
Where i find the cl.cert; cl.key. ta.key ca.cert on the server?
I think this is files aremissing ?
is there an other solutions?
Greeting
![client](https://cloud.githubusercontent.com/assets/6453691/21494446/d9ab2b16-cc11-11e6-9495-d2f37f2b8c75.jpg)

**Comment by fyellin** [comment]
The certificates and private keys live in the directory `/etc/openvpn/easy-rsa/pki` and its two subdirectories `private` and `issued`.

**Comment by fyellin** [comment]
Actually, I've just gone back and re-read your original message.  Are you trying to have your two pis talking to each other by having them run the exact same configuration?  That won't work. One has to be the client and the other the server.  

You should set up a client configuration for your second pi the exact same way you set up a client configuration for any other client.  You should then be able to run `sudo openvpn  <configurationFile>` on the client pi.

**Comment by cfcolaco** [comment]
@redfast00 and here! no answer from @regalboot since @fyellin reply. think we can assume that this is no longer an issue! 

Thank you
