### ISSUE TITLE
[Install Failed]: no wireguard option on pimox container

### ISSUE THREAD

**Issue by caiotizio** [pivpn/pivpn#1762]
### In raising this issue I confirm that

- [X] I have read the [documentation](https://docs.pivpn.io)
- [X] I have read and understood the [PiVPN General Guidelines](https://github.com/pivpn/pivpn/#general-guidelines)
- [X] I have read and understood the [PiVPN Troubleshooting Guidelines](https://docs.pivpn.io/faq/#how-do-i-troubleshoot-connection-issues)
- [X] The issue I am reporting isn't a duplicate, see [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen).
- [X] I have searched for similar issues and solutions
- [X] I can replicate the issue even after a clean OS installation

### Describe the issue

i'm trying to install wireguard using PiVpn, but it automatically install openvpn. there is no choose to select wireguard or openvpn.

### Expected behavior

possibility to select wich vpn to install

### Please describe the steps to replicate the issue

just run the script on fresh OS 

### Have you taken any steps towards solving your issue?

nope

### Screenshots

![screenshoot](https://github.com/pivpn/pivpn/assets/5230212/0d70b0b5-b11f-436d-adbc-03dc559e53ca)

### Where did you run pivpn?

raspberry pi 4 64 bit

### Please provide your output from `uname -a`

root@wireguard:~# uname -a
Linux wireguard 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux

### Details about Operative System

debian bullseye container on Pimox (proxmox for raspberry)

**Comment by 4s3ti** [comment]
containers are not really supported, specially lxc containers which i believe are the ones in use.

https://docs.pivpn.io/faq/#what-boardsoses-does-pivpn-support

**Comment by caiotizio** [comment]
in proxmox x86 it works out of the box.
thank you anyway.
