### ISSUE TITLE
enter IP when creating a user

### ISSUE THREAD

**Issue by Vincenzoferrara** [pivpn/pivpn#1769]
### In raising this issue I confirm that

- [X] I have read the [documentation](https://docs.pivpn.io)

Hi, I'm new to github and I'm not sure if this is the right place to ask this.

I would like to be able to also choose an IP when I create a client (makes it easier to create firewall rules)
example: [write an IP or leave blank for the default one: (10.0.0.1)]

ps: if it is possible to also have the text in Italian it would be "scrivi l'ip o lascia vuoto per quello di default"

**Comment by orazioedoardo** [comment]
> I would like to be able to also choose an IP when I create a client (makes it easier to create firewall rules)

Can't you just create a client and see which IP is assigned?

> if it is possible to also have the text in Italian

We wouldn't add a single localized string for this feature. Currently this project is english only, localization is possible but would required replacing all text in scripts with placeholder shell variables and then create language files with variables mapping to the localized strings.

**Comment by Vincenzoferrara** [comment]
I divided my subnet into:
10.0.0.xxx for clients that need remote desktop access only
10.0.1.xxx for access to my servers (nas, mysql database etc..)
and 10.0.2.xxx for clients that need access to the smart home only

so random client generation is a bit of a problem

**Comment by orazioedoardo** [comment]
So actually you want a specific subnet, not a specific IP. You can do that this way:

```
curl -L -o install.sh https://install.pivpn.io
chmod +x install.sh
pivpnNET=10.0.2.0 ./install.sh
```

You can also automate the whole install: https://docs.pivpn.io/guides/user-data

**Comment by Vincenzoferrara** [comment]
I would like my clients to have different submasks, not my "wireguard server"

**Comment by 4s3ti** [comment]
Pre-archive closing, more information [here](https://github.com/pivpn/pivpn/releases/tag/v4.6.0)
