### ISSUE TITLE
[General Issue]: Alpine: No routing after reboot (with FIX?)

### ISSUE THREAD

**Issue by notreallybob** [pivpn/pivpn#1773]
### In raising this issue I confirm that

- [X] I have read the [documentation](https://docs.pivpn.io)
- [X] I have read and understood the [PiVPN General Guidelines](https://github.com/pivpn/pivpn/#general-guidelines)
- [X] I have read and understood the [PiVPN Troubleshooting Guidelines](https://docs.pivpn.io/faq/#how-do-i-troubleshoot-connection-issues)
- [X] The issue I am reporting isn't a duplicate, see [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen).
- [X] I have searched for similar issues and solutions
- [X] I can replicate the issue even after a clean OS installation

### Describe the issue

On Alpine Linux, the iptables is not saved during pivpn install, so after a reboot, clients are not able to reach other servers.

### Expected behavior

iptables should be persisted.

### Please describe the steps to replicate the issue

1. Tested on fresh install of Alpine (under proxmox)
2. Install using curl -L https://install.pivpn.io | bash
3. Run iptables -t nat -L
4. Reboot
5. Run iptables -t nat -L

### Have you taken any steps towards solving your issue?

Only for Alpine:
1. The iptables+ip6tables package doesn't appear to enable the respective services for persistence. This needs to be enabled.
2. Call to enable persistence, similar to existing code under debian/ubuntu.

I modified the auto_install/install.sh script:
1. After package installation, around line 128
  if [[ "${PLAT}" == 'Alpine' ]]; then
    installDependentPackages BASE_DEPS_ALPINE[@]
    ${SUDO} rc-update add iptables    # enable persistence for ipv4
    ${SUDO} rc-update add ip6tables  # enable persistence for ipv6
  else  
    installDependentPackages BASE_DEPS[@]
  fi

2. Near line 3391, add case to persist.
  case "${PLAT}" in   
    Debian | Raspbian | Ubuntu)
      ${SUDO} iptables-save \         
        | ${SUDO} tee /etc/iptables/rules.v4 > /dev/null
      ${SUDO} ip6tables-save \    
        | ${SUDO} tee /etc/iptables/rules.v6 > /dev/null
      ;;                                                             
    Alpine)    #<====== HERE
      ${SUDO} /etc/init.d/iptables save    
      ${SUDO} /etc/init.d/ip6tables save                          
      ;;                                                                              
  esac

### Where did you run pivpn?

Alpine Linux, under Proxmox virtual environment.

### Please provide your output from `uname -a`

Linux pivpntest 6.2.16-15-pve #1 SMP PREEMPT_DYNAMIC PMX 6.2.16-15 (2023-09-28T13:53Z) x86_64 GNU/Linux

### Details about Operative System

NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.19_alpha20230901
PRETTY_NAME="Alpine Linux edge"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://gitlab.alpinelinux.org/alpine/aports/-/issues"

### Debug output

grep: warning: stray \ before =
::: Generating Debug Output
::::            PiVPN debug              ::::
=============================================
::::            Latest commit            ::::
Branch: master
Commit: f9ae9662ecc49896d09cdb38e177d2efa90e7119
Author: camdenAR
Date: Thu Oct 19 18:56:19 2023 -0500
Summary: fix(scripts): Match full client name when disabling
=============================================
::::        Installation settings        ::::
PLAT=Alpine
OSCN=3.19_alpha20230901
USING_UFW=0
pivpnforceipv6route=1
IPv4dev=eth0
install_user=blah
install_home=/home/blah
VPN=wireguard
pivpnPORT=51820
pivpnDNS1=9.9.9.9
pivpnDNS2=1.1.1.1
pivpnHOST=REDACTED
INPUT_CHAIN_EDITED=0
FORWARD_CHAIN_EDITED=0
INPUT_CHAIN_EDITEDv6=
FORWARD_CHAIN_EDITEDv6=
pivpnPROTO=udp
pivpnMTU=1420
pivpnDEV=wg0
pivpnNET=10.211.164.0
subnetClass=24
pivpnenableipv6=0
ALLOWED_IPS="0.0.0.0/0, ::0/0"
UNATTUPG=0
INSTALLED_PACKAGES=()
=============================================
::::  Server configuration shown below   ::::
[Interface]
PrivateKey = server_priv
Address = 10.211.164.1/24
MTU = 1420
ListenPort = 51820
=============================================
::::  Client configuration shown below   ::::
::: There are no clients yet
=============================================
::::    Recursive list of files in       ::::
::::    /etc/wireguard shown below       ::::
/etc/wireguard:
configs
keys
wg0.conf

/etc/wireguard/configs:
clients.txt

/etc/wireguard/keys:
server_priv
server_pub
=============================================
::::            Self check               ::::
grep: warning: stray \ before =
:: [OK] IP forwarding is enabled
:: [OK] Iptables MASQUERADE rule set
:: [OK] WireGuard is running
:: [OK] WireGuard is enabled (it will automatically start on reboot)
:: [OK] WireGuard is listening on port 51820/udp
=============================================
:::: Having trouble connecting? Take a look at the FAQ:
:::: https://docs.pivpn.io/faq
=============================================
:::: WARNING: This script should have automatically masked sensitive       ::::
:::: information, however, still make sure that PrivateKey, PublicKey      ::::
:::: and PresharedKey are masked before reporting an issue. An example key ::::
:::: that you should NOT see in this log looks like this:                  ::::
:::: asdfasdasfasdasd                          ::::
=============================================
::::            Debug complete           ::::
::: 
::: Debug output completed above.
::: Copy saved to /tmp/debug.log
:::

**Comment by 4s3ti** [comment]
Pre-archive closing, more information [here](https://github.com/pivpn/pivpn/releases/tag/v4.6.0)

**Comment by pulpe** [comment]
@notreallybob thanks for the fix
