### ISSUE TITLE
[BUG]: No internet after migrating PiVPN to new setup with PiHole installed (Solution included)

### ISSUE THREAD

**Issue by MattH688** [pivpn/pivpn#1775]
### In raising this issue I confirm that

- [X] I have read the [documentation](https://docs.pivpn.io)
- [X] I have read and understood the [PiVPN General Guidelines](https://github.com/pivpn/pivpn/#general-guidelines)
- [X] I have read and understood the [PiVPN Troubleshooting Guidelines](https://docs.pivpn.io/faq/#how-do-i-troubleshoot-connection-issues)
- [X] The issue I am reporting isn't a duplicate, see [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen).
- [X] I have searched for similar issues and solutions
- [X] I can replicate the issue even after a clean OS installation

### Describe the issue

No internet access occurs on client devices after following the migration guide for moving PiVPN, [see documentation "PiVPN Docs: Migrating PiVPN & Wireguard"](https://docs.pivpn.io/wireguard/), with a PiHole installation.

Requests are sent from the clients device to PiVPN where the DNS is resolved, as can be monitored in PiHole, however the answers are not returned to the client. This leads to no internet access however local network access is available.

### Expected behavior

DNS requests should be returned when the client requests them. Essentially they are blocked by a Network Address translation (NAS) which does not pass the returned responses to the client.

This occurs due to how PiVPN installation on the new system almost always uses a different subnet mask compared to the subnet mask being imported from the migration. For example...

PiVPN-Alpha = New installation = Subnet 10.10.8.0/24
PiVPN-Beta = Old installation being imported to maintain clients = Subnet 10.50.8.0/24

1. PiVPN new installation, PiVPN-Alpha, is initiated with a subnet of 10.10.8.0/24. This is written into the IP tables which can be viewed using `sudo iptables -t nat -S` as `-A POSTROUTING -s 10.10.8.0/24 -o eth0 -m comment --comment wireguard-nat-rule -j MASQUERADE`
2. PiVPN-Alpha undergoes the migration where the server, clients and extras are imported from PiVPN-Beta. This is carried out following the ["PiVPN Docs: Migrating PiVPN & Wireguard"](https://docs.pivpn.io/wireguard/). However, PiVPN-Betas' subnet is not 10.10.8.0/24, it is 10.50.8.0/24. This leads to PiVPN-Beta subnet clients and previous working PiVPN-Alpha being unanswered on the new installation however clients and requests appearing and answered in PiHole.

### Please describe the steps to replicate the issue

A previous PiVPN installation is required to replicate the issue.

PiVPN-Alpha = New installation = Subnet 10.10.8.0/24
PiVPN-Beta = Old installation being imported to maintain clients = Subnet 10.50.8.0/24

1. Backup the previous PiVPN installation, PiVPN-Beta, using command `pivpn -bk` 
2. Transfer the PiVPN backup, "pivpnbackup.tgz", to the new installation.
3. Install PiHole on the new installation.
4. Install PiVPN using Wireguard on the new installation. PiVPN should detect a PiHole installation and apply relevant settings.
5. Follow the ["PiVPN Docs: Migrating PiVPN & Wireguard"](https://docs.pivpn.io/wireguard/).
6. Attempt to connect to VPN where local network is accessible but no internet is available. PiHole should present VPN client and DNS requests with response.

### Have you taken any steps towards solving your issue?

PiVPN-Alpha = New installation = Subnet 10.10.8.0/24
PiVPN-Beta = Old installation being imported to maintain clients = Subnet 10.50.8.0/24

Firstly, check that this is the issue for your installation using `sudo iptables -t nat -S` and confirm that the subnet for your clients is not present in IP tables. If the migrated client subnet is present in the IP tables, this will not solve your issue. For example...

 `-A POSTROUTING -s 10.10.8.0/24 -o eth0 -m comment --comment wireguard-nat-rule -j MASQUERADE`

To solve the issue, add a new line to IP table for NAT with the previous subnet which was migrated. The previous subnet can be viewed on a client config file. For example...

 `sudo iptables -t nat -I POSTROUTING 1 -s 10.50.8.0/24 -o eth0 -j MASQUERADE`

Note it is important that the subnet is 10.50.8.**0** whilst the client will have a number greater than 0. This is for the Wireguard server.

### Where did you run pivpn?

Raspberry Pi 5 using the latest Raspberry Pi OS Bookworm

### Please provide your output from `uname -a`

Linux PiNAS 6.1.0-rpi4-rpi-2712 #1 SMP PREEMPT Debian 1:6.1.54-1+rpt2 (2023-10-05) aarch64 GNU/Linux

### Details about Operative System

PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian

### Debug output

::: Generating Debug Output
::::            PiVPN debug              ::::
=============================================
::::            Latest commit            ::::
Branch: master
Commit: f9ae9662ecc49896d09cdb38e177d2efa90e7119
Author: camdenAR
Date: Thu Oct 19 18:56:19 2023 -0500
Summary: fix(scripts): Match full client name when disabling
=============================================
::::        Installation settings        ::::
PLAT=Debian
OSCN=bookworm
USING_UFW=0
pivpnforceipv6route=1
IPv4dev=eth0
IPv4addr=[REDACTED]
IPv4gw=[REDACTED]
install_user=[REDACTED]
install_home=[REDACTED]
VPN=wireguard
pivpnPORT=[REDACTED]
pivpnDNS1=[REDACTED - PiHole DNS]
pivpnDNS2=
pivpnHOST=REDACTED
INPUT_CHAIN_EDITED=1
FORWARD_CHAIN_EDITED=0
INPUT_CHAIN_EDITEDv6=
FORWARD_CHAIN_EDITEDv6=
pivpnPROTO=udp
pivpnMTU=1420
pivpnDEV=wg0
pivpnNET=[REDACTED]
subnetClass=24
pivpnenableipv6=0
ALLOWED_IPS="0.0.0.0/0, ::0/0"
UNATTUPG=1
INSTALLED_PACKAGES=(grepcidr bsdmainutils dhcpcd5 iptables-persistent wireguard-tools qrencode unattended-upgrades)
=============================================
::::  Server configuration shown below   ::::
[Interface]
PrivateKey = [REDACTED]
Address = [REDACTED]
MTU = [REDACTED]
ListenPort = [REDACTED]
[REDACTED PEERS]
=============================================
::::  Client configuration shown below   ::::
[Interface]
PrivateKey = [REDACTED]
Address = [REDACTED]
DNS = [REDACTED]

[Peer]
PublicKey = [REDACTED]
PresharedKey = [REDACTED]
Endpoint = [REDACTED]
AllowedIPs = 0.0.0.0/0, ::0/0
=============================================
::::    Recursive list of files in       ::::
::::    /etc/wireguard shown below       ::::
/etc/wireguard:
configs
keys
wg0.conf

/etc/wireguard/configs:
[REDACTED]

/etc/wireguard/keys:
[REDACTED]
=============================================
::::            Self check               ::::
:: [OK] IP forwarding is enabled
:: [OK] Iptables MASQUERADE rule set
:: [OK] Iptables INPUT rule set
:: [OK] WireGuard is running
:: [OK] WireGuard is enabled
(it will automatically start on reboot)
:: [OK] WireGuard is listening on port 51820/udp
=============================================
:::: Having trouble connecting? Take a look at the FAQ:
:::: https://docs.pivpn.io/faq
=============================================
:::: WARNING: This script should have automatically masked sensitive       ::::
:::: information, however, still make sure that PrivateKey, PublicKey      ::::
:::: and PresharedKey are masked before reporting an issue. An example key ::::
:::: that you should NOT see in this log looks like this:                  ::::
:::: YIAoJVsdIeyvXfGGDDadHh6AxsMRymZTnnzZoAb9cxRe                          ::::
=============================================
::::            Debug complete           ::::
:::
::: Debug output completed above.
::: Copy saved to /tmp/debug.log
:::

**Comment by SNMetamorph** [comment]
> This will work until reboot (or at least the next time you run `pivpn -d`). If you want to change your subnet on the new install to the same as the old install, edit `/etc/pivpn/wireguard/setupVars.conf` and change the line `pivpnNET=x.x.x.0` to your old subnet.
> 
> It would be nice if the install script asked what subnet you want to use during setup

Little tip needed here, likely that you'll want to remove old iptables rules for initial subnet settings.
To show all rules you can use command: 
`sudo iptables -t nat -L --line-numbers`

You will find unneeded rule, remember it's number. To remove this rule you can use:
`sudo iptables -t nat -D POSTROUTING rule_number`

Next, you need to save your changes so they won't discarded after reboot. I don't know how this works in other distros, but in Ubuntu/Debian this is command:
`sudo sh -c '/sbin/iptables-save > /etc/iptables/rules.v4'`

**Comment by 01tot10** [comment]
Phew, thanks for reporting this, as well as for the instructions on how to solve the problem!
I was facing this exact problem after migrating my PiVPN instance to a new server.

My process for fixing the issue went more or less as follows, in case it might help someone (sorry for repetition):

Verify the mismatch between the subnets using a process similar to the original posting:
(SERVER) `sudo iptables -t nat -L POSTROUTING`
(CLIENT) `sudo cat /etc/wireguard/[USERID].conf|grep Address`

If there's a mismatch, check if adding a new POSTROUTING rule fixes it:
(SERVER) `sudo iptables -t nat -I POSTROUTING 1 -s [ORIGINAL-SUBNET] -o eth0 -j MASQUERADE`

Connect using the client and if everything works, continue making the changes persistent in the server.

(All of the following in SERVER)
Change your new PiVPN instance to use the old subnet:
`sudo nano /etc/pivpn/wireguard/setupVars.conf # Edit pivpnNET=[ORIGINAL-SUBNET]`
Backup your old iptables rules just in case:
`sudo cp /etc/iptables/rules.v4 /etc/iptables/rules.v4.bk`
Run PiVPN debug. This should notice the change in setupVars and create a new NAT rule:
`pivpn -d`
Delete the old NAT rule by first checking it's number and then removing it
`sudo iptables -t nat -L --line-numbers`
`sudo iptables -t nat -D POSTROUTING [RULE-NUMBER]`
(Confirm everything is as expected `sudo iptables -t nat -L POSTROUTING`)
Make NAT-rules persist reboots
`sudo sh -c '/sbin/iptables-save > /etc/iptables/rules.v4' # on Debian/Ubuntu`

Enjoy your working PiVPN 🎉 .

I'm not at all used to configuring these NAT-rules, and my only concern after having done the process is that my iptables rules in `/etc/iptables/rules.v4` went from a very minimal looking one with 9 lines, to one with 48 lines and all sorts of entries (In my case, there's lot's of DOCKER-stuff that wasn't there before..). Maybe someone knows if this is something to be worried about?

**Comment by 4s3ti** [comment]
Pre-archive closing, more information [here](https://github.com/pivpn/pivpn/releases/tag/v4.6.0)
