### ISSUE TITLE
Cloning my PIVPN server on the Rpi - Copying all relevant certs and keys

### ISSUE THREAD

**Issue by yogiberra** [pivpn/pivpn#179]
I want to build a backup PIVPN server using the same relevant certs and keys (my router will select the active server).  Can you tell me which files to move and their respective locations.  Thanks EBJ

**Comment by fyellin** [comment]
You also need to be clearer about how much of a backup the new system needs to be.  Do you just want it to run OpenVPN on it, or are you expecting to create and revoke new client keys on the new system, also?

**Comment by cfcolaco** [comment]
Things you will need to backup are in /etc/openvpn and in /etc/pivpn however not sure on how well will this work.

@yogiberra have you managed to make a working backup? some info on this would be useful. 

@redfast00 what you think of creating a backup feature in case someone needs to port to another pi?

**Comment by 0-kaladin** [comment]
Not that I find this terribly useful, as this is designed to be so easy to install from scratch. And reinstalling client certs for home users should be on a qty of 1-5.
That being said, a pivpn backup that throws all relevant files in user home directory as tgz.
Then a pivpn restore that knows to look for said file and restore them... Should not be a hard thing to implement.

**Comment by 4s3ti** [comment]
I think at this point adding a backup feature should be good, if anyone wants to jump at it ill be more than glad to aprove the PR

**Comment by 4s3ti** [comment]
Added backup script to test branch, please go ahead and test it. 
Thank you.

**Comment by panchopico** [comment]
Is the backup script run from through pivpn, or can it be run on its own? Would I need to install the entire "test" branch to run it? I've run into problems with my PiVPN installation, and was gonna blow it away and reinstall, but I thought as long as I was gonna do that, I might as well give this a spin.

**Comment by 4s3ti** [comment]
@panchopico you should be able to pickup just the backup script and use it on its own ... but please be aware its testing ... try it before you relly 100% on it and please comeback with feedback ... i would like more feebdack from our users before i push code to master/stable branch. 

alternatively you can do is: 

git clone this repo
copy the scripts inside the scripts directory  /opt/pivpn
copy pivpn/pivpn to /usr/local/bin/pivpn
copy pivpn/bash-completion /etc/bash_completion.d/pivpn


this is pretty much the manual way of this part of the script:

https://github.com/pivpn/pivpn/blob/d0c10db6ec391961b7201fb564055c1176ca73e3/auto_install/install.sh#L395-L419


then you can run the pipvn -bk

**Comment by 4s3ti** [comment]
this has been merged today into Master branch. 
Closing

**Comment by Kallb123** [comment]
The migration documentation is here:
https://github.com/pivpn/pivpn/wiki/OpenVPN#how-can-i-migrate-my-configs-to-another-pivpn-instance

**Comment by GramThanos** [comment]
Wiki no longer exists, you can find instructions on docs sites:

- OpenVPN: https://docs.pivpn.io/openvpn/#migrating-pivpn-openvpn
- Wireguard: https://docs.pivpn.io/wireguard/#migrating-pivpn-wireguard
