### ISSUE TITLE
[General Issue]: ipv6 test depends on HTTP status code

### ISSUE THREAD

**Issue by PAStheLoD** [pivpn/pivpn#1809]
### In raising this issue I confirm that

- [X] I have read the [documentation](https://docs.pivpn.io)
- [X] I have read and understood the [PiVPN General Guidelines](https://github.com/pivpn/pivpn/#general-guidelines)
- [X] I have read and understood the [PiVPN Troubleshooting Guidelines](https://docs.pivpn.io/faq/#how-do-i-troubleshoot-connection-issues)
- [X] The issue I am reporting isn't a duplicate, see [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen).
- [X] I have searched for similar issues and solutions
- [X] I can replicate the issue even after a clean OS installation

### Describe the issue

`curl -6 --fail https://google.com`  fails with error code 22 because the server gives HTTP 403 on a Hetzner VM.   Using https://aws.amazon.com succeeds.

It would be amazing to treat exit code 22 as success, after all IPv6 works marvelously, just big G is grumpy.

Thanks for considering!

### Expected behavior

ipv6 test succeeds

### Please describe the steps to replicate the issue

run install script on a hetzner VM located in Germany

### Have you taken any steps towards solving your issue?

```
curl -L https://install.pivpn.io | sed s/google.com/aws.amazon.com/g | bash -x
```

### Where did you run pivpn?

it was run on an ubuntu 22.04.3 LTS (GNU/Linux 6.5.0-14-generic x86_64) VM

### Please provide your output from `uname -a`

6.5.0-14-generic #14~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Nov 20 18:15:30 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Details about Operative System

N/A

### Debug output

N/A

**Comment by orazioedoardo** [comment]
Should be fixed with https://github.com/pivpn/pivpn/commit/20d3a4ccd4f2d080d6f9a13a74e6369aa9d54476
