### ISSUE TITLE
Why was easy-rsa forked?

### ISSUE THREAD

**Issue by dp87** [pivpn/pivpn#181]
I was looking at the [install.sh](https://github.com/pivpn/pivpn/blob/master/auto_install/install.sh) script, and I was wondering if it was really necessary to use [pivpn's own easy-rsa fork](https://github.com/pivpn/pivpn) rather than the [official one](https://github.com/OpenVPN/easy-rsa/tree/master/easyrsa3)?

What was the reason behind this choice?

**Comment by redfast00** [comment]
We want to eventually use ECDSA. Since the easy-rsa package in Debian is outdated, we decided to host it ourselves.

**Comment by dp87** [comment]
Understood, makes sense.

**Comment by devZer0** [comment]
i don't understand. what has "outdated in debian" to do with forking / bringing own version ? why not using https://github.com/OpenVPN/easy-rsa instead ?

it looks ecdsa is in there for years, at least according to https://github.com/OpenVPN/easy-rsa/commit/cc65460437554409dee7592ca36d3ed6f1db057f

**Comment by Giraffe1966** [comment]
@devZer0 The official easy-rsa package is now used in the script. See #597.

**Comment by devZer0** [comment]
what about deleting the forked github repo then ?
