### ISSUE TITLE
[General Issue]: Warn on Long Client Name

### ISSUE THREAD

**Issue by davidbeesley** [pivpn/pivpn#1816]
### In raising this issue I confirm that

- [X] I have read the [documentation](https://docs.pivpn.io)
- [X] I have read and understood the [PiVPN General Guidelines](https://github.com/pivpn/pivpn/#general-guidelines)
- [X] I have read and understood the [PiVPN Troubleshooting Guidelines](https://docs.pivpn.io/faq/#how-do-i-troubleshoot-connection-issues)
- [X] The issue I am reporting isn't a duplicate, see [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen).
- [X] I have searched for similar issues and solutions
- [X] I can replicate the issue even after a clean OS installation

### Describe the issue

client names login than 15 characters will generate an client_name.conf that will not work in linux (at least when using wireguard)

See a simliar issue and discussion here: (https://github.com/Nyr/wireguard-install/issues/114)

### Expected behavior

pivpn provides a warning if the new client name is longer that 15 characters.

### Please describe the steps to replicate the issue

1. Generate a client with a long name.
2. Export the LONG_NAME_HERE_CLIENT.conf to a linux machine (tested this on debian 12).
3.  Try to connect
```
root@thinkpad:~# wg-quick up dave_thinkpad_1492k
wg-quick: `dave_thinkpad_1492k' does not exist
root@thinkpad:~# mv /etc/wireguard/dave_thinkpad.conf /etc/wireguard/wg0.conf
root@thinkpad:~# wg-quick up wg0
[#] ip link add wg0 type wireguard

```

### Have you taken any steps towards solving your issue?

I renamed my client.

### Where did you run pivpn?

Debian 12 on Le Potato  (Official image)

### Please provide your output from `uname -a`

Linux pihole 6.1.74-12781-g74961fb0a5d2 #1 SMP PREEMPT_DYNAMIC Wed Jan 24 02:05:32 EST 2024 aarch64 GNU/Linux

### Details about Operative System

PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

### Debug output
```
::::		PiVPN debug		 ::::
=============================================
::::		Latest commit		 ::::
Branch: master
Commit: 20d3a4ccd4f2d080d6f9a13a74e6369aa9d54476
Author: Orazio
Date: Mon Jan 29 08:53:41 2024 +0100
Summary: fix(install): don't treat http errors as unavailable ipv6
=============================================
::::	    Installation settings    	 ::::
PLAT=Debian
OSCN=bookworm
USING_UFW=0
pivpnforceipv6route=1
IPv4dev=end0
install_user=dave
install_home=/home/dave
VPN=wireguard
pivpnPORT=51820
pivpnDNS1=10.242.112.1
pivpnDNS2=
pivpnHOST=REDACTED
INPUT_CHAIN_EDITED=1
FORWARD_CHAIN_EDITED=0
INPUT_CHAIN_EDITEDv6=
FORWARD_CHAIN_EDITEDv6=
pivpnPROTO=udp
pivpnMTU=1420
pivpnDEV=wg0
pivpnNET=10.242.112.0
subnetClass=24
pivpnenableipv6=0
ALLOWED_IPS="0.0.0.0/0, ::0/0"
UNATTUPG=1
INSTALLED_PACKAGES=()
=============================================
::::  Server configuration shown below   ::::
[Interface]
PrivateKey = server_priv
Address = 10.242.112.1/24
MTU = 1420
ListenPort = 51820
### begin dave_thinkpad_1492k ###
[Peer]
PublicKey = dave_thinkpad_1492k_pub
PresharedKey = dave_thinkpad_1492k_psk
AllowedIPs = 10.242.112.2/32
### end dave_thinkpad_1492k ###
=============================================
::::  Client configuration shown below   ::::
[Interface]
PrivateKey = dave_thinkpad_1492k_priv
Address = 10.242.112.2/24
DNS = 10.242.112.1

[Peer]
PublicKey = server_pub
PresharedKey = dave_thinkpad_1492k_psk
Endpoint = REDACTED:51820
AllowedIPs = 0.0.0.0/0, ::0/0
=============================================
:::: 	Recursive list of files in	 ::::
::::	/etc/wireguard shown below	 ::::
/etc/wireguard:
configs
keys
wg0.conf

/etc/wireguard/configs:
clients.txt
dave_thinkpad_1492k.conf

/etc/wireguard/keys:
dave_thinkpad_1492k_priv
dave_thinkpad_1492k_psk
dave_thinkpad_1492k_pub
server_priv
server_pub
=============================================
::::		Self check		 ::::
:: [OK] IP forwarding is enabled
:: [OK] Iptables MASQUERADE rule set
:: [OK] Iptables INPUT rule set
:: [OK] WireGuard is running
:: [OK] WireGuard is enabled 
(it will automatically start on reboot)
:: [OK] WireGuard is listening on port 51820/udp
=============================================
:::: Having trouble connecting? Take a look at the FAQ:
:::: https://docs.pivpn.io/faq
=============================================
:::: WARNING: This script should have automatically masked sensitive       ::::
:::: information, however, still make sure that PrivateKey, PublicKey      ::::
:::: and PresharedKey are masked before reporting an issue. An example key ::::
:::: that you should NOT see in this log looks like this:                  ::::
:::: YIAoJVsdIeyvXfGGDDadHh6AxsMRymZTnnzZoAb9cxRe                          ::::
=============================================
::::		Debug complete		 ::::
::: 
::: Debug output completed above.
::: Copy saved to /tmp/debug.log
::: 
```

**Comment by 4s3ti** [comment]
Pre-archive closing, more information [here](https://github.com/pivpn/pivpn/releases/tag/v4.6.0)

**Comment by orazioedoardo** [comment]
Fixed
