### ISSUE TITLE
[General Issue]: "Handshake did not complete..."

### ISSUE THREAD

**Issue by PlatanosVerdes** [pivpn/pivpn#1827]
### In raising this issue I confirm that

- [X] I have read the [documentation](https://docs.pivpn.io)
- [X] I have read and understood the [PiVPN General Guidelines](https://github.com/pivpn/pivpn/#general-guidelines)
- [X] I have read and understood the [PiVPN Troubleshooting Guidelines](https://docs.pivpn.io/faq/#how-do-i-troubleshoot-connection-issues)
- [X] The issue I am reporting isn't a duplicate, see [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen).
- [X] I have searched for similar issues and solutions
- [X] I can replicate the issue even after a clean OS installation

### Describe the issue

I configured everything to make a VPN on my Raspberry Pi, and it was perfect. I created a few more clients and after a few days it stopped working. I haven't done anything.

But when I try to connect with my IOS mobile and look at the bugs I get "Handshake did not complete...".

I've checked everything the documentation says, but I can't find the bug.

I have seen people with the same error but not the solution.

Thanks in advance

### Expected behavior

Successful connection for my clients

### Please describe the steps to replicate the issue

- Configuration with WireGuard
- Use default port to forwarding: 51820
- Use duckdns

### Have you taken any steps towards solving your issue?

Reinstall

### Where did you run pivpn?

Raspberry Pi

### Please provide your output from `uname -a`

Linux raspberrypi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux

### Details about Operative System

PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

### Installation

curl -L https://install.pivpn.io | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  111k  100  111k    0     0   380k      0 --:--:-- --:--:-- --:--:--  380k
:::
::: sudo will be used for the install.
::: Repair option selected.
::: Hostname length OK
::: Verifying free disk space...
:::
::: Package Cache update is needed, running apt-get update -y ...
 done!
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: Your system is up to date! Continuing with PiVPN installation...
:::    Checking for git... already installed!
:::    Checking for tar... already installed!
:::    Checking for curl... already installed!
:::    Checking for grep... already installed!
:::    Checking for dnsutils... already installed!
:::    Checking for grepcidr... already installed!
:::    Checking for whiptail... already installed!
:::    Checking for net-tools... already installed!
:::    Checking for bsdmainutils... already installed!
:::    Checking for bash-completion... already installed!
:::    Checking for dhcpcd5... already installed!
:::    Checking for iptables-persistent... already installed!
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
::: PiVPN Automated Installer
::: This installer will transform your Raspbian host into an OpenVPN or WireGuard server!
::: Initiating network interface
::: Enable forced IPv6 route with no IPv6 uplink on server.
::: Using interface: eth0 for IPv4
::: Your static IPv4 address:    192.168.0.250/24
::: Your static IPv4 gateway:    192.168.0.1
::: Using DHCPCD
::: Static IP already configured.
::: raspi will hold your VPN client configuration files.
:::
::: Checking for existing base files...
:::    Checking /usr/local/src/pivpn is a repo... OK!
::: Repairing an existing installation, not downloading/updating local repos
::: WireGuard will be installed
::: Installing WireGuard from Raspbian package...
:::    Checking for wireguard-tools... already installed!
:::    Checking for qrencode... already installed!
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
::: Using port 51820
::: Using DNS 8.8.8.8 8.8.4.4
[2024-03-24T12:56:08+0100]: dig failed, now trying to curl checkip.amazonaws.com
::: Using domain name PRIVATENAME.duckdns.org
::: Backing up the wireguard folder to /etc/wireguard_2024-03-24-125609.tar.gz
::: The Server Keys will now be generated.
::: Server Keys have been generated.
::: Server config generated.
::: Install Complete...
::: Restarting services...
::: Enabling unattended upgrades
:::    Checking for unattended-upgrades... already installed!
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
::: Setupfiles copied to /etc/pivpn/wireguard/setupVars.conf
::: Installing scripts to /opt/pivpn...
 done.
::: Flushing writes to disk...
::: done.
::: Installation Complete!
::: Now run 'pivpn add' to create the client profiles.
::: Run 'pivpn help' to see what else you can do!

::: If you run into any issue, please read all our documentation carefully.
::: All incomplete posts or bug reports will be ignored or deleted.

::: Thank you for using PiVPN.
::: It is strongly recommended you reboot after installation.
:::

### Profile / Client creation

pivpn add -n platano
::: Client Keys generated
::: Client config generated
::: Updated server config
::: WireGuard reloaded

### Debug output

pivpn -d
::: Generating Debug Output
::::            PiVPN debug              ::::
=============================================
::::            Latest commit            ::::
Branch: master
Commit: 20d3a4ccd4f2d080d6f9a13a74e6369aa9d54476
Author: Orazio
Date: Mon Jan 29 08:53:41 2024 +0100
Summary: fix(install): don't treat http errors as unavailable ipv6
=============================================
::::        Installation settings        ::::
PLAT=Raspbian
OSCN=bullseye
USING_UFW=0
pivpnforceipv6route=1
IPv4dev=eth0
dhcpReserv=
IPv4addr=192.168.0.250/24
IPv4gw=192.168.0.1
install_user=raspi
install_home=/home/raspi
VPN=wireguard
pivpnPORT=51820
pivpnDNS1=8.8.8.8
pivpnDNS2=8.8.4.4
pivpnHOST=REDACTED
INPUT_CHAIN_EDITED=1
FORWARD_CHAIN_EDITED=1
INPUT_CHAIN_EDITEDv6=
FORWARD_CHAIN_EDITEDv6=
pivpnPROTO=udp
pivpnMTU=1420
pivpnDEV=wg0
pivpnNET=10.185.254.0
subnetClass=24
pivpnenableipv6=0
ALLOWED_IPS="0.0.0.0/0, ::0/0"
UNATTUPG=1
INSTALLED_PACKAGES=(wireguard-tools)
=============================================
::::  Server configuration shown below   ::::
[Interface]
PrivateKey = server_priv
Address = 10.185.254.1/24
MTU = 1420
ListenPort = 51820
### begin platano ###
[Peer]
PublicKey = platano_pub
PresharedKey = platano_psk
AllowedIPs = 10.185.254.2/32
### end platano ###
=============================================
::::  Client configuration shown below   ::::
[Interface]
PrivateKey = platano_priv
Address = 10.185.254.2/24
DNS = 8.8.8.8, 8.8.4.4

[Peer]
PublicKey = server_pub
PresharedKey = platano_psk
Endpoint = REDACTED:51820
AllowedIPs = 0.0.0.0/0, ::0/0
=============================================
::::    Recursive list of files in       ::::
::::    /etc/wireguard shown below       ::::
/etc/wireguard:
configs
keys
wg0.conf

/etc/wireguard/configs:
clients.txt
platano.conf

/etc/wireguard/keys:
platano_priv
platano_psk
platano_pub
server_priv
server_pub
=============================================
::::            Self check               ::::
:: [OK] IP forwarding is enabled
:: [OK] Iptables MASQUERADE rule set
:: [OK] Iptables INPUT rule set
:: [OK] Iptables FORWARD rule set
:: [OK] WireGuard is running
:: [OK] WireGuard is enabled
(it will automatically start on reboot)
:: [OK] WireGuard is listening on port 51820/udp
=============================================
:::: Having trouble connecting? Take a look at the FAQ:
:::: https://docs.pivpn.io/faq
=============================================
:::: WARNING: This script should have automatically masked sensitive       ::::
:::: information, however, still make sure that PrivateKey, PublicKey      ::::
:::: and PresharedKey are masked before reporting an issue. An example key ::::
:::: that you should NOT see in this log looks like this:                  ::::
:::: YIAoJVsdIeyvXfGGDDadHh6AxsMRymZTnnzZoAb9cxRe                          ::::
=============================================
::::            Debug complete           ::::
:::
::: Debug output completed above.
::: Copy saved to /tmp/debug.log
:::

**Comment by 4s3ti** [comment]
Pre-archive closing, more information [here](https://github.com/pivpn/pivpn/releases/tag/v4.6.0)
