### ISSUE TITLE
curl redirect (was: PiVPN on UBUNTU)

### ISSUE THREAD

**Issue by siamak06** [pivpn/pivpn#183]
Hi All,

I have used the PiVPN and worked like magic, no problem there at all.
There is no issue at all just a wish or request: Would it be possible that PiVPN work on UBUNTU?

Cheers

Siamak

**Comment by redfast00** [comment]
It should already work on Ubuntu. If you have any issues, please reply.

**Comment by siamak06** [comment]
Hi
Thanks for the reply, I tried it:
1. curl needs installing was difficult to install but one has to do :
a. sudo apt-get update
b. sudo apr-get install curl
when I type the following, as I did on Raspberry Pi

curl -L https://install.pivpn.io | bash 

I get these lines:
bash: line 1: html: no such file or directory
bash: line 2: syntax error near unexpected token '<'
bash: line 2: <head><title>301 Moved Permanently</title></head>

Any suggestions why 

Siamak

P.S. The ubuntu file structure must be different from Jessy, I would be surprised if it worked without modifications.

**Comment by redfast00** [comment]
Bash gets the redirect as input instead of the script. Can you try replaci

**Comment by siamak06** [comment]
Hi its me again,

I got it working, don't ask me how but it did and it is working ABSOLUTELY FINE, it asked me all the questions that it did for Raspberry Pi and boom it worked.

**Comment by redfast00** [comment]
Was it the `-L`?

**Comment by siamak06** [comment]
What I did was is this:

Yes the -L did not work.

Could not get putty working, I had to install openSSH from the so called software place, got that, nothing up to now would work out of the Terminal i.e alt ctl T brings up a terminal but nothing works on that.

I got putty working form there every thing went smoothly and worked perfectly like as if it was working on the RasPi.

So many thanks to those created this Script for RasPi "PiVPN" that is also working with UBUNTU.
Cheers
Siamak

**Comment by siamak06** [comment]
Hi Everyone,
I tried again to install PiVPN on another RasPI 3 and there is no way would it work, is there a problem with it.
I don't understand at all, one day it is fantastically working the next zilch, Nada, diddly squat.
Is there a manual way of doing this, I have the zip file, can any body guide me how and where I copy the files to please?

Thanks
Siamak

**Comment by redfast00** [comment]
Can you please give me the exact  output?  You can always install OpenVPN manually, but we don't support that.

**Comment by siamak06** [comment]
Good afternoon,

Thanks for the reply, I am trying just now and it is working fine, I just don't understand why it was not working yesterday and why it is working today.

I am using the same as indicated on the site i.e. : curl -L https://install.pivpn.io | bash
working fine no problem at all, any idea WHY?

I have another question; if I want o take the RasPi somewhere else is there any command that I can use to modify the parameters to suit the new Router/area, or I have to install it from scratch?

Thanks again I will report any issues should there be any.

Siamak

**Comment by redfast00** [comment]
It will probably be the easiest to just reinstall. Moving the server isn't exactly a usecase we expect to have, so if you don't want to reinstall, you'll have to edit the iptables and the static address yourself.

**Comment by siamak06** [comment]
Thanks for taking the time and answering,

I have, if I may another question, would it be possible to just install the PiVPN using the install.sh locally at all, why does it have to have access the github of some sort?

If it is possible to run the install locally what would the command be?

I have downloaded the zip file and have all the files on my PC, please advise.

I have finished the installation for second OpenVPN server this time I used TCP protocol and it seems working fine, I may have 2 RasPi running at the same time as a VPN servers one UDP protocol the other TCP.

Cheers and many thanks again for the effort of making such powerful and easy to use installation.

Siamak

**Comment by 0-kaladin** [comment]
Just fyi github did have a large outage yesterday.

**Comment by siamak06** [comment]
Ahhh, nevertheless it would be a good idea to be able to install locally, don't you think?

I suppose one needs to change the ownership of the Install.sh to the root and make it executable and theoretically should run?

Cheers

Siamak

**Comment by redfast00** [comment]
It will run, but it might still need to connect to the Internet after that.

**Comment by siamak06** [comment]
Thanks again, no worries, it will be connected to the Internet from the start any way, I will have to install OpenVPN, update and upgrade  for the PiVPN installation work.

Cheers, and would you advise how to make a Client router out of the RasPi please, there are many tutorials out there but there are not that clear, to me at least.

Siamak

**Comment by siamak06** [comment]
Hello every one,
The VPN Server is up and running with NO PROBLEM at all.

I have a question; is it possible to configure the VPN Server without having a FIXED Public IP address, if yes would you please advise.

Cheers
Siamak

**Comment by redfast00** [comment]
Yes, you can use a service like dyndns or noip to have a subdomain pointing to your changing IP.

**Comment by siamak06** [comment]
Excellent thanks, now would you please let me know how to have Static IP on my Laptop UBUNTU running the VPN server please.
I know I have to modify the Interfaces but I don't know where to look.
Cheers
Siamak

**Comment by siamak06** [comment]
Hi alll,

No worries, I have done it on the Router level.

Thanks

Siamak

**Comment by siamak06** [comment]
Hi Everyone,

It me again, I know, don't want to be a pain but I have a question:

I have downloaded the PiVPN zip file and have unzipped it to a folder on my laptop, if I want to run it on a Raspberry Pi as a stand alone program where in Raspberry Pi should I copy the program and its dependencies Please.

I appreciate a breve guide on this please, I am semi novice on all this so please go a bit slowly.

Cheers

Siamak

**Comment by siamak06** [comment]
Hi Guys,

I am a bit stock, Thanks to you guys I have set-up my OpenVPN Server and it is working fine using my windoze.

Would you please guide me in how to make connection to my server using Raspberry Pi.

As you may have noticed I am an absolute novice in all that.

Thanks.
Siamak

**Comment by siamak06** [comment]
Hi Guys,

After many research I finally managed to get this message from my PI:

sudo openvpn --config /etc/openvpn/siamak.conf
Wed Mar  1 11:48:20 2017 OpenVPN 2.3.4 arm-unknown-linux-gnueabihf [SSL (OpenSSL                                )] [LZO] [EPOLL] [PKCS11] [MH] [IPv6] built on Jan 23 2016
Wed Mar  1 11:48:20 2017 library versions: OpenSSL 1.0.1t  3 May 2016, LZO 2.08
Enter Private Key Password: **********
Wed Mar  1 11:48:26 2017 WARNING: this configuration may cache passwords in memo                                ry -- use the auth-nocache option to prevent this
Wed Mar  1 11:48:26 2017 Control Channel Authentication: tls-auth using INLINE s                                tatic key file
Wed Mar  1 11:48:26 2017 Attempting to establish TCP connection with [AF_INET]82                                .234.134.109:443 [nonblock]
Wed Mar  1 11:48:27 2017 TCP connection established with [AF_INET]xx.xxx.xxx.xxx                                :443
Wed Mar  1 11:48:27 2017 TCPv4_CLIENT link local: [undef]
Wed Mar  1 11:48:27 2017 TCPv4_CLIENT link remote: [AF_INET]xxx.xxx.xxx.xxx:443
Wed Mar  1 11:48:28 2017 [server] Peer Connection Initiated with [AF_INET]xxx.xxx                                .xxx.xxx:443
Wed Mar  1 11:48:30 2017 TUN/TAP device tun0 opened
Wed Mar  1 11:48:30 2017 do_ifconfig, tt->ipv6=0, tt->did_ifconfig_ipv6_setup=0
Wed Mar  1 11:48:30 2017 /sbin/ip link set dev tun0 up mtu 1500
Wed Mar  1 11:48:30 2017 /sbin/ip addr add dev tun0 10.8.0.2/24 broadcast 10.8.0                                .255
RTNETLINK answers: File exists
Wed Mar  1 11:48:30 2017 ERROR: Linux route add command failed: external program                                 exited with error status: 2

Any suggestions?

Cheers
Siamak

**Comment by siamak06** [comment]
Hi Everyone,

I actually found the solution foe me, here is the solution and it worked:

sudo openvpn --config /etc/openvpn/Client.ovpn replace the Client.ovpn with the one you have created.

It will prompt you to type in the password and that's it.

Cheers

Siamak

**Comment by siamak06** [comment]
Hi Every one,

I would really like to thank the author or authors of this beautiful peace of software.

I have been installing it for friends and they LOVE it.

I nevertheless have a question, can this program run totally independently without any link to any site at all just in case if the site hosting it disappears? I know it is very much unlikely but you never know it may happen.

I did look in to the Script and it does have a link to the Github. 

I would appreciate an answer please

**Comment by 0-kaladin** [comment]
You can always download from github the repo. But you'll still need Internet for the dependencies.

**Comment by siamak06** [comment]
Thanks for the answer, appreciate it.

It would have been absolutely fantastic if the program would run without Internet First, of course one needs the Internet, without it, it will defy the whole purpose of making the VPN Server in the first place wouldn't it. 

Any way I go with this and congratulations for this beautiful software.

Cheers

Siamak

**Comment by siamak06** [comment]
Hi All,

As I have mentioned above I have set-up VPN Server with this powerful peace of work and very happy with it.

I have 2 VPN Servers one in France using Laptop running UBUNTU  the other here in England using RasPi 3 running Jessy, both TCP/IP.

I am in England at the moment and when I try to connect to either of the VPN Servers the WiFi level triangle indicates "Unidentified network, No Internet access", any idea why it says that?

Is there any way to have a name for or make it as such that it would be identified at all? Sometimes it would not connect although I have an IP address and the VPN Server says it is connected successfully.

Will appreciate some hints on this please.

Cheers

Siamak
