### ISSUE TITLE
[General Issue]: no packets reaching rasp5 pivpn wireguard

### ISSUE THREAD

**Issue by 1980Yo** [pivpn/pivpn#1838]
### In raising this issue I confirm that

- [X] I have read the [documentation](https://docs.pivpn.io)
- [X] I have read and understood the [PiVPN General Guidelines](https://github.com/pivpn/pivpn/#general-guidelines)
- [X] I have read and understood the [PiVPN Troubleshooting Guidelines](https://docs.pivpn.io/faq/#how-do-i-troubleshoot-connection-issues)
- [X] The issue I am reporting isn't a duplicate, see [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen).
- [X] I have searched for similar issues and solutions
- [X] I can replicate the issue even after a clean OS installation

### Describe the issue

Hi everyone. 
I've been using wireguard vpn for a month or two with no problems at all. Today, I wanted to connect to my server at home and there's no traffic so I tried the steps described here: https://docs.pivpn.io/faq/

### Expected behavior

I cannot get internet access after connecting to my server using Wireguard

### Please describe the steps to replicate the issue

1. Installed Wireguard some months ago with duckdns.org DDNS following instructions and have been running it with no issues whatsover. 
2. Wanted to connect today (via iPhone, via iPad, via PC) with no luck.
3. Tried to solve the problem following instructions found in docs.pivpn.io/faq:
          - $ pivpn -d: selfcheck everything checked out "ok"
          - $ sudo systemctl restart wg-quick@wg0
          - $ lsmod | grep wireguard: 
                           wireguard             114688  0
                           libchacha20poly1305    49152  1 wireguard
                           ip6_udp_tunnel         49152  1 wireguard
                           udp_tunnel             49152  1 wireguard
                           libcurve25519_generic    65536  1 wireguard
                           ipv6                  589824  60 wireguard
          - cat /etc/pivpn/wireguard/setupVars.conf
                           IPv4dev=eth0
                           IPv4addr=192.168.1.109/24
                           IPv4gw=192.168.1.1
                           pivpnPORT=51220
                           pivpnHOST=REDACTED
                           pivpnPROTO=udp
          - ip address matches ("dig REDACTED +short" & "curl -s https://checkip.amazonaws.com" commands used)
         

### Have you taken any steps towards solving your issue?

1. sudo -s
2. apt install tcpdump -y
3. used Termius from iPhone from outside the net: Run tcpdump -n -i IPv4dev pivpnPROTO port pivpnPORT (it will block the terminal but don't worry)
Try to connect from your device
Shortly after you should see some packets being exchanged between your Raspberry Pi and your device

### Screenshots

![Captura 2024-05-26 a las 18 05 21](https://github.com/pivpn/pivpn/assets/162378717/d635932c-2cb6-43c5-aa49-a90fead7f617)

### Where did you run pivpn?

Raspberry pi 5

### Please provide your output from `uname -a`

Linux palo 6.6.28+rpt-rpi-2712 #1 SMP PREEMPT Debian 1:6.6.28-1+rpt1 (2024-04-22) aarch64 GNU/Linux

### Details about Operative System

PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

### Installation

![Captura de pantalla 2024-05-26 183617](https://github.com/pivpn/pivpn/assets/162378717/5e0e8ccc-029c-419b-b806-efe3ec0646b9)

### Debug output

 Self check               ::::
:: [OK] IP forwarding is enabled
:: [OK] Iptables MASQUERADE rule set
:: [OK] Iptables INPUT rule set
:: [OK] WireGuard is running
:: [OK] WireGuard is enabled 
(it will automatically start on reboot)
:: [OK] WireGuard is listening on port 51220/udp

**Comment by 1980Yo** [comment]
Well, I'm really new to this, so I created new clients because the clients I had somehow disappeared. 
Nonetheless, when I "sudo nano /etc/pivpn/hosts.wireguard" the previous clients are listed there as well as they are listed in the configs ls.
But, if you look at it, the address are duplicated: (Burri_cris & cris_iphone are .2 and so on). 
Can any one tell me how it is possible that the clients dissappeared? Is there anyway I can make the previous tunnels work?
Thanks
![Captura de pantalla 2024-05-26 224810](https://github.com/pivpn/pivpn/assets/162378717/5bae3098-0c45-4ff0-9d7f-f9e643db16b5)
![Captura de pantalla 2024-05-26 224727](https://github.com/pivpn/pivpn/assets/162378717/3ddbc6c3-6b8b-4071-adb8-5eb7fc6e7371)

**Comment by orazioedoardo** [comment]
I've redacted the endpoint address in the issue text.

> I've been using wireguard vpn for a month or two with no problems at all. Today, I wanted to connect to my server at home and there's no traffic so I tried the steps described here: https://docs.pivpn.io/faq/

If you made no change to port forwarding one your router you may have been moved to CGNAT.

**Comment by 1980Yo** [comment]
No, I checked. Sorry, I didn’t say so.
Thanks

**Comment by 1980Yo** [comment]
Eventhough in "canyouseeme.org" I received the message "Error: I could not see your service on 88.5.33.168 on port (12354)
Reason: Connection refused", in the rasp I got this:

![image](https://github.com/pivpn/pivpn/assets/162378717/ef7491e3-84ed-447b-8690-6a0840a19ee7)

So I think, it worked.

**Comment by orazioedoardo** [comment]
Yeah it worked. Is there a change your clients you are trying to use are referencing the wrong IP/DDNS in endpoint? Recommend also reinstalling to remove that clutter.

**Comment by 1980Yo** [comment]
No, I don’t think so. The configuration is ok! I’ll reinstall it.
Thanks for your time!

**Comment by orazioedoardo** [comment]
@1980Yo Can you check whether the installer now works for you?

**Comment by 1980Yo** [comment]
I reinstalled it from scratch and not realizing (sorry, I’m really really quite new at this) that I could backup the clients I created new ones (fortunately it’s for us at home to use so I didn’t have many clients created).
Thanks for your time. Nonetheless,
