### ISSUE TITLE
[Connection Issue]: Unable to load websites from Phone through PiVPN

### ISSUE THREAD

**Issue by dboisvert** [pivpn/pivpn#1841]
### In raising this issue I confirm that

- [X] I have read the [documentation](https://docs.pivpn.io)
- [X] I have read and understood the [PiVPN General Guidelines](https://github.com/pivpn/pivpn/#general-guidelines)
- [X] I have read and understood the [PiVPN Troubleshooting Guidelines](https://docs.pivpn.io/faq/#how-do-i-troubleshoot-connection-issues)
- [X] The issue I am reporting isn't a duplicate, see [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen).
- [X] I have searched for similar issues and solutions
- [X] I can replicate the issue even after a clean OS installation

### Describe the issue

Attempt to enable Wireguard and browse the web through the android phone app. (I also ensured that I was on mobile and not on the same network as the PiHole + PiVPN)
Internet pages on the phone do not load

### Expected behavior

I should be able to browse the internet with WireGuard enabled.

### Please describe the steps to replicate the issue

1. PiHole Setup
2. PiVPN Setup
- Made sure to check that the VPN will use the PiHole DNS server for all clients
- The PiHole setting to allow clients from all adapters is set
3. Port forwarding on the router is setup to forward port 51820 to the pihole
4. The pihole IP Address is reserved as 192.168.4.254
5. Setup Wireguard Phone App (Android) by scanning the QR Code

Attempt to enable Wireguard and browse the web through the phone app. (I also ensured that I was on mobile and not on the same network as the PiHole + PiVPN)
Internet pages on the phone do not load

### Have you taken any steps towards solving your issue?

I ran through the troubleshooting steps on the webpage.

The  output of `pivpn -d` was as follows: 
[pivpnd_output.txt](https://github.com/user-attachments/files/15571285/pivpnd_output.txt)

The output after running:
`sudo systemctl restart wg-quick@wg0`
`lsmod | grep wireguard`
[grep wireguard.txt](https://github.com/user-attachments/files/15571291/grep.wireguard.txt)

`cat /etc/pivpn/wireguard/setupVars.conf`
[cat.txt](https://github.com/user-attachments/files/15571294/cat.txt)

` ip -f inet address show enxb827eb06c4ac`
[ip.txt](https://github.com/user-attachments/files/15571299/ip.txt)

I can confirm that the command `curl -s https://checkip.amazonaws.com` matches the pivpnHOST variable, but am omitting it for privacy.

The packet capture from tcpdump
[tcpdump.txt](https://github.com/user-attachments/files/15571304/tcpdump.txt)

In addition I am able to ping the phones IP Address from the pihole.

### Where did you run pivpn?

I ran this on a Raspberry PI 2 B

### Please provide your output from `uname -a`

Linux pihole 6.6.20+rpt-rpi-v7 #1 SMP Raspbian 1:6.6.20-1+rpt1 (2024-03-07) armv7l GNU/Linux

### Details about Operative System

PRETTY_NAME="Raspbian GNU/Linux 12 (bookworm)"
NAME="Raspbian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

### Debug output

This information is included in the above as well.
[pivpnd_output.txt](https://github.com/user-attachments/files/15571315/pivpnd_output.txt)

**Comment by orazioedoardo** [comment]
Do DNS requests from VPN clients show in the Pi-hole dashboard / logs?

**Comment by dboisvert** [comment]
> Do DNS requests from VPN clients show in the Pi-hole dashboard / logs?

Yes, I see the DNS requests in the PiHole Query log. They show up as DansPhone.pivpn

**Comment by dboisvert** [comment]
I was also able to confirm that when WireGuard is enabled on the phone I can ping the DNS server.

I also was able to confirm that with WireGuard enabled on the phone I CANNOT ping google.com or 8.8.8.8

**Comment by dboisvert** [comment]
I resolved this by uninstalling PiVPN and manually installing wire guard. Everything works as expected now.

I followed the wire guard guide on the pihole site
