### ISSUE TITLE
Cant Connect to internet 

### ISSUE THREAD

**Issue by pAbhi001** [pivpn/pivpn#1848]
### In raising this issue I confirm that

- [X] I have read the [documentation](https://docs.pivpn.io)
- [X] I have read and understood the [PiVPN General Guidelines](https://github.com/pivpn/pivpn/#general-guidelines)
- [X] I have read and understood the [PiVPN Troubleshooting Guidelines](https://docs.pivpn.io/faq/#how-do-i-troubleshoot-connection-issues)
- [X] The issue I am reporting isn't a duplicate, see [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen).
- [X] I have searched for similar issues and solutions
- [X] I can replicate the issue even after a clean OS installation

### Describe the issue

Hello, I'm new to IT and software.
I have PI 4 2gb, running on PI-OS lite. 
I have set OMV on my PI and that is working fine. In addition to that to access my file remotely i am trying to install PIVpn wg.
After installation and boot up im seeing this Error 

![Cmd 2](https://github.com/user-attachments/assets/8b8b3f0f-fdf7-425c-a304-3e9a12fe5176)

### Expected behavior

since i dont know much about port forwading and ip , piv6 
It would be beneficial for me to get it done   

Im also new to GITHUB, so please bear with me for proper contain 

### Please describe the steps to replicate the issue

failing to load wire-gaurd vpn 

### Have you taken any steps towards solving your issue?

Tried installing PIVpn multiple times,

### Screenshots

![wwg quick ](https://github.com/user-attachments/assets/393d1e9c-d08c-4087-b533-46283f8c6b8d)
![port forwadidng 2](https://github.com/user-attachments/assets/3f983056-2742-4b17-9b34-74ccc8008793)
![DHCP reservation](https://github.com/user-attachments/assets/1b830c98-739f-407a-8e28-2a784a4814e2)
![setup 1](https://github.com/user-attachments/assets/611f51e7-6ac7-49ad-8346-89ae790f176b)
![setup 2](https://github.com/user-attachments/assets/d2b1da67-813f-489b-a42b-c1ea5c862ace)
![setup 3](https://github.com/user-attachments/assets/e74bc3c2-ac02-4816-8f4b-b2b986537c36)
![setup 4](https://github.com/user-attachments/assets/a7328a0a-f44a-4e27-83df-a2f2d7f56b58)
![cmd 1](https://github.com/user-attachments/assets/de133d32-3c52-447c-91a7-b64fc97c4b57)
![common Service](https://github.com/user-attachments/assets/ab2c90e8-6bd0-4684-8547-54fa1de17b10)
![port forwarding](https://github.com/user-attachments/assets/11a24348-c456-46d1-b60a-9317fa5f2fea)
![ipv6 1](https://github.com/user-attachments/assets/5ccaef36-b835-4c5f-8f3a-6792d820d551)
![ipv6 2](https://github.com/user-attachments/assets/d5869709-7492-40e2-aaa9-73fda800ce3c)
![ipv6 3](https://github.com/user-attachments/assets/a46ab363-319e-4f5b-920d-1eab9917b09b)
![wgo service ](https://github.com/user-attachments/assets/a6415d4c-86fd-4a08-a7ee-d8bca454404f)

### Where did you run pivpn?

Raspberry PI 4 on Lite OS running with OMV 

### Please provide your output from `uname -a`

Abhishek@AbhiPI4:/$ pivpn add
/etc/pivpn/wireguard/setupVars.conf: line 10: syntax error near unexpected token `('
/etc/pivpn/wireguard/setupVars.conf: line 10: `install_home=/srv/dev-disk-by-uuid-86A3-1677/New folder (3)/Abhishek'
/opt/pivpn/ipaddr_utils.sh: line 23: 2 ** 32 - 1 ^ (2 ** (32 - ) - 1): syntax error: operand expected (error token is ") - 1)")
/opt/pivpn/ipaddr_utils.sh: line 30: 2 ** (32 - ) - 1: syntax error: operand expected (error token is ") - 1")
Enter a Name for the Client: piabhi
::: Client Keys generated
/opt/pivpn/ipaddr_utils.sh: line 5: ( & 4278190080) >> 24: syntax error: operand expected (error token is "& 4278190080) >> 24")
::: Client config generated
::: Updated server config
Job for wg-quick@wg0.service failed.
See "systemctl status wg-quick@wg0.service" and "journalctl -xeu wg-quick@wg0.service" for details.
[2024-07-28T12:53:04+0530]: ::: Failed to reload WireGuard

### Details about Operative System

Abhishek@AbhiPI4:/$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Comment by orazioedoardo** [comment]
First off I think there is some issue with the home directory having a space in it. Second there is another issue with generating the VPN ip address. Can you provide the output of `pivpn -d`? (paste the text, don't make a screenshot).

**Comment by pAbhi001** [comment]
Here it is 

Abhishek@AbhiPI4:/$ pivpn -d
::: Generating Debug Output
::::            PiVPN debug              ::::
=============================================
::::            Latest commit            ::::
Branch: /etc/pivpn/wireguard/setupVars.conf: line 10: syntax error near unexpected token `('
/etc/pivpn/wireguard/setupVars.conf: line 10: `install_home=/srv/dev-disk-by-uuid-86A3-1677/New folder (3)/Abhishek'
master
Commit: 55ed0cb3a569237843c74ff888f453772f037e05
Author: Xavier L
Date: Tue Jun 4 11:45:37 2024 -0400
Summary: feat(install): add support for wireguard in containers
=============================================
::::        Installation settings        ::::
sed: -e expression #1, char 0: no previous regular expression
=============================================
::::  Server configuration shown below   ::::
[Interface]
PrivateKey = server_priv
Address = 10.7.27.1/24
MTU = 1420
ListenPort = 51820
=============================================
::::  Client configuration shown below   ::::
::: There are no clients yet
=============================================
::::    Recursive list of files in       ::::
::::    /etc/wireguard shown below       ::::
/etc/wireguard:
configs
keys
wg0.conf

/etc/wireguard/configs:
clients.txt

/etc/wireguard/keys:
server_priv
server_pub
=============================================
::::            Self check               ::::
[2024-07-30T22:16:22+0530]: ::: Missing setup vars file!
=============================================
:::: Having trouble connecting? Take a look at the FAQ:
:::: https://docs.pivpn.io/faq
=============================================
:::: WARNING: This script should have automatically masked sensitive       ::::
:::: information, however, still make sure that PrivateKey, PublicKey      ::::
:::: and PresharedKey are masked before reporting an issue. An example key ::::
:::: that you should NOT see in this log looks like this:                  ::::
:::: YIAoJVsdIeyvXfGGDDadHh6AxsMRymZTnnzZoAb9cxRe                          ::::
=============================================
::::            Debug complete           ::::
:::
::: Debug output completed above.
::: Copy saved to /tmp/debug.log

**Comment by orazioedoardo** [comment]
Yeah that's quite broken. If you don't mind, in the meantime, try to uninstall then reinstall with a user that has no spaces in their home folder.

**Comment by pAbhi001** [comment]
I tried to install it into new directory
still same result
here is the cmd 

PS C:\Users\Abhishek> ssh Abhishek@192.xxx.x.xxx
Abhishek@192.xxx.x.xxx's password:
Linux AbhiPI4 6.6.31+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.31-1+rpt1 (2024-05-29) aarch64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Wed Jul 31 22:00:50 2024 from 192.xxx.x.xxx
Could not chdir to home directory /srv/dev-disk-by-uuid-86A3-1677/New folder (3)/Abhishek: No such file or directory
Abhishek@AbhiPI4:/$ pwd
/
Abhishek@AbhiPI4:/$ ls
Abhi123  configs  export  lost+found  opt          proc  sbin  tmp
bin      dev      home    media       pivpnbackup  root  srv   usr
boot     etc      lib     mnt         portainer    run   sys   var
Abhishek@AbhiPI4:/$ cd Abhi123
Abhishek@AbhiPI4:/Abhi123$ curl -L https://install.pivpn.io | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  117k  100  117k    0     0   190k      0 --:--:-- --:--:-- --:--:--  190k
:::
::: sudo will be used for the install.
::: Hostname length OK
::: Verifying free disk space...
:::
::: Package Cache update is needed, running apt-get update -y ...
 done!
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: Your system is up to date! Continuing with PiVPN installation...
:::    Checking for git... already installed!
:::    Checking for tar... already installed!
:::    Checking for curl... already installed!
:::    Checking for grep... already installed!
:::    Checking for dnsutils... already installed!
:::    Checking for grepcidr... already installed!
:::    Checking for whiptail... already installed!
:::    Checking for net-tools... already installed!
:::    Checking for bsdmainutils... already installed!
:::    Checking for bash-completion... already installed!
:::    Checking for iptables-persistent... already installed!
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
::: IPv6 test connections to google.com have failed. Disabling IPv6 support. (The curl test failed with code: 7)
::: Using User: Abhishek
:::
::: Checking for existing base files...
:::    Checking /usr/local/src/pivpn is a repo... not found!
:::    Cloning https://github.com/pivpn/pivpn.git into /usr/local/src/pivpn ... done!
::: Using VPN: WireGuard
::: Generating random subnet in network 10.0.0.0/8...
::: Installing WireGuard from Debian package...
:::    Checking for wireguard-tools... already installed!
:::    Checking for qrencode... already installed!
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
::: Using OpenDNS servers.
::: Backing up the wireguard folder to /etc/wireguard_2024-07-31-220604.tar.gz
::: Server Keys have been generated.
::: Server config generated.
::: Install Complete...
::: Restarting services...
:::    Checking for unattended-upgrades... already installed!
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
::: Setupfiles copied to /etc/pivpn/wireguard/setupVars.conf
::: Installing scripts to /opt/pivpn...
 done.
::: Flushing writes to disk...
::: done.

Rebooting system 


AFTER REBOOT 

Abhishek@AbhiPI4:/$ pivpn add
/etc/pivpn/wireguard/setupVars.conf: line 10: syntax error near unexpected token `('
/etc/pivpn/wireguard/setupVars.conf: line 10: `install_home=/srv/dev-disk-by-uuid-86A3-1677/New folder (3)/Abhishek'
/opt/pivpn/ipaddr_utils.sh: line 23: 2 ** 32 - 1 ^ (2 ** (32 - ) - 1): syntax error: operand expected (error token is ") - 1)")
/opt/pivpn/ipaddr_utils.sh: line 30: 2 ** (32 - ) - 1: syntax error: operand expected (error token is ") - 1")
Enter a Name for the Client: abhi
::: Client Keys generated
/opt/pivpn/ipaddr_utils.sh: line 5: ( & 4278190080) >> 24: syntax error: operand expected (error token is "& 4278190080) >> 24")
::: Client config generated
::: Updated server config
Job for wg-quick@wg0.service failed.
See "systemctl status wg-quick@wg0.service" and "journalctl -xeu wg-quick@wg0.service" for details.
[2024-07-31T22:11:45+0530]: ::: Failed to reload WireGuard
======================================================================
::: Done! abhi.conf successfully created!
::: abhi.conf was copied to /configs for easytransfer.
::: Please use this profile only on one device and create additional
::: profiles for other devices. You can also use pivpn -qr
::: to generate a QR Code you can scan with the mobile app.
======================================================================

**Comment by orazioedoardo** [comment]
It’s the same issue, your home folder has spaces in it: `/srv/dev-disk-by-uuid-86A3-1677/New folder (3)/Abhishek `

**Comment by pAbhi001** [comment]
Is there any option to save that into particular folder.
Or anything to solve issue.

**Comment by orazioedoardo** [comment]
Yes, what I said above. Reinstall but select or create first a user with an home folder without spaces, example: `/home/pabhi001`

**Comment by pAbhi001** [comment]
**Update** 
I have created new user and reinstalled it.
Cant access to internet or local network connnected to vpn 

**Here is output of pivpn add**

Abhishek@AbhiPI4:/$ pivpn add
mkdir: cannot create directory ‘/home/AbhiVPN/configs’: No such file or directory
chown: cannot access '/home/AbhiVPN/configs': No such file or directory
chmod: cannot access '/home/AbhiVPN/configs': No such file or directory
Enter a Name for the Client: Abhi
::: Client Keys generated
::: Client config generated
::: Updated server config
::: WireGuard reloaded
cp: cannot create regular file '/home/AbhiVPN/configs/Abhi.conf': No such file or directory
chown: cannot access '/home/AbhiVPN/configs/Abhi.conf': No such file or directory
chmod: cannot access '/home/AbhiVPN/configs/Abhi.conf': No such file or directory
======================================================================
::: Done! Abhi.conf successfully created!
::: Abhi.conf was copied to /home/AbhiVPN/configs for easytransfer.
::: Please use this profile only on one device and create additional
::: profiles for other devices. You can also use pivpn -qr
::: to generate a QR Code you can scan with the mobile app.
======================================================================
Abhishek@AbhiPI4:/$ pivpn -qr
::  Client list  ::
1) Abhi
Please enter the Index/Name of the Client to show: 1
::: Showing client Abhi below
        QR CODE 

 **Output of pivpn -d**

Abhishek@AbhiPI4:/$ pivpn -d
::: Generating Debug Output
::::            PiVPN debug              ::::
=============================================
::::            Latest commit            ::::
Branch: master
Commit: 4e4d608b35255680eb1545bfb5555c5b74411b31
Author: wlmchen
Date: Sun Jul 28 17:29:36 2024 -0700
Summary: Fix Alpine persistence
=============================================
::::        Installation settings        ::::
PLAT=Debian
OSCN=bookworm
USING_UFW=0
pivpnforceipv6route=1
IPv4dev=end0
dhcpReserv=1
IPv4addr=192.16x.x.xxx/24
IPv4gw=192.16x.x.xxx
install_user=AbhiVPN
install_home=/home/AbhiVPN
VPN=wireguard
pivpnPORT=51820
pivpnDNS1=8.8.8.8
pivpnDNS2=8.8.4.4
pivpnHOST=REDACTED
INPUT_CHAIN_EDITED=0
FORWARD_CHAIN_EDITED=1
INPUT_CHAIN_EDITEDv6=
FORWARD_CHAIN_EDITEDv6=
pivpnPROTO=udp
pivpnMTU=1420
pivpnDEV=wg0
pivpnNET=10.55.22.0
subnetClass=24
pivpnenableipv6=0
ALLOWED_IPS="0.0.0.0/0, ::0/0"
UNATTUPG=1
INSTALLED_PACKAGES=()
=============================================
::::  Server configuration shown below   ::::
[Interface]
PrivateKey = server_priv
Address = 10.55.22.1/24
MTU = 1420
ListenPort = 51820
### begin Abhi ###
[Peer]
PublicKey = Abhi_pub
PresharedKey = Abhi_psk
AllowedIPs = 10.55.22.2/32
### end Abhi ###
=============================================
::::  Client configuration shown below   ::::
[Interface]
PrivateKey = Abhi_priv
Address = 10.55.22.2/24
DNS = 8.8.8.8, 8.8.4.4

[Peer]
PublicKey = server_pub
PresharedKey = Abhi_psk
Endpoint = REDACTED:51820
AllowedIPs = 0.0.0.0/0, ::0/0
=============================================
::::    Recursive list of files in       ::::
::::    /etc/wireguard shown below       ::::
/etc/wireguard:
configs
keys
wg0.conf

/etc/wireguard/configs:
Abhi.conf
clients.txt

/etc/wireguard/keys:
Abhi_priv
Abhi_psk
Abhi_pub
server_priv
server_pub
=============================================
::::            Self check               ::::
:: [OK] IP forwarding is enabled
:: [OK] Iptables MASQUERADE rule set
:: [OK] Iptables FORWARD rule set
:: [OK] WireGuard is running
:: [OK] WireGuard is enabled
(it will automatically start on reboot)
:: [OK] WireGuard is listening on port 51820/udp
=============================================
:::: Having trouble connecting? Take a look at the FAQ:
:::: https://docs.pivpn.io/faq
=============================================
:::: WARNING: This script should have automatically masked sensitive       ::::
:::: information, however, still make sure that PrivateKey, PublicKey      ::::
:::: and PresharedKey are masked before reporting an issue. An example key ::::
:::: that you should NOT see in this log looks like this:                  ::::
:::: YIAoJVsdIeyvXfGGDDadHh6AxsMRymZTnnzZoAb9cxRe                          ::::
=============================================
::::            Debug complete           ::::
:::
::: Debug output completed above.
::: Copy saved to /tmp/debug.log


**output of sudo nano /etc/pivpn/wireguard/setupVars.conf**

PLAT=Debian
OSCN=bookworm
USING_UFW=0
pivpnforceipv6route=1
IPv4dev=end0
dhcpReserv=1
IPv4addr=192.16x.x.xxx/24
IPv4gw=192.16x.x.xxx
install_user=AbhiVPN
install_home=/home/AbhiVPN
VPN=wireguard
pivpnPORT=51820
pivpnDNS1=8.8.8.8
pivpnDNS2=8.8.4.4
pivpnHOST=49.36.91.36
INPUT_CHAIN_EDITED=0
FORWARD_CHAIN_EDITED=1
INPUT_CHAIN_EDITEDv6=
FORWARD_CHAIN_EDITEDv6=
pivpnPROTO=udp
pivpnMTU=1420
pivpnDEV=wg0
pivpnNET=10.55.22.0
subnetClass=24
pivpnenableipv6=0
ALLOWED_IPS="0.0.0.0/0, ::0/0"
UNATTUPG=1
INSTALLED_PACKAGES=()


![WhatsApp Image 2024-08-03 at 16 11 36_891cce4a](https://github.com/user-attachments/assets/5dd33650-f65e-457b-aff3-82ed26342925)

**Comment by orazioedoardo** [comment]
Endpoint is clearly wrong in the WireGuard app, that doesn’t seem a valid IPv6 address, and it should be the value of pivpnHOST in setup vars (which you haven’t removed).

**Comment by pAbhi001** [comment]
Q.1 My VPNHOST is not matching with my Internet service provider ip or my pi's reserved ip address
VPNHOST- 49.36.xx.xx
Pi's - 192.168.xx.xx
 
Is that ok ? 

Q.2 Should I change Endpoint on my  mobile app, and match it to my PiVPNHOST  or my Pi's reserved ip address/ my Internet service provider ip

**Comment by orazioedoardo** [comment]
> Q.2 Should I change Endpoint on my mobile app, and match it to my PiVPNHOST

This. Make sure to do port forwarding as well.

**Comment by pAbhi001** [comment]
Well when i try to change my Endpoint ip on mobile app it shows my ip 49.36.xx.xxx
port forwarding is also enable 

pic for reference
 
![WhatsApp Image 2024-08-04 at 16 12 02_45a64593](https://github.com/user-attachments/assets/6df53f15-5469-40e4-b2da-973408a113a7)
![WhatsApp Image 2024-08-04 at 16 12 02_0500eb53](https://github.com/user-attachments/assets/42d6d06d-9dc3-4618-9ed1-da6bf3209fbe)
![Screenshot 2024-08-04 160851](https://github.com/user-attachments/assets/8b86d6d2-1e58-4802-81d6-c12826599bf3)

**Comment by orazioedoardo** [comment]
So I don't know why Wireguard is showing that enpdoint address. Does `sudo cat /etc/wireguard/configs/Abhi.conf` show the correct endpoint address?

**Comment by pAbhi001** [comment]
here is the command 

Abhishek@AbhiPI4:/$ sudo cat /etc/wireguard/configs/Abhi.conf
[Interface]
PrivateKey = CDERYHa4XCCcwmM3kUt6ZvvvAcpEDdygfc3rQweDZm0=
Address = 10.73.xxx.xx/24
DNS = 208.67.222.222, 208.67.220.220

[Peer]
PublicKey = e5GkwtPTvVl9cdZE0dfS4o6k7XsYbaSpLGxnkO1LIm0=
PresharedKey = GE3U9a5Bp371Z16+br56pl4QJaj94t67DayaEHqzhfM=
Endpoint = 49.36.xx.xxx:51820
AllowedIPs = 0.0.0.0/0, ::0/0

**Comment by pAbhi001** [comment]
i tried connect it to windows, but still same result :(
can you check if there is any problem on my router setting 
i have attached snap before, for ipv6 and port forwarding ( one more thing - i am using my router as extender ( connected via lan )and haven't  applied same ip on my extender as my main router )

**Comment by orazioedoardo** [comment]
Port forwarding in that screenshot is correct, however if you have multiple router you need to do multiple port forward. Can you explain how your network is set up?

**Comment by pAbhi001** [comment]
I haven't done anything on my main router, everything I was doing was on my second router. For using second router I haven't done anything, only plugged LAN port and start using it. 

![image](https://github.com/user-attachments/assets/7bb91041-f0a2-465b-b2e5-6489fa0b7568)

**Comment by orazioedoardo** [comment]
Looks like you are in this situation: https://docs.pivpn.io/faq/#what-to-do-if-i-see-no-packets

> If you have multiple chained routers, then you need to configure multiple port forwardings. Example: (192.0.2.48) ISP router (192.168.1.1) ---> (192.168.1.2) Own router (192.168.23.1) ---> (192.168.23.211) Raspberry Pi. Given that, on the ISP router port forward 1194 udp to 192.168.1.2 and on your own router port forward 1194 UDP to 192.168.23.211.

**Comment by orazioedoardo** [comment]
Have you configured port on both gateway as well as router? You can also try https://docs.pivpn.io/faq/#how-do-i-troubleshoot-connection-issues

**Comment by pAbhi001** [comment]
Yes i did set that on both router , didn't work.
Also did clean installation of my os, then tried again , no result 
 https://docs.pivpn.io/faq/#how-do-i-troubleshoot-connection-issues every thing seems fine on my case

**Comment by orazioedoardo** [comment]
Assuming port forwarding is correct, you might be under CGNAT.

**Comment by pAbhi001** [comment]
Any way to correct it ?

**Comment by pAbhi001** [comment]
I have tried it on Docker also, same result ( assuming there must be anything on my router or my pi's IP setting )

**Comment by orazioedoardo** [comment]
You may ask your ISP whether your internet connection plan is under CGNAT. If it is, you may ask for a public IP (usually not free). If you can't get a public IP, you can't use PiVPN. An alternative may be Tailscale.

**Comment by pAbhi001** [comment]
Ok
I have confirmed with my isp that they only allow static ip on their highest plan 

Installed Tailscale which is working fine as I can access my nas 

But for next cloud which is installed via Docker on OMB is not allowing my to change my config file to allow my new IP address. 
Any solution for that or I have to use cloudfare or other service like that 

And Is tailscale safe and secure because it is not hosted locally on my pc

**Comment by orazioedoardo** [comment]
Static IP is not the same as public IP. Tailscale should be fairly secure.

**Comment by pAbhi001** [comment]
Thanks 
Connected via Tailscale, working fine.

Thank you for guiding me through this.
