### ISSUE TITLE
Is there any way to remove clients?

### ISSUE THREAD

**Issue by cdrandin** [pivpn/pivpn#185]
I have a test case using PiVPN i.e.) `Test` and would like to remove it. I tried the revoke method, but that didn't necessarily removed it. When I try and add a new client it says it still exist, but I am unsure where to find it.

**Comment by fyellin** [comment]
Removing a client just means that that client is blacklisted from using OpenVPN.  The client isn't actually deleted.

**Comment by cdrandin** [comment]
Alright, is there anyway to reuse the same client name? Like generating a new key for an already existing client.

**Comment by 0-kaladin** [comment]
hmm, don't think i've given an easy way to do that with pivpn.  if you manually delete the clients you should be able to add a new one with same name.  I only provide for revoke and add.

**Comment by 0-kaladin** [comment]
This is now possible with the above commit.
