### ISSUE TITLE
Configuration for initial PIVPN

### ISSUE THREAD

**Issue by bubu8300** [pivpn/pivpn#186]
## Issue
I'm installing my PIVPN and come accros to DNS entry.
I have my domain (exemple domain.com) and a freedns for it at freedns.afraid.org. If i ping my domain my home ip respondes. What do I enter in DNS entry? It will ask me "Wat is the public dns name of this server?" and after this dns provider for my VPN... and ask for some ip address if i choose custom.
What setting should i give?

**Comment by fyellin** [comment]
The public DNS of your server is whatever name you can use externally to reach your domain.  If you own `example.com` and pinging `example.com` reaches your machine, then that's what you should use.

How `example.com` gets mapped to your  machine is irrelevant.   Presumably you actually have a name like `example.afraid.com`

**Comment by bubu8300** [comment]
Thanks... I've put my example.com... but if I don't want to go through google dns or something like that... what can I do? If I put example.com and dns from google for example is working. But for my I prefer not to go through there.

**Comment by fyellin** [comment]
I honestly don't know what you're asking.   You can't use a static IP address because you don't have one.  I'm not sure why you don't want to use the IP address provided by whoever is hosting your dns service.

**Comment by bubu8300** [comment]
I'm following this tutorial https://www.sitepoint.com/setting-up-a-home-vpn-using-your-raspberry-pi/ for instaling pivpn.
Take a look at DNS provider step. That is where I have the problem. If I choose custom I have to enter some IP address for DNS. The question is what IP address? From where...

**Comment by 0-kaladin** [comment]
You don't need to use custom there.  that is the dns your clients will use.  Just pick Google DNS and you'll be fine.  Or research the others if you prefer.

**Comment by cfcolaco** [comment]
Marking as information and Closing issue as it is quite old and quite well explained.
