### ISSUE TITLE
[General Issue]: No packet arrives to the VPN server

### ISSUE THREAD

**Issue by DucNM11** [pivpn/pivpn#1862]
### In raising this issue I confirm that

- [X] I have read the [documentation](https://docs.pivpn.io)
- [X] I have read and understood the [PiVPN General Guidelines](https://github.com/pivpn/pivpn/#general-guidelines)
- [X] I have read and understood the [PiVPN Troubleshooting Guidelines](https://docs.pivpn.io/faq/#how-do-i-troubleshoot-connection-issues)
- [X] The issue I am reporting isn't a duplicate, see [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen).
- [X] I have searched for similar issues and solutions
- [X] I can replicate the issue even after a clean OS installation

### Describe the issue

No packet arrives to the VPN server when following the troubleshooting steps from the FAQs

### Expected behavior

Can connect to the internet with VPN's config

### Please describe the steps to replicate the issue

installed pivpn, used pivpn add. Passed the conf file to the client devices.

### Have you taken any steps towards solving your issue?

1. Restart wireguard service successfully with `sudo systemctl restart wg-quick@wg0`.
2. Checked pivpn -d
`:: [OK] IP forwarding is enabled
:: [OK] Iptables MASQUERADE rule set
:: [OK] WireGuard is running
:: [OK] WireGuard is enabled 
(it will automatically start on reboot)
:: [OK] WireGuard is listening on port 51820/udp`

3. Checked that the current IP address of the interface IPv4dev is the same as IPv4addr.
4. Checked that the current public IP of my connection is the same as pivpnHOST
5. Checked tcpdump, no packets arrived
`tcpdump -n -i wlan0 udp port *redacted*
tcpdump: verbose output suppressed, use -v[v]... for full protocol decode
listening on wlan0, link-type EN10MB (Ethernet), snapshot length 262144 bytes`
6. Check for "What to do if I see no packets?" section
- If you set up PiVPN with ethernet and later switched to wifi, you will have a different IP. Easiest way to fix is to reinstall and pick the new network interface. **-> It's still wlan0**
- Check if your ISP uses Carrier-grade NAT (check online). With CGNAT, your router gets a private IP, making port forwarding ineffective. This is mostly the norm if your router connects via 4G/LTE. If that's the case, you need to ask the ISP for a public IP. **-> My router IP address is the same with the public IP address**
- If you see packets coming to the Pi, but no response to the smartphone, it may indicate routing issues, attempts to block the connection (on either side), poor connectivity. In all cases, try to connect from a different network. It may also indicate misconfigured keys though this shouldn't happen with the official scripts. **-> There was no packets coming**
-  If you have multiple chained routers, then you need to configure multiple port forwardings. Example: (192.0.2.48) ISP router (192.168.1.1) ---> (192.168.1.2) Own router (192.168.23.1) ---> (192.168.23.211) Raspberry Pi. Given that, on the ISP router port forward 1194 udp to 192.168.1.2 and on your own router port forward 1194 UDP to 192.168.23.211. **-> Don't have chained routers**
- You may have misconfigured firewall rules on your Pi, open an issue and add the output of sudo iptables -S and sudo iptables -t nat -S.
  - iptables -S:
`-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT`
   - iptables -t nat -S
`-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT
-A POSTROUTING -s 10.89.60.0/24 -o wlan0 -m comment --comment wireguard-nat-rule -j MASQUERADE`

### Where did you run pivpn?

Raspberry Pi 4

### Please provide your output from `uname -a`

Linux pi 6.6.31+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.31-1+rpt1 (2024-05-29) aarch64 GNU/Linux

### Details about Operative System

PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

### Debug output

::: Generating Debug Output
tee: /tmp/debug.log: Permission denied
::::		PiVPN debug		 ::::
=============================================
::::		Latest commit		 ::::
Branch: master
Commit: 4e4d608b35255680eb1545bfb5555c5b74411b31
Author: wlmchen
Date: Sun Jul 28 17:29:36 2024 -0700
Summary: Fix Alpine persistence
=============================================
::::	    Installation settings    	 ::::
PLAT=Debian
OSCN=bookworm
USING_UFW=0
IPv4dev=wlan0
IPv6dev=wlan0
dhcpReserv=1
IPv4addr=192.168.1.135/24
IPv4gw=192.168.1.1
install_user=dwc
install_home=/home/dwc
VPN=wireguard
pivpnPORT=51820
pivpnDNS1=9.9.9.9
pivpnDNS2=149.112.112.112
pivpnHOST=REDACTED
INPUT_CHAIN_EDITED=0
FORWARD_CHAIN_EDITED=0
INPUT_CHAIN_EDITEDv6=0
FORWARD_CHAIN_EDITEDv6=0
pivpnPROTO=udp
pivpnMTU=1420
pivpnDEV=wg0
pivpnNET=10.89.60.0
subnetClass=24
pivpnenableipv6=1
pivpnNETv6="fd11:5ee:bad:c0de::"
subnetClassv6=64
ALLOWED_IPS="0.0.0.0/0, ::0/0"
UNATTUPG=1
INSTALLED_PACKAGES=(dnsutils grepcidr bsdmainutils iptables-persistent wireguard-tools qrencode unattended-upgrades)
=============================================
::::  Server configuration shown below   ::::
[Interface]
PrivateKey = server_priv
Address = 10.89.60.1/24,fd11:5ee:bad:c0de::a59:3c01/64
MTU = 1420
ListenPort = 51820
### begin dwc ###
[Peer]
PublicKey = dwc_pub
PresharedKey = dwc_psk
AllowedIPs = 10.89.60.2/32,fd11:5ee:bad:c0de::a59:3c02/128
### end dwc ###
=============================================
::::  Client configuration shown below   ::::
[Interface]
PrivateKey = dwc_priv
Address = 10.89.60.2/24,fd11:5ee:bad:c0de::a59:3c02/64
DNS = 9.9.9.9, 149.112.112.112

[Peer]
PublicKey = server_pub
PresharedKey = dwc_psk
Endpoint = REDACTED:51820
AllowedIPs = 0.0.0.0/0, ::0/0
=============================================
:::: 	Recursive list of files in	 ::::
::::	/etc/wireguard shown below	 ::::
/etc/wireguard:
configs
keys
wg0.conf

/etc/wireguard/configs:
clients.txt
dwc.conf

/etc/wireguard/keys:
dwc_priv
dwc_psk
dwc_pub
server_priv
server_pub
=============================================
::::		Self check		 ::::
:: [OK] IP forwarding is enabled
:: [OK] Iptables MASQUERADE rule set
:: [OK] WireGuard is running
:: [OK] WireGuard is enabled 
(it will automatically start on reboot)
:: [OK] WireGuard is listening on port 51820/udp
=============================================
:::: Having trouble connecting? Take a look at the FAQ:
:::: https://docs.pivpn.io/faq
=============================================
:::: WARNING: This script should have automatically masked sensitive       ::::
:::: information, however, still make sure that PrivateKey, PublicKey      ::::
:::: and PresharedKey are masked before reporting an issue. An example key ::::
:::: that you should NOT see in this log looks like this:                  ::::
:::: YIAoJVsdIeyvXfGGDDadHh6AxsMRymZTnnzZoAb9cxRe                          ::::
=============================================
::::		Debug complete		 ::::
::: 
::: Debug output completed above.
::: Copy saved to /tmp/debug.log

**Comment by orazioedoardo** [comment]
Have you solved it?
