### ISSUE TITLE
[General Issue]: I've already followed the FAQ to trouble shoot, but I still can't connect through wireguard

### ISSUE THREAD

**Issue by tzssssam** [pivpn/pivpn#1877]
### In raising this issue I confirm that

- [X] I have read the [documentation](https://docs.pivpn.io)
- [X] I have read and understood the [PiVPN General Guidelines](https://github.com/pivpn/pivpn/#general-guidelines)
- [X] I have read and understood the [PiVPN Troubleshooting Guidelines](https://docs.pivpn.io/faq/#how-do-i-troubleshoot-connection-issues)
- [X] The issue I am reporting isn't a duplicate, see [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen).
- [X] I have searched for similar issues and solutions
- [X] I can replicate the issue even after a clean OS installation

### Describe the issue

I've arleady followed the steps in FAQ to trouble shoot. 
Now I believe the issue is Packet capture since noting shown after running "tcpdump -n -i IPv4dev pivpnPROTO port pivpnPORT" 
After that, I also reinstall pivpn with a new IP address
And I can confirm my prmary router has a public IP address.

### Expected behavior

I expect the vpn to be working on both my phone and my travel router, I hope someone can help me with this and give me some instruction on how to troubleshoot this. Thanks

### Please describe the steps to replicate the issue

1. Install pivpn through wireguard
2. reboot using "sudo reboot" after the installation complete
3. use "pivpn wg -d" to fix some bugs
4. use "pivpn -a" and "pivpn -qr" to add the service on my phone
5. Turned on the connection on my phone, couldn't open any webpages
6. Also, I added the config to my Glinet travel router, it says "the client is starting, please wait....."

### Have you taken any steps towards solving your issue?

I've arleady followed the steps in FAQ to trouble shoot. 
Now I believe the issue is Packet capture since nothing shown after running "tcpdump -n -i IPv4dev pivpnPROTO port pivpnPORT" 
After that, I also reinstall pivpn with a new IP address
And I can confirm my prmary router has a public IP address.

### Screenshots

Here's the output for "sudo iptables -S":
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
-A INPUT -p udp -m udp --dport 51820 -j ACCEPT
-A INPUT -p udp -m udp --dport 51820 -j ACCEPT
-A INPUT -i wlan0 -p udp -m udp --dport 1194 -m comment --comment openvpn-input-rule -j ACCEPT
-A INPUT -p udp -m udp --dport 51820 -j ACCEPT
-A INPUT -i wlan0 -p udp -m udp --dport 51820 -m comment --comment wireguard-input-rule -j ACCEPT
-A INPUT -p udp -m udp --dport 51820 -j ACCEPT
-A INPUT -p udp -m udp --dport 51820 -j ACCEPT
-A INPUT -p udp -m udp --dport 51820 -j ACCEPT
-A INPUT -p udp -m udp --dport 51820 -j ACCEPT
-A INPUT -p udp -m udp --dport 51820 -j ACCEPT
-A INPUT -p udp -m udp --dport 51820 -j ACCEPT
-A INPUT -p udp -m udp --dport 51820 -j ACCEPT
-A INPUT -p udp -m udp --dport 51820 -j ACCEPT
-A INPUT -p udp -m udp --dport 51820 -j ACCEPT
-A INPUT -p udp -m udp --dport 51820 -j ACCEPT
-A INPUT -p udp -m udp --dport 51820 -j ACCEPT
-A INPUT -p udp -m udp --dport 51820 -j ACCEPT
-A INPUT -p udp -m udp --dport 51820 -j ACCEPT
-A INPUT -p udp -m udp --dport 51820 -j ACCEPT
-A FORWARD -d 10.194.152.0/24 -i wlan0 -o wg0 -m conntrack --ctstate RELATED,ESTABLISHED -m comment --comment wireguard-forward-rule -j ACCEPT
-A FORWARD -s 10.194.152.0/24 -i wg0 -o wlan0 -m comment --comment wireguard-forward-rule -j ACCEPT
-A FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -s 10.7.0.0/24 -j ACCEPT
-A FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -s 10.7.0.0/24 -j ACCEPT
-A FORWARD -d 10.242.205.0/24 -i wlan0 -o tun0 -m conntrack --ctstate RELATED,ESTABLISHED -m comment --comment openvpn-forward-rule -j ACCEPT
-A FORWARD -s 10.242.205.0/24 -i tun0 -o wlan0 -m comment --comment openvpn-forward-rule -j ACCEPT
-A FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -s 10.7.0.0/24 -j ACCEPT
-A FORWARD -d 10.226.237.0/24 -i wlan0 -o wg0 -m conntrack --ctstate RELATED,ESTABLISHED -m comment --comment wireguard-forward-rule -j ACCEPT
-A FORWARD -s 10.226.237.0/24 -i wg0 -o wlan0 -m comment --comment wireguard-forward-rule -j ACCEPT
-A FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -s 10.7.0.0/24 -j ACCEPT
-A FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -s 10.7.0.0/24 -j ACCEPT
-A FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -s 10.7.0.0/24 -j ACCEPT
-A FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -s 10.7.0.0/24 -j ACCEPT
-A FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -s 10.7.0.0/24 -j ACCEPT
-A FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -s 10.7.0.0/24 -j ACCEPT
-A FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -s 10.7.0.0/24 -j ACCEPT
-A FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -s 10.7.0.0/24 -j ACCEPT
-A FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -s 10.7.0.0/24 -j ACCEPT
-A FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -s 10.7.0.0/24 -j ACCEPT
-A FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -s 10.7.0.0/24 -j ACCEPT
-A FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -s 10.7.0.0/24 -j ACCEPT
-A FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -s 10.7.0.0/24 -j ACCEPT
-A FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -s 10.7.0.0/24 -j ACCEPT
-A FORWARD -d 10.31.103.0/24 -i wlan0 -o wg0 -m conntrack --ctstate RELATED,ESTABLISHED -m comment --comment wireguard-forward-rule -j ACCEPT
-A FORWARD -s 10.31.103.0/24 -i wg0 -o wlan0 -m comment --comment wireguard-forward-rule -j ACCEPT
-A FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -s 10.7.0.0/24 -j ACCEPT

And here's the output for "sudo iptables -t nat -S":
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT
-A POSTROUTING -s 10.194.152.0/24 -o wlan0 -m comment --comment wireguard-nat-rule -j MASQUERADE
-A POSTROUTING -s 10.242.205.0/24 -o wlan0 -m comment --comment openvpn-nat-rule -j MASQUERADE
-A POSTROUTING -s 10.226.237.0/24 -o wlan0 -m comment --comment wireguard-nat-rule -j MASQUERADE
-A POSTROUTING -s 10.137.222.0/24 -o wlan0 -m comment --comment wireguard-nat-rule -j MASQUERADE
-A POSTROUTING -s 10.7.0.0/24 ! -d 10.7.0.0/24 -j SNAT --to-source 192.168.x.X
-A POSTROUTING -s 10.7.0.0/24 ! -d 10.7.0.0/24 -j SNAT --to-source 192.168.x.x
-A POSTROUTING -s 10.7.0.0/24 ! -d 10.7.0.0/24 -j SNAT --to-source 192.168.x.x
-A POSTROUTING -s 10.7.0.0/24 ! -d 10.7.0.0/24 -j SNAT --to-source 192.168.x.x
-A POSTROUTING -s 10.7.0.0/24 ! -d 10.7.0.0/24 -j SNAT --to-source 192.168.x.x
-A POSTROUTING -s 10.7.0.0/24 ! -d 10.7.0.0/24 -j SNAT --to-source 192.168.x.x

### Where did you run pivpn?

Raspberry PI

### Please provide your output from `uname -a`

Linux raspberrypi 6.6.51+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.51-1+rpt3 (2024-10-08) aarch64 GNU/Linux

### Details about Operative System

PRETTY_NAME="Raspbian GNU/Linux 12 (bookworm)"
NAME="Raspbian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

### Installation

 % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  117k  100  117k    0     0  72653      0  0:00:01  0:00:01 --:--:-- 72661
:::
::: sudo will be used for the install.

### Profile / Client creation

"pivpn add":
::: To pass off to the pivpn command for each protocol
:::
::: Usage: pivpn wg  <command> [option]
::: Usage: pivpn ovpn <command> [option]
:::
:::  -h,  help             Show this help dialog
:::  -u,  uninstall        Uninstall pivpn from your system!
:::  -bk, backup           Backup VPN configs and user profiles

"pivpn add nopass":
::: To pass off to the pivpn command for each protocol
:::
::: Usage: pivpn wg  <command> [option]
::: Usage: pivpn ovpn <command> [option]
:::
:::  -h,  help             Show this help dialog
:::  -u,  uninstall        Uninstall pivpn from your system!
:::  -bk, backup           Backup VPN configs and user profiles

### Debug output

::: Generating Debug Output
::::            PiVPN debug              ::::
=============================================
::::            Latest commit            ::::
Branch: master
Commit: 4e4d608b35255680eb1545bfb5555c5b74411b31
Author: wlmchen
Date: Sun Jul 28 17:29:36 2024 -0700
Summary: Fix Alpine persistence
=============================================
::::        Installation settings        ::::
PLAT=Raspbian
OSCN=bookworm
USING_UFW=0
pivpnforceipv6route=1
IPv4dev=wlan0
IPv4addr=my IP address
IPv4gw=192.168.x.x
useNetworkManager=true
install_user=my username
install_home=/home/my username
VPN=wireguard
pivpnPORT=51820
pivpnDNS1=1.1.1.1
pivpnDNS2=1.0.0.1
pivpnHOST=REDACTED
INPUT_CHAIN_EDITED=1
FORWARD_CHAIN_EDITED=1
INPUT_CHAIN_EDITEDv6=
FORWARD_CHAIN_EDITEDv6=
pivpnPROTO=udp
pivpnMTU=1420
pivpnDEV=wg0
pivpnNET=10.194.152.0
subnetClass=24
pivpnenableipv6=0
ALLOWED_IPS="0.0.0.0/0, ::0/0"
UNATTUPG=1
INSTALLED_PACKAGES=()
=============================================
::::  Server configuration shown below   ::::
[Interface]
PrivateKey = server_priv
Address = 10.194.152.1/24
MTU = 1420
ListenPort = 51820
### begin wg1 ###
[Peer]
PublicKey = wg1_pub
PresharedKey = wg1_psk
AllowedIPs = 10.194.152.2/32
### begin wg2 ###
[Peer]
PublicKey = wg2_pub
PresharedKey = wg2_psk
AllowedIPs = 10.194.152.3/32
### begin wg3 ###
[Peer]
PublicKey = wg3_pub
PresharedKey = wg3_psk
AllowedIPs = 10.194.152.4/32
### end wg3 ###
=============================================
::::  Client configuration shown below   ::::
[Interface]
PrivateKey = wg1_priv
Address = 10.194.152.2/24
DNS = 1.1.1.1, 1.0.0.1

[Peer]
PublicKey = server_pub
PresharedKey = wg1_psk
Endpoint = REDACTED:51820
AllowedIPs = 0.0.0.0/0, ::0/0
=============================================
::::    Recursive list of files in       ::::
::::    /etc/wireguard shown below       ::::
/etc/wireguard:
configs
keys
wg0.conf

/etc/wireguard/configs:
clients.txt
wg1.conf
wg2.conf
wg3.conf

/etc/wireguard/keys:
server_priv
server_pub
wg1_priv
wg1_psk
wg1_pub
wg2_priv
wg2_psk
wg2_pub
wg3_priv
wg3_psk
wg3_pub
=============================================
::::            Self check               ::::
:: [OK] IP forwarding is enabled
:: [OK] Iptables MASQUERADE rule set
:: [OK] Iptables INPUT rule set
:: [OK] Iptables FORWARD rule set
:: [OK] WireGuard is running
:: [OK] WireGuard is enabled
(it will automatically start on reboot)
:: [OK] WireGuard is listening on port 51820/udp
=============================================
:::: Having trouble connecting? Take a look at the FAQ:
:::: https://docs.pivpn.io/faq
=============================================
:::: WARNING: This script should have automatically masked sensitive       ::::
:::: information, however, still make sure that PrivateKey, PublicKey      ::::
:::: and PresharedKey are masked before reporting an issue. An example key ::::
:::: that you should NOT see in this log looks like this:                  ::::
:::: YIAoJVsdIeyvXfGGDDadHh6AxsMRymZTnnzZoAb9cxRe                          ::::
=============================================
::::            Debug complete           ::::
:::
::: Debug output completed above.
::: Copy saved to /tmp/debug.log
:::

**Comment by orazioedoardo** [comment]
What the exact tcpdump command you ran while trying to connect?

**Comment by stefaux** [comment]
Hi, I was just about to post the same issue.

**Comment by tzssssam** [comment]
> Hi, I was just about to post the same issue.

Actually I figured out myself, my ISP is not providing a static external IP address and this is causing the problem. My solution is to create an account on one of those free dynamic DNS services so that I can get access to my main router and see the IP address wherever I am. Then i'm able to update the endpoint in the conf. files. 
Basically I need to update it everytime when the external IP address change,  not sure if there's a better way to do though

**Comment by tzssssam** [comment]
I figured out the problem myself, it is because my ISP is not providing a static external IP address
