### ISSUE TITLE
[General Issue]:  cipher AES-256-CBC deprecated option

### ISSUE THREAD

**Issue by Rouzic6666** [pivpn/pivpn#1878]
### In raising this issue I confirm that

- [X] I have read the [documentation](https://docs.pivpn.io)
- [X] I have read and understood the [PiVPN General Guidelines](https://github.com/pivpn/pivpn/#general-guidelines)
- [X] I have read and understood the [PiVPN Troubleshooting Guidelines](https://docs.pivpn.io/faq/#how-do-i-troubleshoot-connection-issues)
- [X] The issue I am reporting isn't a duplicate, see [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen).
- [X] I have searched for similar issues and solutions
- [X] I can replicate the issue even after a clean OS installation

### Describe the issue

Hi,
In template file /etc/openvpn/easy-rsa/pki/Default.txt "cipher AES-256-CBC" is deprecated
Regards

### Expected behavior

cipher AES-256-GCM

### Please describe the steps to replicate the issue

$ pivpn -a   => client.ovpn
$ sudo openvpn --config client.ovpn
...
DEPRECATED OPTION: --cipher set to 'AES-256-CBC' but missing in --data-ciphers (AES-256-GCM:AES-128-GCM:CHACHA20-POLY1305). OpenVPN ignores --cipher for cipher negotiations.
...

### Have you taken any steps towards solving your issue?

modify  /etc/openvpn/easy-rsa/pki/Default.txt
AES-256-CBC ->  AES-256-GCM

### Where did you run pivpn?

Raspberry

### Please provide your output from `uname -a`

Linux proxylocal 6.6.62+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.62-1+rpt1 (2024-11-25) aarch64 GNU/Linux

### Details about Operative System

Debian GNU/Linux 12 (bookworm)

### Debug output

NR

**Comment by orazioedoardo** [comment]
Could be changed to AES-256-CBC by needs to be tested on oldest supported distributions to verify it doesn't beak those. Note that on newer OpenVPN it doesn't hurt since it does the upgrade automatically.

**Comment by Rouzic6666** [comment]
Ok thanks
