### ISSUE TITLE
whois 82.200.69.80 reveals a russian server

### ISSUE THREAD

**Issue by pipapo** [pivpn/pivpn#189]
Hi

In the DNSchoices of install.sh, the address 82.200.69.80 ("::: Using DNS.WATCH servers.") points to:

netname:        ZSTTK-NET
descr:          JSC "Zap-SibTranstelecom"
descr:          Komsomolqskijj Avenue, 1/4
descr:          630004, Novosibirsk

whereas the dns.watch services are provided by the german company IAMONSYS GMBH.

I do not feel comfortable with that!

**Comment by redfast00** [comment]
Well, then don't use that DNS service I guess? You are able to choose what DNS server you want to use. (unless you mean we got the IP wrong, in which case you can submit a PR or leave a comment)

**Comment by 0-kaladin** [comment]
It is their server, it is not wrong. 
https://dns.watch/index#ips

You should not feel uncomfortable with it, but if you are, that is why there are a ton of choices there.

**Comment by pipapo** [comment]
@0-kaladin : Sorry but in your link https://dns.watch/index#ips the server address is 8**4**.200.69.80 and not 82.200.69.80. You may have a mistype error in install.sh.

**Comment by redfast00** [comment]
Since this is a security issue, I thought it had higher priority and immediately fixed it. I also checked the other IPs of the DNS servers, and the seem to be correct.

**Comment by 0-kaladin** [comment]
Thanks @redfast00
