### ISSUE TITLE
Should we offer unattended upgrades

### ISSUE THREAD

**Issue by 0-kaladin** [pivpn/pivpn#19]
Wonder if we should offer the setup of unattended upgrades for security packages.
Being this is something that will have at least one port open to the internet, we could offer to configure unattended upgraded for security packages only so that on some regular basis the pi is upgraded with new security patches. 
I'd take it to a thumb up/down vote here.

**Comment by PaTall** [comment]
thumb up here. Thanks

**Comment by ostermayer** [comment]
thumbs up as well but only security packages
