### ISSUE TITLE
How to update a password/key?

### ISSUE THREAD

**Issue by damienchallet** [pivpn/pivpn#191]
The only way to update a key I have found is to revoke it and to add another client name (X1, X2, X3, etc.). Is there any other way or plan to add this feature ?

**Comment by fyellin** [comment]
Are you asking about changing the password you need to use your client?    This is really easy.

1) Save a copy of your `client.ovpn`.  If you make a mistake, you want a backup.

2) Find the two lines in your `client.ovpn` containing the markers `<key>` and `</key>`.  Copy everything between those two markers (but not the markers themselves) into a file `myKey.key`.

3) `openssl rsa -in myKey.key -out myKey.key.new -aes256`.  You will be asked for your old password (once) and your new password (twice).

4) Replace the text between the two markers with the contents of `myKey.key.new`

**Comment by damienchallet** [comment]
Many thanks, that is very clear. 

Now if I revoke some key, can I generate a new one with the same name ? 

Alternatively, I could delete any reference to the revoked key and generate a new one if only I knew where this information is store.

**Comment by 0-kaladin** [comment]
As of this commit: bfd2c435709de2328caa1b0463836ac7846140de  you can now revoke a client and issue new one with same name.
