### ISSUE TITLE
will this work on Mac?

### ISSUE THREAD

**Issue by dylanbach5150** [pivpn/pivpn#192]
I see instructions for using this with Windows and Android and the RPI, but what about Mac?  I want to know before I go through with installation.  Will I be able to open a program on my Mac to connect to my pi, with a program like privatetunnel-mac-2.8?
Thanks!

# PiVPN Issue Template

## Console output of `curl install.pivpn.io | bash`
```

```

## Console output of `pivpn add` or `pivpn add nopass`
```

```

## Console output of `pivpn debug`
```

```

**Comment by fyellin** [comment]
Yes.  You can either use openvpn directly, or a program like tunnelblick which puts a pretty front-end on Mac.
