### ISSUE TITLE
change dns to ip configuration?

### ISSUE THREAD

**Issue by dylanbach5150** [pivpn/pivpn#193]
I set it up to work with dns connection but would like to change it to ip.  Is there a way to make this change or do I need to reinstall it? 
Thanks!

# PiVPN Issue Template

## Console output of `curl install.pivpn.io | bash`
```

```

## Console output of `pivpn add` or `pivpn add nopass`
```

```

## Console output of `pivpn debug`
```

```

**Comment by redfast00** [comment]
You will have to edit your generated ovpn files and replace the domainnames with the IP. If you want future ovpns to also have that IP, you can edit `/etc/openvpn/easy-rsa/pki/Default.txt`. If you want, you can update the wiki page FAQ, with this path, since it has changed.
