### ISSUE TITLE
how to transfer .ovpn config file to Mac ?

### ISSUE THREAD

**Issue by dylanbach5150** [pivpn/pivpn#194]
I'm using a Mac and shelling into the pi.  Pivpn is installed and ready to go, just can't get to the .ovpn file and would like to transfer it to my Mac. Is there a way to copy to my Mac and then drop into Tunnelblick? I've tried the scp command to copy it to my downloads folder, and it looks like it works, but then it doesn't appear in the downloads folder.  Trying to get the configuration file to drop into Tunnelblick and get everything working--stuck on last step.
Thank you!

.  

# PiVPN Issue Template

## Console output of `curl install.pivpn.io | bash`
```

```

## Console output of `pivpn add` or `pivpn add nopass`
```

```

## Console output of `pivpn debug`
```

```

**Comment by fyellin** [comment]
What you've done should work.  Try just copying the file to /tmp/.   

Are you getting any sort of error message from scp, or is it actually claiming to copy the file.

**Comment by dylanbach5150** [comment]
I’m not getting any error messages, it just lists the file example.ovpn  100% 5125     5.0KB/s   00:00  
I’ve tried copying to my Mac’s downloads, desktop, tmp, always the same thing—looks like it’s doing it correctly, but then can’t locate the file.

**Comment by dylanbach5150** [comment]
I found a solution.  I downloaded Cyberduck to connect to the Pi through SFTP.  I saw the OVPN file immediately and could transfer it.  Thanks for your help!

**Comment by fyellin** [comment]
I still wished I knew what the problem was.  I've had no problem with scp.

**Comment by dylanbach5150** [comment]
It’s possible I was doing it wrong, although it is strange that it looked like it worked and didn’t give me an error message.  Is there a guide for commands for Jessie lite or a resource site?

**Comment by Firemanjoe** [comment]
I used this method via netatalk and it worked perfectly!

http://www.instructables.com/id/How-to-share-files-between-Mac-OSX-and-Raspberry-P/

**Comment by rvoortman** [comment]
I personally don't think this is an issue of pivpn, but I'll share you my method anyway.

What I did is using the scp utility on the mac. Open up your terminal.app and enter te following command:

`scp <username_of_pi>@<ip_of_pi>:/home/<username_of_pi>/ovpns/<chosen_username>.ovpn ~/Desktop/`

Replace the fields with your information and you should be ready to go. The chosen_username is the name you've chosen when generating an ovpn file at the end of 'pivpn add'.

Hope this helps.

**Comment by cfcolaco** [comment]
old issue, marked as information as scp info can be useful for someone else. 

Closing.
