### ISSUE TITLE
Requesting permission to use PiVPN logo for article

### ISSUE THREAD

**Issue by cheebert** [pivpn/pivpn#198]
# PiVPN publication request

## Publication request for PiVPN logo
I'm trying to obtain permission to use the PIVPN logo in an InfoWorld article and this seemed to be the only way to contact the team. The gist is that I'm doing a slide show of enterprise Raspberry Pi applications and tools for InfoWorld Magazine and I need permission to use any graphics from the site.

/brian chee
brian_chee@infoworld.com

**Comment by 0-kaladin** [comment]
Approved.  
If you could, please post link here to article. Thanks!

**Comment by Yezariael** [comment]
I wrote an article how to install and use PiVPN in German. It's written especially for noobs without much experience in how to configure a VPN-Server.
If you like it I would be happy to get the article shared.
https://www.dennis-henss.de/2017/12/05/installation-pivpn-den-raspberry-pi-einfach-zum-vpn-server-ausbauen/

Regards,
Dennis
