### ISSUE TITLE
TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)

### ISSUE THREAD

**Issue by cephasiii** [pivpn/pivpn#199]
I have setup pivpn on a RPi 3 without any issues, created a .ovpn for my MacBook Pro and added it to my Tunnelblick client. When I try to connect to the pivpn server, I receive the TLS Error stated in the subject line. I have searched the web for a couple of days trying to resolve this issue, to no avail. 

Please assist. Let me know if you need any other files.

Tunnelblick log
http://pastebin.com/HACukejm

Debug log
http://pastebin.com/6jhpbjkG

PiVPN Server.conf
http://pastebin.com/tbdpFPHr

MacBook Pro .ovpn
http://pastebin.com/ybtPif5V

**Comment by 0-kaladin** [comment]
Well thanks for the detailed logs. All looks good except for that error. Where is your Mac when you are trying this? 
Have you tried a different location? 
Also try removing the tls-version-min line from the client ovpn and the server.conf

**Comment by cephasiii** [comment]
Deleting the "tls-version-min" line seemed to do the trick. Thanks for the quick response.

**Comment by 0-kaladin** [comment]
hmm not happy that line seemed to break it though.  Let me research that a bit more.  Thanks for the details though.
