### ISSUE TITLE
Problem connecting to server from Asus Router

### ISSUE THREAD

**Issue by planetahuevo** [pivpn/pivpn#20]
Hi, 
I am trying to connect to my openvpn server from my Router N66RT from Asus. 
The configuration is huge I am a little lost. 
For screens and information this link on torguard could help:
https://torguard.net/knowledgebase.php?action=displayarticle&id=216
I have imported my .ovpn file into the router but when I try to connect it does not work and it says:
```
Apr 30 11:40:13 openvpn[3020]: OpenVPN 2.3.8 mipsel-unknown-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [MH] [IPv6] built on Dec 24 2015
Apr 30 11:40:13 openvpn[3020]: library versions: OpenSSL 1.0.2e 3 Dec 2015, LZO 2.08
Apr 30 11:40:13 openvpn[3022]: WARNING: No server certificate verification method has been enabled.  See http://openvpn.net/howto.html#mitm for more info.
Apr 30 11:40:13 openvpn[3022]: NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Apr 30 11:40:13 openvpn[3022]: neither stdin nor stderr are a tty device, can't ask for Private Key password.  If you used --daemon, you need to use --askpass to make passphrase-protected keys work, and you can not use --auth-nocache.
Apr 30 11:40:13 openvpn[3022]: Exiting due to fatal error
```

Any Ideas on how to config this client to work with the open VPN?
Thanks

**Comment by 0-kaladin** [comment]
The error tells you what is going on:

> neither stdin nor stderr are a tty device, can't ask for Private Key password.  If you used --daemon, you need to use --askpass to make passphrase-protected keys work

I'm not familiar with the asus router but is there a way to add an '--askpass' option?  The problem is your ovpn generated cert is password protected and its telling you it has no way to ask you for the password.  You can manually generate a cert that does not have a password but before you do that...

Where is pivpn installed?  On the same network (home?) as this asus router?  If that is the case I don't know what you are trying to accomplish as the router being a client on your home network where the pivpn resides won't yield any benefit.  But I could be missing something.

**Comment by 0-kaladin** [comment]
I looked at that link, if you are trying to connect to torguard then that has nothing to do with pivpn.  you'd get an account from there and use that user/pass in the asus.

**Comment by planetahuevo** [comment]
The link is used to show screenshots. I am not using that config, It was just an example of the asus router screen. 
The server is on another network, with a static IP and I have been able to connect using the computer sofware with no issues at all. So the openvpn is working, the firewall is working and the ovpn file is working too. 
Now I want to connect my router as client, so any device connected to my router will go through the OpenVPN, for example a chromecast, that cannot install the openvpn app. 
There are some options for add a user and a passsword on the asus router (as you can see on the screen shots of that link) but I think is not on the private key password... not sure about this.

**Comment by 0-kaladin** [comment]
Gotcha.  So if you want to get a client cert without a pass to see if it'll work on the router...
Go on your pivpn and 
`cd /opt/pivpn/makeOVPN.sh`
Edit that file with (well I use 'vi makeOVPN.sh' but if you don't know the vi editor i guess normal people use nano?) so 'nano makeOVPN.sh'
find the line that says `./build-key-pass $NAME`
and change it to say `./build-key $NAME`

Then run pivpn add again and name this "router" or something.
Copy the resultant ovpn to your router and try  that.  Be sure to change the makeOVPN file back to ./build-key-pass so normal clients will be prompted for a password when they connect.

**Comment by planetahuevo** [comment]
I will try that and let you know. Thanks!

**Comment by planetahuevo** [comment]
I got this error:
Enter PEM pass phrase:
unable to write key

3069625552:error:28069065:lib(40):UI_set_result:result too small:ui_lib.c:869:You must type in 4 to 1024 characters
3069625552:error:0906406D:PEM routines:PEM_def_callback:problems getting password:pem_lib.c:111:
3069625552:error:0906906F:PEM routines:PEM_ASN1_write_bio:read key:pem_lib.c:382:

Not sure if the file will work. Testing right now.

**Comment by planetahuevo** [comment]
If I leave it blank, I have that error. If I put a pem phrase I have the same issue as before.

**Comment by 0-kaladin** [comment]
yea you'd have to make more changes to have a password-less.  
Probably easier if you just do it manually by running the ./build-key yourself.  
You'd have to put together the ovpn though.

**Comment by planetahuevo** [comment]
What do you mean with "put together the ovpn"?

**Comment by 0-kaladin** [comment]
the raw commands just make the certs.  the pivpn add takes the certs and builds an ovpn from them.  
you can run ./build-key and get a password less cert but that isn't an ovpn file.  you'd then have to put that together.
I could eventually add this functionality to pivpn add as maybe another option but that won't be trivial and I don't have time for that today.

**Comment by planetahuevo** [comment]
That´s OK.
I will try removing the phrase from the key and see if I can do this manually. 
Of course it does not needed to be today! :+1:

**Comment by 0-kaladin** [comment]
Well guess this could be an enhancement,
pivpn add nopass

**Comment by 0-kaladin** [comment]
Implemented a nopass option to 'pivpn add'
Commit: 6956fcb99b96679a15ab1ed2378352b2155600ee

**Comment by planetahuevo** [comment]
This is great! Thank you!
One question, I cannot find how to update the install on the readme.

**Comment by 0-kaladin** [comment]
There is no update.  Depending on the changes I'd have no way to tell if a change required all new certificates.  If you needed all new certificates you'd have to revoke all existing and create new.  For now it's easier to uninstall and reinstall.  I do it 6 times a day, it takes about 5 minutes:
'pivpn uninstall', reboot, 'curl -L https://install.pivpn.io | bash'

**Comment by planetahuevo** [comment]
So if the changes are minor, the config files we already have on our devices will still work?
Installing is 5 minutes but get the new config files to all my devices (9 so far) is not that easy for me.

**Comment by 0-kaladin** [comment]
if the changes are minor the config files can still work.  but i'd have no way of knowing in any given update, being able to track which will require new client certs or new server config and then modifying those options.  Once you have an install done and working for you, you won't really need updates (since this is an installer really and you install once).  
Bottom line, I'm not attempting to code in an updater here, too many potential bugs vs clean install and tons of forks of QA.  If there were 10 other contributors here willing to test permutations of upgrades vs clean installs and the options you can pick then sure, but just me, no way.  So if you want the password-less option, re-install.

**Comment by planetahuevo** [comment]
Understood. :+1: 
Thank you for the work. I would like to help with the code, but I am not good on this. 
I will help with testing and things like this as much as I can.

**Comment by planetahuevo** [comment]
I was able to connect using the nopass feature. 
There are some thing to fix on the router but nothing to do with the server. 

Thanks!

**Comment by 0-kaladin** [comment]
Great!

**Comment by mwoolweaver** [comment]
@planetahuevo how did you get this working?

**Comment by planetahuevo** [comment]
Oh, I cannot remember now, long time ago and I do not have the router here anymore... Sorry.

**Comment by mwoolweaver** [comment]
I ended up installing [asuswrt-merlin](https://github.com/RMerl/asuswrt-merlin) and I was able to connect to the OpenVPN server as a client.
