### ISSUE TITLE
Access to other device on VPN network

### ISSUE THREAD

**Issue by candoit3721** [pivpn/pivpn#201]
Great work! I was able to connect to the VPN and browse the internet. Is there a way to access NFS on the same network? (PI w/ OpenVPN 192.168.1.45, NFS 192.168.1.104, for example)? Thanks.

**Comment by 0-kaladin** [comment]
Might need bridge mode for that.  See Issue #45

**Comment by cfcolaco** [comment]
@redfast00  think this one might be closed since bridge mode is being discussed in issue #45
