### ISSUE TITLE
New features request

### ISSUE THREAD

**Issue by GabrieleCorrieri** [pivpn/pivpn#202]
Hello I'm very happy with this vpn: setup very easy also for me that I'm a very newbie on linux world.

Could I ask a new other installer script for doing:

a) using a wan (or lan) interface instead to the same: lan at eth0 and wan at wlan or other plugin eth

b) do a lan to lan connection between more raspberry pi, but not all at same time. My dream is more raspberry waiting to connect to me (mine is server side) by select a checkbox I ask them to connect me without man at client side. Also a signal of life (such as red / green mark) could be useful

These request are a beta test for teleservice equipment, so I can pay a little for these features.

**Comment by cfcolaco** [comment]
@redfast00 ???

**Comment by redfast00** [comment]
I didn't really think this was in scope of PiVPN, but the user offered to pay, so I left it open in case other users wanted to do this. Closing this.
