### ISSUE TITLE
PiVPN & let's encrypt

### ISSUE THREAD

**Issue by cephasiii** [pivpn/pivpn#204]
I installed pivpn, set it up and got it working great with multiple clients. I then installed let's encrypt for my Apache webserver running on the same server as pivpn. I use my ddns name to connect to the VPN. 
Let's encrypt works great when accessing the webpage, automating forwards http requested to https. However, pivpn clients will only connect took the VPN server using www. Domainname.com, not https://www.domainname.com. 

1. Is this a security issue?
2. How do I force the VPN clients to use https://www.domainname.com to connect took the VPN server?

If you need conf files let me know. 
Thanks.

**Comment by redfast00** [comment]
No, this is not a security issue. HTTP and OpenVPN are different protocols. Think of it as a car: normally, you'd like to have a seatbelt in your car (https), but you're riding a bike (OpenVPN) and worrying that it doesn't have a seatbelt,  Your OpenVPN traffic is automatically encrypted with the keys you generated as part of the install.
