### ISSUE TITLE
Is it possible to install PiVPN on CentOS?

### ISSUE THREAD

**Issue by ghost** [pivpn/pivpn#205]
Hi,

I absolutely love PiVPN! I It was pleasantly surprising how it took only 2 minutes to set up PiVPN and its openvpn runs perfectly on all the clients I tested. In comparison, I gave up setup openvpn the old ways many times before, with one success which turned out had buggy implementation (Synology NAS' openvpn).

I understand pivpn can be quite compatible with debian-based systems, yet, another popular branch of OSes are CentOS / RHEL based. 

I tried to google how to set up pivpn on CentOS but could not find it, so can I ask if this is something possible? But if not, hey this is totally understandable, and I'm not even requesting it. Just curious.

Thank you!

**Comment by redfast00** [comment]
Currently, it cannot do an install on a distro that doesn't have apt as package manager. We are however working on a way to install on other distros.

**Comment by cfcolaco** [comment]
@redfast00 ; @0-kaladin ; I would like to start building the support for CentOS and perhaps Arch ARM later, However would like to ask you what you consider to be the best approach for this: 

1 - Unique install script by adding support for centOS (dnf / yum ) inside the existing script
2 - Make a separate script based on the existing one but for CentOS / Fedora / RHEL

**Comment by redfast00** [comment]
There has been a PR in the test branch which makes it easier to add support for other distros. I don't know how much centOS is different from Debian, but I think that as long as it's manageable, we should try to keep it in one script for ease of use. @0-kaladin: when will we merge the test branch into the master branch?

**Comment by 0-kaladin** [comment]
Def should stay one script. Pihole does it as well. I need to test more
before merging and there are comments in the PR that need addressing. The
past year I've been going through a lot with work and home life. Free time
for hobby projects has been nil. After I move, I'm hoping by Sept I'll
tackle a ton of changes and updates here.

**Comment by cfcolaco** [comment]
@redfast00 it's bit different, default firewall in centOS 7 is firewalld, when using iptables rules are in /etc/sysconfig/iptables , off course package manager which is yum (getting deprecated and being replaced with dnf). 
will take a look in test branch and pihole, and eventually start building based on test. 
:) ty

**Comment by cfcolaco** [comment]
@redfast00  @0-kaladin 

Since I am migrating my cloud servers to new servers in a new provider I will need to use OpenVPN in CentOS ... having this said I would love to have pivpn with me on this one ... so will start to work on this and eventually do a major code review and fix some issues around here!! =)

**Comment by redfast00** [comment]
Okay, glad to hear that. I'm currently taking exams, so I won't have a lot of time for code review. Good luck!

**Comment by cfcolaco** [comment]
@redfast00 I dont have much time as well but will set aside stuff I have to do to do this one because I really want to use pivpn ... so ... will try to improve it and fix some stuff on the queue

**Comment by guest2** [comment]
The current pi-hole install script works great on CentOS. Can it be adapted to install PiVPN?

**Comment by 4s3ti** [comment]
@guest2 this is an improvement we are whiling to do, but not taking priority at the moment, if anyone comes forward with it i don't mind to review, test and accept/request changes. 

unfortunately we are not many active maintainers and we don't either have a contributing community as big as pihole so things here have to go slower and small bits at a time  =/

**Comment by redfast00** [comment]
Sorry guys, just wanted to unsubscribe
