### ISSUE TITLE
Retrieving Client keys: SSH/SFTP not enabled by default

### ISSUE THREAD

**Issue by ocf187** [pivpn/pivpn#206]
This is an informational post, not an issue.
I have successfully installed PIVPN about 5 times now over the past few months and it's worked great. I recently decided to wipe it out and start again (for various reasons).
So, last night I re-downloaded the NOOBS installer (full, not Lite), which presumably retrieves the latest version of Raspian.

Two things I noticed during the install that are different from last time I did it (a few months ago):
1) The screen/step that displays Certificate Information (Country, City, State, Org, etc.). is gone. I know this wasn't critical info, so I'm guessing the developers just removed it.
But more importantly...
2) After completing the install and generating a client cert, I was unable to SSH/SFTP in using another computer (obviously) on the same LAN, I tried using WinSCP and Linux command line.
I finally figured out the problem. SSH is not longer enabled by default. I know it used to be, because I never had this problem before. To enable, there's a nice "control panel" accessible using the following command: sudo raspi-config
Within there, it's under 7. Advanced Options
Just turn on SSH, then reboot (sudo reboot), and you should be fine.

I don't do much with Rasbian, so this may be obvious to others. But just in case, i thought I'd share.

**Comment by redfast00** [comment]
Or you can use DietPi, which has ssh enabled by default. Marking this as resolved, but will add information tag.
