### ISSUE TITLE
PiVPN connects but no Internet

### ISSUE THREAD

**Issue by R3Z1H** [pivpn/pivpn#207]
ok recently my PiVPN couldn't give internet access to any of its clients. Clients got only local access to the Pi. The problem is iptables. With days of research, i finally figured it out. Linux just needs to run the command `iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE` (if in eth0 of course). But the problem is, it only hold until the Pi reboots. Just letting you know about this issue. If possible please let me know how i can make this iptables setting permanent so that it holds even after the Pi reboots...

**Comment by stualoo** [comment]
Hi, see here https://github.com/pivpn/pivpn/issues/151 and https://github.com/pivpn/pivpn/issues/182
All are related. The method in 182 works for getting the rule set on boot/reboot, but seems a bug. Are you on Rasping Jessie as well?

**Comment by 0-kaladin** [comment]
the installer runs the iptables commands and then runs netfilter-persistent save to save them so they persist reboots.  can you post output of the commands i'm using here and see if your output looks similar:
```
root@raspberrypi:~# cat /etc/iptables/rules.v4
# Generated by iptables-save v1.4.21 on Sat Jan 28 16:25:36 2017
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [1:172]
:POSTROUTING ACCEPT [1:172]
-A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE
COMMIT
# Completed on Sat Jan 28 16:25:36 2017
# Generated by iptables-save v1.4.21 on Sat Jan 28 16:25:36 2017
*filter
:INPUT ACCEPT [1083:271462]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [1128:141424]
COMMIT
# Completed on Sat Jan 28 16:25:36 2017
root@raspberrypi:~# netfilter-persistent save
run-parts: executing /usr/share/netfilter-persistent/plugins.d/15-ip4tables save
run-parts: executing /usr/share/netfilter-persistent/plugins.d/25-ip6tables save
root@raspberrypi:~# cat /etc/iptables/rules.v4
# Generated by iptables-save v1.4.21 on Fri Feb 24 12:58:29 2017
*nat
:PREROUTING ACCEPT [51321:15096654]
:INPUT ACCEPT [47684:14906417]
:OUTPUT ACCEPT [9613:719442]
:POSTROUTING ACCEPT [9613:719442]
-A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE
COMMIT
# Completed on Fri Feb 24 12:58:29 2017
# Generated by iptables-save v1.4.21 on Fri Feb 24 12:58:29 2017
*filter
:INPUT ACCEPT [905883:377673837]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [64827:4306545]
COMMIT
# Completed on Fri Feb 24 12:58:29 2017
```

**Comment by Nephilimi** [comment]
I'm having a similar issue but don't really have the skills to troubleshoot it. Hoping for something to be fixed soon? I don't think this could be me?

A while ago I set up PiVPN, PiHole, and ddclient on a standard jese install on a Pi3. Everything worked great including OpenVPN resolving DNS through PiHole, I could hit my LAN as well of course.

I have been regularly doing sudo apt-get update and sudo apt-get dist-upgrade every couple of weeks to stay current. This weekend I installed Ubiquiti UniFi on that same Raspberry Pi, are there any known conflicts with this? I wouldn't think so but not sure.

Troubleshoot step 1: I restored my disk image from before I installed Ubiquiti UniFi and I still get the same issue, so I don't think that caused it. ALSO I learned I can hit the PiHole admin page through the VPN, so that's weird. Still can't reach any of my LAN devices via IP or anything on the internet.

Troubleshoot step 2: I started with a fresh copy of raspbian jese, reinstalled pihole, ddclient, and pivpn. Exact same symptoms, VPN connects and I can't even reach my routers internal IP.

Troubleshoot step 3: I took a new/different Raspberry Pi3, installed default jesse on it, did apt-get update/upgrade. Gave it a new/different static IP on my LAN, configured new port forwarding for different port than I was using previously and then installed/setup PiVPN with this new info. SAME EXACT SYMPTOMS AS ABOVE.

**Comment by R3Z1H** [comment]
really sorry for the late reply...

@Nephilimi did you try executing this command? `iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE` (assuming your Pi in connected through ethernet)... just copy paste this code with sudo, then connect to your VPN with your phone & browse something. If it don't work, then you gota try different forums... OpenVPN community forum is a good place to start or raspberry pi forum...

I personally feel some RPi update caused this conflict with PiVPN..anyways..

@stualoo yea Raspbian Jessie

@0-kaladin `root@raspberrypi:~# cat /etc/iptables/rules.v4
# Generated by iptables-save v1.4.21 on Sat Feb 18 05:53:58 2017
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
COMMIT
# Completed on Sat Feb 18 05:53:58 2017
# Generated by iptables-save v1.4.21 on Sat Feb 18 05:53:58 2017
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [1:184]
:POSTROUTING ACCEPT [1:184]
-A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE
COMMIT
# Completed on Sat Feb 18 05:53:58 2017
----------------------------------------------
root@raspberrypi:~# netfilter-persistent save
run-parts: executing /usr/share/netfilter-persistent/plugins.d/15-ip4tables save
run-parts: executing /usr/share/netfilter-persistent/plugins.d/25-ip6tables save
----------------------------------------------
root@raspberrypi:~# cat /etc/iptables/rules.v4
# Generated by iptables-save v1.4.21 on Mon Feb 27 00:30:45 2017
*nat
:PREROUTING ACCEPT [5373:729437]
:INPUT ACCEPT [1302:260571]
:OUTPUT ACCEPT [1934:207628]
:POSTROUTING ACCEPT [244:22292]
-A POSTROUTING -o eth0 -j MASQUERADE
COMMIT
# Completed on Mon Feb 27 00:30:45 2017
# Generated by iptables-save v1.4.21 on Mon Feb 27 00:30:45 2017
*filter
:INPUT ACCEPT [1523690:2074714767]
:FORWARD ACCEPT [279366:231778950]
:OUTPUT ACCEPT [803500:363224637]
COMMIT
# Completed on Mon Feb 27 00:30:45 2017`

ok this is the result...could you explain what happened after i ran `netfilter-persistent save`? i see different results than the first... :S

**Comment by R3Z1H** [comment]
@0-kaladin also i just got this error trying to do a `apt full-upgrade`
`Errors were encountered while processing:
 netfilter-persistent
 iptables-persistent
E: Sub-process /usr/bin/dpkg returned an error code (1)`

**Comment by Nephilimi** [comment]
> @Nephilimi did you try executing this command? iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE (assuming your Pi in connected through ethernet)... just copy paste this code with sudo, then connect to your VPN with your phone & browse something. If it don't work, then you gota try different forums... OpenVPN community forum is a good place to start or raspberry pi forum...
> 
> I personally feel some RPi update caused this conflict with PiVPN..anyways..

Did this and it is working again. Given I can't get it working with a brand new up to date install of Jesse I would have to agree with you.

**Comment by raffib33** [comment]
I was having the same issue. I ran "iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE" which solved the issue. Still need to run this command after each reboot. Reading other comments I don't believe this issue has been resolved yet?

**Comment by R3Z1H** [comment]
@raffib33 i found a fix for this in raspberry pi forum.. basically you write few lines of code which tells iptables what to do. then you tell iptables to execute those codes every time the Pi boots. This is a work around, so it might cause your iptables to not update properly (i posted an example in my previous comment) but the VPN works in every reboot. anyways here is the link [https://www.raspberrypi.org/forums/viewtopic.php?t=17694&p=176040](url) scroll down to malicious's comment where he explains the steps...

**Comment by stualoo** [comment]
@0-kaladin 
Here is my output of the commands:
`pi@pi3:~ $ **sudo cat /etc/iptables/rules.v4**
# Generated by iptables-save v1.4.21 on Thu Mar  2 00:13:52 2017
*filter
:INPUT ACCEPT [1:69]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [1:40]
COMMIT
# Completed on Thu Mar  2 00:13:52 2017
# Generated by iptables-save v1.4.21 on Thu Mar  2 00:13:52 2017
*nat
:PREROUTING ACCEPT [2:134]
:INPUT ACCEPT [2:134]
:OUTPUT ACCEPT [4:1697]
:POSTROUTING ACCEPT [4:1697]
-A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE
COMMIT
# Completed on Thu Mar  2 00:13:52 2017
pi@pi3:~ $ **sudo netfilter-persistent save**
run-parts: executing /usr/share/netfilter-persistent/plugins.d/15-ip4tables save
run-parts: executing /usr/share/netfilter-persistent/plugins.d/25-ip6tables save
pi@pi3:~ $ **sudo cat /etc/iptables/rules.v4**
# Generated by iptables-save v1.4.21 on Thu Mar  2 00:57:00 2017
*nat
:PREROUTING ACCEPT [79:5671]
:INPUT ACCEPT [75:5463]
:OUTPUT ACCEPT [74:5925]
:POSTROUTING ACCEPT [74:5925]
-A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE
COMMIT
# Completed on Thu Mar  2 00:57:00 2017
# Generated by iptables-save v1.4.21 on Thu Mar  2 00:57:00 2017
*filter
:INPUT ACCEPT [5349:291957]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [8224:9452459]
COMMIT
# Completed on Thu Mar  2 00:57:00 2017'

It looks like the rules are updating/saving as the timestamp changes and the rules exist.
See CoderCoyote's post on https://github.com/pivpn/pivpn/issues/182
It seems running just `netfilter-persistent start` works, as the rules are there. Putting that line in /etc/rc.local works, but as CoderCoyote says, should netfilter-persistent start on it's own on reboot? :-)

**Comment by 0-kaladin** [comment]
shouldn't need to do that every time.  can you test by removing that line from rc.local.
run ONCE:
`invoke-rc.d netfilter-persistent start`
as root.  then run 
`netfilter-persistent save`
then reboot and see if the rules are there and loaded still or not.

**Comment by Nephilimi** [comment]
ran into this after a apt-get dist-upgrade, possibly related? Is this not connecting to the local network going to be fixed with an update to PiHole?

> Setting up netfilter-persistent (1.0.3+deb8u1) ...
>update-rc.d: warning: start and stop actions are no longer supported; falling back to defaults
>A dependency job for netfilter-persistent.service failed. See 'journalctl -xn' for details.
>invoke-rc.d: initscript netfilter-persistent, action "start" failed.
>dpkg: error processing package netfilter-persistent (--configure):
> subprocess installed post-installation script returned error exit status 1
>dpkg: dependency problems prevent configuration of iptables-persistent:
> iptables-persistent depends on netfilter-persistent (= 1.0.3+deb8u1); however:
>  Package netfilter-persistent is not configured yet.

**Comment by dpaight** [comment]
Thanks very much, R3Z1H. I've placed the command you suggested in .bashrc, and all is right again: pivpn is working perfectly, now.

**Comment by Nephilimi** [comment]
BTW if this bug hits you I realized that while the VPN is connected and you can't reach anything on the LAN you can reach the raspberry itself. So just SSH into it and run pivpn -d and it will fix your tables and grant LAN access. Not a persistent fix but avoids doing any workarounds.

**Comment by Nephilimi** [comment]
In troubleshooting other things I just configured a brand new Pi3 using the new Jesse lite 2017-03-02 image, still has the same problem. I find this a bit odd as this is supposed to be the recommended configuration.

**Comment by Nephilimi** [comment]
I was doing something else with this device today and noticed that after a reboot it is working again. Not clear if it was something I did or not.

**Comment by jrddyson** [comment]
I had the same issue and followed the fix here: https://www.raspberrypi.org/forums/viewtopic.php?f=63&t=174648

In brief, I had to comment out all three lines (lp, ppdev and parport_pc) in the /etc/modules-load.d/cups-filters.conf file as we don't have those in our Pi.

These were stopping the netfilter from running and bringing up our rules.

**Comment by ljcp** [comment]
I followed the @jrddyson and it works for me in every restart

**Comment by killermosi** [comment]
As mentioned before, #151 and #182 are related, and the actual issue is a messed up configuration by one of the latest Raspbian updates.

I suppose that this issue will be fixed in the future, but should we stick this solution into the wiki or something?

**Comment by Jswee1** [comment]
Thanks @jrddyson Works now

**Comment by cfcolaco** [comment]
@redfast00 this one looks solved by now ... its working and this issue no longer happen ... 

Thank you redfast.

**Comment by pr4xx** [comment]
Using a fresh ubuntu 16 installation together with this script does not get me a working installation. I can connect but my client has no internet. The iptable rule was not in the saved file. But even adding the rule does not do the trick. Still no internet. Debug does not output any important messages.

**Comment by cfcolaco** [comment]
@pr4xx please provide the output of:

```
pivpn debug
sudo iptables -T NAT -S 
sudo iptables -S 
cat /etc/iptables/rules.v4
cat /etc/server.conf (hide any public IP address)
```

I am a currently out of time to help however, this info will be really helpful for me or anyone to help you

**Comment by pr4xx** [comment]
pivpn debug: https://pastebin.com/UQNF80v7

sudo iptables -T NAT -S
iptables v1.6.0: unknown option "-T"
Try `iptables -h' or 'iptables --help' for more information.

sudo iptables -S 
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT

cat rules.v4

# Generated by iptables-save v1.6.0 on Mon Jul 17 21:58:58 2017
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [1:152]
:POSTROUTING ACCEPT [1:152]
-A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE
COMMIT
# Completed on Mon Jul 17 21:58:58 2017
# Generated by iptables-save v1.6.0 on Mon Jul 17 21:58:58 2017
*filter
:INPUT ACCEPT [790:91821]
:FORWARD ACCEPT [231:15574]
:OUTPUT ACCEPT [476:61926]
COMMIT
# Completed on Mon Jul 17 21:58:58 2017

cat server.conf
cat: /etc/server.conf No such file

**Comment by louis002** [comment]
I had the same problems until I followed this great step by step tutorial on how to route the VPN traffic past my firewall.  Jump to section 4 if you already have OpenVPN setup. 
https://www.digitalocean.com/community/tutorials/how-to-set-up-and-configure-an-openvpn-server-on-centos-7

**Comment by Hyukishi** [comment]
> `iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE` 

This resolved my issue. The only thing I had to change was the interface from `eth0` to `wlan0` because the Pi in use is only connected via wireless.

**Comment by aashishvanand** [comment]
I still have this issue in RPi4 connected via ethernet. Once I run sudo iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE all my connected devices get internet

**Comment by eddiecorrigall** [comment]
I switched from wlan0 to a wired connection. I was able to connect to establish a VPN tunnel and interact with the local network, but was not able to connect to any outside network.

This is what I did to resolve my issue:

Updated the interface from wlan0 to my new interface in these files:
- `/etc/pivpn/setupVars.conf`
- `/etc/iptables/rules.v4`
- `/etc/iptables/rules.v6`

Then I rebooted the machine. I did not need to run any iptables commands.

**Comment by x011** [comment]
For some unknown reason, the default `eth0` name was changed to `enxb827ebdccf9d`. 
Once I changed `eth0` to `enxb827ebdccf9d` on the following files and `rebooted`, it worked as expected:

```
/etc/pivpn/setupVars.conf
/etc/iptables/rules.v4
/etc/iptables/rules.v6
```

**The question is to know why the default network card name was changed because this breaks the config and the all point of `piVPN`, which is make things easy.**

Tks @eddiecorrigall

**Comment by orazioedoardo** [comment]
@x011 enx\<macaddress\> is usually the name of a USB wifi or ethernet adapter.

**Comment by Macherte** [comment]
@eddiecorrigall Worked like a charm, thank you!

**Comment by cconcannon** [comment]
for what it's worth, I ran into this issue in Sept 2021 while setting up a Pi Zero with PiVPN and this thread was one of the top troubleshooting threads that popped up while searching for a solution. My solution ended up being very, very simple:

`pivpn debug`

Here's my result... I needed to set several Iptables rules, but the interactive menu allowed me to simply type `Y` to fix it all:

```shell
...
::::		Self check		 ::::
:: [OK] IP forwarding is enabled
:: [ERR] Iptables MASQUERADE rule is not set, attempt fix now? [Y/n] Y
Done
:: [ERR] Iptables INPUT rule is not set, attempt fix now? [Y/n] Y
Done
:: [ERR] Iptables FORWARD rule is not set, attempt fix now? [Y/n] Y
Done
:: [OK] WireGuard is running
:: [OK] WireGuard is enabled (it will automatically start on reboot)
:: [OK] WireGuard is listening on port 51820/udp
```

After finishing, it works like a charm. Thanks for everyone's input here.

**Comment by Zovereign** [comment]
I have the same problem, but it's fixed now.
After setting up and configured everything, easiest way it to run
`pivpn -d`

After that, the problem still remained, don't worry it is because your network need to restart:
sudo service networking restart

Test it. If it is working now, you will need to configured you pi by running
`sudo rasp-config`

Then choose **System Options**, under **Network at boot** choose **YES**.

You should be fine now. The reason it is not working that I found is that. because there is no network when pivpn start.
So the last part is to make sure that has network before system logon.

You can do another way round as well by using crontab to restart network when user logon. I prefered using raspi-config method.
