### ISSUE TITLE
Can't connect VPN (connected for a split second)

### ISSUE THREAD

**Issue by drekkie** [pivpn/pivpn#208]
I can't connect to my VPN anymore. UDP port 1194 is open. What's wrong?

curl install.pivpn.io | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   178  100   178    0     0    563      0 --:--:-- --:--:-- --:--:--   563
bash: line 1: html: No such file or directory
bash: line 2: syntax error near unexpected token `<'
'ash: line 2: `<head><title>301 Moved Permanently</title></head>

**Comment by redfast00** [comment]
Just to clarify, have you installed PiVPN completely (setting up hostname, keys,...) or are you stuck at the install? Has it worked before?

**Comment by drekkie** [comment]
Yes, yes and yes it worked before

Op 24 feb. 2017 19:45 schreef "redfast00" <notifications@github.com>:

**Comment by redfast00** [comment]
Do you have a static WAN and LAN IP?

**Comment by drekkie** [comment]
Yes nothing changed, both static and same as before

**Comment by redfast00** [comment]
Can the client device ping the server? Can your phone connect to the internet? I don't really knpw what else it could be

**Comment by drekkie** [comment]
forgot the ping command, can you tell me?

**Comment by redfast00** [comment]
I think it's `ping` on both Linux and Windows

**Comment by drekkie** [comment]
Yeah I can ping the server

pi@raspberrypi:~ $ ping 10.8.0.1
PING 10.8.0.1 (10.8.0.1) 56(84) bytes of data.
64 bytes from 10.8.0.1: icmp_seq=1 ttl=64 time=0.263 ms
64 bytes from 10.8.0.1: icmp_seq=2 ttl=64 time=0.146 ms
64 bytes from 10.8.0.1: icmp_seq=3 ttl=64 time=0.136 ms
64 bytes from 10.8.0.1: icmp_seq=4 ttl=64 time=0.129 ms
64 bytes from 10.8.0.1: icmp_seq=5 ttl=64 time=0.141 ms
64 bytes from 10.8.0.1: icmp_seq=6 ttl=64 time=0.142 ms
^C

**Comment by drekkie** [comment]
It's strange I can't see a mac adress, how come?

tun0      Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
          inet addr:10.8.0.1  P-t-P:10.8.0.1  Mask:255.255.255.0
          UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:2 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:100
          RX bytes:0 (0.0 B)  TX bytes:80 (80.0 B)

**Comment by redfast00** [comment]
It doesn't have a MAC address because it's not a physical interface (like eth0 or wlan0). Is the client device on the same network as the Pi? Can you ping the external address of the Pi from that device?

**Comment by GabrieleCorrieri** [comment]
Same issue, no static ip but no-ip works well with other services like vnc. Nothing change at least updates and upgrades of raspberry

**Comment by GabrieleCorrieri** [comment]
Little more debug info: on my mobile phone got a timeout after 5 tries, and more than 1kb sent and nothing reiceved. 

On raspberry with pivpn-c i see 5  different tries of connect no one from my client id that is avaiable in list. The source ip is right but it seems that it not recognizes me (or my certificate)

**Comment by GabrieleCorrieri** [comment]
Update: raspberry doesn't reach the network: isn't a DNS problema because it doesn't ping also ip addresses, outside my lan: inside is everything ok. 

At this point raspberry reiceve but cannot sends packet over network. 

Because also is sunday night and I need a working vpn connection tomorrow morning I've restored a imaged working config, but I've also imaged this not working config: if everyone wants to go deep in question I'll be put it online, or if someone else wants to help  me to discover why packets are not delivered

**Comment by drekkie** [comment]
I did an uninstall with pivpv -u and a reboot. 

After that I did a complete reinstall and I got it working again.

**Comment by drekkie** [comment]
I can connect now for a split second and then I got disconnected immediatly.


::: Generating Debug Output
:::                                     :::
::              PiVPN Debug              ::
:::                                     :::
::      Latest Commit                    ::
:::                                     :::
commit 6ce39bfec399d9a8203409a108ef27f2ee29327a
Author: 0-kaladin <0.kaladin@gmail.com>
Date:   Mon Feb 27 21:01:23 2017 -0500

    Update README for IRC channel

    Due to discontinuation of Google Spaces
:::                                     :::
::      Recursive list of files in       ::
::      /etc/openvpn/easy-rsa/pki        ::
:::                                     :::
/etc/openvpn/easy-rsa/pki/:
ca.crt
Default.txt
derek.ovpn
dh2048.pem
index.txt
index.txt.attr
index.txt.attr.old
index.txt.old
issued
private
serial
serial.old
ta.key

/etc/openvpn/easy-rsa/pki/issued:
derek.crt
server.crt

/etc/openvpn/easy-rsa/pki/private:
ca.key
derek.key
server.key
:::                                     :::
::      Output of /etc/pivpn/*           ::
:::                                     :::
:: START /etc/pivpn/DET_PLATFORM ::
Raspbian
:: END /etc/pivpn/DET_PLATFORM ::
:: START /etc/pivpn/INSTALL_PORT ::
1194
:: END /etc/pivpn/INSTALL_PORT ::
:: START /etc/pivpn/INSTALL_PROTO ::
udp
:: END /etc/pivpn/INSTALL_PROTO ::
:: START /etc/pivpn/INSTALL_USER ::
pi
:: END /etc/pivpn/INSTALL_USER ::
:: START /etc/pivpn/NO_UFW ::
1
:: END /etc/pivpn/NO_UFW ::
:: START /etc/pivpn/pivpnINTERFACE ::
eth0
:: END /etc/pivpn/pivpnINTERFACE ::
:: START /etc/pivpn/REVOKE_STATUS ::
0
:: END /etc/pivpn/REVOKE_STATUS ::
:::                                     :::
:: /etc/openvpn/easy-rsa/pki/Default.txt ::
:::                                     :::
client
dev tun
proto udp
remote 86.89.70.102 1194
resolv-retry infinite
nobind
persist-key
persist-tun
key-direction 1
remote-cert-tls server
tls-version-min 1.2
verify-x509-name server name
cipher AES-256-CBC
auth SHA256
comp-lzo
verb 1
:::                                     :::
::      Debug Output Complete            ::
:::                                     :::
:::
::: Debug output completed above.
::: Copy saved to /tmp/debug.txt

![2017_03_05_22 30 59](https://cloud.githubusercontent.com/assets/25414493/23591631/94252dd6-01f3-11e7-918e-41b2a52de373.png)
