### ISSUE TITLE
Can't access other devices in network

### ISSUE THREAD

**Issue by bubu8300** [pivpn/pivpn#209]
I've installed and run PiVpn on my raspbery pi.
It worked. The script is so simple and easy. But now i come accros a little problem.
On my LAN I have an ipcam that I can connect via browser or android app, and also some other service on another device. 
Until 2 weeks ago I could acces ipcam via android app under my vpn connection via pivpn from my phone, but nothing else on my network. So I decided to do an update to my pi. Since that update over my vpn connection I only get internet but nothing on my netowrk, not even the ipcam, that worked before.
I also have a router but there is only port forword for pivpn and nothing else.
What could be the problem and what can I do to acces my LAN over my vpn connection.
10x

**Comment by cfcolaco** [comment]
@bubu8300 there goes a long time since you posted, I apologize for that. 
do you still require help or can this be closed?

**Comment by bubu8300** [comment]
I've solved it. I don't remember exactly the command but i had to run something in a terminal. It had something to do with updating the OS. If someone else is interested I could look for it and post a reply.

**Comment by cfcolaco** [comment]
thank you for your feedback @bubu8300 . if you don't remember don't worry! I will be around to help out other users! 

glad you figured it out. once again sorry for leaving you without an answer so many time! =/
