### ISSUE TITLE
Would like a VPN Gateway PIVPN

### ISSUE THREAD

**Issue by shadowaero** [pivpn/pivpn#210]
# PiVPN Issue Template

## Console output of `curl install.pivpn.io | bash`
```

```

## Console output of `pivpn add` or `pivpn add nopass`
```

```

## Console output of `pivpn debug`
```

```

## Issue
PIVPN is incredible.  I like the simplicity and very secure.  Could you consider a fork where you make the pi a VPN gateway.  All traffic routes through Pi that is connected to VPN Host such as PureVPN or PIA or "Insert Openvpn compatible".   It could be either ethernet or combination wifi devices to ethernet to router.

**Comment by redfast00** [comment]
While that would indeed be cool, I don't think that's in the scope of this project. I think you can use dd-wrt for this.

**Comment by shadowaero** [comment]
I want to use my raspberry Pi.  i don't think Rd-wrt would work with a pi.

**Comment by redfast00** [comment]
https://wiki.openwrt.org/toh/raspberry_pi_foundation/raspberry_pi don't know if it will do what you want, but it's worth a shot
