### ISSUE TITLE
root access required to build keys

### ISSUE THREAD

**Issue by deanjwade** [pivpn/pivpn#211]
When I attempted an install from Jessie Lite following the instructions on http://www.pivpn.io/ it failed to generate the keys.

the solution was to have root access.

I recommend that you add `sudo -s` as the first stage of install for noobs like myself.

**Comment by redfast00** [comment]
That's strange... It should normally autoelevate to root. Do you still have the logs of the failed installation?

**Comment by deanjwade** [comment]
No I do not, but could recreate if you need - this was a totally fresh installation with fresh formatted Sandisk 32GB microSD.

**Comment by cfcolaco** [comment]
@redfast00 what about this one? it seems that no one else had the same issue, could have been an isolated case.

**Comment by redfast00** [comment]
There are no logs and no way to reproduce. Closing this
