### ISSUE TITLE
pkcs12 certificate generation for ChromeOS

### ISSUE THREAD

**Issue by deanjwade** [pivpn/pivpn#212]
ChromeOS does not as yet support ca.crt key format (this request has been on the back-burner for a couple of years, perceived as low priority!), it currently requires the OpenVPN certificate to be in pkcs12 format.
More details here:
https://goo.gl/CvJQiR

Would you be able to include the generation of pksc12 format in your script please?

This would help make RPi & pivpn more popular as ChromeOS users would be more likely to adopt.

**Comment by redfast00** [comment]
This has been discussed before (see #27). If you really want this and got it working, you can maybe open a PR.
