### ISSUE TITLE
DDWRT client

### ISSUE THREAD

**Issue by solohelp** [pivpn/pivpn#218]
Hi
PiVPN is configured and working well from the openvpn app on ipad.
Im now trying to setup a DDWRT to act as client to pivpn but am having no luck making it connect.  If anybody has successfully used DDWRT as client can you post a screenshot of your setup.
Here are the config options available in DDWRT.
maybe if I knew which ciphers were used I could work through it.  what commands in pivpn would tell me this info?
http://imgur.com/a/SoeAN

**Comment by fyellin** [comment]
The configuration file should give you all the information you need.

In any case the cipher is AES-256.

**Comment by solohelp** [comment]
so frustrating how hard you nerds make this ;)
finally got it working!
Im using DDwrt v3.0-r28788 std

with a default client setup on pivpn with no username/password

encryption cipher = AES-256 CBC
hash algorithm = SHA256
user pass auth = disable
tls cipher = none
lzo compression = yes
nat= enable
firewall = disable
ipaddress=blank
subnet =blank
tunnel UDP MSS-Fix = disable
advanced option = enable
nscerttype verification = unchecked
tls authkey = openvpn static key from openvpn config file
additional config = blank
policy based routing = blank
pkcs12 key = blank
static key = blank
ca cert / public client cert / private client key are from openvpn config file.

then go to administration - commands
paste this into the box and click save firewall 
iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -j MASQUERADE

**Comment by 977hr** [comment]
I am having the same problem with connecting to my PiVPN (OpenVPN) via Linksys E1500 with DD-WRT v3.0-r42819 mega (03/30/20). Connecting to VPN using OpenVPN Connect on my computer and smartphone works flawlessly.

I'm attaching a screenshot of my setting on router and contents of the .ovpn file here:

 
![Screenshot_PiVPN_DDWRT](https://user-images.githubusercontent.com/60018512/95621385-dff6ae80-0a71-11eb-801d-abe290e6e4a9.jpg)

**######### .ovpn F #######**

client
dev tun
proto udp
remote MY.IP.ADD.RESS 1194
resolv-retry infinite
nobind
remote-cert-tls server
tls-version-min 1.2
verify-x509-name homebridge name
cipher AES-256-CBC
auth SHA256
auth-nocache
verb 3
<ca>
-----BEGIN CERTIFICATE-----
-----END CERTIFICATE-----
</ca>
<cert>
-----BEGIN CERTIFICATE-----
-----END CERTIFICATE-----
</cert>
<key>
-----BEGIN ENCRYPTED PRIVATE KEY-----
-----END ENCRYPTED PRIVATE KEY-----
</key>
<tls-crypt>
#
2048 bit OpenVPN static key
#
-----BEGIN OpenVPN Static key V1-----
-----END OpenVPN Static key V1-----
</tls-crypt>
