### ISSUE TITLE
It seems that pivpn works but all traffic a bit strange.

### ISSUE THREAD

**Issue by mingas** [pivpn/pivpn#219]
Maybe someone can explain how pivpn server works. I install pivpn on my raspberry pi 3 and I connect to my pivpn server from remote location over WAN. In my remote location I used wireless network connection and when I have successfully joined pivpn server in my network connections also I saw active local area connection. 
Then I tried to check all traffic on both connections with Wire Shark by browsing over different websites. I was able successfully open any web but when I checked my both connections Status details, on “Wireless network connection status” I saw IPv4 connectivity: Internet and on IPv6 Connectivity: No Internet access. On “Local area connection” I saw IPv4  and IPv6 connectivity: no internet access. 
On Wire Shark window with my wireless traffic I saw my local private IP and destination IP was my remote site where is my pivpn server public IP. All traffic in protocols raw  was openvpn, I not seen any http traffic so it seems like that traffic was encrypted. 
On Wire Shark window with my local area traffic I saw in source row IP from my visited websites and in my destination row I saw IP 10.8.0.2 provided to me by pivpn server. In protocol row I saw just TCP traffic and no HTTP. 
Can somebody explain how all traffic moving between pivpn server and clients? Seems that traffic between client and pivpn server encrypted but what about traffic between pivpn server and destination websites? Is all traffic routed through pivpn server raspberry pi or traffic bypasses raspberry pi? On raspberry pi cpu usage bar I see only 1% - 5% when I using it as vpn server so seems that raspberry pi don’t have any load.
Thanks.

**Comment by anaknaga** [comment]
If traffic between the client and the server is encrypted, then it's good. That's what it's supposed to do.

The VPN is useful when you're at a coffee shop for instance, so it seems like you're browsing from home (or where ever you set up the pivpn). Pivpn is good for your privacy in the face of the coffee shop or other public place, NOT anonymity. A commercial VPN might be better for privacy in the face of your ISP. Again, achieving anonymity is not what any kind of VPN is meant for, just varying degrees of privacy!

**Comment by mingas** [comment]
Can you explain me how all traffic moves between client and raspberry pi pivpn server? Is all traffic routed through pivpn server raspberry pi, or traffic bypasses raspberry pi? 
Usually Rapberry pi 3 is a relatively slow if you trying to use it as a normal PC. Even youtube videos slightly slow and hangs if you watching it directly on raspberry pi. However when I using raspberry pi 3 as a pivpn server, even if I have connected 3 clients at the same time, I can watch youtube videos on all clients with quite good speed. At the same time CPU usage on raspberry pi nearly 0%, seems that raspberry pi doing nothing and don’t have any load. I am wondering what is raspberry pi role in this case and how all traffic encrypted. In the case if traffic routed through raspberry pi with three connected clients we should see almost 100% cpu usage on raspberry pi and very slow internet speed on clients.

**Comment by anaknaga** [comment]
Your reply tells me that you have no idea what a VPN is or does. Please search the internet for more sources. There are many many places out there which explain what a VPN is and does.

Here's just a random one I picked up: https://www.howtogeek.com/133680/htg-explains-what-is-a-vpn/

Concerning the load. If you're using the Pi as a VPN, you're using `openvpn`. The Pi's load is low, because if you're doing it right, you don't even have a graphical environment! If you play youtube on a client connected to the pivpn, you're using the client's hardware for the content of the video, *not* the Pi.

So,
Client -------encrypted tunnel over the internet---------------> pivpn server ------------normal HTTP(S) traffic---------------> Internet

And back,
Internet ---------normal HTTP(S) traffic---------> pivpn server -------------encrypted tunnel over the internet------------>client

**Comment by mingas** [comment]
I know the basics about VPN, but biggest question for me was why CPU usage on raspberry pi 3 so low. I thought maybe for some reason VPN traffic bypassing pivpn server on raspberry pi, but you’re right all traffic routed through pivpn server. Yesterday I installed tshark on raspberry pi and I could clearly see openvpn traffic from remote clients. Simultaneously cpu usage on raspberry pi was very low.
Many thanks for your explanation.
