### ISSUE TITLE
Uninstalling - Installing Questions (formerly update)

### ISSUE THREAD

**Issue by planetahuevo** [pivpn/pivpn#22]
Do you recommend to remove all the packages when uninstalling for install it later?
Which ones do you recommend to remove completely?

Thanks

**Comment by 0-kaladin** [comment]
You can just hit y on everything.

**Comment by planetahuevo** [comment]
Yes, I know that. But why uninstall git (for example, the only one i know) to install it again in 5 minutes?
Is there any other package that has nothing to do with the server (like the git package) and we can skip the uninstall? 
I suppose you just recommend to uninstall everything.

**Comment by 0-kaladin** [comment]
No reason.  It really doesn't matter.
