### ISSUE TITLE
Authy/Duo 2FA

### ISSUE THREAD

**Issue by Jswee1** [pivpn/pivpn#220]
Id like two setup Authy or Duo 2FA with my RPI vpn but i have tried and failed mutiple times can anyone provide a tutorial for PiVpn

**Comment by Jswee1** [comment]
Duo's Project https://duo.com/docs/openvpn
Authy's https://www.authy.com/integrations/openvpn/

**Comment by redfast00** [comment]
We don't officially support that, but you might want to read #50.
