### ISSUE TITLE
url: (6) Could not resolve host: install.pivpn.io

### ISSUE THREAD

**Issue by jasper321** [pivpn/pivpn#221]
Im new to vpn but when i type in the command: curl -L https://install.pivpn.io | bash 
i get the error could not resolve host, what is the problem?
Thanks!

**Comment by redfast00** [comment]
Are you sure your Raspberry Pi is connected to the internet?

**Comment by jasper321** [comment]
Sorry the updates were not installed
Thanks!

Op 11 mrt. 2017 14:47 schreef "redfast00" <notifications@github.com>:
