### ISSUE TITLE
TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)

### ISSUE THREAD

**Issue by PD75** [pivpn/pivpn#225]
TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)

- Using a windows 10 laptop to connect. 
- Followed the installation instructions in: 
- Used al default settings except creating a new user with sudo rights.
- Port forwarding work on my router for my webserver and I have configured pivpn in a similar way.
- Tried googling and applied various fixes found on the internet with no luck.
- Also checked all open issues did not find this

Please advice, if you need any files let me know which ones, I have been out of linux for quite a while.

**Comment by cfcolaco** [comment]
#227 seems to be the same issue as your's, please check if any of the possible solutions fix your issue.

**Comment by PD75** [comment]
Worked with TCP, don't know why though!

**Comment by rbucker** [comment]
I know this is closed... what did you change to TCP? Server, Client, Rules or all?

**Comment by PD75** [comment]
@rbucker During installation you get to change from UDP to TCP. It is just the communication protocol of the VPN tunnel I guess.

**Comment by cfcolaco** [comment]
@PD75 @rbucker TCP and UDP are communication protocols if you want to change from one to another, you will have to edit /etc/openvpn/server.conf and change every client config file to use the new protocol.
