### ISSUE TITLE
Add paid vpn service

### ISSUE THREAD

**Issue by lowviz** [pivpn/pivpn#226]
After weeks of trying to install openvpn successfully I got everything to work with Pivpn. Thank You so much. Everything is working along with dns requests going through pi-hole.

Now I would like to have all my traffic go through my paid vpn in order to hide my traffic from my ISP. Because of my old router it is necessary to have the pi handle it. I am confused on how to handle this with the certificates. If this is possible could you please provide me with what needed to do ?

**Comment by redfast00** [comment]
This isn't something we currently support: we support to have the Pi act as a VPN server, so you can connect to it from some place you don't trust. If you don't trust your ISP, you can set up your client device to connect to the paid VPN.

**Comment by lowviz** [comment]
Thank you for response. It would be a wonderful addition in the future

**Comment by EWouters** [comment]
I think you can do this if you setup your pi to use your paid vpn connection and choose the interface the paid vpn runs on during the pivpn installation.

**Comment by redfast00** [comment]
That definitely sounds interesting. Let me know how it goes (I don't know if the Pi will be able to handle that tho)

**Comment by ZenZendra** [comment]
Hello,
Is this now maybe possible.
I want to use PiVpn with PiHole and connect outside of my network with my phone so i have acces to my hard drive and don't have ads :) But i would also like that PiVpn connects to my Expressvpn paid account, so i can browse anonymously, with all those things i mentioned.
Does anybody knows how to set this up?
I found one tutorial, but it doesn't work for me.
Thanks
