### ISSUE TITLE
Can't connect from PC, but can from android app - same opvn file

### ISSUE THREAD

**Issue by oenc** [pivpn/pivpn#227]
Hi, 

I'm quite happily running piVPN and connecting from my android phone using the open vpn app.  It works really well thank you.

However when I try and connect from my computer (win 10) using the open vpn client software and the same .opvn file, I get the following errors:

> Thu Mar 16 11:35:03 2017 OpenVPN 2.4.0 x86_64-w64-mingw32 [SSL (OpenSSL)] [LZO] [LZ4] [PKCS11] [AEAD] built on Jan 31 2017
> Thu Mar 16 11:35:03 2017 Windows version 6.2 (Windows 8 or greater) 64bit
> Thu Mar 16 11:35:03 2017 library versions: OpenSSL 1.0.2k  26 Jan 2017, LZO 2.09
> Enter Management Password:
> Thu Mar 16 11:35:10 2017 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
> Thu Mar 16 11:35:10 2017 TCP/UDP: Preserving recently used remote address: [AF_INET]
> Thu Mar 16 11:35:10 2017 UDP link local: (not bound)
> Thu Mar 16 11:35:10 2017 UDP link remote: [AF_INET]
> Thu Mar 16 11:35:15 2017 OpenSSL: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
> Thu Mar 16 11:35:15 2017 TLS_ERROR: BIO read tls_read_plaintext error
> Thu Mar 16 11:35:15 2017 TLS Error: TLS object -> incoming plaintext read error
> Thu Mar 16 11:35:15 2017 TLS Error: TLS handshake failed
> Thu Mar 16 11:35:15 2017 SIGUSR1[soft,tls-error] received, process restarting

Then this just loops around.

The android app is disconnected at the moment, so there is (or shouldn't be) a conflict.

Any thoughts? (apologies I can't post pivpn debug as its on the pi which I can't access from the pc because of this error)

**Comment by cfcolaco** [comment]
Are You executing OpenVPN client on windows with Administrator Privileges?

**Comment by cfcolaco** [comment]
Tested, Starting OpenVPN on windows without Administrator privileges causes Windows client not being able to reach other machines in the Remote local network. please try and give some feedback.

**Comment by oenc** [comment]
Thanks, I have always been running it as administrator, but I tried again with admin and without and had the same error (as above) each time.

**Comment by cfcolaco** [comment]
Had someone this weekend with a similar issue, that was the problem, was not starting OpenVPN as administrator, can you provide more information?
Server side logs and Config files (booth client and server side), would be useful to properly troubleshoot the problem. 
I'm not an expert but trying to help.

**Comment by oenc** [comment]
I've just done a fresh install of openvpn client on another pc to make sure it wasnt the issue.  I still get the same client log as posted above, the openvpn.log on my server is saying:

> Sun Mar 19 20:40:24 2017 xxxxx(removed):58777 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
> Sun Mar 19 20:40:24 2017 xxxxx(removed):58777 TLS Error: TLS handshake failed

I haven't touched the server.conf file at all, so its exactly as the server_config.txt file in the git code page.

My client config (with bits removed):

> client
> dev tun
> proto udp
> remote (removed but correct)
> resolv-retry infinite
> nobind
> persist-key
> persist-tun
> key-direction 1
> remote-cert-tls server
> tls-version-min 1.2
> verify-x509-name SRVRNAME name
> cipher AES-256-CBC
> auth SHA256
> comp-lzo
> verb 1


This is followed by 2x certificats, an encrypted key and then a static key.

**Comment by cfcolaco** [comment]
Weird if you have everything done by default pivpn settings, should definitely not happen, I have seen similar errors but they happen with some typo's in config files when manually setting up OpenVPN.
makes little sense not happening with android and happening only with Windows. 

As today I have no available time, hope someone with more knowledge comes to help, meanwhile, I will try to replicate and make some more tests, hopefully, come with a solution! 

for now, will just make some wild guesses,

have you managed somehow to move the ta.key?
please check on the server.conf file if the paths for the cert files are correct. 

could it be tls verssion issue? 
try commenting the tls-version-min 1.2 in both server and client config files 


sorry for not beeing much useful, trying to do my best to help out! as i said, have some knowledge but not an expert! ;)

**Comment by oenc** [comment]
Thanks for your suggestions, I have checked all the paths and they seem right.  The ta.key is also on the server as expected.
I've tried commenting the tls version too, but the same issue.
Thanks
Owen

**Comment by cfcolaco** [comment]
Today is beeing a busy day, so i did not had the chance to make some experiments yet, however, came to mi mind one of mine wild guesses! =P 

Can you please try to generate a new client .ovpn file and directly copy the file to the windows machine? 
( i know server.conf allows for the same client certificates to be used, just testing another theory )

**Comment by oenc** [comment]
No problem, I appreciate your help!  

I actually tried that yesterday though but it didn't make any difference sorry!

**Comment by oenc** [comment]
The install process (on pc) is literally just: 
1. Install
2. Import opvn file
or have I just missed a step somewhere?

**Comment by cfcolaco** [comment]
1 - Install 
2 - Mouse Right Click > Run as Administrator
3 - Import .ovpn file

pretty much it!

**Comment by cfcolaco** [comment]
Did a quick google, check here:

https://openvpn.net/index.php/open-source/faq/79-client/253-tls-error-tls-key-negotiation-failed-to-occur-within-60-seconds-check-your-network-connectivity.html

**Another possible cause is that the windows firewall is blocking access for the openvpn.exe binary. You may need to whitelist (add it to the "Exceptions" list) it for OpenVPN to work.**

worth check it out also!

**Comment by PD75** [comment]
I had same problems from windows and android, it connected so I could see the connection on the pi, but still the same error. When I changed to TCP it all worked. Unfortunately I do not know if it was my operator that has blocked UDP, limitations in my router or if it was a windows firewall issue.

**Comment by oenc** [comment]
Hi guys, thanks for the suggestions.  I have added an exception to windows firewall but it made no difference.  I changed the protocol to TCP too on both server and client (just by overtyping udp in both server.conf and the opvn file) - I guess this is the way to do it?

It still connects over TCP on my phone with no problems, but on my PC:

> Tue Mar 21 08:21:06 2017 TCP/UDP: Preserving recently used remote address: [AF_INET]xxxxxxxx
> Tue Mar 21 08:21:06 2017 Attempting to establish TCP connection with [AF_INET]xxxxxxxx [nonblock]
> Tue Mar 21 08:21:07 2017 TCP connection established with [AF_INET]xxxxxxxxx
> Tue Mar 21 08:21:07 2017 TCP_CLIENT link local: (not bound)
> Tue Mar 21 08:21:07 2017 TCP_CLIENT link remote: [AF_INET]xxxxxxxxxxx
> Tue Mar 21 08:21:07 2017 OpenSSL: error:14077102:SSL routines:SSL23_GET_SERVER_HELLO:unsupported protocol
> Tue Mar 21 08:21:07 2017 TLS_ERROR: BIO read tls_read_plaintext error
> Tue Mar 21 08:21:07 2017 TLS Error: TLS object -> incoming plaintext read error
> Tue Mar 21 08:21:07 2017 TLS Error: TLS handshake failed
> Tue Mar 21 08:21:07 2017 Fatal TLS error (check_tls_errors_co), restarting
> Tue Mar 21 08:21:07 2017 SIGUSR1[soft,tls-error] received, process restarting

**Comment by EWouters** [comment]
Does it work if you change the remote ip in the .ovpn file to the local ip of the pi?

**Comment by oenc** [comment]
Hi, I have tried that from a machine on the same network (obvious, but just to make sure you know ive done it) and get the following:

Client

> Tue Mar 21 20:08:34 2017 TCP/UDP: Preserving recently used remote address: [AF_INET]192.168.0.2:1194
> Tue Mar 21 20:08:34 2017 UDP link local: (not bound)
> Tue Mar 21 20:08:34 2017 UDP link remote: [AF_INET]192.168.0.2:1194  ****HANGS FOR MAYBE 1 MIN***
> Tue Mar 21 20:09:34 2017 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
> Tue Mar 21 20:09:34 2017 TLS Error: TLS handshake failed
> Tue Mar 21 20:09:34 2017 SIGUSR1[soft,tls-error] received, process restarting

The server log has no entries for this time.

If it wasnt for the android client working perfectly, I'd try re-installing etc...

**Comment by EWouters** [comment]
Ok, so the problem is not in your router.

Have you tried multiple machines? (Just to rule out any client errors)

**Comment by oenc** [comment]
Yes, I've tried it from win 10 and win 7, outside and inside the home network, error messages are identical for each.  Have also confirmed it working on android inside and outside home network.

**Comment by EWouters** [comment]
I'm out of idea's. I guess you could try a re-install.

**Comment by cfcolaco** [comment]
Me neither, it doesn't seem to be a piVPN bug, more of a client issue, or some misconfiguration somewhere in the way that we are not beeing able to track down.

**Comment by oenc** [comment]
No worries, thanks both for your help - at least we have identified what the problem isnt!

**Comment by 0-kaladin** [comment]
Try removing the tls-version-min line from your ovpn file used on Windows.

**Comment by gswin** [comment]
Hi, I'm having exactly the same issue.

Actually it's working with OpenVPN client 2.3.9 but not with any newer versions. On my phone it's still working fine with any versions...

> Tue Apr 04 15:33:11 2017 MANAGEMENT: >STATE:1491312791,RESOLVE,,,,,,
> Tue Apr 04 15:33:11 2017 TCP/UDP: Preserving recently used remote address: [AF_INET]87.67.209.213:1194
> Tue Apr 04 15:33:11 2017 Socket Buffers: R=[65536->65536] S=[65536->65536]
> Tue Apr 04 15:33:11 2017 UDP link local: (not bound)
> Tue Apr 04 15:33:11 2017 UDP link remote: [AF_INET]87.67.209.213:1194
> Tue Apr 04 15:33:11 2017 MANAGEMENT: >STATE:1491312791,WAIT,,,,,,
> Tue Apr 04 15:33:11 2017 MANAGEMENT: >STATE:1491312791,AUTH,,,,,,
> Tue Apr 04 15:33:11 2017 TLS: Initial packet from [AF_INET]87.67.209.213:1194, sid=719610b4 74f92f23
> Tue Apr 04 15:34:11 2017 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
> Tue Apr 04 15:34:11 2017 TLS Error: TLS handshake failed
> Tue Apr 04 15:34:11 2017 SIGUSR1[soft,tls-error] received, process restarting
> Tue Apr 04 15:34:11 2017 MANAGEMENT: >STATE:1491312851,RECONNECTING,tls-error,,,,,
> Tue Apr 04 15:34:11 2017 Restart pause, 5 second(s)

**Comment by oenc** [comment]
Hi, I actually managed to get this resolved by removing both lines from my config file (on my PC version, but NOT changing the one on my phone.
tls-version-min 1.2
verify-x509-name SRVRNAME name

**Comment by charlieholden73** [comment]
As per oenc removing the tls-version-min config param from the server config file AND the windows client ovpn file worked for me. THANKS!!!!
