### ISSUE TITLE
routing pvpn to pihole

### ISSUE THREAD

**Issue by batman84** [pivpn/pivpn#228]
I have rpi wired to openwrt router (mr3420)
I installed pi hole and pi-vpn.

Pi hole works normal. But when i connect to my vps, pi hole is not blocking ads.

how to route my pivpn connection through pi hole?

any help would be appreciate :)

Thanks

**Comment by cfcolaco** [comment]
Think that editing /etc/openvpn/server.conf and changing:

push "dhcp-option DNS 8.8.8.8"
push "dhcp-options DNS 8.8.4.4"

Might do the trick. comment the second line replace the DNS ip with the raspberry own ip address.

push "dhcp-option DNS 192.168.1.XXX"
push "dhcp-options DNS 8.8.8.8"

or something like this, leaving google DNS as secondary in case something goes wrong with pihole

Give some feedback after you try it out please! 

@0-kaladin noticed there isn't any feature in pivpn commands to change the DNS server in case someone needs to change it after installing pivpn, any plans to add that feature? I can try to add it if you wish.

**Comment by EWouters** [comment]
This is explained in the [wiki](https://github.com/pivpn/pivpn/wiki/FAQ#installing-with-pi-hole).

**Comment by batman84** [comment]
cfcolaco thanks man for reply. Unfortunately that is not solved my problem.

EWouters, ya man i read it. Still just tried to follow guide from wiki, but still having this trouble.

Btw, i subscribe ssh server, they provide .ovpn config. Usually i connect to ssh server from opvpn client at my laptop (windows). I get my internet (wireless) from my router (openwrt) that wired to rpi (pi hole). I guest the problem.

I  guest the problem is in .ovpn config. It containts IP, but in pivpn i am using ip from no-ip.com or freedns.afraid.org

I hope you guys understand.

btw here is example .ovpn config i have

client
dev tun
proto udp
remote xxx.xxx.xxx.xxx 1194
route-method exe
nobind
resolv-retry infinite
persist-key
persist-tun
auth-user-pass
comp-lzo
verb 3
<ca>
blablablabla
</ca>

**Comment by EWouters** [comment]
You can try setting the pivpn DNS to the pi-hole DNS. Almost like @cfcolaco suggested in `/etc/openvpn/server.conf`:
```
push "dhcp-option DNS 10.8.0.1"
push "dhcp-option DNS "
```
I guess you could add an other DNS as a backup, but I don't. The reason being that if I'm able to connect to the vpn I will also be able to connect to the pi-hole.
