### ISSUE TITLE
iptables-persistent and netfilter-persistent problem when apt-get upgrade.

### ISSUE THREAD

**Issue by Amarok73** [pivpn/pivpn#231]
Hello,

The apt-get upgrade shows there are issues with iptables-presistent and netfilter-persistent. It's that only me or there are more users encountering the same problem?
Anyone can advise how to act on that?

Below is some related output from apt-get update...

> Reading package lists...
> Building dependency tree...
> Reading state information...
> 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
> 2 not fully installed or removed.
> After this operation, 0 B of additional disk space will be used.
> Setting up netfilter-persistent (1.0.3+deb8u1) ...
> update-rc.d: warning: start and stop actions are no longer supported; falling back to defaults
> A dependency job for netfilter-persistent.service failed. See 'journalctl -xn' for details.
> invoke-rc.d: initscript netfilter-persistent, action "start" failed.
> dpkg: error processing package netfilter-persistent (--configure):
>  subprocess installed post-installation script returned error exit status 1
> dpkg: dependency problems prevent configuration of iptables-persistent:
>  iptables-persistent depends on netfilter-persistent (= 1.0.3+deb8u1); however:
>   Package netfilter-persistent is not configured yet.
> 
> dpkg: error processing package iptables-persistent (--configure):
>  dependency problems - leaving unconfigured
> Errors were encountered while processing:
>  netfilter-persistent
>  iptables-persistent

**Comment by cfcolaco** [comment]
I believe it is only you! 

" netfilter-persistent, action "start" failed.
dpkg: error processing package netfilter-persistent (--configure):
subprocess installed post-installation script returned error exit status 1 "  

in your logs this is the part causing the error. something wrong with your netfilter-persistent

can you provide the output of journalctl -xn ??

**Comment by Amarok73** [comment]
Here it is:

> -- Logs begin at Fri 2017-03-31 03:00:05 CEST, end at Fri 2017-03-31 12:32:36 CEST. --
> Mar 31 12:32:19 pentagon systemd-modules-load[15266]: Failed to find module 'lp'
> Mar 31 12:32:19 pentagon systemd-modules-load[15266]: Failed to find module 'ppdev'
> Mar 31 12:32:19 pentagon systemd-modules-load[15266]: Failed to find module 'parport_pc'
> Mar 31 12:32:19 pentagon systemd[1]: systemd-modules-load.service: main process exited, code=exited, status=1/FAILURE
> Mar 31 12:32:19 pentagon systemd[1]: Failed to start Load Kernel Modules.
> -- Subject: Unit systemd-modules-load.service has failed
> -- Defined-By: systemd
> -- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
> -- 
> -- Unit systemd-modules-load.service has failed.
> -- 
> -- The result is failed.
> Mar 31 12:32:19 pentagon systemd[1]: Dependency failed for netfilter persistent configuration.
> -- Subject: Unit netfilter-persistent.service has failed
> -- Defined-By: systemd
> -- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
> -- 
> -- Unit netfilter-persistent.service has failed.
> -- 
> -- The result is dependency.
>

**Comment by cfcolaco** [comment]
not pivpn issue ... someting messed up with dependencies which i can't understand exactly what. 
try ...
sudo apt-get update --fix-missing
sudo dpkg --configure -a
sudo apt-get install -f

hope tbhis helps you

**Comment by Amarok73** [comment]
I've found [this thread](https://discourse.osmc.tv/t/failed-to-start-load-kernel-modules/3163/15) describing some CUPS modules as cause of problem with upgrade of netfilter-persistent and iptables-persistent, so I did as described there, means hashed all modules from /etc/modules-load.d/cups-filters.conf as they're for Centronics parallel communication with printer, and that time I was able to successfully update/upgrade system.

**Comment by gaborszita** [comment]
I have this problem too. But if I want to edit the /etc/modules-load.d/cups-filters.conf , it sas it's a new file.

**Comment by xdanx** [comment]
I had the same issue with one of my VPS. On Debian 8, I had in `cat /etc/modules-load.d/modules.conf`

```
# /etc/modules: kernel modules to load at boot time.
#
# This file contains the names of kernel modules that should be loaded
# at boot time, one per line. Lines beginning with "#" are ignored.

loop
acpiphp
```

Once I commented out `acpiphp`, apt worked successfully.
