### ISSUE TITLE
Revoke - Delete

### ISSUE THREAD

**Issue by Gunthervc** [pivpn/pivpn#233]
How to full remove client - certificate
When I revoke the name stays in list

**Comment by 0-kaladin** [comment]
A revoked cert will stay in the list, so you know it is revoked.  you can at that time gen a new cert with that name.

**Comment by Gunthervc** [comment]
Ok thanks you

**Comment by harmanbirdi** [comment]
Would it be possible to update <code>pivpn -l</code> so that you can also filter by the kind of records you want to see. For example <code>pivpn -l -f [valid|revoked|all</code> would show
only the record that you have chosen with -f flag.

Not specifying -f can be same as -f all.

**Comment by mnott** [comment]
Anyway, how can we really remove a certificate, in order to clean up?

"A revoked cert will stay in the list, so you know it is revoked. you can at that time gen a new cert with that name."

**Comment by emoninet2** [comment]
change directory to **/etc/openvpn/easy-rsa/pki**
read the index.txt file. It will contain the list of all the user certificates created including those revoked. The fist letter V indicates the user is valid, and R is for revoked. Delete those revoked in the list from the text file and save it. Next time you type **pyvpn -l**, it will only show the valid users.

**Comment by snakedog116** [comment]
Thanks, what about wireguard? I tried navigating to that file, but it doesn't exist for wireguard.
