### ISSUE TITLE
OSMC supported

### ISSUE THREAD

**Issue by MjBordalo** [pivpn/pivpn#237]
it would be nice if pivnc would work with the OSMC os. ty

**Comment by jellemdekker** [comment]
Can you please provide more information about what exactly is causing problems? Please read the [guidelines on contributing](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md) and use the [issue template](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md#did-you-find-a-bug) when doing so. This way others have a better idea of where to look.

**Comment by MjBordalo** [comment]
Well i abondoned that project. But i have the ideia that in general pivnc would not be able to work with OSMC.

**Comment by jellemdekker** [comment]
Okay, well I'm reading that OSMC is [apparently based on Debian](https://osmc.tv/wiki/general/installing-packages-via-apt/) and supports APT. So I'm going to go ahead and assume that PiVPN works until someone tries it out and opens an issue with more concrete information.

**Comment by josebalu** [comment]
![captura1](https://cloud.githubusercontent.com/assets/29133029/26704319/8ccb02ec-472e-11e7-93f3-eec151ea5aa8.PNG)

**Comment by josebalu** [comment]
Hello,
My OS is osmc.  
I have trouble connecting it out of network with raspberry pi.

With Raspibian perefect but OSMC don,t work. 
I need help for instalation

Thank you

**Comment by cfcolaco** [comment]
@josebalu do you still have the issue? please provide logs properly so can see where it is failing.

**Comment by InnovativeInventor** [comment]
Maybe you could try a vm

**Comment by cfcolaco** [comment]
@redfast00 what should we do about this issue? gives me some doubts =/

**Comment by redfast00** [comment]
User doesn't seem to reply, so I guess I'll close it. If another user with OSMC has an issue and can provide better logs, they can open up a new issue and we'll investigate it.
