### ISSUE TITLE
PiVPN and AirPlay server (cups)

### ISSUE THREAD

**Issue by Jswee1** [pivpn/pivpn#240]
I have a PiVPN and a cups running on my raspberry pi but my printer still doesn't show up on air print when connected to the vpn any one know how to make this work.

**Comment by darkrain-nl** [comment]
Airprint works with the bonjour protocol which is not routable and therefore only works at the local subnet by default.
I think that might be your problem, unfortunately I don't have a solution for you. Maybe somebody else knows how to make this work?

**Comment by Tntdruid** [comment]
Found a guide here https://www.technicallytom.com/2013/12/16/airprint-over-openvpn/

Did not work for me yet

**Comment by redfast00** [comment]
See #45. This is on the todo list.
