### ISSUE TITLE
Route all traffic through VPN Question

### ISSUE THREAD

**Issue by hagensieker** [pivpn/pivpn#242]
Just installed PiVPN at a relatives location as a shared VPN for family members.  LOVE the project.  Great job.  

Just one question, not sure if I have this right or not.  When I ran my own profile and installed it under Mac Viscosity I noticed the radio button for routing all traffic through the VPN was not checked. 

I had to check the block, export the profile (as .visc) then convert it back to .ovpn to share. 

Is there a way to configure up front to route all traffic through the VPN?  

I have an example here:

http://www.hagensieker.com/blog/page/?post_id=51&title=how-to-make-your-own-vpn-server

**Comment by jellemdekker** [comment]
While I believe that the checkbox in that application might be a feature they made custom for their software and file format, OpenVPN does have a [setting](https://www.sparklabs.com/support/kb/article/advanced-configuration-commands/#redirect-gateway) that does something similar. Now it's just a point of figuring out what the right value is for this setting to achieve the behavior you want.

Can you make another .ovpn export of your .visc file and upload it here so I can determine what setting is the correct one (according to the developers of Viscosity)? Of course remove any private information such as `hostname`, `port number`, `<ca>`, `<cert>`, `<key>` and `<tls-auth>` tags. ;)

**Comment by hagensieker** [comment]
This is a dump of the .visc file converted to .ovpn using a ruby script I found on the internet.

I think the route all traffic line is but not sure enough to know for sure.

redirect-gateway def1

```
# OpenVPN Config for VPNatMoms

remote hostname.org XXXX udp
pull
tls-client
key-direction 1
<tls-auth>
#
# 2048 bit OpenVPN static key
#
-----END OpenVPN Static key V1-----
</tls-auth>
persist-key
<ca>
</ca>
redirect-gateway def1
nobind
persist-tun
<cert>

</cert>
comp-lzo adaptive
dev tun
<key>
</key>
resolv-retry infinite
auth SHA256
verify-x509-name server name
remote-cert-tls server
cipher AES-256-CBC
tls-version-min 1.2

```

**Comment by jellemdekker** [comment]
Thank you for providing more information. You are indeed correct. `redirect-gateway def1` would be the setting that routes all traffic (including DNS) over the VPN. [This OpenVPN documentation article](https://openvpn.net/index.php/open-source/documentation/howto.html#redirect) gives some more information. Now it's up to @0-kaladin and @redfast00 to decide if this should become an enhancement.

**Comment by redfast00** [comment]
I think we are already doing that server-side (see [here](https://github.com/pivpn/pivpn/blob/master/server_config.txt)). I don't know if it makes a difference and if so, please make a PR (you'll have to edit `Default.txt`).

**Comment by jellemdekker** [comment]
Hmm, I hadn't noticed that yet, nice catch. It seems then that Viscosity might not be recognizing the `redirect-gateway` option properly. I found [this article](https://www.sparklabs.com/support/kb/article/exporting-and-distributing-connections/) in their documentation that gives more insight to their custom configuration options.

@hagensieker Can you try extracting the .ovpn file from your .visc file directly? Supposedly on Mac OS it's just a `.bundle` that you can open in Finder or some sort of archiver program. Please post the .ovpn here (again with the private information removed like you did last time).

**Comment by hagensieker** [comment]
This is config.conf from the visc file bundle.

```
#-- Config Auto Generated By Viscosity --#

#viscosity name VPNatMoms
remote hostname.org XXXX udp
pull
tls-client
tls-auth ta.key 1
persist-key
ca ca.crt
redirect-gateway def1
nobind
persist-tun
cert cert.crt
comp-lzo adaptive
dev tun
key key.key
resolv-retry infinite
auth SHA256
verify-x509-name server name
remote-cert-tls server
cipher AES-256-CBC
tls-version-min 1.2
```

**Comment by jellemdekker** [comment]
Thanks. Hmm, only `#viscosity name VPNatMoms` is specified. Can you check that you have enabled the checkbox for routing all traffic through the VPN and that this change was saved to the config.conf?

**Comment by hagensieker** [comment]
I can confirm the checkbox is enabled and it was saved to config.conf

My workflow when I discovered this was 

- Filezilla PiVPN file from the Pi to my Mac.  
- Double click and import into Viscosity.
- Discovered radio box for Route All Traffic not checked
- Checked and exported as .visc
- Ran Ruby script to convert to ovpn. 
- For IOS devices I used the bundle file renamed from config.conf to (i.e. john.ovpn)
- Reinstalled profile in Viscosity to ensure radio button was checked to route all traffic through VPN.

I know it worked consistently because I made three other profiles for family members and confirmed that route all traffic box was checked based on the workflow above.

**Comment by hagensieker** [comment]
also the 

redirect-gateway def1 line appears in all exported profiles (after I checked the box in viscosity and exported and converted them).

**Comment by jellemdekker** [comment]
Okay, thanks for being specific. So what you're saying is that it's worked out of the box for three other computers, but your own profile doesn't automatically enable that checkbox when you import it?

**Comment by hagensieker** [comment]
When I made profiles using pivpn add for three accounts none of them had the checkbox for routing all traffic enabled. 

For all three accounts I manually checked the box and exported the config for I could send the profiles to my (and my families) IOS devices.

For viscosity I just showed my family members that they should check that box.

**Comment by cfcolaco** [comment]
@hagensieker any updated about this? is this solved? was it a mac // viscosity related issue? or is it a pivpn side issue? since I don't use mac I have absolutely no clue about this!
