### ISSUE TITLE
Cannot Install

### ISSUE THREAD

**Issue by gxander85** [pivpn/pivpn#244]
Hi, for the past couple of days I have tried to install PiVPN and keep running into issues. Below is the install log. Any assistance would be greatly appreciated.

````
root@raspberrypi:~# curl -L https://install.pivpn.io | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   178  100   178    0     0    139      0  0:00:01  0:00:01 --:--:--   139
100 43750  100 43750    0     0  26145      0  0:00:01  0:00:01 --:--:-- 26145

:::
::: You are root.
::: Verifying free disk space...
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: Your system is up to date! Continuing with PiVPN installation...
bash: line 284: nslookup: command not found
::: Static IP already configured.
::: Using User: pi
 [|]  E: Package 'unattended-upgrades' has no installation candidate
::: 
::: Stopping OpenVPN service...Failed to stop openvpn.service: Unit openvpn.service not loaded.
 done.
sed: can't read /etc/apt/apt.conf.d/50unattended-upgrades: No such file or directory
:::
::: Checking for existing base files...
:::    Checking /etc/.pivpn is a repo...:::    Cloning https://github.com/pivpn/pivpn.git into /etc/.pivpn... done!
:::
::: Installing scripts to /opt/pivpn... done.
::: Using protocol: udp
tar: /etc/openvpn: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
chown: cannot access ‘/etc/openvpn/easy-rsa’: No such file or directory
mkdir: cannot create directory ‘/etc/openvpn/easy-rsa/pki’: No such file or directory
tee: /etc/openvpn/easy-rsa/vars: No such file or directory
bash: line 822: cd: /etc/openvpn/easy-rsa: No such file or directory
Failed to execute operation: No such file or directory
Failed to start openvpn.service: Unit openvpn.service failed to load: No such file or directory.
::: Install Complete...
```
`

**Comment by cfcolaco** [comment]
Hmmm!! something quite wrong ... seems to me that the script is failing to get OpenVPN 

Are you running the install script in a fresh raspbian?
can you please provide more details about your system?

you can solve this by installing openvpn with apt-get and then run the pivpn script ... but I can't even call this a solution! ;)

**Comment by gxander85** [comment]
Hey cfcolaco, I've been running this Pi for several months. It's mainly been used for SickRage/CouchPotato/Transmission. That's it really.
It's a 128gb microSD
I've tried a stand alone install of openvpn but that fails too. Tried that already and no luck.
I spent ages setting up my Pi and user permissions for CP/SR post-processing so I'd like to avoid a rebuild.

**Comment by cfcolaco** [comment]
@gxander85 the install script is working properly, just tested it in fresh Debian VM ... now it could be something to do with the installer code or not as I am not much into the code yet ...

@0-kaladin or @redfast00 can you guys please take a look at this?
maybe the script is failing to detect and report any failure during the process. 

from what I know and I can do to help you, and pivpn devs and maintainers to properly track the issue ...  

maybe you can try to:

    apt-get install openvpn 

and check if it installs or gives any errors and then report back to us please.

**Comment by gxander85** [comment]
Result of apt-get install openvpn. I'll note that I had the same issue trying to install easy-rsa. I have tried searching for other repo/sources and adding them and retrying, but I get the same thing.

```
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package openvpn is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'openvpn' has no installation candidate
```

**Comment by cfcolaco** [comment]
you have to check your repos at  /etc/apt/sources.list  
probably you removed the raspbian main repos. 
fix your repos issue then try pivpn installer again. 

https://www.raspbian.org/RaspbianRepository might be a good start

either way, shouldn't the installer detect a missing dependency or dependency installation errors and properly report that install has failed? @0-kaladin

**Comment by gxander85** [comment]
I had a look at the repos last night. I'll have another look after work tonight. Looking at that link, they may already be there but I will double check and get back to you.

**Comment by cfcolaco** [comment]
this is now out of the scope, however, comment any additional repos you have and leave only the official ones.

then if you want to go deeper to find what caused the issue, start your troubleshooting from there with a clean working repo list.

**Comment by gxander85** [comment]
I thought I would post a few things. (Apologies for the long entry, but I wanted to cover everything)

First, results at the end of apt-get update
```
Reading package lists... Done
W: Duplicate sources.list entry http://mirrordirector.raspbian.org/raspbian/ jessie/main armhf Packages (/var/lib/apt/lists/mirrordirector.raspbian.org_raspbian_dists_jessie_main_binary-armhf_Packages)
W: Duplicate sources.list entry http://mirrordirector.raspbian.org/raspbian/ jessie/contrib armhf Packages (/var/lib/apt/lists/mirrordirector.raspbian.org_raspbian_dists_jessie_contrib_binary-armhf_Packages)
W: Duplicate sources.list entry http://mirrordirector.raspbian.org/raspbian/ jessie/non-free armhf Packages (/var/lib/apt/lists/mirrordirector.raspbian.org_raspbian_dists_jessie_non-free_binary-armhf_Packages)
W: You may want to run apt-get update to correct these problems
```
/etc/apt/sources.list
```
deb http://mirrordirector.raspbian.org/raspbian/ jessie main contrib non-free rpi
deb http://mirrordirector.raspbian.org/raspbian/ jessie main contrib non-free
deb http://archive.raspbian.org/raspbian jessie main contrib non-free

```
Then there is /etc/apt/sources.list.d/
pms.list
`deb https://dev2day.de/pms/ jessie main`
raspi.list
```
deb http://archive.raspberrypi.org/debian/ jessie main ui
# Uncomment line below then 'apt-get update' to enable 'apt-get source'
#deb-src http://archive.raspberrypi.org/debian/ jessie main ui
```

I ran apt-get update again and got the same errors as above.
I then re-ran apt-get install openvpn

```
sudo apt-get install openvpnReading package lists... Done
Building dependency tree       
Reading state information... Done
The following extra packages will be installed:
  libpkcs11-helper1
The following NEW packages will be installed:
  libpkcs11-helper1 openvpn
0 upgraded, 2 newly installed, 0 to remove and 3 not upgraded.
Need to get 530 kB of archives.
After this operation, 1,176 kB of additional disk space will be used.
Do you want to continue? [Y/n]
Get:1 http://archive.raspbian.org/raspbian/ wheezy/main libpkcs11-helper1 armhf 1.09-1 [46.1 kB]
Get:2 http://archive.raspbian.org/raspbian/ wheezy/main openvpn armhf 2.2.1-8+deb7u3 [484 kB]
Fetched 530 kB in 6s (78.1 kB/s)                                               
Preconfiguring packages ...
Selecting previously unselected package libpkcs11-helper1:armhf.
(Reading database ... 121982 files and directories currently installed.)
Preparing to unpack .../libpkcs11-helper1_1.09-1_armhf.deb ...
Unpacking libpkcs11-helper1:armhf (1.09-1) ...
Selecting previously unselected package openvpn.
Preparing to unpack .../openvpn_2.2.1-8+deb7u3_armhf.deb ...
Unpacking openvpn (2.2.1-8+deb7u3) ...
Processing triggers for man-db (2.7.0.2-5) ...
Processing triggers for systemd (215-17+deb8u5) ...
Setting up libpkcs11-helper1:armhf (1.09-1) ...
Setting up openvpn (2.2.1-8+deb7u3) ...
[ ok ] Restarting virtual private network daemon.:.
Processing triggers for libc-bin (2.19-18+deb8u6) ...
Processing triggers for systemd (215-17+deb8u5) ...
``` 
I then re-ran `curl -L https://install.pivpn.io | bash`
A progress bar appeared (this did not happen before)
It also proceeded to generate keys etc. I think it worked (still processing now) and my sources.list was cooked.

**Comment by redfast00** [comment]
@gxander85 Did it work? Can this issue be closed?

**Comment by cfcolaco** [comment]
@redfast00 Since there's no more reply from @gxander85 think you can close this! =S
