### ISSUE TITLE
Using Let's Encrypt certificates with PiVPN

### ISSUE THREAD

**Issue by gulyasal** [pivpn/pivpn#246]
First of all, I successfully installed PiVPN and it works perfectly.  You really mastered the entire process end to end!  I have a tweak to ask about: I currently also use my RPi3 as a webserver (Apache, PHP5), with Joomla installed, as well as a Let's Encrypt certificate which I use as an SSL for my website.

That been said, I am wondering if it is possible to use the same certificates from Let's Encrypt instead of using the ones generated by the PiVPN application.  Certainly it is not more secure, but it would be leveraging the ones already installed (/etc/letsencrypt/live/example.com/).  Is this possible?

Thanks for your consideration,
Alex.

**Comment by redfast00** [comment]
I don't think the certificates are compatible, and even if they were, I don't know why you would do that (issues with renewing certs and other, more subtle issues). I don't think it's a good idea, so I won't help you shoot yourself in the foot :confused:.

**Comment by gulyasal** [comment]
Fair enough.  I have a Synology at home and somehow they have managed to use the Let's Encrypt certs for their VPN server package (server-side).  Agreed that it brings new complexity, and not sure it brings any benefits.

**Comment by redfast00** [comment]
Thanks for understanding, and if you do find any benefits, please reopen this issue.
