### ISSUE TITLE
dd-wrt with PiVPN

### ISSUE THREAD

**Issue by Laurence243** [pivpn/pivpn#248]
## Issue

Hey, I've looked around a bit and can't find the any solution to the issue I'm having. I've also tried asking on the dd-wrt forums and nobody can seem to help.

I recently installed dd-wrt version v3.0-r31899 mega on my WNDR3700v3. Prior to the install I had been using the stock Netgear firmware with OpenVPN. It worked fine on any network that doesn't block the VPN client, including mobile and my own home network. 

Since installing dd-wrt, the OpenVPN client cannot connect when I'm connected to my home wifi. It works fine on mobile and other networks, but on my own network it fails the tls authentication. Same problem on my Android phone and Windows 10 laptop.

Any ideas as to why the router is blocking my VPN client when I'm at home?

**Comment by redfast00** [comment]
On what network is the OpenVPN server? On what network is your OpenVPN client/smartphone? It looks like you want to connect to the VPN while being in the same network, which doesn't really make sense because the traffic will in the end be routed through the same infrastructure.

**Comment by Laurence243** [comment]
The OpenVPN server is on my home network. I know its a bit redundant but basically what I have to do now is disconnect from the VPN when I'm at home, when before I didn't have to do that. I don't see why it wouldn't work differently if I have everything configured properly.

**Comment by Laurence243** [comment]
I managed to get it working. I set my primary router as a static gateway with no DHCP, then enabled the DHCP service on my Pi-Hole install. Don't know why but it works now and everything is a bit faster!
