### ISSUE TITLE
Total # Concurrent Users

### ISSUE THREAD

**Issue by mikezucker** [pivpn/pivpn#250]
I was just wondering how many total concurrent connections PiVPN can have?  I am looking for 10-15 concurrent users at one time for 24/7/365.  Is this possible without drastic performance issues?

**Comment by redfast00** [comment]
This will be dependent on hardware, network and network usage on the client devices. What are you running this on? OpenVPN can certainly be used for more than 15 devices at a time, but the bandwidth might be a bottleneck.

**Comment by mikezucker** [comment]
So I have done this with OpenVPN with a regular PC as a server but never a Pi.  That machine crashed (it was an old machine with a crappy HD). :). Hoping this is a better option.

**Comment by redfast00** [comment]
The Pi only has 100MBit ethernet built in, so that might be a bottleneck. I think the CPU will be fine, but I don't know for sure. Please let me know when you tested this out.

**Comment by mikezucker** [comment]
Will do!  Need to configure everything first... ugh...

**Comment by mikezucker** [comment]
So I finally managed to get my server up.

So far throughput is not a problem and I have 6 machines connected to it, plus a Murmur server on my Pi with those machines connected to that as well.  My only concern is heat and CPU.  I will be connecting another 4 machines tonight so we shall see how that goes.

Will keep this thread updated.

Does anybody know a good graphical way to determine system performance for a Pi?

**Comment by redfast00** [comment]
You can use the `top` command on linux. It's still text base, but will do the task. For cpu temp, see https://askubuntu.com/q/15832/459815.

**Comment by Tharmkin** [comment]
For cpu temp on Pi see here: https://www.raspberrypi.org/forums/viewtopic.php?f=91&t=34994
in short; this command shows the Pi's CPU temperature:
     `/opt/vc/bin/vcgencmd   measure_temp`

**Comment by cfcolaco** [comment]
@mikezucker any news about this or can this issue be closed?

**Comment by mikezucker** [comment]
Close it.  No problems
