### ISSUE TITLE
Change subnet I am on when routed through pivpn?

### ISSUE THREAD

**Issue by rwilli30** [pivpn/pivpn#251]
This may be a basic question but I am not sure. Connecting to my vpn at home drops me on the 10.8.0.0/24 subnet (my home devices are at 10.0.0.0/24). . If I am on my linux machine I can access all the items on my network. If I am on my windows 7 machine I cant see anything. If I ping addresses from my windows computer I "Request Timed Out" whereas on my ubuntu vm running as a guest on my windows machine can see everything. Maybe this is more of a networking question. I dont know. Can anyone offer any assistance? 
## Console output of `pivpn debug`
```
::: Generating Debug Output
:::					:::
::		PiVPN Debug		 ::
:::					:::
::	Latest Commit			 ::
:::					:::
commit 6ce39bfec399d9a8203409a108ef27f2ee29327a
Author: 0-kaladin <0.kaladin@gmail.com>
Date:   Mon Feb 27 21:01:23 2017 -0500

    Update README for IRC channel
    
    Due to discontinuation of Google Spaces
:::					:::
::	Recursive list of files in	 ::
::	/etc/openvpn/easy-rsa/pki	 ::
:::					:::
/etc/openvpn/easy-rsa/pki/:
ca.crt
Default.txt
dh2048.pem
index.txt
index.txt.attr
index.txt.attr.old
index.txt.old
issued
private
rick.ovpn
serial
serial.old
ta.key

/etc/openvpn/easy-rsa/pki/issued:
rick.crt
server.crt

/etc/openvpn/easy-rsa/pki/private:
ca.key
rick.key
server.key
:::					:::
::	Output of /etc/pivpn/*		 ::
:::					:::
:: START /etc/pivpn/DET_PLATFORM ::
Raspbian
:: END /etc/pivpn/DET_PLATFORM ::
:: START /etc/pivpn/INSTALL_PORT ::
1194
:: END /etc/pivpn/INSTALL_PORT ::
:: START /etc/pivpn/INSTALL_PROTO ::
udp
:: END /etc/pivpn/INSTALL_PROTO ::
:: START /etc/pivpn/INSTALL_USER ::
pi
:: END /etc/pivpn/INSTALL_USER ::
:: START /etc/pivpn/NO_UFW ::
1
:: END /etc/pivpn/NO_UFW ::
:: START /etc/pivpn/pivpnINTERFACE ::
eth0
:: END /etc/pivpn/pivpnINTERFACE ::
:: START /etc/pivpn/REVOKE_STATUS ::
0
:: END /etc/pivpn/REVOKE_STATUS ::
:::					:::
:: /etc/openvpn/easy-rsa/pki/Default.txt ::
:::					:::
client
dev tun
proto udp
remote 256.256.256.256 1194
resolv-retry infinite
nobind
persist-key
persist-tun
key-direction 1
remote-cert-tls server
tls-version-min 1.2
verify-x509-name server name
cipher AES-256-CBC
auth SHA256
comp-lzo
verb 1
:::					:::
::	Debug Output Complete		 ::
:::					:::
::: 
::: Debug output completed above.
::: Copy saved to /tmp/debug.txt


```

**Comment by cfcolaco** [comment]
I haven't seen all the configs yet... but since you can access to the network trough the VM in windows host, It brings me the question, are you running OpenVPN "as Administrator" in windows?

I mean, Right click on OpenVPN > Run as Administrator

If I am not mistaken ( I am not using windows for a long time ) it is one of the major causes of not being able to reach other subnets. 
Hope this helps you, I will be waiting for your feedback

**Comment by rwilli30** [comment]
This worked perfectly! Thank you so much!

**Comment by senses3** [comment]
This will work until reboot. If you want to change your subnet on the new install to the same as the old install, edit `/etc/pivpn/wireguard/setupVars.conf` and change the line `pivpnNET=` to the subnet you wish to use.
