### ISSUE TITLE
Installed on Odroid C2 using Ubuntu 16.04 - service not running

### ISSUE THREAD

**Issue by nickr14** [pivpn/pivpn#253]
# PiVPN Issue Template

## Console output of `curl install.pivpn.io | bash`
```

```

## Console output of `pivpn add` or `pivpn add nopass`
```

```

## Console output of `pivpn debug`
```

```

## Issue
The install ran fine, just like when I ran it on a pi 2.  However it noticed that it was not a pi 2 so it did not set my ip to static.  I did this myself.

It created a client ovpn without issue.  However I do not believe that the service is running.

I have run the following to check if the service is running:
```
echo -e "\x38\x01\x00\x00\x00\x00\x00\x00\x00" |  timeout 10 nc -u openvpnserver.com 1194 | cat -v
```

Is there a command I can type to get it running?  How can I get it to run on reboot?

**Comment by cfcolaco** [comment]
@nickr14 do you still have this issue? do you still need help?

to check the status of a service you just need to do:

`systemctl status <servicename>` or `service <servicename> status`

so for OpenVPN, you should do:
 
`systemcl status openvpn` or `service openvpn status`

**Comment by nickr14** [comment]
I ended up installing ubuntu and following the openvpn instructions for ubuntu.

**Comment by cfcolaco** [comment]
@nickr14 so if you no longer need any help regarding this issue can you please close it?
