### ISSUE TITLE
Feature Request: SoftEther support?

### ISSUE THREAD

**Issue by marcdraco** [pivpn/pivpn#254]
Not sure where to put this... but here goes. I found you on DietPi.com (which I use for my nano-servers) and found the script truly superb.

But... I don't really care for OpenVPN that much as it's very limited in scope.

I wonder therefore, if you are able to provide a simplified installer for SoftEther https://www.softether.org ?

There are a laundry list of reasons why I prefer SoftEther (familiarity being a major one) but also that I was unable to get OpenVPN to work on the client as well as Softether. Speed is another issue - I find OpenVPN to be awfully slow.

Thanks and sorry for being so off-topic (so to speak)

**Comment by afcdmc** [comment]
Hi marcdraco I also was looking for a script for SoftEther and found this page: https://community.flexradio.com/flexradio/topics/softether-vpn-install-script-for-raspberry-pi?topic-reply-list%5Bsettings%5D%5Bfilter_by%5D=all

hope it works for you

**Comment by redfast00** [comment]
I think the scope of the PiVPN project is limited to setting up an OpenVPN server. As such, I don't think we support SoftEther. You can still keep commenting in this issue, but I'll close it since it's not related to PiVPN.
