### ISSUE TITLE
Static IP for clients

### ISSUE THREAD

**Issue by anudeepND** [pivpn/pivpn#257]
An option to set a static virtual IP for each client would be great!

**Comment by mikezucker** [comment]
This is ultimately what am I tryin to do, however I am unable to the admin panel.  I am wondering is PiVPN actually has this as part of the install?  I can't find ovpn-init anywhere.

**Comment by mikezucker** [comment]
I was able to set the static IP for all of my clients last night using ifconfig-push.  Just create a new client confit directory and add the client files with ifconfig-push [ststic ip address] [subnet].

If you want more details, let me know.

**Comment by anudeepND** [comment]
Thanks! I configured it successfully

**Comment by toddthegeek** [comment]
I would also like the detailed instructions.

**Comment by anudeepND** [comment]
Hi there!
@joejoe2017 and @toddthegeek 

1. Add this line `client-config-dir` in 
`/etc/openvpn/server.conf`

2. Create client config directory
 `sudo mkdir /etc/openvpn/ccd`

3. Fix permissions
`sudo chown -R pi:nogroup /etc/openvpn/ccd`
 (Make sure to enter correct username, in my case it was pi)

4. Adding clients.
`sudo nano /etc/openvpn/ccd/clientname`
(Enter client name correctly)

5. Configuring static IP.
Add this line to  `/etc/openvpn/ccd/clientname`
`ifconfig-push 10.8.0.3 255.255.255.0`
(Here 10.8.0.3 is going to be static IP for user clientname, if you want add additional users, repeat from step 4)

6. Restart openvpn
`sudo service openvpn restart`

**Comment by mikezucker** [comment]
Please remember that that static ip assigned can NOT be the same IP that is already assigned even if it is assigned dynamically.

**Comment by anudeepND** [comment]
Yes, In order to avoid this, assign a static ip for all clients

**Comment by reek-ch** [comment]
@anudeepND Thanks for the instructions!

**Comment by toddthegeek** [comment]
two months later, but I finally got to it.  

Thanks! This works great!  I think my issue was the permissions of the folder.  It's working great now.

**Comment by GioF71** [comment]
Awesome @anudeepND !!!

**Comment by mossberg93** [comment]
@anudeepND Noob here... Kind of lost at step 4. What exactly does one do with the Nano editor? What content is being added and what file type is it being saved as?

**Comment by mikezucker** [comment]
The nano editor is where you will enter your static IP address for the machine. The file name will be the same name as the .ovpn file.

**Comment by kryptokommunist** [comment]
> Hi there!
> @joejoe2017 and @toddthegeek
> 
> 1. Add this line `client-config-dir /etc/openvpn/ccd` in
>    `/etc/openvpn/server.conf`
> 2. Create client config directory
>    `sudo mkdir /etc/openvpn/ccd`
> 3. Fix permissions
>    `sudo chown -R pi:nogroup /etc/openvpn/ccd`
>    (Make sure to enter correct username, in my case it was pi)
> 4. Adding clients.
>    `sudo nano /etc/openvpn/ccd/exampleuser`
>    (Add clients with their common name, in this case `exampleuser.ovpn`)
> 5. Configuring static IP.
>    Add this line  `ifconfig-push 10.8.0.3 255.255.255.0` to  `/etc/openvpn/ccd/exampleuser`
> 6. Restart openvpn
>    `sudo service openvpn restart`
> 
> (Here 10.8.0.3 is going to be static IP for user `exampleuser`, if you want to configure additional users, repeat from step 4)

Does this ensure that the clients are forced to use this static IP or could a malicious client still use another IP?

I'm asking for a use-case scenario in which I want to filter traffic based on the IP address which only makes sense if the clients can't connect with any other IP than their statically assigned one. Other IP's I wan't to keep dynamically assigned so I need to ensure that the dynamic IP client's can't use the static IPs.

**Comment by theAkito** [comment]
> 
> 
> Does this ensure that the clients are forced to use this static IP or could a malicious client still use another IP?
> 
> I'm asking for a use-case scenario in which I want to filter traffic based on the IP address which only makes sense if the clients can't connect with any other IP than their statically assigned one. Other IP's I wan't to keep dynamically assigned so I need to ensure that the dynamic IP client's can't use the static IPs.

Greetings @kryptokommunist,

if you set for example `ifconfig-push 10.100.0.10 10.100.0.10` in the CCD config for a specific client, the address will be _pushed_ in their faces basically. As far as I know, there should be no way to avoid that, because the server will only accept the client with this IP. If a client wants to use a different IP, too bad for them.

That said, maybe there is a better solution for your specific issue. Maybe you could elaborate what the point of your goal _"I want to filter traffic based on the IP address"_ is.

**Comment by kryptokommunist** [comment]
Salve @theAkito :) 

The goal is to prevent clients from making ssh-connections to the VPN server by default, but to allow this for certain clients.

**Comment by theAkito** [comment]
> 
> 
> Salve @theAkito :)
> 
> The goal is to prevent clients from making ssh-connections to the VPN server by default, but to allow this for certain clients.

I assume client's aren't connected all the time?

**Comment by theAkito** [comment]
@kryptokommunist 
What about [using more than a single CAs](https://serverfault.com/questions/642406/openvpn-server-multiple-certs) and give the cool client cert only to privileged clients, while giving the crappy client cert to the ones excluded from SSH access?
