### ISSUE TITLE
OpenVPN Admin Utility

### ISSUE THREAD

**Issue by mikezucker** [pivpn/pivpn#258]
Can somebody please explain to me how to install Admin utility?  I do not have a /opnevpn_as folder as I believe I should?

**Comment by SilvioMessi** [comment]
+1

**Comment by abpostelnicu** [comment]
I really don't think openvpn as is present on the pi, in fact i believe there is a build for it.

**Comment by redfast00** [comment]
What do you need the Admin utility for? There already is a `pivpn` command that allows you to create, list and revoke `.ovpn` files.

**Comment by mikezucker** [comment]
Now that I have figured out static IP, nothing. :)

**Comment by SilvioMessi** [comment]
For advanced configurations like restrict access only to specific hosts inside the LAN?
