### ISSUE TITLE
Router Setup

### ISSUE THREAD

**Issue by ostermayer** [pivpn/pivpn#26]
If placed connected to a commercial router does anything special need to be configured with the router to allow for connection.  Likewise does a dynamicdns service need to be linked to the pi?

**Comment by 0-kaladin** [comment]
You still need to have the port for vpn (by default 1194) open to the outside.  Depending on the commercial router/firewall there are various ways to do it.  when 1194 hits the outside interface of the router it needs to route do the pivpn.  remember this is UDP not TCP as well. 
Also whether you need a dynamicdns service is something only you would know.  In a commercial setting, many static IP's can home to one router, so you could have a static IP just for the pi, assigned on the router that is open to 1194.  then take that static IP and put it in dns.

**Comment by ostermayer** [comment]
thanks

**Comment by 0-kaladin** [comment]
I'll close this after a week if you have no further questions or you can close it whenever you think you are done.
