### ISSUE TITLE
How to test which ports might work?

### ISSUE THREAD

**Issue by AdySan** [pivpn/pivpn#261]
Please forgive me for not following the template, but this is more of a question rather than a issue.

My spouse works at a state university where the school wifi seems to block certain ports. My PiVPN endpoint works fine from other public wifi, just not the school wifi. My guess is outgoing traffic on certain ports is blocked. So far I've tried the default 1194 (UDP) and 22 (UDP) but no luck. Is there a quick way to do something like a port scan and tell for sure which port might actually work?

**Comment by redfast00** [comment]
TCP 443 might work, since it's used for HTTPS. If the school's wifi only blocks certain ports (so no protocols) check out http://portquiz.net for working TCP ports. Be sure to also check if they are maybe blocking IPs/domains. Do you know what technology they are using to block the ports?

**Comment by AdySan** [comment]
Sorry, I'm not sure how exactly to tell how they're blocking. One person on reddit claims that PIA works for them on the same wifi, but I'm not sure what port they're using with PIA (They allow quite a few options in that respect). 

I tried nmap on a range of ports a while ago and got no-repsonse on all except 22/TCP, that's the reason I tried 22 (UDP), perhaps I should try TCP?

**Comment by redfast00** [comment]
TCP will be slower tho. Definitely try 443/TCP

**Comment by AdySan** [comment]
Port 22 with TCP worked!
