### ISSUE TITLE
OpenVPN Connection Timeout

### ISSUE THREAD

**Issue by Kroesss** [pivpn/pivpn#262]
I have installed pivpn (RPi 3 with Raspbian Jessie, GUI-version), and it looked as if everything is working. I added a user and rebooted the RPi. I then installed OpenVPN Connect on my Android 7.1.1-phone. When I imported the opvn-file and entered the chosen password for this user it tries to connect for a while, then states that it has encountered a connection timeout.

My phone is not connected to my home-network, I have it running on the mobile data-plan.
In my router I have setup a "Virtual server" that points from port 2056 on my external IP to the same port-number on my RPi. Obviously that is the port I chose in the installer because I wanted to use a non-standard port.

My opnv-file:
```
client
dev tun
proto udp
remote <my ip-address> 2056
resolv-retry infinite
nobind
persist-key
persist-tun
key-direction 1
remote-cert-tls server
tls-version-min 1.2
verify-x509-name server name
cipher AES-256-CBC
auth SHA256
comp-lzo
verb 1
<ca>
-----BEGIN CERTIFICATE-----
* removed *
-----END CERTIFICATE-----
</ca>
<cert>
-----BEGIN CERTIFICATE-----
* removed *
-----END CERTIFICATE-----
</cert>
<key>
-----BEGIN ENCRYPTED PRIVATE KEY-----
* removed *
-----END ENCRYPTED PRIVATE KEY-----
</key>
<tls-auth>
#
# 2048 bit OpenVPN static key
#
-----BEGIN OpenVPN Static key V1-----
* removed *
-----END OpenVPN Static key V1-----
</tls-auth>
```

Does anybody know what is going wrong?

**Comment by Kroesss** [comment]
Anybody? I have no idea where to start looking, and I cannot think of any setting that would be wrong...

**Comment by cfcolaco** [comment]
Huumm since it failed after you rebooted, please check booth

`systemctl status openvpn`
`systemctl status openvpn@server`

and see if services started properly. or if there is any errors.
if you don't understand the output, please paste it here so I can check it.

`systemctl start openvpn` 
or
`systemctl start openvpn@server`


hope this helps out.

**Comment by Kroesss** [comment]
> 
Huumm since it failed after you rebooted, please check booth

systemctl status openvpn
systemctl status openvpn@server

and see if services started properly. or if there is any errors.
if you don't understand the output, please paste it here so I can check it.

systemctl start openvpn
or
systemctl start openvpn@server

hope this helps out.
> 
Well, it looks like it is running, but just to be sure, here's the output:

```
pi@raspberrypi:~ $ systemctl status openvpn
● openvpn.service - OpenVPN service
   Loaded: loaded (/lib/systemd/system/openvpn.service; enabled)
   Active: active (exited) since Sat 2017-06-03 15:42:00 CEST; 2 days ago
  Process: 557 ExecStart=/bin/true (code=exited, status=0/SUCCESS)
 Main PID: 557 (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/openvpn.service

pi@raspberrypi:~ $ systemctl status openvpn@server
● openvpn@server.service - OpenVPN connection to server
   Loaded: loaded (/lib/systemd/system/openvpn@.service; disabled)
   Active: active (running) since Sat 2017-06-03 15:41:59 CEST; 2 days ago
  Process: 466 ExecStart=/usr/sbin/openvpn --daemon ovpn-%i --status /run/openvpn/%i.status 10 --cd /etc/openvpn --config /etc/openvpn/%i.conf (code=exited, status=0/SUCCESS)
 Main PID: 518 (openvpn)
   CGroup: /system.slice/system-openvpn.slice/openvpn@server.service
           └─518 /usr/sbin/openvpn --daemon ovpn-server --status /run/openvpn/server.status 10 --cd /etc/openvpn --config /etc/openvpn/server.conf
```
I hope you there is anything I am missing?

**Comment by anudeepND** [comment]
Is port forwarding working?

**Comment by Kroesss** [comment]
@anudeepND Good one! I checked with canyouseeme.org and it claims it cannot reach port 2059 on my IP. Reason is ... timeout.

I think I have it correctly setup on my router (screenshot included), don't know how else to set it up...
![port_forwarding](https://user-images.githubusercontent.com/17062001/26843729-86f0064e-4af1-11e7-92d7-00afb0428343.png)

Any ideas?

**Comment by redfast00** [comment]
Does the checkbox 'enable port forwarding' do anything?

**Comment by cfcolaco** [comment]
@Kroesss don't know that router, however, I believe that you must tick the "enable port forwarding" and the "select" checkboxes and then Apply.

**Comment by Kroesss** [comment]
@redfast00 @cfcolaco You guys are rght (of course). I totally missed that checkbox. Everything works like a charm now.

Thank you!
