### ISSUE TITLE
Application use of the project

### ISSUE THREAD

**Issue by JLA23** [pivpn/pivpn#264]
Hello,

Thank you for sharing this project. I'm studying my end-of-year project is a remote videotape. I need to install a VPN. Your code works very well. I would like to know if you allow me to use your code by modifying the last feature?

Thank you in advance for your response.

Cordially.

Eric Lefebvre (French)

PS: I'm sorry about my English which is very bad.

**Comment by redfast00** [comment]
Yes, you can use or edit our code (check the LICENCE file, you still need to include it). Out of curiosity: what are you doing exactly?

**Comment by JLA23** [comment]
I am in SIO License. With a friend, on the project a video library and video server. On a raspberry server, we install samba, owncloud, vpn and dlna containing games and videos, and raspberry which serves as a RecalBox console. With an installation script, we insert startup scripts to the console so that it connects, if it is on the same local network as the server, directly to samba, otherwise it connects to vpn. So we can access our video via internet (VPN and Owncloud) and local (Samba and DLNA).

Thank you very much.

Cordially.

Eric Lefebvre

**Comment by redfast00** [comment]
I probably wasn't clear: I meant that the PiVPN project uses an MIT licence, and that you still need to include it.

**Comment by JLA23** [comment]
You have been quite clear, I have expressed myself badly. We put your MIT licence with the project. The license of which I speak is a school level. SIO is the type of licence.

**Comment by redfast00** [comment]
Okay. Closing this for now, please reopen of you have any more questions.
