### ISSUE TITLE
Ubuntu server won't open port

### ISSUE THREAD

**Issue by ohdude** [pivpn/pivpn#266]
I've try to install pivpn on a Ubuntu 14.04.5 x64 server (digitalocean), 
But I cannot connect to it (closed port) (I rebooted the  @server)

# PiVPN Issue Template

## Console output of `curl install.pivpn.io | bash`
```
Installed complete
```

## Console output of `pivpn add` or `pivpn add nopass`
```
I added an user
```

## Console output of `pivpn debug`
```
root@vpn:~# pivpn debug
::: Generating Debug Output
:::                                     :::
::              PiVPN Debug              ::
:::                                     :::
::      Latest Commit                    ::
:::                                     :::
commit 6ce39bfec399d9a8203409a108ef27f2ee29327a
Author: 0-kaladin <0.kaladin@gmail.com>
Date:   Mon Feb 27 21:01:23 2017 -0500

    Update README for IRC channel

    Due to discontinuation of Google Spaces
:::                                     :::
::      Recursive list of files in       ::
::      /etc/openvpn/easy-rsa/pki        ::
:::                                     :::
/etc/openvpn/easy-rsa/pki/:
ca.crt
Default.txt
dh1024.pem
index.txt
index.txt.attr
index.txt.old
issued
private
serial
serial.old
ta.key

/etc/openvpn/easy-rsa/pki/issued:
server.crt

/etc/openvpn/easy-rsa/pki/private:
ca.key
server.key
:::                                     :::
::      Output of /etc/pivpn/*           ::
:::                                     :::
:: START /etc/pivpn/DET_PLATFORM ::
Ubuntu
:: END /etc/pivpn/DET_PLATFORM ::
:: START /etc/pivpn/INSTALL_PORT ::
1194
:: END /etc/pivpn/INSTALL_PORT ::
:: START /etc/pivpn/INSTALL_PROTO ::
udp
:: END /etc/pivpn/INSTALL_PROTO ::
:: START /etc/pivpn/INSTALL_USER ::
daan
:: END /etc/pivpn/INSTALL_USER ::
:: START /etc/pivpn/NO_UFW ::
1
:: END /etc/pivpn/NO_UFW ::
:: START /etc/pivpn/pivpnINTERFACE ::
eth0
:: END /etc/pivpn/pivpnINTERFACE ::
:: START /etc/pivpn/REVOKE_STATUS ::
0
:: END /etc/pivpn/REVOKE_STATUS ::
:::                                     :::
:: /etc/openvpn/easy-rsa/pki/Default.txt ::
:::                                     :::
client
dev tun
proto udp
remote 8.8.8.8 1194
resolv-retry infinite
nobind
persist-key
persist-tun
key-direction 1
remote-cert-tls server
tls-version-min 1.2
verify-x509-name server name
cipher AES-256-CBC
auth SHA256
comp-lzo
verb 1
:::                                     :::
::      Debug Output Complete            ::
:::                                     :::
:::
::: Debug output completed above.
::: Copy saved to /tmp/debug.txt
:::

```

**Comment by redfast00** [comment]
Is the openvpn service still running? What does `sudo service openvpn status` print? @0-kaladin I will add this to `pivpn debug`.

**Comment by ohdude** [comment]
```
root@vpn:~# sudo service openvpn status
 * VPN 'server' is running
root@vpn:~# nmap localhost

Starting Nmap 6.40 ( http://nmap.org ) at 2017-06-08 10:24 UTC
Nmap scan report for localhost (127.0.0.1)
Host is up (0.000030s latency).
Not shown: 999 closed ports
PORT   STATE SERVICE
22/tcp open  ssh

Nmap done: 1 IP address (1 host up) scanned in 1.61 seconds
root@vpn:~#


```

**Comment by redfast00** [comment]
Huh... What about `netstat --listen` and `netstat -vaun`?

**Comment by ohdude** [comment]
![vpnm](https://user-images.githubusercontent.com/6848396/26925603-ac44b340-4c4a-11e7-9889-5a293b131529.PNG)


```
root@digitalocean:~# netstat --listen
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 *:ssh                   *:*                     LISTEN
tcp6       0      0 [::]:ssh                [::]:*                  LISTEN
udp        0      0 *:openvpn               *:*
raw6       0      0 [::]:ipv6-icmp          [::]:*                  7
Active UNIX domain sockets (only servers)
Proto RefCnt Flags       Type       State         I-Node   Path
unix  2      [ ACC ]     STREAM     LISTENING     10658    /var/run/dbus/system_bus_socket
unix  2      [ ACC ]     STREAM     LISTENING     11126    /var/run/acpid.socket
unix  2      [ ACC ]     STREAM     LISTENING     11298    /var/run/dhcpcd.sock
unix  2      [ ACC ]     STREAM     LISTENING     8859     @/com/ubuntu/upstart
unix  2      [ ACC ]     SEQPACKET  LISTENING     9595     /run/udev/control
root@digitalocean:~# netstat -vau
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
udp        0      0 *:openvpn               *:*
root@digitalocean:~#

```

**Comment by ohdude** [comment]
Also does not work on Raspberry with the 2017-04-10-raspbian-jessie-lite img file

**Comment by redfast00** [comment]
This all looks good, I think either your client or network has something to do with. Have you tried using another client/device? There are OpenVPN apps for both iOS and Android, can you try using them?

**Comment by ohdude** [comment]
Yes, I've tried your script and another script (https://github.com/Nyr/openvpn-install)
Besides that, I installed OpenVPN client on my phone and Windows computer.

When I install https://github.com/Nyr/openvpn-install on a digital ocean server, then I can connect to it.
But it won't set a static IP like yours (I love it haha).

I've used a clean image for both ones

**Comment by redfast00** [comment]
Can you give me a full client-side log?

**Comment by cfcolaco** [comment]
Hmmm @ohdude @redfast00 could it be related with apparmor? don't know if ubuntu 14 already has apparmor by default since I had not used ubuntu for a long time! don't even know if apparmor can cause this kind of trouble like selinux does if not properly configured.

**Comment by ohdude** [comment]
To be honest I do not know, I use another package for OpenVPN now

**Comment by cfcolaco** [comment]
@ohdude so you no longer have the issue or can continue to troubleshoot this? 

please close then. ty

**Comment by IByte** [comment]
I'm not sure if it is the same issue, but it turned out I had selected the recommended setting of UDP during pivpn installation, but then set port forwarding in the router on a TCP port. D'oh! Oh well, it appears to work for me now, maybe this will give someone else a good idea.

**Comment by dddwwwhhh** [comment]
This is the same problem that I have right now. No port shows and OpenVPN service is running. Someone says need to config the iptables, but I tried and does not work. I do not think iptables is the problem.

**Comment by cfcolaco** [comment]
@dddwwwhhh Are you using ubuntu 14.04??  

( I wonder Why using that old version anyway ... )

**Comment by dddwwwhhh** [comment]
@cfcolaco I use 16.04 version.  I am not sure the OS version and OpenVPN version are matter or not for PiVPN
