### ISSUE TITLE
Easy export of Chrome OS compatible setup files

### ISSUE THREAD

**Issue by TeaTimeSoon** [pivpn/pivpn#27]
pivpn is great and creating .ovpn files for use in Windows and Android mobiles is a synch, but I am struggling to create Chrome OS compatible files and any help would be appreciated.
To get OpenVPN working on Chrome OS, I need the following:
ca.crt  (the certificate authority’s public key certificate)
client-cert.p12  (the clients public / private key).
ta.key (the TLS-auth key)

I have tried exporting certs in the correct format using openssl commands, but am getting nothing but error messages.
I am a bit of a noob here so please be gentle :-)

**Comment by 0-kaladin** [comment]
if you are on your pivpn, then
`cd /etc/openvpn/easy-rsa/keys`
you should see two files that you already need there, the ca.crt and the ta.key.
you should also see a .crt and .key for the client you are trying to use on the chromeOS.  Lets say you called it 'chromeosClient'.  so you'd see also chromeosClient.crt a .key and a .3des.key
None of those are the p12 it wants so you'll want to create it with
`openssl pkcs12 -export -in chromeosClient.crt -inkey chromeosClient.key -out chromeosClient.p12 -name MyChromep12`

you have to enter the password of the key you used when you originally created it.  Once done, in that directory you should now see the chromeosClient.p12
That is the third piece of your puzzle.  Get those 3 files on chromeOS and you should be set.

**Comment by 0-kaladin** [comment]
to be clear you should 'pivpn add' and use name chromeosClient or whatever the name is so that you have a crt and key generated.  then run the openssl command above.

**Comment by TeaTimeSoon** [comment]
Many thanks - will check this out later when I have a few moments to spare.

**Comment by smartyhall** [comment]
ChromeOS requires a Username and Password when setting up a VPN, even if you give it a full set of keys.

**Comment by 0-kaladin** [comment]
Yea i have no chromeos to test on. where does it even want the username from?  @TeaTimeSoon didn't confirm yet if my steps above worked.

**Comment by smartyhall** [comment]
I have an Asus Chromebook. The instructions you posted got me part of the
way there. I found a thread on the Google support forums discussing the
issue — I'll try to find the link when I get back home. Someone mentioned
that it expects what I think they called a "user bound key" that also makes
the keys optional but requires user/pass authentication.

**Comment by 0-kaladin** [comment]
ok, thanks.  If i can figure out exactly what chromeos needs, i could potentially add it to pivpn as an option, like
`pivpn add chromeos` could give you whatever it needs.

**Comment by smartyhall** [comment]
Here's the link to the forum post:  [https://bugs.chromium.org/p/chromium/issues/detail?id=217624](url)
There is also this: [https://docs.google.com/document/d/18TU22gueH5OKYHZVJ5nXuqHnk2GN6nDvfu2Hbrb4YLE/pub](url)

It describes how to use an ONC file to configure setting that are not exposed in the UI at present. I'm about to try building one. I'll let you know how it turns out.

**Comment by smartyhall** [comment]
I was able to build an ONC that would import without errors, but it still requires me to input a password. I'll have to keep poking at it and see if it works the next time I'm on a different network from my home network. If it does work, I'll let you know.

BTW, thanks for all the work thus far; it has worked flawlessly with my Android phones.

**Comment by 0-kaladin** [comment]
what did you use for username?  wouldn't the password be the one you used to create the client cert?

**Comment by 0-kaladin** [comment]
@smartyhall @TeaTimeSoon did this die?  I have to say the more i read about chrome support for openvpn the less I think I should do something in this script for it.  Really they need to support ovpn like everyone else.

**Comment by TeaTimeSoon** [comment]
Hi @0-kaladin - my experience was bad. I followed your help getting the required ta and ca files ready and created a .onc file. Importing this into Chrome was not successful - it does not seem to import, but gives no error message or success message so you are left wondering what on earth happened!
The instructions for the formatting of the .onc file are scattered around the Net - for example some say you should have the key/cert data on a single line with no line returns, some say the header info in these files should be removed (the "-----BEGIN PRIVATE KEY-----" text etc). I have tried all the combinations and permutations possible but still no joy.

If this process could be automated with a script, e.g. generating a valid .onc file on the Pi, this would be fantastic. At the moment, I can fire up an OVPN session at the drop of a hat on my Android device, but not on my Chromebook. 

An alternative to this would be for somebody to create a native OVPN client Chromebook app.

Finally, I should say that there are reports that Google/Alphabet are probably going to be enabling Android apps to run natively on ChromeOS, in which case I assume that the Android OVPN app will run and we will all be dancing in the streets!

Thanks for all the help

**Comment by 0-kaladin** [comment]
Yea I think I'll close this.  Either chromeos supports ovpn or android apps and we get the openvpn app.  Don't think i should try scripting ONC generation myself without a chromebook to test on.  If someone else with a chromebook does it and submits a pull request I'll gladly merge it in.

**Comment by timdonovanuk** [comment]
This doesn't appear to be valid advice anymore. There is no /etc/openvpn/easy-rsa/keys folder after creating an ovpn file.

**Comment by prestonvanloon** [comment]
FYI: ChromeOS supports OpenVPN tunneling through the Android OpenVPN Connect app.

https://bugs.chromium.org/p/chromium/issues/detail?id=696865

I verified on Version 66.0.3359.10:
- install OpenVPN Connect
- Imported opvn file
- Connect
And now I'm on secure VPN. I can close OpenVPN Connect and the VPN status persists in the bottom right toolbar.
