### ISSUE TITLE
Test infrastructure 

### ISSUE THREAD

**Issue by redfast00** [pivpn/pivpn#270]
It would be useful to have a test infrastructure, so that commits will be automatically tested instead of manually.

**Comment by cfcolaco** [comment]
I am moving from my home country soon ( I expect it to be in the end of july ), after moving I will make changes to my home infrastructure and VPS, which presents a chance to provide some kind of CI/CD server for pivpn, perhaps jenkins + docker or some other identical tool! I am fairly new to developing and CI/CD but I think that should be something like that you would like to have and that I would gladly offer to this project as soon as I can ( probably somewhere between September or October ) ;)

**Comment by redfast00** [comment]
https://travis-ci.org might be interesting

**Comment by cfcolaco** [comment]
@redfast00  didn't know it! seems great and simple also! never tried since I use gitlab CI/CD for my private projects, which don't have much of complexity so far! x'D

**Comment by 4s3ti** [comment]
This is not entirely PiVPN related... will place this in a more appropriate place Closing
