### ISSUE TITLE
server.conf DHCP Options

### ISSUE THREAD

**Issue by Geffers** [pivpn/pivpn#271]
Folks,

Just used the script to install pivpn on a R-Pi - worked fine and connected using an Android device.

Trying to understand how it all works I am puzzled how multiple clients connect, I would have expected some kind of DHCP pool but the config file suggests just one connection as below;
`# server and remote endpoints
ifconfig 10.8.0.1 10.8.0.2
`
Great script,

Geffers

**Comment by redfast00** [comment]
Multiple connections definitely work. The config file reserves the 10.8.0.0/24 subnet for OpenVPN clients. Check out `server_config.txt` and the OpenVPN manual at https://openvpn.net/index.php/open-source/documentation/howto.html for more info.
