### ISSUE TITLE
Invalid Os Detected

### ISSUE THREAD

**Issue by Dalto1** [pivpn/pivpn#272]
## Issue
Got this issue when i tried to reinstall pivpn on my pine64 (on dietpi)
Uninstall went successfull (i think) and then install failed

We have not been able to detect a supported OS. 
Currently this installer supports Raspbian jessie, Ubuntu 14.04
(trusty), and Ubuntu 16.04 (xenial).
If you think you received this message in error, you can post an
issue on the GitHub at https://github.com/pivpn/pivpn/issues.

**Comment by cfcolaco** [comment]
don't know diet pi ... as far as I could read it is based on debian jessie, but probably has some changes that makes the script to consider it as non suported... 

Can you please paste the output of: `lsb_release`  ??

**Comment by Dalto1** [comment]
/usr/bin/python: error while loading shared libraries: unexpected PLT reloc type 0x00010402

**Comment by cfcolaco** [comment]
ok ... now `cat /etc/os-release`  please

**Comment by Dalto1** [comment]
I formated my server, problem is gone thanks

**Comment by michaelxchi** [comment]
I got error: We have not been able to detect a supported OS

pi@raspberrypi:~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

**Comment by michaelxchi** [comment]
After changed the os to Raspberry Pi OS with desktop from Lite, that resolved the problem.
