### ISSUE TITLE
Resolve .local with PiVPN & Pi-Hole

### ISSUE THREAD

**Issue by Jacopx** [pivpn/pivpn#274]
## Issue
Good morning,
I have just set up my VPN and it works. I have changed the file to use the Pi-Hole DNS resolver too and it works well. I have a second machine on my network, this FreeBSD run some jail that I have added in the DHCP Lease of Pi-Hole. When I'm accessing to them from local I'm using: 

`http://freenas.local` or `http://gogs.local`

and of course it works, if I try do to the same from the VPN environment no... Someone can help me?

**Comment by cfcolaco** [comment]
Your OpenVPN is using PiHole as DNS right? 
this is a setup that I don't know very well ... but following the logic ... any DNS you use for the VPN server, should be aware of the name --> IP resolution on your local network. 

actually probably the only device that knows that is your router, you might have to add entries to PiHole so it can know that  freenas.local as the ip XXX.XXX.XXX.XXX  ... 

it is something that I have to try it myself to better help you .. but should be something similar to this!

**Comment by Jacopx** [comment]
Yeah yeah, i know how to It and i have already done It. What i can't understand is why if I'm trying to write
'dig gogs.local' from the local LAN and from the VPN I received the correct answer the is 192.168.2.5. 
If I try to reach 192.168.2.5 from the browser under VPN it works and with the hostname no. The hostname works fine but no under VPN...

**Comment by cfcolaco** [comment]
@Jacopx you are not the first one with that issue, I have to make some tests to get to a good solution, however right now I don't have how to make such tests, and probably only will have that chance after summer. hope someone comes with a solution for this otherwise, I will try to get a good solution for this as soon as I can.
