### ISSUE TITLE
Unidentified Network / No Internet Access

### ISSUE THREAD

**Issue by msaptrta** [pivpn/pivpn#275]
# PiVPN Issue Template

## Console output of `curl install.pivpn.io | bash`
```

```

## Console output of `pivpn add` or `pivpn add nopass`
```

```

## Console output of `pivpn debug`
```

```

## Issue
I've been trying to use the pivpn installer to create a OpenVPN server for my raspberry pi 3.  It has been successful in creating the server side setup, as well as the user side setup.  The issue comes after importing the created .opvn file into the client software.  I am able to connect the client to the vpn, and the vpn assigns the client a new ip address of 10.8.0.2; however, once connected I am unable to access anything on my network or anything from the web.

I have searched many forums and this seemed to be a prevalent issue.  I tried all of the suggested fixes from the forums including the DNS addressing issues, iptable fixes, using the debug tool (which never resulted in any fixes), and the even rerunning the installer on a fresh image of Jessie.  None of them fix my issue.

I'd appreciate any suggestions you might have in fixing this issue.

**Comment by redfast00** [comment]
This in itself isn't enough to understand the issue. Can you give the output of `pivpn debug`, `iptables-save` and the client logs?

**Comment by msaptrta** [comment]
[debug.txt](https://github.com/pivpn/pivpn/files/1075590/debug.txt)

[Test.txt](https://github.com/pivpn/pivpn/files/1075598/Test.txt)

Here are my debug.txt and client log (Test.txt).  It wouldn't let me upload my iptables-save

**Comment by cfcolaco** [comment]
@msaptrta your VPN client is a Windows machine right? 

before asking you anything else, how are you opening openvpn in windows? 
the correct way is to:

1 - Right click on OpenVPN Icon 
2 - Click "run as Administrator" 

and you should be good to go! If it doesn't work, please provide the output of 

sudo iptables -t nat -S

**Comment by msaptrta** [comment]
Yes the OpenVPN client is on a windows machine and yes, I right-click and run as administrator.
Here is the output of sudo iptables -t nat -S
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT
-A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE

**Comment by cfcolaco** [comment]
Are you connecting to the VPN from within your local network? 
Can you ping 10.8.0.1 when connected to the vpn? 
Can you ping 8.8.8.8 when connected to the vpn? 

please provide me the server configuration file ( hide any ip address // sensitive information )

**Comment by redfast00** [comment]
@msaptrta btw, you can just paste the content of text files inbetween triple backticks: see https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code. This will make it easier to quickly see the files, without having to download them.

**Comment by msaptrta** [comment]
@redfast00  Okay thanks for the info

**Comment by cfcolaco** [comment]
Connecting locally is pointless, and won't help to troubleshoot at all from now on please connect only from outside of your local network. 

So far ...

IPtables is OK
Client .ovpn seems ok
Server conf seems ok
Running OpenVPN client As Administrator - check 

can't see a reason for it not to be working... 

Is the OpenVPN client log the same when you connect from outside your network? any other messages appear?

Can you try with an Android phone or another device from outside your local network?

**Comment by msaptrta** [comment]
Yes I am running as administrator as stated before, and yes the client log is the same when connecting from outside the network.  No additional messages are given.  I tried on a different computer also running windows, but it also was unable to ping the addresses mentioned previously and returns a similar log file.

**Comment by msaptrta** [comment]
So I was poking around some log files and found something that may help in figuring out the issue.  This particular log file is the /var/log/openvpn.log.
```
Thu Jun 15 13:24:35 2017 OpenVPN 2.3.4 arm-unknown-linux-gnueabihf [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [MH] [IPv6] built on Jan 23 2016
Thu Jun 15 13:24:35 2017 library versions: OpenSSL 1.0.1t  3 May 2016, LZO 2.08
Thu Jun 15 13:24:35 2017 Control Channel Authentication: using '/etc/openvpn/easy-rsa/pki/ta.key' as a OpenVPN static key file
Thu Jun 15 13:24:35 2017 TUN/TAP device tun0 opened
Thu Jun 15 13:24:35 2017 do_ifconfig, tt->ipv6=0, tt->did_ifconfig_ipv6_setup=0
Thu Jun 15 13:24:35 2017 /sbin/ip link set dev tun0 up mtu 1500
Thu Jun 15 13:24:35 2017 /sbin/ip addr add dev tun0 10.8.0.1/24 broadcast 10.8.0.255
Thu Jun 15 13:24:35 2017 GID set to nogroup
Thu Jun 15 13:24:35 2017 UID set to nobody
Thu Jun 15 13:24:35 2017 Listening for incoming TCP connection on [undef]
Thu Jun 15 13:24:35 2017 TCPv4_SERVER link local (bound): [undef]
Thu Jun 15 13:24:35 2017 TCPv4_SERVER link remote: [undef]
Thu Jun 15 13:24:35 2017 Initialization Sequence Completed
```
Anyone have any suggestions on if the information here could lead to a solution?

**Comment by msaptrta** [comment]
I was able to make an "internet connection" through the VPN by removing a port triggering rule I had in place; however, I still am not able to access the network through the VPN.  Here is the client log file and /var/log/openvpn.log

Client Log File
```
Thu Jun 15 09:53:20 2017 OpenVPN 2.4.2 x86_64-w64-mingw32 [SSL (OpenSSL)] [LZO] [LZ4] [PKCS11] [AEAD] built on May 11 2017
Thu Jun 15 09:53:20 2017 Windows version 6.2 (Windows 8 or greater) 64bit
Thu Jun 15 09:53:20 2017 library versions: OpenSSL 1.0.2k  26 Jan 2017, LZO 2.10
Enter Management Password:
Thu Jun 15 09:53:20 2017 TCP/UDP: Preserving recently used remote address: [AF_INET]X.x.x.x:8443
Thu Jun 15 09:53:20 2017 Attempting to establish TCP connection with [AF_INET]X.x.x.x:8443 [nonblock]
Thu Jun 15 09:53:21 2017 TCP connection established with [AF_INET]X.x.x.x:8443
Thu Jun 15 09:53:21 2017 TCP_CLIENT link local: (not bound)
Thu Jun 15 09:53:21 2017 TCP_CLIENT link remote: [AF_INET]X.x.x.x:8443
Thu Jun 15 09:53:24 2017 [server] Peer Connection Initiated with [AF_INET]X.x.x.x:8443
Thu Jun 15 09:53:25 2017 open_tun
Thu Jun 15 09:53:25 2017 TAP-WIN32 device [Ethernet 3] opened: \\.\Global\{X.x.x.x}.tap
Thu Jun 15 09:53:25 2017 Set TAP-Windows TUN subnet mode network/local/netmask = 10.8.0.0/10.8.0.3/255.255.255.0 [SUCCEEDED]
Thu Jun 15 09:53:25 2017 Notified TAP-Windows driver to set a DHCP IP/netmask of 10.8.0.3/255.255.255.0 on interface {X.x.x.x} [DHCP-serv: 10.8.0.254, lease-time: 31536000]
Thu Jun 15 09:53:25 2017 Successful ARP Flush on interface [8] {X.x.x.x}
Thu Jun 15 09:53:25 2017 do_ifconfig, tt->did_ifconfig_ipv6_setup=0
Thu Jun 15 09:53:30 2017 Initialization Sequence Completed
Thu Jun 15 09:54:14 2017 SIGTERM[hard,] received, process exiting
```

/var/log/openvpn.log file
```
Thu Jun 15 13:24:35 2017 OpenVPN 2.3.4 arm-unknown-linux-gnueabihf [SSL (OpenSSL)] [LZO$
Thu Jun 15 13:24:35 2017 library versions: OpenSSL 1.0.1t  3 May 2016, LZO 2.08
Thu Jun 15 13:24:35 2017 Control Channel Authentication: using '/etc/openvpn/easy-rsa/p$
Thu Jun 15 13:24:35 2017 TUN/TAP device tun0 opened
Thu Jun 15 13:24:35 2017 do_ifconfig, tt->ipv6=0, tt->did_ifconfig_ipv6_setup=0
Thu Jun 15 13:24:35 2017 /sbin/ip link set dev tun0 up mtu 1500
Thu Jun 15 13:24:35 2017 /sbin/ip addr add dev tun0 10.8.0.1/24 broadcast 10.8.0.255
Thu Jun 15 13:24:35 2017 GID set to nogroup
Thu Jun 15 13:24:35 2017 UID set to nobody
Thu Jun 15 13:24:35 2017 Listening for incoming TCP connection on [undef]
Thu Jun 15 13:24:35 2017 TCPv4_SERVER link local (bound): [undef]
Thu Jun 15 13:24:35 2017 TCPv4_SERVER link remote: [undef]
Thu Jun 15 13:24:35 2017 Initialization Sequence Completed
Thu Jun 15 13:51:54 2017 TCP connection established with [AF_INET]192.168.1.1:52597
Thu Jun 15 13:51:56 2017 192.168.1.1:52597 [Tester] Peer Connection Initiated with [AF_$
Thu Jun 15 13:51:56 2017 Tester/192.168.1.1:52597 MULTI_sva: pool returned IPv4=10.8.0.$
Thu Jun 15 13:51:57 2017 Tester/192.168.1.1:52597 send_push_reply(): safe_cap=940
Thu Jun 15 13:53:17 2017 TCP connection established with [AF_INET]X.x.x.x:9378
Thu Jun 15 13:53:21 2017 X.x.x.x:9378 [Tester] Peer Connection Initiated with [AF$
Thu Jun 15 13:53:21 2017 Tester/X.x.x.x:9378 MULTI_sva: pool returned IPv4=10.8.0$
Thu Jun 15 13:53:22 2017 Tester/X.x.x.x:9378 send_push_reply(): safe_cap=940
Thu Jun 15 13:54:11 2017 Tester/X.x.x.x:9378 Connection reset, restarting [-1]
```

**Comment by cfcolaco** [comment]
Please, Try with an Android device, or something other than Windows so I can better track the issue and where to focus the troubleshooting!

**Comment by msaptrta** [comment]
I was able to successfully connect using an Android device; however the problem persist of not being able to access the network through the VPN.

**Comment by cfcolaco** [comment]
Ok. Please confirm the status: 
right now you can connect to vpn and reach the Internet with booth android and Windows however  you cant reach anything that is inside your local network.  Correct?

i will be traveling for a few days, ill try to help at the best o can.

**Comment by msaptrta** [comment]
That is correct.  I can connect and reach the internet with both android and windows client, but cannot reach anything inside local network.

**Comment by cfcolaco** [comment]
humm, just to be sure is your local network really 192.168.1.0/24 ? (192.168.1.0 // 255.255.255.0?

Can you ping across windows machines without being connected to the vpn? 

Do you have any firewall on the devices you are trying to reach inside your LAN? (Try to disable )

Sorry if Some questions seems so obvious, but i have to ask them, you would be suprised by number of things that dont work because of simple obvious things, and of course i dont know your background, i have to consider all possible scenarios!

**Comment by msaptrta** [comment]
I figured it out.  The local DNS lookup is unable to be accessed when using the VPN.  I was able to directly access the machines on my local network using direct IP addresses.  A little unconvient, but at least it works.  Thanks all, especially @cfcolaco , for the help and process of debugging the issue.

**Comment by cfcolaco** [comment]
Phew phew! I was starting to go crazy! And yet... a simple obvious thing =p
Good to know! You are not the first one complaining about local name resolution. Definitely something i will study after getting back home.

Cheers! And enjoy pivpn ;) and if there isn't anything else you would like to discuss, please close the issue!
