### ISSUE TITLE
piVPN and OctoPi - anybody able to run both on one raspberry?

### ISSUE THREAD

**Issue by SmilingSamoyed** [pivpn/pivpn#278]
## *warning, linux noob over here* 
i have flashed the SD for my Pi 3 with Octopi (3d printer monitoring software - http://octoprint.org/download/) which is a raspian based image and it works great, can remotely log into Octoprint on my network which was the goal. Now when i try run the bash on http://www.pivpn.io to set up a pi as a vpn server as well I get "installation successful" however, whenever i try opening any pivpn commands i received 'directory not found' or 'command not found' when i try to run it via ssh on Terminal.

http://imgur.com/a/NXtez 

Then when i go to re-install piVPN i notice a few errors pop up (shown below) as soon as a i run the installation. can anyone help me in determining where ive gone wrong in the installation process? All the youtube tutorials show it to be super simple process and ive triple checked the way they have been doing it but im not getting anywhere. Im suspecting it has something to do with the fact i have it flashed with OctoPi first but i have been told both could work on the same SD.

pi@octopi:/opt/pivpn $ sudo bash -c "$(curl -fsSL https://install.pivpn.io)";
:::
::: You are root.
::: Verifying free disk space...
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: Your system is up to date! Continuing with PiVPN installation...
::: Static IP already configured.
::: Using User: ***DELETED FROM DISPLAYING ON GITHUB***
:::   
::: Stopping OpenVPN service... done.
:::
::: Checking for existing base files...
:::    Checking /etc/.pivpn is a repo...:::    Cloning https://github.com/pivpn/pivpn.git into /etc/.pivpn... done!
:::
::: Installing scripts to /opt/pivpn...cp: cannot stat ‘/etc/.pivpn/scripts/makeOVPN.sh’: No such file or directory
cp: cannot stat ‘/etc/.pivpn/scripts/clientStat.sh’: No such file or directory
cp: cannot stat ‘/etc/.pivpn/scripts/listOVPN.sh’: No such file or directory
cp: cannot stat ‘/etc/.pivpn/scripts/removeOVPN.sh’: No such file or directory
cp: cannot stat ‘/etc/.pivpn/scripts/uninstall.sh’: No such file or directory
cp: cannot stat ‘/etc/.pivpn/scripts/pivpnDebug.sh’: No such file or directory
cp: cannot stat ‘/etc/.pivpn/scripts/fix_iptables.sh’: No such file or directory
chmod: cannot access ‘/opt/pivpn/makeOVPN.sh’: No such file or directory
chmod: cannot access ‘/opt/pivpn/clientStat.sh’: No such file or directory
chmod: cannot access ‘/opt/pivpn/listOVPN.sh’: No such file or directory
chmod: cannot access ‘/opt/pivpn/removeOVPN.sh’: No such file or directory
chmod: cannot access ‘/opt/pivpn/uninstall.sh’: No such file or directory
chmod: cannot access ‘/opt/pivpn/pivpnDebug.sh’: No such file or directory
chmod: cannot access ‘/opt/pivpn/fix_iptables.sh’: No such file or directory
cp: cannot stat ‘/etc/.pivpn/pivpn’: No such file or directory
chmod: cannot access ‘/usr/local/bin/pivpn’: No such file or directory
cp: cannot stat ‘/etc/.pivpn/scripts/bash-completion’: No such file or directory
bash: line 409: /etc/bash_completion.d/pivpn: No such file or directory
 done.

**Comment by cfcolaco** [comment]
Sorry for keeping you here without any feedback.do you still have this issue?

As far as I could understand, octopi just run on top of raspbian // debian // ubuntu, so theoretically PiVPN script should work in harmony and have a happy life with octopi. 

the error you provide it makes me think that the script failed to create /opt/pivpn/ directory for some reason ... have you tried to re-run the OpenVPN Install script?

**Comment by SmilingSamoyed** [comment]
Hi, thank you for your reply.

Still have my issue and have tried again and again but still no issue (same issue as before). No matter how careful i am for some reason when i first execute the script, looking in the log it comes up with all those errors shown in the original post.

I have tried posting the issue on Reddit [(link here)](https://www.reddit.com/r/selfhosted/comments/6hwyzx/octopi_pivpn_on_the_same_raspberry/) and someone has said the following which should fix it but i have no idea what it means:

_"Did the installer warn you for a "maybe support" of the host OS? Seems as it has some weird codename checks.

The installer script seemed to have installed some rules into /etc/dhcpd.conf and it seems to only work with static addresses.

Also, check out /opt/pivpn. There are some tools there, like pivpnDebug.sh which seems to be a debug mode for the software.

cd /opt/pivpn;
./pivpnDebug.sh;

pivpn itself should be located at /usr/local/bin/pivpn. If that's not the case you probably missed the sudo before the installer or so."_

**Comment by cfcolaco** [comment]
definitely, there's something is going wrong there! 

Can you try to run the script with the real root user instead of a user that has to sudo in order to scale privileges? ( assuming that you have not did this ) 

Since I don't have a spare pi right know to test this (planning to get one soon), can you please provide me the output of:

`lsb_release`

and 

`cat /etc/os-release` 

I will try to take it from there ...

**Comment by SmilingSamoyed** [comment]
i am trying to run the script now as root (even though i think i already tried by typing the command sudo -s and running the script).

heres the output for your commands:

root@octopi:/home/pi# lsb_release
No LSB modules are available.

root@octopi:/home/pi# cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
root@octopi:/home/pi#

**Comment by SmilingSamoyed** [comment]
Update: running the script in root doesnt look great as well! :')

root@octopi:/home/pi# curl -L https://install.pivpn.io | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   178  100   178    0     0    126      0  0:00:01  0:00:01 --:--:--   126
:::
::: You are root.
100 43750  100 43750    0     0  21246      0  0:00:02  0:00:02 --:--:-- 21246
::: Verifying free disk space...
:::
::: apt-get update has not been run today. Running now... done!
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: There are 17 updates available for your system!
::: We recommend you update your OS after installing PiVPN! 
:::
::: Static IP already configured.
::: Using User: **leaving blank**
:::   
::: Stopping OpenVPN service... done.
:::
::: Checking for existing base files...
:::    Checking /etc/.pivpn is a repo...:::    Cloning https://github.com/pivpn/pivpn.git into /etc/.pivpn... done!
:::
::: Installing scripts to /opt/pivpn...cp: cannot stat ‘/etc/.pivpn/scripts/makeOVPN.sh’: No such file or directory
cp: cannot stat ‘/etc/.pivpn/scripts/clientStat.sh’: No such file or directory
cp: cannot stat ‘/etc/.pivpn/scripts/listOVPN.sh’: No such file or directory
cp: cannot stat ‘/etc/.pivpn/scripts/removeOVPN.sh’: No such file or directory
cp: cannot stat ‘/etc/.pivpn/scripts/uninstall.sh’: No such file or directory
cp: cannot stat ‘/etc/.pivpn/scripts/pivpnDebug.sh’: No such file or directory
cp: cannot stat ‘/etc/.pivpn/scripts/fix_iptables.sh’: No such file or directory
chmod: cannot access ‘/opt/pivpn/makeOVPN.sh’: No such file or directory
chmod: cannot access ‘/opt/pivpn/clientStat.sh’: No such file or directory
chmod: cannot access ‘/opt/pivpn/listOVPN.sh’: No such file or directory
chmod: cannot access ‘/opt/pivpn/removeOVPN.sh’: No such file or directory
chmod: cannot access ‘/opt/pivpn/uninstall.sh’: No such file or directory
chmod: cannot access ‘/opt/pivpn/pivpnDebug.sh’: No such file or directory
chmod: cannot access ‘/opt/pivpn/fix_iptables.sh’: No such file or directory
cp: cannot stat ‘/etc/.pivpn/pivpn’: No such file or directory
chmod: cannot access ‘/usr/local/bin/pivpn’: No such file or directory
cp: cannot stat ‘/etc/.pivpn/scripts/bash-completion’: No such file or directory
bash: line 410: /etc/bash_completion.d/pivpn: No such file or directory
 done.
::: Using protocol: udp
::: Building CA...
Generating a 2048 bit RSA private key
................+++
........................+++
writing new private key to '/etc/openvpn/easy-rsa/pki/private/ca.key.Sz9IzGGd43'
-----

::: CA Complete.

**Comment by cfcolaco** [comment]
`ls -la /etc/ | grep .pivpn `

and tell me if that dir exists, please.

**Comment by SmilingSamoyed** [comment]
root@octopi:/home/pi# ls -la /etc/ | grep .pivpn
drwxr-xr-x  2 root root    4096 Jun 18 11:47 pivpn
root@octopi:/home/pi#

**Comment by cfcolaco** [comment]
there we go!
For some reason .pivpn is not being created ... before trying any workaround, I would like to try to understand where is the script failing. 

Since that folder is created with git when the script clones the git repo into /etc/.pivpn, it makes sense that you git is failing to install and the script fails to detect it! 

@0-kaladin @redfast00  am i right? it seems that the script consistently fails to detect a failure in dependencies installation ... it is not the first time that I see this here ... any solution for this?

Please try to install git manually and provide me the output.

`sudo apt-get install git`

**Comment by SmilingSamoyed** [comment]
Hi this is the output for that command (tried with both normal and root user):

pi@octopi:~ $ sudo apt-get install git
Reading package lists... Done
Building dependency tree       
Reading state information... Done
git is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 24 not upgraded.

pi@octopi:~ $ sudo -s
root@octopi:/home/pi# sudo apt-get install git
Reading package lists... Done
Building dependency tree        
Reading state information... Done
git is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 24 not upgraded.

**Comment by cfcolaco** [comment]
Ok so seems that everything is fine with Git ... 

Let's try to create the .pivpn dir ourselves ...  
please do: 

`sudo git clone https://github.com/pivpn/pivpn.git /etc/.pivpn`

**if** everything goes without any errors, ty to install pivpn again. 

I Have now an rpi where I can make some tests when I have some time I will try to install octopi and see if the same error happens to me also.

**Comment by SmilingSamoyed** [comment]
Thanks for replying, octoprint does not seem to like that command:
oot@octopi:/home/pi# sudo git clone https://github.com/pivpn/pivpn.git /etc/.pivpn
Please run git without sudo, your regular user account is enough :)
root@octopi:/home/pi# git clone https://github.com/pivpn/pivpn.git /etc/.pivpn
Please run git without sudo, your regular user account is enough :)

Some quick Reddit search indicates that Octoprint prevents that command:
https://www.reddit.com/r/pihole/comments/5mheaj/trouble_with_automated_installer/?st=J4HH036O&sh=33b6a0ae 

*That error is usually seen with OctoPrint. Are you using that disribution? You need to contact OctoPrint and ask them to please unblock `git` from being used as it was intended.*

**Comment by cfcolaco** [comment]
try with regular user pls ... however it  might not succeed since regular user probably cant write to /etc/ but worth trying. 

It might be a octoprint related issue ... if it doesnt work we can also work around it like this

with a regular user:
`cd ~/ && git clone https://github.com/pivpn/pivpn.git` 

Now escalate your privileges with sudo or become root ( vhoose your prefered method)
and then:
`cd ~/<regularuser> && mv pivpn /etc/.pivpn`

And rerun the script. I am pretty sure it will work like this

Obs: I am on my mobile phone, and I have an horrible relationship with touchscreens so, sorry for some mistakes, and pay extra attention to commands, hope you get the concept of this workaround.

**Comment by SmilingSamoyed** [comment]
Hi, thanks for all your help, really appreciate it. I did try using the normal user as well and got the same error. 

I am at work so will try the work around and let you know tonight. Thanks again

**Comment by cfcolaco** [comment]
@SmilingSamoyed as I expected usual /etc/ perms are rwxr-x-r-x (755) .. meanwhile I will look through octopi github and check if ther isn't any issue related to this situation, otherwise I will open one.

**Comment by cfcolaco** [comment]
@SmilingSamoyed there's an easier way to do this ... just 

`/usr/bin/git clone https://github.com/pivpn/pivpn.git /etc/.pivpn`

it should work. 
ppl ac Octopi stated their point and it seems that they won't fall back with it, so will think of a better way of pivpn work around it to support octoprint and still keep it's support to other distros. 

meanwhile, all users wanting to use octopi should work around like i've mentioned. 

@redfast00 can this be marked as an enhancement? what's your opinion about his?

**Comment by SmilingSamoyed** [comment]
So judging by that reference post I shouldn't be loading pivpn with octopi flashed because 'I should know what I'm doing'?

**Comment by SmilingSamoyed** [comment]
Oh ok,  never mind, I'll try your suggestion now

**Comment by SmilingSamoyed** [comment]
Thanks for the tip, seems like it was created successfully:
pi@octopi:~ $ sudo -s
root@octopi:/home/pi# /usr/bin/git clone https://github.com/pivpn/pivpn.git /etc/.pivpn
Cloning into '/etc/.pivpn'...
remote: Counting objects: 728, done.
remote: Compressing objects: 100% (4/4), done.
Receiving objects:  94% (685/728), 164.01 KiB | 319.Receiving objects:  95% (692/728), 164.01 KiB | 319.Receiving objects:  96% (699/728), 164.01 KiB | 319.Receiving objects:  97% (707/728), 164.01 KiB | 319.Receiving objects:  98% (714/728), 164.01 KiB | 319.Receiving objects:  99% (721/728), 164.01 KiB | 319.remote: Total 728 (delta 0), reused 3 (delta 0), pack-reused 723
Receiving objects: 100% (728/728), 164.01 KiB | 319.Receiving objects: 100% (728/728), 175.94 KiB | 319.00 KiB/s, done.
Resolving deltas: 100% (396/396), done.
Checking connectivity... done.

**Comment by cfcolaco** [comment]
@SmilingSamoyed won't comment that since I don't want to buy any wars around here. 

Now that you already have /etc/.pivpn  just run the pivpn install script! and it sould work.

**Comment by SmilingSamoyed** [comment]
No worries, amazing community with this group, I really do appreciate the help

**Comment by redfast00** [comment]
Good job figuring it out! I don't think we (PiVPN) should provide a workaround for installing: since OctoPrint messes with the git command, they (or the users that use octoprint) should be responsible for cleaning up the git command. If this comes back in other issues,  you can link other users to this issue. Closing this since the issue got fixed.

**Comment by idrisms** [comment]
GREAT !!!! it works, before this it just skip the UDP/TCP part in the grey blue screen box(seen a vid on you tube) . After i follow all the  instructions over here, and type `curl -L https://install.pivpn.io | bash`, the UDP/TCP part appear in the grey blue box screen. Thanks everyone.. Goodjob!!!

**Comment by tijsrx** [comment]
> try with regular user pls ... however it might not succeed since regular user probably cant write to /etc/ but worth trying.
> 
> It might be a octoprint related issue ... if it doesnt work we can also work around it like this
> 
> with a regular user:
> `cd ~ && git clone https://github.com/pivpn/pivpn.git`
> 
> Now escalate your privileges with sudo or become root ( vhoose your prefered method)
> and then:
> `cd ~<regularuser> && mv pivpn /etc/.pivpn`
> 
> And rerun the script. I am pretty sure it will work like this
> 
> Obs: I am on my mobile phone, and I have an horrible relationship with touchscreens so, sorry for some mistakes, and pay extra attention to commands, hope you get the concept of this workaround.

`cd ~<regularuser> && mv pivpn /etc/.pivpn` gives a syntax error for me :/ (I'm also a complete noob so I need step by step instructions)
