### ISSUE TITLE
Error Creating client crt

### ISSUE THREAD

**Issue by airforceboricua** [pivpn/pivpn#28]
Getting this when running 'pivpn add':

```
Enter a Name for the Client:  test
NOTE: If you run ./clean-all, I will be doing a rm -rf on /etc/openvpn/easy-rsa/keys
/etc/openvpn/easy-rsa/vars: line 65: unexpected EOF while looking for matching ``'
/etc/openvpn/easy-rsa/vars: line 81: syntax error: unexpected end of file
Enter the password for the Client:
Enter the password again to verify:
spawn ./build-key-pass test
pkitool: Need a readable ca.crt and ca.key in /etc/openvpn/easy-rsa/keys
Try pkitool --initca to build a root certificate/key.
expect: spawn id exp6 not open
    while executing
"expect "Verifying - Enter PEM pass phrase" { send "test123\r" }"
spawn openssl rsa -in test.key -des3 -out test.3des.key
Error opening Private Key test.key
1995716704:error:02001002:system library:fopen:No such file or directory:bss_file.c:398:fopen('test.key','r')
1995716704:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:400:
unable to load Private Key
expect: spawn id exp6 not open
    while executing
"expect "Enter PEM pass phrase" { send "test123\r" }"
[ERROR]: Client Public Key Certificate not found: test.crt
```

Any ideas?  Thanks for all of this by the way.  Made everything very simple.

**Comment by 0-kaladin** [comment]
hmm can you 'cat /etc/openvpn/easy-rsa/vars'
and paste that output here?

**Comment by airforceboricua** [comment]
Sure can.

`# easy-rsa parameter settings

# NOTE: If you installed from an RPM,
# don't edit this file in place in
# /usr/share/openvpn/easy-rsa --
# instead, you should copy the whole
# easy-rsa directory to another location
# (such as /etc/openvpn) so that your
# edits will not be wiped out by a future
# OpenVPN package upgrade.

# This variable should point to
# the top level of the easy-rsa
# tree.
export EASY_RSA="/etc/openvpn/easy-rsa"

#
# This variable should point to
# the requested executables
#
export OPENSSL="openssl"
export PKCS11TOOL="pkcs11-tool"
export GREP="grep"


# This variable should point to
# the openssl.cnf file included
# with easy-rsa.
export KEY_CONFIG=`$EASY_RSA/whichopensslcnf $EASY_RSA`

# Edit this variable to point to
# your soon-to-be-created key
# directory.
#
# WARNING: clean-all will do
# a rm -rf on this directory
# so make sure you define
# it correctly!
export KEY_DIR="$EASY_RSA/keys"

# Issue rm -rf warning
echo NOTE: If you run ./clean-all, I will be doing a rm -rf on $KEY_DIR

# PKCS11 fixes
export PKCS11_MODULE_PATH="dummy"
export PKCS11_PIN="dummy"

# Increase this to 2048 if you
# are paranoid.  This will slow
# down TLS negotiation performance
# as well as the one-time DH parms
# generation process.
export KEY_SIZE=2048

# In how many days should the root CA key expire?
export CA_EXPIRE=3650

# In how many days should certificates expire?
export KEY_EXPIRE=3650

# These are the default values for fields
# which will be placed in the certificate.
# Don't leave any of these fields blank.
export KEY_COUNTRY="US"
export KEY_PROVINCE="TX`"
export KEY_CITY="Austin"
export KEY_ORG="Fort Nutz"
export KEY_EMAIL="airforceboricua33@yahoo.com"
export KEY_OU="PiVPN"

# X509 Subject Field
export KEY_NAME="EasyRSA"

# PKCS11 Smart Card
# export PKCS11_MODULE_PATH="/usr/lib/changeme.so"
# export PKCS11_PIN=1234

# If you'd like to sign all keys with the same Common Name, uncomment the KEY_CN        export below
# You will also need to make sure your OpenVPN server config has the duplicate-c       n option set
# export KEY_CN="CommonName"
`

Thanks!

**Comment by 0-kaladin** [comment]
you have a bunch of blank values. 
if you run 'pivpn -v' what version are you on?

Please edit that vars file like
nano /etc/openvpn/easy-rsa/vars
and manually go ahead and put in values for
```
export KEY_COUNTRY="US"
export KEY_PROVINCE="CA"
export KEY_CITY="SanFrancisco"
export KEY_ORG="Fort-Funston"
export KEY_EMAIL="me@myhost.mydomain"
export KEY_OU="PiVPN"
```

you'll see a bunch of yours are blank or just empty.  Not sure how they got that way.  Unless you installed this days ago.

**Comment by airforceboricua** [comment]
Yup, re-ran the install and all is good.  Thank you for your help!

**Comment by arikalfus** [comment]
I am also getting this error and I have custom values for all of the variables mentioned above. I compared my file and the only diff is the key size, mine is 4096 (I know).

However, this error happens after I am prompted to enter a PEM pass phrase. I press enter, and after a timeout, I am presented with the above error. Adding it here because the error is similar - let me know if I should move it to a new issue.

    Enter a Name for the Client:  <clientName>
    NOTE: If you run ./clean-all, I will be doing a rm -rf on /etc/openvpn/easy-rsa/keys
    Enter the password for the Client: <clientPassword>
    Enter the password again to verify: <clientPassword>
    spawn ./build-key-pass <clientName>
    Generating a 4096 bit RSA private key
    ...<generation>..
    writing new private key to '<clientName>.key'
    Enter PEM pass phrase:<passphrase was entered>
    spawn openssl rsa -in <clientName>.key -des3 -out <clientName>.3des.key
    unable to load Private Key
    1995778144:error:0906D06C:PEM routines:PEM_read_bio:no start line:pem_lib.c:696:         
    Expecting: ANY PRIVATE KEY
    expect: spawn id exp6 not open
        while executing
    "expect "Enter PEM pass phrase" { send "<clientPassword>\r" }"
    [ERROR]: Client Public Key Certificate not found: <clientName>.crt

**Comment by 0-kaladin** [comment]
Don't put any spaces in the pass phrase if you are.

**Comment by arikalfus** [comment]
No I'm not adding any spaces, and I also tried alphanumeric in the chance that symbols were causing an issue.

**Comment by arikalfus** [comment]
Wanted to break down what's happening, there's a 30-50 second timeout after entering the PEM pass phrase, followed by the error and the repetition of the PEM pass phrase into bash, as if it wasn't entered into the pivpn prompt. See the output below. The client password was testPass, the PEM pass phrase was testPass123!$. Not sure where testPass123add came from, is that an indicator for what is going on?

    pivpn add
    Enter a Name for the Client:  test
    NOTE: If you run ./clean-all, I will be doing a rm -rf on /etc/openvpn/easy-rsa/keys
    Enter the password for the Client:
    Enter the password again to verify:
    Passwords do not match! Please try again.
    Enter the password for the Client:
    Enter the password again to verify:
    spawn ./build-key-pass test
    Generating a 4096 bit RSA private key
    ........................................++
    ...........................................................................++
    writing new private key to 'test.key'
    Enter PEM pass phrase:testPass123!$
    spawn openssl rsa -in test.key -des3 -out test.3des.key
    unable to load Private Key
    1996294240:error:0906D06C:PEM routines:PEM_read_bio:no start line:pem_lib.c:696:Expecting: ANY PRIVATE KEY
    expect: spawn id exp6 not open
        while executing
    "expect "Enter PEM pass phrase" { send "testPass\r" }"
    [ERROR]: Client Public Key Certificate not found: test.crt
    pi@ari_rp3:~ $ testPass123!$
    testPass123add
    -bash: testPass123add: command not found

**Comment by 0-kaladin** [comment]
You need to use the same pass. So if you use testPass above then that is
what you provide below, not something different.

**Comment by arikalfus** [comment]
I had tried that in earlier examples, wasn't sure about it so had it differently in this example. Thank you for the clarification. So I just got a client certificate to successfully create - using testPass as the password. If I use an alphanumeric or add symbols to the password, it fails. So testPass123 fails, testPass! fails. That can't be right, that the password is limited to alphabetical characters, right?

**Comment by 0-kaladin** [comment]
I'd think it should allow more than just alpha.  I'd have to test outside of the script to see if its me or openvpn build-key-pass itself.

**Comment by arikalfus** [comment]
Re-open issue while that's investigated? Or what makes more sense probably is to make a new issue to look into that and move these last comments over to that?

**Comment by MatthijsLiethof** [comment]
I think this might be related https://github.com/pivpn/pivpn/issues/62
