### ISSUE TITLE
Update to OpenVPN 2.4.3 or 2.3.17

### ISSUE THREAD

**Issue by AdySan** [pivpn/pivpn#280]
# PiVPN Issue Template

## Console output of `pivpn debug`
```
::: Generating Debug Output
:::                                     :::
::              PiVPN Debug              ::
:::                                     :::
::      Latest Commit                    ::
:::                                     :::
commit 6ce39bfec399d9a8203409a108ef27f2ee29327a
Author: 0-kaladin <0.kaladin@gmail.com>
Date:   Mon Feb 27 21:01:23 2017 -0500

    Update README for IRC channel

    Due to discontinuation of Google Spaces
:::                                     :::
::      Recursive list of files in       ::
::      /etc/openvpn/easy-rsa/pki        ::
:::                                     :::
/etc/openvpn/easy-rsa/pki/:
AdyPiOpenVPN.ovpn
ca.crt
Default.txt
dh2048.pem
index.txt
index.txt.attr
index.txt.attr.old
index.txt.old
issued
private
serial
serial.old
ta.key

/etc/openvpn/easy-rsa/pki/issued:
AdyPiOpenVPN.crt
server.crt

/etc/openvpn/easy-rsa/pki/private:
AdyPiOpenVPN.key
ca.key
server.key
:::                                     :::
::      Output of /etc/pivpn/*           ::
:::                                     :::
:: START /etc/pivpn/DET_PLATFORM ::
Raspbian
:: END /etc/pivpn/DET_PLATFORM ::
:: START /etc/pivpn/INSTALL_PORT ::
1194
:: END /etc/pivpn/INSTALL_PORT ::
:: START /etc/pivpn/INSTALL_PROTO ::
udp
:: END /etc/pivpn/INSTALL_PROTO ::
:: START /etc/pivpn/INSTALL_USER ::
pi
:: END /etc/pivpn/INSTALL_USER ::
:: START /etc/pivpn/NO_UFW ::
1
:: END /etc/pivpn/NO_UFW ::
:: START /etc/pivpn/pivpnINTERFACE ::
eth0
:: END /etc/pivpn/pivpnINTERFACE ::
:: START /etc/pivpn/REVOKE_STATUS ::
0
:: END /etc/pivpn/REVOKE_STATUS ::
:::                                     :::
:: /etc/openvpn/easy-rsa/pki/Default.txt ::
:::                                     :::
client
dev tun
proto tcp
remote adysan.ddns.net 22
resolv-retry infinite
nobind
persist-key
persist-tun
key-direction 1
remote-cert-tls server
tls-version-min 1.2
verify-x509-name server name
cipher AES-256-CBC
auth SHA256
comp-lzo
verb 1
:::                                     :::
::      Debug Output Complete            ::
:::                                     :::
:::
::: Debug output completed above.
::: Copy saved to /tmp/debug.txt
:::
```

## Issue
According to [this](https://guidovranken.wordpress.com/2017/06/21/the-openvpn-post-audit-bug-bonanza/) article new vulnerabilities were found an fixed in OpenVPN. Is there any way to upgrade or check the version of OpenVPN being used?

**Comment by cfcolaco** [comment]
Pivpn will always get the latest openvpn version available on distro repos. So no matter the script build date, what pivpn will do to install openvpn is a simple apt-get install openvpn

**Comment by AdySan** [comment]
Hmm, here's what I see, 

```
pi@AdyPi3:~ $ openvpn --version
OpenVPN 2.3.4 arm-unknown-linux-gnueabihf [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [MH] [IPv6] built on Jan 23 2016
library versions: OpenSSL 1.0.1t  3 May 2016, LZO 2.08
Originally developed by James Yonan
Copyright (C) 2002-2010 OpenVPN Technologies, Inc. <sales@openvpn.net>
Compile time defines: enable_crypto=yes enable_debug=yes enable_def_auth=yes enable_dependency_tracking=no enable_dlopen=unknown enable_dlopen_self=unknown enable_dlopen_self_static=unknown enable_fast_install=yes enable_fragment=yes enable_http_proxy=yes enable_iproute2=yes enable_libtool_lock=yes enable_lzo=yes enable_lzo_stub=no enable_maintainer_mode=no enable_management=yes enable_multi=yes enable_multihome=yes enable_pam_dlopen=no enable_password_save=yes enable_pedantic=no enable_pf=yes enable_pkcs11=yes enable_plugin_auth_pam=yes enable_plugin_down_root=yes enable_plugins=yes enable_port_share=yes enable_selinux=no enable_server=yes enable_shared=yes enable_shared_with_static_runtimes=no enable_small=no enable_socks=yes enable_ssl=yes enable_static=yes enable_strict=no enable_strict_options=no enable_systemd=yes enable_win32_dll=yes enable_x509_alt_username=yes with_crypto_library=openssl with_gnu_ld=yes with_ifconfig_path=/sbin/ifconfig with_iproute_path=/sbin/ip with_mem_check=no with_plugindir='${prefix}/lib/openvpn' with_route_path=/sbin/route with_sysroot=no
```

I though I had said yes to the option of doing nightly `apt-get update`

**Comment by AdySan** [comment]
Oh, just saw this on the PiVPN website 

> In regards to PiVPN, this means that once OpenVPN 2.4 is released we will make every effort to have PiVPN use this version. This way we gain the security fixes that will come post audit. At that time we will also be able to use the better EC (elliptic curve) ciphers in creating certificates which should be more secure and also less taxing on clients.

**Comment by cfcolaco** [comment]
@AdySan been looking the code, and you're right, Sorry it was my bad, ignore what I said, I have been traveling these days, just got home, tomorrow I will take a better look at it!

**Comment by wranzzon** [comment]
so there is no way to update to 2.4.3 for the moment?

**Comment by xanalaom00** [comment]
Is there an update when we can expect pivpn script to incorporate the newer 2.4.3?  also, would compiling/installing from source still work with pivpn if I wanted to upgrade asap?

Thank you

**Comment by cfcolaco** [comment]
guess we will have to wait a while for pivpn to use 2.4.3 version ... if you would like to update it, check here: 

https://community.openvpn.net/openvpn/wiki/OpenvpnSoftwareRepos

don't know if it will break pivpn or not. test at your own risk!

**Comment by xanalaom00** [comment]
I have installed the source, so far this just works...  pivpn scripts
behave the same as well so far.  The only difference I see is that for some
reason I am unable to connect to it from the WAN interface, but it connects
just fine on my local network... so I'm thinking either A) my WAN IP
changed but my router needs a reboot or B) there is a firewall rule in
place from PiVPN that is preventing this... but taking a look at the
IPtables rules there isn't anything there... so... it must be my router
blocking traffic.

**Comment by cfcolaco** [comment]
@AdySan @wranzzon @xanalaom00 

PiVPN code was updated with pull request #292  and is now installing openvpn 2.4.3

thank you  @xanalaom00 for making some tests. 

think this can be closed now! =)

**Comment by cfcolaco** [comment]
@AdySan been looking with more attention trough the code, after all, I was right, PiVPN simply does apt-get <package> to install packages. 

for Ubuntu and Debian it adds the OpenVPN repos and for raspbian, it uses the main repo.

having this said after PR #292  Ubuntu and Debian will use the latest stable OpenVPN version, however Raspbian will still use 2.3.2 since ther's still no port to arm architecture yet. users using rpi and raspbian will have to wait a bit more until OpenVPN 2.4 gets ported to ar.

@redfast00 guess would be good to add a side note in the wiki topic about updating OpenVPN about this to avoid that users using raspbian add the OpenVPN repo which will sit there doing nothing but giving an error in apt-get update

**Comment by ScriptAutomate** [comment]
@cfcolaco I'm wondering whether there could be a prompt added, when 'Raspbian' is found to be the PLAT, that asks whether the user would want to compile the latest OpenVPN from source (and to also have an 'update' script that builds the latest stable version each time a release occurs)? 

If so, could we create a new issue with a feature/enhancement flag for this type of option? I have a strong feeling that many people would be interested in this route.

**Comment by cfcolaco** [comment]
@ScriptAutomate that's one possible solution ... however, I don't think it would be the best idea ... PiVPN is used for a large number of linux begginers and I belive that having the possibility to compile openvpn from source would cause a lot of trouble specially for who is trying to maintain this script, specially in terms of support to users. 

I am right now investigating and trying to reach package maintainers to see what can be done to make the package available in raspbian as soon as possible. 

in Fedora / CentOS i know that packages have a karma system where users try the packages from the testing repo and then provide feedback about it. In Debian, i just don't know how it works exactly, but if it is a similar system, I think would be far more reliable to have PiVPN more experienced users testing the package and providing the proper feedback so the package can get released to stable repositories than having it being compiled from source or in the worst case scenario, if package maintainer had left the town, get a couple of volunteers to maintain it! :P

**Comment by cfcolaco** [comment]
@AdySan @ScriptAutomate been digging around ...security is not a concern with raspbian OpenVPN 2.3.4 package since Debian package maintainers backported the security patches.

It can be seen 

here: https://security-tracker.debian.org/tracker/source-package/openvpn
and here: https://tracker.debian.org/pkg/openvpn

Don't expect raspbian Jessie to have a 2.4.x package anytime soon. if OpenVPN 2.4.x is a must have it must be compiled from source or wait until rasbian stretch gets released, however security patches will cotinue to be backported.

**Comment by ScriptAutomate** [comment]
@cfcolaco I was wondering what the deb8u2 was about in just recently updating openvpn on the Pi -- good to see. Current approach makes more sense rather than going through that effort of an ad-hoc compile switch
