### ISSUE TITLE
Add option to regenerate `ovpn` config when config changed

### ISSUE THREAD

**Issue by 3v1n0** [pivpn/pivpn#281]
If some changes happened to `/etc/openvpn/server.conf` and you want to regenerate the `.ovpn` config files, you need to go by hand... It would be nice to have an helper script for that.

**Comment by killermosi** [comment]
You could use a tool like `sed` to do mass replace.

**Comment by cfcolaco** [comment]
Think it would be a great feature to add. 
If someone wants to take the hammer on this one ... go for it .. otherwise will have to wait for someone to have time for it .. me included.
