### ISSUE TITLE
Error parsing OpenVPN profile : option_error: remote option not specified.

### ISSUE THREAD

**Issue by Kevintjeb** [pivpn/pivpn#283]
# **ERROR**

Error parsing OpenVPN profile: option_error: remote option not specified.
---------------------

Installing PiVPN went smoothly, everything is working. Creating a profile also worked fine, but when I try to import it on my phone I get the error: 

Error parsing OpenVPN profile: option_error: remote option not specified.

Now it seems that I am missing the remote option. But I double checked it and it is there. The IP is my public IP and the port is forwarded in my router.

**Comment by redfast00** [comment]
Can you post the output of `pivpn debug`? Can you post the `.ovpn` file? Please censor the keys.

**Comment by Kevintjeb** [comment]
Maybe it is because of the android app. I just connected using my laptop with OpenVPN GUI and it worked fine. Do you still need the pivpn debug and .ovpn file?

**Comment by liam2317** [comment]
I had this same problem when trying to connect with the "OpenVPN Connect" app on Android.  

**.ovpn file:**
```
<ca>
-----BEGIN CERTIFICATE-----
REMOVED
-----END CERTIFICATE-----
</ca>
<cert>
-----BEGIN CERTIFICATE-----
REMOVED
-----END CERTIFICATE-----
</cert>
<key>
-----BEGIN ENCRYPTED PRIVATE KEY-----
REMOVED
-----END ENCRYPTED PRIVATE KEY-----
</key>
<tls-auth>
#
# 2048 bit OpenVPN static key
#
-----BEGIN OpenVPN Static key V1-----
REMOVED
-----END OpenVPN Static key V1-----
</tls-auth>

```

**pivpn debug:**
```
:::					:::
::		PiVPN Debug		 ::
:::					:::
::	Latest Commit			 ::
:::					:::
commit 6ce39bfec399d9a8203409a108ef27f2ee29327a
Author: 0-kaladin <0.kaladin@gmail.com>
Date:   Mon Feb 27 21:01:23 2017 -0500

    Update README for IRC channel
    
    Due to discontinuation of Google Spaces
:::					:::
::	Recursive list of files in	 ::
::	/etc/openvpn/easy-rsa/pki	 ::
:::					:::
/etc/openvpn/easy-rsa/pki/:
ca.crt
crl.pem
dh2048.pem
index.txt
index.txt.attr
index.txt.attr.old
index.txt.old
issued
Laptop.ovpn
Phone.ovpn
private
serial
serial.old
ta.key
Test.ovpn

/etc/openvpn/easy-rsa/pki/issued:
Laptop.crt
Phone.crt
server.crt

/etc/openvpn/easy-rsa/pki/private:
ca.key
Laptop.key
Phone.key
server.key
:::					:::
::	Output of /etc/pivpn/*		 ::
:::					:::
:: START /etc/pivpn/INSTALL_PORT ::
REMOVED
:: END /etc/pivpn/INSTALL_PORT ::
:: START /etc/pivpn/INSTALL_PROTO ::
udp
:: END /etc/pivpn/INSTALL_PROTO ::
:: START /etc/pivpn/INSTALL_USER ::
REMOVED:: END /etc/pivpn/INSTALL_USER ::
:: START /etc/pivpn/NO_UFW ::
0
:: END /etc/pivpn/NO_UFW ::
:: START /etc/pivpn/pivpnINTERFACE ::
eth0
:: END /etc/pivpn/pivpnINTERFACE ::
:::					:::
:: /etc/openvpn/easy-rsa/pki/Default.txt ::
:::					:::
:::					:::
::	Debug Output Complete		 ::
:::					:::

```

I also cannot connect from my Windows 7 laptop.  It fails and says to check the log file.  The log file says:
```
Mon Jun 26 15:31:49 2017 disabling NCP mode (--ncp-disable) because not in P2MP client or server mode
Options error: You must define TUN/TAP device (--dev)
Use --help for more information.

```

Thank you for any assistance you can provide!!

**Comment by Kevintjeb** [comment]
@redfast00 Any idea? I had this the first time I installed PiVPN aswell. But it got fixed when I installed it a second time. Now, the third time, it is back. 

OpenVPN GUI on PC works fine with the same profile.
OpenVPN Connect does not work because of the remote option.

**Comment by redfast00** [comment]
Can you post your `.ovpn` file?

**Comment by Kevintjeb** [comment]
This is my .ovpn file : 
https://pastebin.com/6KUpb4tV

**Comment by redfast00** [comment]
Have you tried using OpenVPN for Android by Arne Schwabe? The ovpn looks okay.

**Comment by Kevintjeb** [comment]
@redfast00 I tried using the app OpenVPN for android but it does not work either. It adds the .ovpn file but when I click on the profile to start the connection it says I need to select a user certificate. But you saw it was all inside the .ovpn file.

**Comment by Kevintjeb** [comment]
Are there other clients I can try to use? I created new client profiles, all with the same error.

**Comment by InfoSecured** [comment]
Did you ever find a resolution for this? I'm having the same issue on the iPhone app.

**Comment by Kevintjeb** [comment]
@infoSecured I have not found a resolution. I did create a new .openvpn last week on the same install, that one worked like a charm. The thing I did differently is not having special characters in my .openvpn file password..

**Comment by jamiejones85** [comment]
I had this issue with the Android app. I'd emailed the ovpn to myself to get it on to my phone. I tried again using the usb cable to get the opvn file on to my phone and it worked.

Strange thing is, I could import the ovpn file I'd emailed to myself on my mac and connect, so it could be something the gmail client on the phone does when it handles the file.

**Comment by kizomanizo** [comment]
In 2020, still getting this on Windows and iPhone client

**Comment by goxofy** [comment]
I Have The same error on iPhone

**Comment by Bajotumn** [comment]
I resolved this by saving the .ovpn profile with CRLF instead of LF. 
This looks like a parsing issue in the OpenVPN mobile client.

**Comment by spaceboy666** [comment]
This error is not caused by problem with configuration file, but in way how you transfer ovpn file into your device. For e.g sending file by email from cmd causes interpretaion of this file and causes mess. The best way to verify is to to open file on device in any text editor. If it is not readable, openvpn will be not able to read it as well and will report an error during a import.

**Comment by GeethRS** [comment]
Solution is simple.
Just copy vpn configuration file through USB cable and try to open.Its working.
I tried to send config file through Email & Whats-up & It did not work. finally I plugged my android tab to pc and copied the vpn file to tablet internal memory.It worked.

**Comment by JirkaZelenka** [comment]
I can confirm that also the transfer through Google drive was ok to open the file later in Android.
