### ISSUE TITLE
Third party client needed for PiVPN?

### ISSUE THREAD

**Issue by Laurence243** [pivpn/pivpn#285]
Not so much an issue but a question. I have been using OpenVPN Connect as my VPN client on my phone to connect to my PiVPN server.

My question is, do I need a third party client for that? Is it possible to connect through Android's [native VPN service](https://puu.sh/wubMz/46c0a370fc.png)? What about Windows 10 through the [Settings](https://puu.sh/wubzP/b2213df21a.png) menu?

**Comment by cfcolaco** [comment]
Yes, @Laurence243, you need the third party client since the VPN clients from Android and Windows does not (as far as I know) support connection to OpenVPN.

**Comment by cfcolaco** [comment]
@redfast00 can you close this pls?
