### ISSUE TITLE
Migrate existing openvpn server to PiVPN

### ISSUE THREAD

**Issue by Meisterschueler** [pivpn/pivpn#286]
What have I to do for migration of a existing OpenVPN server to PiVPN?

**Comment by cfcolaco** [comment]
hmmm ...the only reason I can see to do it is to use PiVPN client certificate management, other than that, don't see any real benefit! 
Do you have many clients? Is that imperative a "Migration"?!?! Is it so important that you have to go trough a trouble of a "hacky" "migration"? 

can't you just make a new one? assuming your existing OpenVPN server has the same settings that PiVPN uses.

**Comment by Meisterschueler** [comment]
Yes, I'd like to use the certificate management. I have about 35 clients. I try to make a new server with PiVPN and use the files of the old server...
