### ISSUE TITLE
How do I allow connecting through multiple host names?

### ISSUE THREAD

**Issue by uniquegodwin** [pivpn/pivpn#287]
Hi,
I would like to be able to connect using multiple alias hostnames. How do I allow connecting to the server through x.server.com, y. server.com for the same ovpn server?

Thanks

**Comment by darkrain-nl** [comment]
Hi, 

You can create a CNAME record in DNS for this.
x.server.com gets an A records pointing to your IP address, then y.server.com gets a CNAME record pointing to x.server.com.

**Comment by uniquegodwin** [comment]
Thanks for the quick reply.
I understand that I can create multiple records but will the openvpn server accept connections when i connect through y.servername.com when the name during the setup wizard is provided as x.servername.com?

Thanks.

**Comment by darkrain-nl** [comment]
Good question, I would think so.
But I'm not sure, maybe someone else knows this?

**Comment by cfcolaco** [comment]
what's the benefit of doing so? however, I don't see a reason why it wouldn't work!

Try it and then come back to us with results! ;)

**Comment by uniquegodwin** [comment]
It works even while using different names. There are different public ip's pointing to the same server. The outbound connections are load balanced . So, it's useful to use a different name when one ISP connecting to the server is down.

Thanks.

**Comment by cfcolaco** [comment]
Good to know @uniquegodwin 

If I understand it right everything is working and you no longer have this issue right? 

can you close it, please?

**Comment by uniquegodwin** [comment]
okay,sure ..so far,so good..Ill close it now. Thank you...
