### ISSUE TITLE
bash: line 366: ifconfig: command not found,  bash: line 367: ifconfig: command not found

### ISSUE THREAD

**Issue by mrfaptastic** [pivpn/pivpn#288]
# PiVPN Issue Template

## Console output of `curl install.pivpn.io | bash`
```
bash: line 366: ifconfig: command not found
bash: line 367: ifconfig: command not found

```

## Issue

In function setNetwork, I think you need to prefix 'ifconfig' with 'sudo'. For example"
`LOCALMASK=$(ifconfig "${pivpnInterface}" | awk '/Mask:/{ print $4;} ' | cut -c6-)`

... would become ..
`LOCALMASK=$(sudo ifconfig "${pivpnInterface}" | awk '/Mask:/{ print $4;} ' | cut -c6-)`

As for some Debian installations this utility is not available to standard users for security reasons.

```
setNetwork() {
    # Sets the Network IP and Mask correctly
    LOCALMASK=$(sudo ifconfig "${pivpnInterface}" | awk '/Mask:/{ print $4;} ' | cut -c6-)
    LOCALIP=$(sudo ifconfig "${pivpnInterface}" | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*')
    IFS=. read -r i1 i2 i3 i4 <<< "$LOCALIP"
    IFS=. read -r m1 m2 m3 m4 <<< "$LOCALMASK"
    LOCALNET=$(printf "%d.%d.%d.%d\n" "$((i1 & m1))" "$((i2 & m2))" "$((i3 & m3))" "$((i4 & m4))")
}
```

**Comment by azlux** [comment]
On recent Debian, ifconfig isn't installed by default, The script need to use "ip add"

**Comment by cfcolaco** [comment]
which distro are you getting this error? 
ifconfing is slowly getting deprecated and being replaced by ip command

@redfast00 consider marking this as bug or enhancement, please, as we will start to get more of this as new distros start being released.

**Comment by cfcolaco** [comment]
Been looking around and this issue is probably already solved in testing branch with commit https://github.com/pivpn/pivpn/commit/2eb11cad0ced98482eaeccc042aa8d5f291ffb57 by adding net-tools as a dependency. 

@0-kaladin @redfast00 this brings the question if should be a better approach to completely replace ifconfig with ip since all the pivpn supported distros have it by default ( I think ). 
of course it is easier in the coding side to just add a dependency to be installed ... but in the long run ...

**Comment by redfast00** [comment]
Will merge the testing branch in a couple of days (ping me if I forget). If you feel like going the `ip` route is easier/cleaner, feel free to create a PR and I'll merge it.

**Comment by cfcolaco** [comment]
@redfast00 for now having net-tools is the best way to go ... meanwhile, I will study about changing to IP and add it in my to do list ... don't think it should be a priority! =)

**Comment by 0-kaladin** [comment]
Thanks for holding down the fort guys. I'll be back soon...

**Comment by cfcolaco** [comment]
@redfast00 @0-kaladin 

with the current test branch, the bug part of this issue gets solved, however, will think of a way to replace ifconfig with ip (feature to add eventually after merging the current test branch)

**Comment by cfcolaco** [comment]
This Ticket does no longer concerns to a BUG, since #376 fixes this issue. 
Keeping ticket open as enhacement since should be a good option to replace ifconfig over ip suite.

**Comment by cfcolaco** [comment]
@redfast00 Merge Fixes this one as well! =)
