### ISSUE TITLE
Successful install of PiVPN, but failed service start on reboot (RP3b, Jessie Lite via Noobs)

### ISSUE THREAD

**Issue by Howjadoo** [pivpn/pivpn#289]
Hi all,

I am unable to start the OpenVPN service after install.  Looking for help reading the logs posted below.  I tried to find the answer to this issue before posting.  Many thanks to you in advance.

Raspberry Pi 3 b
Jessie Lite (installed via NOOBS over WAN)
16gb Sandisk (FAT32)
Logitech Unifying Receiver Keyboard

Immediately after the install, I ran the installation command (curl piped to bash) and successfully installed PiVPN.

After reboot, I noticed a service failure for OpenVPN:
[https://pastebin.com/bA74Qi0M](https://pastebin.com/bA74Qi0M)

Output of `systemctl status openvpn@server.service`
[https://pastebin.com/JPDkRt27](https://pastebin.com/JPDkRt27)

Output of command `pivpn debug`:
[https://pastebin.com/aCuK1TWK](https://pastebin.com/aCuK1TWK)

(note that I am using a registered domain and a CNAME to resolve requests to a dynDNS domain which keeps my IP updated... I can ping the domain to get the correct IP, and I can access lighttpd pages served from Pi to WAN via this domain, so I believe I've ruled out connectivity and port forwarding issues)

... which seems to indicate an issue with iptables setup/config.  When I click yes, the debug screen doesn't solve the issue:

```
::: Would you like us to try to fix this? [y/n]: y
modprobe: ERROR: ../libkmod/libkmod.c:557 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.50-v7+/modules.dep.bin'
iptables v1.4.21: can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
modprobe: ERROR: ../libkmod/libkmod.c:557 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.50-v7+/modules.dep.bin'
iptables v1.4.21: can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
::: Attempt at fix completed.
::: Run 'pivpn debug' again to see if we detect issues.
```

I suspected that apt-get update and apt-get upgrade might need to be run first.

So I uninstalled PiVPN with `pivpn -u` , ran `sudo apt-get update`, then `sudo apt-get upgrade`

Then re-installed PiVPN.  Same issue.

I can see iptables is installed
```
pi@shankvpn:/var/log $ sudo apt-get install iptables
Reading package lists... Done
Building dependency tree       
Reading state information... Done
iptables is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

Seems like a missing dependency.  Ever seen this?  Could it be a new issue due to a Jessie Lite update?

Would you recommend a different installation method for my debian distro?

**Comment by cfcolaco** [comment]
Ok, according to pivpn debug some wierd problem with your iptables. 

can you please post here the output of:

`iptables -t nat -S`

**Comment by Howjadoo** [comment]
Appreciate you getting back to me.

```
pi@shankvpn:~ $ iptables -t nat -S
modprobe: ERROR: ../libkmod/libkmod.c:557 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.50-v7+/modules.dep.bin'
iptables v1.4.21: can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
pi@shankvpn:~ $ sudo iptables -t nat -S
modprobe: ERROR: ../libkmod/libkmod.c:557 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.50-v7+/modules.dep.bin'
iptables v1.4.21: can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
```

Should I just restart installation from the beginning?  I wouldn't mind doing so if it helps us debug any potential issues with the PiVPN script.

But if there's an easy fix, I'd accept that, too.

**Comment by cfcolaco** [comment]
Hmm something wrong here! never seen such issue, there's a kernel module missing,
iptable_nat i belive.

have you been messing with Linux kernel? is this setup a clean setup? where did you get the raspbian image from? 

let's try to fix this without reinstalling, 

please provide me the output of: 

`lsmod | grep iptable`

**Comment by Howjadoo** [comment]
Have not messed with the Kernel, not intentionally.

The only other installs I've done are nginx and lighttpd, which I did after I couldn't get OpenVPN working.

```
pi@shankvpn:~ $ lsmod | grep iptable
pi@shankvpn:~ $ lsmod
Module                  Size  Used by
pi@shankvpn:~ $ sudo lsmod
Module                  Size  Used by
pi@shankvpn:~ $ 
```

I bought a new 16gb sandisk card, UHS-1, didn't format.

Downloaded Noobs network edition, and choose debian lite or jessie lite, whichever was shown on the screen... can't remember what it said.

Restarted, did some basic config in raspi-config, nothing earth-shattering.

Rebooted, tried PiVPN, rebooted, and got to this point.

**Comment by cfcolaco** [comment]
sorry, I tend to forget to use sudo since I have the (bad) habit of using root user directly, so always use sudo with commands I provide, I will try to not forget it =P 

lsmod should output a LOT MORE! your kernel might be cooked since it shows no modules at all. 
maybe because of the way you imaged your sd card since you mentioned you didn't format it ...I usually remove all the partitions and use the unpartitioned card. however, I do it with Linux and use dd for it, never used noobs or Etcher which is mentioned here: https://www.raspberrypi.org/documentation/installation/installing-images/README.md 

I think it would be a safe and easier bet to read again the raspbian installation guide and reinstall Raspbian Jessie Lite ( if you don't want Desktop environment ), and then come back and report us if everything wen't ok or not! ;)

**Comment by Howjadoo** [comment]
I will do this.  Thanks for your help!

**Comment by Howjadoo** [comment]
I am very happy to report no issues after reinstalling Jessie.

This time around, I downloaded the full version of NOOBS, not the smaller network-installed version.

I also chose Jessie instead of Jessie Lite.

OpenVPN started successfully after the PiVPN script and reboot completed.
