### ISSUE TITLE
connection drops after a minute or two

### ISSUE THREAD

**Issue by thayneq** [pivpn/pivpn#291]
Hi,

I have successfully installed pivpn onto a fresh install of Raspbian onto a RPi 3. I am able to connected with OpenVPN on my iPad. However after a minute or two of connectivity, it suddenly just stops. OpenVPN still reports as being "connected" and there is literally nothing that shows up in the OpenVPN log. It is 100% reproducible. If I force a disconnection in OpenVPN, I can immediately reconnect and it works great for another minute or two.

Any ideas what's going on?

**Comment by cfcolaco** [comment]
@thayneq I am not sure but I think I read somewhere that it is caused due to TLS versions ... 

Before we can try anything else, 

Can you try connecting to the VPN with another device? perhaps and Android phone, Windows or Linux computer?
