### ISSUE TITLE
Wiki FAQ Page: Add info on how to update OpenVPN 

### ISSUE THREAD

**Issue by cfcolaco** [pivpn/pivpn#293]
Could be useful adding to the wiki info on how to update OpenVPN to newer version, 
here's the md:

```
## Updating OpenVPN to newer version
If you installed an earlier version of pivpn and wish to update OpenVPN to a newer version ( > 2.4.3 ) just do the following stepes:

    ```
sudo -s
wget -O - https://swupdate.openvpn.net/repos/repo-public.gpg|apt-key add -
echo "deb http://build.openvpn.net/debian/openvpn/stable [osrelease] main" > /etc/apt/sources.list.d/openvpn-aptrepo.list
    ```
where [osrelease] should be replaced with:
**wheezy** (Debian 7.x)
**jessie** (Debian 8.x)
**precise** (Ubuntu 12.04)
**trusty** (Ubuntu 14.04)
**xenial** (Ubuntu 16.04)

More information can be found here: <https://community.openvpn.net/openvpn/wiki/OpenvpnSoftwareRepos>
```

# Here's how it should look like:

## Updating OpenVPN to newer version
If you installed an earlier version of pivpn and wish to update OpenVPN to a newer version ( > 2.4.3 ) just do the following stepes:

```
sudo -s
wget -O - https://swupdate.openvpn.net/repos/repo-public.gpg|apt-key add -
echo "deb http://build.openvpn.net/debian/openvpn/stable [osrelease] main" > /etc/apt/sources.list.d/openvpn-aptrepo.list
```
where [osrelease] should be replaced with:
**wheezy** (Debian 7.x)
**jessie** (Debian 8.x)
**precise** (Ubuntu 12.04)
**trusty** (Ubuntu 14.04)
**xenial** (Ubuntu 16.04)

More information can be found here: <https://community.openvpn.net/openvpn/wiki/OpenvpnSoftwareRepos>

Obs: Mind that backticks are escaped in md code so they can appear in code. 

@redfast00 @0-kaladin if you think it isn't usefull, well just close the issue =P 

thank you

**Comment by redfast00** [comment]
This looks good! Will put it in a wiki entry. @0-kaladin: I think cfcolaco should be given access to the repo: they have helped a lot of users and have submitted a PR.

**Comment by redfast00** [comment]
Done, thanks!
