### ISSUE TITLE
Cant install PIVPN

### ISSUE THREAD

**Issue by l0rdxy** [pivpn/pivpn#295]
pi@raspberrypi:~ $ curl -L https://install.pivpn.io | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:39 --:--:--     0curl: (6) Could not resolve host: install.pivpn.io

Why can i not resolve the hostname? i am able to browse the the install.sh site

**Comment by cfcolaco** [comment]
@l0rdxy , everything is ok with the host .. you must have some connection issues on your side. 

1 - can you `ping google.com` from your raspbery pi? 
2 - can you `ping 8.8.8.8` form your raspberry pi?
3 - can you `ping <your raspberrypi> ` from another device? 
4 - what is the output of `ifconfig`?
5 - what is the output from `ip route`?
6 - what is the output of `cat /etc/resolv.conf`?


thank you

**Comment by l0rdxy** [comment]
i am able to ping all address'

wlan0     Link encap:Ethernet  HWaddr b8:27:eb:ab:19:e1
          inet addr:192.168.1.4  Bcast:192.168.1.255  Mask:255.255.255.0
          inet6 addr: fe80::d59e:cb09:828d:65e7/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:1466 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1165 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:185204 (180.8 KiB)  TX bytes:125025 (122.0 KiB)

pi@raspberrypi:~ $ ip route
default via 192.168.1.254 dev wlan0  metric 302
192.168.1.0/24 dev wlan0  proto kernel  scope link  src 192.168.1.4  metric
302
pi@raspberrypi:~ $

cat /etc/resolv.conf
# Generated by resolvconf
nameserver 8.8.8.8
nameserver 8.8.4.4

**Comment by cfcolaco** [comment]
is there a chance that you have mistyped the url?

try it again and double check if you are typing the url correclty, if it fails try this:

`curl -L https://raw.githubusercontent.com/pivpn/pivpn/master/auto_install/install.sh | bash`

**Comment by l0rdxy** [comment]
Even if I copy and paste that URL, I get the same error

**Comment by cfcolaco** [comment]
@l0rdxy that definitely shouldn't happen. but the issue isn't in PiVPN side ... 

if you want me to help you figure out where the problem is, please provide me the output of:

`sudo iptables -S`

Otherwise if you want to just make this work and workaround, do the following:

```bash
cd
sudo apt-get install -y git
git clone https://github.com/pivpn/pivpn.git
sudo ./pivpn/auto_install/install.sh
```

**Comment by l0rdxy** [comment]
Here is the output. i am running the workaround as well but there are
errors there too (see below) very strange because everything else works and
i can resolve and browse other sites

pi@raspberrypi:~ $ sudo iptables -S
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT

After this operation, 21.0 MB of additional disk space will be used.
Err http://mirrordirector.raspbian.org/raspbian/ jessie/main liberror-perl
all 0.17-1.1
  Could not resolve 'mirrordirector.raspbian.org'
Err http://mirrordirector.raspbian.org/raspbian/ jessie/main git-man all
1:2.1.4-2.1+deb8u3
  Could not resolve 'mirrordirector.raspbian.org'
Err http://mirrordirector.raspbian.org/raspbian/ jessie/main git armhf
1:2.1.4-2.1+deb8u3
  Could not resolve 'mirrordirector.raspbian.org'
Err http://mirrordirector.raspbian.org/raspbian/ jessie/main rsync armhf
3.1.1-3
  Could not resolve 'mirrordirector.raspbian.org'
E: Failed to fetch
http://mirrordirector.raspbian.org/raspbian/pool/main/libe/liberror-perl/liberror-perl_0.17-1.1_all.deb
 Could not resolve 'mirrordirector.raspbian.org'

E: Failed to fetch
http://mirrordirector.raspbian.org/raspbian/pool/main/g/git/git-man_2.1.4-2.1+deb8u3_all.deb
 Could not resolve 'mirrordirector.raspbian.org'

E: Failed to fetch
http://mirrordirector.raspbian.org/raspbian/pool/main/g/git/git_2.1.4-2.1+deb8u3_armhf.deb
 Could not resolve 'mirrordirector.raspbian.org'

E: Failed to fetch
http://mirrordirector.raspbian.org/raspbian/pool/main/r/rsync/rsync_3.1.1-3_armhf.deb
 Could not resolve 'mirrordirector.raspbian.org'

E: Unable to fetch some archives, maybe run apt-get update or try with
--fix-missing?

**Comment by l0rdxy** [comment]
Pinging mirrordirector.raspian.org [69.162.80.60] with 32 bytes of data:
Request timed out.
Reply from 69.162.80.60: bytes=32 time=277ms TTL=37
Reply from 69.162.80.60: bytes=32 time=277ms TTL=37
Reply from 69.162.80.60: bytes=32 time=278ms TTL=37

but apt-get cant resolve.. very strange

**Comment by cfcolaco** [comment]
:O 
You can ping everything from the pi, but you can't reach them by any other means? 
are you connected through wifi correct? how far are you from the router? 

Can you try with an Ethernet cable? 

I have seen similar behavior in networking environments and they were mostly caused by bad Ethernet cables/wifi dongles or poor wifi signal.

**Comment by l0rdxy** [comment]
Thank you for all you help. I have managed to resolve the issue

I reload the device, I think with all the config I had added and removed
and changed, the OS just needed a refresh

All working now
