### ISSUE TITLE
Notify LED [question]

### ISSUE THREAD

**Issue by nonflammable** [pivpn/pivpn#296]
is possible to add notification LED when VPN connection is established with client ?

**Comment by cfcolaco** [comment]
sorry but just can't understand the relation between " **benefit/usefulness vs trouble to code it** " 

pivpn already offers you a script that gives you a list of connected clients which I believe to be way more useful than having a LED ( that needs to be connected trough the Pi GPIO Pinout ) that simply lights when there's a connection to the VPN ...

**Comment by cfcolaco** [comment]
Btw, Don't get me wrong, this is just my opinion. 
don't want you to think that I am being rude or something ;)

**Comment by nonflammable** [comment]
Nevermind. OpenVPN has a "client-connect script" option.
