### ISSUE TITLE
LAN routing

### ISSUE THREAD

**Issue by VinSz2** [pivpn/pivpn#298]
Hello boys and girls,

love the easy setup and everything works fine using armbian, pine64 and openvpn client for android. 

But i noticed i cannot access my lan, so i checked if ip forwarding is set up which it is, but still no access, also it seemed to be configured by pivpn as far as i can tell, ip adresses are 192.168.2.0/24.

Add route to Client routing table for the OpenVPN Server
push "route 10.8.0.1 255.255.255.255"
Add route to Client routing table for the OPenVPN Subnet
push "route 10.8.0.0 255.255.255.0"
your local subnet
push "route 192.168.2.0 255.255.255.0"

thank you in advance

regards

Vin

**Comment by cfcolaco** [comment]
are you trying to reach other devices in lan through their IP or Hostnames? 

when connected to openvpn you can't reach other hosts in the network through their hostnames.

**Comment by VinSz2** [comment]
thank you for your fast and helping reply.

seemed that it also has been a problem of my android app "fx" after i reinstalled it, it worked with the ip addresses, and after i changed the dns to in the config to my routers ip, also the hostnames work just fine now

but i seem to encounter another problem, some android apps dont seem to work anymore, tumblr for example, it cannot connect anymore

**Comment by cfcolaco** [comment]
@VinSz2 Great to know that way it worked fine! :D 

Regarding Tumblr not working that might not be related with OpenVPN, did tumbler worked before you change the DNS to your router? ...

**Comment by VinSz2** [comment]
havent had anything to do with pivpn, once again a problem with the custom firmware of my android phone. 

but thank you very much for the support :)

**Comment by cfcolaco** [comment]
No worries @VinSz2 ! ;) glad everything is working now. 

If you don't have anything else you'd like to discuss please close this issue. 

Thank you
