### ISSUE TITLE
How to update version on pi via your script once installed

### ISSUE THREAD

**Issue by maxm2125** [pivpn/pivpn#30]
How does one update from version 1.3 to version 1.4 with all the changes you made once you have run the install script to install pivpn on your pi? Great work.

**Comment by 0-kaladin** [comment]
I have no updater.  really if you installed then openvpn is doing its job.  Generally the updates improve the installer which you've already completed.  But for now its pivpn uninstall then reinstall.  I do it mult times/day so its not too bad.  only issue would be redistributing the ovpn's if you have a lot.

**Comment by 0-kaladin** [comment]
I keep trying to think of a clever way to make some sort of updates work.  But it all depends on what i'm updating and if i am updating anything that makes a change to the server or client conf you will more than likely need new OVPN's anyway.  And if i provide an update command like pivpn update that just updates the scripts then i don't know how to segment it to not do any conf changes that would break stuff...

**Comment by maxm2125** [comment]
I understand.  Great job on creating the pivpn scripts.  Heard about your script from Security Now/TWiT.  I have it up and running and it works great.
