### ISSUE TITLE
Site Unavailable

### ISSUE THREAD

**Issue by Geffers** [pivpn/pivpn#300]
# PiVPN Issue Template

## Console output of `curl install.pivpn.io | bash`
```

```

## Console output of `pivpn add` or `pivpn add nopass`
```

```

## Console output of `pivpn debug`
```

```

## Issue

Folks,

I've installed PiVPN successfully, I've created .ovpn files for an Android phone and netpad. Both work fine.

Having problems with a Linux Ubuntu laptop, shows as successfully connecting but web browser says 'Site Unavailable' and I've tried a few different sites. As soon as I disconnect from VPN the web sites then appear on the browser.

 A previouspublic OpenVPN I used had the following in the .ovpn file;

# uncomment the following lines on Linux
up /etc/openvpn/update-resolv-conf
down /etc/openvpn/update-resolv-conf

Tried this and got 'Fatal error, exiting' and pivpn -c shows same machine with two connections and consecutive IP addresses.

Looked at log file but no obvious inspiration from that.

Any pointers appreciated.

Geffers

**Comment by cfcolaco** [comment]
How are you connecting to OpenVPN in your ubuntu machine? 

via Gnome NetworkManager openvpn? or cli?

**Comment by Geffers** [comment]
Resolved, needed to put the following in the client .ovpn file.

script-security 2
up /etc/openvpn/update-resolv-conf
down /etc/openvpn/update-resolv-conf

Without script-security 2 I get the fatal error.

Connecting on Ubuntu 16:04 using a terminal with sudo openvpn --config "name of file"

Geffers
