### ISSUE TITLE
Dynamic IP

### ISSUE THREAD

**Issue by Geffers** [pivpn/pivpn#301]
# PiVPN Issue Template

## Console output of `curl install.pivpn.io | bash`
```

```

## Console output of `pivpn add` or `pivpn add nopass`
```

```

## Console output of `pivpn debug`
```

```

## Issue

Folks,

Successfully installed PiVPN on a Raspberry Pi.

Created 3 .ovpn files with two of which are working fine.

Looking in to why the third one don't work I notice the .ovpn file shows the 'remote' as an IP address.

As my ISP issues dynamic addresses this of course could change; am I able to just change the .ovpn file to show my dtdns.net address?

Geffers

**Comment by cfcolaco** [comment]
It is covered in PiVPN wiki! =) 

https://github.com/pivpn/pivpn/wiki/FAQ

**Comment by Kavaho** [comment]
I used the first part of this forum post https://www.raspberrypi.org/forums/viewtopic.php?f=36&t=21566 

It helps you set up a program that checks if your public IP has changed and updates the public IP address on your no-ip account every 30 minutes. Hope it helps, good luck :D

**Comment by cfcolaco** [comment]
@redfast00 think this issue can be closed ...
