### ISSUE TITLE
Accessing the OVPN Admin Web UI 

### ISSUE THREAD

**Issue by timdonovanuk** [pivpn/pivpn#302]
Should the OpenVPN Admin Web UI be accessible (i.e. at https://ip:943/admin) after installing pivpn? Because it doesn't appear to be. It would be really nice to be able to easily download the .ovpn files to clients by just using a browser.

Thanks.

**Comment by timdonovanuk** [comment]
Never mind, realise you need the paid version of OVPN to get the web console! doh :)

**Comment by anudeepND** [comment]
Try <a href="https://play.google.com/store/apps/details?id=com.cea.raspmanager&hl=en&referrer=utm_source%3Dgoogle%26utm_medium%3Dorganic%26utm_term%3Draspmanager&pcampaignid=APPU_1_t79bWbavH8XcvATEvLeIBA">this</a> Android app! Very helpful when running pi headless...
