### ISSUE TITLE
Certificate Files for Wireless Router

### ISSUE THREAD

**Issue by ntsomer** [pivpn/pivpn#305]
I am trying to connect a Netcomm NTC-140W router as a client.   It requires a certificate as follows

 _There are three files that the OpenVPN client in a NetComm Wireless router will
expect to see within a .tgz file:
The master Certificate Authority (CA) certificate file named ca.crt
Client certificate file (e.g., OpenVPN Test Client.crt)
Client key file (e.g., OpenVPN Test Client.key)_

Is it possible to generate these from pivpn

**Comment by cfcolaco** [comment]
You have them all inside ovpn file generated by pivpn. Just copy them for a text file and give it the respective name.extension and it should work

**Comment by stphn404** [comment]
Hi, what I´ve to do?
I copy the ovpn file and then i change the name and the extension?

**Comment by cfcolaco** [comment]
@ntsomer long time since you opened this .. closing ... if you still need help please reach out.
