### ISSUE TITLE
Preventing Local Access

### ISSUE THREAD

**Issue by Geffers** [pivpn/pivpn#307]
# PiVPN Issue Template

## Console output of `curl install.pivpn.io | bash`
```

```

## Console output of `pivpn add` or `pivpn add nopass`
```

```

## Console output of `pivpn debug`
```

```

## Issue

Folks,

I've got pivpn running successfully but would like to prevent connecting machines to have access to the pivpn's network and merely forward for secure internet access.

Am I correct in assuming /etc/openvpn/server.conf is the main config file and HASHING the following should work;

**
'hash' your local subnet
push "route 10.0.0.0 255.0.0.0"
**

My local network is 10.19.44.0/255.255.255.0

Reason I ask is that it doesn't appear to have worked - a connecting machine was still able to access a web server on the local network.

Geffers

**Comment by Geffers** [comment]
Format displays weirdly when I view preview, hoe you can understand message OK

As you can see I hashed the local subnet HASHED on 10/07/2017

server.conf as follows;

`dev tun
proto udp
port 1194
ca /etc/openvpn/easy-rsa/pki/ca.crt
cert /etc/openvpn/easy-rsa/pki/issued/server.crt
key /etc/openvpn/easy-rsa/pki/private/server.key
dh /etc/openvpn/easy-rsa/pki/dh2048.pem
topology subnet
server 10.8.0.0 255.255.255.0
# server and remote endpoints
ifconfig 10.8.0.1 10.8.0.2
# Add route to Client routing table for the OpenVPN Server
push "route 10.8.0.1 255.255.255.255"
# Add route to Client routing table for the OPenVPN Subnet
push "route 10.8.0.0 255.255.255.0"
# your local subnet HASHED on 10/07/2017
# push "route 10.0.0.0 255.0.0.0"
# Set your primary domain name server address for clients
push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 8.8.4.4"
# Override the Client default gateway by using 0.0.0.0/1 and
# 128.0.0.0/1 rather than 0.0.0.0/0. This has the benefit of
# overriding but not wiping out the original default gateway.
push "redirect-gateway def1"
client-to-client
duplicate-cn
keepalive 10 120
tls-version-min 1.2
tls-auth /etc/openvpn/easy-rsa/pki/ta.key 0
cipher AES-256-CBC
auth SHA256
comp-lzo
user nobody
group nogroup
persist-key
persist-tun
#crl-verify /etc/openvpn/crl.pem
status /var/log/openvpn-status.log 20
status-version 3
log /var/log/openvpn.log
verb 1
# Generated for use by PiVPN.io`

Geffers

**Comment by cfcolaco** [comment]
Have you restarted OpenVPN after hashing the  `push "route 10.0.0.0 255.0.0.0"`?

`sudo systemctl restart openvpn`

**Comment by Geffers** [comment]
Is 
```sudo service openvpn stop ```

followed by 
```sudo service openvpn start``` 

the same as
 ``` sudo systemctl restart openvpn``` ?

Geffers

**Comment by redfast00** [comment]
Yup, it is.

**Comment by Geffers** [comment]
Query #319 wasn't actually a duplicate - on this thread I was asking about preventing clients from having access to the server's network but my latest post queried the 'user rights' of a client.

Was under the impression that the client connected as user 'nobody' so had limited access but I may well be understanding this wrongly.

I thought I read that if an unauthorised user got hold of a client's credentials and got unauthorised access that their ability to do damage to server's system was limited.

Geffers

**Comment by cfcolaco** [comment]
@Geffers Please elaborate!! 

you managed to prevent clients to get access to the network correct?

so what is exactly your concern with issue #319 and with your reply?

right now for me, @redfast00 did well closing!

**Comment by Geffers** [comment]
@cfcolaco  I don't think I gave the impression in previous posts that I managed to prevent access to local network, hashing out the lines for local network in the server config file did not appear to work.

I have however solved the issue, I added the following to iptables;

`iptables -A FORWARD -s 10.8.0.0/24 -d (my network address) -j DROP`

This has worked for me.

Geffers

**Comment by Geffers** [comment]
@cfcolaco  I don't think I gave the impression in previous posts that I managed to prevent access to local network, hashing out the lines for local network in the server config file did not appear to work.

I have however solved the issue, I added the following iptables rule;

`iptables -A FORWARD -s 10.8.0.0/24 -d (my network address) -j DROP`

That has worked for me.

Geffers
