### ISSUE TITLE
How to change from initially configured wifi to wired

### ISSUE THREAD

**Issue by paulzak** [pivpn/pivpn#31]
I initially set up my Pi3 on a WiFi network. Now I'd like to run it on my wired network. Are there modifications I must make to the pivpn config or is this exclusively a RP config issue? When I attempt to use the wire, I seem to get a connection, but there is no throughput.

If I'm not mistaken your documentation talks about 2 channels. Perhaps one is working and the other stumbles when I switch??

Unbelievably easy initial setup. Thanks for creating this!

Paul

**Comment by 0-kaladin** [comment]
if your wifi had a static IP and you gave eth0 the same static i don't think you have to change anything. just reboot.  if you gave it a different static, we might need to talk more.

**Comment by paulzak** [comment]
I haven't assigned a static IP at all to either. All I did was set up wifi and go. I did assign a static IP in my router however so port forwarding would go somewhere consistent. My next step is to give the pi a static IP and see how it goes. Sounds like the static IP is critical.
These are the hazards of targeting the unschooled masses. 
Not sure I can dig into this till mid-week, but I'll let you know what happens.


Paul

 
 
  On Thu, May 12, 2016 at 5:59 PM, 0-kaladin<notifications@github.com> wrote:   
if your wifi had a static IP and you gave eth0 the same static i don't think you have to change anything. just reboot. if you gave it a different static, we might need to talk more.

**Comment by 0-kaladin** [comment]
you don't *need* a static just really preferred.  you can assign it a dhcp reservation in your router and this way you can leave the pi doing dhcp but it'll never change.
but regarding this issue at hand run
`ifconfig`
and look at your eth0 inet addr.
then go into the server.conf file in /etc/openvpn and you'll see a line like

> # your local subnet
> push "route 192.168.x.x 255.255.255.0"

change that IP to your inet addr.  it really just needs your subnet but can be your addr too won't matter.

finally check iptables is good
`iptables -t nat -L`

**Comment by 0-kaladin** [comment]
actually maybe just running this if your wired is eth0 will fix it for you.
`sudo iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE`

**Comment by paulzak** [comment]
As of yesterday, it looked like it was working on the wired connection without my doing anything other than looking at the places you suggested.  I wanted to play with it a little more before declaring victory. 

Sent from Yahoo Mail on Android 
 
  On Sun, May 15, 2016 at 8:11 AM, 0-kaladin<notifications@github.com> wrote:   
actually maybe just running this if your wired is eth0 will fix it for you.
sudo iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE

**Comment by 0-kaladin** [comment]
@paulzak everything working?

**Comment by paulzak** [comment]
Yes. I played with it a bit and it's working now. It's a bit over my head and it worked inconsistently but it's up right now.
I did 2 things which I'm fairly sure had no impact, but seemed right anyway.
1) I was getting an error in the OpenVPN log that complained about my subnet being non-canonical so I changed the IP in the push statement in /etc/OpenVPN server.conf to 10.253.80.0 255.255.255.0 which eliminated the log entry, but really didn't seem to correct the problem.
2) Then, I wondered if the DHCP reservation needed to specify the MAC address of the eth0 interface. It was set to the wlan so I corrected that too.
After that, it was still inconsistently working. Just to be clear, in case you hear this from another user, it always works on wlan. When you plug in eth and reboot, the pi comes back after the boot and is managable. The VPN will connect, but no data will pass through the interface. Then, for whatever reason, if you keep trying to reboot, it will eventually connect and work.
I'm OK if you close the issue and I'll follow github to see if this comes back, but I hate to bug you anymore on this. Let me know if you still want me to try something. I did not alter the routing as you suggested in your last note.
Thanks again for all your help.

Paul 

 
 
  On Fri, May 20, 2016 at 5:15 AM, 0-kaladin<notifications@github.com> wrote:   
@paulzak everything working?

**Comment by 0-kaladin** [comment]
Could make this an enhancement to support changing interface.  Not sure it adds a ton of value, I don't imagine most need to change their interface, but will mark as such...

**Comment by redfast00** [comment]
@0-kaladin: wouldn't it be easier to tell users to reinstall?

**Comment by salihys** [comment]
I had the same issue and ran the two commands suggested above and it worked.

> actually maybe just running this if your wired is eth0 will fix it for you.
sudo iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE
sudo netfilter-persistent save
