### ISSUE TITLE
PiVPN Docker Container

### ISSUE THREAD

**Issue by InnovativeInventor** [pivpn/pivpn#310]
Hello everyone! I've created a docker container for PiVPN and was wondering how to get the word out to you guys. It uses a script to pass random data to the docker container (to make sure it has enough entropy) and sets everything up for you except for the VPN configuration process. I'm not sure how to add/combine the container with this project, but here is the link: [https://github.com/InnovativeInventor/docker-pivpn](https://github.com/InnovativeInventor/docker-pivpn
)

I chose to make a docker container with PiVPN because I liked the prompts that made it easy for non-programmers to configure OpenVPN. 

PS: I hope I don't get killed for sharing this via an issue because I wasn't sure where/how to share this info with you guys.

**Comment by redfast00** [comment]
This looks pretty cool! 🎉  Is it easy for users to set up? One thing I don't really understand is [this line in random.sh](https://github.com/InnovativeInventor/docker-pivpn/blob/master/assets/random.sh#L2): this outputs `Making sudo, please ensure that you have verified this script's checksum`. This doesn't make a lot of sense: if a user reads this, the script is already running. There is also no message about what to verify the checksum against and even if the script got modified by a malicious user, the malicious user could just remove the message.

Where exactly do you see this project going? Do you want to have a pivpn-docker repo in the main PiVPN GitHub organisation?

**Comment by InnovativeInventor** [comment]
I meant to get rid of that line but never got around to doing it. I think that it would be good for other PiVPN people to see the docker version as an option for PiVPN users. Maybe we could include a link to docker-pivpn or have a fork of it in PiVPN's github. I'm open to ideas/suggestions!

**Comment by markserrano915** [comment]
@InnovativeInventor This is cool. I like it. You should publish it to Docker Hub. I can tell you put a lot of work on it after reading the shell script files. 

I'll test it when I have time this week. I just got my pivpn setup last night (it was painful working with the iptables).

@redfast00 I think a link or a mention in the README.md file is enough? Or maybe that's not needed. People can Google and should find this post. If it's published in Docker Hub, then that will return in the search results

**Comment by redfast00** [comment]
@InnovativeInventor : if you want a link in the README.md, create a PR and I'll merge it. :+1:

**Comment by marcelstoer** [comment]
This would be sooo valueable to have but unfortunately that image seems unmaintained. I am not sure if one can still recommend using it.

**Comment by 4s3ti** [comment]
@marcelstoer definitely not! will remove it from README as soon as possible...

**Comment by Cjkeenan** [comment]
Are there any maintained Docker containers for PiVPN currently? I have been thinking about switching over all of my RPi servers to docker.

**Comment by 4s3ti** [comment]
@Cjkeenan at least not officially by us ... however its on my plans to add it ... just can't give you an ETA for it.
