### ISSUE TITLE
iptables-persistent & netfilter-persistent

### ISSUE THREAD

**Issue by ifaist0s** [pivpn/pivpn#311]
Hello all!

Thank you for this nice piece of software! :)
I'm facing an issue and decided to post it here because it's heavily related to [this issue.](https://github.com/pivpn/pivpn/issues/231) In fact it's the same issue, but the solution to that issue does not apply in my case :(

**Specifics**:
<pre>RaspberryPi 3 Model B
Linux raspbx 4.9.36-v7+ #1015 SMP Thu Jul 6 16:14:20 BST 2017 armv7l GNU/Linux</pre>

**Issue**
When doing `apt-get upgrade` I get the following error:
<pre>Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
2 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Setting up netfilter-persistent (1.0.3+deb8u1) ...
update-rc.d: warning: start and stop actions are no longer supported; falling back to defaults
A dependency job for netfilter-persistent.service failed. See 'journalctl -xn' for details.
invoke-rc.d: initscript netfilter-persistent, action "start" failed.
dpkg: error processing package netfilter-persistent (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of iptables-persistent:
 iptables-persistent depends on netfilter-persistent (= 1.0.3+deb8u1); however:
  Package netfilter-persistent is not configured yet.

dpkg: error processing package iptables-persistent (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 netfilter-persistent
 iptables-persistent
E: Sub-process /usr/bin/dpkg returned an error code (1)</pre>

Any ideas?

## Console output of `pivpn debug`
<pre>:::                                     :::
::              PiVPN Debug              ::
:::                                     :::
::      Latest Commit                    ::
:::                                     :::
commit 3c764db9b6d670c8bf9eae3ad94f1dbd570043c7
Merge: 6ce39bf fbec57d
Author: redfast00 <redfast00@users.noreply.github.com>
Date:   Thu Jun 29 13:32:14 2017 +0200

    Merge pull request #292 from cfcolaco/master

    changed to new openvpn repos
:::                                     :::
::      Recursive list of files in       ::
::      /etc/openvpn/easy-rsa/pki        ::
:::                                     :::
/etc/openvpn/easy-rsa/pki/:
Default.txt
user.ovpn
ca.crt
dh2048.pem
index.txt
index.txt.attr
index.txt.attr.old
index.txt.old
issued
private
serial
serial.old
ta.key

/etc/openvpn/easy-rsa/pki/issued:
user.crt
server.crt

/etc/openvpn/easy-rsa/pki/private:
user.key
ca.key
server.key
:::                                     :::
::      Output of /etc/pivpn/*           ::
:::                                     :::
:: START /etc/pivpn/DET_PLATFORM ::
Raspbian
:: END /etc/pivpn/DET_PLATFORM ::
:: START /etc/pivpn/INSTALL_PORT ::
1194
:: END /etc/pivpn/INSTALL_PORT ::
:: START /etc/pivpn/INSTALL_PROTO ::
udp
:: END /etc/pivpn/INSTALL_PROTO ::
:: START /etc/pivpn/INSTALL_USER ::
pivpn
:: END /etc/pivpn/INSTALL_USER ::
:: START /etc/pivpn/NO_UFW ::
1
:: END /etc/pivpn/NO_UFW ::
:: START /etc/pivpn/REVOKE_STATUS ::
0
:: END /etc/pivpn/REVOKE_STATUS ::
:: START /etc/pivpn/pivpnINTERFACE ::
eth0
:: END /etc/pivpn/pivpnINTERFACE ::
:::                                     :::
:: /etc/openvpn/easy-rsa/pki/Default.txt ::
:::                                     :::
client
dev tun
proto udp
remote 1.2.3.4 1194
resolv-retry infinite
nobind
persist-key
persist-tun
key-direction 1
remote-cert-tls server
tls-version-min 1.2
verify-x509-name server name
cipher AES-256-CBC
auth SHA256
comp-lzo
verb 1
:::                                     :::
::      Debug Output Complete            ::
:::                                     :::
</pre>

## Console output of `journalctl -x`
<pre>
Jul 21 10:11:34 raspbx systemd[1]: Reloading.
Jul 21 10:11:34 raspbx systemd[1]: Reloading.
Jul 21 10:11:34 raspbx systemd[1]: Starting Load Kernel Modules...
-- Subject: Unit systemd-modules-load.service has begun with start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit systemd-modules-load.service has begun starting up.
Jul 21 10:11:34 raspbx systemd-modules-load[8310]: Failed to find module 'bcm2708_wdog'
Jul 21 10:11:34 raspbx systemd-modules-load[8310]: Failed to find module 'bcm2708-rng'
Jul 21 10:11:34 raspbx systemd[1]: systemd-modules-load.service: main process exited, code=exited, status=1/FAILURE
Jul 21 10:11:34 raspbx systemd[1]: Failed to start Load Kernel Modules.
-- Subject: Unit systemd-modules-load.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit systemd-modules-load.service has failed.
--
-- The result is failed.
Jul 21 10:11:34 raspbx systemd[1]: Dependency failed for netfilter persistent configuration.
-- Subject: Unit netfilter-persistent.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit netfilter-persistent.service has failed.
--
-- The result is dependency.
Jul 21 10:11:34 raspbx systemd[1]: Unit systemd-modules-load.service entered failed state.
</pre>

**Comment by ifaist0s** [comment]
It seems that the problem was related to the modules `bcm2708_wdog` and `bcm2708-rng` found in `/etc/modules-load.d/modules.conf`. I hashed those modules and the problem went away. The solution was found in [here](https://discourse.osmc.tv/t/failed-to-start-load-kernel-modules/3163/14).

**Comment by biddster** [comment]
Apols for commenting on a closed bug, but I had this issue and it's because I'd disabled ipv6. 

This was causing `/usr/share/netfilter-persistent/plugins.d/25-ip6tables start` to fail. A quick look at that script and it seems it can be disabled by moving the following file `/etc/iptables/rules.v6` out of the way. 

E.g. `sudo mv /etc/iptables/rules.v6 /etc/iptables/rules.v6.old`

Then your `dist-upgrade` should work.

**Comment by asderferjerkel** [comment]
Sorry for the necro, I came across this whilst upgrading raspbian from stretch to buster. In my case some steps happened in the wrong order, removing modules from the currently-running kernel and causing the error `iptables/1.8.2 Failed to initialize nft: Protocol not supported`. A simple reboot to switch to the new kernel followed by `sudo dpkg --configure -a` to finish setting up iptables-persistent and nftables-persistent solved it. Hope this helps someone out.
