### ISSUE TITLE
Disable Firewall

### ISSUE THREAD

**Issue by joejoe2017** [pivpn/pivpn#314]
Hello, 

The VPN is working very well with me, but I am trying to run a SQL database between the computers connected to the VPN, I can see all the computers on the LAN but the database does not want to connect to the SQL server.
Is there is anyway I can disable the Firewall in the VPN?

**Comment by cfcolaco** [comment]
@joejoe2017 you can't disable the firewall in the VPN server because you need it at least to forward the packets from the tunnel to the network itself. 

So can you please elaborate more so I can perhaps help you with that?

**Comment by joejoe2017** [comment]
I am trying to share a sql database on my computer to the computers connected to the VPN outside home.
one of the possibilities the sharing is failing is the firewall.

**Comment by cfcolaco** [comment]
So let me see if I understood, 

you have the VPN server 

and a bunch of clients connected, and it happens that one of the clients is actually also a SQL server right?

**Comment by joejoe2017** [comment]
You are correct, but dont worry about I figure it out, it works perfectly after I put the server local network as 10.8.1.x while the vpn is 10.8.0.x

Thank you for the follow up

**Comment by cfcolaco** [comment]
Closing ...
