### ISSUE TITLE
iPhone 6+ Certificate Install

### ISSUE THREAD

**Issue by iWoodzy** [pivpn/pivpn#317]
# PiVPN Issue Template

## Console output of `curl install.pivpn.io | bash`
```

```

## Console output of `pivpn add` or `pivpn add nopass`
```

```

## Console output of `pivpn debug`
```

```

## Issue

How do you install the Certificate on an iPhone or enter the server settings?

**Comment by InnovativeInventor** [comment]
You don't need to. Just download the [OpenVPN Connect](https://itunes.apple.com/us/app/openvpn-connect/id590379981?mt=8) app on your iOS device and import the .ovpn file You can do this via iTunes or email.

**Comment by cfcolaco** [comment]
@iWoodzy if @InnovativeInventor solution has helped you, please close the ticket.

**Comment by cfcolaco** [comment]
closing...
