### ISSUE TITLE
Improper prompt during pivpn uninstall

### ISSUE THREAD

**Issue by arikalfus** [pivpn/pivpn#318]
Caught this gem during an uninstall of pivpn:
```
::: Do you wish to remove git from your system? [y/n]: y
::: You must answer yes or no!
::: Do you wish to remove git from your system? [y/n]: yes
```

The rest of the uninstallation prompts use `y/n` as expected, but the git uninstallation prompt expects the words `yes` or `no`.

Not sure why this behavior is happening - unless I'm misreading the code, there should be no difference between `git` and the other dependencies.
From `scripts/uninstall.sh`, beginning on line 55:
```
dependencies=( openvpn easy-rsa git iptables-persistent dnsutils expect unattended-upgrades )
    for i in "${dependencies[@]}"; do
        if [ "$(dpkg-query -W --showformat='${Status}\n' "$i" 2> /dev/null | grep -c "ok installed")" -eq 1 ]; then
            while true; do
                read -rp "::: Do you wish to remove $i from your system? [y/n]: " yn
                case $yn in
                    [Yy]* ) printf ":::\tRemoving %s..." "$i"; $SUDO apt-get -y remove --purge "$i" &> /dev/null & spinner $!; printf "done!\n";
                            if [ "$i" == "openvpn" ]; then UINST_OVPN=1 ; fi
                            if [ "$i" == "unattended-upgrades" ]; then UINST_UNATTUPG=1 ; fi
                            break;;
                    [Nn]* ) printf ":::\tSkipping %s\n" "$i"; break;;
                    * ) printf "::: You must answer yes or no!\n";;
                esac
            done
        else
            printf ":::\tPackage %s not installed... Not removing.\n" "$i"
        fi
    done
```

Yet, `git` asked for the whole word while the rest of the dependencies were satisfied with `y`.

**Comment by arikalfus** [comment]
(and no worries - reinstalling! Not removing permanently :D)

**Comment by redfast00** [comment]
That is really strange. Can you reproduce this issue or was it a one-time thing?

**Comment by cfcolaco** [comment]
@redfast00 will test this tomorrow on a debian VM, will come back with more details.

**Comment by arikalfus** [comment]
This occurred on a Raspberry Pi in Raspbian, but I do not want to deal with rebuilding my VPN server again. I used an Ubuntu MATE VM in Virtualbox to test, and I could not reproduce. I will close.
