### ISSUE TITLE
Verticle bar "|" on keyboard does not work when installing pivpn to Raspbian.

### ISSUE THREAD

**Issue by PiNoobie** [pivpn/pivpn#32]
at the pivpn.io website to install the pivpn after installing Raspbian Jessie Lite you would enter the command line:

curl -L https://install.pivpn.io | bash

When i try to type in the command line at the vertical line "|" (using the keyboard attached to the Raspberry Pi) i get the "~" symbol.  Using the same keyboard at a windows computer I get the "|" symbol no problem.

Whats up with that?  Is there an alternative way to get the "|" vertical line symbol before the "bash"?

TIA

**Comment by 0-kaladin** [comment]
Not a pivpn question but a raspberry pi one.  Regardless you need to change the keyboard layout to US, it comes as UK for whatever reason.
https://thepihut.com/blogs/raspberry-pi-tutorials/25556740-changing-the-raspberry-pi-keyboard-layout
