### ISSUE TITLE
Disconnecting Clients

### ISSUE THREAD

**Issue by Geffers** [pivpn/pivpn#320]
Folks,

Is there any way of disconnecting a specific client from the pivpn's server?

Experimenting with a setup a friend was under the impression he had disconnected but when I later checked it showed as still connected.

Geffers

**Comment by redfast00** [comment]
You can revoke the `.ovpn` file to permanently block access with `pivpn revoke`.

**Comment by Geffers** [comment]
Didn't want to actually revoke but there again, if he is an authorised client then no real problem I suppose.

Geffers

**Comment by cfcolaco** [comment]
@Geffers if it's unauthorized just block it. 

if for some reason you just want to disconnect it for some time ... 
Just create an IP tables rule matching the IP address to block it,  restart OpenVPN and it won't connect anymore. ( just doing some logical thinking, didn't tested it tough )

something like this; 

`iptables -A INPUT -s XXX.XXX.XXX.XXX -j DROP` ( this will block is access to the whole server) 

or 

`iptables -A INPUT -s XXX.XXX.XXX.XXX -p tcp --destination-port <VPNPORT> -j DROP` ( this will block only on the specified port )
