### ISSUE TITLE
Reinstallation

### ISSUE THREAD

**Issue by symvizan** [pivpn/pivpn#321]
Hello!

How can I delete pivpn?

I want to reinstall it as when I have installed it it I was on another network and I'm not sure if I have completed the installation than. But I want to remove all things related to pivpn so I can reinstall it.

Also I have Ajenti webpanel with OpenVPN already installed I don't know if that messes up something I don't think so.

Thanks.

**Comment by redfast00** [comment]
You can remove PiVPN with `pivpn uninstall`. If you have any issues, reply to this issue and I'll reopen it.
