### ISSUE TITLE
Repository Error Armbian

### ISSUE THREAD

**Issue by VinSz2** [pivpn/pivpn#322]
Hello together,

need help since i m trying to use Pivpn on another ARM-Board.

I m talking about the banana-pi with Armbian.

Using PiVPN on a Pine64 with Armbian already, but only on the B-Pi im receiving following issue

W: Failed to fetch http://build.openvpn.net/debian/openvpn/stable/dists/jessie/Release  Unable to find expected entry 'main/binary-armhf/Packages' in Release file (Wrong sources.list entry or malformed file)

Tried to find it in /etc/apt/sources and delete or replace it, but apparently its not entered there.

Thank you in advance.

Regards

**Comment by cfcolaco** [comment]
@VinSz2 

can you please provide me the output of: 

`lsb-release`  ( think I am writing it well ) 
`cat /etc/os-release` 

Guess I might know what's happening.

**Comment by VinSz2** [comment]
hello,

lsb-release>command not found

 cat /etc/os-release

NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

**Comment by coreinsane** [comment]
I also have this problem with Orange Pi One.
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Comment by cfcolaco** [comment]
Actually I don't have how to test this, but it fails basically because PiVPN expects the info in /etc/os-release to be in one way and those distros have them in another, so supported for those distros needs to be added which will take a while to happen, if it ever will happen, however I will leave the ticket here so I can look at it in the future

**Comment by 0-kaladin** [comment]
I'll assign to me cause I actually can test this. But will be months. Like December.

**Comment by cfcolaco** [comment]
Great @0-kaladin If I ever get the chance to look at it I will also.

**Comment by 4s3ti** [comment]
I think this is not happening anymore, if its the case, please reopen or open a new issue with more details.
