### ISSUE TITLE
How do I uninstall pivpn on my rasberry pi 3?

### ISSUE THREAD

**Issue by fortresscrasher** [pivpn/pivpn#326]
I want to uninstall pivpn on my rasberry pi for acouple weeks but i don't know how.

**Comment by fortresscrasher** [comment]
I know I can't do -u for uninstalling it but is it just that or is there other stuff to uninstall?

**Comment by fortresscrasher** [comment]
Correction I meant to say I can do -u to uninstall but what I'm asking is there anything else I have to uninstall or does that do everything for me

**Comment by redfast00** [comment]
Yup, `pivpn -u` should uninstall everything (it probably will still leave a trace somewhere, but that shouldn't really matter)
