### ISSUE TITLE
install changes default subnet from /24 to /16

### ISSUE THREAD

**Issue by b1x13** [pivpn/pivpn#328]
Very new to linux, rpi, and openvpn.

Here is my config for eth0 before installation. 
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether b8:27:eb:54:15:31 brd ff:ff:ff:ff:ff:ff
    inet **172.16.2.11/24** brd 172.16.2.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::ddd3:5636:19af:905f/64 scope link
       valid_lft forever preferred_lft forever

I then run:
curl -L https://install.pivpn.io | bash

And finally after the install and reboot this is what i am seeing:
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether b8:27:eb:54:15:31 brd ff:ff:ff:ff:ff:ff
    inet **172.16.2.11/16** brd 172.16.255.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::ddd3:5636:19af:905f/64 scope link
       valid_lft forever preferred_lft forever

looking in interfaces here is the config for eth0
iface eth0 inet manual

and finally to my question, where is my subnet getting messed up?

**Comment by nezero** [comment]
I just had this problem. See this post on how [/etc/dhcpcd.conf](https://raspberrypi.stackexchange.com/questions/62665/setting-subnet-mask-with-dhcpd-conf) should be setup.

**Comment by b1x13** [comment]
Just as a follow up, that worked. instead of rebooting pi server after install, i edited the dhcpcd.conf file with a /24 saved and rebooted. I would still consider this a bug but i am closing the issue.
