### ISSUE TITLE
upgrading

### ISSUE THREAD

**Issue by ostermayer** [pivpn/pivpn#33]
What is the best way to upgrade the install. A new curl install or a git pull?

**Comment by 0-kaladin** [comment]
there is no upgrade. since this is an installer if you have no issues immediately after the install then you should be fine.  if you want to upgrade the installer, then run it clean,
pivpn uninstall
then curl command again, you'll have to redistribute new ovpn files.

**Comment by 0-kaladin** [comment]
I added my comments about it to the wiki
https://github.com/pivpn/pivpn/wiki/Upgrading
