### ISSUE TITLE
It won't connect to my iphone

### ISSUE THREAD

**Issue by fortresscrasher** [pivpn/pivpn#330]
im new to this and I've tried different ways multiple times. I have port set up. It's going in my ssh. When I get it on the openvpn app it gets up to like 6KB out but then times me out

**Comment by fortresscrasher** [comment]
I know this isn't much information but if anyone can help me thank you very much

**Comment by fortresscrasher** [comment]
I have a verizon fios router

**Comment by K7LRK** [comment]
I am having the same problem.  I found a solution further back .. Look for "Error using iOS OPRENVPN #171 "  

Here is the relevant text from that issue:
=========
There is some chatter on other groups that some OpenVPN
	implementations cannot handle client keys that are encrypted with
	RSA.

If your client key is encrypted, you might try a different client
	that is unencrypted, or re-encrypting your current client key
	using 3DES.

openssl rsa -in Client1.key -des3 -out Client1.3des.key

and then replace your old client key with the new client key in your
	configuration.

... and then a bit later ...

If you look inside your .ovpn file, you'll see a line <key>, many
	lines of text, and then a line </key>. Everything in between
	those two markers (but not the two markers themselves) is your
	encrypted secret "key" and should be copied to Client1.key as
	described above. Once you then have Client1.3des.key as described
	above, replace the text between the markers with the new key.

Keep a backup of your original .ovpn.
===========
I have not tested this yet so I don't know if it will solve the problem but I am hopeful.

Clark

**Comment by Kavaho** [comment]
@fortresscrasher Can you connect with other machines? If so, try commenting in the "minimal-tls" line using ; before it. Import that edited client file to your iphone and try again. If that does not work too, try commenting the same line in the /etc/openvpn/server.conf. I've also read that there is a bug in the new version of the OpenVPN app for iphones, try reinstalling.

**Comment by magnatronus** [comment]
The only way I found that will work is to NOT use a password when creating the .ovpn just for my iOS devices (iPhone/iPad).

i.e.        use -a nopass     

Create a client ovpn profile with no password

**Comment by nagubal** [comment]
I have no problem connecting to my VPN using iPhones, even with a password set when creating the .ovpn for iOS devices (iOS 10 or 11).
I connect with the [OpenVPN Connect app](https://itunes.apple.com/fr/app/openvpn-connect/id590379981?mt=8) available from the AppStore.

Are you using the OpenVPN Connect app on your iOS devices ?

**Comment by krylle** [comment]
I cannot connect with the OpenVPN Connect App from the AppStore ... when i import the *.ovpn to the App i says "error : PolarSSL: error parsing config private key" ... when i use "pivpn add nopass" it will connect but without asking for the password.

**Comment by cfcolaco** [comment]
please read issue #364 
If further help needed please raise a new issue with detailed information.
