### ISSUE TITLE
Changing IP address?

### ISSUE THREAD

**Issue by jsfrederick** [pivpn/pivpn#331]
If I need to change the IP address of my PiVPN server (ie. from 192.168.0.xx to 192.168.5.xx), will PiVPN pick up that change?  Or will I need to edit Config files?  I realized that I will need to edit /etc/openvpn/server.conf, are there any others?

Thanks!

**Comment by redfast00** [comment]
If you want to change the internal IP of the server, you will at least (so there might be more) need to edit the server config and maybe the forwarding rules. If it doesn't work out, it might be the easiest to just uninstall and reinstall.

**Comment by cfcolaco** [comment]
@jsfrederick 

if is just the internal network IP address, all you need to do is to properly change the port forwarding, and everything else should be.

As this issue is from Aug10 and still no more answers, I am going to close the issue. if you need further help with this just ask.
