### ISSUE TITLE
No Internet if OpenServer is connected to ethernet

### ISSUE THREAD

**Issue by orien2k** [pivpn/pivpn#332]
## Issue
Hello as my description says i loose internet (in some computers) if my OpenVPN Server is online. I created a Raspberry Pi with the Server and if i disconnect the Ethernet cable from the Raspberry the internet is Ok. If i connect the cable back two computers loose internet completely. I checked IPs on the network they are ok. The only thing i did different this time was when i configured the Open VPN Server it asked me if i wanted to use my Public IP or a DNS i choose DNS and used the dyndns.org that i have. If anyone can help me i would be greatly appreciated. Thank you  
PS No Computers is connected to the VPN (inside or out of the network)

**Comment by cfcolaco** [comment]
@orien2k what a Weird issue you have here! xD

First, provide us all the information we request on the PiVPN Issue template. 

Second, when the pi is connected to the network, can you check if you are able to ping 8.8.8.8 on the devices that lose internet access?

**Comment by cfcolaco** [comment]
Closing as no answer was given...
