### ISSUE TITLE
cannot make iptables persistent.  apt-get error after pivpn install

### ISSUE THREAD

**Issue by umpire7777777** [pivpn/pivpn#334]
## Issue
I have pivpn working successfully on my raspbery pi 2+.
I had to manually enter the iptables commands
$ sudo /sbin/iptables --table nat -A POSTROUTING -o wlan0 -j MASQUERADE
$ sudo /sbin/iptables -P FORWARD ACCEPT

I run this:  $ sudo netfilter-persistent save
run-parts: executing /usr/share/netfilter-persistent/plugins.d/15-ip4tables save
run-parts: executing /usr/share/netfilter-persistent/plugins.d/25-ip6tables save

after a reboot, doesn't work unless I run these again.

I also get errors on sudo apt-get now.  Here are results from jounalctl$ sudo journalctl -xe
Aug 12 19:49:54 raspberrypi systemd[1]: Mounted /.
-- Subject: Unit -.mount has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit -.mount has finished starting up.
--
-- The start-up result is done.
Aug 12 19:49:54 raspberrypi systemd[1]: Starting Load Kernel Modules...
-- Subject: Unit systemd-modules-load.service has begun with start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit systemd-modules-load.service has begun starting up.
Aug 12 19:49:54 raspberrypi systemd-modules-load[12885]: Failed to find module 'ipmi_devintf'
Aug 12 19:49:54 raspberrypi systemd-modules-load[12885]: Failed to find module 'ipmi_msghandler'
Aug 12 19:49:54 raspberrypi systemd-modules-load[12885]: Failed to find module 'ipmi_poweroff'
Aug 12 19:49:54 raspberrypi systemd-modules-load[12885]: Failed to find module 'ipmi_si'
Aug 12 19:49:54 raspberrypi systemd-modules-load[12885]: Failed to find module 'ipmi_watchdog'
Aug 12 19:49:54 raspberrypi systemd[1]: systemd-modules-load.service: main process exited, code=exited, stat
Aug 12 19:49:54 raspberrypi systemd[1]: Failed to start Load Kernel Modules.
-- Subject: Unit systemd-modules-load.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit systemd-modules-load.service has failed.
--
-- The result is failed.
Aug 12 19:49:54 raspberrypi systemd[1]: Dependency failed for netfilter persistent configuration.
-- Subject: Unit netfilter-persistent.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit netfilter-persistent.service has failed.
--
-- The result is dependency.
Aug 12 19:49:54 raspberrypi systemd[1]: Unit systemd-modules-load.service entered failed state.
Aug 12 19:49:54 raspberrypi sudo[12822]: pam_unix(sudo:session): session closed for user root
Aug 12 19:49:57 raspberrypi sudo[12891]: pi : TTY=pts/0 ; PWD=/home/pi ; USER=root ; COMMAND=/bin/journalctl
Aug 12 19:49:57 raspberrypi sudo[12891]: pam_unix(sudo:session): session opened for user root by pi(uid=0)
lines 1022-1061/1061 (END)

**Comment by cfcolaco** [comment]
To save that rules you should use:

`iptables-save > /etc/iptables/rules.v4`  Not the Netfilter command. 

Try this first to see if the problem gets solved.
Are you using Raspbian?? Because PiVPN should do this by itself you shouldn't need to issue that manually.

**Comment by Kavaho** [comment]
I had a problem with saving my iptables rules aswell, but managed to fix it reading this: https://www.thomas-krenn.com/en/wiki/Saving_Iptables_Firewall_Rules_Permanently

**Comment by umpire7777777** [comment]
Yes, using Raspian.
Linux raspberrypi 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux

I can write out that rules.v4 file, but it will not persist.  It seems that iptables-persistent and netfilter-persistent will NOT configure correctly.  Anyone seen this before?  I think this is a raspbian issue, not a pivpn issnue.  Although pivpn is impacted.

etting up netfilter-persistent (1.0.3+deb8u1) ...
update-rc.d: warning: start and stop actions are no longer supported; falling back to defaults
A dependency job for netfilter-persistent.service failed. See 'journalctl -xn' for details.
invoke-rc.d: initscript netfilter-persistent, action "start" failed.
dpkg: error processing package netfilter-persistent (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of iptables-persistent:
 iptables-persistent depends on netfilter-persistent (= 1.0.3+deb8u1); however:
  Package netfilter-persistent is not configured yet.

dpkg: error processing package iptables-persistent (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 netfilter-persistent
 iptables-persistent
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by umpire7777777** [comment]
@Kavaho - I think your article has the answer.  At the bottom of that article is a bug mentioned.  The version of netfilter-persisitent v1.0.3 and fixed in v1.0.4.  I'm trying to get v1.0.4 installed now to see if this fixes it.

**Comment by Kavaho** [comment]
@umpire7777777 I am glad if it helped. Good luck.

**Comment by umpire7777777** [comment]
installing v1.0.4 from stretch worked.  I didn't read the full install log of pivpn, but it did fail to add these iptable entries and make them permanent.  Otherwise, everything worked great.

I am working.  You can close this is as an issue whenever you believe it's resolved.
