### ISSUE TITLE
Install issue on a rasp pi stretch release

### ISSUE THREAD

**Issue by thewriteway** [pivpn/pivpn#337]
# PiVPN Issue Template

## Console output of `curl install.pivpn.io | bash`
```
Note: using Easy-RSA configuration from: ./vars
rand: Use -help for summary.
Generating a 2048 bit RSA private key
...............+++
.+++
writing new private key to '/etc/openvpn/easy-rsa/pki/private/server.key.83HmeC4ICF'
-----
Using configuration from /etc/openvpn/easy-rsa/openssl-1.0.cnf
Can't open /etc/openvpn/easy-rsa/pki/index.txt.attr for reading, No such file or directory
1995564448:error:02001002:system library:fopen:No such file or directory:../crypto/bio/bss_file.c:74:fopen('/etc/openvpn/easy-rsa/pki/index.txt.attr','r')
1995564448:error:2006D080:BIO routines:BIO_new_file:no such file:../crypto/bio/bss_file.c:81:
Check that the request matches the signature
Signature ok
The Subject's Distinguished Name is as follows
commonName            :ASN.1 12:'server'
Certificate is to be certified until Aug 18 05:41:31 2027 GMT (3650 days)

Write out database with 1 new entries
Data Base Updated

```

## Console output of `pivpn add` or `pivpn add nopass`
```

```

## Console output of `pivpn debug`
```

```

**Comment by furrybanana** [comment]
I am experiencing the same error. 

> Using configuration from /etc/openvpn/easy-rsa/openssl-1.0.cnf
Can't open /etc/openvpn/easy-rsa/pki/index.txt.attr for reading, No such file or directory
1995564448:error:02001002:system library:fopen:No such file or directory:../crypto/bio/bss_file.c:74:fopen('/etc/openvpn/easy-rsa/pki/index.txt.attr','r')
1995564448:error:2006D080:BIO routines:BIO_new_file:no such file:../crypto/bio/bss_file.c:81:
Check that the request matches the signature
Signature ok

**Comment by FilipStadler** [comment]
I am not able to find the reason - but is the easy-rsa different to the  stretch release compared to the Jessica release? it also happen on a clean stretch installation.

**Comment by ThomasLuyckx** [comment]
Same here. Indeed, on a clean release:

Using configuration from /etc/openvpn/easy-rsa/openssl-1.0.cnf
Can't open /etc/openvpn/easy-rsa/pki/index.txt.attr for reading, No such file or directory
1996297632:error:02001002:system library:fopen:No such file or directory:../crypto/bio/bss_file.c:74:fopen('/etc/openvpn/easy-rsa/pki/index.txt.attr','r')
1996297632:error:2006D080:BIO routines:BIO_new_file:no such file:../crypto/bio/bss_file.c:81:
Check that the request matches the signature
Signature ok

**Comment by cfcolaco** [comment]
@thewriteway @FilipStadler @furrybanana @ThomasLuyckx 

Are you installing on a Fresh raspbian stretch??? 

PR #374 Might have solved this. would be good to have some tests on this. 

Here is how to install from test branch
https://github.com/pivpn/pivpn/wiki#testing

**Comment by cfcolaco** [comment]
Closing issue as per PR #376 this should no longer apply! 

Support for Stretch now on master branch already

Please feel free to report if you need anything I will be glad to help!!

**Comment by SeanChristopherConway** [comment]
I am trying to install pivpn to be used on my Asus AC 3100 router. The install is clean on the Pi.
In my router logs I get this:

Oct 17 09:40:07 vpnclient5[13559]: OpenVPN 2.3.2 arm-unknown-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [eurephia] [MH] [IPv6] built on Aug 31 2017
Oct 17 09:40:07 vpnclient5[13559]: WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Oct 17 09:40:07 vpnclient5[13559]: Error: private key password verification failed

And in my pi openvpn.log I get this:

Tue Oct 17 16:45:45 2017 OpenVPN 2.4.0 arm-unknown-linux-gnueabihf [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jul 18 2017
Tue Oct 17 16:45:45 2017 library versions: OpenSSL 1.0.2l  25 May 2017, LZO 2.08
Tue Oct 17 16:45:45 2017 NOTE: your local LAN uses the extremely common subnet address 192.168.0.x or 192.168.1.x.  Be aware that this might create routing conflicts $
Tue Oct 17 16:45:45 2017 TUN/TAP device tun0 opened
Tue Oct 17 16:45:45 2017 do_ifconfig, tt->did_ifconfig_ipv6_setup=0
Tue Oct 17 16:45:45 2017 /sbin/ip link set dev tun0 up mtu 1500
Tue Oct 17 16:45:45 2017 /sbin/ip addr add dev tun0 10.8.0.1/24 broadcast 10.8.0.255
Tue Oct 17 16:45:45 2017 Could not determine IPv4/IPv6 protocol. Using AF_INET


Also I still notice when I install via bash that the openssl in easy/rsa is 1.0 whereas the etc/ssl version is 1.1.

Any help would be great!

**Comment by cfcolaco** [comment]
@SeanChristopherConway 

your problem has nothing to do with this ticket... and your explanation is quite confusing, please open a new issue and provide the information requested on the template.
