### ISSUE TITLE
IP Address does not change

### ISSUE THREAD

**Issue by blizzardfan44** [pivpn/pivpn#34]
I can successfully connect to the VPN. You did a great job with the code. Thanks for that. However, my address through the VPN is still what my public IP address is. I could be understanding this incorrectly, but shouldn't my IP address with the VPN enabled be different that what my ISP assigned IP address is? I am very new to this, so I apologize if I don't understand this fully.

**Comment by 0-kaladin** [comment]
Your addr through the vpn should be the public IP of whatever location the pi is located.  IE if it is at your house then it will be your home's public IP.  There is no reason to use it, in that case, when you are home.  When you would use it is when you were not at home.  Go to a public wifi hotspot, like starbucks.  See what your IP is.  now connect your vpn and you'll see it'll change to be from your house.  
So what happened?  all your traffic from the starbucks wifi was tunneled (encrypted within) right over to your house where it is now leaving as normal to get to the sites.  so no bad entity at starbucks can sniff your traffic, profile your browsing, grab logins, etc.  You are safe.  Enjoy.

**Comment by blizzardfan44** [comment]
Ok. That makes sense now. Thanks so much for the help. Is it possible to change the location in order to access geographically locked location (like BBC's iplayer to watch their tv shows)

**Comment by 0-kaladin** [comment]
the location is where you physically installed this script.  if it is in your house then that is the location.  changing it means connecting to a vpn server that is not in your house (one of the paid services). Alternatively you can spin up a free tier amazon server on the AWS cloud which you can create in ireland, virginia, oregon, frankfurt, etc. and install this script there.  that would give you that location.  
the paid services generally will have multiple endpoints and on connection you can choose the one you want to connect to.
