### ISSUE TITLE
PIVPN stunnel

### ISSUE THREAD

**Issue by haroonmansha** [pivpn/pivpn#341]
I am new to Pi and this forum, I have successfully installed pivpn script , and then as per instructions from different web ,but problem is that I cant access it outside the lan , while inside lan I can do it. 

anyone can give idea how I should do 

Tks

**Comment by redfast00** [comment]
Have you portforwarded?

**Comment by haroonmansha** [comment]
Yes I have port forward successfully,  Even now if I connect directly to openvpn I can, but doing through stunnel gives connect timeout and sometimes with error no more addresses to connect, maye it seems where I have written connect = localhost:1194 , I should write the ip ,   but it is not working on 127.0.0.1

that's why it's not working outside lan

**Comment by redfast00** [comment]
Well, we only have a script to setup OpenVPN, so we don't really support anything else (like stunnel). Since you said it works fine if you connect directly (without stunnel), I am closing this. Feel free to post a reply if you found a solution though.

**Comment by haroonmansha** [comment]
but I want to use it to wrap with stunnel due to fact some countries filters internet and I want it for it.  I was expecting if you help on this matter.  Do you think I should use 10.0.8.0 as a raspberry ip for connecting internally

**Comment by cfcolaco** [comment]
@haroonmansha we only support you with the PiVPN, we are few maintaining this project and with little time to dedicate to it in the moment.

If your OpenVPN is working properly then, everything else is on you. 
I apologize for that, but right now it has to be that way, and we must keep on PiVPN track, not going sideways.
