### ISSUE TITLE
Why the subnet

### ISSUE THREAD

**Issue by gordonZta** [pivpn/pivpn#344]
someone told me, when I use this, it will be as if I am on my local network. Except that it's not. this apparently builds a whole new subnet and routs traffic onto my local net. Hence, all my static IPs I have assigned to my devices are not used. Can I make it so, it does not run a separate dhcp server etc? I want to be able to log in and be on my local network as if I am there, same internal IP etc.

**Comment by cfcolaco** [comment]
@gordonZta as far as my knowledge goes .. that is not possible. 

This is how it works: 

You connect to your VPN server. 
A Private tunnel is created between the client and the VPN Server
Client traffic is encrypted and routed through VPN server.
VPN Server, has knowledge about the LOCAL subnet where it is sitting and that is why you can access to your local network, However, a VPN Client will always sit in a different subnet, and if you think on this you will see a ton of reasons for this to happen.
It is yet possible to configure OpenVPN to give a Specific 10.8.0.0/24 IP address to a specific client, however ... you cannot have the same VPN Subnet as your local network or it will fail!

Hope my brief and fast explanation helped you.
Closing issue as it has no direct relation with OpenVPN
If you need more information or to discuss something more tough, feel free to comment here, I will be around.
