### ISSUE TITLE
"pivpn" command is not installed automatically

### ISSUE THREAD

**Issue by xubiod** [pivpn/pivpn#345]
## Console output of `pivpn`
```
bash: pivpn: command not found
```
## Issue
The `pivpn` command was not installed correctly.
Attempting to run it shows the default bash command not found output.

**Comment by xubiod** [comment]
I took the `pivpn` file in the root of the repository and copied the code into a superuser terminal running nano and saved the file as `pivpn`. Then I ran `chmod +x pivpn` as superuser to set the file to be excuted by "Anyone". Then the command ran fine. This is the only workaround I could think of, but this may be helpful for someone else.

**Comment by redfast00** [comment]
What OS are you running this on? Do you still have the logs?

**Comment by Quasimorte** [comment]
ran into the same issue and got this on install. I am using octopi which is 2017-06-21-octopi-jessie-lite-0.14.0

Even after creating the directories and chmod 777 just for giggles if failed with that.

::: Installing scripts to /opt/pivpn...cp: cannot stat ‘/etc/.pivpn/scripts/makeOVPN.sh’: No such file or directory
cp: cannot stat ‘/etc/.pivpn/scripts/clientStat.sh’: No such file or directory
cp: cannot stat ‘/etc/.pivpn/scripts/listOVPN.sh’: No such file or directory
cp: cannot stat ‘/etc/.pivpn/scripts/removeOVPN.sh’: No such file or directory
cp: cannot stat ‘/etc/.pivpn/scripts/uninstall.sh’: No such file or directory
cp: cannot stat ‘/etc/.pivpn/scripts/pivpnDebug.sh’: No such file or directory
cp: cannot stat ‘/etc/.pivpn/scripts/fix_iptables.sh’: No such file or directory
chmod: cannot access ‘/opt/pivpn/makeOVPN.sh’: No such file or directory
chmod: cannot access ‘/opt/pivpn/clientStat.sh’: No such file or directory
chmod: cannot access ‘/opt/pivpn/listOVPN.sh’: No such file or directory
chmod: cannot access ‘/opt/pivpn/removeOVPN.sh’: No such file or directory
chmod: cannot access ‘/opt/pivpn/uninstall.sh’: No such file or directory
chmod: cannot access ‘/opt/pivpn/pivpnDebug.sh’: No such file or directory
chmod: cannot access ‘/opt/pivpn/fix_iptables.sh’: No such file or directory
cp: cannot stat ‘/etc/.pivpn/pivpn’: No such file or directory
chmod: cannot access ‘/usr/local/bin/pivpn’: No such file or directory
cp: cannot stat ‘/etc/.pivpn/scripts/bash-completion’: No such file or directory
bash: line 410: /etc/bash_completion.d/pivpn: No such file or directory
 done.

**Comment by cfcolaco** [comment]
@xubiod which distro are you using?? 

@Quasimorte octopi is not supported and there is no intent on supporting it since the octopi devs didn't want to cooperate! 

Check out issue #278  .. might help you.

**Comment by xubiod** [comment]
I'm using Rasbian, but I don't remember the exact version.
But I know it's not the latest Rasbian.

**Comment by cfcolaco** [comment]
@xubiod could be the case it is exiting after the IP address config  as in the isue #382 ??

**Comment by xubiod** [comment]
@cfcolaco Maybe. I was using a static IP for convenience of connecting over and over.

**Comment by cfcolaco** [comment]
@xubiod am closing this issue as there is no way to replicate this. as mentioned in issue #382 , 
Please try with Raspbian Stretch or a proper fresh install of jessie. 

don't see reason to use jessie instead of stretch right now.
