### ISSUE TITLE
Unattended Upgrades

### ISSUE THREAD

**Issue by patch01** [pivpn/pivpn#348]
I've been running my pivpn successfully for about a year. But I can't remember if I answered 'Yes' to the Unattended Upgrades option at time of install.

Is there any way to check if Unattended Upgrades is set to On or Off.

Thanks!

**Comment by jellemdekker** [comment]
Peering through the installation script, if you select 'Yes' it will install the package `unattended-upgrades`. So to check if you've selected yes or no, check if this package is installed with the command `dpkg -s unattended-upgrades`. If the output is similar to `Status: install ok installed`, then you did.

**Comment by cfcolaco** [comment]
@patch01 any news about this? 

Closing issue Reopen if needed.

**Comment by patch01** [comment]
Thankyou. I ran dpkg -s unattended-upgrades
Response showed
Status: install ok installed
