### ISSUE TITLE
Sending emails with thunderbird and pivpn

### ISSUE THREAD

**Issue by allnamesaretakeningithub** [pivpn/pivpn#349]
Hi all, i'm a noob with vpn's, which is one of the serveral reasons why i really like pivpn, and have been using it for some weeks now.
Noticed that i can't send emails from my machine when i'm connected to my pivpn. I use Thunderbird. Is there any setting i can change to be able to send emails with Thunderbird.
Thanks

**Comment by redfast00** [comment]
Do other services work (for example web browsing,...)?

**Comment by allnamesaretakeningithub** [comment]
Sorry i was not, specific in my last post. Other services work, e.g browsing, IM, and i can receive emails in thunderbird, i just can't send emails

**Comment by 0-kaladin** [comment]
What is thunderbird using for a local smtp server and would you have any reason to expect that to not be avail over the tunnel?

**Comment by cfcolaco** [comment]
closing issue as no answer was given. @allnamesaretakeningithub this is not entirely related with pivpn however we can try to help you out. if you need help just say something around here.
