### ISSUE TITLE
is UDP/TCP just used as a wrapper?

### ISSUE THREAD

**Issue by globbergouhl** [pivpn/pivpn#351]
Hello Dear Sir,
when I choose UDP during install, does this prevent me from using services that require TCP (after traffic exits my home network?) In other words, is whatever is sent between VPN client and server just wrapped into UDP and on the server end then unwrapped? Yet another way to ask the same question, is it possible that encrypted TCP traffic is sent through UDP tunnel? I hope it's clear what I am asking.

**Comment by redfast00** [comment]
Yes, whatever is sent is just wrapped in (encrypted) UDP. You should be able to send TCP or UDP packets, regardless of what you choose to tunnel over.
