### ISSUE TITLE
Obscuring traffic

### ISSUE THREAD

**Issue by EdKo66** [pivpn/pivpn#354]
Does this also obscure any traffic I 'might' do to torrents and similair sites. Bit (loads) confused.

**Comment by redfast00** [comment]
If your VPN is at home and you are not at home, all traffic between you and the server will be wrapped in OpenVPN. So what this means: if you were to torrent something (using the technology itself isn't illegal btw), the ISP of the internet connection at home would still be able to see what you are torrenting, but the place you are at can only see you send OpenVPN traffic. Please reply if you have further questions, I am closing this but will reopen if needed.
