### ISSUE TITLE
Newb Stuck at “desired upstream DNS provider(s)" Screen – thanks in advance for your time!

### ISSUE THREAD

**Issue by AZDNice** [pivpn/pivpn#356]
Sorry if this is posted in the wrong area.
I Had RBPi sitting around, doing nothing and one day came across an article about the PiHole-PiVPN. So I thought what the heck…jumped right in.  Started with the Raspbian then went on to the PiHole install; everything went so smooth I even created a back-up img of card.

Then on to PiVPN install. The install was going great. Even when to No-IP site to create a DNS host while generating my keys; that as well went fine, until I started the Public IP or DNS round of screens.
On the Public IP or DNS Screen, since I have PiHole, I selected “DNS Entry”.  On the next screen I had to enter my No-IP DNS Host; which I did.  Which took me to the DNS Provider Screen where I selected “Custom” because I have PiHole.  

After that screen is where I’m a little stuck.  I don’t want to mess this process up and have to do it all over again.  This screen came up next: 
 
![desired upstream dns provider srceenshot3](https://user-images.githubusercontent.com/24562423/30508856-a9573096-9a55-11e7-9184-979b5df482cc.PNG)

On this "desired upstream DNS provider(s)" screen do I enter my PiHole IP address?  I apologize in advance for the long winding explanation but if someones going to assist me with this issue I rather paint with all the information.

Thanks again
DNice

**Comment by 0-kaladin** [comment]
Yes you can enter the local ip of the pi-hole server. See
https://github.com/pivpn/pivpn/wiki/FAQ

**Comment by cfcolaco** [comment]
@AZDNice do you still need help with this?

**Comment by cfcolaco** [comment]
Closing as no more comms in this issue.
