### ISSUE TITLE
feature request? Add options to access local network

### ISSUE THREAD

**Issue by dustinarden** [pivpn/pivpn#36]
Great tool.  Configured it w/o a hitch.  I am able to connect from the android client and browse the internet as well as access the actual pi via ssh remotely.

I'd like to be able to access the rest of the hosts on the inside as well.  I'm pretty sure this type of functionality gets added to the server.conf file right?  Its a way of pushing a route to the client that makes the client "aware" of the other IP's on the LAN.  Does it go there or in the actual router's config?

If it goes in the openvpn config with a few questions you could probably pretty easily get the appropriate information from the user during the configuration steps to setup.

Just a thought.  Off to research openvpn commands in the config that will enable this.

**Comment by 0-kaladin** [comment]
there should already be a push route to your local network and the command 
client-to-client
IE, this should already work...

**Comment by 0-kaladin** [comment]
i just tested on mine and works.  just hit the internal ip of whatever internal server you have.  it wont resolve dns of your internal network, maybe you were trying that.

**Comment by dustinarden** [comment]
do i just need to push a route for each individual address that I need access to?

I was hoping for a more blanket /24 approach.

**Comment by 0-kaladin** [comment]
that's what it is.  what /24 do you want?  and send me what the routes are in your server.conf

**Comment by dustinarden** [comment]
basically while connected i'd like to access anything in the 10.10.1.0/24



dev tun
proto udp
port 1194
ca /etc/openvpn/easy-rsa/keys/ca.crt
cert /etc/openvpn/easy-rsa/keys/server.crt
key /etc/openvpn/easy-rsa/keys/server.key
dh /etc/openvpn/easy-rsa/keys/dh2048.pem
server 10.8.0.0 255.255.255.0
# server and remote endpoints
ifconfig 10.8.0.1 10.8.0.2
# Add route to Client routing table for the OpenVPN Server
push "route 10.8.0.1 255.255.255.255"
# Add route to Client routing table for the OPenVPN Subnet
push "route 10.8.0.0 255.255.255.0"
# your local subnet
push "route 10.10.1.108 255.255.255.0"
# Set your primary domain name server address for clients
push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 8.8.4.4"
# Override the Client default gateway by using 0.0.0.0/1 and
# 128.0.0.0/1 rather than 0.0.0.0/0. This has the benefit of
# overriding but not wiping out the original default gateway.
push "redirect-gateway def1"
client-to-client
duplicate-cn
keepalive 10 120
tls-version-min 1.2
tls-auth /etc/openvpn/easy-rsa/keys/ta.key 0
cipher AES-256-CBC
auth SHA256
comp-lzo
user nobody
group nogroup
persist-key
persist-tun
#crl-verify /etc/openvpn/crl.pem
status /var/log/openvpn-status.log 20
log /var/log/openvpn.log
verb 1
# This configuration file was originally written by Lauren Orsini at ReadWrite.

**Comment by 0-kaladin** [comment]
so this line
`push "route 10.10.1.108 255.255.255.0"`
is giving you access to that subnet already.  why do you think you can't access that subnet when vpn'd in.  what are you trying to access?  are you sure it isn't a dns issue?

**Comment by dustinarden** [comment]
i'm trying to access a webserver on another IP address (using an IP/port number not a DNS name) in the same /24 but it keeps timing out.
https://10.10.1.250:6789 for instance.

**Comment by 0-kaladin** [comment]
and are you sure the webserver is allowing traffic from other subnets?  maybe it is only allowing from the 10.10.1.0/24 while your vpn client is coming from the 10.8.0.0/24

**Comment by dustinarden** [comment]
well hell.  that could be it.

**Comment by 0-kaladin** [comment]
if its apache/nginx i can help if you need it.

**Comment by dustinarden** [comment]
nah its just a synology, but i'd rather not mess with individual routes for the hosts ... in order to have the entire 10.10.1.0/24 talk back to the VPN subnet i'll need to make the changes on my DDWRT router I assume?

I've been looking into that aspect of it but i already have a pretty convoluted custom startup script that outputs all my traffic bound for the internet (except for very specific IP's and ports) to go through my PIA VPN setup.  There is a static route option available that i'm hoping will get me somewhere but I assume i'll need to add some iptables rules in there as well.

**Comment by 0-kaladin** [comment]
you might just want to add the iptables example from bottom of this page
https://www.dd-wrt.com/wiki/index.php/Linking_Subnets_with_Static_Routes
in your case just add the 10.8 subnet

**Comment by dustinarden** [comment]
whats odd is i can ssh into 3 other boxes on the 10.10.1.0/24 VLAN so i have access to other network assets .. i just cant get to my internally hosted websites (sickbeard, nzbget, etc)
i can even ssh into my synology, but i cant browse to the sites hosted on it.

**Comment by 0-kaladin** [comment]
then i'd still wager those sites are maybe only allowing traffic on their local network.  also if you are on the sicbeard server and using localhost:port to connect to it then that is why.  it is only listening locally.

**Comment by 0-kaladin** [comment]
I'm going to close this since we know it isn't a pivpn issue but feel free to keep commenting and I'll reply if i have anything helpful to add.

**Comment by dustinarden** [comment]
thanks for your help!  Still trying to figure this out.
