### ISSUE TITLE
Official OpenVPN Connect Android client error with PiVPN on Stretch: Requested encryption or digest alg not available

### ISSUE THREAD

**Issue by killermosi** [pivpn/pivpn#364]
_Apologies for posting this as an issue here, but the IRC is slow, and we really need a forum or something where the information is more persistent than on IRC anyway._

I have upgraded my Pi OS from Jesse to Stretch a few days ago and finally got around to install PiVPN on the Pi, using the recommended installation method:

`curl -L https://install.pivpn.io | bash`

Everything went smooth, with the exception of a warning screen that the installed OS is not explicitly supported (which was no surprise).

After installation, I have created a new `.ovpn` profile for my Android device, and imported in the the official OpenVPN client: `OpenVPN Connect`.

However, when attempting to connect (after entering the password), this error popped out:

`CORE_ERROR PolarSSL: error parsing config private key : PKCS5 - Requested encryption or digest alg not available`

I did some digging, and the cause is that the encrypted private key in the `.ovpn` file uses a newer format that is not supported by the current Android OpenVPN client.

There are several options:

1. Don't use a password when creating the `.ovpn` file (**NOT** recommended!)
1. Downgrade to Jesse.
1. Wait for an upgrade of the Android OpenVPN client. Should happen sooner than later, but it may take a while.
1. Use an alternative client that supports the newer format. Apparently [OpenVPN for Android](https://play.google.com/store/apps/details?id=de.blinkt.openvpn&hl=en) by Arne Schwabe does so. BEWARE: Untested, use at your ow risk.
1. Re-encode the private key in the `.ovpn` file to an older format that is understood by OpenVPN Connect

For the more impatient people, like me, here is how to re-encode the private key:
```
cd ~/ovpns
cp not-working-profile.ovpn not-working-profile-backup.ovpn
openssl rsa -aes256 -in not-working-profile.ovpn -out new-key-file.key
```

This will ask for the key password and will generate a new key file (asking for a new password - you can use the same one), containing ONLY the key, having the following header:
```
-----BEGIN RSA PRIVATE KEY-----
Proc-Type: 4,ENCRYPTED
DEK-Info: AES-256-CBC,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

<private key content follows>
```

To compare, the old private key header (from the `.ovpn` file) looks like this:
```
-----BEGIN ENCRYPTED PRIVATE KEY-----
<private key content follows>
```

Now, after obtaining the new key, use your favorite text editor and open the `.ovpn` file and replace everything in between the `<key>` and `</key>` tags with the newly generated key.

Save the file, and then re-import the profile on your device. Enjoy!

**Comment by dpaight** [comment]
Thank you. Your solution for making a new key that works in OpenVPN Connect works perfectly.

**Comment by danpilch** [comment]
Hopefully the app is updated but I'm not going to hold my breath... Last update was in 2016

**Comment by redfast00** [comment]
@cfcolaco: do you want to edit the README to suggest clients? (OpenVPN for Android by Arne Schwabe,...)?

**Comment by killermosi** [comment]
Well, the desired solution pretty much boils down to upgrading the `PolarSSL` library used by the `OpenVPN Connect` client. 

I haven't been able to locate a public repository for the client code - was going to check the bugs list..

On a side note, this is on the `OpenVPN Connect` [homepage](https://staging.openvpn.net/openvpn3/), on the features list:

> Supports multiple crypto libraries via static polymorphism including:
> 
> * OpenSSL
> * PolarSSL
> * Apple Security/CommonCrypto API

However, I haven't found a way to manually switch between them.


We could create a script that the user can run to patch the `.ovpn` file to use the older key. Or better yet, can we instruct `openssl` to create the key using the older version?

We could dump the script/old version switch once the mobile client gets upgraded.

**Comment by cfcolaco** [comment]
@redfast00 will change that as soon as I can! (maybe I can have sometime today or tomorrow) ... however... which clients are known to work the best with right now?? 

Need to do some testing! With both Android and iPhone...

**Comment by plasticrake** [comment]
Same issue on iOS. On Stretch and latest OpenVPN iOS app. Had to swap the key manually. Thanks for the instructions!

**Comment by jgleal** [comment]
Perfect "temporary" solution!! Waiting for OpenVPN Connect supports PKCS5

**Comment by cfcolaco** [comment]
So ... @jellemdekker @plasticrake @killermosi @danpilch @dpaight @redfast00  

for me to understand all of this ... is getting hard to keep up with everything! 

The problem lies in the Mobile apps that Doesn't support The newer encryption algorithm??
I don't think we should revert back to older versions, we should instead push for the support to come faster! 

Can you please enlighten me exactly what have changed .. what is not supported? . got a bit confused with this one as encryption // hashing // and so on are not exactly my strongest point here! 

What Apps are know to work Good with the mobile phones?? 

I see that @redfast00 mentioned   **OpenVPN for Android by Arne Schwabe** this one is know to work well? I wonder why the official does not support and this one supports ... 

For iOS what is know to work good?  I am aware that openVPN connect works .. but has some caveats ... would appreciate your guidance in this points please so I can learn a bit more and be able to support our users in the best way I can regarding this matters. 

Thank you all .

**Comment by killermosi** [comment]
@cfcolaco: 

1. Yes, the problem is that the official OpenVPN mobile client (OpenVPN Connect) does not support the newer private key encryption algorithm that the `.ovpn` file uses
1. Only the private key encryption algorithm seems to be unsupported, everything else seems to work just fine - though I am not sure if any other sections of the `.ovpn` file could be encrypted as well.
1. The alternative Android client [OpenVPN for Android](https://play.google.com/store/apps/details?id=de.blinkt.openvpn&hl=en) by Arne Schwabe apparently works (I have found it on a forum page somewhere, recommended for this very issue we're discussing, but I have not tested it) but **I will refrain from openly encouraging anyone to use it, for the simple reason that it is not an official OpenVPN sanctioned client, ant it may contain risky security issues**. Same goes for the iOS client/alternatives.

I am strongly against PiVPN promoting any other client than the official one for the reasons listed above.

Like I said, I feel that until the official mobile client will be updated, if the user indicates that the mobile client version is `1.1.17 ` or below, PiVPN should generate an AES-256 encrypted private key, that is compatible with the current official mobile client.

**Comment by killermosi** [comment]
The Android client was updated to version `1.1.22 ` (several versions actually) since my previous comment, and this may render this entire issue moot. Which is a good thing :+1: 

Beware: there are fresh reviews complaining about functionality (and bad UI/UX), so if you're using the client for mission critical tasks, you may want to deffer upgrading to the latest version, at least for several days.

I'll come back with a comment once I'll upgrade the client.

**Comment by xCozmox** [comment]
There is a new version of the OpenVPN Connect client for Android. Version 1.1.23 but still I have the same issue:
"OpenVPN core error: mbed TLS: error parsing config private key : PKCS5 - Requested encryption or digest alg not available."

Is there any solution? You adivce not to use other Android apps, and you advice not to change the private key encryption.

**Comment by redfast00** [comment]
Well, I am a contributor to PiVPN and I am personally using OpenVPN for Android by Arne Schwabe. It's opensource and it works. https://github.com/schwabe/ics-openvpn/blob/master/README.md. I don't really know @killermosi or why they discourage people from using the app.

**Comment by killermosi** [comment]
Apologies, seems that I may have expressed myself badly.

@xCozmox: I am not advising against changing the key encryption (the original post details just how you can do that), I am advising against using an unprotected `.ovpn` profile (as is a bad idea from a security standpoint). If you are sure your device is secure, then please do so if you wish.

@xCozmox, @redfast00: I have not personally used another mobil client, except for the official one (I had no need to until I opened this very issue), but I feel that actively recommending another client than the official one is a big step that should be carefully considered.

Besides OpenVPN for Android by Arne Schwabe, are there any other alternatives worth mentining?

**Comment by TimmThaler** [comment]
killermosi's instructions I created a script that does convert the original ovpn file of a client from an rsa to aes256 key so that it will be usable with the iOS app "OpenVPN Connect".

I would appreciate some testing :)

**Comment by ordex** [comment]
Hey guys, would you confirm you are using the latest OpenVPN Connect app from PlayStore? I just imported my `.ovpn` file including an encrypted key starting with:
```
-----BEGIN` RSA PRIVATE KEY-----
Proc-Type: 4,ENCRYPTED
DEK-Info: AES-256-CBC,BD3141C2D660B48342DAEA3A8C71E85E
```

and I had no issue connecting.
Would you please confirm? This app is shipping mbedTLS 2.6.0, therefore it should not really have issues of "unsupported algorithms" unless we are talking about something extremely bleeding edge.

If you still have issues, would you mind reporting here how you create/encrypt your private key?
I'd like to give it a try.

Thanks!

**Comment by xCozmox** [comment]
Yes, I used : Version 1.1.23 and had the issue.


"OpenVPN core error: mbed TLS: error parsing config private key : PKCS5 - Requested encryption or digest alg not available."




As mentioned I just installed pivpn on stretch. 


Basic installation, no special adjustments. 




Than I created the ovpn profile and have the issue in open VPN connect app. The issue is not present in the app of Arne Schwabe.




And I get arround it by using the command described in this issue: 


openssl rsa -aes256 -in not-working-profile


And changing the private key in the file.




I did not yet tried v. 1.1.24. 




Best regards, Sebastian








On Sun, Nov 5, 2017 at 7:18 PM +0100, "Antonio Quartulli" <notifications@github.com> wrote:












Hey guys, would you confirm you are using the latest OpenVPN Connect app from PlayStore? I just imported my .ovpn file including an encrypted key starting with:
-----BEGIN` RSA PRIVATE KEY-----
Proc-Type: 4,ENCRYPTED
DEK-Info: AES-256-CBC,BD3141C2D660B48342DAEA3A8C71E85E



and I had no issue connecting.

Would you please confirm? This app is shipping mbedTLS 2.6.0, therefore it should not really have issues of "unsupported algorithms" unless we are talking about something extremely bleeding edge.


If you still have issues, would you mind reporting here how you create/encrypt your private key?

I'd like to give it a try.


Thanks!

**Comment by xCozmox** [comment]
Maybe worth to mention is that I used this installation:


https://github.com/pivpn/pivpn/wiki#testing




As the other one is not yet working on Raspbian Stretch.




Best regards, Sebastian




On Sun, Nov 5, 2017 at 9:28 PM +0100, <swahsner@posteo.de> wrote:










Yes, I used : Version 1.1.23 and had the issue.


"OpenVPN core error: mbed TLS: error parsing config private key : PKCS5 - Requested encryption or digest alg not available."




As mentioned I just installed pivpn on stretch. 


Basic installation, no special adjustments. 




Than I created the ovpn profile and have the issue in open VPN connect app. The issue is not present in the app of Arne Schwabe.




And I get arround it by using the command described in this issue: 


openssl rsa -aes256 -in not-working-profile


And changing the private key in the file.




I did not yet tried v. 1.1.24. 




Best regards, Sebastian








On Sun, Nov 5, 2017 at 7:18 PM +0100, "Antonio Quartulli" <notifications@github.com> wrote:












Hey guys, would you confirm you are using the latest OpenVPN Connect app from PlayStore? I just imported my .ovpn file including an encrypted key starting with:
-----BEGIN` RSA PRIVATE KEY-----
Proc-Type: 4,ENCRYPTED
DEK-Info: AES-256-CBC,BD3141C2D660B48342DAEA3A8C71E85E



and I had no issue connecting.

Would you please confirm? This app is shipping mbedTLS 2.6.0, therefore it should not really have issues of "unsupported algorithms" unless we are talking about something extremely bleeding edge.


If you still have issues, would you mind reporting here how you create/encrypt your private key?

I'd like to give it a try.


Thanks!

**Comment by ordex** [comment]
1.1.24 behaves like 1.1.23 in this regard. So it won't make any difference.
Thanks for the explanation. I'll check the script reported at https://github.com/pivpn/pivpn/wiki#testing to see how it creates the key and I will test here.

**Comment by ordex** [comment]
uhm one question: what version of openssl is installed on the system where you are launching the pivpn script?

**Comment by wospi** [comment]
Hello, 
I have the same issue. 
To answer Ordex question, I have version 1.1.0f (25 may 2017)

**Comment by xCozmox** [comment]
My version is the standard version which is installed with Raspbian 
Stretch. No changes. As I told, I have a standard "Stretch" 
installation, Standard pivpn installation. No changes done on the 
system. Just installed pivpn on a brand new Stretch.
Version is:
openssl version -v
OpenSSL 1.1.0f  25 May 2017

**Comment by ordex** [comment]
Sorry, but I have no experience with Raspbian or pivpn.
Reading the pivpn script has not been helpful to understand how keys are generated.

I don't know how to debug this issue any further if I can't create a 'non working key' of if I don't get one from you.

**Comment by wospi** [comment]
Hello Ordex, 
I can give you mine. 
It works with the app of Arne Schwabe but not with the official OpenVPN app. 

This is my file.ovpn

client
dev tun
proto udp
remote IP.IP.IP.IP PORT
resolv-retry infinite
nobind
persist-key
persist-tun
key-direction 1
remote-cert-tls server
tls-version-min 1.2
verify-xxxx-name server_mmmmmmmmmmmmmmm name
cipher AES-256-CBC
auth SHA256
comp-lzo
verb 1
<ca>
-----BEGIN CERTIFICATE-----
HERE IS THE CERTIFICATE
-----END CERTIFICATE-----
</ca>
<cert>
-----BEGIN CERTIFICATE-----
HERE IS THE CERTIFICATE
-----END CERTIFICATE-----
</cert>
<key>
-----BEGIN ENCRYPTED PRIVATE KEY-----
HERE IS THE KEY
-----END ENCRYPTED PRIVATE KEY-----
</key>
<tls-auth>
#
# 2048 bit OpenVPN static key
#
-----BEGIN OpenVPN Static key V1-----
HERE IS THE KEY
-----END OpenVPN Static key V1-----
</tls-auth>

**Comment by ordex** [comment]
Hi @wospi can you upload a sample private key somewhere so that I can download it? thanks

**Comment by wospi** [comment]
Hi Ordex, what do you need ? An entire key ? Or i can cut some text ?

**Comment by ordex** [comment]
@wospi  As far as I understood the problem is that the key can't be decrypted, therefore I need the entire key to make an attempt to decrypt it here. Note that this is your private key, therefore send me something that you don't want to use in the future.

**Comment by wospi** [comment]
I'll send you that in a few min, just trying to use the new key to be sure it doesn't works

**Comment by wospi** [comment]
How can I send i to you ?

**Comment by ordex** [comment]
Please send it to antonio@openvpn.net
You can encrypt the email if you want. Thanks

**Comment by TZim** [comment]
Thanks to everyone who's investigating this problem. I've encountered the same difficulty (RPI3, standard PiVPN on Raspbian Scratch, Android OpenVPN Connect). killermosi's key-reencode workaround solves it for me. @ordex, please let me know if you need data from other users. (I encountered the problem, and applied the workaround, in 1.1.22. I'm now running 1.1.24, and the workaround still works fine. I haven't re-tested the original problem in 1.1.24, but according to the above comments, it would be the same.)

**Comment by ordex** [comment]
Thanks for your feedback @TZim .
Yeah, 1.1.24 won't make any difference in this regard.

I am still testing, however, the "problem" is likely to be that openssl-1.1.0 is encrypting the key in a way that is not supported by mbedTLS-2.6.0 (that is the library shipped with OpenVPN connect). This is the same reason why "OpenVPN for Android": it ships openssl-1.1, if I am not wrong.

**Comment by killermosi** [comment]
Hey @ordex, thanks for your insight.

Can't the mbedTLS library be upgraded to support the newer key format? I assume it's newer, please correct me on this if I'm wrong...

**Comment by ordex** [comment]
Sure it can. Anybody is free to push patched to mbedTLS, however, it may not be a negligible effort.
However, it is likely that somebody already started this, but it takes time before it can be accepted -> merged -> released -> used. Thus this is not something we can really control, other than by contributing to the project.

**Comment by killermosi** [comment]
Ah, somehow I mistakenly believed that [mbedTLS](https://github.com/ARMmbed/mbedtls) was an internal OpenVPN project.

Will keep an eye on it.

**Comment by thewriteway** [comment]
> Based on killermosi's instructions I created a script that does convert the original ovpn file of a client from an rsa to aes256 key so that it will be usable with the app "OpenVPN Connect".

> https://github.com/TimmThaler/pivpn/blob/master/scripts/convert.openvpnconnect.sh

@TimmThaler your scripted worked perfectly! Once I adjusted my fat fingers for three password entries.

I did a wget of your raw .sh file from github and run it with sudo bash (otherwise unable to access the openvpn pki folder)

-my build = Linux version 4.9.59-v7+ on armv71 Rasp PI 3

Thanks.

**Comment by PeteRock1** [comment]
Thanks, dude. it worked for me thumb-up.

**Comment by ordex** [comment]
FYI, as I mentioned on other threads, the root cause has been identified in mbedTLS not supporting the hmac algo used by openssl 1.1 when encrypting the private key. This resulted in mbedTLS being unable to decrypt the key.

A permament fix to this problem has been proposed to mbedTLS upstream in https://github.com/ARMmbed/mbedtls/pull/1219

If such change will be ACk'd and then merged, it will make its way into mbedTLS and then OpenVPN Connect. At that point there shouldn't be any incompatibility anymore.

**Comment by cfcolaco** [comment]
Cool Thank you a lot for the heads up @ordex 

having this said, when that fix reaches mbedTLS the PR #402 and #412 are pretty much useless correct? 

@redfast00 @0-kaladin Please be aware of this because we might need to revert that PR!

**Comment by ordex** [comment]
@cfcolaco right. However, to be exact, we have to wait for OpenVPN Connect to ship the patched mbedTLS (which may happen even before the patch is merged and released by upstream).

**Comment by cfcolaco** [comment]
@ordex ok you are right!! 
However, I think we as PiVPN project... should not provide such fixes in our code since those are things that are going to be fixed sooner or later ... I think the correct approach should be exactly open an issue in the source of the problem or do what you did, provide a pull request that fixes it! 

Having those pieces of code in our scripts that will become obsolete, is a waste of time and energy! =/ so ... ok, we have a workaround here... until its permanently fixed at the source of the issue ... worst case scenario placing a separate script in a separate repo that does the job until it gets permanently fixed, just for the sake of making life easier to users with less knowledge and not that comfortable with a shell.

anyway, @ordex is there a way we can properly track when this gets solved, or give a hand to make it happen faster? or is the best way to track the PR you mentioned?

**Comment by ordex** [comment]
@cfcolaco I agree that the problem should always be solved where it was originated. Especially when FOSS projects are involved and everybody can contribute.
This said, i think for your situation, the best is simply to monitor the involved apps (Connect for iOS and Android) and check when the changelog of any new release will report this bug as fixed

**Comment by killermosi** [comment]
@ordex: Thank you. Wholeheartedly.

**Comment by dilipprasad** [comment]
Hi,
Thanks, yes i do face the same problem. I am using PI VPN with opel ssl version 1.0.21.Where special characters (such as #) in the passphrase does not seem to be considered. Will tell that its incorrect password. So tried without special characters, only alphanumeric characters and BAM, it works !!!

So the question is, any safe way of upgrading without disturbing the setup ?

**Comment by ordex** [comment]
Hi guys, so https://github.com/ARMmbed/mbedtls/pull/1219 has been merged! It will be shipped with mbedTLS 2.7.1 (and in some older stable release).
I guess it won't take longer before landing on OpenVPN Connect too!

**Comment by cfcolaco** [comment]
cool!! thanks a @ordex Please keep us posted if you can! =)

**Comment by ordex** [comment]
Hi all, OpenVPN Connect for iOS 1.2.9 (the next release in the pipe) should finally have support for keys encrypted with OpenSSL 1.1 (when used with its default settings).

**Comment by killermosi** [comment]
@ordex: Same with the Android version?

**Comment by ordex** [comment]
yeah should come out for Android soon too.
Now that 1.2.9 for iOS is out, could any of you guys give it a shot and let us know?
Thanks

**Comment by killermosi** [comment]
@ordex : Sadly, no iOS devices in my possession. I'll do a test once the Android version will be updated.

Any ETA on the Android update?

**Comment by lawipac** [comment]
@ordex  I tried on ios8  and result is yes + no
yes=success: if we use a key has no passphrase, it works perfectly.
log print with openvpn connect 1.2.9
`
2018-04-24 19:47:06 PROTOCOL OPTIONS:
  cipher: AES-256-GCM
  digest: SHA512
  compress: NONE
  peer ID: 0
2018-04-24 19:47:06 EVENT: ASSIGN_IP
2018-04-24 19:47:06 NIP: preparing TUN network settings
2018-04-24 19:47:06 NIP: init TUN network settings with endpoint: 139.99.192.196
2018-04-24 19:47:06 NIP: adding IPv4 address to network settings 10.8.0.10/255.255.255.252
2018-04-24 19:47:06 NIP: adding (included) IPv4 route 10.8.0.8/30
2018-04-24 19:47:06 NIP: adding (included) IPv4 route 10.8.0.1/32
2018-04-24 19:47:06 NIP: redirecting all IPv4 traffic to TUN interface
2018-04-24 19:47:06 NIP: adding DNS 208.67.222.222
2018-04-24 19:47:06 NIP: adding DNS 208.67.220.220
2018-04-24 19:47:06 Connected via NetworkExtensionTUN
2018-04-24 19:47:06 EVENT: CONNECTED @139.99.192.196:1194 (139.99.192.196) via /UDPv4 on NetworkExtensionTUN/10.8.0.10/ gw=[/]
2018-04-24 19:47:34 EVENT: DISCONNECTED
2018-04-24 19:47:34 Raw stats on disconnect:
  BYTES_IN : 455077
  BYTES_OUT : 167971
  PACKETS_IN : 838
  PACKETS_OUT : 968
  TUN_BYTES_IN : 136869
  TUN_BYTES_OUT : 427861
  TUN_PACKETS_IN : 950
  TUN_PACKETS_OUT : 824
2018-04-24 19:47:34 Performance stats on disconnect:
  CPU usage (microseconds): 1307063
  Tunnel compression ratio (uplink): 1.22724
  Tunnel compression ratio (downlink): 1.06361
  Network bytes per CPU second: 476677
  Tunnel bytes per CPU second: 432060
`
no=**failed to connect**: if it has a passphrase, it shows following errors:
`
2018-04-24 20:06:39 ----- OpenVPN Start -----
OpenVPN core 3.2 ios arm64 64-bit built on Feb 22 2018 12:39:28
2018-04-24 20:06:39 Frame=512/2048/512 mssfix-ctrl=1250
2018-04-24 20:06:39 EVENT: CORE_ERROR mbed TLS: error parsing config private key : PK - Bad input parameters to function [ERR]
2018-04-24 20:06:39 Raw stats on disconnect:
2018-04-24 20:06:39 Performance stats on disconnect:
  CPU usage (microseconds): 33167
  Network bytes per CPU second: 0
  Tunnel bytes per CPU second: 0
`

essentially the passphrase of the private key is not recognized properly.

BTW, same profiles are both working perfectly on window 10 platform.

**Comment by ordex** [comment]
uhm, interesting error.
Could you please run this command on your encrypted key and post the output please:
```openssl asn1parse -in keyfile```

**Comment by ordex** [comment]
@killermosi any luck with the new Android client?

**Comment by killermosi** [comment]
@ordex I was not aware that the Android client updated the mbedtls library, though I kept an eye on the changelogs for it... 

I'll dig up the old `.ovpn` file and make a test.

**Comment by killermosi** [comment]
@ordex : Hmm... it kind of works, sometimes.

Pretty much, 3 out of 4 times I end up with this when attempting to connect:

![image](https://user-images.githubusercontent.com/1872185/39234319-93ca11a6-487b-11e8-8757-d271d5d44a33.png)
(sorry about the big image...)

Retrying does not seem to work at all.

This is the log:

```
11:18:10.004 -- ----- OpenVPN Start -----

11:18:10.005 -- EVENT: CORE_THREAD_ACTIVE

11:18:10.028 -- Frame=512/2048/512 mssfix-ctrl=1250

11:18:10.068 -- EVENT: CORE_THREAD_ERROR info='mbed TLS: error parsing config private key : PK - Invalid key tag or value : ASN1 - ASN1 tag was of an unexpected value'

11:18:10.077 -- EVENT: CORE_THREAD_INACTIVE

11:18:10.078 -- Tunnel bytes per CPU second: 0

11:18:10.078 -- ----- OpenVPN Stop -----
```

Yet in 1 out of 4 cases (or less) it successfully connects, as evidenced by an IP check and the server clients list:

![image](https://user-images.githubusercontent.com/1872185/39234785-ee018b9e-487c-11e8-8f02-68c47d2d6fe7.png)

Anything else I can help with?

**Comment by killermosi** [comment]
Well, this issue seems to have been solved, at least on my side.

If it is fixed for everybody, I'll close it.

**Comment by killermosi** [comment]
Closed.

**Comment by phoerious** [comment]
I'm still having this problem with AES-CBC-encrypted private keys.

**Comment by killermosi** [comment]
Can you post a log? And client version?

**Comment by phoerious** [comment]
Log is basically the same about unsupported ciphers

```
18:57:58.286 -- ----- OpenVPN Start -----

18:57:58.287 -- EVENT: CORE_THREAD_ACTIVE

18:57:58.288 -- Frame=512/2048/512 mssfix-ctrl=1250

18:57:58.288 -- EVENT: CORE_THREAD_ERROR info='mbed TLS: error parsing config private key : PKCS5 - Requested encryption or digest alg not available'

18:57:58.291 -- EVENT: CORE_THREAD_INACTIVE

18:57:58.291 -- Tunnel bytes per CPU second: 0

18:57:58.291 -- ----- OpenVPN Stop -----
```

Client version is 3.0.5 which is the latest from the play store.

**Comment by killermosi** [comment]
If you convert the key using the method outlined in the initial post, does it wok?

**Comment by phoerious** [comment]
I managed to get it working with a new AES-CBC-encrypted RSA key. The old one was a key extracted from a PKCS#12 container. No idea what that didn't work.

**Comment by zapling** [comment]
Can confirm that the issue still exists, converting the key solved the issue.

**Comment by Telman93** [comment]
hello, please help me, windows 10 openvpn erorr
there was an error attempting to connect to the selected server

**Comment by zapling** [comment]
@Telman93 did you try to re-encode the key and update the `.ovpn` file?

**Comment by Telman93** [comment]
Hello, İ try re-encode the key and update, but, " there was an erorr attempting to connection to the selected server. 😔



Sent from my Samsung Galaxy smartphone.

<


-------- Original message --------

**Comment by akorn** [comment]
Update: lately (perhaps as of version 3), `openssl rsa` needs the `-traditional` switch to output encrypted keys in the older format. E.g. `openssl rsa -traditional -aes256 -in old.pem -out new.pem`.
