### ISSUE TITLE
how to get client.crt and client.key

### ISSUE THREAD

**Issue by Lakerway** [pivpn/pivpn#366]
I already got ca.crt and client.ovpn, but didn't find client.crt and client.key. Anyone can advise?

**Comment by redfast00** [comment]
You shouldn't need any file except the .ovpn file: the certificates and keys are in that file and don't need to be extracted. What client app are you using?

**Comment by Lakerway** [comment]
IP phone with VPN. If using openvpn,  the phone menu asks to upload four files: ovpn, ca.crt, client.crt and client.key

**Comment by cfcolaco** [comment]
@Lakerway so you need to extract them from the .OVPN file they are all there! =)

**Comment by Lakerway** [comment]
@cfcolaco found all in ovpn. thanks!

**Comment by cfcolaco** [comment]
no worries @Lakerway 

Closing Issue then. 

If you have further issues just shout, I will reopen the issue. 

Have fun! =)
