### ISSUE TITLE
DDNS

### ISSUE THREAD

**Issue by snakedog116** [pivpn/pivpn#368]
Hi, I'm wondering how to setup pivpn OpenVPN using a DDNS instead of just an IP address. I use DuckDNS.org

Thanks for any help.

**Comment by cfcolaco** [comment]
That is mentioned in the WIki 

https://github.com/pivpn/pivpn/wiki#dyndns

When installing PiVPN the installation will prompt you if you want to use an IP address or a DNS entry. 
You select the DNS Entry and then you are prompted to enter the domain name! 

After that, you just have to setup your router to update the Dynamic DNS server. 
If the router does not support there are clients you can install on the Rpi that will do the job! 

If you have already PiVPN installed and want to switch over to Dynamic DNS
replace your ip address with the dynamic dns domain damin in the ovpn file


from 
```
remote xxx.xxx.xxx.xxx 1194
```
to
```
remote yourDDNSDomain.com 1194
```



Closing issue. 
Reopen if needed!

**Comment by snakedog116** [comment]
Thanks, I don't think it asked me when I was installing it.

I was able to find the file and replace the IP address by using the following SSH commands:

sudo -i
vi /etc/openvpn/easy-rsa/pki/Default.txt
updating the IP address to my DDNS address (Leaving the port number)

**Comment by cfcolaco** [comment]
Oops! 
@snakedog116 forgot to mention that! 

Changing it in that file will change for all new certificates you issue! however you still need to change in the OVPN files you have already in use (if you have any)
