### ISSUE TITLE
Setting up OpenDNS with iOS devices

### ISSUE THREAD

**Issue by snakedog116** [pivpn/pivpn#369]
Hi,

I've setup OpenDNS and it works great. I'm able to use the OpenDNS app to start the VPN on my iPhone.

What I'd like to also be able to do is to make it so that I can start the VPN from the settings area on my phone instead of through the app. Right now I'm getting the error "Bad Private Key".

Do I need to hard program in the password somewhere to make this work?

Using the app isn't the worst, but it would be nice if it could be done from the settings.
Thanks

**Comment by cfcolaco** [comment]
I think OpenVPN is not supported by default on iPhone... not sure on that! 
But a lot of users end up here complaining because of the iPhones! 

Think there is an appropriate app for that! =/

**Comment by snakedog116** [comment]
I have OpenVPN setup to my brother’s house(he runs a linnux server) and it works on my iPhone in the settings app.

Basically when you use the openvpn app it creates a profile that syncs with the iPhone built in settings VPN and it adds a profile there 

However when using this installer The profile that it adds seems to have a password error.

So it’s definitely doable somehow. I’m just not sure how.

**Comment by cfcolaco** [comment]
@snakedog116 phone apps have know issues with certificates with passwords, so far for what I have seen the best option for phones is to use the --nopass switch when creating the certificate ... is not the most secure tough but should not be a problem also! 

please take a look around for similar issues that might help you out. 

Closing issue as this is not entirely related with pivpn, but more with OpenVPN phone apps.
