### ISSUE TITLE
Support for ipv6

### ISSUE THREAD

**Issue by billyprice1** [pivpn/pivpn#370]
Hi is there support for ipv6

**Comment by redfast00** [comment]
Yes, but you might need to edit some config files. https://community.openvpn.net/openvpn/wiki/IPv6

**Comment by redfast00** [comment]
Closing this, if you have any questions, please reply and I'll reopen this issue.

**Comment by billyprice1** [comment]
I dont know how can you make what a saple config for a /64 ipv6 block look like
