### ISSUE TITLE
Check for current installed version of PIVPN

### ISSUE THREAD

**Issue by patch01** [pivpn/pivpn#371]
Just wondering what command I would run to check what my current installed version was?

Is there a web address where I could find a list showing version history?

Thank you.

**Comment by cfcolaco** [comment]
that's kind of pointless!! 

Here is the explanation! 

https://github.com/pivpn/pivpn/wiki/Upgrading

**Comment by patch01** [comment]
*Check back in a month or so and see if features/fixes were added you think
you'd want. If they look like something you want or you are running into an
issue you see is fixed, take the 10min to an hour to uninstall, re-install,
and redistribute new client ovpn configurations.*

So if I'm checking back in a month, where am I checking?

**Comment by cfcolaco** [comment]
I Think we might be misunderstanding each other. 

pivpn is not properly a software that needs to be updated, as the wiki says and very well ... pivpn is an installer, and as a few scripts that make your life a bit easier by creating the ovpn and so on. 

all the important features you want reside in OpenVPN itself! 
all we as a community-driven project is to add support in the installer for newer distros and fix bugs that might occur during the install. 

Other extra new features we might offer is to provide different ways to install the OpenVPN server, like bridge mode and so on. 

however, if it helps you to get a better picture ... pivpn version right now is the exact same version from 6 months ago! the only PR done to Master branch were just bugfixes! 

Test branch has already support for the raspbian stretch,  Devuan, and some improvements but the features it provides are basically the same! 

if you are facing any kind of issue, you should search the issues with specific keywords, or ask here and we will do our best effort to help you out! 

You might also want to search pull requests, being that some mention which issues they fix. 

Hope we can get to an understanding now! =)

**Comment by patch01** [comment]
Hi Carlos,

Thanks for your detailed response.

Don't worry, I understand this is all a voluntary effort and I appreciate
all the fantastic work that has been done.

Thanks again!!
