### ISSUE TITLE
A way to hide my real IP ?

### ISSUE THREAD

**Issue by roms2332** [pivpn/pivpn#381]
Hi everyone,

I just installed PiVPN, and if I understand correctly it works like this (I'm not familiar at all with VPNs) : I connect on the Internet without PiVPN and if I check my IP on a website like https://whatismyipaddress.com/ it shows my real IP, but if I connect to my raspberry, and then go to the same site, it shows the IP where my raspberry is connected (in my case : at home).

My question is : is it "risky" to show our real IP ? Because in my case, with or without PiVPN, I have the same IP (I'm in my home and my raspberry too). And by the way, does my Internet access provider can see all of my browser data and all of these stuff, even if my IP is still visible ? My main goal was to protect me against big websites and my Internet access provider, but as my IP is still visible, I'm asking many questions and to be honest, I don't really know which Internet data is visible for Internet access provider / big sites like Twitter or Google.

Can you explain me how it works and in which proportions am I protected ? It would be very nice ! Thanks ;)

**Comment by redfast00** [comment]
Yes, you're still "visible" for your ISP. The main usecase for PiVPN (an installer script for OpenVPN) is to be able to securely connect to your home network from an untrusted location. For example, if you're in a restaurant and don't trust the wifi, you'll still be able to have a secure connection. PiVPN isn't meant to keep you anonymous: there exist VPN providers like PIA, or the TOR network for that. Please reply if you have any questions.

**Comment by redfast00** [comment]
Well, no, not quite. Your connection between you and the VPN server is secure, but the connection between the VPN server and the ISP is as secure as it would be if you were using the network at home. PiVPN secures against for example someone intercepting the traffic between you and the VPN server.
