### ISSUE TITLE
Running pivpn on multiple ports

### ISSUE THREAD

**Issue by danpilch** [pivpn/pivpn#385]
Is it possible to run pivpn on two ports? E.g.

80 UDP
443TCP

Thanks

**Comment by cfcolaco** [comment]
Attention to the concepts!!

PiVPN - Simply an openvpn Installer

OpenVPN The vpn software itself!! 

To run OpenVPN on two ports, just create a new server profile in `/etc/openvpn/`.

For example:

```
cp /etc/openvpn/server.cong /etc/openvpn/server2.conf
```

Edit server2.conf and change proto to to whatever protocol you want and port to whatever port you want!
