### ISSUE TITLE
How do i change the CA CN.

### ISSUE THREAD

**Issue by trilleplay** [pivpn/pivpn#387]
## Issue
I'm having trouble using the ca_info.txt .
I tried adding everything there but nothing works.
Then i poured over the Automatic Installation script and tried to specify the vars there using set_var .
It didn't use those vars.
It use the standard CN of ChangeMe.
But I could not find any referance to that.

Where should i specify the new CN?

Thanks!

**Comment by redfast00** [comment]
Why do you want to do this?

**Comment by trilleplay** [comment]
@redfast00 I wanted it to look cooler if in the future i commercalize it. However i fixed it by editing the easy-rsa source. Closing this now! (If anyone wants instructions reply here at this thread.)
