### ISSUE TITLE
How do access my Lan when connected via VPN?

### ISSUE THREAD

**Issue by TSether** [pivpn/pivpn#39]
Sorry, I am a total noob to raspberry pi.  I heard about PiVPN on the Security Now podcast.  I bought a pi kit and have it running and have been able to connect from public WIFI.  Thank you for making it so easy!  The one question I have, I how can I configure the VPN so I can see the other computers on my home network when connected via the VPN from outside? 

Thanks!

**Comment by 0-kaladin** [comment]
def read this as the same question you have: https://github.com/pivpn/pivpn/issues/36
bottom line, it should already work and probably you are doing something else wrong.  let me know exactly how you are trying to hit this other computer on your home network etc and I can tell you why it isn't working.

**Comment by TSether** [comment]
Thanks,  I was trying to connect by computer name, rather than by IP.  I tried connecting by IP today from outside the LAN and it worked great,  Thanks! 
I was thinking of putting a user guide together for my friends based on my "noob" experience. Would that be of any value?  I could send you a copy when done if you think it would help others.

**Comment by 0-kaladin** [comment]
Sure, any contributions are welcome.
