### ISSUE TITLE
Alternative home folder locations

### ISSUE THREAD

**Issue by jamesbptrsn** [pivpn/pivpn#390]
I recently did a new install of pivpn to a user whose home folder is not the default /home/user but instead /srv/user.  Generation of a new user file proceeded normally but encountered an error when copying the .ovpn file to the home folder.  It tried to copy the .ovpn file to the nonexistent /home/user folder.  I believe using the $HOME variable in scripts/makeOVPN.sh lines 236 and 237 would fix this problem.
There should also be some way to handle this error in the exit print statements.

## Console output of `pivpn add` or `pivpn add nopass`
```
Enter a Name for the Client:  james
Enter the password for the client:
Enter the password again to verify:
spawn ./easyrsa build-client-full james

Note: using Easy-RSA configuration from: ./vars
Generating a 2048 bit RSA private key
............................................................+++
..............+++
writing new private key to '/etc/openvpn/easy-rsa/pki/private/james.key.WAlYRSdlp8'
Enter PEM pass phrase:
Verifying - Enter PEM pass phrase:
-----
Using configuration from /etc/openvpn/easy-rsa/openssl-1.0.cnf
Check that the request matches the signature
Signature ok
The Subject's Distinguished Name is as follows
commonName            :ASN.1 12:'james'
Certificate is to be certified until Oct 20 02:50:33 2027 GMT (3650 days)

Write out database with 1 new entries
Data Base Updated
Client's cert found: james.crt
Client's Private Key found: james.key
CA public Key found: ca.crt
tls-auth Private Key found: ta.key
cp: cannot create regular file '/home/pivpn/ovpns/james.ovpn': No such file or directory
chown: cannot access '/home/pivpn/ovpns/james.ovpn': No such file or directory


========================================================
Done! james.ovpn successfully created!
james.ovpn was copied to:
  /home/pivpn/ovpns
for easy transfer. Please use this profile only on one
device and create additional profiles for other devices.
========================================================
```

**Comment by cfcolaco** [comment]
that is known issue and is being discussed in issue #377 
the use of $HOME Variable isn't a proper solution, would solve your specific case but not the problem itself!  

feel free to add your opinion there and to help with that if you want!! =) 

Do you require further assistance with this??

**Comment by cfcolaco** [comment]
Closing issue as per previous comment .. this is beinf considered already!
