### ISSUE TITLE
AUTH FAILED after adding lines to the server.conf

### ISSUE THREAD

**Issue by stocksterfhnw** [pivpn/pivpn#391]
Hey guys

Not sure if this behaviour is correct, but as soon as I added the following configuration to my server.conf file, I could not authenticate my VPN Clients anymore:

```
Sun Oct 22 12:28:27 2017 AUTH: Received control message: AUTH_FAILED
Sun Oct 22 12:28:27 2017 SIGUSR1[soft,auth-failure] received, process restarting
```

All I wanted to do is simply setup up email notification on client connect and disconnect events; for that I added the following lines to the config:

```
client-connect /etc/openvpn/triggeremail.sh
client-disconnect /etc/openvpn/triggeremail.sh
script-security 2
```

Once i remove those lines from the config again, authentication with clients starts to work normally again. Is this by design? Does anybody have an input for me? I would be very grateful.

Regards,

stockster

**Comment by cfcolaco** [comment]
@stocksterfhnw that is an issue to place in the openvpn github page ... not here as that is an out of the box setup that is not related at all with pivpn but with OpenVPN itself ... I would reaaaaallly like to help you with that .. as that seems quite interesting!! but ... neither me or any of the project maintainers are with the time to help with "out of the scope" stuff!! ... I would like indeed to ask you to keep us posted with that... however I will be closing the issue!! 

I am really sorry for that... hope you can understand why I am closing the issue.

**Comment by stocksterfhnw** [comment]
Hi cfcolaco

I fully understand. I raised the same question in the OpenVPN forum. In case I should be able to resolve the issue with the help of the openvpn community I will let you know here.

Regards,

stocksterfhnw

**Comment by cfcolaco** [comment]
Thank you for your understanding @stocksterfhnw.

**Comment by stockster** [comment]
Hello @cfcolaco 

Just wanted to let you know that the mistake concerning this problem was my own fault. There was a linefeed above the #!/bin/bash line, that prevented the script from running correctly. 

Rather stupid ^^

Merry Christmas.

Regards,

stockster
