### ISSUE TITLE
Change WAN IP

### ISSUE THREAD

**Issue by PunkRa1n** [pivpn/pivpn#393]
moin, since I have a new modem, I get a new static WAN IP
Question is, how or where can I change the IP address
If I setup a new device, I must every time edit the ovpn file and change the IP
Any suggestions?

**Comment by redfast00** [comment]
See [the FAQ](https://github.com/pivpn/pivpn/wiki/FAQ#can-i-change-the-hostname-the-ip-address-protocol-or-port-after-the-install).

**Comment by PunkRa1n** [comment]
Thanks, but there isn't a "key" folder in /etc/openvpn/easy-rsa/

**Comment by redfast00** [comment]
Does `/etc/openvpn/easy-rsa/pki/Default.txt` work?

**Comment by PunkRa1n** [comment]
Yes, that worked!!
Thank you!!
