### ISSUE TITLE
Unroutable control packet

### ISSUE THREAD

**Issue by electrodog10** [pivpn/pivpn#395]
# PiVPN Issue Template

## Console output of `curl install.pivpn.io | bash`
```

```

## Console output of `pivpn add` or `pivpn add nopass`
```

```

## Console output of `pivpn debug`
```

```

## Issue
I'm getting an error on my computer of 

> TLS Error: Unroutable control packet received...

My iPhone works great however. It was working just fine on my windows computer until today. 
I regenerated the config/certificate for this computer, and it still doesn't work. 
What do you suggest trying? My computer is running the default OpenVPN client.

**Comment by jellemdekker** [comment]
Have you researched the problem yourself? The first thing that comes up when I google your error is [this website](https://www.ivpn.net/knowledgebase/152/TLS-Error-Unroutable-control-packet-received---How-to-fix.html). Go follow its instructions and see if that works for you.

**Comment by cfcolaco** [comment]
Thanks @jellemdekker 
@electrodog10  Any updates on this?

**Comment by electrodog10** [comment]
I did sync the clocks but that didn't work. I think it has something to do with the school network that I'm on. When I went to another location it worked fine. 

Thanks for your guys's help.
