### ISSUE TITLE
Able to connect to pivpn instance without user profile

### ISSUE THREAD

**Issue by harmanbirdi** [pivpn/pivpn#398]
Hi - I need to know if what I am seeing is a serious bug or openvpn feature.
I have not been able to find the answer anywhere, but I am using virtualized
machines in my situation.  Not sure if this should be posted on openvpn forums,
but since I am using pivpn, I am posting it here.

Here is the scenario:

1. Install pivpn on an instance (in my case I used Ubuntu)
2. Create a user profile on it - say userA
3. If all is well, you can connect to your VPN instance using that profile
from a client like Tunnelblick
4. Create an image of that Ubuntu instance (vmware, virtualbox etc.)
5. Spin up a new instance from the image
6. Now, if you change the IP of the VPN server in your VPN profile file,
you should be able to connect to the new instance of it as well.
7. Login to first instance, and create another user - say userB
8. Get the userB.ovpn file, but change the IP to point to 2nd VPN instance.
9. Import it into your vpn client.
10. You will now be able to successfully connect to the 2nd VPN instance
even though the userB was created on 1st VPN instance.

If you login to your VPN instances, and run <code>pivpn -l</code> you will
see that only the first instance has both names listed.  Followed by this,
if you run <code>pivpn -c</code>, you will see that userB is connected
successfully to 2nd instance, even though their name is not listed.

Why is this happening? If this is a feature of OpenVPN, could someone
explain this behavior to me.

I thought I would somehow need to copy some files between the two instances
to get the user connectivity working from the second instance, but it was
not the case.  I was just doing this for sake of redundancy, when I stumbled
upon this behavior.

**Comment by redfast00** [comment]
Well, they're actually the same instance: as far as I know, OpenVPN only cares about the cryptographic keys that get generated when pivpn is installed. You didn't find a security issue, because if an attacker can image the server you're running OpenVPN on, he can do whatever he wants.

**Comment by harmanbirdi** [comment]
So, what about the entire certificate add and revoke process for a user?  Adding a user on one instance, seems to give you access to the other - with just an IP change. I have not tried what happens when you revoke the user. If it would NOT grant access to both the instances after that, then I suppose this can work as long as you are just adding and revoking certificates from the same instance (just to maintain sanity).
