### ISSUE TITLE
View other servers or devices on the PI network

### ISSUE THREAD

**Issue by planetahuevo** [pivpn/pivpn#4]
Would be possible to allow to see other machines or servers that are on the same network as the PI?

Thanks

**Comment by 0-kaladin** [comment]
you mean when vpn'd in?  I can get to things on my internal network when vpn'd in.  
Or maybe i don't quite understand what you mean.

**Comment by planetahuevo** [comment]
Yes I mean when vpn´d in. :)
I am not sure if there is any configuration needed for this to work or it will work just as soon as you are connected, no matter which IP you get from the openvpn server.

**Comment by 0-kaladin** [comment]
It should work.

**Comment by planetahuevo** [comment]
I just laerned that with openvpn you wont be able to see the other devices on the network, but if you their IPs you can connect to them. Which is good. :)
