### ISSUE TITLE
hash replaced by which?

### ISSUE THREAD

**Issue by zounp** [pivpn/pivpn#40]
Hi
Maybe it is a good idea to replace the hash command by the which command ( 2x ).
    if which lsb_release &>/dev/null; then
and
    if which ufw &>/dev/null; then
If I do man hash I get a man (3) manpage so it does not seem to be a regular command unlike which.
Regards,
Zounp

**Comment by 0-kaladin** [comment]
I chose hash based on some of the information here:
http://stackoverflow.com/questions/592620/check-if-a-program-exists-from-a-bash-script
