### ISSUE TITLE
dhcpcd config bricks network on cloud server

### ISSUE THREAD

**Issue by DuBistKomisch** [pivpn/pivpn#400]
Hey, thanks for the great script, worked perfectly for me except for this.

I ran it on a digital ocean droplet running Ubuntu 16.04, and it hits `avoidStaticIPv4Ubuntu` and tells me it won't configure a static IP. Despite that, the `dhcpcd` package was installed anyway, and its default config bricked my network. I managed to fix it by sshing in during the 10 seconds between the network coming up and `dhcpcd` bricking it to run `systemctl disable dhcpcd` and power cycling it again.

I get that it's a script for noobs, but messing with the network config at all seems like a terrible idea to me. Surely it'll already be configured to use DHCP by default, and you should just tell people to set a static IP on their router? That's the only way to avoid IP conflicts on the network anyway.

Regardless... would appreciate if it didn't enable (or ideally install) dhcpcd if not configuring a static IP.

**Comment by cfcolaco** [comment]
huumm ... something went wrong there! =S I have tested the script plenty of times in AWS EC2 instances and never broke the networking ... tbh never noticed that behavior ... worth looking into it.

**Comment by DuBistKomisch** [comment]
Yeah, you'd think it wouldn't do much by default, but I guess DO's network config is more fragile than AWS. Hard to really figure out what's going on since I get kicked off when it happens.

**Comment by cfcolaco** [comment]
yes, it can work differently in both providers, but now I am aware and know where to look when testing.

**Comment by cahl** [comment]
Just ran into this as well. Ubuntu 16.04 VM running on xenserver 6.5.

**Comment by 4s3ti** [comment]
will close this since its very old and might not be happening again. 
Reopen or open up again if seeing any related bug.
