### ISSUE TITLE
Question about IP Address

### ISSUE THREAD

**Issue by toshibochan** [pivpn/pivpn#401]
Thanks for great VPN!
I have question! 
If the internet IP address change how I can update the server to the new IP address?

Thanks

**Comment by cfcolaco** [comment]
Just change .ovpn files to match the new IP address ... or use a dynamic dns and change the .ovpn files to look for your ddns domain. 

https://github.com/pivpn/pivpn/wiki/FAQ#my-isp-doesnt-give-me-a-static-external-ip-address-so-my-servers-ip-address-keeps-changing
