### ISSUE TITLE
NextcloudPi and PiVPN

### ISSUE THREAD

**Issue by MarkEngel** [pivpn/pivpn#403]
Hi all,

I set up the NextcloudPi and it is up and running. 
I red in the wiki that pi-hole is working fine with pivpn on the same raspberry. Is this also with NextcloudPi?

**Comment by cfcolaco** [comment]
I don't see any reason why it should not work. 
however never used nexcloudPi.

**Comment by MarkEngel** [comment]
Allright, i will give it a try tomorrow.

Thnx

**Comment by cfcolaco** [comment]
@MarkEngel any updates?

**Comment by MarkEngel** [comment]
sorry, wasn't aware that you wanted a update.

yes it worked, very easy! 

I took the NexcloudPi image, updated it and did the install and than i did the curl from pivpn.
everything worked fine till i installed pi-hole.

at this moment i start over and see what i did wrong. keep you updated

**Comment by MarkEngel** [comment]
Could not find the sollution on short term. will do this in 1 a 2 weeks.
First trying some other setup of server (vps) and cliennts
