### ISSUE TITLE
FEATURE REQUEST: Change Hostname

### ISSUE THREAD

**Issue by marcdraco** [pivpn/pivpn#404]
Not quite sure how to set this up, but is there any way to either re-run the installer without having to sit for 1/2 hour waiting for the Diffie-Hellman (?) primes to be produced?

Specifically, I've **_twice_** fudged up my Dynamic DNS settings and it'd be really helpful if we could do this bit without having to dive back in and start over.

For example:

If I enter, mydomain.ddns.com (when it should be ".net") I have to go through the whole process again. It's particularly bad for beginners and sleepy admins who aren't paying sufficient attention.

If this is connected to the DH keys, then obviously that's an issue, but if that's the case, a final "ARE YOU SURE" check might be an idea.

I seem to have similarly goofed my outbound DNS forwarder - I've pointed it to the PiHole but that's not working either.

These are _minor_ issues of course, but if if were possible to fix them post install that would be terrific.

Thanks

**Comment by redfast00** [comment]
https://github.com/pivpn/pivpn/wiki/FAQ#can-i-change-the-hostname-the-ip-address-protocol-or-port-after-the-install

**Comment by leewc** [comment]
Updating the wiki link for others:

If using WireGuard: https://github.com/pivpn/pivpn/wiki/WireGuard#how-do-i-change-the-public-ipdns-name-of-the-pivpn-after-the-install

If using OpenVPN: https://github.com/pivpn/pivpn/wiki/OpenVPN#how-do-i-change-the-public-ipdns-name-of-the-pivpn-after-the-install
