### ISSUE TITLE
Can't find /etc/openvpn/easy-rsa/keys/Default.txt to change IP address.

### ISSUE THREAD

**Issue by gmarchi** [pivpn/pivpn#405]
As i mentioned in the title, i was searching for the config file to change IP address (no hostname for me) of my vpn server, but i was not able to find the path shown under FAQs. In particular i have no "keys" directory. This is the content of my "/etc/openvpn/easy-rsa" directory:
```
-rw-r--r-- 1 root root  2415 Nov 21  2016 ChangeLog
-rw-r--r-- 1 root root  1305 Nov 21  2016 COPYING.md
drwxr-xr-x 2 root root  4096 Dec  3  2016 doc
-rwxr-xr-x 1 root root 35253 Nov 21  2016 easyrsa
-rw-r--r-- 1 root root 18093 Nov 21  2016 gpl-2.0.txt
-rw-r--r-- 1 root root  4560 Nov 21  2016 openssl-1.0.cnf
drwx------ 6 root root  4096 Nov  1 06:46 pki
-rw-r--r-- 1 root root  3350 Nov 21  2016 README.quickstart.md
-rw-r--r-- 1 root root   265 Oct 24 16:29 vars
-rw-r--r-- 1 root root  8126 Nov 21  2016 vars.example
drwxr-xr-x 2 root root  4096 Nov 21  2016 x509-types
```
Can anyone help me?

**Comment by d0nlab** [comment]
Is it under INDEX.txt?

pi@pilab:/opt/pivpn $ cat makeOVPN.sh 
#!/bin/bash
# Create OVPN Client
# Default Variable Declarations
DEFAULT="Default.txt"
FILEEXT=".ovpn"
CRT=".crt"
KEY=".key"
CA="ca.crt"
TA="ta.key"
INDEX="/etc/openvpn/easy-rsa/pki/index.txt"
INSTALL_USER=$(cat /etc/pivpn/INSTALL_USER)

**Comment by d0nlab** [comment]
Its here

root@pilab:/etc/openvpn/easy-rsa/pki# cat Default.txt 
client
dev tun
proto udp
remote XXX.XXX.XXX.XXX 1194

**Comment by gmarchi** [comment]
Thank you :) I think someone should update the FAQs in the Wiki.

> Il giorno 06 nov 2017, alle ore 22:30, d0nlab <notifications@github.com> ha scritto:
> 
> Its here
> 
> root@pilab:/etc/openvpn/easy-rsa/pki# cat Default.txt 
> client
> dev tun
> proto udp
> remote XXX.XXX.XXX.XXX 1194
> 
>

**Comment by cfcolaco** [comment]
@gmarchi @d0nlab Thank you!! will update the FAQ as soon as I can breathe a bit! xD

**Comment by cfcolaco** [comment]
Wiki Updated with the correct information. 

once again, Thank you @gmarchi and @d0nlab 

Closing issue!
