### ISSUE TITLE
after installation how to change the encryption strength

### ISSUE THREAD

**Issue by xCozmox** [pivpn/pivpn#406]
Hello, 
I installed pivpn on my Raspbian Stretch. I used the 2048-bit encryption. I was wondering if it is possible to change it afterwards (to 4096),? What is the best option to do so? Do I have to un-install pivpn and re-install? Or any other possibility?

Thanks a lot,
xCozmox

**Comment by redfast00** [comment]
Yes, it will be the easiest to just reinstall.
