### ISSUE TITLE
No DNS configuration step. 

### ISSUE THREAD

**Issue by rmccarthytt** [pivpn/pivpn#407]
Hi,

When I run the install I do not see any window about DNS entries. 
I'm following this http://kamilslab.com/2017/01/22/how-to-turn-your-raspberry-pi-into-a-home-vpn-server-using-pivpn/

This was released in jan of this year but I have seen others since that have been written since then that show the same steps. 

How do I fix this or is this feature change in the recent version?

**Comment by fletchto99** [comment]
I'm having the same issue. @rmccarthytt did you manage to figure it out?

**Comment by dcsooner** [comment]
I am having the same issue as well. I installed it on my RPi 3 a month ago with no problems, but I tried installing on a new RPi3 yesterday, and it will not work.

**Comment by foliveira3101** [comment]
i am too

**Comment by rmccarthytt** [comment]
No, I haven't. Can we have a dev comment on this.

**Comment by orazioedoardo** [comment]
Maybe the script is exiting on [confOVPN](https://github.com/pivpn/pivpn/blob/master/auto_install/install.sh#L1109) or above. Are you able to tell? Check if there are some error messages that could result in a fatal error.

**Comment by rmccarthytt** [comment]
I can try soon. But I did finish the install without errors., It just didn't work.

**Comment by 4s3ti** [comment]
Old thread, lack of details. 
closing.
