### ISSUE TITLE
IP not changing

### ISSUE THREAD

**Issue by Zentrik** [pivpn/pivpn#41]
I installed pi vpn and everything is working except when I go on ipleak.net it shows my real ip, without the need of webrtc

**Comment by Zentrik** [comment]
Should it be showing my real public ip seeing me pi is at my home?

**Comment by Zentrik** [comment]
Now i have dns leaks with tunnelblick but not openvpn android

**Comment by 0-kaladin** [comment]
installing openvpn doesn't suddenly mask your IP.  the IP of your home is the IP the openvpn server is coming from.  when you are NOT home you will have an IP from the place you are at.  if you then connect to your vpn then ipleak.net should show you from the IP you normally see at your house.  
To try to say this a different way, your IP will not change when you are home and when you are home you do not need to connect to the vpn.  It is when you are NOT home you will see one IP from ipleak.net and then connect to your vpn and see your HOME IP.  that is the point as you are now tunneled to your home network.

your last statement also makes little sense so you'd have to elaborate on what you mean by "dns leaks". and also provide details of what you are using for dns. etc.

**Comment by Zentrik** [comment]
OK thanks for explaining, and by dos leaks i mean it shows my ISP's DNS instead of google's DNS, which i chose on the page where it asked for the DNS

**Comment by shanep2300** [comment]
I haven't tried installing pivpn, but I think it might help me out with my current situation. I have OpenVPN with PIA on my Pi. Running torrent checks on the pi show that my ip is from PIA, but when I go to ipleak.net on the pi, my real ip is shown at the top. I'm connected through wifi. I'm thinking it's something to do with openvpn, so will running pivpn fix the issue...?

**Comment by 0-kaladin** [comment]
@shanep2300 in short, no.  PIA is a paid for vpn service where your vpn endpoint is a server somewhere out on the internet.  That is why you shouldn't get your private IP when using that.  PiVPN makes the server be at your house.  So you will have your home IP.  This protects you when you are NOT at home as it will tunnel everything through your home network.  On the other hand, you seem to want to hide from your ISP so this won't help.  UNLESS you install pivpn on a server that is NOT at your house.  then you get the same benefits of PIA.  That is why i made sure pivpn supported installs on ubuntu and debian and not just raspbian, so you can install on a cloud server (amazon for ex).
