### ISSUE TITLE
network configuration for clients

### ISSUE THREAD

**Issue by kakitogit** [pivpn/pivpn#410]
Hi

I just installed pivpn, the script installation was so easy, everything is running fine, I can connect to my vpn using my mobile or my laptop from the internet, but when doing this i´m not able to connect with my Kodi via upnp (when connected directly from my lan i´m able to do so with VLC and i´m able to view all the Kodi stuff), why i can´t contact with my kodi library?, i´m able to ping, ssh.... to my raspberry but can´t use the upnp stuff as from the lan, could it be because my clients are receiving an IP from a different ip-range? (my lan is 192.168.1.X and when connecting from vpn i get 10. ...) it´s needed to open any port? any forwarding rule? where/how could i do that?; maybe i could assing to my vpn clients the 192.168.1.X ip-range? where could i configure that?

Thanks a lot.

**Comment by d0nlab** [comment]
The feature you want is issue #45 - option for bridge mode

**Comment by kakitogit** [comment]
hi, thanks... i will check it.

**Comment by cfcolaco** [comment]
Thanks @d0nlab will be closing the issue then as this needs Bridge mode #45 

@kakitogit you can track it there .. however, don't expect it to come anytime soon =/ 

thank you!! and sorry for not solving your issue.
