### ISSUE TITLE
No Client Internet Connectivity

### ISSUE THREAD

**Issue by ashdavely** [pivpn/pivpn#411]
Hello-

I installed pivpn on a Pi3 that is running Stretch lite. Nothing else installed. Only other config change was to enable ssh. I selected Google as my dns provider during installation.

I'm able to connect to it via the internet and an android phone and see my network. I can connect to the pi using the local ip address via ssh. 

I am not able to connect to the internet through it which was my intended purpose. Ipconfig shows the gateway as blank. I am not sure if this a client or server issue. I am using the client from openvpn.net in Windows 10.

I've seen a handful of posts about internet connectivity not working here which have confused me more. I have tried uninstalling and reinstalling as someone suggested but still the same issue. Everything looks correct. I will post my config info below. 

rules.v4

 ```
Generated by iptables-save v1.6.0 on Fri Nov 17 03:41:54 2017
*nat
:PREROUTING ACCEPT [1:40]
:INPUT ACCEPT [1:40]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
-A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE
COMMIT
# Completed on Fri Nov 17 03:41:54 2017
# Generated by iptables-save v1.6.0 on Fri Nov 17 03:41:54 2017
*filter
:INPUT ACCEPT [12502:1038592]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [8955:989701]
COMMIT
# Completed on Fri Nov 17 03:41:54 2017
```
 
Server.Conf

```
dev tun
proto udp
port 1194
ca /etc/openvpn/easy-rsa/pki/ca.crt
cert /etc/openvpn/easy-rsa/pki/issued/server_heZeF96mIC1zngmf.crt
key /etc/openvpn/easy-rsa/pki/private/server_heZeF96mIC1zngmf.key
dh /etc/openvpn/easy-rsa/pki/dh2048.pem
topology subnet
server 10.8.0.0 255.255.255.0
# server and remote endpoints
ifconfig 10.8.0.1 10.8.0.2
# Add route to Client routing table for the OpenVPN Server
push "route 10.8.0.1 255.255.255.255"
# Add route to Client routing table for the OPenVPN Subnet
push "route 10.8.0.0 255.255.255.0"
# your local subnet
push "route 0.0.0.0 "
# Set your primary domain name server address for clients
push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 8.8.4.4"
# Override the Client default gateway by using 0.0.0.0/1 and
# 128.0.0.0/1 rather than 0.0.0.0/0. This has the benefit of
# overriding but not wiping out the original default gateway.
push "redirect-gateway def1"
client-to-client
keepalive 10 120
remote-cert-tls client
tls-version-min 1.2
tls-auth /etc/openvpn/easy-rsa/pki/ta.key 0
cipher AES-256-CBC
auth SHA256
comp-lzo
user nobody
group nogroup
persist-key
persist-tun
crl-verify /etc/openvpn/crl.pem
status /var/log/openvpn-status.log 20
status-version 3
log /var/log/openvpn.log
verb 1
# Generated for use by PiVPN.io
```

Anyone have an idea how I can resolve?

**Comment by jbutler992** [comment]
Same issue using iOS and Ubuntu clients. My config is similar

**Comment by jbutler992** [comment]
Seems related to issue #380 has anyone found a resolution?

**Comment by ashdavely** [comment]
I have not found a solution. I've blown away my SD card for the Pi a few times now and started over. 

Now I am not able to connect to the Pi at all. I get a TLS failed message. It was at least able to connect before.

**Comment by ashdavely** [comment]
From a Windows 10 client I can use the route change 0.0.0.0 mask 0.0.0.0 <server ip> here to manually add a gateway. I am not sure why it won't add it automatically. Still looking for an answer.

**Comment by shanghaix** [comment]
Same problem here after installing pippin on a fresh install of stretch. Guess the only way to have it working is to go back to Jessie right now..

**Comment by cfcolaco** [comment]
@jbutler992 it seems to me that this issue as nothing to do with the issue you mentioned as that issue was related to an existing docker setup which was causing issues with iptables rules. 

@ashdavely For windows users please make sure you are running OpenVPN with right click and run as administrator ... otherwise, it won't push the routes! 

Try that and then come back with feedback please... I might take a while to come back and reply .. but My time is quite short righ now.

**Comment by cfcolaco** [comment]
No answer was given assuming resolved. 
please ask if you need further help

**Comment by kcha** [comment]
I am running into the same issue with no client internet connectivity. I have a fresh install of PiVPN on a Pi Zero W with Stretch Lite. UFW is installed but currently disabled. Dynamic DNS is set up and port forwarding enabled on my router. I can successfully connect to the VPN from my Android phone over cellular network. From the phone I can SSH into the Pi and `ping google.com` works. However, everywhere else there is no internet availability (e.g. apps, web browser, etc.).

From reading other threads regarding this issue, I tried calling `sudo iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o wlan0 -j MASQUERADE`; but it doesn't make any difference in my case.

Any help would be appreciated! Would love to resolve this as my next step is to pair it with Pihole. Thanks for this great package!

server.conf:
```
dev tun
proto udp
port 1129
ca /etc/openvpn/easy-rsa/pki/ca.crt
cert /etc/openvpn/easy-rsa/pki/issued/server_5SR646nOZ52B1bt2.crt
key /etc/openvpn/easy-rsa/pki/private/server_5SR646nOZ52B1bt2.key
dh /etc/openvpn/easy-rsa/pki/dh2048.pem
topology subnet
server 10.8.0.0 255.255.255.0
# Set your primary domain name server address for clients
push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 8.8.4.4"
# Override the Client default gateway by using 0.0.0.0/1 and
# 128.0.0.0/1 rather than 0.0.0.0/0. This has the benefit of
# overriding but not wiping out the original default gateway.
push "redirect-gateway def1"
client-to-client
keepalive 10 120
remote-cert-tls client
tls-version-min 1.2
tls-auth /etc/openvpn/easy-rsa/pki/ta.key 0
cipher AES-256-CBC
auth SHA256
comp-lzo
user nobody
group nogroup
persist-key
persist-tun
crl-verify /etc/openvpn/crl.pem
status /var/log/openvpn-status.log 20
status-version 3
syslog
verb 3
# Generated for use by PiVPN.io
```


sudo iptables-save:
```
# Generated by iptables-save v1.6.0 on Sat Feb 24 00:59:44 2018
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
-A POSTROUTING -s 10.8.0.0/24 -o wlan0 -j MASQUERADE
COMMIT
# Completed on Sat Feb 24 00:59:44 2018
# Generated by iptables-save v1.6.0 on Sat Feb 24 00:59:44 2018
*filter
:INPUT ACCEPT [20:2098]
:FORWARD ACCEPT [4:290]
:OUTPUT ACCEPT [16:2344]
COMMIT
# Completed on Sat Feb 24 00:59:44 2018
```

sudo ufw status verbose:
```
Status: inactive
```

resolv.conf:
```
# Generated by resolvconf
nameserver 8.8.8.8
nameserver 8.8.4.4
```

pivpn debug:
```
::: Generating Debug Output
:::					:::
::		PiVPN Debug		 ::
:::					:::
::	Latest Commit			 ::
:::					:::
commit 25aaf24c893175894d0a54d159a10fbb74b6b463
Merge: abdce6c c414172
Author: redfast00 <redfast00@gmail.com>
Date:   Wed Feb 21 17:36:09 2018 +0100

    Merge remote-tracking branch 'origin/test'
:::					:::
::	Recursive list of files in	 ::
::	/etc/openvpn/easy-rsa/pki	 ::
:::					:::
/etc/openvpn/easy-rsa/pki/:
ca.crt
crl.pem
Default.txt
dh2048.pem
index.txt
index.txt.attr
index.txt.attr.old
index.txt.old
issued
android.ovpn
private
serial
serial.old
ta.key

/etc/openvpn/easy-rsa/pki/issued:
android.crt
server_5SR646nOZ52B1bt2.crt

/etc/openvpn/easy-rsa/pki/private:
ca.key
android.key
server_5SR646nOZ52B1bt2.key
:::					:::
::	Output of /etc/pivpn/*		 ::
:::					:::
:: START /etc/pivpn/DET_PLATFORM ::
Raspbian
:: END /etc/pivpn/DET_PLATFORM ::
:: START /etc/pivpn/INSTALL_PORT ::
1129
:: END /etc/pivpn/INSTALL_PORT ::
:: START /etc/pivpn/INSTALL_PROTO ::
udp
:: END /etc/pivpn/INSTALL_PROTO ::
:: START /etc/pivpn/INSTALL_USER ::
pi
:: END /etc/pivpn/INSTALL_USER ::
:: START /etc/pivpn/NO_UFW ::
1
:: END /etc/pivpn/NO_UFW ::
:: START /etc/pivpn/pivpnINTERFACE ::
wlan0
:: END /etc/pivpn/pivpnINTERFACE ::
:::					:::
:: /etc/openvpn/easy-rsa/pki/Default.txt ::
:::					:::
client
dev tun
proto udp
remote ***** 1129
resolv-retry infinite
nobind
persist-key
persist-tun
key-direction 1
remote-cert-tls server
tls-version-min 1.2
verify-x509-name server_5SR646nOZ52B1bt2 name
cipher AES-256-CBC
auth SHA256
comp-lzo
verb 3
:::					:::
::	Debug Output Complete		 ::
:::					:::
:::
::: Debug output completed above.
::: Copy saved to /tmp/debug.txt
:::
```
