### ISSUE TITLE
Is this working in China, Great Firewall of China?

### ISSUE THREAD

**Issue by frdteknikelektro** [pivpn/pivpn#413]
Hi, i'm going to china, and I perfectly success setup pivpn using no-ip free dns, but is this going to working in China?
I know that this is not technical issue, but i think there is some other people like me that questioning the same.

Thanks.

**Comment by d0nlab** [comment]
Gave my friend an .ovpn to use while in China. Worked flawlessly. He kept is iPhone connected the whole week he was there.

**Comment by frdteknikelektro** [comment]
Awesome! Then this should be closed. Thank you very much!

**Comment by InnovativeInventor** [comment]
I gave it to my friend also when he went to China, and it didn't work. Try
setting up obfsproxy if it doesn't work.

**Comment by frdteknikelektro** [comment]
Okay thanks. What did u use for dns? just wondering. @InnovativeInventor .

**Comment by d0nlab** [comment]
Hi everyone,

Just realized I failed to provide my setup to understand why it works in China. 

1194 is blocked

The OVPN I gave my friend to use was configured to connect to my pi over TCP 443. 

I run a second instance of pivpn server listening over 443. 

On my phone I have two OVPNs one for each port.  So if 1194 doesn’t work I switch to 443. 

For my friend visiting China I just have him the 443 ovpn. 

James

**Comment by InnovativeInventor** [comment]
Yeah. Random ports work as well. I used pivpn for my dns, but it really doesn’t matter. You could use 8.8.8.8 (google’s public dns servers) or Norton’s servers if you want some malware protection. It all goes through the VPN if things are configured properly.

**Comment by frdteknikelektro** [comment]
@d0nlab Okay thanks, i've already setup second instance openvpn running on TCP 443. Hopefully it will work. I let you guys know. :+1:

**Comment by frdteknikelektro** [comment]
Hello guys!
I'm now in Guangzhou. PiVPN is working. Work in UDP port 1194 and TCP 443 also. I'm using China Unicom SIM Card, and also work with Apartment WiFi.

But there is some problem. For the first time it cannot connect. I wonder why and looking for the problem. What I found is that ddns domain is blocked in here. So I looking my domain ip using some ip site info. Then change the domain in opvn file to global ip.
And it works!

Thank you guys. Hope this can help others!

**Comment by d0nlab** [comment]
Good to know it’s working on both ports. Are you using a free dynamic DNS service like no-ip.com?

**Comment by frdteknikelektro** [comment]
Yes I'm using service from no-ip.com
But it didn't work.
The workaround is I need to change hostname using global ip. But I need to check my global raspi up using site checker, checking my ddns.net domain. Hha

**Comment by d0nlab** [comment]
I use no-ip as well. My router has a built in dynamic dns updater preconfigured for use with no-ip which keeps my host name up to date. Another option is duck dns.
