### ISSUE TITLE
Possible conflict between ufw and iptables-persistent

### ISSUE THREAD

**Issue by orazioedoardo** [pivpn/pivpn#414]
I've noticed this during the installation: if you have `ufw` installed/enabled the vpn is not going to work even after a reboot because `iptables-persistent` interferes with `ufw` (I guess) and doesn't let `ufw` apply new rules (for example allow from 1194/udp and allow from vpn network), result of course is that the port is blocked.

As a workaround i just did `sudo ufw disable` and `sudo ufw enable`. It worked but rules did not stick after reboot. Basically `sudo ufw status verbose` tells you that the rules are in place but `sudo iptables -vnL` does not (they are not present in the chain).

The actual solution was to uninstall `iptables-persistent` and it's depencency: `sudo apt remove iptables-persistent` and `sudo apt autoremove`.

Hope it helps, I'm running Raspbian Stretch.

**Comment by zsamenfeld-encon** [comment]
Thank you a million times over, you really helped me on a new 16.04 I was really having issues with.

**Comment by zsamenfeld-encon** [comment]
Alright after uninstalling iptables-persistent I couldn't use the VPN anymore and I had to use issue #182 to help me get everything working again. I don't know the drawbacks of using /etc/rc.local for such a task but it works for now so I'm happy.

**Comment by orazioedoardo** [comment]
There shouldn’t be any drawbacks of using /etc/rc.local to start the service, however the proper way to enable a service (iptables-persistent in this case) is: `sudo systemctl start iptables-persistent`
For me I only keep ufw installed and let him apply the rules.

**Comment by zsamenfeld-encon** [comment]
But having `iptables-persistent` was what was causing me issues originally if you read the thread.

**Comment by 4s3ti** [comment]
We need to check and confirm how PiVPN is handling ufw.

**Comment by aldencolerain** [comment]
@4s3ti 
I just did a fresh install on a new rasberry pi and ran into this problem.  I followed these instructions and it fixed my issue.  The only think I did out of the ordinary is ran the install script twice, something went wrong the first time and pvpn was not on the path.

https://github.com/pivpn/pivpn/issues/182#issuecomment-272720340

**Comment by adsbenham** [comment]
This confused the heck out of me for most of the day, because some of my ufw rules were actioned at power up but the openvpn rules weren't!  Strangely only IPv4 was affected - IPv6 rules were all actioned OK.
iptables-persistent has been given the heave-ho.

**Comment by SignumPL** [comment]
Same issue here. Removing `iptables-peristent` helped.

**Comment by h2oboy** [comment]
thx life saver!

**Comment by 4s3ti** [comment]
@orazioedoardo wasn't this fixed already?

**Comment by distantorigin** [comment]
This has not been fixed.

Keep in mind that you can add raw iptables rules in /etc/ufw/after.rules and /etc/ufw/before.rules, which will cause ufw to add these rules after or before loading all other rules you've set on the frontend. This is what I did, rather than using /etc/rc.local.

**Comment by distantorigin** [comment]
Looking through the installer script further reveals that this does indeed exist, but for some reason, wasn't passed on my pi. Perhaps the sudo in the status inactive check needs a 'bash -c'? I haven't done any testing -- and don't plan to -- but this is my first guess.

**Comment by orazioedoardo** [comment]
> > @orazioedoardo wasn't this fixed already?
> 
> Actually I don't remember, however this should be easy to fix. Just don't install `iptables-persistent` by default but do so only if ufw is not installed.

@distantorigin Just did this [here](https://github.com/pivpn/pivpn/commit/a561607272226ac50cd9bc687d37f5701e0b3550#diff-299d9b30c952310aace4aba77c698874R439-R440) (install iptables-persistent when UFW is not used/installed).
