### ISSUE TITLE
Can`t get PIVPN to work on the latest version of raspberry pi

### ISSUE THREAD

**Issue by TheExtremeNerd** [pivpn/pivpn#415]
Hello,

I really love this software and its been working great for until now.

I can succefully create and import an open vpn profile but when I try to connect on my iPhone 7 running 11.2 beta 4 with the newest version on open vpn app I get an error like this: OPENVPN error: PolarSSL: error parsing config private key: PKCS5 - Requested encryption or digest alg not available

I have tried to manually install an open vpn server but I get other error with that.

I have also double and tripled checked that the port is open.

Thanks for reading and hopefully someone can help.

I have inclueded a pastebin of the log file

[pastebin.com/xipBQ62Q](https://pastebin.com/xipBQ62Q)

**Comment by orazioedoardo** [comment]
Follow [this](https://github.com/pivpn/pivpn/issues/364#issue-260195914) suggestion, should work.

**Comment by TheExtremeNerd** [comment]
Awesome I will try that thanks so much for the speedy response!

**Comment by cfcolaco** [comment]
@TheExtremeNerd Will assume your issue is solved.... if not please ask for reopen.
