### ISSUE TITLE
Unable to connect from any client after update

### ISSUE THREAD

**Issue by ttravis72** [pivpn/pivpn#417]
After an update and upgrade I restarted my pi and was unable to connect to my vpn from any of my devices. I double checked and the port is being forwarded correctly. I have no problems  with ssh to my pi. 

## Console output of `pivpn debug`
```
:::					:::
::		PiVPN Debug		 ::
:::					:::
::	Latest Commit			 ::
:::					:::
commit 3c764db9b6d670c8bf9eae3ad94f1dbd570043c7
Merge: 6ce39bf fbec57d
Author: redfast00 <redfast00@users.noreply.github.com>
Date:   Thu Jun 29 13:32:14 2017 +0200

    Merge pull request #292 from cfcolaco/master
    
    changed to new openvpn repos
:::					:::
::	Recursive list of files in	 ::
::	/etc/openvpn/easy-rsa/pki	 ::
:::					:::
/etc/openvpn/easy-rsa/pki/:
ca.crt
crl.pem
Default.txt
dh2048.pem
firestick.ovpn
ghome.ovpn
index.txt
index.txt.attr
index.txt.attr.old
index.txt.old
ironthrone.ovpn
issued
private
rlatpop.ovpn
rphone.ovpn
serial
serial.old
ta.key
txlaptop.ovpn
tlaptop1.ovpn
tlaptop.ovpn
tphone.ovpn
ttablet.ovpn
user1.ovpn

/etc/openvpn/easy-rsa/pki/issued:
firestick.crt
ghome.crt
ironthrone.crt
rlatpop.crt
rphone.crt
server.crt
talaptop.crt
tlaptop1.crt
tlaptop.crt
tphone.crt
ttablet.crt
user1.crt

/etc/openvpn/easy-rsa/pki/private:
ca.key
firestick.key
ghome.key
ironthrone.key
rlatpop.key
rphone.key
server.key
talaptop.key
tlaptop1.key
tlaptop.key
tphone.key
ttablet.key
user1.key
:::					:::
::	Output of /etc/pivpn/*		 ::
:::					:::
:: START /etc/pivpn/DET_PLATFORM ::
Raspbian
:: END /etc/pivpn/DET_PLATFORM ::
:: START /etc/pivpn/INSTALL_PORT ::
11920
:: END /etc/pivpn/INSTALL_PORT ::
:: START /etc/pivpn/INSTALL_PROTO ::
udp
:: END /etc/pivpn/INSTALL_PROTO ::
:: START /etc/pivpn/INSTALL_USER ::
pi
:: END /etc/pivpn/INSTALL_USER ::
:: START /etc/pivpn/NO_UFW ::
1
:: END /etc/pivpn/NO_UFW ::
:: START /etc/pivpn/pivpnINTERFACE ::
eth0
:: END /etc/pivpn/pivpnINTERFACE ::
:: START /etc/pivpn/REVOKE_STATUS ::
1
:: END /etc/pivpn/REVOKE_STATUS ::
:::					:::
:: /etc/openvpn/easy-rsa/pki/Default.txt ::
:::					:::
client
dev tun
proto udp
remote *myip* 11920
resolv-retry infinite
nobind
persist-key
persist-tun
key-direction 1
remote-cert-tls server
tls-version-min 1.2
verify-x509-name server name
cipher AES-256-CBC
auth SHA256
comp-lzo
verb 1
:::					:::
::	Debug Output Complete		 ::
:::					:::

```

ifconfig output:

eth0 Link encap:Ethernet HWaddr b8:27:eb:dd:29:28
inet addr: Bcast: Mask:255.255.255.0
inet6 addr: fe80::f01:6eda:69a3:db4d/64 Scope:Link
UP BROADCAST RUNNING MULTICAST MTU:1500 Metric:1
RX packets:16457 errors:0 dropped:53 overruns:0 frame:0
TX packets:7378 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:1000
RX bytes:10897212 (10.3 MiB) TX bytes:693304 (677.0 KiB)

lo Link encap:Local Loopback
inet addr:127.0.0.1 Mask:255.0.0.0
inet6 addr: ::1/128 Scope:Host
UP LOOPBACK RUNNING MTU:65536 Metric:1
RX packets:334 errors:0 dropped:0 overruns:0 frame:0
TX packets:334 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:1
RX bytes:33076 (32.3 KiB) TX bytes:33076 (32.3 KiB)

tun0 Link encap:UNSPEC HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
inet addr: P-t-P: Mask:255.255.255.0
inet6 addr: fe80::671a:c980:2af3:4b72/64 Scope:Link
UP POINTOPOINT RUNNING NOARP MULTICAST MTU:1500 Metric:1
RX packets:0 errors:0 dropped:0 overruns:0 frame:0
TX packets:28 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:100
RX bytes:0 (0.0 B) TX bytes:1344 (1.3 KiB)

wlan0 Link encap:Ethernet HWaddr b8:27:eb:88:7c:7d
inet addr: Bcast: Mask:255.255.255.0
inet6 addr: fe80::94c9:cc9a:b48d:ec51/64 Scope:Link
UP BROADCAST RUNNING MULTICAST MTU:1500 Metric:1
RX packets:5324 errors:0 dropped:38 overruns:0 frame:0
TX packets:2890 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:1000
RX bytes:499641 (487.9 KiB) TX bytes:234565 (229.0 KiB)

iptables -t nat -S output:

-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT
-A POSTROUTING -s /24 -o eth0 -j MASQUERADE

iptables -S output:

-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT

**Comment by orazioedoardo** [comment]
Post the output of `sudo cat /var/log/openvpn.log` and, if you can, the log from a client after a failed connection (remember to hide personal information).

**Comment by ttravis72** [comment]
Mon Nov 13 20:50:30 2017 OpenVPN 2.3.4 arm-unknown-linux-gnueabihf [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [MH] [IPv6] built on Jun 27 2017
Mon Nov 13 20:50:30 2017 library versions: OpenSSL 1.0.1t  3 May 2016, LZO 2.08
Mon Nov 13 20:50:30 2017 Control Channel Authentication: using '/etc/openvpn/easy-rsa/pki/ta.key' as a OpenVPN static key file
Mon Nov 13 20:50:30 2017 TUN/TAP device tun0 opened
Mon Nov 13 20:50:30 2017 do_ifconfig, tt->ipv6=0, tt->did_ifconfig_ipv6_setup=0
Mon Nov 13 20:50:30 2017 /sbin/ip link set dev tun0 up mtu 1500
Mon Nov 13 20:50:30 2017 /sbin/ip addr add dev tun0  broadcast 
Mon Nov 13 20:50:30 2017 GID set to nogroup
Mon Nov 13 20:50:30 2017 UID set to nobody
Mon Nov 13 20:50:30 2017 UDPv4 link local (bound): [undef]
Mon Nov 13 20:50:30 2017 UDPv4 link remote: [undef]
Mon Nov 13 20:50:30 2017 Initialization Sequence Completed

**Comment by orazioedoardo** [comment]
Seems ok bu I’m actually sure, try these steps.

1) Enable openvpn autostart: `sudo systemctl enable openvpn`
2) Restart openvpn: `sudo systemctl restart openvpn`
3) Check if openvpn is actually listening: `sudo netstat -antup | grep 11920`, if it’s not empty, then openvpn is running.
4) Try to connect from a client

If it still does not work describe exactly the error reported by the client.

**Comment by ttravis72** [comment]
It looks like ovpn is not listening which would make sense since there is no error from the client just a timeout disconnect. 

sudo netstat -antup | grep 11920 :

dp        0      0 0.0.0.0:11920           0.0.0.0:*                           24610/openvpn   

log: 

Sat Nov 25 14:15:56 2017 OpenVPN 2.3.4 arm-unknown-linux-gnueabihf [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [MH] [IPv6] built on Jun 27 2017
Sat Nov 25 14:15:56 2017 library versions: OpenSSL 1.0.1t  3 May 2016, LZO 2.08
Sat Nov 25 14:15:56 2017 NOTE: your local LAN uses the extremely common subnet address .  Be aware that this might create routing conflicts if you connect to the VPN server from public locations such as internet cafes that use the same subnet.
Sat Nov 25 14:15:56 2017 Control Channel Authentication: using '/etc/openvpn/easy-rsa/pki/ta.key' as a OpenVPN static key file
Sat Nov 25 14:15:56 2017 TUN/TAP device tun0 opened
Sat Nov 25 14:15:56 2017 do_ifconfig, tt->ipv6=0, tt->did_ifconfig_ipv6_setup=0
Sat Nov 25 14:15:56 2017 /sbin/ip link set dev tun0 up mtu 1500
Sat Nov 25 14:15:56 2017 /sbin/ip addr add dev tun0  broadcast 
Sat Nov 25 14:15:56 2017 GID set to nogroup
Sat Nov 25 14:15:56 2017 UID set to nobody
Sat Nov 25 14:15:56 2017 UDPv4 link local (bound): [undef]
Sat Nov 25 14:15:56 2017 UDPv4 link remote: [undef]
Sat Nov 25 14:15:56 2017 Initialization Sequence Completed


Config:

dev tun
proto udp
port 11920
ca /etc/openvpn/easy-rsa/pki/ca.crt
cert /etc/openvpn/easy-rsa/pki/issued/server.crt
key /etc/openvpn/easy-rsa/pki/private/server.key
dh /etc/openvpn/easy-rsa/pki/dh2048.pem
topology subnet
server 10.8.0.0 255.255.255.0
# server and remote endpoints
ifconfig 10.8.0.1 10.8.0.2
# Add route to Client routing table for the OpenVPN Server
push "route 10.8.0.1 255.255.255.255"
# Add route to Client routing table for the OPenVPN Subnet
push "route 10.8.0.0 255.255.255.0"
# your local subnet
push "route ip 255.255.255.0"
# Set your primary domain name server address for clients
push "dhcp-option DNS 10.8.0.1"
push "dhcp-option DNS 8.8.4.4"
# Override the Client default gateway by using 0.0.0.0/1 and
# 128.0.0.0/1 rather than 0.0.0.0/0. This has the benefit of
# overriding but not wiping out the original default gateway.
push "redirect-gateway def1"
client-to-client
duplicate-cn
keepalive 10 120
tls-version-min 1.2
tls-auth /etc/openvpn/easy-rsa/pki/ta.key 0
cipher AES-256-CBC
auth SHA256
comp-lzo
user nobody
group nogroup
persist-key
persist-tun
crl-verify /etc/openvpn/crl.pem
status /var/log/openvpn-status.log 20
status-version 3
log /var/log/openvpn.log
verb 1
# Generated for use by PiVPN.io

**Comment by orazioedoardo** [comment]
According to netstat openvpn is listening, from a computer on an external network try to run `echo "whatever" | netcat -u -v -w 5 yourip 11920`.

If such computer is able to reach the server, you should see something like missing HMAC in `/var/log/openvpn.log`.

**Comment by ttravis72** [comment]
I tried netcat but I'm not seeing anything like that in the log.

log:

Sat Nov 25 14:15:56 2017 OpenVPN 2.3.4 arm-unknown-linux-gnueabihf [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [MH] [IPv6] built on Jun 27 2017
Sat Nov 25 14:15:56 2017 library versions: OpenSSL 1.0.1t  3 May 2016, LZO 2.08
Sat Nov 25 14:15:56 2017 NOTE: your local LAN uses the extremely common subnet address.  Be aware that this might create routing conflicts if you connect to the VPN server from public locations such as internet cafes that use the same subnet.
Sat Nov 25 14:15:56 2017 Control Channel Authentication: using '/etc/openvpn/easy-rsa/pki/ta.key' as a OpenVPN static key file
Sat Nov 25 14:15:56 2017 TUN/TAP device tun0 opened
Sat Nov 25 14:15:56 2017 do_ifconfig, tt->ipv6=0, tt->did_ifconfig_ipv6_setup=0
Sat Nov 25 14:15:56 2017 /sbin/ip link set dev tun0 up mtu 1500
Sat Nov 25 14:15:56 2017 /sbin/ip addr add dev tun0  broadcast 
Sat Nov 25 14:15:56 2017 GID set to nogroup
Sat Nov 25 14:15:56 2017 UID set to nobody
Sat Nov 25 14:15:56 2017 UDPv4 link local (bound): [undef]
Sat Nov 25 14:15:56 2017 UDPv4 link remote: [undef]
Sat Nov 25 14:15:56 2017 Initialization Sequence Completed

**Comment by orazioedoardo** [comment]
Ok, at this point I’d say that you PiVPN server is not reachable over the internet, check you port forwarding, maybe the local IP assigned to the Raspberry changed? I don’t know what else to try as of now.

**Comment by ttravis72** [comment]
Thanks for all of your help. I believe my port forwarding is set up correctly. How can I try setting the local IP back to what it was? I'm not sure if that is the issue since I'm still able to ssh into it using the same IP I always have been. I may just try a re-install.

**Comment by ttravis72** [comment]
The clients all say they are connecting but never do

**Comment by orazioedoardo** [comment]
If you are accessing your raspberry pi from the same ip, clearly it did not change.

However, I missed this:
`Sat Nov 25 14:15:56 2017 NOTE: your local LAN uses the extremely common subnet address. Be aware that this might create routing conflicts if you connect to the VPN server from public locations such as internet cafes that use the same subnet.`

Post the output of `ip route` (you don’t need to mask any ip here, since they are local).

**Comment by ttravis72** [comment]
default via 192.168.1.1 dev eth0  metric 202 
default via 192.168.1.1 dev wlan0  metric 303 
10.8.0.0/24 dev tun0  proto kernel  scope link  src 10.8.0.1 
192.168.1.0/24 dev eth0  proto kernel  scope link  src 192.168.1.12  metric 202 
192.168.1.0/24 dev wlan0  proto kernel  scope link  src 192.168.1.15  metric 303

**Comment by orazioedoardo** [comment]
You are connected both via wifi as well via ethernet. Try to disable wlan0 with `sudo ifdown wlan0`, then make sure that you forwarded to `192.168.1.12`, restart openvpn then try again (not sure if that is the issue though).

As a last restort, disable openvpn `sudo systemctl disable openvpn`, then, on raspberry pi run `nc -u -l -p 11920`, on a remote computer run `nc -u your_public_ip 11920`. On either side write something to the console, press enter and see if it appears on the other. If it does, CTRL-C on both, if it doesn’t, then port forwarding is not working.

**Comment by ttravis72** [comment]
When I try to run nc -u -l -p 11920 it says nc: Address already in use

**Comment by orazioedoardo** [comment]
Sorry i was wrong, you should stop openvpn, not disable it `sudo systemctl stop openvpn`, then try again with netcat.

**Comment by ttravis72** [comment]
That worked so my port forwarding is incorrect? 
![screenshot from 2017-11-25 17-13-33](https://user-images.githubusercontent.com/16803998/33235332-60111528-d204-11e7-8006-e608b2a4ee32.png)

**Comment by orazioedoardo** [comment]
“That worked” means that with nc you are able to exchange messages? If yes then port forwarding is working.

**Comment by ttravis72** [comment]
Sorry yes I was able to exchange messages with nc but I still can't connect to my vpn

**Comment by orazioedoardo** [comment]
I would just reinstall stretch and pivpn, maybe the openvpn installation is broken.

**Comment by cfcolaco** [comment]
Is this issue still pressisting? 


> I tried netcat but I'm not seeing anything like that in the log.
> 
> log:
> 
> Sat Nov 25 14:15:56 2017 OpenVPN 2.3.4 arm-unknown-linux-gnueabihf [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [MH] [IPv6] built on Jun 27 2017
> Sat Nov 25 14:15:56 2017 library versions: OpenSSL 1.0.1t 3 May 2016, LZO 2.08
> Sat Nov 25 14:15:56 2017 NOTE: your local LAN uses the extremely common subnet address. Be aware that this might create routing conflicts if you connect to the VPN server from public locations such as internet cafes that use the same subnet.
> Sat Nov 25 14:15:56 2017 Control Channel Authentication: using '/etc/openvpn/easy-rsa/pki/ta.key' as a OpenVPN static key file
> Sat Nov 25 14:15:56 2017 TUN/TAP device tun0 opened
> Sat Nov 25 14:15:56 2017 do_ifconfig, tt->ipv6=0, tt->did_ifconfig_ipv6_setup=0
> Sat Nov 25 14:15:56 2017 /sbin/ip link set dev tun0 up mtu 1500
> Sat Nov 25 14:15:56 2017 /sbin/ip addr add dev tun0 broadcast
> Sat Nov 25 14:15:56 2017 GID set to nogroup
> Sat Nov 25 14:15:56 2017 UID set to nobody
> Sat Nov 25 14:15:56 2017 UDPv4 link local (bound): [undef]
> Sat Nov 25 14:15:56 2017 UDPv4 link remote: [undef]
> Sat Nov 25 14:15:56 2017 Initialization Sequence Completed

According to this log seems to me that the clients are connecting, just not going anywhere ... 

1 - are you using windows client? if yes are you launching OpenVPN as administrator? 
2 -  after connecting ...  Can you ping 10.8.0.1 ? can you ping your pi LAN Ip address? Can you ping google.com? can you ping 8.8.8.8? 
3 - be aware ... if you are in a place on the same subnet as your home network, you will be able to connect and reach the internet but not the devices in your internal network.

**Comment by orazioedoardo** [comment]
According to that log, no clients are connecting. Otherwise he would see something like:

```
Tue Dec 19 12:31:08 2017 IP_ADDRESS:PORT [CLIENT_NAME] Peer Connection Initiated with [AF_INET]IP_ADDRESS:PORT
Tue Dec 19 12:31:08 2017 CLIENT_NAME/IP_ADDRESS:PORT MULTI_sva: pool returned IPv4=10.8.0.2, IPv6=(Not enabled)
```

**Comment by cfcolaco** [comment]
hmmm isn't that log form the client side??? it seems to be so ... well, I am having a quite similar issue with my Vpn Server at home ... but I am getting a connection timeout on my client side ... so will take a closer look when I get home after Xmas!

**Comment by orazioedoardo** [comment]
I think lines provide evidence that this is clearly the server log.

`Sat Nov 25 14:15:56 2017 OpenVPN 2.3.4 arm-unknown-linux-gnueabihf [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [MH] [IPv6] built on Jun 27 2017`

`Sat Nov 25 14:15:56 2017 Control Channel Authentication: using '/etc/openvpn/easy-rsa/pki/ta.key' as a OpenVPN static key file`

**Comment by 4s3ti** [comment]
old thread, closing, if the issue still exists lt us know. 
thank you
