### ISSUE TITLE
The server openvpn@server.service do not start

### ISSUE THREAD

**Issue by homerybart** [pivpn/pivpn#418]
Hello everyone

I installed openVPN in my raspberry pi but when I try to boot the server gives the following error:
  
● openvpn@server.service - OpenVPN connection to server
   Loaded: loaded (/lib/systemd/system/openvpn@.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2017-11-24 11:59:26 CET; 6min ago
     Docs: man:openvpn(8)
           https://community.openvpn.net/openvpn/wiki/Openvpn23ManPage
           https://community.openvpn.net/openvpn/wiki/HOWTO
  Process: 32286 ExecStart=/usr/sbin/openvpn --daemon ovpn-server --status /run/openvpn/server.status 10 --cd /etc/openvpn --config /etc/openvpn/server.conf --writepid /run/openvpn/server.pid (code=exited, status=226/NAMESPACE)

Nov 24 11:59:26 Pi systemd[32286]: openvpn@server.service: Failed at step NAMESPACE spawning /usr/sbin/openvpn: Bad file descriptor
Nov 24 11:59:26 Pi systemd[1]: openvpn@server.service: Control process exited, code=exited status=226
Nov 24 11:59:26 Pi systemd[1]: Failed to start OpenVPN connection to server.
Nov 24 11:59:26 Pi systemd[1]: openvpn@server.service: Unit entered failed state.
Nov 24 11:59:26 Pi systemd[1]: openvpn@server.service: Failed with result 'exit-code'.

My piVPN debug is:

::: Generating Debug Output
:::					:::
::		PiVPN Debug		 ::
:::					:::
::	Latest Commit			 ::
:::					:::
commit 7ed7e4652ebe322e51e85a0582907e83eea0d103
Author: Carlos Colaço <xxxxxxxx@gmail.com>
Date:   Fri Oct 20 17:00:23 2017 +0200

    Added info regarding Raspbian Stretch
    
    added info about support for raspbian Strech, and changed the preference from Jessie to Stretch.
    
    Edited and merged directly since it is a minor edit.
:::					:::
::	Recursive list of files in	 ::
::	/etc/openvpn/easy-rsa/pki	 ::
:::					:::
/etc/openvpn/easy-rsa/pki/:
Albert.ovpn
Default.txt
Michael_norula.ovpn
Michael_norulaOk.ovpn
Michael_norula_norula.ovpn
Jose.ovpn
ca.crt
crl.pem
dh4096.pem
index.txt
index.txt.attr
index.txt.attr.old
index.txt.old
issued
private
serial
serial.old
ta.key

/etc/openvpn/easy-rsa/pki/issued:
Albert.crt
Michael_norulaOk.crt
Jose.crt
server_ntQsz4gFFmzJKgoq.crt

/etc/openvpn/easy-rsa/pki/private:
Albert.key
Michael_norulaOk.key
Jose.key
ca.key
server_ntQsz4gFFmzJKgoq.key
:::					:::
::	Output of /etc/pivpn/*		 ::
:::					:::
:: START /etc/pivpn/DET_PLATFORM ::
Raspbian
:: END /etc/pivpn/DET_PLATFORM ::
:: START /etc/pivpn/INSTALL_PORT ::
31194
:: END /etc/pivpn/INSTALL_PORT ::
:: START /etc/pivpn/INSTALL_PROTO ::
udp
:: END /etc/pivpn/INSTALL_PROTO ::
:: START /etc/pivpn/INSTALL_USER ::
pi
:: END /etc/pivpn/INSTALL_USER ::
:: START /etc/pivpn/NO_UFW ::
1
:: END /etc/pivpn/NO_UFW ::
:: START /etc/pivpn/pivpnINTERFACE ::
eth0
:: END /etc/pivpn/pivpnINTERFACE ::
:::					:::
:: /etc/openvpn/easy-rsa/pki/Default.txt ::
:::					:::
client
dev tun
proto udp
remote xxxxxxx.xxxxx.org 1194
resolv-retry infinite
nobind
persist-key
persist-tun
key-direction 1
remote-cert-tls server
tls-version-min 1.2
verify-x509-name server_ntQsz4gFFmzJKgoq name
cipher AES-256-CBC
auth SHA256
comp-lzo
verb 1
:::					:::
::	Debug Output Complete		 ::
:::					:::
::: 
::: Debug output completed above.
::: Copy saved to /tmp/debug.txt
::: 

The version of kernel is:

3.4.112-sun7i

The server.conf is:

dev tun
proto udp
port 1194
ca /etc/openvpn/easy-rsa/pki/ca.crt
cert /etc/openvpn/easy-rsa/pki/issued/server_ntQsz4gFFmzJKgoq.crt
key /etc/openvpn/easy-rsa/pki/private/server_ntQsz4gFFmzJKgoq.key
dh /etc/openvpn/easy-rsa/pki/dh4096.pem
topology subnet
server 10.8.0.0 255.255.255.0
###  server and remote endpoints
ifconfig 10.8.0.1 10.8.0.2
### Add route to Client routing table for the OpenVPN Server
push "route 10.8.0.1 255.255.255.255"
### Add route to Client routing table for the OPenVPN Subnet
push "route 10.8.0.0 255.255.255.0"
### your local subnet
push "route 192.168.1.0 255.255.255.0"
### Set your primary domain name server address for clients
push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 8.8.4.4"
### overriding but not wiping out the original default gateway.
push "redirect-gateway def1"
client-to-client
keepalive 10 120
remote-cert-tls client
tls-version-min 1.2
tls-auth /etc/openvpn/easy-rsa/pki/ta.key 0
cipher AES-256-CBC
auth SHA256
comp-lzo
user nobody
group nogroup
persist-key
persist-tun
crl-verify /etc/openvpn/crl.pem
status /var/log/openvpn-status.log 20
status-version 3
log /var/log/openvpn.log
verb 1
### Generated for use by PiVPN.io

The OS is Raspbian Stretch 9

Thanks in advance for yours help

**Comment by homerybart** [comment]
Hello

   My OS is Raspbian Stretch 9

**Comment by cfcolaco** [comment]
@homerybart do you still have this issue?
