### ISSUE TITLE
Question of on-going maintenance of OpenVPN

### ISSUE THREAD

**Issue by paulzak** [pivpn/pivpn#42]
I have read the wiki and understand that updating the loader isn't likely necessary without good cause, but what about OpenVPN itself? As best I can tell, I'm currently on openvpn -2 3.4-5+deb8u1. It looks like 2 3.11 is current. Presumably we should keep up to a reasonably recent version avoid known bugs.

Can I run sudo apt-get dist-upgrade safely to get the new package? Will I need to re-key?

Thanks in advance.

Paul

**Comment by 0-kaladin** [comment]
yes you can safely run `apt-get update && apt-get upgrade` to keep the packages at latest versions.
apt-get dist-upgrade you don't need to run as frequently but nothing will require reconfiguring or re-keying anything in openvpn once installed.
regarding versions, 2.3.11 is the current released from openvpn.  but on raspbian we need to pull it from debian repo which as you also pointed out is 2.3.4-5+deb8u1.  This is what will get upgraded as you do the apt-get upgrades.  Now it won't upgrade to 2.3.11, package maintainers generally are back rev'd a little to stay on known stable versions of software.  however if you look at the changelog for the debian openvpn http://metadata.ftp-master.debian.org/changelogs//main/o/openvpn/openvpn_2.3.4-5+deb8u1_changelog
you'll see it still gets security patches and any critical fixes applied.  and 2.3.4 and 2.3.11 both have all we need to support the latest security algorithms and hashes and TLS 1.2.

**Comment by paulzak** [comment]
Thanks so much for the education. I genuinely appreciate it.


Paul 

Sonora, CA 95370
 
 
  On Fri, Jun 3, 2016 at 12:22 PM, 0-kaladin<notifications@github.com> wrote:   
yes you can safely run apt-get update && apt-get upgrade to keep the packages at latest versions.
apt-get dist-upgrade you don't need to run as frequently but nothing will require reconfiguring or re-keying anything in openvpn once installed.
regarding versions, 2.3.11 is the current released from openvpn. but on raspbian we need to pull it from debian repo which as you also pointed out is 2.3.4-5+deb8u1. This is what will get upgraded as you do the apt-get upgrades. Now it won't upgrade to 2.3.11, package maintainers generally are back rev'd a little to stay on known stable versions of software. however if you look at the changelog for the debian openvpn http://metadata.ftp-master.debian.org/changelogs//main/o/openvpn/openvpn_2.3.4-5+deb8u1_changelog
you'll see it still gets security patches and any critical fixes applied. and 2.3.4 and 2.3.11 both have all we need to support the latest security algorithms and hashes and TLS 1.2.
