### ISSUE TITLE
Asus Router OpenVPN files.

### ISSUE THREAD

**Issue by stphn404** [pivpn/pivpn#420]
Hi,
I need help with my router.
I have an OpenVPN server installed on my Raspberry.

For my Asus router I have now only the OPNV file.
How do I create the ca.crt file and the others?

Would be happy about help. Thank you!

**Comment by redfast00** [comment]
Those are embedded in the .ovpn file, so you don't need these on some clients. If you do need them, you can just copy-paste them to separate files from the .ovpn file.

**Comment by stphn404** [comment]
I create a new file and copy what I need from the OPNV?

okay thanks. then I'm looking for what I have to copy from it.

**Comment by cfcolaco** [comment]
@stphn404 is your issue solved????

**Comment by cfcolaco** [comment]
Closing ... please as for reopen if you  need!

**Comment by toshibochan** [comment]
@stphn404 you was able to use in asus router. my dont connect. please help if you was able to connect. 
thanks
