### ISSUE TITLE
install.sh failed to run because of "addr" string

### ISSUE THREAD

**Issue by fred06** [pivpn/pivpn#421]
Hi,

on my french raspbian (8.0) OS, I've got $LANG=fr_FR.UTF-8, which leads to translate "address" to "adresse".

That's why the following command:
`ifconfig eth0|grep "inet "
`
returns
`          inet adr:192.168.1.22  Bcast:192.168.1.255  Masque:255.255.255.0
`

problem: in the pivpn install.sh script, in the setNetwork() function, it's the english "addr" that is searched by the grep command, not my french "adr", so the function returns nothing and the script fails.

I've locally solved the problem by changing the string by hand, but maybe there could be a way to tweak the script, for example by temporary setting $LANG to en_EN.UTF-8.

**Comment by orazioedoardo** [comment]
You are right, in fact it results in a wrong `route "0.0.0.0 " ` being placed in `server.conf`. Instead it should be something like `route "192.168.1.0 255.255.225.0`" (VPN still works by the way).

**Comment by cfcolaco** [comment]
PR #379 Already in test branch ... issue to be close as the test branch gets merged into master.

Thank you!

**Comment by cfcolaco** [comment]
@fred06 can you please provide me the output of 
```
ip addr show
```

I mentioned that ifconfig should be replaced to ip link some time ago due to the ifconfig being deprecated

I will be reviewing and changing some code ... and since I am doing it ... would be a great opportunity to replace this! which might fix this and few issues around here! 

Thanks a lot!

**Comment by fred06** [comment]
here's the output:

1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether b8:27:eb:76:21:b4 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.22/24 brd 192.168.1.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::a752:8010:b41d:7469/64 scope link 
       valid_lft forever preferred_lft forever

**Comment by cfcolaco** [comment]
well seems that extracting the info from IP links is way more reliable then ... 

1 - language independent
2 - all distros have it 
3 - is the replacement for net-tools /// ifconfig

**Comment by cfcolaco** [comment]
Meeeh disregard my previous comments as mentioned earlier and as I am going through the code ... this issue is already solved in the test branch!! feel free to use it .. test it and give feedback!

**Comment by redfast00** [comment]
@cfcolaco just merged the test branch into master

**Comment by cfcolaco** [comment]
Cool! we shall close this one then! =)
