### ISSUE TITLE
PiVPN - ovpn file not generate right [Solved]

### ISSUE THREAD

**Issue by smgermano** [pivpn/pivpn#423]
Hi all, in the piVPN on raspbian the ovpn file not generate fine. Can you help me with these?

https://pastebin.com/UFaymczt

I think that values like this was missing:

> _"client
> dev tun
> proto udp
> remote IP ADDRESS PORT NUMBER"_

## Console output of `pivpn add` or `pivpn add nopass`
> pivpn add
https://pastebin.com/gWV8xEnD

## Console output of `pivpn debug`
> pivpn debug
https://pastebin.com/iwQBUAe8

On linux# openvpn --config test1234.ovpn
(because the ovpn is not right i thinks this not work)

Thanks a lot!

**Comment by CrackerStealth** [comment]
There appears to be an issue with the installer creating the config file in the /etc/pivpn/ with all the variables required to run the pivpn command.

I was able to work around the issue in my setup by uninstalling `pivpn uninstall` and then installing the software with this command `curl -L https://install.pivpn.io | sudo bash`.

Escalating the entire installer to root gets around the permissions issue of the configuration file unable to be written where it should be.

**Comment by smgermano** [comment]
Hi CrackerStealth, it works! Maybe i forgot the privilege permissions (there is without "sudo" in the tutorial). Also i must to update openvpn client on my linux mint (to OpenVPN 2.4.4)

Thanks a lot! Have a nice day.
