### ISSUE TITLE
Some traffic is blocked at PiVPN server

### ISSUE THREAD

**Issue by JimC-2** [pivpn/pivpn#424]
## Issue
I'm using a PiVPN server to connect remote VoIP phones to a PBX on the local network.  Everything works fine except for this: on the second phone that connects I cannot get to the phone's Web GUI over the VPN.

Both phones can make and receive VoIP calls over the VPN, and tcpdump shows traffic between remote phones and the local PBX.  Traceroute of Web GUI traffic shows access to the first remote phone proceeding normally and requests sent to the second phone being accepted by the PiVPN server but not being forwarded to the phone.

Traceroute from a local Windows computer to the first phone works fine: 192.168.1.7 (local Windows computer) -> 192.168.1.150 (local PiVPN server) -> 10.8.0.6 (remote phone 1).  Traceroute to the second phone (10.8.0.14) is: 192.168.1.7 -> 192.168.1.150 -> [timeout].

The server.conf file, which has been modified to work with the phones' OpenVPN client, is:

`dev tun 
proto udp 
port 5577 
 
ca /etc/openvpn/1000/ca.crt 
cert /etc/openvpn/1000/server.crt 
key /etc/openvpn/1000/server.key 
dh /etc/openvpn/1000/dh2048.pem 
 
topology net30 
server 10.8.0.0 255.255.255.0 
ifconfig 10.8.0.1 10.8.0.2 
client-to-client
 
push "route 10.8.0.0 255.255.255.0" 
push "route 192.168.1.0 255.255.255.0" 
push "dhcp-option DNS 208.67.222.222" 
push "dhcp-option DNS 208.67.220.220" 
push "redirect-gateway def1"
push "comp-lzo" 
 
keepalive 10 120 
cipher BF-CBC 
comp-lzo 
user nobody 
group nogroup 
persist-key 
persist-tun 
ifconfig-pool-persist /etc/openvpn/1000/ipp.txt 
 
status /var/log/openvpn-status.log 20 
status-version 3 
log /var/log/openvpn.log 
verb 3 `

I've been trying to track this down for weeks and I don't know where to turn.  The problem makes no sense to me.  Something is blocking some but not all traffic to the second client through the VPN but not to the first client.  It sounds like a routing or firewall problem on the local network but there are no rules that I know of that apply to individual VPN clients.

I'd be grateful for any suggestions about what might be causing this or where to look for more clues.  Thanks,

-jimc

**Comment by cfcolaco** [comment]
@JimC-2 

Ok .. just to make sure .. you have a full working OpenVPN server correct? 
Script went well and all is working except those details you mentioned correct ?

that's is completely out of the PiVPN scope... I would suggest you look for help at OpenVPN IRC Channel or at OpenVPN GitHub page ( being the second one not the most appropriate place IMO ) 

I will leave this open just in case someone comes around and knows how to help you out ...

**Comment by JimC-2** [comment]
Thank you for your reply.  And yes it is out of scope but I had run out of options and had spent months trying to track this down.

However since posting I did discover the problem, pretty much by accident.  The local Windows computer's IP was 192.168.1.7, and the remote phone's local IP address was also 192.168.1.7.  According to my limited understanding, that should not be a problem, but it appears that the remote phone's OpenVPN support has a bug in its routing, and the replies to the local Windows computer were being lost.

I'm posting this partly to thank you, and partly in case someone else runs into something like this.  The phone with the (assumed) bug is a Grandstream GXP2140 running 1.0.9.26.

Thanks again,

-jimc
