### ISSUE TITLE
Installation fails on ubuntu 14.

### ISSUE THREAD

**Issue by username-is-already-taken2** [pivpn/pivpn#426]
Hi there

I've hit a bug whilst attempting to install pivpn.

I'm using the `https://app.vagrantup.com/bento/boxes/ubuntu-14.04` as a base image so if you use vagrant you should be able to replicate, here is my vagrantfile

```
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-14.04"
  config.vm.provider "vmware_workstation" do |v|
    v.gui = true
  end
  config.vm.box_check_update = false
end
```

I've started the vm, ran a `apt update` & `apt upgrade` and then when I go

::: Your system is up to date! Continuing with PiVPN installation...
Can't call method "set" on an undefined value at /usr/share/perl5/Debconf/FrontEnd.pm line 126,  to call the script this happens

```
root@vagrant:~# curl -L https://install.pivpn.io | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   178  100   178    0     0    302      0 --:--:-- --:--:-- --:--:--   302
100 53505  100 53505    0     0  71569      0 --:--:-- --:--:-- --:--:-- 71569
:::
::: You are root.
::: Verifying free disk space...
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: Your system is up to date! Continuing with PiVPN installation...
Can't call method "set" on an undefined value at /usr/share/perl5/Debconf/FrontEnd.pm line 126, <GEN0> line 5.```

I could try a fresh install using the iso if you think it might be the box, but I use them for a lot of other tasks.

**Comment by cfcolaco** [comment]
Ok .. Before I test this and check this .. why do you want Ubuntu 14?

Any special requirement? 
PiVPN should work on ubuntu 14 ... however... I consider this to be kind of a waste of time since its already quite old release =/

however don't take me wrong... if you really need that ... we can try to work it out!! Just be aware that I don't have much time to help you out.

**Comment by username-is-already-taken2** [comment]
Hi @cfcolaco Cheers for coming back to me

I'm not tied to that version so don't want to waste your time, I think I only choose that because that's what it said on the homepage

`FLEXIBLE ::: ...the installer will work just as well on an Ubuntu Server running Trusty Tahr 14.04` 

Let me quickly stand up a v16 box and try that.

**Comment by username-is-already-taken2** [comment]
OK here is the result from 16.04

```
root@vagrant:~# uname -a
Linux vagrant 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

root@vagrant:~# cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

root@vagrant:~# curl -L https://install.pivpn.io | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   178  100   178    0     0    201      0 --:--:-- --:--:-- --:--:--   201
100 53505  100 53505    0     0  42691      0  0:00:01  0:00:01 --:--:--  156k
:::
::: You are root.
::: Verifying free disk space...
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: Your system is up to date! Continuing with PiVPN installation...
Can't call method "set" on an undefined value at /usr/share/perl5/Debconf/FrontEnd.pm line 126, <GEN0> line 5.
```

**Comment by cfcolaco** [comment]
Hmm!! odd thing ... I tested it months ago in ubuntu 16.04 ... well .. will take a look at it when as soon as I have the time for it ... 

can you try run apt-get update && apt-get upgrade before running PiVPN?

**Comment by username-is-already-taken2** [comment]
Hi @cfcolaco 

I tried running the update/upgrade but ended up in the same place.

I took a punt at lunchtime to see if I can see what's going on.  I `think`  'debconf-apt-progress' is broken in ubuntu at the moment as the error looks to be when installing the dependenacy's as I get the same perl error when running the command manually.

I've amended that function to not use that when installing on ubuntu and that worked for me.

I'll send over a pr for it, no problem if you don't use it, all good practice.

Gary

**Comment by cfcolaco** [comment]
cool @username-is-already-taken2 thank you for the help! feel free to make the pull request ...  unfortunately, right now I cannot try to replicate this =/

**Comment by cfcolaco** [comment]
@username-is-already-taken2 I have been looking into the packages ... the debconf-apt-progress package is part of the debconf package ....are you sure that you are not missing any deps from debconf??

how deep went you to check the origin of the issue apart from just tell pivpn to not use the "broken package" ?? right now I don't have tests machine to try and run this and check if it is an Ubuntu issue .. or an "your ubuntu" issue .... are there another issues related to this one around?

**Comment by username-is-already-taken2** [comment]
I'm using the [vagrant](https://www.vagrantup.com/) ubuntu box's being generated as part of the [bento ](https://github.com/chef/bento) project so they are basic scripted installs.

I have virtual box on my laptop, I'll create a new vm and do a minimal server install using the 16.04 iso from ubuntu's website.  Just to rule out if its something inside that bento build.  The bento builds are open source and you can see each step but you never know at least that will rull it out

**Comment by username-is-already-taken2** [comment]
@cfcolaco - I'm very sorry, it must be clearly something in the build,  I've just completed a fresh install and it worked first time.

I'm really sorry to have troubled you with this.  I'll see if I can workout whats missing and feed that back to them

**Comment by cfcolaco** [comment]
@username-is-already-taken2 that's cool!! no worries about that!! thank you a lot for your time!!! if you would like to keep helping out and contributing ... we have plenty of work to do around here! =p

**Comment by cfcolaco** [comment]
closing issue since it is not pivpn related. 

@username-is-already-taken2 , feel free to reopen if you find that you need something from our side! 

Thank you for spending time with the project!
