### ISSUE TITLE
Having trouble installing. Installation ends with:

### ISSUE THREAD

**Issue by Haraade** [pivpn/pivpn#429]
# PiVPN Issue Template

## Console output of `curl install.pivpn.io | bash`
```

```

## Console output of `pivpn add` or `pivpn add nopass`
```

```

## Console output of `pivpn debug`
```

```

**Comment by Haraade** [comment]
: error fetching interface information: Device not found
: error fetching interface information: Device not found

Running Debian GNU/Linux 9 (stretch)

**Comment by cfcolaco** [comment]
@Haraade please provide all the requested information in the issue template!!

**Comment by Haraade** [comment]
curl install.pivpn.io | bash

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   178  100   178    0     0    465      0 --:--:-- --:--:-- --:--:--   464
bash: line 1: html: No such file or directory
bash: line 2: syntax error near unexpected token `<'
'ash: line 2: `<head><title>301 Moved Permanently</title></head>

curl -L https://install.pivpn.io | bash
Installation ends 
: error fetching interface information: Device not found
: error fetching interface information: Device not found

Armbian Tinkerboard - Ubuntu and debian

**Comment by cfcolaco** [comment]
@Haraade I am no magician to guess what is causing that!! I Will ask a few more questions ... if the details aren't good enough to for me to help you I will close the issue. 


what distro are you using?
which user are you running the script with?
do you have sudo privileges?
can you log in as root?

try curl -L https://install.pivpn.io | sudo bash

**Comment by Haraade** [comment]
Have tried to install on the following:
Armbian_5.34_Tinkerboard_Ubuntu_xenial_default_4.4.92.
Armbian_5.35_Tinkerboard_Debian_stretch_default_4.4.102.
Armbian_5.37_Tinkerboard_Debian_jessie_next_4.14.5.

Running the script with root user.
curl -L https://install.pivpn.io | sudo bash, ends with the same result.
After page setup for dhcp / static network setup. press OK (installation page 3) and the installation ends with:
: error fetching interface information: Device not found
: error fetching interface information: Device not found

curl -L https://install.pivpn.io | bash, worked excellent on 
Armbian_5.33_Tinkerboard_Ubuntu_xenial_default_4.4.88.

So I have no idea what's the problem!

**Comment by Haraade** [comment]
The problem is actually that first update creates a new mac address, on a device that has got static ip address. The tinkerboard will not be recognized on the network. The solution is first to update and restart with dhcp before static ip is set.
Thanks for Pivpn!

**Comment by wimdecorte** [comment]
Same issue here, brand new Raspbian Stretch with Desktop:
version: November 2017
Release date: 2017-11-29
Kernel version: 4.9

Ran full apt-get update and apt-get upgrade on it
device already was configured with a static IP address.

running the curl command:
![image](https://user-images.githubusercontent.com/5022743/34410386-eb1278a8-eb9d-11e7-818d-ae11b4406e3e.png)

The issue happens right after these two screens:

![image](https://user-images.githubusercontent.com/5022743/34410436-5fb43f0c-eb9e-11e7-8c22-1d84a1affbcc.png)

and then

![image](https://user-images.githubusercontent.com/5022743/34410440-6809d4d2-eb9e-11e7-9d89-9693e464db4d.png)

**Comment by Joey92** [comment]
I ran into the same issue. Before your last screen, the installer gives you a list of devices to choose from.. You have to choose at least 1 from that list by pressing <space> and then <enter>. After that the installer actually continued.

**Comment by Joey92** [comment]
![Device selection](http://kamilslab.com/wp-content/uploads/2017/01/pivpn_3.png) Wanted to attach an image, so here it is :smile: Navigate with arrow keys, select one with space, and hit enter. I've noticed this is the only list where no value is pre-selected, so this might be the reason you silently run into this issue.

**Comment by cfcolaco** [comment]
@Joey92 ahah xD Cool you figured it out!!! actually the "(press space to select)" was added there quite while ago due to that exact same reason!!

I will try to fix that this days while doing some coding review!

**Comment by redfast00** [comment]
@cfcolaco I see you self-assigned this issue. Do you have a PR ready? If not, please tell me and I'll make one.

**Comment by cfcolaco** [comment]
@redfast00 I actually had this done tough a bunch of things changed so will have to review a lot of what I have done. =/ if you have time for it go ahead. sorry for taking so long =.

**Comment by redfast00** [comment]
No problem, I haven't visited this repo in quite some time. I'll take a look at it.
