### ISSUE TITLE
Pivpn fails to install on blank ubuntu docker containers

### ISSUE THREAD

**Issue by InnovativeInventor** [pivpn/pivpn#430]
# PiVPN Issue Template

## Console output of `curl install.pivpn.io | bash`
```

```

## Console output of `pivpn add` or `pivpn add nopass`
```

```

## Console output of `pivpn debug`
```

```

## Issue
This is strange, but when I type `curl -L https://install.pivpn.io | bash` into a blank docker container with Ubuntu 16.04, it exits at installing packages. I'm not sure what is happening here. It looks like PiVPN isn't installing properly.

**Comment by InnovativeInventor** [comment]
I've figured this out from #399 where I need to type `dpkg --configure -a`, then rerun the script again. I think this might be a problem with the install script. Maybe `dpkg --configure -a` could be inserted somewhere?

**Comment by cfcolaco** [comment]
Cool @InnovativeInventor I will close this issue then as I already refferenced it in the the mentioned issue! this way we an track this all in one place ok? 

Thanks a lot for your input ... maybe i will add that to the script when I have the time and if I check that is indeed a common solution for all users with the same kind of issue! =)
