### ISSUE TITLE
Set up was not assigning my public IP. Solved. 

### ISSUE THREAD

**Issue by Socleanjft** [pivpn/pivpn#431]
Hi everyone!

I have PiVPN running on a Pi Zero and for whatever reason, during setup, the script was not assigning my public IP to the .ovpn user config file. It may have been because my ISP recently gave me an IPv6 address instead of my original static IPv4 addr. I have since changed my router settings to force an IPv4 public IP. 

On my iOS OpenVPN app I was getting a connection error of: 

> UDP send error: send: No route to host

After hours of scouring Google, GitHub, and OpenVPN forums, I was at my wits end. In desperation I looked at my old .ovpn and noticed that my public IP was in the line:

> remote _My IP_ 1134

For some reason the IP was not being included in the newly generated .ovpn or showing during installation using the pivpn script for Stretch.

**The Solution**

 I simply edited the .ovpn file at: 

> /home/pi/ovpns/ 

to include my public IP at

> remote 1134  <- What it looked like

> remote _My new IPv4 IP_ 1134 <- What I changed it to

 and VIOLA it worked! 

This may have been an obvious fix to the veteran users around here. Just wanted to share this in case anyone else gets stumped by this issue!

I hope I formatted this correctly.

**Comment by cfcolaco** [comment]
ty for your input!! =) 
Labeled this as information for further reference! 

closing issue! =) 

feel free to reopen if you need anything else.
