### ISSUE TITLE
MD5 tls-auth warning on android

### ISSUE THREAD

**Issue by jvaleros** [pivpn/pivpn#434]
On the android openvpn official client, every time I connect to my profile, I get the warning that my server uses an MD5 certificate for tls-authentication. It also reminds me that it will loose support in April 2018. I was wondering if there is anyway to force a more secure cypher, or if there is any development in the future that might improve this.

Congratulations to the developers of PIVPN as I really enjoy using it and believe they are true professionals that really make our job easy when implementing an Openvpn server.

**Comment by cfcolaco** [comment]
Hi there! 
Thank you for using and enjoying PiVPN. 

About the encryption... tbh my understanding about encryption methods, and ciphers which ones are what ... well ... I just know a bit about that! 

however, I don't think we are generating any certificates with MD5! think everything is using RSA and TLS ... and the support for the elliptic curve is in the loop I guess ( at least OpenVPN already supports it ).

but well ... will leave this one for someone with more understanding of the matter than me!! 
@redfast00 wanna give a hand here?

**Comment by redfast00** [comment]
That doesn't really make sense to me: in both the client and server config, we are using SHA256. I don't know if that's the algorithm used for tls-authentication though. Anyway, I looked through our codebase, there is not a single mention of md5. I don't really know what caused this.

**Comment by evildarknight** [comment]
open file /etc/ssl/openssl.cnf
change "default_md" = default to "default_md" = sha256
regenerate all your certificates and android openvpn will play nice

**Comment by cfcolaco** [comment]
Thanks! 

@evildarknight ... checked in mine config files .. both in the laptop I am using right now ( Ubuntu 16 ) and in a Raspbian Strech with manually installed OpenVPN and both have  

default_md = default

so it makes me wonder ... if that is the correct parameter to change .... but definitely should be something similar to that!

**Comment by orazioedoardo** [comment]
Could br just a [false warning](https://forums.openvpn.net/viewtopic.php?f=33&t=25462), try to update the appl

**Comment by evildarknight** [comment]
yup thats the line that's need changing sorry was busy
