### ISSUE TITLE
nt see any text on my displayotron?

### ISSUE THREAD

**Issue by eddiss** [pivpn/pivpn#437]
# PiVPN Issue Template

## Have you searched for similar issues and solutions? 
    (yes/no / which issues?) 
  

## Console output of `curl install.pivpn.io | bash`
```
  Output Here
```

## Console output of `pivpn add` or `pivpn add nopass`
```
  Output Here
```

## Console output of `pivpn debug`
```
  Output Here
```

## Console Output of `sudo iptables -t nat -S`
```
  Output Here
```

## Console Output of `sudo iptables -S`
```
  Output Here
```

## output of `sudo netstat -uanp | grep openvpn`

```
  Output Here
```

## Have you taken any steps towards solving your issue? 
     which?

**Comment by cfcolaco** [comment]
Please provide clear instructions... Is pivpn working or not? what's the issue itself?
