### ISSUE TITLE
all clients get 10.8.0.2

### ISSUE THREAD

**Issue by rvaneijden** [pivpn/pivpn#439]
I use 1 client profile for multiple computers.
I can connect to the vpn server on all machines, but they all get 10.8.0.2, this causes issues with internet connectivity for all computers except for the last one to connect.
I have another pi3 running elsewhere where each computer will get a unique IP, 10.8.0.2, 10.8.0.3, 10.8.0.4, etc. etc.
I'm using stretch lite.
Any ideas what goes wrong here?

**Comment by nemysys** [comment]
I’m no expert, but isn’t 1 client profile for multiple computers going to give you problems?

**Comment by rvaneijden** [comment]
It doesn't on my other pi, as each pc gets a unique IP.
