### ISSUE TITLE
how to create a client certificate (.p12)

### ISSUE THREAD

**Issue by dpaight** [pivpn/pivpn#44]
pivpn created a working vpn for me (thanks much). I used the .ovpn file to configure OpenVPN Connect on my Nexus phone.  The Chromebook, however, cannot use the .ovpn file. It needs a client certificate. I don't see any likely candidates in my ~/ovpns directory.  Can I create one from the existing key file?

**Comment by dpaight** [comment]
Just noticed the "closed" issues. My question has already been addressed.

**Comment by 0-kaladin** [comment]
I'll link it here for completeness sake https://github.com/pivpn/pivpn/issues/27
