### ISSUE TITLE
Enhancement - IPsec/L2TP and native Cisco IPsec

### ISSUE THREAD

**Issue by drduker** [pivpn/pivpn#443]
Have you considered adding IPsec/L2TP and Cisco(xauth) IPsec to piVPN installations?  I foresee an option at the beginning with a default of just openvpn but also be able to select IPsec options.  All of these protocols could easily be running at once for a relatively light load on a small home device like the pi 3.

Example of installing these both:
https://github.com/hwdsl2/setup-ipsec-vpn

I have used your software in the past and remember that I really liked the easy command line interface.  I would be willing to contribute as I am looking for a class project.

Thanks!

**Comment by 0-kaladin** [comment]
Have not considered. But I do like Libreswan and have used at work on bastion hosts to get into production environments. This has some merit. I'm open to further discussion.

**Comment by Cauchon** [comment]
This would be especially encouraged now given that iOS/OpenVPN is having issues staying connected after the phone goes into standby since the latest update: https://www.reddit.com/r/VPN/comments/7r7k5a/is_anyone_else_having_issues_with_openvpn_on_ios/

**Comment by mtoensing** [comment]
Does this mean I have to install an app (eg. Openvpn) on iOS? I can't use the build in vpn client? Why!? Even my router (fritz box) is able to support that.

**Comment by cezar97** [comment]
@mtoensing ipsec and l2tp have built-in support on most devices, so no need to install an app for that.

**Comment by 4s3ti** [comment]
will close this for now. 
If supporting alternative VPN solutions wireguard should be the way to go.
