### ISSUE TITLE
install hangs after UDP port question

### ISSUE THREAD

**Issue by mainstreetexpress** [pivpn/pivpn#444]
Hi
I'm trying to install pivpn on a fresh pi box running stretch. Everything is fine until I get to the port selection window  and choose the default 1194. After that the script hangs without outputting any error as per below

`+ [[ 1194 == \I\n\v\a\l\i\d ]]
+ whiptail --backtitle 'Specify Custom Port' --title 'Confirm Custom Port Number' --yesno 'Are these settings correct?\n    PORT:   1194' 20 70
+ PORTNumCorrect=True
+ [[ True = True ]]
+ echo 1194
+ sudo cp /tmp/INSTALL_PORT /etc/pivpn/INSTALL_PORT
+ confOpenVPN
++ cat /dev/urandom
++ tr -dc a-zA-Z0-9
++ fold -w 16
++ head -n 1

***nothing***
`
So I never get to the encryption option, any ideas?

**Comment by mainstreetexpress** [comment]
A fresh OS install fixed it

**Comment by TB1234** [comment]
I had the same problem and fixed it by changing one line in the script. BTW: it is not good to make a cat on urandom...

Original Code:
`NEW_UUID=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 16 | head -n 1)`

Changed to:
`NEW_UUID=$(head -n 1 /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 16 | head -n 1)`
