### ISSUE TITLE
Cannot connect after installing PiVPN on XBian

### ISSUE THREAD

**Issue by zevele** [pivpn/pivpn#446]
Hi I've installed without any issues PiVPN (used the default settings). When I'm trying to connect I get timeout error. I've tried both with OpenVPN GUI on my windows machine and OpenVPN connect on my iphone. I've tried both from within the local network and outside. In all cases I end up with connection timeout error. I'm using dynamic DNS and I'm able to connect to other services using this address. I also successfully connected to SSH server on the RPi using the dynamic DNS and forwarding port 22.
I'm running PiVPN on XBian distribution on RPi2.  XBian is fully updated (`apt-get update`, `apt-get upgrade` and `apt-get dist-upgrade`).
I've seen here a lot of similar issues, but was not able to solve mine, apologies if I'm double posting.

## Console output of `cat username.opvn`
```
client
dev tun
proto udp
remote my.dyndns.address.com 1194
resolv-retry infinite
nobind
persist-key
persist-tun
key-direction 1
remote-cert-tls server
tls-version-min 1.2
verify-x509-name server_name name
cipher AES-256-CBC
auth SHA256
comp-lzo
verb 1
<ca>
-----BEGIN CERTIFICATE-----
BunchOfRandomLetters...
-----END CERTIFICATE-----
</ca>
<cert>
-----BEGIN CERTIFICATE-----
BunchOfRandomLetters...
-----END CERTIFICATE-----
</cert>
<key>
-----BEGIN RSA PRIVATE KEY-----
BunchOfRandomLetters...
-----END RSA PRIVATE KEY-----
</key>
<tls-auth>
#
# 2048 bit OpenVPN static key
#
-----BEGIN OpenVPN Static key V1-----
BunchOfRandomLetters...
-----END OpenVPN Static key V1-----
</tls-auth>
```

## Console output of `pivpn debug`
```
  ::: Generating Debug Output
:::                                     :::
::              PiVPN Debug              ::
:::                                     :::
::      Latest Commit                    ::
:::                                     :::
commit 72b3dc24e7959e61e0233f2fde278bfc6498c114
Merge: 041d410 4e814fc
Author: redfast00 <redfast00@users.noreply.github.com>
Date:   Fri Dec 22 12:51:48 2017 +0100

    Merge pull request #432 from pivpn/cfcolaco-Patch

    Updated Issue Template
:::                                     :::
::      Recursive list of files in       ::
::      /etc/openvpn/easy-rsa/pki        ::
:::                                     :::
/etc/openvpn/easy-rsa/pki/:
ca.crt
crl.pem
Default.txt
dh2048.pem
index.txt
index.txt.attr
index.txt.attr.old
index.txt.old
issued
private
serial
serial.old
ta.key
username.ovpn

/etc/openvpn/easy-rsa/pki/issued:
server_name.crt
username.crt

/etc/openvpn/easy-rsa/pki/private:
ca.key
server_name.key
username.key
:::                                     :::
::      Output of /etc/pivpn/*           ::
:::                                     :::
:: START /etc/pivpn/DET_PLATFORM ::
Debian
:: END /etc/pivpn/DET_PLATFORM ::
:: START /etc/pivpn/INSTALL_PORT ::
1194
:: END /etc/pivpn/INSTALL_PORT ::
:: START /etc/pivpn/INSTALL_PROTO ::
udp
:: END /etc/pivpn/INSTALL_PROTO ::
:: START /etc/pivpn/INSTALL_USER ::
xbian
:: END /etc/pivpn/INSTALL_USER ::
:: START /etc/pivpn/NO_UFW ::
1
:: END /etc/pivpn/NO_UFW ::
:: START /etc/pivpn/pivpnINTERFACE ::
eth0
:: END /etc/pivpn/pivpnINTERFACE ::
:::                                     :::
:: /etc/openvpn/easy-rsa/pki/Default.txt ::
:::                                     :::
client
dev tun
proto udp
remote my.dyndns.address.com 1194
resolv-retry infinite
nobind
persist-key
persist-tun
key-direction 1
remote-cert-tls server
tls-version-min 1.2
verify-x509-name server_name name
cipher AES-256-CBC
auth SHA256
comp-lzo
verb 1
:::                                     :::
::      Debug Output Complete            ::
:::                                     :::
:::
::: Debug output completed above.
::: Copy saved to /tmp/debug.txt
:::
```

## Console Output of `sudo iptables -t nat -S`
```
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT
-A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE
```

## Console Output of `sudo iptables -S`
```
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
```

## output of `sudo netstat -uanp | grep openvpn`
**after reboot, returns nothing.**
but before rebooting returned:
```
udp        0      0 0.0.0.0:1194            0.0.0.0:*                           28700/openvpn
```

## output of `cat /etc/openvpn/server.conf`
```
dev tun
proto udp
port 1194
ca /etc/openvpn/easy-rsa/pki/ca.crt
cert /etc/openvpn/easy-rsa/pki/issued/server_name.crt
key /etc/openvpn/easy-rsa/pki/private/server_name.key
dh /etc/openvpn/easy-rsa/pki/dh2048.pem
topology subnet
server 10.8.0.0 255.255.255.0
# server and remote endpoints
ifconfig 10.8.0.1 10.8.0.2
# Add route to Client routing table for the OpenVPN Server
push "route 10.8.0.1 255.255.255.255"
# Add route to Client routing table for the OPenVPN Subnet
push "route 10.8.0.0 255.255.255.0"
# your local subnet
push "route 0.0.0.0 "
# Set your primary domain name server address for clients
push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 8.8.4.4"
# Override the Client default gateway by using 0.0.0.0/1 and
# 128.0.0.0/1 rather than 0.0.0.0/0. This has the benefit of
# overriding but not wiping out the original default gateway.
push "redirect-gateway def1"
client-to-client
keepalive 10 120
remote-cert-tls client
tls-version-min 1.2
tls-auth /etc/openvpn/easy-rsa/pki/ta.key 0
cipher AES-256-CBC
auth SHA256
comp-lzo
user nobody
group nogroup
persist-key
persist-tun
crl-verify /etc/openvpn/crl.pem
status /var/log/openvpn-status.log 20
status-version 3
log /var/log/openvpn.log
verb 1
# Generated for use by PiVPN.io
```

## Have you taken any steps towards solving your issue? 
I don't know if it's a valid test, but I've also tried telnet'ing locally (on the RPi) 
`telnet localhost 1194`
with the following respose
`telnet: can't connect to remote host (127.0.0.1): Connection refused`

Also I've seen in other issues people posting their `systemctl status openvpn`, and `sudo systemctl status openvpn@server` for both I get an error
## output of `sudo systemctl status openvpn` and `sudo systemctl status openvpn@server`
```
Failed to get properties: No such interface ''
```

## Update:
after running `sudo nmap -sU my.dyndns.address.com -p 1194` and `sudo nmap -sU localhost -p 1194`
with the following output:
```
Nmap scan report for my.dyndns.address.com (my.real.ip.address)
Host is up (0.0015s latency).
rDNS record for my.real.ip.address: some-more-information
PORT     STATE  SERVICE
1194/udp open openvpn
```

**I was able to connect**, **BUT**, after rebooting the machine, I was not able to connect anymore. and now `sudo netstat -uanp | grep openvpn` returns nothing.

## Update 2 (Solution?):
I manged to properly connect after running `sudo modeprob tun` and then `service openvpn start`. Apparently the tun module is not properly loaded on restart. 
## So, as a work-around, I added to `/etc/rc.local` 
(just before `exit 0`)
```
modeprob tun
service openvpn start
```
and now it works also after restart.

**Comment by cfcolaco** [comment]
@zevele hi there!! 

So .. apparently, you found the solution correct? 

that issue lies on XBian, however, this is valuable information, which I thank you a lot!!

**Comment by zevele** [comment]
It's been working since my last post. I don't know if it's the best solution, but it does the job. I do have a problem on my iphone: I'm using OpenVPN connect, which get disconnected when the screen is off and fails to reconnect, but I'm not sure it's pivpn's fault. Anyhow thanks for the great job!

**Comment by cfcolaco** [comment]
@zevele Lets put it this way... PiVPN is not a piece of software nor a VPN ... it is an installer, what PiVPN does basically is to automate the deployment of a simple OpenVPN server, by deployment i mean ... install and basic config! 

so that issue is most likely to be related with OpenVPN connect! that doesn't keep your connection when you shut the screen! =/ 

Will then close this issue! 

Thank you!!
