### ISSUE TITLE
Extra cert

### ISSUE THREAD

**Issue by chickengravey** [pivpn/pivpn#448]
Hello,

I have come to add a cert onto my pi, and have found an extra one added. Its begins with server_ then a load of random letters and numbers. Then just the ones that i know about. The weird thing is pivpn -r i do not see it listed. The cert is not the kind of name that i would use. Has my pi been hacked!

Thanks
Richard

**Comment by orazioedoardo** [comment]
Did you read this? `NOTE : The first entry should always be your valid server!`

**Comment by chickengravey** [comment]
sorry i didnt! i was in panic mode! I wrote my car off today, so i am not in the best of moods.
