### ISSUE TITLE
Can't access install.pivpn.io

### ISSUE THREAD

**Issue by jsfrederick** [pivpn/pivpn#449]
# PiVPN Issue Template

## Issue
I just tried to install PiVPN and got the no route to host.  I can ping almost another site and ip address.  I can ping pivpn.io, but not install.pivpn.io.

install.pivpn.io resolves to 71.19.155.138. Cannot ping that IP address either. but other ip addresses resolve and ping fine.

Just wanted check and see if anyone else is having the issue.

## Have you searched for similar issues and solutions? 
    (yes/no / which issues?) 
Yes  

## Console output of `curl install.pivpn.io | bash`
```
root@rock64:~# curl -L https://install.pivpn.io | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0curl: (7) Failed to connect to install.pivpn.io port 443: No route to host
root@rock64:~#
```

## Console output of `pivpn add` or `pivpn add nopass`
```
  Output Here
```

## Console output of `pivpn debug`
```
  Output Here
```

## Console Output of `sudo iptables -t nat -S`
```
  Output Here
```

## Console Output of `sudo iptables -S`
```
  Output Here
```

## output of `sudo netstat -uanp | grep openvpn`

```
  Output Here
```

## Have you taken any steps towards solving your issue? 
     which?

**Comment by orazioedoardo** [comment]
Same for me, no idea why. By the way, you can still install using this url: `curl -L https://raw.githubusercontent.com/pivpn/pivpn/master/auto_install/install.sh | bash`

**Comment by jsfrederick** [comment]
Thanks, I am glad it's not just me.  I will give it a few days and then try again.  If not, I'll try your link.

**Comment by orazioedoardo** [comment]
Well, that’s the url install.pivpn.io points to (in case you were wondering).

**Comment by jsfrederick** [comment]
Updated, I tried again and it's working.  Thanks!

**Comment by bugsybando** [comment]
went through and I fixed it by using a different link, below is alternative download methods 

https://docs.pivpn.io/install/
