### ISSUE TITLE
TLS Error - No Other Post Helped

### ISSUE THREAD

**Issue by Anim8edTech** [pivpn/pivpn#450]
I have setup the PiVPN exactly how the guide says to, and have gotten to the final connection stage, and it does not work. I have tried doing this on several Windows computers, and have had no success. Here are my logs:
`Mon Jan 15 17:32:14 2018 OpenVPN 2.4.4 x86_64-w64-mingw32 [SSL (OpenSSL)] [LZO] [LZ4] [PKCS11] [AEAD] built on Sep 26 2017
Mon Jan 15 17:32:14 2018 Windows version 6.2 (Windows 8 or greater) 64bit
Mon Jan 15 17:32:14 2018 library versions: OpenSSL 1.0.2l  25 May 2017, LZO 2.10
Enter Management Password:
Mon Jan 15 17:32:19 2018 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Mon Jan 15 17:32:19 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]174.54.82.219:1194
Mon Jan 15 17:32:19 2018 UDP link local: (not bound)
Mon Jan 15 17:32:19 2018 UDP link remote: [AF_INET]174.54.82.219:1194
Mon Jan 15 17:33:20 2018 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Mon Jan 15 17:33:20 2018 TLS Error: TLS handshake failed
Mon Jan 15 17:33:20 2018 SIGUSR1[soft,tls-error] received, process restarting
Mon Jan 15 17:33:25 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]174.54.82.219:1194
Mon Jan 15 17:33:25 2018 UDP link local: (not bound)
Mon Jan 15 17:33:25 2018 UDP link remote: [AF_INET]174.54.82.219:1194
Mon Jan 15 17:33:38 2018 SIGTERM[hard,] received, process exiting
`
Any ideas on what I should do? Thanks in advance.

**Comment by orazioedoardo** [comment]
Have you checked [here](https://openvpn.net/index.php/open-source/faq/79-client/253-tls-error-tls-key-negotiation-failed-to-occur-within-60-seconds-check-your-network-connectivity.html)?

Did you forward the port through your router?

**Comment by TheCatster** [comment]
Hi there! Sorry for the later response. Yes I have, here is an image of my settings, maybe I screwed something up. I'm not really sure what went wrong, tried this on multiple pi's and multiple SD cards.

[https://imgur.com/NKBVHL9](url)

**Comment by cfcolaco** [comment]
@TheCatster Hi there!! sorry to put things this way ... but ....  we have an Issue template for a reason!! without those details, we cannot help you! 

Please provide all the info requested in the issue template! and be careful to remove any sensitive information 

I had a similar issue with my server weeks ago ... please provide me as well with the output of: 
``` 
systemctl status openvpn
systemctl status openvpn@server
``` 

thanl you!

**Comment by cfcolaco** [comment]
also, check this #446  it should not happen on raspbian ... but my issue weeks ago was entirely related with this except that for some reason i couldn't load the kernel module .. which ended up with me having to reinstall the whole system!

**Comment by TheCatster** [comment]
# TLS Error - Running PiVPN On Raspbian Stretch



## Issue
I went through the whole setup process, and when trying to connect to my PC using the .ovpn, it answers with TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity).

## Have you searched for similar issues and solutions? 
   
  Yes, but when I tried all of them, which most were to edit the config file, they did not help.

## Console output of `curl install.pivpn.io | bash`
```
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   178  100   178    0     0    557      0 --:--:-- --:--:-- --:--:--   557
bash: line 1: html: No such file or directory
bash: line 2: syntax error near unexpected token `<'
'ash: line 2: `<head><title>301 Moved Permanently</title></head>
```

## Console output of `pivpn add` or `pivpn add nopass`
```
Enter a Name for the Client:  Example
Enter the password for the client:
Enter the password again to verify:
spawn ./easyrsa build-client-full Example

Note: using Easy-RSA configuration from: ./vars
rand: Use -help for summary.
Generating a 2048 bit RSA private key
.......................................+++
.................................................................+++
writing new private key to '/etc/openvpn/easy-rsa/pki/private/Example.key.Uu1Cw4AKY7'
Enter PEM pass phrase:
Verifying - Enter PEM pass phrase:
-----
Using configuration from /etc/openvpn/easy-rsa/openssl-1.0.cnf
Check that the request matches the signature
Signature ok
The Subject's Distinguished Name is as follows
commonName            :ASN.1 12:'Example'
Certificate is to be certified until Jan 16 00:19:18 2028 GMT (3650 days)

Write out database with 1 new entries
Data Base Updated
spawn openssl rsa -in pki/private/Example.key -des3 -out pki/private/Example.key
Enter pass phrase for pki/private/Example.key:
writing RSA key
Enter PEM pass phrase:
Verifying - Enter PEM pass phrase:
Client's cert found: Example.crt
Client's Private Key found: Example.key
CA public Key found: ca.crt
tls-auth Private Key found: ta.key


========================================================
Done! Example.ovpn successfully created!
Example.ovpn was copied to:
  /home/pi/ovpns
for easy transfer. Please use this profile only on one
device and create additional profiles for other devices.
========================================================
```

## Console output of `pivpn debug`
```
  ::: Generating Debug Output
:::                                     :::
::              PiVPN Debug              ::
:::                                     :::
::      Latest Commit                    ::
:::                                     :::
commit 72b3dc24e7959e61e0233f2fde278bfc6498c114
Merge: 041d410 4e814fc
Author: redfast00 <redfast00@users.noreply.github.com>
Date:   Fri Dec 22 12:51:48 2017 +0100

    Merge pull request #432 from pivpn/cfcolaco-Patch

    Updated Issue Template
:::                                     :::
::      Recursive list of files in       ::
::      /etc/openvpn/easy-rsa/pki        ::
:::                                     :::
/etc/openvpn/easy-rsa/pki/:
ca.crt
crl.pem
Default.txt
dh2048.pem
Example.ovpn
index.txt
index.txt.attr
index.txt.attr.old
index.txt.old
issued
LaptopAsus.ovpn
private
serial
serial.old
SirDanyaJames2.ovpn
ta.key

/etc/openvpn/easy-rsa/pki/issued:
Example.crt
LaptopAsus.crt
server_hckDNvU6IKtOVkJn.crt
SirDanyaJames2.crt

/etc/openvpn/easy-rsa/pki/private:
ca.key
Example.key
LaptopAsus.key
server_hckDNvU6IKtOVkJn.key
SirDanyaJames2.key
:::                                     :::
::      Output of /etc/pivpn/*           ::
:::                                     :::
:: START /etc/pivpn/DET_PLATFORM ::
Raspbian
:: END /etc/pivpn/DET_PLATFORM ::
:: START /etc/pivpn/INSTALL_PORT ::
1194
:: END /etc/pivpn/INSTALL_PORT ::
:: START /etc/pivpn/INSTALL_PROTO ::
udp
:: END /etc/pivpn/INSTALL_PROTO ::
:: START /etc/pivpn/INSTALL_USER ::
pi
:: END /etc/pivpn/INSTALL_USER ::
:: START /etc/pivpn/NO_UFW ::
1
:: END /etc/pivpn/NO_UFW ::
:: START /etc/pivpn/pivpnINTERFACE ::
eth0
:: END /etc/pivpn/pivpnINTERFACE ::
:::                                     :::
:: /etc/openvpn/easy-rsa/pki/Default.txt ::
:::                                     :::
client
dev tun
proto udp
remote IP ADDRESS (Not Saying Mine)
resolv-retry infinite
nobind
persist-key
persist-tun
key-direction 1
remote-cert-tls server
tls-version-min 1.2
verify-x509-name server_hckDNvU6IKtOVkJn name
cipher AES-256-CBC
auth SHA256
comp-lzo
verb 1
:::                                     :::
::      Debug Output Complete            ::
:::                                     :::
:::
::: Debug output completed above.
::: Copy saved to /tmp/debug.txt
:::
```
## Console Output of `sudo iptables -t nat -S`
```
  -P PREROUTING ACCEPT
-P INPUT ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT
-A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE

```

## Console Output of `sudo iptables -S`
```
    -P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
```

## output of `sudo netstat -uanp | grep openvpn`

```
 udp        0      0 0.0.0.0:1194            0.0.0.0:*                           426/openvpn

```

## Have you taken any steps towards solving your issue? 
   
I tried changing config files, changing pi's, reflashing SD cards, using Stretch Lite, and rebooting everything.


That better?

**Comment by TheCatster** [comment]
Does anyone have any advice?

**Comment by cfcolaco** [comment]
@TheCatster Sorry for the long waiting time for an answer but we are few supporting here being me one of the most active, and I am currently going to a lot of travelling and doing some PiVPN code review in my free time leaving just a few for providing support, please try to be pro-active and be patient! 

Regarding your issue ... that's much better with almost all the details, although I Still need the output of `sudo systemctl status openvpn` and `sudo systemctl status openvpn@server`

thank you for your patience!

**Comment by TheCatster** [comment]
Oh, sorry, I didn't want to disrupt your traveling! I just wasn't sure. I'll write in the results for those two in my next comment. Thanks for the help you are doing.

**Comment by cfcolaco** [comment]
@TheCatster Don't worry about that I am here to help as much as I can ... If i was traveling for pleasure I can assure you I wouldn't be here replying to you!! =p

**Comment by TheCatster** [comment]
My results for `sudo systemctl status openvpn` are:
```
(THIS IS A DOT) openvpn.service - OpenVPN service
Loaded: loaded (/lib/systemd/system/openvpn.service; enabled; vendor preset: enabled)
Active: active (exited) since Tue 2018-1-16 17:45:16 UTC; 1 weeks 5 days ago
Process: 551 ExecStart=/bin/true (code=exited, status=0/SUCCESS)
Main PID: 551 (Code=exited, status=0/SUCCESS)
CGroup: /system.slice/openvpn.service

Jan 16 17:45:16 raspberrypi systemd[1]: Starting OpenVPN services...
Jan 16 17:45:16 raspberrypi systemd[1]: Started OpenVPN services.
~
~
```
And the results for `sudo systemctl status openvpn@server` are:
```
(THIS IS A DOT) openvpn@server.service - OpenVPN connection to server
Loaded: loaded (/lib/systemd/system/openvpn@.service; disabled; vendor preset: enabled)
Active: active (running) since Tue 2018-1-16 17:45:10 UTC; 1 weeks 5 days ago
Docs: man:openvpn(8)
https://community.openvpn.net/openvpn/wiki/Openvpn23ManPage
https://community.openvpn.net/openvpn/wiki/HOWTO
Process: 353 ExecStart=/usr/sbin/openvpn --daemon ovpn-server --status /run/openvpn/server.status 10 --cd /etc/openvpn --config /etc/openvpn/server.conf --writepid /run/openvpn/server.pid (code=exited, status=0/SUCCESS)
Main PID: 426 (openvpn)
CGroup: /system.slice/system-openvpn.slice/openvpn@server.service
(Some wierd "L" shaped symbol) 426 /usr/sbin/openvpn --daemon ovpn-server --status /run/openvpn/server.status 10 --cd /etc/openvpn --config /etc/openvpn/server.conf --writepid /run/openvpn/server.pid

Jan 16 17:45:09 raspberrypi systemd[1]: Starting OpenVPN connection to server...
Jan 16 17:45:10 raspberrypi systemd[1]: Started OpenVPN connection to server.
```


That was way too much typing. :) Those are the results, hope they can help get a solution.

**Comment by TheCatster** [comment]
Any updates? I tried reinstalling this on a Ubuntu server, so this isn't a Pi or Ubuntu issue. I think it is a Windows problem.

**Comment by orazioedoardo** [comment]
Seems ok, can you connect from a client other than Windows?

**Comment by TheCatster** [comment]
No. It cannot connect to the server on my iPhone, and just times out.

**Comment by chazLnerd** [comment]
@TheCatster 
Here's what worked for me...

My first PiVPN install worked flawlessly, but my second PiVPN install gave me your same TLS issues. The only factors which I changed between the two installs were UFW being added and the default pi user name being changed.
I noticed that the PiVPN installation script automatically forwarded port 1194/udp (ipv4 and ipv6) as well as the tun address in UFW. I tried to troubleshoot my router and iptables since my UFW rules seemed fine, but the problem was deceivingly related to UFW (possibly due to insufficient user privileges during the install).

So, try deleting and readding the UFW rules:

`sudo ufw status verbose` 
`sudo ufw delete allow 1194/udp`
`sudo ufw delete allow from 10.8.0.0/24`
`sudo ufw disable`
`sudo ufw enable`
`sudo ufw allow from 10.8.0.0/24`
`sudo ufw allow 1194/udp`
`sudo ufw disable`
`sudo ufw enable`
`sudo ufw status verbose`

**Comment by TheCatster** [comment]
**@chazLnerd**
So I followed your instructions, and I no longer have ssh on my server, and it is in my attic so it going to take a while to access it to check if the aforementioned method worked. Is that normal that I lost ssh access?

**Comment by orazioedoardo** [comment]
It's normal that you lost SSH access because @chazLnerd did not tell you to allow ssh through ufw: `sudo ufw allow 22/tcp`.

By the way, since you probably need to hook the raspberry to a TV to reset ssh access, can just reinstall Stretch and the latest PiVPN?

**Comment by TheCatster** [comment]
I use it on a Ubuntu PC/Server so I'm confused on your recommendation. Does that apply to my situation as well?

**Comment by orazioedoardo** [comment]
Oh nice, then just run that ufw command to allow ssh. However this does not fix your openvpn problem. Can you try forwarding ssh (port 22) through your router and check [here](https://www.yougetsignal.com/tools/open-ports/) if it acually worked. Just to be sure that your ISP is not blocking ports.

P.S. If it works then disable the forwarding since opening ssh to the world without proper configuration is a bit dangerous.
