### ISSUE TITLE
Where is shared secret in pvpn configuration

### ISSUE THREAD

**Issue by MaxCCC** [pivpn/pivpn#452]
I've successfully installed and configured PiVPN. It works as VPN to connect to my home network. Now I want to know how I can find the 'shared secret' of this setup?

When I want to connect my VPN to my cloud provider it's asking for the shared secret.

**Comment by cfcolaco** [comment]
I don't know exactly what are you trying to accomplish but if I would have to guess ... I would say that you might have to generate a certificate for whatever you are trying to connect to your VPN... if this is not the case please try to be more specific!
