### ISSUE TITLE
How to route all traffic through my OVPN server

### ISSUE THREAD

**Issue by dilipprasad** [pivpn/pivpn#454]
Hi,

I am able to setup my OVPN server successfully, and able to connect to it from my android mobile through the OPENVPN for Android app.

However not all the mobile traffic is not getting routed through my server, for example my chrome browser traffic still goes directly. 

How do i make all the traffic go through my OPEN VPN server ? I am hosting it in my pi

**Comment by git4silver** [comment]
Hi,
I am new to this project but I knew little the OPEN VPN.
Do you use UDP or TCP?
Difference is that for the TCP the whole ethernet frame will be forwarded on 3'rd osi layer. 
That will forward evrything that is going thru your network all services etc. but it will use more bandwitch nad CPU.

**Comment by cfcolaco** [comment]
@dilipprasad our configurations force all clients traffic to be routed through the OpenVPN server if you are experiencing issues regarding routing on your mobile phone it can be related with the Android OpenVPN Client, or some other issues. 

What tests have you done to confirm that? 

Don't see how can we help you on that one =/

**Comment by cezar97** [comment]
Try openvpn for Android by Arne Schwabe and make sure in the settings all apps are checked ( that's actually the default ).

**Comment by devZer0** [comment]
no response for 1 year, so this shoudl be closed if nothing new getting added soon
