### ISSUE TITLE
Cannot connect to VPN, error code = 10054

### ISSUE THREAD

**Issue by BTipold** [pivpn/pivpn#456]
## Issue
Just want to start this off saying I am not knowledgeable in this subject. 
I first followed a tutorial that had me install everything manually and at the end, openvpn got stuck on 

Fri Jan 26 14:22:58 2018 TCP/UDP: Preserving recently used remote address: [AF_INET6] (ip redacted)
Fri Jan 26 14:22:58 2018 UDP link local: (not bound)

I retried everything again but with PiVPN and I literally got the same error. I tried researching this for hours and tried:

Turning off firewall.
commenting out tls-version-min (...)
commenting out x509 (...)
starting with administrator privalages

probably more stuff that I don't remember.

## Have you searched for similar issues and solutions? 
yes
https://github.com/pivpn/pivpn/issues/275
https://github.com/pivpn/pivpn/issues/227
  
## the console output is:

Fri Jan 26 14:22:57 2018 OpenVPN 2.4.4 x86_64-w64-mingw32 [SSL (OpenSSL)] [LZO] [LZ4] [PKCS11] [AEAD] built on Sep 26 2017
Fri Jan 26 14:22:57 2018 Windows version 6.2 (Windows 8 or greater) 64bit
Fri Jan 26 14:22:57 2018 library versions: OpenSSL 1.0.2l  25 May 2017, LZO 2.10
Fri Jan 26 14:22:58 2018 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Fri Jan 26 14:22:58 2018 TCP/UDP: Preserving recently used remote address: [AF_INET6] (ip redacted)
Fri Jan 26 14:22:58 2018 UDP link local: (not bound)
Fri Jan 26 14:22:58 2018 UDP link remote: [AF_INET6] (ip redacted)
Fri Jan 26 14:22:58 2018 read UDP: Unknown error (code=10054)
Fri Jan 26 14:23:00 2018 read UDP: Unknown error (code=10054)
Fri Jan 26 14:23:04 2018 read UDP: Unknown error (code=10054)
Fri Jan 26 14:23:12 2018 read UDP: Unknown error (code=10054)
Fri Jan 26 14:23:28 2018 read UDP: Unknown error (code=10054)
Fri Jan 26 14:23:58 2018 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Fri Jan 26 14:23:58 2018 TLS Error: TLS handshake failed

**Comment by jcstill** [comment]
Same :
> Just want to start this off saying I am not knowledgeable in this subject.

However, let me get this strait, what are you installing pivpn on? It seems like you are trying to install on a Windows machine? (based on the console output)

Not trying to be condescending, but this is for a Raspberry Pi to be a VPN _server_. You need to install the windows client and use the certificates to connect to the server.

If you are trying to set up an openVPN server on a Windows box try [HERE](https://community.openvpn.net/openvpn/wiki/Easy_Windows_Guide) or [HERE](http://blog.bobbyallen.me/2016/02/07/setting-up-openvpn-server-on-windows-2012-r2/). There are many tutorials out there though. I would probably recommend that you uninstall everything. Then start from the beginning.

Sorry if this is not the help you needed.

**Comment by BTipold** [comment]
Thanks for the response. I’m installing the VPN on my RPi3 and I’m installing the client on my windows 10 machine. 

Sent from Mail for Windows 10

**Comment by cfcolaco** [comment]
you issue is quite confusing!!

Please, next time focus on providing all info requested on the form, since it is extremely important to track whatever is going on even if we cannot understand your explanation properly. 

Also, and before requestion you anything more, Please be **aware** that on Windows, you must run the OpenVPN Client Software with admin rights ... so, Mouse Right Click > Run As Administrator  ... please confirm if this solves your problem or not and provide the information in the issue template! 

thank you

**Comment by 4s3ti** [comment]
old topic .. no info.
closing.
