### ISSUE TITLE
Transfer Server Certs/Keys to New Server?

### ISSUE THREAD

**Issue by kyle95wm** [pivpn/pivpn#457]
So right now, I'm running PiVPN on a virtual machine. Everyone has a config file installed on their device. 

How would I go about moving the PiVPN stuff to a new system? Which files would I essentially need to copy over? Would I need to modify anything in the process?

Basically, the end-goal would be, transferring PiVPN from Server A (old) to Server B (new), and allow everyone who has connected before, to connect to the NEW server using the same profile.

Sorry if this is the wrong place to post this. Maybe someone can implement this as a feature, like a `pivpn transfer` command to make the process easier

**Comment by kyle95wm** [comment]
Okay, so I just spun up a new PiVPN instance, installed the software.

On the old server I ran `scp -pr openvpn/* root@192.168.101.124:/etc/openvpn/`

Everything seems to be working perfectly. Would there be any issues with doing it this way?

**Comment by cfcolaco** [comment]
Hi @kyle95wm That's really awesome input here!! I think this question already came up some time ago ... Thanks a lot for providing us with the result of your tests!! 

I don't see any issue of using that procedure, securitywise scp is ok and trafic goes encrypted so :+1: on that.

The only thing people need to be aware is to fix the IP addresses of the client.ovpn files and /etc/server.conf if applicable. 

Will Add that to our FAQ!!

**Comment by cfcolaco** [comment]
Done! 

Thank you a lot @kyle95wm 

Closing Issue
