### ISSUE TITLE
Recently setup pi-hole along with pi-vpn, noticed an unknown IP address connected through my router log this morning

### ISSUE THREAD

**Issue by sabalons** [pivpn/pivpn#458]
I've also posted this on reddit hoping to find some help. Would appreciate any advice on this matter.

I found an odd login in this morning that I'm wondering what it could be from. I just recently started using the pi-hole/pivpn setup and just did a fresh install yesterday on my Pi3. I've been checking my router logs and found this one line which I do not recognize: [LAN access from remote] from 95.215.1.37:49530 to 192.168.1.xx:11548, Sunday, Jan 28,2018 09:20:17. This IP address makes no sense, the only other login was from the openvpn client through my phone that is showing the correct IP address from my cell provider.

I didn't use the 1194 standard port during setup but instead used a random number. I set everything up based on this guide here https://marcstan.net/blog/2017/06/25/PiVPN-and-Pi-hole/ other than this odd login, I haven't had anything else that seemed out of place.

Looks like it came from a Russian IP address. Are there any logs on the Pi I can check to see what this login is from and how can I see if this was someone that managed to hack into my network or something else?

**Comment by orazioedoardo** [comment]
Some questions to begin with: 
1) Is the local IP reported on the router log the one of the Raspberry Pi?
2) Does your VPN run on port 11548 UDP?
3) Did you forward ports to clients other than raspberry pi:vpn port?
4) Do you have UPnP enables on your router?

**Comment by jcstill** [comment]
First thing I would do is turn off port forwarding. And block the IP in your router's firewall

**Comment by cfcolaco** [comment]
There is not much we can do to help you out on this one, 
If you suspect that something is wrong and you might have a breach, I would recommend: 

1) Review your firewall rules and ports
2) Change all your passwords, Routers, websites, you can assume all have been compromised. 
3) Revoke all your VPN certificates
4) Format your SDCard 
5) Reinstall PiVPN && Pi-Hole 
6) Do not reuse any credentials 

This is just a few things you can do to improve your security and privacy and to fix your suspected breach. 

Closing issue.
