### ISSUE TITLE
fail when installing 

### ISSUE THREAD

**Issue by angelflames1337** [pivpn/pivpn#46]
got this error when running the line "curl -L https://install.pivpn.io | bash"

http://i.imgur.com/o4duTUa.png

Im on Raspberry pi 2 model B, and got OSMC installed on the Pi. can i still use this as pivpn server?

**Comment by 0-kaladin** [comment]
What operating system? Seems to be missing a lot of basic commands... Does
osmc use its own OS? I'd stick with one of the supported os's.

**Comment by angelflames1337** [comment]
osmc is on debian linux, is it supported?

**Comment by 0-kaladin** [comment]
Debian is but you have very basic commands not working. Something is messing with core of Linux on your system. Since I dont know what osmc is or what it is doing I can assume it's responsible

**Comment by 0-kaladin** [comment]
maybe they restrict the osmc user and sudo doesn't work?  I'm only guessing cause i've never tested on osmc.  try running the install as a root level user and see if basic built-in linux commands are available to you like ip and whiptail.  they seem not to be avail when you ran the install before.  
OR save up and get another $35 raspberry pi if you can.

**Comment by 0-kaladin** [comment]
@angelflames1337 have you looked at this any more?
