### ISSUE TITLE
cant connect using asus router

### ISSUE THREAD

**Issue by toshibochan** [pivpn/pivpn#460]
i just buy new asus router with openvpn capable but vpn file from pivpn not coonecting. same file work with iphone and mac and GL.INET routers.
any one was able to using in asus router?

**Comment by toshibochan** [comment]
in my router show
vpnclient5[1076]: Options error: Unrecognized option or missing parameter(s) in config.ovpn:35: tls-version-min (2.3.2)

**Comment by cfcolaco** [comment]
@toshibochan I do not know much about configuring those routers as clients ... but from what I know you need to create 3 different certificate and key files from the generated .ovpn and apply the configs manually on the router. 

Can you please be more detailed? provide more logging and all needed info?

**Comment by cezar97** [comment]
As of https://github.com/Angristan/OpenVPN-install/issues/162, currently there are issues with most openvpn installer scripts and asus routers. The only one working is the Nyr's one, but personally I wouldn't use it.
We still need to investigate what is causing this.
