### ISSUE TITLE
support for tls-crypt to better hide OpenVPN traffic

### ISSUE THREAD

**Issue by kimbauters** [pivpn/pivpn#461]
This is mainly a feature request. With openvpn 2.4 being out for a while now, and OpenVPN Connect on iOS and Android finally catching up, it is now possible to better hide OpenVPN traffic using tls-crypt. This is important in cases where the network you are on is actively sniffing for VPN connections. While I understand that some public networks want to keep VPN connections away over concerns of illegal activities, I also have the concern that anyone can snoop my data when I'm connected to a public network.

With tls-crypt it is easy to better hide OpenVPN data, while at the same time further improving security. More information can be found [here](https://build.openvpn.net/doxygen/html/group__tls__crypt.html). To enable tls-crypt is surprisingly easy (assuming tls-auth is already on). All you have to do is edit `/etc/openvpn/server.conf` and change the line `tls-auth /etc/openvpn/easy-rsa/pki/ta.key 0` to `tls-crypt /etc/openvpn/easy-rsa/pki/ta.key`. For each client profile, you need to open the file and change `<tls-auth>` and `</tls-auth>` with `<tls-crypt>` and `</tls-crypt>`, respectively.

Given how easy this is, it would be nice to have this as part of a standard install, possibly as an option (to also support older clients).

_PS:_ if in your configuration file you have the optional line `key-direction 1` you will also need to remove this. If your configuration file does not have this, there is nothing else you need to do.

**Comment by orazioedoardo** [comment]
Yeah, I was about to send a pull request for that, along with `compress lz4`and improved logging, I think i’ll do it in the coming days.

**Comment by orazioedoardo** [comment]
Even more, according to [this](https://forums.openvpn.net/viewtopic.php?f=36&t=25597) we could also replace DH with ECDHE for the key exchange. Using Elliptic Curves there is no need do download or generate DH parameters and they should be faster too.

**Comment by kimbauters** [comment]
I agree, LZ4 is another great option. I would say the compression difference is indiscernible from LZO, but the speed difference is quite substantial. 

I don't have experience with ECDHE though, so I wouldn't know what needs to change there. I do think this setting is omitted by default to let client and server negotiate on their own. I assume this is the best default, but an option to enable it would indeed be quite handy.

I indeed forgot to mention to remove `key-direction 1`. None of my configuration scripts had this though, so I wonder if only certain versions of PiVPN added that?

**Comment by d0nlab** [comment]
+ thread from openvpn forums on this topic. 
Can we now do —tls-crypt v1 & v2 on iOS / Android ?

https://github.com/OpenVPN/openvpn3/issues/11

**Comment by orazioedoardo** [comment]
I've submitted a [pull request](https://github.com/pivpn/pivpn/pull/471).

**Comment by cfcolaco** [comment]
closing as per PR #471 

Thanks a lot @orazioedoardo Good job! =)
