### ISSUE TITLE
USB to Ethernet Dongle doesn't work with PiVPN

### ISSUE THREAD

**Issue by BICEPS-SEAGULL** [pivpn/pivpn#462]
I've been trying to get PiVPN to work for a few days now and it got kind of frustrating trying to figure it out on my own. Everytime I've gotten past the FYI:IP conflict window, the script would instantly terminate and give an error output of "error fetching interface information: Device not found". I am very sure this has something to do with my setup though. I have used a usb to gigabit lan adapter and it's been recognized as eth1. I have set this up using the ethernet port straight on the pi before but I want a faster transfer speed. Am I missing a step that lets me use the usb to ethernet adapter instead? I would appreciate any answers. Thank you!

**Comment by BICEPS-SEAGULL** [comment]
Okay, what's actually very curious is that I do not get interface options before the IP conflicts window. If I could somehow get it to show I could probably get this to work

**Comment by d0nlab** [comment]
Did you resolve on your own? If so how?
