### ISSUE TITLE
Start Script on Client connect/disconnect

### ISSUE THREAD

**Issue by GatoPharaoh** [pivpn/pivpn#463]
# PiVPN Issue Template

## Issue
Is it possible to use 'client-connect' and 'client-disconnect' with PiVPN? 
I would like to implement a scirpt which notifies me whenever a client connects or disconnects. However, adding the following lines to server.conf will not only not work it also prevents my clients from connecting at all.
```
script-security 3 system
client-connect /etc/openvpn/connected.sh
client-disconnect /etc/openvpn/connected.sh
```

## Have you searched for similar issues and solutions? 
    (yes/no / which issues?) 
  yes

## Console output of `curl install.pivpn.io | bash`
```
  Output Here
```

## Console output of `pivpn add` or `pivpn add nopass`
```
  Output Here
```

## Console output of `pivpn debug`
```
  Output Here
```

## Console Output of `sudo iptables -t nat -S`
```
  Output Here
```

## Console Output of `sudo iptables -S`
```
  Output Here
```

## output of `sudo netstat -uanp | grep openvpn`

```
  Output Here
```

## Have you taken any steps towards solving your issue? 
     which? 
checked every OpenVPN page to try different configurations - won't work

**Comment by orazioedoardo** [comment]
> Is it possible to use 'client-connect' and 'client-disconnect' with PiVPN?
I would like to implement a script which notifies me whenever a client connects or disconnects.

It is, however you need to be aware that such scripts are executed as `nobody` user, so make sure that no special privileges are required to run them and they are world readable. Maybe we can help more if you post the actual scripts and the output of `ls -l /etc/openvpn/*.sh`.

P.S. "Output Here" in the debug form means "post the output of the command above".

**Comment by cfcolaco** [comment]
I am not getting the issue itself, and it seems more "OpenVPN related" issue then PiVPN.... however ... 

> Is it possible to use 'client-connect' and 'client-disconnect' with PiVPN?

I am divided about such a feature, i can see use for it but at the same time i can see big caveats on that, 

1 - it can have major Privacy and security implications
2 - You should not have the need to disconnect someone from the server as this is the kind of server you don't expect someone you don't know to be using. 

what you thing @redfast00 ?

**Comment by redfast00** [comment]
I can see a use of this feature, but I don't think this is in scope of the PiVPN project, so I will be closing this issue. I think [the OpenVPN forums](https://forums.openvpn.net/) are a better place for this.
