### ISSUE TITLE
Selected port not open

### ISSUE THREAD

**Issue by keeganjk** [pivpn/pivpn#465]
I've tried using many different ports. My VPN only works when I'm on the same network as my Pi. When I run `nmap 192.168.0.27`, I get this output:
```
PORT     STATE SERVICE
22/tcp   open  ssh
80/tcp   open  http
5900/tcp open  vnc
```
My selected port isn't open.

When I scan my Public IP, it still says that my VPN port (42) is closed:
```
PORT     STATE  SERVICE
22/tcp   open   ssh
23/tcp   closed telnet
24/tcp   closed priv-mail
25/tcp   closed smtp
26/tcp   closed rsftp
32/tcp   closed unknown
37/tcp   closed time
42/tcp   closed nameserver
43/tcp   closed whois
49/tcp   closed tacacs
53/tcp   closed domain
70/tcp   closed gopher
79/tcp   closed finger
80/tcp   open   http
9091/tcp open   xmltec-xmlmail
```

Why is this and how can I fix it?

**Comment by adrianQwest** [comment]
Hi, have you opened a port in your firewall on your router?
If you have then it should show when you scan it. Use http://www.whatsmyip.org/port-scanner/ to scan the specific port.
If it isn't open you've not set it right.

**Comment by keeganjk** [comment]
Yes, I forwarded ports 22-80. 22 is open. 80 is open. 42 is not.

**Comment by adrianQwest** [comment]
what sort of router are you using?

**Comment by keeganjk** [comment]
NetGear. But I think I've found the problem— I think I forwarded TCP instead of UDP. Trying now.

**Comment by adrianQwest** [comment]
Was it a protocol prob?

**Comment by keeganjk** [comment]
Not sure. Still doesn't seem to be working...

**Comment by orazioedoardo** [comment]
What kind of error you are being reported on a client?

**Comment by adrianQwest** [comment]
When you scan a UDP port it may not appear open as there's not handshake, apparently. 
Rather than opening a range of ports why don't you open just one, port 42 in your case. I've always opened one port at a time.

**Comment by justinamcafee** [comment]
We had similar issues with an install of PiVPN, turned out the ISP was doing something weird on their end with ARP that was stopping the connection from forming. Do you get any output at all from the OpenVPN client when attempting to use the VPN? Any error messages?

**Comment by cezar97** [comment]
@keeganjk openvpn's ports will always be reported as closed thanks to tls-auth / tls-crypt. Basically it means that only packets signed with a shared key are processed by the server. This protects from dos, as the scripts already states, port scans and has some other features, too.

**Comment by 4s3ti** [comment]
> yr old thread. 
no info here
not pivpn related. 
Closing.
