### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by cmsimike** [pivpn/pivpn#47]
No problems, I just wanted to say thank you! This was the absolute most painless way I've ever setup openvpn. I really appreciate the work that went into this.

**Comment by 0-kaladin** [comment]
The over arching goal here is to get people who would not be technical enough to be able to have a "free" vpn service available to them that would help protect their traffic when they are not at home.  
The icing on the cake is that this default configuration is hardened quite more than any other generic guide I've seen out there and so even those who CAN install openvpn themselves might as well use this so it gives them a great foundation in 5 minutes.
