### ISSUE TITLE
pivpn add firewall rule for snmp

### ISSUE THREAD

**Issue by edegraaff** [pivpn/pivpn#472]
Hi, 
I want to open the snmp port to monitor my pivpn
What would be the best approach to do so without disturbing the current configuration?

Since i get this output i think the standard iptables have not been used 
root@vpn:/home/pi# iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination
Chain FORWARD (policy ACCEPT)
target     prot opt source               destination
Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
root@vpn:/home/pi#

I expected to use the following commands but i am not quite sure the pivpn script used another way to configure firewall rules

# iptables -I INPUT -p udp -m udp --dport 161 -j ACCEPT
# iptables -I INPUT -p udp -m udp --dport 162 -j ACCEPT
# iptables-save > /etc/sysconfig/iptables

**Comment by orazioedoardo** [comment]
INPUT policy is ACCEPT so you don’t need those rules, it should work as is.

**Comment by edegraaff** [comment]
Hi

That is strange since the NMS is complaining it is not able to access the pivpn device. The NMS is a different device within the interal subnet.

So the NMS uses the snmp port to assess the snmpd service i have installed in the pivpn device.

I expect the firewall on the pivon is denying all access except the openvpn port right?

⁣www.fishfreak.org

Verzonden door BlueMail ​

Op 18 feb. 2018 15:05, om 15:05, Piero <notifications@github.com> schreef:

**Comment by orazioedoardo** [comment]
As you can see [here](https://github.com/pivpn/pivpn/blob/master/auto_install/install.sh#L972) this is the only rule that gets added, it doesn’t block any listening port. In fact, to make it simple the installer leaves the filter chain as default (accept everything).

So I think it is a problem with your snmpd configuration, in such case, since the issue is not related to pivpn you may get better luck asking on [stackexchange](https://unix.stackexchange.com)

**Comment by edegraaff** [comment]
thanks i will check the snmp config

⁣www.fishfreak.org

Verzonden door BlueMail ​

Op 18 feb. 2018 15:28, om 15:28, Piero <notifications@github.com> schreef:

**Comment by edegraaff** [comment]
Found it : 
agentAddress  udp:127.0.0.1:161 needs to be changed 
agentAddress udp:161
thanks for help : solved  👍

**Comment by 4s3ti** [comment]
Clsoing.
