### ISSUE TITLE
Incomplete execution on new versions of DietPi

### ISSUE THREAD

**Issue by grahambo2015** [pivpn/pivpn#475]
# PiVPN Issue Template

## Issue
After much hassle I went back to raspbian and was able to get everything to work. During my many attempts to install and utilize PiVPN on DietPi 6.1 and 6.2 the install TUIs would stop shortly after the port and protocol selection. It never got to the FQDN or DNS server selection. However the pivpn command would still work and allow me to create .ovpn profiles. These profiles were incomplete as they did not have series of commands prior to the ca certificate block. It also appeared that the openvpn service never got to the point of starting due to there being no listening port active.

## Have you searched for similar issues and solutions? 
    Yes and none were found.
  

## Console output of `curl install.pivpn.io | bash`
```
  Output Here
```

## Console output of `pivpn add` or `pivpn add nopass`
```
  OS wiped and replaced before issue determined to be valid. Results no longer exist.
```

## Console output of `pivpn debug`
```
  OS wiped and replaced before issue determined to be valid. Results no longer exist.
```

## Console Output of `sudo iptables -t nat -S`
```
  OS wiped and replaced before issue determined to be valid. Results no longer exist.
```

## Console Output of `sudo iptables -S`
```
  OS wiped and replaced before issue determined to be valid. Results no longer exist.
```

## output of `sudo netstat -uanp | grep openvpn`

```
  OS wiped and replaced before issue determined to be valid. Results no longer exist.
```

## Have you taken any steps towards solving your issue? 
     which?

**Comment by Fourdee** [comment]
@grahambo2015 

We are unable to replicate any issues with DietPi + PiVPN currently:
https://github.com/Fourdee/DietPi/issues/1450#issuecomment-370178919

**Comment by frdrrhr** [comment]
I'm using version 6.9 of DietPi and faced the same situation today.
The installation did finish after creating the private key, so I was not asked for a "Public IP or DNS" and everything else that should have come after this step.
DietPi rebooted and I was able to create a new client, but the ovpn file could not be stored, as the "opns" folder was not created in my local user folder.
I'm happy to share any additional information, if needed.

**Comment by frdrrhr** [comment]
Hi Fourdee,

it was dietpi (root).
Thanks.

**Comment by frdrrhr** [comment]
I did also find the install.log of this try. Are you interested to have a look at it?

**Comment by Fourdee** [comment]
@frdrrhr 

> I did also find the install.log of this try. Are you interested to have a look at it?

Hi,

Although we are unable to replicate this our end, if this is still an issue, please post the logs for us to review.

**Comment by frdrrhr** [comment]
@Fourdee 
This is the file:
[install.log](https://github.com/pivpn/pivpn/files/2156759/install.log)

If needed, I can add other stuff too.
Thx.

**Comment by Fourdee** [comment]
@frdrrhr 

Thanks, apologies for the delay.

The logfile appears fine, no errors/issues reported.
