### ISSUE TITLE
Client cannot access the internet

### ISSUE THREAD

**Issue by kcha** [pivpn/pivpn#477]
Similar to #411, I am running into the same issue with no client internet connectivity. I have a fresh install of PiVPN on a Pi Zero W with Stretch Lite. UFW is installed but currently disabled. Dynamic DNS is set up and port forwarding enabled on my router.  I can successfully connect to the VPN from my Android phone over cellular network. From the phone I can SSH into the Pi and `ping google.com` works. However, everywhere else internet is not available (e.g. apps, web browser, etc.).  

## Console output of `pivpn debug`
```
::: Generating Debug Output
:::					:::
::		PiVPN Debug		 ::
:::					:::
::	Latest Commit			 ::
:::					:::
commit 25aaf24c893175894d0a54d159a10fbb74b6b463
Merge: abdce6c c414172
Author: redfast00 <redfast00@gmail.com>
Date:   Wed Feb 21 17:36:09 2018 +0100

    Merge remote-tracking branch 'origin/test'
:::					:::
::	Recursive list of files in	 ::
::	/etc/openvpn/easy-rsa/pki	 ::
:::					:::
/etc/openvpn/easy-rsa/pki/:
ca.crt
crl.pem
Default.txt
dh2048.pem
index.txt
index.txt.attr
index.txt.attr.old
index.txt.old
issued
android.ovpn
private
serial
serial.old
ta.key

/etc/openvpn/easy-rsa/pki/issued:
android.crt
server_5SR646nOZ52B1bt2.crt

/etc/openvpn/easy-rsa/pki/private:
ca.key
android.key
server_5SR646nOZ52B1bt2.key
:::					:::
::	Output of /etc/pivpn/*		 ::
:::					:::
:: START /etc/pivpn/DET_PLATFORM ::
Raspbian
:: END /etc/pivpn/DET_PLATFORM ::
:: START /etc/pivpn/INSTALL_PORT ::
1129
:: END /etc/pivpn/INSTALL_PORT ::
:: START /etc/pivpn/INSTALL_PROTO ::
udp
:: END /etc/pivpn/INSTALL_PROTO ::
:: START /etc/pivpn/INSTALL_USER ::
pi
:: END /etc/pivpn/INSTALL_USER ::
:: START /etc/pivpn/NO_UFW ::
1
:: END /etc/pivpn/NO_UFW ::
:: START /etc/pivpn/pivpnINTERFACE ::
wlan0
:: END /etc/pivpn/pivpnINTERFACE ::
:::					:::
:: /etc/openvpn/easy-rsa/pki/Default.txt ::
:::					:::
client
dev tun
proto udp
remote ***** 1129
resolv-retry infinite
nobind
persist-key
persist-tun
key-direction 1
remote-cert-tls server
tls-version-min 1.2
verify-x509-name server_5SR646nOZ52B1bt2 name
cipher AES-256-CBC
auth SHA256
comp-lzo
verb 3
:::					:::
::	Debug Output Complete		 ::
:::					:::
:::
::: Debug output completed above.
::: Copy saved to /tmp/debug.txt
:::
```

## Console Output of `sudo iptables -t nat -S`
```
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT
-A POSTROUTING -s 10.8.0.0/24 -o wlan0 -j MASQUERADE
```

## Console Output of `sudo iptables -S`
```
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
```

## output of `sudo netstat -uanp | grep openvpn`

```
udp        0      0 0.0.0.0:1129            0.0.0.0:*                           349/openvpn
```

## server.conf

```
dev tun
proto udp
port 1129
ca /etc/openvpn/easy-rsa/pki/ca.crt
cert /etc/openvpn/easy-rsa/pki/issued/server_5SR646nOZ52B1bt2.crt
key /etc/openvpn/easy-rsa/pki/private/server_5SR646nOZ52B1bt2.key
dh /etc/openvpn/easy-rsa/pki/dh2048.pem
topology subnet
server 10.8.0.0 255.255.255.0
# Set your primary domain name server address for clients
push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 8.8.4.4"
# Override the Client default gateway by using 0.0.0.0/1 and
# 128.0.0.0/1 rather than 0.0.0.0/0. This has the benefit of
# overriding but not wiping out the original default gateway.
push "redirect-gateway def1"
client-to-client
keepalive 10 120
remote-cert-tls client
tls-version-min 1.2
tls-auth /etc/openvpn/easy-rsa/pki/ta.key 0
cipher AES-256-CBC
auth SHA256
comp-lzo
user nobody
group nogroup
persist-key
persist-tun
crl-verify /etc/openvpn/crl.pem
status /var/log/openvpn-status.log 20
status-version 3
syslog
verb 3
# Generated for use by PiVPN.io
```

## resolv.conf:
```
# Generated by resolvconf
nameserver 8.8.8.8
nameserver 8.8.4.4
```

## Have you taken any steps towards solving your issue? 
As per #207, I tried calling `sudo iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o wlan0 -j MASQUERADE`; but it doesn't make any difference in my case. Enabling UFW doesn't change anything either.

I also tried commenting out `push "redirect-gateway def1"` in `/etc/openvpn/server.conf`. Contrary to the [FAQ](https://github.com/pivpn/pivpn/wiki/FAQ#allow-clients-to-connect-but-block-their-access-to-the-internet), internet access was restored, but I could no longer SSH into the Pi. Also, the external IP was that of my cellular network. So I'm unsure if the VPN is behaving as expected?

**Comment by orazioedoardo** [comment]
Try this steps:

- Remove `push "redirect-gateway def1"`
- Add `push "route NETWORK_ID 255.255.255.0"`
- Restart the server with `sudo systemctl restart openvpn`
- Connect again from your smartphone (using cellular network is fine)
- Try to access your router web page

NETWORK_ID is usually your router’s ip with the last number replaced with 0. Example, if the IP is 192.168.1.1 you write 192.168.1.0

**Comment by kcha** [comment]
Thank you for the suggestion! I followed these steps and I can _almost_ access my router login page. The login page doesn't quite finish loading and the progress bar stalls at about 40%. It won't let me proceed with logging in either. On the other hand, it looks other websites load fine and I can SSH into my Pi. Feels like I'm almost there but not sure what else to try!

**Comment by orazioedoardo** [comment]
Ok, if the router web page is somehow loading we know that forwarding and masquerading is working.
Internet access is working but you are browsing with your normal IP.

- Save iptables rules: `sudo sh -c "iptables-save > /etc/iptables/rules.v4"`
- Revert to `push “redirect-gateway def1”`
- Restart the server (better reboot if you can)
- Check if the iptables rule is still in place `sudo iptables -t nat -vnL POSTROUTING` (you should see MASQUERADE rule)
- Connect your smartphone
- Try to visit the router login page, this ip 216.58.205.142 (it’s google), then [check your ip](https://whatismyipaddress.com).
- Post the output of `cat /var/log/openvpn.log` (omit your client’s ip).

**Comment by kcha** [comment]
I restored `push "redirect-gateway def"` and to be clear, `push "route NETWORK_ID 255.255.255.0"` is still there. After rebooting, I confirmed that the MASQUERADE rule is still in place.

Unfortunately, my phone could not reach the router page. The IP 216.58.205.142 seems to resolve to google.com (address bar changes to google.com), but is not able to reach it and times out. Lastly, I could not reach whatismyipaddress.com either.

Here is the openvpn.log
```
Feb 24 16:17:09 raspberrypi ovpn-server[273]: OpenVPN 2.4.0 arm-unknown-linux-gnueabihf [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jul 18 2017
Feb 24 16:17:09 raspberrypi ovpn-server[273]: library versions: OpenSSL 1.0.2l  25 May 2017, LZO 2.08
Feb 24 16:17:09 raspberrypi ovpn-server[290]: Diffie-Hellman initialized with 2048 bit key
Feb 24 16:17:09 raspberrypi ovpn-server[290]: Outgoing Control Channel Authentication: Using 256 bit message hash 'SHA256' for HMAC authentication
Feb 24 16:17:09 raspberrypi ovpn-server[290]: Incoming Control Channel Authentication: Using 256 bit message hash 'SHA256' for HMAC authentication
Feb 24 16:17:09 raspberrypi ovpn-server[290]: TUN/TAP device tun0 opened
Feb 24 16:17:09 raspberrypi ovpn-server[290]: TUN/TAP TX queue length set to 100
Feb 24 16:17:09 raspberrypi ovpn-server[290]: do_ifconfig, tt->did_ifconfig_ipv6_setup=0
Feb 24 16:17:09 raspberrypi ovpn-server[290]: /sbin/ip link set dev tun0 up mtu 1500
Feb 24 16:17:09 raspberrypi ovpn-server[290]: /sbin/ip addr add dev tun0 10.8.0.1/24 broadcast 10.8.0.255
Feb 24 16:17:09 raspberrypi ovpn-server[290]: Could not determine IPv4/IPv6 protocol. Using AF_INET
Feb 24 16:17:09 raspberrypi ovpn-server[290]: Socket Buffers: R=[163840->163840] S=[163840->163840]
Feb 24 16:17:09 raspberrypi ovpn-server[290]: UDPv4 link local (bound): [AF_INET][undef]:1129
Feb 24 16:17:09 raspberrypi ovpn-server[290]: UDPv4 link remote: [AF_UNSPEC]
Feb 24 16:17:09 raspberrypi ovpn-server[290]: GID set to nogroup
Feb 24 16:17:09 raspberrypi ovpn-server[290]: UID set to nobody
Feb 24 16:17:09 raspberrypi ovpn-server[290]: MULTI: multi_init called, r=256 v=256
Feb 24 16:17:09 raspberrypi ovpn-server[290]: IFCONFIG POOL: base=10.8.0.2 size=252, ipv6=0
Feb 24 16:17:09 raspberrypi ovpn-server[290]: Initialization Sequence Completed
Feb 24 16:20:50 raspberrypi ovpn-server[290]: xx.xxx.xx.xx:12783 TLS: Initial packet from [AF_INET]xx.xxx.xx.xx:12783, sid=6df329e2 f738cc2e
Feb 24 16:20:50 raspberrypi ovpn-server[290]: xx.xxx.xx.xx:12783 VERIFY OK: depth=1, CN=ChangeMe
Feb 24 16:20:50 raspberrypi ovpn-server[290]: xx.xxx.xx.xx:12783 Validating certificate key usage
Feb 24 16:20:50 raspberrypi ovpn-server[290]: xx.xxx.xx.xx:12783 ++ Certificate has key usage  0080, expects 0080
Feb 24 16:20:50 raspberrypi ovpn-server[290]: xx.xxx.xx.xx:12783 VERIFY KU OK
Feb 24 16:20:50 raspberrypi ovpn-server[290]: xx.xxx.xx.xx:12783 Validating certificate extended key usage
Feb 24 16:20:50 raspberrypi ovpn-server[290]: xx.xxx.xx.xx:12783 ++ Certificate has EKU (str) TLS Web Client Authentication, expects TLS Web Client Authentication
Feb 24 16:20:50 raspberrypi ovpn-server[290]: xx.xxx.xx.xx:12783 VERIFY EKU OK
Feb 24 16:20:50 raspberrypi ovpn-server[290]: xx.xxx.xx.xx:12783 VERIFY OK: depth=0, CN=android
Feb 24 16:20:50 raspberrypi ovpn-server[290]: xx.xxx.xx.xx:12783 peer info: IV_GUI_VER=OC30Android
Feb 24 16:20:50 raspberrypi ovpn-server[290]: xx.xxx.xx.xx:12783 peer info: IV_VER=3.1.2
Feb 24 16:20:50 raspberrypi ovpn-server[290]: xx.xxx.xx.xx:12783 peer info: IV_PLAT=android
Feb 24 16:20:50 raspberrypi ovpn-server[290]: xx.xxx.xx.xx:12783 peer info: IV_NCP=2
Feb 24 16:20:50 raspberrypi ovpn-server[290]: xx.xxx.xx.xx:12783 peer info: IV_TCPNL=1
Feb 24 16:20:50 raspberrypi ovpn-server[290]: xx.xxx.xx.xx:12783 peer info: IV_PROTO=2
Feb 24 16:20:50 raspberrypi ovpn-server[290]: xx.xxx.xx.xx:12783 peer info: IV_LZO=1
Feb 24 16:20:50 raspberrypi ovpn-server[290]: xx.xxx.xx.xx:12783 peer info: IV_AUTO_SESS=1
Feb 24 16:20:51 raspberrypi ovpn-server[290]: xx.xxx.xx.xx:12783 Control Channel: TLSv1.2, cipher TLSv1/SSLv3 ECDHE-RSA-AES256-GCM-SHA384, 2048 bit RSA
Feb 24 16:20:51 raspberrypi ovpn-server[290]: xx.xxx.xx.xx:12783 [android] Peer Connection Initiated with [AF_INET]xx.xxx.xx.xx:12783
Feb 24 16:20:51 raspberrypi ovpn-server[290]: android/xx.xxx.xx.xx:12783 MULTI_sva: pool returned IPv4=10.8.0.2, IPv6=(Not enabled)
Feb 24 16:20:51 raspberrypi ovpn-server[290]: android/xx.xxx.xx.xx:12783 MULTI: Learn: 10.8.0.2 -> android/xx.xxx.xx.xx:12783
Feb 24 16:20:51 raspberrypi ovpn-server[290]: android/xx.xxx.xx.xx:12783 MULTI: primary virtual IP for android/xx.xxx.xx.xx:12783: 10.8.0.2
Feb 24 16:20:51 raspberrypi ovpn-server[290]: android/xx.xxx.xx.xx:12783 PUSH: Received control message: 'PUSH_REQUEST'
Feb 24 16:20:51 raspberrypi ovpn-server[290]: android/xx.xxx.xx.xx:12783 SENT CONTROL [android]: 'PUSH_REPLY,route 192.168.1.0 255.255.255.0,dhcp-option DNS 8.8.8.8,dhcp-option DNS 8.8.4.4,redirect-gateway def1,route-gateway 10.8.0.1,topology subnet,ping 10,ping-restart 120,ifconfig 10.8.0.2 255.255.255.0,peer-id 0,cipher AES-256-GCM' (status=1)
Feb 24 16:20:51 raspberrypi ovpn-server[290]: android/xx.xxx.xx.xx:12783 Data Channel Encrypt: Cipher 'AES-256-GCM' initialized with 256 bit key
Feb 24 16:20:51 raspberrypi ovpn-server[290]: android/xx.xxx.xx.xx:12783 Data Channel Decrypt: Cipher 'AES-256-GCM' initialized with 256 bit key
```

**Comment by orazioedoardo** [comment]
Regarding the push lines, they do not conflict:  `push “redirect-gateway def1”` instructs the server to tell the client to redirect ALL traffic through the vpn, `push “route 192.168.1.0 255.255.255.0“` instructs the server to tell the client how to reach your just LOCAL network.
The first rule, therefore, makes the second redundant. If you have JUST the second rule your smartphone will know how to reach the local clients (as your router login page for example) but it will not redirect the other traffic through the vpn (that’s why other websites loaded fine (with your cellular network ip).
Putting these aside, I’m not seeing any error in the log, you confimed that the MASQUERADE rule is set too, so it should work. However I still have some scenarios to try:

- Connect your smartphone to wifi network (NOT your home network, important) and check the result
- Try to connect from a computer/different device
- Maybe mtu issue? [See this](https://github.com/pivpn/pivpn/issues/54)

**Comment by kcha** [comment]
Again, thanks for your explanation and suggestions! IP forwarding is indeed enabled. Incredibly, your third suggestion solved my issues with immediate effect!! Also helps that I'm on the same cellular network as that user. Everything seems to be working as it should on my phone now. The three websites suggested above all work (router, google, IP), and the IP is that of the VPN host. I will test the VPN over a different wifi network and on different devices over the next week. Hoping to get Pihole installed next! I'm closing this issue; but will post again if I run into any issues. Thanks again, @orazioedoardo!

**Comment by brnl** [comment]
@kcha what exactly fixed your problem? The MTU issue?

**Comment by lukini26** [comment]
TY @orazioedoardo  , this 3 steps solve my problem  of no internet conecction on clients
sudo apt remove --purge ufw
Remove push "redirect-gateway def1"
Add push "route NETWORK_ID 255.255.255.0"

**Comment by HarvsG** [comment]
Just came here to say I had the same issue and debug output as @kcha and it was fixed by https://github.com/pivpn/pivpn/issues/54, as @kcha's comment wasn't that clear which solution fixed it for him.

**Comment by kcha** [comment]
@HarvsG, glad you resolved your issue! You're right my comment wasn't clear. I've edited to include a link to the relevant issue.
