### ISSUE TITLE
Exiting due to fatal error

### ISSUE THREAD

**Issue by DemianTinkiel** [pivpn/pivpn#48]
Probably nothing to do with the script itself but I would appreciate some help if you can spare the time. Getting 
`Sat Jun 18 17:23:42 2016 Control Channel Authentication: using '/etc/openvpn/easy-rsa/keys/ta.key' as a OpenVPN static key file
Sat Jun 18 17:23:42 2016 ERROR: Cannot open TUN/TAP dev /dev/net/tun: No such file or directory (errno=2)
Sat Jun 18 17:23:42 2016 Exiting due to fatal error
`
Would you know how I can debug this issue. Could sure use that -d option now :smile:

**Comment by 0-kaladin** [comment]
When do you get that?  on trying to start openvpn?  have you tried rebooting?
what is your OS?

**Comment by DemianTinkiel** [comment]
I'm running this on a pi2 running jessie. Did a warm reboot and didn't
help. Trying a cold one now. I get this as soon as I start the open vpn
service. Thanks.

**Comment by 0-kaladin** [comment]
can you try running these two commands as sudo, and try starting openvpn again?
```
mkdir /dev/net
mknod /dev/net/tun c 10 200
```

**Comment by DemianTinkiel** [comment]
done
`Sat Jun 18 22:58:21 2016 ERROR: Cannot open TUN/TAP dev /dev/net/tun: No such device (errno=19)
`

**Comment by 0-kaladin** [comment]
try
`modprobe tun`

did you install as root or a normal user?
try running the uninstall then reboot then install again as root?

**Comment by DemianTinkiel** [comment]
`$modprobe tun
modprobe: ERROR: could not insert 'tun': Operation not permitted
`
Installed as normal. Uninstalling now, will update when finished. Thanks!

**Comment by 0-kaladin** [comment]
@DemianTinkiel reinstall as root help?

**Comment by DemianTinkiel** [comment]
Sorry for the delay. Had to se install from scratch, got into kernel panic
after reboot. Will update when done

**Comment by 0-kaladin** [comment]
@DemianTinkiel I'll close this after another few days if no response.  Just FYI.

**Comment by DemianTinkiel** [comment]
Sorry for the delay. Had to reinstall everything and it took longer than I
expected it to. I think you can close it since I can't reproduce the issue
now. Thanks for the help
