### ISSUE TITLE
Latest version 

### ISSUE THREAD

**Issue by soydepr** [pivpn/pivpn#480]
What is the latest versiónof pivpn , on my pi i am running 1.9 and want to upgrade to latest version , how i do that ?

**Comment by cfcolaco** [comment]
hi @soydepr 

here you have all the info you need: 

https://github.com/pivpn/pivpn/releases

https://github.com/pivpn/pivpn/wiki/Upgrading

Closing.

**Comment by soydepr** [comment]
Thanks. Helpful. I do have one question. Which version of OVPN does pivpn uses now
