### ISSUE TITLE
Migration FAQ entry is wrong

### ISSUE THREAD

**Issue by Jekotia** [pivpn/pivpn#481]
Small issue with the wiki. https://github.com/pivpn/pivpn/wiki/FAQ#how-can-i-migrate-my-configs-to-another-pivpn-instance

The supplied command, scp -pr /etc/openvpn/* root@192.168.101.124:/etc/ , would copy the CONTENTS of /etc/openvpn to /etc. The wildcard should be removed.

**Comment by cfcolaco** [comment]
Cool! Nice catch!! 

My bad not looking at it properly when copied the info to put it there. 

Fixed! 

Thanks a lot!
