### ISSUE TITLE
Not adding local network

### ISSUE THREAD

**Issue by cfcolaco** [pivpn/pivpn#482]
```
push "route <localnet> <localNetMask>"
```

Not being added to /etc/openvpn/server.conf 

Was this removed in any PR? Reason? 
Just me noticing this? 

Needs testing and investigation, otherwise, users installing OpenVPN with PiVPN won't have access to local network devices.

**Comment by orazioedoardo** [comment]
Because it’s not [required](https://github.com/pivpn/pivpn/pull/379)

**Comment by cfcolaco** [comment]
Cool!! Haven't noticed... been busy months to many things to remember some are going to miss! =p 

 Thanks a lot @orazioedoardo closing then!!
