### ISSUE TITLE
DH still being generated instead of ECDSA?

### ISSUE THREAD

**Issue by mattbxd** [pivpn/pivpn#483]
# PiVPN Issue Template

As per https://github.com/pivpn/pivpn/pull/471 commit, elliptic curve support is introduced. However, when I run the script to install, once it gets to "Encryption Strength" screen, I choose 2048 bit, it creates the RSA certificate. The next screen then proceeds to generate the Diffie-Hellman and HMAC key. 

Next, the prompt comes up to asks to enable OpenVPN 2.4 features. Am I wrong in thinking that DH shouldn't have been generated here? Shouldn't elliptic curves have been used instead? 

After transferring ovpn to my phone and using OpenVPN for Android client, I connect and the log shows this

Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-**RSA**-AES256-GCM-SHA384, 2048 bit RSA

My server.conf shows "dh none" though

openvpn:
  Installed: 2.4.0-6+deb9u2
  Candidate: 2.4.0-6+deb9u2
  Version table:
 *** 2.4.0-6+deb9u2 500
        500 http://mirrordirector.raspbian.org/raspbian stretch/main armhf Packages
        100 /var/lib/dpkg/status

Thanks

## Have you searched for similar issues and solutions? 
    (yes/no / which issues?) 
  

## Console output of `curl install.pivpn.io | bash`
```
  Output Here
```

## Console output of `pivpn add` or `pivpn add nopass`
```
  Output Here
```

## Console output of `pivpn debug`
```
::: Generating Debug Output
:::					:::
::		PiVPN Debug		 ::
:::					:::
::	Latest Commit			 ::
:::					:::
commit 25aaf24c893175894d0a54d159a10fbb74b6b463
Merge: abdce6c c414172
Author: redfast00 <redfast00@gmail.com>
Date:   Wed Feb 21 17:36:09 2018 +0100

    Merge remote-tracking branch 'origin/test'
:::					:::
::	Recursive list of files in	 ::
::	/etc/openvpn/easy-rsa/pki	 ::
:::					:::
/etc/openvpn/easy-rsa/pki/:
ca.crt
crl.pem
Default.txt
index.txt
index.txt.attr
index.txt.attr.old
index.txt.old
issued
private
serial
serial.old
ta.key
test.ovpn

/etc/openvpn/easy-rsa/pki/issued:
server_MGlyLE1QumIacuYH.crt
test.crt

/etc/openvpn/easy-rsa/pki/private:
ca.key
server_MGlyLE1QumIacuYH.key
test.key
:::					:::
::	Output of /etc/pivpn/*		 ::
:::					:::
:: START /etc/pivpn/DET_PLATFORM ::
Raspbian
:: END /etc/pivpn/DET_PLATFORM ::
:: START /etc/pivpn/INSTALL_PORT ::
1194
:: END /etc/pivpn/INSTALL_PORT ::
:: START /etc/pivpn/INSTALL_PROTO ::
udp
:: END /etc/pivpn/INSTALL_PROTO ::
:: START /etc/pivpn/INSTALL_USER ::
pi
:: END /etc/pivpn/INSTALL_USER ::
:: START /etc/pivpn/NO_UFW ::
1
:: END /etc/pivpn/NO_UFW ::
:: START /etc/pivpn/pivpnINTERFACE ::
eth0
:: END /etc/pivpn/pivpnINTERFACE ::
:: START /etc/pivpn/TWO_POINT_FOUR ::
:: END /etc/pivpn/TWO_POINT_FOUR ::
:::					:::
:: /etc/openvpn/easy-rsa/pki/Default.txt ::
:::					:::
client
dev tun
proto udp
remote x.x.x.x 1194
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
tls-version-min 1.2
verify-x509-name server_MGlyLE1QumIacuYH name
cipher AES-256-CBC
auth SHA256
compress lz4
verb 3
```

## server.conf`

```
dev tun
proto udp
port 1194
ca /etc/openvpn/easy-rsa/pki/ca.crt
cert /etc/openvpn/easy-rsa/pki/issued/server_iafoVIpw5urPIXRX.crt
key /etc/openvpn/easy-rsa/pki/private/server_iafoVIpw5urPIXRX.key
dh none
topology subnet
server 10.8.0.0 255.255.255.0
# Set your primary domain name server address for clients
push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 8.8.4.4"
# Override the Client default gateway by using 0.0.0.0/1 and
# 128.0.0.0/1 rather than 0.0.0.0/0. This has the benefit of
# overriding but not wiping out the original default gateway.
push "redirect-gateway def1"
client-to-client
keepalive 10 120
remote-cert-tls client
tls-version-min 1.2
tls-crypt /etc/openvpn/easy-rsa/pki/ta.key
cipher AES-256-CBC
auth SHA256
compress lz4
user nobody
group nogroup
persist-key
persist-tun
crl-verify /etc/openvpn/crl.pem
status /var/log/openvpn-status.log 20
status-version 3
syslog
verb 3
# Generated for use by PiVPN.io 
```

## Have you taken any steps towards solving your issue? 
     which?

**Comment by orazioedoardo** [comment]
Oh, I forgot to update the whiptail dialog text, indeed DH parameters are not generated.

**Comment by mattbxd** [comment]
Hmm, excuse my ignorance but shouldn't the cipher state the following if it is using the elliptic curve?

ECDHE-ECDSA-AES256-GCM-SHA384 

instead of 

ECDHE-RSA-AES256-GCM-SHA384

**Comment by orazioedoardo** [comment]
Elliptic curves can be used for the authentication, for the key exchange, or both. For now, elliptic curves are used for the key exchange (ECDHE) but authentication is still done using RSA certificates.

**Comment by neburs** [comment]
i have the same problem. Is possible to configure pivpn to work using dh parameter?

**Comment by orazioedoardo** [comment]
I don’t see why this is a problem but if you want to use dh parameters, here’s how to do it:
`sudo -i`
`cd /etc/openvpn/easy-rsa/pki`
`openssl dhparam -out dhparam.pem 2048` (change 2048 accordingly to the key size you chose during `installation)`
Edit `/etc/openvpn/server.conf`, remove `dh none` and `ecdh-curve secp384r1`, then add `dh /etc/openvpn/easy-rsa/pki/dhparam.pem`
Restart the server with `sudo systemctl restart openvpn`
