### ISSUE TITLE
Port Forwarding/ Connection Issues

### ISSUE THREAD

**Issue by waraulston** [pivpn/pivpn#485]
I have set up an open VPN server on my Raspberry Pi 3 using PiVPN, and everything is working up to the point where I am connecting. when i try to connect to the server from the client Windows 10 PC, I get this error.
```
Wed Feb 28 16:47:53 2018 RESOLVE: Cannot resolve host address: IPv4pub:1194 (No such host is known. )
Wed Feb 28 16:47:53 2018 Could not determine IPv4/IPv6 protocol
```
I have no idea what this could mean, but i think it has something to do with Port Forwarding. ANy Help would be much appreciated.

**Comment by waraulston** [comment]
Here is the full code that the OpenVPN client sends me.
```
Wed Feb 28 16:50:31 2018 SIGUSR1[soft,init_instance] received, process restarting
Wed Feb 28 16:50:31 2018 MANAGEMENT: >STATE:1519854631,RECONNECTING,init_instance,,,,,
Wed Feb 28 16:50:31 2018 Restart pause, 160 second(s)
Wed Feb 28 16:53:11 2018 MANAGEMENT: >STATE:1519854791,RESOLVE,,,,,,
Wed Feb 28 16:53:11 2018 RESOLVE: Cannot resolve host address: IPv4pub:1194 (No such host is known. )
Wed Feb 28 16:53:11 2018 MANAGEMENT: >STATE:1519854791,RESOLVE,,,,,,
Wed Feb 28 16:53:12 2018 RESOLVE: Cannot resolve host address: IPv4pub:1194 (No such host is known. )
Wed Feb 28 16:53:12 2018 Could not determine IPv4/IPv6 protocol
```

**Comment by Reedler01** [comment]
You need to login to your isp home router and forward that port 1194 to the ip address of your pivpn.

**Comment by waraulston** [comment]
![image](https://user-images.githubusercontent.com/36906196/36817053-c9e8349c-1cad-11e8-800c-1b39d4bd466f.png)
The Pi's IP is 192.168.0.13 and this is th port forwarding config on my router.

**Comment by waraulston** [comment]
When I first set up the VPN, I set up the port as 19132. Then I tried the port forwarding and it did not work. After that, I changed the port of the server in /etc/openvpn/server.conf to 1194. I set up the port forwarding in the way that is shown in the picture. Then I generated a new profile and attempted to connecct to the server and it gives the same message
```
Wed Feb 28 17:40:07 2018 SIGUSR1[soft,init_instance] received, process restarting
Wed Feb 28 17:40:07 2018 MANAGEMENT: >STATE:1519857607,RECONNECTING,init_instance,,,,,
Wed Feb 28 17:40:07 2018 Restart pause, 80 second(s)
Wed Feb 28 17:41:27 2018 MANAGEMENT: >STATE:1519857687,RESOLVE,,,,,,
Wed Feb 28 17:41:28 2018 RESOLVE: Cannot resolve host address: IPv4pub:1194 (No such host is known. )
Wed Feb 28 17:41:28 2018 MANAGEMENT: >STATE:1519857688,RESOLVE,,,,,,
Wed Feb 28 17:41:29 2018 RESOLVE: Cannot resolve host address: IPv4pub:1194 (No such host is known. )
Wed Feb 28 17:41:29 2018 Could not determine IPv4/IPv6 protocol
Wed Feb 28 17:41:29 2018 SIGUSR1[soft,init_instance] received, process restarting
Wed Feb 28 17:41:29 2018 MANAGEMENT: >STATE:1519857689,RECONNECTING,init_instance,,,,,
Wed Feb 28 17:41:29 2018 Restart pause, 160 second(s)
```

**Comment by orazioedoardo** [comment]
Did you choose to login via public ip or dynamic dns?

**Comment by waraulston** [comment]
I used Public IP, I did not want ot have to make a domain. I can just reinstall the program and switch to the Dynamic DNS if that would be easier. Did my Port Forwarding configuration look correct in the picture above?

**Comment by orazioedoardo** [comment]
It looks correct, does your client config include this line: `remote IPv4pub 1194`? Because if it does you need to change `IPv4pub` to the actual public IP (which should have been place there by the script in the first place).

**Comment by waraulston** [comment]
Yes it has that line, The script did not include the public IP. Sorry I want to be sure, Where would i find that public ip.

**Comment by orazioedoardo** [comment]
Run `wget -qO- http://ipecho.net/plain` on your Raspberry Pi

**Comment by waraulston** [comment]
Then i just insert that IP into the ovpn file right?

**Comment by orazioedoardo** [comment]
Yes, and [fix the template](https://github.com/pivpn/pivpn/wiki/FAQ) too (second question), so that future clients will get the IP.

**Comment by Reedler01** [comment]
Try using TCP UDP

**Comment by Reedler01** [comment]
Actually UDP should work. Firewall settings on your router?

**Comment by waraulston** [comment]
Okay, I did all of that, now when I try to connect it does not give that same error message, now it says this:
```
Thu Mar 01 15:51:38 2018 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Thu Mar 01 15:51:38 2018 TLS Error: TLS handshake failed
```
Any troubleshooting ideas to do with this would be much appreciated!

**Comment by waraulston** [comment]
Here are the Firewall settings
![image](https://user-images.githubusercontent.com/36906196/36869365-8c857314-1d69-11e8-89e9-490dc97756c6.png)

**Comment by waraulston** [comment]
These are the errors coming to me when i try to connect to the VPN
```
Thu Mar 01 16:24:44 2018 OpenSSL: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
Thu Mar 01 16:24:44 2018 TLS_ERROR: BIO read tls_read_plaintext error
Thu Mar 01 16:24:44 2018 TLS Error: TLS object -> incoming plaintext read error
Thu Mar 01 16:24:44 2018 TLS Error: TLS handshake failed
```
Please tell me how to fix it
