### ISSUE TITLE
Certificate Verify Failed, Please Help

### ISSUE THREAD

**Issue by waraulston** [pivpn/pivpn#487]
## Issue
I have set up a PiVPN server running on my Raspberry Pi 3. I have everything figured out except that when i go to connect a OpenSSL ERROR and  a TSL ERROR pop up on my client.

## Have you searched for similar issues and solutions? 
 I have searched for some issues, but nothing that i have found has made any sense, or has to do with other OSes or not a PiVPN.
  
## Console output of `pivpn debug`
```
 
::: Generating Debug Output
:::                                     :::
::              PiVPN Debug              ::
:::                                     :::
::      Latest Commit                    ::
:::                                     :::
commit 25aaf24c893175894d0a54d159a10fbb74b6b463
Merge: abdce6c c414172
Author: redfast00 <redfast00@gmail.com>
Date:   Wed Feb 21 17:36:09 2018 +0100

    Merge remote-tracking branch 'origin/test'
:::                                     :::
::      Recursive list of files in       ::
::      /etc/openvpn/easy-rsa/pki        ::
:::                                     :::
/etc/openvpn/easy-rsa/pki/:
ca.crt
crl.pem
Default.txt
dh2048.pem
index.txt
index.txt.attr
index.txt.attr.old
index.txt.old
issued
PC.ovpn
private
serial
serial.old
ta.key
Will2.ovpn
WILL2.ovpn
WillLaptop.ovpn
Will.ovpn
WILL.ovpn

/etc/openvpn/easy-rsa/pki/issued:
server_MXF0LSpZuoZYLVtn.crt
WillLaptop.crt

/etc/openvpn/easy-rsa/pki/private:
ca.key
server_MXF0LSpZuoZYLVtn.key
WillLaptop.key
:::                                     :::
::      Output of /etc/pivpn/*           ::
:::                                     :::
:: START /etc/pivpn/DET_PLATFORM ::
Raspbian
:: END /etc/pivpn/DET_PLATFORM ::
:: START /etc/pivpn/INSTALL_PORT ::
19132
:: END /etc/pivpn/INSTALL_PORT ::
:: START /etc/pivpn/INSTALL_PROTO ::
udp
:: END /etc/pivpn/INSTALL_PROTO ::
:: START /etc/pivpn/INSTALL_USER ::
pi
:: END /etc/pivpn/INSTALL_USER ::
:: START /etc/pivpn/NO_UFW ::
1
:: END /etc/pivpn/NO_UFW ::
:: START /etc/pivpn/pivpnINTERFACE ::
eth0
:: END /etc/pivpn/pivpnINTERFACE ::
:::                                     :::
:: /etc/openvpn/easy-rsa/pki/Default.txt ::
:::                                     :::
client
dev tun
proto udp
remote 104.xxx.xxx.xx 1194
resolv-retry infinite
nobind
persist-key
persist-tun
key-direction 1
remote-cert-tls server
tls-version-min 1.2
verify-x509-name SRVRNAME name
cipher AES-256-CBC
auth SHA256
comp-lzo
verb 3
:::                                     :::
::      Debug Output Complete            ::
:::                                     :::
:::
::: Debug output completed above.
::: Copy saved to /tmp/debug.txt
:::

```

## Console Output of `sudo iptables -t nat -S`
```
 -P PREROUTING ACCEPT
-P INPUT ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT
-A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE

```

## Console Output of `sudo iptables -S`
```
 -P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT

```

## output of `sudo netstat -uanp | grep openvpn`

```
udp        0      0 0.0.0.0:1194            0.0.0.0:*                           5442/openvpn 
```

## What the Client says to me when i attempt to connect

```
Thu Mar 01 16:59:58 2018 OpenSSL: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
Thu Mar 01 16:59:58 2018 TLS_ERROR: BIO read tls_read_plaintext error
Thu Mar 01 16:59:58 2018 TLS Error: TLS object -> incoming plaintext read error
Thu Mar 01 16:59:58 2018 TLS Error: TLS handshake failed
```

## Have you taken any steps towards solving your issue? 
Since I saw it was something to do with the certificate, I revoked all certificated I had made and generated new ones, which did nothing. I truly have no idea what to do, so any help would be much appreciated!

**Comment by orazioedoardo** [comment]
- On the PiVPN run `tail -f /var/log/openvpn.log`, this will show you the server log in real time
- Try to connect a client
- Check whether in the above log you see any activity

If you do, then post such log (omit your client ip if you see it).

**Comment by waraulston** [comment]
It may be worth noting that i am emailing the ovpn files to myself, maybe that could cause them to be invalid?

**Comment by waraulston** [comment]
I will not be able to try the command you have given me for a few hours, as I am at work

**Comment by waraulston** [comment]
This is the output when I do tail `-f /var/log/openvpn.log`
```
tail: cannot open '/var/log/openvpn.log' for reading: No such file or directory
tail: no files remaining
```

**Comment by orazioedoardo** [comment]
Restsrt the server with `sudo systemctl restart openvpn` then try again

**Comment by waraulston** [comment]
This is what happens when i do it
pi@192:~ $ sudo systemctl restart openvpn
pi@192:~ $ tail -f /var/log/openvpn.log
tail: cannot open '/var/log/openvpn.log' for reading: No such file or directory
tail: no files remaining
pi@192:~ $

**Comment by orazioedoardo** [comment]
So OpenVPN is not starting at all. To be fair, at this point I would just reinstall stretch and PiVPN.

**Comment by waraulston** [comment]
is stretch the os i am supposed to be running on? I am using Rasbian

**Comment by waraulston** [comment]
I have been using Jessie instead of Stretch
That is probably a problem right?

**Comment by orazioedoardo** [comment]
No you can still use jessie. Actually I suggested you to start from scratch because it’s really odd that openvpn is not starting, and we tried several approaches too.

By the way, if you want we could still investigate, for example you could see if there are any errors with openvpn by running: `sudo systemctl status openvpn`

**Comment by waraulston** [comment]
I am just going to reinstall Stretch from a brand new image and try to reinstall PiVPN again and see if that fixes some things. Thanks for your help by the way.

**Comment by waraulston** [comment]
When I reinstall PiVPN should I use the option that supports the 2.4 update or such. It said not to use it for best compatibility, and I am using a laptop with the OpenVPN 2.4. I chose for the best compatibility because i might use it on mobile devices.

**Comment by orazioedoardo** [comment]
Mobile clients are supported too.

**Comment by waraulston** [comment]
Okay, so I will now be using the 2.4 supported mode on the PiVPN when i set it up.

**Comment by waraulston** [comment]
Okay, So i reinstalled the new version of OS, Rasbian Stretch. The tail command to show logs does not work, but when i use this command `sudo systemctl status openvpn` it shows this:
```
pi@192:~ $ sudo systemctl status openvpn
● openvpn.service - OpenVPN service
   Loaded: loaded (/lib/systemd/system/openvpn.service; enabled; vendor preset: enabled)
   Active: active (exited) since Sat 2018-03-03 16:50:37 EST; 4s ago
  Process: 7583 ExecStart=/bin/true (code=exited, status=0/SUCCESS)
 Main PID: 7583 (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/openvpn.service

Mar 03 16:50:37 192.168.0.16 systemd[1]: Stopping OpenVPN service...
Mar 03 16:50:37 192.168.0.16 systemd[1]: Starting OpenVPN service...
Mar 03 16:50:37 192.168.0.16 systemd[1]: Started OpenVPN service.
```
This makes me think that the OpenVPN service is started and that the log command just does not work.

**Comment by orazioedoardo** [comment]
Yes, no idea why though. By the way, is the VPN working now?

**Comment by waraulston** [comment]
No, It still gives this error:
```
Sun Mar 04 13:39:44 2018 OpenSSL: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
Sun Mar 04 13:39:44 2018 TLS_ERROR: BIO read tls_read_plaintext error
Sun Mar 04 13:39:44 2018 TLS Error: TLS object -> incoming plaintext read error
Sun Mar 04 13:39:44 2018 TLS Error: TLS handshake failed
```
I don't know what to do, but I am not ready to give up yet.

**Comment by orazioedoardo** [comment]
Can you try to connect from a different client?

**Comment by waraulston** [comment]
The client I am using is on the same network, would that potentially pose a problem?
I can try a different client, but it will be on the same network, cause I do not have a mobile hotspot.

**Comment by orazioedoardo** [comment]
It doesn’t make sense, read [this](https://github.com/pivpn/pivpn/issues/459).

**Comment by waraulston** [comment]
What if I use a VPN to change my location and the try to connect?

**Comment by orazioedoardo** [comment]
You mean another VPN then PiVPN? Mmmmh, maybe, not sure though.

**Comment by waraulston** [comment]
Okay, i see what you mean, I will try connecting from another network tonight or tommorrow.

**Comment by waraulston** [comment]
I tried the VPN then PiVPN option, and that does not work, Like expected.

**Comment by waraulston** [comment]
I think the network at my work blocks the VPN, and that is why it is not working

**Comment by 4s3ti** [comment]
closing as this is not PiVPN related. 
if you still need some help or continue the discussion take it over to reddit pls. 
https://www.reddit.com/r/pivpn/
