### ISSUE TITLE
Connecting to server to manage remotely?

### ISSUE THREAD

**Issue by arkid** [pivpn/pivpn#492]
A really simple and maybe silly question but is this possible or is the install so locked down that you can't do this?

**Comment by cfcolaco** [comment]
can you please be more clear?

**Comment by arkid** [comment]
Hi @cfcolaco What I mean is that I have a working install.  I can connect to it via my android or windows open vpn client and I'm instantly inside my home LAN.   What I want to do is telnet into the raspberry Pi running the pivpn install and do various management tasks on it via the shell.

**Comment by cfcolaco** [comment]
aw ok ... you are confusing things a litle bit, lets clear it up then. 

Only thing PiVPN does is to Install OpenVPN, and give you a good working VPN server with some scripts that help you to manage your openvpn server. SImple!

To remotely manage your server you don't want to use telnet, you want to use SSH instead if you are using Windows your best friend to achieve this might be PuTTY. 

You connect through OpenVPN then you SSH into your Raspberry pi and you have a shell to do whatever you want! =)

**Comment by arkid** [comment]
Ok... so no reconfiguration of the server itself, its open ports is done at al?   All the "hardening" is just to openvpn's default setup, is that more or less correct ?

**Comment by cfcolaco** [comment]
@arkid PiVPN is only concerned about OpenVPN installation. 
So regarding OpenVPN, you don't need to do anything else, unless, you need some very specific tweaks ( it doesn't seems to be the case ). 

Regarding SSH .. all the hardening it's on your own, but with the defaults, you should be fairly safe. 
Just don't expose SSH to the Internet, and access it only trough the VPN. 

Though, there are a bunch of good practices and hardening stuff for SSH. 
Just google around you will find plenty.

**Comment by arkid** [comment]
Hi @cfcolaco thanks so much for your reply and clarifying for me.  I'm on the write track now, really appreciate your time!
