### ISSUE TITLE
install script doesn't cater for non-detected public IP address, would like to generate correct ovpn files

### ISSUE THREAD

**Issue by riasevern** [pivpn/pivpn#499]
# PiVPN Issue Template

## Issue
Simple one really. I've used the script to install openvpn and then used the pivpn command to add/create the user .ovpn files.
When I use these to configure a client all is fine except that the server IP address is wrong.
I can change this address manually in client or in file and all works happily.
Of course I can continue to edit the files individually or reconfigure the clients but it would be nice to generate them correctly in the first place. so...
Where is the external IP address stored that the pivpn command references.

Within the script I was given the option of a public IP address (this picked up the external address of the VDSL router) and DNS. I want to use an IP address but not the detected one.
Why? I have a small private IP range from which I direct one of the addresses to the VPN server using the VDSL router.

## Have you searched for similar issues and solutions? 
    (yes/no / which issues?) 
  Couldn't find anything similar here or generally on the web for openvpn so I'm guessing pivpn stores this somewhere or extracts it from OpenVPN files. It's not obviously in the files in /etc/pivpn directory (nearly everything else is in setupVars.conf) and unfortunately I'm not good enough to trace the script file through.

## Console output of `curl install.pivpn.io | bash`
```
  Output Here
```

## Console output of `pivpn add` or `pivpn add nopass`
```
  Output Here
```

## Console output of `pivpn debug`
```
  Output Here
```

## Console Output of `sudo iptables -t nat -S`
```
  Output Here
```

## Console Output of `sudo iptables -S`
```
  Output Here
```

## output of `sudo netstat -uanp | grep openvpn`

```
  Output Here
```

## Have you taken any steps towards solving your issue? 
     which? 
Yes, tried looking through obvious configuration files, searching web etc.

**Comment by orazioedoardo** [comment]
You just need to edit this file `/etc/openvpn/easy-rsa/pki/Default.txt`

**Comment by riasevern** [comment]
Perfect, thought it would be simple. Presumably therefore the pivpn command simply calls easyRSA.

Bit more reading required now I know which direction to head for.
