### ISSUE TITLE
Help with: read UDP: Unknown error (code=10054)

### ISSUE THREAD

**Issue by cpaplaczyk** [pivpn/pivpn#500]
# PiVPN Issue Template

## Issue
Receiving error when trying to connect from multiple clients, result is unable to connect (connection loop).

Fri Mar --Date-- 2018 read UDP: Unknown error (code=10054)
Fri Mar --Date-- 2018 read UDP: Unknown error (code=10054)
Fri Mar --Date-- 2018 read UDP: Unknown error (code=10054)
Fri Mar --Date-- 2018 read UDP: Unknown error (code=10054)
Fri Mar --Date-- 2018 read UDP: Unknown error (code=10054)
Fri Mar --Date-- 2018 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Fri Mar --Date-- 2018 TLS Error: TLS handshake failed

## Have you searched for similar issues and solutions? 
    yes

## Console output of `pivpn debug`
```
::: Generating Debug Output
:::					:::
::		PiVPN Debug		 ::
:::					:::
::	Latest Commit			 ::
:::					:::
commit aa625b98ffb00d71ef40ade3ac6b69cce40b7a8e
Merge: 25aaf24 3e042ef
Author: redfast00 <redfast00@users.noreply.github.com>
Date:   Fri Mar 9 19:20:27 2018 +0100

    Merge pull request #493 from justinamcafee/master
    
    Added FamilyShield DNS server as option
:::					:::
::	Recursive list of files in	 ::
::	/etc/openvpn/easy-rsa/pki	 ::
:::					:::
/etc/openvpn/easy-rsa/pki/:
ca.crt
clayton.ovpn
crl.pem
Default.txt
index.txt
index.txt.attr
index.txt.attr.old
index.txt.old
issued
private
serial
serial.old
ta.key

/etc/openvpn/easy-rsa/pki/issued:
clayton.crt
server_d4BxgBUK6n6efUjb.crt

/etc/openvpn/easy-rsa/pki/private:
ca.key
clayton.key
server_d4BxgBUK6n6efUjb.key
:::					:::
::	Output of /etc/pivpn/*		 ::
:::					:::
:: START /etc/pivpn/DET_PLATFORM ::
Raspbian
:: END /etc/pivpn/DET_PLATFORM ::
:: START /etc/pivpn/INSTALL_PORT ::
11948
:: END /etc/pivpn/INSTALL_PORT ::
:: START /etc/pivpn/INSTALL_PROTO ::
udp
:: END /etc/pivpn/INSTALL_PROTO ::
:: START /etc/pivpn/INSTALL_USER ::
pi
:: END /etc/pivpn/INSTALL_USER ::
:: START /etc/pivpn/NO_UFW ::
1
:: END /etc/pivpn/NO_UFW ::
:: START /etc/pivpn/pivpnINTERFACE ::
eth0
:: END /etc/pivpn/pivpnINTERFACE ::
:: START /etc/pivpn/TWO_POINT_FOUR ::
:: END /etc/pivpn/TWO_POINT_FOUR ::
:::					:::
:: /etc/openvpn/easy-rsa/pki/Default.txt ::
:::					:::
client
dev tun
proto udp
remote ddns/ip 11948
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
tls-version-min 1.2
verify-x509-name server_d4BxgBUK6n6efUjb name
cipher AES-256-CBC
auth SHA256
compress lz4
verb 3
:::					:::
::	Debug Output Complete		 ::
:::					:::
::: 
::: Debug output completed above.
::: Copy saved to /tmp/debug.txt
::: 

```

## Console Output of `sudo iptables -t nat -S`
```
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT
-A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE
```

## Console Output of `sudo iptables -S`
```
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
```

## output of `sudo netstat -uanp | grep openvpn`

```
  None
```

## Have you taken any steps towards solving your issue? 
Yes, I have tried Jessie and Scratch along with the current version of PiVPN and the test version. My old OpenVPNAS was configured before so I can verify my port forwarding is correct on my router. It seems it may be an issue with PiVPN not associating the correct listening port for the Pi, is there a command that I can run to make sure OpenVPN is listening on port 11948? 

The below command from a local network computer shows us that 11948 is not open for UDP, where to go from here?
$ nmap ipofpi
Starting Nmap 7.60 ( https://nmap.org ) at 2018-03-16 10:50 MST
Nmap scan report for OpenVPNPi (ipofpi)
Host is up (0.0058s latency).
Not shown: 999 closed ports
PORT   STATE SERVICE
22/tcp open  ssh

**Comment by cfcolaco** [comment]
1. Are you trying to connect to the VPN from within the same network? 
2. Have you forwarded the correct port on your router? 
3. Provide us with the output of:

`systemctl status openvpn`
`systemctl status openvpn@server`

4. the Nmap command you ran is wrong, it will give you only TCP, the correct one for UDP is
`nmap -sU <host>` 

Due to the nature of UDP protocol, scanning UDP takes long and is not reliable, so in this case you might want to scan only the specific port

`nmap -sU -p 11948 <host>`

**Comment by terminalcat** [comment]
are u using the new version of openvpn ? i had issues but it looks like the new Openvpn uses UDP & TCP so that might be it

**Comment by cpaplaczyk** [comment]
I am using the version the PiVPN installs but I select during setup to use the latest version for faster connection and routing.

I will not be in front of my Pi for about a week so I will get back to testing once I get back in town. Are you thinking I need to use udp and tcp ports through router?

Clayton Paplaczyk
Cpaplaczyk@asu.edu

**Comment by terminalcat** [comment]
Yeah i suggest u just set the portforwarding to BOTH, and turn off any other firewalls on you rpi. I have had problems with ufw.

**Comment by cpaplaczyk** [comment]
Is there a command to verify all firewalls are turned off on the Pi? 

I am currently trying to connect from outside of the local network. Both from my phone and from a desktop and or laptop both at different external networks. 
Yes I have forwarded the correct udp port. I am not currently in front of the Pi but when I get back I will run the commands and post the information.

**Comment by cpaplaczyk** [comment]
Are you trying to connect to the VPN from within the same network? **No**
    Have you forwarded the correct port on your router? **Yes this is setup correctly.**

    Provide us with the output of:

systemctl status openvpn
**● openvpn.service - OpenVPN service
   Loaded: loaded (/lib/systemd/system/openvpn.service; enabled)
   Active: active (exited) since Tue 2018-03-27 08:17:06 UTC; 28min ago
  Process: 768 ExecStart=/bin/true (code=exited, status=0/SUCCESS)
 Main PID: 768 (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/openvpn.service**

systemctl status openvpn@server
**● openvpn@server.service - OpenVPN connection to server
   Loaded: loaded (/lib/systemd/system/openvpn@.service; disabled)
   Active: failed (Result: exit-code) since Tue 2018-03-27 08:17:03 UTC; 29min ago
  Process: 446 ExecStart=/usr/sbin/openvpn --daemon ovpn-%i --status /run/openvpn/%i.status 10 --cd /etc/openvpn --config /etc/openvpn/%i.conf (code=exited, status=1/FAILURE)**


    the Nmap command you ran is wrong, it will give you only TCP, the correct one for UDP is
    nmap -sU <host>

Due to the nature of UDP protocol, scanning UDP takes long and is not reliable, so in this case you might want to scan only the specific port

nmap -sU -p 11948 <host>
**This command shows that the port is closed even though this was the port I selected during the setup.**

**Comment by cpaplaczyk** [comment]
This has been getting to me as I need would like to get the PiVPN up and running. I did some searching today and looked through the log and they seem to show this error for OpenVPN.

Options error: Unrecognized option or missing parameter(s) in /etc/openvpn/server.conf:21: tls-crypt (2.3.4)

I went and looked a little further and went to the the server.conf file it states and line 21 and it seems to be pulling the tls-crypt from this location. tls-crypt /etc/openvpn/easy-rsa/pki/ta.key

I went into the file and it did not have <tls-crypt> nor </tls-crypt> I added them and saved and that did not work. 

Hit a road block here, wonder what could be the issue with the tls key?

**Comment by orazioedoardo** [comment]
Oh that’s the problem, some time ago I submitted a pull request for tls-crypt but I forgot to add a check for the openvpn version. So if you have the older raspbian jessie with openvpn 2.3.4 it won’t work. You should reinstall with openvpn 2.4 features disabled (or update to stretch first).

**Comment by cpaplaczyk** [comment]
@orazioedoardo I had previously tried Stretch and Jessie without any success. I just tried installing PiVPN with 2.4 features disabled but I could not connect, same error. I then wiped the Pi and installed Stretch and tried both with 2.4 and 2.3.4 enabled and neither of them work. Still continue to receive the same error (from Windows computer outside of network, running OpenVPN GUI v11.10.0.0.0

 read UDP: Unknown error (code=10054)

**Comment by cpaplaczyk** [comment]
@orazioedoardo Figured out the issue. I currently have my router set in a DMZ config but for some reason it was not forwarding the port I specified. I port forwarded that specific port to the router and it connected. I tried this setting before with no success, maybe it was a combination of the older version of Jessie.

Anyways thank you all for your assistance.

**Comment by lreynolds188** [comment]
Thanks to @cfcolaco just spent 48 hours trying to get past this issue and it was because I was trying to connect from inside the network.
