### ISSUE TITLE
cli to ban/unban user?

### ISSUE THREAD

**Issue by hannibal1986** [pivpn/pivpn#504]
any pivpn cli to ban/unban user? only ban, no revoke i test this https://docs.openvpn.net/command-line/managing-user-and-group-properties-from-command-line/ but no work. Thanks

**Comment by cezar97** [comment]
I didn't dig in too much, but setting up openvpn client config directories ( aka ccd ) on server side and pushing a dummy route / subnet to the client you want to "ban" should do it. Later to "unban" just comment the line you've added previously.
Here's something related: https://superuser.com/questions/663024/using-ccd-openvpn-user-can-connect-but-cant-access-other-devices.

**Comment by cezar97** [comment]
Rethinking on this and came up with the fact that what I said can be bypassed by setting the routes on client side, so if the user is technical he'll connect anyway.
To solve this you should set username and password as required to connect, too. In this case the user set the credentials along with the private key in the ovpn file, so they're not going to be re-typed every time. This way, if you want to ban an user just change the password and set it back to unban.

**Comment by cfcolaco** [comment]
Don't see any benefit in such an option ... either you want the user there or not ... either the user has a certificate or not. easy. why complicate what is simple.

Closing issue.
