### ISSUE TITLE
Port 1194 not open, can't find fix

### ISSUE THREAD

**Issue by M4rzzombie** [pivpn/pivpn#505]
I have been working on setting up PiVPN for a bit now, and my client continually gives me this output:

Mon Mar 26 18:17:40 2018 MANAGEMENT: >STATE:1522109860,WAIT,,,,,,
Mon Mar 26 18:18:41 2018 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Mon Mar 26 18:18:41 2018 TLS Error: TLS handshake failed

And does so consistently, across many different configurations of my server.conf. 
I am aware that port 1194 is not open on my Pi, but is correctly forwarded in my router. 
My firewall-openvpn-rules.sh looks like this:

#!/bin/sh

iptables -A FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -A FORWARD -s 10.8.0.0/24 -j ACCEPT
iptables -A FORWARD -j REJECT
iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o wlan0 -j SNAT --to-source 172.16.0.3
exit 0

I feel as if I am missing lines here where the firewall makes an exception for port 1194, but I am not experienced with linux / raspberry pis to know what to add.

Any and all help is appreciated!

**Comment by orazioedoardo** [comment]
Run `iptables -vnL INPUT`. If you have the policy set to DROP you need to add this rule to open the port: `iptables -I INPUT 1 -i wlan0 -p udp --dport 1194 -j ACCEPT`

**Comment by M4rzzombie** [comment]
Here is the output from that command:

root@Pi2:/home/pi# iptables -vnL INPUT
Chain INPUT (policy ACCEPT 2991 packets, 325K bytes)
 pkts bytes target     prot opt in     out     source               destination

and the client still cannot connect to the server. 
I have run the second command you suggested, and will test if this makes a difference
And just to add, here is a look at the open ports on this pi

PORT        STATE            SERVICE
68/udp     open|filtered dhcpc
123/udp   open             ntp
5353/udp open|filtered zeroconf

**Comment by orazioedoardo** [comment]
Since the policy is ACCEPT and there are no rules in the chain, that rule is not needed. However, from the nmap scan it looks like openvpn is not binding to the port.

Post the output of these: `sudo systemctl status openvpn` and `sudo nmap -antup | grep openvpn`

**Comment by M4rzzombie** [comment]
First command:
root@Pi2:/# systemctl status openvpn
● openvpn.service - OpenVPN service
   Loaded: loaded (/lib/systemd/system/openvpn.service; enabled)
   Active: active (exited) since Tue 2018-03-27 00:56:58 MDT; 6min ago
  Process: 1354 ExecStart=/bin/true (code=exited, status=0/SUCCESS)
 Main PID: 1354 (code=exited, status=0/SUCCESS)

Mar 27 00:56:58 Pi2 systemd[1]: Started OpenVPN service.

As far as the nmap command, my pi keeps telling me -antup isn't a recognized

**Comment by orazioedoardo** [comment]
That was my fault, it was the netstat command, try now.

**Comment by M4rzzombie** [comment]
I just ran the netstat command and it gave me no output?

pi@Pi2:~ $ sudo su
root@Pi2:/home/pi# netstat -antup | grep openvpn
root@Pi2:/home/pi#

**Comment by orazioedoardo** [comment]
It means that OpenVPN is not running, or it’s running but not properly (not bound to any port).
Can you post the log file (if it exists): `/var/log/openvpn.log` and also the server config: `/etc/openvpn/server.conf`

**Comment by M4rzzombie** [comment]
Openvpn.log:
root@Pi2:/home/pi# cat /var/log/openvpn.log
Mar 26 21:15:56 Pi2 ovpn-server[469]: Options error: --dh fails with 'none': No such file or directory
Mar 26 21:15:56 Pi2 ovpn-server[469]: Options error: Please correct these errors.
Mar 26 21:15:56 Pi2 ovpn-server[469]: Use --help for more information.
Mar 27 00:38:47 Pi2 ovpn-server[472]: Options error: You must define DH file (--dh)
Mar 27 00:38:47 Pi2 ovpn-server[472]: Use --help for more information.
Mar 27 00:56:58 Pi2 ovpn-server[1353]: Options error: Unrecognized option or missing parameter(s) in /etc/openvpn/server.conf:23: tls-crypt (2.3.4)
Mar 27 00:56:58 Pi2 ovpn-server[1353]: Use --help for more information.

Server.conf:
root@Pi2:/home/pi# cat /etc/openvpn/server.conf 
dev tun
proto udp
port 1194
ca /etc/openvpn/easy-rsa/pki/ca.crt
cert /etc/openvpn/easy-rsa/pki/issued/server.crt
key /etc/openvpn/easy-rsa/pki/private/server.key
dh none
topology subnet
server 10.8.0.0 255.255.255.0
# Set your primary domain name server address for clients
push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 8.8.4.4"
# Prevent DNS leaks on Windows
push "block-outside-dns"
# Override the Client default gateway by using 0.0.0.0/1 and
# 128.0.0.0/1 rather than 0.0.0.0/0. This has the benefit of
# overriding but not wiping out the original default gateway.
push "redirect-gateway def1"
client-to-client
keepalive 10 120
remote-cert-tls client
tls-version-min 1.2
tls-crypt /etc/openvpn/easy-rsa/pki/ta.key
cipher AES-256-CBC
auth SHA256
compress lz4
user nobody
group nogroup
persist-key
persist-tun
crl-verify /etc/openvpn/crl.pem
status /var/log/openvpn-status.log 20
status-version 3
syslog
verb 3
#DuplicateCNs allow access control on a less-granular, per user basis.
#Remove # if you will manage access by user instead of device. 
#duplicate-cn
# Generated for use by PiVPN.io

**Comment by orazioedoardo** [comment]
Same as [this issue](https://github.com/pivpn/pivpn/issues/500), upgrade to stretch or reinstall without 2.4 features.

**Comment by M4rzzombie** [comment]
I have both upgraded to stretch, and reinstalled with 2.4 features disabled, and I still get the exact same response.

Sat Mar 31 13:28:56 2018 OpenVPN 2.4.5 x86_64-w64-mingw32 [SSL (OpenSSL)] [LZO] [LZ4] [PKCS11] [AEAD] built on Mar  1 2018
Sat Mar 31 13:28:56 2018 Windows version 6.2 (Windows 8 or greater) 64bit
Sat Mar 31 13:28:56 2018 library versions: OpenSSL 1.1.0f  25 May 2017, LZO 2.10
Enter Management Password:
Sat Mar 31 13:28:56 2018 MANAGEMENT: TCP Socket listening on [AF_INET]127.0.0.1:25340
Sat Mar 31 13:28:56 2018 Need hold release from management interface, waiting...
Sat Mar 31 13:28:56 2018 MANAGEMENT: Client connected from [AF_INET]127.0.0.1:25340
Sat Mar 31 13:28:56 2018 MANAGEMENT: CMD 'state on'
Sat Mar 31 13:28:56 2018 MANAGEMENT: CMD 'log all on'
Sat Mar 31 13:28:56 2018 MANAGEMENT: CMD 'echo all on'
Sat Mar 31 13:28:56 2018 MANAGEMENT: CMD 'bytecount 5'
Sat Mar 31 13:28:56 2018 MANAGEMENT: CMD 'hold off'
Sat Mar 31 13:28:56 2018 MANAGEMENT: CMD 'hold release'
Sat Mar 31 13:28:59 2018 MANAGEMENT: CMD 'password [...]'
Sat Mar 31 13:28:59 2018 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Sat Mar 31 13:28:59 2018 Outgoing Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Sat Mar 31 13:28:59 2018 Outgoing Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Sat Mar 31 13:28:59 2018 Incoming Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Sat Mar 31 13:28:59 2018 Incoming Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Sat Mar 31 13:28:59 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]73.78.11.197:1194
Sat Mar 31 13:28:59 2018 Socket Buffers: R=[65536->65536] S=[65536->65536]
Sat Mar 31 13:28:59 2018 UDP link local: (not bound)
Sat Mar 31 13:28:59 2018 UDP link remote: [AF_INET]myip:1194
Sat Mar 31 13:28:59 2018 MANAGEMENT: >STATE:1522524539,WAIT,,,,,,
Sat Mar 31 13:29:59 2018 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Sat Mar 31 13:29:59 2018 TLS Error: TLS handshake failed
Sat Mar 31 13:29:59 2018 SIGUSR1[soft,tls-error] received, process restarting
Sat Mar 31 13:29:59 2018 MANAGEMENT: >STATE:1522524599,RECONNECTING,tls-error,,,,,
Sat Mar 31 13:29:59 2018 Restart pause, 5 second(s)

**Comment by orazioedoardo** [comment]
Post the output of `/var/log/openvpn.log` again.

**Comment by M4rzzombie** [comment]
here is the output of var/log/openvpn.log:

Apr  1 11:35:31 Pi2 ovpn-server[350]: OpenVPN 2.4.0 arm-unknown-linux-gnueabihf [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jul 18 2017
Apr  1 11:35:31 Pi2 ovpn-server[350]: library versions: OpenSSL 1.0.2l  25 May 2017, LZO 2.08
Apr  1 11:35:31 Pi2 ovpn-server[414]: Diffie-Hellman initialized with 2048 bit key
Apr  1 11:35:31 Pi2 ovpn-server[414]: Outgoing Control Channel Authentication: Using 256 bit message hash 'SHA256' for HMAC authentication
Apr  1 11:35:31 Pi2 ovpn-server[414]: Incoming Control Channel Authentication: Using 256 bit message hash 'SHA256' for HMAC authentication
Apr  1 11:35:32 Pi2 ovpn-server[414]: TUN/TAP device tun0 opened
Apr  1 11:35:32 Pi2 ovpn-server[414]: TUN/TAP TX queue length set to 100
Apr  1 11:35:32 Pi2 ovpn-server[414]: do_ifconfig, tt->did_ifconfig_ipv6_setup=0
Apr  1 11:35:32 Pi2 ovpn-server[414]: /sbin/ip link set dev tun0 up mtu 1500
Apr  1 11:35:32 Pi2 ovpn-server[414]: /sbin/ip addr add dev tun0 10.8.0.1/24 broadcast 10.8.0.255
Apr  1 11:35:32 Pi2 ovpn-server[414]: Could not determine IPv4/IPv6 protocol. Using AF_INET
Apr  1 11:35:32 Pi2 ovpn-server[414]: Socket Buffers: R=[163840->163840] S=[163840->163840]
Apr  1 11:35:32 Pi2 ovpn-server[414]: UDPv4 link local (bound): [AF_INET][undef]:1194
Apr  1 11:35:32 Pi2 ovpn-server[414]: UDPv4 link remote: [AF_UNSPEC]
Apr  1 11:35:32 Pi2 ovpn-server[414]: GID set to nogroup
Apr  1 11:35:32 Pi2 ovpn-server[414]: UID set to nobody
Apr  1 11:35:32 Pi2 ovpn-server[414]: MULTI: multi_init called, r=256 v=256
Apr  1 11:35:32 Pi2 ovpn-server[414]: IFCONFIG POOL: base=10.8.0.2 size=252, ipv6=0
Apr  1 11:35:32 Pi2 ovpn-server[414]: Initialization Sequence Completed

I appreciate your continued help with this project! :D

**Comment by orazioedoardo** [comment]
OpenVPN seems to be working, has your public ip changed?
Post the output of `sudo iptables -vnL -t nat` and `sudo iptables -vnL`

**Comment by cezar97** [comment]
@orazioedoardo Nmap or other port scanners shouldn't be used to see openvpn port binding / open port as due to hmac will be reported as closed ( issue #465 ). Netstat is the only working way...

**Comment by Ry10p** [comment]
Is there any update to this issue? I am having the same exact problem happen with my PIVPN.

RE:
      ` TLS Error: TLS handshake failed`

Thanks in advance!

**Comment by 4s3ti** [comment]
tls handshake failed issues can happen in different scenarios, 
and often are related with networking or happen due to thinkering with OpenVPN configs. 
closing thread. as its quite old by now. 

https://www.reddit.com/r/pivpn/ should be the place for this kind of issues.
