### ISSUE TITLE
PiVPN on Armbian Stretch (Rock64)

### ISSUE THREAD

**Issue by jsfrederick** [pivpn/pivpn#508]
# PiVPN Issue Template

I would like to install PiVPN on a Rock64 board using Armbian stretch.  Does anyone see any potential issues?  I have it running on my RPi using Raspbian stretch and it works fine.

## Have you searched for similar issues and solutions? 
    (yes/no / which issues?) 
  

## Console output of `curl install.pivpn.io | bash`
```
  Output Here
```

## Console output of `pivpn add` or `pivpn add nopass`
```
  Output Here
```

## Console output of `pivpn debug`
```
  Output Here
```

## Console Output of `sudo iptables -t nat -S`
```
  Output Here
```

## Console Output of `sudo iptables -S`
```
  Output Here
```

## output of `sudo netstat -uanp | grep openvpn`

```
  Output Here
```

## Have you taken any steps towards solving your issue? 
     which?

**Comment by orazioedoardo** [comment]
Do not post an issue if there is no issue yet.

**Comment by jsfrederick** [comment]
Ok.  Then where do I ask questions?

**Comment by orazioedoardo** [comment]
I mean, this is the place to as questions but I think a bit of an exaggeration to open an issue for such a question.

By the way, the FAQ states that the installer should work on any Ubuntu/Debian (as OpenVPN is compatible with many platforms).

**Comment by cfcolaco** [comment]
The script should work in any debian based system. some distros make some weird changes which breaks the script but until now are only some specific cases. 

It should work with the system you are trying to use.

If you run into any issues please open an issue... till there... closing this one.
