### ISSUE TITLE
PiVPN installed however can not connect from outside

### ISSUE THREAD

**Issue by UNlDAN** [pivpn/pivpn#509]
## PiVPN does not connect at all, all appropriate ports have been opened. To double check port forwarding is good, I ran a different device on port 1194 as an apache2 server and I could access files no problem, and ran openvpn access server to test. Works no problem. 
After setting pivpn back to 1194 for UDP default, I asked my client to conenct to it using the OVPN file. I enter my password (entering wrong password shows wrong password so that's good) and it is stuck.
It just waits and waits. EVENT WAIT

## Have you searched for similar issues and solutions? 
    Yes, googled openvpn not connecting etc on google yet nothing helps.
  

## Console output of `curl install.pivpn.io | bash`
```
The install went fine, I did not want to install again as it is my ~21st time installing tonight

```
## Console output of `pivpn add` or `pivpn add nopass`
```
 Enter a Name for the Client:  testuser
Enter the password for the client:  
Enter the password again to verify:  
Passwords do not match! Please try again.
Enter the password for the client:  
Enter the password again to verify:  
spawn ./easyrsa build-client-full testuser

Note: using Easy-RSA configuration from: ./vars
Generating a 2048 bit RSA private key
.....................................................+++
.....................................................................+++
writing new private key to '/etc/openvpn/easy-rsa/pki/private/testuser.key.bNNnmnfv2G'
Enter PEM pass phrase:
Verifying - Enter PEM pass phrase:
-----
Using configuration from /etc/openvpn/easy-rsa/openssl-1.0.cnf
Check that the request matches the signature
Signature ok
The Subject's Distinguished Name is as follows
commonName            :PRINTABLE:'testuser'
Certificate is to be certified until Mar 25 04:18:35 2028 GMT (3650 days)

Write out database with 1 new entries
Data Base Updated
spawn openssl rsa -in pki/private/testuser.key -des3 -out pki/private/testuser.key
Enter pass phrase for pki/private/testuser.key:
writing RSA key
Enter PEM pass phrase:
Verifying - Enter PEM pass phrase:
Client's cert found: testuser.crt
Client's Private Key found: testuser.key
CA public Key found: ca.crt
tls-auth Private Key found: ta.key


========================================================
Done! testuser.ovpn successfully created! 
testuser.ovpn was copied to:
  /home/pvpn/ovpns
for easy transfer. Please use this profile only on one
device and create additional profiles for other devices.
========================================================

  
```

## Console output of `pivpn debug`
```
  :::					:::
::		PiVPN Debug		 ::
:::					:::
::	Latest Commit			 ::
:::					:::
commit 33ed7e7012d5278162d72c3477a0d9b4345520ab
Merge: 1375fa1 30397f2
Author: redfast00 <redfast00@users.noreply.github.com>
Date:   Sat Mar 24 13:39:55 2018 +0100

    Merge pull request #502 from stan3/nonexecutable
    
    Changed permission bits on text files.
:::					:::
::	Recursive list of files in	 ::
::	/etc/openvpn/easy-rsa/pki	 ::
:::					:::
/etc/openvpn/easy-rsa/pki/:
ca.crt
crl.pem
Default.txt
index.txt
index.txt.attr
index.txt.attr.old
index.txt.old
ishm.ovpn
issued
private
serial
serial.old
ta.key
testuser.ovpn

/etc/openvpn/easy-rsa/pki/issued:
ishm.crt
server_bRGuOH6SexEW34Zi.crt
testuser.crt

/etc/openvpn/easy-rsa/pki/private:
ca.key
ishm.key
server_bRGuOH6SexEW34Zi.key
testuser.key
:::					:::
::	Output of /etc/pivpn/*		 ::
:::					:::
:: START /etc/pivpn/DET_PLATFORM ::
Ubuntu
:: END /etc/pivpn/DET_PLATFORM ::
:: START /etc/pivpn/INSTALL_PORT ::
1194
:: END /etc/pivpn/INSTALL_PORT ::
:: START /etc/pivpn/INSTALL_PROTO ::
udp
:: END /etc/pivpn/INSTALL_PROTO ::
:: START /etc/pivpn/INSTALL_USER ::
pvpn
:: END /etc/pivpn/INSTALL_USER ::
:: START /etc/pivpn/NO_UFW ::
1
:: END /etc/pivpn/NO_UFW ::
:: START /etc/pivpn/pivpnINTERFACE ::
eth0
:: END /etc/pivpn/pivpnINTERFACE ::
:: START /etc/pivpn/TWO_POINT_FOUR ::
:: END /etc/pivpn/TWO_POINT_FOUR ::
:::					:::
:: /etc/openvpn/easy-rsa/pki/Default.txt ::
:::					:::
client
dev tun
proto udp
remote MYIP 1194
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
tls-version-min 1.2
verify-x509-name server_bRGuOH6SexEW34Zi name
cipher AES-256-CBC
auth SHA256
compress lz4
verb 3
:::					:::
::	Debug Output Complete		 ::
:::					:::

```

## Console Output of `sudo iptables -t nat -S`
```
 pvpn@pvpn47:~$ sudo iptables -t nat -S
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT
-A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE

```

## Console Output of `sudo iptables -S`
```
  pvpn@pvpn47:~$ sudo iptables -S
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT

```

## output of `sudo netstat -uanp | grep openvpn`

```
  pvpn@pvpn47:~$ sudo netstat -uanp | grep openvpn
pvpn@pvpn47:~$ <Yes, this shows nothing>

```

## Have you taken any steps towards solving your issue? 
     which? 
I tried starting from fresh, changing the port, changing to TCP, tried ports 443, 1194, 9999, 8888, 3333 and many more yet nothing helps. It's almost like the server does not exist or anything. after I shutdown pivpn then fire up my old openvpn access server and reassign the port forward to openvpn access server, it works no problem.

Commands:

**pvpn@pvpn47:~$ netstat -l**
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 pvpn47:domain           *:*                     LISTEN     
tcp        0      0 *:ssh                   *:*                     LISTEN     
tcp        0      0 localhost:ipp           *:*                     LISTEN     
tcp6       0      0 [::]:ssh                [::]:*                  LISTEN     
tcp6       0      0 ip6-localhost:ipp       [::]:*                  LISTEN     
udp        0      0 *:ipp                   *:*                                
udp        0      0 *:65509                 *:*                                
udp        0      0 pvpn47:domain           *:*                                
udp        0      0 *:bootpc                *:*                                
udp        0      0 *:mdns                  *:*                                
udp        0      0 *:53721                 *:*                                
udp6       0      0 [::]:mdns               [::]:*                             
udp6       0      0 [::]:37212              [::]:*                             
udp6       0      0 [::]:26178              [::]:*                             
raw6       0      0 [::]:ipv6-icmp          [::]:*                  7          
Active UNIX domain sockets (only servers)
Proto RefCnt Flags       Type       State         I-Node   Path
unix  2      [ ACC ]     STREAM     LISTENING     12989    /run/user/1000/keyring-GOIcEj/control
unix  2      [ ACC ]     STREAM     LISTENING     11689    @/tmp/dbus-aCGKupfQwZ
unix  2      [ ACC ]     STREAM     LISTENING     11747    @/tmp/dbus-o4ZE8eo5GH
unix  2      [ ACC ]     STREAM     LISTENING     11787    @/tmp/.ICE-unix/1818
unix  2      [ ACC ]     STREAM     LISTENING     13030    /run/user/1000/keyring-GOIcEj/ssh
unix  2      [ ACC ]     STREAM     LISTENING     11224    /run/user/1000/keyring-GOIcEj/gpg
unix  2      [ ACC ]     STREAM     LISTENING     11225    /run/user/1000/keyring-GOIcEj/pkcs11
unix  2      [ ACC ]     STREAM     LISTENING     13285    /run/user/1000/pulse/native
unix  2      [ ACC ]     STREAM     LISTENING     9141     @/tmp/.X11-unix/X0
unix  2      [ ACC ]     STREAM     LISTENING     13008    @/tmp/dbus-0p90CxZvJJ
unix  2      [ ACC ]     STREAM     LISTENING     9755     /var/run/sdp
unix  2      [ ACC ]     STREAM     LISTENING     9782     /var/run/avahi-daemon/socket
unix  2      [ ACC ]     STREAM     LISTENING     9831     /var/run/cups/cups.sock
unix  2      [ ACC ]     STREAM     LISTENING     10818    /var/run/acpid.socket
unix  2      [ ACC ]     STREAM     LISTENING     7922     @/com/ubuntu/upstart
unix  2      [ ACC ]     STREAM     LISTENING     9984     /var/run/dhcpcd.sock
unix  2      [ ACC ]     STREAM     LISTENING     13676    @/tmp/dbus-RwNCcD7p
unix  2      [ ACC ]     STREAM     LISTENING     9687     /var/run/dbus/system_bus_socket
unix  2      [ ACC ]     STREAM     LISTENING     11659    @/com/ubuntu/upstart-session/1000/1636
unix  2      [ ACC ]     STREAM     LISTENING     9142     /tmp/.X11-unix/X0
unix  2      [ ACC ]     STREAM     LISTENING     11788    /tmp/.ICE-unix/1818
unix  2      [ ACC ]     SEQPACKET  LISTENING     8807     /run/udev/control

## What shows on clients when I try to connect with the OVPN file:

Tue Mar 27 21:31:14 2018 UDP link remote: [AF_INET]**MYIP**:1194
Tue Mar 27 21:31:14 2018 MANAGEMENT: >STATE:1522211474,WAIT,,,,,,

**Comment by orazioedoardo** [comment]
> pvpn@pvpn47:~$ sudo netstat -uanp | grep openvpn
pvpn@pvpn47:~$ <Yes, this shows nothing>

Looks like openvpn does not bind to the port. Dumb question: did you reboot after installing? Can you post the log file `/var/log/openvpn.log`

**Comment by Sp4c3C4k3** [comment]
I am having the exact same problem as @UNlDAN is having also on ubuntu 16.04, so if i need to test something just tell me!

**Comment by orazioedoardo** [comment]
- Get root: `sudo -i`
- Add the key: `wget -O - https://swupdate.openvpn.net/repos/repo-public.gpg|apt-key add -`
- Add the repo: `echo "deb http://build.openvpn.net/debian/openvpn/stable xenial main" > /etc/apt/sources.list.d/openvpn-aptrepo.list`
- Update the package cache: `apt update`
- Reinstall OpenVPN: `apt install --reinstall openvpn`
- Reboot and try again: `reboot`

**Comment by Sp4c3C4k3** [comment]
@orazioedoardo That worked! Thankyou!

**Comment by Thijn99** [comment]
@orazioedoardo Thank you so so much for this. I've spent so many hours searching for a solution with this simple installation. This worked for me! I'd hug you if I could.
