### ISSUE TITLE
Advanced set-up for cases such as blocked common ports/protocols

### ISSUE THREAD

**Issue by armatiti** [pivpn/pivpn#51]
Hi there,

Unbelievably straightforward and robust install. It might go in the opposite direction of this particular point however I use such VPNs in environments where traditional ports and protocols such UDP are blocked. Therefore at the moment I'm fiddling the end result of the configuration files on both client and server side to make it work.

It would be very helpful and useful for such cases to have an advanced menu at start up or at the end (where the prompt on default port to be used occurs) to go through such steps. This could be extended to other relevant optional fields to the config files (no-auth? type of compression?)

Well done again!!!

**Comment by redfast00** [comment]
See #91: Most environments will allow 443/tcp, since HTTPS goes over that port and is also encrypted.
