### ISSUE TITLE
How to block the connection to specific ip addresses ?

### ISSUE THREAD

**Issue by yourkaribbean** [pivpn/pivpn#513]
Hi everyone,

I just installed pivpn and it works perfectly. I would like to create connection restrictions, because at the moment, I can connect to all devices in my home. In the best of all worlds, I would like the connection to be effective only on the server where is installed pivpn. 

Do you have any idea about the procedure?

I thank you in advance !

**Comment by orazioedoardo** [comment]
So you want your clients to be able to connect to your SERVER and the INTERNET but not to your home devices?
