### ISSUE TITLE
VPN server and client on a single Raspberry working as a router for home devices

### ISSUE THREAD

**Issue by marekszewczyk** [pivpn/pivpn#515]
Hi,

My goal is to setup a single raspberry to work as a vpn router like here:
                                                          
![raspberry pi infrastucture](https://user-images.githubusercontent.com/8479822/38316842-f64acb50-382b-11e8-9128-49a8d22b8361.png)

Then I could connect to my vpn from any network and e.g. stream tv to my mobile or browse the storage
How can I achieve it using pivpn?

**Comment by cfcolaco** [comment]
**Just a note:** PiVPN is a collection of scripts that helps you install and maanage an OpenVPN server. 

I think the instructions here are pretty clear. 

https://github.com/pivpn/pivpn
https://github.com/pivpn/pivpn/wiki

just don't forget to forward the correct port from the Home roouter to the Raspberry pi

**Comment by cfcolaco** [comment]
as this is not really an issue I am closing.
