### ISSUE TITLE
Cannot ping client from server

### ISSUE THREAD

**Issue by svib** [pivpn/pivpn#520]
I have made a setup with one RPi Server and one RPi client. PiVPN is installed on the Server while I have only run "sudo apt-get install openvpn" on the client. I put the client.ovpn client config file created by the server on the client and put it in my home directory on the client. After running "sudo openvpn client.ovpn" on the client the tunnel comes up as it should and I can ping the server eth0 IP address from the client. Everything is perfectly fine so far. Now to the problem: I cannot ping the client eth0 IP address from the server. It works fine to ping the client tun0 IP address 10.8.0.2 from the server and also ssh from the server to the client tun0 IP address. So the problem is somewhere on the client, but I cannot figure out how to make this work. I guess it is something with the routing on the client. Any solutions to this would be appreciated!

**Comment by orazioedoardo** [comment]
This is more of a question on OpenVPN rather then PiVPN specific, however, check [this](https://openvpn.net/index.php/open-source/documentation/howto.html#scope) guide “Including multiple machines on the client side when using a routed VPN (dev tun)”.
Basically you need to set a static ip for your vpn client and then a route to the client side lan.

**Comment by svib** [comment]
At this stage I don't bother about reaching any lan connected to the client, just the client eth0 IP adress itself. 

Even if it probably isn't the most prioritized issue, it would have been a nice feature if the PiVPN script included a question if this shoud be possible. It would helpful lead to understand how to continue the routing to other machines on the client network for the less experinced user.  Let's assume that the client has a fixed IP adress.

**Comment by svib** [comment]
After some additional googling I found the answer at https://serverfault.com/questions/593314/openvpn-routing-for-lan-to-lan-through-tun

Here is a step-by-step instruction:

_The following assumes that openvpn has been installed on the server with the PiVPN script and that openvpn has been installed by using "apt-get install openvpn" on the client._ 

_ON THE CLIENT
Allow packet forwarding by adding the following line in /etc/sysctl.conf on the client:_
net.ipv4.ip_forward=1

_ON THE SERVER
Add the following line to /etc/openvpn/server.conf on the server:_
route X.X.X.X Y.Y.Y.Y Z.Z.Z.Z #X=client net Y=netmask for client net, Z=Unique IP adress on the VPN net, example 192.168.1.0 255.255.255.0 10.8.0.3
client-config-dir /etc/openvpn/ccd

_Create the directory_ "/etc/openvpn/ccd"
_Put a file with the client certificate name In the /ccd directory. This should be "client_1" if your client config name is "client_1.conf". 
The content of this client specific configuration file should be:_
push "route X.X.X.X Y.Y.Y.Y 10.8.0.1"  #X=client net Y=netmask for client net, example: push "route 192.168.1.0 255.255.255.0 10.8.0.1"
iroute X.X.X.X Y.Y.Y.Y #X=client net Y=netmask for client net, example: iroute 192.168.1.0 255.255.255.0

**Comment by orazioedoardo** [comment]
Well, that was pretty much the guide I linked you in my first comment.
