### ISSUE TITLE
pivpn and magic packet broadcast on UDP port 9 won't work!

### ISSUE THREAD

**Issue by RaspiGuru** [pivpn/pivpn#522]
Hello Every one,
After successfuly installed (with default values) pivpn server on my Raspberry, everything working fine except my python script won't wake my PCs.  Until pivpn server installation, my script worked perfectly.
I'm using a python script to broadcast magic packets on UDP port 9. Here is my script:

import sys, struct, socket

#1C:87:2C:5E:A3:6F

# Configuration variables
broadcast = ['10.10.10.255']
wol_port = 9

def WakeOnLan(ethernet_address):

    # Construct 6 byte hardware address
    add_oct = ethernet_address.split(':')
    if len(add_oct) != 6:
        print "\n*** Illegal MAC address\n"
        print "MAC should be written as 00:11:22:33:44:55\n"
        return
    hwa = struct.pack('BBBBBB', int(add_oct[0],16),
        int(add_oct[1],16),
        int(add_oct[2],16),
        int(add_oct[3],16),
        int(add_oct[4],16),
        int(add_oct[5],16))

    # Build magic packet

    msg = '\xff' * 6 + hwa * 16

    # Send packet to broadcast address using UDP port 9

    soc = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    soc.setsockopt(socket.SOL_SOCKET, socket.SO_BROADCAST,1)
    for i in broadcast:
        soc.sendto(msg,(i,wol_port))
    soc.close()

print WakeOnLan(sys.argv[1])

Advance thanks for your valuable help
Raphy

**Comment by orazioedoardo** [comment]
AFAIK, WakeOnLAN does not work over VPN if you are using an L3 VPN (which pivpn is, in fact it sets `dev tun ` in the config). You need to create a tap version to make it working.

**Comment by cezar97** [comment]
Maybe the broadcast is send on the VPN network, so specifying the IP's manually should correctly redirect the packets to the pc's and wake them.

**Comment by 4s3ti** [comment]
MagicPackets are L2 Packets and PiVPN sets up a L3 VPN having this said WoL won't work. 
for this OpenVPN needs to be setup in Bridged mode which is not supported by PiVPN. 
There are indeed plans to support it however can't forsee any Bridged setup in the near term. 
closing.
