### ISSUE TITLE
Add IPv6 Routes By Default

### ISSUE THREAD

**Issue by mep85** [pivpn/pivpn#529]
Many devices have IPv6 enabled by default, and some (e.g. iOS) do not allow it to be disabled in the .ovpn config, or pushed by the server.

It would be nice if PiVPN would also create IPv6 routes to push to the clients and redirect IPv6 traffic through the tunnel. It could then either be discarded at the server or forwarded along with the IPv4 traffic.

At a minimum this should serve as a workaround in the cases where it is impossible to block IPv6 traffic entirely, or the interface can not be disabled on the client.

**Comment by 4s3ti** [comment]
closing as #259 is already up to add support for IPv6
