### ISSUE TITLE
Certificate valid period and auto login

### ISSUE THREAD

**Issue by vikingza** [pivpn/pivpn#530]
Good day,

I cannot see how to set the valid period for the user so I can either set their login validation for 10 minutes, 1 year or to never expire, I am looking at using openvpn on a raspberry pi for access to a Search and Rescue server which we use for logging of deployments, but I want to be able to set how long the user may have access for before he needs to apply for his / her profile to be renewed (re-activated).

I am also cant find how to make a opvn file to remember its password so that each time one connects, the user does not have to put in a password, I am looking at using this on autonomous systems like field servers that one just connects to a router with internet and Wifi access before powering up, once powered up it can auto "dial" the OpenVPN gateway and then start syncing the field databases with the main servers databases.

**Comment by 4s3ti** [comment]
@vikingza sorry for the late reply the project has been stalled for quite a while and we are trying to get back on track now. 

Get certificates to auto-expire seems quite a cool feature however i don't really know how to make it happen, @orazioedoardo , @devZer0 what you think about this? 

> am also cant find how to make a opvn file to remember its password 

I believe that is an option at the User side and it might depend on the client that is being used, not something the server admin can fix on his side. 
however, I highly discourage this for the obvious security reasons.

**Comment by orazioedoardo** [comment]
@4s3ti You can do that by tweaking the EASYRSA_CERT_EXPIRE variable when creating a new client. [By default](https://github.com/OpenVPN/easy-rsa/blob/master/easyrsa3/vars.example#L124) it's 1080 days, about 3 years.

**Comment by Giraffe1966** [comment]
@vikingza About not typing in a password, you could just run `pivpn add nopass` to generate a private key that isn't encrypted with a password, or use a client feature to remember your password (setting it up depends on the client. It is unwise in high-security environments, as it is essentially the same security as no password at all).

**Comment by 4s3ti** [comment]
already available in test brach.
Issue to be closed after test gets merged into master.

**Comment by 4s3ti** [comment]
this has been already pushed into master with PR #740
Closing this issue.

Thank you for your interest.
