### ISSUE TITLE
Unable to connect from Android (works fine on Windows)

### ISSUE THREAD

**Issue by mikester01** [pivpn/pivpn#532]
# PiVPN Issue Template

## Issue

I'm unable to connect to my server from my Android phone using the OpenVPN client. If I use the same OVPN file on Windows, it connects without issue.

The OpenVPN log shows this in the failure case:

```
May  7 14:20:32 pivpn ovpn-server[939]: 166.170.38.243:35017 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #1 / time = (1525728031) Mon May  7 14:20:31 2018 ] -see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
May  7 14:20:32 pivpn ovpn-server[939]: 166.170.38.243:35017 TLS Error: incoming packet authentication failed from [AF_INET]166.170.38.243:35017
May  7 14:20:33 pivpn ovpn-server[939]: 166.170.38.243:35017 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #1 / time = (1525728031) Mon May  7 14:20:31 2018 ] -see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
May  7 14:20:33 pivpn ovpn-server[939]: 166.170.38.243:35017 TLS Error: incoming packet authentication failed from [AF_INET]166.170.38.243:35017
May  7 14:20:34 pivpn ovpn-server[939]: 166.170.38.243:35017 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #1 / time = (1525728031) Mon May  7 14:20:31 2018 ] -see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
May  7 14:20:34 pivpn ovpn-server[939]: 166.170.38.243:35017 TLS Error: incoming packet authentication failed from [AF_INET]166.170.38.243:35017
May  7 14:20:35 pivpn ovpn-server[939]: 166.170.38.243:35017 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #1 / time = (1525728031) Mon May  7 14:20:31 2018 ] -see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
```

## Have you searched for similar issues and solutions? 
Yes, I've searched. Most of the issues appear to be related to Private Internet Access, which I'm not using.
  

## Console output of `curl install.pivpn.io | bash`
```
  When I tried to run `curl install.pivpn.io | bash` from my server, I was getting a HTTP/301 (301 Moved Permanently) error. I went to the redirected URL (https://raw.githubusercontent.com/pivpn/pivpn/master/auto_install/install.sh) and piped it through bash, but that leads to a reinstall of PiVPN.

```

## Console output of `pivpn add` or `pivpn add nopass`
```
  No failures in creating the .ovpn file.
```

## Console output of `pivpn debug`
```
remote-cert-tls server
tls-version-min 1.2
verify-x509-name server_RSbpHvh2PaE5IoJS name
cipher AES-256-CBC
auth SHA256
comp-lzo
verb 3
:::                                     :::
::      Debug Output Complete            ::
:::                                     :::
```

## Console Output of `sudo iptables -t nat -S`
```
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT
-A POSTROUTING -s 10.8.0.0/24 -o ens3 -j MASQUERADE
```

## Console Output of `sudo iptables -S`
```
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
```

## output of `sudo netstat -uanp | grep openvpn`

```
udp        0      0 0.0.0.0:1194            0.0.0.0:*                           939/openvpn
```

## Have you taken any steps towards solving your issue?  

Checked for updates (including Beta) to OpenVPN on Android
Tried re-creating the OVPN file

**Comment by orazioedoardo** [comment]
Can you post the full log of the openvpn handshake when connecting from your Android phone?

**Comment by mikester01** [comment]
Given the size of the log, I've copied it to Pastebin:

https://pastebin.com/K5bPUXSR

**Comment by mikester01** [comment]
My phone gets time from the cellular network, so there's nothing I can do to override it.

The PiVPN server is showing the correct time. I've also got it configured to sync over NTP.

```
mike@pivpn:~$ date
Wed May  9 10:13:52 PDT 2018
mike@pivpn:~$ timedatectl
      Local time: Wed 2018-05-09 10:15:55 PDT
  Universal time: Wed 2018-05-09 17:15:55 UTC
        RTC time: Wed 2018-05-09 17:15:55
       Time zone: America/Los_Angeles (PDT, -0700)
 Network time on: yes
NTP synchronized: yes
 RTC in local TZ: no
```

**Comment by orazioedoardo** [comment]
May not be related at all but can you try changing the port in the server config at `/etc/openvpn/server.conf`? Then restart the server with `sudo systemctl restart openvpn`, change the port in the client config and try again.

**Comment by mikester01** [comment]
OpenVPN connect log is here (IP address / FQDN changed for privacy):

https://pastebin.com/hCcdEKtZ 

I also tried changing the port from 1194 to 2294, re-created a new client profile via pivpn -a, and sent it to my phone. No change in behaviour.

**Comment by orazioedoardo** [comment]
That log sheds some light. As far as I can tell this is what happens:
- Your Android phone tries to contact you server: `Connecting to [fqdn.is.here]:2294 (ip.address.is.here) via UDPv4`
- The server itself receives packet: `TLS: Initial packet from [AF_INET]167.XXX.XXX.XXX:39429`
- Your Android phone DOES NOT receive an answer, so it tries to reconnect for 10 seconds.
- In the meanwhile, you server still receives the connection attempts but they are effectively replays to they are discarded: `167.XXX.XXX.XXX:39429 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #1 / time = (1525816932) Tue May  8 15:02:12 2018 ]` (note that the timestamp is always the same).
- Your Android phone eventually times out.

Considering that your windows client work, I would try those things in order:
- Try another client, possibly android too
- Try another client connected to android’s personal hotspot
- Try to switch to TCP
- Disable replay protection on the server with `no-replay` (this should be a workaround as it decreases security).

**Comment by mikester01** [comment]
Apologies for the delay in responding - real life got in the way. :)

I've switched from the stock "OpenVPN Connect" client to "OpenVPN for Android", and that appears to have made a significant difference - I can actually connect using the latter client.

As far as server: This instance of PiVPN is running in a virtualized KVM environment. It is behind a NAT (as it's in my house) but the actual VM has a bridged virtual NIC.

**Comment by bigjohns97** [comment]
Just wanted to chime in but i am having the same issue and openvpn for android resolved it for me but it seems much slower. Hopefully whatever is broken with connect can be resolved.
