### ISSUE TITLE
Installation stoped an now i cant edit ips

### ISSUE THREAD

**Issue by FaxMac** [pivpn/pivpn#539]
how to write an issue I got a problema on the instalation, i installed a fresh rapsian ingate to my rpi and executed the command on the command prompt, my probem is when its time to choose an interface and change the ip, the installers stops , it leaves the message  "cannot find device "" "
 and when i try to edit the ips via the graphic way, the application bars resets and it doesn't let me edit them (i can through the command prompt tho)

is it a bug or is there a way to fix it?
(pd: sorry for my broken english)

**Comment by cfcolaco** [comment]
Please fill the issue template accordingly. 

which version of raspbian are you using? is it in another language other than english (i think this was solved but asking anyway) ?

read trough issue #399 and you will find almost all reasons why PiVPN script breaks during the install.
