### ISSUE TITLE
Trouble connecting through Android OpenVPN Connect on mobile data

### ISSUE THREAD

**Issue by AngusF22** [pivpn/pivpn#54]
I've had considerable trouble connecting to my Pi VPN while on mobile data. I can ping my phone from the local network when connected, but couldn't do anything else unless the phone was connected to the VPN via Wi-Fi.

I was able to solve this issue after considerable hassle and research by adding two lines to /etc/openvpn/server.conf:

```
tun-mtu 1400 
mssfix 1360
```

With these, I am able to connect the VPN over mobile data, and have complete access to my home network, as well as being able to browse outside the network.

I don't know enough about OpenVPN to say that these are a good idea to add by default. Perhaps someone else who is better versed can weigh in.

**Comment by 0-kaladin** [comment]
@AngusF22 I can connect fine over mobile data without those changes.  They seem maybe specific for your mobile network.  In the interest of helping others maybe with the same issue can you respond with your moble provide and device type you used?  Thanks!

**Comment by AngusF22** [comment]
I'm on Rogers, using an LG G3. I forget the exact bit of Googling I did to find those strings, but someone else was having similar issues, and they posted them as a working fix.

**Comment by 0-kaladin** [comment]
I'll add a link to this in the wiki so others may find as well.  Thanks!

**Comment by webdude21** [comment]
@AngusF22 After an entire day of fiddling and wondering why internet over the vpn doesn't work, i've stumbled upon your post. Thank you, you made my day!

**Comment by CheezusChrust** [comment]
Thank you for this - this fixed my issue completely. Could somebody smarter than me explain what those commands are doing to actually fix this? It's odd because my mother's phone on the same mobile network has had no issues, however with mine it couldn't stay connected without these settings.
