### ISSUE TITLE
Allow 4096 Bit Diffie-Hellman Key

### ISSUE THREAD

**Issue by anonymouz4** [pivpn/pivpn#540]
PiVPN already allows 4096 bit RSA keys but doesn't give any option to also use 4096 bit with Diffie-Hellman keys.
It only uses 2048 bit Diffie-Hellman keys.

**Comment by orazioedoardo** [comment]
Actually no, the DH parameters size is the same as the RSA key size.

**Comment by anonymouz4** [comment]
Why does it then say 2048 bit in the .ovpn client profile?
If I setup the server via [Angristan's OpenVPN Setup Script](https://github.com/Angristan/OpenVPN-install), it lets me choose the bit size for RSA keys **AND** DH Keys and also later, 4096 bit is in the .ovpn config file.

**Comment by orazioedoardo** [comment]
It doesn't let you choose DH size but it will match the RSA key size, so if you choose 4096 bit encryption it will generate 4096 bit RSA and 4096 bit DH (unless you found a bug).

Look [here](https://github.com/pivpn/pivpn/blob/master/auto_install/install.sh#L803) and [here](https://github.com/pivpn/pivpn/blob/master/auto_install/install.sh#L883).

**Comment by anonymouz4** [comment]
But why does it then says 2048 bit in the .ovpn file or is it something else?

<img width="234" alt="screensh1" src="https://user-images.githubusercontent.com/32394757/40495789-71ad513c-5f78-11e8-9d3f-8cbec30020dd.png">

**Comment by orazioedoardo** [comment]
First of all, DH is not a “key”, instead they are parameters stored on the server and sent to the client to perform the authentication. Second, that static key is an additional security measure that encrypts the authentication itself (not related to dh).

From the manual:

> Encrypting (and authenticating) control channel packets:
• provides more privacy by hiding the certificate used for the TLS connection,
• makes it harder to identify OpenVPN traffic as such,
• provides "poor-man's" post-quantum security, against attackers who will never know the pre-shared key (i.e. no forward secrecy).

**Comment by anonymouz4** [comment]
I'm not an expert so I didn't know. But still do you know why it says 2048 bit in the .ovpn from this script and 4096 bit in the one from the other script?

**Comment by orazioedoardo** [comment]
Can you show me where in the other .ovpn file it spells `4096 bit OpenVPN static key`?

**Comment by anonymouz4** [comment]
Well I can't bc I already uninstalled everything inkl. ovpn and installed pivpn
