### ISSUE TITLE
Unable to connect from Kubuntu 18.04

### ISSUE THREAD

**Issue by syco** [pivpn/pivpn#542]
Hi,
I installed pivpn and generated a client profile without password, moved it to the second computer and tried to connect:

From commandline (sudo openvpn client.ovpn) it works beautifully.

When I imported the same profile in networkmanager it doesn't connect, here the output from journal:
```bash
May 30 13:42:05 torann nm-openvpn[10748]: WARNING: No server certificate verification method has been enabled.  See http://openvpn.net/howto.html#mitm for more info.
May 30 13:42:05 torann nm-openvpn[10748]: NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
May 30 13:42:05 torann nm-openvpn[10748]: TCP/UDP: Preserving recently used remote address: [AF_INET]my_public_ip:1194
May 30 13:42:05 torann nm-openvpn[10748]: Attempting to establish TCP connection with [AF_INET]w:1194 [nonblock]
May 30 13:42:06 torann nm-openvpn[10748]: TCP connection established with [AF_INET]my_public_ip:1194
May 30 13:42:06 torann nm-openvpn[10748]: TCP_CLIENT link local: (not bound)
May 30 13:42:06 torann nm-openvpn[10748]: TCP_CLIENT link remote: [AF_INET]my_public_ip:1194
May 30 13:42:06 torann nm-openvpn[10748]: Connection reset, restarting [0]
May 30 13:42:06 torann nm-openvpn[10748]: SIGUSR1[soft,connection-reset] received, process restarting
```
do you know how to fix it?
Thanks

**Comment by orazioedoardo** [comment]
I had the same problem with Manjaro, turns out it’s network manager’s fault. It doesn’t support the latest features very well. It you really want to use network manager you should uninstall pivpn and reinstall without 2.4 features.

P.S. I chose to use the command line and stick with a systemd service

**Comment by NESC1US** [comment]
https://bugs.kde.org/show_bug.cgi?id=395596

**Comment by devZer0** [comment]
https://bugs.launchpad.net/ubuntu/+source/network-manager/+bug/1749562?comments=all
