### ISSUE TITLE
Discord voice connecting

### ISSUE THREAD

**Issue by KyKyIIIKuH** [pivpn/pivpn#544]
## Issue
Hello.
Discord When connecting via OpenVPN, the message Connecting
The OpenVPN server uses the UDP port 11949
OS: Debian 9 x86_64
> Linux debian-2gb-fsn1-1 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64

This problem occurs if you connect via OpenVPN for Android, Linux, Windows.

![screenshot_20180613_183406](https://user-images.githubusercontent.com/7987636/41401311-2ef84f26-6fc8-11e8-9613-1878d57a14a1.png)

If you disable OpenVPN then everything works
![screenshot_20180614_115727](https://user-images.githubusercontent.com/7987636/41402103-1ea99baa-6fca-11e8-9616-e0e07631de57.png)

## Log console Discord Web Version:
> [RTCControlSocket] [CONNECT] wss://eu-west956.discord.gg/
> 
> [RTCConnection(178214961477189632)] Connecting to RTC server wss://eu-west956.discord.gg/.
[WS CLOSED] (false, 0, The connection timed out after 20000 ms - did not receive OP_HELLO in time.) retrying in 2.84 seconds.
> 
> [RTCControlSocket] [RECONNECT] wasClean=false code=0 reason=The connection timed out after 20000 ms - did not receive OP_HELLO in time.
> 
> [RTCControlSocket] [CONNECT] wss://eu-west956.discord.gg/
> 
> [RTCControlSocket] [WS CLOSED] (false, 0, The connection timed out after 20001 ms - did not receive OP_HELLO in time.) retrying in 5.00 seconds.
> 
> [RTCControlSocket] [RECONNECT] wasClean=false code=0 reason=The connection timed out after 20001 ms - did not receive OP_HELLO in time.

## Have you searched for similar issues and solutions? 
[https://support.discordapp.com/hc/en-us/articles/115001310031-Voice-Connection-Errors](https://support.discordapp.com/hc/en-us/articles/115001310031-Voice-Connection-Errors)

## Console output of `pivpn debug`
```
::: Generating Debug Output
:::                                     :::
::              PiVPN Debug              ::
:::                                     :::
::      Latest Commit                    ::
:::                                     :::
commit 33ed7e7012d5278162d72c3477a0d9b4345520ab
Merge: 1375fa1 30397f2
Author: redfast00 <redfast00@users.noreply.github.com>
Date:   Sat Mar 24 13:39:55 2018 +0100

    Merge pull request #502 from stan3/nonexecutable
    
    Changed permission bits on text files.
:::                                     :::
::      Recursive list of files in       ::
::      /etc/openvpn/easy-rsa/pki        ::
:::                                     :::
/etc/openvpn/easy-rsa/pki/:
akko0.ovpn
alina.ovpn
ca.crt
crl.pem
dan37rus.ovpn
Default.txt
dh2048.pem
index.txt
index.txt.attr
index.txt.attr.old
index.txt.old
issued
kykyiiikuh.ovpn
montes.ovpn
private
serial
serial.old
ta.key
xbox.ovpn

/etc/openvpn/easy-rsa/pki/issued:
akko0.crt
alina.crt
dan37rus.crt
kykyiiikuh.crt
montes.crt
server_MZImj1F7ZvUXURdr.key
xbox.crt

/etc/openvpn/easy-rsa/pki/private:
akko0.key
alina.key
ca.key
dan37rus.key
kykyiiikuh.key
montes.key
server_MZImj1F7ZvUXURdr.key
xbox.key
:::                                     :::
::      Output of /etc/pivpn/*           ::
:::                                     :::
:: START /etc/pivpn/DET_PLATFORM ::
Debian
:: END /etc/pivpn/DET_PLATFORM ::
:: START /etc/pivpn/INSTALL_PORT ::
11949
:: END /etc/pivpn/INSTALL_PORT ::
:: START /etc/pivpn/INSTALL_PROTO ::
udp
:: END /etc/pivpn/INSTALL_PROTO ::
:: START /etc/pivpn/INSTALL_USER ::
kykyiiikuh
:: END /etc/pivpn/INSTALL_USER ::
:: START /etc/pivpn/NO_UFW ::
1
:: END /etc/pivpn/NO_UFW ::
:: START /etc/pivpn/pivpnINTERFACE ::
eth0
:: END /etc/pivpn/pivpnINTERFACE ::
:: START /etc/pivpn/setupVars.conf ::
pivpnUser=kykyiiikuh
UNATTUPG=unattended-upgrades
pivpnInterface=eth0
IPv4dns=
IPv4addr=90.99.99.55
IPv4gw=142.39.1.1
pivpnProto=udp
PORT=11949
ENCRYPT=2048
APPLY_TWO_POINT_FOUR=false
DOWNLOAD_DH_PARAM=false
PUBLICDNS=
OVPNDNS1=8.8.8.8
OVPNDNS2=8.8.4.4
:: END /etc/pivpn/setupVars.conf ::
:::                                     :::
:: /etc/openvpn/easy-rsa/pki/Default.txt ::
:::                                     :::
client
dev tun
proto udp
remote 90.99.99.55 11949
resolv-retry infinite
nobind
persist-key
persist-tun
key-direction 1
remote-cert-tls server
tls-version-min 1.2
verify-x509-name server_MZImj1F7ZvUXURdr name
cipher AES-256-CBC
auth SHA256
comp-lzo
verb 3
:::                                     :::
::      Debug Output Complete            ::
:::                                     :::
::: 
::: Debug output completed above.
::: Copy saved to /tmp/debug.txt
::: 
```

## Console Output of `sudo iptables -t nat -S`
```
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT
-A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE
-A POSTROUTING -s 10.8.0.0/24 -o eth0 -j SNAT --to-source 90.99.99.55
```

## Console Output of `sudo iptables -S`
```
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
-A INPUT -p udp -m udp --dport 1900 -j DROP
-A INPUT -s 5.61.16.0/21 -j DROP
-A INPUT -s 5.61.232.0/21 -j DROP
-A INPUT -s 79.137.157.0/24 -j DROP
-A INPUT -s 79.137.174.0/23 -j DROP
-A INPUT -s 79.137.183.0/24 -j DROP
-A INPUT -s 94.100.176.0/20 -j DROP
-A INPUT -s 95.163.32.0/19 -j DROP
-A INPUT -s 95.163.212.0/22 -j DROP
-A INPUT -s 95.163.216.0/22 -j DROP
-A INPUT -s 95.163.248.0/21 -j DROP
-A INPUT -s 128.140.168.0/21 -j DROP
-A INPUT -s 178.22.88.0/21 -j DROP
-A INPUT -s 178.237.16.0/20 -j DROP
-A INPUT -s 178.237.29.0/24 -j DROP
-A INPUT -s 185.5.136.0/22 -j DROP
-A INPUT -s 185.16.148.0/22 -j DROP
-A INPUT -s 185.16.244.0/23 -j DROP
-A INPUT -s 185.16.246.0/24 -j DROP
-A INPUT -s 185.16.247.0/24 -j DROP
-A INPUT -s 188.93.56.0/21 -j DROP
-A INPUT -s 194.186.63.0/24 -j DROP
-A INPUT -s 195.211.20.0/22 -j DROP
-A INPUT -s 195.218.168.0/24 -j DROP
-A INPUT -s 217.20.144.0/20 -j DROP
-A INPUT -s 217.69.128.0/20 -j DROP
-A FORWARD -i tun0 -j ACCEPT
-A FORWARD -i tun0 -o eth0 -m state --state RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i eth0 -o tun0 -m state --state RELATED,ESTABLISHED -j ACCEPT
```

## output of `sudo netstat -uanp | grep openvpn`

```
udp        0      0 0.0.0.0:11949           0.0.0.0:*                           835/openvpn
```

## Discord developers answer
> Hey there, 
> 
> I'm afraid we don't provide support for getting VPNs up and running in conjunction with Discord. I'm so sorry about the trouble, and I really wish I could help you out here. 
> 
> Cheers, 
> Bjaker

Is it my server's problem or the discord problem?

**Comment by KyKyIIIKuH** [comment]
No one can help solve the problem?

**Comment by orazioedoardo** [comment]
I guess your server is on an hosted network, maybe they block discord all together (but I'm not sure). You could try to install pivpn on an home server to check if it works.

**Comment by KyKyIIIKuH** [comment]
When I'm connected to the VPN the internet is working.
On the home server through a VPN works Discord.

**Comment by orazioedoardo** [comment]
So, discord doesn't work from this specific server? `Linux debian-2gb-fsn1-1 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64`

**Comment by KyKyIIIKuH** [comment]
yes

**Comment by orazioedoardo** [comment]
Is that server a vps rented from some hosting service?

**Comment by KyKyIIIKuH** [comment]
This server is rented from Hetzner.
https://www.hetzner.com/cloud

**Comment by KyKyIIIKuH** [comment]
Thanks for the information provided.
