### ISSUE TITLE
PiVPN wrong path to ovpn files causing can not add a client

### ISSUE THREAD

**Issue by lebinho** [pivpn/pivpn#545]
# PiVPN Issue Template

## Issue
**I installed the PIVPN and attempted to create client certificates. They were created but I got strange paths where files were stored - see below the code I get when I add a client - weird lines I highlighted by putting 4 lines at the beginning :**

pi@raspberrypi ~ $ sudo pivpn add
cat: /etc/pivpn/INSTALL_USER: No such file or directory
Enter a Name for the Client:  pivpn-client1
Enter the password for the client:  
Enter the password again to verify:  
spawn ./easyrsa build-client-full pivpn-client1

Note: using Easy-RSA configuration from: ./vars
Generating a 2048 bit RSA private key
.....................+++
..........................................+++
writing new private key to '/etc/openvpn/easy-rsa/pki/private/pivpn-client1.key.B9r8jyAW88'
Enter PEM pass phrase:mypass

Verifying - Enter PEM pass phrase: mypass

-----
Using configuration from /etc/openvpn/easy-rsa/openssl-1.0.cnf
Check that the request matches the signature
Signature ok
The Subject's Distinguished Name is as follows
commonName            :PRINTABLE:'pivpn-client1'
Certificate is to be certified until Jun 11 22:32:18 2028 GMT (3650 days)

Write out database with 1 new entries
Data Base Updated
spawn openssl rsa -in pki/private/pivpn-client1.key -aes128 -out pki/private/pivpn-client1.key
Enter pass phrase for pki/private/pivpn-client1.key:mypass

writing RSA key
Enter PEM pass phrase:mypass

Verifying - Enter PEM pass phrase:mypass

Client's cert found: pivpn-client1.crt
Client's Private Key found: pivpn-client1.key
CA public Key found: ca.crt
tls-auth Private Key found: ta.key
cat: Default.txt: No such file or directory
>>>> cp: cannot create regular file `/home//ovpns/pivpn-client1.ovpn': No such file or directory
>>>> chown: cannot access `/home//ovpns/pivpn-client1.ovpn': No such file or directory

========================================================
Done! pivpn-client1.ovpn successfully created! 
pivpn-client1.ovpn was copied to:
  >>>> /home//ovpns
for easy transfer. Please use this profile only on one
device and create additional profiles for other devices.
========================================================
## Have you searched for similar issues and solutions? 

  YES, not found on raspberry main forum. When opened a topic more experienced people said to raise issue with you.

## Console output of `curl -L install.pivpn.io | bash`
```
  Output Here
```

## Console output of `pivpn add` or `pivpn add nopass`
```
  Output Here
```

## Console output of `pivpn debug`
```
  cat: /etc/pivpn/NO_UFW: No such file or directory
::: Generating Debug Output
:::					:::
::		PiVPN Debug		 ::
:::					:::
::	Latest Commit			 ::
:::					:::
commit b7c28af844d7a0fe0bbca5bf867c6f41863d2226
Merge: 8adbff7 d569034
Author: redfast00 <redfast00@users.noreply.github.com>
Date:   Tue May 29 22:38:46 2018 +0200

    Merge pull request #541 from pivpn/test
    
    Merge test branch into master
:::					:::
::	Recursive list of files in	 ::
::	/etc/openvpn/easy-rsa/pki	 ::
:::					:::
/etc/openvpn/easy-rsa/pki/:
ca.crt
crl.pem
dh2048.pem
index.txt
index.txt.attr
index.txt.attr.old
index.txt.old
issued
pivpn-client1.ovpn
pivpn-client2.ovpn
private
serial
serial.old
ta.key

/etc/openvpn/easy-rsa/pki/issued:
pivpn-client1.crt
pivpn-client2.crt
server_VU2DlmbB3PEJAfZA.crt

/etc/openvpn/easy-rsa/pki/private:
ca.key
pivpn-client1.key
pivpn-client2.key
server_VU2DlmbB3PEJAfZA.key
:::					:::
::	Output of /etc/pivpn/*		 ::
:::					:::
:: START /etc/pivpn/INSTALL_PORT ::
2222
:: END /etc/pivpn/INSTALL_PORT ::
:: START /etc/pivpn/INSTALL_PROTO ::
udp
:: END /etc/pivpn/INSTALL_PROTO ::
:: START /etc/pivpn/pivpnINTERFACE ::
wlan0
:: END /etc/pivpn/pivpnINTERFACE ::
:::					:::
:: /etc/openvpn/easy-rsa/pki/Default.txt ::
:::					:::
cat: /etc/openvpn/easy-rsa/pki/Default.txt: No such file or directory
:::					:::
::	Debug Output Complete		 ::
:::					:::
::: 
::: Debug output completed above.
::: Copy saved to /tmp/debug.txt
::: 
```

## Console Output of `sudo iptables -t nat -S`
```
  -P PREROUTING ACCEPT
-P INPUT ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT
```

## Console Output of `sudo iptables -S`
```
 -P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
```

## output of `sudo netstat -uanp | grep openvpn`
```
  pi@raspberrypi ~ $ sudo netstat -uanp | grep openvpn
pi@raspberrypi ~ $ 
```

## Have you taken any steps towards solving your issue? 
     which?

**Comment by lebinho** [comment]
@orazioedoardo no problems during installation. It is an instal with few programs on it. I think it was not the latest. I did an upgrade and planning to uninstall PiVPN and re-install to see if that will help.

**Comment by lebinho** [comment]
I made an upgrade to the latest Raspbian version and installed PiVPN again - this time works well.

**Comment by cfcolaco** [comment]
closing, as it seems to be resolved, thanks a lot @orazioedoardo for holding the boat around here!
