### ISSUE TITLE
Thanks for a great package!!

### ISSUE THREAD

**Issue by bmccorm2** [pivpn/pivpn#547]
Hi - I don't know if this is the appropriate forum but I couldn't find any other way.  I really appreciate your package and it has saved me money that I use to buy a VPN service :)  So I'd like to donate.  How do I do this?

Thanks again!

**Comment by cfcolaco** [comment]
@bmccorm2 Thanks for appreciating the project and will to contribute. however, pivpn // project maintainers are not accepting any direct contributions. 

> ## Contributions
> 
> I'm also interested in improving this script, please check the current issues to see where you can help. If you have any feature ideas or requests, or are interested in adding your ideas to it, testing it on other platforms, please comment or leave a pull request. If you contribute often I can add you as a member of the PiVPN project. I will be happy to work with you!
> 
> If you have found this tool to be useful and want to Donate then consider the following sources.
> 
>     I began this as a rough merger of the code at OpenVPNSetup who you can donate to at this PayPal link
> 
>     And the code at pi-hole.net
> 
>     Of course there is OpenVPN
> 
>     And as always the ever vigilant EFF
> 
> I don't take donations at this time but if you want to show your appreciation to me, then contribute or leave feedback on suggestions or improvements.


Once again thank you for enjoying and using PiVPN. 
Closing issue.
