### ISSUE TITLE
It installs fine but don't start on my BananaPi

### ISSUE THREAD

**Issue by gustavolinux** [pivpn/pivpn#548]
So, I just installed pivpn on my Banana Pi, it worked fine, no issues at all. But for some reason, the OpenVPN does not start when my system boots. 
I'm using debian on it.
The log file from the installation is below.

```
landi@bananapi:/etc/pivpn$ cat install.log 
:::
::: Stopping OpenVPN service...Stopping virtual private network daemon:.
 done.
:::   
::: Installing scripts to /opt/pivpn... done.
::: Using protocol: udp
::: Using OpenDNS servers.
Stopping enhanced syslogd: rsyslogd.
Starting enhanced syslogd: rsyslogd.
```

That's what happens when I try to run it manually:

```
landi@bananapi:/etc/pivpn$ sudo /etc/init.d/openvpn start
[FAIL] Starting virtual private network daemon: server failed!
```
Can someone help me?

**Comment by orazioedoardo** [comment]
Can you run `cat /etc/os-release` to check the debian version. Also `openvpn --version`.

**Comment by gustavolinux** [comment]
I have solved the issue some days ago, sorry for not posting it here.
It was just a wrong option that I've chosen when installing it.
