### ISSUE TITLE
No Default Gateway in Tunnel

### ISSUE THREAD

**Issue by Len-F** [pivpn/pivpn#55]
Setup PIVPN on RaspberryPi 3 - No Problems.
Created 3 user profiles on Rpi3 - No Problems.
Setup Windows Client OpenVPN-GUI (v2.3.11) - No Problems.
Connect to VPN - No Internet connectivity, but I can ping the VPN server, ssh to the VPN server, and then I can successfully ping the Internet world.

1) I cannot access the Internet from my laptop when connected to the VPN.
2) Errors appear in the client status log.

Here is the complete client status log:

---

Thu Jul 21 14:02:27 2016 OpenVPN 2.3.11 x86_64-w64-mingw32 [SSL (OpenSSL)] [LZO] [PKCS11] [IPv6] built on May 10 2016
Thu Jul 21 14:02:27 2016 Windows version 6.1 (Windows 7) 64bit
Thu Jul 21 14:02:27 2016 library versions: OpenSSL 1.0.1t  3 May 2016, LZO 2.09
Thu Jul 21 14:02:51 2016 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Thu Jul 21 14:02:51 2016 Control Channel Authentication: tls-auth using INLINE static key file
Thu Jul 21 14:02:51 2016 UDPv4 link local: [undef]
Thu Jul 21 14:02:51 2016 UDPv4 link remote: [AF_INET]75.85.162.112:1194
Thu Jul 21 14:02:52 2016 [pivpn] Peer Connection Initiated with [AF_INET]75.85.162.112:1194
Thu Jul 21 14:02:57 2016 do_ifconfig, tt->ipv6=0, tt->did_ifconfig_ipv6_setup=0
Thu Jul 21 14:02:57 2016 open_tun, tt->ipv6=0
Thu Jul 21 14:02:57 2016 TAP-WIN32 device [Local Area Connection 2] opened: \.\Global{87CA0FDB-AE94-4F72-B989-F29E9557973A}.tap
Thu Jul 21 14:02:57 2016 Notified TAP-Windows driver to set a DHCP IP/netmask of 10.8.0.6/255.255.255.252 on interface {87CA0FDB-AE94-4F72-B989-F29E9557973A} [DHCP-serv: 10.8.0.5, lease-time: 31536000]
Thu Jul 21 14:02:57 2016 Successful ARP Flush on interface [37] {87CA0FDB-AE94-4F72-B989-F29E9557973A}
Thu Jul 21 14:03:02 2016 **Warning: address 192.168.10.100 is not a network address in relation to netmask 255.255.255.0**
Thu Jul 21 14:03:02 2016 **ROUTE: route addition failed using CreateIpForwardEntry: The parameter is incorrect.   [status=87 if_index=37]**
Thu Jul 21 14:03:02 2016 env_block: add PATH=C:\Windows\System32;C:\Windows;C:\Windows\System32\Wbem
Thu Jul 21 14:03:02 2016 **ROUTE: route addition failed using CreateIpForwardEntry: The object already exists.   [status=5010 if_index=37]**
Thu Jul 21 14:03:02 2016 env_block: add PATH=C:\Windows\System32;C:\Windows;C:\Windows\System32\Wbem
Thu Jul 21 14:03:02 2016 Initialization Sequence Completed

---

Here is the relevant portion of the windows config (ipconfig /all) when connected to the tunnel:

---

Windows IP Configuration

   Host Name . . . . . . . . . . . . : Skibuff-T410
   Primary Dns Suffix  . . . . . . . : 
   Node Type . . . . . . . . . . . . : Hybrid
   IP Routing Enabled. . . . . . . . : No
   WINS Proxy Enabled. . . . . . . . : No

Ethernet adapter Local Area Connection 2:

   Connection-specific DNS Suffix  . : 
   Description . . . . . . . . . . . : TAP-Windows Adapter V9
   Physical Address. . . . . . . . . : 00-FF-87-CA-0F-DB
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : fe80::94c1:f970:6c7c:7adc%37(Preferred) 
   IPv4 Address. . . . . . . . . . . : 10.8.0.6(Preferred) 
   Subnet Mask . . . . . . . . . . . : 255.255.255.252
   Lease Obtained. . . . . . . . . . : Friday, July 22, 2016 2:01:24 PM
   Lease Expires . . . . . . . . . . : Saturday, July 22, 2017 2:01:24 PM
   **Default Gateway** . . . . . . . . . : 
   DHCP Server . . . . . . . . . . . : 10.8.0.5
   DHCPv6 IAID . . . . . . . . . . . : 620822407
   DHCPv6 Client DUID. . . . . . . . : 00-01-00-01-1D-30-76-37-F0-DE-F1-17-B5-A5
   DNS Servers . . . . . . . . . . . : 8.8.8.8
                                       8.8.4.4
   NetBIOS over Tcpip. . . . . . . . : Enabled

---

As you can see, the "Default Gateway" is blank.  My guess is that this is related to the "failed" route pushes during the VPN connection.

Finally, here is the server.conf file:

---

dev tun
proto udp
port 1194
ca /etc/openvpn/easy-rsa/keys/ca.crt
cert /etc/openvpn/easy-rsa/keys/pivpn.crt
key /etc/openvpn/easy-rsa/keys/pivpn.key
dh /etc/openvpn/easy-rsa/keys/dh2048.pem
server 10.8.0.0 255.255.255.0
# server and remote endpoints

ifconfig 10.8.0.1 10.8.0.2
# Add route to Client routing table for the OpenVPN Server

push "route 10.8.0.1 255.255.255.255"
# Add route to Client routing table for the OPenVPN Subnet

push "route 10.8.0.0 255.255.255.0"
# your local subnet

push "route 192.168.10.100 255.255.255.0"
# Set your primary domain name server address for clients

push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 8.8.4.4"
# Override the Client default gateway by using 0.0.0.0/1 and
#128.0.0.0/1 rather than 0.0.0.0/0. This has the benefit of
# overriding but not wiping out the original default gateway.

push "redirect-gateway def1"
client-to-client
duplicate-cn
keepalive 10 120
tls-version-min 1.2
tls-auth /etc/openvpn/easy-rsa/keys/ta.key 0
cipher AES-256-CBC
auth SHA256
comp-lzo
user nobody
group nogroup
persist-key
persist-tun
# crl-verify /etc/openvpn/crl.pem

status /var/log/openvpn-status.log 20
log /var/log/openvpn.log
verb 1
# This configuration file was originally written by Lauren Orsini at ReadWrite.

---

Can you advise me as to why the errors in the GUI status log, and why no Internet connectivity from client?  And thanks for doing this project.

**Comment by Len-F** [comment]
NOTE: Windows administrator account is being used.

**Comment by 0-kaladin** [comment]
hmm not sure what is going on here.  can you paste just the config (not certs) of the ovpn you are using?  Please paste within the code tags so it doesn't get formatted.

**Comment by Len-F** [comment]
Here is my client .ovpn file, and thank you in advance for your help.

`client
dev tun
proto udp
remote lfvpn.mynetgear.com 1194
resolv-retry infinite
nobind
persist-key
persist-tun
key-direction 1
remote-cert-tls server
tls-version-min 1.2
verify-x509-name pivpn name
cipher AES-256-CBC
auth SHA256
comp-lzo
verb 3
`

**Comment by Len-F** [comment]
Still no Internet connectivity through the tunnel.  I have tried a variety of environments
with EXACTLY the same symptoms.
   - Set up pivpn on Raspberry Pi 3 with Raspberian, eth0. No install problems.
   - Set up pivpn on lubuntu, eth0. No install problems.
   - Set up openvpn-gui on two different laptops (both WIN 7, 64-bit). No install problems.
   - Updated to openvpn-gui version 2.3.12  No install problems.

The Symptoms:
   - The tunnel comes up, but includes a client status message that says:
        Wed Sep 07 10:26:32 2016 Warning: address 192.168.10.100 is not a network address in
        relation to netmask 255.255.255.0
        Wed Sep 07 10:26:32 2016 ROUTE: route addition failed using CreateIpForwardEntry: The
        parameter is incorrect.   [status=87 if_index=17]
        Wed Sep 07 10:26:32 2016 Initialization Sequence Completed
   - Client is assigned an IP address of 10.8.0.6
   - I can ping 10.8.0.1 (the openvpn server)
   - I can SSH to 10.8.0.1 and login to the server via the command line
   - I can RDP to 10.8.0.1 and login to the server via the server gui
   - I can ping to devices on server's local network, including network printer
   - While logged in to the server, I can ping google.com
   ... BUT, FROM THE WINDOWS 7 CLIENT ...
   - I can NOT ping to any Internet site
   - I can NOT bring up any web browser page
   - I can NOT bring up the printer's http page
   - The client's Windows ipconfig shows no "default gateway" for the TAP device, but
     correctly shows the IP address and DNS addresses.

What Now?
I'm not too concerned about the fact that DNS is NOT going through the tunnel.  I presume
that I can change the server.conf file to push dns to 10.8.0.1.  Is that corrrect?  I can
make that change AFTER the vpn is working correctly.
My guess is that if I could correct the client's connect error ("route addition failed"),
then the vpn would work as expected.  But I need help with this.

**Comment by guydeke** [comment]
No, you should never point a DNS to your gateway or tunnel address.
Set it to 8.8.8.8 and 8.8.4.4   
See this page for it: https://en.wikipedia.org/wiki/Google_Public_DNS
Those are the Google DNS addresses. If this is not the solution you maybe have a firewall problem. 
Is your broadband router configurated to let through vpn trafic? 
Some routers block that traffic standard.
I asume you did your portforwarding in your router all right so from the internet side and all 1194 trafic is pushed to a certain static IP (e.g. 192.168.1.14 and NOT your tunnel address!) ?

**Comment by Len-F** [comment]
Sorry.  I accidentally closed this issue, but I just re-opened it.

Thank you for your suggestions to NOT to push the DNS through the tunnel.  As I indicated, I am NOT doing that, but I am curious why not.

As I indicated in my comment, the vpn tunnel is up.  The client is connecting to the vpn server via ping and ssh.  The router is Netgear WNDR4500v3, and it is configured to port forward 1194 to the vpn server: 192.168.10.100.  I can ping the server on both that address as well as 10.8.0.1.  Netgear states that no special config is required for vpn.

I need help with the connection error: "route addition failed".

**Comment by guydeke** [comment]
Probably you are connecting from your own home network. Try it from a friend / neighbours network. 
Now, from the inside of your home network, your vpn client is connecting to the outside address that is in your .ovpn file. Once connected with your PiVPN it is connecting to the internet again with the same address (your internet ip address). That can give connection failures. So try it from a neighbour's / friends internet connection and see if you can connect to your own VPN server. 
I think you'll find out that connecting from the internet side (thats where your vpn is for) will work.

**Comment by Len-F** [comment]
I AM NOT connecting the client from my home network.  I am connecting my client through my phone to the Internet.  Also, I am launching the client using "run as administrator".

You can see the client's status log at the top of this thread.  That shows the error.

**Comment by Len-F** [comment]
*** SOLVED! ***

ORIGINAL SYMPTOMS ON WINDOWS 7 CLIENT
The OpenVPN-GUI client showed that the tunnel was up. I could ping from the remote client to 
devices on the server's local lan, using addresses in the 192.168.xx.xx range.  However,
   1) I could not ping google.com.
   2) I could not ping or connect to any Internet site via a browser.
   3) I could not connect to the web service on the local lan's printer.
   4) I had errors in the client's log file about "route addition failed",
      and warnings about "address 192.168.xx.xx is not a network address in
      relation to netmask 255.255.255.0".
   5) The client's "ipconfig /all" output showed the default gateway for the
      Windows tap interface was blank.

ROOT CAUSE
The server firewall rule for the NAT was missing from the file /etc/iptables/rules.v4.  Once I 
corrected that and rebooted the server, then everything worked well.  The client was NOT the 
problem!

USER RECOMMENDATIONS
This install script is a great tool for simplifying the installation of OpenVPN on Raspberian.
However, it is not without its weaknesses when encountering errors.  Here are some
recommendations when using the (undated, as of September 15, 2016) script:

   1) Manually install the dependent packages "iptables-persistent", "dnsutils"
      and "expect", insuring that they install correctly
      (sudo apt-get install xxxx).  Then proceed with the normal installation.

   2) Be careful when/if changing the defaults for the certificate fields.  I
      tried to make some of them blank, and the easy-rsa module failed to
      create the necessary key and cert files.  I chose to keep the defaults,
      which will insure a degree of anonymity and works correctly - I recommend
      you do the same.

   3) Keep a close eye on the installation screen.  If I had done so, I would
      have seen that the "iptables-persistent" package did not install.  If
      you see some error, then stop the installation (^C) and deal with the
      problem.  This is important because I never did find the log files for
      the pivpn installtion which was supposed to be at /etc/pivpn/install.log.
      NOTE: You can walk away during the very long key-generation part of
      the script.

   4) After a presumed successful install, check the firewall rules, in both
      iptables and the file at /etc/iptables/rules.v4.  
         To see the rules in iptables, do this:
            sudo iptables-save
         To see the rules in the rules.v4 file, do this:
            sudo cat /etc/iptables/rules.v4
      In both cases, you should see a section that looks something like this: 
          *nat
          :PREROUTING ACCEPT [1288:154639]
          :INPUT ACCEPT [491:112273]
          :OUTPUT ACCEPT [312:23619]
          :POSTROUTING ACCEPT [312:23619]
          -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE
      The last line above is the important one.  If there is no such rule, or if
      there are multiple entries for this POSTROUTING rule, then you will need to
      fix it/them in one or both places so that they are identical.

   5) If you do an uninstall (pivpn -u), then pay attention to the firewall. A
      subsequent install may result in multiple entries for the NAT rule.  I had
      multiple rules for the NAT in iptables and the /etc/iptables/rules.v4 and
      had to manually fix this.

OTHER OBSERVATIONS
   1) Regarding the errors and warnings in the Windows client log as noted at the
      top, I found that they were NOT critical to correct operation.  I still
      don't know why they appear in the log and hope that someone else can provide
      an explanation.  I wasted a lot of time thinking that the problem was with
      the client when the problem was with the server.

   2) I was able to install pivpn onto a Lubuntu 16.04 distro on a HP laptop, but
      encountered the same problem as with the Raspberry PI, i.e. the iptables
      rules had no entry in both iptables and rules.v4.  I updated the rule in
      both places and the server performed as expected.

I will keep this issue opened for a little while to see if there are any comments, or 
suggestions, or corrections, or complaints.  Good luck to all.

**Comment by engelfrost** [comment]
Your 4th recomendation helped me. I had installed ufw before running the pivpn script. Removing /etc/iptables/rules.v4 (and using the settings in the configuration files in /etc/ufw/) solved it for me.

**Comment by 0-kaladin** [comment]
I'll close this but label as information as there is good information here.
The warning you got in the windows client log is now fixed.
I am still curious why iptables-persistent did not orig install for you.
That seemed to be the root of your issue.
per OTHER OBSERVATIONS:
1. I don't see this but on uninstall I do have it uninstall the iptables-persistent package.  this might clean those up for me.
2. Would again like to know where that is failing if you can ever dupe and provide the install output.  esp if you just run the same commands in the script after the install to get it working.

**Comment by aaronh86** [comment]
Additional Observation:
I had to do:
netfilter-persistant save in addition to the steps mentioned above.
I noticed that it was failing on start-up and was empty.

**Comment by wnabil** [comment]
This works for me as you mentioned to allow NAT into the firewall
https://www.revsys.com/writings/quicktips/nat.html
