### ISSUE TITLE
Incomplete Installation. It finish before all configurated...

### ISSUE THREAD

**Issue by lolako** [pivpn/pivpn#550]
I can't use pivpn add or something like this.
The Installer Blue Screen Stops before the Protocol Screen and in the Console output we can see that:

## Console output of `curl -L install.pivpn.io | bash`
```
root@raspberrypi:/# curl -L https://install.pivpn.io | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   178  100   178    0     0    180      0 --:--:-- --:--:-- --:--:--   180
100 54741  100 54741    0     0  36243      0  0:00:01  0:00:01 --:--:--  352k
:::
::: You are root.
::: Verifying free disk space...
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: Your system is up to date! Continuing with PiVPN installation...
::: Static IP already configured.
::: Using User: sergio
:::
::: Checking for existing base files...
:::    Checking /etc/.pivpn is a repo...:::    Cloning https://github.com/pivpn/                    pivpn.git into /etc/.pivpn... done!
:::
::: Stopping OpenVPN service... done.
 [\]  E: Unable to correct problems, you have held broken packages.       sed: c                    an't read /etc/apt/apt.conf.d/50unattended-upgrades: No such file or directory
::: Install Complete...
::: Restarting services...
openvpn.service is not a native service, redirecting to systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable openvpn
::: done.
:::
::: Installation Complete!
::: Now run 'pivpn add' to create an ovpn profile for each of your devices.
::: Run 'pivpn help' to see what else you can do!
::: It is strongly recommended you reboot after installation.
:::
::: The install log is located at: /etc/pivpn/install.log

```

**Comment by AlfredDing** [comment]
I got the same problem and I haven't found a way to fix it yet. I've tried to reinstall it for several times and always ended up before configuration.

**Comment by lolako** [comment]
I clean the Raspbian SO (New image burned) . And I tried again... It seems it works, i will tell you later

**Comment by cfcolaco** [comment]
Please read issue #399

**Comment by sheungon** [comment]
I got the same issue. Install was stopped before config.
And I found a fix.

1. Download the script by the following command
`curl -L https://install.pivpn.io | sed '2s/.*/set -x/' > install.sh; chmod a+x install.sh;`
2. Edit it by `nano install.sh`
3. Remove line 398 `$SUDO cp /tmp/pivpnINT /etc/pivpn/pivpnINTERFACE`
4. Save and close the script.
5. Run the script again by `sudo ./install.sh`

Looks like line 398 was a debug line. But it caused a failure during the install.

**Comment by pbassham** [comment]
`Remove line 398 $SUDO cp /tmp/pivpnINT /etc/pivpn/pivpnINTERFACE`

That worked for me. Thanks!

**Comment by 4s3ti** [comment]
we need to check if this is still happening. 
marking as bug for further investigation.

**Comment by 4s3ti** [comment]
closed by mistake .. reopening

**Comment by rrik** [comment]
This did not work for me. The installer continues to crash mid-install.

**Comment by 4s3ti** [comment]
Closing this ... lots of changes happened i guess this might be fixed if not it requires more and new data and more troubleshooting.
