### ISSUE TITLE
Incorrect generation of 2048 Bit RSA Key

### ISSUE THREAD

**Issue by renoimp** [pivpn/pivpn#551]
# PiVPN Issue Template

## Issue
Just did a new install of piVPN on Raspberry with Rspian Stretch (27.06.2018). The Generation of the 2048 Bit RSA Key only took about 10 Seconds instead of ca. 20-30 minutes. Cant verify, if correct encryption is used. Reinstalled the Raspberry three times, every time i got the same issue. On my old installation the generation of the rsa key took about 30 minutes.

## Have you searched for similar issues and solutions? 
    (yes/no / which issues?) 
  yes. Found an older reddit entry: https://www.reddit.com/r/raspberry_pi/comments/83iios/pivpn_2048_key_generation_time/

## Console output of `curl -L install.pivpn.io | bash`
```
  Output Here
```

## Console output of `pivpn add` or `pivpn add nopass`
```
  Output Here
```

## Console output of `pivpn debug`
```
  ::: Generating Debug Output
::: :::
:: PiVPN Debug ::
::: :::
:: Latest Commit ::
::: :::
commit
Merge:
Author: redfast00 <redfast00@users.noreply.github.com>
Date: Tue May 29 22:38:46 2018 +0200

Merge pull request #541 from pivpn/test

Merge test branch into master
::: :::
:: Recursive list of files in ::
:: /etc/openvpn/easy-rsa/pki ::
::: :::
/etc/openvpn/easy-rsa/pki/:
ca.crt
crl.pem
Default.txt
index.txt
index.txt.attr
index.txt.attr.old
index.txt.old
issued
private
serial
serial.old
ta.key
#hostname#.ovpn

/etc/openvpn/easy-rsa/pki/issued:
server_xxxxxxxxx.crt
#hostname#.crt

/etc/openvpn/easy-rsa/pki/private:
ca.key
server_XXXXXXXXXXX.key
#hostname#.key
::: :::
:: Output of /etc/pivpn/* ::
::: :::
:: START /etc/pivpn/DET_PLATFORM ::
Raspbian
:: END /etc/pivpn/DET_PLATFORM ::
:: START /etc/pivpn/INSTALL_PORT ::
1194
:: END /etc/pivpn/INSTALL_PORT ::
:: START /etc/pivpn/INSTALL_PROTO ::
udp
:: END /etc/pivpn/INSTALL_PROTO ::
:: START /etc/pivpn/INSTALL_USER ::
pi
:: END /etc/pivpn/INSTALL_USER ::
:: START /etc/pivpn/NO_UFW ::
1
:: END /etc/pivpn/NO_UFW ::
:: START /etc/pivpn/pivpnINTERFACE ::
eth0
:: END /etc/pivpn/pivpnINTERFACE ::
:: START /etc/pivpn/setupVars.conf ::
pivpnUser=pi
UNATTUPG=unattended-upgrades
pivpnInterface=eth0
IPv4dns=xxx.xxx.xx.3
IPv4addr=xxx.xxx.xx.4
IPv4gw=xxx.xxx.xx.1
pivpnProto=udp
PORT=1194
ENCRYPT=2048
APPLY_TWO_POINT_FOUR=true
DOWNLOAD_DH_PARAM=
PUBLICDNS=xyz.xyz.de
OVPNDNS1=xxx.xxx.xx.3
OVPNDNS2=
:: END /etc/pivpn/setupVars.conf ::
:: START /etc/pivpn/TWO_POINT_FOUR ::
:: END /etc/pivpn/TWO_POINT_FOUR ::
::: :::
:: /etc/openvpn/easy-rsa/pki/Default.txt ::
::: :::
client
dev tun
proto udp
remote xyz.xyz.de 1194
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
tls-version-min 1.2
verify-x509-name server_xxxxxxxxx name
cipher AES-256-CBC
auth SHA256
compress lz4
verb 3
::: :::
:: Debug Output Complete ::
::: :::
:::
::: Debug output completed above.
::: Copy saved to /tmp/debug.txt
:::
```

## Console Output of `sudo iptables -t nat -S`
```
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT
-A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE
```

## Console Output of `sudo iptables -S`
```
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT

```

## output of `sudo netstat -uanp | grep openvpn`

```
 udp        0      0 0.0.0.0:1194            0.0.0.0:*                           339/openvpn
```

## Have you taken any steps towards solving your issue? 
     which? 
Checked the openvpn server.conf and cant find a hint for 2048 Bit:

dev tun
proto udp
port 1194
ca /etc/openvpn/easy-rsa/pki/ca.crt
cert /etc/openvpn/easy-rsa/pki/issued/server_xxxxxxxxx.crt
key /etc/openvpn/easy-rsa/pki/private/server_xxxxxxxxx.key
dh none
ecdh-curve secp384r1
topology subnet
server 10.8.0.0 255.255.255.0
`# Set your primary domain name server address for clients
push "dhcp-option DNS xxx.xxx.xxx.xx"
push "block-outside-dns"
`# Override the Client default gateway by using 0.0.0.0/1 and
`# 128.0.0.0/1 rather than 0.0.0.0/0. This has the benefit of
`# overriding but not wiping out the original default gateway.
push "redirect-gateway def1"
client-to-client
keepalive 1800 3600
remote-cert-tls client
tls-version-min 1.2
tls-crypt /etc/openvpn/easy-rsa/pki/ta.key
cipher AES-256-CBC
auth SHA256
compress lz4
user nobody
group nogroup
persist-key
persist-tun
crl-verify /etc/openvpn/crl.pem
status /var/log/openvpn-status.log 20
status-version 3
syslog
verb 3
`#DuplicateCNs allow access control on a less-granular, per user basis.
`#Remove # if you will manage access by user instead of device.
`#duplicate-cn
`# Generated for use by PiVPN.io

**Comment by orazioedoardo** [comment]
I think you are referring to the Diffie-Hellman parameters. When you chosse to enable openvpn 2.4 features, an elliptic curve used for the key exchange, so the standard parameters are not created.

You can see it in the config:
> dh none
ecdh-curve secp384r1

Aside from this, is the VPN working for you?

**Comment by renoimp** [comment]
Hi orazioedoardo,
indeed the dh parameters. You`re right i can remember during the installation process i was asked for using "new" features. I choosed "yes".

VPN is working fine through double NAT. No big deal! : )

But is my setup less secure than generating an 2048 Bit Key for 30 minutes?
(Should really do a VPN-learning-session)

Thank you for the answer and sry for creating an issue.

**Comment by cfcolaco** [comment]
@renoimp no your setup is not less secure. ... elliptic curve is lighter and more secure than RSA which removes also the need for extra DH.

**Comment by renoimp** [comment]
Thank you cfcolaco for your help. Just was a bit worried.
