### ISSUE TITLE
Regenerate expired crl ?

### ISSUE THREAD

**Issue by damdam76** [pivpn/pivpn#553]
Hello all,

Thanks you for this great software suite.
Since yesterday, i can not connect anymore to my server.
After some researches, I found that it is a problem of expired crl.
There are some good threads on the internet dealing about this problem, but since I don't know where are locate the ca.key and ca.crt files (I'm even not sure PiVPN uses them) I can't regenerate using the command
`openssl ca  -gencrl -keyfile keys/ca.key -cert keys/ca.crt  -out keys/crl.pem -config ./openssl.cnf`
Can anyone help me please ?

**Comment by orazioedoardo** [comment]
This was fixed a long time ago, now the CRL last 3650 days instead of 180.
