### ISSUE TITLE
Successful Instal on Pi, but cannot get connected via iPhone Openvpn connect app

### ISSUE THREAD

**Issue by Markyloo** [pivpn/pivpn#556]
Hi, I don't believe my issue is related to pivpn, but the openvpn connect ios app.
I have successfully created a .ovpn file and got it onto the iphone, added the certificate, entered the password and hit connect.
It connects fine, and i see a vpn logo in the status bar at the top of the screen, but then whenever i change app it automatically disconnects.
In addition to thisif i press the cert link at the top of the app, it says this:
No Certificates are present in the keychain.
NOTE: PKCS#12 files need to end with '.ovpn12' instead of '.p12' or '.pfx', for proper importing (check FAQ)

I have checked the FAQ and can't find a solution.
Has anyone else come across this problem?

**Comment by orazioedoardo** [comment]
> No Certificates are present in the keychain.
NOTE: PKCS#12 files need to end with '.ovpn12' instead of '.p12' or '.pfx', for proper importing (check FAQ)
This is not a problem

However, this
> It connects fine, and i see a vpn logo in the status bar at the top of the screen, but then whenever i change app it automatically disconnects.
and this
> I am also running ios 12 beta 3 if that makes a difference.
make me think it’s a problem with the ios app, expecially since you are running a beta firmware. 

Do other (non ios-non beta) clients work?

**Comment by orazioedoardo** [comment]
@soydepr that’s not an problem, pivpn generates .ovpn files instead. Are you able to import them into the app?

**Comment by soydepr** [comment]
Yes I imported and just hangs 

![e909494e-06aa-48bb-8c9c-f76791f7fa1a](https://user-images.githubusercontent.com/546367/43687690-b3e8c5dc-98a7-11e8-96cc-4972a5a4983e.jpeg)

**Comment by orazioedoardo** [comment]
Ok so it’s not the same issue, post the raspberry pi log (omit ips if necessary): `cat /var/log/openvpn.log`

**Comment by soydepr** [comment]
Aug  5 09:04:49 coqui ovpn-server[310]: /sbin/ip addr add dev tun0 10.8.0.1/24 broadcast 10.8.0.255
Aug  5 09:04:49 coqui ovpn-server[310]: Could not determine IPv4/IPv6 protocol. Using AF_INET
Aug  5 09:04:49 coqui ovpn-server[310]: Socket Buffers: R=[163840->163840] S=[163840->163840]
Aug  5 09:04:49 coqui ovpn-server[310]: UDPv4 link local (bound): [AF_INET][undef]:1194
Aug  5 09:04:49 coqui ovpn-server[310]: UDPv4 link remote: [AF_UNSPEC]
Aug  5 09:04:49 coqui ovpn-server[310]: GID set to nogroup
Aug  5 09:04:49 coqui ovpn-server[310]: UID set to nobody
Aug  5 09:04:49 coqui ovpn-server[310]: MULTI: multi_init called, r=256 v=256
Aug  5 09:04:49 coqui ovpn-server[310]: IFCONFIG POOL: base=10.8.0.2 size=252, ipv6=0
Aug  5 09:04:49 coqui ovpn-server[310]: Initialization Sequence Completed

**Comment by orazioedoardo** [comment]
Server seems to be running fine. Check if the public ip specified in the .ovpn matches the public ip of your home connection (where the raspberry pi sits) and also check if forwarding on your router is correct: internal port, external port and internal ip.

**Comment by soydepr** [comment]
THANK YOU THANK YOU THANK YOU -


Seems my initial issue was certificate, after reinstall i change the port - now is working 

Thanks so much
