### ISSUE TITLE
xxx.ovpn file did not get copied to the Home directory.

### ISSUE THREAD

**Issue by WolfManLuke** [pivpn/pivpn#557]
# PiVPN Issue Template

## Have you searched for similar issues and solutions? 
 Yes, however, I am getting mix results.
  

## Console output of `curl -L install.pivpn.io | bash`
```
  pi@Petes_PI:~ $ pivpn add
cat: /etc/pivpn/INSTALL_USER: No such file or directory
Enter a Name for the Client:  petes_s5
Name can only contain alphanumeric characters and dashes (-).
pi@Petes_PI:~ $ pivpn add
cat: /etc/pivpn/INSTALL_USER: No such file or directory
Enter a Name for the Client:  petes-s5
Enter the password for the client:  
Enter the password again to verify:  
spawn ./easyrsa build-client-full petes-s5

Note: using Easy-RSA configuration from: ./vars
rand: Use -help for summary.
Generating a 2048 bit RSA private key
..................+++
...........+++
writing new private key to '/etc/openvpn/easy-rsa/pki/private/petes-s5.key.Dk42s0bY8c'
Enter PEM pass phrase:
Verifying - Enter PEM pass phrase:

-----
Using configuration from /etc/openvpn/easy-rsa/openssl-1.0.cnf
Check that the request matches the signature
Signature ok
The Subject's Distinguished Name is as follows
commonName            :ASN.1 12:'petes-s5'
Certificate is to be certified until Jul  4 13:39:09 2028 GMT (3650 days)

Write out database with 1 new entries
Data Base Updated
spawn openssl rsa -in pki/private/petes-s5.key -aes128 -out pki/private/petes-s5.key
Enter pass phrase for pki/private/petes-s5.key:
writing RSA key
Enter PEM pass phrase:
Verifying - Enter PEM pass phrase:
Client's cert found: petes-s5.crt
Client's Private Key found: petes-s5.key
CA public Key found: ca.crt
tls-auth Private Key found: ta.key
cat: Default.txt: No such file or directory
cp: cannot create regular file '/home//ovpns/petes-s5.ovpn': No such file or directory
chown: cannot access '/home//ovpns/petes-s5.ovpn': No such file or directory


========================================================
Done! petes-s5.ovpn successfully created! 
petes-s5.ovpn was copied to:
  /home//ovpns
for easy transfer. Please use this profile only on one
device and create additional profiles for other devices.
========================================================

pi@Petes_PI:~ $ 

```

## Console output of `pivpn add` or `pivpn add nopass`
```
 ## Console Output of `sudo iptables -t nat -S`
```
pi@Petes_PI:~ $ sudo iptables -t nat -S
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT
pi@Petes_PI:~ $ 

```

## Console Output of `sudo iptables -S`
```
  pi@Petes_PI:~ $ sudo iptables -S
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
pi@Petes_PI:~ $ 

```

## output of `sudo netstat -uanp | grep openvpn`

```
 pi@Petes_PI:~ $ sudo netstat -uanp | grep openvpn
udp        0      0 0.0.0.0:1194            0.0.0.0:*                           362/openvpn         
pi@Petes_PI:~ $ 

```

## Have you taken any steps towards solving your issue? 
     which?  No,  Not sure what to do.

<!-- If something else fails, please state the command you used and it's output -->

**Comment by orazioedoardo** [comment]
While I try to fix the underlying bug, try this workaround:

- Get back your certificate: `sudo cp "/etc/openvpn/easy-rsa/pki/petes-s5.ovpn" "/home/pi/ovpns/petes-s5.ovpn"` and `sudo chown pi "/home/pi/ovpns/petes-s5.ovpn"`
- Fix your installation so you can create more certificates`echo pi | sudo tee /etc/pivpn/INSTALL_USER`

**Comment by WolfManLuke** [comment]
Hello,
Thanks for the reply.  I will have to provide the additional  information you asking for later today.

**Comment by WolfManLuke** [comment]
pi@Petes_PI:~ $ cat /etc/passwd
root:$6$3UUjczOV$eeADWfqlCeViHXnRi0UZgUa4W6fPMaLmwMiFNFzbQJW8p7Z8GV3u.EBu8MrpA8G/lXWZYPIuOROrDHiqETBAE/:0:0:root:/root:/bin$
daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin
bin:x:2:2:bin:/bin:/usr/sbin/nologin
sys:x:3:3:sys:/dev:/usr/sbin/nologin
sync:x:4:65534:sync:/bin:/bin/sync
games:x:5:60:games:/usr/games:/usr/sbin/nologin
man:x:6:12:man:/var/cache/man:/usr/sbin/nologin
lp:x:7:7:lp:/var/spool/lpd:/usr/sbin/nologin
mail:x:8:8:mail:/var/mail:/usr/sbin/nologin
news:x:9:9:news:/var/spool/news:/usr/sbin/nologin
uucp:x:10:10:uucp:/var/spool/uucp:/usr/sbin/nologin
proxy:x:13:13:proxy:/bin:/usr/sbin/nologin
www-data:x:33:33:www-data:/var/www:/usr/sbin/nologin
backup:x:34:34:backup:/var/backups:/usr/sbin/nologin
list:x:38:38:Mailing List Manager:/var/list:/usr/sbin/nologin
irc:x:39:39:ircd:/var/run/ircd:/usr/sbin/nologin
gnats:x:41:41:Gnats Bug-Reporting System (admin):/var/lib/gnats:/usr/sbin/nologin
nobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin
systemd-timesync:x:100:103:systemd Time Synchronization,,,:/run/systemd:/bin/false
systemd-network:x:101:104:systemd Network Management,,,:/run/systemd/netif:/bin/false
systemd-resolve:x:102:105:systemd Resolver,,,:/run/systemd/resolve:/bin/false
systemd-bus-proxy:x:103:106:systemd Bus Proxy,,,:/run/systemd:/bin/false
_apt:x:104:65534::/nonexistent:/bin/false
pi:x:1000:1000:,,,:/home/pi:/bin/bash
messagebus:x:105:109::/var/run/dbus:/bin/false
statd:x:106:65534::/var/lib/nfs:/bin/false
sshd:x:107:65534::/run/sshd:/usr/sbin/nologin
avahi:x:108:112:Avahi mDNS daemon,,,:/var/run/avahi-daemon:/bin/false
lightdm:x:109:113:Light Display Manager:/var/lib/lightdm:/bin/false
epmd:x:110:115::/var/run/epmd:/bin/false
pi@Petes_PI:~ $

**Comment by orazioedoardo** [comment]
This raspbian installation is very unusual, you are not supposed to have the root password hash in the passwd file.

1. First edit your previous comment and paste again the /etc/passwd file. This time remove the first line (starting with root) and enclose the test inside the "insert code" tag.
2. Now post the content of `uname -a` and `cat /etc/os-release`.
3. Answer this question: 

> So, dumb question, did you reach the end of the installation? I mean, this text:

**Comment by WolfManLuke** [comment]
`pi@Petes_PI:~ $ sudo cat /etc/passwd
..........line deleted....................
daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin
bin:x:2:2:bin:/bin:/usr/sbin/nologin
sys:x:3:3:sys:/dev:/usr/sbin/nologin
sync:x:4:65534:sync:/bin:/bin/sync
games:x:5:60:games:/usr/games:/usr/sbin/nologin
man:x:6:12:man:/var/cache/man:/usr/sbin/nologin
lp:x:7:7:lp:/var/spool/lpd:/usr/sbin/nologin
mail:x:8:8:mail:/var/mail:/usr/sbin/nologin
news:x:9:9:news:/var/spool/news:/usr/sbin/nologin
uucp:x:10:10:uucp:/var/spool/uucp:/usr/sbin/nologin
proxy:x:13:13:proxy:/bin:/usr/sbin/nologin
www-data:x:33:33:www-data:/var/www:/usr/sbin/nologin
backup:x:34:34:backup:/var/backups:/usr/sbin/nologin
list:x:38:38:Mailing List Manager:/var/list:/usr/sbin/nologin
irc:x:39:39:ircd:/var/run/ircd:/usr/sbin/nologin
gnats:x:41:41:Gnats Bug-Reporting System (admin):/var/lib/gnats:/usr/sbin/nologin
nobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin
systemd-timesync:x:100:103:systemd Time Synchronization,,,:/run/systemd:/bin/false
systemd-network:x:101:104:systemd Network Management,,,:/run/systemd/netif:/bin/false
systemd-resolve:x:102:105:systemd Resolver,,,:/run/systemd/resolve:/bin/false
systemd-bus-proxy:x:103:106:systemd Bus Proxy,,,:/run/systemd:/bin/false
_apt:x:104:65534::/nonexistent:/bin/false
pi:x:1000:1000:,,,:/home/pi:/bin/bash
messagebus:x:105:109::/var/run/dbus:/bin/false
statd:x:106:65534::/var/lib/nfs:/bin/false
sshd:x:107:65534::/run/sshd:/usr/sbin/nologin
avahi:x:108:112:Avahi mDNS daemon,,,:/var/run/avahi-daemon:/bin/false
lightdm:x:109:113:Light Display Manager:/var/lib/lightdm:/bin/false
epmd:x:110:115::/var/run/epmd:/bin/false
pi@Petes_PI:~ $ `

`pi@Petes_PI:~ $ sudo uname -a
Linux Petes_PI 4.14.52-v7+ #1123 SMP Wed Jun 27 17:35:49 BST 2018 armv7l GNU/Linux
pi@Petes_PI:~ $ `


`pi@Petes_PI:~ $ sudo cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
pi@Petes_PI:~ $ 
`

So, dumb question, did you reach the end of the installation? I mean, this text:
::: Installation Complete!  **_YES ... INSTALLATION COMPLETED WITH ONLY THE ERROR ABOVE_**.
::: Now run 'pivpn add' to create an ovpn profile for each of your devices.
::: Run 'pivpn help' to see what else you can do!
::: It is strongly recommended you reboot after installation.

**Comment by farlock85** [comment]
I did a fresh install on my RPI3 with DietPI today and have the same problem:

`cat /etc/passwd
root:x:0:0:root:/root:/bin/bash
daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin
bin:x:2:2:bin:/bin:/usr/sbin/nologin
sys:x:3:3:sys:/dev:/usr/sbin/nologin
sync:x:4:65534:sync:/bin:/bin/sync
games:x:5:60:games:/usr/games:/usr/sbin/nologin
man:x:6:12:man:/var/cache/man:/usr/sbin/nologin
lp:x:7:7:lp:/var/spool/lpd:/usr/sbin/nologin
mail:x:8:8:mail:/var/mail:/usr/sbin/nologin
news:x:9:9:news:/var/spool/news:/usr/sbin/nologin
uucp:x:10:10:uucp:/var/spool/uucp:/usr/sbin/nologin
proxy:x:13:13:proxy:/bin:/usr/sbin/nologin
www-data:x:33:33:www-data:/var/www:/usr/sbin/nologin
backup:x:34:34:backup:/var/backups:/usr/sbin/nologin
list:x:38:38:Mailing List Manager:/var/list:/usr/sbin/nologin
irc:x:39:39:ircd:/var/run/ircd:/usr/sbin/nologin
gnats:x:41:41:Gnats Bug-Reporting System (admin):/var/lib/gnats:/usr/sbin/nologin
nobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin
systemd-timesync:x:100:103:systemd Time Synchronization,,,:/run/systemd:/bin/false
systemd-network:x:101:104:systemd Network Management,,,:/run/systemd/netif:/bin/false
systemd-resolve:x:102:105:systemd Resolver,,,:/run/systemd/resolve:/bin/false
systemd-bus-proxy:x:103:106:systemd Bus Proxy,,,:/run/systemd:/bin/false
_apt:x:104:65534::/nonexistent:/bin/false
messagebus:x:105:109::/var/run/dbus:/bin/false
statd:x:106:65534::/var/lib/nfs:/bin/false
dietpi:x:1000:1000::/home/dietpi:/bin/bash`

`Linux home 4.14.52-v7+ #1123 SMP Wed Jun 27 17:35:49 BST 2018 armv7l GNU/Linux`

`PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"`

Installation completed without errors for me too. I set the run user as `dietpi` but am SSH'd as `root`.

**Comment by mjsteinbaugh** [comment]
I just did a clean install of my Raspberry Pi using Raspbian stretch, and I'm seeing these same errors.

**Comment by jeremy21212121** [comment]
I also just hit this issue. There were some easily missed errors in the output. The first is this:
```
Using configuration from /etc/openvpn/easy-rsa/openssl-easyrsa.cnf
Can't open /etc/openvpn/easy-rsa/pki/index.txt.attr for reading, No such file or directory
3069325312:error:02001002:system library:fopen:No such file or directory:../crypto/bio/bss_file.c:74:fopen('/etc/openvpn/easy-rsa/pki/index.txt.attr','r')
3069325312:error:2006D080:BIO routines:BIO_new_file:no such file:../crypto/bio/bss_file.c:81:
```

The next error involves ip tables:

```

net.ipv4.ip_forward = 1
iptables v1.6.0: can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
::: Install Complete...
::: Restarting services...
Synchronizing state of openvpn.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable openvpn
::: done.

```
Notice the above text: `nat'. It is wrapped with one backtick and one single quote. Is this a typo? I need to investigate further.

I'm pretty sure I saw the installation completed message but I don't see it anymore. Is it output on stderr?

The missing INSTALL_USER file caused 'pivpn add' to output this:
```
cat: /etc/pivpn/INSTALL_USER: No such file or directory
Enter a Name for the Client:
```
...then it continues on to show more errors and falsely claim success.

```
Write out database with 1 new entries
Data Base Updated
Client's cert found: mobile.crt
Client's Private Key found: mobile.key
CA public Key found: ca.crt
tls-auth Private Key found: ta.key
cat: Default.txt: No such file or directory
cp: cannot create regular file '/home//ovpns/mobile.ovpn': No such file or directory
chown: cannot access '/home//ovpns/mobile.ovpn': No such file or directory


========================================================
Done! mobile.ovpn successfully created! 
mobile.ovpn was copied to:
  /home//ovpns
for easy transfer. Please use this profile only on one
device and create additional profiles for other devices.
========================================================
```
Notice the file path above: /home//ovpns. It tries to make a file path even though the variable is missing, causing cp to fail.

So, in summary, I see four issues here:

1. Missing file during install : /etc/openvpn/easy-rsa/pki/index.txt.attr
2. iptables can't find table `nat'
3. Missing INSTALL_USER file, even tho installer showed correct user 'pi'
4. 'pivpn add' should error and exit if a needed file is missing

I am halfway-decent with bash, so I will dive in and see what I can find.

I'd also like to replicate the issue with `set -x` to get a better idea what is going on. I will also try uninstalling, reinstalling and see if that resolves the issue for me too.

I do not have a hash for root in /etc/passwd. I was running an older kernel (from September 2018) during the install. I have since updated it to 4.14.

Here is the full output of the installer:

```
:::
::: sudo will be used for the install.
::: Verifying free disk space...
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: There are 33 updates available for your system!
::: We recommend you update your OS after installing PiVPN! 
:::
::: Static IP already configured.
::: Using User: pi
:::
::: Checking for existing base files...
:::    Checking /etc/.pivpn is a repo...:::    Cloning https://github.com/pivpn/pivpn.git into /etc/.pivpn... done!
:::
::: Stopping OpenVPN service... done.
:::   
::: Installing scripts to /opt/pivpn... done.
::: Using protocol: udp
set_var EASYRSA_ALGO       ec
set_var EASYRSA_CURVE      prime256v1
::: Building CA...
Generating an EC private key
writing new private key to '/etc/openvpn/easy-rsa/pki/private/ca.key.LXCYZhCpz0'
-----

::: CA Complete.

Note: using Easy-RSA configuration from: ./vars
Generating an EC private key
writing new private key to '/etc/openvpn/easy-rsa/pki/private/server_64FxhGn6n5xEstyA.key.ie6CXj0OKB'
-----
Using configuration from /etc/openvpn/easy-rsa/openssl-easyrsa.cnf
Can't open /etc/openvpn/easy-rsa/pki/index.txt.attr for reading, No such file or directory
3069325312:error:02001002:system library:fopen:No such file or directory:../crypto/bio/bss_file.c:74:fopen('/etc/openvpn/easy-rsa/pki/index.txt.attr','r')
3069325312:error:2006D080:BIO routines:BIO_new_file:no such file:../crypto/bio/bss_file.c:81:
Check that the request matches the signature
Signature ok
The Subject's Distinguished Name is as follows
commonName            :ASN.1 12:'server_64FxhGn6n5xEstyA'
Certificate is to be certified until Nov 24 22:19:39 2028 GMT (3650 days)

Write out database with 1 new entries
Data Base Updated

Note: using Easy-RSA configuration from: ./vars
Using configuration from /etc/openvpn/easy-rsa/openssl-easyrsa.cnf

An updated CRL has been created.
CRL file: /etc/openvpn/easy-rsa/pki/crl.pem

net.ipv4.ip_forward = 1
iptables v1.6.0: can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
::: Install Complete...
::: Restarting services...
Synchronizing state of openvpn.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable openvpn
::: done.
```

**Comment by jeremy21212121** [comment]
Note: I noticed when uninstalling pivpn that `easy-rsa` was never installed.

**Comment by 4s3ti** [comment]
> So, in summary, I see four issues here:
>
>1.Missing file during install : /etc/openvpn/easy-rsa/pki/index.txt.attr
>2.iptables can't find table `nat'
>3.Missing INSTALL_USER file, even tho installer showed correct user 'pi'
>4.'pivpn add' should error and exit if a needed file is missing


all of these are ofenly related to a badly installed Image, or as a result of thinkering with the OS. 
Please Make a fresh install of Raspian Stretch ... run
```
sudo apt-get update && sudo apt-get upgrade
```
then run PiVPN as per our documentation. 
If issue still persist please reopen this issue so it can be put up to investigation. 

Kind Regards.
