### ISSUE TITLE
VERIFY ERROR

### ISSUE THREAD

**Issue by iggs0** [pivpn/pivpn#56]
I try to install pivpn on a VPS with Ubuntu 14.04.
Installation works without problems.
But when i run 

```
ME@compPUTER ~ $ sudo openvpn --config me.ovpn 
Wed Jul 27 23:31:15 2016 OpenVPN 2.3.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [MH] [IPv6] built on Jul  8 2015
Wed Jul 27 23:31:15 2016 library versions: OpenSSL 1.0.2d 9 Jul 2015, LZO 2.08
Enter Private Key Password: ********************
Wed Jul 27 23:31:22 2016 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Wed Jul 27 23:31:22 2016 Control Channel Authentication: tls-auth using INLINE static key file
Wed Jul 27 23:31:22 2016 UDPv4 link local: [undef]
Wed Jul 27 23:31:22 2016 UDPv4 link remote: [AF_INET]185.136.89.164:1194
Wed Jul 27 23:31:22 2016 VERIFY ERROR: depth=1, error=certificate is not yet valid: C=CO, ST=ST, L=CITY, O=ORG, OU=ORG-UNIT, CN=COMMON-NAME, name=NAME, emailAddress=EMAIL
Wed Jul 27 23:31:22 2016 TLS_ERROR: BIO read tls_read_plaintext error: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
Wed Jul 27 23:31:22 2016 TLS Error: TLS object -> incoming plaintext read error
Wed Jul 27 23:31:22 2016 TLS Error: TLS handshake failed
Wed Jul 27 23:31:22 2016 SIGUSR1[soft,tls-error] received, process restarting
```

Server log shows

`Wed Jul 27 18:30:42 2016 OpenVPN 2.3.11 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [MH] [IPv6] built on May 10 2016
Wed Jul 27 18:30:42 2016 library versions: OpenSSL 1.0.1f 6 Jan 2014, LZO 2.06
Wed Jul 27 18:30:42 2016 Control Channel Authentication: using '/etc/openvpn/easy-rsa/keys/ta.key' as a OpenVPN static key file
Wed Jul 27 18:30:42 2016 TUN/TAP device tun0 opened
Wed Jul 27 18:30:42 2016 do_ifconfig, tt->ipv6=0, tt->did_ifconfig_ipv6_setup=0
Wed Jul 27 18:30:42 2016 /sbin/ip link set dev tun0 up mtu 1500
Wed Jul 27 18:30:42 2016 /sbin/ip addr add dev tun0 local 10.8.0.1 peer 10.8.0.2
Wed Jul 27 18:30:42 2016 GID set to nogroup
Wed Jul 27 18:30:42 2016 UID set to nobody
Wed Jul 27 18:30:42 2016 UDPv4 link local (bound): [undef]
Wed Jul 27 18:30:42 2016 UDPv4 link remote: [undef]
Wed Jul 27 18:30:42 2016 Initialization Sequence Completed
Wed Jul 27 18:32:28 2016 217.150.235.37:42522 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Wed Jul 27 18:32:28 2016 217.150.235.37:42522 TLS Error: TLS handshake failed
Wed Jul 27 18:32:30 2016 217.150.235.37:60157 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
`
Any ideas what I'm doing wrong

**Comment by 0-kaladin** [comment]
no idea why you are running that command, just read here https://github.com/pivpn/pivpn
or pivpn.io how to add a client.

**Comment by iggs0** [comment]
Hi 0-kaladin. You got this wrong - sudo openvpn --config me.ovpn is the command to connect the openvpn client to the OpenVPN server.
This ends in an endless loop. I assume something is wrong with certificate generation.

**Comment by iggs0** [comment]
Issue was with a bad configured OpenVZ VPS (wrong clock on host system). Issue resolved
