### ISSUE TITLE
How can you move a PiVPN installation to a new machine?

### ISSUE THREAD

**Issue by expertchoice** [pivpn/pivpn#560]
I have PiVPN installed on a odroid SBC unit, and I want to install PiVPN on a new RPI unit but use all of the current certificates and settings I have.  What would the process be to install PiVPN on the new unit and what files would I need to copy over?

**Comment by kyle95wm** [comment]
Just SCP your entire /etc/openvpn folder to the new Pi after setting up PiVPN

**Comment by FVilli** [comment]
ok, I do this. But "pivpn -l" return only the server ...

**Comment by james-lasersoft** [comment]
Did you copy all of the sub directories as well?

**Comment by 4s3ti** [comment]
Closing this as there is already an issue opened for this and we might implement a backup script. 

#179 

for further  discussion take it to subreddit. 
https://www.reddit.com/r/pivpn/
