### ISSUE TITLE
Installation error: Eth0 not selected by default, wizard proceeds

### ISSUE THREAD

**Issue by ChristofferNissen** [pivpn/pivpn#561]
# PiVPN Issue Template

No error reported. The installer just skips encryption. 

## Issue
Doing the installing, the eth0 interface isn't selected by default, and the installation proceeds without a network interface if the user does nothing.

## Have you searched for similar issues and solutions? 
    (yes/no / which issues?) 
Yes, read through all issues, and none seemed to be about this issue.

## Console output of `curl -L install.pivpn.io | bash`
```
  Output Here
```

## Console output of `pivpn add` or `pivpn add nopass`
```
  Output Here
```

## Console output of `pivpn debug`
```
  Output Here
```

## Console Output of `sudo iptables -t nat -S`
```
  Output Here
```

## Console Output of `sudo iptables -S`
```
  Output Here
```

## output of `sudo netstat -uanp | grep openvpn`

```
  Output Here
```

## Have you taken any steps towards solving your issue? 
     which? 

Installation works if I reinstall the program and select eth0

I know I haven't provided any of the output for commands, but doesn't seem relevant. Delete issue if you must.

**Comment by Giraffe1966** [comment]
@ChristofferNissen Please fill out your issue template, as it makes it easier to see what went wrong where. Also, did you get the whiptail prompt for interface selection? If you did, was anything in the prompt selected by default?

**Comment by 4s3ti** [comment]
Closing. 
Issue template not providing all details. 
Information Requested by @Giraffe1966 was not provided.
