### ISSUE TITLE
Is it possible to setup pivpn with a bridge mode router?

### ISSUE THREAD

**Issue by xiaohk** [pivpn/pivpn#564]
Hello, I have successfully installed `pivpn` but my clients cannot connect ("waiting for the server"). I guess my bridge mode router might be the problem.

I am using Airport Extreme router and to solve the "Double Nat" problem I have to configure it to bridge mode. I am not familiar with networking so I am wondering if it is possible to set up my server with a bridge mode router?

**Comment by d0nlab** [comment]
Sure you can. If the AE is in bridge more then your port forwarding must be setup on your gateway. Most likely the router/modem combo provided by your ISP. Have you already made configuration changes there?

**Comment by xiaohk** [comment]
@d0nlab Thanks for the input.

The problem is I am using a free network provided by my apartment. I connect my AE to the ethernet socket on the wall and I guess I have no control over the "main router".

**Comment by devZer0** [comment]
if you have no control of the routing device and don't have a public ip, i.e. if you cannot add port forwarding rule for your internal pivpn server with private ip, then you are out of luck.

as this ticket is quite old, please someone close this. we cannot do anything to help fixing your probem. for using von you may subscribe to a public vpn service provider. you can use that as a client vpn or you may even setup peer-to-peer vpn, so you can access your internal network from the outside via vpn provider. but afaik, that's not what pivpn is made for. you may have a look at pfsense, which has good openvpn support for all kind of complex setups. but it's much more complicated to setup/run.
