### ISSUE TITLE
CRL has expired

### ISSUE THREAD

**Issue by svib** [pivpn/pivpn#567]
After having worked splendidly for about half a year my piVPN server installation refuses connecting clients.  From the server log file, it seems that the CA certificate has expired. I have looked around and there are some guides how to renew it, but nothing specific for the piVPN installation, so it is not directly clear how to apply it.  Maybe this could be an option in the pivpn menu? Any suggestion how to resolve it?

```
Fri Jul 27 13:07:46 2018 us=790264 MULTI: multi_create_instance called
Fri Jul 27 13:07:46 2018 us=790712 192.168.4.100:53808 Re-using SSL/TLS context
Fri Jul 27 13:07:46 2018 us=790800 192.168.4.100:53808 LZO compression initializing
Fri Jul 27 13:07:46 2018 us=791129 192.168.4.100:53808 Control Channel MTU parms [ L:1622 D:1172 EF:78 EB:0 ET:0 EL:3 ]
Fri Jul 27 13:07:46 2018 us=791215 192.168.4.100:53808 Data Channel MTU parms [ L:1622 D:1450 EF:122 EB:406 ET:0 EL:3 ]
Fri Jul 27 13:07:46 2018 us=791412 192.168.4.100:53808 Local Options String (VER=V4): 'V4,dev-type tun,link-mtu 1570,tun-mtu 1500,proto UDPv4,comp-lzo,keydir $
Fri Jul 27 13:07:46 2018 us=791483 192.168.4.100:53808 Expected Remote Options String (VER=V4): 'V4,dev-type tun,link-mtu 1570,tun-mtu 1500,proto UDPv4,comp-l$
RFri Jul 27 13:07:46 2018 us=791670 192.168.4.100:53808 TLS: Initial packet from [AF_INET]192.168.4.100:53808, sid=e68cd7e3 4f098689
WRRWWRRWRFri Jul 27 13:07:46 2018 us=932679 192.168.4.100:53808 VERIFY ERROR: depth=0, error=CRL has expired: CN=XXXXXXX
Fri Jul 27 13:07:46 2018 us=932886 192.168.4.100:53808 OpenSSL: error:14089086:SSL routines:ssl3_get_client_certificate:certificate verify failed
Fri Jul 27 13:07:46 2018 us=932924 192.168.4.100:53808 TLS_ERROR: BIO read tls_read_plaintext error
Fri Jul 27 13:07:46 2018 us=932958 192.168.4.100:53808 TLS Error: TLS object -> incoming plaintext read error
Fri Jul 27 13:07:46 2018 us=932991 192.168.4.100:53808 TLS Error: TLS handshake failed
Fri Jul 27 13:07:46 2018 us=933160 192.168.4.100:53808 SIGUSR1[soft,tls-error] received, client-instance restarting
```

**Comment by svib** [comment]
After changing som search terms I got the answer on this forum. Now the client can connect again without doing any changes to it .ovpn client file.  Maybe still could be useful to include as an option to the piVPN menu?

https://github.com/pivpn/pivpn/issues/343

**Comment by adrianharabula** [comment]
Very useful, thanks! Had this problem last week and solved it by reinstalling pivpn. Wished to find a better way.

**Comment by soydepr** [comment]
I am having this issue, I reinstall and issue still not solved ?
any ideas ?

**Comment by ChristianTremblay** [comment]
I can now confirm that existing client will be able to connect again when the CRL "next update" date gets updated.

**Comment by Lagganmhouillin** [comment]
Thanks a lot for your help!

**Comment by thenktor** [comment]
To check the expiration date, do:
`sudo openssl crl -in crl.pem -text`

**Comment by sihui62** [comment]
> On my side, I modified the file `/etc/openvpn/easy-rsa/vars` and added (see last line)

Thx a lot @ChristianTremblay, this solved the problem for me, too.

**Comment by Mohand-Benrezkallah** [comment]
@thenktor Thank you for your help

**Comment by tgd-git** [comment]
@ChristianTremblay
> On my side, I modified the file `/etc/openvpn/easy-rsa/vars` and added (see last line)

Hi i have a little issue with this fix. It works fine until reboot. Everytime i change the vars file and reboot, the changes are lost. What am i missing?
I have applied this fix on another raspi before and it worked just fine, even after reboot.
