### ISSUE TITLE
TLS handshake failed

### ISSUE THREAD

**Issue by cholopa** [pivpn/pivpn#568]
Hi: 

I have setup a pivpn server and when selecting openvpn 2.4 improments it works fine.

My problem is i have an PLC(programable logic controller) that needs to work with version 2.3 of openvpn.

When setting 2.4 improments to off, I haven't been able to make a sucsesfull connection between server an other machines (android phone  or PC)

On client log i get this:

_Tue Jul 31 19:09:37 2018 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Tue Jul 31 19:09:37 2018 TLS Error: TLS handshake failed
Tue Jul 31 19:09:37 2018 SIGUSR1[soft,tls-error] received, process restarting
Tue Jul 31 19:09:37 2018 MANAGEMENT: >STATE:1533056977,RECONNECTING,tls-error,,,,,_

And on server log I get this:

_Jul 31 19:14:37 raspberrypi ovpn-server[10255]: Authenticate/Decrypt packet error: packet HMAC authentication failed
Jul 31 19:14:37 raspberrypi ovpn-server[10255]: TLS Error: incoming packet authentication failed from [AF_INET]XX.XX.XX.XX:51431_

What is strange to me is the port, I can see that it changes continuosly, it is not always 51431.

Shouldn't it be always 1194?

**this is the client ovpn:**

client
dev tun
proto udp
remote **XX.XX.XX.XX** 1194
resolv-retry infinite
nobind
persist-key
persist-tun
key-direction 1
remote-cert-tls server
tls-version-min 1.2
verify-x509-name server_UfmGLN1LedapxClO name
cipher AES-256-CBC
auth SHA256
comp-lzo
verb 3

**And this is the server conf:**

dev tun
proto udp
port 1194
ca /etc/openvpn/easy-rsa/pki/ca.crt
cert /etc/openvpn/easy-rsa/pki/issued/server_UfmGLN1LedapxClO.crt
key /etc/openvpn/easy-rsa/pki/private/server_UfmGLN1LedapxClO.key
dh /etc/openvpn/easy-rsa/pki/dh2048.pem
topology subnet
server 10.8.0.0 255.255.255.0

push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 8.8.4.4"

push "block-outside-dns"

push "redirect-gateway def1"
client-to-client
keepalive 1800 3600
remote-cert-tls client
tls-version-min 1.2
tls-auth /etc/openvpn/easy-rsa/pki/ta.key 0
cipher AES-256-CBC
auth SHA256
comp-lzo
user nobody
group nogroup
persist-key
persist-tun
crl-verify /etc/openvpn/crl.pem
status /var/log/openvpn-status.log 20
status-version 3
syslog
verb 3

Any help appreciatte!!!

**Comment by adrianharabula** [comment]
Hello,

In `server.conf`, replace:
`tls-auth /etc/openvpn/easy-rsa/pki/ta.key 0`
with
`tls-crypt /etc/openvpn/easy-rsa/pki/ta.key`

Then recreate profiles with `pivpn add` OR replace `<tls-auth>` and `</tls-auth>` with `tls-crypt` in existing client config files.

Restart server with `sudo systemctl restart openvpn@server` and try again connecting to the server.

Regards,
Adrian.

**Comment by cholopa** [comment]
Solved!!!

Thanks very much!!!!

**Comment by DazTurnip** [comment]
Yes!!
Been searching for a solution for ages.
This worked for me too.
Connecting to Pivpn via OpenVPN on iPhone. 

Thanks for posting.
