### ISSUE TITLE
Delete Client

### ISSUE THREAD

**Issue by johnBrereton** [pivpn/pivpn#569]
Is there any way to completely remove a client so the device does not appear in the list.

**Comment by adrianharabula** [comment]
Have you tried `pivpn -r`?

**Comment by jbrereton6** [comment]
That just revokes the account I am looking to remove the account so it can not be seen on the list.

**Comment by vrlnx** [comment]
I have same issue, it does not go away with `pivpn remove` nor `pivpn -r`

**Comment by orazioedoardo** [comment]
@vrlnx Assuming we are talking about OpenVPN, that's not a bug. It's by design. The client is still there (revoked) because the server needs to know that the client is explicitly forbidden.

**Comment by vrlnx** [comment]
@orazioedoardo - It's acctually wireguard installed, but I think this is on OpenVPN aswell. I see this as an issue, I don't think this is good to have as a "by-design" feature. I think this will bloat the pi.

**Comment by orazioedoardo** [comment]
@vrlnx It it's wireguard, then it's a bug. If it's openvpn, then it's by openvpn public key infrastructure/certificate design, not PiVPN's design. There is no "solution" in such case.

**Comment by orazioedoardo** [comment]
No replies in a while, closing... If you can reproduce the issue were a wireguard client can't be removed, open a new issue.
