### ISSUE TITLE
CA certificate not configurable

### ISSUE THREAD

**Issue by btopalka** [pivpn/pivpn#57]
The CA certificate information cannot be edited. Endless loop.

**Comment by 0-kaladin** [comment]
at what point exactly? during install?  what do you try to edit?

**Comment by btopalka** [comment]
During the install I can not edit the generated CA certificate.

**Comment by 0-kaladin** [comment]
After it has been generated? Or when the install wizard asks? Any
particular field?

**Comment by btopalka** [comment]
In the wizard during the install where it asks you if this ca info .. I
believe it's this chunk of code.
# Init Cert Values
    COUNTRY="US"
    STATE="CA"
    CITY="SanFrancisco"
    ORG="Fort-Funston"
    SERVER_NAME="server"
    KEY_NAME="EasyRSA"
    EMAIL="me@myhost.mydomain"

    whiptail --title "Certificate Information" --msgbox "You will now be
shown the default values for fields that will be used in the certificate.
\nIt is fine to leave these as-is since only you and the clients you create
will ever see this. \nHowever, if you want to change the values, simply
select the ones you wish to modify." $r $c

    until [[ $CERTVALCorrect = True ]]
    do
        CERTVAL=$(whiptail --title "Certificate Information" --checklist
"Choose any certificate values you want to change" $r $c 7 \
            "COUNTRY" "= US" OFF \
            "STATE" "= CA" OFF \
            "CITY" "= SanFranciso" OFF \
            "ORG" "= Fort-Funston" OFF \
            "SERVER_NAME" "= server" OFF \
            "KEY_NAME" "= EasyRSA" OFF \
            "EMAIL" "= me@myhost.mydomain" OFF 3>&1 1>&2 2>&3)

        exitstatus=$?
        if [ $exitstatus != 0 ]; then
            echo "::: Cancel selected. Exiting..."
            exit 1
        fi

        for i in $CERTVAL
        do
            if [ $i == '"COUNTRY"' ]; then
                COUNTRY=$(whiptail --title "Certificate Country" --inputbox
\
                "Enter a 2 letter abbreviation for Country" $r $c US 3>&1
1>&2 2>&3)
                $SUDO sed -i "s/\(KEY_COUNTRY=\"\).*/\1${COUNTRY}\"/" vars
            fi
            if [ $i == '"STATE"' ]; then
                STATE=$(whiptail --title "Certificate State" --inputbox \
                "Enter a 2 letter abbreviated State or Province" $r $c CA
3>&1 1>&2 2>&3)
                $SUDO sed -i "s/\(KEY_PROVINCE=\"\).*/\1${STATE}\"/" vars
            fi
            if [ $i == '"CITY"' ]; then
                CITY=$(whiptail --title "Certificate City" --inputbox \
                "Enter a City name" $r $c SanFrancisco 3>&1 1>&2 2>&3)
                $SUDO sed -i "s/\(KEY_CITY=\"\).*/\1${CITY}\"/" vars
            fi
            if [ $i == '"ORG"' ]; then
                ORG=$(whiptail --title "Certificate Org" --inputbox \
                "Enter an Organization name" $r $c Fort-Funston 3>&1 1>&2
2>&3)
                $SUDO sed -i "s/\(KEY_ORG=\"\).*/\1${ORG}\"/" vars
            fi
            if [ $i == '"EMAIL"' ]; then
                EMAIL=$(whiptail --title "Certificate Email" --inputbox \
                "Enter an Email Address" $r $c "me@myhost.mydomain" 3>&1
1>&2 2>&3)
                $SUDO sed -i "s/\(KEY_EMAIL=\"\).*/\1${EMAIL}\"/" vars
            fi
            if [ $i == '"SERVER_NAME"' ]; then
                SERVER_NAME=$(whiptail --title "Server Name" --inputbox \
                "Enter a Server Name" $r $c "pivpn" 3>&1 1>&2 2>&3)
                # This began a rabbit hole of errors. Nope.
                #sed -i '/export KEY_CN/s/^#//g' vars
                #sed -i "s/\(KEY_CN=\"\).*/\1${SERVER_NAME}\"/" vars
            fi
            if [ $i == '"KEY_NAME"' ]; then
                KEY_NAME=$(whiptail --title "Key Name" --inputbox \
                "Enter a Key Name" $r $c "EasyRSA" 3>&1 1>&2 2>&3)
                $SUDO sed -i "s/\(KEY_NAME=\"\).*/\1${KEY_NAME}\"/" vars
            fi
        done
        if (whiptail --backtitle "Confirm Certificate Fields" --title
"Confirm Certificate Fields" --yesno "Are these values correct?\n\n
Country:      $COUNTRY\n    State:        $STATE\n    City:
$CITY\n    Org:          $ORG\n    Email:        $EMAIL\n    Server Name:
$SERVER_NAME\n    Key Name:     $KEY_NAME" $r $c) then
            CERTVALCorrect=True
        else
            CERTVALCorrect=False
        fi
    done

It seems to be hard coded to those values and I can't seem to change them.
Ran a local copy and turned ON the country in the very top section which
got me to prompt to change the country code. I even went and hard coded all
the default values but when I went to go through the  generate ca and the
DH I got the output that it was using the default values.

I'll see if I can send some screenshots later on
today.

**Comment by 0-kaladin** [comment]
I've tested this over and over.  it first asks you to choose the ones you want to change.  You don't change it at that time.  The OFF simply means it isn't selected.  You select the ones you will want to edit and hit next.  then it asks you for the new values for the ones you selected.

**Comment by btopalka** [comment]
How are you selecting the ones you want to edit?

**Comment by sven250** [comment]
To select the fields you want to change, you press the space bar. A little star becomes visible in front of the selected option. After selecting the options you want to change, press enter and the script will let you change them. (It took also me a while to discover the space bar thing, maybe something to note in the descriptions?)

**Comment by btopalka** [comment]
thanks fixed ... only took me 2 months actually respond
