### ISSUE TITLE
Script doesn't run on Kali Raspberry Pi (Ubuntu based distro)

### ISSUE THREAD

**Issue by TheRoarkster** [pivpn/pivpn#574]
The script throws the following error when trying to run on the latest version of Kali for the Raspberry Pi:

```
Invalid OS ├───────────────────────────┐
                 │                                                                    │ 
                 │ We have not been able to detect a supported OS.                    │ 
                 │ Currently this installer supports Raspbian and Debian (Jessie and  │ 
                 │ Stretch), Devuan (Jessie) and Ubuntu from 14.04 (trusty) to 17.04  │ 
                 │ (zesty).                                                           │ 
                 │ If you think you received this message in error, you can post an   │ 
                 │ issue on the GitHub at https://github.com/pivpn/pivpn/issues.    
```

Any way to add Kali as a viable option?

**Comment by orazioedoardo** [comment]
As far as I know, the script has not been tested with kali. However, you can force the installation by removing [line 66](url
https://github.com/pivpn/pivpn/blob/master/auto_install/install.sh#L66) from the script.

**Comment by TheRoarkster** [comment]
Thanks.  Will try that and report back with results.

**Comment by TheRoarkster** [comment]
I can run the script piping it through bash **curl -L https://install.pivpn.io | bash**.  But when I copy the full script from the same URL, name it **pivpn_install.sh**, and try running it (as root) using **sh pivpn_install.sh**, I get an error: 

```
root@kali:/tmp# sh pivpn_install.sh
pivpn_install.sh: 27: pivpn_install.sh: Syntax error: "(" unexpected
```

Probably doing something stupid.  If you know, please respond?

**Comment by orazioedoardo** [comment]
It should still show the unsupported os warning but it should continue running it. How are you running the script?

**Comment by TheRoarkster** [comment]
After chmod'ing it to u+x, I used `./install.sh` from root.

**Comment by TheRoarkster** [comment]
Just ran it myself and it **did run without error**. 

Notes:  
1.  The line where "exit 1" resides on the latest version of the script is 69, not 66.  
2.  It won't set a static IP for you b/c you are not running Raspbian

That is all.  Otherwise, the installer runs perfectly.
