### ISSUE TITLE
Cannot connect anymore after RPi upgrade (Jessie -> Stretch)

### ISSUE THREAD

**Issue by Kroesss** [pivpn/pivpn#575]
I have a installation of PiVPN running on a RPi3, it has run without problems for almost a year. Today I upgraded (apt-get dist-upgrade) from Jessie to Stretch, and now I cannot connect to the PiVPN anymore.

Now, my knowlegde of Linuz is very limited, and therefore troubleshooting is also dificult for me. I can SSH with putty to the RPi, so network-connectivity is up. I also checked if Internet could be accessed, and it can (I also have Domoticz running on the same Pi, and that fetches weather-data as usual).

I have tried to check if openVPN is running with the following commands (and their respective output):

sudo service openvpn status
```
● openvpn.service - OpenVPN service
   Loaded: loaded (/lib/systemd/system/openvpn.service; enabled; vendor preset: enabled)
   Active: active (exited) since Mon 2018-08-06 17:53:11 CEST; 7min ago
  Process: 450 ExecStart=/bin/true (code=exited, status=0/SUCCESS)
 Main PID: 450 (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/openvpn.service

Aug 06 17:53:11 raspberrypi systemd[1]: Starting OpenVPN service...
Aug 06 17:53:11 raspberrypi systemd[1]: Started OpenVPN service.
```
ps auxww | grep openvpn
```
nobody     361  0.0  0.5   8564  5312 ?        Ss   17:53   0:00 /usr/sbin/openvpn --daemon ovpn-server --status /run/openvpn/server.status 10 --cd /etc/openvpn --config /etc/openvpn/server.conf --writepid /run/openvpn/server.pid
pi        1405  0.0  0.0   4372   556 pts/0    S+   18:01   0:00 grep --color=auto openvpn
```
Since I see no errors, I assume everything is up-and-running. However, when I try to connect using the native openVPN Android-app, it just sits their waiting for a connection.

Any ideas what might be wrong, or what I could try?

Edit: I also found Issue #343, but that is apparently not my issue, because I do not see a verify error after following through the first steps that are described.

**Comment by orazioedoardo** [comment]
Attempt a connection, then post the raspberry pi log, which you can read with `cat /var/log/openvpn.log` (omit your ip if necessary).

**Comment by Kroesss** [comment]
'''
Mon Aug  6 19:28:21 2018 *router-ip*:38643 VERIFY ERROR: depth=0, error=CRL $
Mon Aug  6 19:28:21 2018 *router-ip*:38643 OpenSSL: error:14089086:SSL routi$
Mon Aug  6 19:28:21 2018 *router-ip*:38643 TLS_ERROR: BIO read tls_read_plai$
Mon Aug  6 19:28:21 2018 *router-ip*:38643 TLS Error: TLS object -> incoming$
Mon Aug  6 19:28:21 2018 *router-ip*:38643 TLS Error: TLS handshake failed
'''
I see a verify error here, does this mean I do need to follow the directions in issue #343?

**Comment by orazioedoardo** [comment]
Yes, looks like it’s the same expired CRL error (even though your output is truncated).

**Comment by Kroesss** [comment]
Okay, I'll give his directions a try tonight or tomorrow and report back here.

**Comment by Kroesss** [comment]
Okay, couldn't contain myself, and turned the laptop back on :)

The truncating of the log-file is due to the fact that i copied it from my phone I think. When I look at the log-file on the laptop with putty, I see the complete lines.

Anyway: the solution worked like a charm! Thanks for your help @orazioedoardo !
