### ISSUE TITLE
How to kick some of the connected client?

### ISSUE THREAD

**Issue by RanaTarush** [pivpn/pivpn#577]
# PiVPN Issue Template

## Have you searched for similar issues and solutions? 
    (yes/no / which issues?) 
  

## Console output of `curl -L install.pivpn.io | bash`
```
  Output Here
```

## Console output of `pivpn add` or `pivpn add nopass`
```
  Output Here
```

## Console output of `pivpn debug`
```
  Output Here
```

## Console Output of `sudo iptables -t nat -S`
```
  Output Here
```

## Console Output of `sudo iptables -S`
```
  Output Here
```

## output of `sudo netstat -uanp | grep openvpn`

```
  Output Here
```

## Have you taken any steps towards solving your issue? 
     which?

**Comment by RanaTarush** [comment]
Like we can see the connected client with pivpn -c , any way we could kick someone from connected client.

**Comment by justinamcafee** [comment]
Do you want to permanently revoke their cert or only remove them?

**Comment by orazioedoardo** [comment]
1. Stop the server with `sudo systemctl openvpn stop`
2. Edit the server config with `sudo nano /etc/openvpn/server.conf`
3. Add this line`management 127.0.0.1 PORT` (replace PORT with a port number, like 1234)
3. Save the file and exit
5. Start the server with `sudo systemctl openvpn start`

To connect to the management interface, use `nc 127.0.0.1 PORT`, then disconnect a client with `kill CLIENTNAME`, use CTRL-C to exit.

More info [here](url
https://openvpn.net/index.php/open-source/documentation/miscellaneous/79-management-interface.html).

Consider also setting a password on the management interface as suggested on the [manual](https://community.openvpn.net/openvpn/wiki/Openvpn24ManPage).

**Comment by 4s3ti** [comment]
This has been added to FAQ here: https://github.com/pivpn/pivpn/wiki/FAQ
Closing.
