### ISSUE TITLE
OpenVpn error

### ISSUE THREAD

**Issue by GuyInHiding** [pivpn/pivpn#579]
When I start OpenVpn and connect to my PiVPN it gives me this error,
Tue Aug 14 13:32:24 2018 write UDP: Unknown error (code=10051)
Tue Aug 14 13:32:53 2018 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Tue Aug 14 13:32:53 2018 TLS Error: TLS handshake failed

I have the correct port forwarded, but still get this error. The VPN was working fine before and then it stopped so I reinstalled everything including the os and now I have this issue after forwarding port 1194

**Comment by soydepr** [comment]
Read this 
https://github.com/pivpn/pivpn/issues/567
