### ISSUE TITLE
After install pivpn, I can not use the "wget" command

### ISSUE THREAD

**Issue by ayton** [pivpn/pivpn#584]
Installed pivpn on Debian 8, everything works fine.
But now I can not use the "wget"

When I try to use this (for example):
wget --no-check-certificate https://raw.githubusercontent.com/teddysun/shadowsocks_install/master/shadowsocksR.sh
--2018-08-16 17:11:21--  https://raw.githubusercontent.com/teddysun/shadowsocks_install/master/shadowsocksR.sh
I get an error:
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... failed: Name or service not known.
wget: unable to resolve host address ‘raw.githubusercontent.com’
How can I fix this? Thanks

**Comment by 4s3ti** [comment]
@ayton this seems to be networking related, Issue template was not filled correctly. closing this issue 

if you still have this issue please take the discussion to pivpn subreddit.

Kind Regards.
