### ISSUE TITLE
DHCP

### ISSUE THREAD

**Issue by mitsoulias** [pivpn/pivpn#585]
I misunderstood how i can set to pivpn to give ip from my lical dhcp server. 

My dhcp server is on IP 192.168.x.x when i am connecting with open vpn client i am getting 10.0.01 how can i set to ask ip from my dhcp server?
Summary how is the easiest way to use an external dhcp server?

**Comment by Giraffe1966** [comment]
DHCP is not your problem. You want to allow clients to connect to your subnet. To do this, you must setup [bridging](https://community.openvpn.net/openvpn/wiki/307-what-is-bridging).
