### ISSUE TITLE
Suggestion/Advice: OpenVPN Review at https://github.com/securai/openvpn-review

### ISSUE THREAD

**Issue by HeCPX** [pivpn/pivpn#586]
## Suggestion / Advice

I just came across this OpenVPN Review and would like to share it with you:
https://github.com/securai/openvpn-review

Its quite nice and you can directly see that/if PiVPN is bullet-proof :)

PS: If anyone who is responsible for PiVPN, you can mark this as "closed/solved"
I just don't know how to tell you guys this without using this "issue-funktion"

PiVPN is a great project, big thank you!

**Comment by Giraffe1966** [comment]
Thanks for the advice! Sadly this repository hasn't been updated in over a year, thus the recommended settings are out of date with the introduction of things such as ECDSA. You may now close this issue if you wish.
