### ISSUE TITLE
pivpn worked well...not it does not

### ISSUE THREAD

**Issue by aerosdle** [pivpn/pivpn#587]
Hello. Some weeks ago i got pivpn working well,  today i tried to access my vpn again but there is no way, I get the TLS error. I didn't change anything since it worked. Now i tried changing from UDP to TCP protocol, unable firewall but nothing worked. The VPN still active as appear in "systemctl openvpn status". Of course ports are forwarded and the IP of the server is correct.

> Wed Aug 22 14:31:21 2018 OpenVPN 2.4.6 x86_64-w64-mingw32 [SSL (OpenSSL)] [LZO] [LZ4] [PKCS11] [AEAD] built on Apr 26 2018
Wed Aug 22 14:31:21 2018 Windows version 6.2 (Windows 8 or greater) 64bit
Wed Aug 22 14:31:21 2018 library versions: OpenSSL 1.1.0h  27 Mar 2018, LZO 2.10
Wed Aug 22 14:31:21 2018 MANAGEMENT: TCP Socket listening on [AF_INET]127.0.0.1:25347
Wed Aug 22 14:31:21 2018 Need hold release from management interface, waiting...
Wed Aug 22 14:31:22 2018 MANAGEMENT: Client connected from [AF_INET]127.0.0.1:25347
Wed Aug 22 14:31:22 2018 MANAGEMENT: CMD 'state on'
Wed Aug 22 14:31:22 2018 MANAGEMENT: CMD 'log all on'
Wed Aug 22 14:31:22 2018 MANAGEMENT: CMD 'echo all on'
Wed Aug 22 14:31:22 2018 MANAGEMENT: CMD 'bytecount 5'
Wed Aug 22 14:31:22 2018 MANAGEMENT: CMD 'hold off'
Wed Aug 22 14:31:22 2018 MANAGEMENT: CMD 'hold release'
Wed Aug 22 14:31:22 2018 MANAGEMENT: CMD 'password [...]'
Wed Aug 22 14:31:22 2018 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Wed Aug 22 14:31:22 2018 Outgoing Control Channel Authentication: Using 256 bit message hash 'SHA256' for HMAC authentication
Wed Aug 22 14:31:22 2018 Incoming Control Channel Authentication: Using 256 bit message hash 'SHA256' for HMAC authentication
Wed Aug 22 14:31:22 2018 MANAGEMENT: >STATE:1534941082,RESOLVE,,,,,,
Wed Aug 22 14:31:22 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]176.83.23.115:1194
Wed Aug 22 14:31:22 2018 Socket Buffers: R=[65536->65536] S=[65536->65536]
Wed Aug 22 14:31:22 2018 UDP link local: (not bound)
Wed Aug 22 14:31:22 2018 UDP link remote: [AF_INET]176.83.23.115:1194
Wed Aug 22 14:31:22 2018 MANAGEMENT: >STATE:1534941082,WAIT,,,,,,
Wed Aug 22 14:32:22 2018 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Wed Aug 22 14:32:22 2018 TLS Error: TLS handshake failed
Wed Aug 22 14:32:22 2018 SIGUSR1[soft,tls-error] received, process restarting
Wed Aug 22 14:32:22 2018 MANAGEMENT: >STATE:1534941142,RECONNECTING,tls-error,,,,,
Wed Aug 22 14:32:22 2018 Restart pause, 5 second(s)
Wed Aug 22 14:32:27 2018 MANAGEMENT: >STATE:1534941147,RESOLVE,,,,,,
Wed Aug 22 14:32:27 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]176.83.23.115:1194
Wed Aug 22 14:32:27 2018 Socket Buffers: R=[65536->65536] S=[65536->65536]
Wed Aug 22 14:32:27 2018 UDP link local: (not bound)
Wed Aug 22 14:32:27 2018 UDP link remote: [AF_INET]176.83.23.115:1194
Wed Aug 22 14:32:27 2018 MANAGEMENT: >STATE:1534941147,WAIT,,,,,,
Wed Aug 22 14:33:27 2018 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Wed Aug 22 14:33:27 2018 TLS Error: TLS handshake failed

The weird thing, as i say, is that the last time it worked, but no it appear the TLS error. Whar could it be?

**Comment by orazioedoardo** [comment]
Check issue #343

**Comment by ChristianTremblay** [comment]
or #590 has I got the same problem for this reason.

**Comment by arkid** [comment]
Check out the last comments at the bottom of this post, if it was working before its very likely due to your certificate expiring.  https://github.com/pivpn/pivpn/issues/567
