### ISSUE TITLE
No public ip address visible during install

### ISSUE THREAD

**Issue by corkerss** [pivpn/pivpn#588]
# PiVPN Issue Template

During installation no public ip address is visible. Only a blank space

## Have you searched for similar issues and solutions? 
  yes, public ip address issues
<img width="649" alt="screen shot 2018-08-23 at 22 13 46" src="https://user-images.githubusercontent.com/36156736/44552614-bf98f800-a722-11e8-9ab4-6861a21a1feb.png">

  

## Console output of `curl -L install.pivpn.io | bash`
```
 % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   178  100   178    0     0    572      0 --:--:-- --:--:-- --:--:--   572
100 51064  100 51064    0     0  91568      0 --:--:-- --:--:-- --:--:-- 91568
:::
::: sudo will be used for the install.
```

## Console output of `pivpn add` or `pivpn add nopass`
```
  Output Here
```

## Console output of `pivpn debug`
```
::: Generating Debug Output
:::					:::
::		PiVPN Debug		 ::
:::					:::
::	Latest Commit			 ::
:::					:::
commit de76940b65bab86eda772158da58328482363559
Merge: 18bfa92 58fcaaf
Author: redfast00 <redfast00@users.noreply.github.com>
Date:   Wed Aug 15 21:17:33 2018 +0200

    Merge pull request #554 from Giraffe1966/issue-552
    
    Fix issue #552 (remove dead code)
:::					:::
::	Recursive list of files in	 ::
::	/etc/openvpn/easy-rsa/pki	 ::
:::					:::
/etc/openvpn/easy-rsa/pki/:
ca.crt
crl.pem
Default.txt
index.txt
index.txt.attr
index.txt.old
issued
private
serial
serial.old
ta.key

/etc/openvpn/easy-rsa/pki/issued:
server_nD8T35MxdmUHaNSg.crt

/etc/openvpn/easy-rsa/pki/private:
ca.key
server_nD8T35MxdmUHaNSg.key
:::					:::
::	Output of /etc/pivpn/*		 ::
:::					:::
:: START /etc/pivpn/DET_PLATFORM ::
Debian
:: END /etc/pivpn/DET_PLATFORM ::
:: START /etc/pivpn/INSTALL_PORT ::
11942
:: END /etc/pivpn/INSTALL_PORT ::
:: START /etc/pivpn/INSTALL_PROTO ::
udp
:: END /etc/pivpn/INSTALL_PROTO ::
:: START /etc/pivpn/INSTALL_USER ::
dietpi
:: END /etc/pivpn/INSTALL_USER ::
:: START /etc/pivpn/NO_UFW ::
1
:: END /etc/pivpn/NO_UFW ::
:: START /etc/pivpn/pivpnINTERFACE ::
eth0
:: END /etc/pivpn/pivpnINTERFACE ::
:: START /etc/pivpn/setupVars.conf ::
pivpnUser=dietpi
UNATTUPG=unattended-upgrades
pivpnInterface=eth0
IPv4dns=
IPv4addr=192.168.1.209
IPv4gw=192.168.1.1
pivpnProto=udp
PORT=11942
ENCRYPT=2048
APPLY_TWO_POINT_FOUR=true
DOWNLOAD_DH_PARAM=
PUBLICDNS=
OVPNDNS1=8.8.8.8
OVPNDNS2=8.8.4.4
:: END /etc/pivpn/setupVars.conf ::
:: START /etc/pivpn/TWO_POINT_FOUR ::
:: END /etc/pivpn/TWO_POINT_FOUR ::
:::					:::
:: /etc/openvpn/easy-rsa/pki/Default.txt ::
:::					:::
client
dev tun
proto udp
remote  11942
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
tls-version-min 1.2
verify-x509-name server_nD8T35MxdmUHaNSg name
cipher AES-256-CBC
auth SHA256
compress lz4
verb 3
:::					:::
::	Debug Output Complete		 ::
:::					:::
::: 
::: Debug output completed above.
::: Copy saved to /tmp/debug.txt
::: 

```

## Console Output of `sudo iptables -t nat -S`
```
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT
-A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE
```

## Console Output of `sudo iptables -S`
```
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
-N ufw-after-forward
-N ufw-after-input
-N ufw-after-logging-forward
-N ufw-after-logging-input
-N ufw-after-logging-output
-N ufw-after-output
-N ufw-before-forward
-N ufw-before-input
-N ufw-before-logging-forward
-N ufw-before-logging-input
-N ufw-before-logging-output
-N ufw-before-output
-N ufw-reject-forward
-N ufw-reject-input
-N ufw-reject-output
-N ufw-track-forward
-N ufw-track-input
-N ufw-track-output
-A INPUT -j ufw-before-logging-input
-A INPUT -j ufw-before-input
-A INPUT -j ufw-after-input
-A INPUT -j ufw-after-logging-input
-A INPUT -j ufw-reject-input
-A INPUT -j ufw-track-input
-A FORWARD -j ufw-before-logging-forward
-A FORWARD -j ufw-before-forward
-A FORWARD -j ufw-after-forward
-A FORWARD -j ufw-after-logging-forward
-A FORWARD -j ufw-reject-forward
-A FORWARD -j ufw-track-forward
-A OUTPUT -j ufw-before-logging-output
-A OUTPUT -j ufw-before-output
-A OUTPUT -j ufw-after-output
-A OUTPUT -j ufw-after-logging-output
-A OUTPUT -j ufw-reject-output
-A OUTPUT -j ufw-track-output
```

## output of `sudo netstat -uanp | grep openvpn`

```
  udp        0      0 0.0.0.0:11942           0.0.0.0:*                           5968/openvpn      
```

## Have you taken any steps towards solving your issue? 
     which? 
google the issue, searched the issues forum

**Comment by elTorito666** [comment]
Lucky guy ;-) i'm trying now 3 hours the install of PiVPN on Raspberry, and this Setup Option will not show me, i can't try for anything of this options.

**Comment by orazioedoardo** [comment]
A lot of similar issues, like missings steps or broken installations seem related to DietPi.

**Comment by martin-corcoran-wdfc** [comment]
This problem also persists on my ubuntu 16.04 installation

**Comment by orazioedoardo** [comment]
What if you run those commands? Do they output your public ip?
`dig +short myip.opendns.com @resolver1.opendns.com`
`curl eth0.me`

**Comment by orazioedoardo** [comment]
I have no idea why dig is not returning your public, ip. What if you run `dig myip.opendns.com @resolver1.opendns.com`? Post the output censoring the IP (if any).

That curl command is a backup solution in case dig failed: in your case dig DID NOT fail, it just returned nothing, so the script does not try to use curl to retrieve the ip, and even if it did, eth0.me is down for me as well.

**Comment by corkerss** [comment]
<<>> DiG 9.10.3-P4-Ubuntu <<>> myip.opendns.com @resolver1.opendns.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 1882
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1452
;; QUESTION SECTION:
;myip.opendns.com.              IN      A

;; AUTHORITY SECTION:
opendns.com.            85840   IN      SOA     auth1.opendns.com. noc.opendns.com. 1535392811 16384 2048 1048576 2560

;; Query time: 141 msec
;; SERVER: 208.67.222.222#53(208.67.222.222)
;; WHEN: Mon Aug 27 19:15:22 BST 2018
;; MSG SIZE  rcvd: 91

**Comment by corkerss** [comment]
my public ip is no where to be seen when I run that command

**Comment by corkerss** [comment]
; <<>> DiG 9.10.3-P4-Debian <<>> myip.opendns.com @resolver1.opendns.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 42136
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;myip.opendns.com.		IN	A

;; AUTHORITY SECTION:
opendns.com.		1160	IN	SOA	auth1.opendns.com. noc.opendns.com. 1535392810 16384 2048 1048576 2560

;; Query time: 23 msec
;; SERVER: 208.67.222.222#53(208.67.222.222)
;; WHEN: Mon Aug 27 19:31:58 BST 2018
;; MSG SIZE  rcvd: 91

**Comment by corkerss** [comment]
first is the ubuntu command and the latte is the diet pi command

**Comment by corkerss** [comment]
This command does work and returns the correct address

dig TXT +short o-o.myaddr.l.google.com @ns1.google.com | sed 's/"//g'

**Comment by orazioedoardo** [comment]
Mmmh, your dig command returned NXDOMAIN, which means that resolver1.opendns.com can’t resolv myip.opendns.com (that is supposed to point to your ip). Before fixing the script using the google dig command can you do these tests first?

1. First, run the dig command using the actual ip of the resolver (bypassing your system dns): `dig myip.opendns.com @208.67.222.222`
2. What dns are you using on your system? Can you temporarily change them to google dns (8.8.8.8 8.8.4.4?
3. After tou have done that try both dig commands again: `dig myip.opendns.com @208.67.222.222` and `dig myip.opendns.com @reolver1.opendns.com`
4. If you still get NXDOMAIN in the output, can you try connecting your system to a different network (like a mobile hostspot) then try the dig commands?

**Comment by corkerss** [comment]
Thanks for all your help. I change my router to the OpenDNS servers for DNS ( its was previously google servers) and now it is showing in my ubuntu installation. Now to get working in odroid

**Comment by corkerss** [comment]
To  be clear

PiVPN could not find the Ip address when my Vodafone UK Router was set to the Google DNS Servers.

It found the correct Ip address once I set my DNS servers manually to the OpenDNS servers
