### ISSUE TITLE
add auth-nocache to client configuration

### ISSUE THREAD

**Issue by Lagganmhouillin** [pivpn/pivpn#589]
For security reasons the client configuration should contain the option auth-nocache.
My OpenVPN connect log contained a warning becaus this was missing, so I added it manually.
If there are clients which don't support that, mybe it can be optional?

**Comment by 4s3ti** [comment]
auth-nocache should not be a reason for concern, and it doesn't provide you with a real security improvement. 
If a third party has access to your memory you will have bigger concerns than your VPN password. 

This will also result in frequent prompts for vpn connection password, which is certainly desirable by most users.  for those who really want the added security it then it can be easily added manually to OVPN File.

adding a --auth-nocache switch to pivpn add should not be hard, however, won't prioritize this.

**Comment by Giraffe1966** [comment]
@4s3ti @Lagganmhouillin This feature was actually merged a long time ago, in #594. So this issue should be closed.
