### ISSUE TITLE
Errors running inside resin/rpi-raspbian container

### ISSUE THREAD

**Issue by krislabs** [pivpn/pivpn#59]
I've managed to set up openvpn inside resin/rpi-raspbian on Raspbian. I think you should probably change:
`if [[ $PLAT == "Ubuntu" || $PLAT == "Debian" ]]; then
        $SUDO service openvpn stop || true`

into:
`if [[ $PLAT == "Ubuntu" || $PLAT == "Raspbian" || $PLAT == "Debian" ]]; then
        $SUDO service openvpn stop || true`

and same for:
`if [[ $PLAT == "Ubuntu" || $PLAT == "Debian" ]]; then
            $SUDO iptables-save`

and this one:
`if [[ $PLAT == "Ubuntu" || $PLAT == "Debian" ]]; then
        $SUDO service openvpn start`

**Comment by 0-kaladin** [comment]
why?  on the supported Jessie raspbian image this is the command to stop it:
systemctl stop openvpn.service

not the service command.  Not sure how your container differs.
