### ISSUE TITLE
Documentation: how to renew expired certificate

### ISSUE THREAD

**Issue by Lagganmhouillin** [pivpn/pivpn#590]
Yesterday my certificate expired and I found no documentation how to renew.
(Workaround: reinstall and do setup again.)

**Comment by ChristianTremblay** [comment]
Same thing here. Revoked the user certificate then recreated the user made it...but a colleague had to be on-site so we can make it work.

**Comment by Lagganmhouillin** [comment]
I think this should be documented on the pivpn website as pivpn creates certificates with an expiry date.
Furthermore there should be an easier way to do that, perhaps the command line tool pivpn can be expanded?

**Comment by ChristianTremblay** [comment]
Finally, I think the real bug I had was related to CRL "next update" date too old. 
See #567 for the solution I found.

**Comment by 4s3ti** [comment]
closing as this is related to #567
