### ISSUE TITLE
Authenticate with RADIUS

### ISSUE THREAD

**Issue by merkyorz** [pivpn/pivpn#592]
OpenVPN allows authentication via RADIUS: https://docs.openvpn.net/configuration/integrating-active-directory-with-access-server-using-radius-and-post_auth/

Does PiVPN have the same capability?

**Comment by Giraffe1966** [comment]
No, as this capability requires OpenVPN Access Server, which only allows two free connections for testing. It is not free and open source. PiVPN installs OpenVPN, not Access Server.

**Comment by peimansh** [comment]
But is it possible to configure PiVPN with Radius plugin for OpenVPN ?

**Comment by 4s3ti** [comment]
@peimansh not at the moment and its not a feature we plan to, 

Be aware that PiVPN IS NOT A VPN ... its an OpenVPN installer.

**Comment by multiOTP** [comment]
Hello @peimansh,
You can check here : https://yvesdebeer.github.io/OpenVPN-with-RADIUS-and-Multi-Factor-Authentication/
Regards,
