### ISSUE TITLE
VPN Connection Very Slow

### ISSUE THREAD

**Issue by aryanasahel** [pivpn/pivpn#595]
# PiVPN Issue Template

## Issue
Firstly, thank you for coming up with this great idea. I was able to configure the setup and VPN. And I can connect to it also. However, I am not able to browse any sites including myip.is or Google. The only thing I can do is send and receive msgs on Whats App. The speed that is shown is usually in bits or kbits.

Can you please help? 

## Have you searched for similar issues and solutions? 
    (yes/no / which issues?) 
  
No

## Console output of `curl -L install.pivpn.io | bash`
```
  Output Here
```

## Console output of `pivpn add` or `pivpn add nopass`
```
  Output Here
```

## Console output of `pivpn debug`
```
  Output Here
```

## Console Output of `sudo iptables -t nat -S`
```
  Output Here
```

## Console Output of `sudo iptables -S`
```
  Output Here
```

## output of `sudo netstat -uanp | grep openvpn`

```
  Output Here
```

## Have you taken any steps towards solving your issue? 
     which?

**Comment by 4s3ti** [comment]
This is not related with PiVPN itself. 
the speed of your connection will depend on multiple factors: 

1 - The connection speed of your physical location
2 - The connection (both Down and UP) speed of OpenVPN server location. 
3 - Router settings on both sides

if you still want to take this further please feel free to take it to our subreddit. 
Kind Regards.
