### ISSUE TITLE
openvpn@server.service not starting automatically after install

### ISSUE THREAD

**Issue by ArthurAttout** [pivpn/pivpn#598]
(This is more of a warning than an issue since it did not result in a loss of functionality after all). 

After installing PIVPN on raspberry pi (debian 8.9) the service openvpn@server did not start automatically. 
Here is the output of `systemctl status openvpn@server`

```
openvpn@server.service - OpenVPN connection to server
Loaded: loaded (/lib/systemd/system/openvpn@.service; disabled)
Active: inactive (dead)
```

Although openvpn started successfully after the installation 

```
openvpn.service - OpenVPN service
   Loaded: loaded (/lib/systemd/system/openvpn.service; enabled)
   Active: active (exited) since Thu 2018-09-06 13:05:20 BST; 26min ago
  Process: 4578 ExecStart=/bin/true (code=exited, status=0/SUCCESS)
 Main PID: 4578 (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/openvpn.service
```
No warning nor error appeared during the installation. Trying to connect a client to the server resulted in `read udp unknown error (code=10054)` on the client. 

The service had to be started manually, then everything seems to work again.

**Comment by garghe** [comment]
Hi all, any update on this? I'm looking for a robust workaround in order to have openvpn to start after installation and reboot.

Thanks,
Marco

**Comment by 4s3ti** [comment]
after installing the service should be enabled. but if for some reason is not starting automatically after boot... 
`sudo systemcl enable openvpn` 
should do the trick.
