### ISSUE TITLE
DNS resolution (local & remote) + DNS suffix

### ISSUE THREAD

**Issue by ftt-prod** [pivpn/pivpn#599]
First, sorry if it isn't clear and if the text isn't formatted, it dosen't work and i dunno why.

Hi there, thanks everyone for the support and that wonderful script. Thats the only way my openvpn works.
**Here's my issue:**

1st case: Pivpn installed on a RPI3B+. Works extremly well. I can ping, access remote network, no problem at all except the DNS resolution

**remote network:**
Pivpn : 192.168.0.101
Gateway/dns/router/dhcp : 192.168.0.1

I'm at work, we've a domain, let's call it "**work.com**"
This is my client.

My remote network _(where the vpn/rpi is)_, has no domain at all (**no suffix**).

When i use my VPN, i need to use a **"dot"** after my hostnames.

For exemple " **Laptop.** " to connect by RDP.

It's a bit annoying as network shares etc.. don't work this way.

But the worst downside is **when the vpn is active on my client**, i have to **use the domain** after the hostnames for local ressources.
**server.work.com** for exemple. (so outlook dosen't work aswell this way)

ipconfig /all on my client gives for the tap:

**Suffixe DNS propre à la connexion. . . :**
   Description. . . . . . . . . . . . . . : TAP-Windows Adapter V9
   Adresse physique . . . . . . . . . . . : macadress
   DHCP activé. . . . . . . . . . . . . . : Oui
   Configuration automatique activée. . . : Oui
   Adresse IPv4. . . . . . . . . . . . . .: 10.8.0.2(préféré)
   Masque de sous-réseau. . . . . . . . . : 255.255.255.0
   Bail obtenu. . . . . . . . . . . . . . : vendredi 7 septembre 2018 14:41:22
   Bail expirant. . . . . . . . . . . . . : samedi 7 septembre 2019 14:41:22
   Passerelle par défaut. . . . . . . . . :
   Serveur DHCP . . . . . . . . . . . . . : 10.8.0.254
   Serveurs DNS. . .  . . . . . . . . . . : **192.168.0.1**
   NetBIOS sur Tcpip. . . . . . . . . . . : Activé

I can't send my nic work info, but **with the vpn active, it stays the same as with the vpn off.**

So on ipconfig the vpn dosen't change my real nic (except the vpn one)

The vpn pushes the right infos (right dns for exemple)

So what could it be? (i hope i'm pretty clear, sorry i'm a poor frenchie)

2nd case:

On a vm, at my parent's home, i installed **openvpn access server** (with an appliance)
DNS works the same, i have to put a dot for remote BUT **local resources work.** **I don't have to add the "work.com"**

Why?
I'm unable to find the server.conf file on the openvpnas, it could help me to compare as local dns work this that one.

Last info: my dns/dhcp one both remotes are ISP routers and **i can't change the domain pushed by the DHCP...**
I'd like to try with a .local and push the .local on my RPI server.conf but i can't. I also tried to push a "dot"  domain on my RPi conf but i gives me of course " .." **so laptop..** (and it doesn't resolves)

Here are some output from my Raspberry
Any "-------" are just private infos

Thanks for any tips..

## Console output of `pivpn debug`
```
  
::: Generating Debug Output
:::                                     :::
::              PiVPN Debug              ::
:::                                     :::
::      Latest Commit                    ::
:::                                     :::
commit b7c28af844d7a0fe0bbca5bf867c6f41863d2226
Merge: 8adbff7 d569034
Author: redfast00 <redfast00@users.noreply.github.com>
Date:   Tue May 29 22:38:46 2018 +0200

    Merge pull request #541 from pivpn/test

    Merge test branch into master
:::                                     :::
::      Recursive list of files in       ::
::      /etc/openvpn/easy-rsa/pki        ::
:::                                     :::
/etc/openvpn/easy-rsa/pki/:
ca.crt
crl.pem
Default.txt
index.txt
index.txt.attr
index.txt.attr.old
index.txt.old
issued
----------.ovpn
private
serial
serial.old
ta.key
---------.ovpn
---------.ovpn

/etc/openvpn/easy-rsa/pki/issued:
-------------.crt
-------------.crt
-------------.crt
-------------.crt

/etc/openvpn/easy-rsa/pki/private:
----------.key
----------.key
----------.key
---------.key
---------.key
:::                                     :::
::      Output of /etc/pivpn/*           ::
:::                                     :::
:: START /etc/pivpn/DET_PLATFORM ::
Raspbian
:: END /etc/pivpn/DET_PLATFORM ::
:: START /etc/pivpn/INSTALL_PORT ::
myport
:: END /etc/pivpn/INSTALL_PORT ::
:: START /etc/pivpn/INSTALL_PROTO ::
udp
:: END /etc/pivpn/INSTALL_PROTO ::
:: START /etc/pivpn/INSTALL_USER ::
myself
:: END /etc/pivpn/INSTALL_USER ::
:: START /etc/pivpn/NO_UFW ::
1
:: END /etc/pivpn/NO_UFW ::
:: START /etc/pivpn/pivpnINTERFACE ::
eth0
:: END /etc/pivpn/pivpnINTERFACE ::
:: START /etc/pivpn/setupVars.conf ::
pivpnUser=myself
UNATTUPG=unattended-upgrades
pivpnInterface=eth0
IPv4dns=192.168.0.1
IPv4addr=192.168.0.101
IPv4gw=192.168.0.1
pivpnProto=udp
PORT=myport
ENCRYPT=2048
APPLY_TWO_POINT_FOUR=true
DOWNLOAD_DH_PARAM=
PUBLICDNS=myddns
OVPNDNS1=208.67.222.222
OVPNDNS2=208.67.220.220
:: END /etc/pivpn/setupVars.conf ::
:: START /etc/pivpn/TWO_POINT_FOUR ::
:: END /etc/pivpn/TWO_POINT_FOUR ::
:::                                     :::
:: /etc/openvpn/easy-rsa/pki/Default.txt ::
:::                                     :::
client
dev tun
proto udp
remote myddns myport
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
tls-version-min 1.2
verify-x509-name ------------- name
cipher AES-256-CBC
auth SHA256
compress lz4
verb 3
:::                                     :::
::      Debug Output Complete            ::
:::                                     :::
:::
::: Debug output completed above.
::: Copy saved to /tmp/debug.txt
:::

```

## Console Output of `sudo iptables -t nat -S`
```
  -P PREROUTING ACCEPT
-P INPUT ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT
-A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE

```

## Console Output of `sudo iptables -S`
```
  
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT

```

## output of `sudo netstat -uanp | grep openvpn`

```
  It outputs nothing (normal?)
```

**Comment by ftt-prod** [comment]
No one? :(

**Comment by 4s3ti** [comment]
sorry @ftt-prod for late response pivpn has been quite stalled for a while .. but or I am missing something, or to me, all seems to be working as it should. 

However, this doesn't even seem to be related to PiVPN. 
if you want to further discuss this or some help, please take the issue to our subreddit, as from now on GitHub is strictly for issues related with PiVPN itself. 

Thank you for using PiVPN.
