### ISSUE TITLE
Cannot add user, i included a picture 

### ISSUE THREAD

**Issue by Ferkulj** [pivpn/pivpn#6]
http://prntscr.com/autwl0

**Comment by 0-kaladin** [comment]
I don't think your install worked.  I probably have issues if you install and are not the root user.  For now, do things as root.  Easiest is to login, then just type `sudo -i` and hit Enter.
then run the install.  Be root again to run `pivpn add`.
first to make sure you start with a clean slate, run the uninstall, `sudo pivpn uninstall`

**Comment by 0-kaladin** [comment]
I just fixed Issue #5  which should resolve your issue.  just
`pivpn uninstall`
then
`curl -L http://install.pivpn.io | bash`
