### ISSUE TITLE
Getting: curl: (7) Failed to connect to install.pivpn.io port 443: Connection refused

### ISSUE THREAD

**Issue by 42ism** [pivpn/pivpn#60]
When running curl -L https://install.pivpn.io | bash I am getting:

curl: (7) Failed to connect to install.pivpn.io port 443: Connection refused

I tried from a few different networks. Same.

Thanks.

**Comment by xifanyan** [comment]
Same here, please fix.

**Comment by ConorMulhern** [comment]
The install.pivpn.io site isn't currently available.

**Comment by ConorMulhern** [comment]
Site is available again and the install is now running for me. Cheers!

**Comment by 0-kaladin** [comment]
Sorry guys. Some maintenance... Will be staying up now.
