### ISSUE TITLE
Ubuntu on RPi3 still at 2.3.10, not 2.4.x

### ISSUE THREAD

**Issue by stna1981** [pivpn/pivpn#600]
Hello,

I'm just migrating my RPi3 from Raspbian to Ubuntu Mate 16.04 as Raspbian caused issues with TVHeadend since a few days. I wanted to use the new elliptic curve feature offered by PiVPN, however had to find out this will not work as PiVPN installs OpenVPN 2.3.10 from the Repo.

I tried to add the official repo and load 2.4 manually, but I only get the error that "repository 'http://build.openvpn.net/debian/openvpn/release/2.4 xenial InRelease' doesn't support architecture 'armhf'". So it seems I cannot do it manually.

Is there any way to get 2.4 branch to Ubuntu 16.04 for the RPi3 or do I have to stick with 2.3 for the next time until the armhf repo is updated? Sorry if this is a silly question, but I'm new to all this Linux stuff.

Best regards

Stefan

**Comment by orazioedoardo** [comment]
You could try to compile openvpn and openssl by yourself. However this way you won't get updates via the package manager.

**Comment by devZer0** [comment]
i think this is no question to ask pivpn project, that should go to the ubuntu distro/project or to openvpn project. 

pvipn cannot do anything about that
