### ISSUE TITLE
Unattended upgrades when read only

### ISSUE THREAD

**Issue by av-solutio** [pivpn/pivpn#603]
Hi,

I used [this ](https://hallard.me/raspberry-pi-read-only/)guide to make my card read only.
Will it be possible to install unattended upgrades when this is done? 

If this is not possible can anyone suggest me how to solve this?

Thanks in advance.

**Comment by orazioedoardo** [comment]
This issue it out of scope. However, personally I run a Raspberry Pi 24/7 powered by a power bank, so in case of a power outage, it stays running for serveral hours until the power is back. You only need to find a power bank that charges while charging.
