### ISSUE TITLE
Speed with 1 Gbps

### ISSUE THREAD

**Issue by joejoe2017** [pivpn/pivpn#605]
Hello, 

it is a question more than an issue, I had internet speed of 100 Mbps + PIVPN on ubuntu server, the speed test from the clients was max of 12 Mbps. lately I got in internet of 1 Gbps, the speed from the client is still 12 mbps.
is there is any way I can increase the VPN speed ?

**Comment by Giraffe1966** [comment]
What is the Internet speed of your client without the VPN? Are you using a Raspberry Pi? A Raspberry Pi will never give you 1 Gbps speed VPN. A VPN can not increase your speed faster than your slowest link, which is either the Raspberry Pi, or the client's Internet connection.

**Comment by joejoe2017** [comment]
the client is using 100 Mbps connection. 
vpn server is on Raspberry PI with 1 Gbps connection.
with this settings , I get the 12 Mbps. is this what it should be ?

**Comment by Giraffe1966** [comment]
The Raspberry Pi does not have very high network speeds. It is also not that fast. This means that encryption/decryption and data transfer will take longer. So 12 Mbps sounds about right. If you want  to get a 1 Gbps VPN, you must get a more powerful device, and faster Internet on the client, as the VPN is only as fast as the slowest link of the connection, which in this case is the Raspberry Pi.

**Comment by Blu-Eagle** [comment]
this article/test can clarify the max speed you can get on a RPI: https://www.jeffgeerling.com/blogs/jeff-geerling/getting-gigabit-networking

**Comment by ddavidebor** [comment]
Which raspberry do you have? Raspberry 3 b+ is the beefier currently

**Comment by devZer0** [comment]
not a pivpn related question but rather generic vpn/openvpn question. please close.
