### ISSUE TITLE
install.sh fails on Debian systems where /opt is not already there

### ISSUE THREAD

**Issue by eriklundh** [pivpn/pivpn#607]
# PiVPN Issue Template

## Issue
The install.sh silently fails, skipping several steps if the /opt dir is not present, but ends with a question if I want to reboot.
/opt is present on Rasbian, but not all Debian's creates /opt by default
mkdir /opt before invoking install.sh solved the problem, and the install completed sucessfully
Suggest adding -p to all instances of mkdir (-p means that missing directories will be created)
Such as
line 381  $SUDO mkdir /opt/pivpn
to 
line 381  $SUDO mkdir -p /opt/pivpn
## Have you searched for similar issues and solutions? 
    (yes/no / which issues?) 
  

## Console output of `curl -L install.pivpn.io | bash`
```
  Output Here
```

## Console output of `pivpn add` or `pivpn add nopass`
```
  Output Here
```

## Console output of `pivpn debug`
```
  Output Here
```

## Console Output of `sudo iptables -t nat -S`
```
  Output Here
```

## Console Output of `sudo iptables -S`
```
  Output Here
```

## output of `sudo netstat -uanp | grep openvpn`

```
  Output Here
```

## Have you taken any steps towards solving your issue? 
     which? 
I just invoked mkdir /opt before trying again with install.sh
Suggest adding -p to all instances of mkdir in the install script.
mkdir -p will create all missing directories in a path

**Comment by Giraffe1966** [comment]
Which distros don't have a `/opt/`?

**Comment by eriklundh** [comment]
Well, at least some of my some of my older dist-upgraded Debians doesn't have /opt as default.
One might argue the case of having some error handling instead of silently failing on such errors,
but my gentle suggestion is mkdir -p on all such paths, eliminating needs for a lot of error checking.

**Comment by 4s3ti** [comment]
Its indeed very weird not having /opt dir .. however won't make any harm to add -p, 
will mark this as bug and enhancement.

**Comment by 4s3ti** [comment]
Fixed, 
both on test: https://github.com/pivpn/pivpn/commit/412c8e83ac94ff47cb532495deba3638d7645ae0
and 
Master (accidentally made the change on the wrong brach): https://github.com/pivpn/pivpn/commit/2ea469359c357395110a0bfc951d0b6d1c7e9141

**Comment by orazioedoardo** [comment]
Merged into master: https://github.com/pivpn/pivpn/pull/914
