### ISSUE TITLE
IP Address

### ISSUE THREAD

**Issue by brckd6** [pivpn/pivpn#61]
I transfered the .ovpn file to my Android phone and loaded it into the Android OpenVPN app. I forwarded port 1194 on my router as well. When I try to connect with the app it just stays on "Waiting for Server" until it times out. I noticed the OpenVPN Profile IP address does not match my Pi's external IP address. Is this the problem? How do I fix this?

**Comment by MohammedHoosen** [comment]
Re-run the setup and use your dyndns host name as the external ip address, then regenerate the ovpn profile.

**Comment by brckd6** [comment]
Is that at the very beginning where it asks for my static IP address?

**Comment by brckd6** [comment]
Okay at the end I tried to select to use the custom DNS but it looks like it just loaded the Google default anyway, how do I change that selection?
