### ISSUE TITLE
problem connecting using iPhone

### ISSUE THREAD

**Issue by Blu-Eagle** [pivpn/pivpn#610]
I installed PiVPN on rpi at home and installed tunnelblick on my Mac.
I connect my Mac to internet through my iPhone via tunnelblick and everything works great, I can see every device at home.

if instead I connect to my home using openVPN app on my iPhone, I can connect to vpn server, but when I connect my Mac to my iPhone via personal hotspot function, my Mac cannot connect home. I do not see even the virtual IP of vpn server (RPI) on the other side.

to better explain:
- iPhone gives to my Mac address: 172.20.10.8
- my iPhone hotspot has as address: 172.20.10.1
- the virtual IP of my iPhone (VPN tunnel on the phone side): is: 10.8.0.2
- the virtual ip of the tunnel on VPN server side  is: 10.8.0.1

if I try to ping from my Mac 10.8.0.1 I do not get any answer. so I do not go beyond the iPhone side of the tunnel.

it seems there is no forwarding rule from iPhone wifi to VPN tunnel.
but if I try to access the servers from my iPhone or opening web page on a server at home from iPhone browser everything works.

any idea on how to solve this issue?

**Comment by orazioedoardo** [comment]
The openvpn app connects your iPhone to the VPN but I guess the hostpot uses a different network interfaces outside the tunnel. This behaviour can’t be modified server side. What would be the benefit anyways?

**Comment by Blu-Eagle** [comment]
> The openvpn app connects your iPhone to the VPN but I guess the hostpot uses a different network interface outside the tunnel. This behaviour can’t be modified server side. What would be the benefit anyways?

The idea was to VPN home with a phone and having one or more devices connected to the phone hotspot as if they were at home. In this way I do not need to set up a vpn on all the devices.
think about a wifi only tablet..
Anyway I agree with your conclusion, I think it cannot be done at least on an iPhone, maybe on a rooted android might work.

**Comment by jalanjarosz** [comment]
Resources might be better handled with individual clients establishing the VPN, over doing a shared VPN though a phone hot-spot.

I watched a YouTube video where he used OpenVPN to connected to a 3rd party VPN service account and allowed all his systems on his network to use a VPN tunnel.   You might need to setup the iPhone as a hot-spot, use a Pi to connect to that, and finally your clients to connect to the Pi to get the tunnel.

**Comment by 4s3ti** [comment]
Not PiVPN related. 
Closing.
