### ISSUE TITLE
CORE_THREAD_INACTIVE Error

### ISSUE THREAD

**Issue by kikkoskat** [pivpn/pivpn#611]
Hello. I install pivpn on my raspberry and everything works but after 3-4 weeks i cannot connect with clients. Error in openvpn app is  CORE_THREAD_INACTIVE. Why? Whta can i do to solve the problem? thank you

**Comment by 4s3ti** [comment]
Seems to me some update got broken, 
and doesn't seems connected to PiVPN at all but rather an OpenVPN issue. 

1. Please try to re-install openvpn
2. Re-install raspbian and run pivpn again
