### ISSUE TITLE
Freeze on Preparing to configure dhcpcd5 (armhf)

### ISSUE THREAD

**Issue by MrAwesome8** [pivpn/pivpn#614]
# PiVPN Issue Template

## PiVPN Freeze on "Preparing to configure dhcpcd5 (armhf)"

It gets to 27% and stops responding. I've left it for a few hours and still at 27%. I've ran it multiple times, the very first it got up to the 60's. Every time after has been 27.

Headless setup via SSH. Fresh install of stretch, installed pihole, now trying to install pivpn.

PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian

## Have you searched for similar issues and solutions? 
   https://old.reddit.com/r/pihole/comments/5lnc0r/updateinstall_hanging_at_configuring_dhcpcd5/
  
   `sudo ps -aux | grep [d]ebconf-apt-progress | awk '{print $2}` returned no pids.

   Website (http://www.pivpn.io/) says get Jesse, but docs (https://github.com/pivpn/pivpn#prerequisites) say Stretch. Assuming website is outdated.

## Console output of `curl -L install.pivpn.io | bash`
```
    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   178  100   178    0     0    576      0 --:--:-- --:--:-- --:--:--   576
100 51064  100 51064    0     0  79127      0 --:--:-- --:--:-- --:--:-- 79127
:::
::: sudo will be used for the install.
::: Verifying free disk space...
:::
::: Checking apt-get for upgraded packages....
::: done!
```

## Console output of `pivpn add` or `pivpn add nopass`
```
  
```

## Console output of `pivpn debug`
```
  
```

## Console Output of `sudo iptables -t nat -S`
```
  
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT

```

## Console Output of `sudo iptables -S`
```
  
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT

```

## output of `sudo netstat -uanp | grep openvpn`

```
  None
```

**Comment by 4s3ti** [comment]
issue is quite old without any activity, lots of stuff had changed, 
If the issue is still a thing, take the issue to our subreddit [r/pivpn](https://www.reddit.com/r/pivpn/)
