### ISSUE TITLE
VPN would not Connect

### ISSUE THREAD

**Issue by siamak06** [pivpn/pivpn#616]
I have made a VPN Server using PiVPN and was working for more than 6 months and sudenlly would not connect, it goes on and on and on and wont connect.

Used to update and upgrade and dist-upgrade, the same, reinstalled the PiVPN (not fresh) it was the same going round and round and not connecting.

What seems to be the problem? The Pi shows on the Router, I probably have to start from square one, which I did not wish to do, if some one comes up with a solution with in next 24 hours I will appreciate it.
Cheers
And thanks in advance.

**Comment by orazioedoardo** [comment]
Follow this: 
https://github.com/pivpn/pivpn/issues/343#issuecomment-327523116
