### ISSUE TITLE
pivpn - duplicate clients

### ISSUE THREAD

**Issue by angrymarker** [pivpn/pivpn#618]
# PiVPN Issue Template

I'm testing creating/revoking from a website. I've added a test account, then revoked it. I went to readd it, with success. When I run "pivpn -l", i see the revoked account and the new account. for clarity, is there a way to reuse the revoked account?

```

pivpn -l

: NOTE : The first entry should always be your valid server!

::: Certificate Status List :::
 ::  Status  ||   Name   :: 
     Valid   ::   server_OMMITTED
     Valid   ::   admin
     Valid   ::   JennJenntheEngine
     Valid   ::   AverageWrasler
     Revoked ::   test
     Valid   ::   test
```

## Have you searched for similar issues and solutions? 
I've referenced #185 and #233 , and saw that it can reuse the account, but I did not see anything about it being a duplicate on the list.

**Comment by orazioedoardo** [comment]
You just did, when you revoke a client you can create a new client with the same name as the revoked one.
