### ISSUE TITLE
IPv6 leaked

### ISSUE THREAD

**Issue by freetom** [pivpn/pivpn#619]
When connected with OpenVPN the IPv6 address of the client leaks (if any present on such interface)

Test: https://whatismyipaddress.com/

I had to disable IPv6. To disable it on all the interface on Debian 9 GNU/Linux type: 
`sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1`

**Comment by 4s3ti** [comment]
This is way to vague ... need more details ... Please open a new issue providing more details, 
such how you have things setup...How you are connecting ... how can we replicate this to identify the behavior? 

Anyway ... PiVPN still does not support IPv6 configurations: https://github.com/pivpn/pivpn/issues/259

If you still want to open an issue regarding this matter please provide more details.

**Comment by freetom** [comment]
I guess [259](https://github.com/pivpn/pivpn/issues/259) it's the problem.

Not configuring IPv6 implies that it "falls back" to the non VPN IPv6 address that can easily read by any website using e.g WebRTC APIs..

There's not much to say about the setup! `pivpn` is installed used to generate a client certificate with which I connect using `openvpn` (using Gnome VPN integration)

**Comment by 4s3ti** [comment]
seems a decent concern perhaps we should disable it until we support it.
