### ISSUE TITLE
generating profile fails

### ISSUE THREAD

**Issue by matthijsl** [pivpn/pivpn#62]
```
spawn ./build-key-pass client
Generating a 4096 bit RSA private key
............................................................................................................................++
................................++
writing new private key to 'client.key'
Enter PEM pass phrase:myphrase
spawn openssl rsa -in client.key -des3 -out client.3des.key
unable to load Private Key
1996052576:error:0906D06C:PEM routines:PEM_read_bio:no start line:pem_lib.c:696:Expecting: ANY PRIVATE KEY
expect: spawn id exp6 not open
    while executing
"expect "Enter PEM pass phrase" { send "theclientpassword\r" }"
Client's cert found: client.crt
[ERROR]: Client 3des Private Key not found: client.3des.key
root@raspberrypi:/etc/openvpn/easy-rsa/keys# myphrase
bash: myphrase: command not found

```

I'm running into this while trying to `pivpn add` a profile.

running `pivpn add [nopass]` works but has me ending up with tunnelblick complaining about an unaccepted passphrase

**Comment by MatthijsLiethof** [comment]
I've been getting very intermittent results, following trying only letters instead of alphanumeric passwords. And even then with short passwords I've needed to run the command with the same input over and over just to get 1 success.

**Comment by MatthijsLiethof** [comment]
I succeeded in getting a working profile with certificates included. I did this by breaking down the steps found in `makeOVPN.sh` what I found is that with the private keys generated through `pivpn -a` fail in the step where you create the des3 file https://github.com/pivpn/pivpn/blob/master/scripts/makeOVPN.sh#L82

Getting an error saying that it was expecting a private key file. 

When I ran `./build-key-pass` manually I was able to step through with an alphanumeric passphrase of significant length. Running these keys through the `openssl rsa -in $NAME$OKEY -des3 -out $NAME$KEY` command did not fail.

After that I used a makeshift script to create the profile.
```
#!/bin/bash
CLIENT_FILE="client.ovpn"
CLIENT_NAME="client"

touch $CLIENT_FILE
cat Default.txt >> $CLIENT_FILE

# Echo the needed certificates 
echo '<ca>' >> /etc/openvpn/easy-rsa/keys/$CLIENT_FILE
cat /etc/openvpn/easy-rsa/keys/ca.crt >> /etc/openvpn/easy-rsa/keys/$CLIENT_FILE
echo '</ca>' >> /etc/openvpn/easy-rsa/keys/$CLIENT_FILE

echo '<cert>' >> /etc/openvpn/easy-rsa/keys/$CLIENT_FILE
cat /etc/openvpn/easy-rsa/keys/$CLIENT_NAME.crt >> /etc/openvpn/easy-rsa/keys/$CLIENT_FILE
echo '</cert>' >> /etc/openvpn/easy-rsa/keys/$CLIENT_FILE

echo '<key>' >> /etc/openvpn/easy-rsa/keys/$CLIENT_FILE
cat /etc/openvpn/easy-rsa/keys/$CLIENT_NAME.key >> /etc/openvpn/easy-rsa/keys/$CLIENT_FILE
echo '</key>' >> /etc/openvpn/easy-rsa/keys/$CLIENT_FILE

#Finally, append the TA Private Key 
echo "<tls-auth>" >> $CLIENT_FILE 
cat ta.key >> $CLIENT_FILE
echo "</tls-auth>" >> $CLIENT_FILE
```

I'm guessing some of the steps changed in the creation of the private key with `pkitool` and thus leave you with some other strings to expect in your script?

**Comment by pdkillian** [comment]
I am having the same issue.  I can't create a client profile.

**Comment by jrotaetxe** [comment]
Same here...
If I leave PEM passwd blank, the process is able to finish. If I enter anything, the script fails.
Is there any workaround meanwhile?
Regards (and thanks for the whole project and tips)

**Comment by Foolson** [comment]
Same problem here too.

**Comment by sniffedagain** [comment]
Same error here as well. PEM passphrase. What is it exactly?

**Comment by derek-roam** [comment]
+1
