### ISSUE TITLE
Reconfiguration after write own Image on a other Raspberry

### ISSUE THREAD

**Issue by Apop85** [pivpn/pivpn#620]
Hello together

The problem I have at the moment is that I want to play my image of my raspberry on a raspberry of my friend. 

So what I want to change now is the dynamic DNS address for the connection as well as generating a new 2048bit server key with necdh-curve (>2.4 option). I haven't found the command or tutorial yet and would be happy to get a hint on how to do this. 

What I already found is the entry of the DynDNS address in ./easy-rsa/pki/Default.txt (entry: `remote myadress.myddns.net 1194`). My question in this regard is whether this is correct to edit this entry to generate new *.ovpn files correctly? 

To solve this problem I already have several googled like "[pivpn OR openvpn] edit dyndns adress" and the like. But in the end I read the installation script (install.pivpn.io) and at least came across Default.txt. 
I also see where the server key is created, but I can't read a direct command from it, though I lack the experience. 

The reason why I don't want to do a new installation is that PiHole and DNSCrypt are installed on this image and I don't like to edit all configs again to get it work. 

Since this is not a problem with the functionality of PiVPN itself, I think attaching logs and outputs is unnecessary. However, if you still want something I will gladly give it to you. 

Greetings Apop

**Comment by orazioedoardo** [comment]
You should regenerate the entire Public Key Infrastructure on your Pi to have it different from your friend. Instead, I would image the Pi as is, copy to your friends Pi, uninstall PiVPN (only PiVPN) and reinstall.
