### ISSUE TITLE
Question: 2 Raspberry Pis with PiVPN on a network possible?

### ISSUE THREAD

**Issue by hanshafner** [pivpn/pivpn#621]
Hi,

is it possible to have two different RPis running pivpn on the same network?

Is there anything special I should consider?

Thanks and kind regards
Hans

**Comment by orazioedoardo** [comment]
Nothing special, just choose different ports during the setup.

**Comment by hanshafner** [comment]
Yes, had different ports.

It didn't work yesterday on the second raspberry pi but it still worked fine on the first. The first one uses TCP.

I should have switched to TCP right away. I think my ISP is doing something with UDP.

Anyway. Tested today on a virtual machine and even there I can get a VPN to work... nice... but I will have to setup the second pi for it.

Thank you!
