### ISSUE TITLE
Cant install on Rp2

### ISSUE THREAD

**Issue by mkono87** [pivpn/pivpn#622]
Using a rp2 and when I enter the command all I get is that its a self assigned cert and to use -k.

 So I did that 
curl -L -k install.pivpn.io | bash
 
but then I get this  

bash: line 1: $'GIF89a\001\001\220\377!\371\004\005\020,\001\001\002\002\004\001': command not found

**Comment by orazioedoardo** [comment]
Update your system with: `sudo apt-get update && sudo apt-get upgrade && sudo reboot`
Then, manually run the script with:
```
wget 
https://raw.githubusercontent.com/pivpn/pivpn/master/auto_install/install.sh
chmod +x install.sh
./install.sh
```

**Comment by devZer0** [comment]
no feedback for months, please close
