### ISSUE TITLE
pivpn add fails, seems like install did not work correctly

### ISSUE THREAD

**Issue by cmot17** [pivpn/pivpn#627]
# PiVPN Issue Template

## Issue
I am trying to install PiVPN on a fresh install of [OctoPi](https://octoprint.org/download/).
Every time I run the installer, it seems to think it is finished right after the "Unattended upgrades" part of the installer. It then just shows "Installation complete" and asks if I want to restart.

The command `pivpn add` simply outputs
`-bash: pivpn: command not found`

## Have you searched for similar issues and solutions? 
    (yes/no / which issues?) 
  yes.

## Console output of `curl -L install.pivpn.io | bash`
```
 pi@octopi:~ $ curl -L https://install.pivpn.io | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   178  100   178    0     0    267      0 --:--:-- --:--:-- --:--:--   266
100 51064  100 51064    0     0  49466      0  0:00:01  0:00:01 --:--:-- 49466
:::
::: sudo will be used for the install.
::: Verifying free disk space...
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: Your system is up to date! Continuing with PiVPN installation...
::: Static IP already configured.
::: Using User: pi
:::
::: Checking for existing base files...
:::    Checking /etc/.pivpn is a repo...:::    Cloning https://github.com/pivpn/pivpn.git into /etc/.pivpn... done!
:::
::: Stopping OpenVPN service... done.
:::
::: Installing scripts to /opt/pivpn...cp: cannot stat '/etc/.pivpn/scripts/makeOVPN.sh': No such file or directory
::: Install Complete...
::: Restarting services...
Synchronizing state of openvpn.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable openvpn
::: done.
:::
::: Installation Complete!
::: Now run 'pivpn add' to create an ovpn profile for each of your devices.
::: Run 'pivpn help' to see what else you can do!
::: It is strongly recommended you reboot after installation.
:::
::: The install log is located at: /etc/pivpn/install.log
pi@octopi:~ $ pivpn add
-bash: pivpn: command not found
```

## Have you taken any steps towards solving your issue? 
     which? 
I have looked around a lot, I haven't managed to find any issues that look the same as mine. 
I did a fresh reinstall of OctoPi.
I also made sure to do `sudo apt-get update && sudo apt-get upgrade` and reboot before trying the installer.

The install log (from `/etc/pivpn/install.log`) looks like this:

```
:::
::: Stopping OpenVPN service... done.
 [/]  ^H^H^H^H^H^H [-]  ^H^H^H^H^H^H [\]  ^H^H^H^H^H^H [|]  ^H^H^H^H^H^H [/]  ^$
::: Installing scripts to /opt/pivpn...
```

**Comment by cmot17** [comment]
I fixed it, I will post an update explaining what I did soon.

**Comment by bcrhiaadn** [comment]
/etc/pivpn/install.log


:::
::: Stopping OpenVPN service... done.
 [/]  ^H^H^H^H^H^H [-]  ^H^H^H^H^H^H [\]  ^H^H^H^H^H^H [|]  ^H^H^H^H^H^H    ^H^H^H^H:::
::: Installing scripts to /opt/pivpn...


If you asked if I turned it off and back on again or if I tried sudo, I will throw a sandal at my neighbor's cat in slight angst. Also, tried the github repository multiple times multiple ways.

running 9.4 on Pi 3b. Linux octopi 4.14.71-v7+ #1145 SMP Fri Sep 21 15:38:35 BST 2018 armv7l GNU/Linux

already (apt get-update and apt-get upgrade)ed, to no success. 

Removed line 398 $SUDO cp /tmp/pivpnINT /etc/pivpn/pivpnINTERFACE from the install.sh already completed, deleted files, reinstalled, rebooted, deleted, reinstalled from github, rebooted, just iron-coated testiballs dragging across my keyboard. have currently readded this line so there's not too many variables if somebody gives me advice on my next step. Instead of using VNC Viewer to view the desktop (great for noobs like me) I have to manually delete the files with sudo rm -v pathhere. 

Changed my language to US English, UK English, Japanese all the newest frameworks utf-8, redeleted, rebooted, retried then the older frameworks. 

Have just given my pi this command > sudo dpkg --configure -a and now it craps out even quicker on the installation screen (right after it says auto security patches are better than toast). Now working on a fresh install of the OctoPi/Rasbian image.

**Comment by pointandyshoot** [comment]
haha, I have the same problem. I have to say 'fixed it, will tell you later' is more frustrating than just saying nothing. At least you seemed to fix it within 3 hours so it can't be *that* bad?

**Comment by bcrhiaadn** [comment]
Apparently it's the lite images that pivpn has trouble on....hmmmmmmmmm wack. I've tried multiple clean installs at this point and would like to make use of the newest .15 octopi software. I'm not giving up yet. So far, it feels like my permissions may be messed up, not creating a directory for the files to be copied into. I've edited the sudoers file more times than I count but installation remains just as poopy. I've pretty much got a list of things to do to get to my restarting point. Write Raspbian Stretch lite, boot, connect to the wifi, sudo apt-get update and upgrade, sudo apt-get install openvpn, then

::: Checking for existing base files...
:::    Checking /etc/.pivpn is a repo...:::    Cloning https://github.com/pivpn/pivpn.git into /etc/.pivpn... done!
:::
::: Stopping OpenVPN service... done.
:::
::: Installing scripts to /opt/pivpn...cp: cannot stat '/etc/.pivpn/scripts/makeOVPN.sh': No such file or directory
::: Install Complete...
::: Restarting services...
Synchronizing state of openvpn.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable openvpn
::: done.
:::
::: Installation Complete!
::: Now run 'pivpn add' to create an ovpn profile for each of your devices.
::: Run 'pivpn help' to see what else you can do!
::: It is strongly recommended you reboot after installation.
:::
::: The install log is located at: /etc/pivpn/install.log

and the install.log says the same mean things about me it was saying earlier :/

going to try booting octopi .14 and pivpn then updating when there's a patch. again, i has a raspi 3b (not plus) so i'm lucky enough to go back.

**Comment by bcrhiaadn** [comment]
oh to update erybody, i went ahead and removed the opt/pivpn and the etc/.pivpn directories and everything in them, then manually created the directory /etc/.pivpn/scripts/ and tried again but i just can't get that makeopvn.sh file to work right. will look into where the new location should be after dinner and ask around to see if somebody knows where to put the new file in. honestly, too much time has been wasted just to get an automated process twerk. it's easier to manually openvpn at this point lol. here's the link for any other noobs that might have this same issue:

https://munkjensen.net/wiki/index.php/Rapsberry_Pi_OpenVPN_Server

Just kidding it's a picture of an anus!

**Comment by bcrhiaadn** [comment]
and i'm back running octopi .14 (jessie-lite)

pi@octopi:~ $ sudo curl -L https://install.pivpn.io | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   178  100   178    0     0    280      0 --:--:-- --:--:-- --:--:--   280
100 51064  100 51064    0     0  57718      0 --:--:-- --:--:-- --:--:--  201k
:::
::: sudo will be used for the install.
::: Verifying free disk space...
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: Your system is up to date! Continuing with PiVPN installation...
::: Static IP already configured.
::: Using User: pi
:::
::: Checking for existing base files...
:::    Checking /etc/.pivpn is a repo...:::    Cloning https://github.com/pivpn/pivpn.git into /etc/.pivpn... done!
:::
::: Stopping OpenVPN service... done.
:::
::: Installing scripts to /opt/pivpn...cp: cannot stat ‘/etc/.pivpn/scripts/makeOVPN.sh’: No such file or directory
::: Install Complete...
::: Restarting services...
Synchronizing state for openvpn.service with sysvinit using update-rc.d...
Executing /usr/sbin/update-rc.d openvpn defaults
Executing /usr/sbin/update-rc.d openvpn enable
::: done.
:::
::: Installation Complete!
::: Now run 'pivpn add' to create an ovpn profile for each of your devices.
::: Run 'pivpn help' to see what else you can do!
::: It is strongly recommended you reboot after installation.
:::
::: The install log is located at: /etc/pivpn/install.log

anybody else have 2 cents to put in?
the install.log had to say:
:::
::: Stopping OpenVPN service... done.
 [/]  ^H^H^H^H^H^H [-]  ^H^H^H^H^H^H [\]  ^H^H^H^H^H^H [|]  ^H^H^H^H^H^H    ^H^H^H^H:::
::: Installing scripts to /opt/pivpn...

first time i had .15.1 octopi image, then tried .15.0, now .14.0. I'm a little ticked but now I know quite a bit of command. now if it could work I'd have learned my lesson. will update as required.

**Comment by bcrhiaadn** [comment]
took openvpn off the auto-startup list with 
sudo update-rc.d -f openvpn remove

**Comment by bcrhiaadn** [comment]
i forgot to mention i have edited the /etc/dhcpcd.conf file to set my pi's static address before every attempt to install. I feel like there's something missing that i'm just not getting. I'll get back to it in a few days

**Comment by bcrhiaadn** [comment]
what worked for me on both .14 and .15.1 is this solution from user @rahendri on thread #602. posted here:

> download gitrepo into /home/pi/.pivpn (im using a Pi, "Raspbian GNU/Linux 8 (jessie)") , then copy the contents into /etc/.pivpn/ and run the script again as root

from-a-fresh-0.15.1-image commands here:
`passwd`
`sudo raspi-config` (change wifi country, enable ssh (si te gusta), update)
`sudo apt-get upgrade`
`sudo apt-get install openvpn`
`git clone https://github.com/pivpn/pivpn.git /home/pi/.pivpn`
`sudo cp -av /home/pi/.pivpn/ /etc/.pivpn/`
`sudo curl -L https://install.pivpn.io | bash`
`sudo reboot`
`pivpn add`

and you're good to go. If this doesn't work you're probably a terrorist or you should stop watching so much hentai you freak, it's unhealthy. if it throws you no such directory codes the command to make a directory is 
'mkdir whateverdirectoryyouwanttomake'
then run the install again and you're guchi

**Comment by z1nfinity** [comment]
> > from-a-fresh-0.15.1-image commands here:
> passwd
> sudo raspi-config (change wifi country, enable ssh (si te gusta), update)
> sudo apt-get upgrade
> sudo apt-get install openvpn
> git clone https://github.com/pivpn/pivpn.git /home/pi/.pivpn
> sudo cp -av /home/pi/.pivpn/ /etc/.pivpn/
> sudo curl -L https://install.pivpn.io | bash
> sudo reboot
> pivpn add
> 
> and you're good to go. If this doesn't work you're probably a terrorist or you should stop watching so much hentai you freak, it's unhealthy. if it throws you no such directory codes the command to make a directory is
> 'mkdir whateverdirectoryyouwanttomake'
> then run the install again and you're guchi
> 
> 

I was able to create a user profile and resolve the issue of skipping steps, following these instructions. However, when connecting to OpenVPN using my pivpn profile, I get this:
Mon Oct 22 11:04:07 2018 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Mon Oct 22 11:04:07 2018 TLS Error: TLS handshake failed

Any help is appreciated, as I'm very new to everything Raspberry Pi, haha.

**Comment by bcrhiaadn** [comment]
That's a separate issue answered on separate threads. But to summarize what devices you need to configure for your VPN: Raspi, Router/any firewalls with local ports/external ports as well as local and public IP(probably 192.168.0.1), DNS/Host (no-ip.com), client keys imported to end device's VPN software. Your raspberry pi will generate keys with pivpn add and give you the location of where they are. Put these keys on the end device (for me, my phone). I'd recommend OpenVPN for Android because it's free and gives you a lot of options. To transfer files from your pi to your phone, use a File Transfer Protocol program. Easiest way.

**Comment by Silventar** [comment]
Noting worked unto I did su
