### ISSUE TITLE
Fail to connect from outside network working before 

### ISSUE THREAD

**Issue by soydepr** [pivpn/pivpn#628]
As of this week not able to reach vpn  from outside network even though 
My network is open  please help
![dbec1859-19a1-4d35-9dbd-93e6cac69c31](https://user-images.githubusercontent.com/546367/46918655-6a4ec980-cfa2-11e8-8686-b7713d4f22fa.png)

**Comment by arkid** [comment]
Check out the last comments at the bottom of this post, if it was working before its very likely due to your certificate expiring.  https://github.com/pivpn/pivpn/issues/567
