### ISSUE TITLE
Read-only filesystem? Protection from SD card corruption

### ISSUE THREAD

**Issue by tomasmcm** [pivpn/pivpn#63]
First of all, let me congratulate you on the amazing piece of software you have here, it couldn't been easier to set this up 👏

My question is regarding the fact that sometimes we turn off the raspberry by killing the power (hard shutdown) and that can cause some corruption issues in the future...

I've seen a lot of tutorials on how to make the file-system read-only, here are a few:
- https://hallard.me/raspberry-pi-read-only/
- https://k3a.me/how-to-make-raspberrypi-truly-read-only-reliable-and-trouble-free/
- http://petr.io/2015/11/09/read-only-raspberry-pi-with-jessie/

Would this work with piVPN? or does it need access to writable filesystem?

**Comment by 0-kaladin** [comment]
Hmm, i know it writes log files but once running, for it to function I don't think it writes anything. I think really would have to try it and see what happens.

**Comment by redfast00** [comment]
@tomasmcm: That really isn't a good idea: `unattended-upgrades` won't work if your filesystem is mounted read-only. This will leave you with old and potentially vulnerable  packages. This is especially dangerous on a public-facing server, like your Pi.
