### ISSUE TITLE
Pivpn doesn't work with 2018-10-09-raspbian-stretch

### ISSUE THREAD

**Issue by thewriteway** [pivpn/pivpn#630]
Situation:  Fresh image load, fresh pivpn, no errors logged. 
Problem: Can't connect to any resource through the vpn internally or externally. 
Issue Analysis: Only change is new Raspbian system OS load.
Remediation: Going to load older Raspbian and see if the same occurs.

**Comment by thewriteway** [comment]
still completely broken, i'm abanding it for now. to be continued...

**Comment by Dinnerspy** [comment]
Mine works with the latest raspian.  What error is your client giving? Can you connect on wifi that is not on the same network as your server? Can you connect over LTE?

**Comment by thewriteway** [comment]
client connects fine, cant access the internet or local VPN resources from mobile or pc whilst connecting to the openvpn tunnel.

**Comment by orazioedoardo** [comment]
What client are you using? iOS/Android app?

**Comment by thewriteway** [comment]
iOS and windows 10 standard openvpn clients

**Comment by orazioedoardo** [comment]
First of all, on iOS, go to OpenVPN connect, than settings and set Compression to "Full". Now attempt a connection, test whether it works, then post the raspberry pi log: `cat /var/log/openvpn.log`

**Comment by Trotter73** [comment]
Hi,
You can grab previous images of Raspbian here, if that helps you. [http://downloads.raspberrypi.org/raspbian/images/](url)

The Pi running my VPN has just had an apt-update and it is running without any issues, not much help I know.....

If you dont use IPV6 try adding this  `ipv6.disable=1` to the end of cmdline.txt I had connectivity and apt issues, this fixed it.

**Comment by Charles-IV** [comment]
I am also getting this, but I also got this when setting up OpenVPN manually.

I just tried with ipv6 disabled, and it still doesn't work.

Here's the [gist](https://gist.github.com/Charles-IV/ad6527b4dfddbabda3f700e1d295bac8) of me connecting from an android, compression was set to full by default.

One thing to note is I did modify the /etc/openvpn/server.conf and the client.ovpn files at some settings I chose in the setup of pivpn weren't reflected (like the protocol), but thats a different problem, and it shouldn't have an affect here, as connecting seems fine, I've just got no internet.

**Comment by thewriteway** [comment]
@Charles-IV you should strip out any public facing IPs from that log.

**Comment by jalanjarosz** [comment]
> First of all, on iOS, go to OpenVPN connect, then settings and set Compression to "Full". Now attempt a connection, test whether it works, then post the raspberry pi log: `cat /var/log/openvpn.log`

I've been having similar issues, PiVPN is up, Windows 10 clients connect but iOS 11.4.1 does not.  After setting compression to "Full" in iOS, I can get to all my LAN resources.

Here is a snippet from my openvpn.log:
Oct 23 07:31:48 pivpn ovpn-server[21783]: <client>/<ip:port> Data Channel Encrypt: Cipher 'AES-256-GCM' initialized with 256 bit key
Oct 23 07:31:48 pivpn ovpn-server[21783]: <client>/<ip:port> Data Channel Decrypt: Cipher 'AES-256-GCM' initialized with 256 bit key
Oct 23 07:32:43 pivpn ovpn-server[21783]: <router/DNS LAN ip> TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Oct 23 07:32:43 pivpn ovpn-server[21783]: <router/DNS LAN ip> TLS Error: TLS handshake failed
Oct 23 07:32:43 pivpn ovpn-server[21783]: <router/DNS LAN ip> SIGUSR1[soft,tls-error] received, client-instance restarting
Oct 23 07:33:10 pivpn ovpn-server[21783]: <client>/<ip:port> SIGTERM[soft,remote-exit] received, client-instance exiting

**Comment by Charles-IV** [comment]
setting the dns in server.conf to `push "dhcp-option DNS 10.8.0.1"` seemed to work for me, then it stopped working, then i disconnected and reconnected and it's working again.

Now however the connection seems very bad, and I'm not sure if the only reason webpages are loading is because they are loading when the vpn is disconnected and trying to reconnect

**Comment by pattagobi** [comment]
by any chance if are behind NAT it wont work, whatever you do.

**Comment by thewriteway** [comment]
full reinstall, all working now with compression disabled.
