### ISSUE TITLE
[REQUEST] Arch Linux Arm support?

### ISSUE THREAD

**Issue by lavanoid** [pivpn/pivpn#631]
I was wondering if support for Arch Linux can be added? ( https://archlinuxarm.org/platforms/armv6/raspberry-pi )

**Comment by 4s3ti** [comment]
I use Arch Linux myself, and this is a thing I wanted pivpn to have as well however I lack the time to code all needed to support arch Linux. 

There is already a feature request for this. 

https://github.com/pivpn/pivpn/issues/190


if you have the knowledge, feel free to make a pull request will be more than happy to review, test and approve it if all is ok! 

Closing as this is a duplicate.
