### ISSUE TITLE
RFC: moving to a different organisation

### ISSUE THREAD

**Issue by redfast00** [pivpn/pivpn#633]
Hi, this is a request for comments about moving to a different GitHub organization.

The main reason to do this would be because @0-kaladin, the owner of both the pivpn.io domainname and the pivpn organisation on GitHub doesn't seem to be active anymore. Since there is no active owner, some settings (like HTTPS on pivpn.io) can't be changed. In addition to that, it's also impossible to add new members to the organisation, which makes it difficult for the existing members to keep up with everything. I myself haven't really looked at PiVPN in a long time, and I've seen that the issues and PR's have piled up.

So what would change? First of all, we'd have more people who are member, and pick some trusted members to also be an owner of the organisation.

What are the advantages/drawbacks?

Advantages:

- We have full control over the repo and repo settings. This will result in quicker merging of pull requests and enabling trusted users to edit and close issues.

Disadvantages:
- We will have to move over existing issues
- There will be no repo in the new organisation connected to the pivpn.io domain name.
- The new repo won't have the stars the current one does, so will be less visible.

Of course, I alone can't go through with this: what do you think? Do you have any alternatives or suggestions?

**Comment by orazioedoardo** [comment]
I agree with @Giraffe1966. If there is no way to have @0-kaladin change ownership, a new repo should be the easiest way to keep on with the project. pivpn/pivpn could just be a placeholder with a minimal README to redirect people to the new repo.

@Giraffe1966 If @redfast00 can't change https://install.pivpn.io to point to the new script, we could change current install.sh to download it. Basically an additional indirection level.

**Comment by Giraffe1966** [comment]
@orazioedoardo Yes, that is what I was thinking.

**Comment by redfast00** [comment]
@orazioedoardo @Giraffe1966 I tried to contact @0-kaladin, both via his personal email and via GitHub support, but they don't seem to reply to any of that.

**Comment by orazioedoardo** [comment]
A new domain is required to enable https on the whole website, right? So the server will be the same but with an additional domain pointing to it? I think this assumes that @redfast00 can edit the website itself.

**Comment by Giraffe1966** [comment]
@orazioedoardo The server/repo with the new website will be different (allowing for https and a different organization), _and_ the domain will be different. The current website's repo could be updated to have a link to the new one or a JavaScript redirect. The website would use GitHub Pages.

**Comment by orazioedoardo** [comment]
It would make a clear distinction between the “old” project and the new one, that’s what you thought? (Instead of messing the old website I mean).

**Comment by redfast00** [comment]
I can edit the website itself (see https://github.com/pivpn/pivpn.github.io), but I don't have access to the actual domainname.

**Comment by Giraffe1966** [comment]
https://github.com/pivpn/pivpn.github.io wouldn't be part of the new organization, though. That's why we need a new website, if we want a website owned by the new organization.

**Comment by orazioedoardo** [comment]
So what's your plan @redfast00?

**Comment by redfast00** [comment]
@orazioedoardo it's on my "todo in case I ever have spare time" list. Since we have a lot of work for uni right now, I don't know if I'll be able to put in work any time soon.

**Comment by jeremy21212121** [comment]
There are a few suitable domains available: pivpn.org, for example.

Someone could acquire the domain name. We'd need to come up with a way of securely transferring the account, preferably in a way that multiple people can access it in a pinch. I don't know how that would work in a way that would prevent this happening again. Any ideas?

Alternatively, you could just drop the custom domain name and use pivpn.github.io. You should be able to disable the 301 redirect from the github account. Is the custom domain name critical?

**Comment by james-lasersoft** [comment]
I would be more than happy to acquire the pivpn.org domain and make it available to the group. If part of the site need be hosted I can provide that as well.

Sorry that I won't be much help in the maintenance of the repo as I am still learning this but I consume this product quite a lot and do not want to see this die.

Just give me an affirmative and I will get this rolling immediately.

**Comment by Giraffe1966** [comment]
@james-lasersoft @jeremy21212121 FYI, pivpn.org was registered 2 days ago. https://whois.icann.org/en/lookup?name=pivpn.org

**Comment by james-lasersoft** [comment]
@Giraffe1966 Actually that was me. I also picked up pivpn.info if we want to add a redirect.

**Comment by Giraffe1966** [comment]
@james-lasersoft Okay, thanks. Thought it might be you.

**Comment by redfast00** [comment]
@james-lasersoft @Giraffe1966 @orazioedoardo see the README
