### ISSUE TITLE
Connect to VPN but no internet / local network

### ISSUE THREAD

**Issue by pointandyshoot** [pivpn/pivpn#634]
I'm adding this as a record of how I solved my problem.

This was on a Raspberry Pi 3, with Raspbian Stretch. The install script was able to complete.

I was able to connect to the VPN from the internet. The connection completes (thinks it's connected) however I was unable to ping anything on local network or connect to internet websites etc.

I tried the suggested iptables commands that you will find everyone else seemed to have success with but nothing was working.

I left my VPN connected computer trying to ping google.com while I was playing with settings.
I noticed in /var/log/openvpn.log the following:

```
Oct 23 15:56:11 pi3 ovpn-server[314]: xps13/49.181.xx.xx:42468 Bad LZ4 decompression header byte: 69
Oct 23 15:56:12 pi3 ovpn-server[314]: xps13/49.181.xx.xx:42468 Bad LZ4 decompression header byte: 69
Oct 23 15:56:13 pi3 ovpn-server[314]: xps13/49.181.xx.xx:42468 Bad LZ4 decompression header byte: 69

```

I fixed the issue by removing the `compress lz4` line from the the following locations and rebooting:
/etc/openvpn/server.conf
and every .ovpn file I generated for devices (the ones made using `pivpn add`)

Everything now works as expected when I connect via VPN. I'm pretty sure all the iptable stuff I did was reset by `pivpn debug`

Anyway, hope this helps people with a similar problem get their VPN working.

**Comment by hughker** [comment]
Thanks @pointandyshoot this did the trick for me. I tried the suggestion from #54 and that didn't solve it but this did. 👍

**Comment by the-other-martin** [comment]
@pointandyshoot:
I'm using similar to you Raspi 3 B+ with Raspbian Stretch Lite 4.14 and PiVPN OpenVPN Server 2.4.0 - connected via LAN (Wifi off) - the PiVPN Script completed.

I am able to connect to the VPN from Internet with OpenVPN Connect 3.0.2 iOS App on IPhone 6s, also able to ping all machines on the LAN where the Raspi resides - but can **_only_** access the Raspi with the OVPN Server itself (e.g. SSH).

All other machines I **_cannot_** reach with e.g. Safari/http(s) or telnet (but works when connected directly to the respective local LAN - via Wifi).

Wondering what exactly you changed in the config file - I didn't find a "compress lz4" entry (?)
Could you please advise?

**Comment by pointandyshoot** [comment]
I had a line saying `compress lz4` near the bottom of `/etc/openvpn/server.conf`
I also had `compress lz4` in each `.ovpn` file

If you want to see if your problem is the same as mine try connecting via vpn and use that computer to keep pinging something (anything, google.com for example) the pings will keep failing. While doing that check the `/var/log/openvpn.log` to see if you get the compression error I noted in the first post. If you're not seeing that your problem may be something else (try the iptables fix in #110 ).

**Comment by the-other-martin** [comment]
hmmm - my server.conf doesn't have a "compress" entry - any idea what else could be the root cause of the problem?

**Raspi**: 3B+ with Raspbian Stretch Lite 4.14
**VPN**: OpenVPN Server 2.4.0
**LAN**: 192.168.1.0/24
**OpenVPN**: 192.168.1.120 (fix ip-address)
**Gateway (ddwrt router)**: 192.168.1.2

`/etc/openvpn/server.conf`:
--------------------------------------------------------------
dev tun
proto udp
port 11940
ca /etc/openvpn/easy-rsa/pki/ca.crt
cert /etc/openvpn/easy-rsa/pki/issued/server_xWc3YJnyGnE6CONk.crt
key /etc/openvpn/easy-rsa/pki/private/server_xWc3YJnyGnE6CONk.key
dh none
topology subnet
server 10.8.0.0 255.255.255.0
# Set your primary domain name server address for clients
push "dhcp-option DNS 192.168.1.2"
push "block-outside-dns"
# Override the Client default gateway by using 0.0.0.0/1 and
# 128.0.0.0/1 rather than 0.0.0.0/0. This has the benefit of
# overriding but not wiping out the original default gateway.
push "redirect-gateway def1"
client-to-client
keepalive 1800 3600
remote-cert-tls client
tls-version-min 1.2
tls-crypt /etc/openvpn/easy-rsa/pki/ta.key
cipher AES-256-CBC
auth SHA256
user nobody
group nogroup
persist-key
persist-tun
crl-verify /etc/openvpn/crl.pem
status /var/log/openvpn-status.log 20
status-version 3
syslog
verb 3
#DuplicateCNs allow access control on a less-granular, per user basis.
#Remove # if you will manage access by user instead of device.
#duplicate-cn
# Generated for use by PiVPN.io` 
--------------------------------------------------------------

**Comment by orazioedoardo** [comment]
@the-other-martin What network are you connecting your iPhone 6S from? Also go to the openvpn connect settings, then confirm that compression is Off. Try to connect to the vpn, then post the output (within a code block) of `/var/log/openvpn.log` omitting your iphone IP.

**Comment by the-other-martin** [comment]
Connecting via LTE from iPhone 6S
Compressin in OpenVPN Connect: **Allow Compression (insecure):** No

```
Oct 29 12:43:19 raspberrypi3b ovpn-server[336]: 213.225.12.48:33583 TLS: Initial packet from [AF_INET]213.225.12.48:33583, sid=2a5a2882 0d4a851f
Oct 29 12:43:19 raspberrypi3b ovpn-server[336]: 213.225.12.48:33583 VERIFY OK: depth=1, CN=ChangeMe
Oct 29 12:43:19 raspberrypi3b ovpn-server[336]: 213.225.12.48:33583 Validating certificate key usage
Oct 29 12:43:19 raspberrypi3b ovpn-server[336]: 213.225.12.48:33583 ++ Certificate has key usage  0080, expects 0080
Oct 29 12:43:19 raspberrypi3b ovpn-server[336]: 213.225.12.48:33583 VERIFY KU OK
Oct 29 12:43:19 raspberrypi3b ovpn-server[336]: 213.225.12.48:33583 Validating certificate extended key usage
Oct 29 12:43:19 raspberrypi3b ovpn-server[336]: 213.225.12.48:33583 ++ Certificate has EKU (str) TLS Web Client Authentication, expects TLS Web Client Authentication
Oct 29 12:43:19 raspberrypi3b ovpn-server[336]: 213.225.12.48:33583 VERIFY EKU OK
Oct 29 12:43:19 raspberrypi3b ovpn-server[336]: 213.225.12.48:33583 VERIFY OK: depth=0, CN=user
Oct 29 12:43:19 raspberrypi3b ovpn-server[336]: 213.225.12.48:33583 peer info: IV_GUI_VER=net.openvpn.connect.ios_3.0.2-894
Oct 29 12:43:19 raspberrypi3b ovpn-server[336]: 213.225.12.48:33583 peer info: IV_VER=3.2
Oct 29 12:43:19 raspberrypi3b ovpn-server[336]: 213.225.12.48:33583 peer info: IV_PLAT=ios
Oct 29 12:43:19 raspberrypi3b ovpn-server[336]: 213.225.12.48:33583 peer info: IV_NCP=2
Oct 29 12:43:19 raspberrypi3b ovpn-server[336]: 213.225.12.48:33583 peer info: IV_TCPNL=1
Oct 29 12:43:19 raspberrypi3b ovpn-server[336]: 213.225.12.48:33583 peer info: IV_PROTO=2
Oct 29 12:43:19 raspberrypi3b ovpn-server[336]: 213.225.12.48:33583 peer info: IV_AUTO_SESS=1
Oct 29 12:43:19 raspberrypi3b ovpn-server[336]: 213.225.12.48:33583 Control Channel: TLSv1.2, cipher TLSv1/SSLv3 ECDHE-ECDSA-AES256-GCM-SHA384
Oct 29 12:43:19 raspberrypi3b ovpn-server[336]: 213.225.12.48:33583 [user] Peer Connection Initiated with [AF_INET]213.225.12.48:33583
Oct 29 12:43:19 raspberrypi3b ovpn-server[336]: user/213.225.12.48:33583 MULTI_sva: pool returned IPv4=10.8.0.2, IPv6=(Not enabled)
Oct 29 12:43:19 raspberrypi3b ovpn-server[336]: user/213.225.12.48:33583 MULTI: Learn: 10.8.0.2 -> user/213.225.12.48:33583
Oct 29 12:43:19 raspberrypi3b ovpn-server[336]: user/213.225.12.48:33583 MULTI: primary virtual IP for user/213.225.12.48:33583: 10.8.0.2
Oct 29 12:43:19 raspberrypi3b ovpn-server[336]: user/213.225.12.48:33583 PUSH: Received control message: 'PUSH_REQUEST'
Oct 29 12:43:19 raspberrypi3b ovpn-server[336]: user/213.225.12.48:33583 SENT CONTROL [user]: 'PUSH_REPLY,dhcp-option DNS 192.168.1.2,block-outside-dns,redirect-gateway def1,route-gateway 10.8.0.1,topology subnet,ping 1800,ping-restart 3600,ifconfig 10.8.0.2 255.255.255.0,peer-id 0,cipher AES-256-GCM' (status=1)
Oct 29 12:43:19 raspberrypi3b ovpn-server[336]: user/213.225.12.48:33583 Data Channel Encrypt: Cipher 'AES-256-GCM' initialized with 256 bit key
Oct 29 12:43:19 raspberrypi3b ovpn-server[336]: user/213.225.12.48:33583 Data Channel Decrypt: Cipher 'AES-256-GCM' initialized with 256 bit key
```

**Comment by orazioedoardo** [comment]
I don’t see any error with the log. Now let’s check iptables with `sudo iptables -vnL` and `sudo iptables -vnL -t nat` (post the output).

Clarify what’s working and what is not (while on VPN):
1) Can you connect to the ddwrt administrator page?
2) Can you go to google.com?
3) On your raspberry pi run `nslookup google.com` to get the google IP, then paste it into Safari anche check if it loads.

**Comment by the-other-martin** [comment]
`sudo iptables -vnL`:

```
Chain INPUT (policy ACCEPT 6580 packets, 9148K bytes)
 pkts bytes target     prot opt in     out     source               destination 

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination 

Chain OUTPUT (policy ACCEPT 3923 packets, 225K bytes)
 pkts bytes target     prot opt in     out     source               destination 
```
`sudo iptables -vnL -t nat`

```
Chain PREROUTING (policy ACCEPT 67 packets, 8673 bytes)
 pkts bytes target     prot opt in     out     source               destination 

Chain INPUT (policy ACCEPT 54 packets, 7849 bytes)
 pkts bytes target     prot opt in     out     source               destination 

Chain OUTPUT (policy ACCEPT 13 packets, 1058 bytes)
 pkts bytes target     prot opt in     out     source               destination 

Chain POSTROUTING (policy ACCEPT 13 packets, 1058 bytes)
 pkts bytes target     prot opt in     out     source               destination 
   13   824 MASQUERADE  all  --  *      eth0    10.8.0.0/24          0.0.0.0/0 
``` 
answering your questions from iPhone 6s/Safari view (connected via OpenVPN Connect App):
1.  no
2. no
3. doesn't load with [https://172.217.22.14](url)
`nslookup google.com`:

```
Server:         192.168.1.2
Address:        192.168.1.2#53

Non-authoritative answer:
Name:   google.com
Address: 172.217.22.14
```

**Comment by orazioedoardo** [comment]
Try #54. Remember to restart the server with `sudo systemctl restart openvpn`

**Comment by the-other-martin** [comment]
I have added
```
tun-mtu 1400 
mssfix 1360
```
to `/etc/openvpn/server.conf` with `sudo nano /etc/openvpn/server.conf`
and restarted the server with `sudo systemctl restart openvpn`

... and: it **works** now for my setup!
Many thanks @orazioedoardo !

**Comment by javiochoa** [comment]
I run `pivpn -d` command and got that exists two issues. After fix them everything works propertly.
