### ISSUE TITLE
Website flagged as not secure in Google Chrome

### ISSUE THREAD

**Issue by jbroderick** [pivpn/pivpn#636]
An invalid certificate

**Comment by orazioedoardo** [comment]
Read #633

**Comment by mikkelrask** [comment]
Well, if you're talking about the pivpn.io website, why would it _need_ to be secure? You're not inputting any data, it's seriously just free for all information. 

I know it's pretty easy to get a SSL certificate these days (thank god), but this cannot be an issue for strictly text based websites.

**Comment by 4s3ti** [comment]
closing as duplicate... here is the main thread about it: https://github.com/pivpn/pivpn/issues/236
