### ISSUE TITLE
Fault in resolv.conf when uninstalling

### ISSUE THREAD

**Issue by rallegade** [pivpn/pivpn#64]
Everytime the script has been uninstalled from the raspberry i end up with a raspberry unable to connect to sites where a DNS is needed (like pinging google.com) but not when pinging IP's.

This was due to the resolver.conf found in /etc/ pointing at the router as nameserver.
easy fix is to add nameservers like google ( 8.8.8.8, 8.8.4.4)

**Comment by 0-kaladin** [comment]
I duped this.  we seem to always set local dns to the gateway.  this works in many home's but is not universal.  should do something about it...

**Comment by redfast00** [comment]
Can't we save the old file to say, `/etc/resolv.conf.old`, and then rename on uninstall?

**Comment by 0-kaladin** [comment]
this actually happens cause we edit the dhcpd.conf file.  that file will update resolv.conf with the dns.  There are a couple things that need investigating...
1. we should only touch the dhcpcd conf file when the user wants US to set the static IP.  In that case we don't want to revert the whole file on uninstall as they probably want to keep the static IP they set.  
2. when i duped this, I did not have the installer set my static, yet on uninstall my gateway is used for dns and this isn't what I wanted. (i wanted it to go to my pi-hole which is a different IP).

The real answer might be to grab what a user has set for DNS on the pi and just put that back on uninstall.  i have to think through all the scenario's more I think.

**Comment by 0-kaladin** [comment]
This should be resolved now.
