### ISSUE TITLE
ExpressVpn on top - double hop connection

### ISSUE THREAD

**Issue by ZenZendra** [pivpn/pivpn#641]
Hello,
I want to use PiVpn with PiHole and connect outside of my network with my phone so i have acces to my hard drive and don't have ads :)
But i would also like that PiVpn connects to my Expressvpn paid account, so i can browse anonymously, with all those things i mentioned.
Does anybody knows how to set this up?
I found one tutorial, but it doesn't work for me.
Thanks

**Comment by Escaonor** [comment]
Take a look at this: https://github.com/mr-canoehead/vpn_client_gateway

Or you can use this guide: https://www.comparitech.com/blog/vpn-privacy/raspberry-pi-vpn/

Good luck :)

**Comment by 4s3ti** [comment]
Not related with PiVPN, 
Not the kind of setup we support, 
not on our plans to setup such configurations. 

If you want to discuss this please take it over to pivpn subreddit at: [r/pivpn](https://www.reddit.com/r/pivpn/)

Kind Regards.
