### ISSUE TITLE
Is there a way to disguise the VPN?

### ISSUE THREAD

**Issue by Sandman224** [pivpn/pivpn#644]
Hey. I recently created a pivpn and it works great on all networks but my school network that has a firewall with Deep Packet Inspection. I am able to connect vpns from the Google play store but not from openvpn. Is there a way to bypass this? I already have my VPN setup to Port 443 with tcp so that it will be hard to block but with DPI on the school network it still is able to be detected. Any solution would be appreciated!

**Comment by d0nlab** [comment]
tls-crypt enabled?

**Comment by mobotus** [comment]
obfs4proxy

**Comment by Giraffe1966** [comment]
@Sandman224 Stunnel (https://stunnel.org) should work.
