### ISSUE TITLE
Error: main: line 120: /tmp/DET_PLATFORM: Permission denied

### ISSUE THREAD

**Issue by cKarlGo** [pivpn/pivpn#647]
# PiVPN Issue Template

Error being received: main: line 120: /tmp/DET_PLATFORM: Permission denied

## Issue
I haven't been able to install pivpn as either pi or root. When running as pi, I get the output shown below. When running as root, I get a flash of a dialog and then nothing. System updated this morning prior to install attempt.

Nothing in any of the logs that appears to be related to this issue.

Version/config info:

WiFi disabled. Static IP address assigned. Network and Internet access appears to be normal.

Linux pi01 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l GNU/Linux

cat /etc/os-release 
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

## Have you searched for similar issues and solutions? 
    (yes/no / which issues?) 

Yes. I've found nothing that seems to be on point with this particular error.  

## Console output of `curl -L install.pivpn.io | bash`
```
  curl -L https://install.pivpn.io | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   178  100   178    0     0    464      0 --:--:-- --:--:-- --:--:--   465
100 53084  100 53084    0     0  98200      0 --:--:-- --:--:-- --:--:-- 98200
:::
::: sudo will be used for the install.
main: line 120: /tmp/DET_PLATFORM: Permission denied

```

## Console output of `pivpn add` or `pivpn add nopass`
```
  Output Here
```

## Console output of `pivpn debug`
```
  Output Here
```

## Console Output of `sudo iptables -t nat -S`
```
iptables -t nat -S
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT

```

## Console Output of `sudo iptables -S`
```
iptables -S
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT

```

## output of `sudo netstat -uanp | grep openvpn`

```
  Output Here
```

## Have you taken any steps towards solving your issue? 
     which?

**Comment by orazioedoardo** [comment]
Never seen this issue. Post the ouput of `ls -ld /tmp` and check if `echo hello > /tmp/world` works as pi user and root user (i.e. you get no output and `ls -l /tmp/world` shows the file).

Can you do [this](https://github.com/pivpn/pivpn/issues/521#issuecomment-420957752) so we can try to figure out the underlying problem?

**Comment by cKarlGo** [comment]
Oddly, the script ran when I saved it locally. I'm going to set up a DDNS account and rerun it with all the proper configs before I test.

=======

root@pi01:/var/log# ls -ld /tmp
drwxrwxrwt 11 root root 4096 Dec 10 18:17 /tmp
=======
root@pi01:/var/log# echo hello > /tmp/world
root@pi01:/var/log# cat /tmp/world 
hello
=======
