### ISSUE TITLE
Add more feature

### ISSUE THREAD

**Issue by redstarksten** [pivpn/pivpn#648]
Hi, any tutorial how to add more feature like limit client expire date? Sometimes I need to give trial vpn for 1 day.

**Comment by orazioedoardo** [comment]
Should be easy to do it using easyrsa's EASYRSA_CERT_EXPIRE variable. Don't know if this is could be merged but I might try to add the code if i find some spare time.

**Comment by felixjmm** [comment]
hi all

do you know it is possible to:
1. set a user expire date? ie certificate valid for 6 months?

2. set a connection time limit? ie: close the vpn connection after 2 hours?

3. suspend temporarily a user instead of doing a full revoque?

thanks

**Comment by 4s3ti** [comment]
feature added and pushed into master branch: https://github.com/pivpn/pivpn/pull/740/commits/e26cef18630515823825019be1dbda586a4b8f30
