### ISSUE TITLE
No prompt for DNS Entry

### ISSUE THREAD

**Issue by RexYuan** [pivpn/pivpn#65]
Hi! I'm following [this guide](https://www.sitepoint.com/setting-up-a-home-vpn-using-your-raspberry-pi/) to install pivpn, but, on the step of choosing between a public IP or a public DNS, after selecting public DNS, I was not prompt for input for my public DNS.

I'm using a raspberry pi 3 I just bought yesterday with Raspbian installed using NOOBS.

**Comment by krisskos** [comment]
Same here!When I pressed ENTER it doesn't let me input my DNS just continues forward.Navigation and selection in prompt msg  is messed up or I'm missing something.

**Comment by 0-kaladin** [comment]
You need to hit space bar to actually select the option.  just highlighting with arrow key movement doesn't do it.
