### ISSUE TITLE
Wiki Contribution - Do not route traffic through VPN

### ISSUE THREAD

**Issue by Pontiac76** [pivpn/pivpn#657]
https://github.com/pivpn/pivpn/wiki/FAQ#allow-clients-to-connect-but-block-their-access-to-the-internet

I can't find how to edit the page, but, I'd like to add a note to this.

Under the "Allow Clients to connect but block their access to the internet" section, please add:

**If you remove the above PUSH command, you'll need to add a route PUSH command to get access to your LAN.
Add the PUSH command:

push "192.168.2.0 255.255.255.0"

Ensure that the IP and netmask match what the VPN side of the network is.**

**Comment by 4s3ti** [comment]
Nice Catch, Done! 

https://github.com/pivpn/pivpn/wiki/FAQ#allow-clients-to-connect-but-block-their-access-to-the-internet

Thank you for your contribution!
