### ISSUE TITLE
IOS 12 rdp and local lan issue. Works only with Android and Windows

### ISSUE THREAD

**Issue by SalientComputers** [pivpn/pivpn#658]
## Issue
I am able to connect to the internet, and RDP into computers behind the vpn with android Oreo and a windows computer only.

IOS 12.1.1 only gives me only internet access through the vpn. It does not allow me to RDP or even ping anything on the LAN behind the vpn.  I have devices with interfaces on port 80 with local addresses (192.*.*.*) that i can not see either.  It is as if the traffic is not being routed to the local Lan but only for apple devices. 

I have searched and searched for issues but I only encounter results for the latest compression issue that was resolved. Maybe this is a lingering issue from that??

## Have you taken any steps towards solving your issue? 
 I have uninstalled and re-installed pivpn with minimal options and only creating one test user. 
I have had the exact same result. Android and windows connect to Lan computers and Internet just fine. IOS devices (iphone 6,8,10, ipad) ONLY connect to internet through the vpn (public ip matches the remote location).

## Console output of `pivpn debug`
```
:::					:::
::		PiVPN Debug		 ::
:::					:::
::	Latest Commit			 ::
:::					:::
commit 95f78aa861761bfe9faa6e34e4b7965266e48ef3
Merge: 375faa6 0b4464b
Author: redfast00 <redfast00@users.noreply.github.com>
Date:   Sat Oct 20 16:13:34 2018 +0100

    Merge pull request #632 from pivpn/test
    
    Merge test branch
:::					:::
::	Recursive list of files in	 ::
::	/etc/openvpn/easy-rsa/pki	 ::
:::					:::
/etc/openvpn/easy-rsa/pki/:
ca.crt
crl.pem
Default.txt
ecparams
index.txt
index.txt.attr
index.txt.attr.old
index.txt.old
issued
private
serial
serial.old
ta.key
Test.ovpn

/etc/openvpn/easy-rsa/pki/ecparams:
prime256v1.pem

/etc/openvpn/easy-rsa/pki/issued:
server_j5L1FoyG2kP2c8ZC.crt
Test.crt

/etc/openvpn/easy-rsa/pki/private:
ca.key
server_j5L1FoyG2kP2c8ZC.key
Test.key
:::					:::
::	Output of /etc/pivpn/*		 ::
:::					:::
:: START /etc/pivpn/DET_PLATFORM ::
Ubuntu
:: END /etc/pivpn/DET_PLATFORM ::
:: START /etc/pivpn/INSTALL_PORT ::
1194
:: END /etc/pivpn/INSTALL_PORT ::
:: START /etc/pivpn/INSTALL_PROTO ::
udp
:: END /etc/pivpn/INSTALL_PROTO ::
:: START /etc/pivpn/INSTALL_USER ::
salientvpn
:: END /etc/pivpn/INSTALL_USER ::
:: START /etc/pivpn/NO_UFW ::
1
:: END /etc/pivpn/NO_UFW ::
:: START /etc/pivpn/pivpnINTERFACE ::

:: END /etc/pivpn/pivpnINTERFACE ::
:: START /etc/pivpn/setupVars.conf ::
pivpnUser=testing
UNATTUPG=unattended-upgrades
pivpnInterface=
IPv4dns=
IPv4addr=192.168.1.10
IPv4gw=192.168.1.1
pivpnProto=udp
PORT=1194
ENCRYPT=256
APPLY_TWO_POINT_FOUR=true
DOWNLOAD_DH_PARAM=false
PUBLICDNS=spcc.testing.com
OVPNDNS1=209.244.0.3
OVPNDNS2=209.244.0.4
:: END /etc/pivpn/setupVars.conf ::
:: START /etc/pivpn/TWO_POINT_FOUR ::
:: END /etc/pivpn/TWO_POINT_FOUR ::
:::					:::
:: /etc/openvpn/easy-rsa/pki/Default.txt ::
:::					:::
client
dev tun
proto udp
remote spcc.testing.com 1194
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
tls-version-min 1.2
verify-x509-name server_j5L1FoyG2kP2c8ZC name
cipher AES-256-CBC
auth SHA256
auth-nocache
verb 3
:::					:::
::	Debug Output Complete		 ::
:::					:::

```

## Console Output of `sudo iptables -t nat -S`
```
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT
-A POSTROUTING -s 10.8.0.0/24 -o enp0s3 -j MASQUERADE

```

## Console Output of `sudo iptables -S`
```
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT

```

## output of `sudo netstat -uanp | grep openvpn`

```
udp        0      0 0.0.0.0:1194            0.0.0.0:*                           1121/openvpn

```

**Comment by SalientComputers** [comment]
Configuration works on every device except iOS.

**Comment by devZer0** [comment]
what openvpn client do you use on iphone?

**Comment by Giraffe1966** [comment]
@SalientComputers This looks like a client problem, not a pivpn/server problem. Could you please attach a log from the client?

**Comment by SalientComputers** [comment]
I use the openvpn client on iOS. The issue ended up being that my local wifi lan and the remote VPN lan are using the same address scope and iOS was not routing to the VPN. I had to have the iOS device connect to the cell network and everything started working perfectly.

**Comment by devZer0** [comment]
so, this problem has nothing to do with ipvpn. can be closed, as it's resolved.

**Comment by SalientComputers** [comment]
I am using pivpn and the openvpn client on ios and android. Android has no issues connecting to remote desktop on the remote network regardless of my local networks scope.  iOS does not route to the remote network if it is using the same scope as the local one.  This seems to me not to be a trivial issue. I was able to find a work around but not a solution.

**Comment by Giraffe1966** [comment]
But this is a problem with the OpenVPN client for iOS, not pivpn. We want to help, but we can't fix the iOS OpenVPN client.
