### ISSUE TITLE
Unsuccessfully tried to modify server.ovpn to use ifconfig-pool and ifconfig-pool-persist to assign remote ip addresses

### ISSUE THREAD

**Issue by yogiberra** [pivpn/pivpn#661]
The standard server pivpn configuration file works.  I wanted to be revised the configuration file to define a specific set of IP addresses to be assigned to the client.

I made changes to the following to lines:
server 
ifconfig-pool-persist 192.168.103.40 192.168.103.60 255.255.255.0

I also tried 
ifconfig-pool 192.168.103.40 192.168.103.60 255.255.255.0

which replaced
server 192.168.104.0  255.255.255.0

OpenVPN did not start up and had the following log
**OpenVPN.log**

_Dec 31 10:33:53 EBJPi6 ovpn-server[274]: Options error: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/server.conf:9: server (2.4.0)
Dec 31 10:33:53 EBJPi6 ovpn-server[274]: Use --help for more information._

server.ovpn  (MODIFIED)
dev tun
proto udp
port 1194
ca /etc/openvpn/easy-rsa/pki/ca.crt
cert /etc/openvpn/easy-rsa/pki/issued/server_VUtZIxxbdDMV4q9J.crt
key /etc/openvpn/easy-rsa/pki/private/server_VUtZIxxbdDMV4q9J.key
dh /etc/openvpn/easy-rsa/pki/dh2048.pem
topology subnet
server 
ifconfig-pool-persist 192.168.103.40 192.108.103.60 255.255.255.0
# Set your primary domain name server address for clients
push "dhcp-option DNS 192.168.103.1"
push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 8.8.4.4"
# Prevent DNS leaks on Windows
push "block-outside-dns"
# Override the Client default gateway by using 0.0.0.0/1 and
# 128.0.0.0/1 rather than 0.0.0.0/0. This has the benefit of

# overriding but not wiping out the original default gateway.
push "redirect-gateway def1"
client-to-client
keepalive 1800 3600
remote-cert-tls client
tls-version-min 1.2
tls-auth /etc/openvpn/easy-rsa/pki/ta.key 0
cipher AES-256-CBC
auth SHA256
user nobody
group nogroup
persist-key
persist-tun
crl-verify /etc/openvpn/crl.pem
status /var/log/openvpn-status.log 20
status-version 3
syslog
verb 3
#DuplicateCNs allow access control on a less-granular, per user basis.
#Remove # if you will manage access by user instead of device. 
#duplicate-cn
# Generated for use by PiVPN.io

## Have you searched for similar issues and solutions? Yes - nothing relevant was found
    (yes/no / which issues?) 
  

## Console output of `curl -L install.pivpn.io | bash`
```
  Output Here
```

## Console output of `pivpn add` or `pivpn add nopass`
```
  Output Here
```

**Comment by 4s3ti** [comment]
we are moving all non-pivpn related issues over to pivpn subrredit at [r/pivpn](https://www.reddit.com/r/pivpn/)

if you still want some help, please reopen this there. 
and please be more clear with what you are really trying to accomplish. 

Kind Regards.
