### ISSUE TITLE
How to forward ports to client?

### ISSUE THREAD

**Issue by pronsta** [pivpn/pivpn#666]
Hi,

I am able to connect to PiVPN everything works good even with Pi-Hole as DNS. Now how can forward ports to the client? 

thanks

**Comment by pronsta** [comment]
this is my plan

![1](https://user-images.githubusercontent.com/25282119/51083995-0503a380-175e-11e9-8453-ecf129e70932.PNG)

**Comment by pronsta** [comment]
I managed to ping from PiVPN to the PFSense router but I cannot ping the PiVPN from the PFSense. 😞

**Comment by 4s3ti** [comment]
I am not really sure if i understood what you really want to accomplish and not even sure if it is really possible, however this is not entirely code related therefore this discussion should be taken to our subreddit  at [r/pivpn](https://www.reddit.com/r/pivpn/)

thanks a lot for your interest in PiVPN! 
If anyone within the community knows how to help you you will certainly get it! 

Kind regards
