### ISSUE TITLE
pivpn return code

### ISSUE THREAD

**Issue by Amaelh** [pivpn/pivpn#669]
When executing pivpn command, most cases end with return code 1. This is inconsistent with conventions : 0 = OK, 1 = Error.
In my case this blocks proper automation of pivpn docker container creation. My Makefile runs the following command to validate the installation : 
```
docker-compose exec rpi-pivpn /usr/local/bin/pivpn -l
```

As return code is 1, make command fails with error (return code <> 0) :
````
: NOTE : The first entry should always be your valid server!

::: Certificate Status List :::
 ::  Status  ||   Name   ::
     Valid   ::   server_kKVj19oJviuCCvvD

Makefile:34 : la recette pour la cible « test » a échouée
make: *** [test] Erreur 1
````

I will submit a patch for this, and also share my running docker pivpn image for raspberry pi zero when I'll have finished :)

**Comment by 4s3ti** [comment]
There is already one similar project, might be worth taking a look at it: https://github.com/InnovativeInventor/docker-pivpn

Will mark this as enhancement so we can take a look at the exiting error codes. 
Thanks for your interest.

**Comment by embolon** [comment]
Any update on this thread? Always exit with 1 fails all python subprocess calls to pivpn.

**Comment by 4s3ti** [comment]
that has already been changed in test branch: 
https://github.com/pivpn/pivpn/commit/9f20f50e6168d4d24d40e938cbb9b48c2f4ee383

**Comment by 4s3ti** [comment]
this has been merged today into Master branch. 
Closing
