### ISSUE TITLE
Transferring ovpn file

### ISSUE THREAD

**Issue by keeshman556** [pivpn/pivpn#67]
So I have tried a million different ways to move the ovpn file from the pi to my computer with winscp and cyberduck. I keep getting a permissions error and when I try to change the permissions in cyberduck it won't let me do that either. I'm a real noob so it is hard for me to understand any of the resources online. any help would be greatly appreciated.

**Comment by keeshman556** [comment]
you have to run sudo chmod 777 /etc/openvpn/easy-rsa/keys

**Comment by keeshman556** [comment]
thanks self

**Comment by peterHendrickx** [comment]
Hi, the script will place all ovpn files in the ovpns directory in your home directory. There is no need to go to the keys directory.

**Comment by sven250** [comment]
You can also connect to the pi via SFTP with Filezilla. From there it's just copying the .ovpn file from /home/pi/ovpns to your computer. SFTP is a file transfer protocol that runs over the SSH port 22, thus there's no need for extra software (except for Filezilla).

**Comment by guydeke** [comment]
I use the sftp with Filezilla or Viper FTP Lite on my MacBook. No extra software needed.

**Comment by guydeke** [comment]
You can also put your cert in the Public folder of your dropbox.
Then go to the directory where the cert is needed on your pi and use the following command:
wget --no-check-certificate" with a link to the file

e.g: wget --no-check-certificate https://dl.dropboxusercontent.com/u/certificate.ovpn

**Comment by timvy** [comment]
If you cannot transfer the file through scp or other tools: simply ssh into the pi (which you already did because you installed the whole thing),  cat the contents (cat /home/pi/ovpns/name.ovpn ) , copy that text from your terminal window and past in a new textfile with the same name. voila.
