### ISSUE TITLE
Problem with client asus router firmware merlin

### ISSUE THREAD

**Issue by Chemyto** [pivpn/pivpn#672]
Problem to connect pivpn with asus router firmware Merlin, I create user with option no pass but dont connect. With windows client work well

Log asus router:

Jan 24 19:48:03 ovpn-client1[4160]: OpenVPN 2.4.6 arm-unknown-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Jul 25 2018
Jan 24 19:48:03 ovpn-client1[4160]: library versions: OpenSSL 1.0.2o  27 Mar 2018, LZO 2.08
Jan 24 19:48:03 ovpn-client1[4161]: NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Jan 24 19:48:03 ovpn-client1[4161]: neither stdin nor stderr are a tty device and you have neither a controlling tty nor systemd - can't ask for 'Enter Private Key Password:'.  If you used --daemon, you need to use --askpass to make passphrase-protected keys work, and you can not use --auth-nocache.

**Comment by Chemyto** [comment]
Solved: 
Create file in router /etc/user.pass with user pass
Add in config vpn client: 
askpass /etc/user.pass

**Comment by PickledNewt** [comment]
@Chemyto 

Hi - please can you expand on your solution a little more? I have exactly the same issue (installed PiVPN on my Pi, Asus router client won't connect) - would love to get it working. No-one else seems to have been able.

Thank you very much!!!

**Comment by Chemyto** [comment]
Activate ssh in asus router, create file user.pass with password client.
Edit config vpn client in your asus router, in custom configuration, add askpass /path user.pass in your router.

**Comment by drmoseley** [comment]
RT-N66U, recently loaded with Merlin 380.70_0, would not connect with OpenVPN 2.4.0-6 running on Raspbian (Stretch - v9) until using workaround described here. Set 'Username/Password Authentication' to 'No' and updated 'Custom Configuration' as suggested.

![Custom Configuration](https://user-images.githubusercontent.com/49561833/57592982-10de5700-74ff-11e9-874d-62a20933e274.jpg)

Problem solved - thanks!

**Comment by gnome1919** [comment]
Thanks for the guide. But I notice that every time that I restarted the router, the user created file (such as /etc/user.pass) would be deleted. What should I do to prevent this?
@Chemyto  @drmoseley
