### ISSUE TITLE
unable to complete PIVPN install - no client DNS option

### ISSUE THREAD

**Issue by vekzla** [pivpn/pivpn#673]
# PiVPN Issue Template

## Issue
I have completed the installation of PIVPN on the latest Stretch OS, the installation is painless and easy however i have the following issues below. Please not i have 0 skills with this, I have been following examples, tutorials and how to etc.
thanks in advance

1) the final screen detailing CLIENT DNS does not show up (installation finishes at setting up my DNS name as I have dynamic IP)
2) the installation finishes and asks to run pivpn add for my clients certificates however it fails as easy-ra is not installed (missing file)
"can't open/etc/openvpn/easy-ras/pki/index.txt/attr for reading, no such file or directory
3) finally there is no pivpn folder in my root folders (i have checked this with filezilla and i have the following only (note below is a full Rasbian OS, i have just finished stretch lite and i have the same issue as per below, Pihole works though)
![image](https://user-images.githubusercontent.com/47047226/51782307-535f6c00-217a-11e9-82f8-ff571871d3ff.png)

## Have you searched for similar issues and solutions? 
    yes
  

## Console output of `curl -L install.pivpn.io | bash`
```
  pi@raspberrypi:~ $ sudo curl -L https://install.pivpn.io | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   178  100   178    0     0    145      0  0:00:01  0:00:01 --:--:--   146
100 53084  100 53084    0     0  31635      0  0:00:01  0:00:01 --:--:--  167k
:::
::: sudo will be used for the install.
::: Verifying free disk space...
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: Your system is up to date! Continuing with PiVPN installation...

```

## Console output of `pivpn add` or `pivpn add nopass`
```
spawn ./easyrsa build-client-full sdphone

Note: using Easy-RSA configuration from: ./vars
Generating a RSA private key
..................+++++
.............................................+++++
writing new private key to '/etc/openvpn/easy-rsa/pki/private/sdphone.key.82wJ40KLlg'
Enter PEM pass phrase:
Verifying - Enter PEM pass phrase:
-----
Using configuration from /etc/openvpn/easy-rsa/openssl-easyrsa.cnf
Check that the request matches the signature
Signature ok
The Subject's Distinguished Name is as follows
commonName            :ASN.1 12:'sdphone'
Certificate is to be certified until Jan 23 03:45:30 2029 GMT (3650 days)

Write out database with 1 new entries
Data Base Updated
Client's cert found: sdphone.crt
Client's Private Key found: sdphone.key
CA public Key found: ca.crt
tls-auth Private Key found: ta.key
cp: cannot create regular file '/home/pi/ovpns/sdphone.ovpn': No such file or directory
chown: cannot access '/home/pi/ovpns/sdphone.ovpn': No such file or directory


========================================================
Done! sdphone.ovpn successfully created!
sdphone.ovpn was copied to:
  /home/pi/ovpns
for easy transfer. Please use this profile only on one
device and create additional profiles for other devices.
========================================================


```

## Console output of `pivpn debug`
```
pi@raspberrypi:~ $ pivpn debug
::: Generating Debug Output
:::                                     :::
::              PiVPN Debug              ::
:::                                     :::
::      Latest Commit                    ::
:::                                     :::
commit 95f78aa861761bfe9faa6e34e4b7965266e48ef3
Merge: 375faa6 0b4464b
Author: redfast00 <redfast00@users.noreply.github.com>
Date:   Sat Oct 20 16:13:34 2018 +0100

    Merge pull request #632 from pivpn/test

    Merge test branch
:::                                     :::
::      Recursive list of files in       ::
::      /etc/openvpn/easy-rsa/pki        ::
:::                                     :::
/etc/openvpn/easy-rsa/pki/:
ca.crt
crl.pem
Default.txt
dh2048.pem
index.txt
index.txt.attr
index.txt.attr.old
index.txt.old
issued
private
sdphone.ovpn
serial
serial.old
ta.key

/etc/openvpn/easy-rsa/pki/issued:
sdphone.crt
server_as9c6cv2b4RcXi4N.crt

/etc/openvpn/easy-rsa/pki/private:
ca.key
sdphone.key
server_as9c6cv2b4RcXi4N.key
:::                                     :::
::      Output of /etc/pivpn/*           ::
:::                                     :::
:: START /etc/pivpn/DET_PLATFORM ::
Raspbian
:: END /etc/pivpn/DET_PLATFORM ::
:: START /etc/pivpn/INSTALL_PORT ::
(removed by author)
:: END /etc/pivpn/INSTALL_PORT ::
:: START /etc/pivpn/INSTALL_PROTO ::
udp
:: END /etc/pivpn/INSTALL_PROTO ::
:: START /etc/pivpn/INSTALL_USER ::
pi
:: END /etc/pivpn/INSTALL_USER ::
:: START /etc/pivpn/NO_UFW ::
1
:: END /etc/pivpn/NO_UFW ::
:: START /etc/pivpn/pivpnINTERFACE ::
eth0
:: END /etc/pivpn/pivpnINTERFACE ::
:::                                     :::
:: /etc/openvpn/easy-rsa/pki/Default.txt ::
:::                                     :::
client
dev tun
proto udp
remote IPv4pub (removed by author)
resolv-retry infinite
nobind
persist-key
persist-tun
key-direction 1
remote-cert-tls server
tls-version-min 1.2
verify-x509-name SRVRNAME name
cipher AES-256-CBC
auth SHA256
auth-nocache
verb 3
:::                                     :::
::      Debug Output Complete            ::
:::                                     :::
:::
::: Debug output completed above.
::: Copy saved to /tmp/debug.txt
:::


```

## Console Output of `sudo iptables -t nat -S`
```
 -P PREROUTING ACCEPT
-P INPUT ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT
-A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE


```

## Console Output of `sudo iptables -S`
```
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT


```

## output of `sudo netstat -uanp | grep openvpn`

```
 udp        0      0 0.0.0.0:(removed by author)           0.0.0.0:*                           336/openvpn

```

## Have you taken any steps towards solving your issue? 
  I have run the installation multiple times with new images, even tried different sd cards with no luck.
Thanks guys, hopefully i am not doing something stupid

**Comment by vekzla** [comment]
> * Manually download the script:
>   `wget https://raw.githubusercontent.com/pivpn/pivpn/master/auto_install/install.sh`
>   `chmod +x install.sh`
> * Open the script:
>   `nano install.sh`
> * Move to the line after `set -e` and add two more lines, one with `set -v` and one with `set -x`. Press CTRL-O, Enter, CTRL-X to exit.
> * Run the script:
>   `sudo ./install.sh`
> 
> If it still doesn’t succeed, post the output (omit the IP address or domain name if you want).

thank you, will keep you posted. The above steps were executed as per your steps and I am currently generating DH parameters.

**Comment by vekzla** [comment]
> * Manually download the script:
>   `wget https://raw.githubusercontent.com/pivpn/pivpn/master/auto_install/install.sh`
>   `chmod +x install.sh`
> * Open the script:
>   `nano install.sh`
> * Move to the line after `set -e` and add two more lines, one with `set -v` and one with `set -x`. Press CTRL-O, Enter, CTRL-X to exit.
> * Run the script:
>   `sudo ./install.sh`
> 
> If it still doesn’t succeed, post the output (omit the IP address or domain name if you want).

:( no luck with the script install, same issue. after i put in my dns server duckdns.org. the install skips the client server dns setup. as per the below 
![image](https://user-images.githubusercontent.com/47047226/51784285-5ec28f80-219a-11e9-8f43-e2d9079e26b2.png)

**Comment by orazioedoardo** [comment]
Actually the terminal output would be more useful, if it’s too long post it as an attachment.

**Comment by vekzla** [comment]
> Actually the terminal output would be more useful, if it’s too long post it as an attachment
are you referring to pivpn debug?
::: Generating Debug Output
:::                                     :::
::              PiVPN Debug              ::
:::                                     :::
::      Latest Commit                    ::
:::                                     :::
commit 95f78aa861761bfe9faa6e34e4b7965266e48ef3
Merge: 375faa6 0b4464b
Author: redfast00 <redfast00@users.noreply.github.com>
Date:   Sat Oct 20 16:13:34 2018 +0100

    Merge pull request #632 from pivpn/test

    Merge test branch
:::                                     :::
::      Recursive list of files in       ::
::      /etc/openvpn/easy-rsa/pki        ::
:::                                     :::
/etc/openvpn/easy-rsa/pki/:
ca.crt
crl.pem
Default.txt
dh2048.pem
index.txt
index.txt.attr
index.txt.old
issued
private
serial
serial.old
ta.key

/etc/openvpn/easy-rsa/pki/issued:
server_(removed by author).crt

/etc/openvpn/easy-rsa/pki/private:
ca.key
server_(removed by author)).key
:::                                     :::
::      Output of /etc/pivpn/*           ::
:::                                     :::
:: START /etc/pivpn/DET_PLATFORM ::
Raspbian
:: END /etc/pivpn/DET_PLATFORM ::
:: START /etc/pivpn/INSTALL_PORT ::
(removed by author)
:: END /etc/pivpn/INSTALL_PORT ::
:: START /etc/pivpn/INSTALL_PROTO ::
udp
:: END /etc/pivpn/INSTALL_PROTO ::
:: START /etc/pivpn/INSTALL_USER ::
pi
:: END /etc/pivpn/INSTALL_USER ::
:: START /etc/pivpn/NO_UFW ::
1
:: END /etc/pivpn/NO_UFW ::
:: START /etc/pivpn/pivpnINTERFACE ::
eth0
:: END /etc/pivpn/pivpnINTERFACE ::
:: START /etc/pivpn/TWO_POINT_FOUR ::
:: END /etc/pivpn/TWO_POINT_FOUR ::
:::                                     :::
:: /etc/openvpn/easy-rsa/pki/Default.txt ::
:::                                     :::
client
dev tun
proto udp
remote IPv4pub (removed by athor)
resolv-retry infinite
nobind
persist-key
persist-tun
key-direction 1
remote-cert-tls server
tls-version-min 1.2
verify-x509-name SRVRNAME name
cipher AES-256-CBC
auth SHA256
auth-nocache
verb 3
:::                                     :::
::      Debug Output Complete            ::
:::                                     :::
:::
::: Debug output completed above.
::: Copy saved to /tmp/debug.txt

**Comment by orazioedoardo** [comment]
Actually not the debug output. Basically the edit I asked you to make tell the script to output to the screen every variable and command being executed so we can see what went wrong. It should look like this: 
https://github.com/pivpn/pivpn/issues/617#issuecomment-428689127

If you haven’t closed the terminal, just scroll up to the point when you run ./install.sh and copy everything past that.

**Comment by vekzla** [comment]
> Actually not the debug output. Basically the edit I asked you to make tell the script to output to the screen every variable and command being executed so we can see what went wrong. It should look like this:
> [#617 (comment)](https://github.com/pivpn/pivpn/issues/617#issuecomment-428689127)
> 
> If you haven’t closed the terminal, just scroll up to the point when you run ./install.sh and copy everything past that.

and if one would have closed it :( sorry

**Comment by orazioedoardo** [comment]
No problem, just reopen a terminal and do `sudo ./install.sh`

**Comment by vekzla** [comment]
> No problem, just reopen a terminal and do `sudo ./install.sh`
sorry took some time to compile, please see attached. thanks 
[pivpnIssue.docx](https://github.com/pivpn/pivpn/files/2798783/pivpnIssue.docx)

**Comment by orazioedoardo** [comment]
So here it is:
`+ sed -i s/IPv4pub/http://(removed by author).duckdns.org/ /etc/openvpn/easy-rsa/pki/Default.txt
sed: -e expression #1, char 17: unknown option to `s'`

When you are asked to input the DDNS do not put http://yourdomain.duckdns.org, just put yourdomain.duckdns.org.

**Comment by vekzla** [comment]
> So here it is:
> `+ sed -i s/IPv4pub/http://(removed by author).duckdns.org/ /etc/openvpn/easy-rsa/pki/Default.txt sed: -e expression #1, char 17: unknown option to `s'`
> 
> When you are asked to input the DDNS do not put http://yourdomain.duckdns.org, just put yourdomain.duckdns.org.

thank you for your help, just show something so stupid can create a problem.
thanks bud

**Comment by orazioedoardo** [comment]
Nice, close the issue if we are done.
