### ISSUE TITLE
Moving Forward

### ISSUE THREAD

**Issue by kjwill555** [pivpn/pivpn#675]
I got a Raspberry Pi a couple days ago with the intent of using it to improve the security and usability of my home network. After setting up Pi-hole, I wanted to configure my Pi to be a VPN server as well so that I could enjoy the benefits of Pi-hole from outside my home network. Finding PiVPN via Google was a rollercoaster of emotions because I was excited to find a project that fit my needs exactly, only to later find out that @redfast00 very recently stepped down as maintainer.

I'm wondering what the plans are, if any, for next steps. I would like to help in some way, I'm just not sure how. I'm not a BASH expert, nor am I security expert, but I strongly believe in making security more accessible to people.

Anyone interested in teaming up and carrying on this project?

**Comment by orazioedoardo** [comment]
I was thinking about a [WireGuard](https://www.wireguard.com/) version of the script: “pi-guard” or something like that. It can be done now however it will need manual compilation since it’s not yet in the Linux kernel.



Here’s the main discussion by the way: https://github.com/pivpn/pivpn/issues/633

**Comment by Giraffe1966** [comment]
I am thinking of writing a new OpenVPN installer program if anybody is interested (using Java or Python since they are easier to code in than bash). WireGuard sounds awesome, but it is still a WIP and shouldn't be relied on.

**Comment by Trotter73** [comment]
I hear what you are saying about WireGuard, I have several spare Pis so was going to try it more out of curiosity than anything.

If you get to writing a script I an more than happy to test, I have a ok understanding of things server side..

**Comment by adrianQwest** [comment]
Hi, 
Given that pivpn is a script to install and configure openvpn I think we should just continue it as is. 
I have suggested a modification previously, which I have used myself but didn't finally submit (it randomised the sub net). I think it's relatively easy to learn bash, sufficient at least for pivpn. For what it's worth IP tables were the tricky but and that was routing rather than bash!
Happy to help as time permits.
Adrian

**Comment by Giraffe1966** [comment]
@adrianQwest Yeah, bash isn't too hard, but it is definitely more difficult to maintain and debug. However bash is found on a lot of systems, so it is good for compatibility. I was just thinking redoing the script in another language (like pi-hole is trying to do) might get rid of some bugs, be easier to test, and easier to maintain.

**Comment by adrianQwest** [comment]
I’ve just been looking through the script. Perhaps pigpen became to complicated by adding support for too many systems. If it were stripped back to the basics, OpenVPN on a pi running raspbian then it would be easier to maintain.
I’ve had it running for about two years now on two pis (TCP and UDP) without any problems. 
That said, I'd be happy to help in Python.

**Comment by orazioedoardo** [comment]
One problem with the script is that instead of handling error, it uses `set -e`, which makes functions [exit](https://ss64.com/bash/set.html) while continuing the rest of the script. This makes the users think that they installed the VPN and also prevents him from seeing the actual error.

Apart from that pivpn is not going to be outdated soon, as OpenVPN developer prefer compatibility over features (they have not added TLS 1.3 support yet). Sure @adrianQwest, it could be stripped down to be raspberry pi only and maybe also improve the debug section (for example with a snippet of the log and better formatting of the serfer/client settings).

**Comment by adrianQwest** [comment]
And I have it on a third pi at my parents' at the other end of the country. So once up and running it's very reliable.

**Comment by james-lasersoft** [comment]
As I have previously stated, I don't want this to die. I have secured pivpn.org and am willing to get a different domain if a different name is to be chosen. There are many improvements that can be made to this as it stands. Allowing for a different subnet would be nice for this of us that use multiple installs. I also use the pivpn gui from OpenRSD to maintain the certs. This shouls be included in any installation. I personally have only had problems with iptables for installs. Who wants to help with this maintenance and what names do you suggest?

**Comment by adrianQwest** [comment]
Hi,
I’m happy to lend a hand. I agree entirely. I’ve had my VPN’s running for two or more years Without issue.
I suspect the tricky bit now is the name. Off the top of my head, vpn2pi? As it has vpn and pi in it and the number can be incremented as needed.

**Comment by TariqMK** [comment]
I too came across this announcement today that PiVPN was no longer being maintained, quite sad to see. 

Although I am happy to see other members of the community looking to pick it up under a new name.  

May I suggest '**VPiN**'?

**Comment by Rohmilchkaese** [comment]
You‘ve got my full support for WireGuard. I myself have a WireGuard VPN with Pihole as DNS. 10 People are using it without any issues.

**Comment by 0-kaladin** [comment]
I like this thread.  I too don't want this to die and on my list for a while was to redo with python so it could be a simple pip install.  If someone wants to work on that i'm happy to assign owner here so you can just branch here for consistency.  I can also make it so the master of pivpn.io git will actually publish to the web page so you guys can update that with news etc as you see fit.

**Comment by james-lasersoft** [comment]
@0-kaladin - if you would like to set that up and assign me as owner I will do my best to take it forward. Personally I would appreciate not changing the name at all. So much easier. Also I prefer bash having more practice there.

**Comment by orazioedoardo** [comment]
I can help with a branch for a WireGuard version (written in bash). I have already adapted part of the code from pivpn, only for the latest Raspbian though.

**Comment by TariqMK** [comment]
A WireGuard version of PiVPN would be incredible. Could see it being very popular!

**Comment by adrianQwest** [comment]
Wire guard is not yet mature therefore not yet ready. We need to stick with a stable solution.

**Comment by orazioedoardo** [comment]
Well, you can test WireGuard with this script: [pi-guard](https://github.com/orazioedoardo/pi-guard). Uses most of the code from PiVPN, works for me on a clean install of Raspbian Stretch.

**Comment by adrianQwest** [comment]
No thanks.
WireGuard themselves say:
“WireGuard is not yet complete. You should not rely on this code. It has not undergone proper degrees of security auditing and the protocol is still subject to change. We're working toward a stable 1.0 release, but that time has not yet come.“
I’l wait out for now.

**Comment by james-lasersoft** [comment]
@0-kaladin Thanks for the assignment. I will try to help keep things up here and work on some updates and additions. I will still be doing this in bash.

**Comment by orazioedoardo** [comment]
> @0-kaladin Thanks for the assignment. I will try to help keep things up here and work on some updates and additions. I will still be doing this in bash.

Nice, does this mean that I can submit new pull requests again?

**Comment by james-lasersoft** [comment]
@orazioedoardo Yes, please do.

**Comment by devZer0** [comment]
i would also be happy to contribute , for example helping with issues etc
