### ISSUE TITLE
PiVPN - able to connect, but no LAN or internet, except Pi IP

### ISSUE THREAD

**Issue by holda29** [pivpn/pivpn#676]
Hi,
I have a problem with my setup on OrangePi Zero + with lovely DietPi. I have PiVPN server and few other services, like Pihole. But I have a problem with VPN. I am able to connect without any problems, but there is no internet or LAN on connected devices. Only address, that is accessible or pingable is IP of DietPi itself (192.168.29.4). It doesnt look like DNS problem, because I cant ping ips as well.
On a DietPi, I can ping anywhere i want to, also DNS resolution works fine.
I changed DNS to 8.8.8.8 to eliminate possible problems with Pihole. I am suspecting it has something to do with routing and iptables, but  I am not skilled in unix enough to troubleshoot it on myself.

Before I had Armbian installed, with PiVPN installed with script and everything worked out of the box, even with Pihole.
Bellow are some configurations, I can post more, if you tell which. 
Thanks a million!

## Console output of `pivpn debug`
```
dietpi@DietPi:~$ pivpn -d
::: Generating Debug Output
:::                                     :::
::              PiVPN Debug              ::
:::                                     :::
::      Latest Commit                    ::
:::                                     :::
commit 84cd315a522d99717cc4f103c5870b8d014bf846
Author: redfast00 <redfast00@gmail.com>
Date:   Tue Jan 29 11:16:48 2019 +0100

    So long and thanks for all the fish
:::                                     :::
::      Recursive list of files in       ::
::      /etc/openvpn/easy-rsa/pki        ::
:::                                     :::
/etc/openvpn/easy-rsa/pki/:
ca.crt
crl.pem
Default.txt
ecparams
Holdaxy.ovpn
index.txt
index.txt.attr
index.txt.attr.old
index.txt.old
issued
private
serial
serial.old
ta.key

/etc/openvpn/easy-rsa/pki/ecparams:
prime256v1.pem

/etc/openvpn/easy-rsa/pki/issued:
Holdaxy.crt
server_znyzUOYI8NRpbnxG.crt

/etc/openvpn/easy-rsa/pki/private:
ca.key
Holdaxy.key
server_znyzUOYI8NRpbnxG.key
:::                                     :::
::      Output of /etc/pivpn/*           ::
:::                                     :::
:: START /etc/pivpn/DET_PLATFORM ::
Debian
:: END /etc/pivpn/DET_PLATFORM ::
:: START /etc/pivpn/INSTALL_PORT ::
1194
:: END /etc/pivpn/INSTALL_PORT ::
:: START /etc/pivpn/INSTALL_PROTO ::
udp
:: END /etc/pivpn/INSTALL_PROTO ::
:: START /etc/pivpn/INSTALL_USER ::
dietpi
:: END /etc/pivpn/INSTALL_USER ::
:: START /etc/pivpn/NO_UFW ::
1
:: END /etc/pivpn/NO_UFW ::
:: START /etc/pivpn/pivpnINTERFACE ::
eth0
:: END /etc/pivpn/pivpnINTERFACE ::
:: START /etc/pivpn/setupVars.conf ::
pivpnUser=dietpi
UNATTUPG=unattended-upgrades
pivpnInterface=eth0
IPv4dns=
IPv4addr=192.168.29.4
IPv4gw=192.168.29.3
pivpnProto=udp
PORT=1194
ENCRYPT=256
APPLY_TWO_POINT_FOUR=true
DOWNLOAD_DH_PARAM=false
PUBLICDNS=
OVPNDNS1=8.8.8.8
OVPNDNS2=
:: END /etc/pivpn/setupVars.conf ::
:: START /etc/pivpn/setupVars.conf.save ::
pivpnUser=dietpi
UNATTUPG=unattended-upgrades
pivpnInterface=eth0
IPv4dns=
IPv4addr=192.168.29.4
IPv4gw=192.168.29.3
pivpnProto=udp
PORT=1194
ENCRYPT=256
APPLY_TWO_P.OINT_FOUR=true
DOWNLOAD_D.H_PARAM=false
PUBLICDNS.=
OVPNDNS1=
OVPNDNS2=
:: END /etc/pivpn/setupVars.conf.save ::
:: START /etc/pivpn/TWO_POINT_FOUR ::
:: END /etc/pivpn/TWO_POINT_FOUR ::
:::                                     :::
:: /etc/openvpn/easy-rsa/pki/Default.txt ::
:::                                     :::
client
dev tun
proto udp
remote x.x.x.x 1194
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
tls-version-min 1.2
verify-x509-name server_znyzUOYI8NRpbnxG name
cipher AES-256-CBC
auth SHA256
auth-nocache
verb 3
:::                                     :::
::      Debug Output Complete            ::
:::                                     :::
:::
::: Debug output completed above.
::: Copy saved to /tmp/debug.txt
:::

```

## Console Output of `sudo iptables -t nat -S`
```
dietpi@DietPi:~$ sudo iptables -t nat -S
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT
-A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE

```

## Console Output of `sudo iptables -S`
```
dietpi@DietPi:~$ sudo iptables -S
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
-A FORWARD -s 10.8.0.0/24 -i tun0 -j ACCEPT
```

## output of `sudo netstat -uanp | grep openvpn`

```
dietpi@DietPi:~$ sudo netstat -uanp | grep openvpn
udp        0      0 0.0.0.0:1194            0.0.0.0:*                           455/openvpn

```

**Comment by XRay437** [comment]
Same issue here, just installed a fresh install of DietPi, piHole and piVPN! I'm only able to reach the VPN server (10.8.0.1) and nothing else!

**Comment by 96Octavian** [comment]
Adding `push "route 192.168.1.0 255.255.255.0"` to your server.conf, where 192.168.1.0 is your LAN, should allow you to see LAN devices from VPN connected devices. 
Also I think that `push "dhcp-option DNS 10.0.0.1"` tells the client to use VPN address 10.0.0.1 as DNS (use the Pi address) so maybe you should check you have that right, and comment out any other option pushing wrong DNS address. 
Hope this helps

**Comment by rda990** [comment]
> Same issue here, just installed a fresh install of DietPi, piHole and piVPN! I'm only able to reach the VPN server (10.8.0.1) and nothing else!

I had the same issue and fixed it by going into the PiHole Web Interface -> Settings -> DNS -> Interface listening behavior. Make sure it's on "Listen on all interfaces" instead of the "eth0" option. That should get piVPN working again, it did for me.

It broke for me after the PiHole v4.2 update, it most likely changed/defaulted to the "eth0" option. OP can you see if this fixes the issue?

**Comment by 4s3ti** [comment]
Closing this, 
long time without any activity. 

thanks for all the help! 

Kind Regards.
