### ISSUE TITLE
Install does not create Elliptic Curve Keys

### ISSUE THREAD

**Issue by Pi-DD** [pivpn/pivpn#680]
# PiVPN Issue Template

Install (Pi 3B, latest raspbian) seems to run successfully, but once complete and device keys created and transferred no connection is possible. 

## Have you searched for similar issues and solutions?
 Yes - there was one from about a year ago #483 about DH keys being generated instead of ECDSA. It did not quite seem to address my problem directly, but gave me a clue!

## Console output of `curl -L install.pivpn.io | bash`
```
 N/A
```

## Console output of `pivpn add` or `pivpn add nopass`
```
  N/A
```

Checking debug logs (no longer available because I foolishly re-installed and solved problem, but lost them!) showed that Easy RSA could not find files in its directories. 

Using pivpn -l also showed no certificates, even though device ones appeared to have been created as the files existed in the relevant directory.

## Console output of `pivpn debug`
```
  Output Here
```

## Console Output of `sudo iptables -t nat -S`
```
  Output Here
```

## Console Output of `sudo iptables -S`
```
  Output Here
```

## output of `sudo netstat -uanp | grep openvpn`

```
  Output Here
```

## Have you taken any steps towards solving your issue?
     I re-installed and when the install reached the point at which you could say "yes" to Elliptical Curve or "no" I chose "no". The install then went into (very lengthy!) creation of 2048 bit key etc. etc. Once installation showed as complete, reboot as instructed, pivpn add to create device keys, transfer them to devices and voila! everything now connects just fine. 
I don't have the skills to get beyond this, but ran debug again and it shows easy-RSA finding all the files it needs and server and device certificates exist.

**Comment by Trotter73** [comment]
Hi,

Try this, it is not Pi specific but does work and uses curves by defualt..

[https://github.com/angristan/openvpn-install](url)

**Comment by Pi-DD** [comment]
Thanks for that. I stumbled across that alternative after I had managed to make Pivpn work without curves. !!! Annoying! 

 Since Pivpn is no longer supported I’m keeping that one in my “back pocket” in case future changes stop it from working and I need to go back to basics.
