### ISSUE TITLE
Changing OpenVPN server port as well as changing to TCP from UDP if my new port doesn't bypass firewall

### ISSUE THREAD

**Issue by n00bpiuser** [pivpn/pivpn#681]
Hi,

I'm a newb Raspberry user and I was able to successfully install OpenVPN on my Raspberry pi by using a walk-through I found on pivpn.  

I have it set up on typical port 1194 udp.  Everything is currently working and I have been able to edit my ip address (I'm dynamic) when it changes (maybe once a year).   I have been editing my ip address with this command I found online on a forum.

"sudo nano /etc/openvpn/easy-rsa/pki/Default.txt"
I edit the ip address and control + x to exit and save changes
restart with 
"sudo reboot"

A new firewall at work has been installed and I can no longer access my VPN at my house (to check my security cameras etc on my local network only).  I'm trying to change to different ports because what I have read indicated that maybe ports 443 and 80 might work for me.  If not, then it was suggested to change to TCP rather than UDP.

So far I tried to edit my Default.txt and change the port the same way that I changed the ip address that I listed above.  I changed the port and saved the default.txt file and used the "pivpn add" command and created a new user/pass and tried the new .ovpn file generated in /home/pi/ovpns but this did not work.  In fact when I tried my older .ovpn file that was on port 1194 it was still working so this leads me to believe that the default.txt file located in /etc/openvpn/easy-rsa/pki/Default.txt is for the remote (login) part of the ovpn file and not actually changing the OpenVPN server port to be listening on port 443.  I did port forward in my router all UDP traffice to port 443 to my internal ip of my Raspberry pi.  I would appreciate any help on:

1)  how can I edit the server port on my OpenVPN configuration?
2)  If my UDP ports are all blocked (I'll try port 443, 80, 22, 587) one at a time I would like to also try the same ports using TCP.  

Can you please elaborate how I can go about doing this rather than re-installing my OpenVPN configuration every time?

Thank you in advance for the help.  It is highly appreciated.

**Comment by n00bpiuser** [comment]
Okay I think I was able to change the port properly as well as change from UDP to TCP.  This may be completely incorrect but my understanding is that:

okay to change the port you basically have to change both the server.conf file and the default.txt file to match - the server.conf file is for my pi to know what port to listen in on and the default.txt is what makes the .ovpn file know what port to use.  Yes I'm sure my ability to interpret and explain and not even close to the "real" part and if someone would like to chime in I would welcome it.  Here's what I just did:

type "sudo nano /etc/openvpn/server.conf"
change port and control + x to exit and save changes
restart with "sudo reboot"

then

type "sudo nano /etc/openvpn/easy-rsa/pki/Default.txt"
edit the ip address and control + x to exit and save changes
restart with "sudo reboot"

Once I complete each of these steps I was able to use:
"pivpn add" and create a new .ovpn file that worked on my new port - 

Also want to chime in that to change from UDP to TCP I was able to edit line 3 of both the server.conf and default.txt file along the way.

**Comment by james-lasersoft** [comment]
You are correct. The Default.txt file is used for generating new CLIENT .ovpn files while the server.conf actually controls how the server responds. 

When you change in the server.conf you will need to restart OpenVPN. If you only change the Default.txt no restart is required as this file is read each time. If you do not want to recreate the client .ovpn file you can edit it directly on the client and restart the OpenVPN service or reboot and it will take effect.

When editing the server.conf file make sure to change your port forwarding on your router.
