### ISSUE TITLE
How can i change the vpn config because i don't know how to turn off the server it starts on the boot

### ISSUE THREAD

**Issue by harukodi** [pivpn/pivpn#684]
How can i turn off the server without uninstall i just want to change a thing in config

**Comment by orazioedoardo** [comment]
Stop the server -> `sudo systemctl stop openvpn`
Start the server -> `sudo systemctl start openvpn`
Restart the server -> `sudo systemctl restart openvpn`
Autostart the server at boot -> `sudo systemctl enable openvpn`
Disable autostart -> `sudo systemctl disable openvpn`
