### ISSUE TITLE
Connection successful but no internet connection

### ISSUE THREAD

**Issue by alexrose** [pivpn/pivpn#686]
Current setup is: debian 9 behind a dd-wrt router.
I managed to install and successfully connect to pivpn; I can access the local network but I can't ping any domain.

Any help will be much appreciated.
Thank you!

**Comment by alexrose** [comment]
Ok, it seems that the problem was from my dd-wrt router; enabled "Forced DNS Redirection" and now it;s working fine.

**Comment by jdus73x** [comment]
I connect fine myself, but I have no data whatsoever. I will look to see if there is a setting similar in my router, but I fear it's too old.
