### ISSUE TITLE
Only Client to Client

### ISSUE THREAD

**Issue by g00sed** [pivpn/pivpn#687]
I was wondering how I can use the pivpn server only to route traffic between clients on its network, and for the clients to connect through other means for the rest of their connections.

**Comment by devZer0** [comment]
i think that's not what pivpn is made/meant for

**Comment by Giraffe1966** [comment]
Using iptables you should be able to change some firewall rules to only allow traffic to other clients. I'm not very good with iptables, though.

**Comment by devZer0** [comment]
ok, i did misunderstand your question on the first view.  the first thing to consider is removing default routing via vpn server, as pivpn is putting  

push "redirect-gateway def1"

in config, which makes pivpn system to be default router for your vpn clients. if you comment that out, you need to add "push routes" to the config to have clients being routed at all.

 not sure how far you get with that and if you may even be able to solve your problem without iptables.

at least there is a nat rule which  does natting of the clients ip adresses to the ip of the openvpn machine

root@ew-vpn1:~# iptables -t nat -n -L
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination

Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination
MASQUERADE  all  --  10.8.0.0/24          0.0.0.0/0

**Comment by Giraffe1966** [comment]
That NAT rule is added by the script and is what allows the clients to access the wider Internet. If you remove the `push "redirect-gateway def1"` option and push some more strict routing rules, the client could still add their own routing rules by editing their config, like by adding `redirect-gateway def1` manually. The only way to enforce client to client only is to use a firewall on the server (never trust the client), and drop all packets from VPN clients not destined to other VPN clients.
