### ISSUE TITLE
ip and version 

### ISSUE THREAD

**Issue by soydepr** [pivpn/pivpn#688]
have 2 questions where is the server address stored don't see in server.conf?

also  how i update to latest version

**Comment by devZer0** [comment]
> where is the server address stored don't see in server.conf?

from the faq at https://github.com/pivpn/pivpn/wiki/FAQ

Can I change the hostname, the IP address, protocol or port after the install?
Yes. To change the hostname or IP address, you will need to change /etc/openvpn/easy-rsa/pki/Default.txt and your .ovpn files if you have already generated them.

>also how i update to latest version
see https://github.com/pivpn/pivpn/wiki/Upgrading

hth
