### ISSUE TITLE
First Connection to the PiVPN doesn't work

### ISSUE THREAD

**Issue by Lazarusprogrammierer** [pivpn/pivpn#689]
I installed PiVPN, opened Port 1194. SSH and VNC is working in local network. I want to use it from anywhere on the world. So I tried to connect my iPhone 8 and my Win 10 PC to the VPN
But stillt the same loop

Sun Mar 17 18:37:51 2019 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Sun Mar 17 18:37:51 2019 TLS Error: TLS handshake failed
Sun Mar 17 18:37:51 2019 SIGUSR1[soft,tls-error] received, process restarting
Sun Mar 17 18:37:51 2019 MANAGEMENT: >STATE:1552844271,RECONNECTING,tls-error,,,,,
Sun Mar 17 18:37:51 2019 Restart pause, 300 second(s)

## Have you searched for similar issues and solutions?
    (yes/no / which issues?)
I watched different videos how to install PiVPN for days. But now I detected that the OpenVPN is perfectly running.

`sudo systemctl status openvpn@server.service`

openvpn@server.service

 - OpenVPN connection to server
   Loaded: loaded (/lib/systemd/system/openvpn@.service; disabled; vendor preset
   Active: active (running) since Sun 2019-03-17 17:28:42 UTC; 9min ago
     Docs: man:openvpn(8)
           https://community.openvpn.net/openvpn/wiki/Openvpn23ManPage
           https://community.openvpn.net/openvpn/wiki/HOWTO
  Process: 283 ExecStart=/usr/sbin/openvpn --daemon ovpn-server --status /run/op
 Main PID: 340 (openvpn)
   CGroup: /system.slice/system-openvpn.slice/openvpn@server.service
           └─340 /usr/sbin/openvpn --daemon ovpn-server --status /run/openvpn/se

Mär 17 17:28:42 Lukas_Pi_VPN ovpn-server[340]: Could not determine IPv4/IPv6 pro
Mär 17 17:28:42 Lukas_Pi_VPN systemd[1]: Started OpenVPN connection to server.
Mär 17 17:28:42 Lukas_Pi_VPN ovpn-server[340]: Socket Buffers: R=[163840->163840
Mär 17 17:28:42 Lukas_Pi_VPN ovpn-server[340]: UDPv4 link local (bound): [AF_INE
Mär 17 17:28:42 Lukas_Pi_VPN ovpn-server[340]: UDPv4 link remote: [AF_UNSPEC]
Mär 17 17:28:42 Lukas_Pi_VPN ovpn-server[340]: GID set to nogroup
Mär 17 17:28:42 Lukas_Pi_VPN ovpn-server[340]: UID set to nobody
Mär 17 17:28:42 Lukas_Pi_VPN ovpn-server[340]: MULTI: multi_init called, r=256 v
Mär 17 17:28:42 Lukas_Pi_VPN ovpn-server[340]: IFCONFIG POOL: base=10.8.0.2 size
Mär 17 17:28:42 Lukas_Pi_VPN ovpn-server[340]: Initialization Sequence Completed

Similiar problems:
    issue #509 
    issue #567 

and some more

## Console output of `curl -L install.pivpn.io | bash`
```
                                                                                 
                                                                                
     ┌───────────────────┤ Existing Install Detected! ├───────────────────┐     
     │                                                                    │     
     │                                                                    │     
     │ We have detected an existing install.                              │     
     │                                                                    │     
     │ Please choose from the following options:                          │     
     │ (You will be updated to the latest version.)                       │     
     │                                                                    │     
     │        Update      This will retain existing settings.             │     
     │        Reconfigure This will allow you to enter new settings       │     
     │                                                                    │     
     │                                                                    │     
     │                                                                    │     
     │                                                                    │     
     │                                                                    │     
     │                                                                    │     
     │                                                                    │     
     │                 <Ok>                     <Abbrechen>               │     
     │                                                                    │     
     └────────────────────────────────────────────────────────────────────┘     
                                                                                
                                                                                
```

## Console output of `pivpn add` or `pivpn add nopass`
```
 pi@Example:~ $ pivpn add
Enter a Name for the Client:  example
Enter the password for the client:  
Enter the password again to verify:  
spawn ./easyrsa build-client-full example

Note: using Easy-RSA configuration from: ./vars
Generating an EC private key
writing new private key to '/etc/openvpn/easy-rsa/pki/private/example.key.lvkoH36jf5'
Enter PEM pass phrase:
Verifying - Enter PEM pass phrase:
-----
Using configuration from /etc/openvpn/easy-rsa/openssl-easyrsa.cnf
Check that the request matches the signature
Signature ok
The Subject's Distinguished Name is as follows
commonName            :ASN.1 12:'example'
Certificate is to be certified until Mar 14 17:49:02 2029 GMT (3650 days)

Write out database with 1 new entries
Data Base Updated
Client's cert found: example.crt
Client's Private Key found: example.key
CA public Key found: ca.crt
tls-auth Private Key found: ta.key


========================================================
Done! example.ovpn successfully created! 
example.ovpn was copied to:
  /home/pi/ovpns
for easy transfer. Please use this profile only on one
device and create additional profiles for other devices.
========================================================


```

## Console output of `pivpn debug`
```
  pi@Lukas_Pi_VPN:~ $ pivpn debug
::: Generating Debug Output
:::					:::
::		PiVPN Debug		 ::
:::					:::
::	Latest Commit			 ::
:::					:::
commit 16f19e29f52d8e829cfccbee166ee32605df28a3
Author: james-lasersoft <37112079+james-lasersoft@users.noreply.github.com>
Date:   Wed Feb 27 11:32:43 2019 -0600

    Update README.md
:::					:::
::	Recursive list of files in	 ::
::	/etc/openvpn/easy-rsa/pki	 ::
:::					:::
/etc/openvpn/easy-rsa/pki/:
ca.crt
crl.pem
Default.txt
ecparams
example.ovpn
index.txt
index.txt.attr
index.txt.attr.old
index.txt.old
issued
L.ovpn
lukas.ovpn
private
serial
serial.old
ta.key

/etc/openvpn/easy-rsa/pki/ecparams:
prime256v1.pem

/etc/openvpn/easy-rsa/pki/issued:
example.crt
L.crt
lukas.crt
server_Qdtwty3GUEpvVkSM.crt

/etc/openvpn/easy-rsa/pki/private:
ca.key
example.key
L.key
lukas.key
server_Qdtwty3GUEpvVkSM.key
:::					:::
::	Output of /etc/pivpn/*		 ::
:::					:::
:: START /etc/pivpn/DET_PLATFORM ::
Raspbian
:: END /etc/pivpn/DET_PLATFORM ::
:: START /etc/pivpn/INSTALL_PORT ::
1194
:: END /etc/pivpn/INSTALL_PORT ::
:: START /etc/pivpn/INSTALL_PROTO ::
udp
:: END /etc/pivpn/INSTALL_PROTO ::
:: START /etc/pivpn/INSTALL_USER ::
pi
:: END /etc/pivpn/INSTALL_USER ::
:: START /etc/pivpn/NO_UFW ::
1
:: END /etc/pivpn/NO_UFW ::
:: START /etc/pivpn/pivpnINTERFACE ::
eth0
:: END /etc/pivpn/pivpnINTERFACE ::
:: START /etc/pivpn/setupVars.conf ::
pivpnUser=pi
UNATTUPG=unattended-upgrades
pivpnInterface=eth0
IPv4dns=192.168.178.1
IPv4addr=192.168.178.75
IPv4gw=192.168.178.1
pivpnProto=udp
PORT=1194
ENCRYPT=256
APPLY_TWO_POINT_FOUR=true
DOWNLOAD_DH_PARAM=false
PUBLICDNS=lukasproxy.ddns.net
OVPNDNS1=8.8.8.8
OVPNDNS2=8.8.4.4
:: END /etc/pivpn/setupVars.conf ::
:: START /etc/pivpn/TWO_POINT_FOUR ::
:: END /etc/pivpn/TWO_POINT_FOUR ::
:::					:::
:: /etc/openvpn/easy-rsa/pki/Default.txt ::
:::					:::
client
dev tun
proto udp
remote 188.210.XXX.XXX 1194
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
tls-version-min 1.2
verify-x509-name server_Qdtwty3GUEpvVkSM name
cipher AES-256-CBC
auth SHA256
auth-nocache
verb 3
:::					:::
::	Debug Output Complete		 ::
:::					:::
::: 
::: Debug output completed above.
::: Copy saved to /tmp/debug.txt
::: 
```

## Console Output of `sudo iptables -t nat -S`
```
  -P PREROUTING ACCEPT
-P INPUT ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT
-A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE

```

## Console Output of `sudo iptables -S`
```
  -P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT

```

## output of `sudo netstat -uanp | grep openvpn`

```
  udp        0      0 0.0.0.0:1194            0.0.0.0:*                           340/openvpn 
```

## Have you taken any steps towards solving your issue?
     which?

I reinstalled PiVPN many many times, but this wasn't the problem. I tried to deactivate my antivirus, without success. Tried instead of Lan-cable in USB slot to eth0.

hope you can fix it? 🗡 
Another point is when I try to connect the network "VPN-L" (that's the name) the system says:
Translation from German to English
"The connection to VPN-L not possible
The remote connection wasn't established because the name of the RAS server was not resolved, 

Can't reach the VPN via iPhone or Computer.

**Comment by LukaTchumburidze** [comment]
Are you sure that your network isn't not under NAT?

**Comment by Lazarusprogrammierer** [comment]
I've activated Cellular, so it shouldn't be possible right?

**Comment by Pi-DD** [comment]
This may (or may not!) be relevant - my knowledge level and expertise are insufficient for me to be at all sure, but...... errors mention TLS handshake

Recent updates to Pi S/W included some comments about levels of TLS  as follows....

`wpasupplicant (2:2.6-19) unstable; urgency=medium

  With this release, wpasupplicant no longer respects the system
  default minimum TLS version, defaulting to TLSv1.0, not TLSv1.2. If
  you're sure you will never connect to EAP networks requiring anything less
  than 1.2, add this to your wpasupplicant configuration:

    tls_disable_tlsv1_0=1
    tls_disable_tlsv1_1=1

  wpasupplicant also defaults to a security level 1, instead of the system
  default 2. Should you need to change that, change this setting in your
  wpasupplicant configuration:

    openssl_ciphers=DEFAULT@SECLEVEL=2
`

Have you run an update and seen that?
Are you Ethernet or WiFi connected? 

Stabbing in the dark somewhat,  but hope it helps

**Comment by Lazarusprogrammierer** [comment]
(I'm connected to Ethernet (eth0))

My device is up to date, because I bought it some days ago. 

I have seen something like your post before, but I didn't noticed, that it could be relevant. 

I'll check it and let you know guys. 
At first, I have to search the wpasupplicant

**Comment by LukaTchumburidze** [comment]
@Lazarusprogrammierer What do you mean by activating Cellular? I was asking about the network in which your Pi server is.

**Comment by Lazarusprogrammierer** [comment]
@LukaTchumburidze 
I'm sorry, I didn't know the word NAT ._.
I looked up the word. Do you mean the step "Port Forwarding"?

I opened the Port 1194 and sticked it to the IP4 of the local ip of my Pi
in this case 192.168.178.75

**Comment by Pi-DD** [comment]
If you are Ethernet connected my suggestion is likely to be irrelevant as wpa_supplicant configures WiFi connections to your Pi.

Out of ideas I’m afraid! (Apart from the very tedious start again from install of Raspbian upwards!) 😩😬🤣

**Comment by LukaTchumburidze** [comment]
@Lazarusprogrammierer 
Make sure on that "Port Forwarding" step you actually allowed UDP traffic. On my router default forwarding type was TCP so I got similar error, since PiVPN used UDP traffic on 1194. So my guess is that you have allowed only TCP traffic to be forwarded.

**Comment by Lazarusprogrammierer** [comment]
@LukaTchumburidze 
Thanks, but I had to choose UDP on my fritz.box.

It would be very cool if you could use Team Viewer to detect the issue?

**Comment by LukaTchumburidze** [comment]
Sure, connect me via Google Hangouts on lukatchumburidze@gmail.com

**Comment by Lazarusprogrammierer** [comment]
@LukaTchumburidze 
sorry for the break. Now we could start?

**Comment by Lazarusprogrammierer** [comment]
Okay, I know the problem.

The problem is my IP-Adress. My router (fritzbox) shows me our extern-ip with 100.XXX.XXX.XXX and the whatismyip.com shows me 188.XXX.XXX.XXX

Now, my Raspberry always wants to connect to the 188.XXX.XXX.XX
Furthermore, I published the Port, but on the nmap scan it's shown as closed.

What can be the issue for that?

**Comment by Lazarusprogrammierer** [comment]
Okay Guys:

Here is the **FIX**

Don't trust the "use this public IP" or whatismyip.com
Go to your routher and watch which IP it shows!

Than use the other option "use DNS" in the installing assistant and paste the shown IP of the router!

Problem solved <3

**Comment by Lazarusprogrammierer** [comment]
Problem is my provider. It's Inexio or Quix. They gave me an IPv4, which are not reachable from the internet. I have to use the IPv6!

**Comment by 4s3ti** [comment]
Closing this issue as it isn't PiVPN related. 
As for IPv6 Support there is already an issue open for it: https://github.com/pivpn/pivpn/issues/259

Kind Regards.
