### ISSUE TITLE
Add option for IPSec also/instead

### ISSUE THREAD

**Issue by drduker** [pivpn/pivpn#690]
It would be nice if piVPN also had an option for IPSec based server.  Example -
https://github.com/hwdsl2/setup-ipsec-vpn

PiVPN is no longer maintained, see the README

# PiVPN Issue Template

## Have you searched for similar issues and solutions?
    (yes/no / which issues?)

## Console output of `curl -L install.pivpn.io | bash`
```
  Output Here
```

## Console output of `pivpn add` or `pivpn add nopass`
```
  Output Here
```

## Console output of `pivpn debug`
```
  Output Here
```

## Console Output of `sudo iptables -t nat -S`
```
  Output Here
```

## Console Output of `sudo iptables -S`
```
  Output Here
```

## output of `sudo netstat -uanp | grep openvpn`

```
  Output Here
```

## Have you taken any steps towards solving your issue?
     which?

**Comment by devZer0** [comment]
i'm strongly against that because that's a complete different vpn/security technology and there is enough work to be done in pivpn itself

**Comment by Giraffe1966** [comment]
@drduker I agree with @devZer0, and if you need an IPSec VPN instead, why not use the project you've linked?

**Comment by drduker** [comment]
PiVPN’s name denotes no specific vpn technology but just vpn.  All I am saying is it would be nice to have the other option.  If pivpn doesn’t have enough support as it is then ignore this suggestion.  I think the adoption of pivpn would be much larger if they used a solution that would work with their phones natively without downloading an OpenVPN client also.  And I wasn’t necessarily suggesting that I would use IPSec instead, it would be nice to have it in addition to and running alongside of as the raspberry pi could handle that.

**Comment by 4s3ti** [comment]
I can agree with both @devZer0 and @drduker ... having this said .. i won't close this .. leave it tagged as enhancement and not priority.

I can see benefit on adding support for both IPSec and Wireguard .. however PiVPN doesn't have enough maintainers and supporters to add such features. 

Maybe if there are already some projects for such type of servers we can help getting them some visibility by adding links for them in our README? 

Dunno .. it is indeed to much for us at the moment but doesn't seems completely nonsense!

**Comment by 4s3ti** [comment]
going to ditch this option as we are considering adding support go wireguard instead. 
Wireguard endorses most of the concerns listed here.
