### ISSUE TITLE
Help w 2 Client Profiles: Both should see LAN, but only 1 routes internet traffic through VPN.

### ISSUE THREAD

**Issue by sumocomputers** [pivpn/pivpn#692]
Help w 2 Client Profiles: Both should see LAN, but only 1 routes internet traffic through VPN.

I am trying to create 2 client side profiles like so:

**Client Profile 1:**
When connected to the VPN, client can see the LAN and internet traffic is routed through the VPN

**Client Profile 2:**
When connected to the VPN, client can see the LAN and internet traffic is NOT routed through the VPN

I am inexperienced, but I gave it a go on my own.

On the server I commented out push "redirect-gateway def1" in /etc/openvpn/server.conf

Then on one of the client profiles I added the line redirect-gateway def1

Now each profile gets a different public IP address and internet works (progress!)

But only the client with redirect-gateway def1 can ping other LAN clients via IP; the client without that entry cannot ping any LAN clients at all.

Various Debug Outputs Below

## Console output of `pivpn debug`
```
::: Generating Debug Output
:::					:::
::		PiVPN Debug		 ::
:::					:::
::	Latest Commit			 ::
:::					:::
commit 16f19e29f52d8e829cfccbee166ee32605df28a3
Author: james-lasersoft <37112079+james-lasersoft@users.noreply.github.com>
Date:   Wed Feb 27 11:32:43 2019 -0600

    Update README.md
:::					:::
::	Recursive list of files in	 ::
::	/etc/openvpn/easy-rsa/pki	 ::
:::					:::
/etc/openvpn/easy-rsa/pki/:
ca.crt
Chris.ovpn
crl.pem
Default.txt
ecparams
index.txt
index.txt.attr
index.txt.attr.old
index.txt.old
issued
private
serial
serial.old
ta.key

/etc/openvpn/easy-rsa/pki/ecparams:
prime256v1.pem

/etc/openvpn/easy-rsa/pki/issued:
Chris.crt
server_8uM6tImcNC7XsQXS.crt

/etc/openvpn/easy-rsa/pki/private:
ca.key
Chris.key
server_8uM6tImcNC7XsQXS.key
:::					:::
::	Output of /etc/pivpn/*		 ::
:::					:::
:: START /etc/pivpn/DET_PLATFORM ::
Raspbian
:: END /etc/pivpn/DET_PLATFORM ::
:: START /etc/pivpn/INSTALL_PORT ::
1194
:: END /etc/pivpn/INSTALL_PORT ::
:: START /etc/pivpn/INSTALL_PROTO ::
udp
:: END /etc/pivpn/INSTALL_PROTO ::
:: START /etc/pivpn/INSTALL_USER ::
pi
:: END /etc/pivpn/INSTALL_USER ::
:: START /etc/pivpn/NO_UFW ::
1
:: END /etc/pivpn/NO_UFW ::
:: START /etc/pivpn/pivpnINTERFACE ::
eth0
:: END /etc/pivpn/pivpnINTERFACE ::
:: START /etc/pivpn/setupVars.conf ::
pivpnUser=pi
UNATTUPG=unattended-upgrades
pivpnInterface=eth0
IPv4dns=192.168.2.1
IPv4addr=192.168.2.14
IPv4gw=192.168.2.1
pivpnProto=udp
PORT=1194
ENCRYPT=256
APPLY_TWO_POINT_FOUR=true
DOWNLOAD_DH_PARAM=false
PUBLICDNS=
OVPNDNS1=8.8.8.8
OVPNDNS2=8.8.4.4
:: END /etc/pivpn/setupVars.conf ::
:: START /etc/pivpn/setupVars.conf.update.bak ::
pivpnUser=pi
UNATTUPG=unattended-upgrades
pivpnInterface=eth0
IPv4dns=192.168.2.1
IPv4addr=192.168.2.14
IPv4gw=192.168.2.1
pivpnProto=udp
PORT=1194
ENCRYPT=256
APPLY_TWO_POINT_FOUR=true
DOWNLOAD_DH_PARAM=false
PUBLICDNS=
OVPNDNS1=8.8.8.8
OVPNDNS2=8.8.4.4
:: END /etc/pivpn/setupVars.conf.update.bak ::
:: START /etc/pivpn/TWO_POINT_FOUR ::
:: END /etc/pivpn/TWO_POINT_FOUR ::
:::					:::
:: /etc/openvpn/easy-rsa/pki/Default.txt ::
:::					:::
client
dev tun
proto udp
remote My-Public-IP 1194
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
tls-version-min 1.2
verify-x509-name server_8uM6tImcNC7XsQXS name
cipher AES-256-CBC
auth SHA256
auth-nocache
verb 3
:::					:::
::	Debug Output Complete		 ::
:::					:::
::: 
::: Debug output completed above.
::: Copy saved to /tmp/debug.txt
::: 

```

## Console Output of `sudo iptables -t nat -S`
```
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT
-A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE
-A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE
-A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE
-A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE
-A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE
-A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE
```

## Console Output of `sudo iptables -S`
```
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
```

## output of `sudo netstat -uanp | grep openvpn`

```
udp        0      0 0.0.0.0:1194            0.0.0.0:*                           349/openvpn
```

**Comment by orazioedoardo** [comment]
If you want one client to route all internet traffic to the vpn use `redirect-gateway def1` inside its config. If you want the client to only route traffic directed to the remote LAN, use `route 192.168.2.0 255.255.255.0` (assuming 192.168.2.0/24 is your LAN). Note that if you use the first option you don't need the second. Be sure to remove push "redirect-gateway def1" in /etc/openvpn/server.conf as you did, otherwhise it will override the client settings.

Note that you only have client Chris, if you want to use its config on multiple devices concurrently, add or decomment `duplicate-cn` inside the server config. Personally I prefer to have different profiles for each device.

**Comment by sumocomputers** [comment]
I now have 2 OVPN config files, one with just redirect-gateway def1 and the other with just route 192.168.2.0 255.255.255.0, and it works perfectly.

Thank you very much.
