### ISSUE TITLE
Optimize piVPN - Easy-RSA is not updated + Suggestion

### ISSUE THREAD

**Issue by himuura** [pivpn/pivpn#693]
PiVPN is no longer maintained, see the README

# PiVPN Issue Template

Easy-RSA stuck on version 3.0.4 (newer is 3.0.7). The install script is set to install the 3.0.4.
Suggestion: Update command should be available from pivpn menu,like pivpn -update.

## Have you searched for similar issues and solutions?
    Yes

## Have you taken any steps towards solving your issue?
     Renamed the older easy-rsa folder, git the new easy-rsa, and copied the PKI folder inside the older easy-rsa to the new easy-rsa

**Comment by devZer0** [comment]
could you please re-adit your issue to skip unnecessary template data? that way it's hard to read....

anyhow, i'm also curious why pivpn brings it's own version of easy-rsa

**Comment by himuura** [comment]
> could you please re-adit your issue to skip unnecessary template data? that way it's hard to read....
> 
> anyhow, i'm also curious why pivpn brings it's own version of easy-rsa
> 
> also see #181

Done mate, thanks for the tip. The issue is quite simple, the install script of pivpn is searching specifically for version 3.0.4 of easy-rsa instead of the latest. I'm not an expert by all means, i'll leave that to the pros. But i checked the change log of 3.0.4 and 3.0.7 (if im not mistaken) and there were a couple of issues resolved by the latest version. It's just that.
Oh and the suggestion is in pivpn command menu, like "pivpn -c" checks for connected clients, it would be quite easier to update pivpn with a similar command like "pivpn -up" to update from the repo and other openvpn dependencies (like easy-rsa perhaps). Just my 2 cents on the subject, hope it's helpful.

**Comment by devZer0** [comment]
yes, i think it's helpful and it's not "just that" because it is a problem if security related programs are being forked and remain unmaintained and don't get their updates. 

so, it's important to know why pivpn still uses 3.0.4 and if there is no real reason anymore, it should get rid of that and use upstream project

**Comment by himuura** [comment]
I concur. Don't know if it helps but on the install.sh i found this:
"easyrsaVer="3.0.4"
easyrsaRel="https://github.com/OpenVPN/easy-rsa/releases/download/v${easyrsaVer}/EasyRSA-${easyrsaVer}.tgz"
"

**Comment by devZer0** [comment]
whoops, apparently i did oversee that pivpn does use upstream easy-rsa - but why is it in https://github.com/pivpn/easy-rsa then ? that could/should be deleted then....

**Comment by Giraffe1966** [comment]
@devZer0 https://github.com/pivpn/easy-rsa is no longer used anymore by the script. See #597.

**Comment by devZer0** [comment]
yes, i recognized that in the meantime. things would be easier (and not so confusing) if that repo would be dropped then. when getting into pivpn, the first thing people do is browsing the web/git repo or reading into things - so why should they come across things which are obsolete already? this is why many software projects simply suck - there is so much oudated information/references everywhere...  life could be so much easier....

**Comment by devZer0** [comment]
https://github.com/pivpn/pivpn/issues/700

**Comment by 4s3ti** [comment]
Closing this... as #700 will take over this issue.
