### ISSUE TITLE
typo in ip information dialogue

### ISSUE THREAD

**Issue by devZer0** [pivpn/pivpn#694]
In IP Information Dialoge, you tell "you had elastic IP", i think this should be "static".

─┤ IP Information ├─────────────────────────┐
<snipp>
│ anyway. Just ensure before this installer started you had set an   │
│ elastic IP on your instance.

**Comment by 4s3ti** [comment]
Nope @devZer0 its actually correct. 

            echo "::: IP Information"
            echo "::: Since we think you are not using Raspbian, we will not configure a static IP for you."
            echo "::: If you are in Amazon then you can not configure a static IP anyway."
            echo "::: Just ensure before this installer started you had set an elastic IP on your instance."

you can use PiVPN in AWS ubuntu instances, and AWS doesn't have static IPs ... in AWS its called Elastic IP instead. 

Some more info here =) 

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/elastic-ip-addresses-eip.html

Closing the issue. 
If you have more questions feel free to reopen.

**Comment by devZer0** [comment]
sorry, i never heard about "elastic ip" before, thanks for the pointer

**Comment by 4s3ti** [comment]
No worries! you are always welcome! =)
