### ISSUE TITLE
duplicated code/scripts in pivpn installation - why ?

### ISSUE THREAD

**Issue by devZer0** [pivpn/pivpn#695]
what is the purpose of these duplicated scripts in /etc/.pivpn/scripts and /opt/pivpn ?

root@pivpn1:/etc/.pivpn/scripts# ls -la /etc/.pivpn/scripts/
insgesamt 48
drwxr-xr-x 2 root root 4096 Mär 22 20:28 .
drwxr-xr-x 5 root root 4096 Mär 22 20:28 ..
-rw-r--r-- 1 root root  651 Mär 22 20:28 bash-completion
-rw-r--r-- 1 root root 1323 Mär 22 20:28 clientStat.sh
-rw-r--r-- 1 root root  335 Mär 22 20:28 fix_iptables.sh
-rw-r--r-- 1 root root  794 Mär 22 20:28 listOVPN.sh
-rwxr-xr-x 1 root root 7205 Mär 22 20:28 makeOVPN.sh
-rw-r--r-- 1 root root 1043 Mär 22 20:28 pivpnDebug.sh
-rw-r--r-- 1 root root 3325 Mär 22 20:28 removeOVPN.sh
-rw-r--r-- 1 root root 5270 Mär 22 20:28 uninstall.sh

root@pivpn1:/etc/.pivpn/scripts# ls -la /opt/pivpn/
insgesamt 44
drwsr-xr-x 2 pivpn root 4096 Mär 22 20:28 .
drwxr-xr-x 3 root  root 4096 Mär 22 20:28 ..
-rwxr-xr-x 1 root  root 1323 Mär 22 20:28 clientStat.sh
-rwxr-xr-x 1 root  root  335 Mär 22 20:28 fix_iptables.sh
-rwxr-xr-x 1 root  root  794 Mär 22 20:28 listOVPN.sh
-rwxr-xr-x 1 root  root 7205 Mär 22 20:28 makeOVPN.sh
-rwxr-xr-x 1 root  root 1043 Mär 22 20:28 pivpnDebug.sh
-rwxr-xr-x 1 root  root 3325 Mär 22 20:28 removeOVPN.sh
-rwxr-xr-x 1 root  root 5270 Mär 22 20:28 uninstall.sh

**Comment by devZer0** [comment]
ok, i see, it's the local git dir  - but wouldn't that better belong in /home/$pivpn ?

i never have seen git repo checkout to /etc , that is directory for configuration/startup files. not for installation-source dir.

**Comment by 4s3ti** [comment]
Been looking at this .. I have never liked the fact of having that Dir there, specially hidden, but never paid much attention to it tough ... 

This should be fixed and we aren't definitely putting stuff in the right places... 

`/etc/.pivp` Should be moved to `/usr/local/share/pivpn`
`/etc/pivpn` Should be moved to `/var/local/pivpn`
the Scripts in /opt/pipvn should be symlinks to `/usr/local/share/pivpn/scripts/<script> `

Update script should then be changed to just here then should just pull latest changes from pivpn maaster or test repo 
guess this actually will simplify a lot of stuff ... 

 @devZer0  @orazioedoardo you agree?

Gues we could put this change on test-wireguard branch.

**Comment by orazioedoardo** [comment]
Considering that the script mimics the structure of Pi-hole, I think `/etc/.pivpn` for storing git files and `/opt/pivpn` for the scripts make sense. Considering the file system hierarchy, I wouldn't use `/var`. I would, however, make make `/opt/pivpn`'s scripts symlinks to `/etc/.pivpn`'s scripts.

**Comment by 4s3ti** [comment]
@orazioedoardo well we don't really need to follow all pihole does even though the similarities are there. 
I personaly don't thing /etc/ is a place to put a dotfile/folder ... Linux as a file system hierachy for this kinds of things, i do believe that /etc/.pivpn should be elsewhere in the file system. 

I Do believe as well this will cause less confusion for our users.

**Comment by 4s3ti** [comment]
I'd really like to get some traction here ... 
I don't really like the fact of having `/etc/.pivpn/` this is against all linux logics and it should go elsewhere. 

I believe that `/etc/.pivpn/` should definitely go to `/usr/local/share/pivpn` 

also `/etc/pivpn` its arguable but, it is not a configuration file, and i can agree as well that `/var/...` its not the best place for it .. so it doesn't really bother me to keep it where it is. 

However i would like some agreement here specially from you @orazioedoardo ... What you thig? 
@devZer0 and you? 

This is the best time to address this!
test branch looks pretty solid now and its a good time to make the change before moving it to master. 
tbh i'd like to have test branch moved to master this weekend .. latest next.

**Comment by orazioedoardo** [comment]
I'm OK with this. Download the git repo to `/usr/local/share/pivpn` and symlink scripts to `/opt/pivpn`.

**Comment by 4s3ti** [comment]
Been working on this.. unfortunately still didn't had time to finish it up. 

But if i see things correctly ... by doing this we don't even actually need to send scripts to /opt/ and to create symlinks.

For sake of simplicity and make it easier to deploy and add new (what i like to call) Management scripts, the only script that needs to be updated is actually pivpn and make it get the scripts from the correct place at /usr/local/share ....

The only script that actually matters is pivpn that is placed into /usr/local/bin 

this way ... all gets even easier to maintain and update.

**Comment by 4s3ti** [comment]
Will set this on hold ... as the update will break once again for users that want to use pivpn -up .. not really sure if we want this at the moment.
