### ISSUE TITLE
why are dots in username disallowed ? 

### ISSUE THREAD

**Issue by devZer0** [pivpn/pivpn#696]
why is only alphanumeric characters and dashes allowed in pivpn ? please add "." , "_" and "@" so it matches allowed openvpn authentication characters.

we always used "my.name-vpn" for accounts and don't want to change naming scheme. i commented out check routine makeOVPN.sh and it seems to work as usual with "." in name.

so why is dot disallowed?

**Comment by devZer0** [comment]
from openvpn manpage:
<snipp>
      --auth-user-pass-verify cmd method
<snipp>
              To protect against a client passing a maliciously formed username or password string, the username string must consist only of these characters: alphanumeric, underbar ('_'),  dash  ('-'),  dot
              ('.'),  or  at  ('@').   The  password string can consist of any printable characters except for CR or LF.  Any illegal characters in either the username or password string will be converted to
              underbar ('_').
<snipp>

**Comment by devZer0** [comment]
for example, i would like to use email adresses for the login-name, to have easy mechanism to send messages to vpn users based on openvpn log. 

so, could you please change makeOVPN.sh to contain this one ?

if [[ "${NAME}" =~ [^a-zA-Z0-9_@\-\.] ]]; then
    echo "Name can only contain alphanumeric characters and dashes (-)."
    exit 1
fi

**Comment by devZer0** [comment]
to be exact - it's not the username but the certificate name/common name in subject field of certificate - and there is no special restriction with that, too:

https://stackoverflow.com/questions/5136198/what-strings-are-allowed-in-the-common-name-attribute-in-an-x-509-certificate

**Comment by Giraffe1966** [comment]
@devZer0 Not really sure, but possibly because if the first character is a dot then the file will become hidden, possibly confusing users who've never heard of hidden files. Of course somebody could add a prompt disallowing or discouraging names that start with a dot, but I don't think anybody thought of this or had the motivation to code it. Perhaps you could add it in?

**Comment by 4s3ti** [comment]
Putting this up for investigation ... Might be worth looking at it ... 

openvpn user is not a system user by itself so it should not be a problem adding it ... maybe @Giraffe1966 is right ... feel free to investigate it if you want @devZer0

**Comment by 4s3ti** [comment]
already available in test branch. 
to be closed when test gets merged into master.

**Comment by 4s3ti** [comment]
this has been already pushed into master with PR #740 
Closing this issue. 

Thank you for your interest.
