### ISSUE TITLE
happy to see this is being maintained again! wouldn't have set up a vpn without it. 

### ISSUE THREAD

**Issue by mrsteve0924** [pivpn/pivpn#698]
PiVPN is no longer maintained, see the README

# PiVPN Issue Template

## Have you searched for similar issues and solutions?
    (yes/no / which issues?)

## Console output of `curl -L install.pivpn.io | bash`
```
  Output Here
```

## Console output of `pivpn add` or `pivpn add nopass`
```
  Output Here
```

## Console output of `pivpn debug`
```
  Output Here
```

## Console Output of `sudo iptables -t nat -S`
```
  Output Here
```

## Console Output of `sudo iptables -S`
```
  Output Here
```

## output of `sudo netstat -uanp | grep openvpn`

```
  Output Here
```

## Have you taken any steps towards solving your issue?
     which?

**Comment by Giraffe1966** [comment]
@mrsteve0924 Thanks for your support. @james-lasersoft This issue can be closed.

**Comment by 4s3ti** [comment]
The project is getting back on track! 
Thanks to you all that have been keeping the boat sailing, 
If all goes well i might be back to maintain this wonderfull project very soon. 

Kind Regards to you all. 
closing issue.
