### ISSUE TITLE
pivnp -l shows more clients than I created

### ISSUE THREAD

**Issue by sharpshot21** [pivpn/pivpn#699]
So Just for curiousity I ran pivpn -l and low and behold there were 5 clients listed. I've only created 4. after running ls -la /etc/openvpn/easy-rsa/pki/issued/ it was determined that the 5th client was actually the first one created on the server. I doubt that someone created one before I could while I was ssh'd into the server. The client name is server_ZemTozqpiKmpg4PI. The crux of the matter is I cannot revoke that cert. pivpn -r server_ZemTozqpiKmpg4pi returns "You pased an invalid cert name: 'server_ZemTozqpiKmpg4PI' " What is this and why can't I get rid of it? And Yes I've tried sudo and no dice there either.

**Comment by devZer0** [comment]
pivpn -l does not show clients but it shows all certificates - the one with "server_..." is the server certificate, openvpn needs to work and which is the "counterpart" for the client certificates.

":::  -l, list             List all valid and revoked certificates"

**Comment by sharpshot21** [comment]
Ahh, thank you. That's my bad for the misinterpretation of what was going on. I just hadn't seen it before. and I could't find anything about it looking through the code on here, or on google. Thank you again.
