### ISSUE TITLE
Test on free-tier Debian Jessie amazon image

### ISSUE THREAD

**Issue by 0-kaladin** [pivpn/pivpn#7]
this would allow people to have a vpn server on the internet, encrypting their communications out of their home ISP, as well as not rely on their home ISP while traveling, they will always have the amazon server to vpn into.

**Comment by 0-kaladin** [comment]
There is no free-tier Jessie.  So I used the free-tier Ubuntu server 14.04.

**Comment by 0-kaladin** [comment]
This commit has it working on ubuntu, assuming using the amazon ami.
fa60d29aa3ceb0ed6c92cbb88cc3c7e6c22c5cdd

**Comment by planetahuevo** [comment]
The free tier is only for a year at amazon.  So it is not really free. 
Just to make it clear to others.

**Comment by 0-kaladin** [comment]
I'd still call it really free.  After a year you can sign up for another amazon account or leverage the ubuntu server with other things you may want to host and the cost is $9.75/mo. 
Either way its a year free and if you just want to swap accounts/servers once a year it is forever free.
The whole point here wasn't whether 'free' or not but running an openvpn server outside of your ISP network.

**Comment by planetahuevo** [comment]
I understand, but I though it was worth to explain it.
