### ISSUE TITLE
please disable/delete https://github.com/pivpn/easy-rsa git-repo

### ISSUE THREAD

**Issue by devZer0** [pivpn/pivpn#700]
as pivpn does seem to use upstream repo/release now

**Comment by 4s3ti** [comment]
@james-lasersoft can you please fix this? 
Perhaps can you raise my permissions within the repo? 

Kind Regards.

**Comment by 4s3ti** [comment]
This has been done.
Deleted pivpn/easy-rsa. 

Closing.
