### ISSUE TITLE
Cannot connect to pivpn

### ISSUE THREAD

**Issue by rhelix** [pivpn/pivpn#701]
PiVPN is no longer maintained, see the README

# PiVPN Issue Template

relix@rcomp:~$ curl -L https://install.pivpn.io | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   178  100   178    0     0    122      0  0:00:01  0:00:01 --:--:--   122
100 53084  100 53084    0     0  23139      0  0:00:02  0:00:02 --:--:-- 23139
:::
::: sudo will be used for the install.
::: Update option selected.
::: Verifying free disk space...

                        ┌───────────────────┤ Existing Install Detected! ├───────────────────┐
                        │                                                                    │
                        │                                                                    │
                        │ We have detected an existing install.                              │
                        │                                                                    │
                        │ Please choose from the following options:                          │
                        │ (You will be updated to the latest version.)                       │
                        │                                                                    │
                        │        Update      This will retain existing settings.             │
                        │        Reconfigure This will allow you to enter new settings       │
                        │                                                                    │
                        │                                                                    │
                        │                                                                    │
                        │                                                                    │
                        │                                                                    │
                        │                                                                    │
                        │                                                                    │
                        │                 <Ok>                     <Cancel>                  │
                        │                                                                    │
                        └────────────────────────────────────────────────────────────────────┘

## Issue
I have install pivpn for RPI3 using Ubuntu Mate, the installation went ok but when trying to connect using client it has problem. In the pi also having pi-hole installed previously.
I have do the forwarding in the router for port 1194. I check to forward other port like 8080 (testing web server) in the same pi and it is working fine.

## Have you searched for similar issues and solutions?
    (yes/no / which issues?)
yes, 324, 386

## Console output of `pivpn debug`
```
relix@rcomp:~$ pivpn debug
::: Generating Debug Output
:::                                     :::
::              PiVPN Debug              ::
:::                                     :::
::      Latest Commit                    ::
:::                                     :::
commit 16f19e29f52d8e829cfccbee166ee32605df28a3
Author: james-lasersoft <37112079+james-lasersoft@users.noreply.github.com>
Date:   Wed Feb 27 11:32:43 2019 -0600

    Update README.md
:::                                     :::
::      Recursive list of files in       ::
::      /etc/openvpn/easy-rsa/pki        ::
:::                                     :::
/etc/openvpn/easy-rsa/pki/:
ca.crt
crl.pem
Default.txt
dh2048.pem
index.txt
index.txt.attr
index.txt.old
issued
private
serial
serial.old
ta.key

/etc/openvpn/easy-rsa/pki/issued:
server_9rJo0MseC3bqy75W.crt

/etc/openvpn/easy-rsa/pki/private:
ca.key
server_9rJo0MseC3bqy75W.key
:::                                     :::
::      Output of /etc/pivpn/*           ::
:::                                     :::
:: START /etc/pivpn/DET_PLATFORM ::
Ubuntu
:: END /etc/pivpn/DET_PLATFORM ::
:: START /etc/pivpn/INSTALL_PORT ::
1194
:: END /etc/pivpn/INSTALL_PORT ::
:: START /etc/pivpn/INSTALL_PROTO ::
udp
:: END /etc/pivpn/INSTALL_PROTO ::
:: START /etc/pivpn/INSTALL_USER ::
relix
:: END /etc/pivpn/INSTALL_USER ::
:: START /etc/pivpn/NO_UFW ::
1
:: END /etc/pivpn/NO_UFW ::
:: START /etc/pivpn/pivpnINTERFACE ::
enxb827ebcbb3a8
:: END /etc/pivpn/pivpnINTERFACE ::
:: START /etc/pivpn/setupVars.conf ::
pivpnUser=relix
UNATTUPG=unattended-upgrades
pivpnInterface=enxb827ebcbb3a8
IPv4dns=
IPv4addr=192.168.0.200
IPv4gw=192.168.0.1
pivpnProto=udp
PORT=1194
ENCRYPT=2048
APPLY_TWO_POINT_FOUR=false
DOWNLOAD_DH_PARAM=false
PUBLICDNS=guzproxy.ddns.net
OVPNDNS1=192.168.0.200
OVPNDNS2=
:: END /etc/pivpn/setupVars.conf ::
:: START /etc/pivpn/setupVars.conf.update.bak ::
pivpnUser=relix
UNATTUPG=unattended-upgrades
pivpnInterface=enxb827ebcbb3a8
IPv4dns=
IPv4addr=192.168.0.200
IPv4gw=192.168.0.1
pivpnProto=udp
PORT=1194
ENCRYPT=2048
APPLY_TWO_POINT_FOUR=false
DOWNLOAD_DH_PARAM=false
PUBLICDNS=guzproxy.ddns.net
OVPNDNS1=192.168.0.200
OVPNDNS2=
:: END /etc/pivpn/setupVars.conf.update.bak ::
:: START /etc/pivpn/TWO_POINT_FOUR ::
:: END /etc/pivpn/TWO_POINT_FOUR ::
:::                                     :::
:: /etc/openvpn/easy-rsa/pki/Default.txt ::
:::                                     :::
client
dev tun
proto udp
remote guzproxy.ddns.net 1194
resolv-retry infinite
nobind
persist-key
persist-tun
key-direction 1
remote-cert-tls server
tls-version-min 1.2
verify-x509-name server_9rJo0MseC3bqy75W name
cipher AES-256-CBC
auth SHA256
auth-nocache
verb 3
:::                                     :::
::      Debug Output Complete            ::
:::                                     :::
:::
::: Debug output completed above.
::: Copy saved to /tmp/debug.txt
:::
relix@rcomp:~$

```

## Console Output of `sudo iptables -t nat -S`
```
  relix@rcomp:~$ sudo iptables -t nat -S
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT
-A POSTROUTING -s 10.8.0.0/24 -o enxb827ebcbb3a8 -j MASQUERADE

```

## Console Output of `sudo iptables -S`
```
  relix@rcomp:~$ sudo iptables -S
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT

```

## output of `sudo netstat -uanp | grep openvpn`

```
  relix@rcomp:~$ sudo netstat -uanp | grep openvpn
udp        0      0 0.0.0.0:1194            0.0.0.0:*                           4444/openvpn

```

## Have you taken any steps towards solving your issue?
     which?
Tried:
- changing port other than 1194
- reinstalling pivpn
- add following iptables
iptables -t nat -A INPUT -i enxb827ebcbb3a8 -p udp -m udp --dport 1194 -j ACCEPT
iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o enxb827ebcbb3a8 -j SNAT --to-source 192.168.200

**Comment by 4s3ti** [comment]
>  ... using client it has problem. In the pi also having pi-hole installed previously. ...

This is way to vague, can you please provide some logs? what error do you get? 

Most likely you are behind a NAT therefore you cannot connect to your Home network as it cannot be reached. 

Kind Regards.

**Comment by rhelix** [comment]
I forget to close this issue. Yes, you are right! Last time when I check directly from the modem it is using private IP, that's why it wont connect.

Thank you.
