### ISSUE TITLE
UFW + PiVPN integration

### ISSUE THREAD

**Issue by himuura** [pivpn/pivpn#702]
Not really an issue but i'm having a couple of issues to configure correctly UFW with pivpn. Connection is done flawlessly but i just cant browse any website...My config:

To                         Action      From
--                         ------      ----
22/tcp                     ALLOW       Anywhere
4096/udp                   ALLOW       Anywhere
53/tcp                     ALLOW       Anywhere
53/udp                     ALLOW       Anywhere
53                         ALLOW       10.8.0.0/24
53,67/udp on wlan0         ALLOW       Anywhere
22/tcp (v6)                ALLOW       Anywhere (v6)
4096/udp (v6)              ALLOW       Anywhere (v6)
53/tcp (v6)                ALLOW       Anywhere (v6)
53/udp (v6)                ALLOW       Anywhere (v6)
53,67/udp (v6) on wlan0    ALLOW       Anywhere (v6)

Anywhere                   ALLOW OUT   Anywhere on tun0
53,4096/udp                ALLOW OUT   Anywhere on wlan0
80/tcp                     ALLOW OUT   Anywhere
443/tcp                    ALLOW OUT   Anywhere
53/udp                     ALLOW OUT   Anywhere on wlan0
4096/udp                   ALLOW OUT   Anywhere on wlan0
Anywhere (v6)              ALLOW OUT   Anywhere (v6) on tun0
53,4096/udp (v6)           ALLOW OUT   Anywhere (v6) on wlan0
80/tcp (v6)                ALLOW OUT   Anywhere (v6)
443/tcp (v6)               ALLOW OUT   Anywhere (v6)
53/udp (v6)                ALLOW OUT   Anywhere (v6) on wlan0
4096/udp (v6)              ALLOW OUT   Anywhere (v6) on wlan0

Any ideas? (using a zero w)

**Comment by 4s3ti** [comment]
if you still need help please reopen an issue using the issue template and filling it the best you can so we can help you out tracking the problem. 

also please consider taking this to our subreddit [r/pivpn](https://www.reddit.com/r/pivpn/) as this is not entirely a code related issue.


Kind Regards.
