### ISSUE TITLE
Backend Updates

### ISSUE THREAD

**Issue by 0-kaladin** [pivpn/pivpn#707]
I'll be performing some backend updates to the pivpn.io site over the next couple of weeks.  
Although i have no time to maintain the actual project, backend work i can do in my sleep so...
The ubuntu server it is hosted on will be upgraded to a newer LTS release, php version upgraded for security patches on the wordpress site, and I'll finally move it to https since github added this: https://github.blog/2018-05-01-github-pages-custom-domains-https/

I'll post updates here and close this once all is done.

**Comment by devZer0** [comment]
>Although i have no time to maintain the actual project,

so, the project is unmaintained?

what about asking for people willing to help for maintenance?

**Comment by Giraffe1966** [comment]
It is maintained, just not by @0-kaladin, see #675.

**Comment by 4s3ti** [comment]
https://github.com/pivpn/pivpn/issues/236

closing this one! @0-kaladin do you need any assistance with this? 
please get in touch with me if so, maybe i can certainly host this on my servers if you don't have the time to keep the website as well.
