### ISSUE TITLE
View queries

### ISSUE THREAD

**Issue by trixonet** [pivpn/pivpn#708]
Just a question, I couldn't find it in any open/closed issues. Is there a way I can see a log of all the DNS queries PiVPN has made?

**Comment by d0nlab** [comment]
That’s not logged with Pivpn but if you install pihole it would.

**Comment by trixonet** [comment]
Would I just install it without doing any changes?

**Comment by Giraffe1966** [comment]
You would have to change the DNS servers of pivpn to point to the pi-hole DNS server. Don't use localhost as the DNS option for OpenVPN, as that tells the clients to use themselves for DNS resolution (learned that the hard way), instead use the IP of the Pi.

**Comment by trixonet** [comment]
Problem solved, pointing the PiVPN server to Pi-Hole works.
