### ISSUE TITLE
Can't connect to PiVPN from asus rt-ac1750

### ISSUE THREAD

**Issue by mwoolweaver** [pivpn/pivpn#709]
# PiVPN Issue Template

## Have you searched for similar issues and solutions?

#20 , #420 , #305 

## Console output of `curl -L install.pivpn.io | bash`
```
  Output Here
```

## Console output of `pivpn add` or `pivpn add nopass`
```
  Output Here
```

## Console output of `pivpn debug`
```
  ::: Generating Debug Output
:::					:::
::		PiVPN Debug		 ::
:::					:::
::	Latest Commit			 ::
:::					:::
commit e4fd3703788a1095e3b4f6c186eefc94e82b2a78
Author: 4s3ti <cfcolaco@gmail.com>
Date:   Fri Mar 29 09:47:27 2019 +0100

    Update ISSUE_TEMPLATE.md
:::					:::
::	Recursive list of files in	 ::
::	/etc/openvpn/easy-rsa/pki	 ::
:::					:::
/etc/openvpn/easy-rsa/pki/:
Default.txt
ca.crt
crl.pem
ecparams
imac.ovpn
index.txt
index.txt.attr
index.txt.attr.old
index.txt.old
issued
kassie-router.ovpn
kassie.ovpn
michael.ovpn
private
serial
serial.old
ta.key

/etc/openvpn/easy-rsa/pki/ecparams:
prime256v1.pem

/etc/openvpn/easy-rsa/pki/issued:
imac.crt
kassie.crt
michael.crt
server_xCjAbzXqsC6xTIyt.crt

/etc/openvpn/easy-rsa/pki/private:
ca.key
imac.key
kassie.key
michael.key
server_xCjAbzXqsC6xTIyt.key
:::					:::
::	Output of /etc/pivpn/*		 ::
:::					:::
:: START /etc/pivpn/DET_PLATFORM ::
Ubuntu
:: END /etc/pivpn/DET_PLATFORM ::
:: START /etc/pivpn/INSTALL_PORT ::
1194
:: END /etc/pivpn/INSTALL_PORT ::
:: START /etc/pivpn/INSTALL_PROTO ::
udp
:: END /etc/pivpn/INSTALL_PROTO ::
:: START /etc/pivpn/INSTALL_USER ::
mach_voucher
:: END /etc/pivpn/INSTALL_USER ::
:: START /etc/pivpn/NO_UFW ::
1
:: END /etc/pivpn/NO_UFW ::
:: START /etc/pivpn/TWO_POINT_FOUR ::
:: END /etc/pivpn/TWO_POINT_FOUR ::
:: START /etc/pivpn/pivpnINTERFACE ::
ens4
:: END /etc/pivpn/pivpnINTERFACE ::
:: START /etc/pivpn/setupVars.conf ::
pivpnUser=mach_voucher
UNATTUPG=unattended-upgrades
pivpnInterface=ens4
IPv4dns=
IPv4addr=10.128.0.2
IPv4gw=10.128.0.1
pivpnProto=udp
PORT=1194
ENCRYPT=256
APPLY_TWO_POINT_FOUR=true
DOWNLOAD_DH_PARAM=false
PUBLICDNS=
OVPNDNS1=10.128.0.2
OVPNDNS2=
:: END /etc/pivpn/setupVars.conf ::
:::					:::
:: /etc/openvpn/easy-rsa/pki/Default.txt ::
:::					:::
client
dev tun
proto udp
remote 
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
tls-version-min 1.2
verify-x509-name server_xCjAbzXqsC6xTIyt name
cipher AES-256-CBC
auth SHA256
auth-nocache
verb 3
:::					:::
::	Debug Output Complete		 ::
:::					:::
::: 
::: Debug output completed above.
::: Copy saved to /tmp/debug.txt
::: 
```

## Console Output of `sudo iptables -t nat -S`
```
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT
-A POSTROUTING -s 10.8.0.0/24 -o ens4 -j MASQUERADE
```

## Console Output of `sudo iptables -S`
```
 -P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
-N sshguard
-A INPUT -i lo -p tcp -m tcp --dport 4711:4720 -j ACCEPT
-A INPUT -p udp -m udp --dport 53 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 53 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 80 -j ACCEPT
-A INPUT -j sshguard

```

## output of `sudo netstat -uanp | grep openvpn`

```
 udp        0      0 0.0.0.0:1194            0.0.0.0:*                           5599/openvpn
```

## Have you taken any steps towards solving your issue?
     which?

I can't seem to get my asus rt-ac1750 (in client mode) to connect to piVPN? I have tried multiple different ovpn file created with ```pippin add nopass``` with no success.

relative log from asus rt-ac1750

``` 
Apr  2 19:49:00 rc_service: httpd 346:notify_rc restart_vpncall
Apr  2 19:49:05 rc_service: httpd 346:notify_rc restart_vpncall
Apr  2 19:49:05 vpnclient4[3764]: Options error: Unrecognized option or missing parameter(s) in config.ovpn:33: tls-version-min (2.3.2)
Apr  2 19:49:05 vpnclient4[3764]: Use --help for more information.
```

**Comment by Giraffe1966** [comment]
@mwoolweaver Please post the config from the asus rt-ac1750, as the options error at the bottom of the log means the asus has a problem.

**Comment by mwoolweaver** [comment]
@Giraffe1966 would you be able to lead me in the right direction to accomplish that?

**Comment by mwoolweaver** [comment]
@Giraffe1966 figured that part out. 


not sure what's wrong with it though tbh

config.ovpn that is on the router 

# Automatically generated configuration

# Tunnel options
remote 
resolv-retry infinite
nobind
proto udp
port 1194
dev tun14
sndbuf 0
rcvbuf 0
persist-tun
persist-key
daemon vpnclient4
verb 3
status-version 2
status status 10

# Client Mode
client

# Data Channel Encryption Options
auth SHA256
cipher AES-256-CBC

# TLS Mode Options
ca ca.crt
cert client.crt
key client.key

# Custom Configuration
remote-cert-tls server
tls-version-min 1.2
verify-x509-name server_xCjAbzXqsC6xTIyt name
auth-nocache
tls-crypt [[INLINE]] "#
# 2048 bit OpenVPN static key
#
-----BEGIN OpenVPN Static key V1-----
e879e785f6b36324ba4717b23238d5d3
5f31b13ead5edeba20f2a3cf3c6de9d3
c86fe8fc401d417cdb0b0f4bdab69aee
511d74e80b34b546067a9fce6e796ab7
309d37788428294f735761b93f25d35c
8990a31267bc8a341b55b8ea00a3da01
ea36f4785bab8446681286d4ef42e71e
7055f57a7ec3f27fe84f713fdb83c5c2
25350aef71214b454d6422b5bb195e72
53d4ca0eda59230dadf63ab469dcbb27
4f597b6881a1fcab667613c71e2c752a
2e8ef7be45982f7992e5d92620699558
c5e30f8489512ca762cbe14b46d8bdbe
5dafd10f4696da6f20da9fb83f1d9f1a
d68c4bb63568b1fae8a1906dc7c0bf0b
18fdd263a63ca667721fdb2273987206
-----END OpenVPN Static key V1-----

**Comment by mwoolweaver** [comment]
fixed the issue by installing [asus-merlin](https://github.com/RMerl/asuswrt-merlin). As this was, from what I can tell, an issue with the default asuswrt firmware.
