### ISSUE TITLE
A handful of little things

### ISSUE THREAD

**Issue by Roger-Shepherd** [pivpn/pivpn#71]
I think you've done a great job with the script, it's taken most of the work out of setting up VPN on the Pi. I have previous run VPN on the Pi but decided to move over to a brand new Pi as my host machine. I came across pivpn when search for instructions. I have had a number of problems, most of which seem to be DNS related, but that is a not what this post is about. Because of the issues I was having, I went though the installation a couple of times, and on the second noted a few details that caused issues.
1. Some of the terms used in the dialogues aren't completely clear. For example, when the dialogue talks about "user" name it wasn't clear to me that this was the username of the Pi user who was setting up the VPN, and that the name was needed so that the .ovpn file could be written somewhere easy to get to. First time round I ended up using Pi rather than my username.
2. It wasn't clear that the certificate related password was (i) certificate related, and (ii) would be needed to unlock the information in the .ovpn file. First time round I used my password for the Pi rather than a new one.
3. I may be wrong, but my reading (in the OpenVPN documentation) of what "server 10.8.0.0 255.255.255.0" does is that it implicitly does the next two items in the .ovpn file. I've seen other "how to guides" which also have those following lines so I may be wrong.
4. The script seems to be generating the wrong line for "your local subnet". The script produces (for me) 

push "route 10.0.117.24 255.255.255.0"

which generates a warning in the client's log. I believe it should be 

push "route 10.0.117.0 255.255.255.0"
1. If the user fails to enter a second DNS server, the script generates an ill-formed push 

push "dhcp-option DNS "

which generates a warning in the client log.

**Comment by eelstretching** [comment]
Fixing the same thing as 4 in my server config led to connecting with no warnings, when I was previously getting warnings about not being able to set routes.

I'm successfully connecting, but I still can't get out to the Web from the VPN'd machine. I can do name resolution, though, which seems weird.

**Comment by 0-kaladin** [comment]
next time I i'm modifying for updates I'll address these.

**Comment by 0-kaladin** [comment]
I believe 1. and 2. above have been modified and are pretty clear.  
3. I don't understand.
4. and 5.(1.) fixed with commit referenced here.
