### ISSUE TITLE
Connection timeout

### ISSUE THREAD

**Issue by silvioto** [pivpn/pivpn#712]
# PiVPN Issue Template

## Issue
Connecting from network manager I receive this error after about 30 seconds:
The VPN connection "myvpn" failed because the connection attempt timed out.
- PI 3 model B
- modem router Fritz!Box 3390
- wired connection
- networkmanager 1.4.4 don't import the client file generated; I followed this guide to import: https://askubuntu.com/questions/134918/setting-vpn-client

## Have you searched for similar issues and solutions?
    yes

## Console output of `curl -L install.pivpn.io | bash`
```
sudo will be used for the install.
Cancel selected. Exiting
```

## Console output of `pivpn add` or `pivpn add nopass`
```
Enter a name for the client
```

## Console output of `pivpn debug`
```
https://pastebin.com/DaeAu41x
```

## Console Output of `sudo iptables -t nat -S`
```
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT
-A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE
```

## Console Output of `sudo iptables -S`
```
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
```

## output of `sudo netstat -uanp | grep openvpn`

```
udp        0      0 0.0.0.0:1194            0.0.0.0:*                           301/openvpn  
```

## Have you taken any steps towards solving your issue?
 I see in deep the router and port configuration, and it "seems" ok...

**Comment by Giraffe1966** [comment]
Are you on the same network as the pi?

**Comment by silvioto** [comment]
Yes:
pi - 192.168.178.135
router: 192.168.178.1
client: 192.168.178.25

**Comment by Giraffe1966** [comment]
Your router likely doesn't support NAT loopback, so you will have to make sure port forwarding is set up properly and connect from a different network.

**Comment by silvioto** [comment]
Maybe this configuration?
pi - 192.168.**128**.XXX
router: 192.168.178.XXX
client: 192.168.178.XXX

**Comment by 4s3ti** [comment]
@silvioto you should not connect to a vpn from the same network where it is being served, its pointless and useless. 

VPN purpose is to allow secure connections to remote networks over insecure networks ( for example the internet). 

For testing purposes consider using mobile data to test if everything is working. 

As this seems not to be entirely related with PiVPN itself, i will be closing this issue. 
if you still require community help please consider taking this over to [r/pivpn](https://github.com/pivpn/pivpn/issues/236)

Kind Regards.
