### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by Giraffe1966** [pivpn/pivpn#717]
I think we should have a better versioning system that tests commits before they are put into stable releases. The current versioning system doesn't have a whole lot of testing, and with the merger of #705, it appears there have been consequences. Here is what I propose: 
- test/develop branch - where all new code is merged. 
- master branch - more stable than the test branch, and this is where test is merged
- releases - use [releases](https://github.com/pivpn/pivpn/releases) for all stable code (releases are made from tested master commits). This is where the installer will download the files (when not in testing mode), and where the stable version of the installer resides

And, as suggested in #270, we really should have some infrastructure to automatically test new commits.

Any suggestions would be appreciated.

**Comment by 4s3ti** [comment]
@Giraffe1966 completely agree with you... lets take all of this into #270 ... I will try to go over this and get something up to help us with that task after cleaning the repo! =)
