### ISSUE TITLE
Installation step "Choose a user" displays users only uid >1000

### ISSUE THREAD

**Issue by 74cmonty** [pivpn/pivpn#719]
# PiVPN Issue Template

## Issue
Running pivpn installation assistant allows me to select a user for storing pivpn configuration. However the list includes users only with uid > 1000.
In my opinion this is a restriction that should be removed.
I defined a user account "pivpn" with uid < 1000 because I disabled login for this user; this is the relevant line in _/etc/passwd_:
```
pivpn:x:998:994::/home/pivpn:/usr/sbin/nologin
```

## Have you searched for similar issues and solutions?
    (yes/no / which issues?)
yes

## Have you taken any steps towards solving your issue?

I have used this workaround:

1. Create user "pivpn" with uid > 1000
2. Completed pivpn installation
3. Modify user "pivpn" to have uid < 1000 and gid < 1000

**Comment by orazioedoardo** [comment]
In the past pivpn looked for user with uid > 500 but i changed that to prevent system users like “pihole” that have no home folder o show up. However, this could be changed to show system users if they have an home folder.

**Comment by 74cmonty** [comment]
Actually I have installed pihole before.
If one concludes that every user having a home-directory must get uid > 1000 this check is fine.
However I prefer to have a user "pivpn" that is kind of system user, means I cannot login with this user and, in my understanding, I don't need to login.

As far as I can see in _/home/<pivpn-user>/_ directory only the profiles of created accounts are stored.

My proposal would be to create a system user "pivpn" and store the profiles in another directory, e.g. _/opt/pivpn/_.

**Comment by orazioedoardo** [comment]
So if we store profiles inside another directory, why should we create “pivpn” user?

**Comment by 74cmonty** [comment]
Fair question... 
I assumed that this user is required to run the application.
There are multiple dirs that belong to this user, e.g.
```
/opt/pivpn
/usr/local/bin/node
/usr/local/include/node
/home/pivpn
```

**Comment by orazioedoardo** [comment]
Sorry, what does node have to do with pivpn/openvpn?

**Comment by 74cmonty** [comment]
I didn't validate this.
I just searched for dirs belonging to user pivpn.

In my opinion user pivpn should be a system user and the storage location of profiles should be defined accordingly.
E.g. netdata defines a directory _/var/lib/netdata_ for its system user _netdata_.

**Comment by 4s3ti** [comment]
Let's keep things simple, here is the issue related to this: here https://github.com/pivpn/pivpn/issues/377

@orazioedoardo change to look for users with uid > 1000 is the correct approach as linux by default and as a good practice ... 

system users < 1000
regular users > 1000

system users typically don't have a home dir and should not have a home dir ... obviously, there are some exceptions but should be avoided and not mixed with regular useres home dirs 

There is no need to create a pivpn user, as nothing runs as pivpn, pivpn is just an Installer! 

we need to better handle that, I personally don't like the idea of having it stored in a user home directory. 

Having this said i will be closing this issue, so we can keep things clean. 
for further discussion regarding this topic please use the issue i mentioned above.
