### ISSUE TITLE
OpenVPN client on Android offers: LZO Compression - Is this supported?

### ISSUE THREAD

**Issue by 74cmonty** [pivpn/pivpn#720]
# Question

The OpenVPN client on Android offers: LZO Compression

Is this compression supported / enabled / recommended for PiVPN?
Or are the HW resources of Raspi insufficient for this compression?

**Comment by Giraffe1966** [comment]
Compression has been intentionally disabled because of the [VORACLE attack](https://community.openvpn.net/openvpn/wiki/VORACLE).
