### ISSUE TITLE
Re-Open#542: Unable to connect from Kubuntu 18.04

### ISSUE THREAD

**Issue by devZer0** [pivpn/pivpn#721]
i'm hereby reopening #542 as kubuntu is a major distro and kde a major desktop environment. 

as the kde bugticket shows this also applies to archlinux (and maybe other kde based distros).

so, if pivpn enables "secure settings" by default and settings cannot be modified during installation appropriately - there should be at least a warning that you cannot use pivpn .ovpn files with kde network manager.

the problem exists for nearly a year and it is NOT fixed (as you cannot select non tls-crypt for pivpn in install script)

so, it's at least a documentation bug.

https://bugs.kde.org/show_bug.cgi?id=395596
https://github.com/pivpn/pivpn/issues/542

**Comment by devZer0** [comment]
major annoyance!

**Comment by NilsGriebner** [comment]
Please fix!

**Comment by 4s3ti** [comment]
What's your suggestion for a fix here @devZer0 ?

**Comment by stecue** [comment]
It is not the fault of _pivpn_. I have the same problem on OpenSUSE KDE5 and I have to import the .ovpn file using command line (not the plasma applet). Actually the command line is very simple:
`sudo nmcli connection import type openvpn file your_vpn.ovpn`
where `your_vpn.ovpn` is the .ovpn file generated by _pivpn_. Maybe _pivpn_ should display a warning message after installation.

**Comment by 4s3ti** [comment]
not pivpn related. tagged as information. 
resolving.
