### ISSUE TITLE
Back to active ... lets clean the house? 

### ISSUE THREAD

**Issue by 4s3ti** [pivpn/pivpn#723]
Ok guys .. @0-kaladin @james-lasersoft @redfast00  ... 
And more active contributers ... 

Ill be slowly coming back to active and supporting this amazing project... 
this project clearly got a whole lot of visibility and fasts growth, and i believe there are a couple of things we should endorse

First and foremost, We need to better highlight users that PiVPN is a Tool (or Installer) that installs openVPN with pre-configured standard settings and not a full fleged VPN software. 

with the advent of privacy (pseudo) paranoia, everyone wants a VPN without even realize what that really implies or understanding the basic concept of VPN Server! 

for this topic i will work in some possible Use cases and scenarios, and to get them placed somewhere where ppl can really read and learn about what a VPN is and if they really need it or not! 

Also, There are a lot of issues here that are not *AT ALL* Related with pivpn code .. this needs to end .. because we end up loosing more time providing IT Support than fixing and improving this tool!

Here i ask you guys for opinion and help ... What you think we should use to drive people away from github with that kind of issues? 

I'd suggest creating more comunity driven like a subredit for PiVPN where users can go and post their use cases, ask for help and so on .. in similarity of what happens with pi-hole, what you think? 
Unfortunately i don't have Enough karma for that as i am not a reddit poster, more of a reader! 
If you have a better solution... Be aware i am more than glad to host any kind of forum or other platform on my servers! 

At last but no the least ... The issues tab needs a big cleanup.. and once we get to a solution to drive users away with "IT Support" issues ill be closing and driving users away to the new "general Support" area! 

Then ill focus again on more code and fixing issues. 

What you think? Any Suggestions?

**Comment by quwip10** [comment]
I agree with this. The issues section has become almost entirely a support section rather than a bug report. It would be good to have another resource for users seeking help. We could even have a tutorial and FAQ already posted. We could use reddit or we could create a Wiki for it.

**Comment by devZer0** [comment]
yes, please.  github bugtracker shouldn't be abused as a user-support tool. please open up some forum or mailing list. even some chat/freenode via web would be better then the current method

**Comment by mwoolweaver** [comment]
there's actually already a sub reddit with the PiVPN name 

https://www.reddit.com/r/pivpn/

not sure who has control of it tho

**Comment by 4s3ti** [comment]
Cool, for some reason i couldn't find that redit ... 
does anyone knows the owner of that subredit? 
is IAintShootinMister around? =p 
maybe that will need bit more mods overthere

**Comment by boelle** [comment]
i discovered pivpn just yesterday and yes a dedicated forum of some sorts would be nice since i have more advanced questions

so reddit is the place so far? discord could also be a place since it allows text chat (ie not limited to voice chat)

**Comment by boelle** [comment]
@4s3ti you need people here that can drive people with support questions toward another platform?

**Comment by 4s3ti** [comment]
@boelle i think the place to go should definitely be reddit. 
but for now need to find who owns that subredit so we can throw more mods there .. 
then ill start drive ppl and non code related issues there.

**Comment by boelle** [comment]
hehe, no problem with that :-D

i just thought that discord could be an alternative to reddit should contact to owner fail

i tried to contact you on twitter but for some reason i could not send a DM

**Comment by 4s3ti** [comment]
@boelle discord is also a good option .. but lets stick with reddit for now and lets see where it leads us.

**Comment by boelle** [comment]
you need people here to guide people with support Q's to reddit? i'm home going so i have plenty of time to put on labels and close issues that are not bugs

**Comment by justinamcafee** [comment]
@4s3ti , 

For several reasons, I've made you a partial mod there. You have the ability to do everything except for add moderators or remove them, and by proxy, me.

As you have no karma and I have no way of verifying that you are the same 4s3ti who controls the github account, I'll be leaving it this way until my suspicions are satisfied.

I am a huge fan of the pihole project and have made great use of it over the years. The safety and privacy of the pivpn community is of the utmost importance to me.

I hope you can understand and respect my reservations,
- IAintShootinMister 

Additionally, I am excited to see this project be cared for again and hope to contribute where possible. If that's from assisting with the subreddit, I'll serve diligently.

**Comment by 4s3ti** [comment]
Hi @justinamcafee yes it was me indeed, yes the account was freshly created for this sole purpose.
Thank you for your fast action and for being carefull!! =D 

I appreciate your reservations and I can go with that and i really appreciate your caution!

we could use a couple more of mods Ill throw some names here please reach out to @justinamcafee ... if you all agree and want to assist with this one. 

@james-lasersoft as the new "owner"
@0-kaladin @redfast00 

and some of the most active useres that kept the boat floating ... 
 @orazioedoardo @Giraffe1966 @devZer0 


@boelle I really appreciate your offer and help! however i can't grant you any previleges and at this stage we don't really know you elevate your privileges here, so ill still be trusting in our most active users that kept the boat floating! in our absence.

**Comment by boelle** [comment]
no problemo

and yes github does not allow granular control, its either full access or not

there is no way to give a user rights to only open and close isses and do labels, i have tried that on the marlin firmware project and github said directly it cant be done

**Comment by justinamcafee** [comment]
@4s3ti  Sounds good, also, as a welcome back, you might place together a few sentences for the subreddit, and we'll pin it to the top noting that its: 
- an actively maintained support forum
- an actively maintained project 
- determine  some form of template for reporting within the subreddit
<hr>
Additionally, since this is a refresh, might I bend your ear and suggest the wireguard protocol? If we could leverage the simplicity of pivpn, I think the future road map could include conversion from openvpn to the wireguard vpn with a *substantial* increase in throughput, security, and simplicity. 

I began using the wireguard service in pivpn's absence and have had amazing results.

**Comment by boelle** [comment]
oh... thought/idea just came in my head

since the script makes it VERY easy to setup a server, could there be a script that makes setting up the client side of things? there might be but them i'm blind :-D

**Comment by justinamcafee** [comment]
@boelle  Client side scripts are unnecessary as of now, it's as simple as 
- install client
- click certificate 

As its done through a gui, I'm not sure of a use case. And while server installs can be standardized to a point, client installs would need to cover, the iOS app, the macOS app, the Windows app, the Linux network manager, and the android app.

**Comment by boelle** [comment]
oh i was thinking on the pi only, and it might be simple once you know how to do it

but from CLI how could it be done? and i mention CLI as i intend to use a headless pi with a 4g dongle as the client "out in the field"

**Comment by 4s3ti** [comment]
I don't see a real bennefit of a client side config to be honest! 
about the wireguard ... might be a good adition indeed! 
however for now i'de like to focus in getting the house and the code clean, fix some bugs that might be around get back on track to then focus on growth and expanding new features ... might sound a bit conservative ... but at this time i consider to be the best approach ... but suggestions are always welcome!

**Comment by james-lasersoft** [comment]
I personally have a standard method of installing on my clients. Most of my users are headless servers so I move the client ovpn file to an ftp server and copy/paste a quick script that installs OpenVPN, ftp's the ovpn file (keyed from the hostname) and starts everything running. 

I also use pivpn-gui for management. This makes everything really simple.

I will look at that reddit feed and see what can be done to push user issues over there to clean some things up.

**Comment by boelle** [comment]
the one benefit from a install script for the client side is that it makes it dead simple

and the more simple things are the more users it will attract, and also it will reduce the number of questions etc as people just run a script and it takes care of the rest

i had big doubts on getting the server side to run as i have tried it before with guides and manual entry of commands, but the pivpn install script made it dead easy and i had server tested and running in 30 mins or so

and its just my guess but i guess most supports Q's are related to how to set things up etc etc

but again its just my 0.02$ worth of thoughts

**Comment by boelle** [comment]
@james-lasersoft would you mind sharing how you do it?

**Comment by boelle** [comment]
@james-lasersoft 

thanks :-D

i might take bits of it as i do not have a monitor hooked up to either server or client

and i guess the gui is for linux only?

**Comment by james-lasersoft** [comment]
@boelle 
I do all this through SSH as the VPN server is headless and clients are installed elsewhere. 

The GUI is web based so no worries. Makes PiVPN really simple to use. Look for OpenRSD here on GitHub.

**Comment by boelle** [comment]
@james-lasersoft nice :-D

seems that this "crazy" project of mine will see the light of day anyway
not sure if i mentioned it, but its going to be an a remote controlled rc car(parcel delivery robot thing) just to keep me busy and sane

**Comment by boelle** [comment]
@james-lasersoft Q: the ca.crt is in /etc/openvpn/easy-rsa/x509-types right? its the only directory where i can see a file named ca, but it does not have the crt extension

but i did manage to make the file with fixed ip on the server in /etc/openvpn/ccd/4grover

i assume the config file is the ovpn file with extension renamed to conf? i'm at the #download config file and ca.crt step right now

**Comment by james-lasersoft** [comment]
The certs are included in the ovpn file.

James Arnold
Lasersoft

**Comment by boelle** [comment]
so basicly i just copy the ovpn to /etc/openvpn/ but change the extension to .conf
and then run this: openvpn --config /etc/openvpn/4grover.conf --daemon  ?

**Comment by boelle** [comment]
how do i check if the client has opened a connection?

**Comment by james-lasersoft** [comment]
Correct. Then give the ifconfig command and you will see the tunnel.

James Arnold
Lasersoft

**Comment by boelle** [comment]
:-( no luck

i think its this part that screwed up

#create an ovpn file without password on the client cert and all will be well

how do i do that?

**Comment by boelle** [comment]
i do see a tunnel on the server, but not on the client

**Comment by boelle** [comment]
just to sum it up, after i tested the server last night with phone and the openvpn app i have done this on server:

created a file in /etc/openvpn/ccd called 4grover (no extension) with this line in it:

ifconfig-push 10.8.0.3 255.255.255.0

then i copied the 4grover.ovpn from server to client /etc/openvpn but as 4grover.conf

then on client i run the command: openvpn --config /etc/openvpn/4grover.conf --daemon

**Comment by james-lasersoft** [comment]
All looks correct. When you created the client config did you give it a
password?

James Arnold
Lasersoft

**Comment by boelle** [comment]
no, i do not know how to create one

but the ovpn file i created last night and copied to my phone is with password of course, and its the same file i copied to the client but with .conf extension instead

**Comment by boelle** [comment]
what might confuse me here is this:

#create an ovpn file without password on the client cert and all will be well

the on the client cert....

does this mean the pivpn add command ?? and that i should have done pivpn add nopass instead when i created the ovpn file?

**Comment by james-lasersoft** [comment]
Exactly. Create the client co fig with the nopass option.

James Arnold
Lasersoft

**Comment by boelle** [comment]
i tried to revoke the ovpn on the server and create a new one without password

still no tunnel, is there a log i can dive in to and maybe figure what goes wrong

**Comment by boelle** [comment]
grep VPN /var/log/syslog

`Apr 24 20:53:00 raspberrypi openvpn[548]: OpenVPN 2.4.0 arm-unknown-linux-gnueabihf [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Oct 14 2018
Apr 24 20:53:24 raspberrypi systemd[1]: Starting OpenVPN connection to 4grover...
Apr 24 20:53:24 raspberrypi ovpn-4grover[217]: OpenVPN 2.4.0 arm-unknown-linux-gnueabihf [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Oct 14 2018
Apr 24 20:53:25 raspberrypi systemd[1]: Started OpenVPN connection to 4grover.
Apr 24 20:53:35 raspberrypi systemd[1]: Starting OpenVPN service...
Apr 24 20:53:36 raspberrypi systemd[1]: Started OpenVPN service.
`

**Comment by boelle** [comment]
have tried to install OpenRSD to see if that makes things more easy, but i have an 403 error and need to sort that if going the OpenRSD

but i guess its something simple that prevents the client connecting the server, 

now i just fear that this turns in to a mile long support thing, which we should prevent in the first place

**Comment by thewriteway** [comment]
Good to see pivpn come back to life. Let me know if you need anymore volunteers for anything on this project?

**Comment by 4s3ti** [comment]
@thewriteway there is a lot to do ... there is a lot of issues ...
everyone that wants to support can help cleaning .. going through issues and seeing if there is activity on it or not,  .. if it is not Code related redirect it to Reddit, and tag me so I can close it for example. 
if you have the knowledge go through the code and fix any issues or excess code, I don't know .. just do it .. then the maintainers will give the final wording about it. 

that's how the opensource world works, we are a community we all can do something! =D 

having this said will start with this one .. closing this ... PiVPN redit is there for everyone to use! discussion, non-related code help etc etc... 

Have fun guys! =D and thanks for the warm welcome and for keeping the boat floating!
