### ISSUE TITLE
Not creating folders

### ISSUE THREAD

**Issue by Firemanjoe** [pivpn/pivpn#725]
Hello, 

I am wondering if anyone else is having issues with installing piVPN. My SD card crapped out on my yesterday & I've been trying to get it to install and it's simply not working. There are some instances where the certificate isn't generated (simply skips over it) or when I come to add a client, it is not creating the folder ovpns to be able to write the client profile to. I've completed a fresh install of Raspian Lite - dated April 2019. 

Please let me know what else I can try to help resolve this. 

Thanks!

**Comment by devZer0** [comment]
please do a fresh install and post the output of your installation log

**Comment by Firemanjoe** [comment]
where do I find the installation log? Just to make sure that I'm sending you the right information?

**Comment by devZer0** [comment]
just capture the output during installation like this one: https://github.com/pivpn/pivpn/issues/97

**Comment by Firemanjoe** [comment]
OK, this time, it worked as expected! I'm closing this ticket.
