### ISSUE TITLE
PIVPN Server with OpenWRT client router

### ISSUE THREAD

**Issue by guydeke** [pivpn/pivpn#73]
First of all, I'm not a native English speaking person so apologies for my grammar. 
This post is maybe to basic for most of the people who read it, but I made a network configuration with a PiVPN Raspberry B and a TP-Link router and I would share that with people who maybe also need one. Reason for that is that I wanted to use my Dutch tv application on Android in foreign country's at holidays and so. In the beginning I could use the tv application in combination with a VPN client like PIA. But after a few weeks it stopped after a application update. Watching tv using a web browser is still possible but I just bought a MXQ box (that's a wanna-bee-Apple-TV on Android) and on that box you need a web browser with Silverlight or the application from my tv distributor. And Silverlight with Android is not a match. Because the web browser tv watching worked on my Macbook, but on the MXQ box the application said "watching tv not possible" , I assumed that the application does a bit more then only streaming the tv signal and maybe detects traffic on known VPN ports or does some geo location detecting. Because why could I otherwise watch tv on my MacBook with the VPN client PIA from e.g. Germany and not with the MXQ box? So I tried fake locations app's on the MXQ box but all failed. And then I found out about PIVPN and made a configuration on a old Raspberry Pi that I bought on ebay for about 12 euro :) From now on I could make my own VPN connection's with my own VPN server, AWESOME!!! (for a newbee like me). I've watched the logfiles on it for a few days and saw a lot of hacking attempts on it so I also installed "fail2ban" on the PIVPN: http://www.fail2ban.org/ . The PIVPN also resorts in the DMZ of my router/modem.

On the MXQ box I used "OpenVPN Connect" app with the on the PIVPN created cert. 
Yep ........ but the tv app on the MXQ Box still did not buy it! .....grrrrrrrrr @#!!!!
So I looked for DNS leaks, could not find them and in my opinion (hey I'm not a pro) when you install the tv app you give it rights to your system and it sniffs for VPN traffic on the same client.
After thinking a while for a solution I took a router I had from TP-Link that was not in use at that moment. I flashed OpenWRT on it and used this manual from a guy that know's what he is doing, named  Logan Marchione (all credits for him AND the PIVPN team!): 

https://www.loganmarchione.com/2014/10/openwrt-with-openvpn-client-on-tp-link-tl-mr3020/

So I followed his "recipe" and now I have a embedded OpenWRT router with OpenVPN client.
But then I had another problem, how do you get the password check for your ovpn cert automated, without logging in your OpenWRT with Putty and do it manually every time. Because the "auth-user-pass" files are for a username AND password. So I experimented a bit with using the password twice in the authuser file, or leave a blank line for the username, but no effort. So I made a [nopass] cert on the PIVPN and it worked :)
Getting the cert in the OpenWRT router was not easy at first, but then I put it in the Public area of my dropbox and used a "wget --no-check-certificate" with a link to the file, and it worked 💃 

After uninstalling all the rubbish from the MXQ box I can watch tv now with it because the tv app can not detect there is some kind of VPN tunnel, since the tunnel setup is somewhere between the LAN and the WAN on the OpenWRT router and not on the same client as the tv application :)
I would like to share this solution with people who have a same kind of issue, for them I made this post so I hope it is not to basic or off-topic here. 

I've added a picture I made with a scheme of my VPN network, hope you guys like it :)

<img width="794" alt="screen shot 2016-08-21 at 09 22 12" src="https://cloud.githubusercontent.com/assets/21152718/17836006/6689823c-6784-11e6-9fe7-f19faba87fe0.png">

**Comment by Landero** [comment]
Great. Thanks for sharing! Will give it a shot and get back to you. Setup is nearly the same but in a Belgian-Spanish connection.
