### ISSUE TITLE
Not all ports runing trough VPN tunnel

### ISSUE THREAD

**Issue by 19marc85** [pivpn/pivpn#743]
Hi there 

In my case the VPN connection is working correctly but I have an specific program that uses following ports:

80, 2025, 2113, 4110, 4310, 14124, 50001, 50002, 50003

If I do run trough the VPN tunnel only following ports are routed:

80, 50001, 50002, 50003

**Comment by devZer0** [comment]
imho, that's not possible, as "routing" in pivpn/openvpn is not about ports. so it must be something which is not pivpn/openvpn related. check firewall or whatever else...
