### ISSUE TITLE
Cannot connect to OpenVPN with PiVPN server on R-pi

### ISSUE THREAD

**Issue by spote210** [pivpn/pivpn#745]
Hey 4s3ti,

I am trying for my laptop to connect the VPN server from Raspberry Pi 3 model created using PiVPN. I am able to connect it once I replace the IP in .opvn file with Pi's IP address. The error I am getting in OpenVPN GUI is ::

_Thu May 16 16:37:11 2019 TCP: connect to [AF_INET]182.74.185.114:4430 failed: Unknown error
Thu May 16 16:37:11 2019 SIGUSR1[connection failed(soft),init_instance] received, process restarting
Thu May 16 16:37:11 2019 MANAGEMENT: >STATE:1558004831,RECONNECTING,init_instance,,,,,
Thu May 16 16:37:11 2019 Restart pause, 300 second(s)
Thu May 16 16:42:11 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]182.74.185.114:4430
Thu May 16 16:42:11 2019 Socket Buffers: R=[65536->65536] S=[65536->65536]
Thu May 16 16:42:11 2019 Attempting to establish TCP connection with [AF_INET]182.74.185.114:4430 [nonblock]
Thu May 16 16:42:11 2019 MANAGEMENT: >STATE:1558005131,TCP_CONNECT,,,,,,
Thu May 16 16:44:11 2019 TCP: connect to [AF_INET]182.74.185.114:4430 failed: Unknown error_

Please help me with the issue.

**Comment by orazioedoardo** [comment]
You are supposed to fill the Issue template when reporting an issue.

**Comment by spote210** [comment]
> You are supposed to fill the Issue template when reporting an issue.

How to do that? new here...

**Comment by orazioedoardo** [comment]
When you click "new issue" you get the issue template in the body of the input box. It's [this one](https://github.com/pivpn/pivpn/blob/master/ISSUE_TEMPLATE.md).

**Comment by spote210** [comment]
> When you click "new issue" you get the issue template in the body of the input box. It's [this one](https://github.com/pivpn/pivpn/blob/master/ISSUE_TEMPLATE.md).

Yes...got it!! Also posted new issue.
Thanks for help.
