### ISSUE TITLE
ERROR: pivpn: command not found

### ISSUE THREAD

**Issue by OfficialMuffin** [pivpn/pivpn#747]
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

### Issue
I have installed PiVPN with no errors in the install. I cannot "sudo pivpn" as the Pi does not recognise that pivpn is installed. I cannot uninstall it for the same reason.

If I use the install script again, it recognises that there is an existing installation.

### Have you searched for similar issues and solutions?
    (yes/no / which issues?)
Yes, there are no issues the same as mine

### Console output of      `curl -L install.pivpn.io | bash`
```
  N/A Existing installation detected
```

### Console output of      `pivpn add` or `pivpn add nopass`
```
  -bash: pivpn: command not found
```

### Console output of      `pivpn debug`
```
  -bash: pivpn: command not found
```
### Have you taken any steps towards solving your issue?
```
  sudo apt remove pivpn
  sudo apt purge pivpn

still get the error "-bash: pivpn: command not found"
```

**Comment by orazioedoardo** [comment]
Try [this](https://github.com/pivpn/pivpn/issues/673#issuecomment-457809053)
