### ISSUE TITLE
Question - do I need to have static IP to use this?

### ISSUE THREAD

**Issue by zulhfreelancer** [pivpn/pivpn#748]
Hi,

This is not related to bugs. I'm new here and I want to ask a question. Do I need to have static IP for my home internet if I want to use this pivpn and access my Raspberry Pi from outside?

Thank you.

**Comment by 4s3ti** [comment]
Hi, thank you for your interest, Non bug/code related issues should be posted at https://www.reddit.com/r/pivpn

Regarding your question, the answer is here: 

https://github.com/pivpn/pivpn/wiki/FAQ#my-isp-doesnt-give-me-a-static-external-ip-address-so-my-servers-ip-address-keeps-changing

and here

https://github.com/pivpn/pivpn/wiki#setting-up-static-ip-for-clients


Next time please read all the documentation before asking, that's a great way to help the project to help as we can better use our free time for other stuff! =) 


Once again thank you for your interest in PiVPN.
Closing the issue. 
Kind Regards.
