### ISSUE TITLE
Create certificates for Grandstream Phones

### ISSUE THREAD

**Issue by lucaslena** [pivpn/pivpn#749]
I would like to use PiVop for remote sip extensions.
Already use with grandstream Router or FreePbx vpn.

I try to create files .ca and key files form de .ovpn but i cant connect.

This is the sreenshot form GS phone [image](https://vitalpbx.org/wp-content/uploads/2018/07/openvpngrandstream.png)

There is a config instrucction for  [Grandstream Router](http://www.grandstream.com/sites/default/files/Resources/openvpn_site-to-site.pdf)

this is a example for crt file created with GS Router

```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 2 (0x2)
    Signature Algorithm: sha1WithRSAEncryption
        Issuer: C=US, ST=MIAMI, L=FLORIDA, O=GRANDSTREAM, OU=SOPORTE, CN=OpenVPN/emailAddress=GRANDSTREAM@GRANDSTREAM.COM
        Validity
            Not Before: Mar  7 21:13:13 2018 GMT
            Not After : Mar  7 21:13:13 2019 GMT
        Subject: C=US, ST=MIAMI, L=FLORIDA, O=GRANDSTREAM, CN=GXP1625-1/emailAddress=GRANDSTREAM@GRANDSTREAM.COM
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (512 bit)
                Modulus:
                       REDACTED
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Basic Constraints: 
                CA:FALSE
            X509v3 Subject Key Identifier: 
                REDACTED
            X509v3 Authority Key Identifier: 
                REDACTED                DirName:/C=US/ST=MIAMI/L=FLORIDA/O=GRANDSTREAM/OU=SOPORTE/CN=OpenVPN/emailAddress=GRANDSTREAM@GRANDSTREAM.COM
                serial:D1:C0:2D:FD:0B:E1:72:85

            X509v3 Extended Key Usage: 
                TLS Web Client Authentication
            X509v3 Key Usage: 
                Digital Signature
    Signature Algorithm: sha1WithRSAEncryption
                      REDACTED
-----BEGIN CERTIFICATE-----
REDACTED
-----END CERTIFICATE-----
```
![openvpngrandstream](https://user-images.githubusercontent.com/27502631/57985767-c9922200-7a3a-11e9-9c20-96746c2336b9.png)

Any help to create this connection?

**Comment by 4s3ti** [comment]
I have redacted your post, Please *NEVER* post Certificate data in a public forum/website, 
Please generate a new one and don't use the one you have just posted. 

This is not PiVPN Related at all ... 
Remember PiVPN is just an OpenVPN Installer. 
GitHub is meant for code related issues, please take the discussion over to our subreddit [r/pivpn](https://www.reddit.com/r/pivpn) 

If you want to use other type of devices with OpenVPN, all you need is properly identified inside the .OVPN file.


CA Cert: 
```
<ca>
-----BEGIN CERTIFICATE-----

-----END CERTIFICATE-----
</ca>
```
Certificate: 

```<cert>
-----BEGIN CERTIFICATE-----

-----END CERTIFICATE-----
</cert>
```
key: 
```
<key>
-----BEGIN RSA PRIVATE KEY-----

-----END RSA PRIVATE KEY-----
</key>
```

you should take that data out, and put each on in its own file, example: 
( copy everything within those parameters including, for example the <ca></ca> )

cacert.ca
ovpncert.cert
privkey,key

About the username and password is something i don't really know ... 
i'd suggest creating certificates with --nopass flag and leave it blank in the settings.

hope this helps.
as this is not entirely
