### ISSUE TITLE
Options for TCP instead of UDP

### ISSUE THREAD

**Issue by JonJon2** [pivpn/pivpn#75]
The script is great & has saved many hours of work.
My only issue is that it only asks which port you want to use (and not whether it is TCP or UDP).
As a result, every ovpn I create, I then need to modify to "proto tcp" to allow it to connect.

Maybe this could be added to a future release?

**Comment by sithsiri** [comment]
Or at least a switch in the pivpn command that let's you change between UDP and TCP?

**Comment by trikst3r** [comment]
Option like this would be most useful for noobs like me. I spent a lot of time trying to do it manually.

**Comment by guydeke** [comment]
Why should you change between UDP and TCP for a VPN tunnel? UDP give better performance

**Comment by 0-kaladin** [comment]
I'll add this as an option but the reason I left it out is because UDP is a LOT better for a tunnel.  I didn't want "noobs" just picking TCP cause they think it is better for some reason.  When I add it, I'll put a warning on choosing TCP and state I recommend against it unless you know what you are doing.

**Comment by ThuYein** [comment]
I had trouble connecting, after i change the server.conf to TCP. Couldn't connect, so I regenerated the ovpn profile. But figured out that the ovpn profile still says `proto udp`. It would be great if pivpn can detect the proto automatically from server.conf and generate appropiate ovpn. This script is really great. Thanks for saving me hours of work.

**Comment by redfast00** [comment]
@0-kaladin: are you currently working on this? If not, please ping me and I'll add it. Thanks! :smiley:
