### ISSUE TITLE
iptables v1.8.1 syntax on Buster

### ISSUE THREAD

**Issue by PnjDbq** [pivpn/pivpn#751]
First up, I'm using packages from Buster.

cat /etc/os-release
```
PRETTY_NAME="Raspbian GNU/Linux buster/sid"
NAME="Raspbian GNU/Linux"
ID=raspbian
ID_LIKE=debian
```

I performed an uninstall / reinstall of PiVPN.  Was having issues accessing the outside world so I ran `pivpn debug`:

```
:: [ERR] Iptables MASQUERADE rule is not set, attempt fix now? [Y/n] y
iptables: Operation not supported.
iptables v1.8.2 (nf_tables): Chain 'MASQUERADE' does not exist
Try `iptables -h' or 'iptables --help' for more information.
```
Pretty quickly realized there is a syntax issue in the script preventing the masquerade rule from applying.  Poked around and found the solution.

Ran
`update-alternatives --config iptables`
selected the legacy version.  Re-ran the debug command and the script was able to auto-fix.

Problem solved.

Wanted to give the dev team a heads-up that this is on the horizon.

**Comment by 4s3ti** [comment]
Thanks for the headsup .. added some tags for further investigation.

**Comment by xia0u** [comment]
Same issue on raspbian buster with iptables 1.8.2-4

**Comment by 4s3ti** [comment]
Guess this is probably fixed. resolving.  

Reopen if its stilla thing.

**Comment by nicktheone** [comment]
Having this issue too. iptables is already set in legacy mode but the script is unable to auto-fix.

`::::            Self check               ::::
:: [OK] IP forwarding is enabled
:: [ERR] Iptables MASQUERADE rule is not set, attempt fix now? [Y/n] y
iptables v1.8.2 (legacy): invalid mask `' specified
Try `iptables -h' or 'iptables --help' for more information.
Done
:: [OK] WireGuard is running
:: [OK] WireGuard is enabled (it will automatically start on reboot)
:: [OK] WireGuard is listening on port 51820/
[INFO] Run pivpn -d again to see if we detect issues`

**Comment by 7system7** [comment]
Have the same problem.
