### ISSUE TITLE
-d option inconsistency

### ISSUE THREAD

**Issue by devZer0** [pivpn/pivpn#754]
there is insonsistency in the "-d" param within /opt/pivpn/makeOVPN.sh and /usr/local/bin/pivpn

by default, expiration time is interactively queried instead so -d option is mandatory when using pivpn in scripted mode

/opt/pivpn/makeOVPN.sh

helpFunc() {
    echo "::: Create a client ovpn profile, optional nopass"
    echo ":::"
    echo "::: Usage: pivpn <-a|add> [-n|--name <arg>] [-p|--password <arg>]|[nopass] [-d|--days <number>] [-h|--help]"
    echo ":::"
    echo "::: Commands:"
    echo ":::  [none]               Interactive mode"
    echo ":::  nopass               Create a client without a password"
    echo ":::  -d,--days            Expire the certificate after specified number of days (default: 1080)"
    echo ":::  -n,--name            Name for the Client (default: '"$(hostname)"')"
    echo ":::  -p,--password        Password for the Client (no default)"
    echo ":::  -h,--help            Show this help dialog"
}

/usr/local/bin/pivpn

# pivpn -h
::: Control all PiVPN specific functions!
:::
::: Usage: pivpn <command> [option]
:::
::: Commands:
:::  -a, add [nopass]     Create a client ovpn profile, optional nopass
:::  -c, clients          List any connected clients to the server
:::  -d, debug            Start a debugging session if having trouble
:::  -l, list             List all valid and revoked certificates
:::  -r, revoke           Revoke a client ovpn profile
:::  -h, help             Show this help dialog
:::  -u, uninstall        Uninstall PiVPN from your system!

function helpFunc {
    echo "::: Control all PiVPN specific functions!"
    echo ":::"
    echo "::: Usage: pivpn <command> [option]"
    echo ":::"
    echo "::: Commands:"
    echo ":::  -a, add [nopass]     Create a client ovpn profile, optional nopass"
    echo ":::  -c, clients          List any connected clients to the server"
    echo ":::  -d, debug            Start a debugging session if having trouble"
    echo ":::  -l, list             List all valid and revoked certificates"
    echo ":::  -r, revoke           Revoke a client ovpn profile"
    echo ":::  -h, help             Show this help dialog"
    echo ":::  -u, uninstall        Uninstall PiVPN from your system!"
    exit 1
}

**Comment by orazioedoardo** [comment]
Probably you want the script to just use the default number of days when creating non interactively, however I made the script ask the expiration date bey default to make the user aware that the feature is there.

**Comment by devZer0** [comment]
yes, but pivpn is also telling wrong meaning of -d , as there is "-d debug" and "-d days" - so everybody needs to guess how it's being used non-interactively

**Comment by orazioedoardo** [comment]
Good point but to use -d as days you need to prepend -a

**Comment by devZer0** [comment]
and how do i get to that information if "pivpn -h" does not tell it ?

**Comment by orazioedoardo** [comment]
> and how do i get to that information if "pivpn -h" does not tell it ?

`pivpn -a -h`

**Comment by 4s3ti** [comment]
closing this thread as both flags are used in different scripts with different objectives ... 

pivpn -d  its for debug 
pivpn -a -d its for days and not related.
