### ISSUE TITLE
No internet Access over VPN

### ISSUE THREAD

**Issue by Metiiin** [pivpn/pivpn#757]
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

The VPN connects no problem. However I lost internet access when connected. I checked similar problems and none of the solutions worked. I am using Pi-Hole as well.
https://pastebin.com/GZJjfaig

> rulesv4:
> Generated by iptables-save v1.6.0 on Wed May 29 11:00:49 2019
> *nat
> :PREROUTING ACCEPT [0:0]
> :INPUT ACCEPT [0:0]
> :OUTPUT ACCEPT [0:0]
> :POSTROUTING ACCEPT [0:0]
> -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE
> -A POSTROUTING -s 10.8.0.0/24 ! -d 10.8.0.0/24 -j SNAT --to-source 10.8.0.1
> COMMIT
> Completed on Wed May 29 11:00:49 2019
> Generated by iptables-save v1.6.0 on Wed May 29 11:00:49 2019
> *filter
> :INPUT ACCEPT [27663:5114078]
> :FORWARD ACCEPT [0:0]
> :OUTPUT ACCEPT [17466:18178606]
> -A INPUT -p udp -m udp --dport 1194 -j ACCEPT
> -A FORWARD -s 10.8.0.0/24 -j ACCEPT
> -A FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
> COMMIT
> Completed on Wed May 29 11:00:49 2019
> 

```
server.conf: 

_> dev tun
> proto udp
> port 31415
> ca /etc/openvpn/easy-rsa/pki/ca.crt
> cert /etc/openvpn/easy-rsa/pki/issued/server_MTdWABnaYNGe03bR.crt
> key /etc/openvpn/easy-rsa/pki/private/server_MTdWABnaYNGe03bR.key
> dh none
> topology subnet
> server 10.8.0.0 255.255.255.0
> Set your primary domain name server address for clients
> push "dhcp-option DNS 8.8.8.8"
> push "dhcp-option DNS 8.8.4.4"
> Prevent DNS leaks on Windows
> push "block-outside-dns"
> Override the Client default gateway by using 0.0.0.0/1 and
> 128.0.0.0/1 rather than 0.0.0.0/0. This has the benefit of
> overriding but not wiping out the original default gateway.
> push "redirect-gateway def1"
> client-to-client
> keepalive 1800 3600
> remote-cert-tls client
> tls-version-min 1.2
> tls-crypt /etc/openvpn/easy-rsa/pki/ta.key
> cipher AES-256-CBC
> auth SHA256
> user nobody
> group nogroup
> persist-key
> persist-tun
> crl-verify /etc/openvpn/crl.pem
> status /var/log/openvpn-status.log 20
> status-version 3
> syslog
> verb 3
>DuplicateCNs allow access control on a less-granular, per user basis.
>Remove # if you will manage access by user instead of device. 
> duplicate-cn
>  Generated for use by PiVPN.io
> push "route 192.168.1.192 255.255.255.0"
> local 192.168.1.192_

### Have you searched for similar issues and solutions?
    (yes/no / which issues?)

Yes, many.


### Have you taken any steps towards solving your issue?
```
396, 752, 380, etc
```

**Comment by mwoolweaver** [comment]
Is your pihole setup to listen on all interfaces should be the first option under Settings > DNS > Listening Behavior.

![as seen here](https://user-images.githubusercontent.com/5729320/58589014-90ba3000-8226-11e9-85b5-5885171fcbe4.png)

**Comment by Metiiin** [comment]
> Is your pihole setup to listen on all interfaces should be the first option under Settings > DNS > Listening Behavior.
> 
> ![as seen here](https://user-images.githubusercontent.com/5729320/58589014-90ba3000-8226-11e9-85b5-5885171fcbe4.png)

yes, i have it on that setting. Also tried the third one.

I just tried reinstalling pivpn to have a clean slate, and once again vpn connects no problem. however no internet access.

**Comment by mwoolweaver** [comment]
try changing this line in your server.conf

``` push "dhcp-option DNS 8.8.8.8" ```

to 


``` push "dhcp-option DNS 10.8.0.1"

and remove the other Google DNS option

**Comment by Metiiin** [comment]
> try changing this line in your server.conf
> 
> `push "dhcp-option DNS 8.8.8.8"`
> 
> to
> 
> ```
> 
> and remove the other Google DNS option 
> ```

I think you missed something? I commented out the other option.

**Comment by orazioedoardo** [comment]
Since you just reinstalled can you post the output of `pivpn debug` (which you were supposed to do when you opened the issue).

**Comment by Metiiin** [comment]
> Since you just reinstalled can you post the output of `pivpn debug` (which you were supposed to do when you opened the issue).

Sorry, here it is.

> ::::		[4mPiVPN debug[0m		 ::::
> =============================================
> ::::		[4mLatest commit[0m		 ::::
> commit 2e5b804893aa2c263f455e80b4aa56797e9c64a5
> Author: 4s3ti <cfcolaco@gmail.com>
> Date:   Tue May 14 09:58:15 2019 +0100
> 
>     Merge pull request #740 from 4s3ti/master
>     
>     Merging Test Branch into Master
> =============================================
> ::::	    [4mInstallation settings[0m    	 ::::
> /etc/pivpn/DET_PLATFORM -> Raspbian
> /etc/pivpn/INSTALL_PORT -> 31415
> /etc/pivpn/INSTALL_PROTO -> udp
> /etc/pivpn/INSTALL_USER -> pi
> /etc/pivpn/NO_UFW -> 1
> /etc/pivpn/pivpnINTERFACE -> eth0
> /etc/pivpn/setupVars.conf.update.bak -> pivpnUser=pi
> UNATTUPG=unattended-upgrades
> pivpnInterface=eth0
> IPv4dns=127.0.0.1
> IPv4addr=192.168.1.192
> IPv4gw=192.168.1.1
> pivpnProto=udp
> PORT=31415
> ENCRYPT=521
> APPLY_TWO_POINT_FOUR=true
> DOWNLOAD_DH_PARAM=false
> PUBLICDNS=
> OVPNDNS1=8.8.8.8
> OVPNDNS2=8.8.4.4
> /etc/pivpn/TWO_POINT_FOUR -> 
> =============================================
> ::::	[4msetupVars file shown below[0m	 ::::
> pivpnUser=pi
> UNATTUPG=unattended-upgrades
> pivpnInterface=eth0
> IPv4dns=127.0.0.1
> IPv4addr=192.168.1.192
> IPv4gw=192.168.1.1
> pivpnProto=udp
> PORT=31415
> ENCRYPT=521
> APPLY_TWO_POINT_FOUR=true
> DOWNLOAD_DH_PARAM=false
> PUBLICDNS=
> OVPNDNS1=8.8.8.8
> OVPNDNS2=8.8.4.4
> =============================================
> ::::  [4mServer configuration shown below[0m   ::::
> dev tun
> proto udp
> port 31415
> ca /etc/openvpn/easy-rsa/pki/ca.crt
> cert /etc/openvpn/easy-rsa/pki/issued/server_DI5rmHS0Vyi6UNNA.crt
> key /etc/openvpn/easy-rsa/pki/private/server_DI5rmHS0Vyi6UNNA.key
> dh none
> topology subnet
> server 10.8.0.0 255.255.255.0
> # Set your primary domain name server address for clients
> push "dhcp-option DNS 8.8.8.8"
> #push "dhcp-option DNS 8.8.4.4"
> # Prevent DNS leaks on Windows
> push "block-outside-dns"
> # Override the Client default gateway by using 0.0.0.0/1 and
> # 128.0.0.0/1 rather than 0.0.0.0/0. This has the benefit of
> # overriding but not wiping out the original default gateway.
> push "redirect-gateway def1"
> client-to-client
> keepalive 1800 3600
> remote-cert-tls client
> tls-version-min 1.2
> tls-crypt /etc/openvpn/easy-rsa/pki/ta.key
> cipher AES-256-CBC
> auth SHA256
> user nobody
> group nogroup
> persist-key
> persist-tun
> crl-verify /etc/openvpn/crl.pem
> status /var/log/openvpn-status.log 20
> status-version 3
> syslog
> verb 3
> #DuplicateCNs allow access control on a less-granular, per user basis.
> #Remove # if you will manage access by user instead of device. 
> #duplicate-cn
> # Generated for use by PiVPN.io
> =============================================
> ::::  [4mClient template file shown below[0m   ::::
> client
> dev tun
> proto udp
> remote REMOTE 31415
> resolv-retry infinite
> nobind
> persist-key
> persist-tun
> remote-cert-tls server
> tls-version-min 1.2
> verify-x509-name server_DI5rmHS0Vyi6UNNA name
> cipher AES-256-CBC
> auth SHA256
> auth-nocache
> verb 3
> =============================================
> :::: 	[4mRecursive list of files in[0m	 ::::
> ::: [4m/etc/openvpn/easy-rsa/pki shows below[0m :::
> /etc/openvpn/easy-rsa/pki/:
> ca.crt
> crl.pem
> Default.txt
> ecparams
> extensions.temp
> index.txt
> index.txt.attr
> index.txt.attr.old
> index.txt.old
> iphonemk2.ovpn
> issued
> openssl-easyrsa.cnf
> private
> renewed
> revoked
> safessl-easyrsa.cnf
> serial
> serial.old
> ta.key
> 
> /etc/openvpn/easy-rsa/pki/ecparams:
> secp521r1.pem
> 
> /etc/openvpn/easy-rsa/pki/issued:
> iphonemk2.crt
> server_DI5rmHS0Vyi6UNNA.crt
> 
> /etc/openvpn/easy-rsa/pki/private:
> ca.key
> iphonemk2.key
> server_DI5rmHS0Vyi6UNNA.key
> 
> /etc/openvpn/easy-rsa/pki/renewed:
> private_by_serial
> reqs_by_serial
> 
> /etc/openvpn/easy-rsa/pki/renewed/private_by_serial:
> 
> /etc/openvpn/easy-rsa/pki/renewed/reqs_by_serial:
> 
> /etc/openvpn/easy-rsa/pki/revoked:
> private_by_serial
> reqs_by_serial
> 
> /etc/openvpn/easy-rsa/pki/revoked/private_by_serial:
> 
> /etc/openvpn/easy-rsa/pki/revoked/reqs_by_serial:
> =============================================
> ::::		[4mSelf check[0m		 ::::
> :: [OK] IP forwarding is enabled
> :: [OK] Iptables MASQUERADE rule set
> :: [OK] OpenVPN is running
> :: [OK] OpenVPN is enabled (it will automatically start on reboot)
> :: [OK] OpenVPN is listening on port 31415/udp
> =============================================
> ::::      [4mSnippet of the server log[0m      ::::
> May 30 06:43:48 raspberrypi ovpn-server[27205]: 99.203.88.231:21796 ++ Certificate has EKU (str) TLS Web Client Authentication, expects TLS Web Client Authentication
> May 30 06:43:48 raspberrypi ovpn-server[27205]: 99.203.88.231:21796 VERIFY EKU OK
> May 30 06:43:48 raspberrypi ovpn-server[27205]: 99.203.88.231:21796 VERIFY OK: depth=0, CN=iphonemk2
> May 30 06:43:48 raspberrypi ovpn-server[27205]: 99.203.88.231:21796 peer info: IV_GUI_VER=net.openvpn.connect.ios_3.0.2-894
> May 30 06:43:48 raspberrypi ovpn-server[27205]: 99.203.88.231:21796 peer info: IV_VER=3.2
> May 30 06:43:48 raspberrypi ovpn-server[27205]: 99.203.88.231:21796 peer info: IV_PLAT=ios
> May 30 06:43:48 raspberrypi ovpn-server[27205]: 99.203.88.231:21796 peer info: IV_NCP=2
> May 30 06:43:48 raspberrypi ovpn-server[27205]: 99.203.88.231:21796 peer info: IV_TCPNL=1
> May 30 06:43:48 raspberrypi ovpn-server[27205]: 99.203.88.231:21796 peer info: IV_PROTO=2
> May 30 06:43:48 raspberrypi ovpn-server[27205]: 99.203.88.231:21796 peer info: IV_AUTO_SESS=1
> May 30 06:43:48 raspberrypi ovpn-server[27205]: 99.203.88.231:21796 Control Channel: TLSv1.2, cipher TLSv1/SSLv3 ECDHE-ECDSA-AES256-GCM-SHA384
> May 30 06:43:48 raspberrypi ovpn-server[27205]: 99.203.88.231:21796 [iphonemk2] Peer Connection Initiated with [AF_INET]99.203.88.231:21796
> May 30 06:43:48 raspberrypi ovpn-server[27205]: iphonemk2/99.203.88.231:21796 MULTI_sva: pool returned IPv4=10.8.0.2, IPv6=(Not enabled)
> May 30 06:43:48 raspberrypi ovpn-server[27205]: iphonemk2/99.203.88.231:21796 MULTI: Learn: 10.8.0.2 -> iphonemk2/99.203.88.231:21796
> May 30 06:43:48 raspberrypi ovpn-server[27205]: iphonemk2/99.203.88.231:21796 MULTI: primary virtual IP for iphonemk2/99.203.88.231:21796: 10.8.0.2
> May 30 06:43:48 raspberrypi ovpn-server[27205]: iphonemk2/99.203.88.231:21796 PUSH: Received control message: 'PUSH_REQUEST'
> May 30 06:43:48 raspberrypi ovpn-server[27205]: iphonemk2/99.203.88.231:21796 SENT CONTROL [iphonemk2]: 'PUSH_REPLY,dhcp-option DNS 8.8.8.8,block-outside-dns,redirect-gateway def1,route-gateway 10.8.0.1,topology subnet,ping 1800,ping-restart 3600,ifconfig 10.8.0.2 255.255.255.0,peer-id 0,cipher AES-256-GCM' (status=1)
> May 30 06:43:48 raspberrypi ovpn-server[27205]: iphonemk2/99.203.88.231:21796 Data Channel Encrypt: Cipher 'AES-256-GCM' initialized with 256 bit key
> May 30 06:43:48 raspberrypi ovpn-server[27205]: iphonemk2/99.203.88.231:21796 Data Channel Decrypt: Cipher 'AES-256-GCM' initialized with 256 bit key
> May 30 06:51:49 raspberrypi ovpn-server[27205]: iphonemk2/99.203.88.231:8858 SIGTERM[soft,remote-exit] received, client-instance exiting
> =============================================
> ::::		[4mDebug complete[0m		 ::::
>

**Comment by Metiiin** [comment]
> Since you just reinstalled can you post the output of `pivpn debug` (which you were supposed to do when you opened the issue).

Sorry, here it is.

https://pastebin.com/GZJjfaig

**Comment by orazioedoardo** [comment]
There doesn't seem to be issues with the pivpn (except that you are using google dns and not pihole).
From the client can you connect to the router's web interface (192.168.1.1)? Any other website?

**Comment by Metiiin** [comment]
> There doesn't seem to be issues with the pivpn (except that you are using google dns and not pihole).
> From the client can you connect to the router's web interface (192.168.1.1)? Any other website?

No, when I am connected to pi cant connect to anything. If I type my pihole ip, I get a message saying "Did you mean to go to the admin panel?" But can't actually load it.

Should I switch the DNS to the piholes?

**Comment by orazioedoardo** [comment]
Seems strange that the pihole ip (is it the same raspberrypi?) load but the admin page doesn't. I'm asking again, does the router web interface load when you are connected to the vpn?

**Comment by Metiiin** [comment]
> Seems strange that the pihole ip (is it the same raspberrypi?) load but the admin page doesn't. I'm asking again, does the router web interface load when you are connected to the vpn? Try to connect from a cellular network too.

Let me clarify because I dont think we are on the same page. Pardon me as I am not extremely experienced. I have tried multiple solutions in aforementioned issues as well.

Testing on my phone with Wifi and Cellular.

Wifi+VPN:

Can access home router and pihole admin page, np. However, in this state I get no adblocking on webpages.

Cellular + VPN:

I can send messages, however, webpages do not load. The most I have gotten a webpage to load was trying to access the pihole admin page. Which doesnt even take me to the main splashscreen. just a plaintext version.

Would making my router the DNS do anything? My pihole also uses google.

**Comment by orazioedoardo** [comment]
Does Wifi+VPN mean that you connect to the vpn from the your home network, where the raspberry pi sits? It's not really useful. If that's the case, I'll focus on Cellular + VPN:
> I can send messages, however, webpages do not load. The most I have gotten a webpage to load was trying to access the pihole admin page. Which doesnt even take me to the main splashscreen. just a plaintext version.

Is your home connection UPLOAD speed very slow? In the openvpn connect app check whether you have compression enabled or not (it should be disabled).

> Would making my router the DNS do anything? My pihole also uses google.

No, currently your vpn clients are using 8.8.8.8. If we manage to make it work, I will tell you how to use pihole as dns.

**Comment by Metiiin** [comment]
Wifi with VPN was just me testing to see for myself how it would perform.

Main purpose is to transport my pihole adblocking with my cellular wherever I go.

I have Gigabit up and down on my home network and compression is already disabled.

**Comment by orazioedoardo** [comment]
Can you try #54? You need to add those line to the file `/etc/openvpn/server.conf` and then restart the server with `sudo systemctl restart openvpn`.

**Comment by Metiiin** [comment]
> sudo systemctl restart openvpn

That worked.... Do you happen to know what those two lines mean?

Thanks for the help. I appreciate it a lot.

**Comment by orazioedoardo** [comment]
> That worked.... Do you happen to know what those two lines mean?

Probably your cellular provider is slicing packets in fragments smaller than the size of the openvpn packets. Those options  openvpn to use smaller packets so they fit inside packets that flow across the network.

> I am assuming I have to point openvpn to the pi instead of public DNS 

Yeah, edit the `server.conf` file again, replace

```
push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 8.8.4.4"
```

with

`push "dhcp-option DNS 10.8.0.1"`

Then restart the server. If everything works, close the issue.

**Comment by Metiiin** [comment]
When I do that I lose the ability to access websites again.

**Comment by orazioedoardo** [comment]
Usually “Listen to all interfaces” is enough (probably not for you because you customized dnsmasq.conf). Permit all origin POTENTIALLY allows anyone to connect but PRATICALLY you would need to forward port 53 on your router, which I suppose you didn’t do, and you don’t need to since you use the VPN to connect to the internal network.

**Comment by Metiiin** [comment]
Well everything seems to be functioning properly... but I have lost proper query logs? This is all I get now.

![image](https://user-images.githubusercontent.com/12926627/58650449-b86bcf80-82dc-11e9-994d-896980c42a29.png)

**Comment by Metiiin** [comment]
> That’s 100% not pivpn related, so perhaps you could ask that on pihole’s reddit or discourse forum.

Thank you for the assistance. Cheers
