### ISSUE TITLE
Something suddenly broke

### ISSUE THREAD

**Issue by DonavynDeRaine** [pivpn/pivpn#758]
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

### Issue
The VPN was online and working well up until a few days ago, and I honestly don't know what has changed.

I have verified that port 1194 UDP is open in the router and forwarded to the RaspPi, I can see it in the 'Admin' portion of the router, however when I attempt to connect it hangs, and then errors out after 60 seconds with:

Wed May 29 14:21:15 2019 VERIFY EKU OK
Wed May 29 14:21:15 2019 VERIFY X509NAME OK: CN=server_OEw9sdF9XYm3zyRY
Wed May 29 14:21:15 2019 VERIFY OK: depth=0, CN=server_OEw9sdF9XYm3zyRY
Wed May 29 14:22:15 2019 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Wed May 29 14:22:15 2019 TLS Error: TLS handshake failed
Wed May 29 14:22:15 2019 SIGUSR1[soft,tls-error] received, process restarting
Wed May 29 14:22:15 2019 MANAGEMENT: >STATE:1559161335,RECONNECTING,tls-error,,,,,

I cannot connect any of the VPN profiles.

I've created a new profile just in case one became corrupt or something.

### Have you searched for similar issues and solutions?
    (yes/no / which issues?) Yes - Not Connecting to the VPN

### Console output of      `curl -L install.pivpn.io | bash`
```
curl -L install.pivpn.io | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   178  100   178    0     0   2562      0 --:--:-- --:--:-- --:--:--  2579
100 54916  100 54916    0     0   112k      0 --:--:-- --:--:-- --:--:--  112k
:::
::: sudo will be used for the install.
::: Cancel selected. Exiting

It detects that there is an existing install and provides to me the options to Update, Reconfigure, OK and Cancel.

I attempted the reconfigure yesterday after posting.

```

Profiles are created successfully without error

### Console output of      `pivpn add` or `pivpn add nopass`
```
pivpn add
Enter a Name for the Client:

```

### Console output of      `pivpn debug`
```
pivpn debug
::: Generating Debug Output
::::            PiVPN debug              ::::
=============================================
::::            Latest commit            ::::
commit 2e5b804893aa2c263f455e80b4aa56797e9c64a5
Author: 4s3ti <cfcolaco@gmail.com>
Date:   Tue May 14 09:58:15 2019 +0100

    Merge pull request #740 from 4s3ti/master

    Merging Test Branch into Master
=============================================
::::        Installation settings        ::::
/etc/pivpn/DET_PLATFORM -> Raspbian
/etc/pivpn/install.log -> :::
::: Stopping OpenVPN service... done.
:::
::: Installing scripts to /opt/pivpn... done.
::: Using protocol: udp
::: Building CA...

::: CA Complete.

Note: using Easy-RSA configuration from: ./vars

Note: using Easy-RSA configuration from: ./vars

DH parameters of size 2048 created at /etc/openvpn/easy-rsa/pki/dh.pem


Note: using Easy-RSA configuration from: ./vars

An updated CRL has been created.
CRL file: /etc/openvpn/easy-rsa/pki/crl.pem

net.ipv4.ip_forward = 1

/etc/pivpn/INSTALL_PORT -> 1194
/etc/pivpn/INSTALL_PROTO -> udp
/etc/pivpn/INSTALL_USER -> pi
/etc/pivpn/NO_UFW -> 1
/etc/pivpn/pivpnINTERFACE -> eth0
/etc/pivpn/setupVars.conf.update.bak -> pivpnUser=pi
UNATTUPG=unattended-upgrades
pivpnInterface=eth0
IPv4dns=127.0.0.1
IPv4addr=192.168.7.15
IPv4gw=192.168.7.1
pivpnProto=udp
PORT=1194
ENCRYPT=2048
APPLY_TWO_POINT_FOUR=false
DOWNLOAD_DH_PARAM=false
PUBLICDNS=defshard.synology.me
OVPNDNS1=1.1.1.1
OVPNDNS2=1.0.0.1
/etc/pivpn/TWO_POINT_FOUR ->
=============================================
::::    setupVars file shown below       ::::
pivpnUser=pi
UNATTUPG=unattended-upgrades
pivpnInterface=eth0
IPv4dns=127.0.0.1
IPv4addr=192.168.7.15
IPv4gw=192.168.7.1
pivpnProto=udp
PORT=1194
ENCRYPT=256
APPLY_TWO_POINT_FOUR=true
DOWNLOAD_DH_PARAM=false
PUBLICDNS=REMOTE
OVPNDNS1=8.8.8.8
OVPNDNS2=8.8.4.4
=============================================
::::  Server configuration shown below   ::::
dev tun
proto udp
port 1194
ca /etc/openvpn/easy-rsa/pki/ca.crt
cert /etc/openvpn/easy-rsa/pki/issued/server_SG2ipTyp9WAgbS2B.crt
key /etc/openvpn/easy-rsa/pki/private/server_SG2ipTyp9WAgbS2B.key
dh none
topology subnet
server 10.8.0.0 255.255.255.0
# Set your primary domain name server address for clients
push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 8.8.4.4"
# Prevent DNS leaks on Windows
push "block-outside-dns"
# Override the Client default gateway by using 0.0.0.0/1 and
# 128.0.0.0/1 rather than 0.0.0.0/0. This has the benefit of
# overriding but not wiping out the original default gateway.
push "redirect-gateway def1"
client-to-client
keepalive 1800 3600
remote-cert-tls client
tls-version-min 1.2
tls-crypt /etc/openvpn/easy-rsa/pki/ta.key
cipher AES-256-CBC
auth SHA256
user nobody
group nogroup
persist-key
persist-tun
crl-verify /etc/openvpn/crl.pem
status /var/log/openvpn-status.log 20
status-version 3
syslog
verb 3
#DuplicateCNs allow access control on a less-granular, per user basis.
#Remove # if you will manage access by user instead of device.
#duplicate-cn
# Generated for use by PiVPN.io
=============================================
::::  Client template file shown below   ::::
client
dev tun
proto udp
remote REMOTE 1194
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
tls-version-min 1.2
verify-x509-name server_SG2ipTyp9WAgbS2B name
cipher AES-256-CBC
auth SHA256
auth-nocache
verb 3
=============================================
::::    Recursive list of files in       ::::
::: /etc/openvpn/easy-rsa/pki shows below :::
/etc/openvpn/easy-rsa/pki/:
ca.crt
crl.pem
Default.txt
ecparams
extensions.temp
index.txt
index.txt.attr
index.txt.attr.old
index.txt.old
issued
KevAtWork.ovpn
KevChrome.ovpn
KevPC.ovpn
openssl-easyrsa.cnf
private
renewed
revoked
safessl-easyrsa.cnf
serial
serial.old
ta.key

/etc/openvpn/easy-rsa/pki/ecparams:
prime256v1.pem

/etc/openvpn/easy-rsa/pki/issued:
KevAtWork.crt
KevChrome.crt
KevPC.crt
server_SG2ipTyp9WAgbS2B.crt

/etc/openvpn/easy-rsa/pki/private:
ca.key
KevAtWork.key
KevChrome.key
KevPC.key
server_SG2ipTyp9WAgbS2B.key

/etc/openvpn/easy-rsa/pki/renewed:
private_by_serial
reqs_by_serial

/etc/openvpn/easy-rsa/pki/renewed/private_by_serial:

/etc/openvpn/easy-rsa/pki/renewed/reqs_by_serial:

/etc/openvpn/easy-rsa/pki/revoked:
private_by_serial
reqs_by_serial

/etc/openvpn/easy-rsa/pki/revoked/private_by_serial:

/etc/openvpn/easy-rsa/pki/revoked/reqs_by_serial:
=============================================
::::            Self check               ::::
:: [OK] IP forwarding is enabled
:: [OK] Iptables MASQUERADE rule set
:: [OK] OpenVPN is running
:: [OK] OpenVPN is enabled (it will automatically start on reboot)
:: [OK] OpenVPN is listening on port 1194/udp
=============================================
::::      Snippet of the server log      ::::
May 29 22:26:10 raspberrypi ovpn-server[453]: KevPC/192.168.7.1:50616 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
May 29 22:26:10 raspberrypi ovpn-server[453]: KevPC/192.168.7.1:50616 TLS Error: TLS handshake failed
May 29 22:26:10 raspberrypi ovpn-server[453]: KevPC/192.168.7.1:50616 TLS: tls_multi_process: killed expiring key
May 29 22:26:10 raspberrypi ovpn-server[453]: KevPC/192.168.7.1:50616 SIGUSR1[soft,tls-error] received, client-instance restarting
May 30 02:41:10 raspberrypi ovpn-server[453]: tls-crypt unwrap error: packet too short
May 30 02:41:10 raspberrypi ovpn-server[453]: TLS Error: tls-crypt unwrapping failed from [AF_INET]185.200.118.80:42380
May 30 10:02:34 raspberrypi ovpn-server[453]: tls-crypt unwrap error: packet authentication failed
May 30 10:02:34 raspberrypi ovpn-server[453]: TLS Error: tls-crypt unwrapping failed from [AF_INET]24.11.120.46:58445
May 30 10:02:36 raspberrypi ovpn-server[453]: tls-crypt unwrap error: packet authentication failed
May 30 10:02:36 raspberrypi ovpn-server[453]: TLS Error: tls-crypt unwrapping failed from [AF_INET]24.11.120.46:58445
May 30 10:02:39 raspberrypi ovpn-server[453]: tls-crypt unwrap error: packet authentication failed
May 30 10:02:39 raspberrypi ovpn-server[453]: TLS Error: tls-crypt unwrapping failed from [AF_INET]24.11.120.46:58445
May 30 10:08:54 raspberrypi ovpn-server[453]: tls-crypt unwrap error: packet authentication failed
May 30 10:08:54 raspberrypi ovpn-server[453]: TLS Error: tls-crypt unwrapping failed from [AF_INET]24.11.120.46:54922
May 30 10:08:56 raspberrypi ovpn-server[453]: tls-crypt unwrap error: packet authentication failed
May 30 10:08:56 raspberrypi ovpn-server[453]: TLS Error: tls-crypt unwrapping failed from [AF_INET]24.11.120.46:54922
May 30 10:09:01 raspberrypi ovpn-server[453]: tls-crypt unwrap error: packet authentication failed
May 30 10:09:01 raspberrypi ovpn-server[453]: TLS Error: tls-crypt unwrapping failed from [AF_INET]24.11.120.46:54922
May 30 10:09:09 raspberrypi ovpn-server[453]: tls-crypt unwrap error: packet authentication failed
May 30 10:09:09 raspberrypi ovpn-server[453]: TLS Error: tls-crypt unwrapping failed from [AF_INET]24.11.120.46:54922
=============================================
::::            Debug complete           ::::
:::
::: Debug output completed above.
::: Copy saved to /tmp/debug.txt

```
### Have you taken any steps towards solving your issue?
```
Yes, the most likely candidate of issue is going to be the port forward to the Pi from WAN connections.  I can see that the router has the port forwarded, but it doesn't appear to be if I issue a port scan.
```

**Comment by christyler80** [comment]
This is exactly the same problem as I have recently encountered (#755). I have removed and reinstalled PiVPN, but the same issue persists.

**Comment by orazioedoardo** [comment]
You are supposed to replace `Output Here` with the output of the command above.

**Comment by christyler80** [comment]
Sorry, but I do not understand what is being asked for.

**Comment by orazioedoardo** [comment]
When you open the issue, the template text asks you to run some commands and copy the ouput, like `pivpn debug`.

**Comment by 4s3ti** [comment]
@christyler80 please read carefully everything that is asked for in the issue template! without details, we cannot help.

please help us helping you by reading carefully everything, and providing the information we ask for, searching for similar issues. 

Since it seems you don't have all the knowledge, feel free to make any suggestions on how we can make it easier to understand! 

Kind Regards.

**Comment by christyler80** [comment]
My problem, was that the name of my Pi listed under 'Ethernet' devices on my router was the Raspbian 'default name' of 'raspberrypi', rather than actual name I had give to the Pi (via /etc/hosts and /etc/hostname).
My Pi also has WiFi (turned off though) and this name was listed correctly by the router under 'Wireless' devices.
Manually changing the Ethernet device name on router from 'raspberrypi', to its actual name has solved the problem.

**Comment by DonavynDeRaine** [comment]
My apologies, I thought I had provided all of the information that was asked for.

What output would you like for me to provide?

I have reinstalled pivpn, which allowed me to generate new profiles.  I can create a profile and connect to the VPN via LAN connection, but not WAN.

Again, I know that the ports are opened, just not sure why they aren't directing traffic to the Pi like it had before.

**Comment by orazioedoardo** [comment]
See your first message? [This one](https://github.com/pivpn/pivpn/issues/758#issue-450006999). It says “Console output of...” and some command. When you open an issue there is some text prefilled that asks you to run some command after the checkboxes.

**Comment by DonavynDeRaine** [comment]
I've updated the original comment, again my apologies for not doing this initially.

**Comment by orazioedoardo** [comment]
`May 30 10:09:09 raspberrypi ovpn-server[453]: tls-crypt unwrap error: packet authentication failed
May 30 10:09:09 raspberrypi ovpn-server[453]: TLS Error: tls-crypt unwrapping failed from [AF_INET]`

Is this your last attempt at connecting? I mean, after reinstalling? Over WAN? Have you accidentally reused the old profile on the client?

**Comment by DonavynDeRaine** [comment]
Yes that was my last attempt over WAN.  I'm currently at work, so used the 'AtWork' profile for my business laptop.  I made sure that I did not use an old Profile, the others were removed after I reconfigured just to be sure.

I am using OpenVPN GUI

**Comment by DonavynDeRaine** [comment]
I just found this in doing a search for that part "Looks like there's a new functionality introduced in v2.4 that this tool does not yet support: tls-crypt. Currently, it assumes that ta.key file supplied is only for the tls-auth option."

**Comment by orazioedoardo** [comment]
> I just found this in doing a search for that part "Looks like there's a new functionality introduced in v2.4 that this tool does not yet support: tls-crypt. Currently, it assumes that ta.key file supplied is only for the tls-auth option."

Is your openvpn client updated? If it’s the latest version it should support tls-crypt, otherwhise hfor simplicity) you need to reinstall without opting into using v2.4 features.

> EDIT: It just hit me, if the VPN server can see the failed attempt to connect, then the port forward is fine ... right?

Yes.

**Comment by DonavynDeRaine** [comment]
SMH I just figured it out, you asked a question which I started to ponder after disregarding the port forward aspect:

"Have you accidentally reused the old profile on the client? "

When I created the profile I made sure that I used it, even so much as to remove OpenVPN client (using Geek Uninstaller) and reinstalling.

Copied the profile to the OpenVPN\config folder, right clicked on the gui and selected 'connect'

I went looking for log files, more specifically OpenVPN log files.  For Windows, the log and config files are sent to the %USERPROFILE% folder under OpenVPN.

I checked the config folder, sure enough the old config file was still listed in there.

I removed everything except the readme.txt file from that folder, then right-clicked on the GUI icon in the task bar, this time I IMPORTED the profile.

After receiving the message "Imported Successfully", I attempted to connect again.

Which was successful.

**Comment by DonavynDeRaine** [comment]
Going to close this thread, but thank you orazioedoardo for your help and guidance.

**Comment by christyler80** [comment]
Ok. The issue I opened was #755 and I will update the output section there.

 

On Thu, 30 May 2019, 11:06 Orazio, <notifications@github.com <mailto:notifications@github.com> > wrote:

You are supposed to replace Output Here with the output of the command above.

**Comment by christyler80** [comment]
Hi,

 

What is your role – we have not spoken before?

 

Best Regards

 

Chris
