### ISSUE TITLE
Systematic incomplete issues. 

### ISSUE THREAD

**Issue by 4s3ti** [pivpn/pivpn#759]
Hi all, 

@orazioedoardo @devZer0 @james-lasersoft @Giraffe1966 

will add a note to README.md

This is a repetitive thing, and it keeps taking us time from the important stuff.

Due to PiVPN nature, we keep systematically seeing users posting incomplete issue templates and not even reading what is written, from now on all incomplete issue templates will be closed straight away. 

Is there any suggestion to make it easier for less technically savy users to understand what we request and that we really need that info? 

I wonder if people go to the doctor just saying " I am sick, cure me!" =( 

Kind regards.

**Comment by orazioedoardo** [comment]
> from now on all incomplete issue templates will be closed straight away.

Agree, incomplete issues just don't even encourage into answering.

> Is there any suggestion to make it easier for less technically savy users to understand what we request and that we really need that info?

I don't think there is much we can do if the user doesn't see `PLEASE READ THIS TEMPLATE CAREFULLY BEFORE OPENING AN ISSUE! `. Probably we could add a whiptail dialog at the end of the installation pointing out how to open an issue. After all, most issues occur just after the installation so the user won't have already forgotten what was stated in the dialog.

**Comment by 4s3ti** [comment]
I like the whiptail solution, adding enhancement tag here! thanks @orazioedoardo
