### ISSUE TITLE
Pi is not accessible via lan after install/reboot. 

### ISSUE THREAD

**Issue by N6MIK** [pivpn/pivpn#762]
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

 I flashed a headless stretch-lite image, apt-got the upgrades, and installed PiVPN... rebooted as recommended (prior to adding clients) and can not see the Pi on the network...

The only changes I made during install were the incoming VPN port and the client DNS.
I've repeated this a couple of times.

### Have you searched for similar issues and solutions?
Yes - close duplicate are issue with clients connecting to the vpn. 

### Console output of      `curl -L install.pivpn.io | bash`
```
 Not possible
```

### Console output of      `pivpn add` or `pivpn add nopass`
```
Not possible
```

### Console output of      `pivpn debug`
```
  Output Here
```
### Have you taken any steps towards solving your issue?
```
Reinstalled numerous times with minimal changes to the defaults. 
```

**Comment by 4s3ti** [comment]
Closing this issue.

As per: https://github.com/pivpn/pivpn/issues/759

Please make sure you read everything carefully before posting an issue. 
please make sure you fill issue template correctly.
please make sure it is really PiVPN / Code related issue. 
Consider taking the issue over to PiVPN Subreddit. 
Kind Regards.
