### ISSUE TITLE
OpenVPN installed ok and it works over lan but not remotely outside of home network

### ISSUE THREAD

**Issue by arkid** [pivpn/pivpn#763]
- [x] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [x] The issue I am reporting isn't a duplicate (see [FAQs]

### Issue
The install works fine but I can't access the vpn from an external network over the internet.  Accessing from inside my home lan works fine.   I've tried from my android phone and a windows PC and both connect near instantly.  However with the same Android phone with wifi disabled, the connection ALWAYS times out.

### Have you searched for similar issues and solutions?
Yes I have and I know there are other issues similar closed in githuib already but believe me I've read them and they don't seem to apply to my case.

### Console output of      `curl -L install.pivpn.io | bash`
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   178  100   178    0     0    504      0 --:--:-- --:--:-- --:--:--   505
100 54916  100 54916    0     0  93875      0 --:--:-- --:--:-- --:--:-- 93875
:::
::: sudo will be used for the install.
::: Reconfigure option selected
::: Verifying free disk space...
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: Your system is up to date! Continuing with PiVPN installation...
::: Static IP already configured.
::: Using User: pi
:::
::: Checking for existing base files...
:::    Checking /etc/.pivpn is a repo...:::    Cloning https://github.com/pivpn/pivpn.git into /etc/.pivpn... done!
:::
::: Stopping OpenVPN service... done.
:::
::: Installing scripts to /opt/pivpn... done.
::: Using protocol: udp
set_var EASYRSA_ALGO       ec
set_var EASYRSA_CURVE      prime256v1
::: Building CA...
read EC key
writing EC key

::: CA Complete.

Note: using Easy-RSA configuration from: ./vars

Using SSL: openssl OpenSSL 1.1.0j  20 Nov 2018
Generating an EC private key
writing new private key to '/etc/openvpn/easy-rsa/pki/private/server_IEje2NDzWM6wBpas.key.SQw0p5ZYTe'
-----
Using configuration from /etc/openvpn/easy-rsa/pki/safessl-easyrsa.cnf
Can't open /etc/openvpn/easy-rsa/pki/index.txt.attr for reading, No such file or directory
1996120064:error:02001002:system library:fopen:No such file or directory:../crypto/bio/bss_file.c:74:fopen('/etc/openvpn/easy-rsa/pki/index.txt.attr','r')
1996120064:error:2006D080:BIO routines:BIO_new_file:no such file:../crypto/bio/bss_file.c:81:
Check that the request matches the signature
Signature ok
The Subject's Distinguished Name is as follows
commonName            :ASN.1 12:'server_IEje2NDzWM6wBpas'
Certificate is to be certified until May 16 21:31:02 2022 GMT (1080 days)

Write out database with 1 new entries
Data Base Updated

Note: using Easy-RSA configuration from: ./vars

Using SSL: openssl OpenSSL 1.1.0j  20 Nov 2018
Using configuration from /etc/openvpn/easy-rsa/pki/safessl-easyrsa.cnf

An updated CRL has been created.
CRL file: /etc/openvpn/easy-rsa/pki/crl.pem

net.ipv4.ip_forward = 1
run-parts: executing /usr/share/netfilter-persistent/plugins.d/15-ip4tables save
run-parts: executing /usr/share/netfilter-persistent/plugins.d/25-ip6tables save
::: Using Google servers.
sleep 0.1
::: Install Complete...
::: Restarting services...
Synchronizing state of openvpn.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable openvpn
::: Flushing writes to disk...
::: done.
:::
::: Installation Complete!
::: Now run 'pivpn add' to create an ovpn profile for each of your devices.
::: Run 'pivpn help' to see what else you can do!
::: It is strongly recommended you reboot after installation.
:::
```

### Console output of      `pivpn add` or `pivpn add nopass`
```
Note: using Easy-RSA configuration from: ./vars

Using SSL: openssl OpenSSL 1.1.0j  20 Nov 2018
Generating an EC private key
writing new private key to '/etc/openvpn/easy-rsa/pki/private/xxxx.key.8tujXd2auF'
Enter PEM pass phrase:
Verifying - Enter PEM pass phrase:
-----
Using configuration from /etc/openvpn/easy-rsa/pki/safessl-easyrsa.cnf
Check that the request matches the signature
Signature ok
The Subject's Distinguished Name is as follows
commonName            :ASN.1 12:'xxxx'
Certificate is to be certified until May 29 21:33:07 2029 GMT (3650 days)

Write out database with 1 new entries
Data Base Updated
Client's cert found: xxxx.crt
Client's Private Key found: xxxx.key
CA public Key found: ca.crt
tls-auth Private Key found: ta.key


========================================================
Done! xxxx.ovpn successfully created!
xxxx.ovpn was copied to:
  /home/pi/ovpns
for easy transfer. Please use this profile only on one
device and create additional profiles for other devices.
========================================================

```

### Console output of      `pivpn debug`
```
::: Generating Debug Output
::::            PiVPN debug              ::::
=============================================
::::            Latest commit            ::::
commit 2e5b804893aa2c263f455e80b4aa56797e9c64a5
Author: 4s3ti <cfcolaco@gmail.com>
Date:   Tue May 14 09:58:15 2019 +0100

    Merge pull request #740 from 4s3ti/master

    Merging Test Branch into Master
=============================================
::::        Installation settings        ::::
/etc/pivpn/DET_PLATFORM -> Raspbian
/etc/pivpn/install.log -> :::
::: Stopping OpenVPN service... done.
:::
::: Installing scripts to /opt/pivpn... done.
::: Using protocol: udp
::: Building CA...

::: CA Complete.

Note: using Easy-RSA configuration from: ./vars

Note: using Easy-RSA configuration from: ./vars

DH parameters of size 2048 created at /etc/openvpn/easy-rsa/pki/dh.pem


Note: using Easy-RSA configuration from: ./vars

An updated CRL has been created.
CRL file: /etc/openvpn/easy-rsa/pki/crl.pem

net.ipv4.ip_forward = 1
::: Using Google DNS servers.
/etc/pivpn/INSTALL_PORT -> 60111
/etc/pivpn/INSTALL_PROTO -> udp
/etc/pivpn/INSTALL_USER -> pi
/etc/pivpn/NO_UFW -> 1
/etc/pivpn/pivpnINTERFACE -> eth0
/etc/pivpn/setupVars.conf.update.bak -> pivpnUser=pi
UNATTUPG=unattended-upgrades
pivpnInterface=eth0
IPv4dns=192.168.2.1
IPv4addr=192.168.2.165
IPv4gw=192.168.2.1
pivpnProto=udp
PORT=60111
ENCRYPT=256
APPLY_TWO_POINT_FOUR=true
DOWNLOAD_DH_PARAM=false
PUBLICDNS=xxxxxxx
OVPNDNS1=8.8.8.8
OVPNDNS2=8.8.4.4
/etc/pivpn/TWO_POINT_FOUR ->
=============================================
::::    setupVars file shown below       ::::
pivpnUser=pi
UNATTUPG=unattended-upgrades
pivpnInterface=eth0
IPv4dns=192.168.2.1
IPv4addr=192.168.2.165
IPv4gw=192.168.2.1
pivpnProto=udp
PORT=60111
ENCRYPT=256
APPLY_TWO_POINT_FOUR=true
DOWNLOAD_DH_PARAM=false
PUBLICDNS=REMOTE
OVPNDNS1=8.8.8.8
OVPNDNS2=8.8.4.4
=============================================
::::  Server configuration shown below   ::::
dev tun
proto udp
port 60111
ca /etc/openvpn/easy-rsa/pki/ca.crt
cert /etc/openvpn/easy-rsa/pki/issued/server_IEje2NDzWM6wBpas.crt
key /etc/openvpn/easy-rsa/pki/private/server_IEje2NDzWM6wBpas.key
dh none
topology subnet
server 10.8.0.0 255.255.255.0
# Set your primary domain name server address for clients
push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 8.8.4.4"
# Prevent DNS leaks on Windows
push "block-outside-dns"
# Override the Client default gateway by using 0.0.0.0/1 and
# 128.0.0.0/1 rather than 0.0.0.0/0. This has the benefit of
# overriding but not wiping out the original default gateway.
push "redirect-gateway def1"
client-to-client
keepalive 1800 3600
remote-cert-tls client
tls-version-min 1.2
tls-crypt /etc/openvpn/easy-rsa/pki/ta.key
cipher AES-256-CBC
auth SHA256
user nobody
group nogroup
persist-key
persist-tun
crl-verify /etc/openvpn/crl.pem
status /var/log/openvpn-status.log 20
status-version 3
syslog
verb 3
#DuplicateCNs allow access control on a less-granular, per user basis.
#Remove # if you will manage access by user instead of device.
#duplicate-cn
# Generated for use by PiVPN.io
=============================================
::::  Client template file shown below   ::::
client
dev tun
proto udp
remote REMOTE 60111
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
tls-version-min 1.2
verify-x509-name server_IEje2NDzWM6wBpas name
cipher AES-256-CBC
auth SHA256
auth-nocache
verb 3
=============================================
::::    Recursive list of files in       ::::
::: /etc/openvpn/easy-rsa/pki shows below :::
/etc/openvpn/easy-rsa/pki/:
xxxx.ovpn
ca.crt
crl.pem
Default.txt
ecparams
extensions.temp
index.txt
index.txt.attr
index.txt.attr.old
index.txt.old
issued
openssl-easyrsa.cnf
private
renewed
revoked
safessl-easyrsa.cnf
serial
serial.old
ta.key

/etc/openvpn/easy-rsa/pki/ecparams:
prime256v1.pem

/etc/openvpn/easy-rsa/pki/issued:
xxxx.crt
server_IEje2NDzWM6wBpas.crt

/etc/openvpn/easy-rsa/pki/private:
xxxx.key
ca.key
server_IEje2NDzWM6wBpas.key

/etc/openvpn/easy-rsa/pki/renewed:
private_by_serial
reqs_by_serial

/etc/openvpn/easy-rsa/pki/renewed/private_by_serial:

/etc/openvpn/easy-rsa/pki/renewed/reqs_by_serial:

/etc/openvpn/easy-rsa/pki/revoked:
private_by_serial
reqs_by_serial

/etc/openvpn/easy-rsa/pki/revoked/private_by_serial:

/etc/openvpn/easy-rsa/pki/revoked/reqs_by_serial:
=============================================
::::            Self check               ::::
:: [OK] IP forwarding is enabled
:: [OK] Iptables MASQUERADE rule set
:: [OK] OpenVPN is running
:: [OK] OpenVPN is enabled (it will automatically start on reboot)
:: [OK] OpenVPN is listening on port 60111/udp
=============================================
::::      Snippet of the server log      ::::
Jun  1 17:31:24 raspberrypi ovpn-server[1908]: OpenVPN 2.4.0 arm-unknown-linux-gnueabihf [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Oct 14 2018
Jun  1 17:31:24 raspberrypi ovpn-server[1908]: library versions: OpenSSL 1.0.2r  26 Feb 2019, LZO 2.08
Jun  1 17:31:24 raspberrypi ovpn-server[1909]: Outgoing Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Jun  1 17:31:24 raspberrypi ovpn-server[1909]: Outgoing Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Jun  1 17:31:24 raspberrypi ovpn-server[1909]: Incoming Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Jun  1 17:31:24 raspberrypi ovpn-server[1909]: Incoming Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Jun  1 17:31:24 raspberrypi ovpn-server[1909]: TUN/TAP device tun0 opened
Jun  1 17:31:24 raspberrypi ovpn-server[1909]: TUN/TAP TX queue length set to 100
Jun  1 17:31:24 raspberrypi ovpn-server[1909]: do_ifconfig, tt->did_ifconfig_ipv6_setup=0
Jun  1 17:31:24 raspberrypi ovpn-server[1909]: /sbin/ip link set dev tun0 up mtu 1500
Jun  1 17:31:24 raspberrypi ovpn-server[1909]: /sbin/ip addr add dev tun0 10.8.0.1/24 broadcast 10.8.0.255
Jun  1 17:31:24 raspberrypi ovpn-server[1909]: Could not determine IPv4/IPv6 protocol. Using AF_INET
Jun  1 17:31:24 raspberrypi ovpn-server[1909]: Socket Buffers: R=[163840->163840] S=[163840->163840]
Jun  1 17:31:24 raspberrypi ovpn-server[1909]: UDPv4 link local (bound): [AF_INET][undef]:60111
Jun  1 17:31:24 raspberrypi ovpn-server[1909]: UDPv4 link remote: [AF_UNSPEC]
Jun  1 17:31:24 raspberrypi ovpn-server[1909]: GID set to nogroup
Jun  1 17:31:24 raspberrypi ovpn-server[1909]: UID set to nobody
Jun  1 17:31:24 raspberrypi ovpn-server[1909]: MULTI: multi_init called, r=256 v=256
Jun  1 17:31:24 raspberrypi ovpn-server[1909]: IFCONFIG POOL: base=10.8.0.2 size=252, ipv6=0
Jun  1 17:31:24 raspberrypi ovpn-server[1909]: Initialization Sequence Completed
=============================================
::::            Debug complete           ::::
:::
::: Debug output completed above.
::: Copy saved to /tmp/debug.txt
```
### Have you taken any steps towards solving your issue?
```
Yes sure, I've done all I can to confirm where the issue is and it is definitely something specific to pivpn.    By that I mean that I've checked that my routers are open and that port forwarding is working and it is.  I installed the ssh deamon and setup the required port forwards for port 22 and I could successfully access the ssh server on the raspberry pi via port 22 on my mobile with wifi disabled.  Basically any port to any device works, its just openvpn to the raspberry pi that doesn't work.

I've already reinstalled pivpn and created new certificates, none of this helps.   Constantly the issue seems to be that the connection can't be made and it just times out.    Checking the openvon log file its empty whenever I try to connect from outside the home lan.   Same is confirmed on the android openvpn app, it states timeouts, it never gets to start handshaking.

Yes I am using a custom port right now and that is the port setup in my router.   

I believe this problem started when I added a second router to my home network (not my choice but thats what had to happen).   The raspberry pi used to work fine with openvpn when my home network consisted of a single subnet and a single router with the required open port.

However I've since got a slightly more complex network setup where I have the ISPs router on 192.168.1.1 and then the local LAN is now on 192.168.2.x via another router. All devices including the RaspPi are on the 2.x network and the ISP router on the 1.x network has all ports open to the ip address of the router on the 2.x network.    To confirm again, this setup works for any other port and service on any device on my 2.x network.
```

**Comment by 4s3ti** [comment]
HI, thanm you for using PiVPN. 

> Yes sure, I've done all I can to confirm where the issue is and it is definitely something specific to pivpn.

sorry, But no it is not, specially considering this: 

> The install works fine but I can't access the vpn from an external network over the internet. Accessing from inside my home lan works fine. I've tried from my android phone and a windows PC and both connect near instantly. However with the same Android phone with wifi disabled, the connection ALWAYS times out.

worst case scenario is OpenVPN related, and most likely its a networking issue. 
all your configs seems to me ok! not spoting anything unusual on them. 

Most common reasons for Timeouts are: 

1 - ISP keeping customers behind NAT ( Seems not to be your case ) 
2 - Ports not open in routers
3 - Ports not properly forwarded. 


This brings me one question... when you opened the port in your router ... which protocol have you used? 

please make sure you have opened and forwarded port 60111 UDP 


> port proto udp
remote REMOTE 60111

**Comment by arkid** [comment]
Thanks for the response @4s3ti - yes absolutely It's always been set to UDP since day one.
![Image of my router setup](http://adam-makes-websites.com/tests/unifi/openvpn-unifi.JPG)

I completely understand why you conclude it must be something simple like this with the network and I'd agree off hand as well but I've checked, double checked and triple checked.   I can take the rule that you see in that screenshot, change the port number to 22 for ssh and instantly I have an open ssh port to my raspberry pi that works from outside the network.

What is beyond my knowledge is how to troubleshoot this further, ie is there a tool that can capture incoming traffic to a port on the raspberry pi itself that i can use to see if the traffic is reaching it ?   

Also just to check in the opensvn config, things like "topology subnet" are ok ?   I don't quite understand what they do but it just caught my attention... that doesn't need altering ?

**Comment by Giraffe1966** [comment]
@arkid Have you tried using the standard port of 1194? If that doesn't work, try again from a new network while still using 1194. It's possible somebody is blocking ephemeral and unknown port numbers, or the OpenVPN protocol or port. Also, your config file looks fine.

**Comment by Xray965** [comment]
Am having the same exact issue, just to confirm that it is not my router causing the issue, I can access pi via ssh from the outside, and can also run octopi and access it from the outside, but when using the openvpn client to access the lan, it will not do anything, calling Openvpn client accessing by profile. Did several clean reinstalls and still no luck, revoked the account reccreated the account on the vpn still nothing.

On the router tried everything to no firewall, enabling dmz still nothing. Am using no-ip and its working perfectly fine. Tried different ports still nothing.

**Comment by Giraffe1966** [comment]
Some networks block OpenVPN using deep packet inspection, which means no matter which port you use, it will be blocked. Have you tried connecting from a variety of networks using port 443 tcp? I doubt all of them will use DPI, and mistake this for HTTPS.

**Comment by orazioedoardo** [comment]
Here's how you can check whether port forwarding worked:
- Get root: `sudo -s`
- Temporarly stop OpenVPN: `systemctl stop openvpn`
- Add some firewall rule to log udp packets:
```
iptables -P INPUT ACCEPT
iptables -F
iptables -X
iptables -A INPUT -p udp --dport 60111 -j LOG
```
- Setup an UDP netcat listener: `nc -luv -p 60111`
- Open a new shell on the raspberry pi and run to watch the system log in real time: `tail -f /var/log/syslog`
- On a different computer, on a different network (for example a cellular network) try to connect to it: `nc -u -v your.public.ip 60111`
- Write something an press enter, you should see the same text on the netcat listener or at least a line like this one on the system log: `Jun  2 18:54:03 raspberrypi kernel: [  340.192176] IN=eth0 OUT= MAC=OMITTED SRC=SOMEIP DST=SOMEOTHERIP LEN=33 TOS=0x00 PREC=0x00 TTL=64 ID=61131 DF PROTO=UDP SPT=45351 DPT=60111 LEN=13`.
- If you do, then port forwarding is working. You can stop the listener and the real time log with CTRL-C, and revert the firewall by rebooting.

Note that on Linux/Mac you already have netcat but on windows you probably need to download it separately. On android I think you could use "Terminal Emulator for Android", assuming your phone has netcat built in.

**Comment by arkid** [comment]
In my I don't believe this is related to the ISP blocking the vpn and it was working fine until some months ago.   It either stopped working due to updating my Raspberry Pi with apt-get updates or due to changing my internal lan somewhat.

@orazioedoardo thanks for these details, that is really useful.   When I setup the netcat listener command I get the following, is this ok to have 0.0.0.0 ?

`root@raspberrypi:/home/pi# nc -luv -p 60111
Listening on [0.0.0.0] (family 0, port 60111)`

I don't get any logs when I do this monitoring through a remote netcat message outside of my LAN .  If I do it from within the LAN its fine.

Outside of the router what could this suggest, still anything on the Pi itself ?

**Comment by orazioedoardo** [comment]
> When I setup the netcat listener command I get the following, is this ok to have 0.0.0.0 ?
Yes it is, it means that it's accepting connections from any IP.

> Outside of the router what could this suggest, still anything on the Pi itself?

No, I think that it's your network configuration, however, try with TCP too, basically it works the same, but you replace some of the previous commands with these:
```
iptables -A INPUT -p tcp --dport 60111 -j LOG
nc -lv -p 60111
nc -v your.public.ip 60111
```
According to your [comment](https://github.com/pivpn/pivpn/issues/763#issuecomment-498033873) you forwarded both udp and tcp port 60111, are your sure that your DMZ on the first router works the same?

**Comment by arkid** [comment]
So odd, I got it working as soon as I changed to TCP.   Is this common, that there are maybe more things in the way of UDP connections working ?    All I have done on my routers to make this work is change an existing rule from UDP to TCP.

**Comment by Xray965** [comment]
I tried UDP and TCP still no go on the connection. Reset the router also and still nothing, from within the LAN I can connect, but from outside to inside still cannot.

Any ideas ?

**Comment by arkid** [comment]
> I tried UDP and TCP still no go on the connection. Reset the router also and still nothing, from within the LAN I can connect, but from outside to inside still cannot.
> 
> Any ideas ?

@Xray965 , are you running on default ports or something custom ?  I originally had a very high port number that I concluded may not have been helpful.

**Comment by Xray965** [comment]
> > I tried UDP and TCP still no go on the connection. Reset the router also and still nothing, from within the LAN I can connect, but from outside to inside still cannot.
> > Any ideas ?
> 
> @Xray965 , are you running on default ports or something custom ? I originally had a very high port number that I concluded may not have been helpful.

Ran both default and custom, but noticed something today my router wont accept TCP 443 seems like it's reserved for something, firmware level not something you can change in the routers GUI.

Check iptables on pi and nothing in there other then the default settings with everything open. I am concluding that either this is a router issue or service provider issue.

What I need to know is how to test and see if it is a service provider issue causing openvpn to not work.

**Comment by orazioedoardo** [comment]
> Ran both default and custom, but noticed something today my router wont accept TCP 443 seems like it's reserved for something, firmware level not something you can change in the routers GUI.

@Xray965 Probably 443 tcp it’s not allowed because it should be used to access the router web interface via https.

> What I need to know is how to test and see if it is a service provider issue causing openvpn to not work.

Use my steps 

> I got it working by changing the port from UDP to TCP. Is this common, that there are maybe more things in the way of UDP connections working ? All I have done on my routers to make this work is change an existing rule from UDP to TCP.

@arkid UDP is connectionless, this means that there is no connection establishment between two hosts, you just send packets and hope that they reach the destination. I don’t know if this could be a problem with your double router setup. Perhaps you could try to connect the raspberry pi straight to the ISP router and forward the udp port?

**Comment by Xray965** [comment]
Okay will try again today, thx

**Comment by 4s3ti** [comment]
No Updates, 
Closing, 
Feel free to reopen.
