### ISSUE TITLE
pivpn clients - output missaligned

### ISSUE THREAD

**Issue by m4rtini2** [pivpn/pivpn#764]
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

### Required Information

    DietPi version | 6.24.1
    Distro version | 9.9
    Kernel version | 4.19.42-v7+ #1219 SMP Tue May 14 21:20:58 BST 2019 armv7l GNU/Linux
    SBC device     | RPi 2 Model B (armv7l)

Additional Information (if applicable)

    Software title | pivpn
    accessing dietpi shell over ssh from external machine

### Issue

When the name of the client is shorter than 8 characters the output of the first column (Remote IP) starts 8 characters to early which makes the list difficult to read. It looks like a missing tab in a table. Something like this:
###
    client_89a              127.0.0.0 ...
    client7         123.533.111.111 ...
    client_8                10.10.10.10 ...
    12345           123.533.111.112 ...
###

### Steps to reproduce

in the shell execute `pivpn clients`

### Expected behaviour

list of clients in a correctly formated table. Like this:
###
    client_89a              127.0.0.0 ...
    client7                 123.533.111.111 ...
    client_8                10.10.10.10 ...
    12345                   123.533.111.112 ...
###

### Have you searched for similar issues and solutions?
    (yes/no / which issues?)
yes, no similar issues or solutions found

### Console output of      `curl -L install.pivpn.io | bash`
```
n.a.
```

### Console output of      `pivpn add` or `pivpn add nopass`
```
n.a.
```

### Console output of      `pivpn debug`
```
n.a.
```
### Have you taken any steps towards solving your issue?
```
none, except this bug report
```

**Comment by 4s3ti** [comment]
Thanks, for your input mark this as enhancement so we can fix it later on =)

**Comment by orazioedoardo** [comment]
Fixed here: https://github.com/pivpn/pivpn/commit/4466f1503c9797808d49d8cb55063bec5a79deed
```

: NOTE : The output below is NOT real-time!
:      : It may be off by a few minutes.

::: Client Status List :::
Name              Remote IP            Virtual IP      Bytes Received      Bytes Sent      Connected Since
short             127.0.0.1:45109      10.8.0.4        3,6KiB              4,1KiB          Dec 3 2019 - 17:08:14
longer12          127.0.0.1:57610      10.8.0.5        3,6KiB              4,1KiB          Dec 3 2019 - 17:08:20
short2            127.0.0.1:48756      10.8.0.2        3,6KiB              4,2KiB          Dec 3 2019 - 17:07:54
verylongname      127.0.0.1:59739      10.8.0.3        3,6KiB              4,1KiB          Dec 3 2019 - 17:08:05
```

**Comment by orazioedoardo** [comment]
Merged into master: https://github.com/pivpn/pivpn/pull/914
