### ISSUE TITLE
Official Support for Raspbian Buster

### ISSUE THREAD

**Issue by Giraffe1966** [pivpn/pivpn#775]
Raspbian Buster was released recently, and if the install script is run on Buster, it will trigger the `maybeOS_Support()` function. Has anybody tested PiVPN on Buster yet? Does it work?

**Comment by orazioedoardo** [comment]
Not out of the box but with [minimal changes](https://github.com/pivpn/pivpn/compare/master...orazioedoardo:patch-for-buster?expand=1) it works on a clean install. I got [this error](https://github.com/OpenVPN/easy-rsa/issues/261) from easy-rsa but it doesn't seem to affect the installation. As suggested [here](https://github.com/pivpn/pivpn/issues/751), iptables can still be used even though nftables is now the default. However the [wiki](https://wiki.debian.org/nftables) suggests to use the new one so we should probably upgrade to the new firewall at some point.

What's cool is that now is that openvpn 2.4.7 uses TLS 1.3, the latest version of the protocol (when supported by the client):
```
Control Channel: TLSv1.3, cipher TLSv1.3 TLS_AES_256_GCM_SHA384, 256 bit EC, curve: prime256v1
```

**Comment by TheGreatestJannet** [comment]
This is great news! Any plans to make a pull request?

**Comment by 4s3ti** [comment]
I will be away for about a month on holidays but ill be around but without anytime for coding. 
if anyone wants to make it feel free and ill merge it if it looks ok .. if in the meantime no one does it ill do it myself when I get back

**Comment by danilodiogo** [comment]
Worked for me. I received a note OS wasn't supported (since install script doesn't know yet the name nor number of this raspbian release) but I continued bravely and everything worked.

**Comment by 4s3ti** [comment]
Test branch already has support for Buster.

**Comment by manulpz** [comment]
I have a problem that puts me downloading package 14 of 15 and I get the installation of the pivpn. I have the last raspbian that with other raspberry if it had worked. any ideas?

**Comment by daaan** [comment]
Same here. At 'Retreiving file 14 of 15' it just goes back to the shell.

**Comment by Giraffe1966** [comment]
@manulpz @daaan Are you sure that you used the test branch? To install from the test branch, run:
`curl -L https://install.pivpn.io | TESTING= bash`
The space between `TESTING=` and `bash` is important.

**Comment by manulpz** [comment]
Ok. No, i using the normal. I Sony know no how yo install versión testing. Thanks.

**Comment by daaan** [comment]
> @manulpz @daaan Are you sure that you used the test branch? To install from the test branch, run:
> `curl -L https://install.pivpn.io | TESTING= bash`
> The space between `TESTING=` and `bash` is important.

No, I tried nothing and it didnt work at all ;) It was late and I didnt know how to install from the testing branch. Thanks for the intel, will try again this evening.

**Comment by whathappend1** [comment]
Raspbian Buster Lite (June 2019) fresh installed on Raspberry Pi 3.

installation with this works:
`curl -L https://install.pivpn.io`

but after connecting to the VPN i can not access any website or service. NAT not working. internet not working. also iptables -L is empty.

also i've tried to install with "TESTING" but the installation is always aborting.

` curl -L https://install.pivpn.io | TESTING= bash`

**Comment by Giraffe1966** [comment]
@whathappend1 @manulpz @daaan Sorry, that was the wrong download link. Here is the right command:
`curl -L https://raw.githubusercontent.com/pivpn/pivpn/test/auto_install/install.sh | TESTING= bash`

**Comment by daaan** [comment]
@Giraffe1966 I still have the same issue, but perhaps i'm doing something wrong. 

Somehow the pipe doesn't work like it did. When i run the command it just echoes the whole script to my console.
I tried to work around this by outputting it to a .sh file and executing that, but then i see no difference between the release and test versions.

I don't know exactly what the TESTING= bit does in the command so i cant judge what goes wrong.

**Comment by orazioedoardo** [comment]
> Somehow the pipe doesn't work like it did. When i run the command it just echoes the whole script to my console.

Piping the last command suggested by @Giraffe1966 works for me.

> I tried to work around this by outputting it to a .sh file and executing that, but then i see no difference between the release and test versions.

So, does the installation succeed or not?

> I don't know exactly what the TESTING= bit does in the command so i cant judge what goes wrong.

It install pivpn from the test branch.

**Comment by sergey-alekseev** [comment]
A week ago I followed instructions from https://github.com/pivpn/pivpn/issues/782#issuecomment-508362092 and they worked for me.

**Comment by daaan** [comment]
@orazioedoardo 
> So, does the installation succeed or not?

No it does not, like i said, still the same issue. I reinstalled Buster, ran the TESTING url command and now it gives me: 'Retrieving file 15 of 16' and then it exits to the shell again. I only did a apt-get update && upgrade before installing pivpn, also the disk is far from full. I have no clue so im downloading Jessie.

**Comment by dangrey100** [comment]
Just so I understand: stable pivpn, not the test branch, does not work on Buster, correct?

**Comment by 4s3ti** [comment]
@dangrey100 it should work, however you should get a warning.

**Comment by SirBinyamin** [comment]
Same problem on raspberry pi 4
I have the error os not supoted then continue and jump back to the shell

pi@raspberrypi:~ $ curl -L install.pivpn.io | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   178  100   178    0     0    505      0 --:--:-- --:--:-- --:--:--   507
100 55086  100 55086    0     0  86886      0 --:--:-- --:--:-- --:--:-- 86886
:::
::: sudo will be used for the install.
::: Did not detect perfectly supported OS but,
::: Continuing installation at user's own risk...
::: Verifying free disk space...
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: Your system is up to date! Continuing with PiVPN installation...
pi@raspberrypi:~ $

**Comment by StevenSeifried** [comment]
> Same problem on raspberry pi 4
> I have the error os not supoted then continue and jump back to the shell
> 
> pi@raspberrypi:~ $ curl -L install.pivpn.io | bash
> % Total % Received % Xferd Average Speed Time Time Time Current
> Dload Upload Total Spent Left Speed
> 100 178 100 178 0 0 505 0 --:--:-- --:--:-- --:--:-- 507
> 100 55086 100 55086 0 0 86886 0 --:--:-- --:--:-- --:--:-- 86886
> :::
> ::: sudo will be used for the install.
> ::: Did not detect perfectly supported OS but,
> ::: Continuing installation at user's own risk...
> ::: Verifying free disk space...
> :::
> ::: Checking apt-get for upgraded packages.... done!
> :::
> ::: Your system is up to date! Continuing with PiVPN installation...
> pi@raspberrypi:~ $

Try curl -L https://install.pivpn.io | TESTING=1 bash

**Comment by orazioedoardo** [comment]
@StevenSeifried that downloads the script from the master branch, use [this](https://github.com/pivpn/pivpn/issues/775#issuecomment-510686097) instead.

**Comment by rvath** [comment]
I have the problem with the installation beginning and then exiting back shell also.  tried all of the links and alternates above.  just completed Buster upgrades prior to attempting installation.  Any advice?  TIA

**Comment by 4s3ti** [comment]
> I have the problem with the installation beginning and then exiting back shell also. tried all of the links and alternates above. just completed Buster upgrades prior to attempting installation. Any advice? TIA

hmmm... try clean Buster instead of upgrading?

**Comment by MembershipExcel** [comment]
Trying to install pivpn on a fresh install (rasbian full from NOOBS). I get a" :~ $ curl -L https://install.pivpn.io                        curl: (6) Could not resolve host: install.pivpn.io"
Error.

**Comment by Braveshock** [comment]
When will OpenVPN work with Buster officially?

**Comment by muibusan** [comment]
And when will http://www.pivpn.io/ be updated with notes and hints on buster compatibility?

**Comment by 4s3ti** [comment]
@Braveshock  its supported already officially just has not been pushed yet to the master branch, I still didn't had the time to make the push as I want to test everything properly first. I have been busy lately but I expect to be full throttle back in less than a month time. 

@muibusan as far as I know and unfortunately no one has access to the website at the moment, I think maybe @james-lasersoft @0-kaladin have full access to the project. 

Actually ... @james-lasersoft @0-kaladin can I get full access to it? looks I am the only one that keeps coming back here.

**Comment by Braveshock** [comment]
Hey,
Thanks for the update! I really appreciate.
    	
    	

    	PozdrawiamMateusz
    
  




On Mon, Aug 12, 2019 at 10:39 AM -0400, "4s3ti" <notifications@github.com> wrote:












@Braveshock  its supported already officially just has not been pushed yet to the master branch, I still didn't had the time to make the push as I want to test everything properly first. I have been busy lately but I expect to be full throttle back in less than a month time.


@muibusan as far as I know and unfortunately no one has access to the website at the moment, I think maybe @james-lasersoft @0-kaladin have full access to the project.


Actually ... @james-lasersoft @0-kaladin can I get full access to it? looks I am the only one that keeps coming back here.

**Comment by G0nz0uk** [comment]
Hi guys - I know it's only been 3 days, but it's it ok to run on Raspbian Buster Lite or worth waiting a few more days until the official release on http://www.pivpn.io/ ?

**Comment by 4s3ti** [comment]
> 
> 
> Hi guys - I know it's only been 3 days, but it's it ok to run on Raspbian Buster Lite or worth waiting a few more days until the official release on http://www.pivpn.io/ ?

@G0nz0uk seems there are some misconceptions on your side... first PiVPN is not a VPN per se .. is just an installer ... so there is no biggie from running it now or not! 

If you install OpenVPN using pivpn main branch it will work equally as good, you will just get a warning that the version might not be supported, you continue and it should install. 

If you want the latest changes you can do as stated here in this thread as in our wiki as well, and  install OpenVPN using pivpn test branch. 

`curl -L https://install.pivpn.io | TESTING=1 bash`

actually, I even appreciate that you install using the test branch and report back if you found any issues, so I can consider them the time I test it before merging with the main branch. 


thank you.

**Comment by orazioedoardo** [comment]
@4s3ti https://github.com/pivpn/pivpn/issues/775#issuecomment-510686097

**Comment by 4s3ti** [comment]
@orazioedoardo thanks a lot for the correction! missed that one =/ 
Edited already and changed the Wiki! 

Thanks a mil!

**Comment by r3z4-test** [comment]
@4s3ti I tried test branch 
`curl -L https://raw.githubusercontent.com/pivpn/pivpn/test/auto_install/install.sh | TESTING= bash`
for a few minutes it stops after key generation. Output is:

> DH parameters of size 2048 created at /etc/openvpn/easy-rsa/pki/dh.pem
> 
> 
> Note: using Easy-RSA configuration from: ./vars
> 
> Using SSL: openssl OpenSSL 1.1.1c  28 May 2019
> Using configuration from /etc/openvpn/easy-rsa/pki/safessl-easyrsa.cnf
> 
> An updated CRL has been created.
> CRL file: /etc/openvpn/easy-rsa/pki/crl.pem
> 
> net.ipv4.ip_forward = 1
> run-parts: executing /usr/share/netfilter-persistent/plugins.d/15-ip4tables save
> run-parts: executing /usr/share/netfilter-persistent/plugins.d/25-ip6tables save
> cp: der Aufruf von stat für '/tmp/OLD_UFW' ist nicht möglich: Datei oder Verzeichnis nicht gefunden
cp: file /tmp/OLD_UFW not found
I choose an update on script start. 

Are there any infos about suppoting nftables?
Thanks for your script!

**Comment by orazioedoardo** [comment]
I think you installed the test branch over the stable one. Try Reconfigure in such case since the test branch copies a file (`/tmp/OLD_UFW`) not available on the stable branch.

**Comment by G0nz0uk** [comment]
Just to let you know I did a fresh install using:

curl -L https://raw.githubusercontent.com/pivpn/pivpn/test/auto_install/install.sh | TESTING= bash

And all works, thanks.

**Comment by r3z4-test** [comment]
@orazioedoardo  and @G0nz0uk : thanks for the help. Yes, I installed the test branch over the stable. I tried  a reconfigure now, looks good now!

**Comment by lllluke** [comment]
If I use the PiVPN script to install OpenVPN on my RPi3 running Raspbian Buster, a DH key gets calculated, whereas on Raspbian Strech automatically the elliptic curve encryption is used.

How am I able the use elliptic curve encryption on Raspbian Buster?

**Comment by Joery** [comment]
Anyone else getting the following error when installing the testing branch?
`E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)`
`E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?`

No error when I'm using the stable branch, but the client can't connect:
`Server poll timeout, trying next remote entry` on OpenVPN Connect (Android)

Getting both errors on a fresh Raspbian Buster install with the latest updates. No errors when I installed it on Stretch a while ago.

**Comment by 4s3ti** [comment]
test branch merged into master. 
Buster should be now fully supported. 

closing.

**Comment by muibusan** [comment]
@4s3ti Thank you very much for all the effort and the numerous latest changes to the master branch! :) Great work and project! I am really happy to have PiVPN on my rPi. 🥇

**Comment by FredMa01** [comment]
All is ok now with Buster on raspbian but also on Debian server ! All thanks...

**Comment by dawn2duskpt** [comment]
Hi. I've installed the script on a fresh raspbian buster. After reboot the system doesn't come online.

**Comment by 4s3ti** [comment]
> Hi. I've installed the script on a fresh raspbian buster. After reboot the system doesn't come online.

How do you expect anyone to help you with that? 

Please, read the documentation, and  make a popper issue report

**Comment by dawn2duskpt** [comment]
> > Hi. I've installed the script on a fresh raspbian buster. After reboot the system doesn't come online.
> 
> How do you expect anyone to help you with that?
> 
> Please, read the documentation, and make a popper issue report

I've read the documentation. There is no similar issue described on the faq topics. When I'm able to boot physically the machine I'll try to read the logs and post them here!

**Comment by orazioedoardo** [comment]
@dawn2duskpt The only way i can think PiVPN could cause this is that it could have messed with DHCP settings. Maybe hook the Pi to a monitor and see what's going on.

**Comment by dawn2duskpt** [comment]
thanks! that’s what I will do. I’ve already set the pi with static ip before pivpn.
