### ISSUE TITLE
Question : Client Cert # of days until expiry

### ISSUE THREAD

**Issue by jpknz** [pivpn/pivpn#784]
This is a question rather than a bug/issue. I've just noticed that on a new install of PiVPN when creating a new client is slightly different in that it asks for the number of days before expiry whereas before it didn't. I couldn't find any info on this so am asking here. 

What was the default expiry previously (if any)?
Why was just under 3 years chosen as the expiry period?

Thanks

**Comment by orazioedoardo** [comment]
> I've just noticed that on a new install of PiVPN when creating a new client is slightly different in that it asks for the number of days before expiry whereas before it didn't. I couldn't find any info on this so am asking here.

See https://github.com/pivpn/pivpn/pull/731.

> What was the default expiry previously (if any)?

I think 10 years.

> Why was just under 3 years chosen as the expiry period?

It's just the [default value](https://github.com/OpenVPN/easy-rsa/blob/6b7b6bf1f0d3c9362b5618ad18c66677351cacd1/easyrsa3/vars.example#L126) for easy-rsa if you don't set one.

**Comment by orazioedoardo** [comment]
Oh wait, now you got me thinking: given that by default certificates last for 1080 days, this means that the server certificate created at the time of installation lasts just as long. For this reason setting a client expiration period of over 1080 days is useless since the server expires sooner! I might send a pull request later next week...

**Comment by jpknz** [comment]
Ahh thanks.
Think I created my server cert outside of pivpn anyway and set it to 10 years (don't remember the exact process but it was directly using easy-rsa I think). I just use PiVpn for the easy add/remove client scripts

**Comment by 4s3ti** [comment]
test branch merged into master. 
closing.
