### ISSUE TITLE
- is no longer allowed in client 

### ISSUE THREAD

**Issue by jpknz** [pivpn/pivpn#786]
Using `pivpn -a nopass -n name-here -d 365` the response recieved is `Name can only contain alphanumeric characters and these characters (.-@_).`

`@` and `_` work as expected but `-` gives the above error

**Comment by orazioedoardo** [comment]
Thanks, apparently, there is a missing `\` before `-` [here](https://github.com/pivpn/pivpn/blob/8e3a95152412a9d35b67d51bfc80379350815252/scripts/makeOVPN.sh#L150).

**Comment by tycrek** [comment]
This error occurs in interactive mode as well: `pivpn add nopass`

**Comment by mquirin** [comment]
> Thanks, apparently there is a missing `\` right before the fourth `-` [here](https://github.com/pivpn/pivpn/blob/8e3a95152412a9d35b67d51bfc80379350815252/scripts/makeOVPN.sh#L150).

I think this works differently than you intend: After patching makeOVPN.sh with the change
you propose it also accepts '\' as a valid char (e.g. 'foo\bar' is not refused).

I think a better pattern is this: `[^a-zA-Z0-9.@_-]`

Have a look here as well (according to this there is no real escaping within character classes in Posix ERE (which IIRC is what bash is using)):
https://stackoverflow.com/questions/399078/what-special-characters-must-be-escaped-in-regular-expressions

**Comment by orazioedoardo** [comment]
Thanks for the insights @mquirin, so since `-` is a metacharacter used to represent a range, you have to place it just after `^` or as the last character if you want the shell to interpret it as a literal `-`.

**Comment by 4s3ti** [comment]
Test branch merged into master. 
Closing
