### ISSUE TITLE
Need help, simple question

### ISSUE THREAD

**Issue by Nyflheim** [pivpn/pivpn#79]
So I installed pivpn, rebooted, and then created a profile. I send the profile to my email and open it through OpenVPN connect and try to connect, but it says connection timeout? I turned off wifi and tried with my data and it still says connection timeout.

After installation do I need to do anything else? What am I missing?

**Comment by guydeke** [comment]
Probably because you are on your own internet, connecting tot your vpn and tell the vpn to go to (the same) internet connection. Try to connect to your home vpn from e.g. your neighbour / coffee bar / work etc.

**Comment by 0-kaladin** [comment]
also did you port forward from your router to the Pi?
