### ISSUE TITLE
Just a feedback

### ISSUE THREAD

**Issue by anselal** [pivpn/pivpn#790]
Tested on Debian 10 and runs without any issues

**Comment by orazioedoardo** [comment]
Default install or test branch? Does `pivpn -d`‘s give any error?

**Comment by anselal** [comment]
Default install i guess. I used the curl command to install it.
Is it ok to paste here the output of `pivpn -d` or has it sensitive informations?

**Comment by orazioedoardo** [comment]
> Is it ok to paste here the output of pivpn -d or has it sensitive informations?
The public ip/domain name of the server should be censored (replaced with “REMOTE”), while the last section, the server log could contain some IPs of the clients, feel free to hide them, other information is not sensitive. By the way I don’t really need the output, just wanted to know whether “Self check” reports “[OK]” to everything.
How about this one too? I would like to know if by default debian 10 is using nftables or not.
`update-alternatives --display iptables`

**Comment by anselal** [comment]
Self check returns OK.

Output of ` update-alternatives --display iptables`:

```sh
iptables - auto mode
  link best version is /usr/sbin/iptables-nft
  link currently points to /usr/sbin/iptables-nft
  link iptables is /usr/sbin/iptables
  slave iptables-restore is /usr/sbin/iptables-restore
  slave iptables-save is /usr/sbin/iptables-save
/usr/sbin/iptables-legacy - priority 10
  slave iptables-restore: /usr/sbin/iptables-legacy-restore
  slave iptables-save: /usr/sbin/iptables-legacy-save
/usr/sbin/iptables-nft - priority 20
  slave iptables-restore: /usr/sbin/iptables-nft-restore
  slave iptables-save: /usr/sbin/iptables-nft-save
```

**Comment by 4s3ti** [comment]
this is now on mainbranch .. PiVPN installing OpenVPN under Debian 10.

**Comment by anselal** [comment]
Cool !!
