### ISSUE TITLE
iOS Client OVPN format issue

### ISSUE THREAD

**Issue by pr0z4k** [pivpn/pivpn#792]
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

When creating a new profile, and importing to the OpenVPN client in iOS v3.0.2 the profile will not connect.

### Have you searched for similar issues and solutions?
   yes

### Console output of      `curl -L install.pivpn.io | bash`
```
  Not needed, not about the install
```

### Console output of      `pivpn add` or `pivpn add nopass`
```
  Profiles are created properly in the pivpn host
```

### Console output of      `pivpn debug`
```
No need, solution is below
```
### Have you taken any steps towards solving your issue?
```
  Found the guide in the OpenVPN help website about unified file, the file structure needs to be as follows: 
Descriptors
....
Descriptors
<ca>
CERT
</ca>
<cert>
CERT
</cert>
<key>
KEY
</key>
**key-direction 1**
**<tls-auth>**
KEY
**</tls-auth>**

Original created file would have the value key-direction 1 in the header for descriptors AND tls-auth was tls-crypt. 

After changing the format in the unified file (ovpn export) it was loaded in the iOS client and is working as expected.

```

**Comment by orazioedoardo** [comment]
The file is already in the [unified format](https://github.com/pivpn/pivpn/blob/8e3a95152412a9d35b67d51bfc80379350815252/scripts/makeOVPN.sh#L238-L269).

> Original created file would have the value key-direction 1 in the header for descriptors AND tls-auth was tls-crypt.

So the file created by pivpn had `key-direction 1` and `<tls-crypt>` at the same time?

**Comment by pr0z4k** [comment]
Yes, the Out of the box profile generated had the following format:

client
dev tun
proto udp
remote HOSTNAME PORT
resolve-retry infinite
nobind
persist-key
persist-tun
key-direction 1
remote-cert-tls server
tls-version-min 1.2
verify-x509-name NAME
cipher CIPHER
auth CIPHER
auth-nocache
verb 3
<ca>
CERTIFICATE
</ca>
<cert>
CERTIFICATE
</cert>
<key>
key
</key>
<tls-crypt>
KEY
</tls-crypt>

The problem is that when imported to the iOS application, this format will not work and will stay in disconnected mode. Followed the guide https://openvpn.net/vpn-server-resources/faq-regarding-openvpn-connect-ios/ here, in the section "i am having trouble importing my .ovpn file"

when modified the exported site as in the initial submission (moving the key-direction value and changing tls-auth instead of tls-crypt the profile was able to connect while using the iOS application.

**Comment by orazioedoardo** [comment]
I'm not able to replicate. Are you running Raspbian Buster? Can you post the debug output (omit client IPs in the server log)?

**Comment by pr0z4k** [comment]
Using debian 9.9 kernel 4.19.57

Please let me know if this helps, can also create a test user (fresh) if this helps. 

Finally, if this is a single issue that i'm only experiencing it's fine, just tought about reporting in case more people were experiencing the same thing.

Thank you!
[debug.txt](https://github.com/pivpn/pivpn/files/3432634/debug.txt)

**Comment by orazioedoardo** [comment]
Looks like you chose not to use 2.4 features but for some reason `/etc/pivpn/TWO_POINT_FOUR` had been created, resulting in client configs being created with tls-crypt. I can't think of a way to ask questions to get to the root cause for now, so I'll just leave you with a command to make sure that future clients are created with tls-auth `sudo rm /etc/pivpn/TWO_POINT_FOUR`.

**Comment by pr0z4k** [comment]
Thank you! let me know if theres anything else i can help with

**Comment by 4s3ti** [comment]
Could not replicate. ... /etc/pivpn/TWO_POINT_FOUR is not being created if 2.4 is not accepted.
