### ISSUE TITLE
How to disable traffic routing based on profile

### ISSUE THREAD

**Issue by ashubisht** [pivpn/pivpn#793]
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [ ] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

### Issue
I need to restrict traffic routing based on profile at pivpn server side. I see instruction to remove at client side, or restrict traffic for all by removing redirect-gateway line from /etc/openvpn/server.conf
Can this be done on server side based on profile as client may override the setting .

### Have you searched for similar issues and solutions?
    (yes/no / which issues?)

### Console output of      `curl -L install.pivpn.io | bash`
```
  pivpn installed successfully with two profiles created and routing traffic via pivpn
```

### Console output of      `pivpn add` or `pivpn add nopass`
```
  Asked for password and successfully created ovpn profile
```

### Console output of      `pivpn debug`
```
  Not sure on how or what to debug in this scenario.
```

**Comment by orazioedoardo** [comment]
Not PiVPN related [but](https://github.com/pivpn/pivpn/issues/692)...

**Comment by mwoolweaver** [comment]
this would probably require setting up 2 vpn servers on the same machine which isn't hard to do at all. Of course they wouldn't be able to use the same port number but you could have the desired setup.

**Comment by ashubisht** [comment]
> this would probably require setting up 2 vpn servers on the same machine which isn't hard to do at all. Of course they wouldn't be able to use the same port number but you could have the desired setup.
> 
> I am running a similar setup but i'm using it for a split tunnel and a full tunnel.
> 
> ![Screen Shot 2019-07-23 at 5 08 06 PM](https://user-images.githubusercontent.com/5729320/61751046-a6eaf500-ad6c-11e9-99f4-4ee676e23e80.png)

This will be odd. I am guessing it will have performance issues as we will be running two servers for this?

**Comment by ashubisht** [comment]
> Not PiVPN related [but](https://github.com/pivpn/pivpn/issues/692)...

I believe this happens on client side inside file which I will be distributing for connection. This means client can simply overwrite that file and allow itself to shape its traffic from pivpn server?

**Comment by orazioedoardo** [comment]
> I believe this will happen on client side inside file which will be ditributed for connection. this means client can overwrite the file and allow itself to shape its traffic via pivpn server?

Yes, however if you are worried of “potentially malicious clients”, you could configure openvpn to set them static ips and then tweak the iptables firewall to selectively route packets based on the source IP.

**Comment by mwoolweaver** [comment]
@ashubisht I'm not good with iptables rules so that was the easiest approach. I don't do anything that requires a ton of bandwidth so works reliably for me.

**Comment by 4s3ti** [comment]
Not PiVPN Related and some solutions have been provided, hence closing this.
