### ISSUE TITLE
Client connects, but no internet access

### ISSUE THREAD

**Issue by Henrytje** [pivpn/pivpn#796]
Hi there,

Started today with Pivpn and installed it using Jessie. I successfully connected my Android phone using the client ovpn file. However, when using the openvpn client on my android phone, it can't connect to the internet. 

Log of the client: 
19:39:14.966 -- ----- OpenVPN Start -----

19:39:14.970 -- EVENT: CORE_THREAD_ACTIVE

19:39:14.990 -- Frame=512/2048/512 mssfix-ctrl=1250

19:39:15.001 -- UNUSED OPTIONS
4 [resolv-retry] [infinite] 
5 [nobind] 
6 [persist-key] 
7 [persist-tun] 
11 [verify-x509-name] [server_WXyX2zjIT3ZYexAq] [name] 
14 [auth-nocache] 
15 [verb] [3] 

19:39:15.002 -- EVENT: RESOLVE

19:39:15.502 -- Contacting 83.87.71.183:1194 via UDP

19:39:15.503 -- EVENT: WAIT

19:39:15.507 -- Connecting to [raspigetaart.duckdns.org]:1194 (83.87.71.183) via UDPv4

19:39:15.567 -- EVENT: CONNECTING

19:39:15.572 -- Tunnel Options:V4,dev-type tun,link-mtu 1569,tun-mtu 1500,proto UDPv4,keydir 1,cipher AES-256-CBC,auth SHA256,keysize 256,tls-auth,key-method 2,tls-client

19:39:15.575 -- Creds: UsernameEmpty/PasswordEmpty

19:39:15.578 -- Peer Info:
IV_GUI_VER=OC30Android
IV_VER=3.2
IV_PLAT=android
IV_NCP=2
IV_TCPNL=1
IV_PROTO=2
IV_AUTO_SESS=1

19:39:16.403 -- VERIFY OK : depth=1
cert. version     : 3
serial number     : A8:50:A8:35:1B:D3:F7:F4
issuer name       : CN=ChangeMe
subject name      : CN=ChangeMe
issued  on        : 2019-07-25 05:57:06
expires on        : 2029-07-22 05:57:06
signed using      : RSA with SHA-256
RSA key size      : 2048 bits
basic constraints : CA=true
key usage         : Key Cert Sign, CRL Sign

19:39:16.410 -- VERIFY OK : depth=0
cert. version     : 3
serial number     : C7:18:E6:CE:FB:3A:C5:E9:B2:45:2E:33:14:3F:94:5F
issuer name       : CN=ChangeMe
subject name      : CN=server_WXyX2zjIT3ZYexAq
issued  on        : 2019-07-25 05:57:25
expires on        : 2022-07-09 05:57:25
signed using      : RSA with SHA-256
RSA key size      : 2048 bits
basic constraints : CA=false
subject alt name  : server_WXyX2zjIT3ZYexAq
key usage         : Digital Signature, Key Encipherment
ext key usage     : TLS Web Server Authentication

19:39:17.819 -- SSL Handshake: TLSv1.2/TLS-DHE-RSA-WITH-AES-256-GCM-SHA384

19:39:17.822 -- Session is ACTIVE

19:39:17.823 -- EVENT: GET_CONFIG

19:39:17.830 -- Sending PUSH_REQUEST to server...

19:39:17.875 -- OPTIONS:
0 [dhcp-option] [DNS] 
1 [dhcp-option] [DNS] 
2 [block-outside-dns] 
3 [redirect-gateway] [def1] 
4 [route-gateway] [10.8.0.1] 
5 [topology] [subnet] 
6 [ping] [1800] 
7 [ping-restart] [3600] 
8 [ifconfig] [10.8.0.2] [255.255.255.0] 

19:39:17.880 -- PROTOCOL OPTIONS:
  cipher: AES-256-CBC
  digest: SHA256
  compress: NONE
  peer ID: -1

19:39:17.894 -- EVENT: ASSIGN_IP

19:39:17.901 -- Error parsing dhcp-option: [dhcp-option] [DNS]  : option_error: option 'dhcp-option' must have exactly 3 arguments

19:39:17.912 -- Error parsing dhcp-option: [dhcp-option] [DNS]  : option_error: option 'dhcp-option' must have exactly 3 arguments

19:39:17.913 -- Google DNS fallback enabled

19:39:17.988 -- Connected via tun

19:39:17.989 -- EVENT: CONNECTED info='@raspigetaart.duckdns.org:1194 (83.87.71.183) via /UDPv4 on tun/10.8.0.2/ gw=[10.8.0.1/]' trans=TO_CONNECTED

OpenVPN server.conf
dev tun
proto udp
port 1194
ca /etc/openvpn/easy-rsa/pki/ca.crt
cert /etc/openvpn/easy-rsa/pki/issued/server_WXyX2zjIT3ZYexAq.crt
key /etc/openvpn/easy-rsa/pki/private/server_WXyX2zjIT3ZYexAq.key
dh /etc/openvpn/easy-rsa/pki/dh2048.pem
topology subnet
server 10.8.0.0 255.255.255.0
# Set your primary domain name server address for clients
push "dhcp-option DNS "
push "dhcp-option DNS "
# Prevent DNS leaks on Windows
push "block-outside-dns"
# Override the Client default gateway by using 0.0.0.0/1 and
# 128.0.0.0/1 rather than 0.0.0.0/0. This has the benefit of
# overriding but not wiping out the original default gateway.
push "redirect-gateway def1"
client-to-client
keepalive 1800 3600
remote-cert-tls client
tls-version-min 1.2
tls-auth /etc/openvpn/easy-rsa/pki/ta.key 0
cipher AES-256-CBC
auth SHA256
user nobody
group nogroup
persist-key
persist-tun
crl-verify /etc/openvpn/crl.pem
status /var/log/openvpn-status.log 20
status-version 3
syslog
verb 3
#DuplicateCNs allow access control on a less-granular, per user basis.
#Remove # if you will manage access by user instead of device.
#duplicate-cn
# Generated for use by PiVPN.io

.ovpn file

client
dev tun
proto udp
remote raspigetaart.duckdns.org 1194
resolv-retry infinite
nobind
persist-key
persist-tun
key-direction 1
remote-cert-tls server
tls-version-min 1.2
verify-x509-name server_WXyX2zjIT3ZYexAq name
cipher AES-256-CBC
auth SHA256
auth-nocache
verb 3

**Comment by edalquist** [comment]
I think this may be the same as https://github.com/pivpn/pivpn/issues/799 where ufw on Jessie doesn't support the route setup.

**Comment by orazioedoardo** [comment]
Please, fill the issue template first.

**Comment by RevealedFrom** [comment]
I ran used `pivpn` to install OpenVPN server on two Pi's on the same day. One worked flawlessly. For the other, clients connect fine but just could not access the Internet. It turned out that NAT wasn't running. The machine where the VPN server resides has to perform NAT for the client's traffic in order to forward them onto the LAN and out to the Internet.

My problem was solved with just this command:

```
iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE
```

I hope this can help you. You may have to change the IP address/mask and interface accordingly.

**Comment by orazioedoardo** [comment]
No updates in a while, closing...
