### ISSUE TITLE
VPN over ISP with private NAT'ed IP

### ISSUE THREAD

**Issue by n5yzv** [pivpn/pivpn#797]
Here is the topology:  Real Static IP address -> NAT'ed all ports/protocols to Private IP on Firewall --> NAT'ed 1194/UDP to PiVPN.  
On Client Getting:  Core Exception:  Exception Error: PEM_PASSWORD_FAIL:  PolarSSL: error parsing

In logs, I don't see the connection happening.  I have other UDP ports NAT'ed through without issue.  Client is connecting to the correct public IP Address.  Suggestions?

**Comment by n5yzv** [comment]
Well, tcpdump reveals nothing.  ie: no packets arriving at the interface, so it is firewall or ISP related.  So nevermind.

**Comment by Giraffe1966** [comment]
What client are you using (it appears to be a client issue, not a PiVPN issue)? The default OpenVPN client doesn't use PolarSSL (now mbed TLS) for cryptographic functions, it uses OpenSSL (which is what makes me think you have a different client). Also, it appears you are having some password issues, which would prevent the client from initiating the connection. Also, please provide the information in the issue template, as without it it is much harder to debug your problem.

**Comment by n5yzv** [comment]
I figured it out.  It didn't like a "dash" in the profile user name.  Thanks for the efforts!

**Comment by 4s3ti** [comment]
Thanks for using PiVPN, 

closing, please re-open if you still need help. 


Kind Regards.
