### ISSUE TITLE
ufw setup fails on raspbian Jessie

### ISSUE THREAD

**Issue by edalquist** [pivpn/pivpn#799]
- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

debug output:

```
net.ipv4.ip_forward = 1
::: Detected UFW is enabled.
::: Adding UFW rules...
ERROR: Invalid syntax
::: UFW configuration completed.
dig failed, now trying to curl checkip.amazonaws.com
::: Using Google servers.
sleep 0.1
::: Install Complete...
::: Restarting services...
Synchronizing state for openvpn.service with sysvinit using update-rc.d...
Executing /usr/sbin/update-rc.d openvpn defaults
Executing /usr/sbin/update-rc.d openvpn enable
::: Flushing writes to disk...
::: done.
```

It looks like the `route` command doesn't exist on the version of ufw packaged in Jessie: https://manpages.debian.org/jessie/ufw/ufw.8.en.html

Upgrading to raspbian Stretch fixed it: https://manpages.debian.org/stretch/ufw/ufw.8.en.html

Maybe the installer needs a min-ufw-version check?

**Comment by orazioedoardo** [comment]
Are you able to pinpoint the exact version that started supporting the `route` command?

**Comment by 4s3ti** [comment]
fix pushed into test branch.

**Comment by edalquist** [comment]
Thanks for the fix! It looked like every version in the Jessie repo is pre-route support. I didn't bother trying to install a later .deb version and just upgraded my base raspbian install to Stretch (which also gave me modern versions of a bunch of other packages)

**Comment by 4s3ti** [comment]
@edalquist @orazioedoardo

Test branch Merged into Master.
closing
