### ISSUE TITLE
Code review, improvements, esp in regular expressions

### ISSUE THREAD

**Issue by 0-kaladin** [pivpn/pivpn#8]
I'm no guru in regular expressions.  There is surely pieces of this code that can be optimized and made more robust.  Looking for a guru to review and submit any pull requests.

**Comment by daeric** [comment]
This is great. I just tested it out and it's phenomenal. The only things I'd suggest are; when choosing to change the port, maybe add whether it should be TCP or UDP. Would be a nice addition for the user who is behind a restrictive firewall since most do not block TCP 443. You'd have to change the Default.txt to use "proto tcp-client" and server_config.txt to use "proto tcp-server" if they chose TCP. 

Also, the 

"# your local subnet 
push route 0.0.0.0 0.0.0.0"

in the sever.conf should be something like 192.168.1.0 255.255.255.0 or you'll get some "route is not canonical" errors. Seems to still work with your approach though.

**Comment by 0-kaladin** [comment]
Yes I did always consider letting user chose TCP or UDP.  However I didn't want someone uneducated thinking TCP would be better.  UDP 443 isn't generally blocked and it is much better to use UDP has your transport for the tunnel since you will have TCP traffic within the tunnel anyway.  Having TCP tunnel with TCP traffic encapsulated within is a lot of 2 way overhead and can slow down the tunnel which is already running on a raspberry pi...  So I left out that choice for now as I purposely wanted to abstract the transport used from the mainly non technical user base of this script.

And yes the local subnet that the config wants ends up with the IP address which will throw warns/errors in logs.  I should fix that though as you noticed the server does just take the IP and use the subnet it is on, it just throws a warning about it first.

**Comment by maxfan8** [comment]
I have to agree. This project is amazing. You could have a little bit of text telling the user the pros and cons of TCP and UDP. That way, the ordinary uneducated user would become educated. You could then make the default UDP, so if a user came along and needed TCP, they could set that up.

**Comment by redfast00** [comment]
@maxfan: this was already solved :D Thanks for your advice though.

**Comment by jellemdekker** [comment]
I can help out with regular expressions. Would you like me to go over the code, improve where I think is necessary and then make a pull request?

**Comment by 0-kaladin** [comment]
That's always welcome!

**Comment by corbolais** [comment]
Just did some PR including support for Debian bullseye, sid, improvements on update.sh and shellchecking install.sh.

**Comment by 4s3ti** [comment]
Guess this is a living thing at this point doesn't makes more sense to have it around, specially with the new changes.

**Comment by corbolais** [comment]
Sorry, could you elaborate on the part where you're talking about the `living thing` and` to have it around`, with what `new changes`?

I honestly have no clue what you mean by that.

Thanks.

**Comment by 0-kaladin** [comment]
I orig created this to get someone to help with code review or optimizations.  This is constantly being changes/updated (living thing) so it doesn't make sense to leave an abstract issue open at this point.

**Comment by 4s3ti** [comment]
> I orig created this to get someone to help with code review or optimizations. This is constantly being changes/updated (living thing) so it doesn't make sense to leave an abstract issue open at this point.

exactly! =)
