### ISSUE TITLE
Raspberry pi4 with Debian Buster/Raspian Buster

### ISSUE THREAD

**Issue by siniztr** [pivpn/pivpn#800]
This is not an Issue, more a Thank you. 

I can confirm after having just run the installation that PiVPN works with Raspberry Pi4 with Raspian Buster. The entire installation ran through and OpenVPN is successfully running for me. 

My compliments to the contributors.

You may close this ticket.

**Comment by parthdmaniar** [comment]
Hi could you kindly confirm if you used the test branch (curl -L https://raw.githubusercontent.com/pivpn/pivpn/test/auto_install/install.sh | TESTING= bash)  or used general availability - curl -L https://install.pivpn.io | bash

**Comment by doctorvenables** [comment]
I installed PiVPN on RPi3B in buster yesterday and appears to be working on general availability.
It was a fresh buster install.
Also have PiHole installed and it gets rid of adverts if I log in to VPN via mobile phone data and browse.
Requests for browsing timed out when I went into a store and used their wifi though.

**Comment by siniztr** [comment]
I used the general availability install code from the website. It installed without any errors and everything runs perfect for me.

**Comment by parthdmaniar** [comment]
Did using general branch give you a warning that installation has not been tested on the OS (buster)?

Using the production branch does not prompt me by **default** to have ECC encryption. It defaults to RSA, which is computationally heavy. For an RPi, this may add up to be a concern if there are multiple simultaneous connections.

ECC is also extremely secure when compared to RSA. 512 bits of ECC is equivalent to 15360 bits of RSA key (you can only create up to 4096 bit key).

Hence using the test branch is the only way to get an optimal installation of OpenVPN on RPi. 

Could someone kindly confirm?

**Comment by orazioedoardo** [comment]
> Did using general branch give you a warning that installation has not been tested on the OS (buster)?

Yes

> Using the production branch does not prompt me by default to have ECC encryption.

True ([reason](https://github.com/pivpn/pivpn/issues/801#issuecomment-517896579))

**Comment by 4s3ti** [comment]
Great info! thanks a lot to everyone! 
Closing this threat for now.

**Comment by siniztr** [comment]
> Did using general branch give you a warning that installation has not been tested on the OS (buster)?

Yes it did say this.

As to your second question. The question did not come up, and I did notice in the installation logs that it did indeed create the certificates using RSA. 

Good to know that the test branch uses ECC. I have to reconfigure the OpenVPN on the Pi4 because it is being moved to a different location (the IP will change). I will remove the OpenVPN and reinstall using the test branch. I can give you feed back on the installation and testing of it afterwards if you want.
