### ISSUE TITLE
tls-crypt vs tls-auth

### ISSUE THREAD

**Issue by tigernero79** [pivpn/pivpn#801]
Since I updated my pi3 to the buster and installed pivpn I noticed that automatically having removed the tls-crypt encryption for "2048 bit OpenVPN static key"
now by tagging the "tls-auth" tag with stretch instead the certificate generated it with the tls-crypt tag.

tls-crypt allows you to connect to your vpn even with perimeter firewalls. see Italian post that gives its free wifi but blocks openvpn on qlc port. sniffs the packets I suppose.

is it possible to make the "2048 bit OpenVPN static key 1" be created with the tls-crypt tag and not tls auth as it already does with raspbian stretch? instead with buster you have reset tls auth?

**Comment by orazioedoardo** [comment]
On raspbian buster pivpn uses tls-auth because the script logic uses tls-crypt only if that the os version is stretch. This has been fixed in the test branch, that you can install with this command: https://github.com/pivpn/pivpn/issues/775#issuecomment-510686097

**Comment by tigernero79** [comment]
thanks for the news.  so when will the testing branch become stable with tls crypt?  I solved by editing the server.conf file and giving the certificate the tls-crypt tag and modifying the certificate ta in the client ovpn with tls-crypt tag and it works.  giovanni from italy

**Comment by d0nlab** [comment]
TLS crypt in the test branch is fine. I used the test branch to install on buster and no issues.

**Comment by tigernero79** [comment]
Url correct testing is:
curl -L https://raw.githubusercontent.com/pivpn/pivpn/test/auto_install/install.sh | TESTING= bash

Or

curl -L https://install.pivpn.io | TESTING= bash

**Comment by tigernero79** [comment]
I installed the test branch and although the certificate generates the tls-crypt tag correctly on the screen instead it says it has found tls-auth I think they need to fix.

![Screenshot_20190803-211451](https://user-images.githubusercontent.com/35575744/62416047-3ed1c400-b634-11e9-8945-2ccd11c3aba6.png)

**Comment by orazioedoardo** [comment]
Yeah, the script aleays says “tls-auth”. By the way `curl -L https://install.pivpn.io | TESTING= bash` is NOT the correct command. It installs the master (not testing) script while using the test branch fron git. Use the first command instead.

**Comment by tigernero79** [comment]
then I noticed that the tedting branch does not generate the dh certificate, it inserts the Key direction 1 entry according to you better the generation of the dh certificate or not?

**Comment by orazioedoardo** [comment]
If you choose not to use 2.4 features, the dh parameters are not generated (not used with elliptic curves), tls-crypt is used and key direction 1 is NOT inserted (since it’s useless with tls-crypt).

If key direction 1 is inserted but you have tls-crypt at the same time, then i think you used the wrong curl command.

**Comment by tigernero79** [comment]
I don't have Key direction 1 and dh with va, but if I launch the official script (no testing) pivpn let me generate Key direction and dh certificate at 2048bit.  I was wondering having launched the sky testing because it generated voice dh none?  I chose yes to the openvpn 2.4 question

**Comment by orazioedoardo** [comment]
If you choose yes to the 2.4 question, then dh is not generated (dh none in the server config) for the reason in the above config.

The official script wrongly detects that your system does not support 2.4 features so it uses the “old” 2048 bit certificate with dh, which is the same beahaviour as if you chose “no” to the 2.4 question.

**Comment by tigernero79** [comment]
using the testing channel I said yes to the question if my clients use openvpn 2.4 (of course) and in any case the server carries dh none

**Comment by tigernero79** [comment]
I tried to choose no to the compatibility item and rightly asked me to generate Key for DH, but if I choose to give me the voice "dh none" does not put me elliptic curve in server.conf

**Comment by orazioedoardo** [comment]
If you choose Yes the elliptic curve used is the one from the certificate. OpenVPN uses that if not specified in the config. For example if you choose a 256 bit certificate, openvpn automatically uses curve prime256v1 (NIST P-256).

**Comment by tigernero79** [comment]
in Raspbian Stretch before it brought me this way: 
dh none
ecdh-curve secp384r1 

Now on raspbian buster only 
dh none

**Comment by orazioedoardo** [comment]
That has been changed several commits ago: https://github.com/pivpn/pivpn/pull/597/files#diff-299d9b30c952310aace4aba77c698874R849

**Comment by tigernero79** [comment]
Thanks thanks

**Comment by tigernero79** [comment]
thanks for everything anyway and good night

**Comment by tigernero79** [comment]
then I noticed that they basically put "cipher AES-256-CBC" but it's not better to "AES-256-GCM" cipher?

**Comment by orazioedoardo** [comment]
CBC keeps compatibility with older clients however if both client and server run openvpn 2.4 or later, the cipher is ipgraded to GCM. You should see that in the logs.

**Comment by tigernero79** [comment]
ok understand, set gcm for me as all my clients are 2.4.  openvpn compression suggests disabling it after a vulnerability has been found.  for auth sha256 and auth sha512 which one should I use?  have a nice Sunday
