### ISSUE TITLE
Generate certs on other machine and use them for PiVPN?

### ISSUE THREAD

**Issue by muibusan** [pivpn/pivpn#806]
Generating the certificates takes too long on my Raspberry Pi. Is there a way to (manually) pre-create the certificates on another machine like my laptop and then make PiVPN use them on my Raspberry during its installation? How?

**Comment by 4s3ti** [comment]
first.. what's too long for you? 
have you considered that something might be wrong with your system? it shouldn't take that long!

regardless,  I don't think that's a good approach, and it might be a bit too hacky, 

but maybe this might help you to step in the right direction: 

https://github.com/pivpn/pivpn/wiki/FAQ#how-can-i-migrate-my-configs-to-another-pivpn-instance

**Comment by muibusan** [comment]
Thanks and I wasn't aware of that reddit forum for PiVPN.

Well, my Raspberry is as fast as all his bros and sis.

**Comment by 4s3ti** [comment]
@muibusan is right here: https://github.com/pivpn/pivpn#feedback--support 

kind advice, read the documentation first ehehe =)
