### ISSUE TITLE
unattended install

### ISSUE THREAD

**Issue by foster82** [pivpn/pivpn#808]
Hi , is it possible to setup  pivpn with out having to interact with it. S
So for example it can be deployed via ansible,

Thanks

Jonathan

**Comment by 4s3ti** [comment]
There is some undocumented stuff regarding that, --unattended is implemented in the code but, as I have been away for quite a while I am not entirely sure how that is working! 
@orazioedoardo, @Giraffe1966  any of you know if this is working properly? really need to get up to speed again and run a couple of test cases asap

**Comment by orazioedoardo** [comment]
I see in the script that you can pass `--unattended` but I’m not sure how that works. There is a variable being set that “should” make the script non-interactive by disabling dialogs but then i don’t know how to pass user choises.

**Comment by MichaIng** [comment]
@4s3ti @orazioedoardo 
https://github.com/pivpn/pivpn/blob/master/auto_install/install.sh#L1332
https://github.com/pivpn/pivpn/blob/master/auto_install/install.sh#L15
- `/etc/pivpn/setupVars.conf` must exist and contain the variable assignments then.

And here the overview of required/used variables:
https://github.com/pivpn/pivpn/blob/master/auto_install/install.sh#L1099-L1112
Or, for testing, use a file created from another interactive install.

**Comment by Dhy19971** [comment]
How did you solve it? I have a similar problem with the raspberry pi 3 ..

``root@raspberrypi://home/pi# curl -L https://install.pivpn.io | bash
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
root@raspberrypi://home/pi# curl --insecure -L https://install.pivpn.io | bash
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
100 178 100 178 0 0 249 0 --:--:-- --:--:-- --:--:-- 248
100 58458 100 58458 0 0 43206 0 0:00:01 0:00:01 --:--:-- 43206
:::
::: You are root.
::: Verifying free disk space...
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: Your system is up to date! Continuing with PiVPN installation...
::: Static IP already configured.
::: Using User: pi
:::
::: Checking for existing base files...
::: Checking /etc/.pivpn is a repo...::: Cloning https://github.com/pivpn/pivpn.git into /etc/.pivpn... [/] fatal: unable to access 'https://github.com/pivpn/pivpn.git/': server certificate verification failed. CAfile: none CRLfile: none done!
:::
::: Stopping OpenVPN service... done.

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
cp: cannot stat 'unattended-upgrades-1.9/data/50unattended-upgrades.Raspbian': No such file or directory
:::
::: Installing scripts to /opt/pivpn...cp: cannot stat '/etc/.pivpn/scripts/makeOVPN.sh': No such file or directory
cp: cannot stat '/etc/.pivpn/scripts/clientStat.sh': No such file or directory
cp: cannot stat '/etc/.pivpn/scripts/listOVPN.sh': No such file or directory
cp: cannot stat '/etc/.pivpn/scripts/removeOVPN.sh': No such file or directory
cp: cannot stat '/etc/.pivpn/scripts/uninstall.sh': No such file or directory
cp: cannot stat '/etc/.pivpn/scripts/pivpnDebug.sh': No such file or directory
chmod: cannot access '/opt/pivpn/makeOVPN.sh': No such file or directory
chmod: cannot access '/opt/pivpn/clientStat.sh': No such file or directory
chmod: cannot access '/opt/pivpn/listOVPN.sh': No such file or directory
chmod: cannot access '/opt/pivpn/removeOVPN.sh': No such file or directory
chmod: cannot access '/opt/pivpn/uninstall.sh': No such file or directory
chmod: cannot access '/opt/pivpn/pivpnDebug.sh': No such file or directory
cp: cannot stat '/etc/.pivpn/pivpn': No such file or directory
chmod: cannot access '/usr/local/bin/pivpn': No such file or directory
cp: cannot stat '/etc/.pivpn/scripts/bash-completion': No such file or directory
main: line 414: /etc/bash_completion.d/pivpn: No such file or directory
done.
::: Using protocol: udp

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
chown: cannot access '/etc/openvpn/easy-rsa': No such file or directory
mkdir: cannot create directory ‘/etc/openvpn/easy-rsa/pki’: No such file or directory
main: line 825: cd: /etc/openvpn/easy-rsa: No such file or directory
root@raspberrypi://home/pi#`

**Comment by orazioedoardo** [comment]
Merged into master: https://github.com/pivpn/pivpn/pull/914
