### ISSUE TITLE
Change Interface on Installation

### ISSUE THREAD

**Issue by ant1612** [pivpn/pivpn#81]
Hello,

I really like the concept of this and have been (for a while) looking for an easy and secure openVPN service for the Pi

However, I have a new RPi v2 B on a WLAN0 and am unable to select this as the primary interface. This port has a static address (10.0.1.32) assigned by the router on MAC association and also written in to /etc/network/interfaces (i need to disable this as it's pointless to have two) - I have my router port forwarding to this address on 1194, so it's all good

I am SSH on WLAN0 and do not (and will never) have anything plugged in to ETH0. There is asterix (*) selected on ETH0, though is unable to be selected for another interface

I have also observed that I can do change from 2048 to 1024 (for testing purposes) or 4096 for "true" encryption. Also, unable to change any of the address details

I've tried this on SSH and terminal local to the unit - Both the same result

I looked through the issues and couldn't see someone else with this exact fault. 

Thoughts?

**Comment by PeterChauYEG** [comment]
Hey I was having this issue was well. 

You can use the arrow key to navigate to the interface, then press `space`.

**Comment by ant1612** [comment]
Hi,

I've just tried that now and it worked. I must have hit every key other than space

Thanks so much for your help...
