### ISSUE TITLE
Cannot connect to pivpn gui after storage upgrade

### ISSUE THREAD

**Issue by biscuitduke** [pivpn/pivpn#810]
Hello,

I recently upgraded my pi storage via a dd command. So far the rest of my pi software is working fine (pihole, ftp and plex) but for some reason my pivpn is not working. the clients for which I have the .ovpn files for can no longer connect, and the weirdest thing is I cannot log into the vpn web interface. It has my credentials are incorrect but I am able to ssh into my pi just fine. I've tried rebooting my pi and restarting the openvpn process. I've aslo seen the solution by using running the script `/usr/local/openvpn_as/bin/ovpn-init --force` but I have no such script. Any ideas?

**Comment by 4s3ti** [comment]
Hi, thanks for using pivpn, 

Please read properly the documentation and openup an issue only if entirely related with PiVPN Codebase. 

having this said, I am closing this issue, 
if you still need support please properly fill in the issue template, without details we cannot help you out .

kind regards.
