### ISSUE TITLE
Where is the server address for `pivpn add` kept?

### ISSUE THREAD

**Issue by RevealedFrom** [pivpn/pivpn#813]
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

### Issue
I accidentally used the default for the server address during installation, and now `pivpn add` will generate a .ovpn file with `remote` set to the IP address the ISP gave me on the night of installation. I have a proper domain name for my server. How do I patch this in to avoid reinstalling all over again?

### Have you searched for similar issues and solutions?
    (yes/no / which issues?)
  I searched /opt/pivpn/makeOVPN.sh and all the files in /etc/pivpn, but could not find the IP address.

### Console output of      `pivpn add` or `pivpn add nopass`
```
Write out database with 1 new entries
Data Base Updated
Client's cert found: test.crt
Client's Private Key found: test.key
CA public Key found: ca.crt
tls-auth Private Key found: ta.key
```

### Have you taken any steps towards solving your issue?
```
  I edit each .opvn file manually to replace the IP address with my server domain name.
```

**Comment by 4s3ti** [comment]
> ### Have you searched for similar issues and solutions?
> 
> ```
> (yes/no / which issues?)
> ```
> 
> I searched /opt/pivpn/makeOVPN.sh and all the files in /etc/pivpn, but could not find the IP address.

Seems you haven't searched in the right place =)

https://github.com/pivpn/pivpn/wiki/FAQ#can-i-change-the-hostname-the-ip-address-protocol-or-port-after-the-install

here you have! hope it helps. 
in the future Please move this type of questions to [r/pivpn](https://www.reddit.com/r/pivpn/)

Thank you!
