### ISSUE TITLE
See client browsing history

### ISSUE THREAD

**Issue by nikosolihin** [pivpn/pivpn#814]
Hello,

Is it possible to view which sites my connected clients are visiting? Similar to browsers history.

Thanks

**Comment by 4s3ti** [comment]
Please read properly the documentation before opening an issue in PiVPN GitHub Page. 

Not a feature supported by PiVPN neither I think it should be supported at all by our scripts. 
Seems quite intrusive to me. 

That is a more networking / OpenVPN related question rather then PiVPN. 
Try asking on OpenVPN support channels if there is a way to do it. 

Having this said closing this thread. 
kind Regards.
