### ISSUE TITLE
PIVPN install fails

### ISSUE THREAD

**Issue by homerybart** [pivpn/pivpn#815]
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

`  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   178  100   178    0     0    206      0 --:--:-- --:--:-- --:--:--   206
100 55086  100 55086    0     0  57488      0 --:--:-- --:--:-- --:--:-- 57488
:::
::: You are root.
::: Verifying free disk space...
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: Your system is up to date! Continuing with PiVPN installation...
::: Static IP already configured.
::: Using User: pi
:::
::: Checking for existing base files...
:::    Checking /etc/.pivpn is a repo...:::    Cloning https://github.com/pivpn/pivpn.git into /etc/.pivpn... [/]  fatal: unable to access 'https://github.com/pivpn/pivpn.git/': Problem with the SSL CA cert (path? access rights?)
 done!
:::
::: Stopping OpenVPN service... done.

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
cp: cannot stat 'unattended-upgrades-1.9/data/50unattended-upgrades.Raspbian': No such file or directory
:::
::: Installing scripts to /opt/pivpn...cp: cannot stat '/etc/.pivpn/scripts/makeOVPN.sh': No such file or directory
cp: cannot stat '/etc/.pivpn/scripts/clientStat.sh': No such file or directory
cp: cannot stat '/etc/.pivpn/scripts/listOVPN.sh': No such file or directory
cp: cannot stat '/etc/.pivpn/scripts/removeOVPN.sh': No such file or directory
cp: cannot stat '/etc/.pivpn/scripts/uninstall.sh': No such file or directory
cp: cannot stat '/etc/.pivpn/scripts/pivpnDebug.sh': No such file or directory
chmod: cannot access '/opt/pivpn/makeOVPN.sh': No such file or directory
chmod: cannot access '/opt/pivpn/clientStat.sh': No such file or directory
chmod: cannot access '/opt/pivpn/listOVPN.sh': No such file or directory
chmod: cannot access '/opt/pivpn/removeOVPN.sh': No such file or directory
chmod: cannot access '/opt/pivpn/uninstall.sh': No such file or directory
chmod: cannot access '/opt/pivpn/pivpnDebug.sh': No such file or directory
cp: cannot stat '/etc/.pivpn/pivpn': No such file or directory
chmod: cannot access '/usr/local/bin/pivpn': No such file or directory
cp: cannot stat '/etc/.pivpn/scripts/bash-completion': No such file or directory
bash: line 412: /etc/bash_completion.d/pivpn: No such file or directory
 done.
::: Using protocol: udp

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
chown: cannot access '/etc/openvpn/easy-rsa': No such file or directory
mkdir: cannot create directory '/etc/openvpn/easy-rsa/pki': No such file or directory
bash: line 810: cd: /etc/openvpn/easy-rsa: No such file or directory`

### Have you searched for similar issues and solutions?
    (yes/no / which issues?)
Yes, but not resolve the issue / #215 and #674
     
### Console output of      `curl -L install.pivpn.io | bash`
```
  Output Here
```

### Console output of      `pivpn add` or `pivpn add nopass`
```
  Output Here
```

### Console output of      `pivpn debug`
```
  Output Here
```
### Have you taken any steps towards solving your issue?
```
  which?
```

**Comment by orazioedoardo** [comment]
Output of `git clone https://github.com/pivpn/pivpn.git`?

**Comment by homerybart** [comment]
Hi

This is the ouptu of git clone:

"root@bananaPi:~# git clone https://github.com/pivpn/pivpn.git
Cloning into 'pivpn'...
fatal: unable to access 'https://github.com/pivpn/pivpn.git/': Problem with the SSL CA cert (path? access rights?)"

and raspbian version is: Raspbian linux 8

I had installed vivpn and it worked fine,  but i tryed update openssl and i remove pivpn and when trying to install pivnp again it fails 


--




Raspbian Linux 8
--




Raspbian Linux 8
--

**Comment by orazioedoardo** [comment]
Well I don't know anything about bananaPi but that's not PiVPN's fault, so you should ask why git clone is not working on the bananapi forum. Try this though (update the system then reinstall CA certificates then reboot):
```
sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get install --reinstall ca-certificates
sudo reboot
```

**Comment by homerybart** [comment]
bananaPi is a clon of raspberrypi, and the problem occurs when installing pivpn, there are at least two issues relationed #215 and #674, In addition I have already installed pivpn and it worked fine.
The error occurs in the line 805 of the script "wget -q -O - "${easyrsaRel}" | $SUDO tar xz -C /etc/openvpn && $SUDO mv /etc/openvpn/EasyRSA-v${easyrsaVer} /etc/openvpn/easy-rsa" 
it  can't seem to download easy-rsa to openvpn line 30 of script:
"easyrsaRel="https://github.com/OpenVPN/easy-rsa/releases/download/v${easyrsaVer}/EasyRSA-unix-v${easyrsaVer}.tgz"

**Comment by orazioedoardo** [comment]
How about `wget https://google.com`?

**Comment by homerybart** [comment]
I have solved the problem by restoring a backup

**Comment by Dhy19971** [comment]
> I have solved the problem by restoring a backup

How did you solve it? I have a similar problem with the raspberry pi 3 ..

``root@raspberrypi://home/pi# curl -L https://install.pivpn.io | bash
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
root@raspberrypi://home/pi# curl --insecure -L https://install.pivpn.io | bash
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
100 178 100 178 0 0 249 0 --:--:-- --:--:-- --:--:-- 248
100 58458 100 58458 0 0 43206 0 0:00:01 0:00:01 --:--:-- 43206
:::
::: You are root.
::: Verifying free disk space...
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: Your system is up to date! Continuing with PiVPN installation...
::: Static IP already configured.
::: Using User: pi
:::
::: Checking for existing base files...
::: Checking /etc/.pivpn is a repo...::: Cloning https://github.com/pivpn/pivpn.git into /etc/.pivpn... [/] fatal: unable to access 'https://github.com/pivpn/pivpn.git/': server certificate verification failed. CAfile: none CRLfile: none done!
:::
::: Stopping OpenVPN service... done.

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
cp: cannot stat 'unattended-upgrades-1.9/data/50unattended-upgrades.Raspbian': No such file or directory
:::
::: Installing scripts to /opt/pivpn...cp: cannot stat '/etc/.pivpn/scripts/makeOVPN.sh': No such file or directory
cp: cannot stat '/etc/.pivpn/scripts/clientStat.sh': No such file or directory
cp: cannot stat '/etc/.pivpn/scripts/listOVPN.sh': No such file or directory
cp: cannot stat '/etc/.pivpn/scripts/removeOVPN.sh': No such file or directory
cp: cannot stat '/etc/.pivpn/scripts/uninstall.sh': No such file or directory
cp: cannot stat '/etc/.pivpn/scripts/pivpnDebug.sh': No such file or directory
chmod: cannot access '/opt/pivpn/makeOVPN.sh': No such file or directory
chmod: cannot access '/opt/pivpn/clientStat.sh': No such file or directory
chmod: cannot access '/opt/pivpn/listOVPN.sh': No such file or directory
chmod: cannot access '/opt/pivpn/removeOVPN.sh': No such file or directory
chmod: cannot access '/opt/pivpn/uninstall.sh': No such file or directory
chmod: cannot access '/opt/pivpn/pivpnDebug.sh': No such file or directory
cp: cannot stat '/etc/.pivpn/pivpn': No such file or directory
chmod: cannot access '/usr/local/bin/pivpn': No such file or directory
cp: cannot stat '/etc/.pivpn/scripts/bash-completion': No such file or directory
main: line 414: /etc/bash_completion.d/pivpn: No such file or directory
done.
::: Using protocol: udp

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
chown: cannot access '/etc/openvpn/easy-rsa': No such file or directory
mkdir: cannot create directory ‘/etc/openvpn/easy-rsa/pki’: No such file or directory
main: line 825: cd: /etc/openvpn/easy-rsa: No such file or directory
root@raspberrypi://home/pi#`

**Comment by 4s3ti** [comment]
which board of bannana pi are you using? because most of them don't support raspbian and use an adapted version of armbian, are you sure you are using raspbian? pleas3e  .. i have a banana pi myself and it getting its quite a sensible thing. please provide the output of: 

`cat /etc/os-release`

Also i am sorry if this sounds rude .. what do ppl have against filling an issue template properly?  =( this one is not that bad but still =/

**Comment by award28** [comment]
I ran into this same issue while trying to install pivpn on my my octoprint raspberry pi.

If anyone else runs into this same issue, I found that removing the `sudo git` sanity check before running the script allowed the installation to continue.

Probably not the best idea to completely remove this from your system, so I'd recommend moving it, and then moving it back when you're done 🙂

```bash
sudo mv /root/bin/git ~/git_sanity_check
curl -L install.pivpn.io | bash
sudo mv ~/git_sanity_check /root/bin/git
```
