### ISSUE TITLE
Revise file & Dir permissions

### ISSUE THREAD

**Issue by 4s3ti** [pivpn/pivpn#816]
Some permissions appear to be quite open while they should be more strict. 

exmaple: 

https://github.com/pivpn/pivpn/blob/8e3a95152412a9d35b67d51bfc80379350815252/auto_install/install.sh#L1061

go through the code and check all permissions

Make some cleaning and change permissions for numerical values instead of letters.

**Comment by orazioedoardo** [comment]
Now they are too strict =D
https://github.com/pivpn/pivpn/blob/add3daf8deb6c949d54abb11ea2a992a48b865e3/auto_install/install.sh#L1139

```
[user@debian ~]$ cd ovpns/
-bash: cd: ovpns/: Permission denied
[user@debian ~]$ ls -ld ovpns
drwxr-x--- 2 root root 4096 Sep  2 11:53 ovpns
[user@debian ~]$ sudo chown user:user ovpns
[user@debian ~]$ cd ovpns/
[user@debian ovpns]$ ls
test2.ovpn  test2.ovpn12  test.ovpn
```

**Comment by 4s3ti** [comment]
they aren't too strict .. but something makes it owned by root .. when it should be owned by the user ... 
ill add a final chown in the end of the script to make that no matter what by the end of the installation it is owned by $INSTALL_USER , but at least its creating ovpns dir now ... before it was throwing a quite big junk error ( is somehwere in commit messages) xD

**Comment by orazioedoardo** [comment]
> but something makes it owned by root

Because the folder is created with `$SUDO mkdir...`.

> ill add a final chown in the end of the script to make that no matter what by the end of the installation

or inside the if statement that creates the ovpns folder

**Comment by 4s3ti** [comment]
I am actually changing the ownership to $INSTALL_USER:root right after i change the permissions... testing it as we speak,  what you think?

**Comment by orazioedoardo** [comment]
The pratical implication of $INSTALL_USER:root is that users part of the $INSTALL_USER groups won't be able to enter the folder (and read its contents since .ovpn files are $INSTALL_USER:root). Personally I like to have user:user inside my home folder however the implication above is probably an edge case.

**Comment by 4s3ti** [comment]
@orazioedoardo should be just fine now.

**Comment by 4s3ti** [comment]
firex here: 50ad223e83fb96d20d732d9c35dedd2f0186dadc
Closing @orazioedoardo reopen pls if you still find something related.
