### ISSUE TITLE
Connecting error

### ISSUE THREAD

**Issue by snues** [pivpn/pivpn#82]
Hello

I need help please. I create a Client and download de config from Raspberry to my Smartphone. Use the config on Openvpn client free and become the error "operation not permitted code1" Connected refused code 111

What is the problem ? 
I use Raspian jessie on the raspberry.

Bernd

**Comment by 0-kaladin** [comment]
> ECONNREFUSED means that the port you are trying to connect to is not open on the IP you are trying to connect to. This implies that either you are connecting to the wrong IP, you did not open the port on your firewalls successfully, the server did not launch successfully, or the server is using a different port. 

basically ensure your port is open from the outside correctly for your client to connect and ensure the client is set to hit that outside IP.
