### ISSUE TITLE
Script currently not working as apt not called with sudo

### ISSUE THREAD

**Issue by orazioedoardo** [pivpn/pivpn#821]
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

### Fix

Manually download the script, make it executable, add `$SUDO` before `apt` [here](https://github.com/pivpn/pivpn/blob/ad29af219920189beac873d8d7eb6b15b85f3dee/auto_install/install.sh#L479-L483) in the code (possibly before `npm` too). 
```
wget https://raw.githubusercontent.com/pivpn/pivpn/master/auto_install/install.sh
chmod +x ./install.sh
```
make the change, then run with `./install.sh`

**Comment by 4s3ti** [comment]
ooooh crap .. really my bad here with this one! I made my tests with root account which obviously worked flawlessly and didn't spotted that! will make a hotfix for that right away

**Comment by 4s3ti** [comment]
I am working on making it optional as well ... will make it show a whiptail message asking if user wants to install it.

**Comment by 4s3ti** [comment]
@orazioedoardo should be fixed, can you test and comeback with feedback pls? 

Thanks a lot

**Comment by 4s3ti** [comment]
As per comments here: https://github.com/pivpn/pivpn/issues/823 I have removed Bitwarden installation from the script. commit: 510979ae90682c4ca11eb59d763c91930ffb5847

Thanks a lot for your help @orazioedoardo 
should no longer be an issue. 
Closing.
