### ISSUE TITLE
Install failed: Error: Cannot find module '/usr/local/lib/node_modules/@bitwarden/cli/node_modules/tldjs/bin/postinstall.js'

### ISSUE THREAD

**Issue by martin-ward** [pivpn/pivpn#823]
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

### Issue

This is a new Raspberry Pi 4 with Raspian installed via NOOBS.
It has been updated with "apt-get update" and "apt-get upgrade"

The installation of pivpn failed as described below.

### Have you searched for similar issues and solutions?

yes

### Console output of      `curl -L install.pivpn.io | bash`
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   178  100   178    0     0    246      0 --:--:-- --:--:-- --:--:--   246
100 58657  100 58657    0     0  68524      0 --:--:-- --:--:-- --:--:-- 68524
:::
::: You are root.
::: Verifying free disk space...
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: Your system is up to date! Continuing with PiVPN installation...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
nodejs is already the newest version (10.15.2~dfsg-2+rpi1).
npm is already the newest version (5.8.0+ds6-4).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
/usr/local/bin/bw -> /usr/local/lib/node_modules/@bitwarden/cli/build/bw.js

> tldjs@2.3.1 postinstall /usr/local/lib/node_modules/@bitwarden/cli/node_modules/tldjs
> node ./bin/postinstall.js

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '/usr/local/lib/node_modules/@bitwarden/cli/node_modules/tldjs/bin/postinstall.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tldjs@2.3.1 postinstall: `node ./bin/postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tldjs@2.3.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-09-02T10_26_20_301Z-debug.log


```

### Console output of      `pivpn add` or `pivpn add nopass`
```
bash: pivpn: command not found

```

### Console output of      `pivpn debug`
```
bash: pivpn: command not found

```
### Have you taken any steps towards solving your issue?
```
Posting this message :-)
```

**Comment by orazioedoardo** [comment]
Try this workaround for now:

Manually download the script
`wget https://raw.githubusercontent.com/pivpn/pivpn/master/auto_install/install.sh`

Apply permissions
`chmod +x install.sh`

Remove this line from the file `install.sh`
https://github.com/pivpn/pivpn/blob/add3daf8deb6c949d54abb11ea2a992a48b865e3/auto_install/install.sh#L1376

Run the script
`./install.sh`

**Comment by 4s3ti** [comment]
fix for this going to be pushed in about an hour or two.

**Comment by 4s3ti** [comment]
@martin-ward Fix has been pushed, please try again and come back with feedback pls.

**Comment by martin-ward** [comment]
It got as far as installing Bitwarden:

```
::: Installing Bitwarden
/usr/local/bin/bw -> /usr/local/lib/node_modules/@bitwarden/cli/build/bw.js

> tldjs@2.3.1 postinstall /usr/local/lib/node_modules/@bitwarden/cli/node_modules/tldjs
> node ./bin/postinstall.js

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '/usr/local/lib/node_modules/@bitwarden/cli/node_modules/tldjs/bin/postinstall.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tldjs@2.3.1 postinstall: `node ./bin/postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tldjs@2.3.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-09-02T12_14_19_477Z-debug.log
```

**Comment by 4s3ti** [comment]
hmm that one seems odd ... 
Guess it will throw a lot of errors in the future depending on everyone's environment .. going to remove 
Guess its safer Bit warden installation form the script completely, and leave the integration only with pivpn add  ... and users that want it installed should install it manually

**Comment by 4s3ti** [comment]
well nevermind ... @orazioedoardo @martin-ward since i am part of this project i have tried to keep it as simple as possible and i have refused a bunch of PR's for less. 

having this said ... I have removed bitwarden installation it from the installation script and no more issues should arise regarding this. 

Integrating bitwarden install into this script its a cool feature, but should be kept to a minimum and by installing bitwarden with the install script i have deviated from what have been my principles since i joined this project.  for that my sincere apologies! 

Bitwarden is still supported but only on pivpn add .. and it will bail out if doesn't find bw installed and warn users about it. 

users that want bitwarden should install it themselves manually, as it turned out to be an extra painpoint which can cause a lot of errors depending on each user environment, and we have already enough of those issues around to worry about! 

Thanks for all your patience,  help and support!

**Comment by martin-ward** [comment]
I skipped intstallation of bitwarden and the rest of the installation worked. The VPN seems to be working (tested on my Mac with Tunnelblick).

**Comment by 4s3ti** [comment]
Great news! thanks a lot for your feedback! 
once again my apologies for this buggy update! =(
