### ISSUE TITLE
failure to create OVPN

### ISSUE THREAD

**Issue by Drzet** [pivpn/pivpn#826]
root@raspberrypi:/etc/openvpn/easy-rsa# pivpn add
Enter a Name for the Client:  pixel
#How many days should the certificate last?  1080
Enter the password for the client:
Enter the password again to verify:
/opt/pivpn/makeOVPN.sh: line 162:  1073 Segmentation fault      expect  <<EOF
    set timeout -1
    set env(EASYRSA_CERT_EXPIRE) "${DAYS}"
    spawn ./easyrsa build-client-full "${NAME}"
    expect "Enter PEM pass phrase" { send -- "${PASSWD}\r" }
    expect "Verifying - Enter PEM pass phrase" { send -- "${PASSWD}\r" }
    expect eof
EOF

[ERROR]: Client Public Key Certificate not found: pixel.crt

**Comment by orazioedoardo** [comment]
Please fill the issue template first.

**Comment by 4s3ti** [comment]
https://github.com/pivpn/pivpn#feedback--support

`Please read carefully the issue template and the contributors' guide, we will close all incomplete issue templates.`
