### ISSUE TITLE
Unable to create .ovpn 

### ISSUE THREAD

**Issue by Drzet** [pivpn/pivpn#827]
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting can be directly related to the pivpn installer script.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

### 
Can not create .ovpn file

### Have you searched for similar issues and solutions?
    yes, unsuccessfully

### Console output of      `curl -L install.pivpn.io | bash`
```
 root@raspberrypi:/# sudo curl -L https://install.pivpn.io | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   178  100   178    0     0     33      0  0:00:05  0:00:05 --:--:--    37
100 58448  100 58448    0     0  10050      0  0:00:05  0:00:05 --:--:--  157k
:::
::: You are root.
::: Verifying free disk space...
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: Your system is up to date! Continuing with PiVPN installation...
::: Static IP already configured.
::: Using User: pi
:::
::: Checking for existing base files...
:::    Checking /etc/.pivpn is a repo...:::    Cloning https://github.com/pivpn/pivpn.git                                                                  into /etc/.pivpn... done!
:::
::: Stopping OpenVPN service... done.
:::
::: Installing scripts to /opt/pivpn... done.
::: Using protocol: udp
set_var EASYRSA_ALGO       ec
set_var EASYRSA_CURVE      prime256v1
::: Building CA...
read EC key
writing EC key

::: CA Complete.

Note: using Easy-RSA configuration from: ./vars

Using SSL: openssl OpenSSL 1.1.0k  28 May 2019
Generating an EC private key
writing new private key to '/etc/openvpn/easy-rsa/pki/private/raspberrypi_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.key.pxR6XFLUA1'
-----
Using configuration from /etc/openvpn/easy-rsa/pki/safessl-easyrsa.cnf
Can't open /etc/openvpn/easy-rsa/pki/index.txt.attr for reading, No such file or director                                                                 y
1996156928:error:02001002:system library:fopen:No such file or directory:../crypto/bio/bs                                                                 s_file.c:74:fopen('/etc/openvpn/easy-rsa/pki/index.txt.attr','r')
1996156928:error:2006D080:BIO routines:BIO_new_file:no such file:../crypto/bio/bss_file.c                                                                 :81:
Check that the request matches the signature
Signature ok
The Subject's Distinguished Name is as follows
commonName            :ASN.1 12:'raspberrypi_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
Certificate is to be certified until Aug 31 04:37:43 2029 GMT (3650 days)

Write out database with 1 new entries
Data Base Updated

Note: using Easy-RSA configuration from: ./vars

Using SSL: openssl OpenSSL 1.1.0k  28 May 2019
Using configuration from /etc/openvpn/easy-rsa/pki/safessl-easyrsa.cnf

An updated CRL has been created.
CRL file: /etc/openvpn/easy-rsa/pki/crl.pem

net.ipv4.ip_forward = 1
run-parts: executing /usr/share/netfilter-persistent/plugins.d/15-ip4tables save
run-parts: executing /usr/share/netfilter-persistent/plugins.d/25-ip6tables save
cp: cannot stat '/tmp/OLD_UFW': No such file or directory
sleep 0.1
::: Install Complete...
::: Restarting services...
Synchronizing state of openvpn.service with SysV service script with /lib/systemd/systemd                                                                 -sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable openvpn
::: Flushing writes to disk...
::: done.

Rebooting system...

```

### Console output of      `pivpn add` or `pivpn add nopass`
```
root@raspberrypi:/opt/pivpn# pivpn -a
Enter a Name for the Client:  pixel
How many days should the certificate last?  2000
Enter the password for the client:
Enter the password again to verify:
/opt/pivpn/makeOVPN.sh: line 162:  1518 Segmentation fault      expect  <<EOF
    set timeout -1
    set env(EASYRSA_CERT_EXPIRE) "${DAYS}"
    spawn ./easyrsa build-client-full "${NAME}"
    expect "Enter PEM pass phrase" { send -- "${PASSWD}\r" }
    expect "Verifying - Enter PEM pass phrase" { send -- "${PASSWD}\r" }
    expect eof
EOF

[ERROR]: Client Public Key Certificate not found: pixel.crt

```

### Console output of      `pivpn debug`
```
 pivpn -d
::: Generating Debug Output
::::            PiVPN debug              ::::
=============================================
::::            Latest commit            ::::
commit 510979ae90682c4ca11eb59d763c91930ffb5847
Author: cfcolaco <carlos@vidispine.com>
Date:   Mon Sep 2 14:27:10 2019 +0200

    removing bitwarden installation from script
=============================================
::::        Installation settings        ::::
/etc/pivpn/DET_PLATFORM -> Raspbian
/etc/pivpn/FORWARD_CHAIN_EDITED -> 0
/etc/pivpn/HELP_SHOWN ->
/etc/pivpn/INPUT_CHAIN_EDITED -> 0
/etc/pivpn/INSTALL_PORT -> 1172
/etc/pivpn/INSTALL_PROTO -> udp
/etc/pivpn/INSTALL_USER -> pi
/etc/pivpn/NO_UFW -> 1
/etc/pivpn/pivpnINTERFACE -> wlan0
/etc/pivpn/TWO_POINT_FOUR ->
=============================================
::::    setupVars file shown below       ::::
INSTALL_USER=pi
UNATTUPG=unattended-upgrades
pivpnInterface=wlan0
IPv4dns=127.0.0.1
IPv4addr=192.168.0.15
IPv4gw=192.168.0.1
pivpnProto=udp
PORT=1172
ENCRYPT=256
APPLY_TWO_POINT_FOUR=true
DOWNLOAD_DH_PARAM=false
PUBLICDNS=REMOTE
OVPNDNS1=10.8.0.1
OVPNDNS2=
=============================================
::::  Server configuration shown below   ::::
dev tun
proto udp
port 1172
ca /etc/openvpn/easy-rsa/pki/ca.crt
cert /etc/openvpn/easy-rsa/pki/issued/raspberrypi_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.crt
key /etc/openvpn/easy-rsa/pki/private/raspberrypi_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.key
dh none
topology subnet
server 10.8.0.0 255.255.255.0
# Set your primary domain name server address for clients
push "dhcp-option DNS 10.8.0.1"
push "block-outside-dns"
# Override the Client default gateway by using 0.0.0.0/1 and
# 128.0.0.0/1 rather than 0.0.0.0/0. This has the benefit of
# overriding but not wiping out the original default gateway.
push "redirect-gateway def1"
client-to-client
keepalive 1800 3600
remote-cert-tls client
tls-version-min 1.2
tls-crypt /etc/openvpn/easy-rsa/pki/ta.key
cipher AES-256-CBC
auth SHA256
user nobody
group nogroup
persist-key
persist-tun
crl-verify /etc/openvpn/crl.pem
status /var/log/openvpn-status.log 20
status-version 3
syslog
verb 3
#DuplicateCNs allow access control on a less-granular, per user basis.
#Remove # if you will manage access by user instead of device.
#duplicate-cn
# Generated for use by PiVPN.io
=============================================
::::  Client template file shown below   ::::
client
dev tun
proto udp
remote REMOTE 1172
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
tls-version-min 1.2
verify-x509-name raspberrypi_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx name
cipher AES-256-CBC
auth SHA256
auth-nocache
verb 3
=============================================
::::    Recursive list of files in       ::::
::: /etc/openvpn/easy-rsa/pki shows below :::
/etc/openvpn/easy-rsa/pki/:
ca.crt
crl.pem
Default.txt
ecparams
extensions.temp
index.txt
index.txt.attr
index.txt.old
issued
openssl-easyrsa.cnf
private
renewed
revoked
safessl-easyrsa.cnf
serial
serial.old
ta.key

/etc/openvpn/easy-rsa/pki/ecparams:
prime256v1.pem

/etc/openvpn/easy-rsa/pki/issued:
raspberrypi_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.crt

/etc/openvpn/easy-rsa/pki/private:
ca.key
raspberrypi_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.key

/etc/openvpn/easy-rsa/pki/renewed:
private_by_serial
reqs_by_serial

/etc/openvpn/easy-rsa/pki/renewed/private_by_serial:

/etc/openvpn/easy-rsa/pki/renewed/reqs_by_serial:

/etc/openvpn/easy-rsa/pki/revoked:
private_by_serial
reqs_by_serial

/etc/openvpn/easy-rsa/pki/revoked/private_by_serial:

/etc/openvpn/easy-rsa/pki/revoked/reqs_by_serial:
=============================================
::::            Self check               ::::
:: [OK] IP forwarding is enabled
:: [OK] Iptables MASQUERADE rule set
:: [OK] OpenVPN is running
:: [OK] OpenVPN is enabled (it will automatically start on reboot)
:: [OK] OpenVPN is listening on port 1172/udp
=============================================
::::      Snippet of the server log      ::::
=============================================
::::            Debug complete           ::::
:::
::: Debug output completed above.
::: Copy saved to /tmp/debug.txt
:::

```
### Have you taken any steps towards solving your issue?
```
I had pivpn working before with no issues. This is a fresh reinstall which  can't generate .ovpn
I was able to execute './easyrsa build-client-full' successfully but my understanding is when this command is invoked by the pivpn -add script it fails.
I have uninstalled and reinstalled pivpn with all dependencies several times to no avail
```

**Comment by orazioedoardo** [comment]
Edit `/opt/pivpn/makeOVPN.sh`, add this line: `set -x` after `INSTALL_HOME=${INSTALL_HOME%/} # remove possible trailing slash`, then post the output of `pivpn -a`. This will enable "verbose" mode in Bash.

**Comment by 4s3ti** [comment]
@orazioedoardo a bit off-topic ... what you think about what you think about adding some system information to pivpn debug .. for example /etc/os-release and uname -a .. 
I think it might give us a bit more info about the system where it is running and possibly help track down this weird issues

**Comment by Drzet** [comment]
Verbose makeOVPN:

###
 root@raspberrypi:/opt/pivpn# ./makeOVPN.sh
+ '[' '!' -f /etc/pivpn/HELP_SHOWN ']'
+ test 0 -gt 0
+ '[' '!' -d /home/pi/ovpns ']'
+ [[ '' =~ 2 ]]
+ '[' -z '' ']'
+ printf 'Enter a Name for the Client:  '
Enter a Name for the Client:  + read -r NAME
XXXXXXXX
+ [[ p == \. ]]
+ [[ p == \- ]]
+ [[ pics =~ [^a-zA-Z0-9.@_-] ]]
+ [[ -z pics ]]
+ read -r line
++ echo 'V      290831043743Z           E3AF40EFBC749DF8ADB39A16418C52E8        unknown /CN=raspberrypi_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
++ awk '{print $1}'
+ STATUS=V
+ '[' V == V ']'
++ echo 'V      290831043743Z           E3AF40EFBC749DF8ADB39A16418C52E8        unknown /CN=raspberrypi_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
++ sed -e 's:.*/CN=::'
+ CERT=raspberrypi_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
+ '[' raspberrypi_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx == pics ']'
+ read -r line
+ '[' -n '' ']'
+ '[' '' == 1 ']'
+ '[' pics == ta ']'
+ '[' pics == server ']'
+ '[' pics == ca ']'
+ '[' -z '' ']'
+ read -r -e -p 'How many days should the certificate last?  ' -i 1080 DAYS
How many days should the certificate last?  1080
+ [[ ! 1080 =~ ^[0-9]+$ ]]
+ '[' 1080 -lt 1 ']'
+ '[' 1080 -gt 3650 ']'
+ cd /etc/openvpn/easy-rsa
+ [[ '' =~ 1 ]]
+ keyPASS
+ [[ -z '' ]]
+ stty -echo
+ true
+ printf 'Enter the password for the client:  '
Enter the password for the client:  + read -r PASSWD
+ printf '\n'

+ printf 'Enter the password again to verify:  '
Enter the password again to verify:  + read -r PASSWD2
+ printf '\n'

+ '[' xxxxxxx = xxxxxxx']'
+ break
+ stty echo
+ [[ -z xxxxxxxx ]]
+ '[' 7 -lt 4 ']'
+ '[' 7 -gt 1024 ']'
++ echo -n xxxxxxx
++ sed -e 's/\\/\\\\/g' -e 's/\//\\\//g' -e 's/\$/\\\$/g' -e 's/!/\\!/g' -e 's/\./\\\./g' -e 's/'\''/\\'\''/g' -e 's/"/\\"/g' -e 's/\*/\\\*/g' -e 's/\@/\\\@/g' -e 's/\#/\\\#/g' -e 's/£/\\£/g' -e 's/%/\\%/g' -e 's/\^/\\\^/g' -e 's/\&/\\\&/g' -e 's/(/\\(/g' -e 's/)/\\)/g' -e 's/-/\\-/g' -e 's/_/\\_/g' -e 's/\+/\\\+/g' -e 's/=/\\=/g' -e 's/\[/\\\[/g' -e 's/\]/\\\]/g' -e 's/;/\\;/g' -e 's/:/\\:/g' -e 's/|/\\|/g' -e 's/</\\</g' -e 's/>/\\>/g' -e 's/,/\\,/g' -e 's/?/\\?/g' -e 's/~/\\~/g' -e 's/{/\\{/g' -e 's/}/\\}/g'
+ PASSWD=xxxxxxxx
+ expect
./makeOVPN.sh: line 163:  3536 Segmentation fault      expect  <<EOF
    set timeout -1
    set env(EASYRSA_CERT_EXPIRE) "${DAYS}"
    spawn ./easyrsa build-client-full "${NAME}"
    expect "Enter PEM pass phrase" { send -- "${PASSWD}\r" }
    expect "Verifying - Enter PEM pass phrase" { send -- "${PASSWD}\r" }
    expect eof
EOF

+ cd pki
+ '[' '!' -f issued/pics.crt ']'
+ echo '[ERROR]: Client Public Key Certificate not found: pics.crt'
[ERROR]: Client Public Key Certificate not found: pics.crt
+ exit
###

###
uname -a
Linux raspberrypi 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux
###

**Comment by orazioedoardo** [comment]
What if you replace this: https://github.com/pivpn/pivpn/blob/d0c10db6ec391961b7201fb564055c1176ca73e3/scripts/makeOVPN.sh#L196-L203

With this:
`EASYRSA_CERT_EXPIRE=1080 ./easyrsa build-client-full`

Do you still get segmentation fault?

@4s3ti agree, we could add $OSCN and $PLAT. Actually i was thinking of simplifying the script. See, we have both individual files in /etc/pivpn containing setting as long as setupvars.conf. I think we could merge everything into setupvars.conf and just source the file when we need vars in other scripts like makeovpn.sh. This could also be coupled with an option to compress the /etc/openvpn folder to backup the config. Restoring would be something like `pivpn restore vars.conf backup.tar.gz`.

However i need to understand what’s the role of the “Update” option, that relies on setupvars.conf: basically it redownloads all scripts from github and perform an unattended install sourcing most vars from setupvars.conf. Then it proceeds rebuilding the server (new certificates, keys) so it doesn’t really seem an update to me.

**Comment by 4s3ti** [comment]
@orazioedoardo agree  there is plenty of room for simplifying the script is getting quite big xD 
about the update .. considering pivpn structure and what it does .. to update pivpn it would be more an update of /opt/pivpn  other than anything else .. as all other stuff is updated via apt ...

**Comment by Drzet** [comment]
Sorry guys, I couldn't wait for a solution as I needed a working VPN.
Formatted the card and reinstalled everything anew. Now it works

**Comment by orazioedoardo** [comment]
@Drzet well i actually asked you to test this `EASYRSA_CERT_EXPIRE=1080 ./easyrsa build-client-full`. By the I'm speculating that a segmentation fault on expect could be caused by [sd card corruption](https://raspberrypi.stackexchange.com/questions/5404/what-means-segmentation-fault-error-using-apt). You might want to check from time to time `dmesg | grep ext4` for file system errors, in case this happens again.

**Comment by Drzet** [comment]
Thank you, will do.
