### ISSUE TITLE
Problems Making Certificate Request - string is too long, it needs to be no more than 64 bytes long

### ISSUE THREAD

**Issue by ahmed-sigmalux** [pivpn/pivpn#831]
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

### Issue
Install script fails because EC private key filename is too long

### Have you searched for similar issues and solutions?
    (yes/no / which issues?)
Yes

### Console output of      `curl -L install.pivpn.io | bash`
```
::: Installing scripts to /opt/pivpn... done.
set_var EASYRSA_ALGO       ec
set_var EASYRSA_CURVE      prime256v1
::: Building CA...
read EC key
writing EC key
Can't load /etc/openvpn/easy-rsa/pki/.rnd into RNG
140632924271744:error:2406F079:random number generator:RAND_load_file:Cannot open file:../crypto/rand/randfile.c:98:Filename=/etc/openvpn/easy-rsa/pki/.rnd

::: CA Complete.

Note: using Easy-RSA configuration from: ./vars

Using SSL: openssl OpenSSL 1.1.1c  28 May 2019
Generating an EC private key
writing new private key to '/etc/openvpn/easy-rsa/pki/private/pihole-northamerica-northeast1-1_5a93a934-9f11-4ff7-80f4-dc8f61d60156.key.S9pvXM64Sz'
-----
string is too long, it needs to be no more than 64 bytes long
problems making Certificate Request

Easy-RSA error:

Failed to generate request
./easyrsa: 319: set: Illegal option -o echo
```

### Console output of      `pivpn add` or `pivpn add nopass`
```
  Output Here
```

### Console output of      `pivpn debug`
```
n/a
```
### Have you taken any steps towards solving your issue?
```
No
```

**Comment by 4s3ti** [comment]
fix for this pushed into test branch, please checkout and test it. thank you.

**Comment by 4s3ti** [comment]
this has been merged today into Master branch. 
Closing
