### ISSUE TITLE
pivpn cant connect at all

### ISSUE THREAD

**Issue by ewouddeenik** [pivpn/pivpn#833]
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

I completely installed pivpn, after install i cannot connect through my client (mobile). i'm using NOIP for my hostname. The pi is also behind two seperate routers. the first one that's connected to the outside internet forwards all ports to the IP of the second router. this one forwards port 1194 to the PI.

### Have you searched for similar issues and solutions?
    (yes/no / which issues?)
yes

### Console output of      `curl -L install.pivpn.io | bash`
```
  Output Here
```
<pre>  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   178  100   178    0     0    502      0 --:--:-- --:--:-- --:--:--   501
100 58458  100 58458    0     0  81079      0 --:--:-- --:--:-- --:--:-- 81079
:::
::: sudo will be used for the install.
::: Update option selected.
::: Verifying free disk space...
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: Your system is up to date! Continuing with PiVPN installation...
::: Using IP address: 192.168.1.147
::: Using interface: eth0
::: Using User: pi
::: Using protocol: udp
::: Using port: 1194
:::
::: Static IP already configured.
:::
::: Checking for existing base files...
:::    Checking /etc/.pivpn is a repo... OK!
:::     Updating repo in /etc/.pivpn... done!
:::
::: Stopping OpenVPN service... done.
:::   
::: Installing scripts to /opt/pivpn... done.
set_var EASYRSA_ALGO       ec
set_var EASYRSA_CURVE      secp521r1
::: Building CA...
read EC key
writing EC key
Can&apos;t load /etc/openvpn/easy-rsa/pki/.rnd into RNG
3070009360:error:2406F079:random number generator:RAND_load_file:Cannot open file:../crypto/rand/randfile.c:98:Filename=/etc/openvpn/easy-rsa/pki/.rnd

::: CA Complete.

Note: using Easy-RSA configuration from: ./vars

Using SSL: openssl OpenSSL 1.1.1c  28 May 2019
Generating an EC private key
writing new private key to &apos;/etc/openvpn/easy-rsa/pki/private/pi-rate_a54760ec-7eb3-42d6-a9b7-fc14b2970832.key.8KLCR7fXBl&apos;
-----
Using configuration from /etc/openvpn/easy-rsa/pki/safessl-easyrsa.cnf
Check that the request matches the signature
Signature ok
The Subject&apos;s Distinguished Name is as follows
commonName            :ASN.1 12:&apos;pi-rate_a54760ec-7eb3-42d6-a9b7-fc14b2970832&apos;
Certificate is to be certified until Sep 12 18:19:12 2029 GMT (3650 days)

Write out database with 1 new entries
Data Base Updated

Note: using Easy-RSA configuration from: ./vars

Using SSL: openssl OpenSSL 1.1.1c  28 May 2019
Using configuration from /etc/openvpn/easy-rsa/pki/safessl-easyrsa.cnf

An updated CRL has been created.
CRL file: /etc/openvpn/easy-rsa/pki/crl.pem

net.ipv4.ip_forward = 1
::: Detected UFW is enabled.
::: Adding UFW rules...
::: UFW configuration completed.
::: Restarting services...
Synchronizing state of openvpn.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable openvpn
::: Flushing writes to disk...
::: done.
:::
::: Update complete!
:::
</pre>
### Console output of      `pivpn add` or `pivpn add nopass`
```
<pre>Enter a Name for the Client:  test
How many days should the certificate last?  1080
spawn ./easyrsa build-client-full test nopass

Note: using Easy-RSA configuration from: ./vars

Using SSL: openssl OpenSSL 1.1.1c  28 May 2019
Generating an EC private key
writing new private key to &apos;/etc/openvpn/easy-rsa/pki/private/test.key.NSP7wFKqFE&apos;
-----
Using configuration from /etc/openvpn/easy-rsa/pki/safessl-easyrsa.cnf
Check that the request matches the signature
Signature ok
The Subject&apos;s Distinguished Name is as follows
commonName            :ASN.1 12:&apos;test&apos;
Certificate is to be certified until Aug 30 18:20:08 2022 GMT (1080 days)

Write out database with 1 new entries
Data Base Updated
Client&apos;s cert found: test.crt
Client&apos;s Private Key found: test.key
CA public Key found: ca.crt
tls Private Key found: ta.key


========================================================
<b>Done! test.ovpn successfully created!</b> 
test.ovpn was copied to:
  /home/pi/ovpns
for easy transfer. Please use this profile only on one
device and create additional profiles for other devices.
========================================================
</pre>
```

### Console output of      `pivpn debug`
```
<pre>::: Generating Debug Output
::::		<u style="text-decoration-style:single">PiVPN debug</u>		 ::::
=============================================
::::		<u style="text-decoration-style:single">Latest commit</u>		 ::::
commit d0c10db6ec391961b7201fb564055c1176ca73e3
Author: 4s3ti &lt;cfcolaco@colacoweb.net&gt;
Date:   Tue Sep 3 10:09:48 2019 +0200

    install.sh: apt-get with , uninstall.sh: added var PKG_MANAGER and replaced apt-get with
=============================================
::::	    <u style="text-decoration-style:single">Installation settings</u>    	 ::::
/etc/pivpn/DET_PLATFORM -&gt; Raspbian
/etc/pivpn/FORWARD_CHAIN_EDITED -&gt; 
/etc/pivpn/HELP_SHOWN -&gt; 
/etc/pivpn/INPUT_CHAIN_EDITED -&gt; 
/etc/pivpn/INSTALL_PORT -&gt; 1194
/etc/pivpn/INSTALL_PROTO -&gt; udp
/etc/pivpn/INSTALL_USER -&gt; pi
/etc/pivpn/NO_UFW -&gt; 0
/etc/pivpn/OLD_UFW -&gt; 0
/etc/pivpn/pivpnINTERFACE -&gt; eth0
/etc/pivpn/TWO_POINT_FOUR -&gt; 
=============================================
::::	<u style="text-decoration-style:single">setupVars file shown below</u>	 ::::
INSTALL_USER=pi
UNATTUPG=unattended-upgrades
pivpnInterface=eth0
IPv4dns=
IPv4addr=192.168.1.147
IPv4gw=192.168.1.1
pivpnProto=udp
PORT=1194
ENCRYPT=521
APPLY_TWO_POINT_FOUR=true
DOWNLOAD_DH_PARAM=false
PUBLICDNS=REMOTE
OVPNDNS1=194.168.1.149
OVPNDNS2=1.1.1.1
=============================================
::::  <u style="text-decoration-style:single">Server configuration shown below</u>   ::::
dev tun
proto udp
port 1194
ca /etc/openvpn/easy-rsa/pki/ca.crt
cert /etc/openvpn/easy-rsa/pki/issued/pi-rate_a54760ec-7eb3-42d6-a9b7-fc14b2970832.crt
key /etc/openvpn/easy-rsa/pki/private/pi-rate_a54760ec-7eb3-42d6-a9b7-fc14b2970832.key
dh none
topology subnet
server 10.8.0.0 255.255.255.0
# Set your primary domain name server address for clients
push &quot;dhcp-option DNS 194.168.1.149&quot;
push &quot;dhcp-option DNS 1.1.1.1&quot;
# Prevent DNS leaks on Windows
push &quot;block-outside-dns&quot;
# Override the Client default gateway by using 0.0.0.0/1 and
# 128.0.0.0/1 rather than 0.0.0.0/0. This has the benefit of
# overriding but not wiping out the original default gateway.
push &quot;redirect-gateway def1&quot;
client-to-client
keepalive 1800 3600
remote-cert-tls client
tls-version-min 1.2
tls-crypt /etc/openvpn/easy-rsa/pki/ta.key
cipher AES-256-CBC
auth SHA256
user nobody
group nogroup
persist-key
persist-tun
crl-verify /etc/openvpn/crl.pem
status /var/log/openvpn-status.log 20
status-version 3
syslog
verb 3
#DuplicateCNs allow access control on a less-granular, per user basis.
#Remove # if you will manage access by user instead of device. 
#duplicate-cn
# Generated for use by PiVPN.io
=============================================
::::  <u style="text-decoration-style:single">Client template file shown below</u>   ::::
client
dev tun
proto udp
remote REMOTE 1194
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
tls-version-min 1.2
verify-x509-name pi-rate_a54760ec-7eb3-42d6-a9b7-fc14b2970832 name
cipher AES-256-CBC
auth SHA256
auth-nocache
verb 3
=============================================
:::: 	<u style="text-decoration-style:single">Recursive list of files in</u>	 ::::
::: <u style="text-decoration-style:single">/etc/openvpn/easy-rsa/pki shows below</u> :::
/etc/openvpn/easy-rsa/pki/:
ca.crt
crl.pem
Default.txt
ecparams
extensions.temp
index.txt
index.txt.attr
index.txt.attr.old
index.txt.old
issued
openssl-easyrsa.cnf
private
renewed
revoked
safessl-easyrsa.cnf
serial
serial.old
ta.key
test.ovpn

/etc/openvpn/easy-rsa/pki/ecparams:
secp521r1.pem

/etc/openvpn/easy-rsa/pki/issued:
pi-rate_a54760ec-7eb3-42d6-a9b7-fc14b2970832.crt
test.crt

/etc/openvpn/easy-rsa/pki/private:
ca.key
pi-rate_a54760ec-7eb3-42d6-a9b7-fc14b2970832.key
test.key

/etc/openvpn/easy-rsa/pki/renewed:
private_by_serial
reqs_by_serial

/etc/openvpn/easy-rsa/pki/renewed/private_by_serial:

/etc/openvpn/easy-rsa/pki/renewed/reqs_by_serial:

/etc/openvpn/easy-rsa/pki/revoked:
private_by_serial
reqs_by_serial

/etc/openvpn/easy-rsa/pki/revoked/private_by_serial:

/etc/openvpn/easy-rsa/pki/revoked/reqs_by_serial:
=============================================
::::		<u style="text-decoration-style:single">Self check</u>		 ::::
:: [OK] IP forwarding is enabled
:: [OK] Ufw is enabled
:: [OK] Iptables MASQUERADE rule set
:: [OK] Ufw input rule set
:: [OK] Ufw forwarding rule set
:: [OK] OpenVPN is running
:: [OK] OpenVPN is enabled (it will automatically start on reboot)
:: [OK] OpenVPN is listening on port 1194/udp
=============================================
::::      <u style="text-decoration-style:single">Snippet of the server log</u>      ::::
Sep 15 20:19:21 pi-rate ovpn-server[8066]: OpenVPN 2.4.7 arm-unknown-linux-gnueabihf [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 20 2019
Sep 15 20:19:21 pi-rate ovpn-server[8066]: library versions: OpenSSL 1.1.1c  28 May 2019, LZO 2.10
Sep 15 20:19:21 pi-rate ovpn-server[8066]: NOTE: your local LAN uses the extremely common subnet address 192.168.0.x or 192.168.1.x.  Be aware that this might create routing conflicts if you connect to the VPN server from public locations such as internet cafes that use the same subnet.
Sep 15 20:19:21 pi-rate ovpn-server[8066]: Outgoing Control Channel Encryption: Cipher &apos;AES-256-CTR&apos; initialized with 256 bit key
Sep 15 20:19:21 pi-rate ovpn-server[8066]: Outgoing Control Channel Encryption: Using 256 bit message hash &apos;SHA256&apos; for HMAC authentication
Sep 15 20:19:21 pi-rate ovpn-server[8066]: Incoming Control Channel Encryption: Cipher &apos;AES-256-CTR&apos; initialized with 256 bit key
Sep 15 20:19:21 pi-rate ovpn-server[8066]: Incoming Control Channel Encryption: Using 256 bit message hash &apos;SHA256&apos; for HMAC authentication
Sep 15 20:19:21 pi-rate ovpn-server[8066]: TUN/TAP device tun0 opened
Sep 15 20:19:21 pi-rate ovpn-server[8066]: TUN/TAP TX queue length set to 100
Sep 15 20:19:21 pi-rate ovpn-server[8066]: /sbin/ip link set dev tun0 up mtu 1500
Sep 15 20:19:21 pi-rate ovpn-server[8066]: /sbin/ip addr add dev tun0 10.8.0.1/24 broadcast 10.8.0.255
Sep 15 20:19:21 pi-rate ovpn-server[8066]: Could not determine IPv4/IPv6 protocol. Using AF_INET
Sep 15 20:19:21 pi-rate ovpn-server[8066]: Socket Buffers: R=[163840-&gt;163840] S=[163840-&gt;163840]
Sep 15 20:19:21 pi-rate ovpn-server[8066]: UDPv4 link local (bound): [AF_INET][undef]:1194
Sep 15 20:19:21 pi-rate ovpn-server[8066]: UDPv4 link remote: [AF_UNSPEC]
Sep 15 20:19:21 pi-rate ovpn-server[8066]: GID set to nogroup
Sep 15 20:19:21 pi-rate ovpn-server[8066]: UID set to nobody
Sep 15 20:19:21 pi-rate ovpn-server[8066]: MULTI: multi_init called, r=256 v=256
Sep 15 20:19:21 pi-rate ovpn-server[8066]: IFCONFIG POOL: base=10.8.0.2 size=252, ipv6=0
Sep 15 20:19:21 pi-rate ovpn-server[8066]: Initialization Sequence Completed
=============================================
::::		<u style="text-decoration-style:single">Debug complete</u>		 ::::
::: 
::: Debug output completed above.
::: Copy saved to /tmp/debug.txt
::: 
</pre>
```
### Have you taken any steps towards solving your issue?
```
  i have completely removed pivpn and tried to install it various times without luck. Also i tried connecting through my local network without luck.
pining port 1194 from a separate PC on the same network revealed it's open
```
Thank you guys in advance

**Comment by 4s3ti** [comment]
trying to connect from the same network is useless and often not helpful at all for troubleshooting.
the port might be open but if there is no NAT Loop-back support on your router it is not activated won't help much as you will still wont be able to connect. 

if everything on your router is forwarded like you say then all should be fine on that side. 

Can you please try to connect from another network outside of your home and provide some logs on the client side? 

Also, often ISP's place their customers behind a NAT and in those cases you can't connect to home as that IP is shared with a bunch of other customers, can you check if its not your case as well? 


Thank you.

**Comment by ewouddeenik** [comment]
I have port forwarding set up correctly, i also run a plex-server that im able to connect to from outside my network. The first router sends all data from these ports to the second router that forwards it to the pi. I dont know if it makes any difference but i use No-IP to provide a hostname to the outside IP.

I tried re-installing it again but still no working VPN.
The log's from the client side do not seem to reveal anything to me but maybe to you they provide some data.

Wed Oct 02 20:13:06 2019 OpenVPN 2.4.7 x86_64-w64-mingw32 [SSL (OpenSSL)] [LZO] [LZ4] [PKCS11] [AEAD] built on Apr 25 2019
Wed Oct 02 20:13:06 2019 Windows version 6.2 (Windows 8 or greater) 64bit
Wed Oct 02 20:13:06 2019 library versions: OpenSSL 1.1.0j  20 Nov 2018, LZO 2.10
Wed Oct 02 20:13:06 2019 MANAGEMENT: TCP Socket listening on [AF_INET]127.0.0.1:25341
Wed Oct 02 20:13:06 2019 Need hold release from management interface, waiting...
Wed Oct 02 20:13:06 2019 MANAGEMENT: Client connected from [AF_INET]127.0.0.1:25341
Wed Oct 02 20:13:06 2019 MANAGEMENT: CMD 'state on'
Wed Oct 02 20:13:06 2019 MANAGEMENT: CMD 'log all on'
Wed Oct 02 20:13:06 2019 MANAGEMENT: CMD 'echo all on'
Wed Oct 02 20:13:06 2019 MANAGEMENT: CMD 'bytecount 5'
Wed Oct 02 20:13:06 2019 MANAGEMENT: CMD 'hold off'
Wed Oct 02 20:13:06 2019 MANAGEMENT: CMD 'hold release'
Wed Oct 02 20:13:12 2019 MANAGEMENT: CMD 'password [...]'
Wed Oct 02 20:13:12 2019 WARNING: Your certificate is not yet valid!
Wed Oct 02 20:13:12 2019 Outgoing Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Wed Oct 02 20:13:12 2019 Outgoing Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Wed Oct 02 20:13:12 2019 Incoming Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Wed Oct 02 20:13:12 2019 Incoming Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Wed Oct 02 20:13:12 2019 MANAGEMENT: >STATE:1570039992,RESOLVE,,,,,,
Wed Oct 02 20:13:12 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]217.120.28.139:1194
Wed Oct 02 20:13:12 2019 Socket Buffers: R=[65536->65536] S=[65536->65536]
Wed Oct 02 20:13:12 2019 UDP link local: (not bound)
Wed Oct 02 20:13:12 2019 UDP link remote: [AF_INET]217.120.28.139:1194
Wed Oct 02 20:13:12 2019 MANAGEMENT: >STATE:1570039992,WAIT,,,,,,
Wed Oct 02 20:14:12 2019 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Wed Oct 02 20:14:12 2019 TLS Error: TLS handshake failed
Wed Oct 02 20:14:12 2019 SIGUSR1[soft,tls-error] received, process restarting
Wed Oct 02 20:14:12 2019 MANAGEMENT: >STATE:1570040052,RECONNECTING,tls-error,,,,,
Wed Oct 02 20:14:12 2019 Restart pause, 5 second(s)
Wed Oct 02 20:14:17 2019 MANAGEMENT: >STATE:1570040057,RESOLVE,,,,,,
Wed Oct 02 20:14:17 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]217.120.28.139:1194
Wed Oct 02 20:14:17 2019 Socket Buffers: R=[65536->65536] S=[65536->65536]
Wed Oct 02 20:14:17 2019 UDP link local: (not bound)
Wed Oct 02 20:14:17 2019 UDP link remote: [AF_INET]217.120.28.139:1194
Wed Oct 02 20:14:17 2019 MANAGEMENT: >STATE:1570040057,WAIT,,,,,,
Wed Oct 02 20:15:17 2019 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Wed Oct 02 20:15:17 2019 TLS Error: TLS handshake failed
Wed Oct 02 20:15:17 2019 SIGUSR1[soft,tls-error] received, process restarting
Wed Oct 02 20:15:17 2019 MANAGEMENT: >STATE:1570040117,RECONNECTING,tls-error,,,,,
Wed Oct 02 20:15:17 2019 Restart pause, 5 second(s)
Wed Oct 02 20:15:22 2019 MANAGEMENT: >STATE:1570040122,RESOLVE,,,,,,
Wed Oct 02 20:15:22 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]217.120.28.139:1194
Wed Oct 02 20:15:22 2019 Socket Buffers: R=[65536->65536] S=[65536->65536]
Wed Oct 02 20:15:22 2019 UDP link local: (not bound)
Wed Oct 02 20:15:22 2019 UDP link remote: [AF_INET]217.120.28.139:1194
Wed Oct 02 20:15:22 2019 MANAGEMENT: >STATE:1570040122,WAIT,,,,,,

**Comment by ewouddeenik** [comment]
complete fresh install and reset of router (and port forwarding) worked.
pivpn is now up and running. Probably i made a mistake in a config file of some sort.
