### ISSUE TITLE
PiVPN with Pi-Hole Wiki FAQ

### ISSUE THREAD

**Issue by ZetiX** [pivpn/pivpn#835]
Is the wiki FAQ for PiVPN with Pi-Hole still correct? 

`/etc/dnsmasq` only contains `conf-dir=/etc/dnsmasq.d`

Should I still add `listen-address=127.0.0.1, 192.168.1.2, 10.8.0.1` to this file or the `01-pihole.conf` file in `/etc/dnsmasq.d`?

**Comment by orazioedoardo** [comment]
Not in the `01-pihole.conf`, because that will be replaced upon pihole update. Create a new file like `02-pivpn.conf` and that line inside. Alternatively you could just add `interface=tun0` that works the same. Remember to restart the dns `pihole restartdns`.

**Comment by ZetiX** [comment]
I just added the line to `/etc/dnsmasq` and it works fine after restarting. But the wiki really needs an update though. Some of the paths and information are a bit dated/incorrect such as editing the conf file but it's telling you to edit a con file.

**Comment by 4s3ti** [comment]
will fix it later today. thanks for the heads up.

**Comment by 4s3ti** [comment]
FAQ Updated. closing
