### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by Dhy19971** [pivpn/pivpn#837]
there are problems with the installation. What am I doing wrong? Rapbian light last version on raspberry pi 3 b+.

`root@raspberrypi://home/pi# curl -L https://install.pivpn.io | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
root@raspberrypi://home/pi# curl --insecure -L https://install.pivpn.io | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   178  100   178    0     0    249      0 --:--:-- --:--:-- --:--:--   248
100 58458  100 58458    0     0  43206      0  0:00:01  0:00:01 --:--:-- 43206
:::
::: You are root.
::: Verifying free disk space...
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: Your system is up to date! Continuing with PiVPN installation...
::: Static IP already configured.
::: Using User: pi
:::
::: Checking for existing base files...
:::    Checking /etc/.pivpn is a repo...:::    Cloning https://github.com/pivpn/pivpn.git into /etc/.pivpn... [/]  fatal: unable to access 'https://github.com/pivpn/pivpn.git/': server certificate verification failed. CAfile: none CRLfile: none                                                                                                      done!
:::
::: Stopping OpenVPN service... done.

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
cp: cannot stat 'unattended-upgrades-1.9/data/50unattended-upgrades.Raspbian': No such file or directory
:::
::: Installing scripts to /opt/pivpn...cp: cannot stat '/etc/.pivpn/scripts/makeOVPN.sh': No such file or directory
cp: cannot stat '/etc/.pivpn/scripts/clientStat.sh': No such file or directory
cp: cannot stat '/etc/.pivpn/scripts/listOVPN.sh': No such file or directory
cp: cannot stat '/etc/.pivpn/scripts/removeOVPN.sh': No such file or directory
cp: cannot stat '/etc/.pivpn/scripts/uninstall.sh': No such file or directory
cp: cannot stat '/etc/.pivpn/scripts/pivpnDebug.sh': No such file or directory
chmod: cannot access '/opt/pivpn/makeOVPN.sh': No such file or directory
chmod: cannot access '/opt/pivpn/clientStat.sh': No such file or directory
chmod: cannot access '/opt/pivpn/listOVPN.sh': No such file or directory
chmod: cannot access '/opt/pivpn/removeOVPN.sh': No such file or directory
chmod: cannot access '/opt/pivpn/uninstall.sh': No such file or directory
chmod: cannot access '/opt/pivpn/pivpnDebug.sh': No such file or directory
cp: cannot stat '/etc/.pivpn/pivpn': No such file or directory
chmod: cannot access '/usr/local/bin/pivpn': No such file or directory
cp: cannot stat '/etc/.pivpn/scripts/bash-completion': No such file or directory
main: line 414: /etc/bash_completion.d/pivpn: No such file or directory
 done.
::: Using protocol: udp

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
chown: cannot access '/etc/openvpn/easy-rsa': No such file or directory
mkdir: cannot create directory ‘/etc/openvpn/easy-rsa/pki’: No such file or directory
main: line 825: cd: /etc/openvpn/easy-rsa: No such file or directory
root@raspberrypi://home/pi#
`

**Comment by Dhy19971** [comment]
I also tried this way .. but not work


`root@raspberrypi://home/pi/pivpn/auto_install# ./install.sh
:::
::: You are root.
::: Verifying free disk space...
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: Your system is up to date! Continuing with PiVPN installation...
::: Static IP already configured.
::: Using User: pi
:::
::: Checking for existing base files...
:::    Checking /etc/.pivpn is a repo... OK!
:::     Updating repo in /etc/.pivpn... done!
:::
::: Stopping OpenVPN service... done.
:::
::: Installing scripts to /opt/pivpn... done.
::: Using protocol: udp
tar: /etc/openvpn: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
chown: cannot access '/etc/openvpn/easy-rsa': No such file or directory
mkdir: cannot create directory ‘/etc/openvpn/easy-rsa/pki’: No such file or directory
./install.sh: line 825: cd: /etc/openvpn/easy-rsa: No such file or directory
root@raspberrypi://home/pi/pivpn/auto_install#
`

**Comment by Dhy19971** [comment]
I also tried this way .. no work

`root@raspberrypi://home/pi/pivpn/auto_install# ./install.sh
:::
::: You are root.
::: Verifying free disk space...
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: Your system is up to date! Continuing with PiVPN installation...
::: Static IP already configured.
::: Using User: pi
:::
::: Checking for existing base files...
:::    Checking /etc/.pivpn is a repo... OK!
:::     Updating repo in /etc/.pivpn... done!
:::
::: Stopping OpenVPN service... done.
:::
::: Installing scripts to /opt/pivpn... done.
::: Using protocol: udp
tar: /etc/openvpn: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
chown: cannot access '/etc/openvpn/easy-rsa': No such file or directory
mkdir: cannot create directory ‘/etc/openvpn/easy-rsa/pki’: No such file or directory
./install.sh: line 825: cd: /etc/openvpn/easy-rsa: No such file or directory
root@raspberrypi://home/pi/pivpn/auto_install# ^C
root@raspberrypi://home/pi/pivpn/auto_install#
`

**Comment by orazioedoardo** [comment]
This is the reason: `curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.`.

What os are you on?

Output of `cat /etc/os-release`?

Try to reinstall the certificates: `sudo apt install --reinstall ca-certificates`.

**Comment by 4s3ti** [comment]
@orazioedoardo aparently is using raspbian as per: 

> there are problems with the installation. What am I doing wrong? Rapbian light last version on raspberry pi 3 b+.

but looks to me the result of a heavily broken system!  please read: https://github.com/pivpn/pivpn#feedback--support

and reopen this ticket with a issue template properly filled and detailed. 

before reopening or opening a new issue i recommend a fresh install of raspbian, 
run: `sudo apt-get update && sudo apt-get upgrade` then try again running pivpn with `curl -L https://install.pivpn.io | bash`
