### ISSUE TITLE
Portforwarding UDP or TCP?

### ISSUE THREAD

**Issue by Mausy5043** [pivpn/pivpn#839]
In raising this issue, I confirm the following: 

- [x] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*. I keep having the same question 
- [x] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

### Question
Not so much a bug/issue as a question.  
When I went to open port 1194 on my Firewall/Router I noticed that it insisted on using TCP and seemed to discourage use of UDP. The installer seems to insist on UDP and implicitly warns against use of TCP unless "you know why you need TCP". 

I've set-up the router to use UDP port 1194, but I was just wondering what the considerations would be to choose either UDP or TCP?

**Comment by orazioedoardo** [comment]
Suggested reading: https://openvpn.net/faq/what-is-tcp-meltdown/

If satisfied, close the issue.

**Comment by Mausy5043** [comment]
TIL, TCP meltdown.

Thanks!
