### ISSUE TITLE
www.pivpn.io lacks a proper security certificate.

### ISSUE THREAD

**Issue by peatrick** [pivpn/pivpn#841]
http://www.pivpn.io/ lacks an SSL/TLS security certificate and this is scaring away potential (sometimes less technically savvy) users.  This is something that can (and should) be easily remedied at no additional cost, in under an hour of your time (assuming you have access to your domain registrar).  [Let's Encrypt](https://letsencrypt.org/getting-started/) is a fabulous solution and was intended for this exact scenario.

![image](https://user-images.githubusercontent.com/26148066/66248433-f2b70480-e6f4-11e9-9566-6578a8d478b6.png)

Thank you for your time and attention to my little matter.  Help me, help you.  Love and have been using PiVPN for a number of years now.  Thank you for all of your hard work!  I'll be looking forward to seeing a bright green "A" on these results in the not too distant future:  https://www.ssllabs.com/ssltest/analyze.html?d=www.pivpn.io

**Comment by orazioedoardo** [comment]
I recall it was because of the difficulty in reaching the website owner. Such conversation is probably in the closed issues.

**Comment by 4s3ti** [comment]
Closing.. Duplicate of: https://github.com/pivpn/pivpn/issues/236
