### ISSUE TITLE
 impossible connection during installation

### ISSUE THREAD

**Issue by n0v0caine** [pivpn/pivpn#842]
_**pi@novo:~ $**_ **curl -L https://install.pivpn.io/ | bash**

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:07 --:--:--     0curl: (7) Failed to connect to install.pivpn.io port 443: Aucun chemin d'accès pour atteindre l'hôte cible

**Comment by n0v0caine** [comment]
I tested several times and the soft (pivpn) answer is always the same. I don't understood why...
Perhaps it's my port

**Comment by orazioedoardo** [comment]
The error is "No route to host". Your Raspberry Pi doesn't know how to reach the pivpn website (which works so it's an issue on your side). Does `curl google.com` work?

**Comment by n0v0caine** [comment]
Hello @orazioedoardo ,

Yes "curl google.com" is working:

> pi@NovoRaspberry:~ $ curl google.com
> <HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
> <TITLE>301 Moved</TITLE></HEAD><BODY>
> <H1>301 Moved</H1>
> The document has moved
> <A HREF="http://www.google.com/">here</A>.
> </BODY></HTML>

**Comment by orazioedoardo** [comment]
Install traceroute with `sudo apt install traceroute` and post the output of `traceroute install.pivpn.io`.

**Comment by n0v0caine** [comment]
I have already tried this solution, and the answer is the same:


`` pi@NovoRaspberry:~ $ curl https://raw.githubusercontent.com/pivpn/pivpn/master/auto_install/install.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:06 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:07 --:--:--     0curl: (7) Failed to connect to raw.githubusercontent.com port 443: Aucun chemin d'accès pour atteindre l'hôte cible
pi@NovoRaspberry:~ $

**Comment by orazioedoardo** [comment]
No updates in a while and most likely a misconfiguration on the user network, closing...
