### ISSUE TITLE
PiVPN not working with Ubuntu 19.04

### ISSUE THREAD

**Issue by mortosss** [pivpn/pivpn#843]
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

### Issue
Hello, 
I've installed pivpn on Ubuntu 19.04, it's installing successfully, but while I'm trying to connect from my Android device I'm getting timeout and waiting status. There are no logs. I've made a test and installed the full OpenVPN version manually and it's working fine. Can you please inform me is this going to be resolved ?
### Have you searched for similar issues and solutions?
    (yes)

### Console output of      `curl -L install.pivpn.io | bash`
```
  Output Here
```

### Console output of      `pivpn add` or `pivpn add nopass`
```
  Output Here
```

### Console output of      `pivpn debug`
```
  Output Here
```
### Have you taken any steps towards solving your issue?
```
I've checked the /var/log/openvpn-status.log, but it's empty
```

**Comment by orazioedoardo** [comment]
You are supposed to replace `Output Here` with the output of the commands above.

**Comment by mortosss** [comment]
@orazioedoardo  What output do you expect ? The installation is successful, but once I try to connect via my Android phone, the connection is not happening, there are no logs - nothing. I made legacy openvpn installation and it's working. Can someone try to use pivpn on Ubuntu 19.04 ?

**Comment by 4s3ti** [comment]
Closed ... Wondering why? 

Read here: 

https://github.com/pivpn/pivpn#feedback--support
