### ISSUE TITLE
[Request for Comments] Add optional WireGuard support

### ISSUE THREAD

**Issue by orazioedoardo** [pivpn/pivpn#844]
I would like to discuss about WireGuard support within the PiVPN script. I'm going to skip over the speed and simplicity advantages over OpenVPN, instead i will talk about the impact on the project.

The main advantage is that WireGuard is very hard to get wrong: since there is very little configuration to do, the installation would be much simpler to handle: no easy-rsa, no PKI to create, no client expiration, no mismatched client and server features. Also mobile clients can connects just by scanning a qr-code instead of moving sensitive configurations over the network.

WireGuard is available as a package via the armhf Debian repo, which I have been testing with for a while on the Raspberry Pi. It works perfectly fine however I found that during some kernel upgrades the module is not being rebuild, requiring `dpkg-reconfigure wireguard-dkms` to solve (this could be automated using an apt post-install script).

According to [this](https://github.com/adrianmihalko/raspberrypiwireguard/wiki/Install-WireGuard-on-Raspberry-Pi-1,-2-(not-v1.2),-Zero,-Zero-W), on some Raspberry Pis we would need to manually download and compile the script. I managed to replicate the apt installation using DKMS but not on every Pi since I don't have all of them. Perhaps the script should read `/proc/cpuinfo` and decide whether to install the package or compile manually.

I see WireGuard implemented more and more on reputable projects like [AlgoVPN](https://github.com/trailofbits/algo) and [Streisand](https://github.com/StreisandEffect/streisand).

I'm tagging @4s3ti to get started.

**Comment by 4s3ti** [comment]
O only see advantages with wireguard to be honest .. however... will we ditch OpenVPN? keep both?

**Comment by 4s3ti** [comment]
to get this done initially i would say we put a branch test-wireguard that goes sideways with test branch and wen we feel its stable and clean enough we push it to master branch.

i haven't tested wireguard myself but guess its a great time to test it.. i am needing vpn at home so i guess that will be it =)

**Comment by orazioedoardo** [comment]
Can you add the `test-wireguard` branch? I will send a pull request shortly to begin with.

**Comment by 4s3ti** [comment]
ill fork it from test and push it in a sec

**Comment by 4s3ti** [comment]
Done, branched from test which includes the changes i have just pushed to test branch. 

https://github.com/pivpn/pivpn/tree/test-wireguard

**Comment by mwoolweaver** [comment]
Is WireGuard a full tunnel or split tunnel?

**Comment by orazioedoardo** [comment]
> Is WireGuard a full tunnel or split tunnel?

You can do both. PiVPN is full tunnel so the client forwards everything (0.0.0.0/0): https://github.com/pivpn/pivpn/blob/d34577329e47bff4151de82daf715a1ca6e8de48/scripts/wireguard/makeCONF.sh#L105

**Comment by mwoolweaver** [comment]
Thank you for that! Also changing to just the IP range of the tunnel will make it a split tunnel.

**Comment by JasperTecHK** [comment]
Ah, good to see that wireguard may get a simplifed script install. I can ditch the one I wrote in favor of this one, assuming it makes it past the test branch!

**Comment by orazioedoardo** [comment]
> Also, would you guys be opting to just generate the users and presenting the access file or would you also integrate the suggested QR code method as well?

Yes, have a look! https://github.com/pivpn/pivpn/tree/test#connecting-to-the-pivpn-server-wireguard

**Comment by 4s3ti** [comment]
Just finished reviewing the whole installer... 

I have to say that i really like your code @orazioedoardo GJ with test branch and wireguard. 

The only thing that worries me is the support we had for Devuan, which as the script is right now completely dropped it as devuan doesn't have systemctl which is part of systemd.

Other than that... guess we can just finish with any pending feature requests and issues and we are good to go.  

during today and tomorrow i will still do some code changes to change some simple stuff.

**Comment by orazioedoardo** [comment]
> The only thing that worries me is the support we had for Devuan, which as the script is right now completely dropped it as devuan doesn't have systemctl which is part of systemd.

I don’t remember Devuan-specific code, so it should work just by adding `sudo service whatever restart`. For WireGuard though, we need an [init script](https://dev1galaxy.org/viewtopic.php?id=2802).

**Comment by orazioedoardo** [comment]
> The only thing that worries me is the support we had for Devuan, which as the script is right now completely dropped it as devuan doesn't have systemctl which is part of systemd.

I don’t remember Devuan-specific code, so it should work just by using `sudo service whatever restart`. Not sure

**Comment by 4s3ti** [comment]
@orazioedoardo yeah ... i am actually considering drop devuan tbh ... instead of supporting extra OS ... i with unattended working we can distribute docker image instead which will be far better than all the trouble of supporting more OS

**Comment by muibusan** [comment]
Here's an article with quite a few cons to Wireguard. How do they apply to PiVPN?

https://restoreprivacy.com/wireguard/
German translation: https://vpn-anbieter-vergleich-test.de/wireguard-vpn-was-du-wissen-solltest/

I'd vote for not ditching OpenVPN support.

**Comment by JasperTecHK** [comment]
> Here's an article with quite a few cons to Wireguard. How do they apply to PiVPN?
> 
> https://restoreprivacy.com/wireguard/
> German translation: https://vpn-anbieter-vergleich-test.de/wireguard-vpn-was-du-wissen-solltest/
> 
> I'd vote for not ditching OpenVPN support.

IMO, even though I'm not the devs, my opinion on this, is that most of the cons are related to no trust on the untested new system, and the fact that it keeps static information. 

The thing is, they even claim up front to not trust this until they roll out a 1.0 release, so already, they say "Here, it should work, but if you're working on security heavy stuff, maybe put off it for now until it has been thoroughly vetted. 

Next, the fact that everything had to start somewhere. Wireguard is new, and as said above, unvetted yet. So, not everyone would trust it. Makes sense. But that just means when it does get vetted, and flaws are fixed, it would probably work just fine. Surely even OpenVPN had to go through this.

No dynamic address allocation isn't that big of an issue for this project, IMO, since the intended targets are more likely to be diy hobbyists and not the enterprise or security critical people. But even if it needed dynamic allocation, you could probably bundle an extra script that could deal with it. Of course, not a feasible operation if you have a lot of clients and a lot of server endpoints, but again, not the target anyways.

But I won't address the TCP issue. I'm not "learned" enough to answer that. But I suppose packet integrity is a nice thing to have.

Btw. I believe it's an optional thing. I.e. PiVPN will still keep OpenVPN, but it would alsl set up Wireguard. So, just generate clients on either one when you need it, as it is now?

**Comment by orazioedoardo** [comment]
> WireGuard lacks dynamic IP address management. The client needs to be assigned in advance a pre-defined VPN IP address uniquely linked to its key on each VPN server. The impact on the anonymity layer is catastrophic;

Having a static IP address inside the tunnel makes easy for a VPN operator to track users across different sessions, but this is not a concern for PiVPN as YOU are the actual VPN operator.

> WireGuard client does not verify the server identity (a feature so essential that it will be surely implemented when Wireguard will be no more an experimental sofware); the impact on security caused by this flaw is very high;

This is not true, the client literally has the public key of the server inside its config so you can’t connect to a fake WireGuard server since it won’t have the corresponding private key.

TCP support is missing (third party or anyway additional code is required to use TCP as the tunneling protocol, as you suggest, and that’s a horrible regression when compared to OpenVPN);

> That’s why OpenVPN is still supported in the test (soon to be master) branch.

> there is no support to connect Wireguard to a VPN server over some proxy with a variety of authentication methods.

WireGuard is a basic building block on top of which additional features may be added in the future using other tools, but if you need these now, as the previous, you have OpenVPN.

Regarding security, there are several audits of the WireGuard protocol (check the website), formal verification and it will be in the Linux 5.6 kernel. I’ve not seen catastrophic vulnerabilities by now and it is in development since 2015-2016 i think.

**Comment by TinCanTech** [comment]
Also note:  WireGaurd developed a driver called `wintun` (Tun adapter for Windows). OpenVPN are now using that themselves along with the normal TAP adapter.

**Comment by orazioedoardo** [comment]
> Also note: WireGaurd developed a driver called `wintun` (Tun adapter for Windows). OpenVPN are now using that themselves along with the normal TAP adapter.

Didn’t know that, thanks!

**Comment by 4s3ti** [comment]
WoW! =D great topic and talk here!!! 

anyhow @JasperTecHK We are not dropping OpenVPN it will still be there, just pic the one you prefer! =)

**Comment by 4s3ti** [comment]
WoW! =D great topic and talk here!!! 

anyhow @JasperTecHK We are not dropping OpenVPN it will still be there, just pic the one you prefer! =)

**Comment by JasperTecHK** [comment]
> WoW! =D great topic and talk here!!!
> 
> anyhow @JasperTecHK We are not dropping OpenVPN it will still be there, just pic the one you prefer! =)

I... know you would be keeping OpenVPN. I think you might have CC'd the wrong person.

**Comment by JasperTecHK** [comment]
> WoW! =D great topic and talk here!!!
> 
> anyhow @JasperTecHK We are not dropping OpenVPN it will still be there, just pic the one you prefer! =)

I... know you would be keeping OpenVPN. I think you might have CC'd the wrong person.

**Comment by 4s3ti** [comment]
hmmm ... Opps!!! xD I am sorry @JasperTecHK actually that answer was meant to @muibusan

**Comment by Beowulf2** [comment]
I have a problem...
I cannot generate a QRCode...
![image](https://user-images.githubusercontent.com/60288895/73120321-b42bab00-3f6c-11ea-978f-1dadbd158c08.png)

**Comment by orazioedoardo** [comment]
@Beowulf2 qrencode should have been installed though... `sudo apt install qrencode`

**Comment by 4s3ti** [comment]
Guess this can be closed, for any issues please open a proper issue report.
