### ISSUE TITLE
Pem password when adding vpn user

### ISSUE THREAD

**Issue by kingcatdaan** [pivpn/pivpn#85]
i get this error no matter what i do

root@Anna:~# pivpn add
Enter a Name for the Client:  daan
NOTE: If you run ./clean-all, I will be doing a rm -rf on /etc/openvpn/easy-rsa/keys
Enter the password for the Client:
Enter the password again to verify:
spawn ./build-key-pass daan
Generating a 4096 bit RSA private key
....................................................................................................................++
......................................................................++
writing new private key to 'daan.key'
Enter PEM pass phrase:
spawn openssl rsa -in daan.key -des3 -out daan.3des.key
unable to load Private Key
3069334736:error:0906D06C:PEM routines:PEM_read_bio:no start line:pem_lib.c:696:Expecting: ANY PRIVATE KEY
expect: spawn id exp6 not open
    while executing
"expect "Enter PEM pass phrase" { send "passwd\r" }"
[ERROR]: Client Public Key Certificate not found: daan.crt

**Comment by ant1612** [comment]
Hi,

I've got this error before. The only way I've "fixed" this is to repeat the same command again. Seems to work the second time round. 

I've done this for two/three different users and each time it appears with a fault

After the second attempt on each user, I've not issues logging in or it appearing to be at fault

**Comment by michielvanhoorn** [comment]
I have this issue too but doing it twice does not help.

**Comment by BOZG** [comment]
It worked fine for me when I first installed PiVPN. I need to uninstall and then reinstall and after that, this error kept appearing.
