### ISSUE TITLE
auth-user-pass-verify in a config file

### ISSUE THREAD

**Issue by rameijeirasfe** [pivpn/pivpn#854]
Hi,

Is possible add to the config file the line auth-user-pass-verify for manual parse the credenciales by scrtipt??

Thanks

**Comment by 4s3ti** [comment]
can you please clarify and better detail what you pretend? thanks

**Comment by rameijeirasfe** [comment]
Yes. I need create a script for mapping the user credentials.

https://medium.com/@nqbao/openvpn-auth-user-pass-verify-example-8d99023f08f7

**Comment by 4s3ti** [comment]
This feature falls away from pivpn scope.
Once pivpn installs openvpn you can do with the config whatever you want so you can easily follow what its mentioned on that blog and adapt to your needs.
