### ISSUE TITLE
`easyrsa` executable not on $PATH

### ISSUE THREAD

**Issue by Mausy5043** [pivpn/pivpn#858]
### In raising this issue, I confirm the following: 

- [x] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

### Question
After some searching I discovered that the `easyrsa` executable is installed hidden inside `/etc/openvpn/easy-rsa`   
Is there an operational reason for this set-up ?
Why isn't it installed in one of the `bin` directories?

**Comment by orazioedoardo** [comment]
I think it's simply convenient to keep the script alongside all other related files when unpacking the tar.gz:
```
root@debian:/etc/openvpn/easy-rsa# ls -l
totale 124
-rw-rw-r-- 1 root root  3968 feb  2  2019 ChangeLog
-rw-rw-r-- 1 root root  1305 feb  2  2019 COPYING.md
drwxrwxr-x 2 root root  4096 feb  2  2019 doc
-rwxrwxr-x 1 root root 48730 feb  2  2019 easyrsa
-rw-rw-r-- 1 root root 18093 feb  2  2019 gpl-2.0.txt
-rw-rw-r-- 1 root root  1036 feb  2  2019 mktemp.txt
-rw-rw-r-- 1 root root  4651 feb  2  2019 openssl-easyrsa.cnf
drwx------ 8 root root  4096 ott 14 16:46 pki
-rw-rw-r-- 1 root root  2039 feb  2  2019 README.md
-rw-rw-r-- 1 root root  3335 feb  2  2019 README.quickstart.md
-rw-r--r-- 1 root root   253 ott 14 16:46 vars
-rw-rw-r-- 1 root root  8576 feb  2  2019 vars.example
drwxrwxr-x 2 root root  4096 ott 14 16:46 x509-types
```

**Comment by orazioedoardo** [comment]
No replies in a while, closing...
