### ISSUE TITLE
Unattended Install

### ISSUE THREAD

**Issue by NeoP5** [pivpn/pivpn#86]
It would be good to provide support for unattended installation.

Possible solutions would be:
- possibility to use configuration file
- possibility to use parameters for script

I want to create a PiBakery block(s) for PiVPN.

Thanks in advance....

**Comment by 0-kaladin** [comment]
So would it work for you if the command was something like
`curl -L http://install.pivpn.io | UNATTEND=1 bash`
and that would tell the script to look for a certain formatted config file in a certain location that provides the values you want?

**Comment by NeoP5** [comment]
Hello @0-kaladin ,
yes this would be fine.
Using a predefined config-file is just what I need to run the install-script unattended.

It would be good if the config file is in a format that makes it easy to replace values using a script and is well documented; e.g. http://wiki.bash-hackers.org/howto/conffile

Please let me know if i can help somehow.
Best, Neo

**Comment by 0-kaladin** [comment]
Yea no worries on the format, I won't make it cryptic :)
I'll keep this on my shorter list of enhancement's to tackle since I think it provides good value overall to the project.  thanks for the suggestion as well.

**Comment by jellemdekker** [comment]
Is this issue resolved now that PR #224 was merged?

**Comment by redfast00** [comment]
No, not yet, it'll be resolved when the test branch is merged into the master branch. I don't have any free time atm, so either merging will have to wait at least a week or @0-kaladin will test and merge the test branch.

**Comment by EWouters** [comment]
I'm a bit late to the party, but [this](https://gist.github.com/EWouters/03dfdf88fabd03d33049fb144ec717dd) gist explains how I use the unattended install.

The structure of the config is based on how pi-hole implemented the install. However the suggestions above seem nice too.

**Comment by 4s3ti** [comment]
--unattended has been implemented. 
Resolving.
