### ISSUE TITLE
IP is wrong when I create my .ovpn profiles! 

### ISSUE THREAD

**Issue by computertechie75** [pivpn/pivpn#860]
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*.
- [] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

### Issue
I setup my PIVPN at work and when I took it home to create my profiles I have to go in and edit the IP as it has my work IP in there, Is there a place to change that?

### Have you searched for similar issues and solutions?
    (yes/no / which issues?) Yes

### Console output of      `curl -L install.pivpn.io | bash`
```
  Output Here
```

### Console output of      `pivpn add` or `pivpn add nopass`
```
  Output Here
```

### Console output of      `pivpn debug`
```
  Output Here
```
### Have you taken any steps towards solving your issue?
```I have googles the issue and have came up short on an answer
  which?
```

**Comment by barqySpaniel** [comment]
I believe the default for the config comes from here (this is the only play I found my public address in the openvpn subdirectory):

/etc/openvpn/easy-rsa/pki/Default.txt

you'll need admin rights, like this
sudo nano /etc/openvpn/easy-rsa/pki/Default.txt

**Comment by computertechie75** [comment]
Thank you very much I was able to modify the IP.
