### ISSUE TITLE
PIVPN stopped after no changes - cant't explain it

### ISSUE THREAD

**Issue by scargill** [pivpn/pivpn#864]
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*.
- [] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

### Have you searched for similar issues and solutions?
    (yes/no / which issues?)

### Console output of      `curl -L install.pivpn.io | bash`
```
  Output Here
```

### Console output of      `pivpn add` or `pivpn add nopass`
```
  Output Here
```

### Console output of      `pivpn debug`
```
  Output Here
```
### Have you taken any steps towards solving your issue?
```
  which?
```

**Comment by scargill** [comment]
I've been using PIVPN here in the UK and my place in Spain, no problem for a year or more.  Currently both are on PI4 and have been for weweks. The onl odd circumstances are broadband issues here for the same amount of time. 3 days ago PIVPN here stopped working or rather my Pocophone could not connect to it, neither could/can my wife's phone.

Today the Vodaphone broadband is working just fine, so with that out of the way I tried again. No joy, so rather than mess about I read your instructions here. https://github.com/pivpn/pivpn/wiki/Upgrading

I uninstalled PVPN and reinstalled... I the ncleared the client file fom my phone and made a new one. I am of course running th phone on lonly mobile data, not the house Internet. My Voda router has port redirects to the relevant (none standard but very close) port number. I tried to connect the phone and the result shos that PiVPN is SEEING the phone - but won; connect.


Nov 11 16:37:21 ukpi4 ovpn-server[746]: 82.132.238.165:30655 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #1 / time = (1573490239) Mon Nov 11 16:37:19 2019 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Nov 11 16:37:21 ukpi4 ovpn-server[746]: 82.132.238.165:30655 TLS Error: incoming packet authentication failed from [AF_INET]82.132.238.165:30655

HELP...

**Comment by orazioedoardo** [comment]
Please fill the issue template first (replace `Output Here` with the output of the requested commands).

**Comment by scargill** [comment]
The install was done months ago - and works a treat in one property and has worked every day for months in this property without fail - until last week when Vodafone broadband started giving me trouble - the broadband has ben ok dince yesterday but still no VPN, no other changes that I can think of - and it cannot be my mobile phone client as the OTHER VPN is working just fine. AFTER this I did a full re-install of PIVPN exactly as your recommendation - and it makes no difference. I checked, the Vodafone people did not disable port redirections.  I've tested both UDP and TCP now, neither will let the client connect. Any thoughts?

Here is the output just now of PIVPN DEBUG

 pivpn debug
::: Generating Debug Output
::::            PiVPN debug              ::::
=============================================
::::            Latest commit            ::::
commit d0c10db6ec391961b7201fb564055c1176ca73e3
Author: 4s3ti <cfcolaco@colacoweb.net>
Date:   Tue Sep 3 10:09:48 2019 +0200

    install.sh: apt-get with , uninstall.sh: added var PKG_MANAGER and replaced apt-get with
=============================================
::::        Installation settings        ::::
/etc/pivpn/DET_PLATFORM -> Raspbian
/etc/pivpn/FORWARD_CHAIN_EDITED -> 0
/etc/pivpn/HELP_SHOWN ->
/etc/pivpn/INPUT_CHAIN_EDITED -> 0
/etc/pivpn/INSTALL_PORT -> 1195
/etc/pivpn/INSTALL_PROTO -> udp
/etc/pivpn/INSTALL_USER -> pi
/etc/pivpn/NO_UFW -> 1
/etc/pivpn/pivpnINTERFACE -> eth0
=============================================
::::    setupVars file shown below       ::::
INSTALL_USER=pi
UNATTUPG=unattended-upgrades
pivpnInterface=eth0
IPv4dns=
IPv4addr=192.168.14.74
IPv4gw=192.168.14.1
pivpnProto=udp
PORT=1195
ENCRYPT=2048
APPLY_TWO_POINT_FOUR=false
DOWNLOAD_DH_PARAM=false
PUBLICDNS=
OVPNDNS1=8.8.8.8
OVPNDNS2=8.8.4.4
=============================================
::::  Server configuration shown below   ::::
dev tun
proto udp
port 1195
ca /etc/openvpn/easy-rsa/pki/ca.crt
cert /etc/openvpn/easy-rsa/pki/issued/ukpi4_2c4c30a8-071a-4ab3-a316-95dfb87fac4b.crt
key /etc/openvpn/easy-rsa/pki/private/ukpi4_2c4c30a8-071a-4ab3-a316-95dfb87fac4b.key
dh /etc/openvpn/easy-rsa/pki/dh2048.pem
topology subnet
server 10.8.0.0 255.255.255.0
# Set your primary domain name server address for clients
push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 8.8.4.4"
# Prevent DNS leaks on Windows
push "block-outside-dns"
# Override the Client default gateway by using 0.0.0.0/1 and
# 128.0.0.0/1 rather than 0.0.0.0/0. This has the benefit of
# overriding but not wiping out the original default gateway.
push "redirect-gateway def1"
client-to-client
keepalive 1800 3600
remote-cert-tls client
tls-version-min 1.2
tls-auth /etc/openvpn/easy-rsa/pki/ta.key 0
cipher AES-256-CBC
auth SHA256
user nobody
group nogroup
persist-key
persist-tun
crl-verify /etc/openvpn/crl.pem
status /var/log/openvpn-status.log 20
status-version 3
syslog
verb 3
#DuplicateCNs allow access control on a less-granular, per user basis.
#Remove # if you will manage access by user instead of device.
#duplicate-cn
# Generated for use by PiVPN.io
=============================================
::::  Client template file shown below   ::::
client
dev tun
proto udp
remote REMOTE 1195
resolv-retry infinite
nobind
persist-key
persist-tun
key-direction 1
remote-cert-tls server
tls-version-min 1.2
verify-x509-name ukpi4_2c4c30a8-071a-4ab3-a316-95dfb87fac4b name
cipher AES-256-CBC
auth SHA256
auth-nocache
verb 3
=============================================
::::    Recursive list of files in       ::::
::: /etc/openvpn/easy-rsa/pki shows below :::
/etc/openvpn/easy-rsa/pki/:
ca.crt
crl.pem
Default.txt
dh2048.pem
extensions.temp
index.txt
index.txt.attr
index.txt.attr.old
index.txt.old
issued
openssl-easyrsa.cnf
private
renewed
revoked
safessl-easyrsa.cnf
serial
serial.old
ta.key
ukpi4.ovpn

/etc/openvpn/easy-rsa/pki/issued:
ukpi4_2c4c30a8-071a-4ab3-a316-95dfb87fac4b.crt
ukpi4.crt

/etc/openvpn/easy-rsa/pki/private:
ca.key
ukpi4_2c4c30a8-071a-4ab3-a316-95dfb87fac4b.key
ukpi4.key

/etc/openvpn/easy-rsa/pki/renewed:
private_by_serial
reqs_by_serial

/etc/openvpn/easy-rsa/pki/renewed/private_by_serial:

/etc/openvpn/easy-rsa/pki/renewed/reqs_by_serial:

/etc/openvpn/easy-rsa/pki/revoked:
private_by_serial
reqs_by_serial

/etc/openvpn/easy-rsa/pki/revoked/private_by_serial:

/etc/openvpn/easy-rsa/pki/revoked/reqs_by_serial:
=============================================
::::            Self check               ::::
:: [OK] IP forwarding is enabled
:: [OK] Iptables MASQUERADE rule set
:: [OK] OpenVPN is running
:: [OK] OpenVPN is enabled (it will automatically start on reboot)
:: [OK] OpenVPN is listening on port 1195/udp
=============================================
::::      Snippet of the server log      ::::
Nov 11 22:37:11 ukpi4 ovpn-server[746]: REDACTED:15001 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #1 / time = (1573511825) Mon Nov 11 22:37:05 2019 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Nov 11 22:37:11 ukpi4 ovpn-server[746]: REDACTED:15001 TLS Error: incoming packet authentication failed from [AF_INET]REDACTED:15001
Nov 11 22:37:12 ukpi4 ovpn-server[746]: REDACTED:15001 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #1 / time = (1573511825) Mon Nov 11 22:37:05 2019 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Nov 11 22:37:12 ukpi4 ovpn-server[746]: REDACTED:15001 TLS Error: incoming packet authentication failed from [AF_INET]REDACTED:15001
Nov 11 22:37:13 ukpi4 ovpn-server[746]: REDACTED:15001 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #1 / time = (1573511825) Mon Nov 11 22:37:05 2019 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Nov 11 22:37:13 ukpi4 ovpn-server[746]: REDACTED:15001 TLS Error: incoming packet authentication failed from [AF_INET]REDACTED:15001
Nov 11 22:37:14 ukpi4 ovpn-server[746]: REDACTED:15001 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #1 / time = (1573511825) Mon Nov 11 22:37:05 2019 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Nov 11 22:37:14 ukpi4 ovpn-server[746]: REDACTED:15001 TLS Error: incoming packet authentication failed from [AF_INET]REDACTED:15001
Nov 11 22:37:15 ukpi4 ovpn-server[746]: REDACTED:9266 TLS: Initial packet from [AF_INET]REDACTED:9266, sid=27fabd9e 22da0379
Nov 11 22:37:16 ukpi4 ovpn-server[746]: REDACTED:9266 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #1 / time = (1573511835) Mon Nov 11 22:37:15 2019 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Nov 11 22:37:16 ukpi4 ovpn-server[746]: REDACTED:9266 TLS Error: incoming packet authentication failed from [AF_INET]REDACTED:9266
Nov 11 22:37:49 ukpi4 ovpn-server[746]: REDACTED:1024 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Nov 11 22:37:49 ukpi4 ovpn-server[746]: REDACTED:1024 TLS Error: TLS handshake failed
Nov 11 22:37:49 ukpi4 ovpn-server[746]: REDACTED:1024 SIGUSR1[soft,tls-error] received, client-instance restarting
Nov 11 22:38:05 ukpi4 ovpn-server[746]: REDACTED:15001 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Nov 11 22:38:05 ukpi4 ovpn-server[746]: REDACTED:15001 TLS Error: TLS handshake failed
Nov 11 22:38:05 ukpi4 ovpn-server[746]: REDACTED:15001 SIGUSR1[soft,tls-error] received, client-instance restarting
Nov 11 22:38:15 ukpi4 ovpn-server[746]: REDACTED:9266 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Nov 11 22:38:15 ukpi4 ovpn-server[746]: REDACTED:9266 TLS Error: TLS handshake failed
Nov 11 22:38:15 ukpi4 ovpn-server[746]: REDACTED:9266 SIGUSR1[soft,tls-error] received, client-instance restarting
=============================================
::::            Debug complete           ::::
:::
::: Debug output completed above.
::: Copy saved to /tmp/debug.txt

**Comment by 4s3ti** [comment]
Jeez @scargill  .. it was hard to read!! 
Edited your comment to get the debug output in a code block

**Comment by orazioedoardo** [comment]
Output of `grep tls /etc/openvpn/easy-rsa/pki/ukpi4.ovpn`?

**Comment by scargill** [comment]
Here, meanwhile a pal of mine is on - remotely from his home and he cannot get in but again on debug(good tip) I can see him try and fail... so port redirection is definitely still working.

 sudo grep tls /etc/openvpn/easy-rsa/pki/ukpi4.ovpn
remote-cert-tls server
tls-version-min 1.2
<tls-auth>
</tls-auth>

**Comment by orazioedoardo** [comment]
I updated the comment, try the new one

**Comment by scargill** [comment]
Not sure what that was about...

**Comment by scargill** [comment]
Clearly I and a collage can get to the PIVPN from our moile phones (which contact my Spanish PIVPN no prolem and talked to THIS one until Vodaphone remoted into my modem at the weekend - but as you can see, TLS negotation (I know little about that) fails in a previously perfectly working setup. I have to speak to Vodaphone tomorrow so any insights would be GREATLY appreciated. The port redirection still works or the server would not see the mobiles trying to connect....

**Comment by TinCanTech** [comment]
> I updated the comment, try the new one



> Not sure what that was about...



> Output of `grep 'tls\|direction' /home/pi/ovpns/ukpi4.ovpn`?

Meaning: grep for `tls` or `direction` and post the results.

**Comment by orazioedoardo** [comment]
> Clearly I and a colleague can get to the PIVPN from our mobile phones (which contact my Spanish PIVPN no prolem and talked to THIS one until Vodaphone remoted into my modem at the weekend

Better ask Vodafone what they changed first.

> TLS negotation (I know little about that) fails in a previously perfectly working (for msny months) PIVPN setup.

I usually get those TLS error when there is a poor connection between the client and the server. From the output I think your mobile tries to contact the PiVPN but it doesn’t receive an answer from the server, so it resends the packet (replay error).

> The port redirection still works or the server would not see the mobiles trying to connect....

Yes for sure.

**Comment by scargill** [comment]
Here it is, TinCanTech

grep 'tls\|direction' /home/pi/ovpns/ukpi4.ovpn
key-direction 1
remote-cert-tls server
tls-version-min 1.2
<tls-auth>
</tls-auth>

**Comment by orazioedoardo** [comment]
@scargill Do you have a `<tls-auth>` section inside the .ovpn file you use to connect (ukpi4 i think)?

**Comment by scargill** [comment]
Hi

Before the CERTinfo, this is what the client file has..

client
dev tun
proto udp
remote 90.255.233.42 1195
resolv-retry infinite
nobind
persist-key
persist-tun
key-direction 1
remote-cert-tls server
tls-version-min 1.2
verify-x509-name ukpi4_2c4c30a8-071a-4ab3-a316-95dfb87fac4b name
cipher AES-256-CBC
auth SHA256
auth-nocache
verb 3
<ca>

**Comment by orazioedoardo** [comment]
I know but it’s not what I asked for, I asked whether your client file has a <tls-auth> block at the end, like this one: 
![](https://www.dnsflex.com/wp-content/uploads/2018/05/tls-auth-4.png)
Do not post the content, just confirm.

**Comment by scargill** [comment]
Hi

Right - confirming - it DOES... pretty much like that but the "key direction 1" i s much higher up the file...

**Comment by TinCanTech** [comment]
FTR: 
`Authenticate/Decrypt packet error: bad packet ID (may be a replay)`
This is a non-fatal error and for the most part can be ignored.
(Further information about `replays` is available in the OpenVPN manual)

`TLS Error: incoming packet authentication failed`
This is a fatal error.
However, when the packet fails authentication due to incorrect `--tls-auth` the message would normally include `HMAC`, which is the purpose of `--tls-auth`.

This is definately a problem originating from OpenVPN itself but here are some things we (OpenVPN) tend to recommend to people:
Client config generally should **not** include:
```
persist-tun
persist-key
```
These are option intended for use by the server (PiVPN should take this into account in future).
```
keepalive 1800 3600
```
This completely defeats the purpose of `--keepalive` because almost all router/firewalls UPD port will timeout within 30 seconds. `--keepalive 15 120` maybe more suitable. Also, be aware `--ping`s are not sent while the VPN passes data (PiVPN should take this into account in future).

However, these simple changes may not be the cause of your issue and in such cases we (OpenVPN) recommend that the user try using `--proto tcp` (Server and client, obviously).

**Comment by scargill** [comment]
i

This install I have them in 2 properties, one is working, the other worked for months until last week. I used PIVPN and understand VERY little about the inner workings...

I've just tsken a copy of the client file, renamed and removed persist-run and persist-key from the file before importing it into my phone. Made no difference.  I don;t know how to make changes at the server (Raspberry Pi) end but I CAN use NANO. HELP??

Pete

**Comment by orazioedoardo** [comment]
@scargill I know that correlation does not imply causality but since everything worked before Vodafone made the change I’d suggest that that’s the cause, expecially since you had two identical setups? Does the phone you use to (attempt to) connect to the faulty pivpn work with the other pivpn?

**Comment by TinCanTech** [comment]
@scargill - Try rebooting your server before you try the problem client.

**Comment by scargill** [comment]
> @scargill - Try rebooting your server before you try the problem client.
Hi Orazioedoardo and TinCanTech...   I've not only rebooted he server, I've tried ininstalling and reinstalling PIVPN. Yes, the client(s) connect just fine to my other site - and TRY to connect to this site (the server knows they tried) but there is a TLS failure.  

It gets worse, after the Vodafone tech guy supposedly "adjusted the noise floor" on my router remotely, he promised an engineer would be there within 72 hours. No-one turned up. I then contacted Voda and was promised at night (by a female called "Ankita" - all logged) that I could talk to their dedicated VPN team during the day so I contacted them the next day and the tech support guy insisted that Vodafone do not have a VPN support team - and won't take responsibility for VPN issues. That started a chain of complaints currently in progress.

So, I've tried my phone, my wife's phone, my colleague's computer (several miles North). In each case the Raspberry Pi running PiVPN sees them attempting to come in - but there's a TLS failure and won't let them in.

**Comment by orazioedoardo** [comment]
@TinCanTech 
Actually keepalive was 10 120 in the past but someone sent a [pull request](https://github.com/pivpn/pivpn/pull/535/files) to change that. Makes sense to me: 1800 seconds between ping is way bigger that the typical NAT timeout so the connection will expire before the client and the server have a chance to ping each other. However, since we are tunnelling everything, empirically (especially for a mobile phone), it's unlikely that no packets will be exchanged for 1800 seconds (DNS common).

Regarding persist-key and persist-tun, it's not clear from the manual that they are meant for the server side, in fact it's suggested in the client config too [here](https://github.com/OpenVPN/openvpn/blob/master/sample/sample-config-files/client.conf

@scargill 
Try the suggested changes, edit the server configuration with `sudo nano /etc/openvpn/server.conf` and change `keepalive 1800 3600` to `keepalive 10 120`, then restart the server with `sudo systemctl restart openvpn`.

If it still doesn't work, edit the server configuration again and replace `proto udp` with `proto tcp`, then restart the server. Make the same change in the client config as well.

**Comment by scargill** [comment]
Orazio - do you have ANY idea how happy you have made me? The keepalive changes made no difference, but that and the move to TCP FIXED the problem. I've just spent 2 days fighting with the idiots at Vodaphone who had no idea. On Tuesday an Indian woman told me to get onto the Vodafone "dedicated vpn team during the day, so YESTERDAY I rang them and the tech support guy insisted they don't HAVE a VPN team.  As this has worked for months until their guy remoted into my router at the weekend, was that a coincidence or is there something I can do at the router end (as Vodafone clearly don;t know now to) to restore UDP. I have opened the port for both TCP and UDP access. THANK YOU and others who have provided feedback.

**Comment by TinCanTech** [comment]
@orazioedoardo 
 - `--keepalive`
 The problem with the current `--keepalive` is that the VPN will not detect any issues (timeout etc) for at least 1 hour.  Maybe this is something which does not often effect your users but it is not something I would do.  PiVPN's choice though ..
 - `--persist-*`
 The `--persist-*` settings are only useful when the process drops privileges, eg. `--user nobody`, `--group nobody`, which is only commonly done on the server. PiVPN's choice though .. However, we have seen that using these settings in the client can sometimes disturb reconnects, especially true when certain keys go out of sync, unfortunately, the cause is not really clear. (The sample files are meant only as a guide)

**Comment by TinCanTech** [comment]
@scargill If TCP works but UDP does not make very sure that the client configs have the right keys etc. Also, make sure your firewall is setup correctly. Otherwise, sorry I cannot really help any more than that. Maybe it is Vodaphone have done something wrong .. curious ..

**Comment by orazioedoardo** [comment]
@TinCanTech Thanks for the insights! I will submit a pull request with those changes providing your rationale.

**Comment by TinCanTech** [comment]
FYI: I have been active in the openvpn community for around 8 years and have been actively participating in openvpn devel for much of that time.

**Comment by TinCanTech** [comment]
> > @scargill - Try rebooting your server before you try the problem client.

> Hi Orazioedoardo and TinCanTech...   I've not only rebooted he server, **I've tried ininstalling and reinstalling PIVPN**. 

I just want to ensure here that you have updated the client to the newly re-installed server PKI, I presume that all certificates and keys were recreated ?

**Comment by 4s3ti** [comment]
Guess this can be closed now. 
reopen if i am wrong.

**Comment by scargill** [comment]
All working - thanks
