### ISSUE TITLE
Android device connect to OpenVPN, can resolve dns and route, but Internet not working

### ISSUE THREAD

**Issue by stadros83** [pivpn/pivpn#865]
Hello there and first thanks for this product !

I'm having a strange behavior.

I have a small computer with LUBUNTU.
On this small computer I've installed PIHOLE and PIVPN.
PiHole is working great.

PiVPN is also working. I can connect from outside with an Android device and a Windows OS.
But on both devices I have the same issue : 

I can resolve DNS (for example www.google.fr), I can ping, I can trace route ... BUT I just can't go on Internet (email or web browser for example). I just can't understand what's happening here.

Any idea ? The UFW is disabled.

***** Server conf *****

dev tun
proto udp
port 1194
ca /etc/openvpn/easy-rsa/pki/ca.crt
cert /etc/openvpn/easy-rsa/pki/issued/ASROCK_96a0d03d-ab8e-4a94-9fea-6b8b17df363b.crt
key /etc/openvpn/easy-rsa/pki/private/ASROCK_96a0d03d-ab8e-4a94-9fea-6b8b17df363b.key
dh none
topology subnet
server 10.8.0.0 255.255.255.0
push "dhcp-option DNS 10.8.0.1"
push "block-outside-dns"
push "redirect-gateway def1"
client-to-client
keepalive 1800 3600
remote-cert-tls client
tls-version-min 1.2
tls-crypt /etc/openvpn/easy-rsa/pki/ta.key
cipher AES-256-CBC
auth SHA256
user nobody
group nogroup
persist-key
persist-tun
crl-verify /etc/openvpn/crl.pem
status /var/log/openvpn-status.log 20
status-version 3
syslog
verb 3

******* user conf *******

client
dev tun
proto udp
remote **** 1194
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
tls-version-min 1.2
verify-x509-name ASROCK_96a0d03d-ab8e-4a94-9fea-6b8b17df363b name
cipher AES-256-CBC
auth SHA256
auth-nocache
verb 3

**Comment by 4s3ti** [comment]
Please properly fill the Issue template .. that's why it is there, not to be ignored, without those details no one cant help you to properly troubleshoot the issue. 

that sounds pretty much like browser issue .. what browser are you using?  Have you tried with different browsers?

**Comment by orazioedoardo** [comment]
Try to change the MTU https://github.com/pivpn/pivpn/issues/54

**Comment by stadros83** [comment]
Hello

I've reinstalled everything and now it's working.
I've must had make a mistake the first time.

Thanks for your time !
