### ISSUE TITLE
Debug defaults are not working as expected.

### ISSUE THREAD

**Issue by fossum** [pivpn/pivpn#870]
## In raising this issue, I confirm the following: 

- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

### Issue

After the install script I was having some troubles with routes. I ran the debug option (great tool that should be talked about more) and chose the default for all the found issues (just hit enter). Took me a while to figure out that this doesn't select the default, I have to actually type 'y' then 'Enter'. Output below should show this pretty well.

### Have you searched for similar issues and solutions?

yes

#### which issues?

I searched for `is:issue is:open debug` and `is:issue is:open default`. None of the titles seem to have had what I'm referring to.

### Output from my console

As you'll see, even though the yes option is capitalized, just hitting enter does not answer yes.

```
pi@ovpn:~ $ sudo pivpn -d
::: Generating Debug Output

...

=============================================
::::		Self check		 ::::
:: [OK] IP forwarding is enabled
:: [ERR] Iptables MASQUERADE rule is not set, attempt fix now? [Y/n] 
:: [ERR] Iptables INPUT rule is not set, attempt fix now? [Y/n] 
:: [ERR] Iptables FORWARD rule is not set, attempt fix now? [Y/n] 
:: [OK] OpenVPN is running
:: [OK] OpenVPN is enabled (it will automatically start on reboot)
:: [OK] OpenVPN is listening on port 1194/udp
[INFO] Run pivpn -d again to see if we detect issues
=============================================

...

pi@ovpn:~ $ sudo pivpn -d
::: Generating Debug Output

...

=============================================
::::		Self check		 ::::
:: [OK] IP forwarding is enabled
:: [ERR] Iptables MASQUERADE rule is not set, attempt fix now? [Y/n] y
Done
:: [ERR] Iptables INPUT rule is not set, attempt fix now? [Y/n] y
Done
:: [ERR] Iptables FORWARD rule is not set, attempt fix now? [Y/n] y
Done
:: [OK] OpenVPN is running
:: [OK] OpenVPN is enabled (it will automatically start on reboot)
:: [OK] OpenVPN is listening on port 1194/udp
[INFO] Run pivpn -d again to see if we detect issues
=============================================

...

pi@ovpn:~ $ sudo pivpn -d
::: Generating Debug Output

...

=============================================
::::		Self check		 ::::
:: [OK] IP forwarding is enabled
:: [OK] Iptables MASQUERADE rule set
:: [OK] Iptables INPUT rule set
:: [OK] Iptables FORWARD rule set
:: [OK] OpenVPN is running
:: [OK] OpenVPN is enabled (it will automatically start on reboot)
:: [OK] OpenVPN is listening on port 1194/udp
=============================================

...

pi@ovpn:~ $ 

```

### Have you taken any steps towards solving your issue?

Explicitly answering the question fixed my situation, but I have not tried to fix the code.

**Comment by orazioedoardo** [comment]
I've fixed this in the test branch: https://github.com/pivpn/pivpn/commit/580e1b128e485cdafd8fefd30548e2dfe8c742da

**Comment by orazioedoardo** [comment]
Merged into master: https://github.com/pivpn/pivpn/pull/914
