### ISSUE TITLE
new -bk command does not save inside the newly created backup directory

### ISSUE THREAD

**Issue by jkehrel** [pivpn/pivpn#871]
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

### Issue
the new command -bk creates a new directory "/home/pi/pivpnbackup/" but the created .tgz file is not saved inside this directory but also in "/home/pi/" 

### Have you searched for similar issues and solutions?
    (yes/no / which issues?)

### Console output of      `curl -L install.pivpn.io | bash`
```
  Output Here
```

### Console output of      `pivpn add` or `pivpn add nopass`
```
  Output Here
```

### Console output of      `pivpn debug`
```
  Output Here
```
### Have you taken any steps towards solving your issue?
```
  which?
```

**Comment by 4s3ti** [comment]
will take a look at that as soon as i have a bit of time. thanks for reporting.

**Comment by 4s3ti** [comment]
Hi, 

I was probably veeeery drunk when i did the backup script.. i don't even know how it worked in first place so i could push it... 
For that i have to apologize for the really bad code i've pushed to a stable branch. 

I have now pushed a fix as well as support for the new wire-guard setup to test branch. 
Commit: dd6bb069f05559fb626ee9b1bb398df07ff45206

I won't be pushing it to master as it has a bunch of changes and tbh its not worth the effort at this point. 

Test branch will become the new master quite soon, just a bit more patience please.

**Comment by TinCanTech** [comment]
@4s3ti  _happy new year_ started a little early for you ;-)

**Comment by 4s3ti** [comment]
@TinCanTech that's the only logical reason! xD

**Comment by orazioedoardo** [comment]
Merged into master: https://github.com/pivpn/pivpn/pull/914
