### ISSUE TITLE
Server side CLI to see what clients are connected

### ISSUE THREAD

**Issue by groundglass** [pivpn/pivpn#88]
Good morning. I installed PiVPN without a hitch and am able to connect multiple devices without issues. I was wondering if there is any way for me (on the server) to see who is connected? If not part of PiVPN scripts would there be a way using openvpn (new to openvpn).
Thank you, Kris

**Comment by 0-kaladin** [comment]
You can try cat /etc/openvpn/openvpn-status.log
the "real" way would be to enable the mangement interface and telnet into it on localhost only!
then there is a status command and a bunch others that will tell you details of the openvpn server and connected clients.  You'd be best served googling for the openvpn managment interface, how to enable, etc.

**Comment by 0-kaladin** [comment]
This commit: da5facecbc2a18e5856f6b52367dd92446054097
now adds this functionality.

**Comment by jfavega** [comment]
Look in here: https://github.com/furlongm/openvpn-monitor. Works very well for me.
