### ISSUE TITLE
Pi-VPN with Pi-Hole

### ISSUE THREAD

**Issue by xelemorf** [pivpn/pivpn#885]
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

This is morelike a suggestion for the installer, to bring to the user's attention how to configure Pi-VPN to be used with Pi-Hole. AFAIK Pi-VPN's basic idea about the installer comes from the Pi-Hole installer itself, and probably most of the users who find Pi-VPN can relate to Pi-Hole, therefore I think based on the relationship with the two "products", it would be a good idea to include suggestions (or on the log run maybe the proper autoconf) on how to make Pi-VPN usable with Pi-Hole. In case we cannot move furward with including a note for the users's installing Pi-VPN, can we at least pin this here in GitHub? Since I could not find any platform to make any suggestion I have created this thread.

**Now that OpenVPN and Pi-hole are both running independently it's time to connect them.**

If you use OpenVPN from outside your network, you'll notice that it doesn't forward the DNS requests to Pi-Hole yet (e.g. google-analytics.com isn't blocked) so let's fix that:

    Edit OpenVPN server config:

    sudo nano /etc/openvpn/server.conf

Remove all existing "dhcp-option" entries you can find and add a single new one.

    push "dhcp-option DNS 10.8.0.1"

(10.8.0.X being the default OpenVPN subnet, if you changed this in the installer, use your custom values).

Presss Ctrl + X to exit, then Y to confirm saves then Enter to select the existing file name and to overwrite it.

    Edit Pi-hole config:

    sudo nano /etc/pihole/setupVars.conf

Update: eth0 stands for ethernet connection. If your raspberry is not connected by cable or you want to use wifi, you will have to use wlan0 instead of eth0. You can also see the network names by typing ifconfig into a terminal.

Add "PIHOLE_INTERFACE=tun0" belowe the "eth0".

You should now have entries:

    PIHOLE_INTERFACE=eth0

    PIHOLE_INTERFACE=tun0

Save the file.

    Edit one last file (the file should not yet exist):

    sudo nano /etc/dnsmasq.d/02-ovpn.conf

Add single line "interface=tun0" and save it. This will create the file.

A file "01-pihole.conf" exists in the same directory and we could add this entry there, but we shouldn't. Edits to it may be overriden by any Pi-hole update.

Luckily, Pi-hole also respects config values from all *.conf files in the same directory and won't touch other files when updating, so this config should remain intact on future updates!

One final reboot: "sudo reboot" and we're finished!

Source: https://marcstan.net/blog/2017/06/25/PiVPN-and-Pi-hole/

### Have you searched for similar issues and solutions?
    (**yes**, my Pi-VPN was not utilizing Pi-Hole, and it took me a fair amount of time to make it work. I thought I would share the solution, and propose to include this in the installer as a helper, or maybe as part of the autoconf)

### Console output of      `curl -L install.pivpn.io | bash`
```
  All good
```

### Console output of      `pivpn add` or `pivpn add nopass`
```
  All good
```

### Console output of      `pivpn debug`
```
  All good
```
### Have you taken any steps towards solving your issue?
```
  which? The described solution above worked perfectly. Finding the right solution took hours.
```

**Comment by 4s3ti** [comment]
if i am not mistaken @orazioedoardo added some code to test branch that detects if Pihole is running and offers to use it as DNS... 

About everything else ... guess people just dont read: https://github.com/pivpn/pivpn/wiki/FAQ#installing-with-pi-hole

**Comment by xelemorf** [comment]
> 
> 
> if i am not mistaken @orazioedoardo added some code to test branch that detects if Pihole is running and offers to use it as DNS...
> 
> About everything else ... guess people just dont read: https://github.com/pivpn/pivpn/wiki/FAQ#installing-with-pi-hole

I wanted a step by step guide for the users who don't want to spend several hours to figure it out, that's the whole point of using Pi-Hole's installer. The FAQ you have linked is not covering all of the steps required, but if you indeed checked you could see that, try setting up by that and you'll see. Maybe extending that article would be suitable enough.

**Comment by orazioedoardo** [comment]
@xelemorf Updated the FAQ.

> if i am not mistaken @orazioedoardo added some code to test branch that detects if Pihole is running and offers to use it as DNS...

Yes, here's the code: https://github.com/pivpn/pivpn/blob/a2a325e58ca97cbbe31ad0de5404a4d701933554/auto_install/install.sh#L978-L988

**Comment by 4s3ti** [comment]
I Personally just think its an over complicated way to do it ... 
I like the simple idea of setting custom DNS on PiVPN setup and give it the router ip address
then having the router using pihole as default DNS. 

but this is one way to do it as well. 

@xelemorf  just to be on the safe side, please edit and change

>Remove all existing "dhcp-option" entries you can find and add a single new one.

to

>Remove all existing "dhcp-ption DNS  <<...some ip...>>" entries you can find and add a single new one.

fix the typo on:
> Add "PIHOLE_INTERFACE=tun0" **belowe** the "eth0".


I have added the link to this issue to: https://github.com/pivpn/pivpn/wiki/FAQ#installing-with-pi-hole

Closing but feel free to edit and add any extra information. 
Thanks for the guide.
