### ISSUE TITLE
Connection Timeout issue

### ISSUE THREAD

**Issue by santanu-chatterjee59** [pivpn/pivpn#886]
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

I am trying to connect but connection timeout from my mobile. I have tried using mobile data as well as wifi. Both raspberry pi 3 A+ and my mobile are in the same network.Please guide.

### Have you searched for similar issues and solutions?
    (yes/no / which issues?)
Yes

### Console output of      `curl -L install.pivpn.io | bash`
```
  Output Here
```

### Console output of      `pivpn add` or `pivpn add nopass`
```
  Output Here
```

### Console output of      `pivpn debug`
```[4mPiVPN debug[0m		 ::::
=============================================
::::		[4mLatest commit[0m		 ::::
commit d243d9ae1212a30a7959cfe2ec3ef04e7eb9935c
Author: cfcolaco <carlos@vidispine.com>
Date:   Fri Nov 29 10:45:32 2019 +0100

    Fixed Typo
    
    Line 1262: s/jkkprintf/printf/
=============================================
::::	    [4mInstallation settings[0m    	 ::::
/etc/pivpn/DET_PLATFORM -> Raspbian
/etc/pivpn/FORWARD_CHAIN_EDITED -> 0
/etc/pivpn/HELP_SHOWN -> 
/etc/pivpn/INPUT_CHAIN_EDITED -> 0
/etc/pivpn/INSTALL_PORT -> 1567
/etc/pivpn/INSTALL_PROTO -> udp
/etc/pivpn/INSTALL_USER -> pi
/etc/pivpn/NO_UFW -> 1
/etc/pivpn/pivpnINTERFACE -> wlan0
/etc/pivpn/TWO_POINT_FOUR -> 
=============================================
::::	[4msetupVars file shown below[0m	 ::::
INSTALL_USER=pi
UNATTUPG=unattended-upgrades
pivpnInterface=wlan0
IPv4dns=192.168.1.1
IPv4addr=192.168.1.16
IPv4gw=192.168.1.1
pivpnProto=udp
PORT=1567
ENCRYPT=256
APPLY_TWO_POINT_FOUR=true
DOWNLOAD_DH_PARAM=false
PUBLICDNS=
OVPNDNS1=8.8.8.8
OVPNDNS2=8.8.4.4
=============================================
::::  [4mServer configuration shown below[0m   ::::
dev tun
proto udp
port 1567
ca /etc/openvpn/easy-rsa/pki/ca.crt
cert /etc/openvpn/easy-rsa/pki/issued/VPN_040afd54-2100-44a4-9fba-4d49fba1106a.crt
key /etc/openvpn/easy-rsa/pki/private/VPN_040afd54-2100-44a4-9fba-4d49fba1106a.key
dh none
topology subnet
server 10.8.0.0 255.255.255.0
# Set your primary domain name server address for clients
push "dhcp-option DOMAIN XXXXXXXXX.hopto.org" 
push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 8.8.4.4"
# Prevent DNS leaks on Windows
push "block-outside-dns"
# Override the Client default gateway by using 0.0.0.0/1 and
# 128.0.0.0/1 rather than 0.0.0.0/0. This has the benefit of
# overriding but not wiping out the original default gateway.
push "redirect-gateway def1"
client-to-client
keepalive 1800 3600
remote-cert-tls client
tls-version-min 1.2
tls-crypt /etc/openvpn/easy-rsa/pki/ta.key
cipher AES-256-CBC
auth SHA256
user nobody
group nogroup
persist-key
persist-tun
crl-verify /etc/openvpn/crl.pem
status /var/log/openvpn-status.log 20
status-version 3
syslog
verb 3
#DuplicateCNs allow access control on a less-granular, per user basis.
#Remove # if you will manage access by user instead of device. 
#duplicate-cn
# Generated for use by PiVPN.io
=============================================
::::  [4mClient template file shown below[0m   ::::
client
dev tun
proto udp
remote REMOTE 1567
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
tls-version-min 1.2
verify-x509-name VPN_040afd54-2100-44a4-9fba-4d49fba1106a name
cipher AES-256-CBC
auth SHA256
auth-nocache
verb 3
[4mSelf check[0m		 ::::
:: [OK] IP forwarding is enabled
:: [OK] Iptables MASQUERADE rule set
:: [OK] OpenVPN is running
:: [OK] OpenVPN is enabled (it will automatically start on reboot)
:: [OK] OpenVPN is listening on port 1567/udp
=============================================
::::      [4mSnippet of the server log[0m      ::::
Dec 19 21:25:21 VPN ovpn-server[333]: OpenVPN 2.4.0 arm-unknown-linux-gnueabihf [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Oct 14 2018
Dec 19 21:25:21 VPN ovpn-server[333]: library versions: OpenSSL 1.0.2t  10 Sep 2019, LZO 2.08
Dec 19 21:25:21 VPN ovpn-server[391]: Outgoing Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Dec 19 21:25:21 VPN ovpn-server[391]: Outgoing Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Dec 19 21:25:21 VPN ovpn-server[391]: Incoming Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Dec 19 21:25:21 VPN ovpn-server[391]: Incoming Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Dec 19 21:25:21 VPN ovpn-server[391]: TUN/TAP device tun0 opened
Dec 19 21:25:21 VPN ovpn-server[391]: TUN/TAP TX queue length set to 100
Dec 19 21:25:21 VPN ovpn-server[391]: do_ifconfig, tt->did_ifconfig_ipv6_setup=0
Dec 19 21:25:21 VPN ovpn-server[391]: /sbin/ip link set dev tun0 up mtu 1500
Dec 19 21:25:21 VPN ovpn-server[391]: /sbin/ip addr add dev tun0 10.8.0.1/24 broadcast 10.8.0.255
Dec 19 21:25:21 VPN ovpn-server[391]: Could not determine IPv4/IPv6 protocol. Using AF_INET
Dec 19 21:25:21 VPN ovpn-server[391]: Socket Buffers: R=[163840->163840] S=[163840->163840]
Dec 19 21:25:22 VPN ovpn-server[391]: UDPv4 link local (bound): [AF_INET][undef]:1567
Dec 19 21:25:22 VPN ovpn-server[391]: UDPv4 link remote: [AF_UNSPEC]
Dec 19 21:25:22 VPN ovpn-server[391]: GID set to nogroup
Dec 19 21:25:22 VPN ovpn-server[391]: UID set to nobody
Dec 19 21:25:22 VPN ovpn-server[391]: MULTI: multi_init called, r=256 v=256
Dec 19 21:25:22 VPN ovpn-server[391]: IFCONFIG POOL: base=10.8.0.2 size=252, ipv6=0
Dec 19 21:25:22 VPN ovpn-server[391]: Initialization Sequence Completed
=============================================
::::		[4mDebug complete[0m		 ::::

  Output Here
```
### Have you taken any steps towards solving your issue?
```
  I have looked through the iptable comand that I found in one of the strings for issue here but output appears to be ok as per my understanding. I am using tp link router.
```

**Comment by orazioedoardo** [comment]
https://github.com/pivpn/pivpn/issues/868#issuecomment-559383482

**Comment by santanu-chatterjee59** [comment]
How? can you share with me steps or weblink which contains these steps. I am new to this.

**Comment by orazioedoardo** [comment]
> How? can you share with me steps or weblink which contains these steps.

The steps were in the comment I linked above:

Let's test port forwarding:

- Install tcpdump with `sudo apt install tcpdump`
- Sniff the network interface with `sudo tcpdump -i wlan0 port 1567`
- Try to connect from your smartphone

You should see some tcpdump output. Specifically the private IP of your Raspberry Pi and the public IP of the device you are trying to connect from. Mask the client IP if you want and post the output (assuming you get any). CTRL-C to stop the packet capture.

**Comment by santanu-chatterjee59** [comment]
Hi Thank you for the help. I have been able to successfully establish connection from my android mobile and Kodi(OSMC) to my open VPN server. However, I still see connection timeout error from my windows 7 open vpn client and I am still at a total loss to configure my linux mint to my openvpn. I would also like to share with all the readers of this thread that I got 2 addons for kodi+open vpn integration, only the github addon called service.vpn.manager-master.zip worked flawlessly. In my Linux Mint 18 I do see OpenVPN profile option but it is separately asking for certificates, keys.Although, I tried copy pasting these details from my .ovpn file to text files with legitimate file endings like .crt,.key. I am stuck in the .key file which is not recognized as a valid file so not visible also when I am going through that file import dialog box in network manager. Your help is required in this matter.

**Comment by 4s3ti** [comment]
@santanu-chatterjee59 For Network Manager, i don't really know how it looks like on mint .. but don't chose OpenVPN you should have an option called "Import a saved VPN Connection" and on that one you load the ovpn file .. at least that is how i usually have it with NetworkManger

**Comment by santanu-chatterjee59** [comment]
I did what you said. network manager throws the following error: "Error: the plugin does not support import capability."

**Comment by santanu-chatterjee59** [comment]
after the aforesaid trial and error I encounter connection timeout error.

**Comment by 4s3ti** [comment]
@santanu-chatterjee59 
Sorry for the delayed response. 
I will be closing this issue as am not sure if you are still having issues. 
If so .. please try reinstalling now ... maybe consider using wireguard? dunno if it fits your needs. 
and if you still have any issues please reopen this one or open a new issue with details request in the template. 

Once again Sorry for leaving you without an answer for such long time.
