### ISSUE TITLE
pivpn Install uses insecure connections. 

### ISSUE THREAD

**Issue by 4s3ti** [pivpn/pivpn#887]
There are several calls to http, 
Debian repositories are also being installed with http instead of https.

**Comment by 4s3ti** [comment]
Pushed into test branch a fix for this as well as other stuff as moving pivpn.io to pivpn.dev

https://github.com/pivpn/pivpn/commit/33b2b2468d823ea1ab192eefa0ef2599efcf9b31

**Comment by orazioedoardo** [comment]
> @orazioedoardo I have changed the deb repos to https, I am almost sure it causes no harm, but i haven't really tested it ...
 
It well established that most repositories are HTTP but it doesn’t matter since packages and sources files are GPG checked before installing, https://deb.debian.org/debian redirects to http.

**Comment by 4s3ti** [comment]
@orazioedoardo yup I know, but doesn't harm to have it https if it doesn't break anything! =) 
If it does then we fall back to http again.
