### ISSUE TITLE
pivpn, iptables and rc.local

### ISSUE THREAD

**Issue by ghuname** [pivpn/pivpn#888]
Hi,

I need a simple clarification how pivpn works.
In my case I have some iptables rules set in my /etc/rc.local file with which I am satisfied with.
Now I have installed pivpn, rebuted the rapberry pi 2B, and upon reboot, I executed sudo iptables -L to check rules.
I was quite supprised that all chains are now with ACCEPT policies, and with no my rules at all (LOGDROP is my chain):

```
root@rpi2:/etc# iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

Chain LOGDROP (0 references)
target     prot opt source               destination

```

I uninstalled pivpn, and my iptable rules are active again.

I would rather mantain my iptables by myself.

I have following questions:

- What rules should I put in my rc.local file for pivpn?
- How to prevent pivpn to change iptables by any means?
- How unattended security updates work? At one moment pivpn will automatically download and install new version but that will not work until reboot. How I will know that I have to reboot rpi?

Regards.

**Comment by orazioedoardo** [comment]
> What rules should I put in my rc.local file for pivpn?

NAT VPN traffic:

`iptables -t nat -I POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE`

Allow incoming traffic on the VPN port:

`iptables -I INPUT 1 -i eth0 -p udp --dport 1194 -j ACCEPT`

If your FORWARD policy is not ACCEPT:
```
iptables -I FORWARD 1 -d 10.8.0.0/24 -i eth0 -o tun0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
iptables -I FORWARD 2 -s 10.8.0.0/24 -i tun0 -o eth0 -j ACCEPT
```

> How to prevent pivpn to change iptables by any means?

Don't use rc.local. Use iptables-persistent ad pivpn does. Just edit your rules and run `iptables-save > /etc/iptables/rules.v4` to save them.

> How unattended security updates work? At one moment pivpn will automatically download and install new version but that will not work until reboot. How I will know that I have to reboot rpi?

You have to reboot to apply kernel upgrades. Check if the kernel was upgraded by looking at `/var/log/unattended-upgrades/unattended-upgrades.log`

**Comment by ghuname** [comment]
Yes, you are right. Now I am using iptables-persistent and everything works well.
Still, I have a question about port forwarding.

On my ISP router, OpenVPN external port is X which is forwarded to my RPI's OpenVPN server port 1194.
During setup of pivpn, as I am using ddns.net, i have set hostname as my.ddns.net.

When I create a new client certificate in the .ovpn file there is:
remote my.ddns.net 1194
, so I have to edit the file and replace 1194 with X, as this is external port.

Everything is OK, and works properly, I am just asking is there a way to change 1194 -> X, just in .ovpn file upon new client certificate creation.

Best regards.

**Comment by 4s3ti** [comment]
what a chaos @ghuname ... 

Whatever port you setup on `/etc/openvpn.conf` is the port that you have to open and forward on your router,

So openvpn has port 1194  ... Open and forward port 1194 to your raspberry pi. 

 don't over complicate suff that is simple
if you want to change it ... 

Edit /etc/openvpn.conf and change the profile.ovpn files on each client to whatever port you have open facing the internet.
