### ISSUE TITLE
pivpn auto-detecting wrong WAN IP address during install

### ISSUE THREAD

**Issue by newkton1** [pivpn/pivpn#89]
I've installed pivpvn on RPi3 a few times without problems but with this last install, it is auto-detecting a completely incorrect WAN IP address. I've tried changing it manually to what I know is the correct WAN IP but that does not seem to work.
All ideas welcome.

**Comment by 0-kaladin** [comment]
from the pi if you 'curl icanhazip.com' does it too give the wrong wan IP?

**Comment by 0-kaladin** [comment]
@newkton1 if there is no further feedback i'll close this soon.
