### ISSUE TITLE
Client net cant access server net

### ISSUE THREAD

**Issue by skinny602** [pivpn/pivpn#892]
I have a pivpn and a ubuntu client.

The Pivpn net is 172.x.x.x and the ubuntu client is on 192.x.x.x. The tunnel is on 10.8.0.0.

From the server lan 172.x I can access all clients on 192.x.x.x.

From the Client machine only I can access all of the server lan 172.x.x.x.

From the client net I can ping every device on the server lan 192 => 172. Ping only.
From the server lan 172 => 192 I can access all devices and services.

From the client Net I can't access the server side services.

The only way I can access the servers on the 172 from the 192 is if I change the default gateway to the ubuntu client. With the default gateway set to the router I can ping but nothing else. Traceroute works correctly and the hops are correct.

Please help me access the server side without changing the default gateway.

**Comment by orazioedoardo** [comment]
It's a generic VPN routing problem, not related with PiVPN, which works as expected, since

> From the Client machine only I can access all of the server lan 172.x.x.x.

By the way, to access 172's net from 192's net you need to add on every 172's net client (or their default gateway) a route to 172's net using the ubuntu client IP. You need to enable IP forwarding too and possibly some firewall rules.

**Comment by skinny602** [comment]
Routing is correct for the network.
Route 172/24 => 192 Ubuntu Client IP.
Traceroute from 192 net with default route set to router.

192.x ubuntu Client IP
10.8.x.x tunnel IP
172.x destination address trying to connect to.
Client ip forwarding set.
net.ipv4.ip_forward = 1
IPTABLES rules.
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
-A INPUT -i eth0 -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -i ens33 -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -i tun0 -m state --state RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -j ACCEPT
