### ISSUE TITLE
[Support] Long connection time with FritzBox-Domain

### ISSUE THREAD

**Issue by BaumGuard** [pivpn/pivpn#893]
Hello,

thank you for that great installation script!
But I‘ve got an issue with it:
I set up an openvpn-server with TCP because I had a few problems with UDP in the past. When I use the public ip-address, I don‘t have connection problems. But when I use the public domain of my FritzBox, the following message is shown in the terminal while connecting to the vpn:
```

SIGUSR1[connection failed(soft),init_instance] received, process restarting 
Restart pause, 5 second(s)
```

Although I can connect to the vpn and use it, it takes some time to establish the connection.

I searched the internet but the result weren‘t very helpful.

So, how can I solve that problem?

Thank you for your answer in advance.

**Comment by orazioedoardo** [comment]
Probably your client is very slow at resolving the FritzBox domain.

**Comment by BaumGuard** [comment]
This problem doesn't only occur on one client. It's everywhere the same whether I'm connecting with my smartphone or with my notebook.

**Comment by BaumGuard** [comment]
I now had a look at the log-file of my openvpn-server and there I found the same issue:
```
Connection reset, restarting [0]
raspberrypi ovpn-server[415]: client/ip-address:57956 SIGUSR1[soft,connection-reset] received, client-instance restarting
```

The strange thing is that the port displayed in the log-file is 57956. But I configured the port 2004 on the server.
Do you have an explanation for that?

**Comment by orazioedoardo** [comment]
> This problem doesn't only occur on one client. It's everywhere the same whether I'm connecting with my smartphone or with my notebook.

I don't know, the connection process is the same whether you connect from IP or domain name. Try using another dynamic dns. In the meanwhile, connect via IP and post the output of `pivpn debug` so we check if the connection works.

> The strange thing is that the port displayed in the log-file is 57956. But I configured the port 2004 on the server.

That's the client port, which is picked at random. It's completely [normal](https://en.wikipedia.org/wiki/Ephemeral_port).

**Comment by BaumGuard** [comment]
Okay, now it connects normally. I only replaced the domain in the vpn-file with my public ip-address. Indeed the problem seems to be caused by the DNS. I use the built-in internet-access-domain from the FritzBox, which comes along with the MyFritz-account.
My FritzBox doesn't have a certificate. Could it help if I create a certificate for it?

**Comment by orazioedoardo** [comment]
> My FritzBox doesn't have a certificate. Could it help if I create a certificate for it?

No, this is not related to dynamic DNS. Dynamic DNS simply translate whatever.example.com to some IP.

**Comment by 4s3ti** [comment]
seems its okay now. 
Closing, reopen i am wrong and this still needs to be looked into .
