### ISSUE TITLE
[Support] How to run OpenVPN on multiple ports TCP/UDP with Buster release?

### ISSUE THREAD

**Issue by djkraven** [pivpn/pivpn#895]
I have followed the process out line in 
how to add multiple ports (say 1194,943 and 443 in UDP and TCP for load balancing etc.) #178
but is it not loading all the /etc/openvpn/*.conf files and openvpn is not listening on the additional ports I have configured with each .conf file. The /var/log//openvpn.log shows only the server.conf file loading.

Is there an updated process for the Buster kernel 4.19 release of Raspbian?

**Comment by 4s3ti** [comment]
In a nutshell ... 
`cp /etc/openvpn/server.conf /etc/openvpn/<WhateverNameYouWant>.conf`
Change the ports and protocol as you see fit. 
`systemctl start openvpn@<WhateverYouCaledUYourConfFile>`

and you should be good to go. 
Closing.

**Comment by vincentkenny01** [comment]
hello reopening this as there seems to be an issue. 

I wrote https://github.com/pivpn/pivpn/issues/178 this guide but it does not seem to working anymore.

So basically I have two clients who want to use same port 443 one as UDP and one as TCP. if I make a copy of server and change dhcp and server options and give new ip range, make forwarding in iproutes, ifconfig shows two servers running at different ip range on same port BUT when you connect udp client, it does not seem to get any internet, tcp seems fine so something is broken.....I will do some more tests tomorrow but so far I haven't been able to figure what is not working..there seems to be an issue with dns resolution i think!

**Comment by berndte23** [comment]
@vincentkenny01  

Did you solve the problem?

**Comment by vincentkenny01** [comment]
Yes,
There should be a guide under information tag that explains how I did it and it works fine.  
-------- Original message --------From: berndte23 <notifications@github.com> Date: 28/08/2020  07:54  (GMT+00:00) To: pivpn/pivpn <pivpn@noreply.github.com> Cc: vincentkenny01 <inkx27@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [pivpn/pivpn] [Support] How to run OpenVPN on multiple ports TCP/UDP with Buster release? (#895) 
@vincentkenny01
Did you solve the problem?
