### ISSUE TITLE
[FR] Network configuration choice (yes/no for fixed IP)

### ISSUE THREAD

**Issue by xJMV** [pivpn/pivpn#897]
**Is your feature request related to a problem? Please describe.**
Yes, once PiVPN install process complete, if the static IP params are not removed, the Pi will not reconnect to mesh network. So we must remove the dhcpd added lines

**Describe the solution you'd like**
Offer a choice to set a static IP or not. If user select Yes, the actual way to configure is continuing. if NO is selected, it continues like a non-raspbian device do.

**Describe alternatives you've considered**
None

**Additional context**
We use RPI over AREDN mesh network to provide Internet access to certain in mesh devices. Configuring static IP in PiVPN just keeps the device out of network on reboot. We use DHCP reservation instead of fixed IP because in case of IP collision, IP of the nodes can be changed to mitigate problems.

**Comment by 4s3ti** [comment]
This is actually something i've been thinking for a while as i use DHCP reservation myself as well. 
might look at this during this week.

**Comment by 4s3ti** [comment]
Done here: b9f237fe92bdf08847d24f26cc2aedd6e0802b91

**Comment by xJMV** [comment]
Yeah! Thank you! :)

**Comment by orazioedoardo** [comment]
Merged into master: https://github.com/pivpn/pivpn/pull/914
