### ISSUE TITLE
[BUG] OpenVPN service continously failing to start

### ISSUE THREAD

**Issue by Zaman8** [pivpn/pivpn#898]
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

**Describe the bug**
I can't connect to my vpn server, running on a Raspberry PI Model 3 B+, after a clean setup. The windows client says "server poll timeout. try next remote entry" until it gives up. After trying to diagnose the problem everything looks correct except for continoues entries in the system log every 5 secs. These logs say "Stopped OpenVPN service for server", "Starting OpenVPN service for server", Failed to start OpenVPN service for server". 

**To Reproduce**
1. Install PiVPN
2. enter grep VPN syslog
3. See error

**Screenshots**
Here is the System Log
![image](https://user-images.githubusercontent.com/21971457/71599306-56947200-2b18-11ea-8116-39f5596ab9d4.png)

I've also included a screenshot of the server.conf. I also have pihole running on the same machine and I've followed the wiki guide to using that DNS with the VPN. 

![image](https://user-images.githubusercontent.com/21971457/71599388-a5daa280-2b18-11ea-82fa-8921ee9a0ea3.png)

**Desktop (please complete the following information):**
 - VPN Protocol: OpenVPN
 - OS: Windows 10

**Additional context**
I'm using port 5500 for security obfuscation. 
Pihole is currently operating properly for lan, I can't connect to the VPN to test
I've tried to connect to the VPN several times using a my laptop on a mobile hotspot
I've set up the server to use a DDNS which maps to my public IP, looking at the client side logs it finds the right address and port, but I can't see any evidence of an attempted connection on my server. 
Only the configured IPtables are from the PiVPN installation.
I've set up my router to port forward 5500 to the server's 5500 port.

**Comment by orazioedoardo** [comment]
You wrote `push "dhcp-option DNS 10.8.01"` instead of `push "dhcp-option DNS 10.8.0.1" `

**Comment by Zaman8** [comment]
nice catch @orazioedoardo, after changing it and restarting the system it still fails to load. 

After asking several friends, I believe it may be a resources issue since the raspberry pi 3 B+ only has 1GB of memory, a majority of which is used by Pihole. The minimum recommended amount of memory to run OpenVPN is 1GB so it simply doesn't have the resources to start the server and thus fails

**Comment by orazioedoardo** [comment]
That’s impossible, if that was the case the PiVPN project wouldn’t make sense in the first place. I’ve been running Pivpn + Pihole for quite a while on a Raspberry Pi with 512 MB of RAM without any issue. Check out `/var/log/openvpn.log` for any error.

**Comment by Zaman8** [comment]
`::: Generating Debug Output
::::            PiVPN debug              ::::
=============================================
::::            Latest commit            ::::
commit 86f60b95041cb80e4ac9a859cbacc243da5b9a59
Author: 4s3ti <cfcolaco@colacoweb.net>
Date:   Sun Dec 22 18:52:58 2019 +0100

    Deleted Old Issue Template
=============================================
::::        Installation settings        ::::
/etc/pivpn/DET_PLATFORM -> Raspbian
/etc/pivpn/FORWARD_CHAIN_EDITED -> 1
/etc/pivpn/HELP_SHOWN ->
/etc/pivpn/INPUT_CHAIN_EDITED -> 1
/etc/pivpn/INSTALL_PORT -> 5500
/etc/pivpn/INSTALL_PROTO -> udp
/etc/pivpn/INSTALL_USER -> pi
/etc/pivpn/NO_UFW -> 1
/etc/pivpn/pivpnINTERFACE -> eth0
/etc/pivpn/TWO_POINT_FOUR ->
=============================================
::::    setupVars file shown below       ::::
INSTALL_USER=pi
UNATTUPG=unattended-upgrades
pivpnInterface=eth0
IPv4dns=
IPv4addr=192.168.86.46
IPv4gw=192.168.86.1
pivpnProto=udp
PORT=5500
ENCRYPT=521
APPLY_TWO_POINT_FOUR=true
DOWNLOAD_DH_PARAM=false
PUBLICDNS=REMOTE
OVPNDNS1=192.168.86.46
OVPNDNS2=
=============================================
::::  Server configuration shown below   ::::
dev tun
proto udp
port 5500
ca /etc/openvpn/easy-rsa/pki/ca.crt
cert /etc/openvpn/easy-rsa/pki/issued/raspberrypi_14a18b42-5fa2-4f5d-9b2a-5dc77d                                                     8ca7f5.crt
key /etc/openvpn/easy-rsa/pki/private/raspberrypi_14a18b42-5fa2-4f5d-9b2a-5dc77d                                                     8ca7f5.key
dh none
topology subnet
server 10.8.0.0 255.255.255.0
# Set your primary domain name server address for clients
push "dhcp-option DNS 10.8.0.1"
push "block-outside-dns"
# Override the Client default gateway by using 0.0.0.0/1 and
# 128.0.0.0/1 rather than 0.0.0.0/0. This has the benefit of
# overriding but not wiping out the original default gateway.
push "redirect-gateway def1"
client-to-client
keepalive 1800 3600
remote-cert-tls client
tls-version-min 1.2
tls-crypt /etc/openvpn/easy-rsa/pki/ta.key
cipher AES-256-CBC
auth SHA256
user nobody
group nogroup
persist-key
persist-tun
crl-verify /etc/openvpn/crl.pem
status /var/log/openvpn-status.log 20
status-version 3
syslog
verb 3
#DuplicateCNs allow access control on a less-granular, per user basis.
#Remove # if you will manage access by user instead of device.
#duplicate-cn
# Generated for use by PiVPN.io
=============================================
::::  Client template file shown below   ::::
client
dev tun
proto udp
remote REMOTE 5500
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
tls-version-min 1.2
verify-x509-name raspberrypi_14a18b42-5fa2-4f5d-9b2a-5dc77d8ca7f5 name
cipher AES-256-CBC
auth SHA256
auth-nocache
verb 3
=============================================
::::    Recursive list of files in       ::::
::: /etc/openvpn/easy-rsa/pki shows below :::
/etc/openvpn/easy-rsa/pki/:
ca.crt
crl.pem
Default.txt
ecparams
extensions.temp
index.txt
index.txt.attr
index.txt.attr.old
index.txt.old
issued
openssl-easyrsa.cnf
private
renewed
revoked
safessl-easyrsa.cnf
serial
serial.old
ta.key
Laptop.ovpn

/etc/openvpn/easy-rsa/pki/ecparams:
secp521r1.pem

/etc/openvpn/easy-rsa/pki/issued:
raspberrypi_14a18b42-5fa2-4f5d-9b2a-5dc77d8ca7f5.crt
Laptop.crt

/etc/openvpn/easy-rsa/pki/private:
ca.key
raspberrypi_14a18b42-5fa2-4f5d-9b2a-5dc77d8ca7f5.key
Laptop.key

/etc/openvpn/easy-rsa/pki/renewed:
private_by_serial
reqs_by_serial

/etc/openvpn/easy-rsa/pki/renewed/private_by_serial:

/etc/openvpn/easy-rsa/pki/renewed/reqs_by_serial:

/etc/openvpn/easy-rsa/pki/revoked:
private_by_serial
reqs_by_serial

/etc/openvpn/easy-rsa/pki/revoked/private_by_serial:

/etc/openvpn/easy-rsa/pki/revoked/reqs_by_serial:
=============================================
::::            Self check               ::::
:: [OK] IP forwarding is enabled
:: [OK] Iptables MASQUERADE rule set
:: [OK] Iptables INPUT rule set
:: [OK] Iptables FORWARD rule set
:: [OK] OpenVPN is running
:: [OK] OpenVPN is enabled (it will automatically start on reboot)
:: [OK] OpenVPN is listening on port 5500/udp
=============================================
::::      Snippet of the server log      ::::
Jan  1 10:32:36 raspberrypi ovpn-server[1267]: SIGTERM[hard,] received, process                                                      exiting
Jan  1 10:32:37 raspberrypi ovpn-server[5984]: OpenVPN 2.4.7 arm-unknown-linux-g                                                     nueabihf [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built                                                      on Feb 20 2019
Jan  1 10:32:37 raspberrypi ovpn-server[5984]: library versions: OpenSSL 1.1.1d                                                       10 Sep 2019, LZO 2.10
Jan  1 10:32:37 raspberrypi ovpn-server[5984]: Outgoing Control Channel Encrypti                                                     on: Cipher 'AES-256-CTR' initialized with 256 bit key
Jan  1 10:32:37 raspberrypi ovpn-server[5984]: Outgoing Control Channel Encrypti                                                     on: Using 256 bit message hash 'SHA256' for HMAC authentication
Jan  1 10:32:37 raspberrypi ovpn-server[5984]: Incoming Control Channel Encrypti                                                     on: Cipher 'AES-256-CTR' initialized with 256 bit key
Jan  1 10:32:37 raspberrypi ovpn-server[5984]: Incoming Control Channel Encrypti                                                     on: Using 256 bit message hash 'SHA256' for HMAC authentication
Jan  1 10:32:37 raspberrypi ovpn-server[5984]: TUN/TAP device tun0 opened
Jan  1 10:32:37 raspberrypi ovpn-server[5984]: TUN/TAP TX queue length set to 10                                                     0
Jan  1 10:32:37 raspberrypi ovpn-server[5984]: /sbin/ip link set dev tun0 up mtu                                                      1500
Jan  1 10:32:37 raspberrypi ovpn-server[5984]: /sbin/ip addr add dev tun0 10.8.0                                                     .1/24 broadcast 10.8.0.255
Jan  1 10:32:37 raspberrypi ovpn-server[5984]: Could not determine IPv4/IPv6 pro                                                     tocol. Using AF_INET
Jan  1 10:32:37 raspberrypi ovpn-server[5984]: Socket Buffers: R=[163840->163840                                                     ] S=[163840->163840]
Jan  1 10:32:37 raspberrypi ovpn-server[5984]: UDPv4 link local (bound): [AF_INE                                                     T][undef]:5500
Jan  1 10:32:37 raspberrypi ovpn-server[5984]: UDPv4 link remote: [AF_UNSPEC]
Jan  1 10:32:37 raspberrypi ovpn-server[5984]: GID set to nogroup
Jan  1 10:32:37 raspberrypi ovpn-server[5984]: UID set to nobody
Jan  1 10:32:37 raspberrypi ovpn-server[5984]: MULTI: multi_init called, r=256 v                                                     =256
Jan  1 10:32:37 raspberrypi ovpn-server[5984]: IFCONFIG POOL: base=10.8.0.2 size                                                     =252, ipv6=0
Jan  1 10:32:37 raspberrypi ovpn-server[5984]: Initialization Sequence Completed
=============================================
::::            Debug complete           ::::
:::
::: Debug output completed above.
::: Copy saved to /tmp/debug.txt
:::
`

Sorry about that I forgot to post that in the original.

**Comment by orazioedoardo** [comment]
Seems to be running:
`Jan  1 10:32:37 raspberrypi ovpn-server[5984]: Initialization Sequence Completed`

**Comment by Zaman8** [comment]
![image](https://user-images.githubusercontent.com/21971457/71676866-49ad9380-2d4f-11ea-9ef8-21c50c227b40.png)
PiVPN doesn't seem to detect any issue, at least not in the server configuration. But after examining the output of the job attempting to start "openvpn-server@server.service" it seems it can't properly access the server.conf files. 
Does anyone know how to fix this>?

**Comment by orazioedoardo** [comment]
Don't run random commands. The systemd unit `openvpn-server@server.service` expects the server.conf inside `/etc/openvpn/server` but it's not there, in fact it is inside `/etc/openvpn`. To start/stop openvpn use `sudo systemctl start openvpn` and `sudo systemctl stop openvpn`. With `sudo chmod 666 /etc/openvpn/server.conf` you make the server configuration world writable, which is not secure, revert to 644.

**Comment by Zaman8** [comment]
Here is the openvpn.log and openvpn status
![image](https://user-images.githubusercontent.com/21971457/71685201-969c6480-2d65-11ea-8721-3b08cfdc52f5.png)
 
![image](https://user-images.githubusercontent.com/21971457/71685227-a74cda80-2d65-11ea-8560-18e85aab982c.png)

It seems that the openvpn service is running, but the status of the `openvpn-server@server.service` is still unable to start. I've copied the `server.conf` to `/etc/openvpn/service`, so now it exists in both locations. 

I'm also posting the output of `syslog` because it shows that the socket bind on port 5500 is failing, which is new. 

![image](https://user-images.githubusercontent.com/21971457/71685442-538ec100-2d66-11ea-8e24-678bb483dffb.png)

**Comment by orazioedoardo** [comment]
Image 1 and 2 show that OpenVPN is running perfectly fine, there is nothing you have to do, you are set.

> I'm also posting the output of syslog because it shows that the socket bind on port 5500 is failing, which is new.

It shows that socket bind is failing because another process is running on that udp port, which is indeed openvpn.

> It seems that the openvpn service is running, but the status of the openvpn-server@server.service is still unable to start. I've copied the server.conf to /etc/openvpn/service, so now it exists in both locations.

You are insisting on running openvpn via `openvpn-server@server.service` but I've already told you it's not the case as pivpn is not configured in that way.

**Comment by Zaman8** [comment]
Its then not an issue with PiVPN but my networking to it as it always times out when attempting to connect
