### ISSUE TITLE
[BUG] Typo in test branch

### ISSUE THREAD

**Issue by spectrumcomputing** [pivpn/pivpn#900]
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [X I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

**Describe the bug**
The is a typo in the testing branch installation screens. Should be choice rather than choise.

![Spelling](https://user-images.githubusercontent.com/38283339/71672592-5ee5ea80-2d6e-11ea-8f80-1b94d958b2ef.PNG)

**Comment by orazioedoardo** [comment]
Done, thanks.
