### ISSUE TITLE
[BUG] Unattended install exits unsuccessfully on copying non-existent old configs

### ISSUE THREAD

**Issue by rmpratt1** [pivpn/pivpn#902]
## In raising this issue, I confirm the following: 

- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

**Describe the bug**
When performing an unattended install (--unattended) install.sh exits unsuccessfully and immediately when there are non-existent old configuration files. The error text is:

> cp: cannot stat '/tmp/OLD_UFW': No such file or directory

In this specific example it is due to ufw not being installed and enabled. The lines causing the issue are 1058-1061:

`$SUDO cp /tmp/noUFW /etc/pivpn/NO_UFW`
`$SUDO cp /tmp/OLD_UFW /etc/pivpn/OLD_UFW`
`$SUDO cp /tmp/INPUT_CHAIN_EDITED /etc/pivpn/INPUT_CHAIN_EDITED`
`$SUDO cp /tmp/FORWARD_CHAIN_EDITED /etc/pivpn/FORWARD_CHAIN_EDITED`

**To Reproduce**
1. Start from clean system install (without ufw)
2. Create file /etc/pivpn/setupVars.conf
3. Fill-in /etc/pivpn/setupVars.conf as appropriate:
`INSTALL_USER=pi`
`UNATTUPG=unattended-upgrades`
`pivpnInterface=eth0`
`IPv4dns=`
`IPv4addr=192.168.1.2`
`IPv4gw=192.168.1.1`
`pivpnProto=ufw`
`PORT=1194`
`ENCRYPT=256`
`APPLY_TWO_POINT_FOUR=true`
`DOWNLOAD_DH_PARAM=false`
`PUBLICDNS=[REDACTED]`
`OVPNDNS1=1.1.1.1`
`OVPNDNS2=1.0.0.1`
4. Run unattended installer
`bash install.sh --unattended`
5. See error
> ...
> cp: cannot stat '/tmp/OLD_UFW': No such file or directory
6. Check exit code
`echo $?`

**Expected behavior**
Installation to continue progressing and error not thrown to console

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by orazioedoardo** [comment]
The unattended install has been reworked in the test branch, see if you have the same issue there.

**Comment by rmpratt1** [comment]
@orazioedoardo from a quick look on the test branch I didn't see the same issue. The scope of the change for the test branch seemed bigger so I wasn't sure when that was coming out. I did submit a PR for the fix if the test branch is going to be a while.

**Comment by orazioedoardo** [comment]
I see but i can’t merge as [those /tmp files](https://github.com/pivpn/pivpn/pull/903/commits/926eb9d891ec52375f9a5a8c742c8264f069c7c8) are not in the test branch anymore.

**Comment by rmpratt1** [comment]
Ahh yeah. I probably should have done the PR to master. 

Is there an ETA for test to become stable? Should I make a new PR for master?

**Comment by orazioedoardo** [comment]
> Is there an ETA for test to become stable?

No ETA yet, mainly because is need [more testing](https://github.com/pivpn/pivpn/issues/896#issuecomment-569631946) on older distributions, even though it should work well by now.

> Should I make a new PR for master?

No sorry, the master branch and test branch have already diverged, more commit would make merging from test to master more difficult.

**Comment by 4s3ti** [comment]
Merged into master:

https://github.com/pivpn/pivpn/pull/914
