### ISSUE TITLE
Installed from: curl -L https://install.pivpn.io | bash SAFE?

### ISSUE THREAD

**Issue by dcaccount** [pivpn/pivpn#904]
Hello,

following an "old" website, I have installed pippin from 

> curl -L https://install.pivpn.io | bash

instead of from:

> curl -L https://install.pivpn.dev | bash

Could it be an issue or is it safe?

Please advise.
Thanks,
Dan

**Comment by orazioedoardo** [comment]
It is, as they both download the script from https://raw.githubusercontent.com/pivpn/pivpn/master/auto_install/install.sh

**Comment by dcaccount** [comment]
> It is, as they both download the script from https://raw.githubusercontent.com/pivpn/pivpn/master/auto_install/install.sh

Thanks!
