### ISSUE TITLE
[FR] Test Branch: VPN Protocol Selection

### ISSUE THREAD

**Issue by 4s3ti** [pivpn/pivpn#905]
**Is your feature request related to a problem? Please describe.**
On test branch when choosing VPN Protocol user should do yes for wireguard, or No for OpenVPN. 

**Describe the solution you'd like**
Instead of of a yes/no selection, a radiolist defaulted to wireguard would be better and more intuitive. 

**Describe alternatives you've considered**
Instead of Yes or No Buttons or radio list, having 2 buttons wireguard and OpenVPN can be good as well.. however not really sure how to do it with whiptail as i am not that good with it. 

**Additional context**
n/a

**Comment by orazioedoardo** [comment]
Done: https://github.com/pivpn/pivpn/commit/800fd91353a18fd17d4113e38a4835691fd1962e

**Comment by 4s3ti** [comment]
Awesome! =D

**Comment by 4s3ti** [comment]
Merged into master:

https://github.com/pivpn/pivpn/pull/914
