### ISSUE TITLE
Master vs. test, io vs. dev, overview

### ISSUE THREAD

**Issue by muibusan** [pivpn/pivpn#907]
Hi!

Sorry, but I've lost track of all the changes and the current difference between test and master. 

1. Website pivpn.io vs. pivpn.dev: are both the same, is one of them newer, what's the difference?
2. test branch vs. master branch: is there an up-to-date list showing what bug improvements, new features etc. are available obnly in test branch and which ones made it to the master branch?

Can someone sort it out? Thank you very much!

**Comment by 4s3ti** [comment]
@muibusan 

We are currently going to major changes in the script... bunch of refactor, code improvement and cleanup.. as well as adding support for wireguard VPN Protocol.

To answer your questions, 
this file should be somewhat up to date with the changes: 

https://github.com/pivpn/pivpn/blob/master/LatestUpdate.md

you can check the same file on test branch to kind of check whats going on.  
its not 100% accurate but its close, Its hard to keep up with all that changes, definitely an area for improvement in the future. other than that you can check the git log/history.

Master branch is currently Locked, and we are not accepting any changes based on that code, 
Test branch on active development and testing and as soon as we feel its ready will be merged to master branch. 

How we will do it .. i still don't know as a LOT of the code is changed. 

pivpn.io is deprecated! that domain is owned by 0-kaladin the original developer of the project that stepped away (more to disappeared), therefore we didn't had full control over it and no way to provide https on it. 

Now that I managed to take over the project, 
pivpn.dev is our new domain, owned by me. 
the website is still fully open sourced here: https://github.com/pivpn/pivpn.dev


Hope this clarifies your questions, If so please close the issue. 

i also recommend you to read the documentation, wiki, faq, README.md files, also on test branch and you will find a lot of info there as well. 
you can also search issues the the label fix in test branch to get a picture of what we are working, and what has been pushed as well. 
 

Kind Regards.

**Comment by 4s3ti** [comment]
no more comms i guess the answer was enough. 
Closing.
