### ISSUE TITLE
[Support] PiVPN, Android phone connects, has internet. PC connects, does not have internet.

### ISSUE THREAD

**Issue by DudeBart** [pivpn/pivpn#909]
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

I've set up a PiVPN server on my Pi4. It seems to work, because I can connect to it with my Android Phone, and with my pc. With both I can access everything on my LAN. But here comes the strange part. When connected, my phone still has a working internet. I can access all sites, and ads are nicely blocked with PiHole (installed on the same Pi). 

However, when I connect with my PC with Windows 10, I can't browse the internet. I can see everything on my LAN. I think the problem is with DNS, because I can ping 1.1.1.1, but I can't ping google.com. Also, I see this in the OpenVPN-client:
https://i.imgur.com/WBouLAX.png
Don't know if that got something to do with my problem. I'm new to Linux/Pi. So please be gentle with my feelings! I've been trying for a few hours, but don't know what to do anymore...

### Have you searched for similar issues and solutions?
I've searched but couldn't find similar problems. However, I don't know if I used the right search words.

### Console output of      `curl -L install.pivpn.dev | bash`
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     5  100     5    0     0     92      0 --:--:-- --:--:-- --:--:--    92
100   162  100   162    0     0   1117      0 --:--:-- --:--:-- --:--:--  1117
100 59088  100 59088    0     0   216k      0 --:--:-- --:--:-- --:--:--  216k
:::
::: sudo will be used for the install.
::: Hostname length OK
::: Cancel selected. Exiting

```

### Console output of      `pivpn add` or `pivpn add nopass`
```
No problems with this.
```

### Console output of      `pivpn debug`
```
::: Generating Debug Output
::::		PiVPN debug		 ::::
=============================================
::::		Latest commit		 ::::
commit 2ea469359c357395110a0bfc951d0b6d1c7e9141
Author: 4s3ti <4s3ti@protonmail.com>
Date:   Wed Jan 8 13:13:34 2020 +0100

    Issue #607
    
    Added -p on mkdir /opt/pivpn this fixes issue #607
=============================================
::::	    Installation settings    	 ::::
/etc/pivpn/DET_PLATFORM -> Raspbian
/etc/pivpn/FORWARD_CHAIN_EDITED -> 0
/etc/pivpn/HELP_SHOWN -> 
/etc/pivpn/INPUT_CHAIN_EDITED -> 0
/etc/pivpn/INSTALL_PORT -> 1194
/etc/pivpn/INSTALL_PROTO -> udp
/etc/pivpn/INSTALL_USER -> pi
/etc/pivpn/NO_UFW -> 1
/etc/pivpn/pivpnINTERFACE -> eth0
/etc/pivpn/TWO_POINT_FOUR -> 
=============================================
::::	setupVars file shown below	 ::::
INSTALL_USER=pi
UNATTUPG=unattended-upgrades
pivpnInterface=eth0
IPv4dns=
IPv4addr=10.0.8.14
IPv4gw=10.0.8.1
pivpnProto=udp
PORT=1194
ENCRYPT=256
APPLY_TWO_POINT_FOUR=true
DOWNLOAD_DH_PARAM=false
PUBLICDNS=
OVPNDNS1=127.0.0.1
OVPNDNS2=
=============================================
::::  Server configuration shown below   ::::
dev tun
proto udp
port 1194
ca /etc/openvpn/easy-rsa/pki/ca.crt
cert /etc/openvpn/easy-rsa/pki/issued/raspberrypi_9f2feb5e-55bc-47f2-9c80-ab96d3887809.crt
key /etc/openvpn/easy-rsa/pki/private/raspberrypi_9f2feb5e-55bc-47f2-9c80-ab96d3887809.key
dh none
topology subnet
server 10.8.0.0 255.255.255.0
# Set your primary domain name server address for clients
push "dhcp-option DNS 127.0.0.1"
push "block-outside-dns"
# Override the Client default gateway by using 0.0.0.0/1 and
# 128.0.0.0/1 rather than 0.0.0.0/0. This has the benefit of
# overriding but not wiping out the original default gateway.
push "redirect-gateway def1"
client-to-client
keepalive 1800 3600
remote-cert-tls client
tls-version-min 1.2
tls-crypt /etc/openvpn/easy-rsa/pki/ta.key
cipher AES-256-CBC
auth SHA256
user nobody
group nogroup
persist-key
persist-tun
crl-verify /etc/openvpn/crl.pem
status /var/log/openvpn-status.log 20
status-version 3
syslog
verb 3
#DuplicateCNs allow access control on a less-granular, per user basis.
#Remove # if you will manage access by user instead of device. 
#duplicate-cn
# Generated for use by PiVPN.io
=============================================
::::  Client template file shown below   ::::
client
dev tun
proto udp
remote REMOTE 1194
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
tls-version-min 1.2
verify-x509-name raspberrypi_9f2feb5e-55bc-47f2-9c80-ab96d3887809 name
cipher AES-256-CBC
auth SHA256
auth-nocache
verb 3
=============================================
:::: 	Recursive list of files in	 ::::
::: /etc/openvpn/easy-rsa/pki shows below :::
/etc/openvpn/easy-rsa/pki/:
bart.ovpn
ca.crt
crl.pem
Default.txt
ecparams
extensions.temp
index.txt
index.txt.attr
index.txt.attr.old
index.txt.old
issued
openssl-easyrsa.cnf
private
renewed
revoked
safessl-easyrsa.cnf
serial
serial.old
ta.key

/etc/openvpn/easy-rsa/pki/ecparams:
prime256v1.pem

/etc/openvpn/easy-rsa/pki/issued:
bart.crt
raspberrypi_9f2feb5e-55bc-47f2-9c80-ab96d3887809.crt

/etc/openvpn/easy-rsa/pki/private:
bart.key
ca.key
raspberrypi_9f2feb5e-55bc-47f2-9c80-ab96d3887809.key

/etc/openvpn/easy-rsa/pki/renewed:
private_by_serial
reqs_by_serial

/etc/openvpn/easy-rsa/pki/renewed/private_by_serial:

/etc/openvpn/easy-rsa/pki/renewed/reqs_by_serial:

/etc/openvpn/easy-rsa/pki/revoked:
private_by_serial
reqs_by_serial

/etc/openvpn/easy-rsa/pki/revoked/private_by_serial:
479BCD3B1A39387F7D623E972AD8A1B9.key
D78AB4D78EE6AB13BBCBD4AB17760DA6.key

/etc/openvpn/easy-rsa/pki/revoked/reqs_by_serial:
479BCD3B1A39387F7D623E972AD8A1B9.req
D78AB4D78EE6AB13BBCBD4AB17760DA6.req
=============================================
::::		Self check		 ::::
:: [OK] IP forwarding is enabled
:: [OK] Iptables MASQUERADE rule set
:: [OK] OpenVPN is running
:: [OK] OpenVPN is enabled (it will automatically start on reboot)
:: [OK] OpenVPN is listening on port 1194/udp
=============================================
::::      Snippet of the server log      ::::
Jan 12 18:47:09 raspberrypi ovpn-server[781]: Initialization Sequence Completed
Jan 12 18:49:12 raspberrypi ovpn-server[781]: OpenVPN 2.4.7 arm-unknown-linux-gnueabihf [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 20 2019
Jan 12 18:49:12 raspberrypi ovpn-server[781]: library versions: OpenSSL 1.1.1d  10 Sep 2019, LZO 2.10
Jan 12 18:49:12 raspberrypi ovpn-server[781]: Outgoing Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Jan 12 18:49:12 raspberrypi ovpn-server[781]: Outgoing Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Jan 12 18:49:12 raspberrypi ovpn-server[781]: Incoming Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Jan 12 18:49:12 raspberrypi ovpn-server[781]: Incoming Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Jan 12 18:49:12 raspberrypi ovpn-server[781]: TUN/TAP device tun0 opened
Jan 12 18:49:12 raspberrypi ovpn-server[781]: TUN/TAP TX queue length set to 100
Jan 12 18:49:12 raspberrypi ovpn-server[781]: /sbin/ip link set dev tun0 up mtu 1500
Jan 12 18:49:12 raspberrypi ovpn-server[781]: /sbin/ip addr add dev tun0 10.8.0.1/24 broadcast 10.8.0.255
Jan 12 18:49:12 raspberrypi ovpn-server[781]: Could not determine IPv4/IPv6 protocol. Using AF_INET
Jan 12 18:49:12 raspberrypi ovpn-server[781]: Socket Buffers: R=[163840->163840] S=[163840->163840]
Jan 12 18:49:12 raspberrypi ovpn-server[781]: UDPv4 link local (bound): [AF_INET][undef]:1194
Jan 12 18:49:12 raspberrypi ovpn-server[781]: UDPv4 link remote: [AF_UNSPEC]
Jan 12 18:49:12 raspberrypi ovpn-server[781]: GID set to nogroup
Jan 12 18:49:12 raspberrypi ovpn-server[781]: UID set to nobody
Jan 12 18:49:12 raspberrypi ovpn-server[781]: MULTI: multi_init called, r=256 v=256
Jan 12 18:49:12 raspberrypi ovpn-server[781]: IFCONFIG POOL: base=10.8.0.2 size=252, ipv6=0
Jan 12 18:49:12 raspberrypi ovpn-server[781]: Initialization Sequence Completed
=============================================
::::		Debug complete		 ::::
::: 
::: Debug output completed above.
::: Copy saved to /tmp/debug.txt
::: 

```
### Have you taken any steps towards solving your issue?
```
I've tried changing DNS IP-adressess in Windows. Also tried changing all the settings in the OpenVPN client. Nothing helped.
```

**Comment by DudeBart** [comment]
Well, I got it to work if I choose a public DNS in the setup of PiHole. But then PiHole doesn't work. Also, why does it work with my own DNS on my Android Phone, and not on my pc?

**Comment by 4s3ti** [comment]
@DudeBart seems you are getting something wrong ... pi-hole needs to use a public DNS and at the resolution time it filters according to black/white lists. 

You have to setup OpenVPN to use your pihole as a resolver. 
Are they both on the same Raspberry pi? if so .. check this: https://github.com/pivpn/pivpn/wiki/FAQ#installing-with-pi-hole

if they are not on the same pi .. then just use a custom DNS During the installation with PiVPN and use the Pi-hole IP address. 

Also on Windows you need to run OpenVPN as adminstrator otherwise it won't work properly. 

Why it works on Android i am not sure ... but if I am not mistaken Android usually falls-back to using Mobile Data or whatever it has available if the main connection doesn't work.

**Comment by TinCanTech** [comment]
OpenVPN on Windows 10 should **not** be run as administrator.
Use the OpenVPN-GUI and the OpenVPN Interactive-service and do not login as administrator.  https://community.openvpn.net/openvpn/wiki/OpenVPN-GUI-New

**Comment by 4s3ti** [comment]
> OpenVPN on Windows 10 should **not** be run as administrator.
> Use the OpenVPN-GUI and the OpenVPN Interactive-service and do not login as administrator. https://community.openvpn.net/openvpn/wiki/OpenVPN-GUI-New
> 
> If you are logged in to your computer as an administrator then you take responsibility for what happens.

well ... Thanks for the heads up @TinCanTech ..i do not use windows for quite a while now .. and a few years ago was the only way to get it working properly =/

**Comment by DudeBart** [comment]
@4s3ti the guide in your link solved my problem, thank you so much! I'm eternal grateful :-)

@TinCanTech it's just a game pc with only one user (me), no business usage, no important stuff, and it is in my house and therefore fysically not easily accessible by other people. So the risk is low. But thank you for the warning, I appreciate it!

**Comment by TinCanTech** [comment]
@4s3ti _hehe_ .. sorry about my abrupt interruption ;-) Completely understand your misunderstanding. At least you have some info now.

@DudeBart .. I understand what you mean and openvpn GUI ought to work properly even if somebody is logged in as an admin.  Hopefully, it does.  If you have any issues with that you can report them to https://github.com/OpenVPN/openvpn-gui
