### ISSUE TITLE
OpenVPN / Pi-Hole - modify vpn ip addresses/pool

### ISSUE THREAD

**Issue by henryammons** [pivpn/pivpn#911]
Hello,
I have set up a Pi with Pi-Hole and OpenVPN using pivpn.io. All is working perfectly and the extensive information I've found in forums has been very helpful. I've run into an issue. The default ip scheme in OpenVPN is 10.8.0.0 and I'd like to change it to 10.8.1.0 as this is a second Pi on my network serving the same purpose. I have modified the openVPN.conf file:

> server 10.8.1.0 255.255.255.0
> push "dhcp-option DNS 10.8.1.1"

and my remote testing system connected via vpn receives a 10.8.1.x address and connects fine. It is able to resolve local dns (systems I've added to dnsmasq) but not anything outside of my network (Internet). The log file for pihole shows the following:

Dec 30 09:48:21 dnsmasq[1079]: query[A] www.raspberrypi.org from 10.8.1.2
Dec 30 09:48:21 dnsmasq[1079]: forwarded www.raspberrypi.org to 127.0.0.1
Dec 30 09:48:21 dnsmasq[1079]: reply www.raspberrypi.org is 104.22.0.43
Dec 30 09:48:21 dnsmasq[1079]: reply www.raspberrypi.org is 104.22.1.43

but the remote system errors out: This site can't be reached. www.raspberrypi.org took too long to respond. ERR_CONNECTION_TIMED_OUT
Hopefully I'm not missing something simple--I've searched quite a bit and haven't found any similar information/solutions.

Futher info:
Kernel IP routing table
Destination Gateway Genmask Flags Metric Ref Use Iface
0.0.0.0 10.0.0.1 0.0.0.0 UG 202 0 0 eth0
10.0.0.0 0.0.0.0 255.255.252.0 U 202 0 0 eth0
10.8.1.0 0.0.0.0 255.255.255.0 U 0 0 0 tun0

I am unable to ping my gateway, 10.0.0.1 which leads me to think that it isn't routing from 10.8.1.1 vpn gateway to 10.0.0.1 gateway, then out to the Internet.

Thank you for your help.

**Comment by 4s3ti** [comment]
@henryammons sorry but the issue template is quite clear: 

```
# PiVPN Issue Template
PLEASE READ THIS TEMPLATE CAREFULLY BEFORE OPENING AN ISSUE! 
Any Issue opened that doesn't follow this template will be removed. 

```

Closing this issue.. please edit and reopen with the information requested there otherwise we won't have all the details we need to help specially with an issue that specific as yours.
