### ISSUE TITLE
[Support] No Traffic on Clients, Server installed on Android Container

### ISSUE THREAD

**Issue by FabioC4** [pivpn/pivpn#913]
## In raising this issue, I confirm the following: 

- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

### Issue

Hello!

I'm having some issues with a project regarding VPN capabilities.

My setup right now is an ARM Android Device which is rooted, running a Linux Image on a Chroot Container (Ubuntu 16/18, Debian) via Linux Deploy.

I managed to install before a Pihole on the device, working correctly, so my next step was to install a working OpenVPN package with Pivpn, i'm testing this ONLY with the Pivpn packages (Without Pihole).

I have consulted every thread and post regarding this issues on similar setups, Linux Containers on Android, with no solution. Also i have all the prerequisites correctly.

Normally, if you try to install the Pivpn using the Stable Branch some issues arise, the Installer cannot configure correctly or bypasses the IPtables installation, generating a 'Quota2' Library problem, that it's shown during the configuration wizard and on Pivpn -debug.

![image](https://user-images.githubusercontent.com/39930208/72686317-9fc25b00-3af3-11ea-90d7-d1d0ccfe305b.png)

With this settings, creating a client profile can be done, but no traffic can be passed.

So, i think i found the origin of the Quota2 issue, it appears that Chroot containers does not include normally the extended iptables packages, and that's why the Openvpn/Pivpn installer sometimes crashes when reaching the Iptables download and installation, the iptables package seems to install correctly because the "iptables command" can be called, but not the xtables, so it prompts the Quota2 message.

I proceeded to intall a clean Ubuntu Chroot Container and then the xtables package before OpenVpn or Pivpn installation, so the installer can continue without issues.

The package required is this one:

xtables-addons-common

(sudo apt-get install)

But now the issue are the IPtables config, because even with this errors cleared, no traffic is being passed during VPN connection.

I tried with a virtual machine the same steps and runs fine, but on this type of setup it does not.

Also tried to copy a working iptables rules.v4 and adapt it to the Android rules with no avail.

Hope you guys can help me or guide me a little.

Thanks!

### Have you searched for similar issues and solutions?
    (yes/no / which issues?)

Yes! several.

Here is one similar on OpenVPN repo:

https://github.com/angristan/openvpn-install/issues/145

### Console output of      `pivpn debug`
```
 ::::		[4mPiVPN debug[0m		 ::::
=============================================
::::		[4mLatest commit[0m		 ::::
commit 2ea469359c357395110a0bfc951d0b6d1c7e9141
Author: 4s3ti <4s3ti@protonmail.com>
Date:   Wed Jan 8 13:13:34 2020 +0100

    Issue #607
    
    Added -p on mkdir /opt/pivpn this fixes issue #607
=============================================
::::	    [4mInstallation settings[0m    	 ::::
/etc/pivpn/DET_PLATFORM -> Ubuntu
/etc/pivpn/FORWARD_CHAIN_EDITED -> 1
/etc/pivpn/HELP_SHOWN -> 
/etc/pivpn/INPUT_CHAIN_EDITED -> 1
/etc/pivpn/INSTALL_PORT -> 1194
/etc/pivpn/INSTALL_PROTO -> udp
/etc/pivpn/INSTALL_USER -> android
/etc/pivpn/NO_UFW -> 1
/etc/pivpn/pivpnINTERFACE -> eth0
=============================================
::::	[4msetupVars file shown below[0m	 ::::
INSTALL_USER=android
UNATTUPG=unattended-upgrades
pivpnInterface=eth0
IPv4dns=
IPv4addr=192.168.1.20
IPv4gw=192.168.1.1
pivpnProto=udp
PORT=1194
ENCRYPT=2048
APPLY_TWO_POINT_FOUR=false
DOWNLOAD_DH_PARAM=false
PUBLICDNS=
OVPNDNS1=1.1.1.1
OVPNDNS2=1.0.0.1
=============================================
::::  [4mServer configuration shown below[0m   ::::
dev tun
proto udp
port 1194
ca /etc/openvpn/easy-rsa/pki/ca.crt
cert /etc/openvpn/easy-rsa/pki/issued/localhost_36c98ddd-e409-4cfa-abac-25bb64f9f8a6.crt
key /etc/openvpn/easy-rsa/pki/private/localhost_36c98ddd-e409-4cfa-abac-25bb64f9f8a6.key
dh /etc/openvpn/easy-rsa/pki/dh2048.pem
topology subnet
server 10.8.0.0 255.255.255.0
# Set your primary domain name server address for clients
push "dhcp-option DNS 1.1.1.1"
push "dhcp-option DNS 1.0.0.1"
# Prevent DNS leaks on Windows
push "block-outside-dns"
# Override the Client default gateway by using 0.0.0.0/1 and
# 128.0.0.0/1 rather than 0.0.0.0/0. This has the benefit of
# overriding but not wiping out the original default gateway.
push "redirect-gateway def1"
client-to-client
keepalive 1800 3600
remote-cert-tls client
tls-version-min 1.2
tls-auth /etc/openvpn/easy-rsa/pki/ta.key 0
cipher AES-256-CBC
auth SHA256
user nobody
group nogroup
persist-key
persist-tun
crl-verify /etc/openvpn/crl.pem
status /var/log/openvpn-status.log 20
status-version 3
syslog
verb 3
#DuplicateCNs allow access control on a less-granular, per user basis.
#Remove # if you will manage access by user instead of device. 
#duplicate-cn
# Generated for use by PiVPN.io
=============================================
::::  [4mClient template file shown below[0m   ::::
client
dev tun
proto udp
remote REMOTE 1194
resolv-retry infinite
nobind
persist-key
persist-tun
key-direction 1
remote-cert-tls server
tls-version-min 1.2
verify-x509-name localhost_36c98ddd-e409-4cfa-abac-25bb64f9f8a6 name
cipher AES-256-CBC
auth SHA256
auth-nocache
verb 3
=============================================
:::: 	[4mRecursive list of files in[0m	 ::::
::: [4m/etc/openvpn/easy-rsa/pki shows below[0m :::
/etc/openvpn/easy-rsa/pki/:
ca.crt
crl.pem
Default.txt
dh2048.pem
extensions.temp
index.txt
index.txt.attr
index.txt.attr.old
index.txt.old
issued
openssl-easyrsa.cnf
private
renewed
revoked
safessl-easyrsa.cnf
serial
serial.old
ta.key
test.ovpn

/etc/openvpn/easy-rsa/pki/issued:
localhost_36c98ddd-e409-4cfa-abac-25bb64f9f8a6.crt
test.crt

/etc/openvpn/easy-rsa/pki/private:
ca.key
localhost_36c98ddd-e409-4cfa-abac-25bb64f9f8a6.key
test.key

/etc/openvpn/easy-rsa/pki/renewed:
private_by_serial
reqs_by_serial

/etc/openvpn/easy-rsa/pki/renewed/private_by_serial:

/etc/openvpn/easy-rsa/pki/renewed/reqs_by_serial:

/etc/openvpn/easy-rsa/pki/revoked:
private_by_serial
reqs_by_serial

/etc/openvpn/easy-rsa/pki/revoked/private_by_serial:

/etc/openvpn/easy-rsa/pki/revoked/reqs_by_serial:
=============================================
::::		[4mSelf check[0m		 ::::
:: [OK] IP forwarding is enabled
:: [OK] Iptables MASQUERADE rule set
:: [OK] Iptables INPUT rule set
:: [OK] Iptables FORWARD rule set
:: [OK] OpenVPN is running
:: [OK] OpenVPN is enabled (it will automatically start on reboot)
:: [OK] OpenVPN is listening on port 1194/udp
=============================================
::::      [4mSnippet of the server log[0m      ::::
=============================================
::::		[4mDebug complete[0m		 ::::


```
### Here are the IPtables rules.v4 generated after Pivpn Debug, seems a bit long compared with other installations:
```
# Generated by iptables-save v1.6.1 on Sun Jan 19 19:24:20 2020
*raw
:PREROUTING ACCEPT [292:167782]
:OUTPUT ACCEPT [325:179322]
:bw_raw_PREROUTING - [0:0]
:idletimer_raw_PREROUTING - [0:0]
-A PREROUTING -j bw_raw_PREROUTING
-A PREROUTING -j idletimer_raw_PREROUTING
-A bw_raw_PREROUTING -m owner --socket-exists
COMMIT
# Completed on Sun Jan 19 19:24:20 2020
# Generated by iptables-save v1.6.1 on Sun Jan 19 19:24:20 2020
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
:natctrl_nat_POSTROUTING - [0:0]
:oem_nat_pre - [0:0]
-A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE
COMMIT
# Completed on Sun Jan 19 19:24:20 2020
# Generated by iptables-save v1.6.1 on Sun Jan 19 19:24:20 2020
*mangle
:PREROUTING ACCEPT [291:167472]
:INPUT ACCEPT [291:167472]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [325:179322]
:POSTROUTING ACCEPT [356:307705]
:bw_mangle_POSTROUTING - [0:0]
:idletimer_mangle_POSTROUTING - [0:0]
:natctrl_mangle_FORWARD - [0:0]
-A INPUT -i eth0 -j MARK --set-xmark 0x30064/0xffffffff
-A FORWARD -j natctrl_mangle_FORWARD
-A POSTROUTING -j bw_mangle_POSTROUTING
-A POSTROUTING -j idletimer_mangle_POSTROUTING
-A bw_mangle_POSTROUTING -m owner --socket-exists
-A natctrl_mangle_FORWARD -p tcp -m tcp --tcp-flags SYN SYN -j TCPMSS --clamp-mss-to-pmtu
COMMIT
# Completed on Sun Jan 19 19:24:20 2020
# Generated by iptables-save v1.6.1 on Sun Jan 19 19:24:20 2020
*filter
:INPUT ACCEPT [1:40]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:bw_FORWARD - [0:0]
:bw_INPUT - [0:0]
:bw_OUTPUT - [0:0]
:bw_costly_shared - [0:0]
:bw_happy_box - [0:0]
:bw_penalty_box - [0:0]
:fw_FORWARD - [0:0]
:fw_INPUT - [0:0]
:fw_OUTPUT - [0:0]
:natctrl_FORWARD - [0:0]
:natctrl_tether_counters - [0:0]
:oem_fwd - [0:0]
:oem_out - [0:0]
-A INPUT -i eth0 -p udp -m udp --dport 1194 -j ACCEPT
-A INPUT -j bw_INPUT
-A INPUT -j fw_INPUT
-A FORWARD -d 10.8.0.0/24 -i eth0 -o tun0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -s 10.8.0.0/24 -i tun0 -o eth0 -j ACCEPT
-A FORWARD -j oem_fwd
-A FORWARD -j fw_FORWARD
-A FORWARD -j bw_FORWARD
-A FORWARD -j natctrl_FORWARD
-A OUTPUT -j oem_out
-A OUTPUT -j fw_OUTPUT
-A OUTPUT -j bw_OUTPUT
-A bw_INPUT -m quota2 --name globalAlert  ! --quota 2097152 
-A bw_INPUT -m owner --socket-exists
-A bw_OUTPUT -m quota2 --name globalAlert  ! --quota 2097152 
-A bw_OUTPUT -m owner --socket-exists
-A bw_costly_shared -j bw_penalty_box
-A natctrl_FORWARD -j DROP
COMMIT
# Completed on Sun Jan 19 19:24:20 2020


```

**Comment by FabioC4** [comment]
When debugging, to where is pointing this specific line or referring?

![3](https://user-images.githubusercontent.com/39930208/72686694-b23e9380-3af7-11ea-89f3-05b09d39de19.png)

**Comment by orazioedoardo** [comment]
> But now the issue are the IPtables config, because even with this errors cleared, no traffic is being passed during VPN connection.
> 
> I tried with a virtual machine the same steps and runs fine, but on this type of setup it does not.
> 
> Also tried to copy a working iptables rules.v4 and adapt it to the Android rules with no avail.
> 
> Hope you guys can help me or guide me a little.

I've never tried to install PiVPN on Linux Deploy, maybe the container is firewalled? Can you SSH into it from the LAN. I think openvpn is not running as there is no `/var/log/openvpn.log` file. What does `systemctl status openvpn` tell you?

> When debugging, to where is pointing this specific line or referring?

It's the self check trying to figure out if OpenVPN is running.

> Here is the IPtables rules.v4 generated by pivpn, seems a bit long compared with other installations

Those additional rules have not been set by PiVPN

**Comment by FabioC4** [comment]
Thank you very much Orazio for taking the time to answer the issue!

Indeed, this setup on a Linux Container is a bit abnormal, but for the sake of testing and achieving  a working configuration i am gonna try to the end. 👍 

> Can you SSH into it from the LAN?

I can SSH on my local network as normal, but do you mean once the OpenVPN connection is being made and use SSH? I have tried connecting by SSH to the Server (Linux Deploy) with a device using an outside network once the OpenVPN tunnel appear as running and connected, with no avail, no traffic. The weird thing is that even the PiVPN clients command shows the external device as connected using the correspondent profile generated by OpenVPN/PiVPN, and some bytes of data transferred.

> I think openvpn is not running as there is no `/var/log/openvpn.log` file. Those additional rules have not been set by PiVPN

Good Point, i´m gonna try to search once again every log. 

If the server itself detects an external connection and also the phone that is being use with OpenVPN App appear as routing traffic, the OpenVPN service may still not even running or in process?

> What does systemctl status openvpn tell you?

Since it is a Deploy container, "systemctl" commands cannot be used, but i´m going to try installing new packages like "servicectl" for this daemons on Chroot environments and report back. I also want to try with a Wireguard installation and changing some table rules. Maybe the container is missing additional packages besides the ones that i referred on the OP.

**Comment by orazioedoardo** [comment]
> I also want to try with a Wireguard installation and changing some table rules. Maybe the container is missing additional packages besides the ones that i referred on the OP.

As the chroot uses the Android kernel, installing WireGuard probably is not that easy as you need to find a custom kernel with the wireguard module or build the kernel yourself: https://forum.xda-developers.com/android/development/wireguard-rom-integration-t3711635

Alterntively, the userspace implementation should work inside the chroot: https://git.zx2c4.com/wireguard-go/about/

**Comment by FabioC4** [comment]
Investigating a bit more i think the issue is related to the way Chroot Containers manage the Systemd / Init, since Android devices normally cannot run it as PID1.

This causes the following messages if i try to install the OpenVPN packages directly without PiVPN:

![image](https://user-images.githubusercontent.com/39930208/73601671-e2f5e280-4565-11ea-80b3-fca15e1f791b.png)


> What does `systemctl status openvpn` tell you?

The settings that can be tweaked on Linux Deploy (Android Environment) for INIT are these:

![image](https://user-images.githubusercontent.com/39930208/73601703-6f080a00-4566-11ea-80f9-2f66d609e127.png)

Selected "sysv" to run automatically on start the needed packages (Ex: Pihole, OpenVPN), and with sysv i can change these:

![image](https://user-images.githubusercontent.com/39930208/73601723-b4c4d280-4566-11ea-9632-e7ec55d3804b.png)

Using Root as INIT and Level 3 for normal multi user boot.

With this tweaking when i start the container, the OpenVPN service appears as started correctly.

![image](https://user-images.githubusercontent.com/39930208/73601739-08cfb700-4567-11ea-9cd8-0051c3034ce0.png)
 
Since "systemctl" cannot be used, i tried replacing it with "service openvpn status", and the Status shows "OK".

![image](https://user-images.githubusercontent.com/39930208/73601753-3c124600-4567-11ea-92bb-5568348678fb.png)

And as reported before, if i try to connect from an outside network using the generated OpenVPN profile, it detects the client but no traffic.

![image](https://user-images.githubusercontent.com/39930208/73601772-85629580-4567-11ea-9ee7-51b693bc23b5.png)

So it brings me once again to think as you said, that maybe the server is not being even correctly started/running because no log is weird.

For example, after a normal PiVPN installation the remaining files on "/etc/openvpn" are like this, with the server folder empty.

![image](https://user-images.githubusercontent.com/39930208/73601804-3d903e00-4568-11ea-8fef-3ec90a718aec.png)

But if i install as standalone the OpenVPN packages, without PiVPN, the folders are like this:

![image](https://user-images.githubusercontent.com/39930208/73601872-872d5880-4569-11ea-8e51-9f0802bce9c3.png)

Is this a normal behavior? PiVPN uses other directory or it should be populated with files?


> Alterntively, the userspace implementation should work inside the chroot: https://git.zx2c4.com/wireguard-go/about/

Trying this next :)


Thanks again Orazio!

**Comment by orazioedoardo** [comment]
> And as reported before, if i try to connect from an outside network using the generated OpenVPN profile, it detects the client but no traffic.

If the client is detected, probably the TLS handshake worked. Can you at least SSH from the VPN client into the container using IP 10.8.0.1? You could also use tcpdump to inspect the traffic. I think it has to do with those weird firewall rules.

> So it brings me once again to think as you said, that maybe the server is not being even correctly started/running because no log is weird.

Maybe openvpn can't log to syslog. Replace `syslog` with `log /tmp/openvpn.log` in the server config `/etc/openvpn/server.conf` and restart the server. I chose `/tmp` so to avoid permissions issues.

> Is this a normal behavior? PiVPN uses other directory or it should be populated with files?

They are stored inside `/etc/openvpn/easy-rsa/pki`.

**Comment by orazioedoardo** [comment]
Interesting thread but no more activity, closing...

**Comment by FabioC4** [comment]
Hi!

Well, after trying a bit of everything i finally managed to succeed and get a working VPN Server hosted on an Android device with Linux using OpenVPN by an installation of PiVPN. This also works perfectly in addition with Pihole.

This packages are neccessary for the correct installation of the PiVPN script on Ubuntu Linux using a Chroot Environment:

1. For IP Tables management we need the package: sudo apt-get install xtables-addons-common

2. For OpenVPN rules we need the firewall package: sudo apt-get install firewalld

3. Run the PiVPN -d for iptables fixing.

4. Add the following rule to enable the tunnel traffic: ip rule add from all lookup main pref 1

With this pre requisites we can get an awesome setup, later i should be doing a complete guide with more improvements so everyone that have a deprecated android device or a phone laying around can put it to some good use.

Thanks!

**Comment by TinCanTech** [comment]
> Hi!
> 
> Well, after trying a bit of everything i finally managed to succeed and get a working VPN Server hosted on an Android device with Linux

FYI: --mode server has been permanently disabled for Android.
https://www.mail-archive.com/openvpn-devel@lists.sourceforge.net/msg19904.html

**Comment by FabioC4** [comment]
> FYI: --mode server has been permanently disabled for Android.
> https://www.mail-archive.com/openvpn-devel@lists.sourceforge.net/msg19904.html

Hi! 

Thanks for the info,

this was pushed to the official stable branch of OpenVPN yesterday May 18?

so it would break future installations of this kind?

**Comment by TinCanTech** [comment]
> so it would break future installations of this kind?

That is my understanding yes.

**Note**: Even if you get a server running on Android, the Andoid tun device cannot do routing.  This means any device connected to your Android server would only be able to see the Android server.  This is a limitation of Android not Openvpn.

**Comment by FabioC4** [comment]
> **Note**: Even if you get a server running on Android, the Android tun device cannot do routing. This means any device connected to your Android server would only be able to see the Android server. This is a limitation of Android not Openvpn.

That is correct, the Android device itself it´s capped for that kind of interactions unless several kernel modifications are made. 

But since this little project of mine is inteded to enable the Pihole capabilities on the road, thankfully it works.

I appreciate your response Tin.

**Comment by bennasar99** [comment]
> > so it would break future installations of this kind?
> 
> That is my understanding yes.
> 
> **Note**: Even if you get a server running on Android, the Android tun device cannot do routing. This means any device connected to your Android server would only be able to see the Android server. This is a limitation of Android not Openvpn.

Sorry but does that mean no internet on VPN clients? 
I'm trying to make an OpenVPN server on linux chroot in android and I can't get internet to work on clients.

**Comment by TinCanTech** [comment]
> does that mean no internet on VPN clients?

Yes.

For clarity, the **Android tun device** cannot do `net.ipv4.ip_forward`.

Try IPv6 ..

**Comment by Fat-ctrl** [comment]
So it is not possible to set up Wireguard on an Android container for now?
