### ISSUE TITLE
Purpose of reboot during installation?

### ISSUE THREAD

**Issue by mikebakke** [pivpn/pivpn#915]
I am merely trying to understand the purpose of the reboot which I see is part of the installation script. 

My reason for asking is to be clear if it's *mandatory* or more best practice. I have seen other manual procedures which also contain a reboot but no-one ever explains why.

My hesitation is just that I have many important (to me and a few others) things running on the Pi so any downtime needs to be managed. If it's required but can happen "later" then fine, I'll crack on - if it must be done at the time I'll schedule the install later.

Thanks!

**Comment by orazioedoardo** [comment]
Rebooting is not strictly required but it's an heuristic way to make sure everything work. Sometimes user have problems with firewall rules not being applied after reboot, or a service doesn't start. If you have them reboot immediately you can catch those problems quicker.

**Comment by mikebakke** [comment]
Thank you for confirming this - means I can install and  do the reboot at a later point.
