### ISSUE TITLE
[pivpn -up] cp: calling stat for '/etc/.pivpn/scripts/bash-completion' is not possible: file or directory not found

### ISSUE THREAD

**Issue by pheiduck** [pivpn/pivpn#916]
Getting this error at `pivpn -up`
```
going do update PiVPN Scripts
....
cp: calling stat for '/etc/.pivpn/scripts/bash-completion' is not possible: file or directory not found
PiVPN Scripts have been updated
```

**Comment by orazioedoardo** [comment]
The scripts layout in the repo has been changed with the last commits, so running `pivpn -up` from an older installation won't work (you don't need to).

**Comment by 4s3ti** [comment]
hmm yeah ... that's not a good thing =/ update from older script to new one will not work, well i guess it wont break anything as well... Guess we can call this pivpn v2.0 since its not bacwards compatible? xD 

guess we could start using versioning xD

**Comment by GvY85** [comment]
Ok, so how should this be solved?

I have a pivpn install from a few months ago and that on cant be updated to the current (running) releases? 
Also, the master repo gets changed all the time but the last prober release is from 2018?
So, if you want to do a fresh install now of pivpn how do you know you wont install some semi buggy unreleased version?
PiVPN is great but lately it feels very messy here

**Comment by 4s3ti** [comment]
@GvY85 I don't really think its messy,  or .. better .. we are actually now that we have full access to the project  we are indeed cleaning up the mess it was before with the main developer and project creator having disappeared, another main contributor stepping down and a secondary owner that is not always available! 

Long story short ...Master branch always changed frequently but now ...  PiVPN its an even more active project with 2 maintainers giving their free time and knowledge to the public and community.

having this said you think it can be better or we can do things another way? well .. this is an opensource project hence you are very welcome to contribute with whatever you can and we will be very happy to read and consider your suggestions / contributions! 

Ont other hand maybe you have have the wrong concepts about PiVPN and the updating? 
in the words of pivpn creator: https://github.com/pivpn/pivpn/wiki/Upgrading


PiVPN Is an installer and most often its updated to fix bugs or add support to some new stuff that comes up ...

After you have installed your OpenVPN/Wireguard PiVPN has served its sole purpose in life!

We do however provide some scripts that make managing the thing a bit easier and Those are the scripts being updated by pivpn -up .. unfortunately with the new major update the file structure changed a bit and older installations using pivpn -up will break. 

I didn't have time yet to think of a nice solution for this and you don't really need to update as it doesn't really provide an extra benefit. 

still if you want to update the scripts 


for OpenVPN the safest way to make it compatible should be doing this: 

```
##Not sure if VPN variable is on legacy setupVars.conf so adding it there. 

sudo echo "VPN=openvpn" >> /etc/pivpn/setupVars.conf
cd /etc/.pivpn/
git pull origin master
cp scripts/update.sh /opt/pivpn/
pivpn -up
```

**Comment by orazioedoardo** [comment]
> We do however provide some scripts that make managing the thing a bit easier and Those are the scripts being updated by pivpn -up .. unfortunately with the new major update the file structure changed a bit and older installations using pivpn -up will break.
> 
> I didn't have time yet to think of a nice solution for this and you don't really need to update as it doesn't really provide an extra benefit.

Agree, also recently most changes to the script are in accordance of new features (like wireguard) or simply new scripts are added that require a new 'pivpn' command, which as of now won't be updated by 'pivpn -up'.

**Comment by pheiduck** [comment]
> @GvY85 I don't really think its messy, or .. better .. we are actually now that we have full access to the project we are indeed cleaning up the mess it was before with the main developer and project creator having disappeared, another main contributor stepping down and a secondary owner that is not always available!
> 
> Long story short ...Master branch always changed frequently but now ... PiVPN its an even more active project with 2 maintainers giving their free time and knowledge to the public and community.
> 
> having this said you think it can be better or we can do things another way? well .. this is an opensource project hence you are very welcome to contribute with whatever you can and we will be very happy to read and consider your suggestions / contributions!
> 
> On other hand maybe you have have the wrong concepts about PiVPN and the updating?
> in the words of pivpn creator: https://github.com/pivpn/pivpn/wiki/Upgrading
> 
> PiVPN Is an installer and most often its updated to fix bugs or add support to some new stuff that comes up ...
> 
> After you have installed your OpenVPN/Wireguard PiVPN has served its sole purpose in life!
> 
> We do however provide some scripts that make managing the thing a bit easier and Those are the scripts being updated by pivpn -up .. unfortunately with the new major update the file structure changed a bit and older installations using pivpn -up will break.
> 
> I didn't have time yet to think of a nice solution for this and you don't really need to update as it doesn't really provide an extra benefit.
> 
> still if you want to update the scripts
> 
> for OpenVPN the safest way to make it compatible should be doing this:
> 
> ```
> ##Not sure if VPN variable is on legacy setupVars.conf so adding it there. 
> 
> sudo bash -c 'echo VPN=openvpn >> /etc/pivpn/setupVars.conf'
> cd /etc/.pivpn/
> git pull origin master
> cp scripts/update.sh /opt/pivpn/
> cd
> sudo pivpn -up
> ```

Thanks a lot, this workaround works for me 💯
