### ISSUE TITLE
Why I can't choose Elliptic Curve encription for OpenVPN anymore

### ISSUE THREAD

**Issue by MatejsLab** [pivpn/pivpn#917]
When I install pivpn with 
> curl -L https://install.pivpn.dev | bash

And I choose OpenVPN... 
I can't choose elliptic curve cryptography anymore, but I was able to about 2 days ago on the previous install. As far as I remember before I was able to choose between RSA and ECDH so why the menu is different now. ECDH is faster to create and should be more secure.

I am running the latest raspbian on Rpi4.

I don't trust wireguard though because it seems less secure with only config and no password-protected certificate am I wrong. 

I have installed OpenVPN 2.4.7 (copied from debug output). I seem to remember it was written that OpenVPN 2.4 supports ECDH (written on previous installations), why not now, am I missing something?

For now I want to stick with OpenVPN it works nice but I want ECDH back, please.

Thanks, Matej

**Comment by orazioedoardo** [comment]
We removed ECDSA support in favor of WireGuard + OpenVPN RSA for this simple reason: have the first protocol for up to date devices, plus the second compatible with virtually every device. WireGuard uses Elliptic Curve similarly to OpenVPN ECDSA (even though they work very differently) so for simplicity of the script we removed the latter.

However we are not convinced yet so if more people demand ECDSA we will bring it back. For this reason, we kept a 'pivpnlegacy' branch without the latest commits which you can use in the meanwhile: 
```
curl -L https://raw.githubusercontent.com/pivpn/pivpn/pivpnlegacy/auto_install/install.sh | bash
```

> I don't trust wireguard though because it seems less secure with only config and no password-protected certificate am I wrong.

Not having the password protection is mainly a concern when moving the config. When the config is on the destination device, it depends: if you have malware on your PC that is able to steal the config it may be able to steal the password for a password protected config too when you type it in.

**Comment by 4s3ti** [comment]
@orazioedoardo however i think the legacy one will get kind of broken as the script is not ready for the current repo file structure. and most likely stuff will break specially scripts installation.

**Comment by MatejsLab** [comment]
Appriciate you for quick response and your interes. I prefer EC over the RSA especially because of faster key generation.

Regarding password protected certificate, of Course anything can be hacked, but I guess for copying conf files you don't need to be hacker. Password needs to be hacked but conf can be stolen pyisically if I bring it to school or office on USB key. Don't want to argue but thats how I see it. 

When trying out WireGuard, I was able to finish instalation and generate conf but with some errors during the proces, so I haven't managed to get it working. Also the app on the Phone doesn't give me the the conectivity information that OpenVPN does. For that reason OpenVPN seems more friendly to Use.

If WireGuard has significalntly lower CPU usage, and consequently lower power consumption on mobile devices, I am still interested in it. 

I am curious, has enyone also encountered errors during WireGuard instalation with pivpn. I may post some pictures of errors when I get to the PC. 

Matej

**Comment by orazioedoardo** [comment]
> Why I can't choose Elliptic Curve encription for OpenVPN anymore

Now you can https://github.com/pivpn/pivpn/commit/44feb0b8534528ecc652cb0810bb919a99a52d55 Please report if it works fine.

> Regarding password protected certificate, of Course anything can be hacked, but I guess for copying WireGuard conf files you don't need to be hacker.

This falls in the general concept of WireGuard being simple and not bothering to implement key distribution. It's assumed that you exchange keys "somehow". We could easily encrypt the config with GPG, but that requires specific software on the destination device too...

> I am curious, has enyone also encountered errors during WireGuard instalation with pivpn. I may post some pictures of errors when I get to the PC.

Sure

**Comment by orazioedoardo** [comment]
> @orazioedoardo however i think the legacy one will get kind of broken as the script is not ready for the current repo file structure. and most likely stuff will break specially scripts installation.
> 
> without code that controls where repo is pulled from then it will just pull the master branch and therefore the whole new dir structure and so on.
> 
> I do Believe we should put back EC on OpenVPN and let users make their decision.

Actually I think it's broken now since it will download script from master, which are not compatible.

**Comment by TinCanTech** [comment]
I have not had time to prepare a test environment but reading through the commit, it LGTM.

FYI: OpenVPN without ECDSA is like "Cheese _without_ onion".

**Comment by 4s3ti** [comment]
Rebased test and pushed. 

@orazioedoardo try to always move the other way around please =) 
Test and then Master if it looks good even if its just quick patch or something similar =)

**Comment by MatejsLab** [comment]
OpenVPN with Elliptic curve encryption works now again, like a charm. **@orazioedoardo** Thanks for your effort. 
Matej

**Comment by 4s3ti** [comment]
Guess this can be closed.
