### ISSUE TITLE
[FR] <Per-user access permissions?>

### ISSUE THREAD

**Issue by eccen** [pivpn/pivpn#918]
**Is your feature request related to a problem? Please describe.**
It seems the pivpn is configured to give the same access (that is, total LAN access) to every user. I would like to restrict this for some, but not all, users. 

**Describe the solution you'd like**
I’d like to be able to grant specific users access to only one server, and nothing else on the network. Ideally they would also not use internet through the vpn but their own instead. At the same time, I’d like to grant other users unrestricted access. Is this possible?

**Describe alternatives you've considered**
I guess it might be possible to set up two different PIs, on different ports. But I’d rather not add hardware if possible. 

**Additional context**
I’d like to be able to allow a subset of users access to a demonstration server that exists behind a vpn, but I definitely don’t want them to have access to the rest of the network (for example the management interface of said server).

**Comment by 4s3ti** [comment]
I guess to make that happen .. just create another server with different settings. 

for example, 

`sudo cp /etc/openvpn/server.conf /etc/openvpn/restricted.conf`

Chang whatever you need on restricted.conf

then `sudo systemctl start openvpn@restricted.service`
