### ISSUE TITLE
lack of firewall rules upon install 

### ISSUE THREAD

**Issue by hyenadog** [pivpn/pivpn#92]
Hi,

firstly thanks for all your efforts, I installed PiVPN on an Armbian Actions S500 board which seemed to go ok .. but for some reason i ended up without the firewall rules needed for it to work (and be reasonably secure (particularly SSH) ... I know very little about IPtables but i have come up with a set of rules that seem to work and are autoloaded upon the wifi interface coming up : 

It would be great if someone more familiar with IP tables could correct any silly errors  I have made
(and perhaps put a vanilla script in the install to help others ?) 

thanks in advance 
ian
```
# !/bin/sh
# Firewall rules in script at /etc/network/if-up.d/firewall
# Remember to make this script executable

Drop ALL INPUT FORWARD connections / Accept ALL OUTPUT by default
iptables -P INPUT DROP
iptables -P FORWARD DROP
iptables -P OUTPUT ACCEPT
# Lock down SSH port to access from local network ONLY

iptables -I  INPUT -s 192.168.1.0/24 -m state --state NEW,ESTABLISHED -p tcp --dport 22 -j ACCEPT
# allow the UDP connection on the openvpn port

iptables -A INPUT -i wlan0 -m state --state NEW -p udp --dport 1194 -j ACCEPT
# Allow TUN interface connections to OpenVPN server

iptables -A INPUT -i tun+ -j ACCEPT
Allow TUN interface connections to be forwarded through other interfaces
iptables -A FORWARD -i tun+ -j ACCEPT
iptables -A FORWARD -i tun+ -o wlan0 -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -A FORWARD -i wlan0 -o tun+ -m state --state RELATED,ESTABLISHED -j ACCEPT
# NAT the VPN client traffic to the Internet. change the ip address mask according to your info of tun0

iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o wlan0 -j MASQUERADE
```

**Comment by dhsc19** [comment]
In my case, I didn't need the ssh access restrictions and a simpler set of rules worked:

iptables -I FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -I FORWARD -s 10.8.0.0/24 -j ACCEPT
iptables -I INPUT -p udp --dport 1194 -j ACCEPT
iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -j SNAT --to <insert your Internet facing IP>
