### ISSUE TITLE
[BUG] NoAccess to local network (Wireguard endpoint)

### ISSUE THREAD

**Issue by Spanishu** [pivpn/pivpn#921]
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

**Describe the bug**
installed the latest pivpn on my raspberrypi (had a previous install of pivpn on it) and chose wireguard. 
At this moment I can use wireguard on myiphone (no issues). When I use it on my windows 10 PC I can navigate to the outside world, but I cannot access any service on my local network (192.168.1.xx range)

**Expected behavior**
I would expect that I am fully tunneled to my local network and can navigate through it.

**Desktop (please complete the following information):**
 - Wireguard
 - WireguardServer Raspian 4.19.93 / Wireguard Client on Windows 10 (0.0.38)

**Comment by orazioedoardo** [comment]
Output of `pivpn debug`?

**Comment by Spanishu** [comment]
192.168.1.xx is my local network

[pvpndebug.txt](https://github.com/pivpn/pivpn/files/4108301/pvpndebug.txt)

**Comment by orazioedoardo** [comment]
If both the Windows PC you are connecting from and the Raspberry Pi are on 192.168.1.0/24, then this is expected behavior.

Say you want to connect to 192.168.1.15: your Windows PC doesn't know whether you want to connect to the local 192.168.1.15 or the remote 192.168.1.15 (where you have the Raspberry Pi). To be more precise, probably windows will try to connect to the local 192.168.1.15.

**Comment by Spanishu** [comment]
;) Thanks. Just tried to connect via the cellphone (tethering) and it does work. However seems to be utterly slow... any suggestions for where to look?

**Comment by orazioedoardo** [comment]
What's the network speed (download/upload) of your home connection and your cellular connection?

**Comment by Spanishu** [comment]
Home 600mbit up and down / 3G on the cellphone. I will make some more trials when I am actually travelling. For the moment I will close this thread. 
Due to the "fairly new status of Wireguard" it would be cool if the script would allow to run both Openvpn and Wireguard in parallel

Thanks for the help
