### ISSUE TITLE
PiVPN not compatible with OpenVPN anymore

### ISSUE THREAD

**Issue by J4TPlays** [pivpn/pivpn#923]
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

**Describe the bug**

Installing PiVPN has an issue where the config file for OpenVPN it generates isn't compatible with OpenVPN. I have tried reinstalling PiVPN multiple times and the same issue arises. Another issue is that while installing, the installer seems to be tied more towards WireGuard than PiVPN and doesn't allow me to use a domain instead of a numerical IP address.

**To Reproduce**
1. Go through the PiVPN installation
2. (for custom domain) attempt to use a custom domain
3. (for OpenVPN incompatibility) finish installation
4. Make a new profile for the VPN and read through contents
5. See error

**Expected behavior**

I believed that the PiVPN .ovpn files should have worked on OpenVPN, however they were unsuccessful as they were made for WireGuard instead.

**Screenshots**

**Desktop (please complete the following information):**
 - VPN Protocol

**Smartphone (please complete the following information):**
 - VPN Protocol: OpenVPN 3.1.0 (4292)
 - Device: Huawei P Smart 2019
 - OS: Android 9

**Additional context**

**Comment by orazioedoardo** [comment]
Before asking more question, can I see the output of `pivpn debug`?

**Comment by TTorini** [comment]
I'm having the same problem. 
After creating a client, my .config file returns an 'unrecognized option or missing or extra parameter' error from OpenVPN (although I am connecting through Tunnelblick as I'm on MacOS).

**Comment by orazioedoardo** [comment]
@TTorini Same reply, please provide the `pivpn debug` output.

**Comment by TTorini** [comment]
::::		Latest commit		 ::::
commit 843daa73cf0c0bf11716cc03fdffcccb4612ac53 (grafted, HEAD -> master, origin/master, origin/HEAD)
Author: 4s3ti <4s3ti@protonmail.com>
Date:   Fri Jan 24 16:28:08 2020 +0100

    Add link to pivpn.dev status dashboard (#922)
    
    * added link to server status dashboard
=============================================
::::	    Installation settings    	 ::::
PLAT=Raspbian
OSCN=buster
USING_UFW=0
IPv4dev=eth0
IPv4addr=10.0.0.37
IPv4gw=10.0.0.138
install_user=pi
install_home=/home/pi
VPN=wireguard
pivpnPORT=51820
pivpnDNS1=9.9.9.9
pivpnDNS2=149.112.112.112
pivpnHOST=REDACTED
INPUT_CHAIN_EDITED=0
FORWARD_CHAIN_EDITED=0
UNATTUPG=1
TO_INSTALL=(dnsutils iptables-persistent qrencode raspberrypi-kernel-headers wireguard wireguard-tools wireguard-dkms unattended-upgrades)
=============================================
::::  Server configuration shown below   ::::
[Interface]
PrivateKey = server_priv
Address = 10.6.0.1/24
ListenPort = 51820
# begin tom
[Peer]
PublicKey = tom_pub
PresharedKey = psk
AllowedIPs = 10.6.0.2/32
# end tom
# begin tomf
[Peer]
PublicKey = tomf_pub
PresharedKey = psk
AllowedIPs = 10.6.0.3/32
# end tomf
=============================================
::::  Client configuration shown below   ::::
[Interface]
PrivateKey = tom_priv
Address = 10.6.0.2/24
DNS = 9.9.9.9, 149.112.112.112

[Peer]
PublicKey = server_pub
PresharedKey = psk
Endpoint = REDACTED:51820
AllowedIPs = 0.0.0.0/0
=============================================
:::: 	Recursive list of files in	 ::::
::::	/etc/wireguard shown below	 ::::
/etc/wireguard:
configs  keys  wg0.conf

/etc/wireguard/configs:
clients.txt  tom.conf  tomf.conf

/etc/wireguard/keys:
psk  server_priv  server_pub  tomf_priv  tomf_pub  tom_priv  tom_pub
=============================================
::::		Self check		 ::::
:: [OK] IP forwarding is enabled
:: [OK] Iptables MASQUERADE rule set
:: [ERR] WireGuard is not running, try to start now? [Y/n] ^C

**Comment by orazioedoardo** [comment]
Well, if you install WireGuard, then clearly you can't use it's config for OpenVPN.

**Comment by TTorini** [comment]
Thanks - I was following a tutorial that uses OpenVPN, I must have overlooked the Wireguard install.

**Comment by orazioedoardo** [comment]
Just run `pivpn -u` then reinstall choosing OpenVPN when prompted.

**Comment by 4s3ti** [comment]
Closing this one. 
I might be releasing a sort of how-to-pivpn official video in the next couple of months... guess people keep consuming outdated how-to's form random people.
