### ISSUE TITLE
New install on rasbpian (Octoprint/Pi) server.

### ISSUE THREAD

**Issue by simonduz** [pivpn/pivpn#925]
Attempting a new install on an updated Octopi Rasbpi 3b+.
I had already configured static IP and did all the OS updates prior to attempting the install.
It makes it past the user selection then throws and error about a missing directory.
The directory does not exist anywhere on the system.   Not sure why it is failing.
Any ideas?
Error:
::: Checking for existing base files...
:::    Checking /etc/.pivpn is a repo...:::    Cloning https://github.com/pivpn/pivpn.git into /etc/.pivpn...main: line 867: cd: /etc/.pivpn: No such file or directory

Lines of output.   Everything else looks clean no errors.
root@octopi:/# curl -L https://install.pivpn.io | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   178  100   178    0     0    110      0  0:00:01  0:00:01 --:--:--   110
100 72059  100 72059    0     0  30807      0  0:00:02  0:00:02 --:--:--  210k
:::
::: You are root.
::: Hostname length OK
::: Verifying free disk space...
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: Your system is up to date! Continuing with PiVPN installation...
:::    Checking for git... installed!
:::    Checking for tar... installed!
:::    Checking for wget... installed!
:::    Checking for grep... installed!
:::    Checking for dnsutils... installed!
:::    Checking for whiptail... installed!
:::    Checking for net-tools... installed!
:::    Checking for bsdmainutils... installed!
:::    Checking for dhcpcd5... installed!
:::    Checking for iptables-persistent... installed!
::: Static IP already configured.
::: Using User: pi
:::
::: Checking for existing base files...
:::    Checking /etc/.pivpn is a repo...:::    Cloning https://github.com/pivpn/pivpn.git into /etc/.pivpn...main: line 867: cd: /etc/.pivpn: No such file or directory

**Comment by orazioedoardo** [comment]
Run the script like so: `curl -L https://install.pivpn.dev | bash -x`. Post the output (may contain IPs or usernames, decide if you want to redact them).

**Comment by 4s3ti** [comment]
Here: https://github.com/pivpn/pivpn/wiki/FAQ#what-about-octopi

**Comment by simonduz** [comment]
@4s3ti This worked for me.
To disable the git wrapper please do: `sudo rm /root/bin/git`
Thanks for your help.   
Now I have to research how to test this install.   Profile configured, router/firewall configured.  ;-)
