### ISSUE TITLE
[FR] Documentation request for Raspbian

### ISSUE THREAD

**Issue by johned0** [pivpn/pivpn#927]
**Is your feature request related to a problem? Please describe.**
I ran the script on a brand new Raspbian installation with all updates applied.
I chose OpenVPN for legacy reasons.
I could connect to the VPN server no problem but I couldn't access the Internet from the client.
Running this command made it work perfectly :

sudo iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE

**Describe the solution you'd like**
Can the command be listed in the Wiki to make it easy for other people to find.

Thanks very much and thanks for a great solution, it is much apprecaited.
John

**Comment by 4s3ti** [comment]
actually this needs to be investigated as it could be a bug, 

The script should be adding this by default.

**Comment by johned0** [comment]
Wonderful, thanks very much,,
Please let me know if you need me to help with some testing.
J

**Comment by orazioedoardo** [comment]
Output of these?
```
sudo cat /etc/iptables/rules.v4
sudo iptables -vnL -t nat
pivpn debug
```

**Comment by johned0** [comment]
This is the output on the working system (after running the "sudo iptables" command).

$ sudo cat /etc/iptables/rules.v4
# Generated by iptables-save v1.8.2 on Thu Jan 30 14:31:55 2020
*filter
:INPUT ACCEPT [4742372:1392214556]
:FORWARD ACCEPT [2:1152]
:OUTPUT ACCEPT [3937047:584538666]
COMMIT
# Completed on Thu Jan 30 14:31:55 2020
# Generated by iptables-save v1.8.2 on Thu Jan 30 14:31:55 2020
*nat
:PREROUTING ACCEPT [536935:35075918]
:INPUT ACCEPT [481050:32392838]
:OUTPUT ACCEPT [31065:2652884]
:POSTROUTING ACCEPT [31066:2653460]
-A POSTROUTING -s 10.8.0.0/24 -o wlan0 -j MASQUERADE
COMMIT
# Completed on Thu Jan 30 14:31:55 2020
$ sudo iptables -vnL -t nat
Chain PREROUTING (policy ACCEPT 28258 packets, 1708K bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain INPUT (policy ACCEPT 25567 packets, 1574K bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain OUTPUT (policy ACCEPT 909 packets, 76913 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain POSTROUTING (policy ACCEPT 909 packets, 76913 bytes)
 pkts bytes target     prot opt in     out     source               destination
    0     0 MASQUERADE  all  --  *      wlan0   10.8.0.0/24          0.0.0.0/0

The VPN is being used today so I won't be able to do the pivpn debug until the weekend.
J

**Comment by 4s3ti** [comment]
> Output of these?
> 
> ```
> sudo cat /etc/iptables/rules.v4
> sudo iptables -vnL -t nat
> pivpn debug
> ```

Guess right now it will show what is expected to be there as @johned0 added the rule manually ... need to test and check if this is being applied or not ... 

Regardless @johned0  the way you added it will not persist after a reboot,
make sure you have that rule on `/etc/iptables/rules.v4`

I have checked the code and we are definitely adding that rule here:

https://github.com/pivpn/pivpn/blob/master/auto_install/install.sh#L1859-L1861

and saving it later here:

https://github.com/pivpn/pivpn/blob/master/auto_install/install.sh#L1902-L1906

output of pivpn debug would be useful. 
also would have been nice to have a copy of the installation output but guess that one is gone =/

**Comment by johned0** [comment]
Thanks for the reply.

Your links don't line up with the newly edited script but I've done a bit more thinking.
I can't prove it without doing a complete reinstall but I've got a feeling that the script configured the routing for wifi0, rather than eth0. I.E. :

sudo iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o wifi0 -j MASQUERADE

In my configuration, wifi is disabled and I'm using eth.

Would this make sense ?

J

**Comment by 4s3ti** [comment]
> Thanks for the reply.
> 
> Your links don't line up with the newly edited script but I've done a bit more thinking.
> I can't prove it without doing a complete reinstall but I've got a feeling that the script configured the routing for wifi0, rather than eth0. I.E. :
> 
> sudo iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o wifi0 -j MASQUERADE
> 
> In my configuration, wifi is disabled and I'm using eth.
> 
> Would this make sense ?
> 
> J

hmm ...well in fact we can see the wlan0 there  ....

```
*nat
:PREROUTING ACCEPT [536935:35075918]
:INPUT ACCEPT [481050:32392838]
:OUTPUT ACCEPT [31065:2652884]
:POSTROUTING ACCEPT [31066:2653460]
-A POSTROUTING -s 10.8.0.0/24 -o wlan0 -j MASQUERADE
COMMIT
```

indeed it could have picked up the wrong interface ... 
Could you by any chance have selected the wrong one? that would explain it .. as we haven't seen this happening ...

**Comment by orazioedoardo** [comment]
> Could you by any chance have selected the wrong one? that would explain it .. as we haven't seen this happening ...

Right, If the installer showed wlan0 as an interface to pick, it means that he was connected to wifi (on my system `ip address` shows that if I'm connected to wifi the interface is UP, if not connected DOWN).

@johned0 do you remember if you switched from wifi to ethernet after the install?

**Comment by johned0** [comment]
Hi Guys, Sorry for the delayed reply, I've been out of the office.

@orazioedoardo - do you remember if you switched from wifi to ethernet after the install?
You are absolutely correct. My bad.
Yes, I originally set this up when the wifi was being used but then moved over to Ethernet.

My apologies for my oversight and thanks again for your help.
Best regards,
John
