### ISSUE TITLE
WireGuard Issue

### ISSUE THREAD

**Issue by jsmgithub** [pivpn/pivpn#928]
Hi,

WireGuard Client Create Issue. It´s create a .conf file but no keys for client and the server.
/opt/pivpn/makeCONF.sh: line 77: wg: command not found
/opt/pivpn/makeCONF.sh: line 77: wg: command not found
Failed to restart wg-quick@wg0.service: Unit wg-quick@wg0.service not found
Failed to restart WireGuard

**Comment by orazioedoardo** [comment]
Closing as not following the issue template. Edit the issue with the information requested in the template and reopen.

**Comment by 4s3ti** [comment]
also the solution for this is already in existing issues!
