### ISSUE TITLE
everythng install fine except generated .ovpn in the home/pi/ovpns folder it always blank

### ISSUE THREAD

**Issue by JustMev** [pivpn/pivpn#93]
everythng install fine except the generated .ovpn file  in the home/pi/ovpns folder it always blank I have regenerated few times only to find black folder ? SO i cannot extract the file with wscp to put into my cleint.

any idea's using raspbian latest jessie lite on rpi3

**Comment by redfast00** [comment]
Have you ran `pivpn add` or `pivpn add nopass`? After the install (`curl -L https://install.pivpn.io | bash` and filling in a bunch of questions), you have to generate client configurations with `pivpn add` or `pivpn add nopass` if you don't want to encrypt your keys in the .ovpn file.

**Comment by jobensingh** [comment]
I have the same problem I have run pivpn add, entered the correct information, but in the end I get this, "[ERROR]: Client Public Key Certificate not found: " And when I check the ovpns folder it is empty

**Comment by redfast00** [comment]
This was fixed by #102. You can either manually edit the files or you can uninstall and reinstall.
