### ISSUE TITLE
Support for Ed25519?

### ISSUE THREAD

**Issue by npburns224** [pivpn/pivpn#934]
Will a future update add support for Ed25519 encryption?

**Comment by orazioedoardo** [comment]
As far as I know, OpenVPN does not support Ed25519.

**Comment by orazioedoardo** [comment]
> It will ask which authentication method you wish the guts of your server to use. If you go for WireGuard, you don't get to choose: you will use a Curve25519 public key, which provides 128-bit security.

Also mentioned in the README.
