### ISSUE TITLE
[Support] "internal compiler error: Segmentation fault" when building WireGuard

### ISSUE THREAD

**Issue by jameshope87** [pivpn/pivpn#936]
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

### Issue

I installed a fresh Buster image on my raspberry pi 3B a couple of weeks ago. Upgraded and then installed pivpn successfully and everything worked well.

However I started having issues connected and when I checked Wireguard was not running.

I have uninstalled, purged and removed as many folders as I can find. However this is the result of the installation:

https://pastebin.com/wN0iktHm

And this is the output of the make.log referenced in the above paste:

https://pastebin.com/5L0f2U2f

### Have you searched for similar issues and solutions?
    (yes/no / which issues?)
Yes, I have found a few issues on here, bit none completely match the error and none solve the issue.

**Comment by orazioedoardo** [comment]
> I have uninstalled, purged and removed as many folders as I can find.

Could you explain what you have done exactly?

**Comment by jameshope87** [comment]
Hard to say now, I have been working on this for a few days.

But I have definitely done:

`sudo apt purge wireguard*`
`sudo apt autoremove`
`sudo apt purge`

This also removed dkms

Then I removed the /etc/wireguard folder.

**Comment by orazioedoardo** [comment]
I suspect you messed up something with the compiler, try these:

```
sudo apt update
sudo apt remove --purge build-essential raspberrypi-kernel-headers wireguard wireguard-tools wireguard-dkms
sudo apt install build-essential raspberrypi-kernel-headers wireguard wireguard-tools wireguard-dkms
```

**Comment by jameshope87** [comment]
> I suspect you messed up something with the compiler, try these:
> 
> ```
> sudo apt update
> sudo apt remove --purge build-essential raspberrypi-kernel-headers wireguard wireguard-tools wireguard-dkms
> sudo apt install build-essential raspberrypi-kernel-headers wireguard wireguard-tools wireguard-dkms
> ```
Unfortunately this still did not work:

```
Message from syslogd@raspberrypi-main at Feb  5 17:43:14 ...
 kernel:[  123.466148] Code: e92dd9f8 e24cb004 e52de004 e8bd4000 (e5903070)
Error! Bad return status for module build on kernel: 4.19.93+ (armv7l)
Consult /var/lib/dkms/wireguard/0.0.20200128/build/make.log for more information.
dpkg: error processing package wireguard-dkms (--configure):
 installed wireguard-dkms package post-installation script subprocess returned erro
r exit status 10
Setting up wireguard-tools (1.0.20200121-2) ...
Setting up libstdc++-8-dev:armhf (8.3.0-6+rpi1) ...
dpkg: dependency problems prevent configuration of wireguard:
 wireguard depends on wireguard-dkms (>= 0.0.20200121-2) | wireguard-modules (>= 0.
0.20191219); however:
  Package wireguard-dkms is not configured yet.
  Package wireguard-modules is not installed.

dpkg: error processing package wireguard (--configure):
 dependency problems - leaving unconfigured
Setting up g++-8 (8.3.0-6+rpi1) ...
Setting up g++ (4:8.3.0-1+rpi2) ...
update-alternatives: using /usr/bin/g++ to provide /usr/bin/c++ (c++) in auto mode
Setting up build-essential (12.6) ...
Processing triggers for man-db (2.8.5-2) ...
Errors were encountered while processing:
 wireguard-dkms
 wireguard
E: Sub-process /usr/bin/dpkg returned an error code (1)
```


> > However I started having issues connected and when I checked Wireguard was not running.
> 
> There is `pivpn debug` for those cases.

Yes, that is how I found Wireguard wasn't running

**Comment by orazioedoardo** [comment]
Output of the kernel buffer? `dmesg -l emerg,alert,crit,err,warn`
And DKMS modules? `dkms status`

**Comment by jameshope87** [comment]
> Output of the kernel buffer? `dmesg -l emerg,alert,crit,err,warn`
> And DKMS modules? `dkms status`
> Also memory status? `free -m`

When I went to do this, I thought I would install pastebinit to make this easier. On running apt get update and upgrade the issue seemed to have been fixed...

No idea why it worked that time.

Thank you

**Comment by jameshope87** [comment]
Ok so while doing and apt upgrade it did an update to raspberry pi kernel while caused the whole system to fail so that it would not boot. I made a completely fresh as card, changed passwords, enabled private key SSH and disabled password access, did a full upgrade, installed pihole, then installed pivpn and I have the same issue.

The outputs to the commands you asked for above:

http://paste.debian.net/1130255

`pi@raspberrypi-main:~ $ dkms status
wireguard, 0.0.20200205, 4.19.97+, armv7l: installed`

`pi@raspberrypi-main:~ $ free -m
              total        used        free      shared  buff/cache   available
Mem:            926          70         514           8         341         792
Swap:            99           0          99`

**Comment by orazioedoardo** [comment]
> Ok so while doing and apt upgrade it did an update to raspberry pi kernel while caused the whole system to fail so that it would not boot.

This makes me think that your SD card might be dying.

> wireguard, 0.0.20200205, 4.19.97+, armv7l: installed

On a Raspberry Pi 3B you should have 2 or 3 lines of dkms output, depending how may kernel headers you have inside /usr/src. If you have only one, probably kernel headers were corrupted, for the same reason above. You can check the apt output (and dkms) with `cat /var/log/apt/term.log`.

**Comment by jameshope87** [comment]
> This makes me think that your SD card might be dying.
Possible, but it is a brand new SD card and a different one to before. I'm also not the only one who seems to have trouble installing wireguard it seems.

> On a Raspberry Pi 3B you should have 2 or 3 lines of dkms output, depending how may kernel headers you have inside /usr/src. If you have only one, probably kernel headers were corrupted, for the same reason above. You can check the apt output (and dkms) with cat /var/log/apt/term.log

is there a way to fix this?

That log is here: http://paste.debian.net/1130257

**Comment by orazioedoardo** [comment]
> Possible, but it is a brand new SD card and a different one to before. I'm also not the only one who seems to have trouble installing wireguard it seems.

Sure, but crash on kernel update is very weird. I’m not saying it’s not wireguard fault, but it never happened to me that the wireguard module crashed the kernel.

> http://paste.debian.net/1130257

First reboot to make sure you load the new kernel (if you have any), then:

```
apt remove --purge wireguard wireguard-dkms raspberrypi-kernel-headers
apt install raspberrypi-kernel-headers
apt install wireguard wireguard-dkms
```

I know they are the same commands as above but this is what comes into my mind now. Then `pivpn debug` and accept fixes (post the output too).

**Comment by jameshope87** [comment]
> First reboot to make sure you load the new kernel (if you have any), then:

apt remove --purge wireguard wireguard-dkms raspberrypi-kernel-headers
apt install raspberrypi-kernel-headers
apt install wireguard wireguard-dkms

> I know they are the same commands as above but this is what comes into my mind now.

Unfortunately the Wireguard installation still fails.

http://paste.debian.net/1130260

I'll try again on a fresh SD tonight.

**Comment by orazioedoardo** [comment]
What’s the make output? `cat /var/lib/dkms/wireguard/0.0.20200205/build/make.log`

**Comment by jameshope87** [comment]
> What’s the make output? `cat /var/lib/dkms/wireguard/0.0.20200205/build/make.log`

http://paste.debian.net/1130261/

This log is way beyond me! Thanks for taking the time to look

**Comment by orazioedoardo** [comment]
Ok basically the same as error as the first post. I can’t find much information on the web. I know the following is not really a solution to the underlying problem but...

- Reflash the latest Raspbian (2020-02-05)
- Perform all upgrades and reboot `sudo bash -c 'apt update && apt upgrade -y && reboot'`
- Install Pi-hole
- Install PiVPN

Do exactly these steps so we end up in a reproducible state in case of problems.

**Comment by jameshope87** [comment]
> Ok basically the same as error as the first post. I can’t find much information on the web. I know the following is not really a solution to the underlying problem but...
> 
> * Reflash the latest Raspbian (2020-02-05)
> * Perform all upgrades and reboot `sudo bash -c 'apt update && apt upgrade -y && reboot'`
> * Install Pi-hole
> * Install PiVPN
> * Post `dkms status`
> * Post `dmesg -l emerg,alert,crit,err` (only errors and above this time)
> 
> Do exactly these steps so we end up in a reproducible state in case of problems. If you have some, just stop and report.

Thank you, I will have to do this once home because I can't reflash raspbian remotely over SSH!

I will try it on the same SD and then on a new SD as well to help with diagnosis.

**Comment by jameshope87** [comment]
Ok i did that with a fresh install on a brand new out of the pack SD card. still failed at the install of wireguard:

```
:::    Checking for raspberrypi-kernel-headers... not installed!
:::    Checking for wireguard... not installed!
:::    Checking for wireguard-tools... not installed!
:::    Checking for wireguard-dkms... not installed!
:::    Checking for qrencode... not installed!
:::    Package raspberrypi-kernel-headers successfully installed!
:::    Failed to install wireguard!
:::    Package wireguard-tools successfully installed!
:::    Failed to install wireguard-dkms!
:::    Package qrencode successfully installed!
pi@raspberrypi:~ $ dkms status
wireguard, 0.0.20200205: added
pi@raspberrypi:~ $ dmesg -l emerg,alert,crit,err
[    4.967087] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43430-sdio for chip BCM43430/1
[    5.177721] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43430-sdio for chip BCM43430/1
[    5.180765] brcmfmac: brcmf_c_process_clm_blob: no clm_blob available (err=-2), device may have limited channels available
[    5.181799] brcmfmac: brcmf_c_preinit_dcmds: Firmware: BCM43430/1 wl0: Oct 23 2017 03:55:53 version 7.45.98.38 (r674442 CY) FWID 01-e58d219f
```

**Comment by JohnAWolf** [comment]
I am getting the same message when I try to use PiVPN to set up Wireguard.  OpenVPN works just fine, but Wireguard and wireguard-dkms fail to install on a fresh SD.

**Comment by orazioedoardo** [comment]
> Then attempting to instill Wireguard manually using apt caused the whole system to lock up and crash. Lost SSH cannot reconnect.

At this point, this looks like a problem with the wireguard-dkms package, not pivpn specific.

@jameshope87 I don’t see relevant errors in the kernel log, these are errors regarding the wifi drivers.

**Comment by jameshope87** [comment]
> > Then attempting to instill Wireguard manually using apt caused the whole system to lock up and crash. Lost SSH cannot reconnect.
> 
> At this point, this looks like a problem with the wireguard-dkms package, not pivpn specific.
> 
> @jameshope87 I don’t see relevant errors in the kernel log, these are errors regarding the wifi drivers.

So I guess is should open an issue on the Wireguard page?

**Comment by orazioedoardo** [comment]
Maybe ask on the reddit wireguard page first and see if you get some interest, i.e. lots of people have the same error: show [this](https://paste.debian.net/1130260) and [this](https://paste.debian.net/1130261/). Me personally, I can't reproduce the issue like [what happened here](https://github.com/pivpn/pivpn/issues/920) so I won't ask you to report to the debian bug reporting system straight.

**Comment by orazioedoardo** [comment]
What model do you have `cat /proc/device-tree/model`? @jameshope87 @JohnAWolf

**Comment by JohnAWolf** [comment]
I have a Model 3 B Rev 1.2. Hope that helps.

**Comment by giuliano108** [comment]
I'm not sure which of these two actions fixed the problem for me, but I've:

* Updated `raspberrypi-kernel` (you can check the version below)
* Installed `gcc-7`

Wireguard, from debian unstable, compiles and installs now.

```
root@octopi:~# find /lib/modules/`uname -r` | grep wiregu
/lib/modules/4.19.97-v7+/kernel/net/wireguard.ko
root@octopi:~# modprobe wireguard
root@octopi:~# dmesg | tail
[   19.609585] Bluetooth: HCI UART driver ver 2.3
[   19.609594] Bluetooth: HCI UART protocol H4 registered
[   19.609649] Bluetooth: HCI UART protocol Three-wire (H5) registered
[   19.609768] Bluetooth: HCI UART protocol Broadcom registered
[   21.169098] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[   21.169107] Bluetooth: BNEP filters: protocol multicast
[   21.169122] Bluetooth: BNEP socket layer initialized
[  434.991356] wireguard: loading out-of-tree module taints kernel.
[  434.999035] wireguard: WireGuard 0.0.20200215 loaded. See www.wireguard.com for information.
[  434.999048] wireguard: Copyright (C) 2015-2019 Jason A. Donenfeld <Jason@zx2c4.com>. All Rights Reserved.
root@octopi:~#
```
