### ISSUE TITLE
[REQUEST FOR COMMENTS] Move documentation

### ISSUE THREAD

**Issue by 4s3ti** [pivpn/pivpn#937]
Wondering if we should move our wiki/faq section to something like: 

https://www.mkdocs.org/  or https://www.sphinx-doc.org/

guess this will allow more people to contribute to it and will probably look better than current wiki on github. 

What everyone around here thinks about it?

**Comment by 4s3ti** [comment]
actually the FAQ might be better placed straight on the website itself

**Comment by orazioedoardo** [comment]
Anything as long as we encourage people to actually read the wiki (and maybe Issues too). If i had to choose, I would add documentation on the website itself.

**Comment by 4s3ti** [comment]
Started working on this, should be up in the next couple of days. 

Will be using https://squidfunk.github.io/mkdocs-material/

**Comment by 4s3ti** [comment]
https://docs.pivpn.io

https://github.com/pivpn/docs
