### ISSUE TITLE
[FR] Add hosts file to identify clients (PiHole)

### ISSUE THREAD

**Issue by jacklul** [pivpn/pivpn#942]
When Pi-hole is detected I see no reason to not add new config to `/etc/dnsmasq.d/` with (for example) `addn-hosts=/etc/wireguard/hosts` which could contain entries like `10.6.0.2 peer1.pivpn`. This would allow to identify peers directly in Pi-hole dashboard as well as resolve peers by those names.
You already do something similar with file containing list of clients so adding this should be easy.

I think many people would appreciate this addition!

**Comment by orazioedoardo** [comment]
Good idea: https://github.com/pivpn/pivpn/commit/3f616d9254acab1a153190c7fde821e95bfc46a9

```
$ pivpn -a
Enter a Name for the Client: alice
::: Client Keys generated
::: Client config generated
::: Updated server config
::: Updated hosts file for Pi-hole
::: WireGuard restarted
======================================================================
::: Done! alice.conf successfully created!
::: alice.conf was copied to /home/user/configs for easy transfer.
::: Please use this profile only on one device and create additional
::: profiles for other devices. You can also use pivpn -qr
::: to generate a QR Code you can scan with the mobile app.
======================================================================
$ dig +short alice.pivpn
10.6.0.2
$ cat /etc/pivpn/hosts.wireguard
10.6.0.2 alice.pivpn
$ cat /etc/dnsmasq.d/02-pivpn.conf
interface=wg0
addn-hosts=/etc/pivpn/hosts.wireguard
```

`/etc/wireguard/hosts` was not a suitable location since `/etc/wireguard` is root owned with `700` permissions, and pihole-FTL runs as pihole user.
