### ISSUE TITLE
Help. I cannot install PiVPN on my Raspberry pi 4 (4gb)

### ISSUE THREAD

**Issue by TariqTheCoder** [pivpn/pivpn#943]
when I run this "curl -L https://test.pivpn.io | TESTING= bash"
I get this error
Checking for git... already installed!
:::    Checking for tar... already installed!
:::    Checking for wget... already installed!
:::    Checking for curl... already installed!
:::    Checking for grep... already installed!
:::    Checking for dnsutils... not installed!
:::    Checking for whiptail... already installed!
:::    Checking for net-tools... already installed!
:::    Checking for bsdmainutils... already installed!
:::    Checking for dhcpcd5... already installed!
:::    Checking for iptables-persistent... not installed!
:::    Failed to install dnsutils!
:::    Failed to install iptables-persistent!
pi@raspberrypi:~ $

**Comment by orazioedoardo** [comment]
I should close this issue because It doesn’t really follow the issue template, however, the console output is there so... what’s the output of `sudo apt-get —yes --no-install-recommends install dnsutils iptables-persistent`?

**Comment by TariqTheCoder** [comment]
I got it to work by following wherever in this blog https://blog.mxard.com/persistent-iptables-on-raspberry-pi-raspbian
PS: I'm very sorry if I broke any rules this is my first post in this website and I have no clue what im doing.
