### ISSUE TITLE
[BUG] wireguard ipv6 in lsmod

### ISSUE THREAD

**Issue by corfeur12** [pivpn/pivpn#944]
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

**Describe the bug**
Connecting to the VPN from outside of my LAN results in no webpages loading. On going through the [FAQ](https://github.com/pivpn/pivpn/wiki/FAQ), I ran `lsmod | grep wireguard` which produced the additional line `ipv6                  454656  52 wireguard`. This does not match the exact specified output in the FAQ, so I suspect this is causing the issue.

**To Reproduce**
1. Install PyVPN with wireguard as the VPN, using a dynamic IP, pihole already installed (select yes when offered to use pihole), and using wifi (as ethernet is unavailable to me)
2. Create a new client using `pivpn -a`
3. Import client config using `pivpn -qr client` onto a mobile phone
4. Start wireguard with the imported config on the mobile phone (using mobile data)
5. Try to access any website throught the browser

**Expected behavior**
I expected any/all websites to load, but instead they timeout after 60 seconds.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - VPN Protocol: WireGuard
 - OS: Raspbian Lite
 - Version: 10

**Smartphone (please complete the following information):**
 - VPN Protocol: WireGuard
 - Device: Samsung Galaxy J5 2017
 - OS: Android
 - Version: 9.0

**Additional context**
I don't think this is related to issue [920](https://github.com/pivpn/pivpn/issues/920) as WireGuard successfully installs but I'm noting it as it is recent and could be related.

I have checked through all steps in the FAQ and the other step that failed was packet capture. Running `tcpdump -n -i IPv4dev pivpnPROTO port pivpnPORT` with fields filled appropriately, I did not receive any packets from my mobile phone. My router does not use CGNAT, and I have not switched from ethernet to wifi. The outputs of `sudo iptables -S` and `sudo iptables -t nat -S` are:
```
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
```

```
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT
-A POSTROUTING -s 10.6.0.0/24 -o wlan0 -m comment --comment wireguard-nat-rule -j MASQUERADE
```

PiHole was installed over wifi as well and that works as expected.

I have tried uninstalling and reinstalling PiVPN but this has led to the same issue occurring.

Running `pivpn -d` yields me
```
::::            PiVPN debug              ::::
=============================================
::::            Latest commit            ::::
commit bf0015c3030ea8ea54ff5473f957858c814c1ac7 (grafted, HEAD -> master, origin/master, origin/HEAD)
Author: Orazio <orazioedoardo@users.noreply.github.com>
Date:   Wed Feb 5 20:51:24 2020 +0100

    Replaced last reference to pivpn.dev with pivpn.io
=============================================
::::        Installation settings        ::::
PLAT=Raspbian
OSCN=buster
USING_UFW=0
IPv4dev=wlan0
dhcpReserv=1
IPv4addr=192.168.1.97/24
IPv4gw=192.168.1.254
install_user=pi
install_home=/home/pi
VPN=wireguard
pivpnPORT=33227
pivpnDNS1=10.6.0.1
pivpnDNS2=
pivpnHOST=REDACTED
INPUT_CHAIN_EDITED=0
FORWARD_CHAIN_EDITED=0
UNATTUPG=1
INSTALLED_PACKAGES=(raspberrypi-kernel-headers wireguard wireguard-tools wireguard-dkms)
=============================================
::::  Server configuration shown below   ::::
[Interface]
PrivateKey = server_priv
Address = 10.6.0.1/24
ListenPort = 33227
# begin EaglesJ5
[Peer]
PublicKey = EaglesJ5_pub
PresharedKey = psk
AllowedIPs = 10.6.0.2/32
# end EaglesJ5
=============================================
::::  Client configuration shown below   ::::
[Interface]
PrivateKey = EaglesJ5_priv
Address = 10.6.0.2/24
DNS = 10.6.0.1

[Peer]
PublicKey = server_pub
PresharedKey = psk
Endpoint = REDACTED:33227
AllowedIPs = 0.0.0.0/0
=============================================
::::    Recursive list of files in       ::::
::::    /etc/wireguard shown below       ::::
/etc/wireguard:
configs  keys  wg0.conf

/etc/wireguard/configs:
clients.txt  EaglesJ5.conf

/etc/wireguard/keys:
EaglesJ5_priv  EaglesJ5_pub  psk  server_priv  server_pub
=============================================
::::            Self check               ::::
:: [OK] IP forwarding is enabled
:: [OK] Iptables MASQUERADE rule set
:: [OK] WireGuard is running
:: [OK] WireGuard is enabled (it will automatically start on reboot)
:: [OK] WireGuard is listening on port 33227/udp
=============================================
:::: Having trouble connecting? Take a look at the FAQ:
:::: https://github.com/pivpn/pivpn/wiki/FAQ
=============================================
:::: WARNING: This script should have automatically masked sensitive       ::::
:::: information, however, still make sure that PrivateKey, PublicKey      ::::
:::: and PresharedKey are masked before reporting an issue. An example key ::::
:::: that you should NOT see in this log looks like this:                  ::::
:::: YIAoJVsdIeyvXfGGDDadHh6AxsMRymZTnnzZoAb9cxRe                          ::::
=============================================
::::            Debug complete           ::::
```

Port forwarding is set up correctly on my router also.

Please let me know if any additional information is needed.

**Comment by orazioedoardo** [comment]
Actually I think the output of your `lsmod | grep wireguard` indicates that the module is indeed running even if you have that additional line. Seems like the output is not consistent across distribution, that said can you provide yours so I can update the FAQ?

Back to the issue: considering that you followed all steps in the FAQ (you did right) I’m not sure whether your port forwarding is actually working: tcpdump captures traffic at the “edges” of the packet flow. It is the first that sees packets INCOMING and the last that sees OUTGOING packets. So If `tcpdump -n -i wlan0 udp port 33227` shows nothing this means that no packets reach the raspberry pi, regardless of iptables, ufw or the software using that port.

What if you forward a random unused port (for example port 12345 proto tcp) and test with https://www.canyouseeme.org, while you keep `tcpdump -n -i wlan0 tcp port 12345` running? canyouseeme will fail but you should at least see packets in the tcpdump output (use tcp for this test as the website only does tcp).

**Comment by corfeur12** [comment]
The full output of `lsmod | grep wireguard` is
```
wireguard             143360  0
ip6_udp_tunnel         16384  1 wireguard
udp_tunnel             16384  1 wireguard
ipv6                  454656  36 wireguard
```

It turned out there was a bug in the firmware of my router which was preventing all port forwarding. I have updated this and now the VPN works as expected so the issue is resolved. Thank you for all your help!
