### ISSUE TITLE
[BUG] PiVPN breaks pihole when choosing to use pihole in the install script

### ISSUE THREAD

**Issue by richie510** [pivpn/pivpn#946]
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

**Describe the bug**
PiVPN breaks pihole when choosing to use pihole for dns after pihole is detected.

It appears the problem is due to the file /etc/dnsmasq.d/02-pivpn.conf
This file had this one line in it: interface=wg0
removing this file and restarting pihole fixed it for me.

**To Reproduce**
1. have a running pihole server
2. install PiVPN and chose yes after pihole is detected
3. observe that pihole is broken

**Expected behavior**
I expected pihole not to be broken

**Screenshots**
n/a

**Additional context**
This reddit thread got me at least understanding what triggered the error, then I just went searching around in /etc until I found something related, and that file was it. 

https://www.reddit.com/r/pivpn/comments/ess90x/pivpn_kills_pihole/

**Comment by orazioedoardo** [comment]
> It appears the problem is due to the file /etc/dnsmasq.d/02-pivpn.conf
> This file had this one line in it: interface=wg0

That file tells pihole to listen on the wg0 (WireGuard) interface al well, and it’s the only change you (or the script) have to do to allow dns resolution to work via VPN.

Have you changed some settings via the Pi-hole admin interface?

**Comment by richie510** [comment]
I don't think I have any special pihole settings. I also enabled my piholes for vpn dns by specifying them specifically in the dns setup of PiVPN. That works perfectly. 

That file with that setting made it so that no device on my network could use the ip address of the pihole to fulfill dns requests. Even from the pihole device itself, I could not use its ip address, I could only successfully get dns queries answered by using the 127.0.0.1 address. I'm not the only one with this problem as shown in the reddit thread I linked to. 

If there are any suggestions on extra debugging that I should do, I'm happy to do it, but right now it seemed pretty cut and dry that the extra setting put into pihole was hurting my pihole, and several others as well.

**Comment by orazioedoardo** [comment]
What’s your `Interface listening behavior` in the DNS settings?

**Comment by richie510** [comment]
Further, I looked into that setting on the dnsmasq man page. That setting identifies the ONLY interface that dnsmasq should listen to:
interface=<interface name>
    Listen only on the specified interface(s).

Looking at the pihole dnsmasq config file I do not see any interface listed. I would assume that if none are listed, then any ok. 
@orazioedoardo I just saw your latest message. In my pihole settings it is set to "listen on all interfacess"

**Comment by richie510** [comment]
So it would seem to me that the install script needs to either know how pihole is setup, or query from the user to determine if it needs to add this extra interface.

**Comment by orazioedoardo** [comment]
> Looking at the pihole dnsmasq config file I do not see any interface listed. I would assume that if none are listed, then any ok.

That’s what I was about to say.  If you have no `interface=` specified, then dnsmasq listens on EVERY interface. But if you have an interface specified, for example `interface=wg0`, it listens ONLY on that interface.

HOWEVER, when you install Pi-hole, the default listening behavior is `listen only interface eth0` which sets `interface=eth0`, thus adding wg0 via the PiVPN installer works just fine.

> @orazioedoardo I just saw your latest message. In my pihole settings it is set to "listen on all interfacess"

Well you did change some setting.

**Comment by richie510** [comment]
> Well you did change some setting.
This setting is quite prominent in the web GUI, so it is not exactly hidden low level feature.

**Comment by orazioedoardo** [comment]
I’m wondering why you changed that though

**Comment by richie510** [comment]
I had wireguard installed the old fashioned way on my other raspberry pi. I had to change that setting to get dns to work properly for that pi. I keep the settings consistent between the two Pis. 

But there could be any number of reasons for any user to change that setting. I also may have done it because I initially setup my raspberry pi zero w with a usb ethernet dongle, and later switched to using the native wireless lan. 

Regardless, the setting to "listen on all interfaces" is more permissive, and I want that on my local network.

**Comment by orazioedoardo** [comment]
> I had wireguard installed the old fashioned way on my other raspberry pi. I had to change that setting to get dns to work properly for that pi.

That’s the lazy approach most _Pi-hole + anything VPN_ guides suggest to do: just listen on every interface instead of what you specifically tell Pi-hole to listen on, and I bet most of those “breaks” arise from [this](https://github.com/pivpn/pivpn/issues/923#issuecomment-581118773).

> But there could be any number of reasons for any user to change that setting. I also may have done it because I initially setup my raspberry pi zero w with a usb ethernet dongle, and later switched to using the native wireless lan.

That’s also a lazy approach to me, why not just change the interface (however I respect that use case, lazy but easy for non tech savvy).

**Comment by orazioedoardo** [comment]
> So it would seem to me that the install script needs to either know how pihole is setup, or query from the user to determine if it needs to add this extra interface.

I’m not really a fan of adding this workaround but it should be possible to check for existing `interface=` inside Pi-hole configs and just avoid adding `interface=wg0` if the former is not found.

**Comment by richie510** [comment]
> That’s also a lazy approach to me, why not just change the interface in the /etc/dnsmsq.d folder? (however I respect that use case, lazy but easy for non tech savvy). Even though you should also update the static DHCP settings inside /etc/dhcpcd.conf if you switch from ethernet to wifi...

It is through pihole, PiVPN, wireguard and several other projects that I have learned so much about how all of these things work. At the time I didn’t know that the switch in pihole was just changing something in the dnsmasq config file. I know that now, and it would be reasonable to just change the config file. 

I would hope that PiVPN at the very least can educate the user that if they have made poor decisions in their dnsmasq settings, that the installer could break their pihole setup, and educate them on how they could fix it after the fact.

**Comment by orazioedoardo** [comment]
Sometimes, I browse reddit and see problems or questions that could be solved just by reading the PiVPN wiki or existing issues, (like, how do I allow pihole, how do I not tunnel all my traffic, my Pivpn is not connecting, what do i check?). For this reason I had to add a link to the pivpn debug to point at the FAQ, and here’s one example when someone has actually read the [FAQ](https://github.com/pivpn/pivpn/wiki/FAQ), such that the issue was quickly [resolved](https://github.com/pivpn/pivpn/issues/944).

> It is through pihole, PiVPN, wireguard and several other projects that I have learned so much about how all of these things work. At the time I didn’t know that the switch in pihole was just changing something in the dnsmasq config file. I know that now, and it would be reasonable to just change the config file.

PiVPN and Pi-hole are great to get started but like all abstractions, If you have problems and you don’t know the inner working, It might be hard to fix. I understand that most beginners are “scared” of the VPN term and want a tutorial about anything, to feel comfortable. Or they are simply tinkering with they Pi and learning. So @richie510 I’m not 100% blaming the individual.

> I would hope that PiVPN at the very least can educate the user that if they have made poor decisions in their dnsmasq settings, that the installer could break their pihole setup, and educate them on how they could fix it after the fact.

The intent was actually not to break the installer, I didn’t now that setting all interfaces + interface=wg0 would have “broken” dnsmasq. I think I will add [this](https://github.com/pivpn/pivpn/issues/946#issuecomment-585485382) check and explain the reasons in the [FAQ](https://github.com/pivpn/pivpn/wiki/WireGuard#how-do-i-use-pi-hole-with-pivpn).

**Comment by orazioedoardo** [comment]
Done: https://github.com/pivpn/pivpn/commit/87cf243abca687b680849de0fbead48c6b6e325d. Now if you have "Listen on all interfaces" the script won't add the line `interface=[...]`.

**Comment by richie510** [comment]
@orazioedoardo please continue to forgive my ignorance... 

I would like to test the fix you made. The only way I can see to do it is to copy down the script from the testing branch and run that locally. Is there a better way?

**Comment by orazioedoardo** [comment]
@richie510 According to [this](https://pivpn.io) or [this](https://github.com/pivpn/pivpn/wiki#testing), to use the test branch, just run `curl -L https://test.pivpn.io | TESTING= bash`. If you do it on your pi, choose 'Reconfigure' (will reinstall PiVPN).

**Comment by richie510** [comment]
I can confirm it work well now with my setup. Thank you @orazioedoardo

**Comment by dschaper** [comment]
Will this address the situation where a user changes the Listen All via the Pi-hole web interface?

**Comment by orazioedoardo** [comment]
Do you mean a situation where a user changes the listening behavior before installing pivpn or after? If you mean before, it should have been addressed:
- **Listen only on interface something**: create file `/etc/dnsmasq.d/02-pivpn.conf` with `interface=tun0` inside.
- **Listen on all interfaces** or **Listen on all interfaces, permit all origins**: don't create the file.

Here's the section: https://github.com/pivpn/pivpn/blob/e73f274fca692f40f7aa83d3931dc43257da5a54/auto_install/install.sh#L1441-L1475

**Comment by dschaper** [comment]
After. The interface can be toggled to a few different states via the Pi-hole Admin interface so the state of that configuration section isn't a one-time setting.

**Comment by orazioedoardo** [comment]
> After. The interface can be toggled to a few different states via the Pi-hole Admin interface so the state of that configuration section isn't a one-time setting.

State change after installation can’t be detected as there is no pivpn daemon or something like that. At best we could point out the inconsistency (and others) if the user runs the debug script.

**Comment by dschaper** [comment]
It's not an easy situation, I agree. At this point when users come to us to tell us that Pi-hole is no longer listening to their needed network interfaces the only real option we have for fixing it is to have users remove `/etc/dnsmasq.d/02-pivpn.conf`. It may not be the best solution but it's really the only one we have right now.

**Comment by orazioedoardo** [comment]
@dschaper I've changed the Pi-hole opt-in to run `pihole -a -i all` instead of adding `interface=wg0` in the config https://github.com/pivpn/pivpn/commit/5b2bc9ba70a24250246da8c942a31e123a431096
