### ISSUE TITLE
[BUG] Upgraded PiVPN breaks Pi-Hole DNS resolution completely (Wireguard/OpenVPN)

### ISSUE THREAD

**Issue by mx2k** [pivpn/pivpn#948]
Maybe related to https://github.com/pivpn/pivpn/issues/946

**Describe the bug**
Installing PiVPN with WireGuard completely breaks PiHole name resolution

- I was running a working PiVPN with OpenVPN on my Pi-Hole. 
- The Pi-Hole is running unbound as per https://docs.pi-hole.net/guides/unbound/
- The OpenVPN config has been edited to allow forwarding through ufw as per https://www.digitalocean.com/community/tutorials/how-to-set-up-an-openvpn-server-on-ubuntu-16-04#step-8-adjust-the-server-networking-configuration
- The PiVPN scripts were old (not including -backup and -update switches), something from early 2018.
- To upgrade PiVPN, I followed the FAQ
- `pivpn uninstall` to remove the old scripts. I have kept the installed packages like OpenVPN etc. to maybe reuse them after reinstallation.
- Once PiVPN was uninstalled, Pi-Hole was still working.
- Then I run the installer again `curl -L https://install.pivpn.io | bash` and select WireGuard during setup. So far, it seems working properly.
- **Once Wireguard is installed and it asks me to reboot, that is the moment when Pi-Hole name resolution completely stops.** 
- **Tail pihole-FTL.log doesn't show any DNS requests anymore. Any website I try I get ERR_NAME_NOT_RESOLVED.**
- After rebooting the system, DNS resolution still doesn't work.
- Using SSH, I noticed the hostname of PiHole/PiVPN is different. It was `rpi-dnshole.fritz.box`. Now it is `rpi-dnshole.local`. Maybe that is related to things not working?
- DNS resolution only starts working after I remove PiVPN again and reboot the system without PiVPN installed.
- I walked through the system logs of my Raspi. There is no indication of any failed services from PiHole or PiVPN or unbound. No idea what might be the cause that breaks the DNS.

**To Reproduce**

- Uninstall old PiVPN scripts configured for OpenVPN
- DNS resolution still working
- Reinstall PiVPN selecting Wireguard
- DNS resolution breaks after setup/reboot.
- DNS resolution stays broken until I run the PiVPN uninstall again
- Once booted without PiVPN/Wireguard, DNS resolution works again.
- I have repeated this 3 times now with always the same result of DNS breaking.

**Expected behavior**
- A straightforward working Wireguard VPN, as it happened flawlessly with the initial/1st installation of PiVPN using OpenVPN in 2018. (Back then, no Wireguard support was available) 

**Additional Info**
- Now I'm checking if the same applies when I try to reinstall with OpenVPN. I will update this issue with the results.
- Is there any other way to update the installed PiVPN scripts without uninstalling them first? Maybe a git pull etc?

## In raising this issue, I confirm the following: 

- [x] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

**Comment by mx2k** [comment]
Now I have tested to reinstall OpenVPN, with the same result.

Installation:

```
Adding system user `openvpn' (UID 115) ...
Adding new group `openvpn' (GID 119) ...
Adding new user `openvpn' (UID 115) with group `openvpn' ...
Creating home directory `/var/lib/openvpn/' ...
::: Install Complete...
::: Restarting services...
  [✓] Restarting DNS service
:::    Checking for unattended-upgrades... already installed!
:::
::: Installing scripts to /opt/pivpn...
 done.
::: Flushing writes to disk...
::: done.
:::
```
The DNS resolution breaks exactly when `[✓] Restarting DNS service` happens.

Uninstallation:
```
::: Preparing to remove packages, be sure that each may be safely removed depending on your operating system.
::: (SAFE TO REMOVE ALL ON RASPBIAN)
::: Do you wish to completely remove PiVPN configuration and installed packages from your system? (You will be prompted for each package) [y/n]: y
::: Stopping and disabling services...
::: Removing firewall rules...
net.ipv6.conf.all.use_tempaddr = 0
net.ipv6.conf.default.use_tempaddr = 0
::: Purge dependencies...
::: Do you wish to remove grepcidr from your system? [Y/n]: n
:::     Skipping grepcidr
::: Auto removing remaining dependencies...done!
::: Auto cleaning remaining dependencies...done!
:::
::: Removing pivpn system files...
  [✓] Restarting DNS service
:::
::: Removing VPN configuration files...
:::
::: Finished removing PiVPN from your system.

```

The DNS resolution starts working again exactly the moment `[✓] Restarting DNS service` happens

**Comment by mx2k** [comment]
Issue https://github.com/pivpn/pivpn/issues/946 contains the fix in testing branch.
It was related to setting `interface=` despite listen on all interfaces was configured.
Please integrate it from testing to main branch asap.

**Comment by 4s3ti** [comment]
> Please integrate it from testing to main branch asap.

Please refrain from this kind of comments in the future! 

We are no ones employee other than our daily IRL Jobs!

In case you don't know ... this is what you should have read: https://github.com/pivpn/pivpn#please-read-carefully-the-issue-template-and-the-contributors-guide-we-will-close-all-incomplete-issue-templates

**Comment by mx2k** [comment]
> Please integrate it from testing to main branch asap.
> 
> Please refrain from this kind of comments in the future!
> 
> We are no ones employee other than our daily IRL Jobs!

Sorry, didn't mean to be rude or anything. Just hoping the fix is integrated soon. Seems pulling up "asap" was the wrong wording to use at all. I also do all my IT stuff as hobbi when I find time, sorry for bothering or confusion caused. At least I learned the required workaround from your posts, to not use testing at all and get it main branch working properly anyways by manually editing the "interface=" line.


> In case you don't know ... this is what you should have read: https://github.com/pivpn/pivpn#please-read-carefully-the-issue-template-and-the-contributors-guide-we-will-close-all-incomplete-issue-templates

Now where am I supposed to find that? I read all the Wiki and FAQ, but neither contained the above doc. That documentation would have really been helpful, now that I read it..

**Comment by orazioedoardo** [comment]
> Now where am I supposed to find that? I read all the Wiki and FAQ, but neither contained the above doc. That documentation would have really been helpful, now that I read it.

It's literally in the readme of the main github page: https://github.com/pivpn/pivpn

**Comment by mx2k** [comment]
[Please Review the FAQ>Upgrading](https://github.com/pivpn/pivpn/wiki/Upgrading)

The info there seems outdated. 

> It still says "How do we Upgrade PiVPN
> A: You don't
> The only supported way to ensure you are on the latest scripts is to run the uninstaller, `pivpn uninstall` then run the installer again  `curl -L https://install.pivpn.io | bash`

- On the upgrading FAQ page, there is no reference to the `-up` switch included in newer script versions for updating scripts, so the above described solutions seems obsolete. Since the -up parameter updates the scripts without error.
- `pivpn uninstall` is not necessarily required. Just running the install script  `curl -L https://install.pivpn.io | bash` on an active PiVPN installation gives you options `Uninstall, Reconfigure, Reinstall` as modifiers for the detected installation.

Maybe this could be considered as an input to an upcoming review/edit of the FAQ section.
