### ISSUE TITLE
[Support] <Dyn DNS>

### ISSUE THREAD

**Issue by onechok** [pivpn/pivpn#949]
Bonjour,
Tout fonctionne avec l'adresse ip public mes pas avec le domaine je ne comprend pas, j'ai un routeur asus RT-AC66U pour faire du vpn ça fonctionne bien avec le nom de domaine,

j'ai testé tout les configuration possible je n'arrive pas a me connecté avec le domaine
pourtant avec l'ancienne version tout fonctionné correctement :)

Merci Quentin

**Comment by 4s3ti** [comment]
Closing... 
shouldn't even need to justify myself but here it goes: 

1 - French... 
2 - No issue template

you can start with this: https://github.com/pivpn/pivpn/blob/master/README.md
