### ISSUE TITLE
[Support] Bullseye support

### ISSUE THREAD

**Issue by flaker** [pivpn/pivpn#952]
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

### Issue

I see a reference for Bullseye here (https://github.com/pivpn/pivpn/issues/8) but I am not sure if this landed and it's working.

The script seems to be moving forward until after selecting my user and Wireguard. The output stops like this:
```
::: Updating package cache...
:::    Checking for linux-headers-amd64... not installed!
:::    Checking for qrencode... already installed!
:::    Checking for wireguard... already installed!
:::    Checking for wireguard-tools... already installed!
:::    Checking for wireguard-dkms... already installed!
:::    Failed to install linux-headers-amd64!
```
I do have the module already built since I have a manually setup Wireguard configuration that I was planning to erase.

Also, some extra info:
```
pi@raspberrypi:~ $ sudo apt list --installed|grep header

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

raspberrypi-kernel-headers/testing,now 1.20200212-1 armhf [installed]


pi@raspberrypi:~ $ uname -a
Linux raspberrypi 4.19.97-v7+ #1294 SMP Thu Jan 30 13:15:58 GMT 2020 armv7l GNU/Linux
pi@raspberrypi:~ $ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux bullseye/sid"
NAME="Debian GNU/Linux"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
### Have you searched for similar issues and solutions?
    yes

### Console output of      `curl -L install.pivpn.dev | bash`
```
:::
::: sudo will be used for the install.
::: Did not detect perfectly supported OS but,
::: Continuing installation at user's own risk...
::: Hostname length OK
::: Verifying free disk space...
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: Your system is up to date! Continuing with PiVPN installation...
:::    Checking for git... already installed!
:::    Checking for tar... already installed!
:::    Checking for wget... already installed!
:::    Checking for curl... already installed!
:::    Checking for grep... already installed!
:::    Checking for dnsutils... already installed!
:::    Checking for whiptail... already installed!
:::    Checking for net-tools... already installed!
:::    Checking for bsdmainutils... already installed!
:::    Checking for iptables-persistent... already installed!
::: Using User: pi
:::
::: Checking for existing base files...
:::    Checking /etc/.pivpn is a repo... OK!
:::     Updating repo in /etc/.pivpn... done!
::: Using VPN: WireGuard
::: Installing WireGuard from Debian package...
::: Updating package cache...
:::    Checking for linux-headers-amd64... not installed!
:::    Checking for qrencode... already installed!
:::    Checking for wireguard... already installed!
:::    Checking for wireguard-tools... already installed!
:::    Checking for wireguard-dkms... already installed!
:::    Failed to install linux-headers-amd64!
```

### Console output of      `pivpn add` or `pivpn add nopass`
```
  Output Here
```

### Console output of      `pivpn debug`
```
  Output Here
```
### Have you taken any steps towards solving your issue?

Took a look at the script and it seems to be taking the path to Debian and trying to install `linux-headers-amd64`. Replaced that to install  `raspberrypi-kernel-headers` and it moved along. Of course it's not a real solution.

**Comment by 4s3ti** [comment]
has bullseye been officially release already? 

as per this there is still no release date: https://www.debian.org/releases/

**Comment by orazioedoardo** [comment]
> Took a look at the script and it seems to be taking the path to Debian and trying to install linux-headers-amd64. Replaced that to install raspberrypi-kernel-headers and it moved along. Of course it's not a real solution.

If this is all you had to do, than it’s a good solution. It takes the Debian path because it found _Debian_ inside `/etc/os-release`.

**Comment by orazioedoardo** [comment]
No answer in a while, closing...
