### ISSUE TITLE
Don't use default gateway

### ISSUE THREAD

**Issue by nexusle** [pivpn/pivpn#953]
What is to do to NOT change the Host-Default-Gateway?? I use OpenVPN in companies notebook. When OpenVPN is in use, the default gateway is changed and I cannot reach my local machines anymore.

**Comment by orazioedoardo** [comment]
Saving you two clicks to the Wiki: https://github.com/pivpn/pivpn/wiki/OpenVPN#how-do-i-allow-clients-access-to-my-home-network-but-not-the-internet-through-my-pivpn

Closing as not following the issue template.

**Comment by nexusle** [comment]
Sure. Nice. That I had found. But now I only can reach my host machine (means 192.168.1.3 (it's the ovpnserver)), not all other machine. Config is this:

dev tun
proto udp
port 1194
ca /etc/openvpn/easy-rsa/pki/ca.crt
cert /etc/openvpn/easy-rsa/pki/issued/raspberrypi_756776fd-ed1c-4722-a60a-3685058eb654.crt
key /etc/openvpn/easy-rsa/pki/private/raspberrypi_756776fd-ed1c-4722-a60a-3685058eb654.key
dh /etc/openvpn/easy-rsa/pki/dh2048.pem
topology subnet
server 192.168.10.0 255.255.255.0
# Set your primary domain name server address for clients
push "dhcp-option DNS 192.168.10.1"
push "block-outside-dns"
# Override the Client default gateway by using 0.0.0.0/1 and
# 128.0.0.0/1 rather than 0.0.0.0/0. This has the benefit of
# overriding but not wiping out the original default gateway.
#push "redirect-gateway def1"
push "route 192.168.1.0 255.255.255.0"
#push "route 192.168.2.0 255.255.255.0"
#push "route 192.168.178.0 255.255.255.0"
client-to-client
keepalive 15 120
remote-cert-tls client
tls-version-min 1.2
tls-auth /etc/openvpn/easy-rsa/pki/ta.key 0
cipher AES-256-CBC
auth SHA256
user openvpn
group openvpn
persist-key
persist-tun
crl-verify /etc/openvpn/crl.pem
status /var/log/openvpn-status.log 20
status-version 3
syslog
verb 3
#DuplicateCNs allow access control on a less-granular, per user basis.
#Remove # if you will manage access by user instead of device. 
#duplicate-cn
# Generated for use by PiVPN.io

**Comment by orazioedoardo** [comment]
You changed the VPN subnet from 10.8.0.0/24 to 192.168.10.0/24. What’s your NAT tables: `sudo iptables -t nat -S`?

**Comment by nexusle** [comment]
Ah ok, that's the error...

-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT
-A POSTROUTING -s 10.8.0.0/24 -o eth0 -m comment --comment openvpn-nat-rule -j MASQUERADE

How to change this? Because our company have the 10.8.0.0/24 network too

**Comment by orazioedoardo** [comment]
```
sudo -s
iptables -t nat - D POSTROUTING -s 10.8.0.0/24 -o eth0 -m comment --comment openvpn-nat-rule -j MASQUERADE
iptables -t nat - I POSTROUTING 1 -s 192.168.10.0/24 -o eth0 -m comment --comment openvpn-nat-rule -j MASQUERADE
exit
```

Please post cose inside the code blocks, otherwise is hard to read.

**Comment by nexusle** [comment]
Thank you!! That did it :-)

Great support
