### ISSUE TITLE
No connection over Wi-Fi 

### ISSUE THREAD

**Issue by Hesi-Re** [pivpn/pivpn#954]
I just installed a fresh copy of Raspbian lite with PiVPN. I opened a port for vpn server in my router. I can connect with 3G but not with WiFi. I tested with different routers and with openvpn and wireguard but with the same result.

**Comment by orazioedoardo** [comment]
Closing as not following the issue template: https://github.com/pivpn/pivpn/issues/951#issuecomment-586625973
