### ISSUE TITLE
[Support] Android client does not connect after PiVPN reinstall.

### ISSUE THREAD

**Issue by 4k3or3et** [pivpn/pivpn#955]
Hi All

i removed and reinstalled PiVPN to Feb 17th 2020 changelog.

Now i have an issue where Andoid client does not want to connect to my RPi where i have OpenVPN server set using PiVPN.

If i try that particular newly generated .ovpn profile on PC with Windows 10 and OpenVPN GUI software it connects fine.

Android has the latest version of OpenVPN app.

I did also pivpn -d to debug. Here is what i get:

`tls-crypt unwrap error: packet authentication failed,
TLS Error: tls-crypt unwrapping failed from [AF_INET]REDACTED:6988`

Before updating PiVPN to newest version that same Android client could connect with no issues with old .ovpn profile...

Anybody could help me to start troubleshooting?

Thank you.

**Comment by 4k3or3et** [comment]
I figured this out. In server config and in .ovpn profiles you have to change tls-crypt to tls-auth. Less secure but Android app works then...

**Comment by orazioedoardo** [comment]
OpenVPN Connect should support tls-crypt though: https://openvpn.net/faq/does-openvpn-connect-support-the-tls-crypt-option/

**Comment by billsteiner** [comment]
Using this install curl -L https://install.pivpn.io | bash and using all the defaults why do I still get the error message?
