### ISSUE TITLE
Select OpenVPN in install menu

### ISSUE THREAD

**Issue by vikdb** [pivpn/pivpn#956]
Hi,

I feel a bit stupid for asking, but i cant seem to select openvpn instead of wireguard on the install menu.

You have to choose between them but i cant move the '*' to openvpn.. 

What am i doing wrong here? When i press enter when the red marker is on openvpn it starts installing wireguard :/

**Comment by orazioedoardo** [comment]
> What am i doing wrong here? When i press enter when the red marker is on openvpn it starts installing wireguard :/

The dialog tells you to press space to select your choice: https://github.com/pivpn/pivpn/blob/e73f274fca692f40f7aa83d3931dc43257da5a54/auto_install/install.sh#L1027

**Comment by vikdb** [comment]
Lets test it tonight but i'm pretty sure i did that

**Comment by 4s3ti** [comment]
That gotta be something on your side ... 
otherwise we would have noticed, and looooot more users would have complained about that ... 
most likely somethin you are doing wrong, or something wrong with your setup.
