### ISSUE TITLE
issue with running pivpn two instances on udp/tcp on same port

### ISSUE THREAD

**Issue by vincentkenny01** [pivpn/pivpn#959]
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*.
- [] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

### Issue
So I wrote this guide a while back on how to run multiple instances on pivpn on same and different ports with udp/tcp for load balancing https://github.com/pivpn/pivpn/issues/178 

I am running two server.conf with tcp and udp on same port as per my guide before.

However I have recently updated PI to buster and re-installed the pivpn and something does not seem to be working as I can connect on tcp and udp on port 443 but the data only comes through tcp but not udp. Not much has changed in terms of router/firewall or raspberry pi itself except that it is a fresh install of raspbian and pivpn etc. 

I am using android openvpn app to connect and below you can see the two screenshots. What I can only make out is that tcp connects fine but udp does not and for some reason if you look at tcp screenshot, the openvpn client shows the android ip address and it seems to be missing on the udp version. Now I don't know if something has changed the way pivpn creates its server files where a copy/paste of same file and changing tcp to udp and giving new subnet range does not work or it is the android openvpn app that has some bug or is it the Android 10 that has stopped udp from working. It seems to connect fine but no data comes through. very odd....happy to paste any screenshots, logs etc. if someone can troubleshoot this with me.

### Have you searched for similar issues and solutions?
    (yes/no / which issues?)
yes

### Have you taken any steps towards solving your issue?
```
 I have re-installed pivpn and also created other copies of the server.conf to replicate the issue.
```
![Screenshot_20200220-134714_OpenVPN for Android](https://user-images.githubusercontent.com/9219050/74941597-3633b600-53eb-11ea-83e6-5fce7c231fb8.jpg)
![Screenshot_20200220-134727_OpenVPN for Android](https://user-images.githubusercontent.com/9219050/74941612-3af86a00-53eb-11ea-85c5-00ebfb265571.jpg)

**Comment by vincentkenny01** [comment]
ok, i have figured out how to make it work as the way the pivpn now creates folder structure there needs to be an additional change in one of the files. I will update the original guide accordingly. It will be good to if pivpn folder/file structure changes are published alongside with updates. Thanks

**Comment by orazioedoardo** [comment]
What change in the directory structure required you to update the guide?

**Comment by DawaLaw** [comment]
> What change in the directory structure required you to update the guide?

@orazioedoardo 

Can you try this?
1. Go to `/etc/openvpn/ccd`
2. run `ls` to see all ovpn profile name.
3. run `sudo mv <ovpn file> <ovpn file>.bak` for the ovpn profile that you would like to test out.
4. Then retry connecting via UDP 1194 again.
