### ISSUE TITLE
[Support] syslog is filled with openvpn errors but pivpn clients and connections work fine.

### ISSUE THREAD

**Issue by vincentkenny01** [pivpn/pivpn#964]
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

### 
I am trying to run udp and tcp on same port 443. both my tcp and udp clients can connect and receive data- no issues with the connections but syslog is getting filled like crazy as per below.

I have pasted my syslog error file below but it appears that system keeps trying to open each server.conf and it fails due to some error. 

Feb 26 13:41:42 raspberrypi systemd[1]: Starting OpenVPN connection to server.conf...
Feb 26 13:41:42 raspberrypi ovpn-serverudp.conf[858]: Options error: In [CMD-LINE]:1: Error opening configuration file: /etc/openvpn/serverudp.conf.conf
Feb 26 13:41:42 raspberrypi ovpn-serverudp.conf[858]: Use --help for more information.
Feb 26 13:41:42 raspberrypi ovpn-server.conf[859]: Options error: In [CMD-LINE]:1: Error opening configuration file: /etc/openvpn/server.conf.conf
Feb 26 13:41:42 raspberrypi ovpn-server.conf[859]: Use --help for more information.
Feb 26 13:41:42 raspberrypi systemd[1]: openvpn@serverudp.conf.service: Main process exited, code=exited, status=1/FAILURE
Feb 26 13:41:42 raspberrypi systemd[1]: openvpn@serverudp.conf.service: Failed with result 'exit-code'.
Feb 26 13:41:42 raspberrypi systemd[1]: Failed to start OpenVPN connection to serverudp.conf.
Feb 26 13:41:42 raspberrypi systemd[1]: openvpn@server.conf.service: Main process exited, code=exited, status=1/FAILURE
Feb 26 13:41:42 raspberrypi systemd[1]: openvpn@server.conf.service: Failed with result 'exit-code'.
Feb 26 13:41:42 raspberrypi systemd[1]: Failed to start OpenVPN connection to server.conf.
Feb 26 13:41:47 raspberrypi systemd[1]: openvpn@serverudp.conf.service: Service RestartSec=5s expired, scheduling restart.
Feb 26 13:41:47 raspberrypi systemd[1]: openvpn@serverudp.conf.service: Scheduled restart job, restart counter is at 20.
Feb 26 13:41:47 raspberrypi systemd[1]: openvpn@server.conf.service: Service RestartSec=5s expired, scheduling restart.
Feb 26 13:41:47 raspberrypi systemd[1]: openvpn@server.conf.service: Scheduled restart job, restart counter is at 20.
Feb 26 13:41:47 raspberrypi systemd[1]: Stopped OpenVPN connection to server.conf.
Feb 26 13:41:47 raspberrypi systemd[1]: Starting OpenVPN connection to server.conf...
Feb 26 13:41:47 raspberrypi systemd[1]: Stopped OpenVPN connection to serverudp.conf.
Feb 26 13:41:47 raspberrypi systemd[1]: Starting OpenVPN connection to serverudp.conf...
Feb 26 13:41:47 raspberrypi ovpn-server.conf[864]: Options error: In [CMD-LINE]:1: Error opening configuration file: /etc/openvpn/server.conf.conf
Feb 26 13:41:47 raspberrypi ovpn-server.conf[864]: Use --help for more information.
Feb 26 13:41:48 raspberrypi systemd[1]: openvpn@server.conf.service: Main process exited, code=exited, status=1/FAILURE
Feb 26 13:41:48 raspberrypi systemd[1]: openvpn@server.conf.service: Failed with result 'exit-code'.
Feb 26 13:41:48 raspberrypi systemd[1]: Failed to start OpenVPN connection to server.conf.
Feb 26 13:41:48 raspberrypi ovpn-serverudp.conf[865]: Options error: In [CMD-LINE]:1: Error opening configuration file: /etc/openvpn/serverudp.conf.conf
Feb 26 13:41:48 raspberrypi ovpn-serverudp.conf[865]: Use --help for more information.
Feb 26 13:41:48 raspberrypi systemd[1]: openvpn@serverudp.conf.service: Main process exited, code=exited, status=1/FAILURE
Feb 26 13:41:48 raspberrypi systemd[1]: openvpn@serverudp.conf.service: Failed with result 'exit-code'.
Feb 26 13:41:48 raspberrypi systemd[1]: Failed to start OpenVPN connection to serverudp.conf.

### Have you searched for similar issues and solutions?
    (yes/no / which issues?)

### Console output of      `curl -L install.pivpn.dev | bash`
```
  Output Here
```

### Console output of      `pivpn add` or `pivpn add nopass`
```
  Output Here
```

### Console output of      `pivpn debug`
```

pi@raspberrypi:~ $ pivpn -d
::: Generating Debug Output
::::            PiVPN debug              ::::
=============================================
::::            Latest commit            ::::
commit e73f274fca692f40f7aa83d3931dc43257da5a54
Author: Orazio <orazioedoardo@users.noreply.github.com>
Date:   Mon Feb 17 16:34:07 2020 +0100

    Update LatestUpdate.md
=============================================
::::        Installation settings        ::::
PLAT=Raspbian
OSCN=buster
USING_UFW=0
IPv4dev=wlan0
dhcpReserv=1
IPv4addr=192.168.0.13/24
IPv4gw=192.168.0.1
install_user=pi
install_home=/home/pi
VPN=openvpn
pivpnDEV=tun0
pivpnNET=10.8.0.0
subnetClass=24
pivpnPROTO=tcp
pivpnPORT=443
pivpnDNS1=10.8.0.1
pivpnDNS2=
pivpnSEARCHDOMAIN=
pivpnHOST=REDACTED
TWO_POINT_FOUR=1
pivpnENCRYPT=256
USE_PREDEFINED_DH_PARAM=0
INPUT_CHAIN_EDITED=0
FORWARD_CHAIN_EDITED=0
UNATTUPG=0
INSTALLED_PACKAGES=(iptables-persistent openvpn grepcidr expect)
HELP_SHOWN=1
=============================================
::::  Server configuration shown below   ::::
dev tun
proto tcp
port 443
ca /etc/openvpn/easy-rsa/pki/ca.crt
cert /etc/openvpn/easy-rsa/pki/issued/raspberrypi_06697edf-c4d9-47bc-8569-50b2b9c0e446.crt
key /etc/openvpn/easy-rsa/pki/private/raspberrypi_06697edf-c4d9-47bc-8569-50b2b9c0e446.key
dh none
ecdh-curve prime256v1
topology subnet
server 10.8.0.0 255.255.255.0
# Set your primary domain name server address for clients
push "dhcp-option DNS 192.168.0.13"
push "block-outside-dns"
# Override the Client default gateway by using 0.0.0.0/1 and
# 128.0.0.0/1 rather than 0.0.0.0/0. This has the benefit of
# overriding but not wiping out the original default gateway.
push "redirect-gateway def1"
client-to-client
client-config-dir /etc/openvpn/ccd
keepalive 15 120
remote-cert-tls client
tls-version-min 1.2
tls-crypt /etc/openvpn/easy-rsa/pki/ta.key
cipher AES-256-CBC
auth SHA256
user openvpn
group openvpn
persist-key
persist-tun
crl-verify /etc/openvpn/crl.pem
status /var/log/openvpn-status.log 20
status-version 3
syslog
verb 3
#DuplicateCNs allow access control on a less-granular, per user basis.
#Remove # if you will manage access by user instead of device.
#duplicate-cn
# Generated for use by PiVPN.io
=============================================
::::  Client template file shown below   ::::
client
dev tun
proto tcp
remote REDACTED 443
resolv-retry infinite
nobind
remote-cert-tls server
tls-version-min 1.2
verify-x509-name raspberrypi_06697edf-c4d9-47bc-8569-50b2b9c0e446 name
cipher AES-256-CBC
auth SHA256
auth-nocache
verb 3
=============================================
::::    Recursive list of files in       ::::
::: /etc/openvpn/easy-rsa/pki shows below :::
/etc/openvpn/easy-rsa/pki/:
ca.crt
crl.pem
Default.txt
ecparams
extensions.temp
index.txt
index.txt.attr
index.txt.attr.old
index.txt.old
issued
openssl-easyrsa.cnf
private
renewed
revoked
safessl-easyrsa.cnf
serial
serial.old
ta.key
tcp1.ovpn
udp1.ovpn

/etc/openvpn/easy-rsa/pki/ecparams:
prime256v1.pem

/etc/openvpn/easy-rsa/pki/issued:
raspberrypi_06697edf-c4d9-47bc-8569-50b2b9c0e446.crt
tcp1.crt
udp1.crt

/etc/openvpn/easy-rsa/pki/private:
ca.key
raspberrypi_06697edf-c4d9-47bc-8569-50b2b9c0e446.key
tcp1.key
udp1.key

/etc/openvpn/easy-rsa/pki/renewed:
private_by_serial
reqs_by_serial

/etc/openvpn/easy-rsa/pki/renewed/private_by_serial:

/etc/openvpn/easy-rsa/pki/renewed/reqs_by_serial:

/etc/openvpn/easy-rsa/pki/revoked:
private_by_serial
reqs_by_serial

/etc/openvpn/easy-rsa/pki/revoked/private_by_serial:

/etc/openvpn/easy-rsa/pki/revoked/reqs_by_serial:
=============================================
::::            Self check               ::::
:: [OK] IP forwarding is enabled
:: [OK] Iptables MASQUERADE rule set
:: [OK] OpenVPN is running
:: [OK] OpenVPN is enabled (it will automatically start on reboot)
:: [OK] OpenVPN is listening on port 443/tcp
=============================================
:::: Having trouble connecting? Take a look at the FAQ:
:::: https://github.com/pivpn/pivpn/wiki/FAQ
=============================================
::::      Snippet of the server log      ::::
Feb 26 13:39:25 raspberrypi ovpn-server[518]: ECDH curve prime256v1 added
Feb 26 13:39:25 raspberrypi ovpn-server[518]: Outgoing Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Feb 26 13:39:25 raspberrypi ovpn-server[518]: Outgoing Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Feb 26 13:39:25 raspberrypi ovpn-server[518]: Incoming Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Feb 26 13:39:25 raspberrypi ovpn-server[518]: Incoming Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Feb 26 13:39:25 raspberrypi ovpn-server[518]: TUN/TAP device tun0 opened
Feb 26 13:39:25 raspberrypi ovpn-server[518]: TUN/TAP TX queue length set to 100
Feb 26 13:39:25 raspberrypi ovpn-server[518]: /sbin/ip link set dev tun0 up mtu 1500
Feb 26 13:39:25 raspberrypi ovpn-server[518]: /sbin/ip addr add dev tun0 10.8.0.1/24 broadcast 10.8.0.255
Feb 26 13:39:25 raspberrypi ovpn-server[518]: Could not determine IPv4/IPv6 protocol. Using AF_INET
Feb 26 13:39:25 raspberrypi ovpn-server[518]: Socket Buffers: R=[131072->131072] S=[16384->16384]
Feb 26 13:39:25 raspberrypi ovpn-server[518]: Listening for incoming TCP connection on [AF_INET][undef]:443
Feb 26 13:39:25 raspberrypi ovpn-server[518]: TCPv4_SERVER link local (bound): [AF_INET][undef]:443
Feb 26 13:39:25 raspberrypi ovpn-server[518]: TCPv4_SERVER link remote: [AF_UNSPEC]
Feb 26 13:39:25 raspberrypi ovpn-server[518]: GID set to openvpn
Feb 26 13:39:25 raspberrypi ovpn-server[518]: UID set to openvpn
Feb 26 13:39:25 raspberrypi ovpn-server[518]: MULTI: multi_init called, r=256 v=256
Feb 26 13:39:25 raspberrypi ovpn-server[518]: IFCONFIG POOL: base=10.8.0.2 size=252, ipv6=0
Feb 26 13:39:25 raspberrypi ovpn-server[518]: MULTI: TCP INIT maxclients=1024 maxevents=1028
Feb 26 13:39:25 raspberrypi ovpn-server[518]: Initialization Sequence Completed
=============================================
::::            Debug complete           ::::
:::
::: Debug output completed above.
::: Copy saved to /tmp/debug.txt

```
### Have you taken any steps towards solving your issue?
```
  which?
```

**Comment by orazioedoardo** [comment]
Output of `ls -lR /etc/openvpn`?

**Comment by vincentkenny01** [comment]
Below is the output pi@raspberrypi:~ $ ls -lR /etc/openvpn/etc/openvpn:total 32drwxr-xr-x 2 root    root    4096 Feb 26 13:24 ccddrwxr-xr-x 2 root    root    4096 Feb 20  2019 client-rw------- 1 openvpn openvpn  378 Feb 26 12:51 crl.pemdrwxrwxr-x 5 root    root    4096 Feb 26 12:51 easy-rsadrwxr-xr-x 2 root    root    4096 Feb 26 13:38 server-rw-r--r-- 1 root    root    1172 Feb 26 13:36 server1.conf-rw-r--r-- 1 root    root    1172 Feb 26 13:17 server.conf-rwxr-xr-x 1 root    root    1468 Feb 20  2019 update-resolv-conf/etc/openvpn/ccd:total 8-rw-r--r-- 1 root root 37 Feb 26 13:08 tcp1-rw-r--r-- 1 root root 37 Feb 26 13:08 udp1/etc/openvpn/client:total 0pi@raspberrypi:~ $ ls -lR /etc/openvpn/etc/openvpn:total 32drwxr-xr-x 2 root    root    4096 Feb 26 13:24 ccddrwxr-xr-x 2 root    root    4096 Feb 20  2019 client-rw------- 1 openvpn openvpn  378 Feb 26 12:51 crl.pemdrwxrwxr-x 5 root    root    4096 Feb 26 12:51 easy-rsadrwxr-xr-x 2 root    root    4096 Feb 26 13:38 server-rw-r--r-- 1 root    root    1172 Feb 26 13:36 server1.conf-rw-r--r-- 1 root    root    1172 Feb 26 13:17 server.conf-rwxr-xr-x 1 root    root    1468 Feb 20  2019 update-resolv-conf/etc/openvpn/ccd:total 8-rw-r--r-- 1 root root 37 Feb 26 13:08 tcp1-rw-r--r-- 1 root root 37 Feb 26 13:08 udp1/etc/openvpn/client:total 0/etc/openvpn/easy-rsa:total 124-rw-rw-r-- 1 root root  3968 Feb  2  2019 ChangeLog-rw-rw-r-- 1 root root  1305 Feb  2  2019 COPYING.mddrwxrwxr-x 2 root root  4096 Feb  2  2019 doc-rwxrwxr-x 1 root root 48730 Feb  2  2019 easyrsa-rw-rw-r-- 1 root root 18093 Feb  2  2019 gpl-2.0.txt-rw-rw-r-- 1 root root  1036 Feb  2  2019 mktemp.txt-rw-rw-r-- 1 root root  4651 Feb  2  2019 openssl-easyrsa.cnfdrwx------ 9 root root  4096 Feb 26 12:52 pki-rw-rw-r-- 1 root root  2039 Feb  2  2019 README.md-rw-rw-r-- 1 root root  3335 Feb  2  2019 README.quickstart.md-rw-r--r-- 1 root root   258 Feb 26 12:51 vars-rw-rw-r-- 1 root root  8576 Feb  2  2019 vars.exampledrwxrwxr-x 2 root root  4096 Feb 26 12:51 x509-types/etc/openvpn/easy-rsa/doc:total 40-rw-rw-r-- 1 root root 5389 Feb  2  2019 EasyRSA-Advanced.md-rw-rw-r-- 1 root root 9562 Feb  2  2019 EasyRSA-Readme.md-rw-rw-r-- 1 root root 2496 Feb  2  2019 EasyRSA-Upgrade-Notes.md-rw-rw-r-- 1 root root 5891 Feb  2  2019 Hacking.md-rw-rw-r-- 1 root root 4923 Feb  2  2019 Intro-To-PKI.mdls: cannot open directory '/etc/openvpn/easy-rsa/pki': Permission denied/etc/openvpn/easy-rsa/x509-types:total 24-rw-rw-r-- 1 root root 426 Feb  2  2019 ca-rw-rw-r-- 1 root root 192 Feb  2  2019 client-rw-rw-r-- 1 root root 193 Feb  2  2019 code-signing-rw-rw-r-- 1 root root 300 Feb  2  2019 COMMON-rw-rw-r-- 1 root root 208 Feb  2  2019 server-rw-rw-r-- 1 root root 226 Feb  2  2019 serverClient/etc/openvpn/server:total 0pi@raspberrypi:~ $
-------- Original message --------From: Orazio <notifications@github.com> Date: 26/02/2020  17:33  (GMT+00:00) To: pivpn/pivpn <pivpn@noreply.github.com> Cc: vincentkenny01 <inkx27@gmail.com>, Author <author@noreply.github.com> Subject: Re: [pivpn/pivpn] [Support] syslog is filled with openvpn errors but pivpn clients and connections work fine. (#964) Output of ls -lR /etc/openvpn?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/pivpn/pivpn/issues/964?email_source=notifications\u0026email_token=ACGKX2WFZ36LONU4OKPITYTRE2RWBA5CNFSM4K4FZO2KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOENBE67A#issuecomment-591548284",
"url": "https://github.com/pivpn/pivpn/issues/964?email_source=notifications\u0026email_token=ACGKX2WFZ36LONU4OKPITYTRE2RWBA5CNFSM4K4FZO2KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOENBE67A#issuecomment-591548284",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by vincentkenny01** [comment]
Update

**Comment by orazioedoardo** [comment]
Please format the output correctly

**Comment by vincentkenny01** [comment]
Linux raspberrypi 4.19.102-v7+ #1295 SMP Thu Feb 6 15:43:59 GMT 2020 armv7l

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Wed Feb 26 18:07:41 2020 from 192.168.0.91
pi@raspberrypi:~ $ ls -lR /etc/openvpn
/etc/openvpn:
total 32
drwxr-xr-x 2 root    root    4096 Feb 26 13:24 ccd
drwxr-xr-x 2 root    root    4096 Feb 20  2019 client
-rw------- 1 openvpn openvpn  378 Feb 26 12:51 crl.pem
drwxrwxr-x 5 root    root    4096 Feb 26 12:51 easy-rsa
drwxr-xr-x 2 root    root    4096 Feb 26 13:38 server
-rw-r--r-- 1 root    root    1172 Feb 26 13:36 server1.conf
-rw-r--r-- 1 root    root    1172 Feb 26 13:17 server.conf
-rwxr-xr-x 1 root    root    1468 Feb 20  2019 update-resolv-conf

/etc/openvpn/ccd:
total 8
-rw-r--r-- 1 root root 37 Feb 26 13:08 tcp1
-rw-r--r-- 1 root root 37 Feb 26 13:08 udp1

/etc/openvpn/client:
total 0

/etc/openvpn/easy-rsa:
total 124
-rw-rw-r-- 1 root root  3968 Feb  2  2019 ChangeLog
-rw-rw-r-- 1 root root  1305 Feb  2  2019 COPYING.md
drwxrwxr-x 2 root root  4096 Feb  2  2019 doc
-rwxrwxr-x 1 root root 48730 Feb  2  2019 easyrsa
-rw-rw-r-- 1 root root 18093 Feb  2  2019 gpl-2.0.txt
-rw-rw-r-- 1 root root  1036 Feb  2  2019 mktemp.txt
-rw-rw-r-- 1 root root  4651 Feb  2  2019 openssl-easyrsa.cnf
drwx------ 9 root root  4096 Feb 26 12:52 pki
-rw-rw-r-- 1 root root  2039 Feb  2  2019 README.md
-rw-rw-r-- 1 root root  3335 Feb  2  2019 README.quickstart.md
-rw-r--r-- 1 root root   258 Feb 26 12:51 vars
-rw-rw-r-- 1 root root  8576 Feb  2  2019 vars.example
drwxrwxr-x 2 root root  4096 Feb 26 12:51 x509-types

/etc/openvpn/easy-rsa/doc:
total 40
-rw-rw-r-- 1 root root 5389 Feb  2  2019 EasyRSA-Advanced.md
-rw-rw-r-- 1 root root 9562 Feb  2  2019 EasyRSA-Readme.md
-rw-rw-r-- 1 root root 2496 Feb  2  2019 EasyRSA-Upgrade-Notes.md
-rw-rw-r-- 1 root root 5891 Feb  2  2019 Hacking.md
-rw-rw-r-- 1 root root 4923 Feb  2  2019 Intro-To-PKI.md
ls: cannot open directory '/etc/openvpn/easy-rsa/pki': Permission denied

/etc/openvpn/easy-rsa/x509-types:
total 24
-rw-rw-r-- 1 root root 426 Feb  2  2019 ca
-rw-rw-r-- 1 root root 192 Feb  2  2019 client
-rw-rw-r-- 1 root root 193 Feb  2  2019 code-signing
-rw-rw-r-- 1 root root 300 Feb  2  2019 COMMON
-rw-rw-r-- 1 root root 208 Feb  2  2019 server
-rw-rw-r-- 1 root root 226 Feb  2  2019 serverClient

/etc/openvpn/server:
total 0
pi@raspberrypi:~ $

**Comment by vincentkenny01** [comment]
Sorry somehow I got the format corrupt on the phone.

**Comment by orazioedoardo** [comment]
So your configurations are inside `server.conf`and `server1.conf` right?

**Comment by vincentkenny01** [comment]
Yes, that's correct. Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Orazio <notifications@github.com> Date: 26/02/2020  19:02  (GMT+00:00) To: pivpn/pivpn <pivpn@noreply.github.com> Cc: vincentkenny01 <inkx27@gmail.com>, Author <author@noreply.github.com> Subject: Re: [pivpn/pivpn] [Support] syslog is filled with openvpn errors but pivpn clients and connections work fine. (#964) So your configurations are inside server.confand server1.conf right?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/pivpn/pivpn/issues/964?email_source=notifications\u0026email_token=ACGKX2X4TC7O26BOSC3PLWLRE24DTA5CNFSM4K4FZO2KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOENBOVIY#issuecomment-591588003",
"url": "https://github.com/pivpn/pivpn/issues/964?email_source=notifications\u0026email_token=ACGKX2X4TC7O26BOSC3PLWLRE24DTA5CNFSM4K4FZO2KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOENBOVIY#issuecomment-591588003",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by orazioedoardo** [comment]
Probably your system is trying to load old configuration from your previous attempts, you can stop and disable them with:
```
sudo systemctl stop openvpn@serverudp.conf.service
sudo systemctl disable openvpn@serverudp.conf.service
sudo systemctl stop openvpn@server.conf.service
sudo systemctl disable @server.conf.service
```

**Comment by vincentkenny01** [comment]
Brilliant. This has stopped all the errors that were getting logged continuously. Thanks a ton. I will close this ticket now. Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Orazio <notifications@github.com> Date: 26/02/2020  19:23  (GMT+00:00) To: pivpn/pivpn <pivpn@noreply.github.com> Cc: vincentkenny01 <inkx27@gmail.com>, Author <author@noreply.github.com> Subject: Re: [pivpn/pivpn] [Support] syslog is filled with openvpn errors but pivpn clients and connections work fine. (#964) Probably your system is trying to load old configuration from your previous attempts, you can stop and disable them with:
sudo systemctl stop openvpn@serverudp.conf.service
sudo systemctl disable openvpn@serverudp.conf.service
sudo systemctl stop openvpn@server.conf.service
sudo systemctl disable @server.conf.service


—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/pivpn/pivpn/issues/964?email_source=notifications\u0026email_token=ACGKX2QWBPXO7NWVM7UYYD3RE26TLA5CNFSM4K4FZO2KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOENBRJ6Q#issuecomment-591598842",
"url": "https://github.com/pivpn/pivpn/issues/964?email_source=notifications\u0026email_token=ACGKX2QWBPXO7NWVM7UYYD3RE26TLA5CNFSM4K4FZO2KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOENBRJ6Q#issuecomment-591598842",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by orazioedoardo** [comment]
Actually the last command was wrong. I edited the comment now.
