### ISSUE TITLE
Install fails please watch my install log

### ISSUE THREAD

**Issue by thundergreen** [pivpn/pivpn#97]
pi@Home-Assistant:~ $ curl -L https://install.pivpn.io | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   178  100   178    0     0    223      0 --:--:-- --:--:-- --:--:--   224
100 37392  100 37392    0     0  38439      0 --:--:-- --:--:-- --:--:--  320k
:::
::: sudo will be used for the install.
::: Using interface: eth0
::: Using User: pi
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: There are 26 updates availible for your pi!
::: We recommend you run 'sudo apt-get upgrade' after installing PiVPN!
:::
:::
::: Checking dependencies:
:::    Checking for openvpn... Not found! Installing.... [|]  E: There are problems and -y was used without --force-yes                                 done!
:::    Checking for easy-rsa... Not found! Installing.... []  E: There are problems and -y was used without --force-yes                                done!
:::    Checking for git... already installed!
:::    Checking for iptables-persistent... Not found! Installing.... [|]  E: There are problems and -y was used without --force-yes                     done!
:::    Checking for dnsutils... already installed!
:::    Checking for expect... Not found! Installing....E: There are problems and -y was used without --force-yes
 done!
:::    Checking for unattended-upgrades... Not found! Installing....E: There are problems and -y was used without --force-yes
 done!
:::
::: Stopping openvpn service...Failed to stop openvpn.service: Unit openvpn.service not loaded.
 done.
sed: can't read /etc/apt/apt.conf.d/50unattended-upgrades: No such file or directory
:::
::: Checking for existing base files...
:::    Checking /etc/.pivpn is a repo... not found!!
:::    Cloning https://github.com/pivpn/pivpn.git into /etc/.pivpn... done!
:::
::: Installing scripts to /opt/pivpn... done.
cp: cannot stat ‘/usr/share/easy-rsa’: No such file or directory
bash: line 617: cd: /etc/openvpn/easy-rsa: No such file or directory
sed: can't read vars: No such file or directory
sed: can't read vars: No such file or directory
sed: can't read vars: No such file or directory
sed: can't read vars: No such file or directory
sed: can't read vars: No such file or directory
sed: can't read vars: No such file or directory
sed: can't read vars: No such file or directory
sed: can't read vars: No such file or directory
sed: can't read vars: No such file or directory
sed: can't read vars: No such file or directory
bash: line 703: ./vars: No such file or directory
sudo: ./clean-all: command not found
::: Building CA...
sudo: ./build-ca: command not found

::: CA Complete.
sudo: ./build-key-server: command not found
sudo: ./build-dh: command not found
sudo: openvpn: command not found
cp: cannot create regular file ‘/etc/openvpn/server.conf’: No such file or directory
sed: can't read /etc/openvpn/server.conf: No such file or directory
sed: can't read /etc/openvpn/server.conf: No such file or directory
sed: can't read /etc/openvpn/server.conf: No such file or directory
sed: can't read /etc/openvpn/server.conf: No such file or directory
net.ipv4.ip_forward = 1
sudo: netfilter-persistent: command not found
cp: cannot create regular file ‘/etc/openvpn/easy-rsa/keys/Default.txt’: No such file or directory
sed: can't read /etc/openvpn/easy-rsa/keys/Default.txt: No such file or directory
sed: can't read /etc/openvpn/easy-rsa/keys/Default.txt: No such file or directory
::: Using OpenDNS servers.
sed: can't read /etc/openvpn/server.conf: No such file or directory
sed: can't read /etc/openvpn/server.conf: No such file or directory
Failed to execute operation: No such file or directory
Failed to start openvpn.service: Unit openvpn.service failed to load: No such file or directory.
::: Install Complete...

**Comment by redfast00** [comment]
It seems `apt` wasn't able to install the `openvpn` package and a bunch of other packages. It might be because you haven't updated in a while (see [here](http://askubuntu.com/a/158824)). Can you reproduce this issue on a fresh install? (If you don't want/can't do a fresh install, can you manually install the required packages with `sudo apt-get install openvpn easy-rsa git iptables-persistent dnsutils expect unattended-upgrades` and try again?)

**Comment by 0-kaladin** [comment]
This could be messed up sdcard as well.  Either way not an inherent failure of pivpn.  Will close.
