### ISSUE TITLE
openvpn tunnel with rpi and xbox one

### ISSUE THREAD

**Issue by pipi111** [pivpn/pivpn#972]
Hi All
I just wonder if is possible to create a vpntunnel between the rpi server and the xbox one 
Now the xbox one doesnt have an app to connect to openvpn 
I want to do this wireless as my console is far from the router
there is a way to do this

**Comment by orazioedoardo** [comment]
Closing as not following the issue template (no information regarding the current PiVPN setup). 

Don't know why your issue got closed? 

You can start by reading here: https://www.pivpn.io/#contrib
And here: https://github.com/pivpn/pivpn/blob/master/README.md
And here: https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md

and the first lines on the issue template that appeared after you have pressed all those green buttons to open up this issue: 

```
<!-- 
# PiVPN Issue Template
PLEASE READ THIS TEMPLATE CAREFULLY BEFORE OPENING AN ISSUE! 
Any Issue opened that doesn't follow this template will be removed.
```

Still not happy? 

Feel free to express yourself but most likely our position won't change, and hopefully you have now learned how to open an issue anywhere in the opensource community! 

Wish you a great day, feel free to reopen this issue but this time make sure it follows the rules!

Also if you have had read the documentation you would find that there is a more appropriate place for this kind of things: https://www.reddit.com/r/pivpn

By the way, if your router has openvpn you could try to setup a PiVPN profile on it and tunnel all traffic though it, so the xbox should be able to see the PiVPN LAN.
