### ISSUE TITLE
 "Failed to import Debian GPG keys" during pivpn installation

### ISSUE THREAD

**Issue by emclab** [pivpn/pivpn#975]
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

./auto_install/install.sh
:::
::: sudo will be used for the install.
::: Hostname length OK
::: Verifying free disk space...
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: Your system is up to date! Continuing with PiVPN installation...
:::    Checking for git... already installed!
:::    Checking for tar... already installed!
:::    Checking for wget... already installed!
:::    Checking for curl... already installed!
:::    Checking for grep... already installed!
:::    Checking for dnsutils... already installed!
:::    Checking for whiptail... already installed!
:::    Checking for net-tools... already installed!
:::    Checking for bsdmainutils... already installed!
:::    Checking for dhcpcd5... already installed!
:::    Checking for iptables-persistent... already installed!
::: Static IP already configured.
::: Using User: pi
:::
::: Checking for existing base files...
:::    Checking /etc/.pivpn is a repo... OK!
:::     Updating repo in /etc/.pivpn... done!
::: Using VPN: WireGuard
::: Installing WireGuard from Debian package...
:::    Checking for dirmngr... already installed!
::: Adding repository keys...
Executing: /tmp/apt-key-gpghome.QOZkFDQmS3/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys 0xe1cf20ddffe4b89e802658f1e0b11894f66aec98 0x80d15823b7fd1561f9f7bcdddc30d7c23cbbabee
gpg: keyserver receive failed: Server indicated a failure
::: Failed to import Debian GPG keys

### Issue
The installation of pivpn failed with the same message with installation Method1 and Method3. 

### Have you searched for similar issues and solutions?
    (yes/no / which issues?)
yes without applicable solution. Repeated the process several times and end with the same error.

### Console output of      `curl -L install.pivpn.dev | bash`
```
See the output above.
```

### Console output of      `pivpn add` or `pivpn add nopass`
```
  Output Here  
```

### Console output of      `pivpn debug`
```
  Output Here
```
### Have you taken any steps towards solving your issue?
```
  which?
```

**Comment by orazioedoardo** [comment]
What's the output of these three commands?
```
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 0xe1cf20ddffe4b89e802658f1e0b11894f66aec98 0x80d15823b7fd1561f9f7bcdddc30d7c23cbbabee
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 0xe1cf20ddffe4b89e802658f1e0b11894f66aec98 0x80d15823b7fd1561f9f7bcdddc30d7c23cbbabee
dig +short keyserver.ubuntu.com
```

**Comment by scorpionx1** [comment]
i get the same error.  output of the five commands above is:
1) 
`Executing: /tmp/apt-key-gpghome.Ey8jTde6Sd/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys 0xe1cf20ddffe4b89e
802658f1e0b11894f66aec98 0x80d15823b7fd1561f9f7bcdddc30d7c23cbbabee
gpg: failed to start the dirmngr '/usr/bin/dirmngr': No such file or directory
gpg: connecting dirmngr at '/tmp/apt-key-gpghome.Ey8jTde6Sd/S.dirmngr' failed: No such file or directory
gpg: keyserver receive failed: No dirmngr`
2)
`Executing: /tmp/apt-key-gpghome.KCC5dFpaHC/gpg.1.sh --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 0xe1cf20d
dffe4b89e802658f1e0b11894f66aec98 0x80d15823b7fd1561f9f7bcdddc30d7c23cbbabee
gpg: failed to start the dirmngr '/usr/bin/dirmngr': No such file or directory
gpg: connecting dirmngr at '/tmp/apt-key-gpghome.KCC5dFpaHC/S.dirmngr' failed: No such file or directory
gpg: keyserver receive failed: No dirmngr`
3)
`162.213.33.8
162.213.33.9`
4)
`keyserver.ubuntu.com [162.213.33.9] 11371 (hkp) open`
5)
`keyserver.ubuntu.com [162.213.33.8] 80 (http) open`

**Comment by kygarys** [comment]
I'm having the same issue however my output from the commands are different than scorpionx, please see below.

`pi@raspberrypi:~ $ curl -L https://install.pivpn.io | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   162  100   162    0     0    246      0 --:--:-- --:--:-- --:--:--   246
100 81925  100 81925    0     0  77507      0  0:00:01  0:00:01 --:--:-- 77507
:::
::: sudo will be used for the install.
::: Hostname length OK
::: Verifying free disk space...
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: Your system is up to date! Continuing with PiVPN installation...
:::    Checking for git... already installed!
:::    Checking for tar... already installed!
:::    Checking for wget... already installed!
:::    Checking for curl... already installed!
:::    Checking for grep... already installed!
:::    Checking for dnsutils... already installed!
:::    Checking for whiptail... already installed!
:::    Checking for net-tools... already installed!
:::    Checking for bsdmainutils... already installed!
:::    Checking for dhcpcd5... already installed!
:::    Checking for iptables-persistent... already installed!
::: Using User: pi
:::
::: Checking for existing base files...
:::    Checking /etc/.pivpn is a repo... OK!
:::     Updating repo in /etc/.pivpn... done!
::: Using VPN: WireGuard
::: Installing WireGuard from Debian package...
:::    Checking for dirmngr... already installed!
::: Adding repository keys...
Executing: /tmp/apt-key-gpghome.2HWElBZPz8/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys 0xe1cf20ddffe4b89e802658f1e0b11894f66aec98 0x80d15823b7fd1561f9f7bcdddc30d7c23cbbabee
gpg: keyserver receive failed: Server indicated a failure
::: Failed to import Debian GPG keys

pi@raspberrypi:~ $ sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 0xe1cf20ddffe4b89e802658f1e0b11894f66aec98 0x80d15823b7fd1561f9f7bcdddc30d7c23cbbabee
Executing: /tmp/apt-key-gpghome.VuDQNayq0o/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys 0xe1cf20ddffe4b89e802658f1e0b11894f66aec98 0x80d15823b7fd1561f9f7bcdddc30d7c23cbbabee
gpg: keyserver receive failed: Server indicated a failure

pi@raspberrypi:~ $ sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 0xe1cf20ddffe4b89e802658f1e0b11894f66aec98 0x80d15823b7fd1561f9f7bcdddc30d7c23cbbabee
Executing: /tmp/apt-key-gpghome.ACQW8lXXax/gpg.1.sh --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 0xe1cf20ddffe4b89e802658f1e0b11894f66aec98 0x80d15823b7fd1561f9f7bcdddc30d7c23cbbabee
gpg: key DC30D7C23CBBABEE: public key "Debian Archive Automatic Signing Key (10/buster) <ftpmaster@debian.org>" imported
gpg: key E0B11894F66AEC98: public key "Debian Archive Automatic Signing Key (9/stretch) <ftpmaster@debian.org>" imported
gpg: Total number processed: 2
gpg:               imported: 2
pi@raspberrypi:~ $ dig +short keyserver.ubuntu.com
162.213.33.9
162.213.33.8

pi@raspberrypi:~ $ nc -z -v keyserver.ubuntu.com 11371
Connection to keyserver.ubuntu.com 11371 port [tcp/hkp] succeeded!

pi@raspberrypi:~ $ nc -z -v keyserver.ubuntu.com 80
Connection to keyserver.ubuntu.com 80 port [tcp/http] succeeded!
`

**Comment by kygarys** [comment]
Hi @orazioedoardo, thank you for your reply!  The test branch does work.   Thanks!

**Comment by scorpionx1** [comment]
confirmed, testing branch works!  thanks!
