### ISSUE TITLE
[Support] <Your Issue here>ls-crypt unwrap error: packet too short

### ISSUE THREAD

**Issue by billsteiner** [pivpn/pivpn#976]
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*.
- [] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

### Have you searched for similar issues and solutions?
    (yes/no / which issues?)

### Console output of      `curl -L install.pivpn.dev | bash`
```
  Output Here
```

### Console output of      `pivpn add` or `pivpn add nopass`
```
  Output Here
```

### Console output of      `pivpn debug`
```
  Output Here
```
### Have you taken any steps towards solving your issue?
```
  which?
```

**Comment by billsteiner** [comment]
I had to reinstall PiVPN on my Pi 4 and now I keep getting the following error: ls-crypt unwrap error: packet too short. Can anyone tell me how I can correct this?

**Comment by orazioedoardo** [comment]
Closing as not following the issue template you are presented with when opening a new issue, reopen when you have filled the relevant parts.
