### ISSUE TITLE
[FR] bytes sent/recvd with "human readable" numfmt is not optimal in every situation

### ISSUE THREAD

**Issue by devZer0** [pivpn/pivpn#977]
with a larger list of logged in users, i found that it's hard to see on a quick view

- which user is transferring big amounts of data
- which user's session stalls becaus of no data flows

compare yourself - make a copy of clientStat.sh and change the printf line this way:

`                    printf "%s  \t  %s  \t  %s  \t  %'d  \t  %'d \t  %s %s %s - %s\n" ${array[1]} ${array[2]} ${array[3]} ${array[4]} ${array[5]} ${array[7]} ${array[8]} ${array[10]} ${array[9]}`

then run:
watch -c --interval=21 -d ./clientStat.sh

i would suggest adding a second output option for that, i.e. "-c" (leave as is) and "-cb" (show bytes in dotted notation)

**Comment by orazioedoardo** [comment]
So basically you want 2000000 B instead of 2.0 MiB?

**Comment by devZer0** [comment]
yes, but in dotted decimal notation it's easier to read:

2.000.000

**Comment by orazioedoardo** [comment]
Does `numfmt --grouping --suffix=B 2000000` work for you?

**Comment by devZer0** [comment]
yes, but suffix looks a little bit ugly this way, do we need suffix "B"  at all when the colum ins named "recv/sent bytes" ?

**Comment by orazioedoardo** [comment]
> yes, but suffix looks a little bit ugly this way, do we need suffix "B" at all when the colum ins named "recv/sent bytes" ?

Agree

> mind that numfmt isn't even needed, as you can printf "%'d" ....

Oh ok thank you, I couldn't test the line in the first comment as I had no installation.

**Comment by orazioedoardo** [comment]
I’ve implemented your feature request into the test branch: `pivpn -c -b`

**Comment by devZer0** [comment]
fantastic, thanks!

will test and report
