### ISSUE TITLE
Transfer Key

### ISSUE THREAD

**Issue by electrodog10** [pivpn/pivpn#98]
How do I transfer the client key to my computer once I have one generated? Thanks!

**Comment by brookshank** [comment]
There will be a folder in the home directory of whichever user you selected during your install (probably pi). Inside it will be a file ending in .ovpn, this is your client key. If your client is a unix system (mac or linux), you can grab the file off of your pi with scp: 

`scp user@raspberrypi:location_of_file .`

This will copy the file at "location_of_file" to whichever directory you are currently in.

**Comment by electrodog10** [comment]
What would be the default location for storage?

**Comment by redfast00** [comment]
See #67
