### ISSUE TITLE
[BUG] .ovpn files stored in /ovpns after creating 

### ISSUE THREAD

**Issue by pheiduck** [pivpn/pivpn#980]
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *pivpn add example*.
- [] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

**Describe the bug**
When You create a VPN Client (OpenVPN)
`pivpn add example`
It will be stored under /ovpns not /home/pi/ovpns 
**To Reproduce**
1. Go to 'pivpn add example'
2. Click 'Enter'
3. See error

**Comment by pheiduck** [comment]
Current workaround `mv /ovpns/example.ovpn /home/pi/ovpns`

**Comment by orazioedoardo** [comment]
Never seen this. Output of `pivpn -d`?

**Comment by pheiduck** [comment]
::: Generating Debug Output
::::		PiVPN debug		 ::::
=============================================
::::		Latest commit		 ::::
commit e73f274fca692f40f7aa83d3931dc43257da5a54
Author: Orazio <orazioedoardo@users.noreply.github.com>
Date:   Mon Feb 17 16:34:07 2020 +0100

    Update LatestUpdate.md
=============================================
::::	    Installation settings    	 ::::
sed: -e Ausdruck #1, Zeichen 0: Kein vorheriger regulärer Ausdruck
=============================================
::::  Server configuration shown below   ::::
dev tun
proto udp
port 1194
ca /etc/openvpn/easy-rsa/pki/ca.crt
cert /etc/openvpn/easy-rsa/pki/issued/raspberrypi_7ad3891e-4370-458d-9361-de021acd8cbc.crt
key /etc/openvpn/easy-rsa/pki/private/raspberrypi_7ad3891e-4370-458d-9361-de021acd8cbc.key
dh none
topology subnet
server 10.8.0.0 255.255.255.0
# Set your primary domain name server address for clients
push "route 192.168.178.0 255.255.255.0"
push "dhcp-option DNS 192.168.178.2"
push "block-outside-dns"
# Override the Client default gateway by using 0.0.0.0/1 and
# 128.0.0.0/1 rather than 0.0.0.0/0. This has the benefit of
# overriding but not wiping out the original default gateway.
push "redirect-gateway def1"
client-to-client
keepalive 1800 3600
remote-cert-tls client
tls-version-min 1.2
tls-crypt /etc/openvpn/easy-rsa/pki/ta.key
cipher AES-256-CBC
auth SHA256
user nobody
group nogroup
persist-key
persist-tun
crl-verify /etc/openvpn/crl.pem
status /var/log/openvpn-status.log 20
status-version 3
syslog
verb 3
#DuplicateCNs allow access control on a less-granular, per user basis.
#Remove # if you will manage access by user instead of device. 
#duplicate-cn
# Generated for use by PiVPN.io
=============================================
::::  Client template file shown below   ::::
sed: -e Ausdruck #1, Zeichen 0: Kein vorheriger regulärer Ausdruck
=============================================
:::: 	Recursive list of files in	 ::::
::: /etc/openvpn/easy-rsa/pki shows below :::
/etc/openvpn/easy-rsa/pki/:
ca.crt
crl.pem
Default.txt
ecparams
extensions.temp
index.txt
index.txt.attr
index.txt.attr.old
index.txt.old
iPhone.ovpn
issued
Macbook.ovpn
openssl-easyrsa.cnf
private
renewed
revoked
safessl-easyrsa.cnf
serial
serial.old
ta.key

/etc/openvpn/easy-rsa/pki/ecparams:
prime256v1.pem

/etc/openvpn/easy-rsa/pki/issued:
iPhone.crt
Macbook.crt
raspberrypi_7ad3891e-4370-458d-9361-de021acd8cbc.crt

/etc/openvpn/easy-rsa/pki/private:
ca.key
iPhone.key
Macbook.key
raspberrypi_7ad3891e-4370-458d-9361-de021acd8cbc.key

/etc/openvpn/easy-rsa/pki/renewed:
private_by_serial
reqs_by_serial

/etc/openvpn/easy-rsa/pki/renewed/private_by_serial:

/etc/openvpn/easy-rsa/pki/renewed/reqs_by_serial:

/etc/openvpn/easy-rsa/pki/revoked:
private_by_serial
reqs_by_serial

/etc/openvpn/easy-rsa/pki/revoked/private_by_serial:
1A8CC1E651CC006827D6DA0CFA7E0555.key
4CEBD286B05F49C820AD830933CFA706.key
4D07B880669D06A91710062698858A3F.key
86915C66675DEB4760DC4F555C82FD6A.key
91E3B2717CABB506E3DD16CD61B2442D.key

/etc/openvpn/easy-rsa/pki/revoked/reqs_by_serial:
1A8CC1E651CC006827D6DA0CFA7E0555.req
4CEBD286B05F49C820AD830933CFA706.req
4D07B880669D06A91710062698858A3F.req
86915C66675DEB4760DC4F555C82FD6A.req
91E3B2717CABB506E3DD16CD61B2442D.req
=============================================
::::		Self check		 ::::
:: [OK] IP forwarding is enabled
/opt/pivpn/self_check.sh: Zeile 33: [: : Ganzzahliger Ausdruck erwartet.
/opt/pivpn/self_check.sh: Zeile 80: ufw: Kommando nicht gefunden.
:: [ERR] Ufw is not enabled, try to enable now? [Y/n]

**Comment by pheiduck** [comment]
there noting about this :(

**Comment by orazioedoardo** [comment]
If you are still in this situazion, probably you are missing some essential variables the script uses: https://github.com/pivpn/pivpn/issues/916

`sudo bash -c "echo 'install_user=pi' >>> /etc/pivpn/setupVars.conf"` could fix. A reinstall is suggested.

**Comment by pheiduck** [comment]
`sudo bash -c "echo 'install_user=pi' >> /etc/pivpn/setupVars.conf" `
dosent fix this

**Comment by pheiduck** [comment]
reinstall pending otherwise is ufw required?

**Comment by pheiduck** [comment]
Reinstall fixed it
`Done! iPhone.ovpn successfully created! 
iPhone.ovpn was copied to:
  /home/pi/ovpns
for easy transfer. Please use this profile only on one
device and create additional profiles for other devices.`

**Comment by orazioedoardo** [comment]
Closed, reopen if you still have the issue
