### ISSUE TITLE
[INSTALL FAIL] (WireGuard) Your kernel headers cannot be found

### ISSUE THREAD

**Issue by adrian0007** [pivpn/pivpn#981]
## In raising this issue, I confirm the following: 

- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

**Describe the issue**
Installation fails:
```
Your kernel headers for kernel 4.19.49v6v7-aufs cannot be found at
/lib/modules/4.19.49v6v7-aufs/build or /lib/modules/4.19.49v6v7-aufs/source.
```
**To Reproduce**
Device: Raspberry Pi Model B Rev 2
OS: Raspbian buster lite
Using a wired Ethernet connection
Already reserved the IP address in the router homepage before starting the install

1. Copy [berryboot](https://www.berryterminal.com/doku.php/berryboot) to a 1GB microSD Card
2. Insert microSD Card, and a 16GB USB Flash drive
3. Select OS (Raspbian Buster lite) and flash it to USB
4. Wait for OS installer to complete
5. Log in as pi
6. Run `sudo raspi-config` and `Change Default Password`,  `Enable SSH` and then `Update` the tool
7. Run `sudo apt-get update` and `sudo apt-get upgrade`
8. Run `curl -L https://install.pivpn.io | bash`
9. Press `Enter` at every dialog (the settings are correct as far as my setup is concerned)
10. The installer will prompt to select `WireGuard` or `OpenVPN`. `Wireguard` is recommended by default, so press `Enter`
11. Minutes later, the terminal outputs the following:
```
::: Compiling WireGuard modules via DKMS...
Error! echo
Your kernel headers for kernel 4.19.49v6v7-aufs cannot be found at
/lib/modules/4.19.49v6v7-aufs/build or /lib/modules/4.19.49v6v7-aufs/source.
failed!

------------------------------
Deleting module version: 0.0.20200215
completely from the DKMS tree.
------------------------------
Done.
```

**Expected behavior**
Installer should complete successfully

**Full Log**
```
pi@raspberrypi:~ $ curl -L https://install.pivpn.io | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   162  100   162    0     0    325      0 --:--:-- --:--:-- --:--:--   325
100 81925  100 81925    0     0  73212      0  0:00:01  0:00:01 --:--:--     0
:::
::: sudo will be used for the install.
::: Hostname length OK
::: Verifying free disk space...
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: Your system is up to date! Continuing with PiVPN installation...
update-alternatives: using /usr/sbin/iptables-legacy to provide /usr/sbin/iptables (iptables) in manual mode
update-alternatives: using /usr/sbin/ip6tables-legacy to provide /usr/sbin/ip6tables (ip6tables) in manual mode
:::    Checking for git... not installed!
:::    Checking for tar... already installed!
:::    Checking for wget... already installed!
:::    Checking for curl... already installed!
:::    Checking for grep... already installed!
:::    Checking for dnsutils... not installed!
:::    Checking for whiptail... already installed!
:::    Checking for net-tools... already installed!
:::    Checking for bsdmainutils... already installed!
:::    Checking for dhcpcd5... already installed!
:::    Checking for iptables-persistent... not installed!
:::    Package git successfully installed!
:::    Package dnsutils successfully installed!
:::    Package iptables-persistent successfully installed!
:::
::: Setting IP to 192.168.0.31/24.  You may need to restart after the install is complete.
:::
::: Using User: pi
:::
::: Checking for existing base files...
:::    Checking /etc/.pivpn is a repo...:::    Cloning https://github.com/pivpn/pivpn.git into /etc/.pivpn... done!
::: Using VPN: WireGuard
dpkg: warning: version '(none)' has bad syntax: version number does not start with digit
::: Installing WireGuard from source...
:::    Checking for checkinstall... not installed!
:::    Checking for dkms... not installed!
:::    Checking for libelf-dev... not installed!
:::    Checking for raspberrypi-kernel-headers... not installed!
:::    Checking for build-essential... already installed!
:::    Checking for pkg-config... already installed!
:::    Checking for qrencode... not installed!
:::    Checking for jq... not installed!
:::    Package checkinstall successfully installed!
:::    Package dkms successfully installed!
:::    Package libelf-dev successfully installed!
:::    Package raspberrypi-kernel-headers successfully installed!
:::    Package qrencode successfully installed!
:::    Package jq successfully installed!
::: Downloading wireguard-tools source code...
done!
::: Compiling WireGuard tools...
  CC      wg.o
  CC      config.o
  CC      curve25519.o
  CC      encoding.o
  CC      genkey.o
  CC      ipc.o
  CC      pubkey.o
  CC      set.o
  CC      setconf.o
  CC      show.o
  CC      showconf.o
  CC      terminal.o
  LD      wg
done!
::: Installing WireGuard tools...

checkinstall 1.6.2, Copyright 2009 Felipe Eduardo Sanchez Diaz Duran
           This software is released under the GNU GPL.


The package documentation directory ./doc-pak does not exist.
Should I create a default set of package docs?  [y]: y

Preparing package documentation...OK

*** No known documentation files were found. The new package
*** won't include a documentation directory.

*****************************************
**** Debian package creation selected ***
*****************************************

This package will be built according to these values:

0 -  Maintainer: [ root@raspberrypi ]
1 -  Summary: [ Package created with checkinstall 1.6.2 ]
2 -  Name:    [ wireguard-tools ]
3 -  Version: [ 1.0.20200206 ]
4 -  Release: [ 1 ]
5 -  License: [ GPL ]
6 -  Group:   [ checkinstall ]
7 -  Architecture: [ armhf ]
8 -  Source location: [ src ]
9 -  Alternate source location: [  ]
10 - Requires: [  ]
11 - Provides: [ wireguard-tools ]
12 - Conflicts: [  ]
13 - Replaces: [  ]

Enter a number to change any of them or press ENTER to continue:

Installing with make install...

========================= Installation results ===========================
'wg' -> '/usr/bin/wg'
'man/wg.8' -> '/usr/share/man/man8/wg.8'
'completion/wg.bash-completion' -> '/usr/share/bash-completion/completions/wg'
'wg-quick/linux.bash' -> '/usr/bin/wg-quick'
install: creating directory '/etc/wireguard'
'man/wg-quick.8' -> '/usr/share/man/man8/wg-quick.8'
'completion/wg-quick.bash-completion' -> '/usr/share/bash-completion/completions/wg-quick'
'systemd/wg-quick@.service' -> '/lib/systemd/system/wg-quick@.service'

======================== Installation successful ==========================

Copying files to the temporary directory...OK

Stripping ELF binaries and libraries...OK

Compressing man pages...OK

Building file list...OK

Building Debian package...OK

Installing Debian package...OK

Erasing temporary files...OK

Deleting temp dir...OK


**********************************************************************

 Done. The new package has been installed and saved to

 /usr/src/wireguard-tools-1.0.20200206/src/wireguard-tools_1.0.20200206-1_armhf.deb

 You can remove it from your system anytime using:

      dpkg -r wireguard-tools

**********************************************************************

done!
::: Downloading wireguard-linux-compat source code...
done!
::: Adding WireGuard modules via DKMS...

Creating symlink /var/lib/dkms/wireguard/0.0.20200215/source ->
                 /usr/src/wireguard-0.0.20200215

DKMS: add completed.
done!
::: Compiling WireGuard modules via DKMS...
Error! echo
Your kernel headers for kernel 4.19.49v6v7-aufs cannot be found at
/lib/modules/4.19.49v6v7-aufs/build or /lib/modules/4.19.49v6v7-aufs/source.
failed!

------------------------------
Deleting module version: 0.0.20200215
completely from the DKMS tree.
------------------------------
Done.
```

**Steps taken to try and resolve this issue**
* Reinstalled OS (Raspbian Buster + desktop)
* Reinstalled OS (Raspbian Buster lite)

* Followed the steps suggested in a post by [orazioedoardo](https://github.com/pivpn/pivpn/issues/673#issuecomment-457809053) and the installer failed at the same stage
* Ran `apt-get install --reinstall raspberrypi-bootloader raspberrypi-kernel`
* Followed [adrianmihalko's  WireGuard manual installation steps](https://github.com/adrianmihalko/raspberrypiwireguard/wiki/Install-WireGuard-on-Raspberry-Pi-1,-2-(not-v1.2),-Zero,-Zero-W)
* Also tried `sudo rpi-update` on a previous install of the OS. (note that all logs provided in this post are from a completely fresh install, exactly as described step-by-step at the beginning of the post)

**Note**
I never get to see the `Installation Complete` screen where it tells you about `pivpn add`, the installer fails before that.

Any command I try to run with `pivpn` is not recognised:
```
pi@raspberrypi:~ $ pivpn add
-bash: pivpn: command not found
pi@raspberrypi:~ $ sudo pivpn add
sudo: pivpn: command not found
```

**Comment by orazioedoardo** [comment]
What kernel is this? `4.19.49v6v7-aufs`

**Comment by adrian0007** [comment]
Not sure how to answer that.
I haven't made any system modifications whatsoever, the steps I outlined in the main post are exactly what I did to get here.
I believe it's the default kernel that comes with the OS?

**Comment by orazioedoardo** [comment]
I think berryboot uses a custom kernel, the default kernel for Raspbian Lite doesn’t have the `aufs` suffix. Either find an headers pacakge for that kernel version or just us the default Raspbian.

**Comment by adrian0007** [comment]
Thanks for the tip, I eventually found some headers which got me through the installer, but then it would fail to start the wireguard service, and again it had something to do with the kernel.

I tried not to use berryboot and manually configure the OS to run from the USB (OS keeps getting corrupted on 3 SDs that I have). I spent days following every tutorial I could find on how to run the OS from USB for my Raspberry Pi Model B Rev 2, and magically the only thing which worked without a hiccup was berryboot. But it's a bitter victory...

**Comment by orazioedoardo** [comment]
> Thanks for the tip, I eventually found some headers which got me through the installer, but then it would fail to start the wireguard service, and again it had something to do with the kernel.

The install output would be useful in such case.

> I spent days following every tutorial I could find on how to run the OS from USB for my Raspberry Pi Model B Rev 2, and magically the only thing which worked without a hiccup was berryboot. But it's a bitter victory...

If you need help for that, you should ask on the raspberry pi forum.

**Comment by adrian0007** [comment]
Thanks Orazio.

I suppose the takeaway here is that berryboot is fine to use with node-red and/or pihole, but not pivpn/wireguard.
