### ISSUE TITLE
[Support] pivpn add command creates .conf file - not .ovpn

### ISSUE THREAD

**Issue by Lanko2019** [pivpn/pivpn#984]
Hello all,
I've installed PiVPN on my RPi and after complete all the steps, I create a user with **sudo pivpn add** and giving the name. It doesn't ask me for a password, as both tutorials in pivpn website show. After create the client, the output is:

```
pi@servur:~ $ pivpn add
Enter a Name for the Client: XXX
::: Client Keys generated
::: Client config generated
::: Updated server config
::: Updated hosts file for Pi-hole
::: WireGuard restarted
::: Done! xxx.conf successfully created!
::: xxx.conf was copied to /home/pi/configs for easy transfer.
::: Please use this profile only on one device and create additional
::: profiles for other devices. You can also use pivpn -qr
::: to generate a QR Code you can scan with the mobile app.
```

So as it says, the file is xxx.conf. I try to connect via Android app but it expects a .ovpn file.
If I scan the QR it just shows me the content of the .conf file, which is:

```
[Interface]
PrivateKey = XXX
Address = 10.6.0.2/24
DNS = 10.6.0.1

[Peer]
PublicKey = XXX
PresharedKey = XXX
Endpoint = mydomain.dyndns.com:51820
AllowedIPs = 0.0.0.0/0
```

How can I get the .ovpn?

Thank you

**Comment by orazioedoardo** [comment]
You chose WireGuard during the installation, thus you need to use the WireGuard app. Instead if you wanted OpenVPN, uninstall with `pivpn -u` and reinstall choosing OpenVPN.

**Comment by Lanko2019** [comment]
Totally true, now I can connect using WireGuard app.
Thank you so much!!

**Comment by Lanko2019** [comment]
Totally true, now I can connect using WireGuard app.
Thank you so much!!
