### ISSUE TITLE
[BUG] <Installation autoselects ovpn>

### ISSUE THREAD

**Issue by KassabNova** [pivpn/pivpn#985]
## In raising this issue, I confirm the following: 

- [x] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

**Describe the bug**
The installer just autoselects ovpn when I want to choose wireguard

**To Reproduce**

On a raspberry 4 with a clean ubuntu install.
After updating and upgrading.
Run the pivpn script `curl -L https://install.pivpn.io | bash`
Follow screen instructions
It will ask for ovpn port instead of allowing to choose wireguard

**Expected behavior**
The installer should ask if wireguard or ovpn should be installed. 

**Desktop (please complete the following information):**
 - VPN Protocol: NA
 - OS: Ubuntu  
 - Version 18.04 ARM64

**Comment by orazioedoardo** [comment]
Ubuntu on the Raspberry Pi is not supported: https://github.com/pivpn/pivpn/wiki#what-boardsoses-does-pivpn-support

I think the installer selected OpenVPN beacuse WireGuard is only available on Raspbian and x86 Ubuntu/Debian.

**Comment by KassabNova** [comment]
Weird. A couple of weeks ago it did install under Ubuntu 18.04, the same OS I'm using now.  I'll try again with Raspbian Lite, and comeback
