### ISSUE TITLE
[Support] WireGuard update fails

### ISSUE THREAD

**Issue by jacklul** [pivpn/pivpn#988]
```
$ pivpn -wg
::: You are running the lastest version of wireguard-tools (1.0.20200319)
A new wireguard-dkms update is available (0.0.20200318), install? [Y/n]: y
::: Upgrading wireguard-dkms from 0.0.20200205 to 0.0.20200318...
::: Downloading wireguard-linux-compat source code...
done!
::: Adding WireGuard module via DKMS...

Creating symlink /var/lib/dkms/wireguard/0.0.20200318/source ->
                 /usr/src/wireguard-0.0.20200318

DKMS: add completed.
done!
::: Compiling WireGuard module via DKMS...

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area.....
make -j1 KERNELRELEASE=4.19.97+ -C /lib/modules/4.19.97+/build M=/var/lib/dkms/wireguard/0.0.20200318/build..........................................................................................................
cleaning build area.....

DKMS: build completed.
done!
::: Installing WireGuard module via DKMS...

wireguard.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.19.97+/kernel/net/

depmod....

DKMS: install completed.
done!
::: Removing old kernel module and source code...
Error! There are no instances of module: wireguard
0.0.20200205 located in the DKMS tree.
failed!
```

This basically doesn't mark the version as installed, rerunning the command attempts to install same version again throwing new errors 'cannot enter src/*' (mostly because the source directory already exists?).
The only workaround is to manually change module version in setupVars.conf.

This is Pi Zero W with Pi-hole, previous updates installed without any issues, since then PiVPN scripts were updated few times via `pivpn -up` so it makes me think something in scripts got messed up.

**Comment by orazioedoardo** [comment]
I’ve seen this error but have not fixed this since we switched to the bullseye repo, which doesn’t need manual compilation. I suggest you remove the current WireGuard installation and reinstall.

```
sudo dkms remove wireguard/0.0.20200318 --all
```

Confirm that `sudo dkms status` is empty, then remove userspace tools:

```
sudo apt remove wireguard-tools
```

Now remove the code: `sudo rm -rf /usr/src/wireguard-*`

I’m writing from the phone however If you want i can tell you just how to switch to the bullseye repo.

**Comment by jacklul** [comment]
I don't think I want to mess with that

**Comment by orazioedoardo** [comment]
Output of `sudo dkms status` and `ls -l /usr/src`?

**Comment by jacklul** [comment]
Actually I'm in a process of reinstalling PiVPN, I don't like that this new approach builds the module 3 times. 
It compiles for 4.19.97+, 4.19.97-v7+, 4.19.97-v7l+ while previously it did only 4.19.97+, any way to skip the compilation for the other ones?

**Comment by orazioedoardo** [comment]
> It compiles for 4.19.97+, 4.19.97-v7+, 4.19.97-v7l+ while previously it did only 4.19.97+, any way to skip the compilation for the other ones?

I know, it’s really annoying. I think that’s build into the wireguard-dkms package configuration.
