### ISSUE TITLE
PersistentKeepalive Client

### ISSUE THREAD

**Issue by 5J2J** [pivpn/pivpn#990]
**Is your feature request related to a problem? Please describe.**
A PersistentKeepalive should be added automatically when creating a client, I use PersistentKeepalive 1

**Describe the solution you'd like**
Add PersistentKeepalive to the script

**Comment by orazioedoardo** [comment]
What would be the benefit?

**Comment by orazioedoardo** [comment]
No comments in a while, closing...

**Comment by franklouwers** [comment]
Would suggest to reopen this: I have the same issue.

As to your question: adding this keeps the connection alive through most NAT setups. WG will only use the tunnel when a packet needs to be sent. Most (all) NAT gateways / firewalls / routers, will see that no traffic happens for a while, and will wipe the NAT entry. If the client (behind NAT) needs to connect to the server, that's fine: the client initiates a new connection, this is picked up by the NAT gw, etc. But if the connection has expired and the server needs to connect to the client, it can't.

Adding "PersistentKeepalive = 25" will send a keep-alive packet from the client to the server every 25 seconds, thus forcing the NAT gateway to keep everything in place, allowing the server to connect to the client if needed.

More info: https://www.wireguard.com/quickstart/#nat-and-firewall-traversal-persistence

Patch: https://github.com/pivpn/pivpn/pull/1174

**Comment by DerDanilo** [comment]
FYI: Added to wireguard profiles
https://github.com/pivpn/pivpn/pull/1321/commits/88a701c16a62b002daf291fb0822c5e5f720c58a
