### ISSUE TITLE
[BUG] Correct headers are not installed when using Debian Buster backports kernel such as 5.4

### ISSUE THREAD

**Issue by GvY85** [pivpn/pivpn#992]
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

**Describe the bug**
Wireguard service does not start because correct headers are not installed when using an other kernel than DEbian Buster 4.19 (in my case 5.4 via Backports)

**To Reproduce**
Log:
_sudo apt -t buster-backports install wireguard
(some stuff)
Setting up wireguard-dkms (0.0.20200215-2~bpo10+1) ...
Loading new wireguard-0.0.20200215 DKMS files...
Building for 5.4.0-0.bpo.4-amd64
**Module build for kernel 5.4.0-0.bpo.4-amd64 was skipped since the
kernel headers for this kernel does not seem to be installed.**
Setting up wireguard (1.0.20200206-2~bpo10+1) ...
Processing triggers for libc-bin (2.28-10) ...

Scanning processes...

Scanning processor microcode...

Scanning linux images...

Running kernel seems to be up-to-date.

The processor microcode seems to be up-to-date.

No services need to be restarted.

No containers need to be restarted.

No user sessions are running outdated binaries._

Solved by:
_apt install linux-headers-5.4.0-0.bpo.4-amd64_
in seems only headers-4.19 are installed by the script, even when kernel 5.4 is running.

**Comment by orazioedoardo** [comment]
Looks like that installing `linux-headers-amd64` (what the script does) indeed installs `linux-headers-5.4.0-0.bpo.4-amd64` on Buster backports: https://packages.debian.org/buster-backports/linux-headers-amd64

**Comment by Ghostbird** [comment]
I'm on ARM Debian buster-backports (for wireguard) too. I opted to manually install the header dependency and remove the dependency from the script. Otherwise I'd try to install AMD64 headers.

**Comment by 4s3ti** [comment]
Is this still happening now that Wireguard ships by default on linux kernel?

**Comment by Ghostbird** [comment]
I haven't retried. I set-up an OpenVPN instead. If this has been fixed, I may replace it with WireGuard after all.

**Comment by 4s3ti** [comment]
@Ghostbird ITs ARM64 right?

**Comment by Ghostbird** [comment]
It was `armv7l`

**Comment by 4s3ti** [comment]
might need testing then .. not sure if its gone or not.

**Comment by Ghostbird** [comment]
If I try to install `wireguard` from buster-backports, it wants to install a realtime kernel. I don't think that would be a good idea in my case. However, it's probably unrelated to this repository. At least it doesn't seem to try to install `amd64` packages.

**Comment by 4s3ti** [comment]
Wonder if this is still a thing and needs real investigation .. been quite dead and not many comments or issues related to this ... 🤔🤔🤔

**Comment by Ghostbird** [comment]
I'll close this, I have no way to test this, since I upgraded that system to a Raspberry Pi 4, which is ARM64, so it will resolve different packages.

**Comment by 4s3ti** [comment]
will close if needed can be reopened.
