### ISSUE TITLE
Easy-TLS a companion script to Easy-RSA

### ISSUE THREAD

**Issue by TinCanTech** [pivpn/pivpn#993]
Please see this repo:
https://github.com/TinCanTech/easy-tls

OpenVPN 2.5 release (scheduled sometime this year) will have support for TLS-Crypt-V2 and the script above is intended to help manage those keys and .inline files for OpenVPN nodes.

Sorry to _spam_ your github issues. Please close if you are not interested.

Kind Regards

**Comment by TinCanTech** [comment]
Because this issue is still open I would like to believe there is a _little_ interest.  With that in mind I have prepared some preliminary work for PiVPN in advance.  I am prepared to provide ongoing support if my PRs are accepted.

**Comment by orazioedoardo** [comment]
Personally I left the issue open because I haven't had time to see the repo. Is it supposedly a replacement for EasyRSA for a specific OpenVPN use case?

**Comment by TinCanTech** [comment]
NO, it is not a replacement for EasyRSA.

EasyRSA manages x509 PKI cert/keys.

EasyTLS manages OpenVPN specific TLS keys. `--tls-auth/--tls-crypt/--tls-crypt-v2`.  It also generates and manages `.inline` node package files.  On top of that, it keeps a basic database of EasyRSA revoked certs in order to warn when cert has been revoked but an `.inline` file still has the old cert.
It can also renew an `.inline` file when a certificate is renewed in EasyRSA.
Finally, when OpenVPN ships with `--tls-crypt-v2`, EasyTLS generates `--tls-crypt-v2` keys and metadata with the OpenVPN recommended metadata (Client cert serial number & CA fingerprint) with a little extra customisation on top.

**Comment by TinCanTech** [comment]
There is one other point to the application.  It comes with a `--tls-cryp-v2-verify.sh` script which is compatible with the `--tls-crypt-v2` keys generated with the preferred metadata fields.

**Comment by orazioedoardo** [comment]
> Note-1: EasyRSA maintainer decided that he does not want OpenVPN specific TLS keys managed by EasyRSA.
> Note-2: I am hoping to have this script folded into OpenVPN in the future, as per their requirement here: https://github.com/OpenVPN/openvpn/blob/75aa88af774abaa168bf72e43e1dbb57be14c044/doc/tls-crypt-v2.txt#L187

I guess that EasyRSA is for generic PKI while your script is geared specifically towards OpenVPN keys, right?

>  With that in mind I have prepared some preliminary work for PiVPN in advance. I am prepared to provide ongoing support should my PRs be accepted.

Sure, we'll see.

**Comment by TinCanTech** [comment]
> I guess that EasyRSA is for generic PKI while your script is geared specifically towards OpenVPN keys, right?

Exactly.  But also, providing a verified mechanism to manage `.inline` VPN node packages.

So for example, you have your standard `server.conf` or `client.conf` with general OpenVPN directives and then use `--config /path/to/server.inline` (or `client.inline`) or simply append the `.inline` file to the general config file.

Also, once TLS-crypt-v2 is released it will be necessary to tie specific TLS-crypt-v2 keys to both server and client in almost the same way that standard x509 does now.

**Comment by TinCanTech** [comment]
EasyTLS will plug directly in to your EasyRSA installation and runs along side EasyRSA. EasyTLS command structure is intended to also follow the EasyRSA style.

**Comment by TinCanTech** [comment]
Also, EasyTLS script is more or less complete, barring any unforeseen bugs, so it is ready to go (once OpenVPN release TLS crypt v2).  The only thing that may be subject to change is the metadata field in TLS crypt v2 client keys but that is unlikely to change again because it has been thoroughly reviewed.

`tls-crypt-v2-verify.sh` is still a work-in-progress but it is almost complete, again, barring any unforeseen bugs. However, I have been very thorough in it's construction because it needs to be very robust due to the security implications.

EasyTLS also works in Windows but that is not of value to PiVPN.

Initially I wanted to have `tls-crypt-v2-verify.sh` script support Windows but I have decided to make OpenVPN scripts for Windows a separate project.

**Comment by TinCanTech** [comment]
Is PiVPN not interested in this ?

**Comment by orazioedoardo** [comment]
Yes, however I don't know if 2.5 features that your script uses are available on all platforms.

**Comment by TinCanTech** [comment]
In fact, Easy-TLS is specifically designed to work everywhere that OpenVPN and Easy-RSA3 work.  I would be very interested in any failure because that would be indicative of something much more serious.

The only thing that Easy-TLS does which PiVPN does not _currently_ do is to create TLS-Crypt-V2 keys and a little extra inlining.  There are the extra server side scripts to take full advantage on the V2-Key-metadata field but the scripts are not necessary to use the keys for a VPN.

I'll draft something for you to consider. And for the record, I understand that you may not want to use EasyTLS at all.
