### ISSUE TITLE
 Could not find any active network interface, exiting

### ISSUE THREAD

**Issue by alfonzodi** [pivpn/pivpn#994]
Hi,

I'm using Raspberry withg lte modem with static ip , when i install pivpn, i have this error : 
 
![q](https://user-images.githubusercontent.com/57092573/77419803-47e0f280-6dc9-11ea-9656-07040ec4d533.png)

Can you help me to resolve this ?

**Comment by orazioedoardo** [comment]
What's the output of `ip -o link`? By the way, even if we manage to make it work, usually cellular connections don't give you IP addresses you can directly connect to.

**Comment by fana13** [comment]
Hi,
I've got same issue here.
`ip -o link` give this for me
`1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT \    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: gre0: <NOARP> mtu 1476 qdisc noop state DOWN mode DEFAULT \    link/gre 0.0.0.0 brd 0.0.0.0
3: gretap0: <BROADCAST,MULTICAST> mtu 1476 qdisc noop state DOWN mode DEFAULT qlen 1000\    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
4: venet0: <BROADCAST,POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT \    link/void
`

**Comment by orazioedoardo** [comment]
@fana13 What computer is this?

**Comment by fana13** [comment]
Sorry, it's on debian jessie

**Comment by orazioedoardo** [comment]
Debian Jessie is not supported. Besides this the script doesn't work because all your interfaces are state DOWN (PiVPN looks for UP).

**Comment by fana13** [comment]
Ok.
No I've only venet0 which provdided an IP like : 
`venet0: <BROADCAST,POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN
    link/void
    inet 127.0.0.2/32 scope host venet0
    inet 1xx.xxx.xxx.xxx/32 brd 1xx.xxx.xxx.xxx scope global venet0:0
         valid_lft forever preferred_lft forever
`

**Comment by orazioedoardo** [comment]
@fana13 Ok if you want to install, upgrade to stretch or buster, replace `state UP` with `state UNKNOWN` [here](https://github.com/pivpn/pivpn/blob/f045e3935d12e1eb714fa0f630b021209e926aef/auto_install/install.sh#L550) and manually run the script.

**Comment by fana13** [comment]
Work perfectly.
Amazing, many many thanks !!

**Comment by orazioedoardo** [comment]
@fana13 I've added the `--show-unsupported-nics` command line argument: https://github.com/pivpn/pivpn/commit/ba4c2c91db0e75dd4c2728e63fdabd532da55d99

**Comment by fabietto01** [comment]
Hello,

I tried to use the script, but it returned the following error:

`Status: inactive
::: Checking for git... already installed!
::: Checking for tar... already installed!
::: Checking for curl... already installed!
::: Checking for grep... already installed!
::: Checking for dnsutils... already installed!
::: Checking for grepcidr... already installed!
::: Checking for whiptail... already installed!
::: Checking for net-tools... already installed!
::: Checking for bsdmainutils... already installed!
::: Checking for bash-completion... already installed!
::: Checking for iptables-persistent... already installed!
Reading package lists... Done
Building dependency tree
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove, and 0 not upgraded.
::: IPv6 test connections to google.com have failed. Disabling IPv6 support. (The curl test failed with code: 7)
[2024-01-20T15:33:25+0000]: ::: Could not find any active network interface, exiting`

Below are the interfaces:

`ip -o link`
`1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000\ link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: venet0: <BROADCAST,POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT group default \ link/void`

If I'm not mistaken, I'm using the interface called venet0.

**Comment by orazioedoardo** [comment]
@fabietto01 

```
curl -O https://raw.githubusercontent.com/pivpn/pivpn/master/auto_install/install.sh
chmod +x install.sh
./install.sh --show-unsupported-nics
```
