### ISSUE TITLE
[Support] <Question: Would piVpn secure that communication between device and website>

### ISSUE THREAD

**Issue by kannieWeesNie** [pivpn/pivpn#996]
I am considering using piVpn and would appreciate some help.

I would like to connect an esp32 (microcontroller) to piVpn which would then have a two-way communication with my website on the internet. Users would open my website which would communicate with the esp32 (in both directions) via the piVpn.

Currently i am able to communicate (without the piVpn) between the esp32 and website using http so all communication is insecure.

Would the piVpn secure that communication?

thanks

**Comment by orazioedoardo** [comment]
Question is not actually PiVPN related but a general VPN problem. My idea: connect the microcontroller to a VPN capable router and then connect the router to the server hosting the website.

**Comment by 4s3ti** [comment]
why not use https instead? 

using a VPN would encrypt the traffic between the micro controller and the website would sill be unencrypted inside the VPN.

**Comment by orazioedoardo** [comment]
No comments in a while, closing...
