### ISSUE TITLE
pivpn with openvpn and ca certificate

### ISSUE THREAD

**Issue by pipi111** [pivpn/pivpn#997]
Hi All

I have setup pivpn with openvpn on my rpi3 model b
Im having difficulty to generate a  .p12file  CA  certificate authentication to be imported on my client machine
i have looked on many tutorials but no luck 
i have easy-rsa 3.0

**Comment by orazioedoardo** [comment]
> Im having difficulty to generate a .p12file CA certificate authentication to be imported on my client machine
> i have looked on many tutorials but no luck
> i have easy-rsa 3.0

You don't need to do this on the client, just generate a configuration file on the raspberry using `pivpn -a` and use that file to connect via the OpenVPN app on the client.

**Comment by orazioedoardo** [comment]
No comments in a while, closing...
