### ISSUE TITLE
[Support] Standard wireguard install, unable to connect!

### ISSUE THREAD

**Issue by tamis-laan** [pivpn/pivpn#999]
I gave my raspberry pi 4 a static IP and in my router settings I forwarded port 51820 to my raspberry. 

I installed pivpn using the easy install script using all the default settings accept for the dns entry which I changed my personal domain name.  

Next I added a user using pivpn add, and used the pivpn -qr command to generate a QR code. 

On my android phone I used the wireguard app to read the QR code and load in the config. 

Given this basic process I'm unable to connect to the vpn. I also tried using the command telnet <local_ip_address> 51820 as wel as telnet <my_domain> 51820 both of which give me:
 telnet: Unable to connect to remote host: Connection refused

I'm wondering where the problem might be and if there is some way to debug the progress so I can see where things are going wrong.

**Comment by orazioedoardo** [comment]
> I’m wondering where the problem might be and if there is some way to debug the progress so I can see where things are going wrong.

Closing as not following the issue template, reopen after providing such information, and possibly follow the FAQ too.

**Comment by tamis-laan** [comment]
Fixed the problem by following the wiki FAQ. Would like to suggest to put a clear link to the wiki and the FAQ on the front page of the website to make sure more questions like these won't pop up in the future!
